[자동차 경주-단위테스트] 2단계 - 문자열 계산기
next-step/java-racingcar pull request #1340
Opened 2020-10-30 07:17 UTC by eyabc

미션을 혼자서 진행하기에는 어려워서 미리 하신 분들의 코드를 보고 코드를 수정해 보았습니다

- @DongHwani 님
    - 코드 베이스 
    - interface, enum
    
- @junilHwang 님
    - 상수 사용
    - 생성자 실행방지
    
- @oen142 님
    - 에러 커스텀

2020-10-30 07:33 UTC, oen142 reviewed
갑자기 저한테 메일이 날라와서,
 저도 코멘트를 하나 남기겠습니다. 
많이 배워가요!

2020-10-30 07:33 UTC, oen142 commented on src/main/java/exception/ErrorMessage.java
> +    public static String DIVIDED_BY_ZERO = "피 제수를 0 으로 나눌 수 없습니다.";
이 메시지를 따로 상수화해서 하나의 클래스에 넣을까도 생각을 해봤는데,
만약 Error메시지가 무수히 많아지면 결국 보기가 힘들어질까봐 
저는 해당 Exception클래스에 문자열을 넣는걸로 결정을했는데, 어떻게 생각하시나요??

2020-10-30 07:33 UTC, oen142 commented on src/main/java/step02/Operator.java
> +    };
Interface로 추상화한후에 enum에서 상속받아서 쓸경우 이렇게 쓸수가 있구나 하면서
배워갑니다!

2020-10-30 07:33 UTC, oen142 commented on src/main/java/step02/README.md
> +    - 에러 커스텀
![image](https://user-images.githubusercontent.com/46095454/97672299-210c3c80-1acd-11eb-9aa1-a2c9b79bf542.png)

이거에 메일이 와서 깜짝놀랐어요 ㅋㅋㅋ

2020-10-30 07:33 UTC, oen142 commented on src/test/java/step02/CalculatorTest.java
> +        assertThat(Operator.DIVIDE.calculate(first, second)).isEqualTo(first / second);
한 테스트당 assertThat은 하나만 쓰는게 좋다구 하더라구요. 하나로 줄이는건 어떻게 생각하시나요?

2020-10-30 07:33 UTC, oen142 commented on src/test/java/step02/ExceptionTest.java
> +    }
0으로 나눌경우는 전 생각을 안했는데 좋은 아이디어 같아요!

2020-10-30 07:33 UTC, oen142 commented on src/main/java/step02/Calculator.java
> +    }
처음에 isBlank라는 외부 메소드를 사용했는데,
isEmpty()랑 isBlank()랑 다른 부분이 
문자열 "" 랑 " "을 해석하는 기준이 다르더라구요.
그래서 어떻게 예외를 처리할까 생각했는데, trim으로 자르고 하면 되겠네요 꿀팁 감사합니다 ㅋㅋ

2020-10-30 07:33 UTC, oen142 commented on src/main/java/step02/Calculator.java
> +            int leftOperand = calculateResult;
변수명이 눈에 확 들어오네요 👍

2020-10-30 10:51 UTC, eyabc commented on src/main/java/exception/ErrorMessage.java
> +    public static String DIVIDED_BY_ZERO = "피 제수를 0 으로 나눌 수 없습니다.";
저도 이보다 더 확장적인 프로그래밍을 해본적이 없어서 잘모르겠습니다 ㅋㅋ  리뷰어 분들의 말씀들 더 들어보고 싶군요!

2020-10-30 10:51 UTC, eyabc commented on src/main/java/step02/Operator.java
> +    };
DongHwani 님의 코드인데 너무 신기해서 따라 쳐보았어요 !

2020-10-30 10:52 UTC, eyabc commented on src/test/java/step02/CalculatorTest.java
> +        assertThat(Operator.DIVIDE.calculate(first, second)).isEqualTo(first / second);
오호 꿀팁 감사합니다!

2020-10-30 10:52 UTC, eyabc commented on src/test/java/step02/ExceptionTest.java
> +    }
넵 리뷰어 분들이 0 으로 나누는 경우도 처리해 주면 좋겠다는 코멘트들을 많이 보았어요!

2020-10-30 10:53 UTC, eyabc commented on src/main/java/step02/Calculator.java
> +    }
이부분도 DongHwani 님의 아이디어 랍니다!

2020-10-30 10:54 UTC, eyabc commented
준일님의 도움을 받아 
6c14734 을 한번 변경해 보았습니다!

2020-10-30 10:54 UTC, eyabc commented
@oen142 님이랑 블랙커피스터디 하는것 같아서 TDD 스터디에서도 이질감이 없네요 ㅋㅋ

2020-10-31 08:51 UTC, vagabond95 requested changes
다른 분들의 구현과정을 참고하고 고민하시는 모습이 너무 인상적이었습니다 👍 👍 

테스트 코드도 빈틈없이 잘 작성해주셨네요!
클래스의 역할측면에서 몇가지 코멘트를 달았습니다, 요 개념은 앞으로도 진행할 미션에서 계속 생각해볼만한 주제이므로 한번쯤 고민해보셨으면 좋겠다는 측면에서 Request changes 로 남겨둘게요. 

수정 후 다시 리뷰요청 부탁드려요!

코멘트 내용 혹은 구현과정에서 궁금하거나 논의하고 싶으신 부분 있으면 편하게 DM 주세요 :)

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/exception/DividedByZero.java
> +public class DividedByZero extends ArithmeticException {
구체적인 예외 클래스 👍 

그런데 클래스 이름에 예외를 나타내는 표현 (ex / Exception, Error) 등이 나타난다면 좀 더 역할을 명확히 파악할 수 있을 것 같습니다 :)

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/exception/ErrorMessage.java
> +    public static String DIVIDED_BY_ZERO = "피 제수를 0 으로 나눌 수 없습니다.";
에러메세지를 상수로 관리한다는 포인트는 관리 및 가독성 측면에서 좋은 시도라고 생각됩니다.

다만, @oen142 님이 얘기주신 것 처럼 에러 메세지를 하나의 클래스에서 모두 관리할 경우 프로젝트가 커질 수록 거대한 상수덩어리 클래스가 되어 파악하기 어려울 수 있으므로, 하나의 클래스에 몰아넣지않고 에러 메세지가 사용되는 클래스에 상수를 선언하고 사용하는 접근 방식도 사용될 수 있습니다!

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/step02/README.md
> +- 타입없는 자바 스크립트만 하다가 자바를 보니 깜짝 놀랬다
다른 분 코드를 보면서 세세히 분석하며 진행하시는 모습 너무 멋지십니다 💯 💯

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/step02/Operator.java
> +public enum Operator {
연산자 enum 으로 관리 👍 
Operator 가 스스로 계산식을 수행할 수 있음 👍

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/step02/Calculator.java
> +    private void validateInputHasContents(String input) {
Calculator 클래스의 역할을 어떻게 정의하고 계신지 궁금합니다!

우선 클래스이름으로 유추할 수 있는 것은 '계산 (혹은 사칙연산)'에 대한 내용을 담당한다고 떠올릴 수 있을 것 같은데요,
String 의 null 여부, empty 여부를 해당 클래스에서 체크하는 것이 '계산' 과 직접적인 연관이 있을까요~?

좀 더 풀어보면, 계산을 수행할 때 계산식이 String 으로 넘어오는지, 계산식이 null 인지 꼭 알아야할 정보일까요?

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/step02/Calculator.java
> +        String[] rowData = input.split(" ");
String 으로 된 계산식을 파싱하는 로직이 포함되어 있는데요, 
위 코멘트와 마찬가지로 Calculator 클래스에서 수행할 수 있는 적절한 역할일지 고민해보시면 좋을 것 같아요.

Calculator 라는 이름에 비해 많은 역할을 가지고 있는 것 아닐까요~? 혹은 클래스 이름에서 역할을 좀 더 잘 드러낼 수 있도록 바꿔볼 수 있지 않을까요~?

2020-10-31 08:51 UTC, vagabond95 commented on src/main/java/step02/Calculator.java
> +        String[] rowData = input.split(" ");
" " 와 같은 String 도 상수로 다루어 좀 더 의미를 명확히 할 수 있으면 좋을 것 같아요!

2020-10-31 14:36 UTC, eyabc commented on src/main/java/exception/DividedByZero.java
> +public class DividedByZero extends ArithmeticException {
오호 감사합니다! 리뷰 반영하였습니다 ! 테스트 케이스를 작성하니 리팩토링을 하고 수정을 잘하였는지 확인하는 과정이 간소화 되서 좋은것 같아요!

2020-10-31 14:39 UTC, eyabc commented on src/main/java/step02/Operator.java
> +public enum Operator {
저의 아이디어는 아니지만 ! 구현의 장점을 정리해 주셔서 감사합니다!

2020-10-31 14:45 UTC, eyabc commented on src/main/java/step02/Calculator.java
> +    private void validateInputHasContents(String input) {
- Operator 클래스의 역할은 각각의 사칙연산을 수행하는 것입니다. 
- Calculator 는 Operator 의 각각의 사칙연산을 이용해 input (식) 의 값을 도출하는 역할을 하는 것입니다. 

`String 의 null 여부, empty 여부를 해당 클래스에서 체크하는 것이 '계산' 과 직접적인 연관이 있을까요~?`
- 직접적인 연관이 없는 것 같아요 그럼 Null 과 Empty 여부를 체크하는 로직을 Calculator 의 로직과 분리하면 더 좋을 것 같습니다!

2020-10-31 15:24 UTC, eyabc commented
@vagabond95 
첫 리뷰를 받았는데 너무 많은 꿀팁을 받아가는 것 같아요! 정말 감사합니다!!

2020-11-01 06:32 UTC, vagabond95 approved these changes
코멘트 내용 잘 반영해주셨네요 👍 

이 클래스의 역할은 무엇인지, 이 클래스가 꼭 알아야할 정보인지 고민하시다보면
나머지 미션을 진행하시는데 큰 도움이 되실 것이라 생각됩니다 ㅎㅎ

2단계는 머지할게요, 3단계 진행해주세요~!

2020-11-01 06:32 UTC, vagabond95 commented on src/main/java/exception/DividedByZeroException.java
>      public DividedByZeroException() {
에러 메세지를 통합 클래스에서 분리하시는 시도 좋았습니다 👍 
다만, 하드코딩하지 않고 아래와 같이 상수로 선언 후 사용하는 것이 관리 및 가독성 측면에서 더 좋지 않을까요~?

```java
public static final String ERROR_MESSAGE = "피 제수를 0 으로 나눌 수 없습니다.";
```

2020-11-01 06:32 UTC, merged

2020-11-01 06:35 UTC, eyabc commented on src/main/java/exception/DividedByZeroException.java
>      public DividedByZeroException() {
오호 정말 감사합니다!