ghojeong(고정완) [자동차 경주 - 단위 테스트] 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #1380
Opened 2020-11-01 11:09 UTC by ghojeong

#1341  과 클래스 다이어그램은 동일하므로, 새로 이미지를 첨부하지는 않았습니다.

이번에는 구현할 기능을 README.md 에 먼저 적고,
기능을 구현할 때마다, 구현한 기능에 [0] 표시를 앞에 붙였습니다.

2020-11-01 11:13 UTC, ghojeong commented on src/test/java/racingcar/CarGroupTest.java
> +        });
carStream 과 expectedStream 을 더 효과적으로 예쁘게 비교할 수 있는 방법이 있을지 여쭈어봅니다.
Java 람다 처음부터 공부해보면서 적용하고 있는데, 현재 머리를 싸맨 시점에서는 이게 최대한 깔끔한 표현이었습니다.

현업에서 쓰이는 표준 같은게 있는지 궁금합니다.

2020-11-01 11:13 UTC, ghojeong commented on src/main/java/racingcar/RacingGame.java
>      }
우승자를 가져오기 위해, 함수 체이닝을 덕지덕지 발랐는데,
혹시 더 깔끔한 표현법이 있을 까요?
Java 8의 함수형 프로그래밍 어렵네요.

2020-11-01 11:17 UTC, neojjc2 commented
#tag @neojjc2

2020-11-01 23:27 UTC, neojjc2 commented
#tag @neojjc2

2020-11-02 05:20 UTC, neojjc2 requested changes
안녕하세요 정완님 🙇 
4단계 구현 잘 해주셨습니다 💯 

테스트 코드도 잘 작성해 주셨고, 이전 구조가 좋아서 
변경사항 반영하는데 큰 어려움은 없으셨을 거라 생각듭니다 😄 

람다식을 활용하는 부분에서 많은 고민들이 느껴졌습니다 
도움이 되실 만한 의견들을 몇 가지 드렸습니다
참고 정도만 해주시고 이번 기회에 정리 하는 시간이 되셨으면 좋겠습니다 🙇  

조금만 수정되면 더 좋은 코드가 나올 것 같아서 Request changes 요청 드렸습니다 

수정 후 다시 리뷰 요청 주시면 감사하겠습니다 🔥 
화이팅 입니다 🥇

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/Main.java
>              racingView.print();
Game과 View가 서로 의존적인 부분이 있는 것 같습니다 😅 
Game이 촤종 종료 된 후 결과만 View에 전달 해서 화면에 보여지도록 개선하면 어떨까요??
검토 부탁 드립니다 🙇

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/NumConst.java
>      private NumConst() {}
인스턴스 화 방지 👍 
용도별 클래스 분리 👍 

한 가지 의견 드리자면 형(type) 별로 구분을 하셨는데
용도별로 (혹은 도메인 별로) 구분하는 건 어떨까요?? 
이 부분도 검토 부탁 드립니다 🙇

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/README.md
> +# 구현할 기능 목록
README.md 요구사항 정리 👍

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/RacingView.java
> +            sb.append(ViewConst.PLAYER_TOKEN);
공통 변수 사용 👍

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/RacingView.java
> +        List<String> winners = winnerList
람다식 사용 👍 
우승자를 가져오는 로직과 View로직 분리 👍 

자신을 참조 하기 때문에 
`.map(car -> car.getName())` -> `.map(Car::getName)` 로 변경해 볼 수 있습니다 😄

2020-11-02 05:20 UTC, neojjc2 commented on src/test/java/racingcar/CarGroupTest.java
> +        MoveStrategy strategy = new MoveStrategy() {
`MoveStrategy strategy = () -> true;`

2020-11-02 05:20 UTC, neojjc2 commented on src/main/java/racingcar/RacingGame.java
> +    public List<Car> getWinners() {
이 부분에 대해서 질문을 주셨는데, 어떻게 우승자를 구할 것인지에 대한 방식의 차이 인 것 같습니다 
<position, car>로 group을 하고 max position을 가져오는 방식을 선택하셨고, 많은 고민을 하신거 같아서
방식의 차이라 크게 문제 되보이지는 않습니다 😅 

하지만, 좀 더 깔끔한(?) 방식이 궁금하시다 하셔서 의견 드리자면
저라면 이렇게 할 수 도 있을 것 같습니다.

1. 가장 긴 거리를 구한다 (max position)
2. 1의 max position보다 큰 car 들을 필터링한다 

이런 방법도 한번 참고 부탁 드리겠습니다 🙇

2020-11-02 05:21 UTC, neojjc2 commented on src/test/java/racingcar/CarGroupTest.java
> +        });
리뷰에도 의견 드렸지만, stream 끼리 비교하기 보다는 다른 방식으로 테스트를 고민해 보는 건 어떨까요?? 😄

2020-11-02 05:22 UTC, neojjc2 commented on src/main/java/racingcar/RacingGame.java
>      }
이 부분은 코드에 의견 드렸습니다 :-) 
확인 부탁 드립니다 😄

2020-11-02 05:31 UTC, neojjc2 commented on src/main/java/racingcar/RacingGame.java
> +    private CarGroup carGroup;
요구사항 반영 👍

2020-11-02 07:36 UTC, ghojeong commented on src/main/java/racingcar/RacingGame.java
> +    public List<Car> getWinners() {
>  크게 문제 되보이지는 않습니다

오, 넵. 람다 처음 써보는지라 자신감이 없었는데, 다행이네요.
지금과 같은 방식을 유지하고 Resolve 하겠습니다.

2020-11-02 07:44 UTC, ghojeong commented on src/main/java/racingcar/Car.java
> +        this.name = name;
```java
        if (name.length() > NumConst.MAX_NAME_LENGTH) {
            throw new IllegalArgumentException(MsgConst.MAX_NAME_LENGTH_EXCEEDED);
        }
```

바로 위의 코드에서 자동차 이름이 5자를 초과할 경우에, IllegalArgumentException 을 throw  하고 있습니다.
아무래도 tryNum 까지 입력받은 다음에야, IllegalArgumentException 이 발생해서 누락되었다고 말씀하신것 같은데,
자동차 이름을 입력하자 마자 바로 에러를 발생시킬 수 있도록 수정하겠습니다.

2020-11-02 11:22 UTC, ghojeong commented on src/main/java/racingcar/NumConst.java
>      private NumConst() {}
@neojjc2
혹시 도메인이라는게 무엇인지 설명들을 수 있을까요?
DDD(Domain Driven Development) 에서 들어보기는 했는데,
도메인이란게 정확히 무엇인지 잘 모르겠어서요.

2020-11-02 12:44 UTC, neojjc2 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
아 맞네요 😄 
로컬에서 실행하면서 코드 보다가 착각 했나 봅니다 😭 죄송합니다 🙇 
수정은 안하셔도 될 것 같습니다 

다만 null 값이 입력될 경우 NPE가 발생할 것 같습니다 🙇 
이 부분이 보완 검토 부탁 드립니다

2020-11-02 12:44 UTC, neojjc2 commented on src/main/java/racingcar/NumConst.java
>      private NumConst() {}
아, 도메인이라고 해서 어렵게 생각하실 필요 전혀 없습니다 😄 
사전적 의미를 보면 아래와 같습니다 

1. (지식·활동의) **영역**; (책임의) **범위**
2. (특히 옛날 개인·정부 등의) **소유**지
3. 도메인

말 그대로 영역, 범위 등을 나누는 논리적인 개념이라고 보시면 될 것 같습니다 
예를 들어 자동차와 관련된 일을 하는 도메인, 경주에만 관련된 일을 하는 도메인, 출력을 하는 일만 하는 도메인
이런식으로 용도별로 도메인을 분리하고 그 안에서 공통으로 쓰는 변수들을 모아놓는다면 해당 도메인과 관련된 부분을 수정할 때 공통 변수가 어떤건지 쉽게 찾을수 있기 때문에 검토 요청 드린 겁니다 😄 

도움 되실 만한 내용 공유 드립니다 
> https://joont92.github.io/ddd/%EB%8F%84%EB%A9%94%EC%9D%B8-%EB%AA%A8%EB%8D%B8/

2020-11-02 12:44 UTC, neojjc2 commented on src/main/java/racingcar/RacingGame.java
> +    public List<Car> getWinners() {
네 좋습니다 👍 
제가 리뷰 하고 계신 다른 분 중에 제가 제안드린 방법과 비슷하게 구현하신 분이 계십니다 
소스 보시고 참고 정도만 하시면 될 것 같습니다 🙇 
같은 문제를 다른 사람은 어떤 방식으로 해결하는지 관점으로 보시면 도움이 되실거라 생각합니다 😄 

> https://github.com/joswlv/java-racingcar/blob/a0cf3464681e1398a997ec449aaa9a27de6388b1/src/main/java/racinggame/model/MovingResult.java#L36-L48

2020-11-03 07:21 UTC, ghojeong commented on src/main/java/racingcar/Car.java
> +        this.name = name;
<img width="393" alt="스크린샷 2020-11-03 오후 4 18 36" src="https://user-images.githubusercontent.com/38595650/97958450-8a9f8a00-1df0-11eb-835f-780332a9f916.png">

현재, name으로 비어있는 string 을 입력하면 비어있는 이름이 name 에 저장됩니다.
name 에 직접적으로 null 값이 입력되는 경우는 없지만,
CarTest 에 NPE 상황에 대한 테스트 코드를 추가해 놓겠습니다.

2020-11-03 07:45 UTC, ghojeong commented on src/test/java/racingcar/CarGroupTest.java
> +        MoveStrategy strategy = new MoveStrategy() {
와우! 익명 클래스를 람다식으로 바꾸었는데도, checkMovable 추상 함수가 잘 작동하네요.
원리가 어떻게 되죠? 신기하지만 동작과정이 궁금해서 질문드립니다.

() -> true 가 checkMovable 추상 함수에게 어떻게 매핑이 되는 건가요?
만약 제가 MoveStrategy 인터페이스에 여러개의 추상함수를 선언해도 이런 람다 표현식을 사용할 수 있나요?

2020-11-03 08:41 UTC, neojjc2 commented on src/test/java/racingcar/CarGroupTest.java
> +        MoveStrategy strategy = new MoveStrategy() {
아 익명클래스에 대해 람다식 표현을 했을 뿐입니다 🙇 
사다리 미션으로 가시면 람다에 대해서 체계적으로 학습하며 미션을 수행할 시간이 오니 걱정안하셔도 됩니다 😄 

그나마 아래 내용이 좀 이해하기 쉬우실 것 같습니다 
> https://feco.tistory.com/76

2020-11-04 02:16 UTC, ghojeong commented on src/main/java/racingcar/NumConst.java
>      private NumConst() {}
8dfe2cd

개발할 때 개발 편의성 또한 중요시하는 편인데,
`CMD + Shift + O`  로 파일 검색을 했을 때 검색이 쉽도록,
class, test, const 가 비슷한 네이밍을 가질 수 있도록 해보았습니다.

가령 CarGroup 이라는 파일명을 검색하게 되면,
CarGroup, CarGroupTest, CarGroupConst 3개의 class 가 검색되므로,
서로 다른 디렉토리 혹은 패키지로 분리되더라도 찾기 쉬운 장점이 있습니다.

개인적으로 React 웹 프론트 개발자로써 이런 상황이 생기면 아래처럼 관리하는 편인데,
자바같은 경우에는 연관된 클래스들을 어떻게 관리하나요?
자바스크립트처럼 디렉토리 단위가 아닌 패키지 단위로 관리되는 것 같아서요.

```txt
└── CarComponent
    ├── index.jsx
    ├── style.js
    ├── test.js
    └── const.js
└── GameComponent
    ├── index.jsx
    ├── style.js
    ├── test.js
    └── const.js
```

2020-11-04 06:34 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
> Game과 View가 서로 의존적인 부분이 있는 것 같습니다

RacingView 에서 RacingGame을 의존하지 않도록 분리해내어 아래와 같은 모양이 되었습니다.

<img width="544" alt="스크린샷 2020-11-04 오후 3 31 08" src="https://user-images.githubusercontent.com/38595650/98077252-36111300-1eb3-11eb-9867-1c3eb00db25b.png">

2020-11-04 06:36 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
분리하기 위해 고심을 하다보니,
RacingView 를 기존의 InputView 와 유사한 인터페이스를 갖게 하도록 하기 위해,
싱글톤 객체로서, Car 를 출력하는 consumer 객체만 반환 하도록 하였습니다.

2020-11-04 06:40 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
View 가 consumer 를 리턴하도록 하는 것은,
RacingView 은 레이아웃만 제공하고, 출력이 CarGroup 컬렉션의 데이터에 리액티브하게 반응했으면 하는 욕심에 이렇게 해본 것인데,

> Game이 최종 종료 된 후 결과만 View에 전달 해서 화면에 보여지도록 개선하면 어떨까요??

피드백 주신 대로, RacingGame 객체는 play 를 할 때마다, GameState 를 generate 해서,
그렇게 만들어진 GameState 배열을 View 가 출력하도록 하는게 좋을 지 여쭈어봅니다.

2020-11-04 06:41 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
>  GameState 배열을 View 가 출력

본래 이런 형태로 작성하다가, 이렇게 되면 RacingView 가 GameState 클래스에 대한 새로운 의존성이 생기는 것 같아서 지금과 같은 형태로 바꾸게 되었습니다.

2020-11-04 06:52 UTC, ghojeong commented
RacingView 에서 RacingGame 을 없애려다 보니 오래걸리게 되었네요.

3a8e074 커밋 위주로 변경사항 봐주시면 감사하겠습니다.

일단 리뷰 주신 내용은 나름대로 고친것 같습니다.

2020-11-04 06:55 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
아니면, CarGroups 에서 getPositions 와 getNames 함수를 통한 Integer 와 String 리스트를 RacingView 에게 넘겨서 출력하도록 할까요?
Integer 와 String 리스트를 넘기는 아이디어는,
렌더링의 최소 단위가 Car 가 아닐경우,
이름과 position 을 잘못 매칭하는 불상사가 생길 수 있다고 생각해서 그만두었습니다.

2020-11-04 10:44 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
> Game이 최종 종료 된 후 결과만 View에 전달 해서 화면에 보여지도록 개선하면 어떨까요?

69f8ac8 커밋에서 메멘토 패턴을 사용해서 말씀하신대로, 수정했습니다.
아래 그림과 같이 클래스 관계를 구성했는데, carGroup 가 Originator 역할을 맡고,
CareTaker 클래스는 따로 분리하지 않고 메인에서 해당 역할을 처리하도록 했습니다.

<img width="647" alt="스크린샷 2020-11-04 오후 7 42 09" src="https://user-images.githubusercontent.com/38595650/98101764-04f60a00-1ed6-11eb-8c59-42cdd2fdfa26.png">

2020-11-05 00:51 UTC, ghojeong commented
현재 이런 모양이 되었습니다.

<img width="564" alt="스크린샷 2020-11-05 오전 9 51 11" src="https://user-images.githubusercontent.com/38595650/98183891-77a1cc80-1f4c-11eb-98c0-273b92b77daf.png">

2020-11-05 00:59 UTC, ghojeong commented
점점 클래스가 늘어나고 있는데,
클래스간에 소통하는 DTO 의 단위가 Car 가 되어야 할지,
일급 컬렉션인 CarGroup 가 되어야 할지,
Memento 가 되어야 할지 고민입니다.

지금은 위 다이어그램에서 보이다시피 Car 단위로 소통하고 있습니다.
CarGroup 으로 소통의 단위를 바꿀까요?

2020-11-05 01:08 UTC, ghojeong commented on src/main/java/racingcar/RacingView.java
> -        this.game = game;
> Caretaker 클래스는 따로 분리하지 않고 메인에서 해당 역할을 처리하도록 했습니다.

cf4eca8 커밋으로 인해, CarGroup가 Originator, RacingGame d이 Caretaker 역할을 하게되었습니다.

2020-11-05 01:21 UTC, ghojeong commented on src/main/java/racingcar/RacingGame.java
> +        this.carGroup = new CarGroup(nameCsv, defaultStrategy);
현재 RacingGame 에서만, RandomStrategy 에 접근하고 있는데,
MoveStrategy 와 하위 클래스들은 도메인 영역에 속하는지 여쭈어봅니다.
지금은 아래처럼 생각하고 있어서요.

- Controller: Main
- View: InputView, RacingView
- Domain: Car, CarGroup, Memento, RacingGame
- 외부 라이브러리: MoveStrategy 와 각종 Strategy들

2020-11-05 01:24 UTC, ghojeong commented
> 지금은 위 다이어그램에서 보이다시피 Car 단위로 소통하고 있습니다.

참고로 Car 을 단위로 선택한 이유는 단위 테스트를 짜기 그나마 수월해서입니다.
CarGroup 이나 Memento 를 소통 단위로 작성을 해보니,
단위 테스트를 할 때 mocking 을 해야할 게 늘어났습니다.

2020-11-05 05:57 UTC, neojjc2 approved these changes
안녕하세요 정완님 🙇 

요청 사항 반영 정말 잘해주셨습니다 
전체적으로 엄청 정돈되고 정리된 느낌입니다 💯 💯 💯 

객체의 역할과 책임에 대해서도 어느정도 잘 정리가 되었고 
무엇보다도 정완님의 고민과 정성이 느껴져서 코드 보는 내내 
저도 같이 열정적이게 됐네요 😅 🔥 🔥 

몇 가지 소소한 의견 드렸습니다 
마지막 단계 구현 하실 때 검토 해주시고 반영해주시면 좋을 것 같습니다 👍 

정말 고생 많으셨습니다 

마지막 단계는 그간 작업하신 내용을 package에 맞도록 refactoring 하고 정리하는 미션 입니다
단위테스트를 할 수 있도록 객체들이 더 자기만의 역할과 책임에 대해 집중할 수 있게 개선해 나가시면 됩니다 🙇 

이제 거의 다 왔습니다!!
조금만 더 힘내주세요!!

마지막 단계에서 기다리고 있겠습니다 🔥 
정말 고생 많으셨습니다 🙇  

🚗 🚗 🚗 🚗 🚗

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/Car.java
> +    public Car(Car car) {
생성자에서 중복되는 부분이 있는 것 같습니다 😄 

정적 팩토리 메소드 (static factory method)를 한번 활용해보시는 건 어떨까요??

도움 되실 만한 내용 공유 드립니다
> https://medium.com/@logishudson0218/effective-java-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EA%B3%BC-%ED%8C%8C%EA%B4%B4-01-9999e6da4f66

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/Car.java
> +        if (name == null) {
NPE 방어 로직 👍

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/InputView.java
> +    private boolean validateNameCsv(String nameCsv) {
요청사항 반영 👍

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/Memento.java
> +        return cars;
반환 할 때 외부에서 변경하지 못하도록 (추가나 삭제 하지 못하도록) read only로 반환 하도록 수정 하시는걸 권장 드립니다 😄 
> https://medium.com/@logishudson0218/effective-java-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EA%B3%BC-%ED%8C%8C%EA%B4%B4-01-9999e6da4f66

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/OutputView.java
> +        StringBuilder sb = new StringBuilder();
`StringBuilder` 👍 
`StringBuffer`와의 차이점도 한번 정리해두시면 좋겠습니다 😄 

> https://ifuwanna.tistory.com/221

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/OutputView.java
> +            String carStr = this.convertCar(car);
`this`는 굳이 안붙여 주셔도 됩니다 😄 
일차적으로 같은 class 내에서 찾기 때문에 같은 class 내에 있는 method 호출이나 class 변수등에는 안붙이셔도 됩니다

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/OutputView.java
> +        return String.join(OutputViewConst.WINNER_DELIMITER, winners) + OutputViewConst.WINNER_MSG;
이렇게 바꿔볼 수 있을 것 같습니다 😄 
```
return winnerList.stream()
                .map(Car::getName)
                .collect(Collectors.joining(RacingViewConst.WINNER_DELIMITER)) + RacingViewConst.WINNER_MSG;
```

2020-11-05 05:57 UTC, neojjc2 commented on src/main/java/racingcar/RacingGame.java
> +    public List<List<Car>> getHistory() {
`List<List<Car>> ` 다소 어려운(?) 반환형입니다 😅  `Mementos `일급 컬렉션으로 개선 해 볼 수 있을 것 같습니다 🙇

2020-11-05 06:01 UTC, neojjc2 commented
https://github.com/next-step/java-racingcar/pull/1380#issuecomment-722058450

지금 디자인도 괜찮아 보입니다
하나의 DTO로 통일할 필요는 없어 보입니다
DTO야 말로 그 때 그 때 객체들간에 소통할 때 얼마든지 만들어질 수 있는 부분입니다 😄

2020-11-05 06:06 UTC, merged

2020-11-05 07:13 UTC, ghojeong commented on src/main/java/racingcar/RacingGame.java
> +    public List<List<Car>> getHistory() {
Memento 도 일급 컬렉션으로 만들 수 있다는 생각을 못했네요!
아이디어 감사합니다

2020-11-05 07:14 UTC, ghojeong commented on src/main/java/racingcar/OutputView.java
> +            String carStr = this.convertCar(car);
IntelliJ 의 autoFormat 에서 자동으로 붙여주던데,
관련 설정 수정하겠습니다.

2020-11-05 08:10 UTC, ghojeong commented on src/main/java/racingcar/Memento.java
> +        return cars;
올려주신 링크는 정적 팩토리 메소드에 관한 medium 글인데,
혹시 java 에서 read only로 반환하는 방법에 대한 글이 있다면,
공유해주시면 감사하겠습니다.

2020-11-05 08:11 UTC, ghojeong commented on src/main/java/racingcar/Memento.java
> +        return cars;
지금은 [Collections.unmodifiable](https://www.tutorialspoint.com/how-to-make-an-arraylist-read-only-in-java) 을 활용해볼까 하고 생각중입니다.
@neojjc2

2020-11-05 08:40 UTC, neojjc2 commented on src/main/java/racingcar/Memento.java
> +        return cars;
에고 죄송합니다 🙇 
> https://soft.plusblog.co.kr/71