[리뷰요청 드림]2단계 - 문자열 계산기
next-step/java-racingcar pull request #1387
Opened 2020-11-01 17:39 UTC by MaroKim

안녕하세요 황준일님~

자동차 미션까지 잘 부탁드리겠습니다 ㅎㅎ 

2단계 문자열 계산기 리뷰 요청 드립니다. 

부족한 점 알려주시면 바로 고민해보고 재요청 드리겠습니다. 

감사합니다~

2020-11-02 05:21 UTC, JunilHwang requested changes
안녕하세요! 리뷰를 종합해보자면 다음과 같습니다.

- 멤버 변수에 접근제한자가 생략되었습니다. 접근제한자를 사용해주세요! (private/protected/public)
- 메소드/클래스 이름에 줄여쓰기는 지양해주세요!
  - 특별한 일이 없는 한 풀 네임으로 작성해주세요.
- 객체를 역할별로 분리해주세요!
  - 지금은 하나의 객체가 굉장히 많은 역할을 수행하고 있습니다.
  - 사람에 비유해보자면, 한 사람이 기획/디자인/퍼블리싱/개발 전체를 하고 있는 형태입니다.
  - 따라서 각각의 역할에 맞게 분리해주는 작업이 필요합니다.

2020-11-02 05:21 UTC, JunilHwang commented on src/main/java/study/Cal.java
> +public class Cal {
줄여쓰기는 지양해주세요!
Calculator 처럼 풀 네임으로 작성해야 다른 사람들도 쉽게 이해할 수 있습니다.

2020-11-02 05:21 UTC, JunilHwang commented on src/main/java/study/Cal.java
> +public class Cal {
지금은 하나의 클래스에서 모든 기능을 구현하고 있습니다. 조금 더 객체를 분석해서 역할별로 나눠보시는게 어떨까요?

2020-11-02 05:21 UTC, JunilHwang commented on src/main/java/study/Cal.java
> +    }
연산을 메소드가 아닌 객체로 추상화해보세요!

2020-11-02 05:21 UTC, JunilHwang commented on src/main/java/study/Cal.java
> +    }
이러한 코드는 아예 새로운 객체로 분리시키는게 좋을 것 같습니다!

2020-11-02 05:21 UTC, JunilHwang commented on src/main/java/study/Cal.java
> +    }
객체지향 생활체조 원칙에 따라서
- 중첩 if
- if/for 중첩
- switch/case
이렇게 세 가지는 사용하지 않는 방식으로 작성해주세요!
새로운 메소드로 만들거나 스트림을 사용하면 된답니다.

2020-11-03 15:59 UTC, MaroKim commented
리뷰 감사 드립니다. 
말씀해주신 부분에 대해 고민하고 구글링 해보면서 부족한 점을 깨달았습니다. 감사합니다. 

말씀해주신 부분중 객체 분할과 Switch-case문 제거, if/for 중복 제거에 생각이 잘 떠오르지 않아 오래 걸린것 같습니다. 
다시 확인 부탁드리고 또 말씀해주신 부분에 대해 고민하고 수정하겠습니다.감사합니다.

2020-11-03 16:04 UTC, JunilHwang requested changes
안녕하세요 광수님!
피드백 반영 잘 해주셨네요 👍 
다만 아직 몇 가지 보완점이 있습니다.

요약해보자면
- 멤버 변수는 최대 3개만 사용해주세요!
- 현재 검증 과정은 새로운 객체를 만들면 어떨까요?
- 연산자들을 관리하는 객체를 만들면 어떨까요?
- 연산자를 조금 더 유연하게 관리할 수 있도록 설계해보세요!

이상입니다!

2020-11-03 16:04 UTC, JunilHwang commented on src/main/java/study/Calculator.java
> +        operatorMap = new HashMap<String, Operator>();
operatorMap을 Calculator에서 관리하는게 아니라
아예 Operators에 대한 집합을 관리하는 객체가 있으면 어떨까요?
그래서

```java
operators.put("+", (a, b) -> a + b);
operators.put("-", (a, b) -> a - b);
operators.put("*", (a, b) -> a * b);
operators.put("/", (a, b) -> a / b);
new Calculator(operators);
```
이런식으로 사용할 수 있게 만들면 좋을 것 같습니다.
그래야 조금 더 확장하기가 수월합니다.

2020-11-03 16:04 UTC, JunilHwang commented on src/main/java/study/Calculator.java
> +                                        .collect(Collectors.toList());
문자열로 필터링을 하는게 아니라 `operatorMap`에 존재하는지의 여부로 필터링 하면 어떨까요?

2020-11-03 16:04 UTC, JunilHwang commented on src/main/java/study/Calculator.java
> +                                        .collect(Collectors.toList());
앞 부분에서 숫자인지 검사하고, 연산자인지 검사하는 과정을 거쳤다면 이 부분은 불필요할 것 같습니다.

2020-11-04 13:52 UTC, MaroKim commented
안녕하세요 황준일님

어제 빠르고 꼼꼼하게 확인해주셔서 감사합니다.

어제 리뷰해주신 내용을 바탕으로 또 좋은 공부가 되었습니다.
특히 람다 관련해서 많이 보게 되어서 좋았습니다.

어제 말씀해주신데로 Calculator의 역할을 줄이고
Tokenizer 클래스 생성 및 OperatorManager(연산자 관리) 클래스 생성해서 정리해봤습니다.

유연하게 관리할수 있도록 하라고 말씀해주셔서 연산자를 따로 입력할 수 있도록 만들었는데 제가 잘 이해한것인지 모르겠네요 ㅎㅎ 

이번에도 잘 부탁드립니다. 감사합니다.

2020-11-04 14:02 UTC, JunilHwang approved these changes
안녕하세요 성태님! 피드백 반영 잘 해주셨네요 👍 
이제 본격적으로 자동차 미션을 수행해봅시다!
🚗 🚗 🚗 🚗 🚗 

추가적인 리뷰는 당장 반영할 필요는 없고 계속 고민해보시면 될 것 같아요!

2020-11-04 14:02 UTC, JunilHwang commented on src/main/java/study/InputCheckor.java
> +            }
이 부분은 먼저 숫자를 검증하고, 오퍼레이터를 검증하는건 직접 등록된 객체와 비교하는게 어떨까요?
그리고 For과 if가 중첩되어 있어서 새로운 메소드로 분류하면 좋을 것 같습니다!

2020-11-04 14:02 UTC, merged