[자동차 경주-단위테스트] 3단계 - 자동차 경주
next-step/java-racingcar pull request #1388
Opened 2020-11-01 18:41 UTC by eyabc

2020-11-02 11:20 UTC, vagabond95 requested changes
다른 분들의 구현을 참고하며 적극적으로 개선하고 노력하는 모습 정말 멋지십니다 💯 🥇 

2단계 코멘트도 잊지 않고 잘 반영해주셨네요 ㅎㅎ
전략 패턴을 통해 움직임을 관리하는 로직을 추상화해주신 시도도 좋았습니다 👍 

구현내용에 대하여 몇가지 코멘트를 달았는데요, 수정 후 다시 리뷰요청 부탁드립니다!
리뷰 내용에 대하여 궁금하거나 논의하고 싶은 점 있으시면 편하게 DM 주세요 :)

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/step03/Car.java
> +        final int defaultCarKind = 1;
해당 변수는 생성자에 바로 넘겨주므로 매번 생성하지 않고 상수로 관리되어도 괜찮을것 같아요~!

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/step03/Car.java
> +        if (moveStrategy.isGoing()) {
움직임을 결정하는 로직을 전략패턴으로 추상화 👍

다만, moveStrategy 는 move 할 때 마다 사용되므로 
move 메소드에서 주입 받는 것이 아닌 생성자 레벨에서 받고, 멤버변수로 초기화 후 사용하는 방식은 어떨까요?

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/exception/NotPositiveIntegerException.java
> +public class NotPositiveIntegerException extends IllegalArgumentException {
커스텀 예외 추가 👍

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/step03/Operator.java
> +        Stream.iterate(1, a -> a + 1)
단순히 for - loop 로 나타낼 수 있는 코드라면 stream 을 사용함으로 얻는 이점이 많지 않은 것 같아요. (요건 개인적인 생각입니다 ㅎ)

요런 글도 있으니 한번 같이 고민해보시면 좋을 것 같아요~!
[stream to for loop?](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/step03/Cars.java
> +    public static Cars of (List<Car> cars) {
사용되지 않는 정적 팩토리 메소드는 지워주세요~!

2020-11-02 11:20 UTC, vagabond95 commented on src/main/java/step03/view/ResultView.java
> +    public static void print(Stream<Car> cars, final String carKind) {
cars 를 stream 타입으로 넘기신 의도가 궁금합니다!

2020-11-02 11:20 UTC, vagabond95 commented on src/test/java/step03/CarTest.java
> +        car.move(() -> input);
전략패턴을 사용하여 랜덤조건이 들어가있는 비즈니스로직을 잘 분리해주셨네요 👍 💯

2020-11-02 11:20 UTC, vagabond95 commented on src/test/java/step03/RandomGeneratorTest.java
> +        assertThat(result).isBetween(0, input + 1);
랜덤 값은 테스트 수행 시마다 다른 결과를 반환하기에 테스트를 시도하는 의미가 없다고 생각되요.
우리가 암묵적으로 제한된 범위 내에서 반환될 것이라고 **기대**할 수 는 있어도 기본적으로 랜덤값이라는 특성상 다음 테스트 시에도 동일할 것이라는 보장이 안되기 때문입니다!

그래서 이러한 부분을 테스트할 수 없기 때문에, 적용해주신 전략패턴 등을 이용하여 동작을 분리하고 통제할 수있는 결과를 반환하도록 하여 테스트가 진행 가능하도록 접근하고 있습니다 :)

2020-11-02 11:46 UTC, eyabc commented on src/test/java/step03/CarTest.java
> +    void DEFAULT_Position_CAR_생성_테스트() {
좋은 아티클도 같이 첨부해 주셔서 정말 감사합니다! 테스트 케이스의 네이밍도 이쁘게 짓는 방법이 있었군요! 

134b4be 
한번 영어로 고쳐보았는데요, 처음이라 많이 어색합니다! 지훈님께서 조언해 주신부분 항상 생각하면서
한글로도 써보고 여러 방법으로도 시도해 보겠습니다!

2020-11-02 11:58 UTC, eyabc commented on src/main/java/step03/view/InputView.java
> +    public static int scanNumberOfCars() {
java 에서 input io 를 하는 방법이 scanner 외 다른 방법도 있군요! 
4257fc0

기존의 두 메서드를 readInterger(String message) 의 인터페이스로 변경하고 
main 에서 메세지를 변경할 수 있는 형태로 만들어보았는데 이 방법은 어떻게 생각하시나요?

2020-11-02 13:48 UTC, eyabc commented on src/main/java/step03/RandomGenerator.java
> +    public static int ZeroToPositiveIntGenerate(int to) {
ddb807e 
항상 기억하도록 하겠습니다!

2020-11-02 13:53 UTC, eyabc commented on src/main/java/step03/Operator.java
> +public class Operator {
500c074

Operator 를 Race(경주) 로 변경해보았습니다!

2020-11-02 14:54 UTC, eyabc commented on src/main/java/step03/Main.java
> +        Validator.validatePositiveNumber(numberOfMoves);
현재 방식
-  Main 에서 받은 input 을  Validator.validatePositiveNumber 으로 검사하고 검사된 input 을 Cars 인스턴스와, Operator 의 인스턴스에게 주었습니다. 이 경우, Cars 와 Operator 에게 input 을 검사하는 짐을 덜어주어야 한다고 생각했기 때문입니다.
-  Validator 는 여러가지 Validator 들을 모아두는 유틸성 클래스로 쓰일 것 같아 Validator 클래스를 만들었습니다. 보내주신 utill class anti pattern 를 읽어보니 유틸성 클래스를 어떻게 인스턴스를 만드는 클래스로 만들지 생각해 봐야겠어요!

지훈님 의견을 구현해보고 한번 비교해 보겠습니다!

2020-11-03 05:07 UTC, eyabc commented on src/main/java/step03/Main.java
> +        Validator.validatePositiveNumber(numberOfMoves);
`numberOfCars` 와 `numberOfMoves` 를 검증해주는 것을 외부에서 주입해주어야 유연 하다고 생각을 하였습니다.

하지만 **객체에 대한 검증은 객체 스스로 해야되며 검증 validate 의 기능을 바꾸기 위해서는 **상속** 의 방식을 택해야 한다.** 라고 준일님의 피드백을 받았습니다. 

경험이 부족해서 앞으로 많이 알아가야 할 것 같습니다

2020-11-03 05:16 UTC, eyabc commented on src/main/java/step03/Car.java
> +        final int defaultCarKind = 1;
1d63953 

dcc564a

지적 감사합니다!

2020-11-03 05:29 UTC, eyabc commented on src/main/java/step03/Main.java
> +        final String carKind = "-";
https://github.com/next-step/java-racingcar/pull/1388#discussion_r516430267

2020-11-03 05:44 UTC, eyabc commented on src/main/java/step03/Main.java
> +        final String carKind = "-";
84d7db4 
변경을 해보았는데 지훈님이 생각하신것과 같은지 궁금합니다 ㅠㅠ

2020-11-03 08:19 UTC, eyabc commented on src/main/java/step03/Car.java
> +        if (moveStrategy.isGoing()) {
9d9c09c

**같은 동작으로 동일하게 사용 되는 변수가 매 번 만들어진다면 생성자를 사용해 보자.**

Car 클래스에 `default 멤버변수 값`을 정하는 것 괜찮은 건가?
- 고민한 이유, default 멤버 변수가 늘어날 수록 만들어야 하는 생성자의 수는 2 의 제곱으로 늘어난다.
 -> 한 클래스 멤버변수는 3개이상 쓰지 않는 것 이 좋다.

하지만 default 멤버변수 값` 인한 두 번째 문제는,
-
- Cars 클래스 역시 default 를 가지는 속성을 생성자 매개변수로 받아오기 때문에, 
- Car 인스턴스를 만드는 Cars 클래스 에서도 그 만큼의 생성자를 만들어 줘야 하는 문제점이 있었다.

이 방법이 썩 좋아 보이지는 않네요.. 객체의 책임과 역할을 지정하는 일이 아직은 힘든 것 같습니다. 

이에 Default 상수를 정의하는 생성자는 없앴습니다.

2020-11-03 08:35 UTC, eyabc commented on src/main/java/step03/Operator.java
> +        Stream.iterate(1, a -> a + 1)
[stream to for loop?](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)
java 의 `stream 의 forEach`, `for 문`을 비교해 본 적이 없었기 때문에, 성능 차이가 별로 없고 함수형 프로그래밍은 가독성이 더 좋으므로 스트림을 써야한다고 생각 하고 있었습니다.
위 글을 읽고 난 후, `stream 의 forEach`, `for 문` 의 성능은 같지 않다는 이야기와, forEach 의 가독성이 항상 좋은 것은 아니라는 것을 알게 되었고.   
무분별하게 stream forEach 를 사용하는 것에 대한 경계를 일깨워 준 것 같습니다!

2020-11-03 08:42 UTC, eyabc commented on src/main/java/step03/Cars.java
> +    public static Cars of (List<Car> cars) {
40c0280

감사합니다!

2020-11-03 08:46 UTC, eyabc commented on src/main/java/step03/view/ResultView.java
> +    public static void print(Stream<Car> cars, final String carKind) {
최대한 가공된 cars 를 print 메서드에 넘겨주어야 한다고 생각했기 때문에 stream 으로 넘겨주었습니다. 지훈님 생각은 어떠신가요?

2020-11-03 08:50 UTC, eyabc commented on src/test/java/step03/RandomGeneratorTest.java
> +        assertThat(result).isBetween(0, input + 1);
랜덤값이 들어가는 부분을 어떻게 테스트 해야될지 고민을 많이했었는데 감사합니다!

2020-11-04 02:10 UTC, vagabond95 commented on src/main/java/step03/view/InputView.java
> +    public static int scanNumberOfCars() {
외부에서 메세지를 주입할 수록 View 는 알아야할 정보가 적어지므로 더 독립적으로 동작할 수 있어 추후 변경에도 용이할 것 같습니다 👍 
메소드 네이밍도 내부 구현을 드러내지 않도록 잘 지어주셨네요.

2020-11-04 02:14 UTC, vagabond95 commented on src/main/java/step03/Main.java
> +        Validator.validatePositiveNumber(numberOfMoves);
이미 제가 의도한 깨달음을 얻고 가신 것 같습니다 :)

위 내용에 대해 좀 더 다뤄보면 사실 저는 객체지향 프로그래밍 관점에서 최대한 Util 클래스 사용을 지양해야한다고 생각하는 편입니다.
Util 클래스가 담고있는 의미 자체가 하나이상의 책임을 가지기 쉬워 바로 SRP 법칙이 위반될 수 있고, 링크로 첨부드린 god object 로 금방 변질이 되기 때문인데요,

객체가 책임져야할 일은(= 관련된 정보를 알고 있다.) 스스로 수행할 수 있어야한다는 측면에도 잘 맞지 않는 다고 생각합니다 :)

2020-11-04 02:19 UTC, vagabond95 commented on src/main/java/step03/view/ResultView.java
> +    public static void print(Stream<Car> cars, final String carKind) {
절대적인 정답은 없으므로 참고만 해주시면 될 거 같습니다.

제 기준으로 Stream 은 List 와 같은 콜렉션에 비해 기본적으로 자유도가 떨어진다고 생각되는 편입니다. 보통 자료형은 콜렉션 형태로 대부분 들고 있는 경우가 많아 해당 메소드를 사용하기 위해서는 stream 으로 변환해줘야하는 일이 생길 수 있고, stream 자체도 element 를 순회하면서 처리할 수 있는 로직에는 특화되어 있을 뿐 일반적으로 기대하는 자료구조의 역할 (값을 가져오고, 확인하는 것) 을 수행하기에는 조금 애매한 부분이 있지 않나 싶어서요!

2020-11-04 02:22 UTC, vagabond95 commented on src/main/java/step03/Operator.java
> +        Stream.iterate(1, a -> a + 1)
사실 함수형 프로그래밍을 사용했을 때 가독성이 좋아진다. 라는 내용에 대해 저는 조금 보수적인 입장을 취하고 있는데요,

만약 각 element 값마다 변경이 필요하고 이러한 값들을 취합하여 로직을 수행하는 일들에는 함수형 프로그래밍과 같은 선언적인 방식이 좀 더 가독성이 좋을 수 있겠으나, 단순히 element 를 순회하는 로직이라면 가독성면에서나 성능 면에서나 (사실 거의 미미하긴 합니다 ㅎㅎ;) 조금 오버스펙이라는 생각을 개인적으로 가지고 있습니다. 이부분은 정답이 없으므로 계속 과제 진행하면서 고민해보셔도 좋을 것 같아요~!

2020-11-04 06:05 UTC, vagabond95 commented on src/main/java/step03/Car.java
> +        if (moveStrategy.isGoing()) {
제가 제대로 이해한 것인지 모르겠으나,
멤버변수가 생긴다고해서 항상 생성자의 수가 2^n 개 만큼 늘어나지는 않을 것 같습니다!
2^n 개 만큼 늘어나려면 각 멤버변수 조합 경우의 수만큼 생성자를 만들어주신 다는 의미인데 실제로는 그런경우가 많지않고 매번 그러한 상황이 필요하다면 클래스 분리의 신호 혹은 멤버변수가 적절히 있는지 고민해볼 필요가 있을거 같습니다 ㅎㅎ

위 내용과 별개로, 메소드 레벨에서 주입받으나 생성자를 통해 멤버변수로 가지고 있으나 현재로는 동작에는 크게 차이가 없으므로 어느쪽이 나중에 변경에 좀 더 용이할지는 고민해보시면 좋을 거 같아요!

2020-11-04 06:09 UTC, vagabond95 commented on src/main/java/step03/Main.java
> +        final String carKind = "-";
ResultView 를 어떤역할로 정의하시느냐에 따라 다를 것 같아요 ㅎㅎ
1. ResultView 는 화면에 print 하는 역할만 수행한다. -> 라고 한다면 print 할 내용은 외부에서 주입받고, 클래스는 print 에만 신경을 쓰는 형태가 될거에요.
2. ResultView 는 화면에 '자동차 게임의 결과를 print' 하는 역할을 수행한다. -> 이 경우 자동차 게임에 대한 결과를 어떻게 그릴지 View 에서 알고 있는 것이 적절하지 않을까요~?

다만, 현재 작성해주신 구조에서는 View - Main (Controller) - Domain 의 구조로 구성된 것으로 보이는데, Controller 레벨에서 어떻게 그릴지에 대한 정보를 아는 것보다는 View 에서 알고 관리하는 것이 어떨까 하는 의도에서 코멘트를 달아봤습니다 ㅎㅎ

2020-11-04 06:10 UTC, vagabond95 approved these changes
피드백 잘 반영해주셨습니다 👍 
각 단계에서 고민의 흐름을 적어주셔서 저도 다시 코멘트 달기 수월했던 것 같아요 ㅎㅎ

각 질문주신 내용에 대하여 제 생각을 추가로 담아봤는데요, 해당 내용에 대해 이해가 가지않거나 논의하고 싶은점 있으시면 편하게 DM 주세요~!

다음단계 진행부탁드립니다!

2020-11-04 06:11 UTC, merged