step3
next-step/java-racingcar pull request #1398
Opened 2020-11-02 14:06 UTC by am003507

안녕하세요 
코드를 다시 정리 해보았습니다 ㅎㅎ
이전에 있던 풀리퀘스트를 close 하고 다시 pr 날리는게 맞나요..?
private 메소드 테스트 관려해서 링크 올려주셔서 감사합니다. 아직 잘모르겠지만 ㅎㅎ 많은 도움이 되었습니다.

날씨가 춥네요! 감기 조심하세요 ㅋㅋ

2020-11-03 04:52 UTC, enemfk777 commented
피드백 반영을 해주시면서 클래스 분리가 더 이루어졌는데요,
View나 Input 클래스, 단순한 DTO 클래스가 아닌 클래스에도 테스트코드를 작성해주세요

2020-11-03 05:00 UTC, enemfk777 requested changes
미션을 매일 열심히 진행해주고 계시네요 💯 

PR 관련 문의 주신건 이전 step Merge 슬랙 메세지에도 남겨드렸는데,
병무님 레파지토리의 브랜치에 피드백 내용을 푸시 해주시면 PR에도 반영되니
PR을 Close 하고 다시 요청하지 않으셔도 됩니다 :)

그럼 리뷰 드린내용 확인후 반영 부탁드립니다!! 🙇‍♂️

화이팅입니다!!

2020-11-03 13:27 UTC, am003507 commented on src/main/java/step3/ErrorMessage.java
> +    public final static String RACING_SPEC_IS_NULL = "racing spec is null";
아이고 ㅜㅜ 여기도 남아있었군요 ..

2020-11-03 13:30 UTC, am003507 commented on src/main/java/step3/RacingCarManager.java
> +        joinCarList.stream().forEach(car -> car.move());
에고 피드백 받았던 부분인데 ㅎㅎ; 쉽지 않네요 !  감사합니다~

2020-11-03 16:00 UTC, am003507 commented on src/main/java/step3/RacingCarManager.java
> +    private final List<Car> joinCarList = new ArrayList<>();
오우 .. 이런게 있었군요.. 고려하지 못했습니다..ㅠ

2020-11-04 13:37 UTC, enemfk777 approved these changes
안녕하세요 병무님 🙇‍♂️

제 피드백 설명 역량이 부족해서 피드백을 반영하시다가
잘 잡혀가던 구조에 균열이 간 느낌입니다 😭

잘 못 반영 된 부분에 다시 피드백을 드렸습니다.
이번 피드백도 긴가 민가 하시다면 DM 주세요!!

다음 미션 진행을 위해 이번 PR은 Merge 하겠습니다!!

다음 미션에서 같이 반영해서 PR 부탁드립니다!!

2020-11-04 13:37 UTC, enemfk777 commented on src/main/java/step3/Car.java
> +        if (value > 4) {
저의 역량 부족으로 의미가 잘 못 전달 된것 같네요 ㅜㅜ
MoveStrategy를 Car가 가지고 있는건 옳은 부분 이었습니다 👍 

다만 여전히 Car의 move 메서드가 랜덤성 때문에 테스트가 어려웠는데요

그렇다면 MoveStrategy를 주입받는 생성자를 이용하면 좋을 것 같아 드린 말씀이었답니다.

기존 처럼 인자가 필요없이 new Car()로 생성할 수 있게 하는 생성자 하나,
new Car(new 테스트용전략) 과 같이 테스트하기 용이한 전략을 만드는 형식이죠.

그리고 테스트 클래스에 내부 클래스로 TestStrategy 클래스를 하나 작성하고, new Car에서 TestStrategy의 객체를 주입시켜 Car의 테스트를 용이하게 했으면 했답니다 ㅜㅜ

아래와 같이 TestStrategy를 짠다면 ParameterizedTest에서 true와 false를 넘겼을 때의기대 값도 한번에 테스트를 할 수 있겠죠

```
public class ForTestStrategy implements MoveStrategy {
   
   private BooleanSupplier supplier;

   ForTestStrategy(BooleanSupplier supplier) {
            this.supplier = supplier;
        }

    @Override
    public boolean move() {
        return supplier.getAsBoolean();
    }
}
```

2020-11-04 13:37 UTC, enemfk777 commented on src/main/java/step3/Main.java
> +        });
이부분도 제 의도가 잘 전달되지 못 한 것 같은데요  😭
IntStream의 forEach의 위치는 RacingGame에서 진행되고 있던 이전 코드가 옳아 보입니다.
RacingGame에서 RacingSpec을 들고 있으니 거기서 진행하는게 자연스러웠죠 :)

다만 forEach 안의 람다에서 
1. RacingCarManager.moveCars() 한 번 실행하고
2. RacingCarManager.get getRacingStatus()를 실행하고 (무분별한 Getter 사용)
3. RacingRecord. saveOneStepRecord()로 2번을 저장하고 
하는 구조에서

RacingCarManager.moveCars()를 호출하면 RacingCarManager 내부에서 RacingRecord를 만들어서 반환하고,
최종적으로 List<RacingRecord>를 반환해 이걸 바로 resultController에 넘기면 좀 더 코드가 깔끔해 지지 않을까 생각해봤답니다.

직접 코드로 보여드리는게 아니니 역시 어려운데요.. 😭
이 부분이 이해가 안되신다면 DM 부탁드려요!!

2020-11-04 13:37 UTC, enemfk777 commented on src/main/java/step3/controller/ResultController.java
> +public class ResultController {
InputController와 같이 이 클래스도 상태를 갖지 않는데요,
그렇다면 굳이 비싼 연산인 new 를 이용해서 객체로 만들어서 사용할 필요가 있을까요? :)

2020-11-04 13:37 UTC, merged

2020-11-05 13:45 UTC, am003507 commented on src/main/java/step3/controller/ResultController.java
> +            throw new NullPointerException();
NullPointerException을 사용하면서도 조금 햇갈리는 부분이 있었는데요 정리가 되는느낌이네요 ㅎㅎ