[Step3] 자동차 경주
next-step/java-racingcar pull request #1404
Opened 2020-11-02 16:36 UTC by SungMinHong

<h1>자동차 경주 구현</h1>

리뷰어님 안녕하세요. 
아직 테스트 코드를 다 작성하진 않았지만 
현재 진행하고 있는 방향이 맞는지 검토 받고자 먼저 리뷰 요청 드립니다.
🙇‍♂️

1. 레이어 설계
레이어는 view, application, domain 이렇게 3단계로 나눠 진행 했습니다.

2020-11-03 03:14 UTC, vagabond95 requested changes
테스트 코드부터 보며 리뷰를 진행했음에도 각 클래스의 역할을 파악하는데 어려움이 크게 없었습니다. 역할별로 잘 분류하고 네이밍이 신경을 많이 써주신 것 같아요 👍 👍 

전략 패턴을 사용해서 랜덤을 포함하는 로직을 분리하여 테스트에 용이하도록 구현하신 시도도 좋았습니다. 💯 

그외 구현내용에 대하여 간략히 코멘트를 달았는데요, 고민해보시고 반영 후 다시 리뷰요청 부탁드릴게요~!

2020-11-03 03:14 UTC, vagabond95 commented on src/main/java/step3/view/output/ResultView.java
> +    public String toString() {
InputView 는 내부에서 Printer 를 활용하여 콘솔에 노출 시키는 역할을 수행하고 있는데요,

ResultView 도 같은 View 개념이라면 자동차 결과를 그리는 결과를 리턴하는 것이 아니라 내부에서 Printer 를 이용하여 그려주는 역할도 수행해줘야하지 않을까요~?

2020-11-03 03:14 UTC, vagabond95 commented on src/main/java/step3/application/SimulationResult.java
> +        this.snapshots = Collections.unmodifiableList(snapshots);
불편 리스트 활용 👍

2020-11-03 03:14 UTC, vagabond95 commented on src/main/java/step3/NextStepRacingCarSimulation.java
> +        return new InputView().receiveSimulationCondition();
InputView 는 내부에서 멤버변수를 사용하지 않으므로 별도 인스턴스 생성없이 메소드를 static 으로 제공하도록 바꿀수도 있을 거 같아요.

2020-11-03 03:14 UTC, vagabond95 commented on src/main/java/step3/domain/RacingMap.java
> +        return new RacingMap(Collections.unmodifiableMap(new HashMap<>(racingCarLocation)));
새로 hashMap 을 생성하지 말고 바로 넘겨줘도 되지 않을까요~?

2020-11-03 03:14 UTC, vagabond95 commented on src/main/java/step3/view/output/ResultView.java
> +            final int position = racingMap.findPosition(car);
View 가 RacingCar 의 위치를 구하는데 알아야 하는 정보가 꽤 많은 것 같아요. 즉, RacingCar 도메인의 내부 구현에 종속되어 있는 부분이 제법 있는데요, 최대한 이러한 의존성을 줄여볼 수 있을까요?

ex) View 에서 racingMap.findPostion(car) 를 호출해야 각 자동차의 위치를 그릴 수 있다는 사실을 꼭 알필요가 있을까요?

2020-11-03 13:30 UTC, SungMinHong commented on src/main/java/step3/view/input/InputView.java
> +    private int QuestionAndAnswer(final String question) {
엇 감사합니다 ㅎㅎ

2020-11-03 13:41 UTC, SungMinHong commented on src/main/java/step3/view/output/ResultView.java
> +    public String toString() {
넵 View라는 클래스를 결과값을 담을 dto로 여길지 아니면 직접 print를 하는 역할까지 수행하도록 할지 고민이 많았습니다.. 이 고민하며 작성을 하다보니 InputView와 ResultView 클래스의 특징이 달라졌던 것 같습니다.. 😂
말씀 주신 것 처럼 InputView와 같은 개념으로 ResultView에서 직접 wirte를 할 수 있도록 하는게 좋을 것 같아보여 리펙토링 하도록 하겠습니다. 감사합니다!

2020-11-03 13:43 UTC, SungMinHong commented on src/main/java/step3/NextStepRacingCarSimulation.java
> +        return new InputView().receiveSimulationCondition();
넵 static 클래스로 변경하도록 하겠습니다~ ResultView도 통일성 있게 static으로 변경하겠습니다~ 😃

2020-11-03 13:55 UTC, SungMinHong commented on src/main/java/step3/domain/RacingMap.java
> +        return new RacingMap(Collections.unmodifiableMap(new HashMap<>(racingCarLocation)));
HashMap의 생성자에 Map을 전달한 이유는 깊은 복사를 하기 위해서였습니다~
얕은 복사가 되면 모두 동일한 Map 인스턴스를 참조해 아래와 같이 모두 동일한 결과를 출력할 수 있습니다.
![image](https://user-images.githubusercontent.com/18229419/97993617-a8d4ac80-1e27-11eb-845c-3639a72a281b.png)

2020-11-03 14:26 UTC, SungMinHong commented on src/main/java/step3/view/output/ResultView.java
> +            final int position = racingMap.findPosition(car);
네 도메인 내부 구현에 view가 너무 의존하고 있는 것 같네요. 
의존성을 줄여보도록 하겠습니다. 
감사합니다~

2020-11-04 09:40 UTC, vagabond95 approved these changes
View 에서 도메인에 대한 의존성이 대부분 끊겼네요 👍 

처음에는 사소하게 놓칠 수 있는 부분이지만, 도메인이 복잡해질수록 View 로 부터 분리도 어렵고 도메인의 변경이 View 에도 영향을 끼치기 때문에 전반적으로 수정하기 어려운 구조가 되는 것을 미리 방지하는 연습을 수행해보셨다고 생각합니다 ㅎㅎ

다음단계 진행해주세요~!

2020-11-04 09:40 UTC, merged