Step5
next-step/java-racingcar pull request #1413
Opened 2020-11-03 11:10 UTC by joswlv

리뷰 잘부탁드립니다.

2020-11-03 11:42 UTC, neojjc2 commented
#tag @neojjc2

2020-11-03 12:48 UTC, javajigi commented on src/main/java/racinggame/domain/Car.java
>      this.moveRule = new RandomMoveRule();
생성자에 중복이 많은데 중복 제거하면 어떨까요?

2020-11-03 12:50 UTC, javajigi commented on src/main/java/racinggame/domain/model/MovingResult.java
>          .filter(carSateInRace -> carSateInRace.getRacingPosition() == winnerPosition)
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.
이와 같이 구현했을 때 테스트 관점에서 어떤 장점이 있을까? 
코드 재사용 측면에서 어떤 장점이 있을까?

2020-11-03 13:11 UTC, neojjc2 requested changes
안녕하세요 승완님 🙇 

마지막 미션도 잘 구현해주셨습니다 💯 

도메인 별로 package를 잘 만들어 주셔서, 
한결 정돈된 느낌이 듭니다 👍 

몇 가지 개선 되면 더 좋은 코드가 될 것 같아서
의견 드렸습니다 

한번 검토해 주시고 다시 리뷰 요청해주시면 감사하겠습니다 

마지막 입니다 😄 
조금만 더 힘내주세요 🔥

2020-11-03 13:11 UTC, neojjc2 commented on src/main/java/racinggame/domain/Car.java
>    public Car(String carName, MoveRule moveRule) {
Car를 생성할 때 `MoveRule`이 결정되는 구조입니다 😄 
만약에 1,2 라운드를 진행하다가 3라운드에 뭔가 문제가 생겨서 참가한 Car들을 모두 멈춰야 한다면 어떻게 될까요??
물론 예가 좀 억지스럽긴 하지만 😅 

Car가 MoveRule의 상태를 가지고 있을 필요가 있을까요??
전략 패턴은 유연한 변경에 대응하기 위해 사용 됩니다 
만약 중간에 레이스 Rule이 변경 되었을 때 
레이스에 이미 참가한 Car들은 변경된 Rule을 따라갈 수 없습니다

오히려 `CarRacing` 을 보면 racing car 들을 준비시키고 racing 을 시작하고, 결과를 받아오는 역할 밖에 없습니다. 
게임 진행을 어떤 Rule로 할지 역할을 가져가야 한다면 `CarRacing`가 가져가야 하는게 더 자연스럽지 않나 
조심스럽게 의견 드려 봅니다 🙇 

검토 부탁 드리겠습니다 😄

2020-11-03 13:11 UTC, neojjc2 commented on src/main/java/racinggame/domain/Car.java
>    private int racingPosition;
racingPosition을 하나의 도메인으로 분리해보는 건 어떨까요?? 😄

2020-11-03 13:11 UTC, neojjc2 commented on src/main/java/racinggame/domain/Car.java
> +    return Objects.equals(carName, car.carName);
👍

2020-11-05 03:55 UTC, neojjc2 approved these changes
안녕하세요 승완님 🙇 

요청 사항 반영 잘 해주셨습니다 💯 

그래도 코드가 많이 개선 된 것 같아서 보기 좋습니다
이만하면 미션에서 요구되는 사항들은 충분히 달성하신 것 같습니다 😄 

저와는 이제 마지막 이겠지만 😭 
미션 진행 하시면서 궁금 하셨던 부분이나, 개선하고 싶은 부분 그리고 이외에 다른 것들 있으시면
언제든 DM 주세요 🙇 

미션 진행하시느라 정말 수고 많으셨습니다 
이번 미션에서 하셨던 내용들 한번 정리하시고 
다음 미션 시작하시면 좋을 것 같습니다  

그럼 완주 하실 때 까지 응원하겠습니다 🔥  
수고 많으셨습니다 🙇 

이만 merge 하겠습니다 🚗

2020-11-05 03:55 UTC, neojjc2 commented on src/main/java/racinggame/CarRacing.java
> +    this.racingCars = new RacingCars(racingInfo.getRacingCarNames(), new RandomMoveRule());
`CarRacing` 시작 (생성) 될 때, 외부에서 Racing rule에 대해 선택할 수 있게 하면 더 좋을 것 같습니다 😄

2020-11-05 03:55 UTC, neojjc2 commented on src/main/java/racinggame/README.md
> +6. 우승자 판단로직 개발
히스토리 정리 👍

2020-11-05 03:55 UTC, neojjc2 commented on src/main/java/racinggame/domain/Car.java
> +  public static Car newInstanceByCarName(String carName) {
요청사항 반영 👍

2020-11-05 03:55 UTC, neojjc2 commented on src/main/java/racinggame/domain/model/RacingCars.java
> +        .map(racingCarName -> Car.of(racingCarName, moveRule))
👍

2020-11-05 03:55 UTC, neojjc2 commented on src/main/java/racinggame/vo/CarSateInRace.java
> +  public boolean isSamePosition(CarSateInRace otherCarSateInRace) {
객체에 역할 위임 👍

2020-11-05 03:57 UTC, merged