Step2
next-step/java-racingcar pull request #1426
Opened 2020-11-03 16:52 UTC by dudu0166

문자열 계산기 요구사항 완료했습니다!

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Main.java
> +
의미가 없는 개행은 제거해주세요~!

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/operator/Addition.java
> +        return x+y;
```suggestion
        return x + y;
```
연산자 사이에 공백이 있으면 가독성이 좀 더 확보될 거 같아요~!

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/operator/Division.java
> +        return x/y;
0 으로 나눴을 때에 대한 예외처리가 필요할 것 같아요.

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/operator/Operator.java
> +    Long action(Long x, Long y);
primitive 타입이 아닌 wrapper 타입으로 정의하신 이유가 있을까요~?

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +public class Calculator {
파라미터, 지역 변수 등 변수 이름으로 축약어 사용은 지양해주세요~!

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +            throw new IllegalArgumentException("입력된 값에 오류가 있습니다.");
문자열은 하드 코딩하지 않고 상수로 관리해보는 것은 어떨까요~?
가독성이 확보되고 관리에도 좀 더 용이할 거 같아요.

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +    static public Operator getOperator(String in) throws IllegalArgumentException{
operator 와 같이 그룹화 시킬 수 있는 도메인은 enum 으로 따로 빼서 관리해보는 것은 어떨까요~?

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +        for(int i =1; i<items.length; i = i+2){
```suggestion
        for(int i = 1; i < items.length; i = i + 2){
```
for 문 컨벤션 맞춰주세요~!

IDE 에서 제공하는 reformat 기능을 이용하시면 권장되는 컨벤션을 일괄적으로 적용할 수 있습니다 :)

2020-11-04 09:51 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +        String[] items = StringUtil.split(expr, " ");
공백을 기준으로 연산자와 피연산자를 나누는 것은 일부 케이스만 커버 가능할 것 같아요.
예를 들어 2+ 3 -5 와 같이 들어오면 제대로 split 이 안되지 않을까요~? 
space 여부와 상관없이 연산식을 계산할 수 있도록 바꿔볼 수 있을까요?

2020-11-04 09:53 UTC, vagabond95 requested changes
요구 사항에 맞게 계산기 구현 잘해주셨습니다 👍 

구현 내용에 대하여 몇가지 코멘트 남겼는데요, 확인 후 수정 부탁드릴게요!
코멘트를 적용하다보면 몇개의 로직은 새로운 클래스로 이동될 수 있는데요, 클래스가 분리되면 그에 맞게 테스트도 분리해서 작성해주시면 더 좋을 것 같습니다 :)

리뷰 내용 중 궁금하거나 논의하고 싶은 부분 있으시면 편하게 DM 주세요!

2020-11-05 14:47 UTC, dudu0166 commented on src/main/java/calculator/operator/Operator.java
> +    Long action(Long x, Long y);
특별한 이유는 없습니다 ㅎㅎ 오랜만에 자바로 개발하는 거라서 헷갈렸습니다!

2020-11-06 05:36 UTC, vagabond95 approved these changes
코멘트 내용 잘 반영해주셨네요 👍 👍 

3단계 진행해주세요~!

2020-11-06 05:36 UTC, vagabond95 commented on src/main/java/calculator/Calculator.java
> +                .filter(x->!x.isEmpty())
```suggestion
                .filter(x- > !x.isEmpty())
```
다음과 같은 space 컨벤션은 IDE 의 **reformat** 기능을 활용하시면 일괄적으로 적용이 가능합니다. ㅎㅎ

2020-11-06 05:37 UTC, merged