[3단계] - 자동차 경주
next-step/java-racingcar pull request #1437
Opened 2020-11-05 04:00 UTC by devyoon91

**자동차 경주**
--

**Car Racing Package**
![](https://i.ibb.co/frh181t/image.png)

> 꼼꼼한 리뷰 부탁드립니다 ! 🤗

**기능 요구사항**

- 초간단 자동차 경주 게임을 구현한다.
- 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
- 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.

<br>

**실행결과**

![](https://i.ibb.co/SJTBtGR/image.png)

<br>

**프로그래밍 요구사항**

- **모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외**
  - 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
  - UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.
- **자바 코드 컨벤션을 지키면서 프로그래밍한다.**
- **else 예약어를 쓰지 않는다.**
  - 힌트: if 조건절에서 값을 return하는 방식으로 구현하면 else를 사용하지 않아도 된다.
  - else를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.

**기능 목록 및 commit 로그 요구사항**

- 기능을 구현하기 전에 README.md 파일에 구현할 기능 목록을 정리해 추가한다.
- git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.
  - 참고문서: `AngularJS Commit Message Conventions`

**참조**

- [자바 코드 컨벤션 #1](https://google.github.io/styleguide/javaguide.html)
- [자바 코드 컨벤션 #2](https://myeonguni.tistory.com/1596)
- [AngularJS Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
```
  feat (feature)
  fix (bug fix)
  docs (documentation)
  style (formatting, missing semi colons, …)
  refactor
  test (when adding missing tests)
  chore (maintain)
```

2020-11-05 16:36 UTC, slamdunk7575 requested changes
안녕하세요 😊 병윤님.

열심히 자동차 경주 미션 수행하셨네요 👍

몇가지 고민해볼 부분이 있어 피드백 남기고 Request Changes 드렸습니다.

- List를 Wrapping 하여 일급 컬렉션으로 만들어보면 어떤 장점이 있을까요?
꼭 제가 피드백 드린 부분 말고도 병윤님이 생각하시는 부분에 자유롭게 적용해보시고 장점을 찾아보시면 좋겠습니다.

- Random 값에 대한 테스트를 어떻게 하는게 좋을까요?
인터페이스 기반으로 전략을 바꿔가며 테스트 하기 쉬운 부분과 어려운 부분을 나누고 적용해보세요.

- 비지니스 로직과 UI로직은 분리해주세요.

위의 피드백 중점으로 고민해보시고 궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥

리팩토링 해보시고 PR 부탁드립니다~🚗🚗🚗 끝까지 화이팅 입니다!

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/Grid.java
> +            raceRecording.add("\n");
비즈니스 로직과 UI 로직은 분리 해주세요! 😄

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/Grid.java
> +    private List<Car> statingGrid;
`List<Car>`를 Wrapping한 일급컬렉션 Cars를 만들면 어떠한 장점이 있을까요? 🤔 

꼭 제가 피드백 드린 부분 말고도 창권님이 생각하시는 부분에 자유롭게 적용해보시고 장점을 찾아 보시길 바랍니다.

[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)
[일급 컬렉션을 사용하는 이유](https://woowacourse.github.io/javable/2020-05-08/First-Class-Collection)

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/Grid.java
> +    private final LinkedList<String> raceRecording;
경기 기록을 관리하는 RacingRecord 클래스를 만들어 보면 어떨까요?

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/Grid.java
> +        while(round <= rounds) {
while문 내에서 Stream을 사용하고 있네요 🤔

어떻게 깔끔하게 리팩토링 해볼 수 있을까요?

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/ResultView.java
> +    public void play(Grid grid) {
경기 결과를 보여준다는 네이밍으로 바꿔보는건 어떨까요?

2020-11-05 16:36 UTC, slamdunk7575 commented on src/main/java/racing/domain/Grid.java
> +    public List<Car> getStartingGrid() {
테스트 용도로 만드신거면 제거하는 편이 좋겠네요. 😃

2020-11-05 16:36 UTC, slamdunk7575 commented on src/test/java/racing/CarTest.java
> +            car.move();
위에서 피드백 드린 내용을 토대로 Random 값에 대한 테스트를 고민해보시면 좋을것 같아요 😄

2020-11-07 15:22 UTC, slamdunk7575 requested changes
안녕하세요 😊 병윤님.

피드백 반영 잘해주셨네요 👍

다음 미션을 진행하기 전에 몇가지 피드백을 반영하시면
원할하게 미션을 수행하실 수 있을 것 같아 Request changes 하였습니다!

- Random() 값 테스트에 대한 설명을 추가했습니다. 조금 더 고민해보셨으면 좋겠어요.
- 각 Labs의 결과를 관리하는 RacingResult 객체를 만들고 리턴해보면 어떨까요.

위의 피드백 중점으로 고민해보시고 궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥

리팩토링 해보시고 다시 리뷰요청 부탁드립니다~ 🚗  끝까지 화이팅 입니다!

2020-11-08 06:17 UTC, devyoon91 commented on src/main/java/racing/domain/Car.java
> +    private final String name;
사실 마지막 출력 테스트 할때 테스트용도로 넣어둔건데 ㅎㅎ; 일부로 빼지는 않았습니다

2020-11-08 09:02 UTC, slamdunk7575 commented
피드백 반영하느라 고생하셨습니다 👍 
이전보다 구조가 훨씬 좋아졌네요.

`모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외`
RaceResult에 대한 테스트도 있으면 좋겠네요.

현재 테스트 코드가 많이 부족한 상태입니다. 다음 미션을 진행하시기 전에 
테스트 코드부터 추가하시고 작업하시면 좋을것 같아요 😄

2020-11-08 09:10 UTC, slamdunk7575 approved these changes
안녕하세요 😊 병윤님.

피드백 반영하느라 고생하셨습니다. 처음보다 구조가 훨씬 좋아졌네요👍

3단계 이만 머지하도록 하겠습니다!

현재 테스트 코드가 부족한 상태입니다. 다음 미션 진행하시기 전에
테스트 코드부터 반영하시고 작업하시면 좋을것 같아요 😄

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥
끝까지 화이팅 입니다! 🚗 🚗 🚗

2020-11-08 09:11 UTC, merged