Step4
next-step/java-racingcar pull request #1454
Opened 2020-11-06 18:38 UTC by changgunyee

2020-11-07 18:25 UTC, slamdunk7575 commented
- 테스트 코드에 대한 답변은 피드백에 추가했습니다.

- 창권님이 어떤 책이 맞으실지 모르겠어서 제가 알고 있는 테스트 관련 좋은 책과 강의를 추천드리겠습니다.

[TDD 실천법과 도구](https://repo.yona.io/doortts/blog/issue/1)
[더 자바, 애플리케이션을 테스트하는 다양한 방법](https://www.inflearn.com/course/the-java-application-test)
테스트 주도 개발(인사이트)

2020-11-07 18:29 UTC, slamdunk7575 requested changes
안녕하세요 😊  창권님.

전반적으로 구조가 잘 잡혀있어 어렵지 않게 우승자 구하는 로직을 추가하셨네요.

조금 더 고민해볼 부분이 있어 피드백과 함께 Request changes 드렸습니다.

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥

리팩토링 해보시고 다시 리뷰요청 부탁드립니다~ 🚗  끝까지 화이팅 입니다!

2020-11-08 08:21 UTC, slamdunk7575 commented
테스트 코드에서 containsExactly() 사용에 있어서 

클래스에 equals(), hashCode() 메소드 재정의에 대해서 고민해보시면 좋을거 같다는 것은

TDD로 객체지향 프로그래밍을 한다고 했을때 객체에서 값을 꺼내서 비교하는 것이 아니라 
객체 자체를 비교하는 것을 말씀드릴려고 했습니다. 아마 포비님이 강의에서도 말씀하실꺼에요 😄 

예를들어, CarsTest 내에서 자동차 생서에 대한 테스트를 작성 한다고 했을때 
equals(), hashCode() 메소드를 재정의 하지 않은면 테스트는 깨지고 말것입니다.

```
   @DisplayName("Car 생성 테스트")
    @Test
    void car_create_test() {

        // given
        List<String> names = Arrays.asList("pobi", "crong", "honux");

        // when
        Cars cars = new Cars(names);

        // then
        assertThat(cars.getCarList().size()).isEqualTo(3);
        assertThat(cars.getCarList()).containsExactly(new Car("pobi"), new Car("crong"), new Car("honux"));

    }
```

2020-11-08 17:32 UTC, slamdunk7575 approved these changes
피드백 반영 잘 해주셨네요. 💯
소소한 코멘트 남겨드렸으니 다음 미션에 반영해보시면 좋을것 같네요.

마지막 미션은 MVC 형태로의 리팩토링인데
지금 구조가 이미 요구사항을 많은 부분 만족하고 있다고 생각해요.

전반적인 구조에 대해서 고민해보시고 PR 주시면 될 것 같아요.
궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥

미션 마무리까지 얼마 남지 않으셨네요~🏎️  끝까지 화이팅 입니다!

2020-11-08 17:32 UTC, slamdunk7575 commented on src/main/java/racingcar/GameManager.java
> +        return gameRounds.getRecords();
잘 분리해주셨네요 👍

2020-11-08 17:32 UTC, slamdunk7575 commented on src/main/java/racingcar/RacingGame.java
> +        }
따로 분리하신 이유가 있을까요? 🤔 

크게 분리할 이유가 없을듯 해서 여쭤봤습니다.

2020-11-08 17:32 UTC, slamdunk7575 commented on src/test/java/racingcar/GameManagerTest.java
> +    }
적용해보셨군요 😄

2020-11-08 17:33 UTC, merged

2020-11-09 15:38 UTC, changgunyee commented on src/main/java/racingcar/RacingGame.java
> +        }
자동차 최대 이름 수로 오류가 날 때, 오류를 print해주려고 넣었습니다!