Step4
next-step/java-racingcar pull request #1497
Opened 2020-11-10 15:22 UTC by hoonick91

리뷰어님 안녕하세요

지난번에 주신 피드백 감사합니다.

특히나 전략패턴을 테스트에 이렇게 이용하는 지 알게되어 너무 뿌듯합니다.

다시 한번 수고 부탁드립니다.

2020-11-11 12:57 UTC, sah3122 requested changes
요구사항 구현 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었으니 확인해주세요 😄

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/MainSimulator.java
> +        List<Car> cars = carsGenerator.generateCars(carName);
Main 함수에서 Cars를 생성하는것 보다 Cars를 사용하는 클래스에서 생성한다면 응집도를 높일 수 있지 않을까요 ? 
객체 생성은 객체를 사용하는 곳에서 생성하는것이 불필요한 Coupling을 없앨수 있다고 생각해요 😄

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/CarsGenerator.java
>  public class CarsGenerator {
`CarsGenerator`는 자동차 객체 생성을 맡고 있는 클래스 인것 같아요. 
개인적으로는 이와 같이 특정 기능을 도와주는 Util 클래스를 선호하지 않아요. 중요한 도메인의 책임이 분산되는것과 불필요한 의존성이 생기게 되기때문이죠. 
`RacingSimulator`에게 자동차를 생성하는 책임을 위임하는것은 어떻게 생각하시나요 ? 
`RacingSimulator`는 자동차 경주의 실행을 맡고 있는 클래스이니 자동차 객체를 생성하는 역할이 부자연스럽지 않을것 같아요.

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/CarsGenerator.java
> +    String blank = " ";
static final 과 default 접근 제어자의 차이점을 알아보세요 !

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/CarsGenerator.java
> +    private void validateName(String name) {
다른 개발자가 `CarsGenerator`의 존재를 모르고 new Car("racingCar", 0); 와 같이 객체를 선언 한다면 어떤 문제점이 발생할까요 ? 
상태값의 유효성 검사는 반드시 도메인 객체의 생성자에서 검증해야 합니다 !

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/RacingSimulator.java
> +        int maxDistance = winner.get().getDistance();
```java
int maxDistance = cars.stream()
                .mapToInt(Car::getDistance)
                .max()
                .orElseThrow(IllegalArgumentException::new);
```
위와 같이도 최댓값을 구할수 있겠네요 😄

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/RacingSimulator.java
> +                .filter(car -> car.getDistance() == maxDistance)
객체에게 메시지를 던진다 라는 이야기를 알고 계시나요 ?
Car 객체에게 메시지를 던지도록 변경해보세요 👍

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/RacingSimulator.java
> +            resultView.printDistanceOfCar(cars);
도메인 객체와 UI클래스를 분리해보세요.

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/number/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements NumberGenerator {
전략 패턴으로 구현 잘해주셨네요 👍 
추가적으로 전략에서 특정 값을 전달 하는 방법도 있지만 **행위**자체를 전략으로 만드는 방법도 있습니다 👍 
```java
public class RandomMovingStrategy implements MovingStrategy {
    private static final int RANDOM_BOUND = 10;
    private static final int MOVABLE_NUMBER = 4;

    @Override
    public boolean isMovable() {
        return new Random().nextInt(RANDOM_BOUND) >= MOVABLE_NUMBER;
    }
}
```

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/number/NumberGenerator.java
> +public interface NumberGenerator {
메소드가 하나만 있는 인터페이스를 **FunctionalInterface**라고 합니다. 
찾아보고 활용법을 공부해보세요 !

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/application/number/NotMovableNumberGenerator.java
> +public class NotMovableNumberGenerator implements NumberGenerator {
테스트 코드에서 사용하기 위해 선언 잘해주셨네요 👍 
테스트를 위한 코드는 메인 패키지가 아닌 테스트 패키지에 존재하는것을 권장 드려요 !

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/domain/Car.java
> +        final int FORWARD_CRITERION = 4;
상수는 static 영역에 선언하여 불필요한 메모리 낭비를 줄여 보세요.

2020-11-11 12:57 UTC, sah3122 commented on src/main/java/racingcar/view/ResultView.java
>              System.out.print("-");
StringBuilder 와 StringBuffer를 알아보고 활용해보세요 !

2020-11-14 14:17 UTC, hoonick91 commented on src/main/java/racingcar/application/CarsGenerator.java
>  public class CarsGenerator {
처음에 자동차를 생성하는 부분을 따로 두어, RacingGame을 진행하는 객체는 그 책임만 지도록 분리해야겠다고 생각했습니다.
근데, 주신 의견을 읽고 생각해보니 RacingSimulator의 책임이 많이 않아 위임하는 것도 좋다고 생각했습니다.

추후 RacingSimulator의 책임이 많아지면, 그때는 분리하는게 어떨까 ❓  합니다

2020-11-15 07:18 UTC, sah3122 approved these changes
피드백을 잘 반영해주셨네요 👍 
일급 컬렉션과 불변 객체를 사용하여 기존에 존재하던 문제점들을 멋있게 보완해주셧네요 💯 
간단한 피드백 한가지 남겨두었는데 다음 미션을 진행하며 도전해보세요 !

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/domain/car/Name.java
> +public class Name {
자동차 이름을 불변 객체로 정의해주셨네요 👍 
아래 문서를 통해 불변 클래스에 대해 조금더 알아보세요 !
https://meetup.toast.com/posts/217

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/view/InputView.java
>          Scanner scanner = new Scanner(System.in);
Scanner 객체를 매번 생성하지 않고 사용할수 있는 방법을 고민해봐요.

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/MainSimulator.java
> +        }
입력받은 횟수 만큼 자동차 경주를 실행하는 로직은 Main 함수가 아닌 RacingGame 객체가 담당해야하는 책임이지 않을까요 ?

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/MainSimulator.java
>      public static void main(String[] args) {
Main함수에서 너무 많은 역할을 하고 있는것 같아요. 
main에서는 자동차 경주에 필요한 값을 입력 받고, RacingGame 에게 자동차 경주를 실행하라는 메시지를 던지고, 
자동차 경주의 결과값을 ResultView로 전달해주는 정도면 되지 않을까요  ?

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/domain/car/Cars.java
> +public class Cars {
자동차들을 일급 컬렉션으로 묶어 주셨네요 👍 
아래 문서를 통해 일급 컬렉션에 대해 조금더 알아보세요 ! 
https://jojoldu.tistory.com/412

2020-11-15 07:18 UTC, sah3122 commented on src/test/java/racingcar/domain/NameTest.java
> +}
파일의 마지막은 new line으로 끝나는 것을 권장드려요. 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2020-11-15 07:18 UTC, sah3122 commented on src/main/java/racingcar/application/CarsGenerator.java
>  public class CarsGenerator {
좋은 의견인것 같습니다 !
한가지 주의할 점은 객체 생성을 위임 하더라도 항상 완벽한 상태로 객체가 생성 될 수 있도록 중요한 요구사항이나 유효성 검사는 
객체의 생성자에서 처리해야할것 같아요 !

2020-11-15 07:18 UTC, merged