4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #1499
Opened 2020-11-10 16:26 UTC by joongs

### 제목
4단계 - 자동차 경주(우승자)

### 작업내용
- [x] 경주할 자동차의 이름을 입력받는다. - InputView(이름은 최대 5자, 쉼표로 구분) (`step4 new`)
- [x] 자동차를 이동한다. (자동차 이름 포함) (`step4 new`)
- [x] 자동차 경주 완료 후 우승자동차 이름 출력한다. (`step4 new`)
- [x] new Random().nextInt(10) 은 매번 method가 호출 될 때 마다 초기화 안되게 개선 (`step3 feedback`)
- [x] createRacingCars() 함수는 RacingGame의 역할로 개선 (`step3 feedback`)
- [x] ResultView만 담당하는 객체를 하나 생성 추가 (`step3 feedback`)
- [x] 움직임(RacingCarMoveBehavior)의 상태를 RacingCar가 가지고 있을 필요가 있을 까요?? 생성 시점이 아닌 움직이는 시점에 전략이 반영되면 어떨까요?? (`step3 feedback`)

### 학습내용
4단계 - 자동차 경주(우승자)](https://edu.nextstep.camp/s/MNii0Puk/ls/99e57MsX)

### 참고 
[junit - parameterized](https://www.baeldung.com/parameterized-tests-junit-5)
[assertj 활용](https://www.baeldung.com/introduction-to-assertj)

### 한줄일기
기능은 만들어지는데, 테스트케이스는 잘 만들어지 지지 않는다. (csv 형식으로 하는데 string array는 입력할 방법이 없는걸까?)

2020-11-10 16:26 UTC, joongs commented on src/main/java/racingcar/RacingCarBehavior.java
> +    private Random random = new Random();
Ramdom에 대해서 함수 실행이 아니라 클래스 변수로 가지고 있는 방법을 했습니다.

2020-11-10 16:30 UTC, joongs commented on src/test/java/racingcar/TestRacingCarGame.java
> +    @CsvSource({"AAA,2", "BBBB,3", "CCCCC,4"})
`CvsSource`를 가지고는 String 값으로 입력받는 자동차들에 대해서 표현을 할수가 없는것 같습니다.

` @CsvSource("AAA,BBB,CCC,2")` 여기서 "AAA,BBB,CCC"까지가 하나의 문자열로 처리를 해야하는데요. `CvsSource`로는 해당 부분을 처리가 안되는것 같습니다.
이부분이 제대로 처리가 안되서 아래 testcase들에서도 의도된 test를 만들지 못하고 있습니다.

2020-11-11 01:33 UTC, neojjc2 commented
#tag @neojjc2

2020-11-11 02:25 UTC, neojjc2 requested changes
안녕하세요 세중님 🙇 

4단계 구현도 잘해주셨습니다 💯 

몇 가지 개선사항에 대해 의견 드렸습니다 🙇 
검토해 주시고 다시 리뷰 요청 부탁 드립니다 😄 

화이팅 입니다 🔥

2020-11-11 02:25 UTC, neojjc2 commented on src/test/java/racingcar/TestRacingCarGroups.java
> +    @DisplayName("승자 찾기 - Q 랜덤으로 결과가 바뀌기 때문에 test 케이스 assert문을 어떻게 작성해야 할까요?")
Test sub 이라는 방법이 있습니다 
> https://medium.com/@SlackBeck/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%8A%A4%ED%85%81-test-stub-%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80-ff9c8840c1b0

관련 내용 개념 한번 파악하시고 😄 
쉽게 말씀 드려 예상한 결과 (만들어진 결과) 를 항상 반환하는 객체를 만들어 테스트 하는 방법입니다 

세중님이 여기에서 테스트를 하시는 방법은 
승자를 찾는 부분입니다 

그럼 항상 직진한다고 가정할 때와 
아무도 직진하지 않았다고 가정하고 입력 값에 따른 승자 결과가 잘 나오는지 확인해보면 됩니다 
(다시한번 정리 드리자면 **승자를 찾는 부분이 테스트 범위**지 직진 혹은 모두가 정지하는 내용은 테스트 범위가 아닙니다) 

항상 직진하는 전략을 하나 생성합니다 
```
public class AlwaysGoBehavior implements RacingCarMoveBehavior {
    @Override
    public int action(int currentDistance) {
        return 1;
    }
}
```
그리고 해당 전략을 사용하는 RacingCarGroups을 생성합니다
단 해당 기능 이외에 다른 기능은 변경이 없어야 하므로 상속 받아 생성합니다 

```
import java.util.List;

public class AlwaysRacingCarGroups extends RacingCarGroups {
    public AlwaysRacingCarGroups(List<RacingCar> racingCars) {
        super(racingCars);
    }
    
    @Override
    public void move() {
        for(int i = 0; i < racingCars.size(); i++) {
            racingCars.get(i).move(new AlwaysGoBehavior());
        }
    }
}
```

그리고 AlwaysRacingCarGroups을 이용하면 
항상 참가한 모든 차들은 1씩 움직입니다
그러므로 모두가 승자가 되면 테스트가 통과 입니다 😄 

이런 방법도 있으니 한번 검토 부탁 드립니다 🙇

2020-11-11 02:25 UTC, neojjc2 commented on src/main/java/racingcar/RacingCar.java
> +    public List<String> isWinner(List<String> winners, int condition) {
RacingCar에서 우승을 판단하는 부분이 좀 어색합니다 😄 

그냥 우리가 레이싱 게임을 한번 관람한다고 가정해볼까요?? 😅 
예를 들어 총 5바퀴를 돌고 
각 라운드 마다 LAP이 기록 됩니다 
각 라운드마다 순위도 달라질 수 있습니다 

만약에 **매 라운드 마다 그 때의 승자도 알고 싶다** 라는 요구사항이 생긴다면 
어떻게 될까요??  🤔 

`경기 결과` 에서 확인해야 할 부분들이 RacingCar와 RacingCarGroups에 각각 나뉘어져 있는 모습입니다 
(`경기 결과`와 경기 결과 출력은 별개로 보셔야 합니다 경기 결과 출력은 이미 잘 만들어놓으셨습니다 👍)

어떻게 개선하면 좋을지 고민 부탁 드리겠습니다 
그렇게 개선하시면 테스트 코드 작성하는 부분도 많이 간편해질 것 같습니다 😅 🙇

2020-11-11 02:25 UTC, neojjc2 commented on src/main/java/racingcar/RacingCarBehavior.java
> +    private Random random = new Random();
리팩토링 👍 

private final과 private static final에 대한 부분도 같이 정리하고 가시면 좋을 것 같습니다 😄 
`private static final Random RANDOM = new Random();`

> https://djkeh.github.io/articles/Why-should-final-member-variables-be-conventionally-static-in-Java-kor/

2020-11-11 02:25 UTC, neojjc2 commented on src/main/java/racingcar/RacingCarGame.java
> +        return racingCars;
두 가지 의견을 드리고 싶습니다 😄 
1. 이 부분에서 `RacingCarGroups`을 반환하면 어떨까요??
2. 아예 RacingCarGames를 생성할 때 carNames를 받게 하면 이 부분이 외부로 노출되지는 않을 것 같습니다 

의견 검토 부탁 드립니다 🙇  

참고로 `RacingCarGroups`를 반환하게 한다면 람다식으로 개선해볼 수 있습니다 
이부분은 참고만 부탁 드립니다 (람다를 특훈하시게 될겁니다 😅)

```
public static RacingCarGroups createRacingCarsUsingLambda(String carNames) {
        return Arrays.stream(carNames.split(","))
                .map(String::trim)
                .map(RacingCar::new)
                .collect(Collectors
                        .collectingAndThen(Collectors.toList(),
                                RacingCarGroups::new));
    }
```

2020-11-11 02:25 UTC, neojjc2 commented on src/main/java/racingcar/RacingCar.java
> +        this.name = name;
**각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.** 부분이 누락된 것 같습니다 😄 
확인 부탁 드리겠습니다 🙇

2020-11-11 02:25 UTC, neojjc2 commented on src/main/java/racingcar/InputView.java
> +        Scanner scanner = new Scanner(System.in);
이 부분도 반복적으로 생성하고 있습니다 😅 
개선 부탁 드립니다 🙇

2020-11-11 15:23 UTC, joongs commented on src/main/java/racingcar/RacingCarBehavior.java
> +    private Random random = new Random();
리뷰 해주신거와 링크 주신거 읽어보니  아래와 같이 개선이 필요하네요.

* static final 로 상수를 처리 하는 것에 대해서 확인했습니다. 👍 
* final로 DI를 하는 부분도 잘 봤습니다. 👍 

기존 | 개선
-- | --
`private final int MOVING_CONDITION = 4;` | `private static final int MOVING_CONDITION = 4;`
`private Random random = new Random();` | `private static final Random random = new Random();`

이걸로 개선해보겠습니다.

2020-11-11 15:39 UTC, joongs commented on src/test/java/racingcar/TestRacingCarGame.java
> +    @CsvSource({"AAA,2", "BBBB,3", "CCCCC,4"})
`delimiter = ':'` 로 분리할 수 있었습니다. 
피드백 감사드립니다. 👍

2020-11-11 16:02 UTC, joongs commented on src/test/java/racingcar/TestRacingCar.java
> +    void test_is_winner(int condition, String result) {
`winner test case`를 작성할 수 없는 이유는 아래에 있었습니다.
- `RacingCar`의 distance를 외부 입력으로 초기화를 할 수 가 없었습니다.

해당부분 반영해서 추가해보겠습니다.

2020-11-11 16:15 UTC, joongs commented on src/main/java/racingcar/ResultView.java
> +        System.out.print(racingCar.getName() + " : ");
쓰레드와 관련은 없으니, 이번엔 `StringBuilder`를 사용해서 개선해보겠습니다. 👍

2020-11-11 16:29 UTC, joongs commented on src/main/java/racingcar/RacingCar.java
> +        this.name = name;
네 해당건 추가하겠습니다. 👍

2020-11-11 16:34 UTC, joongs commented on src/main/java/racingcar/InputView.java
> +        Scanner scanner = new Scanner(System.in);
`public static final Scanner scanner = new Scanner(System.in);`처리해서 사용겠습니다.

2020-11-11 16:55 UTC, joongs commented on src/main/java/racingcar/RacingCarGame.java
> +        return racingCars;
> 이 부분에서 RacingCarGroups을 반환하면 어떨까요??
앗 그렇네요, 이렇게 하면 new를 할 필요도없어지네요. 👍 

> 아예 RacingCarGames를 생성할 때 carNames를 받게 하면 이 부분이 외부로 노출되지는 않을 것 같습니다
racing car games에는 carNames만 넘기면 되겠군요 👍 

> 람다식 특훈
제가 이부분은 생소해서 기대가 됩니다. 👍

2020-11-11 17:01 UTC, joongs commented on src/main/java/racingcar/RacingCar.java
> +    public List<String> isWinner(List<String> winners, int condition) {
네 이부분은 추가로 의견주신것처럼 고민해보고 개선해보겠습니다. 👍

2020-11-13 14:53 UTC, joongs commented on src/test/java/racingcar/TestRacingCarGroups.java
> +    @DisplayName("승자 찾기 - Q 랜덤으로 결과가 바뀌기 때문에 test 케이스 assert문을 어떻게 작성해야 할까요?")
@neojjc2님,
해당방법에 대해서 의견 감사드립니다.
이렇게 하는 방법도 있군요 👍 

이번에 제가 고민했던 방식은 결과지를 준비한 작업은 동일합니다.
다만 setUp()에서 미리 준비를 해두고 사용하는 방법으로 해봤습니다.

의견주신건도 테스트를 할 때 엄청 훌륭한 방법인것 같습니다. 👍 
이 방법도 고려해보겠습니다.

2020-11-13 15:01 UTC, joongs commented on src/main/java/racingcar/RacingCarGroups.java
> +    private int getMaxDistance() {
`private` 메소드는 테스트를 케이스를 만들지 않아도 될까요?

2020-11-13 15:03 UTC, joongs commented on src/main/java/racingcar/RacingCarGroups.java
> +    public List<String> findWinners() {
`RacingCarGame`에게 `winner`를 찾는 역할을 위임해줬습니다.
그런데 이와 관련된 메소드들이 여러개가 추가가 되었습니다.
이방향이에 대해서 맞는것인가에 대해서 고민이 됩니다.

2020-11-13 15:04 UTC, joongs commented on src/test/java/racingcar/TestRacingCarGroups.java
> +    void setUp() {
해당방법을 통해서 `RacingGame`의 결과를 결정하고 여기서 우승자를 찾게 해봤습니다.
그런데 move를 추가로 한게 아니어서 부족한 test가 된것같습니다.

2020-11-14 15:10 UTC, neojjc2 approved these changes
안녕하세요 세중님 🙇 

요구사항 반영해주시느라 너무 고생 많으셨습니다 💯 

많은 고민이 느껴져서 참 좋았습니다  
한결 정리 되고 개선된 느낌이 듭니다 👍 
이정도면 마지막 단계 진행하셔도 될 것 같습니다 💯 
이만 merge 하겠습니다 🥇 

이제 마지막 단계네요
거의 다 왔습니다
조금만 더 힘내주세요 🔥

2020-11-14 15:10 UTC, neojjc2 commented on src/main/java/racingcar/RacingCarGroups.java
> +    private int getMaxDistance() {
이 부분은 두가지 의견을 드리고 싶습니다 
하나는 private method 들을 별도의 객체로 분리하고 
테스트에서는 분리한 객체를 테스트 하는 방법이 있을 수 있을 것 같습니다
물론 이 부분에서는 별도로 분리한 객체를 통해 maxDistnace를 구하도록 수정해야겠지요 😅 

또 다른 방법은 해당 private method를 사용하는 public method를 테스트하면서 다른 변화 요인을 통제하고 
private method만 테스트 될 수 있도록 하는 방법이 있을 것 같습니다 😄 

근데 이미 제가 의견 드린 두번째 방법으로 충분히 테스트 하신것 같네요 🙇 
상황에 따라서 적절히 판단하시면 될 것 같습니다

2020-11-14 15:10 UTC, neojjc2 commented on src/test/java/racingcar/TestRacingCarGroups.java
> +    void setUp() {
아닙니다 잘하셨습니다 💯 
테스트는 given, when, then 입니다 
여기서는 우승자를 제대로 찾는가에 대한 테스트 입니다 
move는 given의 영역입니다 
테스트를 하기위해 상황을 제공하는것을 꼭 move를 통하지 않아도 됩니다
move는 잘 move가 되는지에서 테스트 되면 됩니다 

항상 테스트 하실 때는 테스트 범위를 잘 정하는게 중요합니다 
이미 범위를 잘 정하셨고 그 테스트를 위한 given을 잘 주셨습니다 💯

2020-11-14 15:11 UTC, merged

2020-11-14 15:19 UTC, joongs commented on src/main/java/racingcar/RacingCar.java
> +    public RacingCar(String name, int distance) {
`if (name.trim().length() > 5) `
--> private final static MAX_NAME_LENGTH = 5`로 개선으로 마지막 미션때 정리해보겠습니다.

2020-11-14 15:21 UTC, joongs commented on src/main/java/racingcar/RacingCarBehavior.java
> +    private static final Random random = new Random();
`private static final Random random = new Random();` --> `private static final Random RANDOM = new Random();` 으로 개선해야되겠네요 😄

2020-11-14 15:25 UTC, joongs commented
@neojjc2 님께서, 훌륭한 리뷰를 해주셔서 자동차 게임의 코드 질이 달라지고 있는것을 배웠습니다.
`좋은 리뷰가 좋은 코드를 만는다.` 에 대해서 느끼게 해주셔서 감사합니다. 👍 
자동차게임 마지막미션에서 추가 의견 주신분들이 반영될 수 있도록 하겠습니다. 🙇

2020-11-14 15:29 UTC, neojjc2 commented
@joongs 아닙니다 세중님께서 너무 잘 따라와 주시고
적극적으로 개선하고 의견 반영해주시려고 해주셔서 점점 품질이 좋아지는게 느껴지니
저도 힘이나고 괜한 열정이 막 샘솟습니다 🔥 
너무 괴롭혀드린게 아닌가 고민이 되면서도 
이 참에 하나라도 더 정리하시고 가도록 도와드리는게 
제 역할이기에 😅 
함께 좋은 코드 만들어 온 것 같아서 너무 기쁩니다!!

마지막도 기대하고 있겠습니다 👍 

LGTM 👍