[Step5] 자동차 경주(리팩토링)
next-step/java-racingcar pull request #1502
Opened 2020-11-11 05:09 UTC by PeonyF

이슬님 리뷰 부탁드립니다🙏🙏

- 추가된 클래스 하는 역할
Round: Main함수에서 마지막 라운드값을 입력받아 첫라운드 부터 마지막라운드까지 진행, 마지막 라운드시 결과값 호출하는 역할

- 질문사항
Round 클래스에서 마지막 라운드 진행 후, 결과값을 ResultView에서 호출하도록 하였는데, 이부분이 domain 패키지의 객체인 Round가 view 패키지 객체인 ResultView에 의존하지 않는 구현이 맞는지 궁금합니다.

+ 도메인 로직(각 객체에 객체가 수행해야 하는 업무에 관한 로직) 에 대해 좀 더 배우게 된 계기였습니다.

2020-11-11 16:30 UTC, parkeeseul requested changes
피드백 잘 반영해주셨녜요! 👍 

몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
자동차 경주 미션이 막바지네요! 화이팅 이에요! 🔥

2020-11-11 16:30 UTC, parkeeseul commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
라운드를 진행하기 위해 별도의 클래스로 분리하기 보다는 
RacingCars 에서 담당하는게 객체의 응집도를 높여줄거 같은데
미정님의 생각은 어떠신가요? 😄

2020-11-11 16:30 UTC, parkeeseul commented on src/main/java/racingcar/domain/Round.java
> +        ResultView.printNamesOfWinnerCarsResult(racingCars.getNamesOfWinnerCars());
도메인 로직에 UI 로직이 섞여 있네요 😢 
DTO 를 통해 car의 기록을 UI 객체에 넘겨주면 어떨까요? 😄

2020-11-12 02:39 UTC, PeonyF commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
그러면 RacingCars 클래스에서 하는일이 많아지지 않을까요? 저는 클래스 별 하는일을 나열하면서 하는 역할을 생각하는편인데요, RacingCars 클래스의 경우 차들을 생성한 후 , 가장 빠른 우승자를 정한다. 즉 RacingCars에 관해서만 했습니다만, Round는 운전하는 차들 과는 조금 다른 개념이라고 판단하여 클래스를 따로 분리하였습니다.

중요도를 객체의 응집도> 클래스 분리 로 봐야 하는걸까요? 🤔🤔

2020-11-12 02:42 UTC, PeonyF commented on src/main/java/racingcar/domain/Round.java
> +        ResultView.printNamesOfWinnerCarsResult(racingCars.getNamesOfWinnerCars());
말씀하신대로 변경하였으나, 제대로 한것인지 잘 모르겠습니다. 🤔
cd15252
본래 생각은 while문 루틴또한 도메인로직이라고 생각하여 Round 클래스에 넣고 싶었는데 그러면 ResultView가 따라와서 이렇게 하는게 최선이더라구요 😢
main함수에 ResultView와 InputView만 보여지도록 하지 않아도 괜찮은건가요? 🤔

2020-11-12 13:08 UTC, parkeeseul commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
의견 감사합니다! 😄 
저의 의견을 더 추가해보자면 현재 RacingCar 는 Round 를 인스턴스 변수로 가지고 있고 Round의 progressRound 메서드는 RacingCar 를 서로 의존하고 있어서 구조가 어색해 보이는거 같은데 어떻게 생각하시나요? 🤔 
양방향 의존을 하게 되면 코드를 이해하기에 좀더 어려워 지고 또한 데이터가 분산되어 있다는 코드스멜로 볼 수도 있을거 같습니다.
한번 보시면 좋을거 같아요!
https://jojoldu.tistory.com/425

2020-11-12 13:22 UTC, parkeeseul commented on src/main/java/racingcar/domain/Round.java
> +        ResultView.printNamesOfWinnerCarsResult(racingCars.getNamesOfWinnerCars());
[MVC 패턴](https://medium.com/@jang.wangsu/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-mvc-%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80-1d74fac6e256)에 대해 한번 보시면 좋을거 같아요! 😄 
Model 은 도메인, View 는 UI, 그럼 Controller 는 여기서 main 이 될거 같아요!
즉 main 함수에서는 분리한 model과 UI 를 연결하는 역할을 하게 되겠네요!
view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현하는게 좋을 거 같아요!

2020-11-12 13:31 UTC, parkeeseul requested changes
리팩토링 열심히 진행해주셨네요! 👍 

질문 주신사항에 대한 저의 의견 남겨두었으니
확인 부탁드립니다! 
화이팅!! 🔥

2020-11-14 17:00 UTC, PeonyF commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
아하 양방향 의존관계의 문제점을 생각하지 못했어요!
클래스 분리에만 집중하다보니 의존성을 간과했네요😄
Round 클래스와 관련 테스트를 삭제하고 (ffefdf1, 32b57d0)
RacingCars 클래스와 해당 테스트에 해당 내용을 업데이트 하였습니다. (94b81f1,c59dbd3)

2020-11-14 17:02 UTC, PeonyF commented on src/main/java/racingcar/domain/Round.java
> +        ResultView.printNamesOfWinnerCarsResult(racingCars.getNamesOfWinnerCars());
말씀하신 "view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만" 의 상황이 
=> ResultView.printPositionResult(racingCars.progressRound()); 이고
"domain 패키지의 객체는 view 패키지 객체에 의존" 의 상황은 제가 이전에 코딩한 (위의 상황)
Round클래스에  ResultView.printPositionResult(cars); 를 넣은 상황이라고 이해하면 될까요? 🤔🤔

2020-11-15 10:58 UTC, parkeeseul commented on src/main/java/racingcar/domain/Round.java
> +        ResultView.printNamesOfWinnerCarsResult(racingCars.getNamesOfWinnerCars());
네!!! 정확합니다 !! 👍 😄

2020-11-15 11:44 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨습니다 ! 👍 
마지막으로 소소한 코멘트 남겨드렸는데요 한번 확인 부탁드립니다! 😄 

드디어 자동차 경주 미션을 완주하셨네요!! 축하드립니다!!! 🎉🎉🎉🎉🎉 
미션 꾸준히 진행하시기 쉽지 않으셨을텐데 피드백 잘 반영해주셔서 감사합니다 🙇 
미정님과 함께 의견 나눌 수 있어서 즐거웠고 남은 미션에서 많은 인사이트들 얻어가시길 바라겠습니다 😄 
지금 처럼 꾸준히 모든 미션 꼭 완주하시길 바랄게요!!! 남은 미션도 화이팅 입니다 ! 🔥

2020-11-15 11:44 UTC, parkeeseul commented on src/test/java/racingcar/domain/RacingCarTest.java
> +
getMaxPosition() 메서드를 사용해 maxPostion 이 맞는지 검증을 해주고 있는데요
만약 getMaxPosition의 로직이 잘못 되었다면 어떤 상황이 벌어질까요? 🤔 
잘못된 결과 값으로 검증을 하게 되겠어요 😢
결과값으로 나와야 하는 값을  변수에 직접 할당해주면 어떨까요? 

또한 제가 지난 리뷰에서 놓친 부분이 있었는데요 😢 RandomMovingTest 에서 랜덤을 테스트 하는 부분입니다.
랜덤이라는 요소는 어떠한 규칙을 가지지 않기 때문에 일반적으로 테스트하지 않는데요
 `특정 로직이 예상하는 대로 동작하는가?` 를 목적으로하는 테스트 코드의 작성 의미에서 보면 
랜덤 자체에 집중하기 보다는` 랜덤 요소를 사용하는 로직을 어떻게 구현하고 테스트해야할까?`에 대한 고민을 해보시는게 어떨까요? 😄

2020-11-15 11:44 UTC, merged