[5단계 - 자동차 경주 리팩토링]
next-step/java-racingcar pull request #1511
Opened 2020-11-12 08:47 UTC by dbeod2

마지막 미션 피드백도 잘 부탁드립니다 : )

2020-11-12 13:03 UTC, yongdae requested changes
이전 단계에서 피드백 드렸던 부분이 반영안되어있어요 😭

리팩토링은 step5 패키지를 만들어서 진행하셨는데
step5에 대한 테스트는 작성되지 않았네요 ㅜㅡㅜ

확인하시고 다시 리뷰 요청 부탁드립니다!

2020-11-12 13:17 UTC, dbeod2 commented on src/main/java/step4/RacingCarApplication.java
> +    public static void main(String[] args) {
ㅜㅜ코드가 꼬인것 같아요 수정한 부분이없는데 확인해서 다시 요청드릴게요

2020-11-12 13:18 UTC, dbeod2 commented on src/main/java/step4/RacingCarGame.java
> +    private int getRandom() {
이부분은 step5에
적용했습니다

2020-11-12 13:18 UTC, dbeod2 commented on src/main/java/step4/RacingCarGame.java
> +    private List<Car> car(String[] racingCars) {
이부분은 step5에
적용했습니다

2020-11-12 13:18 UTC, dbeod2 commented on src/main/java/step5/domain/Car.java
> +        RacingCarUi.resultPrint(cars);
이부분은 아까말씀드린부분입니다ㅜㅜ

2020-11-12 13:18 UTC, dbeod2 commented on src/main/java/step4/RacingCarGame.java
> +        resultPrint(cars);
이부분은 step5에
적용했습니다

2020-11-12 15:27 UTC, yongdae commented
유라님! 지금까지 보내주신 PR들을 확인해봤는데
rebase 하시는 부분이 뭔가 문제가 있는 것 같아요.

<img width="502" alt="Screen Shot 2020-11-13 at 12 22 29 AM" src="https://user-images.githubusercontent.com/4317804/98959366-8e48b480-2546-11eb-900f-8582177c0f1f.png">
일반적인 PR

<img width="311" alt="Screen Shot 2020-11-13 at 12 23 45 AM" src="https://user-images.githubusercontent.com/4317804/98959444-a0c2ee00-2546-11eb-949f-6cd4038bd133.png">
유라님 PR

[rebase하는 내용](https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md) 참고 한번 부탁드립니다~ 😄

2020-11-14 05:44 UTC, yongdae requested changes
안녕하세요. 유라님 ~ :)

이전 피드백 중에 반영되어야 하는 부분이 아직 남아있는 것 같아요~
해당 내용은 코멘트로 의견 드렸어요.

그 외에 의견 :
- 테스트 코드도 프로덕션 코드와 마찬가지로 패키지를 구분해서 작성해주세요.
- 커밋 메시지를 기능 단위/ 작업 단위 로 작성해주세요.

그럼 다시 리뷰 요청 부탁드립니다.!! 🔥🔥

2020-11-14 05:44 UTC, yongdae commented on src/main/java/step5/controller/RacingCarApplication.java
> +    public static void main(String[] args) {
public static void main(String[] args) 메소드를 분리해주세요.

프로그램의 진입점을 가지고 있는 클래스는 Controller 클래스가 될 수 없어요.
별도의 Main 클래스를 분리해주세요~ :)

2020-11-14 05:44 UTC, yongdae commented on src/main/java/step5/domain/RacingCarGame.java
> +    public List<Car> carMove(List<Car> cars) {
자동차 목록을 외부에서 받지 않고 RacingCarGame 클래스가 가지고 있다가 활용하게 해주세요 ~ !

2020-11-14 05:44 UTC, yongdae commented on src/main/java/step5/domain/RacingWinner.java
> +    public String toString() {
이 부분은 화면과 관련 된 내용 같아요 분리해주세요 :)

2020-11-14 06:02 UTC, dbeod2 commented on src/main/java/step5/controller/RacingCarApplication.java
> +    public static void main(String[] args) {
아하 네네! 이부분은 저도 놓치고있었네요 ㅎ

2020-11-14 06:03 UTC, dbeod2 commented on src/main/java/step5/domain/RacingWinner.java
> +    public String toString() {
넵!

2020-11-14 15:46 UTC, yongdae requested changes
유라님 수고하셨습니다!! 🙇 

커밋 메시지도 잘 작성해주셨네요. 👍 
이제 미션 종료가 얼마안남은 것 같네요. 😄 

한가지 의견 드렸습니다.
힘내주세요. 🔥🔥

2020-11-14 15:46 UTC, yongdae commented on src/main/java/step5/RacingCarMain.java
> +                .forEach(RacingCarUi::resultPrint);
RacingCarController 클래스가 게임을 진행 할 수 있게해주세요~ :)

레이싱 게임 진행에 관련 된 부분을 Main에서 진행하게 되면
레이싱 게임은 Main에 종속되게 되는 문제가 발생해요. 😭 

그리고 RacingCarController에 게임 진행 관련된 내용이 생긴다면
게임 진행과 관련된 테스트 코드도 추가가 되어야해요!

2020-11-14 23:58 UTC, dbeod2 commented on src/main/java/step5/RacingCarMain.java
> +                .forEach(RacingCarUi::resultPrint);
네네 ㅎㅎ 알겠습니다~

2020-11-15 15:59 UTC, yongdae requested changes
이전에 드렸던 피드백 내용 중 한가지 내용이
이번 피드백을 반영하시면서 원래대로 돌아온 부분이 있네요. 😭

의견 남겨놓았으니 확인 부탁드려요!
화이팅 입니다. 🔥

2020-11-15 15:59 UTC, yongdae commented on src/main/java/step5/controller/RacingCarController.java
> +    }
이 부분을 코드를 정렬해보면 아래와 같이 되요.

    public int carMove(int numberOfMove) {
        IntStream.range(0, numberOfMove)
                .forEach(count -> {
                    carMoveCount++;
                    RacingCarUi.resultPrint(this.carMove());
                });
        return carMoveCount;
    }

[규칙 1: 메서드당 들여쓰기 한 번](https://developerfarm.wordpress.com/2012/01/26/object_calisthenics_2)

이 규칙을 적용해주세요~

2020-11-15 15:59 UTC, yongdae commented on src/main/java/step5/controller/RacingCarController.java
> +            RacingCarUi.resultPrint(this.carMove());
화면과 관련 된 기능이 있어요.
이전에 피드백 드렸던 내용 중 UI와 도메인의 분리를 고려해주세요. :)

2020-11-16 13:56 UTC, yongdae approved these changes
유라님! 고생많으셨습니다. 🙇

화면과 도메인 분리에 대한 피드백도 잘 반영해주셨네요. 💯
거기에 피드백 드리지 않은 부분까지
직접 찾아서 반영해주시다니.. 멋지세요. 👍

진행해주신 미션에 대해서 피드백 남겨 놓았어요.
마지막으로 피드백은 확인만 해주시고
다음 미션인 로또 미션으로 넘어가시면 될 것 같아요. 😄

시작부터 지금까지 포기하지 않고 꾸준하게 열심히 해주셔서 감사드립니다!
마지막 미션까지 유라님을 응원하겠습니다.

정말 수고많으셨습니다. 🙇

2020-11-16 13:56 UTC, yongdae commented on src/main/java/step5/RacingCarMain.java
> +        finalWinner(racingCarController.getCars());
`racingCarController.getCars()` 보다 `racingCarController.getWinners()`는 어떨까요?

지금은 화면에 관련된 RacingCarUi 클래스가 Winner를 만들어서 사용하는데
그것보다는 우승자 목록을 미리 만들어서 반환해주는게 좋아요.
화면은 화면의 일만 도메인은 비지니스만 각 각의 역할에 충실 할 수 있게 해줄 수 있습니다. 😄

2020-11-16 13:56 UTC, yongdae commented on src/main/java/step5/controller/RacingCarController.java
> +    }
멋지세요. 💯

피드백 의견을 따로 안드렸는데도 정적 팩토리 메소드를 사용해주셨네요. :)

2020-11-16 13:56 UTC, yongdae commented on src/main/java/step5/controller/RacingCarController.java
> +    private int carMoveCount;
명확한 의미를 가진 이름을 한번 더 고민해주세요. 😄

`carMoveCount`라는 변수명 보다는 `hasNextRound()`를 통해서 게임 진행을 확인하고 있으니까
`round` 같은 이름을 사용하면 더 좋지않을까요??

2020-11-16 13:56 UTC, yongdae commented on src/main/java/step5/controller/RacingCarController.java
> +    private void carMove() {
이 부분도 `carMove()`도 좋지만 `racing()` 같이 이름으로 조금 더 직접적인 의미를
말해주면 이해하기 좋을 것 같아요. ~

2020-11-16 13:56 UTC, merged

2020-11-16 14:06 UTC, dbeod2 commented on src/main/java/step5/controller/RacingCarController.java
> +    private void carMove() {
넵! 네이밍은 부분확인해서 수정하겟습니다'

2020-11-16 14:06 UTC, dbeod2 commented on src/main/java/step5/controller/RacingCarController.java
> +    private int carMoveCount;
흐음 그렇네요! 수정하겠습니다 ㅎㅎ