Step3 racingcar
next-step/java-racingcar pull request #1531
Opened 2020-11-14 04:51 UTC by kim-daeyong

리뷰 요청 드릴게요~
테스트를 어떤식으로 작성해야할지 감이 안잡히네요
지금 파라미터가 이리저리 타다니는게 싫어서 전역으로 두고 return을 void로 해두었는데..
어떤식으로 하면 좋을까요??

2020-11-14 14:21 UTC, misudev requested changes
안녕하세요 대용님~
기능 구현 잘 해주셨네요 😀
질문에 대한 답변과 함께 코멘트 드렸어요!
확인 후 다시 리뷰 요청 부탁드립니다 ~ 🙏

2020-11-14 14:21 UTC, misudev commented on src/main/java/racingcar/RacingGame.java
> +        for(int i = 0; i < input.get(0); i++){
코드 컨벤션을 지켜주세요~
아래 글에서 **8.2 공백** 부분 참고해보세요 :)
https://myeonguni.tistory.com/1596

2020-11-14 14:21 UTC, misudev commented on src/test/java/racingcar/RacingGameTest.java
> +    }
RacingGame 객체 자체를 비교하면 어떨까요?

그 전에, RacingGame이 거의 모든 비지니스로직을 담당하고 있어서 테스트가 쉽지 않은 것 같아요.
> 메소드 분리 -> 책임에 맞게 메소드와 데이터를 구분 -> 클래스 분리

메소드를 작은 단위로 분리하는 것 부터 시작해보세요! 👍

2020-11-15 06:17 UTC, kim-daeyong commented on src/main/java/racingcar/RacingGame.java
> +        int random = (int)(Math.random()*9);
랜덤클래스를 사용하는 이점이 있을까요??

2020-11-15 06:18 UTC, kim-daeyong commented on src/main/java/racingcar/RacingGame.java
> +        int random = (int)(Math.random()*9);
Math.random() 메소드는 0.0에서 1사이의 double 난수를 얻는데만 사용한다면, Random 클래스는 boolean, int, long, float, double 난수를 얻을 수 있다.
요런걸까요?

2020-11-16 23:19 UTC, misudev commented on src/main/java/racingcar/RacingGame.java
> +        int random = (int)(Math.random()*9);
네, 랜덤클래스를 사용하면 말씀해주신 것 처럼 다양한 타입을 지원하기 때문에 형변환이 필요 없을 것 같아요!

2020-11-17 08:45 UTC, kim-daeyong commented on src/main/java/racingcar/RacingGame.java
> +        int random = (int)(Math.random()*9);
한번 사용하는 클래스라 random class 생성해주는거보다 형변환이 나을 것 같았는데.. 바꾸는게 좋을까요??

2020-11-18 11:46 UTC, misudev requested changes
안녕하세요 대용님~
피드백 반영 잘 해주셨는데요 👍
실행 결과가 상이한 부분이 있어서 확인 부탁드릴께요!
이해 안가는 부분 있으면 DM주세요 🙂

2020-11-18 11:46 UTC, misudev commented on src/main/java/racingcar/Racing.java
> +    }
domain 객체가 view객체를 의존하고 있는데요,
domain이 view를 의존하지 않도록 구현해주세요!

2020-11-18 11:46 UTC, misudev commented on src/main/java/racingcar/Car.java
> +    }
여기서 car는 어떤 목적으로 할당해주시는 걸까요?

2020-11-18 11:46 UTC, misudev commented on src/main/java/racingcar/RacingGame.java
> +        }
![image](https://user-images.githubusercontent.com/45555378/99525491-3cd47580-29dd-11eb-8555-c46ca3770c24.png)
이 부분에서 cars 초기화가 잘못되는 것 같네요.
input size는 무조건 2이니 반복분이 3번 실행되어 자동차가 3대만 생성되고 있어요 😢

2020-11-18 11:46 UTC, misudev commented on src/main/java/racingcar/Car.java
> +public class Car {
도메인에 대한 단위테스트가 부족해보여요.
equals(), hashCode() 메소드를 재정의 해서 객체간의 비교를 하면 어떨까요?

     // when
      car.move();
     // then
     assertThat(car).isEqualsTo(expectedCar);

이런식으로 테스트 가능할 것 같아요.

2020-11-18 11:46 UTC, misudev commented on src/main/java/racingcar/Scoreboard.java
> +    private List<Car> cars;
List<Car> 를 랩핑하는 객체를 만들면 어떨까요?
일급 컬렉션으로 만들어 관리해보세요~ 😀
참고할 만한 글 남깁니다!
https://jojoldu.tistory.com/412

2020-11-18 11:54 UTC, kim-daeyong commented on src/main/java/racingcar/RacingGame.java
> +        }
헉 못봤네요!

2020-11-18 12:01 UTC, kim-daeyong commented on src/main/java/racingcar/Car.java
> +    }
헉 잘못했어요..

2020-11-18 12:58 UTC, kim-daeyong commented on src/main/java/racingcar/Racing.java
> +    }
이렇게 하는게 맞나 싶네요..

2020-11-18 13:38 UTC, kim-daeyong commented on src/main/java/racingcar/Scoreboard.java
> +    private List<Car> cars;
굉장히 좋네요 변경되지 말아야할 객체를 만들때 사용하면 좋을 것 같아요 감사합니다

2020-11-19 23:11 UTC, misudev requested changes
안녕하세요 대용님~
피드백 반영 잘 해주셨는데요,
실행 결과에 문제가 있어 확인 부탁드릴께요 😢
![image](https://user-images.githubusercontent.com/45555378/99734938-0dba2300-2b07-11eb-9697-8a8b8f275f06.png)
고민되는 부분 있으면 DM주세요~

2020-11-19 23:11 UTC, misudev commented on src/main/java/racingcar/service/RacingGame.java
> +    }
RacingGame이 UI 객체를 가지고 있어, Domain 객체가 View에 의존하는 것 같아요. 😢
RacingGame에서 필요한 값만 controller에서 받아 view에게 넘겨주면 어떨까요?

2020-11-21 08:22 UTC, misudev approved these changes
안녕하세요 대용님~
리팩토링 하느라 고생하셨습니다 !
이번 스텝은 이만 머지하도록 할께요~
소소한 코멘트 남겨 놨는데요, 다음 스텝에서 반영해 주시면 좋을 것 같습니다 🙂
날씨가 많이 추워졌는데 건강 조심하시고 화이팅입니다 🙏

2020-11-21 08:22 UTC, misudev commented on src/main/java/racingcar/service/RacingGame.java
> +    int move = 0;
안쓰는 필드는 제거해주세요~

2020-11-21 08:22 UTC, misudev commented on src/main/java/racingcar/service/Racing.java
> +        final int move = random.nextInt(10);
final로 선언하신 이유가 있을까요? 👀

2020-11-21 08:22 UTC, merged

2020-11-21 10:21 UTC, kim-daeyong commented on src/main/java/racingcar/service/RacingGame.java
> +    }
수정 했어요~!

2020-11-21 10:23 UTC, kim-daeyong commented on src/main/java/racingcar/service/Racing.java
> +        final int move = random.nextInt(10);
헉 만들면서 오타났네요!