step4
next-step/java-racingcar pull request #1543
Opened 2020-11-16 13:25 UTC by jaehee0145

안녕하세요!

요구사항을 다 구현하지 못했는데 😭 
리뷰 남겨주시면 같이 작업해서 
다시 pr 올리겠습니다 !

2020-11-17 17:24 UTC, parkeeseul requested changes
꾸준히 미션 진행해주시느라 고생이 많으십니다!

몇 가지 피드백 남겨두었으니 확인 부탁드립니다!
나머지 요구사항들도 화이팅 입니다! 🔥

2020-11-18 15:39 UTC, jaehee0145 commented on src/main/java/racingcar/InputView.java
> +        carNames = Arrays.asList(scanner.next().split(","));
1. 쉼표를 상수로 만드는게 좋을까요?
2. 해당 부분이 중복적으로 늘어난다고 말씀하신건 자동차 이름, 시도 횟수처럼 다른 입력값이 늘어나는 상황을 뜻하는 걸까요? 
3. 입력 받은 자동차 이름을 분리해서 각각 이름으로 저장하는 부분을 도메인 로직으로 옮기라는 의미로 이해하면 될까요? 😄

2020-11-18 15:50 UTC, jaehee0145 commented on src/main/java/racingcar/RacingGame.java
> +        for (int i = 1; i < rounds + 1; i++) {
첫 라운드에는 랜덤 숫자를 만들어서 전진시키지 않고 모두 location 1로 출력을 시키고 싶은데 어디에 로직을 추가해야 될지 고민이 됩니다 🤔

2020-11-18 16:18 UTC, jaehee0145 commented on src/test/java/racingcar/CarTest.java
> +        car = new Car("car");
@parkeeseul validateName 메소드에 대한 테스트를 추가하려고 했는데  @BeforeEach로 자동차를 생성하고 있어서 고민이 됩니다! 생성자에서 사용하는 메소드를 테스트 하려면 @BeforeEach 를 사용하지 않는 방법 밖에 없을까요?

2020-11-18 16:31 UTC, jaehee0145 commented on src/main/java/racingcar/RacingGame.java
> +    public String getWinner() {
우선 중복 우승자를 표시할 수 있게 수정했습니다!
메소드를 분리해봤는데.. 역할 별로 어떻게 나눌 수 있을까요? 🤔

2020-11-18 16:33 UTC, jaehee0145 commented on src/test/java/racingcar/RacingGameTest.java
> +
RacingGame에 private 메소드가 많아서 테스트를 작성하기가 어려운데요 😭 
private 메소드는 어떻게 테스트를 하는게 좋은가요?

2020-11-18 16:45 UTC, jaehee0145 commented on src/main/java/racingcar/RacingGame.java
> +    public String getWinner() {
getWinner() 에 대한 테스트 메소드를 작성하려고 했는데 
raceRecord를 테스트 코드 내에서 직접 생성해서 RacingGame에 넣어줄 수 없는거 같은데... 😢 
어떤 식으로 테스트를 할 수 있을까요? 
테스트가 어려운 구조라서 어려운건가요 😂

2020-11-18 16:51 UTC, jaehee0145 commented
첫번째 과제인데도 어렵네요 😂 
고민하다보니 질문이 많아졌는데 잘 부탁드립니다 🙏 
늦은 시간까지 고생이 많으세요 😭 
감사합니다 🍎

2020-11-19 16:29 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요!
질문에 대한 저의 의견과 몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 

다음 단계가 리팩토링이라 이만 머지하겠습니다!
다음 단게에서 반영 부탁드려요! 자동차 미션 마지막 단계네요 !! 화이팅! 😄

2020-11-19 16:29 UTC, parkeeseul commented on src/main/java/racingcar/Car.java
>      public void move() {
해당 매서드는 외부에 공개할 필요가 없을거 같아요!
접근제어자를 private 으로 변경해주면 어떨까요? 😄

2020-11-19 16:29 UTC, parkeeseul commented on src/main/java/racingcar/InputView.java
>  package racingcar;
view 와 domain 으로 패키지를 나눠보면 어떨까요? 😄

2020-11-19 16:29 UTC, parkeeseul commented on src/main/java/racingcar/RacingGame.java
> +        for (int i = 1; i < rounds + 1; i++) {
지금 해주신 대로 Car 객체에 location  초기화를 1로 해주시면 될거 같네요! 👍

2020-11-19 16:29 UTC, parkeeseul commented on src/test/java/racingcar/RacingGameTest.java
> +
private 메서드들은 public 메소드에서 사용되기 때문에 굳이 테스트 코드를 따로 작성하지 않아도 public 메서드 안에서 자연스레 테스트가 됩니다! 하지만 만약 클래스 내부에 private 메소드가 심하게 있다고 하면 그 클래스는 단일 책임 원칙에 의해서 잘 설계된 클래스가 맞는지 의심해 볼 필요가 있을거 같아요! 이를테면 분할을 잘못한 구조거나 procedure 스타일로 짜여진 클래스일 가능성이 있습니다.

피드백에 남겨드렸듯이 Car 객체와 RaceRecords 를 분리해보면 좋을거 같아요! 😄

2020-11-19 16:29 UTC, merged