Step4 winner
next-step/java-racingcar pull request #1555
Opened 2020-11-21 16:56 UTC by kim-daeyong

step 4 진행하여 리뷰 요청 드립니다.

2020-11-22 02:32 UTC, misudev requested changes
안녕하세요 대용님~ 
4단계 요구사항 잘 구현해주셨는데요
자동차 이름은 5자를 초과할 수 없는데, 검증 로직이 빠진 것 같아요 😯
이 부분과 함께 코멘트 반영 부탁드려요~ 😀
이해 안 가거나, 궁금한 점 있으면 DM주세요~ 🙏

2020-11-22 02:32 UTC, misudev commented on src/main/java/racingcar/service/RacingGame.java
> +        String[] getName = input.get(0).split(",");
input 문자열에 대한 처리는 view에서 해주면 어떨까요?
만약 새로운 유저가 자동차 이름을 "**jay:toto:tom**" 이런식으로 받고 싶어하면,
이를 지원해주는 새로운 view 를 만들어 주면, 비지니스 로직의 변경 없이 유연한 대응이 가능할 것 같아요. 🙂

2020-11-22 02:32 UTC, misudev commented on src/main/java/racingcar/domain/Scoreboard.java
>      private List<Car> cars;
cars를 일급컬랙션으로 만들어보세요~ 😀

2020-11-22 02:32 UTC, misudev commented on src/main/java/racingcar/domain/Scoreboard.java
>  public class Scoreboard {
ScoreBoard란 이름을 봤을 땐, 점수에 대한 정보가 저장 될 것 같은데,
단순히 getter, setter 만 지원해주고 있네요.
매 라운드 결과 값에 대한 처리가 아쉬운데요, 이 클래스를 활용해보면 좋을 것 같아요.

2020-11-22 02:32 UTC, misudev commented on src/main/java/racingcar/service/RacingGame.java
> +        List<String> result = racing.moveCar(placetForRacingByName(input));
placetForRacingByName(input)을 두 번 실행해주는 이유가 있을까요? 😯

2020-11-22 02:32 UTC, misudev commented on src/main/java/racingcar/service/RacingGame.java
>          System.out.println("실행 결과");
출력은 View단에서 처리해주세요~ 🙏

2020-11-22 02:32 UTC, misudev commented on src/test/java/racingcar/domain/CarTest.java
>      void carMoveTest(){
전반적으로 테스트 코드가 부족한 것 같아요😢

2020-11-22 14:15 UTC, kim-daeyong commented on src/main/java/racingcar/service/RacingGame.java
> +        List<String> result = racing.moveCar(placetForRacingByName(input));
헉 실수에요 ㅋㅋㅋ 지금 봤어요..

2020-11-28 14:57 UTC, misudev requested changes
많은 코멘트 반영하시느라 고생하셨어요 👍 👍 
마지막 단계 전에 리팩토링하면 좋을 것 같아, 몇 가지 의견 드렸습니다.💭 
확인하시고 재요청 부탁드려요 ~
마지막까지 화이팅입니다!! 🔥

2020-11-28 14:57 UTC, misudev commented on src/main/java/racingcar/view/ResultView.java
> +    }
승자를 구하는 로직은 Cars가 가져가는게 어떨까요?
필요한 정보를 Cars가 가지고 있기 때문에 더 적절한 분리같아요.
예를 들면 아래와 같이 구현 할 수 있겠네요! 
```java
// Cars 클래스로 간다면?
    public List<String> getWinnerName(int winnerLocation) {
        return cars.stream()
                .filter(car -> car.getLocation() == winnerLocation)
                .map(Car::getCar)
                .collect(Collectors.toList());
    }
```

2020-11-28 14:57 UTC, misudev commented on src/main/java/racingcar/view/InputView.java
> +    }
한번에 두가지 값을 받아오면, 처리하는 객체도 복잡할 것 같아요.
메소드를 각각 분리해보면 어떨까요?  😀
```java
    public String[] getRacerNames() {
        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
        String[] racer = sc.nextLine().split(",");
        validateNameLength(racer);
        
        return racer;
    }

    public int getNumberOfRacing() {
        System.out.println("시도할 횟수는 몇회 인가요?");
        return sc.nextInt();
    }
```

2020-11-28 14:57 UTC, misudev commented on src/main/java/racingcar/domain/Car.java
> +    private  String car;
변경되지 않는 값은 final로 선언해주세요! :)

2020-11-28 14:57 UTC, misudev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
순서를 바꿔주세요!

2020-11-28 14:57 UTC, misudev commented on src/main/java/racingcar/view/InputView.java
> +                throw new RuntimeException(s + "의 이름이 5글자 이상입니다.");
IllegalArgumentException 을 사용하면 더 명시적인 예외가 될 것 같습니다!

2020-12-07 10:22 UTC, misudev approved these changes
많은 코멘트 반영하시느라 고생하셨습니다 👍 👍 
이번 단계는 이만 머지하겠습니다 😀
코멘트 몇개 남겨 놨는데요, 마지막 단계 진행하면서 반영해주시면 좋을 것 같아요. :)
마지막까지 화이팅입니다 🔥🔥

2020-12-07 10:22 UTC, misudev commented on src/main/java/racingcar/domain/RacingCar.java
> +    private List<Car> cars;
final로 선언하면 어떨까요?

2020-12-07 10:22 UTC, misudev commented on src/main/java/racingcar/view/InputView.java
>      }
메소드를 분리해주셨으니, 두 값을 Map에 담아 반환하지 않아도 될 것 같아요 😯

2020-12-07 10:22 UTC, misudev commented on src/test/java/racingcar/service/RacingTest.java
> +        assertThat(scoreboard.getRacingCar()).isEqualTo(cars);
scoreboard.getRacingCar()와 cars는 동일한 인스턴스를 가리키는 것 같아요 😯

현재는 아래랑 동일합니다 ㅜㅜ 

    assertThat(cars).isEqualTo(cars); 

이런식으로, 예상되는 값을 만들어줘서 검증해보세요

    assertThat(scoreboard.getRacingCar()).isEqualTo(expectedCars);

2020-12-07 10:22 UTC, misudev commented on src/main/java/racingcar/domain/RacingHistory.java
> +	}
위에는 space 4개, 아래는 tab인 것 같아요~
다른 곳과 동일하게 space 4개로 수정하면 좋을 것 같습니다

2020-12-07 10:23 UTC, merged