Step4
next-step/java-racingcar pull request #1560
Opened 2020-11-26 16:21 UTC by yeGenieee

안녕하세요 용대님 ! 
자동차 경주 (우승자) 구현 완료하여 리뷰 요청 드립니다 :)
아직 우승한 자동차에 대한 테스트 코드를 작성하지 못하였는데요ㅠ
고민의 시간이 너무 길어지는 것 같아서 먼저 리뷰 요청 드립니다 !
잘 부탁드립니다 ! :)

- [x] InputView 자동차 이름 입력 제약 조건 테스트
- [x]  RacingGame 입력한 자동차 이름 수와 같은 자동차 리스트 생성되었는지 테스트
- [ ]  ResultView 자동차 경주 결과 출력 테스트
- [ ]  RacingGame 내 우승한 자동차 구하는 로직 테스트

2020-11-27 02:48 UTC, yongdae requested changes
안녕하세요. 예진님 :)

4단계 미션을 잘 진행해주셨네요~
이전 단계보다 코드가 한결 깔끔해진 것 같아요. 👍👍

요구사항 정리랑 구현할 기능 정리도 멋지네요. 💯 

이야기 해주신 것처럼 아직 우승자 자동차와 관련된 내용은 미완성이라
해당 내용을 제외하고 의견을 남겨 놓았습니다. 

확인하고 다시 리뷰 요청 부탁드립니다. 😄

2020-11-27 02:48 UTC, yongdae commented on src/main/java/step4/Main.java
> +        for (int i = 0; i < round; i++) {
이 부분을 메소드로 만들어 보는 것은 어떨까요?

RacingGame 클래스에서 for문을 메소드로 제공해주면 좋을 것 같아요
예를 들어 hasNextRound()라는 메소드를 선언해서 while문을 활용하면

Main 클래스는 지정된 횟수만큼 for문을 돌려야하는
즉 횟수만큼 게임을 실행해야하는 책임을 안가질 수 있어요. 😄

2020-11-27 02:48 UTC, yongdae commented on src/main/java/step4/InputView.java
> +    }
유효성의 위치를 수정해보는 것은 어떨까요?

입력 받는 시점에 유효성을 활용하는것도 좋은 방법이지만
Car 클래스의 생성자에서 유효성을 하는게 더 좋을 것 같아요.

만약에 사용자의 입력을 통해서가 아니라
Car의 생성자를 통해 `new Car(0, "yeGenieee")` 인스턴스를 생성하면
문제없이 인스턴스가 만들어집니다. :)

2020-11-27 02:48 UTC, yongdae commented on src/main/java/step4/Car.java
> +    private static int getRandomNumber() {
유틸리티 클래스를 만들어서 활용하는 것은 어떨까요? 😄

랜덤값을 만들어서 반환하는 내용은 자동차와 무관한 내용일 수 있어요.
자동차는 "전진하기 위해 값을 전달받는 것" 자체가 중요할 뿐이지
전달받는 값이 어떻게 만들어졌는지 관심이 없어요.

2020-11-27 02:48 UTC, yongdae commented on src/test/java/step4/CarTest.java
> +    }
오류가 나요. 😭

<img width="1193" alt="Screen Shot 2020-11-27 at 11 11 41 AM" src="https://user-images.githubusercontent.com/4317804/100404465-c8689900-30a4-11eb-997e-ae86b2bd4304.png">

2020-11-27 02:48 UTC, yongdae commented on src/main/java/step4/RacingGame.java
> +        }
getCars().stream()
                .forEach(Car::move);

스트림을 활용하시면 이런 방법으로도 작성이 가능합니다. 😄

2020-11-27 02:48 UTC, yongdae commented on src/main/java/step4/RacingGame.java
> +                .collect(Collectors.toList());
filter가 호출 될 때마다 getMaxPosition를 호출하는 것보다

        int maxPosition = getMaxPosition();
        
        return getCars().stream()
                .filter(car -> car.getPosition() == maxPosition)
                .collect(Collectors.toList());

미리 호출해서 값을 가지고 연산 할 때 사용하면 더 좋을 것 같은데
어떻게 생각하시나요? 😄

2020-11-27 03:08 UTC, yeGenieee commented on src/main/java/step4/Main.java
> +        for (int i = 0; i < round; i++) {
오호 그러네요!! 말씀 감사합니다~! 수정하겠습니다

2020-11-27 03:13 UTC, yeGenieee commented on src/main/java/step4/InputView.java
> +    }
아! 😄😄그러네요 ! 자동차 이름이 결국 자동차 객체 관련 사항이니 위치 수정하는 게 더 좋네요!!

2020-11-27 03:17 UTC, yeGenieee commented on src/main/java/step4/Car.java
> +    private static int getRandomNumber() {
의견주신뒤에 생각해보니 그렇네요 😅😅의견 감사합니다 !! 수정하겠습니다 ~~

2020-11-27 03:18 UTC, yeGenieee commented on src/test/java/step4/CarTest.java
> +    }
😭😭 제가 테스트 수정한 걸 커밋을 안했네요 으어ㅠ 수정해두겠습니다 !

2020-11-27 03:20 UTC, yeGenieee commented on src/main/java/step4/RacingGame.java
> +        }
스트림으로 수정할 수 있는 부분은 고쳐두겠습니다 😄

2020-11-27 03:24 UTC, yeGenieee commented on src/main/java/step4/RacingGame.java
> +                .collect(Collectors.toList());
엇 그러네요ㅠㅠ 말씀하신게 훨씬 좋아요!! 수정해두겠습니다~! 😄

2020-11-29 17:53 UTC, merged

2020-11-29 17:56 UTC, yongdae commented
제가 실수로 코멘트를 안남기고 머지를 해버렸네요.. ㅜㅡㅜ 죄송합니다.