Step2
next-step/java-racingcar pull request #1587
Opened 2020-12-01 12:10 UTC by cionman

안녕하세요, 코드 리뷰 부탁드립니다. 
감사합니다.

2020-12-01 16:58 UTC, hongsii requested changes
2단계 요구사항도 깔끔하게 잘 구현해주셨네요! 💯 
간단한 피드백을 남겼으니 확인하셔서 반영해주세요~!

2020-12-02 00:34 UTC, cionman commented on src/main/java/com/woowahan/calculator/StringCalculator.java
> +			.reduce((a, b) -> parseResult.getOperators().get(index.getAndIncrement()).getOperator().applyAsLong(a, b))
피드백 감사합니다. 피드백 반영하여 푸시되었습니다.

2020-12-02 00:35 UTC, cionman commented on src/test/java/com/woowahan/calculator/OperatorTest.java
> +	@CsvSource(value = {"1:2:3", "3:5:8", "7:9:16"}, delimiter = ':')
피드백 감사합니다.

2020-12-02 00:35 UTC, cionman commented
피드백 감사합니다. 피드백 반영하여 푸시되었습니다.

2020-12-02 12:50 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨습니다! 👍 
간단한 피드백 남겼으니, 다음 단계에서 함께 반영해주세요 :)

2020-12-02 12:50 UTC, hongsii commented on src/main/java/com/woowahan/calculator/Operator.java
> +	}
`doOperator` 를 통해서만 연산을 진행하도록 강제하기 위해 getter를 삭제하는건 어떨까요?

2020-12-02 12:50 UTC, merged

2020-12-02 12:53 UTC, cionman commented on src/main/java/com/woowahan/calculator/Operator.java
> +	}
피드백 감사합니다~