Step2 문자열 계산기
next-step/java-racingcar pull request #1628
Opened 2020-12-03 17:18 UTC by baekss

Calculator 도메인이 너무 많은 작업을 담당하지 않도록,
사칙연산 기능은 별도의 도메인으로 분리를 하였습니다.

2020-12-04 09:52 UTC, serverwizard requested changes
문자열 계산기 구현을 잘 해주셨습니다! 👍 

몇 가지 코멘트 남겨두었으니 확인 부탁드릴게요~
궁금한점 있으시면 편하게 코멘트 또는 DM 남겨주세요.

2020-12-04 09:52 UTC, serverwizard commented on src/main/java/step2/operation/ArithmeticOperation.java
> +public interface ArithmeticOperation {
연산을 담당하는 인터페이스 선언 👍👍👍👍👍👍

이건 개인적인 궁금함 인데요~ 
이번 미션에서 연산을 담당하는 인터페이스를 만들어서, 각 연산 객체가 해당 인터페이스를 구현하도록 했을 때 어떤 장점이 있었나요? (순전히 저의 개인적인 궁금함이니 절대절대 부담 갖지 않으셔도 되요!! :pray: )

2020-12-04 09:52 UTC, serverwizard commented on src/main/java/step2/CalculatorMain.java
> +    private static void calculate(String target) {
계산기 역할을 하는 Calculator에게 calculate메소드를 담당하게 하는 건 어떨까요?

테스트 코드로 보여드리면 아래와 같이요!
```
assertThat(Calculator.calculate("4 / 2 * 3")).isEqualTo(6);
```
API를 사용하는 입장에서 Calculator가 어떻게 구현됐는지 나는 잘 모르겠고, input값 줄테니 결과 값줘라는 느낌으로요~

2020-12-04 13:29 UTC, baekss commented on src/main/java/step2/operation/ArithmeticOperation.java
> +public interface ArithmeticOperation {
안녕하세요. 백승석 입니다!

넵! 구체적인 타입에 의존하지 않고, 인터페이스 타입으로 다형성에 따라 기능을 실행할 수 있었기 때문에
연산을 구분하기 위한 비교로직 구현 관점에서 상대적으로 비용을 아낄 수 있었습니다.

또한, 제네릭과 조합해 사용하면 캐스팅 이슈와 같은 상황에 대한 대비가 자연스럽게 이루어질 수 있었습니다.

이러한 컨셉은 유지보수 관점에서도 모듈 이식성과 확장성에 이점을 가지게 하며, 모듈 변화에 의한 영향도를 최소화 할수 있다고 생각합니다.

유익한 코드리뷰 진심으로 감사합니다!!

2020-12-04 13:39 UTC, baekss commented on src/main/java/step2/CalculatorMain.java
> +    private static void calculate(String target) {
넵! Calculator의 역할을 정의하는데 있어서 큰 공부가 되었습니다!
감사합니다!

2020-12-05 06:24 UTC, serverwizard commented on src/main/java/step2/operation/ArithmeticOperation.java
> +public interface ArithmeticOperation {
승석님, 자세한 의견 공유 감사해요~

사실 제가 질문을 드린 이유 중 하나는 승석님이 말씀해주신 인터페이스를 통한 다형성과 
아래와 같이 Enum을 이용한 방식 중에 승석님께선 어떤 고민을 통해 인터페이스 방식을 선택하셨을까 궁금했어요 ^^

그럼 남은 미션도 화이팅입니다.

아래 코드는 정답이 아니라, 제가 표현하고 싶은 느낌 전달 용으로 빠르게 작성한 코드입니다~ ^^
```
    private enum Operator {
        PLUS("+") {
            @Override
            public int calculate(final int operand1, final int operand2) {
                return operand1 + operand2;
            }
        },
        MINUS("-") {
            @Override
            public int calculate(final int operand1, final int operand2) {
                return operand1 - operand2;
            }
        },
        MULTIPLY("*") {
            @Override
            public int calculate(final int operand1, final int operand2) {
                return operand1 * operand2;
            }
        }, DIVIDE("/") {
            @Override
            public int calculate(final int operand1, final int operand2) {
                if (operand2 == 0) {
                    throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
                }
                return operand1 / operand2;
            }
        };

        final private String sign;

        Operator(String sign) {
            this.sign = sign;
        }

        public abstract int calculate(final int operand1, final int operand2);

        public static int calculate(final int operand1, final String operator, final int operand2) {
            Operator selectedOperator = Arrays.stream(Operator.values())
                    .filter(v -> v.sign.equals(operator))
                    .findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("사칙연산을 사용해주세요."));

            return selectedOperator.calculate(operand1, operand2);
        }
    }
```

2020-12-05 06:26 UTC, serverwizard approved these changes
문자열 계산기 구현 잘 해주셨습니다! 👍 

의견 남겨주신 부분에 코멘트 남겨두었으니 다음 Step 진행하실 때 참고만 부탁드릴게요~

다음 Step도 화이팅입니다! 🔥 
감사합니다!

2020-12-05 06:26 UTC, merged