Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #1645
Opened 2020-12-04 16:19 UTC by cionman

안녕하세요, 

처음으로 테스트 코드를 먼저 작성하고, 코드를 작성하는 연습을 해보았습니다. 기존 코드 작성하던 방식에서 거꾸로 하다보니 익숙하지 않더군요,
테스트 코드 작성을 먼저 하다가도, 코드 작성하다가 어느순간 간단한 코드는 먼저 구현해버리기도하면서 뒤늦게 커밋이 들어간 경우도 있습니다.
의식적으로 연습을 할수 있게 노력해야할 듯 합니다.

리뷰 부탁드립니다. 매번 감사합니다 ㅎ

2020-12-05 13:26 UTC, hongsii requested changes
4단계 구현도 잘 해주셨네요!! 👍 
몇 가지 피드백 남겼으니, 참고하셔서 반영해주세요~!

2020-12-05 13:26 UTC, hongsii commented on src/main/java/com/woowahan/racing/constant/Message.java
> +	public static final String MSG_NAME_LENGTH_EMPTY_OR_GREATER_THAN_5 = "자동차 이름이 이름이 없거나  5자보다 큽니다.";
자동차 이름을 5자에서 10자로 늘리면 어떤 일이 발생할까요?
내용을 유추할 수 있는 자세한 변수명/메서드명도 좋지만, 오히려 너무 상세한 내용까지 바깥으로 노출해버리면 
불필요한 변경이 발생하고, 이로 인해 유지보수하기가 힘들어질 수 있습니다!

2020-12-05 13:26 UTC, hongsii commented on src/main/java/com/woowahan/racing/util/ValidationUtil.java
> +		if (value == null || "".equals(value))
`isNullOrEmpty(..)` 를 재사용할 수 있지 않을까요?

2020-12-05 13:26 UTC, hongsii commented on src/main/java/com/woowahan/racing/model/Car.java
> +		return this.distance != null ? distance.length() : 0;
이전 단계에서 지나갔지만, 거리를 숫자로 바꿔보면 어떨까요?
거리를 "-" 라는 문자로 출력해야 한다는 것은 뷰에서 알아야할 책임에 가깝지 않을까요?

2020-12-05 13:40 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Car.java
> +		this.name = name;
피드백 감사합니다.  반영되었습니다.

2020-12-05 13:43 UTC, cionman commented on src/main/java/com/woowahan/racing/model/InputResult.java
> +		this.carCount = carNames.size();
getCarCount 에서 carNames.size()를 반환하면되는데, 생각이 짧았던것 같습니다. 
감사합니다. 반영되었습니다.

2020-12-05 13:49 UTC, cionman commented on src/main/java/com/woowahan/racing/model/InputResult.java
> +		if (carNames == null || carNames.size() == 0) {
피드백 감사합니다.
반영되었습니다.

2020-12-05 13:56 UTC, cionman commented on src/main/java/com/woowahan/racing/model/RacingSimulator.java
> +			cars.add(Car.createCar(inputResult.getCarNameByIndex(i)));
피드백 반영되었습니다.
감사합니다.

2020-12-05 14:06 UTC, cionman commented on src/main/java/com/woowahan/racing/util/ValidationUtil.java
> +		if (value == null || "".equals(value))
피드백 감사합니다.
수정 반영되었습니다.

2020-12-05 14:25 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Car.java
> +		return this.distance != null ? distance.length() : 0;
피드백 감사합니다.

음 이 부분에 있어서는 저는 약간 반대의 생각을 가지고 있습니다.
테스트하기 어려운 View에서는 완전히 그림 그리는 로직도 완전히 덜어내는게 맞지 않을까 생각했거든요. 
결과 출력 하는 부분은 순수하게 출력만 하는 것이 좋지 않을까 생각되었습니다.

2020-12-05 15:12 UTC, cionman commented on src/main/java/com/woowahan/racing/model/RacingSimulator.java
> +	public List<String> getWinners() {
피드백 감사합니다.

RacingSimulator에 많은 책임이 부여되어있는 부분은 코딩하면서 느꼈지만, 마땅히 방법이 떠오르지 않았는데,
일급컬렉션이라는 해결책을 제시해주셔서 감사합니다.

사실 실무에서는 일급컬렉션을 적용해본 경험이 없었는데, 해당 교육 과정을 공부하면서 저도 어제인가 위 내용을 확인했었습니다. 상태를 관리하는 좋은 기법인것 같습니다. 정말 좋은 것을 배운것 같네요 

피드백은 적용하기는 했는데, 좀 부족해보이기는 합니다. 추가로 피드백을 다시 주신다면 다시한번 적용하겠습니다. 감사합니다.

2020-12-05 15:15 UTC, cionman commented on src/main/java/com/woowahan/racing/constant/Message.java
> +	public static final String MSG_NAME_LENGTH_EMPTY_OR_GREATER_THAN_5 = "자동차 이름이 이름이 없거나  5자보다 큽니다.";
피드백 감사합니다. 
수정적용되었습니다.

2020-12-05 15:19 UTC, cionman commented
안녕하세요, 

주말에도 꼼꼼한 피드백을 주셔서 감사합니다.  주말 쉬시는데 오히려 방해가 되지 않는지 모르겠네요 ㅜ
마지막 피드백이외에는 모두 수정 적용되었습니다. 

감사합니다.

2020-12-06 11:40 UTC, cionman commented
마지막 피드백도 수정 반영되었습니다.

2020-12-06 11:41 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Car.java
> +		return this.distance != null ? distance.length() : 0;
의견 코멘트를 들어보고 반영할까 하다가 바로 반영하였습니다. 감사합니다.

2020-12-06 15:30 UTC, hongsii approved these changes
제가 드린 피드백을 모두 잘 반영해주셨네요! 👍 
피드백 남겼으니 확인하시고, 다음 단계에서 함께 반영해주세요~!

2020-12-06 15:30 UTC, hongsii commented on src/main/java/com/woowahan/racing/model/Car.java
> +	public static Car createCar(String name) {
이건 취향차가 있을 수 있지만 개인적으론 코드를 작성했을 때에 발생하는 중복을 줄이면 코드를 자연스럽게 읽는데 도움이 되더라구요 ㅎㅎ

예를 들면, static 메서드를 사용할 때 `Car.createCar(name)`  와 같이 클래스명과 함께 메서드명을 코드로 작성하게 됩니다.
보통은 import static을 하지 않기 때문에  클래스명과 같은 단어가 메서드에서 반복되는 것이 코드를 자연스럽게 읽는 것을 방해한다는 생각이 들었어요.

그래서 저는 static 메서드명을 지을 때엔 이러한 것을 고려해 `Car.create(name)` 와 같이 코드를 사용한 곳에서 자연스럽게 읽을 수 있도록 네이밍하는 것을 선호하는 편입니다 :)

2020-12-06 15:30 UTC, hongsii commented on src/test/java/com/woowahan/racing/model/CarsTest.java
> +	@DisplayName("getWinners메서드는 우승자를 최소 1명 이상 반환한다.")
최소 1명으로 검증하면 결과로 나온 사람이 우승자가 맞는지 정확히 검증되었다고 볼 수 있을까요?
랜덤으로 인해 테스트하기 어려울텐데요. 테스트하기 힘든 부분을 개선해 우승한 자동차 이름이 정확히 출력되는 지 검증하도록 바꿔보면 어떨까요?

2020-12-06 15:31 UTC, merged

2020-12-06 16:03 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Car.java
> +		if (ValidationUtil.isLengthEmptyOrGreaterThanFive(name)) {
step5 브랜치로 피드백 반영하였습니다.

2020-12-06 16:10 UTC, cionman commented on src/main/java/com/woowahan/racing/model/RacingSimulator.java
> +			cars.add(Car.createCar(carName));
step5 브랜치로 피드백 반영하였습니다.

2020-12-06 16:16 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Car.java
> +	public static Car createCar(String name) {
step5에서 피드백 반영하였습니다.

제가 `create` 라는 메소드 명보다 `createCar` 라는 메소드명을 선호하는 이유는 사실 intellij의 리팩토링 기능 때문입니다. intellij 에서 메소드명 또는 변수명에서 짧고 흔한 메소드명이나 변수명을 리펙토링을 하려고 하면 관련이 없어도 많은 내용들이 한꺼번에 결과 화면에 나오게 되는데요. 리펙토링시 실수의 여지도 있고해서 약간은 유니크한 메소드명이 되도록 노력하는 편입니다.

2020-12-06 17:22 UTC, cionman commented on src/test/java/com/woowahan/racing/model/CarsTest.java
> +	@DisplayName("getWinners메서드는 우승자를 최소 1명 이상 반환한다.")
음 랜덤으로 우승자가 정해지는 터라 우승자의 이름을 어떤 방식으로 테스트해야 좋을까요?