Step5 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #1683
Opened 2020-12-06 17:27 UTC by cionman

안녕하세요.

step5 - 자동차 경주(리팩토링) 풀리퀘스트 보냅니다.

그리고, step4에서 머지하면서 남겨주신 피드백중에 하나를 수행하지 못하고 질문을 남겼는데요, 한번 확인해주시면 감사하겠습니다 ㅎ
(https://github.com/next-step/java-racingcar/pull/1645#discussion_r537084424) 

늘 꼼꼼히 피드백 주셔서 감사합니다.

2020-12-07 14:07 UTC, hongsii requested changes
이전 피드백 반영과 함께 구현을 잘 해주셨네요!
피드백 남겼으니 확인하셔서 반영해주세요~!

2020-12-07 14:07 UTC, hongsii commented on src/test/java/com/woowahan/racing/model/CarsTest.java
> +		int maxDistance = cars.findMaxDistance();
> 음 랜덤으로 우승자가 정해지는 터라 우승자의 이름을 어떤 방식으로 테스트해야 좋을까요?

프로덕션 코드를 일부 변경해 테스트를 진행하셨습니다.
테스트는 프로덕션 코드를 검증하기 위해 작성하는 건데 테스트를 위해 프로덕션 코드를 변경하는 것은 적절하지 않다고 생각해요.

말씀하신 대로 자동차가 랜덤하게 움직이다 보니 원하는 상황을 만들어 테스트하기 어렵습니다.
테스트 하기 어려운 상태라면 통제할 수 없는 요인을 분리해 통제할 수 있는 상태로 만들어야 합니다.

아래와 같은 인터페이스를 만들어 랜덤 로직을 분리해 통제할 수 있는 상황으로 바꿔보면 어떨까요?

``` java
public interface GameRandom {

    boolean isWin();
}
```

그리고 테스트 작성 시 자동차가 전부 움직였다는 가정하에 자동차 거리를 설정하고, 아래와 같이 우승자로 설정한 자동차가 정확히 나왔는지 검증해보면 좋을 것 같습니다!

``` java
List<String> winners = cars.getWinners();

assertThat(winners).containsOnly(CAR_NAME1);
```

2020-12-07 15:40 UTC, cionman commented on src/main/java/com/woowahan/racing/model/Cars.java
> +		}
피드백 반영되었습니다. 감사합니다.

2020-12-07 16:13 UTC, cionman commented on src/test/java/com/woowahan/racing/model/CarsTest.java
> +		int maxDistance = cars.findMaxDistance();
static 메소드로 활용했던 부분이어서 interface를 구현하면 된다는 부분에는 생각이 미치지 못했네요 ㅜ
피드백 감사합니다.

2020-12-07 16:15 UTC, cionman commented
피드백 감사합니다.
모두 적용완료되었습니다.

2020-12-08 11:03 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘 해주셨네요! 👍 
이번 미션은 여기서 마무리할게요!
미션 진행하시느라 고생 많으셨습니다.
남은 미션도 마무리 잘 하시기를 바랍니다! 🙏

2020-12-08 11:04 UTC, merged

2020-12-08 11:17 UTC, cionman commented
한주 동안 수고 많으셨습니다~ 
매일 하루 한번 리뷰받기가 목표였던 터라 많이 고생시켜 드린것 같네요 ㅎㅎ 
감사합니다. 코로나로 뒤숭숭하지만 즐거운 연말 되시기를 바랍니다 ㅎ