[Step4] 자동차 경주(우승자)
next-step/java-racingcar pull request #1708
Opened 2020-12-08 09:56 UTC by slamdunk7575

안녕하세요😄  시홍님.

회사와 리뷰어 일을 병행하시느라 고생 많으시네요 😭 

사소한 부분이라도 코멘트 남겨주시면 열심히 반영해보겠습니다.
리뷰 잘 부탁드립니다~!

건강조심하세요😷  감사합니다.

2020-12-08 16:52 UTC, hongsii requested changes
이전 단계에서 구조를 잘 잡으셔서 큰 변경없이 요구사항을 구현하셨네요! 👍 
몇 가지 피드백을 남겼으니, 확인하셔서 반영해주세요!

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingCar.java
> +public class RacingCar implements Comparable<RacingCar> {
Comparable 활용 👍

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/view/InputValidator.java
> +                .allMatch(carName -> RacingCar.validateCarName(carName));
현재 객체의 인스턴스를 생성하기 전에 검증하고 있습니다.
인스턴스가 생성되기 전에 검증한다면 생성된 `RacingCar` 인스턴스는 항상 유효한 이름을 가진 인스턴스라는 것을 보장할 수 있지 않을까요?

2020-12-08 16:52 UTC, hongsii commented on src/test/java/racingcar/domain/RacingCarsTest.java
> +        assertThat(racingCars.getParticipatingCars().size()).isEqualTo(4);
assertj 검증문을 활용해도 좋을 것 같아요 ~!

```suggestion
        assertThat(racingCars.getParticipatingCars()).hasSize(4);
```

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingRound.java
>      public List<RacingCar> getRacingCars() {
개인적으론 getter와 같이 로직이 없고 상대적으로 중요도가 떨어지는 메서드는 클래스의 하단에 배치하는 것이 좋다고 생각해요.
이렇게 함으로써 클래스의 필드부터 로직을 가진 메서드가 한 눈에 들어와 어떤 책임을 지니고 있는지 이해하기가 더 쉽더라구요 :)

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingCars.java
> +            racingCars.add(new RacingCar(carNames.get(i)));
향상된 for문(for-each문)으로 바꿔보면 어떨까요?
index를 사용할 때 발생하는 문제를 줄일 수 있으며, 코드 가독성을 향상시킬 수 있습니다.

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingRound.java
> +    private static final String RACING_CAR_EMPTY_MESSAGE = "참가한 자동차 리스트가 비었습니다.";
클래스 변수와 인스턴스 변수 사이에 공백을 추가해보면 어떨까요?
가능하면 클래스를 구성하는 요소마다 공백으로 영역을 나눠주면 코드를 파악하기 더 좋을 것 같아요 :)

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingCar.java
> +        return other.getCarPosition() == this.carPosition;
같은 클래스는 getter 없이 필드 접근이 가능합니다.

```suggestion
        return other.carPosition == this.carPosition;
```

2020-12-08 16:52 UTC, hongsii commented on src/main/java/racingcar/domain/RacingCar.java
> +    public static boolean validateCarName(String racingCarName) {
메서드 간의 영역을 나눠 배치해보면 어떨까요?
클래스 메서드가 인스턴스 메서드 사이에 섞여 있어 인스턴스 메서드인 줄 알았네요.. ㅎ_ㅎ

2020-12-09 04:01 UTC, slamdunk7575 commented on src/main/java/racingcar/view/InputValidator.java
> +                .allMatch(carName -> RacingCar.validateCarName(carName));
아 그렇네요. 시홍님 말씀대로 `RacingCar` 생성과 함께 이름에 대한 유효성 검사를 하도록 수정하겠습니다 👍

2020-12-09 04:09 UTC, slamdunk7575 commented on src/test/java/racingcar/domain/RacingCarsTest.java
> +        assertThat(racingCars.getParticipatingCars().size()).isEqualTo(4);
수정해보겠습니다 😄

2020-12-09 04:25 UTC, slamdunk7575 commented on src/main/java/racingcar/domain/RacingRound.java
>      public List<RacingCar> getRacingCars() {
왜 확인을 못했는지..😱  수정해보겠습니다.

2020-12-09 04:27 UTC, slamdunk7575 commented on src/main/java/racingcar/domain/RacingCars.java
> +            racingCars.add(new RacingCar(carNames.get(i)));
수정해보겠습니다 😄

2020-12-09 04:28 UTC, slamdunk7575 commented on src/main/java/racingcar/domain/RacingRound.java
> +    private static final String RACING_CAR_EMPTY_MESSAGE = "참가한 자동차 리스트가 비었습니다.";
반영하겠습니다 👍

2020-12-09 04:30 UTC, slamdunk7575 commented on src/main/java/racingcar/domain/RacingCar.java
> +        return other.getCarPosition() == this.carPosition;
수정하겠습니다.

2020-12-09 04:31 UTC, slamdunk7575 commented on src/main/java/racingcar/domain/RacingCar.java
> +    public static boolean validateCarName(String racingCarName) {
위에서 피드백 주신 자동차 객체 생성시 유효성 검사를 하도록 수정하면서 
private 인스턴스 메소드로 변경했습니다 😄

2020-12-09 15:04 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘 해주셨네요!! 👍 
간단한 피드백만 하나 남겼으니 확인해주세요!
머지할게요. 다음 단계 진행해주세요~!

2020-12-09 15:04 UTC, hongsii commented on src/main/java/racingcar/domain/RacingCar.java
> +        this.carName = carName;
생성자별로 중복해서 검증 및 인스턴스 변수 할당을 하고 있습니다.
생성자를 재사용해보면 어떨까요?

2020-12-09 15:04 UTC, merged