"자동차 경주 - 단위테스트" 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #1725
Opened 2020-12-09 03:59 UTC by orgojy

안녕하세요. orgojy(안이민)입니다.
리뷰어님. 매번 꼼꼼히 봐주셔서 감사합니다.
마지막 하나까지도 코멘트로 집어주시는게 감동이네요. 👍 
이번 PR도 부탁드리겠습니다!

2020-12-10 15:19 UTC, hongsii requested changes
앗.. 이민님이 요청주신 PR을 놓쳐서 피드백이 늦어졌습니다.
앞으로는 요청주신 PR을 놓치는 일이 없도록 할게요. 죄송합니다 😥

4단계 요구사항 구현을 일급 콜렉션을 활용해 책임을 잘 나누셨습니다! 👍 
몇 가지 피드백 남겼으니 확인하셔서 반영해주세요!

2020-12-10 15:19 UTC, hongsii commented on src/test/java/carracing/domain/CarNameTest.java
> +        return provideNames(INVALID_NAME_SIZE, INVALID_NAME_SIZE + 10);
테스트 케이스는 가능하면 경계 범위의 값을 테스트하는 것이 효율적이라고 생각합니다 :)
현재 최대값에 대한 테스트만 있는데, 최소값의 테스트 케이스도 추가해보면 어떨까요?

2020-12-10 15:19 UTC, hongsii commented on src/test/java/carracing/domain/CarNameTest.java
> +    private static String provideName(int neededSize) {
👍

2020-12-10 15:19 UTC, hongsii commented on src/main/java/carracing/domain/CarName.java
> +        return nameLength >= MIN_NAME_SIZE && nameLength <= MAX_NAME_SIZE;
`!` 과 같은 논리 연산자는 `!i` 와 같은 비슷한 문자가 붙어 있는 경우 폰트에 따라 논리 연산자가 눈에 보이지 않을 수 있습니다.
그래서 논리 연산자보다 not의 의미가 들어간 메서드명을 짓는다면 이러한 부분에서 가독성도 좋아지고, not을 반대로 치환해서 생각하지 않아도 되기 때문에 코드를 읽기가 더 좋더라구요 ㅎㅎ

2020-12-11 01:18 UTC, orgojy commented on src/main/java/carracing/domain/CarName.java
> +            throw new IllegalArgumentException("자동차의 이름은 1이상 5이하 글자가 입력되어야합니다.");
네 말씀에 정확히 동의합니다. 제가 놓쳤네요. 감사합니다.

2020-12-11 01:35 UTC, orgojy commented on src/main/java/carracing/CarRacingGame.java
> +    private List<CarName> convertCarNames(String carNames) {
고민했던 부분인데, 말씀해주셔서 다시 생각해보니 말씀이 맞네요.

2020-12-11 04:06 UTC, orgojy commented on src/main/java/carracing/domain/CarName.java
> +        return nameLength >= MIN_NAME_SIZE && nameLength <= MAX_NAME_SIZE;
코드로 풀어보려는 노력보다는 말씀하신대로 애초에 명확하게 이름을 짓게되면 생각의 단계가 적게 들어서 이해하기 쉽겠네요. 👍

2020-12-11 12:37 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘 해주셨네요! 👍 
머지할게요! 다음 단계 진행해주세요 :)

2020-12-11 12:37 UTC, merged