Step5 자동차 경주  리팩토링
next-step/java-racingcar pull request #1730
Opened 2020-12-09 15:15 UTC by deviscreen

step4의 피드백을 반영하고, step5의 리팩토링을 했습니다.

2020-12-10 03:18 UTC, ohtaeg requested changes
안녕하세요 대윤님!
마지막 미션도 리팩토링을 잘해주셨어요!! 👍 
몇 개의 피드백을 드렸는데 마지막으로 한번만 더 반영하시면 좋을 것 같아
해당 미션을 잘 끝맺음을 하실 수 있을 것 같아 Request chages 하였습니다!

마지막 한 번의 피드백을 반영해주신 후 재요청 주시면 감사하겠습니다!
마지막 한걸음 남았네요 화이팅입니다 🔥

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/RacingMain.java
> +        for(int i = 0; i < tryNumber; i++){
```suggestion
        for (int i = 0; i < tryNumber; i++) {
```

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/Car.java
> +    }
파라미터 앞부분은 공백으로 띄어져 있네요 😭 
공백을 제거해주시면 좋을 것 같아요! 그다음 파라미터가 끝나는 부분과 블록 시작 "{" 사이에는 공백을 넣어주시면 좋을 것 같아요 :)
```suggestion
    public Car(String name) {
        this.name = name;
    }
    public Car(String name, int totalMeter) {
        this.name = name;
        this.allMeter = totalMeter;
    }
```

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/Car.java
>  //    private Display display;
해당 주석은 제거해주세요 ㅎㅎ

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/Car.java
> +    }
Comparator를 위함이라면 메서드도 좋지만 Comparator를 구현해주시면 어떨까요 :) ?

`public class Car implements Comparator<Car> {`

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/ParticipateCars.java
> +            if(car.totalMeter() == maxTotalMeter){
```suggestion
        cars.forEach(car -> {
            if (car.totalMeter() == maxTotalMeter) {
```

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/CarRacing.java
> +        this.display = display;
생성자로 Display는 받지 않고있기에 굳이 인스턴스 변수로 가지지 않아도 될 것 같아요!
Display를 제거해주세요 ㅎㅎ

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/ParticipateCars.java
> +        throw new RuntimeException("자동차가 존재하지 않습니다.");
Optinal을 사용하지 않고 다음처럼 값을 구해볼 수 있을 것 같아요!
```suggestion
        return cars.stream()
                   .max(Car::compareMeter)
                   .map(Car::totalMeter)
                   .get();
```

2020-12-10 03:18 UTC, ohtaeg commented on src/main/java/racing/domain/ParticipateCars.java
> +        if (winners.size() > numOfWinnerOption || winners.size() == numOfWinnerOption) {
winners.size()가 중복해서 호출되고 있네요!
지역 변수로 호출한 값을 가지도록 하여 중복을 제거해보면 좋을 것 같아요!

2020-12-10 15:18 UTC, deviscreen commented
ParticipateCarTest에서 @BeforeEach에서 participateCars 객체를 만들고 이후에 전체 테스트를 해보니 createCar메서드에서 만들었던 3개의 이름이createCarNumberTest 메서드안의 participateCars가 중복으로 만들어져서 
createCarNumberTest에서는 참여한 차들의 수가 3으로 체크를 했는데 6으로 나와서 테스트가 깨지게 되는데 이럴 경우에는 어떻게 하는 방법이 좋을까요 ??

2020-12-11 06:25 UTC, ohtaeg approved these changes
많이 바쁘심에도 불구하고 끝까지 미션을 완료하신걸 축하드립니다 🎉 
다음 로또 미션도 끝까지 해보시면 좋을 것 같아요!! 👍 

제가 드린 피드백들은 정답이 아니지만 대윤님께 조금이나마 도움이 되었으면 하는 바램입니다!
그동안 고생 많으셨습니다 🙇 
코로나 조심하시구 건강하시길 바랄께요!! 😄

2020-12-11 06:25 UTC, ohtaeg commented on src/main/java/racing/domain/Car.java
> +        return 0;
다음과 같이 변경해도 좋을 것 같아요 :)
```suggestion
       Integer.compare(this.allMeter, otherCar.allMeter);
```

2020-12-11 06:25 UTC, ohtaeg commented on src/main/java/racing/domain/Car.java
>      private String name;
접근 권한을 최소화 하면 어떤 장점이있을까요 :) ?
[이펙티브 자바 규칙 15 - 접근 권한을 최소화 해라](https://jinseongsoft.tistory.com/204)

2020-12-11 06:25 UTC, ohtaeg commented on src/test/java/racing/domain/ParticipateCarsTest.java
>          assertThat(participateCars.getCars().size()).isEqualTo(3);
> ParticipateCarTest에서 `@beforeeach`에서 participateCars 객체를 만들고 이후에 전체 테스트를 해보니 createCar메서드에서 만들었던 3개의 이름이createCarNumberTest 메서드안의 participateCars가 중복으로 만들어져서
createCarNumberTest에서는 참여한 차들의 수가 3으로 체크를 했는데 6으로 나와서 테스트가 깨지게 되는데 이럴 경우에는 어떻게 하는 방법이 좋을까요 ??

해당 현상이 발생하는 이유는 ParticipateCars의 멤버가 정적 변수라서 발생하는 현상입니다!
이미 클래스로더에 의해 메모리에 적재된 상태에서 createCar() 테스트로 인해 메모리에 3개의 차가 들어가있는 상태에서
createCarNumberTest() 테스트시 정적 변수를 공유함으로 인해 3개의 차가 들어간 상태에서 또 3개의 차가 추가되어
6개로 되는 현상입니다!

ParticipateCar가 꼭 static 변수를 가져야할지 고민해보시면 좋을 것 같아요 :)

2020-12-11 06:26 UTC, merged

2020-12-11 07:47 UTC, deviscreen commented on src/main/java/racing/domain/Car.java
> +        return 0;
> 다음과 같이 변경해도 좋을 것 같아요 :)
> ```suggestion
>        Integer.compare(this.allMeter, otherCar.allMeter);
> ```

이런 방법도 있었네요 !! 감사합니다