Step4 : 자동차 경주(우승자)
next-step/java-racingcar pull request #1741
Opened 2020-12-10 08:32 UTC by nawhew

코드리뷰 부탁드립니다 :)
[feat: 이름이있는 자동차 처리 구현] 커밋부터 step4입니다.
이전 커밋은 step3에서 머지와 함께 코드리뷰 해주신부분을 고친 부분입니다.
감사합니다 :)

2020-12-11 04:54 UTC, kang-hyungu requested changes
위환님 4단계 미션 구현하느라 수고하셨어요
좀더 설계를 바꿔보면 좋을 부분에 피드백 남겼어요
수정해보시고 리뷰 재요청주세요
궁금한 점 생기면 dm 남기시거나 코멘트 남겨주세요!

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/InputView.java
> +    public RacingCarDriver inputCarAmount() {
사용하지 않는 메서드는 정리해주세요

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/InputView.java
> +    public String[] makeParticipantsList(String inputs) {
```suggestion
    public List<String> makeParticipantsList(String inputs) {
        return Stream.of(inputs.split(InputView.SPLIT_REGEX))
                .map(String::trim)
                .collect(Collectors.toList());
    }
```

Stream을 활용하시면 코드를 좀더 깔끔하게 작성할 수 있습니다

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/NamedRacingCar.java
> +public class NamedRacingCar extends RacingCar{
상속을 할 필요가 있을까요?
상속은 코드 복잡도를 높이니 정말 필요한 상황이나 객체가 잘 설계된 상황이 아니면 안쓰는게 좋습니다
RacingCar 클래스에 name 필드를 추가하는걸 권장합니다

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/NamedRacingCarDriver.java
> +public class NamedRacingCarDriver extends RacingCarDriver{
상속을 없애고 RacingCarDriver에 코드에 기능 추가하는걸 추천드립니다

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/rule/FixedRacingRule.java
>  public class FixedRacingRule implements RacingRule{
```suggestion
public class FixedRacingRule implements RacingRule {
```
클래스명과 중괄호 사이에 띄어쓰기는 꼭 넣어주세요
코딩 컨벤션입니다

2020-12-11 04:54 UTC, kang-hyungu commented on src/main/java/racingcar/rule/FixedRacingRule.java
> +    private static final int MAX_VALUE = 9;
왜 이 상수가 생겼을까요?
RandomRacingRule 클래스에는 RANDOM_BOUND와 어떤 다른 점이 있는걸까요?
두 상수 모두 게임규칙에 해당되는 값입니다
게임 규칙이 다른 클래스에 각각 쓰이고 있으면 규칙이 바뀔 때마다 클래스 2개를 수정해야됩니다
RacingRule을 구현한 클래스가 추가될 수록 추가해야될 클래스도 늘어나겠죠
게임 규칙이 적용되는 객체는 어느 객체인가요?
RacingCar 객체가 이동 가능 범위를 알고 있으면 RacingCar가 추가되거나 게임 규칙이 바껴도 수정되야할 범위가 줄어들거에요
isWithinRange 메서드도 같이 옮겨야겠네요

2020-12-11 07:23 UTC, nawhew commented on src/main/java/racingcar/InputView.java
> +    public RacingCarDriver inputCarAmount() {
삭제하였습니다~

2020-12-11 07:25 UTC, nawhew commented on src/main/java/racingcar/rule/FixedRacingRule.java
>  public class FixedRacingRule implements RacingRule{
네 변경하였습니다

2020-12-11 07:25 UTC, nawhew commented on src/main/java/racingcar/NamedRacingCar.java
> +public class NamedRacingCar extends RacingCar{
상속하지 않고 기존 RacingCar에 추가하여 변경하였습니다

2020-12-11 07:26 UTC, nawhew commented on src/main/java/racingcar/NamedRacingCarDriver.java
> +public class NamedRacingCarDriver extends RacingCarDriver{
상속하지 않고 기존 RacingCar에 추가하여 변경하였습니다

2020-12-11 09:24 UTC, nawhew commented on src/main/java/racingcar/InputView.java
> +    public String[] makeParticipantsList(String inputs) {
Stream을 활용하도록 변경하였습니다~

2020-12-11 12:23 UTC, nawhew commented on src/main/java/racingcar/rule/FixedRacingRule.java
> +    private static final int MAX_VALUE = 9;
상수의 중복 제거 및 메서드를 이동시켰습니다

2020-12-11 13:22 UTC, kang-hyungu requested changes
위환님 4단계 구현하신 내용 확인했습니다
좀더 챙겨보면 좋을 부분에 피드백 남겼어요
적용해보시고 리뷰 재요청주세요
궁금한 점은 코멘트 남기시거나 dm 주세요!

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/RacingCarDriver.java
> +        } else {
프로그래밍 요구사항
* else 예약어를 쓰지 않는다.
    * 힌트: if 조건절에서 값을 return하는 방식으로 구현하면 else를 사용하지 않아도 된다.
    * else를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/InputView.java
> +        return new RacingCarDriver(RacingCarDriver.createRacingCars(
List<String>을 RacingCarDriver 생성자에 전달하면 되지 않을까요?
RacingCarDriver.createRacingCars 메서드가 필요할까요?

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/RacingCar.java
> +    private String name;
```suggestion
    private final String name;
```

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/RacingCar.java
> +import racingcar.rule.RacingRule;
모든 클래스에서 사용하지 않는 import 구문들은 정리하는게 좋습니다

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/RacingCar.java
>      public int getDistance() {
getter는 하단으로 위치 시켜주세요
메서드 노출 순서는 생성자 먼저, 그리고 클래스 주요 로직을 수행하는 메서드, getter 순서로 정렬해주세요
private은 호출된 public 메서드 다음에 정렬해도 좋고 제일 하단으로 위치시켜도 괜찮습니다

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/ResultView.java
> +    private List<String> getWinner(RacingCarDriver racingCarDriver) {
이 메서드는 뷰 객체에서 처리하면 안됩니다
ResultView는 출력에 관련된 책임만 가지고 있어야 합니다
우승자를 뽑는 기능은 어느 객체에서 처리하면 좋을까요?

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/ResultView.java
>  public class ResultView {
void printResult(RacingCarDriver racingCarController)

메서드는 사용하지 않으면 삭제하는게 좋겠네요

2020-12-11 13:22 UTC, kang-hyungu commented on src/main/java/racingcar/ResultView.java
>  public class ResultView {
ResultView에서 winners 인스턴스 변수를 제거하면 이 객체는 상태(인스턴스 변수)를 갖지 않게 됩니다
상태가 없는 객체의 모든 메서드는 static으로 처리하면 성능상 이점을 얻을 수 있습니다.

2020-12-11 14:14 UTC, nawhew commented on src/main/java/racingcar/RacingCarDriver.java
> +        } else {
기본적인것인데 습관이 무섭네요.. 수정하였습니다!

2020-12-11 14:18 UTC, nawhew commented on src/main/java/racingcar/RacingCar.java
> +    private String name;
변경하였습니다!

2020-12-11 14:35 UTC, nawhew commented on src/main/java/racingcar/ResultView.java
>  public class ResultView {
네 삭제하였습니다~

2020-12-11 15:07 UTC, nawhew commented on src/main/java/racingcar/ResultView.java
> +    private List<String> getWinner(RacingCarDriver racingCarDriver) {
RacingCarDriver에서 처리하도록 변경하였습니다!

2020-12-11 15:20 UTC, nawhew commented on src/main/java/racingcar/ResultView.java
>  public class ResultView {
winner 처리를 RacingCarDriver로 옮기니 자연스럽게 상태를 갖지 않게 되어 모든 메서드를 static으로 변경하였습니다.
대신 이런 경우 인스턴스 변수가 추가되지 않을 것으로 예상 될 때만 성능을 위해 바꾸어야 하는것이죠?

2020-12-12 04:42 UTC, nawhew commented on src/main/java/racingcar/InputView.java
> +        return new RacingCarDriver(RacingCarDriver.createRacingCars(
기존에 List로 받는 생성자가 있어서 만들었었는데, 더이상 사용하지 않아서 말씀해주신 것 처럼 변경하였습니다.
해당부분을 연장해서 계속 생각하다보니 1급 콜렉션을 쓰도록 리팩토링 하게 되었습니다.

2020-12-12 04:43 UTC, nawhew commented on src/main/java/racingcar/RacingCar.java
>      public int getDistance() {
네 메소드 위치도 우선순위를 생각하면서 위치시키도록 하겠습니다

2020-12-12 07:38 UTC, kang-hyungu commented on src/main/java/racingcar/ResultView.java
>  public class ResultView {
객체 성격에 따라 다를텐데 인스턴스 변수가 있지만 static 메서드로 처리하는 경우도 있습니다
현재 객체는 콘솔 출력만 하기 때문에 모든 메서드가 static으로 처리해도 문제가 없는 상황입니다

2020-12-12 07:49 UTC, kang-hyungu approved these changes
위환님 피드백 반영 잘 하셨어요 👏 
추가로 남긴 피드백은 다음 단계 진행하면서 적용해보아요
pr 머지하겠습니다. 수고하셨습니다!

2020-12-12 07:49 UTC, kang-hyungu commented on src/test/java/racingcar/RacingCarTest.java
> +        assertThatThrownBy(() -> {
https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion

위 문서에서 예외 케이스 테스트를 다시 점검해보면 좋을 것 같습니다

2020-12-12 07:49 UTC, kang-hyungu commented on src/main/java/racingcar/domain/Winner.java
> +    public List<String> getWinner(RacingCars racingCars) {
이 메서드의 로직이 너무 복잡하지 않나요?
RacingCars 클래스에 아래 코드를 추가해서 winner를 뽑을 수도 있습니다
RacingCars 객체가 List<RacingCar> racingCars 변수를 직접 관리하기 때문에 불필요한 getter 사용을 줄일 수 있습니다

```java
        int max = racingCars.stream()
                .max(Comparator.comparingInt(Car::getPosition))
                .map(Car::getPosition)
                .orElseThrow(RuntimeException::new);

        List<RacingCar> winners = racingCars.stream()
                .filter(car -> car.getPosition() >= max)
                .collect(Collectors.toList());
```

2020-12-12 07:50 UTC, merged

2020-12-12 13:53 UTC, nawhew commented on src/test/java/racingcar/RacingCarTest.java
> +        assertThatThrownBy(() -> {
예외 케이스 테스트는 given-when-then 구조로 어떻게해야 하는지 몰랐는데, 알려주신 문서를 보고 알게되었습니다.