Step4
next-step/java-racingcar pull request #1761
Opened 2020-12-13 13:24 UTC by monds

리뷰 요청드립니다. 😄

2020-12-13 15:16 UTC, young891221 requested changes
미션 반영 잘 해주셨네요 👍 
간단한 피드백만 남겼습니다. 확인 부탁드립니다.

2020-12-13 15:16 UTC, young891221 commented on src/main/java/racing/domain/CarContext.java
> +public class CarContext {
불필요한 클래스같습니다. 특별히 만든 이유가 있을까요? Car의 Getter 역할뿐이라서요.

2020-12-13 15:16 UTC, young891221 commented on src/main/java/racing/domain/CarContext.java
> +public class CarContext {
만약, 불필요하다면 삭제 부탁드립니다:)

2020-12-14 12:52 UTC, monds commented on src/main/java/racing/domain/CarContext.java
> +public class CarContext {
View 에서 race의 결과를 출력할 때 BiConsumer 로 distance와 name을 주려다가 자동차의 속성 확장성을 고려하여 Consumer<Car> 를 줄까 고민했습니다. 근데 Car를 전달하면 view에서 move를 재호출 할수도 있다고 생각해서 속성만 접근 가능한 context를 만들었습니다.

2020-12-14 12:53 UTC, monds commented on src/main/java/racing/domain/CarContext.java
> +public class CarContext {
사실 불필요한 클래스이긴 한데 속성 접근만 허용 하기 위해 만들어봤습니다.

2020-12-15 13:25 UTC, young891221 commented on src/main/java/racing/domain/CarContext.java
> +public class CarContext {
네, 의도는 인지하였지만 불필요한것 같습니다. 속성이 추가될때 마다 n개의 접근용 getter가 추가되는 형식이라 개선해야 하는 코드로 보여집니다. 삭제하여 처리하도록 수정해 주세요ㅎㅎ

2020-12-17 06:11 UTC, young891221 approved these changes
리뷰 반영 감사합니다:)
머지할게요~!

2020-12-17 06:11 UTC, merged