[11번가.정다은] 문자열 계산기, 자동차 경주 미션
next-step/java-racingcar pull request #1804
Opened 2021-01-22 03:43 UTC by jeongdaeun98

2021-01-22 11:47 UTC, KimDoubleB requested changes
다은님, 조금 늦은 것 같아 죄송한 마음이 앞서네요. 
이러한 죄송한 마음을 가지고 코드를 더 꼼꼼히 보려고 노력했습니다 !!

코드를 보며 제 모자란 부분을 깨닫게 되었던 것 같습니다. Stream의 활용법, enum 사용이라던지, 설계 방식이라던지 보면서 너무나도 많이 배울 수 있었습니다 ! 보면서 궁금한 점들을 적어 놓았었는데, 같이 이야기하면서 더 배워나갔으면 좋겠습니다 !

2021-01-22 11:47 UTC, KimDoubleB commented on src/main/java/calculator/RequestInput.java
> +    public CalculationInfo convertToCalculationInfo(String[] inputArray, int index, Integer total) {
여기서 질문을 드리고 싶은게 있습니다 ~!

파라미터 중 `int index`와 `Integer total`은 같은 정수형 데이터인데 Primitive type과 Wrapper class를 따로 나눠서 사용하신 이유가 있나요~?

최근 공부하며 오토 언박싱으로 인한 성능하락에 대해 볼 수 있었는데요. 이러한 부분을 고려하신 것인지 궁금해 질문드립니다 !
- 제가 공부했던 문서는 [여길](https://docs.oracle.com/javase/8/docs/technotes/guides/language/autoboxing.html) 참조해주세요 !

2021-01-22 11:47 UTC, KimDoubleB commented on src/main/java/calculator/Operator.java
> +
감명 받은 코드였습니다.
enum을 활용해 operator를 정의하고 있는 것과 내부에서 operator에 대한 검증을 하고 있는 부분도 정말 재밌게 봤습니다 👍

2021-01-22 11:47 UTC, KimDoubleB commented on src/main/java/calculator/CalculationInfo.java
> +    private Operator operator;
그레이들에 롬복이 추가되어 있어서 '롬복을 어떻게 활용하셨을까?'하는 궁금증이 있었는데, 여기였군요 !
저도 아직 공부중이지만 이렇게 활용되는 부분을 볼 수 있어 재미있게 보았던 것 같습니다 💯 

앗, `CalculationInfo` 클래스와 더불어 `Calculator`, `CalculatorUtils` 클래스들이 다 나뉘어져있던 것을 볼 수 있었는데요 ! 혹시 나눴던 과정에 대한 이야기를 들어볼 수 있을까요? 
- 저는 단순히 '계산기' 라고 문제에서 접할 때부터 '계산기 클래스를 구현하고 내부에 관련 기능을 넣어야지' 라는 생각으로 설계를 하고 개발을 했는데, 이렇게 나눠서 구현을 했다는 것이 새롭고 신기해서 이렇게 질문드립니다 ~!

2021-01-22 11:47 UTC, KimDoubleB commented on src/main/java/racingcar/Game.java
> +    }
Stream을 활용하여 깔끔하게 작성한 것이 너무나도 보기 좋았고, 저도 이런 식으로 사용해봐야겠다는 생각이 들었습니다.
아직 Stream을 공부하고 있는데, Stream을 통해 이렇게 간결히 작성할 수 있다니 얼른 더 많이 공부해봐야겠다는 생각이 듭니다 👍 
또한, return형으로 이렇게 함수를 엮어 간결히 담아내니 더 보기 좋은 것 같습니다 💯

2021-01-22 11:47 UTC, KimDoubleB commented on src/test/java/calculator/ValidateUtilsTest.java
> +    }
저도 테스트 코드의 인풋을 적는데 Array를 사용해야해서 데이터 인풋을 하나 씩 넣는 `ParameterizedTest`와 `ValueSource`를 사용하기엔 한계가 있었습니다. 하지만 인풋을 다 따로 생성하고, 그것에 대해 테스트를 돌리는 것은 작성하기도 힘들고, 추후 테스트를 확인할 때도 불편하다고 생각했는데요. 

그래서 좀 찾아본 결과 `MethodSource`를 찾을 수 있었습니다. 조금 어떻게보면 복잡하기도 하지만 복잡한 데이터도 인풋으로 넣어 반복된 코드를 제거할 수 있다는 점에서 정말 좋은 것 같습니다. 여기 부분에 `MethodSource` 한 번 적용해보시면 어떨까요?
- `MethodSource`의 경우, Argument를 정의할 때 Stream을 사용하고 있는데요. 다은님이 저보다 더 잘 활용하시니, 더 빠르게 이해하실 것 같습니다 :)
- 만약 수정하시게 되실 경우, InputValidatorTest.java 의 `validateCarName` 테스트도 수정해보시면 연습하시는데 도움이 되실 것 같습니다.

제가 구현하며 참조했던 사이트는 [여기](https://www.baeldung.com/parameterized-tests-junit-5#6-method )입니다. `MethodSource` 말고도 테스트에서 다양한 인풋을 넣는 법을 설명하고 있으니 도움 될 것 같습니다 ^-^

2021-01-22 13:39 UTC, jeongdaeun98 commented on src/main/java/calculator/ValidateUtils.java
> +        for (int i = Constant.OPERATOR_START_INDEX; i < inputArray.length; i += 2) {
자동 정렬을 하다보니 이부분은 신경을 쓰질 못했네요ㅎㅎ 봐주셔서 감사합니다 : ) !!

2021-01-22 13:47 UTC, jeongdaeun98 commented on src/main/java/calculator/ValidateUtils.java
> +    }
오 제가 생각하지 않았던 부분들을 짚어주셔서 감사합니다ㅎㅎ!!!
- 맞습니다! 그게 좋을 거 같아요 : ) print를 통해 오류 메시지를 알려서 사용자에게 다시금 input을 요청하는 것이 더욱 친절할 거 같아요!
- 
```
validateInputSize(input.length),validateAppropriateOperator(input),validateOperand(input)
```
이 부분은 제가 생각했던 건 예외상황에 대한 처리를 validateInput에서 하려다보니 통일성이 없어졌던 거 같습니다~ 이 부분도 통일성이 있게 문제가 있으면 예외, 없으면 true를 리턴하는 것도 좋겠지만 실제로 validateInput을 호출하는 구간에서(do-while문이라ㅎㅎ) 예외 상황에 대한 처리를 하기가 까다롭다보니 이렇게 하게 되었습니다 :)

2021-01-22 13:51 UTC, jeongdaeun98 commented on src/main/java/calculator/RequestInput.java
> +    public CalculationInfo convertToCalculationInfo(String[] inputArray, int index, Integer total) {
오 오토 언박싱으로 인한 성능하락에 대해서는 잘 모르고 있었는데 자료 공유해주셔서 감사합니다 :)
원시타입과 레퍼 클래스로 나누게 된 것은, converToCalculationInfo를 호출할 때 파라미터 내 값으로 String타입의 값을 Integer.parseInt(value) 로 변형하여 넘기게 됩니다! 그래서 나누게 되었습니다~

2021-01-22 13:52 UTC, jeongdaeun98 commented on src/main/java/calculator/Operator.java
> +
면접 공부할 때 enum타입이 타입 안정성을 보장해준다고 하여 이번 프로젝트에 직접 사용해봤는데 편리하더라고요~!
앞으로도 자주 사용하게 될 거 같습니다 :)

2021-01-22 13:56 UTC, jeongdaeun98 commented on src/main/java/calculator/CalculationInfo.java
> +    private Operator operator;
이렇게 나누게 된 계기는 
- CalculationInfo라는 클래스는 계산기 정보 로써 실제로 계산할 때 필요한 정보들을 포함하고 있는 클래스 라는 느낌을 확실하게 주고 싶었습니다~ 
- CalculatorUtils같은 경우 실제 연산을 하는 함수는 광범위하게 쓰일 거 같아 유틸리티로 빼게 되었습니다 :)
- Calculator는 패키지 이름과 동일하게 하여 가장 먼저 개발자가 이 클래스에 진입하여 main함수를 볼수있게(?) 유도하기 위해 나누었습니다ㅎㅎ

2021-01-22 13:57 UTC, jeongdaeun98 commented on src/main/java/racingcar/Game.java
> +    }
저도 스트림에 대해 이번에 문경님을 통해 알게되었는데 직접 사용해보니 보기가 깔끔했습니다 :) 함께 공부합시다ㅎㅎㅎ

2021-01-22 13:59 UTC, jeongdaeun98 commented on src/test/java/calculator/ValidateUtilsTest.java
> +    }
오 감사합니다!! 안그래도 인풋을 다 따로 생성하여 굉장히 테스트하기 불편하다는 생각이 들었는데 MethodSource를 활용한다면 매우 간편한 테스트를 할 수 있을 거 같습니다 👍 정말 좋은 리뷰해주시고, 또 제가 모르는 부분들을 짚어주시고, 좋은 자료 공유해주셔서 감사합니다!!!

2021-01-23 03:06 UTC, merged

2021-01-23 03:07 UTC, KimDoubleB commented
더 완벽하게 작성하신 것 같습니다 !
수고 많으셨습니다 ~ !