splite study test
next-step/java-racingcar pull request #1830
Opened 2021-03-01 13:29 UTC by whdudtlr9042

2021-03-01 13:59 UTC, ghojeong reviewed
안녕하세요 조무건 님 이번 미션 리뷰어를 맡게된 고정완(ghojeong) 입니다. 👻
만나서 반갑습니다. 🙇

수요일부터 본격적으로 수업을 시작하는데, 일찍 PR 을 주셨네요 :clap:
수요일에는 PR 을 어떻게 올려야할지, 그리고 과제는 어떻게 진행하면 좋을지에 대한 본격적인 소개가 수업으로 있을 예정입니다.
아직 과제 요구사항을 충족하지 않은채로, PR 을 처음 시도해 보신 것 같습니다.
(타이틀이 "splite" study test 라고 오타가 생겨버렸네요.)
8주 동안의 기나긴 여정을 대비해서, 수요일까지 푹 쉬시고 재충전하시는 것도 좋을 것 같습니다. :lollipop:

궁금하신 사항 있으시면 부담 갖지 마시고 언제든 DM이나 문의 주세요. :wink:

2021-03-01 13:59 UTC, ghojeong commented on src/test/java/study/StringTest.java
> +    }
무슨 테스트를 하고 있는지에 대한 설명을 주석이 아니라, `@DisplayName` 을 사용해 표시해보는 것은 어떨까요?
나중에 테스트가 실패했을 때, 무슨 테스트가 실패한 것인지 추적이 더 용이하답니다!

2021-03-02 23:27 UTC, ghojeong commented
혹시나 1 커밋 당 1 PR 을 올려야 한다고 알고 계실까봐 확인차 여쭈어봅니다.
(처음 PR 올리시는 분들 중에 헷갈려 하시는 분들도 있으셔서요)
과제 요구사항을 구현한 여러 커밋들을 한꺼번에 올려서 PR 을 올리고는 합니다.

<img width="1625" alt="스크린샷 2021-03-03 오전 8 25 04" src="https://user-images.githubusercontent.com/38595650/109728694-0b815d80-7bfa-11eb-8a77-e6a74c0ebbd5.png">

그리고 타이틀 오른쪽의 Edit 버튼을 누르면 splite 오타를 고칠 수 있답니다!

2021-03-03 01:05 UTC, javajigi requested changes
1단계 - 학습테스트 실습의 모든 요구사항이 구현되지 않았네요.
모든 요구사항을 완료하고 push한 후 다시 리뷰요청해주세요.

2021-03-03 05:07 UTC, whdudtlr9042 commented
안녕하세요! 제가 처음에 가이드 자료를 오해해서 PR을 바로 요청했습니다.

그래서 이전에 요청했던 PR들을 취소하고 싶은데 기능이 따로 없을까요??
PR은  요구사항 전부 끝낸 뒤에 다시하고 싶어서요.


그리고 말씀대로 오타부분은 제가 git ammen을 사용해서, 제꺼 레파지토리에는 수정되어있는데

[image: image.png]

 PR은 제가 새로 푸쉬를 안해서 오타인게 그대로 같습니다.
제가 여태 gitlab 만 쓰다가 gitHub는 아직 익숙하지가 않아서 ㅜㅜ

음 두서가 길었지만 제가 하고싶은애기는

1. 이전에 요청했떤 pr은 취소가 안될까요?
2. 요구사항 완료했을때 그냥 추가로 커밋 하고 PR 요청하는게 좋겠죠??



2021년 3월 3일 (수) 오전 8:27, Pyro(고정완) <notifications@github.com>님이 작성:

> 혹시나 1 커밋 당 1 PR 을 올려야 한다고 알고 계실까봐 확인차 여쭈어봅니다.
> (처음 PR 올리시는 분들 중에 헷갈려 하시는 분들도 있으셔서요)
> 과제 요구사항을 구현한 여러 커밋들을 한꺼번에 올려서 PR 을 올리고는 합니다.
>
> [image: 스크린샷 2021-03-03 오전 8 25 04]
> <https://user-images.githubusercontent.com/38595650/109728694-0b815d80-7bfa-11eb-8a77-e6a74c0ebbd5.png>
>
> 그리고 타이틀 오른쪽의 Edit 버튼을 누르면 splite 오타를 고칠 수 있답니다!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/next-step/java-racingcar/pull/1830#issuecomment-789297834>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APLQBTLD6UIKFGLS6TOYKBDTBVX6FANCNFSM4YMRMOCA>
> .
>

2021-03-04 02:10 UTC, ghojeong commented
> 1. 이전에 요청했떤 pr은 취소가 안될까요?
> 2. 요구사항 완료했을때 그냥 추가로 커밋 하고 PR 요청하는게 좋겠죠??

### 1. 이전에 요청했떤 pr은 취소가 안될까요?

`Close with Comment` 라는 버튼 을 누르면, PR 을 닫는게 가능합니다.

### 2. 요구사항 완료했을때 그냥 추가로 커밋 하고 PR 요청하는게 좋겠죠??

PR 은 요구사항을 전부 완료하고 나서, 혼자서는 더 이상 추가 작업을 할 게 없을 때 PR 요청을 하는게 좋습니다.

현재 생각나는 선택지는 2가지입니다.

1. 현재 PR 을 close 하고 요구사항을 모두 충족한 새로운 PR 을 올린다.
2. 현재 PR 을 close 하지 않고, 현재의 브랜치에 마저 요구사항을 충족한 커밋들을 push 한다.

이 이외에도, 하고 싶은 방향으로 요구사항을 충족해서 PR 을 해주세요.

2021-03-07 07:51 UTC, whdudtlr9042 commented
Step1 요구사항 충족 후 푸쉬했습니다!

2021-03-07 12:18 UTC, ghojeong requested changes
<img width="1090" alt="스크린샷 2021-03-07 오후 9 17 21" src="https://user-images.githubusercontent.com/38595650/110239514-9364c000-7f8a-11eb-9466-bb0e30f3757e.png">

제 로컬에서 돌려보니, 테스트를 전부 통과하고 있지 못한듯 한데 한번 확인해 주시면 감사하겠습니다.
그리고 리뷰 요청할 때는 nextstep 홈페이지에서 "리뷰 요청" 버튼을 꼭 눌러주세요.
제가 메일을 놓칠 때도 있어서요.

2021-03-07 16:39 UTC, whdudtlr9042 commented
1. StringTest 경고 원인 
 - witeMessage() 메소드를 호출할때, StringIndexOutOfBoundsException 의 기본 에러 메세지(detail message) 포멧을 지키지 않아서 발생한것으로 이해하고 있습니다. 
 - Exception 상속으로 인해 발생한것 같은데, AssertJ에서 equals 체크하는것으로 보입니다 <- 이부분은 정확히 확인하지 못하여 추정하고 있습니다. 
 
 개인적으로 원하는 메세지를 출력하고 싶어서 extra를 추가하였습니다. 
- try catch 문으로 강제적으로 발생했는데 그외 좀더 간결한 문법이 있는지 고민하고있습니다.

2. SetTest 오류는 지문을 잘못 이해하여 파라메터를 int값을 넣어야하는데 true 로 입력하여 발생했습니다.

2021-03-08 00:13 UTC, ghojeong approved these changes
요구사항이 모두 훌륭하게 반영된 것을 확인했습니다.
다음 미션을 진행하러 가시죠! :octocat:

2021-03-08 00:13 UTC, merged