[자동차경주 - 3단계] 리뷰요청 드립니다.
next-step/java-racingcar pull request #1884
Opened 2021-03-03 15:25 UTC by JuJinPark

안녕하세요 리뷰어님 😄 😄😄 😄
너무 혼자 고민하기보다는 빠르게 리뷰를 받고자 몇가지 고민하는 부분이 있는데 리뷰요청드립니다.
그리고 저번에 보내준 pr에 대한 의견도 남겼습니다.

제가 이번 미션에서 아직 고민되는 부분입니다.
-랜덤한 숫자 만들기(RandomNumberGenerator)에 대한 테스트는 어떻게 구현해야 할까요? 지금 수준이 괜찮은가?
-화면에 출력에 필요한 문구들을 Message라는 enum으로 만들었는데 응집도가 낮아보이고 다국어를 지원하려면 어떤방식이 좋을까 고민됩니다.
-테스트가 어디까지 적절한 수준일까? 예)자동차 이동의 핵심인 RacingCar.move()는 테스트를 해지만 이를 감싸고 있는 RacingCarList.move()에 대한 테스트는 작성하지 않았습니다. RacingCarList.move()도 필요한건가?
-단지 테스트를위한 추상화는 옳은가? 현재 요구상황에서는 RandomNumberGenerator을 추상화한 인터페이스는 딱히 필요가 없는데 테스트를 위해 추상화를 하게 되었습니다.이게 테스트가 이끄는 좋은 설계로의 변화인 건가요?
-FixedNumberGenerator,FixedMovingStrategy 와 같은 class들은 테스트 이외에는 필요없는 클래스인데 생성하는게 옳은가?

이번 리뷰도 잘 부탁드립니다.🙇🙇🙇

2021-03-04 00:02 UTC, neojjc2 commented
#tag @neojjc2

2021-03-04 04:41 UTC, neojjc2 requested changes
안녕하세요 주진님 🙇 

3단계 구현 잘 해주셨습니다 💯 💯 💯 💯 💯 

4단계 요구사항이 좀 섞여 있는 것 같습니다 😅 
이 부분 다시한번 확인해주시면 감사하겠습니다 🙇 

질문 주신 내용 및 개선되면 좋을 것 같은 부분 
의견 드렸습니다 🙇 

확인 부탁 드리겠습니다 🙇 

그럼 재 리뷰요청 기다리고 있겠습니다 😄 
진행 하시다가 궁금하시거나 고민 되는 부분 있으시면 언제든 DM이나 코멘트 남겨주세요 ✋

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCarGame.java
> +    private RacingCarList participatingRacingCarList;
생성과 동시에 초기화 되는 부분이기도 하고 명시적으로 재 할당을 막기 위해 `final`로 선언하시는건 어떨까요??
코드 전체적으로 `final`로 선언하면 좋은 부분들이 보입니다 😄 
이 참에 한번 정리하고 가시면 좋을 것 같습니다 🙇 

도움 되실만한 내용 공유 드립니다 🙇 
> https://blog.lulab.net/programming-java/java-final-when-should-i-use-it/

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCarGame.java
> +        if(isDone()) throw  new IllegalStateException("game is over");
```
if (isDone()) { 
    throw  new IllegalStateException("game is over");
}
```

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCarList.java
> +        racingCarList=carNameList.stream().map(RacingCar::new).collect(Collectors.toList());
람다식 활용 좋습니다 👍 💯 

저 같은 경우엔 람다식 같은경우 가독성 확보를 위해 아래와 같이 사용합니다 😄 
이 부분은 참고만 부탁 드립니다 🙇 
```
racingCarList = carNameList.stream()
                .map(RacingCar::new)
                .collect(Collectors.toList());
```

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCarList.java
> +    public void move() {
참가한 자동차들을 모두 이동시키는 역할 좋습니다 💯 👍

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCarList.java
> +    private List<RacingCar> racingCarList = new ArrayList<>();
이 부분도 생성자에서 초기화가 되기 때문에 굳이 객체 생성까진 필요 없어 보입니다 😄 
그리고 `final` 이면 더 좋을 것 같습니다 🙇

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +        return new Random().nextInt(maxValue+1-minValue) + minValue;
`minValue`, `maxValue`을 주신 이유와 NumberGenerator를 추상화 하신 이유를 여쭤봐도 될까요?? 🤔 
(테스트 코드 때문이시라면 위에서 의견 드렸습니다 🙇 )

요구사항은
> 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
입니다 😄 

그냥 Random으로 0~9까지 나오게 한 수가 4이상일 경우 `true`를 `MovingStrategy`에 구현하면 좋을 것 같은데

어떻게 생각하시나요?? 😄 
이 부분 개선 검토 부탁 드립니다 🙇

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/dto/CarScore.java
> +public class CarScore {
DTO 사용 좋습니다 💯 👍

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/dto/FinalScoreBoard.java
> +    public void add(int playCountNumber,List<CarScore> carScoreList){
`public void add(int playCountNumber, List<CarScore> carScoreList){`

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/dto/FinalScoreBoard.java
> +    private List<ScoreBoardPerPlay> scoreList = new ArrayList<>();
이 부분도 `final` 로 선언되면 좋을 것 같습니다 🙇

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/view/InputView.java
> +    private final BufferedReader br;
물론 `BufferedReader`도 좋지만 훨씬 더 사용하기 편하도록 Wrapping 및 개선된 클래스가 있습니다 😄 
요 내용 참고 부탁 드립니다 

`private static final Scanner SCANNER = new Scanner(System.in);`

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/view/InputView.java
> +        while(true){
`while (true) {`

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/view/Message.java
> +public enum Message {
`Enum` 을 이용하여 Message를 관리하시려는 아이디어 좋습니다 💯 
하지만 매번 `getDescription()`으로 message를 꺼내야만 하는 불편함이 있어 비효율 적(?)으로 느껴지셔서
고민하셨을 것 같습니다 😅 

아래와 같은 객체도 하나의 대안이 될 수 있을 것 같습니다 😄 

```
package racingcar.view;

public final class MessageConstant {
    public static final String INPUT_CAR_NAME = "자동차 이름을 쉼표(,)로 구분하여 입력해주세요.";
    public static final String INPUT_PLAY_COUNT = "시도할 회수는 몇 회 인가요?";
    public static final String WRONG_INPUT = "잘못입력 하셨습니다.";
    public static final String FINAL_RESULT = "실행 결과";
}

System.out.println(MessageConstant.FINAL_RESULT); // 처럼 사용 가능 
```

그리고 이참에 `Enum`에 대해서도 한번 정리하고 가시면 좋을 것 같습니다 
> https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

그리고 다국어에 대해서도 질문 주셨는데,
일단 이번 미션에서 다국어는 범위 밖 이라서 😅 
하지만 그 정도까지 고민하신 깊이와 열정이 💯💯💯💯💯 🔥 

의견을 드리자면, 
다국어를 지원하기 앞서 
요청할 때 (여기에서는 게임을 실행하는 사용자) 언어 정보를 얻어와야 합니다 😄 
해당 게임(서비스)을요청할 때 language 정보를 알아와야 (그게 아니라면 국가 정보라도) 그
에 맞는 언어 셋을 제공해 줄 수 있으니까요 😄 

그리고 message 관련 부분은 모두 key로 정의 한 후에
ResultView에서 구성할 때 언어셋 정보에 맞는 셋을 가져와서 key에 해당하는 
언어셋 value를 렌더링 하는 방식으로 구현 하면 될 것 같습니다 😄 

방법이야 다양하게 많은데 이번 미션에서는 다국어까지는 지원하지 않아도 되서 😅 

고민이 해결 되셨으면 좋겠습니다 🙇

2021-03-04 04:41 UTC, neojjc2 commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
굳이 생성자가 필요해 보이지는 않는데, 정적 메소드로 한번 개선해보시는 건 어떨까요?? 😄 

도움 되실 만한 내용 공유 드립니다 🙇 
> https://mygumi.tistory.com/253

2021-03-04 12:39 UTC, JuJinPark commented on src/main/java/racingcar/domain/NumberGenerator.java
> +public interface NumberGenerator {
좋은 의견 감사합니다.🙇🙇
제 생각에는 NumberGenerator 인터페이스를 제거하게 되면 DecidingNumberBasedMovingStrategy가 4라는 숫자를 기준으로 isMovable를 결하는지를 테스트 할 수 있을까요?
가령 1이 random으로 선택됬을때  isMovable이 적절하게 값이 나오는지를 체크가 필요하지 않을까요?

2021-03-04 12:58 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCar.java
> +        this(name,new DecidingNumberBasedMovingStrategy());
제가 이해한게 맞다면 외부에서 자동차 객체의 움직임을 통제 할 수 있어야 한다가 맞을까요?🤔🤔🤔
만약 외부에서 통제가 필요하다면 RacingCarList객체를 통해서 모든 자동차는 제어 되어야 된다고 생각합니다.
neojjc2님께서 언급하신 상황이라면 RacingCarList.stop() 이러던지 이런 api로 통제되어야 하지 않을까요?🤔🤔 
moving strategy는 어떻게 움직일까를 표현한거에 더 가깝지 않을까요?(물론 안움직일수도 있지만 .😅😅.)

리뷰어님은 어떻게 생각하시나요?
그리고 또 질물은 하자면 지금 요구상황에서는 외부에서 자동차 객체의 움직임을 통제하는 상황이 필요해 보이지 않아 구현을 하지 않았습니다. 설계를 할때마다 고민이지만 도대체 어디까지가 오버엔지니어링이고 어디까지가 적절한 미래에 변화에 대비한 추상화 일까요? ㅠㅠㅠㅠ

2021-03-04 13:31 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCarList.java
> +    public void move() {
아 그렇게 테스트 하면 되겠군요😄😄😄
감사합니다.🙇🙇🙇
테스트를 위한 조언 정말 감사합니다. 
테스트를 많이 해서 익혀야 겠네요스트 하면 되겠군요😄😄😄
감사합니다.🙇🙇🙇
테스트를 위한 조언 정말 감사합니다. 
테스트를 많이 해서 익혀야 겠네요 ㅠㅠ

2021-03-04 14:19 UTC, JuJinPark commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +        return new Random().nextInt(maxValue+1-minValue) + minValue;
처음에는 무작위로 움직일지 말지를 결정하는 RandomMovingStrategy class를 처음에는 만들었습니다. 하지만 계속 생각해보니 램던번호를 생성하는 책임과 움직임을 결정하는 책임 이렇게 두가지를 한 객체가 지니고 있다고 느껴습니다. 그래서  번호를 생성하는 책임은 NumberGenerator로 분리하였습니다. 
그리고 현재 그럴일은 없어 보이지만  😅 😅 향후 다른 곳에서도 숫자 생성에 사용할 수 있게끔 유연성을 가지기 위해 min max 를 입력받도록 하였습니다. 

리뷰어 님은 어떻게 생각하시는 지요?😄

2021-03-04 14:37 UTC, JuJinPark commented on src/main/java/racingcar/view/Message.java
> +public enum Message {
좋게 봐주셔서 감사합니다.  😄 😄
제가 알고있기론 상수를 저렇게 쓰는 방식은 좋지 않도고 알고 있습니다. 
혹시 string인 경우에는 다른가요? 
> https://madplay.github.io/post/use-enums-instead-of-int-constants

2021-03-04 14:46 UTC, JuJinPark commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
만약 유틸성 클래스였다면 망설임 없이 정적메소드로 사용했을 것 같습니다.
하지만 저는  ResultView 객체는 RacingGame의 결과를 필요하다면 적절히 가공하여 유저에게 보여주는 역할을 한다고 생각했습니다.  정적메서드를 통해 유틸성으로 제공하기에는 여러곳에서 사용시 유연성도 떨어지고 어색해보입니다.
FinalScoreBoard를 받는 생성자를 추가 하면 제 의도가 더욱 확실해 질까요?

리뷰어 님은 어떻게 생각하시나요 ??😄😄

2021-03-04 14:47 UTC, JuJinPark commented on README.md
> +  * 게임에 사용할 자동차 이름, 시도 횟수를 사용자에게 입력받는다
반영하였습니다. 😄 😄 😄

2021-03-04 14:47 UTC, JuJinPark commented on src/main/java/racingcar/domain/DecidingNumberBasedMovingStrategy.java
> +    private static final int DECIDING_NUMBER=4;
반영하였습니다. 😄 😄 😄

2021-03-04 14:47 UTC, JuJinPark commented on src/main/java/racingcar/domain/DecidingNumberBasedMovingStrategy.java
> +    private static final int MAX_RANDOM_NUM=9;
반영하였습니다. 😄 😄 😄

2021-03-04 14:47 UTC, JuJinPark commented on src/main/java/racingcar/domain/DecidingNumberBasedMovingStrategy.java
> +    private static final int MIN_RANDOM_NUM=0;
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/DecidingNumberBasedMovingStrategy.java
> +      this(new RandomNumberGenerator(MAX_RANDOM_NUM,MIN_RANDOM_NUM));
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/DecidingNumberBasedMovingStrategy.java
> +        return (numberGenerator.generate()>=DECIDING_NUMBER);
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/FixedMovingStrategy.java
> +public class FixedMovingStrategy implements MovingStrategy {
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/FixedNumberGenerator.java
> +public class FixedNumberGenerator implements NumberGenerator {
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/FixedNumberGenerator.java
> +    private final int NUMBER;
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/MovingStrategy.java
> +public interface MovingStrategy {
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCar.java
> +        if(movingStrategy.isMovable())  travelledDistance++;
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCarGame.java
> +    private RacingCarList participatingRacingCarList;
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCarGame.java
> +        if(isDone()) throw  new IllegalStateException("game is over");
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCarList.java
> +        racingCarList=carNameList.stream().map(RacingCar::new).collect(Collectors.toList());
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCarList.java
> +    private List<RacingCar> racingCarList = new ArrayList<>();
반영하였습니다. 😄 😄 😄

2021-03-04 14:48 UTC, JuJinPark commented on src/main/java/racingcar/dto/FinalScoreBoard.java
> +    public void add(int playCountNumber,List<CarScore> carScoreList){
반영하였습니다. 😄 😄 😄

2021-03-04 14:49 UTC, JuJinPark commented on src/main/java/racingcar/dto/FinalScoreBoard.java
> +    private List<ScoreBoardPerPlay> scoreList = new ArrayList<>();
반영하였습니다. 😄 😄 😄

2021-03-04 14:49 UTC, JuJinPark commented on src/main/java/racingcar/view/InputView.java
> +    private final BufferedReader br;
반영하였습니다. 😄 😄 😄

2021-03-04 14:49 UTC, JuJinPark commented on src/main/java/racingcar/view/InputView.java
> +        while(true){
반영하였습니다. 😄 😄 😄

2021-03-05 04:48 UTC, neojjc2 approved these changes
다소 많은 의견을 드렸는데 반영 해주시느라 정말 수고 많으셨습니다 🙇 
고민하시는 부분에 대해서는 추가적으로 의견 드렸습니다 😄 

다음 미션 진행 하시면서 
하나씩 답을 찾아나가보면 좋을 것 같습니다  🙇 

이만 merge 하겠습니다 🙇

2021-03-05 04:48 UTC, neojjc2 commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
> ResultView 객체는 RacingGame의 결과를 필요하다면 적절히 가공하여 유저에게 보여주는 역할을 한다고 생각

맞습니다 👍 💯

개인적인 의견을 드리자면, **유틸성 클래스 인 것과 정적메소드 사용은 서로 관련이 없다**고 생각합니다 😄 
유틸성이란 얼마나 범용적으로 추상화 되고 디자인 되었는지 여부로 판단 된다고 생각합니다 
(유틸성 클래스 중에서도 정적메소드를 제공하지 않는 클래스들이 많습니다. 유틸성 = 정적메소드 는 아니라고 생각합니다)

공유드린 내용에도 보면 정적메소드에 대해서 아래와 같이 정리 되어 있는데요, 

> 만약 유틸리티 클래스로 작성되고, 변화를 가정하지 않는다.
만약 메소드가 인스턴스 변수를 사용하지 않는다.
인스턴스 생성에 의존하지 않는다.
메소드가 공유되고 있다면, 정적 메소드로 추출해낼 수 있다.
메소드가 변화되지 않고, 오버라이딩 되지 않는다.

꼭 유틸성, 편의성 때문에 의견 드린건 아닙니다 😅 

다른 관점에서  의도를 강화 하기 위해 `FinalScoreBoard`를 생성자에 추가 하신다고 하셨는데, 
그렇게 된다면 저 위에 주진님께서 생각하신 의도를 어긋나게 됩니다 

지금은 `RacingGame` 의 결과를 출력하기 위해 `FinalScoreBoard` 하나만을 지원하지만 
출력하기 위한 결과 `DTO`들이 늘어나게 되는경우 굳이 `FinalScoreBoard`는 필요 없음에도 불구하고
사용하는 쪽에서는 해당 객체가 있어야 만이 `ResultView`를 사용할 수 있게 됩니다 😅 

고민에 도움 되셨으면 좋겠습니다 🙇

2021-03-05 04:58 UTC, neojjc2 commented on src/main/java/racingcar/domain/RacingCar.java
> +        this(name,new DecidingNumberBasedMovingStrategy());
네네 맞습니다 `RacingCarList` 를 통해 제어되는 설계는 잘하셨습니다 😄 
다만 멈추어야 한다는 예를 드린게 멈추는 기능이 필요하다의미가 아니라, `RacingGame`이 어떻게 진행되어야 하는지에 대한 룰 
즉 moving stragegy를 결정하는게 역할과 책임 관점에서 RacingGame`이면 어떨까 에 대한 의견이었습니다 😄 
(지금은 moving stragegy가 `RacingCarList`에서 결정되고 있습니다)
* RacingCarList는 List에 속한 RacingCar들을 동일한 룰로 움직이는 역할
* RacingGame은 RacingCarList를 어떤 룰로 움직일지 결정 

이라는 관점으로 의견 드린겁니다 😄 
제가 너무 고민스럽게 해드린게 아닌가 염려됩니다 😭

2021-03-05 04:59 UTC, merged

2021-03-05 09:34 UTC, JuJinPark commented on src/main/java/racingcar/domain/RacingCar.java
> +        this(name,new DecidingNumberBasedMovingStrategy());
추가 의견 정말 감사합니다.🙇🙇🙇
저도 리뷰어님께서 주신 질문을 보고 특정 룰을 기반으로 움직임이 결정 된다면 RacingGame에서 결정해야 겠네요 ㅎㅎ
이부분 추가 미션을 통해 필요하다면 변경하겠습니다.
꼼꼼한 리뷰 정말 감사드립니다.😭😭

2021-03-05 09:41 UTC, JuJinPark commented on src/main/java/racingcar/view/Message.java
> +public enum Message {
저는 Enum으로 생성시 저는 String 상수들(언어 셋)은 저 자체로 어떠한 연산 하지않는다고 알고있나
추후에 누군가가 실수로 연산과 같은 작업을 하지 않을까 더 우려했던거 같습니다.
무조건 상수 사용시 enum이 답은 아니다 라는 의견을 통해 또 배워갑니다. 🙇🙇🙇🙇

2021-03-05 10:06 UTC, JuJinPark commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
정적메소드는 유틸성 클래스에서만 보통 쓴다고 생각했는데... 😅
이번기회를 통해 명확하게 짚고 넘어 갈수있어 정말 감사합니다. 🙇🙇
ResultView의 형태는 리뷰어님 의견 유념해서 미션이 진행됨에 따라 결정하겠습니다.
제가 평가하기는 조금 그렇지만 리뷰에서 짚어주시는 부분들 너무너무 좋아요 ㅎㅎ👍 💯👍 💯