문자열 계산기 리뷰 요청드립니다.
next-step/java-racingcar pull request #1924
Opened 2021-03-05 13:45 UTC by wooyonghwa

안녕하세요. 문자열 계산기 리뷰 요청드립니다.

Exception 처리를 저렇게 해주어도 될까요? 

그리구 단위테스트가 익숙치가 많은 고민을 해보았는데 많은 지적 부탁드립니다.

감사합니다~

2021-03-06 03:52 UTC, JunilHwang requested changes
안녕하세요! 문자열 계산기 구현 잘 해주셨네요  👏👏👏

다만, 객체지향 생활체조에 위배되는 내용이 있습니다.
이 외에도 몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드려요!

2021-03-06 03:52 UTC, JunilHwang commented on src/main/java/study/Operations.java
> +        }
for/if가 중첩되지 않도록 작성해주세요! 제일 간단한 방법 중 하나가 메소드로 분리하는 것입니다.

2021-03-06 03:52 UTC, JunilHwang commented on src/main/java/study/Operations.java
> +    }
줄바꿈 처리가 필요할것 같아요!

2021-03-06 03:52 UTC, JunilHwang commented on src/main/java/study/Operations.java
> +    DIVIDE("/",(a,b)->a/b);
```suggestion
    PLUS("+", (a, b) -> a + b),
```
가독성을 조금 더 신경쓰면 좋을 것 같습니다~

2021-03-06 03:52 UTC, JunilHwang commented on src/main/java/study/Operations.java
> +        return this.biFunction.apply(leftOperand,rightOperand);
```suggestion
        return biFunction.apply(leftOperand, rightOperand);
```
this는 생략해도 무방할 것 같아요!

2021-03-06 03:52 UTC, JunilHwang commented on src/test/java/study/StringCalculatorTest.java
> +        }
for/if가 중첩되지 않도록 작성해주세요!

2021-03-06 04:10 UTC, wooyonghwa commented on src/main/java/study/Operations.java
> +    }
혹시 어느 부분에서 줄바꿈을 처리해야할까요?? 메소드 파라미터가 길어서 그런건가요?? 아니면 클래스 변수와 생성자 간의 간격을 주어야하는건가요??

2021-03-06 04:13 UTC, wooyonghwa commented
> 안녕하세요! 문자열 계산기 구현 잘 해주셨네요 👏👏👏
> 
> 다만, 객체지향 생활체조에 위배되는 내용이 있습니다.
> 이 외에도 몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드려요!

넵!! 다른분들 pr을 참고했을때도 부족한 부분들이 많이 있더라구요 다시 적용하고 피드백 요청드리겠습니다!

2021-03-07 07:43 UTC, wooyonghwa commented
안녕하세요 ~
다시 한번 작성해보았습니다~
과제를 진행하며 궁금했던점들에 대해 질문좀 드리겠습니다.

첫번째로, git commit 메세지를 고려해서 작성해보았습니다. 익숙치 않아서 그런데 이렇게 하는게 맞을까요?

두번째로, if 중첩문을 안쓰기 위해서 메소드를 분리하라고 힌트를 주셨는데.. 제가 생각한 메소드 분리로는 해결이 되지 않더라구요. 그래서 stream을 결국 사용했는데 다른 방법도 사용해보려 했는데 잘 되지 않았네요.. 혹시 다른 접근 방법이 또 있을까요?

감사합니다.

2021-03-07 11:52 UTC, JunilHwang approved these changes
안녕하세요, 용하님!
피드백 반영 잘 해주셨네요.

개인적으로 스트림을 사용하는게 더 좋다고 생각합니다 ㅎㅎ

문자열 계산기는 여기서 머지하겠습니다.
이제 본격적으로 자동차 미션 수행하러 가봅시다 🚗🚗🚗! 화이팅 💪

2021-03-07 11:52 UTC, merged