[자동차 경주 - 2단계] 문자열 계산기 리뷰요청 드립니다.
next-step/java-racingcar pull request #1926
Opened 2021-03-05 13:51 UTC by w-beom

안녕하세요. 문자열 계산기 코드 작성하여 리뷰요청 드립니다!

calculate 메소드에서 좀 더 분리를 할 수 있지 않은가 싶은데 감이 도저히 안 잡히더라구요..

1. parseInt하는 부분도 Validator의 책임이 맞을까요..?
2. 짜면서도 무엇을 모르는지 모르니깐 질문도 무엇을 해야할지 모르겠습니다..ㅠㅠ

리뷰 잘 부탁드립니다..!

2021-03-05 15:36 UTC, ghojeong requested changes
전반적으로 굉장히 잘 구현해 주셨습니다!
특히 enum 을 능숙하게 사용하셔서 깜짝 놀랐네요. 🎉 
로컬에서 테스트를 직접 돌려보니, 통과하지 못하는 테스트가 하나 존재하는 듯 하여,
사소한 픽스를 요청드립니다.

<img width="965" alt="스크린샷 2021-03-06 오전 12 11 56" src="https://user-images.githubusercontent.com/38595650/110135980-7efdb780-7e12-11eb-8bd8-c0c4195df567.png">

#### 1. parseInt하는 부분도 Validator의 책임이 맞을까요..?

저는 개인적으로, 특정 객체가 이 역할을 맡는지 고민이 될 때에는, 무조건 2개의 다른 객체로 나누는 것을 추천드립니다.
책임이 맞을까라는 고민을 한다는 것 자체가, 그 객체의 책임과 역할이 (최소한 코드를 작성한 본인이 보기에) 명확하지 않는 상황이라고 생각합니다.
저라면 저런 고민을 하게 된다면, Parser 와 Validator 라는 서로 다른 2개의 다른 클래스로 나눌 것 같습니다.
(물론 어떤 분들은 로직이 매우 작으므로, 나중에 로직이 커지면 나누자고 할 수도 있습니다. 본인이 생각하기에 더 합리적이라고 생각되는 방법을 택하세요.)

#### 2. 짜면서도 무엇을 모르는지 모르니깐 질문도 무엇을 해야할지 모르겠습니다..ㅠㅠ

괜찮습니다! 일단 요구사항을 구현할 수 있도록 집중하세요.
질문들은 저희 리뷰어 분들이 코드를 읽으며 해드립니다.
어쩌면 자신이 무엇을 더 모르는지 모르는 부분까지, 코드를 고심해서 작성하셨다는 뜻이니깐 오히려 대단하시네요.
앞으로도 자신이 무엇을 모르는지 모를 때까지, 코드를 고심하고 수정하는 태도를 유지하시면 엄청나게 성장하시리라 생각합니다. (대신, 이런 완벽주의를 유지하려 하면 엄청 힘드실 겁니다. ㅋㅋ)

2021-03-05 15:36 UTC, ghojeong commented on src/main/java/step2/Operator.java
> +    MUL("*",(a,b) -> a*b);
와! 이미 enum 을 사용하실 줄 잘 알고 계시군요.
OperatorInterface 를 따로 정의하신 점 인상깊습니다. 👍

2021-03-05 15:36 UTC, ghojeong commented on src/main/java/step2/Operator.java
> +                .filter(o -> o.operator.equals(param))
o 와 같은 축약 변수명은 사용하시지 않기를 권장드립니다.

2021-03-05 15:36 UTC, ghojeong commented on src/main/java/step2/OperatorInterface.java
> +    int apply(int a,int b);
```suggestion
    int apply(int a, int b);
```

사소한 지적이지만, IDE 의 auto format 기능을 이용하고 계시지 않은듯 한데,
IntelliJ 의 auto format on save 관련 기능들을 검색해서 사용해보시기를 권장드립니다.
저는 개인적으로 [Save Actions](https://plugins.jetbrains.com/plugin/7642-save-actions) 플러그인을 애용합니다.

2021-03-05 15:36 UTC, ghojeong commented on src/main/java/step2/Calculator.java
> +            leftNumber = Operator.getOperator(token[i]).apply(leftNumber,rightNumber);
<img width="430" alt="스크린샷 2021-03-06 오전 12 20 06" src="https://user-images.githubusercontent.com/38595650/110135332-bd46a700-7e11-11eb-801d-d65705a748b1.png">

객체지향향 생활 체조 원칙의 `규칙 4: 한 줄에 점을 하나만 찍는다.` 를 지켜주세요.

2021-03-05 15:36 UTC, ghojeong commented on src/test/java/step2/CalculatorTest.java
> +                }).withMessage("사칙연산 기호가 아닙니다.");
Validator.java 에서 IllegalArgumentException 예외처리를 직접 해주시고,
이를 테스트하시는 부분 매우 인상 깊습니다. 👍 
조금만 더 욕심을 부리자면, Integer.parseInt 가 실패했을 경우에 대한 예외처리도 추가하면 좋을 것 같습니다.

2021-03-05 15:41 UTC, w-beom commented on src/main/java/step2/Operator.java
> +    MUL("*",(a,b) -> a*b);
Enum은 다행히도 접할 기회가 있었어 가지고 조졸두님이 쓰신 Enum글을 읽어보았던 기억으로 또 참고하면서 작성해보았습니다!

2021-03-05 15:41 UTC, w-beom commented on src/main/java/step2/OperatorInterface.java
> +    int apply(int a,int b);
오 감사합니다!

2021-03-05 15:42 UTC, w-beom commented on src/main/java/step2/Operator.java
> +    MUL("*",(a,b) -> a*b);
혹시 OperatorInterface를 따로 작성하지 않고 이미 만들어져있는 BiFunction을 사용하는게 더 좋았을까요?

2021-03-05 15:49 UTC, ghojeong commented on src/main/java/step2/Operator.java
> +    MUL("*",(a,b) -> a*b);
저는 크게 상관 없다고 생각합니다.
어차피 나중에 BiFunction 과 같은 함수형 인터페이스는 사다리 타기 미션을 할 때 질리도록 하게 되니,
지금은 인터페이스를 직접 정의하는 편이 더 좋다고 생각합니다.
BiFunction 만 사용하신 분들 중에서는, 함수형 "인터페이스"와 익명 클래스 그리고 람다 사이의 상관관계를 이해하지 못하시는 분들도 있으셔서요.

2021-03-05 16:00 UTC, w-beom commented on src/main/java/step2/Operator.java
> +                .filter(o -> o.operator.equals(param))
람다식에서는 축약해서써도 될 줄 알았는데 아니였군요!

2021-03-05 16:19 UTC, w-beom commented on src/test/java/step2/CalculatorTest.java
> +                }).withMessage("사칙연산 기호가 아닙니다.");
넵 추가해보겠습니다!

2021-03-07 02:42 UTC, ghojeong commented
<img width="319" alt="스크린샷 2021-03-07 오전 11 40 50" src="https://user-images.githubusercontent.com/38595650/110227275-fed27180-7f39-11eb-8151-4b7df886c08e.png">


혹시 수정을 완료하셨다면, Re-request review 를 꼭 눌러주시기 부탁드립니다.
그러셔야 저에게 알림이 가서요.

2021-03-07 03:39 UTC, ghojeong approved these changes
피드백이 모두 훌륭히 반영된것을 확인했습니다.
승인 및 머지가 늦어져서 죄송합니다! 💯

2021-03-07 03:39 UTC, merged