Step2 리뷰 요청 드립니다.
next-step/java-racingcar pull request #1943
Opened 2021-03-06 09:53 UTC by tenmillionwon

안녕하세요. 2단계 리뷰 요청 드립니다.

1. 메서드 중 caculate() 메서드가 뭔가 깔끔하지 않은 것 같습니다. splitData안에 숫자와 연산자가 모두 들어가 있다보니 발생한 현상 같습니다.
List 2개를 만들어서, 숫자와, 연사자를 분리해서 저장을 하면 좋을것 같다는 생각은 들었는데, 어느 위치에서 분리를 해서 저장해야할지 잘 모르겠어서, 우선은 이렇게 작성하였습니다.

2. calculatorExecute에서는 if문으로 작성했는데, if문을 이렇게 많이 쓰면 안 좋은 방법인지, 또는 더 좋은 방법이 있는지 알고 싶습니다.

감사합니다.

2021-03-06 09:59 UTC, tenmillionwon commented
추가적으로, calculatorExecute 같은 경우 if문에 걸리지 않을 경우, 이미 앞에서 벨리데이션을 통해 4가지 기호만 있다고 생각했기 때문에 add를 리턴을 해줬습니다. 
그런데 한가지 궁금한 점이,  + 일경우도 if 문을 작성하고, if문에 걸리지 않을 경우 0으로 리턴해주는게 더 좋을지 궁금합니다.

2021-03-06 12:16 UTC, karian7 requested changes
테스팅 라이브러리를 잘 활용해 주셨네요! 👍👍
질문주신 내용 포함, 몇가지 코맨트를 남겨두었으니 확인해 보시고 개선해 보아요! 😀  

> 그런데 한가지 궁금한 점이, + 일경우도 if 문을 작성하고, if문에 걸리지 않을 경우 0으로 리턴해주는게 더 좋을지 궁금합니다.

선행로직에서 `operator` 가 +, -, *, / 만 존재하도록 체크하고 있기 때문에 다른 문자가 들어올 수 없는 상황이지만 이런 있을 수 없는 상황은 가정하기 보다 예외를 발생시키는것에 더 안전한 코드라고 생각합니다.

2021-03-06 12:16 UTC, karian7 commented on src/main/java/calculator/Calculator.java
> +		if (input == null || input.isEmpty() || input.equals(" ")) {
`String#isBlank` 에 대해 학습테스트를 만들어 보고 구현에 적용해 보아요.

[학습테스트란?](https://dodeoni.gitbook.io/study/toby-spring/2-unit-test/learning-test)

2021-03-06 12:16 UTC, karian7 commented on src/test/java/calculator/CalculatorTest.java
> +	@DisplayName("입력값 검증 : 사칙 연산 기호 체크")
꼼꼼한 테스트 👍

2021-03-06 12:16 UTC, karian7 commented on src/main/java/calculator/CalculatorApplication.java
> +	public static void main(String[] args) {
요구사항에 없는 main 까지 작성해 주셨군요 👍

2021-03-06 12:16 UTC, karian7 commented on src/main/java/calculator/Calculator.java
> +	private int calculatorExecute(int firstNumber, String operator, int secondNumber) {
> calculatorExecute에서는 if문으로 작성했는데, if문을 이렇게 많이 쓰면 안 좋은 방법인지, 또는 더 좋은 방법이 있는지 알고 싶습니다.

안좋은 방법은 아니라고 생각해요. 지금 단계에선 이정도도 충분하지만 더 나은 방법을 찾아보신다면 `enum` 을 활용해 볼 수 있습니다.

<details>
  <summary>힌트</summary>
enum 은 열거뿐만 아니라 다형성을 구현할 수 있습니다. enum 안에 스테틱이 아닌 맴버 필드와 메소드를 정의해 보세요.
</details>

2021-03-06 12:16 UTC, karian7 commented on src/test/java/calculator/CalculatorTest.java
> +		assertThatIllegalArgumentException().isThrownBy(() -> {
`assertThatIllegalArgumentException` 👍

2021-03-06 12:56 UTC, tenmillionwon commented on src/main/java/calculator/Calculator.java
> +		if (input == null || input.isEmpty() || input.equals(" ")) {
자바 8까지만 사용해봐서 isBlank란 메서드를 처음봤네요. 찾아보니 Java 11부터 사용할 수 있네요. 우선 java 11로 올려서 변경했습니다.

2021-03-06 13:01 UTC, tenmillionwon commented on src/main/java/calculator/Calculator.java
> +		if (input == null || input.isEmpty() || input.equals(" ")) {
isBlank를 활용할 수 없는 자바 8 환경이라면,  input.trim().isEmpty() 이렇게 활용해도 될까요?

2021-03-06 23:55 UTC, karian7 commented on src/main/java/calculator/Calculator.java
> +		if (input == null || input.isEmpty() || input.equals(" ")) {
아하! 8에선 못쓰는거였군요. 프로젝트가 8로 되어 있으니 trim을 활용하는게 좋겠습니다 😅

2021-03-07 02:10 UTC, tenmillionwon commented
@karian7 자바 8로 다시 변경 후 커밋했습니다. 확인 부탁드릴게요.

2021-03-07 12:13 UTC, karian7 approved these changes
안녕하세요! 호경님.
요청사항 모두 반영해 주셨네요 💯 👍 

문자열 계산기 단계는 여기서 머지하겠습니다. 이제 본격적인 자동차 미션인데요, 즐겁게 만들어 보아요~

2021-03-07 12:13 UTC, merged