[Step 2] 리뷰 요청 드립니다.
next-step/java-racingcar pull request #1945
Opened 2021-03-06 13:26 UTC by Donghui-Lee

CalculatorConst : 계산기 상수 클래스
CalculatorValidator : 계산기 유횽성 체크 클래스
Calculator : 계산기 클래스
CalculatorService : 계산기를 동작하기 위한 클래스

2021-03-06 14:04 UTC, dbeod2 requested changes
안녕하세요 동희님! 

2단계 미션 잘 구현해주셨습니다! 
테스트 코드도 잘 작성해 주셨네요 👍 

고민해보면 좋을 것 같은 부분이 있어 코멘트로 몇가지 남겨두었습니다.
확인부탁드립니다.

피드백 드린 부분 확인해보시고 다시 요청주세요!
기다리고 있겠습니다

2021-03-06 16:31 UTC, Donghui-Lee commented on src/main/java/study/step2/constant/CalculatorConst.java
> +
여러 곳에서 사용하기 위함이 목적이였는데 실제로는 한군대에서 사용하였네요....

다시 수정하고 진행하다보니 enum 클래스로 분리하면서 2군대에서 사용되어 일단은 유지하는 방향으로 push 하였습니다.

하나의 클래스에서 사용한다면 리뷰어님 말씀대로 사용되는 클래스에 선언하여 사용하도록 하겠습니다. :)

2021-03-07 01:53 UTC, dbeod2 approved these changes
안녕하세요. 
동희님! 

2단계 잘 작성해주셨네요! :) 
고민해보면 좋을 것 같은 부분이 있어서 코멘트만 남겨두겠습니다.

다음 미션을 위해 여기서 머지하도록하겠습니다.
감사합니다.

본격적인 자동차 미션 시작하시면 될 것 같아요! :) 🚗

2021-03-07 01:53 UTC, dbeod2 commented on src/main/java/study/step2/Calculator.java
> -    public int operate(String operator, int num1, int num2) {
BinaryOperator를 사용해 보시면 좋을 것 같습니다 :)

도움 될 만한 문서 공유드립니다.
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/BinaryOperator.html

2021-03-07 01:53 UTC, merged

2021-03-07 06:27 UTC, Donghui-Lee commented on src/main/java/study/step2/Calculator.java
> -    public int operate(String operator, int num1, int num2) {
넵 감사합니다 :)