Step2
next-step/java-racingcar pull request #1946
Opened 2021-03-06 14:27 UTC by jbh1024

리뷰 요청 드립니다 :)

2021-03-06 16:50 UTC, ohtaeg requested changes
안녕하세요 병훈님!
2단계 계산기 미션도 잘 구현해주셨어요 👍 
꼼꼼한 입력값 체크가 인상적이네요 💯 
몇 개의 피드백을 드렸는데, 다음 미션을 진행하시기전에 피드백을 반영하시면
좋은 경험이 되실 것 같아 Request changes 하였습니다!
피드백 반영 후 재요청 주시면 감사하겠습니다 :)

피드백에 대해 의논할 것이 있다면 언제든지 슬랙으로 연락주세요 😄 
남은 주말도 잘 보내시구 화이팅입니다 🔥

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    final HashSet<String> FOUR_RULE_OPERATOR_SET = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
참조 변수 타입을 인터페이스가 아닌 HashSet 구현체로 선언하신 이유가 있을까요 :) ?

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    final String DELIMITER = " ";
상수화 👍  
상수는 보통 static + final 키워드를 같이 선언해주시는게 컨벤션이오니 다음 링크를 확인해주시면 감사하겠습니다 :)
[왜 자바에서 final 멤버 변수는 관례적으로 static을 붙일까?](https://djkeh.github.io/articles/Why-should-final-member-variables-be-conventionally-static-in-Java-kor/)

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    }
계산 메서드의 가독성이 매우 좋네요 👍 👍

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +            result = operation(splitedInput[i], result, Integer.parseInt(splitedInput[i+1]));
```suggestion
        for (int i = 1; i < splitedInput.length; i += 2) {
            result = operation(splitedInput[i], result, Integer.parseInt(splitedInput[i + 1]));
```

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    }
다음 미션부터 아래와 같은 요구사항이 존재합니다..!

### else 예약어를 쓰지 않는다.
- 힌트: if 조건절에서 값을 return하는 방식으로 구현하면 else를 사용하지 않아도 된다.
- else를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.

해당 미션부터 해당 요구사항을 만족할 수 있도록 리팩토링 해보시면 좋은 경험이 될 것 같아요 :)
힌트를 드리자면 두가지 방법이 떠오르네요!

1. 각 연산에 맞게 계산하는 행위를 추상 클래스 혹은 인터페이스로 역할을 분리한 후 부모가 연산자를 판단해주고
각 연산을 수행하는 구현체들에게 연산을 위임하는 방법 
2. enum을 이용하여 연산을 수행하는 방법 [enum 활용기](https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html)

이 외에도 병훈님께서 생각하시는 다른 방법이 있다면 자유롭게 구현해주시면 좋을 것 같아요!
연산하는 행위를 StringCalculator가 수행해도 좋지만 다른 클래스에게 위임을 하면 어떤 장점이 있을지 고민해보아요 :)

[if를 피하고 싶어서](http://redutan.github.io/2016/03/31/anti-oop-if)

2021-03-06 16:50 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    private String[] checkParam(String input) {
꼼꼼한 체크..!! 💯 
아쉬운 부분은 해당 메서드의 메서드의 명을 보았을땐 입력값을 검증하는 기능만 수행할 것 같은데
구분자로 분리한 값도 반환하고 있습니다.
메서드 명을 통해 좀 더 명확하게 어떤 기능을 수행하는지 표현해주시거나
기능들을 메서드로 더 작게 분리하면 좋지 않을까 조심스럽게 의견을 드려봅니다..! 😄 

```
private String[] split(final String input) {
    isEmpty(input);
    
    final String[] inputs = input.split(DELIMITER);

    checkParam(inputs);

    return inputs;
}
```

2021-03-06 16:50 UTC, ohtaeg commented on src/test/java/stringCalculator/StringCalculatorTest.java
> +class StringCalculatorTest {
꼼꼼한 테스트 작성 👍

2021-03-09 14:52 UTC, jbh1024 commented on src/main/java/stringCalculator/StringCalculator.java
> +    final HashSet<String> FOUR_RULE_OPERATOR_SET = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
특별한 이유는 없지만 굳이 이유를 하나 꼽자면 사칙연산 외의 연산자 (ex. % < & )의 여부를 체크하기 위해서 set 을 사용하였습니다. 콜렉션에 contains method를 사용하기위해서 간편하게 체크하려고 했습니다 :)

2021-03-10 08:14 UTC, closed without merging

2021-03-10 10:03 UTC, ohtaeg commented on src/main/java/stringCalculator/StringCalculator.java
> +    final HashSet<String> FOUR_RULE_OPERATOR_SET = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
Set을 사용해주신 의도를 알려주셔서 감사합니다 👍 
그렇다면 다음과 같이 인터페이스 참조 타입으로 선언해도 괜찮을 것 같은데 구현체를 명시해주신 이유도 알려주실 수 있으신가요? 🙏 

```
final Set<String> FOUR_RULE_OPERATOR_SET = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
```

2021-03-10 15:49 UTC, jbh1024 commented on src/main/java/stringCalculator/StringCalculator.java
> +    final HashSet<String> FOUR_RULE_OPERATOR_SET = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
아!! 이부분은 제가 잘못 작성한것같습니다 ^^; 회사에서 빨리 PR 다시 해야지 하고 수정하느라 이 코멘트를 이제 확인했네요.. 맞습니다.. Set으로 했었어야했는데 구현체로 해버렸었네요..ㅠㅠ.. 특별한이유는 없습니다 ^^;;