Racing step3
next-step/java-racingcar pull request #1965
Opened 2021-03-07 14:18 UTC by wkdehdlr

[자동차 경주 3단계] 리뷰요청드립니다.

잘 부탁드립니다 :)

2021-03-08 14:20 UTC, vagabond95 requested changes
car list 를 Cars 클래스로 한번 더 묶어 개별 자동차에 대한 로직을 캡슐화 해주신 것이 인상적이었습니다 👍 

전반적으로 코멘트를 크게 드릴 부분이 없을만큼 잘 진행해주신 것 같습니다.ㅎㅎ
다만, 랜덤 테스트와 관련하여 고민해볼만한 지점이 있어 코멘트 남겼는데요, 같이 논의해보면 좋을 것 같습니다 :)

2021-03-08 14:20 UTC, vagabond95 commented on src/main/java/step3/ViewConstant.java
> +public class ViewConstant {
문자열 상수로 분리 👍

2021-03-08 14:20 UTC, vagabond95 commented on src/main/java/step3/Cars.java
> +    private final List<Car> cars;
자동차 리스트를 관리하는 클래스 추가 👍

2021-03-08 14:20 UTC, vagabond95 commented on src/test/java/step3/CarTest.java
> +    private void mockRandom(int input) {
mockRandom 이라는 네이밍과 달리 결과값은 랜덤하지 않고 input 에 의해 결정되고 있는데요, 다음과 같은 내용에 대해 고민해보시면 좋을 것 같아요!

1. 랜덤값을 테스트로 커버하는 것이 가능할까?
2. 가능하다면 이유가 무엇일지, 불가능하다면 대안은 무엇일지?

2021-03-08 15:06 UTC, wkdehdlr commented on src/test/java/step3/CarTest.java
> +    private void mockRandom(int input) {
```mockRandom``` 이라는 네이밍은 결과값을 랜덤하게 반환하기 위함을 나타낸 것이 아니었습니다.
Random 클래스를 mocking 한다는 의미로 네이밍했습니다.

랜덤값을 테스트로 커버하지 못하기 때문에 mock객체를 stubbing해서 사용했습니다.

테스트 목적은 랜덤값 자체가 아니라 랜덤값을 처리하는 비즈니스로직이라고 생각합니다.
우리는 결국 반환된 랜덤값을 이용해 비즈니스 로직을 수행할테고
이 비즈니스로직에 대한 테스트를 하는것이기 때문에 가능하다고 봅니다.
위 예제에서는 4미만, 4이상이라는 기준(비즈니스로직)이 있으니 
이 기준에 대한 테스트를 진행한다고 보면 될 것 같습니다.

2021-03-09 15:46 UTC, vagabond95 approved these changes

2021-03-09 15:46 UTC, vagabond95 commented on src/main/java/step3/Car.java
> +        return randomValue >= CarConstant.LIMIT;
Car 에서 움직임에 대한 rule 을 분리해볼 수 있을 것 같아요!

2021-03-09 15:46 UTC, vagabond95 requested changes

2021-03-09 15:46 UTC, vagabond95 commented on src/main/java/step3/Car.java
> +        return randomValue >= CarConstant.LIMIT;
Car 에서 움직임에 대한 rule 을 분리해볼 수 있을 것 같아요!

2021-03-11 12:58 UTC, wkdehdlr commented on src/test/java/step3/CarTest.java
> +    private void mockRandom(int input) {
[09b9c93](https://github.com/next-step/java-racingcar/pull/1965/commits/09b9c938c9e3c9635f5ddb4c18729213b03d15ad) 적용했습니다!

2021-03-11 12:58 UTC, wkdehdlr commented on src/main/java/step3/Car.java
> +        return randomValue >= CarConstant.LIMIT;
[09b9c93](https://github.com/next-step/java-racingcar/pull/1965/commits/09b9c938c9e3c9635f5ddb4c18729213b03d15ad) 적용했습니다!

2021-03-12 14:36 UTC, vagabond95 approved these changes
업무가 몰려 리뷰가 늦어지게 되었네요. 죄송합니다 😢 
전략 패턴을 적용해보시는 시도 좋습니다 👍 

다만, 랜덤값에 대한 의존성은 아직 남아있는 상태인데요. '랜덤한 값을 기준으로 판단하는 로직'자체를 하나의 전략으로 더 크게 본다면 테스트하기가 용이해질 것 같습니다 :)
다음단계 진행시 한번 고민해보셔도 좋을 것 같아요!

2021-03-12 14:37 UTC, vagabond95 approved these changes

2021-03-12 14:37 UTC, vagabond95 commented on src/main/java/step3/Limit4Strategy.java
> +public class Limit4Strategy implements LimitStrategy {
인터페이스와 구현체의 네이밍 차이가 거의 없는 것으로 보이는데요,
인터페이스를 더 추상적으로 네이밍하거나 구현체를 더 자세히 네이밍해보는 것은 어떨까요?

2021-03-12 14:37 UTC, merged