자동차 경주 - Step4
next-step/java-racingcar pull request #1986
Opened 2021-03-08 15:42 UTC by jhLim97

이전 step3의 마지막 피드백 반영했습니다!!

step3를 진행하면서도 계속 만족스럽지 못한 부분들이 있었고, UI와 비즈니스 로직을 분리하고 한 클래스내에 3개 이상의 인스턴스 객체를 갖지 않으려고 하다보니 구조변화가 필요하다 싶어서 많은 부분을 바꿔보았습니다. 
저번 단계에서 받은 피드백들을 최대한 반영하도록 노력해보았고 그로 인해 많은 부분을 공부할 수 있었던 것 같습니다 ㅎㅎ

바쁜 와중에도 열심히 피드백 주시느라 고생 많으시고 항상 감사드립니다!~

2021-03-09 03:44 UTC, yongdae requested changes
전 단계의 피드백 반영과 4단계 미션을 위해
전체적인 설계를 수정하셨네요. (🔥 - 🔥)

수고하셨습니다 ~

진행해주신 내용에대해 몇가지 의견 전달드렸습니다.
확인하시고 다시 리뷰 요청 부탁드리겠습니다. 😄

2021-03-09 03:44 UTC, yongdae commented on README.md
> +  * 단, 우승자는 한명 이상일 수 있다.
3단계에서 정의 된 요구사항에 대한 기능도 같이 정리하면 좋을 것 같아요 :)

2021-03-09 03:44 UTC, yongdae commented on src/main/java/racingcar/contoller/RacingCarController.java
> +    private static ResultView resultView = new ResultView();
static을 사용하시는 이유가 궁금합니다. 🤔

2021-03-09 03:44 UTC, yongdae commented on src/main/java/racingcar/domain/Car.java
> +    private String carName;
`carName` 대신 `name`을 써도 좋을 것 같아요. :)

클래스명을 통해 누구(Car)의 이름(name)인지를 안다고 생각한다면
중복된 의미를 지니는 carName 보다 name이 어울린다고 생각하는데 어떻게 생각하시나요?

2021-03-09 03:44 UTC, yongdae commented on src/main/java/racingcar/domain/Car.java
> +    public void updateByCondition(int number) {
updateByCondition 대신 updatePositionByCondition 같은 이름은 어떤가요?

2021-03-09 03:44 UTC, yongdae commented on src/main/java/racingcar/domain/Car.java
> +    public void isValidate(int number) {
이 부분도 isValidate 대신 positionValueValdation 어떨까요? 😄

2021-03-09 03:44 UTC, yongdae commented on src/test/java/racingcar/CarTest.java
>  class CarTest {
CarTest에 InputViewTest의 carNameCanUnder5 테스트를 포함시키면 어떨까요?

자동차 이름 길이의 제한은
'입력 받는 제한'이라기보단 '자동차에게 속한 제한'으로 보는게 더 좋을 것 같아요. :)

2021-03-09 03:44 UTC, yongdae commented on src/test/java/racingcar/RacingGameTest.java
> +    void playRacingGameAndGetWinner(int countRound, long minWinnerNumber) {
조금 더 간단하게 만들 수는 없을까요?

예를 들어 '우승자 목록을 반환한다' 같은 기능을 RacingGame에서 구현하면 될 것 같아요 😄

2021-03-09 03:44 UTC, yongdae commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
출력이라는 부분을 클래스로 잘 분리해주셨네요. 💯 
이 클래스를 활용하면 '자동차의 위치 표시' 도 테스트를 작성 할 수 있을것 같아요. :)

2021-03-09 10:40 UTC, jhLim97 commented on src/main/java/racingcar/contoller/RacingCarController.java
> +    private static ResultView resultView = new ResultView();
의미없이 사용하고 있어서 수정했습니다!!..

2021-03-09 10:41 UTC, jhLim97 commented on src/test/java/racingcar/CarTest.java
>  class CarTest {
Car클래스에서 해당 로직을 처리하도록 수정했습니다!!

2021-03-09 10:41 UTC, jhLim97 commented on src/test/java/racingcar/RacingGameTest.java
> +    void playRacingGameAndGetWinner(int countRound, long minWinnerNumber) {
네 반영했습니다!!

2021-03-09 10:42 UTC, jhLim97 commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
네 작성했습니다!!

2021-03-10 03:01 UTC, yongdae requested changes
피드백을 잘 반영해주셨네요. 👍 👍

마지막인 5단계로 넘어가기 전에 한번 더 고민해보면
좋은 내용이 있어 의견 드렸습니다.

확인 후에 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-03-10 04:49 UTC, jhLim97 commented on src/main/java/racingcar/Conditions.java
> +public class Conditions {
현재 Car클래스의 유효성 조건들을 갖고있다고 생각했는데 혹시 어떤 부분이 부족한 지 알 수 있을까요? 제가 이해를 못하는 것 같기도 합니다...!

2021-03-10 09:45 UTC, jhLim97 commented on src/main/java/racingcar/contoller/RacingCarController.java
> +    private ResultView resultView = new ResultView();
수정했습니다!

2021-03-10 09:45 UTC, jhLim97 commented on src/main/java/racingcar/domain/RacingGame.java
> +        Map<String, Integer> finalRound = finalResult.getFinalResult().get(InputManagement.getCountRound());
네 적용했습니다!

2021-03-10 09:45 UTC, jhLim97 commented on src/main/java/racingcar/dto/InputManagement.java
> +    private static int countRound;
아까 질문드린 사항을 토대로 수정했습니다!

2021-03-10 09:46 UTC, jhLim97 commented on src/test/java/racingcar/RacingGameTest.java
> +    void playRacingGameAndGetWinner(int countRound, int minWinnerNumber) {
반영했습니다!

2021-03-10 23:31 UTC, yongdae approved these changes
준혁님 피드백을 잘 반영해주셨네요. 👍

진행하신 내용에대해서는 몇 가지 의견을 남겨놓았습니다.
다음 단계 진행하실때 같이 반영해주시면 될 것 같아요. 😄 

자 이제 마지막 단계로 넘어가시죠! 🔥🔥

2021-03-10 23:31 UTC, yongdae commented on src/test/java/racingcar/CarTest.java
> +    void carNameCanUnder5(String carName, boolean isInValidName) {
isInValidName 는 삭제해도 될 것 같아요. :)

2021-03-10 23:31 UTC, yongdae commented on src/test/java/racingcar/RacingGameTest.java
> +import java.util.stream.Collectors;
사용하지 않는 패키지 임포트 구문은 삭제해주세요 ~ 😄

2021-03-10 23:31 UTC, yongdae commented on src/test/java/racingcar/RacingGameTest.java
> +    void playRacingGameAndGetWinner(String positions, int winnerNumber) {
메소드를 2개로 해보면 어떨까요?

하나의 메소드로 2개의 경우를 만드는 것보다
`우승자 1명인 경우`, `우승자 2명인 경우` 각 각의 테스트로 만들면
조금더 명확하게 단일 우승자와 n명의 우승자에 대한 테스트가 될 수 있을 것 같아요. 😄

2021-03-10 23:31 UTC, yongdae commented on src/test/java/racingcar/CarTest.java
> +    void canDisplayCarPosition(int position, String displayPosition) {
toString()을 잘 사용해주셨네요. 👍

2021-03-10 23:31 UTC, yongdae commented on src/main/java/racingcar/view/InputView.java
> +        return scanner.nextLine().split(",");
"," 는 [매직 넘버](https://hoonmaro.tistory.com/44)를 사용해보면 어떨까요? ~

2021-03-10 23:31 UTC, yongdae commented on src/main/java/racingcar/view/InputView.java
> +            new Car(carName, 0).nameValueInValidation();
Car에 생성자를 추가해보면 어떨까요?

생성자를 추가해서 new를 이용해 인스턴스를 만들때마다
위치 초기값(0)을 주지 않고도 초기화 할 수 있게 만들면 더 좋을 것 같아요 😄

2021-03-10 23:31 UTC, yongdae commented on src/main/java/racingcar/util/Conditions.java
> +    private static final int HIGHER_LIMIT = 9;
https://github.com/next-step/java-racingcar/pull/1986#discussion_r590946234

이 피드백은 예를 들면 MAX_LENGTH를 Car 클래스가 포함하고 있으면 좋지 않을까?
라는 의견입니다.

지금의 설계 상태에서는 자동차의 제약 조건이 추가되면 모든 제약을 Conditions이 가지고 있기 때문에
Conditions이 변경됨으로써 모든 클래스에게 영향을 줄 수 이는 상태입니다.

하지만 Car가 제약을 가지게되면 자동차의 제약 조건이 추가되어도 자동차에게만 영향을 주게됩니다. :)

2021-03-10 23:32 UTC, merged