자동차경주 step3 과정 리뷰 요청드립니다!
next-step/java-racingcar pull request #2005
Opened 2021-03-10 08:10 UTC by limdingdong

이슬님 안녕하세요! 자동차경주 step3 과정 리뷰 요청드립니다!

평소에 사용해보지 않았던 람다식과 stream, 일급컬렉션 개념들을 도입해 보았는데요!
경험이 부족해서 코드가 부자연스러워 보이실 수 있을 것 같습니다^^;;;
코멘트 달아주시면 이번에도 열심히 한 번 개선해 보겠습니다!

또 실습하면서 다음과 같은 질문이 생겨 문의드립니다.
	
1. 일급 컬렉션 패키지 관리
 - 일급 컬렉션은 상태와 행위를 함께 갖는다는 점에서 entity object의 개념을 일부 가진다는 생각이 듭니다.
 - 그런데 또 다른 멤버변수를 가질 수 없고 임의의 명명이 가능하다는 점에서 단순 dto의 개념도 가진다는 생각이 드네요!
 - 그래서 비즈니스 로직을 가지고 있지 않은 단순 dto들과 일급 콜렉션을 분리해서 패키지로 관리하는 것도 좋을 것 같다는 생각이 들었는데요
 - 일급 콜렉션과 나머지 dto들을 분리해서 관리하는 경우를 경험하신 적이 있으신지 궁금합니다.
   더불어, 그런 설계 구조에서는 어떤식의 구조와 작명으로 패키지를 관리하는지 궁금합니다!

2. UI 응답객체의 일급컬렉션 사용 필요성
 - 일급컬렉션을 통해서 상태와 행위를 관리하고 네이티브 컬렉션을 통해 인스턴스로의 직접 접근을 막을 수 있다는 생각이 듭니다.
 - 그런데 프론트엔드로 전달하기 위한 데이터 객체의 경우 UI에서 따로 컬렉션의 행위를 사용하거나 그럴 수 있는 것은 아니므로
   일급 컬렉션 기반의 설계를 하지 않아도 될 것 같다는 생각이 듭니다.
 - 혹시 어플리케이션 외부로 응답을 하기위한 데이터 객체가 일급 컬렉션을 가질 필요성이 있다면 그 이유가 궁금합니다!

2021-03-10 18:09 UTC, parkeeseul requested changes
미션 잘 진행해주셨습니다! 👍 
몇 가지 코멘트와 질문에 대한 저의 의견 남겨두었으니 확인 부탁드립니다!

좀더 고민하실 만한 부분들이 있어 request changes 하겠습니다!
수정 후 다시 한번 리뷰요청 부탁드려요! 😄 
피드백에 대한 의문이나 궁금하신 점이 있으시다면 언제든 DM 주세요! 화이팅 입니다! 🔥

2021-03-13 08:01 UTC, limdingdong commented
이슬님 안녕하세요! 먼저 늦은 시간까지 정성스럽게 코멘트 남겨주셔서 정말 감사합니다😃
제가 아직 많이 부족해서 이슬님의 시간을 많이 쓰도록 만들어 드리는 것 같네요ㅠㅠ 더 열심히 공부해서
개선사항 요소들 줄여보도록 노력하겠습니다. 코멘트 주신내용 참고하여 다음과 같이 수정 진행해 보았습니다.

2021-03-13 08:02 UTC, limdingdong commented
1. 접근제어자 누락
 - 접근제어자를 누락내역들 수정해서 반영 완료하였습니다!
2. DTO 값 세팅 시 setter 사용을 지양하고 생성자를 통한 초기화를 할 것
 - 제가 setter를 남발하는 것에 대한 경계심이 없었네요ㅠㅠ 엔티티 오브젝트들을 제외한 DTO나 VO들은 setter를 사용해도 된다고 생각했는데, 여러 글을 읽어보니 setter의 지양이 왜 필요한 것인지 알게 되었습니다. 앞으로는 생성자나 빌더를 활용해 값을 초기화 하는 습관을 들여보겠습니다!
3. Car 객체가 carNumber 를 상태값으로 가져야 할 이유
 - carNumber는 경기에 참가한 자동차 등록번호를 화면에 DP해주기 위해 정의해 보았습니다. 별도의 비즈니스 로직을 위한것은 아니고 UI로 전달하기 위한 데이터 요소로 사용하고자 했던 것입니다.
 - 이슬님의 코멘트는 자동차 등록번호가 Car 객체에 정의된 설계가 어색하다고 말씀주신 것일까요? getter를 통해 직접 상태를 노출시키는 메소드는 제거하고 자동차별 경주성적을 표현하는 RacingScore 객체를 반환하는 구조로 바꿔보았는데, 제가 이슬님의 의견을 잘 이해한 것인지 모르겠네요ㅠㅠ
4. 랜덤 요소를 외부에서 주입받도록 해볼 것
 - Engine 이라는 클래스를 새로 정의하고 Car 클래스가 이 클래스에 의존하는 구조를 만들어 보았습니다. Engine 클래스는 random 객체를 생성자를 통해서 주입받는 구조로 만들어서 인자값 기반으로 테스트 결과를 제어할 수 있도록 해보았습니다!
5. Car - CarService 객체간의 관계
 - 저는 처음에 Car 클래스를 상태값을 갖는 도메인 객체로 설계하고, CarService 클래스는 이에 대한 도메인서비스 객체로 활용을 해보고자 했습니다. 도메인 객체에 대한 생성과 핸들링은 CarServcie 클래스에 전담하게 해서 일종의 팩토리나 매니저 클래스 역할을 하게 만들고자 했었습니다. 최근에 DDD 관련 책을 읽은 적이 있어서 도메인 서비스 개념을 어설프게 적용하려다 보니 다소 부자연 스러운 구조가 된 것 같습니다ㅠㅠ
 - 아래에서 코멘트 남겨주신 부분 참고하여 Players 클래스를 Cars 클래스로 리팩토링 하고, 도메인 로직을 이곳에서 처리할 수 있게 만들어보니 자연스럽게 CarService 클래스의 역할이 축소되어 결국은 삭제가 되었네요! 일급컬렉션은 도메인에 속한다고 설명해주신 코멘트가 생각을 바꾸게 만들어 준 계기가 되었습니다!
6. private 메소드의 네이밍 컨벤션
 - 제가 실무에서 private 메소드를 _를 붙여 코딩하는 컨벤션을 적용하고 있어서. 습관적으로 코딩을 했네요;;; 이 부분은 수정해서 반영하였습니다!
7. Players 객체 생성로직 객체 내부로 이동
 - 아래에서 언급해주신 코멘트 참고하여 Players 객체를 Cars 객체로 리팩토링 하면서 생성자 기반으로 객체를 생성하는 구조로 변경해 보았습니다!
8. getRacingResult 메소드 생성과 기능 분리하기
 - RacingResult도 행위를 가질 수 있는 일급컬렉션으로 정의했으므로 RoundResult, RacingScore 등 하위객체들을 클래스 내부에서 연쇄적으로 생성할 수 있도록 기능을 클래스 내부로 이동시키고, 초기화는 생성자를 통해서만 가능하도록 수정해 보았습니다!
9. 묻지말고 시켜라 원칙
 - 네 이슬님! executeScoring 메소드는 RacingResult 의 생성자에서 호출되는 구조로 바꾸어 보았습니다. 그 과정에서 Cars 클래스에서 내부 요소를 getting해서 루프를 처리하는 방식은 없애고 driveAll 이라는 메소드를 통해 Cars 클래스가 내부요소를 자체적으로 핸들링 하는 방식으로 수정을 해 보았는데요! 이렇게 되면 Cars 클래스에 내부 Car 객체들에게 drive 메소드라는 행위를 하도록 메시지를 보낸 구조가 된게 아닌가 하는 생각이 듭니다.
10. Players, playerList 네이밍 수정
 - 코멘트 주신 부분 읽고 다시 고민해 보았습니다. 제가 참여자들에 대한 객체로써 Players 클래스를 정의한 것이기는 했는데, 실제 참여자 라는 비즈니스 요소를 가지고 있지는 않다는 생각이 들었습니다. Car 객체의 일급컬렉션으로 처리할 수 있도록 네이밍 수정하고 패키지 이동해서 수정해보았습니다!
11. 도메인에 대한 테스트를 진행할 것
 - CarRacingServiceTest 에 서비스 실행결과에 대한 테스트를 추가해 보았습니다. 도메인에 관한 테스트라고 말씀주신 것이 이러한 내용을 의미하신 것이었는지 궁금합니다.

2021-03-14 06:25 UTC, parkeeseul requested changes
피드백 열심히 반영해주셨네요! 👍 
몇 가지 추가 코멘트 남겨드렸으니 확인 후 다시 한번 리뷰요청 부탁드리겠습니다! 😄 

남은 주말 즐겁게 보내시길 바라겠습니다! 화이팅 입니다! 🔥

2021-03-14 06:25 UTC, parkeeseul commented on src/main/java/carracing/service/dto/RoundResult.java
> +        validateRacingScores(racingScores);
해당 클래스도 DTO 로 보이는데 검증을 하는 비즈니스 로직이 포함되어 있네요!
자동차 경주 라는 책임을 가지는 RacingCar 객체를 분리해 해당 책임을 위임 해보면 어떨까요? 😄

2021-03-14 06:25 UTC, parkeeseul commented on src/test/java/carracing/domain/CarTest.java
> +    }
해당 테스트를 100 번 반복 실행하시는 이유는 car.dirve 에 랜덤 이 존재하기 때문일까요? 😄

2021-03-14 06:25 UTC, parkeeseul commented on src/main/java/carracing/domain/Cars.java
> +public class Cars {
Cars 에 대한 테스트 코드도 작성해보면 어떨까요? 😄

2021-03-14 06:25 UTC, parkeeseul commented on src/main/java/carracing/CarRacingApplication.java
> +public class CarRacingApplication {
질문 주신 사항에 대한 저의 의견 여기에 남기겠습니다! 😄 

> 3. Car 객체가 carNumber 를 상태값으로 가져야 할 이유
> carNumber는 경기에 참가한 자동차 등록번호를 화면에 DP해주기 위해 정의해 보았습니다. 별도의 비즈니스 로직을 위한것은 아니고 UI로 전달하기 위한 데이터 요소로 사용하고자 했던 것입니다.
> 이슬님의 코멘트는 자동차 등록번호가 Car 객체에 정의된 설계가 어색하다고 말씀주신 것일까요? getter를 통해 직접 상태를 노출시키는 메소드는 제거하고 자동차별 경주성적을 표현하는 RacingScore 객체를 반환하는 구조로 바꿔보았는데, 제가 이슬님의 의견을 잘 이해한 것인지 모르겠네요ㅠㅠ

현재 출력결과와 요구사항을 보면 자동차 경주에 대한 결과값만 출력하기 때문에 carNumber 가 상태값으로 필요할까? 에 대한 의문이 들었습니다 😄 

고민하신 내용들과 피드백 반영에 대한 사항들 잘 정리해주셨네요!
열심히 하시는 동섭님을 보니 저도 자극을 받게되네요 감사합니다 😄 
화이팅 입니다! 🔥

2021-03-14 12:52 UTC, limdingdong commented
1. CarRacingRequest, RacingRegisterInfo 클래스를 별도로 정의한 이유
- 네 이슬님~! 컨트롤러와 서비스 클래스의 input은 따로 관리하는게 좋다고 생각을 해서 별도로 정의를 했습니다. 지금은 동일한 상태값을 가지고 있지만 추후에 두 input의 모양이 바뀔수도 있을 것 같아서요!
- 실무에서 이런 설계에 대해 구성원들의 의견을 나누어 본 경험이 없어서;;; 각 레이어의 요청객체의 레이아웃이 동일하게 설계가 될 때 먼저 하나로 사용을 하다가 추후에 요구사항이 변경되면 분리를 하는 식으로 진행하는게 자연스러운 것일까요?
- 우선 RacingRegisterInfo 클래스는 CarRacingRequest 로도 대체가 될 수 있기 때문에 이번 수정작업에는 삭제하고 하나의 클래스로 처리하도록 수정하였습니다!
2. CarRacingValidator 클래스와, 도메인 내부의 중복 검증로직 산재
- 저도 코드를 보니까 어색해 보이는 부분이 많다고 느껴졌네요. 평소에 아무런 제약없이 getter와 setter가 오픈된 DTO를 활용해 개발을 하다보니, validator 라는 것을 만들어서 어플리케이션 레이어별로 심어놓는 습관이 생긴 것 같습니다.
- 이슬님의 코멘트를 읽으면서 생각해보니 도메인을 생성하면서 검증로직을 두면 레이어의 깊은 곳에서부터 검증을 수행할 수 있어 관리하기 좋겠다는 생각이 드네요!
- 중복되는 로직을 갖는 CarRacingValidator 클래스는 삭제하였습니다.
- 컨트롤러나 서비스를 위한 validator 클래스는 어떤 경우에 활용하는 것이 좋을 지 이 부분은 다시 한 번 고민해 보겠습니다. 감사합니다!
3. CarRacing 클래스를 활용해 RacingResult, RoundResult DTO 클래스의 비즈니스 로직 처리책임을 분리해볼 것
- 비즈니스 처리를 담당하는 CarRacing 클래스를 새로 정의해 보았습니다. 경기 진행에 필요한 라운드 수와 등록된 차량리스트를 받아 경기를 진행하고 그 결과를 리턴해주는 역할을 합니다.
- RacingResult, RoundResult 클래스는 값만 가지고 있는 DTO 클래스가 되도록 로직 떼어냈습니다.
- 기존에 Car 클래스가 RacingScore 인스턴스를 리턴하는 구조로 설계되어 있어서 Cars 클래스가 RacingScores 인스턴스를 리턴하는 구조로 바꾸어보았습니다.
4. car_move 테스트
- 처음에 랜덤클래스 사용로직을 private로 지정해 개발을 했었는데, 이걸 어떻게 테스트 해야하나... 하면서 만든 이상한 테스트입니다.
- Engine 클래스를 개발하면서 랜덤클래스의 값을 조절해 테스트 하는 방법을 찾았네요!
- 민망하므로 얼른 삭제하겠습니다!!! (이왕 그렇게 할거면 통크게 한 100만번 돌리지 또 소심해서 100번...)
5. Cars 클래스 테스트 코드 작성
- 새로 추가한 CarRacing 클래스 테스트와 함께 Cars 클래스에 대한 테스트도 함께 추가하였습니다~!
6. carNumber 상태 사용의 의미
- 차량번호는 UI에 더 많은 정보를 제공해주기 위하여 제가 임의로 추가한 변수였습니다.
- 이슬님 코멘트를 보면서 요구사항에 명시되지 않은 범위 내에서 개발자가 사용자 편의를 제공해주는 것은 좋으나, 도메인 객체의 설계를 변경하는 것은 신중해야 겠다는 생각이 들었습니다.
- 앞으로의 실습에서는 좀 더 신중하게 고려해서 클래스 설계를 해 보겠습니다!
- 추가로 기존에 carNumber와 score를 묶어서 RacingScore 라는 DTO를 정의했었는데, carNumber를 제거하면서 이 DTO클래스를 어떻게 할 까 하다가 유지하는 쪽으로 결정을 내렸습니다.
- 변수를 하나만 가지고 있지만, car 클래스가 가진 주행거리와 특정 회차의 라운드별 경기점수는 의미가 다르므로 RacingScore 객체로 score를 방식을 유지하는 것이 좋겠다는 생각이 들었는데, 이슬님의 의견은 어떠신지 궁금합니다!

2021-03-14 15:26 UTC, parkeeseul commented
안녕하세요 동섭님! DTO 에 대해 질문주셨는데요!

DTO 를 무조건 적으로 레이어 사이에 데이터를 전달하기 위한 목적으로 사용하기 보다는 필요한 곳에 적절히 사용하는게 좋다고 생각합니다. 
DTO 를 무분별하게 사용하다 보면 가독성을 해칠 수 있기 때문에 개인적으로 데이터를 재구성해 레이어 간 데이터 전송을 해야 할 경우 DTO 를 만들어 주는 것이 좋다고 생각합니다. 😄 
또한 아직 필요하지 않은 요구사항 때문에 필요 이상으로 구현할 필요는 없을 것 같아요!

현재 자동차 경주에서 많은 부분 DTO 를 사용하고 계신데요, 자동차 경주 미션의 마지막 단계인 5단계 리팩토링에서 DTO 에 대해 한번 고민해보셔도 좋을 것 같습니다. 😄

2021-03-14 15:27 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
소소한 피드백 남겨두었으니 확인 해보시고 다음 단계에서 함께 반영 부탁드립니다 ! 😄 
다음 미션 진행해주세요! 🔥

2021-03-14 15:27 UTC, merged

2021-03-14 15:49 UTC, limdingdong commented on src/main/java/carracing/service/CarRacing.java
> +        }
네 이슬님~! 이 validate 메소드도 앞서 코멘트 주셨던 도메인 검증로직에 관한 부분이 밖으로 나왔다는 생각이 드네요! 도메인 객체의 검증은 도메인에서! 실수하지 않도록 조심하겠습니다😃 코멘트 감사드립니다!