자동차경주 step5 리뷰 요청드립니다!
next-step/java-racingcar pull request #2110
Opened 2021-03-18 03:26 UTC by limdingdong

이슬님 안녕하세요! 자동차경주 step5 리뷰 요청드립니다.
2단계 미션도 리뷰해주시느라 바쁘실텐데 제가 아직 1단계에서 못나가고 있어서 이슬님께 부담을 드리는 것 같네요ㅠㅠ;;;
얼른 마무리해서 진도 나가도록 하겠습니다!

1. 우승자를 Car 객체의 리스트로 리턴할 것
- 네 이슬님! 저번에 플레이어 클래스를 Car로 통합하면서 Car 객체에는 경기 참가자 라는 도메인적 의미가 부여되었는데, 그것을 간과했습니다.
- Car 객체를 단순히 자동차 물건이라고 생각해 버려서 이런 결과가 나왔던 것 같네요.
- 경기에 참가한 자동차들 중 우승한 자동차들의 정보를 리턴하는 도메인 객체 중심의 로직으로 개선하였습니다!
2. Winners 클래스 정의
- 우승한 자동차들 목록을 묶어서 Winners 클래스로 정의하고, 우승자 이름 목록을 리턴해주는 기능을 만들었습니다.
3. 우승자를 구하는 책임을 Cars 클래스로 이관
- 이슬님의 코멘트 중 'Cars 가 우승자의 정보를 가장 잘 알고있다' 라는 표현이 와닿았습니다.
- 정보를 알고있는 주체 내부에 비즈니스 로직을 구현하고, 밖에서는 메시지만 주는 구조에 익숙해져야겠네요!
4. 우승자 판별로직 가독성 향상
- Cars 클래스로 비즈니스 로직을 옮기게 되니 자연스럽게 상태값을 조회해 처리하는 부분이 줄어들게 되는 것을 경험했습니다.
- maxScore 같은 메서드도 만들어서 리팩토링 하니 훨씬 간결한 코드가 되었네요!
- 이번 실습을 통해서는 객체의 책임을 할당하면서 가독성이 눈에 띄게 향상될 수 있다는 점을 배웠습니다.

2021-03-18 16:46 UTC, parkeeseul requested changes
피드백 잘 반영해 주셨습니다! 👍 
몇 가지 피드백 남겨두었으니 확인 부탁드려요!

전혀 부담되지 않으니 충분히 고민해보시고 천천히 진행하셔도 괜찮습니다! 😄 
벌써 금요일이네요! 즐거운 금요일 되시고 화이팅 입니다! 🔥

2021-03-19 14:36 UTC, limdingdong commented
이슬님 안녕하세요! 코멘트 달아주신 부분 다음과 같이 수정 진행하였습니다.
실습하다 생긴 문의사항도 함께 적어보았습니다. 여유있으실 때 확인해주시면 감사하겠습니다~!

1. 메서드 네이밍 동사로 수정
- 네 이슬님! 수요일 강의에서 '엘레강트 오브젝트'의 '빌더와 조정자' 에 대한 부분을 참고해서 get이라는 동사를 뺐습니다.
- 이슬님의 코멘트를 참고해 다시 책을 읽어보니, 빌더라는 메서드 명명 표현은 어떤 과정을 통해서 출력된 결과물, 즉 결과물 생성을 위한 비즈니스 로직이 존재하는 경우에 사용을 하는것이 맞다는 생각이 드네요! 강의랑 책 다시 참고해서 공부하겠습니다.
- 단순 상태값 획득을 위한 메서드는 getter가 맞다는 생각이 들어서 다시 수정했습니다. 감사합니다!
2. Winners의 우승자 이름 출력로직 제거, UI를 위한 Dto 세팅으로 변경
- Winners 클래스를 정의해 nameList 를 뽑아내는 로직을 구현한 것은, Car라는 도메인 객체를 프레젠테이션레이어까지 보내지 않기 위해 정의했던 것입니다.
- 이슬님의 코멘트를 읽고 다시 소스를 보니 서비스 레이어까지는 Car객체를 노출시키고 Controller 에서 UI출력을 위한 이름 리스트를 리턴해주면 되겠다는 생각이 들었네요!
- 다시 CarRacingResponse 라는 프레젠테이션레이어의 dto를 정의하고 여기에 name리스트를 담아서 view로 보내주는 구조로 수정해 보았습니다!
3. addWinner 메서드의 상태 조회로직을 제거하고 객체에 메시지를 주는 방식으로 수정
- 아... 습관이 아주 무섭네요ㅠㅠ getter를 열어두니 상태를 묻고 처리하는 로직을 계속 생성하게 됩니다.
- getter를 먼저 삭제하고 다시 리팩토링 진행해 보니 getter가 없어도 충분히 처리할 수 있다는 것을 경험하게 되네요!
- Cars 클래스의 maxScore도 Car 객체에 상태를 묻도록 하는 것 같아 이 부분도 Car 객체가 처리하도록 수정해 보았습니다.
4. 랜덤요소를 제어할 수 있도록 engine 클래스를 외부에서 주입받도록 변경, 테스트 작성
- Engine 클래스를 제어하면 Car 클래스의 drive를 제어할 수 있다 라는 가정을 하고 코딩을 해버렸네요.
- Engine 클래스를 Car 클래스 drive 메서드의 파라미터로 받아서 처리할 수 있도록 수정하고 테스트 구현했습니다!
5. maxScore 메서드의 테스트 작성
- drive메서드와 maxScore메서드의 테스트 작성해 추가하였습니다!

실습 진행하면서 다음과 같은 질문이 생겨 문의드립니다.
 - Winners 클래스의 nameList 조회로직을 삭제하고 보니 Winners 클래스가 일급 컬렉션으로써의 역할을 하지 못한다는 판단이 들어 이를 삭제하였습니다.
 - 그렇게 되니 RacingResult 클래스가 Car 리스트를 직접 보유하는 형태가 되어버렸는데, 이를 다시 Winners 클래스로 감싸는게 좋은 것일까 라는 생각이 듭니다.
 - 당장은 우승자 Car 리스트를 Winners 클래스로 감싸도 결국 getter만 사용하게 될 것 같은데, 우승자들을 묶어서 무엇인가 처리해야 하는 비즈니스 로직이 생길 때 리팩토링을 하는 것이 좋을 지, RacingResult 클래스의 Car 리스트처럼 도메인 클래스를 컬렉션으로 만들 일이 생기면 별도의 비즈니스 로직을 당장 구현하지 않더라도 일급컬렉션으로 정의해 놓는 것이 좋을 지 이슬님의 의견이 궁금합니다!

2021-03-20 07:09 UTC, parkeeseul commented
안녕하세요 동섭님! 질문주신 사항에 대한 저의 의견 남깁니다. 😄 

객체를 분리하는 이유에 대해 고민해 보면 좋을 것 같아요!
객체지향 설계에서는 책임을 어떤 객체에 부여하느냐가 중요한데요
이런 관점에서 보면 객체에게 책임이 없다면 해당 객체의 존재 이유가 있을지 생각해보면 좋겠어요

Winners 클래스가 결국 getter만을 가지게 된다면
추후 Winners의 책임이 생길때(비즈니스 로직이 생길때) 구현해주시면 될 것 같아요!

2021-03-20 07:11 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
피드백 반영에 대한 꼼꼼한 설명도 항상 잘 보고 있습니다 😄 

한 가지 피드백과 질문 주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드릴게요!
비오는 토요일이네요! 즐거운 토요일 되시길 바라요 ! 화이팅! 🔥

2021-03-20 09:33 UTC, limdingdong commented
- 네 이슬님~! 평소에 자바언어로 개발을 하고있는데, 계속 프로시저를 짜고있다는 느낌을 받아서 객체지향 설계를 어떻게 해야할지가 항상 고민이었습니다. 이슬님이 말씀해주신 대로 객체의 구현단위를 '책임'이라고 생각해보니 소스분리를 할 기준을 잡을 수 있을 것 같네요! 의견 감사드립니다!

- drive 메서드를 인자를 받는 방식으로 바꿨는데, 이를 호출하는 driveAll 메서드를 그대로 두어버리니, 이전에 drive 메서드에 대한 테스트를 진행하지 못했던 상황과 동일하게 되어버렸네요;;; driveAll 메서드부터 인자를 받아서 drive메서드까지 넘기는 식으로 구조 변경해 보았습니다. 랜덤요소가 있는 메서드를 설계할 때에는 call hierarchy의 가장 바깥쪽부터 요소를 제어할 수 있는 구조인지 먼저 살펴보아야 겠네요!

2021-03-20 12:50 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨습니다! 👍 

그동안 많은 피드백 반영 해주시느라 고생 많으셨습니다!
동섭님과 여러 의견 주고 받으면서 저 또한 다시 한번 생각해보게 되었네요! 감사합니다 🙇‍♀️ 
남은 미션도 꼭 완주하셔서 많은 인사이트 얻어 가시길 바라겠습니다!
고생 많으셨습니다! 남은 미션도 화이팅! 🔥

2021-03-20 12:50 UTC, merged