[Step5] 자동차 경주 5단계 리뷰 부탁드립니다 ! !
next-step/java-racingcar pull request #2129
Opened 2021-03-22 15:21 UTC by wjdrbs96

리팩터링 정말 쉽지 않은 거 같습니다 ㅠ , ㅠ

- 궁금한 점은 주석으로 달아놓았습니다 ㅠ (해결되는 대로 지우겠습니다 !)
- 넥스트스텝 홈페이지 강의에서 리팩터링 하는거 보면서 적용해보았씁니다 ! ! (확실히 뭔가 보면 그 쪽으로만 생각하게 되는거 같습니다.. ㅠ)
- 뭔가 정말 동작 코드를 제대로 작성하지 못하거나 의존 관계를 잘못 맺는다?거나 했을 때 테스트 코드 작성하는게 진짜 쉽지 않다는 것도 계속 느끼고 뭔가 여러가지로 아직도 어려운 거 같습니다 ㅠ
- 그래도! 친절하게 리뷰 계속 해주셔서 정말 감사합니다!! (부족하지만 이번 PR도 리뷰 잘 해주세요~~)

2021-03-23 07:41 UTC, ohtaeg requested changes
마지막 미션도 구현을 잘해주셨습니다 👍 👍 
전체적으로 설계 및 객체 분리가 깔끔하게 해주신 것 같아요 :)
마음같아서 미션을 마무리 하고 싶지만 정균님께서 고민하는 부분을 리팩토링하고
다음 로또 미션을 진행하신다면 좀 더 수월하게 진행할 수 있을 것 같아 Request changes 하였습니다.
몇 개의 피드백을 드렸는데 마지막으로 피드백을 반영하시면 좋은 경험이 될 것 같아요 😄 
마지막까지 화이팅입니다❗

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +    // InputDto 를 없애고 Refactor 할 수 있을 거 같은데 당장은 떠오르지 않아서 일단.. 리뷰 받고 고쳐보겠씁니다 ㅠ
값을 Wrapping을 하는 순간 테스트, 의존 관계 등의 복잡성이 증가하는건 어쩔 수 없는 것 같아요 😭 
제일 쉽게 리팩토링할 수 있는 방법은 DTO를 제거하는 방법입니다..!

개인적으로 DTO는 객체가 아닌 데이터를 가지는 구조체로 취급하기에 해당 의존관계는 괜찮다고 생각해요 ㅎㅎ
즉, DTO를 가져도, 가지지 않아도 둘다 좋은 설계라고 생각합니다.
이 부분은 정균님께서 DTO를 유지해주실지, 아니면 DTO를 제거하고 내부 값들을 RacingGame에서 보관하도록 할지
고민해보시면 좋을 것 같습니다 :)

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +    // 외부에서 tryCount를 매개변수로 받아야 더 나을지.. 지금 처럼 필드로 InputDto 받아서 사용하는 것이 나을지 모르겠습니다 흑흑
매개변수로 받는 것은 외부에서 RacingGame의 흐름을 좀 더 구체적으로 컨트롤 한다는 뜻이고
지금처럼 필드로 관리한다면 RacingGame의 흐름을 외부가 아닌 RacingGame 스스로가 컨트롤 한다는 뜻으로 해석될 수 있습니다.

해당 피드백과 마찬가지로 이 부분도 둘 다 괜찮다고 생각하는 부분입니다 :)
이 부분도 정균님께서 고민하신다음 좋다고 생각하시는 방향으로 해주시면 될 것 같네요 😄

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +    // 테스트 코드를 작성하기 위해서 public 으로 만들어둔.. 메소드 인데 괜찮을 지 모르겠습니다 ㅠ(기존 메소드를 그냥 public 하는게 나을까요..)
테스트 코드를 위한 생성자는 괜찮다고 생각하지만 메서드는 실제로 사용되지 않는 것이기에 제거해주시는 것을 권장드립니다 :)
왜냐하면 만약 현재 코드가 더 복잡하고 실무에서 프로덕션 코드라면 사용되지 않는 코드를 쉽게 제거하기도 어려울 것 같아요!
(괜히 제거했다가 장애가 나면..!!!)

현재 여러 자동차 생성에 관해 테스트를 하고 싶으신 것 같아요! 👍  👍 
그렇다면 여러 자동차를 관리하는 객체를 별도로 분리해보면 어떨까요 :) ?
Cars와 같은 여러 자동차를 관리하는 객체를 일급 컬렉션이라고 하며 List\<Car\>를 관리하는 객체를 생성하면 장점으로
정균님께서 원하는 생성 테스트가 가능하며, 여러 자동차들을 통해 우승자를 구하는 로직을 Cars에게 위임함으로써
게임을 중재하는 RacingGame의 책임도 분산할 수 있는 장점이 있다고 생각합니다 :)

일급컬렉션에 관한 내용은 다음 링크를 참고하시면 좋을 것 같아요!
[일급컬렉션](https://jojoldu.tistory.com/412)

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +        return cars.get(0).getPosition().getPosition();
정렬을 위해 Position에서 getter를 사용해주셨고 getter에도 주석을 달아주신 이유가 여기였군요..!
우선 getter를 많이 사용하기에 줄여야 된다고 생각하시는 부분을 칭찬 드리고 싶네요 👍 
getter를 많이 사용하는 것은 내부 접근이 많이 일어난다는 뜻이고 많은 정보들이 노출되고 있다는 뜻으로
**캡슐화가 지켜지지 않고 있다는 신호**이기도 합니다.
캡슐화를 지키기 위해 많은 고민을 해주시는게 보이시네요 👍 

음.. getter를 지양하기 위해선 해당 객체에게 역으로 요청을 하여 요청처리를 해주도록 하면 어떨까요 :)?
현재 RacingGame에서 Position 객체의 값을 꺼내와서 정렬 기준을 세우고 있지만 역으로
Position에게 정렬 기준을 직접 세우도록 요청을 하거나 구현하면 될 것 같아요 :)
이것을 `객체에게 메세지를 보내 객체 스스로가 수행하도록 해라` 라고 표현할 수 있습니다.

다음과 같이 Position 객체가 Comparable을 구현하면 어떨까요 :)?
```suggestion
        Collections.sort(cars);
        return cars.get(0).getPosition().getPosition();
```
```java
public class Position  implements Comparable<Position> {
    @Override
    public int compareTo(Position other) {
        return Integer.compareTo(other.position, this.position);
    }
}

```

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/view/InputView.java
> +    public static InputDto input() {
해당 느낌이 드신다면 리팩토링의 필요성을 감지하신겁니다 ㅎㅎ
해당 메서드는 현재 입력을 수행하고있지만 실질적으로 다른 타입의 값을 두번 받고 있습니다..!
InputView 객체의 책임 자체가 입력을 담당하고 있기에 서로 다른 타입의 값을 받는다면 하나의 메서드가 아닌
서로 다른 메서드로 분리해주시는게 어떨까요 :) ?

2021-03-23 07:41 UTC, ohtaeg commented on src/main/java/step5/view/InputView.java
> +        // 입력을 받자마자 바로 유효성 체크를 하고 싶어서 여기에 이렇게 넣긴 했는데 깔끔해보이지는 않습니다.. (개인적으로 ㅠㅠ)
메서드로 분리해주시면 그만큼 가독성도 좋아지고 메서드가 해야하는 기능에만 충실해질 수 있습니다 👍 
유효성 체크에 대해 같이 고민하시면 좋을 것 같아요 ㅎㅎ
유효성 체크를 언제 해주어야 되는지는 저도 고민이 되는 부분이라고 생각합니다.

개인적으로는 **입력은 변경 가능성이 높기 때문에 최대한 단순하게 유지**하려고 노력합니다.
(지금은 콘솔 어플리케이션이지만, 웹 어플리케이션으로 변경이 된다면..?)

그래서 제가 선호하는 방법은 유효성 검사를 따로 하는 Layer(현재 구조에선 InputValidator)를 만들거나
도메인 객체에서 유효성 검사를 판단해주도록 합니다.
물론 입력을 받고 바로 검사해줘도 괜찮다고 생각하는 부분이기에.. 이 부분은 정답이 없는 부분이라고 생각합니다.
윗 피드백들과 마찬가지로 어떤 방법이 정균님께 좋을지 고민해보신다음 편하신 방법으로 구현해주시면 될 것 같아요 😄 

p.s. 현재 InputValidator가 존재하기에 입력 뷰가 아닌 InputDTO에서 수행해도 좋다고 생각합니다 :)

2021-03-23 07:41 UTC, ohtaeg commented on src/test/java/step5/CarTest.java
> +public class CarTest {
테스트를 잘해주셨네요 👍

2021-03-23 08:52 UTC, wjdrbs96 commented on src/main/java/step5/view/InputView.java
> +        // 입력을 받자마자 바로 유효성 체크를 하고 싶어서 여기에 이렇게 넣긴 했는데 깔끔해보이지는 않습니다.. (개인적으로 ㅠㅠ)
좋은 말씀 감사합니다 ㅎㅎ

2021-03-23 08:53 UTC, wjdrbs96 commented on src/main/java/step5/view/InputView.java
> +    public static InputDto input() {
오호 생각해보지 못한 거 같은데 좋은 말씀 이신 거 같습니다!! 리팩터링 해보겠습니다~~

2021-03-23 08:54 UTC, wjdrbs96 commented on src/main/java/step5/domain/RacingGame.java
> +    // 테스트 코드를 작성하기 위해서 public 으로 만들어둔.. 메소드 인데 괜찮을 지 모르겠습니다 ㅠ(기존 메소드를 그냥 public 하는게 나을까요..)
ㅠㅠㅠ 쉽지 않은 내용이지만 고려해서 리팩터링 해보겠습니다!

2021-03-23 08:55 UTC, wjdrbs96 commented on src/main/java/step5/domain/RacingGame.java
> +        return cars.get(0).getPosition().getPosition();
오오 좋은 말씀이신 거 같습니다.. 저도 뭔가 어디선가 설계?에 문제가 있기에 저렇게 getter를 여러 번 쓰게 되는 거 같다고 생각했습니다 ㅠ 말씀해주신 것과 여러가지 저의 생각을 더해서 리팩터링 해보겠습니다 감사합니다 ㅎㅎ

2021-03-23 10:31 UTC, wjdrbs96 commented on src/main/java/step5/domain/Position.java
> +    // 여기도 getter를 쓰게 되는... 안쓰는 방법이란... 조언 부탁드립니다 ㅠㅠ
오오 좋은 조언 감사합니다 ~~

2021-03-23 16:20 UTC, wjdrbs96 commented
말씀해주신 것과 저의 생각을 기반으로 다시 전체적으로 다시 리팩터링을 해보았습니다 !! 부족한 점이 있다면 계속 리뷰해주시면 감사하겠습니다 ㅎㅎ

마찬가지로 궁금한 점은 주석으로 적어놓았습니다!! 마지막까지 친절하게 리뷰 열심히 해주셔서 정말 감사합니다~~

2021-03-23 17:22 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨습니다 👍 
점진적으로 객체들이 분리되며 코드가 개선되고 있는 것이 인상적이네요 👍 
한시라도 빨리 로또 미션을 체험시켜드리고 싶은데 제 욕심으로인해 마지막으로 Request changes 하였습니다.
몇 개의 피드백을 드렸는데 해당 피드백들을 반영하신다면 원하시는 구조의 코드로 리팩토링이 될 것 같습니다 :)
거의 다 오셔서 마지막 리뷰가 될 것 같네요 ㅎㅎ 화이팅입니다 🔥

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +    }
> 음.. 이것도 Car 클래스 내부에 있어야 더 적합할 거 같은 느낌도 있는데 어떻게 생각하시는지 궁금합니다 !!

개인적으론 다음과 같이 Cars에서 수행하는게 더 어울릴 것 같은데 어떻게 생각하시나요 :) ?
`cars.move(new RandomMovingStrategy());` 라는 코드를 읽어보면
`자동차들을 움직여라` 와 같이 객체에게 명령(요청)하는 것 처럼 읽히지 않나요? ㅎㅎ
이처럼 객체지향의 세계에서는 오직 한 가지 의사소통 수단만이 존재하는데 이를 `메시지`라고 하며
상태를 외부에 노출시키지 않고 수신받은 메시지에 대해 수행함으로써 캡슐화를 지키는 과정중 하나라고 생각되어지는데
정균님께서는 어떻게 생각하시나요~?

```suggestion
    public void start(int tryCount) {
        while (tryCount-- > 0) {
            cars.move(new RandomMovingStrategy());
        }
    }
```

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/RandomMovingStrategy.java
> +    }
움직이는 전략을 새로 만들어 주셨군요 👍 👍

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/RandomMovingStrategy.java
> +        Random random = new Random();
앗..! 메서드가 호출될때 마다 또 Random 객체가 생성되는 구조인 것 같아요 ㅎㅎ
한번만 생성하고 재사용하도록 변경해주시면 좋을 것 같습니다 :)

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/dto/InputDto.java
> +    }
오히려 저는 괜찮다고 생각이 드네요!! 😄 
왜냐하면 DTO는 데이터를 전달하는 구조체이므로 입력은 순수하게 입력받은 값만 넘겨주고
비즈니스 로직에 필요한 데이터 검증은 DTO나 도메인이 검증해주면 좋다고 생각합니다..! ㅎㅎ

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/view/ResultView.java
> +public class ResultView {
군더더기 없는 ResultView 👍

2021-03-23 17:22 UTC, ohtaeg commented on src/test/java/step5/CarTest.java
> +    }
움직임 테스트 추가 💯

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/CarList.java
> +    // 1. 확실히 전체적으로 외부에서 값을 주입 받으니까 테스트 작성하기가 쉬운거 같은데 잘 리팩터링 했을까요??
해당 피드백과 같은 내용입니다 :)

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/CarList.java
> +    // 예를들어.. maxDistance 를 제대로 구하는지 테스트를 한다치면 아래 메서드가 public 이어야 할 거 같은데 ,, ㅠㅠ
외부에 공개할 메서드와 숨겨야할 메서드를 분리해보시면 좋을 것 같아요 :)
그렇다면 현재 코드 기준으로 외부에 공개할 메서드는 무엇일까요~?
요구사항에 맞게 외부 클라이언트들이 Cars에게 궁금한건 최대 거리가 궁금한것이 아닌 우승자인 것 같아요 ㅎㅎ

출력을 **위해서** maxDistance는 필요하지만 출력이 되지 않는 것처럼
클라이언트에서 필요한 요청들 위주로 테스트를 작성해주시면 좋을 것 같아요 ㅎㅎ
최대 거리는 내부 구현으로 숨기면 좋을 것 같습니다 :)

2021-03-23 17:22 UTC, ohtaeg commented on src/main/java/step5/domain/CarList.java
> +        cars.sort((o1, o2) -> o2.getPosition().compareTo(o1.getPosition()));
지금 compareTo가 해당 코드와 Position 객체 내부에서 중복해서 정의되고 있습니다.
compareTo를 하나만 재정의할 수 있도록 변경해주세요 :)

2021-03-23 23:49 UTC, wjdrbs96 commented on src/main/java/step5/domain/CarList.java
> +    // 예를들어.. maxDistance 를 제대로 구하는지 테스트를 한다치면 아래 메서드가 public 이어야 할 거 같은데 ,, ㅠㅠ
오오 모든걸 테스트 한다기 보다 클라이언트 요청들 위주로 테스트 하면 되겠군요!! 좋은 말씀 감사합니다~~

2021-03-23 23:50 UTC, wjdrbs96 commented on src/main/java/step5/domain/CarList.java
> +        cars.sort((o1, o2) -> o2.getPosition().compareTo(o1.getPosition()));
아 맞습니다! 이 부분도 뭔가 이상하다 했는데 깔끔하게 바꿔보겠습니다 감사합니다 ㅎㅎ

2021-03-23 23:52 UTC, wjdrbs96 commented on src/main/java/step5/controller/MainController.java
> +            System.out.println();
프로그램 실행 결과에 한줄 개행이 있어서 일부러 넣은건데 그래도 제거 하는 것이 좋을까요~??

2021-03-23 23:53 UTC, wjdrbs96 commented on src/main/java/step5/controller/MainController.java
> +            RacingGame racingGame = new RacingGame(carList);
ㅠㅠ 전체적인 피드백 바탕으로 한번 더 리팩터링 해보겠습니다!! 감사합니다~~

2021-03-23 23:57 UTC, wjdrbs96 commented on src/main/java/step5/domain/CarList.java
> +    public String findWinner(List<Car> cars, int carMaxDistance) {
오오 저도.. 코드를 작성할 때는 저렇게 생각했는데 말씀을 들으니 굳이 `List<Car> cars`를 받을 매개변수로 받을 필요가 없을 거 같습니다!! 

저번에 링크 남겨주신 거를 기반으로 일급 컬렉션에 대해서 좀 더 공부해보겠습니다~~

2021-03-24 00:25 UTC, wjdrbs96 commented on src/main/java/step5/domain/CarList.java
> +    }
ㅠㅠ 다른 리뷰에서 말씀드린 거 처럼 `create()` 메소드를 테스트 코드를 작성하기 위해 public 으로 했습니다! (설계하면서도 private 하고 싶은데 더 좋은 방법이 없을까 고민하긴 했습니다!!)  

그리고 말씀해주신 거 처럼 생성자에서 create 메소드를 호출해주면 CarList 객체를 만든 후에 create 메소드를 호출하는 코드도 사라질 수 있고 한결 깔끔해질 거 같습니다! (create 메소드 자체를 외부에 노출 시키면 실수로라도 Car 객체를 여러번 만들 수도 있고.. ?? 뭐 등등 문제가 있을 거 같기도 합니다!)  

그래서 친절하게 리뷰해주신 덕에 조금이라도 깔끔하게 설계가 되어 가는 거 같습니다!! 감사합니다 ㅎㅎ

2021-03-24 01:24 UTC, wjdrbs96 commented on src/main/java/step5/domain/CarList.java
> +public class CarList {
꿀팁 감사합니다 ㅎㅎ

2021-03-24 01:27 UTC, wjdrbs96 commented on src/main/java/step5/domain/RacingGame.java
> +    }
오!! 저도 move 랑 print 메소드랑 위와 같이 붙어 있어서 불편하다 생각했는데 말씀해주신 거 들으니 감탄이 나옵니다 ㅠ,ㅠ  저도 나중에는 리뷰어님 처럼 사고할 수 있기를 바라며,, 열심히 리팩터링 해보겠습니다 감사합니다~~

2021-03-24 01:27 UTC, wjdrbs96 commented on src/main/java/step5/domain/RandomMovingStrategy.java
> +        Random random = new Random();
아 고려하지 못한 거 같습니다 수정해보겠습니다 ㅎㅎ

2021-03-24 01:31 UTC, wjdrbs96 commented on src/main/java/step5/dto/InputDto.java
> +    }
그냥 혹시나 제가 작성한 것이 깔끔하지 못할까~? 했는데 괜찮다 해주시니 안심이 되는 거 같습니다! 

> 왜냐하면 DTO는 데이터를 전달하는 구조체이므로 입력은 순수하게 입력받은 값만 넘겨주고
> 비즈니스 로직에 필요한 데이터 검증은 DTO나 도메인이 검증해주면 좋다고 생각합니다..! ㅎㅎ

👍 👍  좋은 말씀 감사합니다~~

2021-03-24 12:37 UTC, ohtaeg commented on src/main/java/step5/controller/MainController.java
> +            System.out.println();
말씀해주신대로 입력 뷰나 ResultView 에서 해주시는게 각 View를 분리한 이유에 맞을 것 같습니다 👍

2021-03-24 15:28 UTC, wjdrbs96 commented
마지막까지 꼼꼼하게 리뷰 해주셔서 정말 감사합니다 ㅎㅎ 저도 100퍼 만족한 코드를 작성하진 못했지만,, 그래도 리뷰 받으면서 계속 생각하고 고민하다 보니 조금씩은 좋은 방향으로 리팩터링 할 수 있었던 거 같습니다 ! !  

마지막으로 궁금한 점도 주석으로 남겨놓았습니다~~

2021-03-24 17:47 UTC, ohtaeg approved these changes
수많은 피드백을 반영하시느라 고생 많으셨습니다 🎉 
첫 자동차 미션부터 많은 피드백을 드려 정균님의 의욕이 저하될까봐 걱정이 많았는데
끝까지 따라와주셔서 그리고 완주해주셔서 감사합니다 🙇 

서로 의견을 공유하면서 점진적으로 리팩토링 되는 과정을 보며 즐겁게 리뷰하였습니다 👍 
다음 로또 미션도 화이팅입니다!! 그동안 정말 고생 많으셨습니다 🥇

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/Cars.java
> +    public Cars(List<Car> cars, int dummy) {
dummy 매개 변수를 따로 사용하지 않기에 받을 필요는 없을 것 같아요 ㅎㅎ

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/Cars.java
> +        }
향상된 포문을 사용하시면 더 깔끔해질 것 같네요 👍 
```suggestion
        for (Car car : carList) {
            car.move(new RandomMovingStrategy());
        }
```

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/Cars.java
> +                .filter(car -> car.getPosition().equals(new Position(position.getPosition())))
getter가 아닌 Car 객체에게 메시지를 보내는 방식으로 구현을 한다면
캡슐화를 지킬 수 있을 것 같아요 :)
```suggestion
                .filter(car -> car.isWinner(position))
```

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/Cars.java
> +    private final List<Car> carList;
Cars 네이밍으로 변경 👍 
필드 명도 같이 변경되었으면 더 좋았을 것 같네요 😄

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/Cars.java
> +        return carList.get(0).getPosition();
람다식으로 변경해볼 수 있을 것 같아요 :)
```suggestion
        return carList.stream()
                      .sorted((o1, o2) -> o2.getPosition().compareTo(o1.getPosition()))
                      .map(Car::getPosition)
                      .findFirst()
                      .orElseThrow(() -> new RuntimeException("max 값을 찾을 수 없습니다."));
```

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/RacingGame.java
> +            ResultView.print(carList.getCarList());
RacingGame은 컨트롤러 역할인 입출력과 도메인간 중개 역할을 해주고 있기에 출력 뷰를 호출해도 좋다고 생각합니다 :)

2021-03-24 17:47 UTC, ohtaeg commented on src/main/java/step5/domain/RandomMovingStrategy.java
> +    private static final Random random = new Random();
피드백 반영 👍

2021-03-24 17:47 UTC, merged

2021-03-24 23:46 UTC, wjdrbs96 commented on src/main/java/step5/domain/Cars.java
> +    public Cars(List<Car> cars, int dummy) {
ㅠㅠ 위에 이미 인자가 하나인 생성자가 존재해서 어쩔 수 없이 dummy 인자를 받았습니다.. (좋은 방법이 생각나지 않아서요 ㅠ ㅠ)

2021-03-24 23:47 UTC, wjdrbs96 commented on src/main/java/step5/domain/Cars.java
> +    private final List<Car> carList;
오오 체크하지 못했는데 감사합니다 ㅎㅎ