Step5 - 자동차 경주(리팩토링) 리뷰 요청드립니다
next-step/java-racingcar pull request #2139
Opened 2021-03-26 13:31 UTC by whdudtlr9042

TDD 강의를 보고 리팩토링을 해봤는데, 고칠 점과 공부할 것이 많았네요. 

강의를 들으면서 연습겸 DTO Data 생성자에 데이터 체크를 넣어봤는데요. 
DTO일 경우에는 생성자에 validation 로직을 넣어도 될지 궁금합니다.

Winner2의 경우에는 Winner 클래스 리팩토링을 위해 임시로 만들어둔 클래스입니다 ^^;
마지막에 Winner2를 Winner로 바꿔서 커밋했습니다.

2021-03-27 01:03 UTC, ghojeong requested changes
조무건님!
마지막 단계라 그런지, 상당히 구조가 잡힌 모습이군요!
조금 더 개선할 여지가 남아있는 듯하여, 수정을 요청드립니다.

> DTO일 경우에는 생성자에 validation 로직을 넣어도 될지 궁금합니다.

dto 객체 내부에서는 로직이 가능한 없도록 해주시면 감사하겠습니다.

2021-03-27 01:03 UTC, ghojeong commented on src/main/java/step4/domain/RandomMovingStrategy.java
> +    }
movable 을 할 때마다, new Random() 으로 랜덤 인스턴스를 매번 새로 생성하고 있는 듯한데,
재활용되고 같은 기능을 하는 인스턴스는 private static 멤버로 관리바랍니다.
자바에서 객체의 생성과 Garbage Collection 은 언제나 커다란 오버헤드라서요.

2021-03-27 01:03 UTC, ghojeong commented on src/main/java/step4/domain/Car.java
> +    }
```suggestion
    public boolean isWinner(int grade) {
        return (grade != 0) && position() == grade;
    }
```

이렇게는 안되나요?

2021-03-27 05:07 UTC, whdudtlr9042 commented on src/main/java/step4/domain/Winner.java
> +    }
말씀대로 연속적으로 2번 호출 했을때 중복된 결과가 도출됩니다.

다만 두번째 findWinner는 private로 선언해서 외부에서는 첫번째 findWinner만 호출하도록 코딩했는데, 

테스트 코드로서 문제될 여지가 있어서 그런건가요 ?? 
추가 수정이 필요한지 질문드립니다.

2021-03-27 05:49 UTC, ghojeong commented on src/main/java/step4/domain/Winner.java
> +    }
흠... 이 부분은 반드시 수정이 필요하다기 보다는 (제가 눈높이를 너무 높인 감이 없지 않아 있네요),
저 같은 경우는 이러한 부분들 까지 고려해서 개발을 진행한다고 말씀을 드리고 싶었습니다.

결국 왜 불변 객체가 중요시되고 강조되는가 하는 부분인데,
누군가 조무건 님의 코드를 이어받아서 유지를 하거나 협업을 한다고 생각을 해보겠습니다.
그 분이 저처럼 코드의 모든 내용을 하나하나 읽어서 개발을 하면 다행이겠지만,
불행히도 그렇지 않은 경우가 매우 많습니다.
findWinner 를 지금은 한번만 하였는데, 다른 동료 개발자가 findWinner 가 이미 호출되었는지 모르고 한번 더 호출한다고 생각해보세요.
그럴 경우, 그 분은 왜 findWinner 메서드를 호출할 때마다, 결과가 달라지냐고 항의를 할 수 있습니다.

java Spring 백엔드 개발자라면, 멱등성(Idempotency) 를 고려해 개발해야하는 경우도 있을 수도 있기에,
참고를 해보시라고 언급해보았습니다.

반드시 꼭 수정하실 필요는 없습니다.
다만 멱등성이라는 단어를 처음 들어보셨다면, 한번쯤 공부는 해두시면 좋겠습니다.
저는 초짜시절 현업에서 선임 개발자가 이는 멱등성에 위반됩니다 라고 한줄 커멘트를 달은 것 때문에 1주일간 멘붕을 했었습니다.

2021-03-28 00:28 UTC, ghojeong approved these changes
조무건 님!
까다로운 리뷰에 대응해주시느라 정말 고생 많으셨습니다! 🙇 
조무건 님처럼 열심히 해주시는 분을 만나면, 저도 모르게 신이나서 점점 허들을 올려버렸네요.
열심히 해주셔서 정말 감사합니다!
모든 미션을 완수할 수 있기를 기원합니다! :octocat:

2021-03-28 00:28 UTC, ghojeong commented on src/main/java/step4/util/InputValidator.java
> +            String message = "자동차 이름이 {0}자 초과하였습니다.".replaceAll("\\{0\\}", String.valueOf(NAME_LENGTH));
```suggestion
        if (name.length() >= NAME_LENGTH) {
            String message = "자동차 이름이 {0}자 초과하였습니다.".replaceAll("\\{0\\}", String.valueOf(NAME_LENGTH));
```

요구사항 중 "자동차 이름은 5자를 초과할 수 없다." 라는 말의 뜻은,
5자 까지는 허용이 되어야 한다는 말입니다.
예시에 나온 crong 과 honux 에 대해 5자를 초과했다고 Exception 이 뜨고 있네요

코드를 너무 잘 작성해주셔서, 마지막으로 요구사항 구현 여부를 하나하나 체크하다가,
사소한 점 하나를 발견했습니다.
수정할 필요는 없고, 저처럼 참 편집증적인 리뷰어가 있구나 하고 웃고 넘어가주시면 될것 같습니다.

<img width="416" alt="스크린샷 2021-03-28 오전 9 23 30" src="https://user-images.githubusercontent.com/38595650/112738572-4d0dea00-8fa7-11eb-830f-2de3b54b3e68.png">

2021-03-28 00:28 UTC, merged