Sh6137step1 문자열계산기 리뷰 요청합니다.
next-step/java-racingcar pull request #2192
Opened 2021-05-02 14:37 UTC by sh6137

2021-05-03 09:10 UTC, liquidjoo requested changes
안녕하세요. 이번 레이싱카 미션 리뷰를 맡게된 김성주 입니다 🙇
문자열 계산기 구현 잘 해주셨어요 👍  특히, 메서드 분리를 잘해주셨습니다!
하지만 아쉬웠던 것은 계산기의 각 기능에 대한 테스트 코드가 없는 것과 자동차 경주에 대한 코드가 없어서 아쉬웠습니다. 😭 
몇가지 피드백 남겨드렸으니 확인하시고 자동차 경주 구현까지 반영해주세요.

넥스트스텝 플랫폼의 `과제 진행 요구 사항` 가이드에 맞게 커밋 메시지 작성해보는 것이 어떨까요?
혼자의 고민으로 해결이 안되는 부분이 있다면 DM 주셔서 같이 고민해봐요!!

2021-05-03 09:10 UTC, liquidjoo commented on src/main/java/step2/Cal.java
> +
```suggestion

```
공백 라인을 의미 있게 사용하는 것이 좋아 보이며, 문맥을 분리하는 부분에 사용하는 것이 좋아요. 과도한 공백은 다른 개발자에게 의문을 줄 수 있어요.

2021-05-03 09:10 UTC, liquidjoo commented on src/main/java/step2/Cal.java
> +                .filter(s -> (s != null && s.length() > 0))
Short circuit evaluation 👍

2021-05-03 09:10 UTC, liquidjoo commented on src/main/java/step2/Cal.java
> +    public String docal(String[] sachicresult, String[] numberresult) {
```suggestion
    public String doCal(String[] sachicresult, String[] numberresult) {
```
자바 스타일 가이드를 참고하시면 좋을 것 같아요 👍 
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

2021-05-25 01:49 UTC, liquidjoo requested changes
조금씩 코드가 발전하고 있는 모습 보기 좋습니다 👍 
몇가지 코멘트 남겨드렸으니 확인해주세요. 
고민이 된다면 언제든 DM 주세요!

2021-05-31 02:01 UTC, sh6137 commented on src/main/java/racing/racingrebuild/Car.java
> +    }
Vo에도 명시적 초기화를 하여야 하는지 궁금합니다.

2021-05-31 02:02 UTC, sh6137 commented on src/main/java/racing/racingrebuild/Car.java
> +        if (number >= 4) {
상수로 치환하여 넣겠습니다.

2022-04-04 06:03 UTC, closed without merging