Step2
next-step/java-racingcar pull request #2277
Opened 2021-07-20 06:15 UTC by kdh85

문자열 계산기

commit 코맨트가 잘못들어간 부분이 있어서 아래와 같이 다시 정리드립니다.

기능 구현 순서
* 변수 두개를 제공 받고 사칙연산 테스트코드와 구현체 코드 작성.(불필요한 변수선언 제거)
* 문자열 값이 null 이거나 빈공간값인 경우, IllegalArgumentException을 리턴하는 기능 개발.
* 사칙연산 기호를 입력 받았을때 해당 기호가 아닌 경우, IllegalArgumentException을 리턴하는 기능 개발.
* 수식을 입력 받아서 " " 기준으로 하나하나 나눠서 값을 리스트에 담는 기능 개발.
* 수식값 리스트에서 사용되는 숫자와 사칙연산 기호를 분리하여 각각 리스트에 담는 기능 개발.
* 연산자 기준으로 순차적으로 값을 받아서 연산 결과를 도출하는 기능 개발.

2021-07-20 08:15 UTC, seok-2-o requested changes
문자열 계산기 잘 구현해주셨네요.
몇 가지 코멘트 남겨놓았으니 확인 후 리펙토링 진행하면 좋을 것 같아요.
수정후 다시 PR 주세요.

2021-07-20 08:15 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +            if(j>0){
```suggestion
            if(j > 0){
```
이번 과정에서 들여쓰기는 1번 이하로 제한하고 있어요 들여쓰기를 줄이려면 어떻게 해야 할까요.

2021-07-20 08:15 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +    public static Map<String,List<String>> valueClassification(List<String> wordList) {
Map<String,List<String>> 가독성이 매우 떨어지는 자료형이네요
객체를 만들어서 분리해보는건 어떤가요 ?

2021-07-20 08:15 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +    public static int getOperation(int num1, String operation, int num2) {
메소드의 이름과 행위과 일치 하지 않네요.

2021-07-20 08:15 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +        List<String> valueList = new ArrayList<>();
변수의 이름의 자료구조를 나타내는것은 추후 유지보수 관점에서 좋지 않다고 생각하는데 동현님은 어떻게 생각하시나요?
자료형을 다른 컬렉션(Set) 으로 변경한다면 어떻게 될까요?

2021-07-20 08:15 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +            }
하나씩 순회할 필요가 있을까요 인덱스를 2개씩 올리면 어떤가요?

2021-07-20 08:15 UTC, seok-2-o commented on src/test/java/study/calculator/CalculatorTest.java
> +    void valueIsNullOrBlankTest() {
@ParameterizedTest 를 활용해 봐도 좋을 것 같아요.

2021-07-20 11:37 UTC, kdh85 commented on src/main/java/study/calculator/Calculator.java
> +            }
말씀하신데로 인덱스값 변경하는 방법도 생각해봤는데요. 일전에 얘기하신 들여쓰기 제한조건도 같이 고려를 해야 할거같아서 방식을 바꾸려고 합니다.

일단 지금 테스트해보는 방법은 stream안에 filter를 사용해서 변수리스트와 연산자 리스트를 각각 만드는걸 생각중입니다.
 //연산자들을 모음.
        List<String> operations = Arrays.stream(words)
                .filter(s -> s.equals("+") || s.equals("-") || s.equals("*") || s.equals("/"))
                .collect(Collectors.toList());

        //연한될 변수값들을 모음.
        List<String> values = Arrays.stream(words)
                //뭔가 더 깔끔한 방법을 모색중.
                .filter(s -> !s.equals("+") && !s.equals("-") && !s.equals("*") && !s.equals("/"))
                .collect(Collectors.toList());

이런식으로 접근하는건 어떻게 생각하시나요?

2021-07-20 11:37 UTC, kdh85 commented on src/test/java/study/calculator/CalculatorTest.java
> +    void valueIsNullOrBlankTest() {
네 해당 부분은 @ParameterizedTest로 다시 테스트 수정해보겠습니다.

2021-07-20 11:42 UTC, kdh85 commented on src/main/java/study/calculator/Calculator.java
> +        List<String> valueList = new ArrayList<>();
이 부분은 제 생각과 다른 점이네요.
저같은 경우는 SI부서에서 재직을 했었는데요.
 사내 개발 문화가 타인에게 변수명을 통해 자료구조를 직관적으로 표현하는 것을 원하는 분위기여서
 저런식으로 작성을 해왔었습니다.

그런데 이 부분을 문제점이라고 말씀하셔서 곰곰히 생각해보았습니다.
왜 안좋다고 표현을 하셨을까,
이건 아무래도 제가 SI의 직군 특성상 빠르게, 산발적으로 개발하던 문화에 오래 노출되서
자사 서비스를 운영, 유지보수하는 분들의 시각과 좀 다른게 아닌가 하는 생각이 듭니다.

유지보스의 측면에서 본다면 저런식으로 자료구조형 메소드명이 분명 추후에 자료구조 변경이 필요한 상황이 오면
수정요소가 되기 때문에 유지보수 측면에선 불리한게 맞는거 같습니다.

이 부분은 제가 좀더 신경을 써서 메소드명을 만드는 것으로 정리하겠습니다.
도움 감사합니다.

2021-07-20 11:42 UTC, kdh85 commented on src/main/java/study/calculator/Calculator.java
> +    public static int getOperation(int num1, String operation, int num2) {
IDE 자동완성으로 만들고 수정을 제대로 못했네요. 수정하겠습니다.

2021-07-20 11:43 UTC, kdh85 commented on src/main/java/study/calculator/Calculator.java
> +    public static Map<String,List<String>> valueClassification(List<String> wordList) {
현재 구조는 맵의 키값 기준으로 각각 연산자 리스트, 변수 리스트를 담고 있는 구조인데요.
여기서 객체로 분리하자고 하신 의미는 연산자, 변수를 각각 도메인 클래스로 분리하고 이것을
Map 또는 Set등으로 담는걸 말씀하시는건지 궁금합니다.

2021-07-20 11:46 UTC, kdh85 commented on src/main/java/study/calculator/Calculator.java
> +            if(j>0){
enum 클래스를 활용해서 구조를 변경해보려고 준비중입니다.

https://techblog.woowahan.com/2527/
여기에서 약간의 힌트를 얻은 기분입니다.

enum과 Bifuntion을 이용해서 수정해보려고 하는데요. 어떻게 생각하시나요?

2021-07-22 00:04 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +    public static Map<String,List<String>> valueClassification(List<String> wordList) {
아뇨 사용자 정의 클래스를
Operator , Number 등을 정의하면 좋을 것 같아요.

2021-07-22 00:08 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +        List<String> valueList = new ArrayList<>();
아하 저와 반대되는 경험을 가지고 계시는군요
저는 서비스회사에서 개발보다 유지보수를 우선시 하면서 개발을 진행해와서 
그 위주로 고민을 많이 했던 것 같습니다.

말씀하신 것처럼 콜렉션을 명시하는 것도 직관적이고 좋을 수 있네요. 
상황에 따라 잘 선택하는게 좋아보이네요.

2021-07-22 00:09 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +            }
가독성은 좋아보이는데 루프를 2번 돌아야하네요. 이부분은 어떻게 생각하시나요?
숫자 한번 기호 한번

2021-07-22 00:12 UTC, seok-2-o approved these changes
리펙토링 잘해주셨네요 👏 

enum 을 활용해서 가독성이 많이 향상된것 같아요.
질문하신 부분에 답변 남겨놓았습니다.

본격적으로 자동차 미션 달려보시죠 🔥

2021-07-22 00:12 UTC, seok-2-o commented on src/main/java/study/calculator/Operation.java
> +public enum Operation {
👍

2021-07-22 00:12 UTC, seok-2-o commented on src/main/java/study/calculator/Calculator.java
> +    public static Map<String,List<String>> valueClassification(List<String> wordList) {
둘을 감싸는 Expression 객채도 나올 수 있겠네요.

오버엔지니어링일 수 있지만 수업이니만큼 객체를 활용하는 연습을 많이 해보시면 좋을 것 같아요.

2021-07-22 00:13 UTC, merged