Step3
next-step/java-racingcar pull request #2293
Opened 2021-07-20 12:53 UTC by kimdonggyu-dev

안녕하세요 현수님 !! 😄
3단계 자동차 경주 미션 완료했습니다.
저번 단계에서 주신 피드백은 반영하여 같이 푸쉬했고, 남겨주신 코멘트에 간단하게 코멘트도 작성해봤습니다.

public 메서드 위주로 테스트를 구성하여 테스트 코드가 몇개 안되는데, 더 이상 마땅히 테스트 할게 생각나지가 않네요.
- private 메서드는 public 메서드를 통해 간접적으로 테스트 하였습니다. (입력값이 정수이거나 Car의 random 범위)

이번에도 피드백 잘 부탁드리겠습니다~ 👍

2021-07-21 06:30 UTC, hyunssooo requested changes
안녕하세요 동규님 🙂
step3까지 빠르게 진행해주셨네요! 
몇 가지 코멘트 남겼습니다. 
코멘트에 대해서 함께 고민하고 싶으시거나 궁금한 점 있으시면 편하게 연락주세요. 🙂

2021-07-21 06:30 UTC, hyunssooo commented on src/main/java/racingcar/RacingGame.java
> +    }
이 부분도 마찬가지로 view에 종속적인 로직으로 보여요. 이 부분은 output view로 나눠보는 것은 어떨까요? 
그리고 패키지도 역할에 맞게 나눠보면 좋을 것 같아요!

2021-07-21 06:30 UTC, hyunssooo commented on src/test/java/racingcar/CarTest.java
> +        });
```suggestion
        assertDoesNotThrow(() -> new Car());
```
한줄로도 표현 가능하겠네요! 따로 변수에 할당할 필요는 없어보입니다. 참고만 부탁드려요!

2021-07-21 10:49 UTC, kimdonggyu-dev commented
@hyunssooo 

안녕하세요. 현수님~
피드백 확인하여 다시 작성해보았습니다.
크게 4가지로 분리해봤어요. 
중간 중간 질문도 있어서 답변 부탁드리겠습니다 😁

### ApplicationRunner
- 클라이언트라고 생각하고 분리해주었습니다.
- 데이터를 입력받고, 그 데이터로 컨트롤러를 호출하는 책임을 가지고 있다고 생각했습니다.

### controller
- 컨트롤러의 책임과 역할은 데이터를 입력받고, 입력값을 검증하는것으로 생각했습니다.
- 그래서 컨트롤러는 입력값을 받고, parseInt() 메서드를 컨트롤러로 옮기어 입력값을 검증했습니다.
- **Q)** 컨트롤러에서 n번 게임을 실행시키고, n번 consoleView 에게 데이터를 전달하는게 옳은 구조일까요?
    - 서비스를 중간에 추가한다면 n번 게임을 실행시킨 값 을 종합해서, 한번만 View 에 전달해줄수는 있을거같아요.

### domain
- 도메인에 존재하는 view 관련 로직을 ConsoleView 로 이동하였습니다.
- **Q)** 하지만 Car 도메인에서 getter를 만들기가 싫었는데.. 딱히 방법이 없더라구요. (좋은 아이디어가 있을까요?)
- 또한 view에 데이터를 전달해주기 위해 RacingGame에서 start() 시에 LIst<Car>를 반환해주었습니다.
- 하지만 view에서 도메인객체의 존재를 감추고 도메인의 변경시 view 변경되는거 까지 막기위해 dto를 두었습니다.
    - 이로 인해 dto의 인터페이스가 변하지 않는 이상, view가 변하지 않을거라고 생각했어요.

### View
- view의 책임은 콘솔 결과를 출력하는 역할을 가지고 있다고 생각했어요.
- **Q)** ConsoleView 에서 getProgressBar() 를 테스트 하자고 접근제어자를 public 으로 만들기도 그래서 consoleView를 테스트 할 수 없었네요. public 메서드인 print() 메서드로 간접적으로 테스트하자니 단순히 출력만 하고있어서 어렵네요. 좋은 방법이 있을까요?

### 기타
- **Q)** 현재 도메인 객체에서 랜덤값에 의존하고 있기 때문에, 게임을 1번 실행할 경우 0인지 1인지를 테스트하게 했네요. (이게 맞을까요?)
- **Q)** 이건 개인적으로 궁금한건데 서비스에서 controller의 request dto를 파라미터로 받는편이신가요? 아니면 dto객체에서 필요한 데이터만 (ex. id값) 서비스로 넘겨주는 것을 선호하실까요? (도메인 객체를 넘겨줄수도있을거같아요.) , 또한 서비스에서 return 도 dto를 반환해주는게 맞을까요? 아니면 도메인 객체를 반환해주고 컨트롤러에서 dto로 변환해주는게 맞을까요?

현수님이 주신 피드백으로 여러 고민을 해본거같아요. 
각 책임에 맞게 적절하게 할당해봤습니다.
또한 추후 웹이 추가되거나 하는 확장성도 고려해봤어요.

피드백 한번 더 부탁드리고, 앞으로도 많이 빡센 피드백 부탁드리겠습니다!! 🙏🏻
감사합니다. 😄

2021-07-21 15:52 UTC, hyunssooo approved these changes
안녕하세요 동규님 🙂
코멘트 빠르게 반영해주셨네요! 
몇 가지 코멘트 남겼습니다. 
다음 step 진행하시면서 참고 부탁드립니다!

2021-07-21 15:52 UTC, hyunssooo commented on src/main/java/racingcar/controller/ConsoleController.java
> +
Controller의 현재 구조는 모든 input을 받아야만 게임을 진행할 수 있는 구조네요. 
Controller가 View를 의존하고 있는 구조를 가진다면 어떤 장점이 있을까요?

2021-07-21 15:52 UTC, hyunssooo commented on src/main/java/racingcar/controller/ConsoleController.java
> +    }
실질적인 game은 여기서 하고 있네요. 그렇다면 이 메서드는 두가지 일을 하는 건 아닐까요? 
responseDto를 도입한 부분 👍
responseDto를 사용하지 않는 방법은 없을까요? VO가 무엇인지 찾아보면 좋을 것 같습니다.

2021-07-21 15:52 UTC, hyunssooo commented on src/main/java/racingcar/domain/Car.java
> +
만약 car 의 위치가 3인 객체를 테스트하려면 어떤 방법이 있을까요?

2021-07-21 15:52 UTC, hyunssooo commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
사용하지 않는 생성자는 제거해주세요.

2021-07-21 15:52 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarTest.java
> +    }
테스트도 프로덕션 코드와 마찬가지로 유지보수 대상입니다. random이라는 변수명이 맞을까요? 🤔

2021-07-21 15:52 UTC, hyunssooo commented on src/test/java/racingcar/domain/RacingGameTest.java
> +        cars.forEach(r -> assertTrue(r.getNumberOfMove() == 1 || r.getNumberOfMove() == 0));
변수명은 축약어를 사용하지 않는 것이 좋습니다. 적절한 이름을 지어주는 것은 어떨까요?

2021-07-21 15:52 UTC, merged

2021-07-21 15:52 UTC, hyunssooo commented
> Q) 컨트롤러에서 n번 게임을 실행시키고, n번 consoleView 에게 데이터를 전달하는게 옳은 구조일까요? 

구조에 대한 정답은 없다고 생각합니다. 현재 서비스가 없더라도 충분히 n번의 결과를 view에 전달할 수 있지 않을까요? 

> Q) 하지만 Car 도메인에서 getter를 만들기가 싫었는데.. 딱히 방법이 없더라구요. (좋은 아이디어가 있을까요?)

도메인 객체의 데이터를 꺼내기 위해서는 불가피하다고 생각합니다. 하지만 비지니스 요구사항을 처리하기 위해 getter는 지양하는 것이 좋습니다. 

> 하지만 view에서 도메인객체의 존재를 감추고 도메인의 변경시 view 변경되는거 까지 막기위해 dto를 두었습니다. 

좋은 방법이라고 생각해요. VO에 대해서 찾아보는 것은 어떨까요? VO의 특징은 어떤 것이 있는지 찾아보면 좋을 것 같아요. 

> Q) ConsoleView 에서 getProgressBar() 를 테스트 하자고 접근제어자를 public 으로 만들기도 그래서 consoleView를 테스트 할 수 없었네요. public 메서드인 print() 메서드로 간접적으로 테스트하자니 단순히 출력만 하고있어서 어렵네요. 좋은 방법이 있을까요?

View에 대한 테스트는 사실 하기 어려운 부분입니다. 테스트 가능한 부분, 어려운 부분을 나눠보고 최대한 테스트 가능한 구조에 대해서 고민해 보는 것도 도움이 될 것 같아요. 또한 실제 비지니스를 담고 있는 도메인 객체에서도 같은 고민을 해보시면 좋을 것 같습니다! 현재 랜덤 값은 테스트하기 어려운 부분입니다. 그렇다면 최대한 랜덤 값을 격리해보는 것은 어떨까요?? 

> 현재 도메인 객체에서 랜덤값에 의존하고 있기 때문에, 게임을 1번 실행할 경우 0인지 1인지를 테스트하게 했네요. (이게 맞을까요?)

이 부분은 RacingGame 클래스를 말씀하시는 것 같아요. 이 부분도 저는 충분히 랜덤 값에 대한 의존성을 끊을 수 있을 것 같습니다. RacingGame 에서 move() 메서드가 실행될 때 1번의 움직임만 시도해보는 것은 어떨까요? 그렇다면 메서드 파라미터로 랜덤하게 생성된 숫자들을 받을 수 있지 않을까요?? 
제 개인적 생각이니 참고만 부탁드려요! 

> Q) 이건 개인적으로 궁금한건데 서비스에서 controller의 request dto를 파라미터로 받는편이신가요? 아니면 dto객체에서 필요한 데이터만 (ex. id값) 서비스로 넘겨주는 것을 선호하실까요? (도메인 객체를 넘겨줄수도있을거같아요.) , 또한 서비스에서 return 도 dto를 반환해주는게 맞을까요? 아니면 도메인 객체를 반환해주고 컨트롤러에서 dto로 변환해주는게 맞을까요?

개인적으로 controller에서 reqeustDto를 서비스로 넘기는 것을 선호하지는 않아요. 이유는 controller와 service는 다른 layer이고 controller는 아래로 service를 의존하고 있습니다. 이 경우에 service가 requestDto를 파라미터로 받는다면 각 레이어에 순환이 생긴다고 생각합니다. 
또한, controller에서 도메인 객체를 넘겨주는 방법도 선호하지 않아요. 도메인 객체는 service 내에서만 관리하는 편을 선호합니다. service에서 도메인 객체를 리턴하는 것도 선호하지 않습니다. 이 두 가지 경우 도메인 객체의 관리 포인트가 controller, servcie 두 곳으로 나뉘기 때문이에요.

2021-07-24 01:44 UTC, kimdonggyu-dev commented on src/main/java/racingcar/ApplicationRunner.java
> +        String numberOfAttempts = scanner.nextLine();
주신 그림으로 생각해보니 view에서도 컨트롤러로 요청을 줄 수가 있겠네요..
평소 view가 없는 server to server api 위주로만 만들다보니 헷갈렸네요 :) 
감사합니다 😀

![image](https://user-images.githubusercontent.com/73709836/126854050-dad29f33-3ea1-4087-bc9c-255565a3d6b6.png)

2021-07-24 01:44 UTC, kimdonggyu-dev commented on src/main/java/racingcar/controller/ConsoleController.java
> +
해당 메서드가 스프링에서 @GetMapping 같은 하나의 인터페이스를 받는 메서드라고 생각해서 view를 의존하는 구조로 만들었습니다.

제가 생각했을때 장점이라면.. 음 .. 뷰와 도메인간의 의존성을 중간에서 끊을 수 있을거같아요.
장점에 대해 설명 부탁드려도될까요? 🤔

2021-07-24 01:45 UTC, kimdonggyu-dev commented on src/main/java/racingcar/controller/ConsoleController.java
> +    }
제가 알고 있는 VO는 도메인 객체에서 특정 필드의 불변성을 유지하고, 원시타입이나 단순 값을 클래스로 래핑하는걸로 알고있어요. 그에따라서 그 래핑한 클래스(vo) 에는 여러가지 로직도 녹일 수 있고요.

그래서 Car클래스의 int numberOfMove 를 value object로 만들어서 controller로 반환해주는걸 의미할까요? 그러면 그 컨트롤에서 반환된 vo는 view에 전달되어서 해당 vo가 view에 의존하게되는 구조인데 괜찮을까요?

어떤식으로 vo를 활용할 수 있는지 여쭤볼 수 있을까요?

2021-07-24 01:46 UTC, kimdonggyu-dev commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
추후 저 이외에 다른 개발자와 협업을 한다고 생각했을때 NoArgumentConstructor 사용을 금지한다는 의미에서 남겨둔건데 삭제하는게 맞을까요? (생성자 파라미터인 numberOfCars가 없으면 시스템이 올바르게 동작하지 않기 때문 입니다)

2021-07-24 01:47 UTC, kimdonggyu-dev commented on src/main/java/racingcar/domain/Car.java
> +
답변주신 내용중에

> 이 부분은 RacingGame 클래스를 말씀하시는 것 같아요. 이 부분도 저는 충분히 랜덤 값에 대한 의존성을 끊을 수 있을 것 같습니다. RacingGame 에서 move() 메서드가 실행될 때 1번의 움직임만 시도해보는 것은 어떨까요? 그렇다면 메서드 파라미터로 랜덤하게 생성된 숫자들을 받을 수 있지 않을까요??

RacingGame에서 Random 필드를 외부로 옮기고, 랜덤값을 파라미터로 받게되면 검증할 수 있을거 같네요 👍

2021-07-24 06:39 UTC, hyunssooo commented on src/main/java/racingcar/controller/ConsoleController.java
> +
ApplicationRunner가 모든 요청을 Dto로 만들어서 넣어주는 구조군요. 
요구사항이 늘어난다면 Dto는 점점 더 두꺼워 지고 여러가지 요청에 대한 요청값이 늘어나지 않을까요? 
한번의 요청으로 모든 것을 처리하는 부분이 저는 조금 과하다고 느꼈습니다. 
물론 지금은 동규님 의견을 들어보니 요구사항이 간단하니 문제 없는 구조라는 생각도 드네요 🙂
이 부분은 개인적인 의견이니 참고만 부탁드릴게요!

2021-07-24 06:39 UTC, hyunssooo commented on src/main/java/racingcar/controller/ConsoleController.java
> +    }
VO의 특징 중 하나는 불변함을 보장합니다. 그래서 저는 View로 바로 나가도 괜찮다고 생각합니다. 사이드 이펙트가 없으니깐요.
이 부분은 개인적인 의견이니 참고만 해주세요. 
Car 객체의 필드들을 VO로 만들어 볼 수 있고 Car 객체 자체를 불변으로 만드는 것도 의미 있을 것 같아요 :)

2021-07-24 06:39 UTC, hyunssooo commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
다른 생성자가 존재하면 기본 생성자는 정의하기 전까지는 사용하지 못하는데.. 제가 놓친 부분이 있을까요?? 🤔

2021-07-24 12:57 UTC, kimdonggyu-dev commented on src/main/java/racingcar/controller/ConsoleController.java
> +
컨트롤러 메서드에 dto를 넘게주는게 아니면 혹시 현수님이라면, 어떻게 만드셨을지 간단한 예제를 볼 수 있을까요?


참고: https://github.com/next-step/java-racingcar/blob/a8d88ef6e534b530e1b9a9736741135a9b88bbfb/src/main/java/racingcar/ApplicationRunner.java

2021-07-24 12:58 UTC, kimdonggyu-dev commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
제가 잘못 알고있었네요. 감사합니다 👍

2021-07-24 13:13 UTC, hyunssooo commented on src/main/java/racingcar/controller/ConsoleController.java
> +
https://github.com/next-step/kotlin-racingcar/tree/hyunssooo

제가 작성한 코드인데 코틀린이지만 별 무리 없이 보실 수 있을 거라 생각합니다 🙂
`Application.main()` 을 컨트롤러라고 생각하시면 됩니다!