Step3 자동차 경주
next-step/java-racingcar pull request #2318
Opened 2021-07-20 16:25 UTC by ryu-sh

클래스를 최대한 잘게 쪼갰는데 맞게 한건지 의문이 드네요. 리뷰 부탁드려요!

2021-07-21 10:51 UTC, dbeod2 requested changes
안녕하세요! 
자동차 경주 미션 잘 진행해주신 것 같아요! 

다만, 몇가지 의견 드릴 부분과 고민해보면 좋을 것 같은 부분에 대해 코멘트 달아놨습니다. 🙇🏻‍♀️
궁금한 점이나 의견나누고 싶은 부분있으시면 편하게 DM주세요! 

피드백 반영 후 리뷰 재요청 부탁드릴께요! 🏎🏎🏎

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/Car.java
> +    int position;
기본적으로 인스턴스 변수의 접근 제어자는 private 입니다. 
default로 선언해주신 이유가 있으실까요?

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/Car.java
> +    }
비지니스 로직과 UI로직을 한 클래스에서 담당하지 않도록 분리해주세요 ~
비지니스 로직과 ui로직이 한 클래스에 있는 것은 단일 책임의 원칙에도 위배가 됩니다. 

프로그래밍 요구사항을 확인해보시면 아래와 같이 작성되어 있습니다. 🙇🏻‍♀️
**핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.**

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/Car.java
> +        final int MOVE_NUM = 4;
MOVE_NUM을 선언하신 이유가 매직넘버라서 의미를 명시해주신 것 같은데 맞을까요?
보통 매직넘버는 클래스 내 상수로 선언해서 사용합니다 :) 

매직넘버를 정수로 치환한 부분의 위치를 수정해보는건 어떨까요?

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/RacingCar.java
> +public class RacingCar {
해당 클래스는 자동차 경주를 위한 도메인일까요? 🤔
메서드 안에  System.out.println(); <- 를 찍어두신 이유가 있으실까요?

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/CreateRandomNumber.java
> +public class CreateRandomNumber {
랜덤한 요소의 코드를 분리해주셨네요! :) 

한가지 의견을 드리자면 createRandomNumber클래스의 getRandomNumber()메서드를 호출 할 때마다
random인스턴스가 반복적으로 호출 되며 반복적으로 생성되는 것보다
한개를 만들어 놓고 사용하는게 자원적인 측면에서 더 좋을 것 같습니다 🙏

2021-07-21 10:51 UTC, dbeod2 commented on src/main/java/racingcar/Car.java
> +    private void print(){
ui로직이긴하지만 print()라는 포괄적인 이름보다는 한눈에 봐도 알 수 있는 의미있는 이름이면 좋을 것 같습니다.

참고해보면 좋을 것 같아 url전달드립니다!
(https://zeddios.tistory.com/419)

2021-07-21 12:31 UTC, ryu-sh commented on src/main/java/racingcar/Car.java
> +    int position;
이부분은 단순 실수 한것 같아요 ㅠ 수정하겠습니다!

2021-07-22 01:03 UTC, dbeod2 approved these changes
안녕하세요 😀
자동차 경주 피드백 잘 반영해주셨네요 👏🏻👏🏻👏🏻

궁금한 부분에 주석 달아주셔서 코멘트 남겨드렸습니다 
보완되면 좋을 것 같아서 코멘트 남긴 부분도 있는데 확인 부탁드립니다. 

다음 미션하면서 적용하셔도 될 것 같아서 여기서 머지하겠습니다! 
다음미션을 진행해주세요 :)

2021-07-22 01:03 UTC, merged