4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2332
Opened 2021-07-21 04:56 UTC by nokchax

안녕하세요, 빠르게 다시 인사드립니다. 🙇‍♂️ 

말씀 주신대로 테스트 코드 먼저 짜고, 기능을 구현하는 식으로 진행해봤습니다.
다만 커밋을 잘게 나누다 보니 테스트 케이스가 깨지는 상황도 커밋에 포함 되어있는데요.
이를 구분하기 위해 커밋 앞에 [RGB 표시](https://medium.com/basic-people/test-driven-development-is-red-green-blue-development-f268e2150981)를 해두었습니다. 참고 부탁드려요

이번 질문!
1. 커밋은 어느정도 단위로 나누는게 좋을까요? 저는 최대한 잘게 나누는 편이 히스토리 참고, 흐름 파악, 이후 롤백에 용이하여 좋다고 생각하는데, 용대님의 생각이 궁금합니다.

3단계에서 마지막으로 피드백 주신부분도 반영해 봤습니다.
이번 리뷰도 잘 부탁드려요 : )

2021-07-21 11:51 UTC, yongdae commented
안녕하세요. 광현님 😄
빠르게 4단계를 진행해주셨네요!! 멋지세요. 👍

리뷰에 앞서 먼저 질문에대해 코멘트로 답변드립니다.

Q. 커밋은 어느정도 단위로 나누는게 좋을까요? 저는 최대한 잘게 나누는 편이 히스토리 참고, 흐름 파악, 이후 롤백에 용이하여 좋다고 생각하는데, 용대님의 생각이 궁금합니다.

A. 광현님과 동일하게 생각합니다. 커밋은 나눌 수 있는한 가장 작은 단위로 나누는게 좋다고 생각합니다.
그래야 이슈를 해결하거나 기능을 추가 할 때 이력을 알기 쉽고, 되돌리거나 수정하기가 쉽기 때문입니다.

더불어 PR이나 git의 rebase를이용하면 여러개의 커밋을 하나의 커밋으로 만들수도 있으니
커밋이 많아도 문제가 될 부분이 전혀 없다고 생각합니다. 😄

2021-07-21 12:26 UTC, yongdae requested changes
안녕하세요. 광현님 ~

4단계 미션을 잘 진행해주셨네요! 💯
설계를 잘 해주셔서 크게 의견 드릴 부분은 없는 것 같아요.
사소하지만 몇 가지 의견을 드렸습니다.

확인하시고 다시 리뷰 요청 부탁드려요. 🙇

2021-07-21 12:26 UTC, yongdae commented on src/test/java/racingcar/car/CarsTest.java
> +    void leaderCarOfCars(int totalRound, int numberOfCars, MoveStrategy moveStrategy, List<String> leaders) {
MoveStrategy를 사용하지 않고 Car, Cars만 사용해서 우승자를 테스트 할 수 있는 방법은 없을까요??

2021-07-21 12:26 UTC, yongdae commented on src/test/java/racingcar/car/CarTest.java
> +    void moveTestWithMoveStrategy(Random random, boolean moved) {
[경계값을 이용해서 테스트](https://toast1307.tistory.com/6)를 해보면 어떨까요?
추가로 0보다 작은 값이 사용되거나 9보다 큰 값이 사용되는 경우에 예외처리를 해보면 좋을 것 같아요. :)

2021-07-21 12:26 UTC, yongdae commented on src/test/java/racingcar/car/CarTest.java
>      }
요구사항 "각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다."을 만족시키는
테스트를 만들어주셨네요. 👍

2021-07-21 12:26 UTC, yongdae commented on src/main/java/racingcar/car/Car.java
> +    }
currentPosition()를 외부에서 사용해 위치를 비교하지 않고
메소드를 이용해 Car에게 위치 비교하는 책임을 가질 수 있도록 해주셨네요. 👍

2021-07-21 12:26 UTC, yongdae commented on src/main/java/racingcar/car/Cars.java
> +    }
일급 컬렉션의 장점을 잘 사용해주셨네요. 💯

2021-07-21 12:36 UTC, nokchax commented on src/test/java/racingcar/car/CarTest.java
> +    void moveTestWithMoveStrategy(Random random, boolean moved) {
아! 경계값 테스트 한다고 작성하긴 했는데, 5의 경우를 뺴먹었네요 :(
유효한 범위 경계를 벗어나는 경우는 말씀 주신대로 예외처리가 더 좋을거 같아요 감사합니다 🙏

2021-07-21 13:43 UTC, nokchax commented on src/test/java/racingcar/car/CarsTest.java
> +    void leaderCarOfCars(int totalRound, int numberOfCars, MoveStrategy moveStrategy, List<String> leaders) {
음... 고민을 해봤는데, MoveStrategy 없이는 Car를 움직일 수 없어서 현재 구조로는 불가능 할거 같구요.

MoveStrategy 없이 테스트를 하려면
1. Car 를 주어진 위치를 가지고 초기화 할 수 있게 만든다. e.g. Car(String name, int initPosition);
2. 1)을 가지고 여러 Car를 생성하고, 이 Car를 Cars에 넣어준다. 마찬가지로 List<Cars> 를 가지고 Cars 를 초기화 할 수 있도록 생성자 추가.
3. Cars에서 우승자를 가져온후, Car를 생성할 때 예상헀던 우승자 목록과 비교한다.

하지만 위처럼 테스트 하려면, 테스트를 위한 생성자 추가가 필요한데, 테스트를 위해서 프로덕션 코드를 수정하는 건 좋지 않다고 생각해서요 
음.... 혹시 제가 생각하지 못한 방법이 있을까요? 🤔

2021-07-22 01:05 UTC, yongdae commented on src/test/java/racingcar/car/CarsTest.java
> +    void leaderCarOfCars(int totalRound, int numberOfCars, MoveStrategy moveStrategy, List<String> leaders) {
광현님이 생각하신 내용 말고는 음.. 더 떠오르는 방법은 없는것 같습니다. :)

1번 생각을 바탕으로 의견을 드린 부분인데, 이미 테스트를 위해 프로덕선 코드를 수정하는건 좋지 않다고 생각하셨다면
의도하신대로 진행하시면 될 것 같습니다. :)

2021-07-22 01:11 UTC, yongdae approved these changes
안녕하세요. 광현님 ~ :)

피드백을 빠르게 반영해주셨네요. 💯 
크게 의견 드릴 부분이 없어 바로 다음 단계로 넘어가도록 하겠습니다.

수고하셨습니다. 🔥🔥

2021-07-22 01:11 UTC, merged