3단계 - 자동차 경주
next-step/java-racingcar pull request #2337
Opened 2021-07-21 06:15 UTC by testrace

2021-07-21 10:10 UTC, dbeod2 requested changes
안녕하세요! 3단계 자동차 경주 잘 구현해 주셨네요! 

전체적으로 코드도 깔끔하고 프러덕션 코드와 view도 잘 분리 해주셨습니다 👏🏻👏🏻👏🏻
테스트 코드도 상황에 맞게 잘 작성해 주셨더라구요! 

고민해보면 좋을 것 같은 부분이 있어서 의견 드렸습니다. 
코멘트 확인 부탁드립니다 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2021-07-21 10:10 UTC, dbeod2 commented on README.md
> -* [텍스트와 이미지로 살펴보는 온라인 코드 리뷰 과정](https://github.com/next-step/nextstep-docs/tree/master/codereview)
요구사항 정리 👏🏻👏🏻👏🏻

2021-07-21 10:10 UTC, dbeod2 commented on src/main/java/racing/domain/Car.java
> +		int randomValue = new Random().nextInt(RANDOM_BOUND);
메소드가 실행시 new Random() 인스턴스가 반복적으로 생성되는 것보단
한개를 만들어 놓고 사용하는게 자원적인 측면에서 좋을 것 같다고 생각되는데요!
어떻게 생각하시나요? 🤔

2021-07-21 10:10 UTC, dbeod2 commented on src/test/java/racing/domain/CarTest.java
> +
테스트코드 👍🏻

2021-07-21 10:10 UTC, dbeod2 commented on src/main/java/racing/domain/Car.java
> +	private static final int RANDOM_BOUND = 10;
클래스 구현 순서는 다음과 같이 중요한 순서로 위치하는게 좋을 것 같아요! 
참고 부탁드립니다 🙇🏻‍♀️

```
class  T {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2021-07-22 02:39 UTC, testrace commented on src/main/java/racing/domain/Car.java
> +		int randomValue = new Random().nextInt(RANDOM_BOUND);
피드백 감사합니다 ^^
단위 테스트 통과 시켜놓고 리팩토링을 하지 못했네요
RandomGenerator 라는 클래스로 분리했습니다! 
`private static final int RANDOM_BOUND = 10;` 
위 코드 처럼 매직 넘버를 상수화 하듯이 특정 값을 반환하는 로직에도 적용해야겠다는 생각이 듭니다.
혹시 이런 기법(?)을 칭하는 용어 같은게 있을까요?

2021-07-22 02:42 UTC, testrace commented on src/main/java/racing/domain/Car.java
> +	private static final int RANDOM_BOUND = 10;
기본 규칙을 지키지 못했네요. 
피드백 감사합니다 ^^

2021-07-22 13:17 UTC, dbeod2 commented on src/main/java/racing/domain/Car.java
> +		int randomValue = new Random().nextInt(RANDOM_BOUND);
매직넘버를 상수화 하는 용어 말씀하시는걸까요? 보통 매직넘버 치환이라고 하기는 합니다 
원하시는 답변일지 모르겠네요 ! 🧐

2021-07-22 13:21 UTC, dbeod2 approved these changes
안녕하세요! 
3단계 미션 잘 구현해주셔서 따로 의견드릴게 없을 것 같네요!  👍🏻👍🏻👍🏻
여기서 머지하겠습니다 

다음 미션을 진행해주세요! ☺️☺️☺️

2021-07-22 13:21 UTC, dbeod2 commented on src/main/java/racing/domain/RandomGenerator.java
> +
피드백 적용 잘해주셨네욤 😄

2021-07-22 13:22 UTC, merged