3단계 - 자동차 경주
next-step/java-racingcar pull request #2368
Opened 2021-07-22 06:54 UTC by darkant99

안녕하세요! 3단계 - 자동차 경주 코드 작성 했습니다.
부족한 부분이 많지만 잘 부탁 드립니다. 👏

2021-07-22 11:58 UTC, yongdae requested changes
안녕하세요. 재원님 :)

자동차 미션 첫 단계를 잘 진행해주셨네요! 🔥🔥
진행해주신 내용에 대해 몇 가지 의견을 드렸습니다.

확인하시고 다시 리뷰 요청 부탁드립니다. 🙇
질문이 있으시거나 의견이 있으시면 언제든 코멘트나 DM 주세요!

2021-07-22 11:58 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +    public void carIteratorTest(int size) {
cars.iterator().hasNext() 를 이용해서 테스트를 만들어보면 어떨까요? :)

2021-07-22 11:58 UTC, yongdae commented on src/test/java/racing/car/CarTest.java
> +    public void randomMoveTest(int limitMoveCount) {
자동차 미션에서 요구하는 사항은 난수를 생성해 난수가 4보다 큰 값인 경우 자동차가 전진합니다.
사실 난수를 가지고 테스트를 작성하는 것은 어렵습니다. 

이러한 경우에는 어떻게 하면 좋을지 고민해보면 좋을 것 같아요. 😄
조금 힌트를 드리자면 자동차 외부에서 값을 전달해 자동차가 움직일 수 있게한다면 어떨까요?

2021-07-22 11:58 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +class CarsTest {
요구사항 "주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다." 에 대한 테스트를 추가 해보면 어떨까요?
꼭 Cars가 아니여도 상관이 없습니다. 🤔

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/readme.md
> +[ x ] InputView와 ResultView를 구현한다.
요구 사항을 잘 정리해주셨네요. 👍

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/car/Location.java
> +public class Location {
위치 값을 객체를 이용해 분리해주셨네요. 💯

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/car/Location.java
> +    private static final char VALUE_UNIT = '-';
이 부분은 출력과 관련 된 내용 같은데 분리해보면 좋을 것 같아요. :)

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/car/Car.java
> +        );
0, 4, 9는 매직 넘버로 보이는데 상수로 치환해보면 어떨까요?

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/car/Car.java
> +    private int moveCount;
location과 Location을 별개로 분리해야하는 이유가 있을까요? 🤔

2021-07-22 11:58 UTC, yongdae commented on src/main/java/racing/RacingSolution.java
> +    public static void main(String[] args) {
<img width="248" alt="스크린샷 2021-07-22 오후 8 54 17" src="https://user-images.githubusercontent.com/4317804/126635100-9f2acc16-f353-4240-9516-bf598e9b5b19.png">

자동차 경주 결과가 요구사항과 다른 것 같아요. 😭 
경주 1회차 마다 자동차는 1칸을 전진 or 멈춤 인데 실행 결과는 그렇지 않아요

2021-07-22 12:12 UTC, darkant99 commented on src/main/java/racing/car/Car.java
> +    private int moveCount;
location과 Location을 별개로 분리 했다는 의미가 이해되지 않습니다!
위치값을 Location 객체로 분리한걸 말씀 하신걸까요?

2021-07-22 12:15 UTC, yongdae commented on src/main/java/racing/car/Car.java
> +    private int moveCount;
제가 오타를 쳤네요. 죄송합니다 😭
lastMoveDistance와 location을 이야기한 부분입니다!

2021-07-22 12:17 UTC, darkant99 commented on src/main/java/racing/car/Car.java
> +    private int moveCount;
테스트 코드에서 이동한 거리의 계산을 조금 더 깔끔하게 구현하고자 해서 분리 했습니다.
수정 하겠습니다!

2021-07-22 14:57 UTC, yongdae requested changes
재원님 ~ 빠르게 피드백을 반영해주셨네요. 👍

자동차 경주 결과에 대한 [피드백](https://github.com/next-step/java-racingcar/pull/2368/files#r674729097)은 아직 수정이 안된 것 같아요.
확인 부탁드려요~ 😄 

아 그리고 리뷰 진행중에 코드를 다시 push 해주셨는데
리뷰 요청 후 코드 수정을 하게 되시면 미리 이야기 해주시면 좋을 것 같아요!
코드 리뷰 중 수정이 발생하면 리뷰를 다시 해야하는 경우가 발생해요. 😭 

진행해주신 내용에 대해서는 다시 의견을 드렸습니다.
내용 확인하시고 다시 리뷰 요청부탁드려요~ 🔥🔥

2021-07-22 14:57 UTC, yongdae commented on src/main/java/racing/RacingSolution.java
> +public class RacingSolution {
<img width="331" alt="스크린샷 2021-07-22 오후 11 29 46" src="https://user-images.githubusercontent.com/4317804/126656652-c6ce4a3d-5e25-4534-80f8-7a37a322ccff.png">

자동차 경주가 끝나면 완전히 종료되게 하면 어떨까요?
경주가 끝나고 횟수를 입력하지 않으면 프로그램을 종료 할 수가 없네요. 😢

2021-07-22 14:57 UTC, yongdae commented on src/test/java/racing/car/CarTest.java
> +    public void moveTest(int distance) {
<img width="1440" alt="스크린샷 2021-07-22 오후 11 35 56" src="https://user-images.githubusercontent.com/4317804/126657432-cef4dd48-d2f8-4ef0-9156-41c0191c4a6d.png">
테스트가 실패해요. 😢

2021-07-22 14:57 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +                        iCar.getMoveCount() > 0
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

getMoveCount()는 일종의 getter로 보이는데
getter을 사용하지 않고 할 수 있는 방법은 없을까요?

2021-07-22 14:57 UTC, yongdae commented on src/main/java/racing/car/Car.java
> +    public enum MovementDistance {
Car 클래스에서 분리해서 사용하면 어떨까요? 🤔

2021-07-22 14:57 UTC, yongdae commented on src/main/java/racing/car/Car.java
> +        MOVEMENT_MAX_VALUE(9);
이 두가지 값은 사용하는 곳이 없는 것 같아요!

2021-07-22 14:57 UTC, yongdae commented on src/main/java/racing/car/Cars.java
> +    private static final Random random = new Random();
random 값도 사용하는 곳이 없는 것 같아요. 😭

2021-07-22 14:57 UTC, yongdae commented on src/main/java/racing/RacingSolution.java
> +    public static void main(String[] args) {
<img width="331" alt="스크린샷 2021-07-22 오후 11 29 46" src="https://user-images.githubusercontent.com/4317804/126658824-dc3460d8-7a70-45c3-a340-cef82a3d95d7.png">

경기가 1회 진행 될 때 1칸만 움직 일 수 있어요.

2021-07-22 14:57 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +                assertThat(
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

이 규칙을 적용해보면 어떨까요? 🤔

2021-07-22 14:57 UTC, yongdae commented on src/main/java/util/RandomUtils.java
> +    public static int nextInt(int minValue, int maxValue) {
이 메소드는 사용하는 곳이 없는 것 같아요~

2021-07-22 17:07 UTC, darkant99 commented
엇 푸쉬 한 다음에 리뷰를 확인 했네요!
리뷰 남겨 주신것 확인하고 다시 요청 드리겠습니다!
늦은 시간에 감사합니다 👏

2021-07-22 18:36 UTC, darkant99 commented
리뷰 진행중에 푸쉬를 남겨서 다시 살펴 보셨을 생각하니 죄송 스럽네요 👏
다음부턴 리뷰 요청 후 푸쉬 사항이 있으면 꼭 전달 드리겠습니다!
미션의 요구 사항이 이제야 이해 됬어요
요구 사항을 꼼꼼히 체크하고 코드를 작성하는 노력을 더 해야겠습니다😭

2021-07-23 00:23 UTC, yongdae requested changes
재원님! 새벽까지 열심히 달리셨군요. 🔥🔥

의견드린 부분을 멋지게 반영해주셨네요. 👍
진행해주신 내용에 대해 다시 의견 남겨놓았습니다!

추가로 아직 자동차 경주 진행과 관련되서 드린 [의견](https://github.com/next-step/java-racingcar/pull/2368/files#r674725352)이 반영되지 않은 부분이 있네요. 😢

리뷰 내용 확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇
즐거운 금요일이네요~ 좋은 하루 되세요!! 😄

2021-07-23 00:23 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +        }
```suggestion
        while (iterator.hasNext()) {
            iterator.next();
        }
```

이렇게 코드를 작성 해 볼 수도 있을 것 같아요. :)

2021-07-23 00:23 UTC, yongdae commented on src/test/java/racing/car/CarTest.java
> +                        .getValue()
getValue()를 사용하지 않고 자동차의 전진 유무를 판별하는 방법은 없을까요?? 🤔

2021-07-23 00:23 UTC, yongdae commented on src/main/java/racing/car/Fuel.java
> +            RandomUtils.nextBoolean(9, 4)),
9와 4를 상수로 만들어보면 더 좋을 것 같아요. :)

2021-07-23 00:23 UTC, yongdae commented on src/main/java/util/RandomUtils.java
> +    }
이 부분은 미션 요구사항에서 이야기하는 전진하는 조건 확인을
RandomUtils 객체가 가지고 있는 것 같아요. 😢

Utility 성격을 가지기 위해서는 범용적인 기능만 가지고 있는게 좋지 않을까요?

2021-07-23 00:23 UTC, yongdae commented on src/test/java/racing/car/FuelTest.java
> +class FuelTest {
자동차가 움직이기 위한 전략을 잘 분리해서 테스트까지 해주셨네요. 👍

2021-07-23 04:41 UTC, darkant99 commented on src/test/java/racing/car/CarsTest.java
> +
while로 작성하게 되면 지정한 size만큼 정확히 반복하는지, hasNext가 무조건 false를 반환하게 될 경우 등의 정확한 테스트가 어렵지 않을까요? 👀

2021-07-23 11:18 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +
음 hasNext()가 무족건 false를 반환하는 경우가 어떤 경우인지는 잘 모르겠어요 😢 
그리고 hasNext() 사용해보시는 의견을 드린 이유는 Iterable를 구현하셔서 이야기 드린 부분이니
넘기셔도 될 것 같아요~ :)

2021-07-23 11:26 UTC, yongdae approved these changes
안녕하세요 ~ 재원님. :)
빠르게 피드백을 반영해주셨군요. 💯 

진행해주신 내용 중 테스트를 보완하면 좋을 것 같은
부분이 있어 의견 남겨놓았습니다. 🔥

이 부분은 다음 단계에서 같이 반영해주시면 좋을 것 같습니다. 😄 

그럼 자동차 미션 4단계로 넘어가시죠.
수고하셨습니다. 🙇

2021-07-23 11:26 UTC, yongdae commented on src/test/java/racing/car/CarsTest.java
> +                    iCar.getLocation().hasValue()
hasValue()는 테스트만을 위해 사용되고 있네요. 😢 

iCar.getLocation().hasValue() 대신 iCar.checkLocation(위치값)
이런 형태가 될 수 있도록 해보아도 좋을 것 같아요. 😄

2021-07-23 11:26 UTC, yongdae commented on src/test/java/racing/car/CarTest.java
> +    public void moveTest(String fuelName, boolean movement) {
"전진하는 조건은 0에서 9" 라는 범위에 대한 테스트는 없는 것 같아요.
0 ~ 9 사이의 값만 움직임을 허용한다는 테스트를 추가 해볼 수는 없을까요? 🤔

2021-07-23 11:27 UTC, merged