3단계 - 자동차 경주
next-step/java-racingcar pull request #2371
Opened 2021-07-22 09:40 UTC by 0n1dev

리뷰어님 안녕하세요 😄 

1단계, 2단계 리뷰를 생각하며 3단계 과제를 제출합니다!

먼저 commit에 docs를 먼저 작성해야했는데 버릇 때문에 가장 마지막에 작성을 했네요 😭 
해당 부분은 다음 단계 때 주의하겠습니다.

Racing 클래스 부분 테스트 케이스를 어떻게 작성할지 고민하다가 방법을 찾을수 없어서 글을 남깁니다!

- 랜덤 값을 어떤식으로 테스트 코드를 작성해야 할 지?
- 접근 제한자가 `private`인 경우 테스트 코드 작성이 불가능해 보이는데 어떻게 해야될지?
- 실제 비즈니스 로직과 View의 사이에 있는 Controller를 추가하였는데 해당 부분도 테스트 케이스가 필요한지?

2021-07-22 14:16 UTC, ep1stas1s requested changes
메서드를 분리해서 잘 진행해주셨네요 👍 
코멘트 참고하셔서 리팩토링 진행해주세요~!

2021-07-22 14:16 UTC, ep1stas1s commented on src/main/java/racing/view/InputView.java
> +	public static void startRacing(int carCount, int tryCount) {
view에서 컨트롤러를 제어하는 느낌이라 생소하네요
아래와 같은 방식처럼 mvc를 고려해보시면 어떨까요?
![image](https://user-images.githubusercontent.com/45464819/126652146-d57e183a-cbe5-4495-9ae8-9177d87a3953.png)

2021-07-22 14:16 UTC, ep1stas1s commented on src/main/java/racing/domain/Car.java
> +	public String toString() {
`toString()`메서드가 view에 의존적으로 사용되는것 같아요~
`toString()`은 보통 객체의 상태를 표현하기 위해 사용하기 때문에, 정해진 규칙에 의해서 재정의하는게 좋습니다.
(일반적으로 generate - toString()을 사용하여 생성합니다) mac : cmd + n / win : alt + insert

2021-07-22 14:16 UTC, ep1stas1s commented on src/main/java/racing/view/InputView.java
> +public class InputView {
> 실제 비즈니스 로직과 View의 사이에 있는 Controller를 추가하였는데 해당 부분도 테스트 케이스가 필요한지?

테스트는 많으면 많을수록 좋지만 가성비도 고려해야겠죠?ㅎㅎㅎ
상황에 따라 통합 테스트를 진행하는 서비스도 있지만, 현재 과정에서는 view 또는 controller 테스트는 생략하셔도 된다고 생각합니당 :)

2021-07-22 14:20 UTC, ep1stas1s commented
> 접근 제한자가 private인 경우 테스트 코드 작성이 불가능해 보이는데 어떻게 해야될지?

public 메서드를 테스트하기 좋은 단위로 구성한다면, private 메서드는 테스트하지 않아도 될 것 같아요ㅎㅎ
[좋은 글](https://www.slipp.net/questions/253)이 있으니 참고해보시길 바랍니다~!

2021-07-22 17:54 UTC, 0n1dev commented on src/main/java/racing/controller/RacingController.java
> +		racing.init();
생성자 내부에서 필드 초기화만 생각하여 반복문 사용이 어색하여 따로 빼내었습니다.
생각해보면 내부에서 반복문을 안써도 메서드로 빼내어 생성자로 호출하면 될것 같군요 ! 😃 

생성자 생성시 크게 신경써야 될 게 무엇이 있을지 궁금합니다!

2021-07-23 12:40 UTC, 0n1dev commented on src/main/java/racing/view/InputView.java
> +	public static void startRacing(int carCount, int tryCount) {
제가 제대로 이해하고 리팩토링했는지 잘 모르겠네요!
평소에 사용자의 Action을 처리하는게 Controller의 역할이라 InputView에서 빼서 main 메서드로 넣었습니다.

2021-07-23 12:46 UTC, 0n1dev commented
매번 좋은 리뷰 감사합니다 😄 
남겨주신 글 읽어보았고 `Car` 클래스에서 조건 비교 후 움직이게 리팩토링 하였고, 해당 로직 테스트 코드를 작성하였기 때문에 `Racing` 클래스에서는 따로 테스트 코드가 필요 없다고 판단하였습니다!

고민이 해소되지 않은 부분이 아직있어서 리뷰 남기신 코멘트에 추가로 남겨두었습니다.

감사합니다 👍

2021-07-23 18:10 UTC, ep1stas1s commented on src/main/java/racing/controller/RacingController.java
> +		racing.init();
저같은 경우엔 필드 초기화를 가장 우선시하는데요~
이전 코드의 경우 init()메서드를 사용하지 않으면 cars가 초기화가 되지 않는 구조였어요
그럴 경우 다른 곳에서 cars를 사용하게되면 NPE가 발생하고, 이러한 부분을 다른 개발자가 알고 사용해야하죠

결론적으론 생성자에서 필드를 초기화하고, 초기화 전에 유효성 검증까지 고려하면 좋을 것 같습니다^_^

2021-07-23 18:47 UTC, ep1stas1s approved these changes
피드백 잘 반영해주셨네요 👍 
코멘트 참고하셔서 다음 스텝 진행해주세요~!

2021-07-23 18:47 UTC, ep1stas1s commented on src/main/java/racing/domain/Racing.java
> +	private static final int COMPARE_VALUE = 4;
개인적으론 Racing이 COMPARE_VALUE를 들고있는 것이 어색해보이네요ㅎㅎ
각각의 Car에서 요 친구를 들고있으면, 상황에 따라 VALUE를 변경하는 기능도 쉽게 구현이 가능할 것 같네요^_^

2021-07-23 18:47 UTC, ep1stas1s commented on src/main/java/racing/domain/Racing.java
> +		}
혹시나 여유가 되신다면 java8의 stream을 학습해보셔도 좋을 것 같습니다 😄

2021-07-23 18:47 UTC, ep1stas1s commented on src/test/java/racing/domain/CarTest.java
> +class CarTest {
깨지는 테스트가 있네요 ㅠ_ㅠ
코드 변경과 함께 테스트도 같이 수정하시면서 TDD를 연습해보셔도 좋을 것 같습니다ㅎㅎㅎ

2021-07-23 18:47 UTC, ep1stas1s commented on src/main/java/racing/RacingMain.java
> +		int carCount =  InputView.inputCarCount();
```suggestion
		int carCount = InputView.inputCarCount();
```

2021-07-23 18:47 UTC, ep1stas1s commented on src/main/java/racing/view/InputView.java
> +import racing.controller.RacingController;
불필요한 코드는 삭제 부탁드립니다ㅎㅎ

2021-07-23 18:47 UTC, merged