(박일한) - Step4 자동자 쳥주 우승
next-step/java-racingcar pull request #2374
Opened 2021-07-22 10:42 UTC by pih6585

이번에 작성하면서 tdd로 작성하려고 했는데 만만치가 않네요...

그리고 우승자를 출력하는데 있어서 너무 아이디어가 떠오르는게 없어서 map으로 진행을 해봤습니다.

class 나누다 보니까 뭔가 더 복잡성이 높이는것 같기도 한것 같아요.

리뷰 부탁드리겠습니다~~~~^^

2021-07-22 13:48 UTC, ksundong requested changes
안녕하세요. 일한님! 😊

4단계 미션도 빠르게 진행해주셨네요!! 👏 👏 👏
이번 단계에서 한 번 우리의 설계를 조금 가다듬고 다음 단계를 진행하면 좋을 것 같습니다.

먼저 도메인과, 일반적인 클래스들에 대해서 리뷰를 남겼는데요.
다른 내용에 대한 피드백은 이 내용이 다듬어지고 난 다음에 리뷰를 하려고 합니다.

### 피드백

- 코딩 컨벤션이 지켜지지 않은 모습이 많이 보이고 있습니다. 항상 신경써주세요!
  - [참고하시면 좋을 사이트를 링크해둡니다. 확인해주세요!](https://naver.github.io/hackday-conventions-java/)
- TODO 항목은 한 번만 작성하고 끝이 아닙니다. 개발을 하면서 지속적으로 관리되어야 하는 항목입니다.
  - 이는 TDD를 연습하기 위함도 있습니다. 😊 개발을 하면서 떠오르는 생각을 TODO로 정리해보세요!
- 단위테스트가 가장 충실히 이뤄져야하는 부분은 도메인 영역입니다. 이 부분에 좀 더 충실하게 단위테스트를 작성해주시면 좋을 것 같습니다!

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-22 13:48 UTC, ksundong commented on README.md
> +- [입력받은 경주시도 수만큼 경주된 거리가 출력된다.]
TODO는 다음과 같이 작성해주시면 됩니다!

```md
- [ ] 자동차 모델을 만든다.
- [x] 완료된 항목은 이렇게 체크해주세요.
```

2021-07-22 13:48 UTC, ksundong commented on src/test/java/racing/CarTest.java
> +    }
ParameterizedTest를 꼭 적용시켜봐주세요!

2021-07-22 13:48 UTC, ksundong commented on src/main/java/racing/Car.java
> +        return randomValue > 3 ? ++raceDistance : raceDistance;
삼항연산자도 if - else로 볼 수 있기 때문에 현재 단계에선 추천드리지 않을게요.
그리고, 연산자 우선순위가 복잡해서, 다른 사람이 이 코드를 봤을 때, 한 번에 이해하기 쉽지 않아보입니다!

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Utils.java
> +public class Utils {
어떤 `Util`인가요? 포괄적인 이름은 이 객체가 하는 역할을 제대로 표현하지 못한다는 의미가 될 수 있습니다.
비슷한 것끼리 뭉쳐서 클래스로 묶어보면 어떨까요?

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Utils.java
> +    }
stringToInt 메서드를 제외하고는 별도의 메서드로 추출할 필요가 없다고 생각합니다.
오히려, 과도한 추상화로 이를 작성하는 다른 개발자들이 혼란을 겪을 우려까지 있어보입니다.

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Utils.java
> +    }
stringToInt에는 유효한 정수값인지 검증하는 기능이 들어가면 더 좋을 것 같네요.

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Validation.java
> +    }
의존성 주입을 잘 설계해주셨습니다.

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Validation.java
> +    }
각 Validation은 객체가 직접 수행할 수 있는 부분이 있고, 공통적인 영역의 경우 따로 구현하거나 공통적인 Validator를 구현해야할 수 있습니다.

간단하게 validStringLength를 car로 이동시켜보면 어떨까요? Car가 생성되는 시점에 validation을 수행한다면 올바른 Car만 생성되도록 할 수 있을것이고, 그 밖에도 도메인의 핵심 로직이 도메인 객체에 드러나게되어 코드 파악이 더 수월해질 수 있을 것 같습니다!

2021-07-22 13:48 UTC, ksundong commented on src/main/java/game/Player.java
> +    }
과연 `Player`가 `raceDistance`를 가져야할까요?
또한 `playToMove`는 `Car`와 중복된 로직이 발생하고 있습니다.

제가 제안드리는 방법은
1. `Player`에서 `Car`를 인스턴스 변수로 관리한다.
2. `Car`에서 `name`을 인스턴스 변수로 관리하고, `Player`는 제거한다.

이 두가지 입니다. 😊
둘 중에서 하나를 선택하셔서 개발해보시면 어떨까요?

2021-07-22 13:48 UTC, ksundong commented on src/main/java/racing/Car.java
> +    private int carNumber;
`carNumber`가 필요한 이유가 있을까요?
제 생각엔 없애도 무방할 것 같습니다! 불필요하게 등장한 인스턴스 변수는 설계의 복잡도를 오히려 올릴 위험이 있다고 생각이됩니다. 😊

2021-07-22 13:48 UTC, ksundong commented on src/test/java/racing/CarTest.java
> +class CarTest {
`Car`를 생성하는 테스트도 만들어보시면 좋을 것 같아요.

1. 유효하게 생성하는 경우
2. 유효하지 않게 생성하는 경우

이 두 가지를 테스트해보시면 좋을 것 같습니다!

2021-07-22 13:48 UTC, ksundong commented on src/test/java/racing/CarTest.java
> +    }
그리고 테스트 메서드 이름이 setter, getter가 들어가는데 이것도 확인해주시면 감사하겠습니다!

2021-07-22 23:46 UTC, pih6585 commented on src/main/java/game/Player.java
> +    }
이거는 제가 step3랑 step4랑 별로로 분리해서 개발해보려고하다보니까 변수명에서도 오해의 소지가많은것 같아요
그래서 game이랑 racing이랑 패키지를 별도로 분리해서 개발을 했습니다.

2021-07-23 00:00 UTC, pih6585 commented on src/main/java/game/Validation.java
> +    }
메소드 실행하는 주체에서 실해되는 로직부분에 car에 들어가지않아도 체크를 하니까 식별하기 좋다고 생각을 했는데
어떻게 생각하시나요?

2021-07-23 16:32 UTC, ksundong commented on src/main/java/game/Validation.java
> +    }
네 그게 기존 절차지향적인 방식의 문제라고도 볼 수 있습니다.
객체가 스스로 판단할 수 없고, 외부에서 모든 일을 다 해줍니다. 빈약한 도메인이 생성되는 것이죠.
이 빈약한 도메인의 문제는, 외부 컨텍스트 없이 이를 테스트 할 수 없다는 점에 있습니다.

자동차의 이름을 외부에서 판단해줘야 한다면, 자동차의 이름을 판단하기 위해서는 해당 비즈니스 로직 전부를 들고와야하는 문제가 생깁니다. 당연히 이는 테스트가 어려운 구조입니다.
테스트 하기 어려운 코드는 좋은 코드와는 거리가 멀 가능성이 높습니다.

2021-07-23 16:33 UTC, ksundong commented on src/main/java/game/Player.java
> +    }
네, 앞으로의 미션에서도 한 기능을 계속해서 리팩토링 하는 것이 이 과정의 목표입니다.
기존 설계를 TDD를 이용해서 지속적인 발전이 가능하고, 요구사항의 변화에 어떻게 대처할 것인가를 본다고 생각해주시면 좋을 것 같아요.

2021-07-24 00:59 UTC, ksundong requested changes
안녕하세요. 일한님! 😊

4단계 미션 피드백도 빠르게 진행해주셨네요!! 👏 👏 👏

질문주셨던 `Map`을 사용해서 우승자를 구한 부분에 대한 피드백을 남겼습니다.

또, 클래스를 사용해서 복잡해지는 이유는 적절한 책임 분리가 이뤄지지 않았기 때문이라는 생각이 듭니다.
결국 객체지향은 복잡한 문제를 적절한 추상화를 통해서 복잡성을 덜어내기 위한 설계방법이기 때문에 이를 잘 익히신다면 아마 도움이 많이 되지않을까 싶네요.

### 피드백

- 코딩 컨벤션이 지켜지지 않은 모습이 많이 보이고 있습니다. 항상 신경써주세요!

마지막 변경요청을 드릴 것 같은데요~ 확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Car.java
> +	}
`carRacing` 이라는 메서드명은 `car`라는 객체가 하는 행동을 효과적으로 드러내는 이름이 아닌 것 같습니다.
좀 더 좋은 네이밍에 대해서 고민해볼 수 있으면 좋겠네요!

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Car.java
> +	}
또한 해당 메서드가 상태를 변화시키면서 값을 반환하는 형태인데, 상태를 변화시키는 것과 값을 가져오는 것을 분리하는 형태를 추천드립니다.

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/CarRacingMain.java
> +	private static final String SECOND_REQUEST = "시도할 회수는 몇회인가요?";
요것도 MessageBox로 옮기는 것이 어떨까요?

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/CarRacingMain.java
> +	}
Main쪽 로직이 깔끔해졌네요. 잘하셨습니다. 😊

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/MessageBox.java
> +	}
해당 메서드는 필요없을 것 같습니다!
별도의 Wrapping 메서드는 만들지 않는 편이 혼란을 최소화시킬 수 있을 것 같아요~

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/MessageBox.java
> +	}
`StringBuffer`를 반환해주신 이유가 있을까요? 그냥 바로 `String`으로 return해주는게 나을 것 같아보입니다.

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/MessageBox.java
> +	}
네이밍 컨벤션을 지켜주세요.

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Racing.java
> +		int CHECK_LENGTH = 4;
네이밍 컨벤션 지켜주시고, 해당 변수는 상수로 추출해주시면 좋겠네요.

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Racing.java
> +		messageBox.commonMessageBox(winnerPlayer.substring(0,winnerPlayer.length()-1), WINNER_MESSAGE);
해당 부분은 출력과 연관되어 있어보입니다.

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	}
별도의 validation이 없다면 굳이 메서드로 추출해줄 필요는 없어보이네요~

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	private final StringBuffer winnerPlayList;
StringBuffer를 상태로 관리해주시는 이유가 있을까요?

2021-07-24 00:59 UTC, ksundong commented on src/test/java/racing/CarRacingMainTest.java
>  public class CarRacingMainTest {
CarRacingMain을 테스트하는 코드가 맞는지 확인해주세요~

2021-07-24 00:59 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	}
`Map`을 사용하신 것에 대한 피드백을 받고 싶어하시는 것 같아서 제 개인적인 의견을 적어봅니다.
먼저 `Map`에 데이터를 계속해서 적재하는 모습이 보입니다. 하지만 이 데이터는 `Car`에도 이미 적재되어 있는 상태 값이기 때문에 `Map`을 사용할 이유가 딱히 보이지 않습니다.
`List`를 잘 이용한다면, `Map`을 사용하지 않고도 우승자를 구할 수 있을 것 같습니다.

2021-07-24 01:01 UTC, pih6585 commented on src/main/java/racing/Racing.java
> +	}
최종코드에는 list로 변경해서 진행을 해봤는데 코드리뷰 부탁드립니다.

2021-07-24 01:03 UTC, ksundong commented on src/main/java/game/Validation.java
> +    }
사용자의 입력값 검증은 두 가지 모두에서 이뤄져야 한다고 생각합니다.
입력을 받는 부분과, 도메인 모델 모두에서요~
이렇게 했을 때의 장점은 개발자는 도메인 모델의 유효성에 대해서 안심하고 프로그래밍 할 수 있고, 사용자는 오류에 대한 즉각적인 피드백을 받을 수 있습니다.

2021-07-24 01:07 UTC, pih6585 commented on src/main/java/racing/Car.java
> +	}
경주를 하면서 해당 내용도 받아와야 되기 때문에 바로 return을 해야한다고 생각을 했는데 궃이 분리를 해야되는 이유가 있나요?

2021-07-24 01:19 UTC, pih6585 commented on src/main/java/racing/MessageBox.java
> +	}
문자열에 단순하게 +=으로 값 추가에 대해서 warning이 발생하여 stringBuffer로 append하게 하였는데 String으로 바로 +=는 이용 하고 할수있는 방법을 생각 해볼게요~

2021-07-24 01:37 UTC, pih6585 commented on src/main/java/racing/Racing.java
> +	}
이부분도 car Name 생성시점의 validation 처리하는 부분처럼 해당 주체에서 일을할때 validation을 할 수 있도록 변경하는게 
좀 더 나은 방법인가요?

2021-07-24 02:14 UTC, ksundong commented on src/main/java/racing/Car.java
> +	}
해당 내용을 바로 받아올지, 나중에 받아올지 선택지를 줄 수 있는것이죠.
또, 이를 명령 - 쿼리 분리원칙이라고 하는데, 부수효과를 일으키는 부분을 제어하여 예측 가능한 프로그래밍을 가능하게합니다.

2021-07-24 02:14 UTC, ksundong commented on src/main/java/racing/MessageBox.java
> +	}
아뇨~ 반환 타입이 `String`이면 좋겠다는 의견입니다.

2021-07-24 02:15 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	}
이는 조금 다릅니다. Utiltiy성 메서드라서 어느곳에 위치해야한다는 관점은 아니거든요.
따라서 가져다 쓰는 Utility성 메서드의 형태로 구현해주는게 좋다고 생각됩니다.

2021-07-24 02:16 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	}
리뷰하는 사이에 코드가 추가되었군요.
리뷰 받은 내용과 함께 수정하시어, 다시 리뷰요청 주시면 감사하겠습니다 ^^

2021-07-25 13:11 UTC, ksundong approved these changes
안녕하세요. 일한님! 😊

4단계 미션 피드백 반영하시느라 정말 고생 많으셨어요!! 👏 👏 👏

이제 마지막 단계만 남았네요. 마지막 단계는 비교적 간단하게 완료하실 수 있을 것 같습니다.
다만 메서드를 가독성이 좋게끔 위치를 변경하는 시도를 해보시면 좋을 것 같아요.

고생하셨습니다! 😊
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-25 13:11 UTC, ksundong commented on src/main/java/racing/Racing.java
> +	private int MAX_VALUE = 0;
`MAX_VALUE` 가 맞나요? 어떤 용도의 `MAX_VALUE` 인지 명확하지 않네요.

2021-07-25 13:11 UTC, ksundong commented on src/test/java/racing/CarTest.java
> +    }
테스트를 잘 만들어주셨네요.

2021-07-25 13:11 UTC, merged