Step03 - 자동차 경주
next-step/java-racingcar pull request #2375
Opened 2021-07-22 10:58 UTC by gunny6026

step02 과제 보다 훨씬 더 많은 시간이 걸렸네요 😂 요구사항에 맞게 설계하고 구현하도록 열심히 해보았는데, 잘 됐는지 모르겠네요.  commit도 정해진 규칙에 따라서 남겨야 해서 쉽지 않은 과제였습니다. 
부족한 점 리뷰 해주지면 최선을 다해 수정 하겠습니다.  🙂🙄

2021-07-23 14:59 UTC, JunHoPark93 requested changes
안녕하세요 건희님!
3단계도 잘 진행해주셨네요 👍
커밋메세지도 지난번에 비해서 훨씬 깔끔해졌어요!

몇가지 코멘트 남겼으니 확인부탁드릴게요 :)
궁금한점 편하게 남겨주세요~

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step02/Application.java
> +package racing_car.step02;
패키지명도 어떤 규칙들이 있는지 찾아보면 좋을 것 같아요 :)

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step03/Race.java
> +            }
이번 미션 요구사항인 들여쓰기는 한단계로 작성하는 것이 있었는데요, 메서드를 분리해보는건 어떨까요? 🤔

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step03/Race.java
> +    private final int MIN_NUMBER = 4;
지난번 피드백인 의미있는 이름을 가진 상수로 추출해보는것이 있었는데요, 이번에 잘 시도하신거같아요 👍
```suggestion
    private static final int MIN_NUMBER = 4;
```

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step03/Race.java
> +        return false;
```suggestion
        return random >= MIN_NUMBER;
```
이렇게 할 수도 있겠네요 :)

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step03/Race.java
> +        return r.nextInt(BORDER);
r 이라는 변수명보다는 의미있는 변수명을 고민해보는건 어떨까요?

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/racing_car/step03/Validation.java
> +        if (carCount<=0){
```suggestion
        if (carCount<=0) {
```
전체적으로 컨벤션 관련해서 검토부탁드려요 :)
option + cmd + L 을 이용하여 자동으로 정리할 수도 있으니 참고하시면 좋을거같아요!

2021-07-23 14:59 UTC, JunHoPark93 commented on src/main/java/todo.md
> +# todo
요구사항 정리 잘해주셨네요 👍

2021-07-23 14:59 UTC, JunHoPark93 commented on src/test/java/racing_car/step03/RacingCarTest.java
> +            System.out.print(random + " ");
테스트는 검증이 들어가야하는데 이 테스트는 검증을 할 수 있을까요?
지금 당장에 해결하는것보다, 어떤것을 테스트할 수 있고 어떤것은 테스트하기 힘든지 고민해보시면 좋을 것 같아요:)

2021-07-24 13:08 UTC, gunny6026 commented on src/test/java/racing_car/step03/RacingCarTest.java
> +            System.out.print(random + " ");
피드백 감사합니다.  ㅎㅎ
피드백을 참고하여 테스트 케이스를 수정하고 있는 중에 궁금한 것이 생겼는데요
요구사항에 맞게 코드를 잘 구현했지만 테스트 하기 힘든 코드는 좋지 않은 코드 인가요? 
(제가 테스트 케이스를 만드는 것에 익숙치 않아서 일 수도 있습니다)

2021-07-25 01:59 UTC, JunHoPark93 commented on src/test/java/racing_car/step03/RacingCarTest.java
> +            System.out.print(random + " ");
좋지않은것은 아니에요! 다만 어떻게할것인가를 고민해야겠죠. 
테스트가 수월한것과 테스트가 어려운것을 최대한 분리해보셔요! 
일단은 랜덤한 수를 생성하는 기능을 독립적으로 분리하고 그외에것들을 먼저 테스트해보는건 어떨까요?
일단은 독립적으로 가두어놓고나서 어떻게할지를 고민해보아요 :)

2021-07-25 07:08 UTC, JunHoPark93 approved these changes
안녕하세요 건희님!
3단계 리뷰 반영하시느라 고생많으셨습니다.
몇 가지 코멘트 추가로 남겨두었는데요, 다음단계 진행하시면서 반영부탁드려요 🙏
궁금한점 언제든 남겨주세요~

2021-07-25 07:08 UTC, JunHoPark93 commented on src/test/java/racingcar/step3/RacingCarTest.java
> +class RacingCarTest {
현재는 RacingCarTest하나로 모든 테스트들을 작성하고 계신데요,
Car라는 도메인을 이번에 새로 만드셨으니, 다음단계에서 CarTest라는 도메인객체를 위한 테스트를 따로 만들어보는건 어떨까요?
현재는 View를 그리는 테스트도 한군데에 있다보니 도메인에 대한 테스트를 한눈에 보기 힘든것 같아요 :)

2021-07-25 07:08 UTC, JunHoPark93 commented on src/test/java/racingcar/step3/RacingCarTest.java
> +        for (int i=0; i< 10; i++){
다음 단계에서는 컨벤션을 다 맞췄는지 다시한번 확인해보면 좋을 것 같아요 :)
그리고 test 패키지를 전체적으로 수행하여 깨지는 테스트가 있는지도 검토부탁드려요.

2021-07-25 07:09 UTC, merged