Step2 - 문자열 계산기
next-step/java-racingcar pull request #2399
Opened 2021-07-23 08:44 UTC by harrisleesh

2021-07-23 17:39 UTC, ep1stas1s requested changes
간단하게 잘 구현해주셨네요 :+1:
이번엔 스텝에선 else를 제거하는 걸 중점으로 리팩토링해보시는 걸 권장드립니다ㅎㅎ

2021-07-23 17:39 UTC, ep1stas1s commented on src/main/java/stringcalculator/StringCalculator.java
> +    public static int calculate(String input) {
한 메서드에서 너무 많은 걸 하고 있는것 같아요 😢 
역할을 나눠서 메서드로 분리해보는건 어떨까요~?

2021-07-23 17:39 UTC, ep1stas1s commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +    void 이항연산(String input, int expected) {
여기도 마찬가지로 displayName을 적극 활용해보시는건 어떨까요~?

2021-07-23 17:39 UTC, ep1stas1s commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
계산식이 잘 못 된 경우도 테스트해보면 좋을 것 같아요^_^

2021-07-23 17:39 UTC, ep1stas1s commented on src/main/java/stringcalculator/StringCalculator.java
> +        String[] split = input.split(" ");
공백이나 매직넘버 등을 상수로 만들어 의미를 부여해주면, 다른 개발자가 읽을 때 큰 도움을 될 것 같습니다ㅎㅎ

2021-07-24 16:24 UTC, harrisleesh commented on src/main/java/stringcalculator/StringCalculator.java
> +        else if (operator == '*')
Enum을 사용하도록 리팩토링을 진행했습니다!!

2021-07-24 16:24 UTC, harrisleesh commented on src/main/java/stringcalculator/StringCalculator.java
> +            throw new IllegalArgumentException();
중괄호 추가하여 변경했습니다!

2021-07-24 16:25 UTC, harrisleesh commented on src/main/java/stringcalculator/StringCalculator.java
> +    public static int calculate(String input) {
메서드 분리해서 적용했어요!!:)

2021-07-24 16:25 UTC, harrisleesh commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
계산식이 잘 못 된 경우의 테스트를 추가했습니다.^^

2021-07-24 16:26 UTC, harrisleesh commented on src/main/java/stringcalculator/StringCalculator.java
> +        String[] split = input.split(" ");
상수로 만들었습니다!
코드리뷰 감사드립니다:)

2021-07-24 16:26 UTC, harrisleesh commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +    void 이항연산(String input, int expected) {
각각의 테스트에 DisplayName을 추가했습니다.

2021-07-25 06:03 UTC, harrisleesh commented
> 간단하게 잘 구현해주셨네요 👍
> 이번엔 스텝에선 else를 제거하는 걸 중점으로 리팩토링해보시는 걸 권장드립니다ㅎㅎ

용준님 SLACK DM 확인 부탁드려요!!

2021-07-25 06:33 UTC, ep1stas1s approved these changes
피드백 잘 반영해주셨네요 👍 
다음 스텝 진행해주세요 ^_^

2021-07-25 06:33 UTC, ep1stas1s commented on src/main/java/stringcalculator/Operation.java
> +public enum Operation {
훨씬 깔끔하네요 👍

2021-07-25 06:33 UTC, ep1stas1s commented on src/main/java/stringcalculator/Operation.java
> +    private final BiFunction<Double, Double, Double> biFunction;
`DoubleBinaryOperator` 요런 친구도 있으니 참고해주세요 :)

2021-07-25 06:33 UTC, merged