Step3
next-step/java-racingcar pull request #2403
Opened 2021-07-23 14:17 UTC by SeoYoungDuk

안녕하세요! 

Step3 자동차 경주 구현 완료 했습니다.

객체의 각자의 역할들에 대해서 생각하는것과 객체들과 View들을  분리 하고 싶었던게 

고민이 많이 됬던 미션 이었습니다.

이번에도 리뷰 잘 부탁드립니다.

감사합니다!

2021-07-24 08:28 UTC, JunilHwang requested changes
안녕하세요 영덕님! 자동차 경주 미션 잘 진행해주셨네요 👍 
몇 가지 피드백 남겼으니 확인 후 다시 리뷰요청 부탁드려요!

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/Service/RacingGame.java
> +        return new ResultView(board);
Service 혹은 Domain 레이어가 View를 반환하는건 어색한 것 같아요! 이 부분은 더 상위 레이어에서 처리해줘야 하지 않을까요?

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Board.java
> +}
이건 Domain보단 DTO에 가까운 것 같아요~

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Car.java
> +    private static int INIT_POSITION = 0;
상수와 멤버변수는 개행으로 구분해주면 어떨까요?

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Car.java
> +    }
```suggestion
    public Car(position) {
        this.position = position;
    }
    
    public Car() {
        this(INIT_POSITION)
    }
```
이런 형태로 관리해주면 어떨까요?

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Car.java
> +    }
```suggestion
    private boolean isMovable(int randomNumber) {
        return randomNumber >= MOVABLE_BOUND;
    }
```
이렇게 표현하면 된답니다~

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Car.java
> +    }
그런데 isMovable의 조건이 여러개일 땐 어떻게 해야 할까요?
지금은 자동차가 움직일 수 있는 조건이 한 개 밖에 없는데, 만약에 조건이 10개, 100개일 때도 이렇게 내부에서 전진조건을 관리하고 조합하여 사용해야할까요?

이를 해결할 수 있는 방법 중 하나가 전략패턴(strategy) 입니다! 인터페이스를 이용해서 로직을 주입하여 사용하는 것인데, 한 번 적용해보세요!

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Cars.java
> +    }
스트림 메소드는 한 줄에 한 개만 사용해주세요!

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Cars.java
> +    }
```java
    public void movable() {
        cars.forEach(car -> car.movable(RandomNumberUtils.executeRandomNumber()));
    }
```
이렇게 표현해도 될 것 같아요~

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/Cars.java
> +    }
```suggestion
    private Cars(List<Car> cars) {
        this.cars = cars;
    }
    
    public static of Cars(List<Car> cars) {
        return new Cars(cars);
    }
    
    public static of Cars(List<Car> cars) {
        List<Car> cars = new ArrayList<Car>();

        for (int i = 0; i < numberOfCar; i++) {
            cars.add(new Car());
        }

        return Cars.of(cars);
    }
```

이렇게 정적 생성 팩토리 메소드 패턴을 사용해보면 어떨까요?

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/model/RacingInfo.java
> +}
이것도 modal보단 dto에 어울리는 것 같아요~

2021-07-24 08:28 UTC, JunilHwang commented on src/main/java/racingcar/view/ResultView.java
> +    }
이 코드도 for이 중첩된것과 동일하다고 생각합니다. forEach에 주입된 메소드를 분리해서 관리해주면 어떨까요?

2021-07-24 08:28 UTC, JunilHwang commented on src/test/java/racingcar/RacingCarTest.java
> +}
테스트코드가 너무 빈약하네요.
도메인 클래스의 전체 메소드에 대해서 테스트할 수 있도록 작업해주세요!

2021-07-24 14:16 UTC, SeoYoungDuk commented on src/main/java/racingcar/Service/RacingGame.java
> +        return new ResultView(board);
네 Board Dto 를 이용하여 더 상위 레이어 에서 처리 하도록 했습니다.

2021-07-24 14:20 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Board.java
> +}
네 DTO 패키지를 만들어 refactor 시켰습니다.

2021-07-24 14:21 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/RacingInfo.java
> +}
네 DTO 패키지를 만들어 RacingInfo class 를 refactor 했습니다.

2021-07-24 14:26 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Car.java
> +    }
넵 ㅎㅎ 이런 형태로 생성자를 수정해보겠습니다 감사합니다 ㅎㅎ

2021-07-24 14:26 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Car.java
> +    private static int INIT_POSITION = 0;
넵 ! 개행처리 했습니다 ㅎㅎ

2021-07-24 14:29 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Cars.java
> +    }
넵 수정 완료 하였습니다 ㅎㅎ 감사합니다!

2021-07-24 14:40 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Cars.java
> +    }
네 정적 생성 팩토리 메소드 패턴 적용해서 구현 해보겠습니다 !

2021-07-24 14:46 UTC, SeoYoungDuk commented on src/main/java/racingcar/view/ResultView.java
> +    }
아 네 ! 분리 처리해주는게 좋을꺼 같습니다 ㅎㅎ 이런식으로 말씀 하신건지  
PR 요청 드릴테니 한번 더 확인 해주시면 감사하겠습니다 ㅎㅎ

2021-07-25 06:50 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Car.java
> +    }
넵 전략 패턴 적용 해보았습니다. 다시 한번 확인 부탁드리겠습니다 ㅎㅎ

2021-07-25 07:19 UTC, SeoYoungDuk commented on src/test/java/racingcar/RacingCarTest.java
> +}
layer 별로 분리 후 추가적으로 테스트 코드 작성 하였습니다!!

2021-07-25 11:29 UTC, JunilHwang approved these changes
안녕하세요 영덕님! 피드백 반영 잘 해주셨네요 👍 
몇 가지 리뷰 남겼으니 다음 단계 진행하실 때 참고하면 좋을 것 같아요!
Step3는 여기서 마무리하겠습니다. 바로 다음 단계 진행해주세요~

2021-07-25 11:29 UTC, JunilHwang commented on src/main/java/racingcar/model/Car.java
> +    private MovingStrategy movingStrategy;
멤버변수로 가지고 있기 보단 최상위 레이어에서 Car 관련 메소드를 실행할 때 건네주는 방식으로 작성해주면 어떨까요? 이렇게 멤버변수로 관리할 경우 유연하게 사용하기가 힘들답니다!

2021-07-25 11:29 UTC, JunilHwang commented on src/main/java/racingcar/model/Cars.java
> +    }
```suggestion
    public List<Integer> getCarsPositions() {
        return cars.stream()
            .map(car -> car.getPosition())
            .collect(Collectors.toList());
    }
```
이렇게 스트림 메소드의 경우 한 줄에 한 개만 사용해주세요!

2021-07-25 11:29 UTC, JunilHwang commented on src/main/java/racingcar/model/Cars.java
> +    }
여기서 movable을 할 때 strategy를 주입해주면 더 좋을 것 같아요!
그리고 movable은 형용사다보니 메소드에는 어울리지 않는 이름인 것 같아요! 동사형태로 작성해주세요~

2021-07-25 11:29 UTC, JunilHwang commented on src/main/java/racingcar/strategy/MovingStrategy.java
> +}
한 개의 메소드만 있어도 되지 않을까요?

2021-07-25 11:29 UTC, JunilHwang commented on src/main/java/racingcar/util/RandomNumberUtils.java
> +}
생성자 방어로직이 있으면 어떨까요? 아니면 싱글톤 객체로 만들어서 사용해주면 더 좋을 것 같아요~

2021-07-25 11:29 UTC, JunilHwang commented on src/test/java/racingcar/model/CarsTests.java
> +    }
이왕 MethodSourec를 사용하는 김에, 더 다양한 input을 만들어주면 어떨까요?

2021-07-25 11:46 UTC, merged

2021-07-25 14:55 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Cars.java
> +    }
넵 다음 step 진행 하기 전에 반영 하겠습니다 !

2021-07-25 15:49 UTC, SeoYoungDuk commented on src/main/java/racingcar/util/RandomNumberUtils.java
> +}
넵 생성자 방어로직으로 인스턴스 생성을 막는게 좋을것 같습니다. 적용하였습니다!

2021-07-25 15:49 UTC, SeoYoungDuk commented on src/test/java/racingcar/model/CarsTests.java
> +    }
다른 input들도 추가하였습니다!

2021-07-25 15:49 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Cars.java
> +    }
넵 바로 적용하겠습니다! 다음 step 에서도 유의하여 사용 하겠습니다 ㅎㅎ

2021-07-25 16:01 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Cars.java
> +    }
넵 move 라는 동사로 반영 완료 했습니다!

2021-07-25 16:02 UTC, SeoYoungDuk commented on src/main/java/racingcar/strategy/MovingStrategy.java
> +}
move 만 사용하여 수정 하였습니다 ㅎㅎ

2021-07-25 16:03 UTC, SeoYoungDuk commented on src/main/java/racingcar/model/Car.java
> +    private MovingStrategy movingStrategy;
Car의 메소드로 strategy를 건네주는 방법으로 수정 완료 했습니다