Feature/step3 pull request
next-step/java-racingcar pull request #2409
Opened 2021-07-23 17:54 UTC by woung717

감사합니다^^

2021-07-24 05:08 UTC, dbeod2 requested changes
안녕하세요! :)

3단계 미션 자동차 경주 늦게까지 구현하신다고 수고 많으셨어용 👏🏻👏🏻👏🏻

몇 가지 의견드릴게 있어서 코멘트 달아두었습니다.
확인 해주시고, 의견나누고싶으신 부분이나 궁금한점 있으시면 편하게 DM주세요 🙂🙂

리뷰 요청 기다리고 있겠습니다! 🚗🚕🚙

2021-07-24 05:08 UTC, dbeod2 commented on src/main/java/step3/Enum/MOVE.java
> +package step3.Enum;
패키지 이름은 클래스 OR 인터페이스 이름과의 충돌을 피하기 위해 모두 소문자로 작성하도록 정해져 있습니다.
확인부탁드리며, 참고 URL전달드릴게요! 
[패키지 네이밍 규칙](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2021-07-24 08:15 UTC, woung717 commented on src/main/java/step3/Interface/OutputInterface.java
> +public interface OutputInterface {
해당 인터페이스는 옵저버 패턴의 구현 클래스인 SimpleRacingStatus을 정의하고 있는데요. 해당 과제에서 요구하는 조건은 아니지만 해당 인터페이스를 통해서 다른 형태의 옵저버도 구현하기 쉽게 하도록 의도한것입니다. 해당 프로젝트에서는 SimpleRacingStatus이외에 별도의 옵저버를 구현하지는 않기때문에 필수는 아니긴 합니다ㅎㅎ

2021-07-24 08:21 UTC, woung717 commented on src/main/java/step3/RacingGame.java
> +    public void detach() {
미사용 코드이긴한데...옵저버패턴을 사용하는 클래스에서는 있어야하는 부분이라..유라님은 어떻게 생각하시나요ㅎㅎ

2021-07-24 08:35 UTC, woung717 commented on src/main/java/step3/RacingGame.java
> +    private OutputInterface outputInterface;
해당 클래스에 정의되어 있는 멤버 outputInterface 는 UI클래스의 역할을 하는 옵저버 클래스를 저장하기 위한 역할(원래는 List형태로 하기는 하지만요.)을 하고 있는데요, 실제 게임을 진행하는 비즈니스 로직은 RacingGame에서 실행되고 RacingGame의 상태를 출력하는 역할은 옵저버 클래스인 SimpleRacingStatus에서 실행되고 있습니다.

2021-07-24 12:20 UTC, dbeod2 commented on src/main/java/step3/RacingGame.java
> +    public void detach() {
일단, 알겠습니다! 🤔 
필수 클래스에 있어야하는 부분이라면..
의도가 있으셔서 옵저버 패턴을 사용하신거라고 판단되서 따로 의견을 드릴게없네요. 
이부분은 넘어가도록 하겠습니다! 👏🏻

2021-07-24 13:05 UTC, woung717 commented on src/main/java/step3/Enum/MOVE.java
> +public enum MOVE {
음 enum 필드값에는 매직넘버가 따로 상수값 치환이 되지 않는것 같습니다....다른 방법이 있을까요?

2021-07-24 13:50 UTC, dbeod2 commented on src/main/java/step3/Enum/MOVE.java
> +public enum MOVE {
엇. 제가 리뷰를 여러개 하다보니 ㅠㅠ혼동이 온것 같습니다 해당 리뷰 제거하겠습니다!

2021-07-25 01:56 UTC, dbeod2 approved these changes
안녕하세요 현웅님! 

피드백 반영 잘 해주셨습니다 👍🏻👍🏻👍🏻
몇가지 의견드릴 부분이 있어서 코멘트 남겨두었습니다. 🙇🏻‍♀️
확인 부탁드리며, 코멘트 남겨드린 부분은 
다음미션때 반영해주셔도 될 것 같아서3단계 미션은 여기서 머지하겠습니다👏🏻

그럼 다음미션을 진행해 주세요! 🏎🏎🏎

2021-07-25 01:56 UTC, dbeod2 commented on src/main/java/step3/observers/SimpleRacingStatusView.java
> +                .collect(Collectors.joining());
ouputString  구현부가 가독성이 좋지 않은 것 같습니다 🥲
이중 for문을 사용하고 계신데요.

이중for에 대해 메서드 분리를 해보시는건 어떨지 의견드려봅니다! 🙏

2021-07-25 01:56 UTC, dbeod2 commented on src/main/java/step3/RandomNumberGenerator.java
> +    private static final int randomIntBound = 10;
매직넘버 치환을 잘 해주셨는데요! 
상수 네이밍 규칙은 모든 글자에 대문자를 사용해야 합니다. 
아래 참고 링크 전달 드립니다 🙇🏻‍♀️
[네이밍 명명규칙](https://wakestand.tistory.com/209)

2021-07-25 01:56 UTC, dbeod2 commented on src/main/java/step3/RandomNumberGenerator.java
> +    private Random random;
피드백 반영 잘해주셨네요👏🏻👏🏻👏🏻
다만, RandomNumberGenerator를 null로 선언해주신 이유가 따로 있을까요? 🤔

2021-07-25 01:56 UTC, dbeod2 commented on src/main/java/step3/RacingGame.java
> +    }
자동차를 만드는 로직 부분은 만들어 주신 Cars 도메인으로 책임이라고 판단됩니다.
현웅님 생각은 어떠신가용?🤔

2021-07-25 01:56 UTC, dbeod2 commented on src/main/java/step3/GameMain.java
> +    }
Scanner 사용 후 종료시 scanner.close(); 를 선언해 암묵적으로 연결을 끊어주어야 합니다.
나중에 리소스 접근이 불가능하거나 connection pool이 꽉 차서 접근이 안되는 경우가 생길 수 있습니다.
그러하므로 I/O사용시에는 연결에 대해 확실하게 끊어줘야 합니다 🙂

2021-07-25 01:57 UTC, merged

2021-07-25 05:19 UTC, woung717 commented on src/main/java/step3/RandomNumberGenerator.java
> +    private Random random;
기능적으로 의미가 있는 부분은 아니고 싱글톤 클래스에서 해당 멤버의 초기 상태가 null이라는 것을 설명해주는 역할의 선언입니다.

2021-07-25 06:03 UTC, woung717 commented on src/main/java/step3/RacingGame.java
> +    }
복수개의 Car 오브젝트를 생성하는 팩토리 클래스로 분리하는것도 괜찮아 보입니다^^