Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2426
Opened 2021-07-24 14:34 UTC by shirohoo

어렵네유 😣

2021-07-25 07:11 UTC, jaeyeonling requested changes
4단계 미션을 잘 구현해주셨네요 👍 
추가적인 코멘트 남겨두었으니 확인 부탁드려요~
반복되는 피드백으로 힘드실텐데 조금만 더 화이팅입니다!!

2021-07-25 07:11 UTC, jaeyeonling commented on src/main/java/racing/model/Car.java
> +    private static final String MARK = "-";
움직인 위치를 "-"가 아닌 "*"로 바꿔달라는 `View의 요구사항`이 바뀔 경우 `Domain`을 수정해야 한다면 어떠한 문제가 있을지 고민해보아요

2021-07-25 07:11 UTC, jaeyeonling commented on src/main/java/racing/domain/RacingGame.java
> +    private class RacingConfig {
```suggestion
    private static class RacingConfig {
```

inner class에 static을 적용할 경우 어떠한 차이가 있을지 공부해보아요

2021-07-25 07:11 UTC, jaeyeonling commented on src/main/java/racing/model/UnnamedCar.java
> +public class UnnamedCar implements Racer {
해당 클래스는 현재 테스트에서만 사용중인 것 같은데요
프로덕션에 필요 없는 코드는 프로덕션에서 제거해도 괜찮을 것 같습니다!

2021-07-25 07:11 UTC, jaeyeonling commented on src/main/java/racing/model/Racers.java
> +public class Racers<T extends Racer> {
전체적으로 코드를 잘 작성하고 계시는데 도메인에서 도메인의 요구사항이 아닌 View의 요구사항이 보이는 것이 조금 아쉽네요!
도메인을 구현할 때는 View에 대한 부분은 생각하지 않고 작성해주셔도 좋을 것 같습니다 :)

또한 기존 코드를 계속 리팩토링하다 보면 오히려 의도하지 않은 방향으로 흘러갈 때가 있는데요
그럴 경우 처음부터 다시 코드를 작성하는 게 더 빠른 시간에 좋은 코드가 나올 때도 있습니다 ㅎㅎ (저도 클린코드 과정 처음 들을 때 한 과제를 5번씩 지우고 짜고 그랬습니다.. 😭 )
물론 힘들더라도 리팩토링을 통해 문제를 해결하는 것이 리팩토링 역량을 키우는 데는 좋습니다 😄

2021-07-25 07:11 UTC, jaeyeonling commented on src/main/java/racing/domain/RacingGame.java
> +        private final Racers racers;
제네릭을 사용할 경우 타입을 명시해주지 않으면 어떠한 문제가 있을지 고민해보아요

2021-07-25 11:04 UTC, shirohoo commented on src/main/java/racing/model/Racers.java
> +public class Racers<T extends Racer> {
이게 나름 고민을 해본 문제였습니다.

요구사항에서 요구하는 콘솔뷰를 어떻게 그려줄것이냐? 라는 명제에서 저는 다음과 같은 두개의 솔루션을 생각했어요.

1.  데이터를 실시간으로 append시키고 완성된 String을 내려준다
2.  각 턴마다 자동차의 상태를 List에 저장하고 완성된 List를 내려준다

뷰에서 요구하는 데이터를 도메인에서 만들어 내려주면 성능상 더 유리하다고 봤습니다.
두번째 방법은 List안에 List가 들어가야되거나 HashMap같은것을 써야할거라고 생각했거든요.
물론 뷰랑 도메인의 관심사가 분리되지 못한다는 단점도 분명 있다고 인지는 하고 있었구요.

그래서 이번에는 뷰에서 요구하는 데이터만을 도메인에서 만들어 내려주게 바꿔봤는데, 생각보다 복잡도가 많이 올라갔다는 생각이 들었습니다.

관심사는 어느정도 분리가 된 것 같기는 한데요.
제가 생각한 두개의 솔루션간에 트레이드오프가 너무 명확합니다.

뭔가 더 좋은 제3의 솔루션이 있을까요?

2021-07-25 11:05 UTC, shirohoo commented on src/main/java/racing/util/RacingGameScanner.java
> +        Scanner sc = new Scanner(System.in);
System.in을 close시키면 두번째 입력이 안받아지는 문제때문에 생략했었어요. 😣

2021-07-26 10:22 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
질문에 대한 답변 남겨두었으니 확인 부탁드리고..! 어려운 부분이 있으면 편하게 DM 주세요 😄 
그럼 다음 단계 진행하며 반영해주세요!!

2021-07-26 10:22 UTC, jaeyeonling commented on src/main/java/racing/model/Racers.java
> +public class Racers<T extends Racer> {
뷰랑 도메인의 관심사 분리의 관점도 있지만, 데이터 주도 설계가 아닌 책임 주도 설계 관점에서 접근해봐도 좋을 것 같은데요
도메인이 자신의 책임과 역할에 집중하지 못하면 어떠한 문제가 있을지 고민해보면 좋을 것 같아요!

Layered Architecture, Clean Architecture, Onion Architecture 등 여러 아키텍처가 존재하는데,
해당 아키텍처가 생긴 모습과 철학은 다르지만, 핵심은 외부와 닿아있는 View에서 Domain이 가장 멀리 존재한다는 사실! 을 시작으로 접근해보면 더욱 좋은 고민이 될 것 같습니다 😄

말씀해주신 것과 같이 실시간으로 String을 만드는 것과 상태를 별도로 저장해두는 것을 단순 성능으로 비교한다면 전자의 경우가 매우 효율적이라고 생각이 됩니다만..!
컴퓨팅 파워가 싸진 현대에서는 효율성 보다는 코드의 퀄리티나 유지보수성을 우선으로 생각하는 트렌드인 것 같습니다
특히 메모리 내부에서 발생하는 연산의 경우 굉장히 빠르기 때문에 더욱 그런 성향이 강한 것 같네요 ㅎㅎ 


현업에서 개발을 하다보면 대용량 트래픽 처리 등의 이유로 순수 도메인에 집중하지 못하게 되는 경우도 있지만, 지금은 순수 객체지향에 집중하여 데이터 중심의 접근법에서 순수 도메인의 모델과 로직에 집중하는 기회가 됐으면 합니다!

해당 코멘트는 어려운 내용이 많아서 의견을 나누고 싶거나, 궁금하신 점이 있으면 편하게 DM 또는 코멘트를 남겨주세요..!!

2021-07-26 10:22 UTC, merged

2021-07-27 10:52 UTC, Changhun-H commented on src/main/java/racing/domain/RacingGame.java
> +        private final Racers racers;
로타입을 사용하면 타입안정성이 깨질 우려가 있다는군요 😯

2021-07-27 10:53 UTC, shirohoo commented on src/main/java/racing/domain/RacingGame.java
> +        private final Racers racers;
로타입을 사용하면 타입 안정성을 아예 포기하는 판단이라고 하네요 😯

2021-07-27 10:58 UTC, shirohoo commented on src/main/java/racing/domain/RacingGame.java
> +    private class RacingConfig {
중첩 클래스에서 `static`을 사용하지 않으면 외부 인스턴스와 암묵적으로 연결될 수 있고, 메모리 누수등의 사이드 이펙트가 발생할 수 있다고 하네요. 😲