Step4 리뷰 요청드립니다.
next-step/java-racingcar pull request #2429
Opened 2021-07-24 15:17 UTC by kdh85

재석님 안녕하세요.
step4에 대한 구현이 완료되어 리뷰를 요청드립니다.

step4는 step3때와는 다르게 소스의 전반적인 리팩토링이 상당히 많이 발생했습니다.
기존에 구현 되있던 코드들을 새로운 요건 기준으로 변경하거나 새롭게 구현해야 했는데요.
이 과정에서 객체지향의 여러 특성 중 다형성에 대해서 많이 생각해 보는 계기가 된 거 같아요.
생성자로 주입하는 방식을 유지하면서도 추가되는 파라메터로 인해 오버라이드를 많이 사용했던 것 같습니다.

구현하면서 가장 힘들었던 점이라면 아무래도
마지막에  경주 승자를 뽑기 위해서 racing 클래스에서 승자 추출 테스트 코드를 작성하다 실패한 일 인거 같아요.

일급콜랙션인 Cars 클래스까지는 제가 테스트값을 주입하는 방식에서 승자를 조작해서 테스트코드 케이스별로 구현을 성공했었지만 전체프로세스를 전부 타게되는 racing 클래스에서의 승자조작은 기존의 코드만으로는 구현하지 못했습니다.
테스트케이스 작성을 위해서 별도의 생성자 타입을 만들고 주입 값을 넣을 수 있는 구조를 구현해야 가능하다고 판단했습니다.

여기서 질문이 생겼는데요.
이렇게 랜덤값을 필연적으로 사용하는 테스트 케이스가 앞으로 개발을 쭉 하면서 많이 발생될 거라고 생각합니다.
이럴 때 어떤식으로 해결을 하는게 유리할까요?
이러한 특수한 경우를 위해서 별도의 로직을 구현해서 테스트코드를 만들어는 방식이 괜찮은지 궁금합니다.

날씨가 많이 덥네요.
건강 유의하시고 항상 감사합니다.
밤이 늦었네요. 오늘 하루 수고하셨습니다.

2021-07-25 08:31 UTC, seok-2-o requested changes
우승자를 구하는 미션을 잘 구현해주셨네요 👍 
몇가지 코멘트 남겨놓았으니 해당부분 수정 후 다시 리뷰 요청주세요.
질문내용은 코멘트로 답변남겨두었습니다.

2021-07-25 08:31 UTC, seok-2-o commented on src/main/java/study/racing/common/Common.java
> +    public static String[] splitCarsName(String carsName) {
또 유틸리티 클래스를 사용하셨네요.

심지어 메소드 이름에 Car가 들어감으로써 특정 도메인에 종속된 느낌을 주는것 같아요.

해당 행위를 구지 유틸리티클래스로 분리해야할 이유가 있을까요?

2021-07-25 08:31 UTC, seok-2-o commented on src/test/java/study/racing/domain/CarTest.java
> +        assertThat(max).isGreaterThan(target);
```suggestion
        int max = car.maxDistance(0);

        assertThat(max).isEquals(1);
```
테스트가 의도하는 바를 명확하게 이해하기가 어렵네요.

2021-07-25 08:31 UTC, seok-2-o commented on src/main/java/study/racing/domain/Cars.java
> +            .filter(car -> car.isWinner(getMaxMoveDistance()))
getMaxMoveDistance() 는 멱등성이 보장될텐데 
매번 새로 max 값을 가져올 필요가 있을까요?

2021-07-25 08:31 UTC, seok-2-o commented on src/main/java/study/racing/domain/Car.java
> +        return distance.getMoveDistance() == maxMoveDistance;
이번 과정에서 getter 사용은 최소화 하는 것이 좋아요 특히 distnace 는 값객체 이므로
equals 를 구현해서 비교하는것은 어떤가요 ?

2021-07-25 08:31 UTC, seok-2-o commented on src/main/java/study/racing/controller/RacingController.java
> +    Racing racing = new Racing(
테스트하기 어려운부분은 어플리케이션 가장 바깥에서 주입해주면 전반적오르 테스트 하기가 쉬워질 수 있습니다.
예를들어 Cars 나 Racing이 랜덤값을 생성해주는 객체를 주입 받는다면 해당 객체를 변형해서 하위 항목들을 테스트하기 
용이해지는 것 같아요
예를들어 임의의 숫자를 반복적으로 응답하는 RandomGenerator를 주입해서 우승자나 가장 멀리 간 자동차를 구할때 활용 할 수 있을 것 같아요.

2021-07-25 10:55 UTC, kdh85 commented on src/main/java/study/racing/common/Common.java
> +    public static String[] splitCarsName(String carsName) {
아 이습관이 쉽게 고쳐지지가 않네요.
차량의 이름들을 나누는 역할에 맞게 Cars에서 처리를 하려합니다.
구분자는 static final로 빼서 처리할 계획입니다.

2021-07-25 11:00 UTC, kdh85 commented on src/test/java/study/racing/domain/CarTest.java
> +        assertThat(max).isGreaterThan(target);
TDD를 통해서 Car 클래스에 메소드를 만드는 식으로 접근하면서 생성된 테스트코드네요.

랜덤값을 주입하지 않고 4보다 큰 값을 주입해서 이동이 발생하게 테스트 값을 유도했을때

정상적으로 수행이 된다면 비교값인 0이 아닌 1이 리턴받게 될 것이고 
이것을 수비교 형식으로 표현해보려고 했습니다.

2021-07-25 11:14 UTC, kdh85 commented on src/main/java/study/racing/domain/Car.java
> +        return distance.getMoveDistance() == maxMoveDistance;
equals 를 사용하란 말씀은 객체비교를 하자는 말씀으로 들리는데 제가 이해한게 맞을까요?

2021-07-25 12:02 UTC, kdh85 commented on src/main/java/study/racing/domain/Cars.java
> +            .filter(car -> car.isWinner(getMaxMoveDistance()))
기존 최대값과 다음 차량의 최대값을 비교하여 더 큰 경우에만 최대값이 갱신되도록 변경하겠습니다.

2021-07-26 02:29 UTC, kdh85 commented on src/main/java/study/racing/controller/RacingController.java
> +    Racing racing = new Racing(
RandomGenerator의 개념이 잘 이해가 되지 않아요... 
racing은 한번 수행되는 상황이라 생성자를 한번 생성하고 있는데요.
이때 랜덤값을 주입을 하라는 말씀이시죠?
근데 이렇게 구현하면 단순히 랜덤값을 하나 넣으면 그 값으로 쭉 연산되는 식이라 안될 것이고
매번 새로운값을 넣어야 하는데 이때 RandomGenerator라는 것을 구현해서 주입을 하라는 말씀이신거 같은데요.
제가 이해한게 맞는지 궁금합니다.
맞다면 RandomGenerator가 구체적으로 어떻게 접근해야할지 조금 막막합니다.

2021-07-26 02:31 UTC, kdh85 commented on src/main/java/study/racing/domain/Car.java
> +        return distance.getMoveDistance() == maxMoveDistance;
제가 조금 고민을 해보았는데요.
car 클래스에서 원시값 포장인 거리클래스의 getter값 비교가 문제가 된다면
거리클래스에 파라메터를 동반하여 메세지를 보내서
boolean 리턴하는 방식으로 구현하는건 어떨까요? 제가 생각할때는 굳이 클래스를 비교할 필요가 없다면
거리에 대한 판별을 요구하는 내용이기 때문에 거리클래스에서 뭔가를 해주고 그것에 대한 리턴을 받는것도 나쁘진 않다고 생각해서요. 재석님의 의견도 생각은 해보겠습니다.

2021-07-26 08:23 UTC, seok-2-o commented on src/main/java/study/racing/controller/RacingController.java
> +    Racing racing = new Racing(
랜덤한 숫자를 만드는 기능을 객체로 만들면
```java
public class RandomPowerEngine implements Engine {

    private static final int MAX_POWER = 10;

    private final Random random = new Random();

    @Override
    public int get() {
        return random.nextInt(MAX_POWER);
    }
}
```
와 같습니다. 임의의 숫자를 매번생성해주는 객체로 활용 할 수 있어요.

테스트를 위해 아래 객체를 만들어 줄 수 있습니다.
```java
public class RepeatPowerEngine implements Engine {

    private final List<Integer> pool;
    private int idx = 0;

    public RepeatPowerEngine(List<Integer> pool) {
        this.pool = pool;
    }

    @Override
    public int get() {
        return pool.get(idx++ % pool.size());
    }
}
```

자동차 한대에 대한 테스트는
```java
    @DisplayName("자동차는 이동 테스트 - 4, 3, 2, 5 일때")
    @Test
    public void move_2() {
        Car car = new Car(new Name("seok2"), new RepeatPowerEngine(List.of(4, 3, 2, 5)));
        assertThat(car.move()).isEqualTo(new Record("seok2", 1));
        assertThat(car.move()).isEqualTo(new Record("seok2", 1));
        assertThat(car.move()).isEqualTo(new Record("seok2", 1));
        assertThat(car.move()).isEqualTo(new Record("seok2", 2));
    }
```

이런식으로 테스트 할 수 있습니다.
자동차들과 게임도 유사한 방식으로 테스트를 진행해보는건 어떤가요?

매번 자동차의 이동을 결정해주는 객체를 넣어주는것이 지저분하다면 아래와같이 분리할 수 있습니다.

```java
public final class EngineGenerator {

    private static final Engine DEFAULT_ENGINE = new RandomPowerEngine();

    private EngineGenerator() {
    }

    public static Engine ofDefault() {
        return DEFAULT_ENGINE;
    }
}
```

2021-07-26 08:24 UTC, seok-2-o commented on src/main/java/study/racing/domain/Car.java
> +        return distance.getMoveDistance() == maxMoveDistance;
값 객체이기때문이 필드를 하나만가지고 있고 equals 를 구현하는것이 더 용이하다고 생각합니다.
말씀하신것처럼 메소드를 만들어 getter 를 사용하지 않고 내부 값과 지금 값을 비교하는 것도 좋습니다 👍

2021-07-26 08:25 UTC, seok-2-o requested changes
마지막 피드백에 부연설명 남겨드렸습니다.
확인 후 리팩토링 진행해보면 좋을 것 같아요.

알고계시겠지만 제가 정답은 아니니 지금 방법이 옳다고 생각하시면
다시 PR 주셔도 무방합니다 :)

2021-07-26 13:51 UTC, seok-2-o commented on src/main/java/study/racing/view/InsertView.java
> +      number =  scanner.nextInt();
```suggestion
      number = scanner.nextInt();
```

2021-07-26 13:55 UTC, seok-2-o approved these changes
보통 프로덕션 코드에 비해 테스트코드가 2배 ~2.5배정도 많이 작성 된다고 해요
그만큼 테스트코드가 작성해야 할 양도 많고 어려운 것 같습니다.

지금 잘하고 계신 만큼 모든 과정이 종료될 때쯤이면 TDD에 더 많은 자신감을 얻어가길 바라겠습니다.

마지막 미션은 리펙토링입니다. 주어진 힌트를 가지고 충분한 연습을 진행해보면 좋겠네요.
물론 지금이 최선이라고 생각하시면 리펙토링은 진행하지 않으셔도 됩니다 :) 

요즘 날씨가 너무 더워서 지치기 쉬운데, 여유를 갖고 시원한 하루 보내시길 바랍니다.

2021-07-26 13:55 UTC, seok-2-o commented on src/main/java/study/racing/view/InsertView.java
> +      number =  scanner.nextInt();
소소하지만 이전에 말씀해주신 코드스타일을 적용하면 이러한 문제를 방지 할 수 있겠네요.

2021-07-26 13:56 UTC, merged