🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #2437
Opened 2021-07-25 05:04 UTC by JJongSue

https://github.com/next-step/java-racingcar/pull/2432
이전 것 까지 같이 포함되어서, PR 새로 등록합니다.
RacingCarInput과 RacingCarOutput으로 분리해 보았는데, 제가 제대로 이해한게 맞나요?

2021-07-25 05:37 UTC, ksundong requested changes
안녕하세요. 종수님! 😊

3단계 미션 진행해주시느라 고생하셨습니다!! 👏 👏 👏

분리해주신 부분은 좋았는데, 아직 조금 아쉬운 부분이 존재합니다. 관련해서 코멘트를 남겼으니 확인해주세요.

### 피드백

- main 메서드가 없어서 실행을 해볼 수 없습니다. 실행이 가능한 상태로 제출해주세요!
- 전체적으로 입출력과 비즈니스 로직이 섞여있어 테스트하기 어려운 구조가 되었습니다.
- I/O는 테스트 하기 어렵기도 하고, 요구사항에도 포함되어 있지 않기 때문에 단위 테스트에 좀 더 집중해주시면 좋을 것 같습니다.
- 테스트에 리플렉션을 활용하셨는데, 지양하시면 좋을 것 같습니다.
- 코드가 전반적으로 정렬이 수행되어있지 않은데, 항상 정렬해주시는 습관을 들여주세요!

그리고 생각해보면 좋을거리들이 보여서 해당 부분에 대한 피드백을 남겨드렸습니다. 💪

확인하시고 다시 리뷰 요청 부탁드립니다! 💪  고생하셨습니다!
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-25 05:37 UTC, ksundong commented on src/docs/3단계 - 자동차 경주.md
> +- [x] 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.
TODO List 작성을 잘 해주셨네요~
앞으로 개발을 하시면서 추가되는 부분도 있을 것이고, 변경되는 부분도 있을겁니다.
지속적으로 꾸준히 관리해주시는게 중요할 것 같습니다! (사소한 것이어도 TODO를 만들어주는게 되게 좋은 습관입니다!)

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +    int moveCount;
상태에는 `private` 접근제어자를 설정하여 가시성을 객체 내부로 한정시켜주세요!

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +    String status;
status는 사실 출력과 연관된 부분이기 때문에, 굳이 Car가 관리할 필요가 없는 상태로 보여집니다!

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +        this.moveCount = 1;
요구사항과는 다른 부분이네요. 시작시점 위치는 0이 아닐까요?

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +        return this.status;
`this`는 생략해주셔도 좋습니다.

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +        this.status += "-";
여기도 `this`는 불필요하기 때문에 추가해주지 않으셔도 좋습니다.

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private String[] gameResults;
`cars`만 가지고도 로직을 구성하는데 문제가 없지 않을까 싶습니다!
그리고 `List` 를 활용해주세요!

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private final int MINMOVENUMBER = 4;
네이밍 컨벤션과 맞지 않는 형태입니다.
상수라면 `static final`을 사용해주셔야 합니다.
또한, 구분자는 언더스코어(`_`)를 사용해주시면 됩니다.

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
내부 클래스의 사용은 해당 클래스들이 종속적인 경우 많이 사용합니다.
I/O는 이 클래스에 종속적인 개념은 아니기 때문에 별도의 클래스로 분리하는 것이 좋을 것 같네요!

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
해당 메서드가 실행을 담당하는걸까요?
몇 개는 이 클래스의 책임이 아닌 부분도 보이는 것 같네요~

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
외부에서 RacingCar를 생성하는 형태로 풀어보면 어떨까요?

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +        }
왜 인덱스가 `j` 로 시작하는지 잘 모르겠습니다!
또,
- 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.
가 지켜지지 않았네요! 확인해주세요~

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
메서드 호출시마다 `Random` 객체가 생성될텐데 이는 매우 좋지 않은 습관입니다.
또한, `r` 이라는 네이밍은 의도는 알겠지만 풀어써주세요~

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
해당 메서드는 여기 있으면 안될 것 같네요~

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    }
StringBuilder를 이용해서 한 번에 만들어주는게 성능상 훨씬 좋을 것 같습니다.

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +
테스트 환경 셋업을 잘 해주셨습니다.

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +    }
생성과 동시에 테스트해주신 부분 좋습니다~

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +    }
`Parameterized Test`의 사용 좋았는데요.
왜 굳이 `Reflection`을 사용해서 테스트를 진행해주셨는지 궁금합니다.
또한, 코드가 전반적으로 포매팅이 되어있지 않다는 느낌을 받습니다. 꼭 정렬을 수행해주세요.

2021-07-25 05:37 UTC, ksundong commented on src/main/java/Car/Car.java
> +        this.status += "-";
또한, 이동을 판단하는 조건이 `Car` 에 없기 때문에 효과적인 테스트가 되지 못할 것 같습니다!

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +    }
IO에 대한 테스트는 하지 않아도 괜찮습니다!

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +    }
리플렉션을 사용하지 않아도 충분히 테스트할 수 있습니다.

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +    }
랜덤에 대한 테스트는 단위테스트로는 불가능하다고 볼 수 있습니다.
API를 믿고 사용하는 것이 좋을 것 같네요.

2021-07-25 05:37 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +    }
해당 부분이 `Car`로 이동하면 어떨까요?

2021-07-25 15:20 UTC, ksundong requested changes
안녕하세요. 종수님! 😊

3단계 미션 피드백을 반영하느라 고생하셨습니다.👏 👏 👏
도메인에 필요한 테스트가 누락되어 다시 한 번 변경요청을 드리고자 합니다.

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/Car.java
> +    private static final int MIN_MOVE_NUMBER = 4;
자바 코딩 컨벤션상 상수가 위에 등장하고 그 아래에 상태가 등장해야합니다!

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/Car.java
> +
자바 코딩 컨벤션상 생성자 아래에 메서드가 위치해야합니다!

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/Car.java
> +
Random이 Car의 상태로 들어가게된다면, 테스트하기가 어려울 겁니다.

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private int gameCount;
이 세가지가 상태로 관리되어야 할 특별한 이유가 있나요?

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +        }
for문 안에 for문이 있는 구조입니다.

2021-07-25 15:20 UTC, ksundong commented on src/main/java/Car/RacingCarMain.java
> +    }
Main으로 잘 나눠주셨네요!

2021-07-25 15:20 UTC, ksundong commented on src/main/java/UI/OutputView.java
> +    private StringBuilder stringBuilder;
이것도 상태로 관리되어야 할 이유가 전혀 없어보입니다.

2021-07-25 15:20 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +    }
Car에 대한 테스트가 부족해보이네요.

2021-07-26 14:35 UTC, JJongSue commented
요구사항 반영해보았습니다.
RacingCarMain의 경우  RacingCar에 gameCount를 제거해서 이를 main에서 관리하는데,  
이 경우 RacingCar와 gameCount를 상태로 갖는 class를 만드는게 좋을까요?

2021-07-27 12:02 UTC, ksundong approved these changes
안녕하세요. 종수님! 😊

3단계 미션 피드백을 반영해주시느라 고생많으셨습니다.!! 👏 👏 👏

대부분 깔끔하게 정리가 된 코드가 된 것으로 보여집니다만, 동작상의 문제가 남아있네요 😭
다음단계에서 꼭 수정되면 좋을 것 같아요.
그리고 생각해보면 좋을거리들이 보여서 해당 부분에 대한 피드백을 남겨드렸습니다. 💪

고생하셨습니다. 이제 4단계네요!! 조금만 더 힘내봅시다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-27 12:02 UTC, merged