자동차경주게임 커밋
next-step/java-racingcar pull request #2449
Opened 2021-07-25 14:42 UTC by superkkj

2021-07-25 16:05 UTC, bass84 requested changes
기준님~! 귀중한 일요일에 시간 내서 만드시느라 수고 많으셨어요.

하지만, 앞서서 말씀 드렸던 기초적인 내용들이 계속해서 지켜지지 않아 아쉽습니다.
이런 것을 넘어 생각해야 할 더 많은 것들이 있는데 계속 아쉬운 마음이 드네요.ㅠㅠ
코멘트 드린 것들 꼼꼼히 체크하셔서 수정해주시고 다시 PR 주세요.

2021-07-26 00:39 UTC, superkkj commented on src/test/java/study/SetTest.java
> +        numbers = new HashSet<>(Arrays.asList( 1 , 1 , 2 , 3 ));
제가 잘못이해한거같습니다 죄송합니다..

2021-07-26 00:39 UTC, superkkj commented on src/test/java/study/StringTest.java
> +        String subString = "( 1 , 2 )".substring( 1 , 4 );
수정하겠습니다.

2021-07-26 04:38 UTC, superkkj commented on src/main/java/Calculator/StringCalculationExecutor.java
> +    private static int calculrationExecute(String operator , int number1 , int number2) {
변경햇는대 적용이안됀거같습니다 제가 실수로 중간에 잘못만져서 파일이 삭제되고 그랬거든요 아직 깃에 익숙하지않아서 수정해서 다시올리겠습니다 ㅠㅠ

2021-07-29 14:25 UTC, bass84 requested changes
기준님 안녕하세요~!
제가 이전 리뷰에서 객체의 책임과 역할에 대한 질문을 많이 드렸는데 답변이 하나도 없으시네요.
그 부분이 정리되지 않은 상태에서 작업을 다시 하셔서 그런지 수정하신 내용이 오히려 더 안 좋아지신 것 같아요. 🤕 
제가 드린 질문들은 다 답변 주셨으면 좋겠습니다. 이 바로 전에 드렸던 리뷰에서 드렸던 질문들도요. 지금 같은 방식으로 진행하는 것은 발전적이지 못한 것 같습니다.

답변 주시고 수정해서 PR 다시 주세요.

2021-07-29 14:25 UTC, bass84 commented on src/main/java/CarRacing/CarRacing.java
> +    public StringBuilder moveCarsToString(int tryCount) {
1. 이 메서드명은 무슨 의미인가요?^^
2. 자동차가 이동을 하는데 그 반환타입이 `-` 형태의 문자열일 필요가 있을까요? 자동차가 이동만 하면 되지 않을까요?^^

2021-07-29 14:25 UTC, bass84 commented on src/main/java/CarRacing/CarRacing.java
> +            cars.getCars().forEach(car -> stringBuilder.append(new String(new char[car.getCarPosition()]).replace("\0", "-") + "\n"));
한번 forEach()를 사용해서 처리하면 될 것을 두번을 돌리셨네요. 몇 가지 할 이야기는 더 있지만 위에 언급했 듯이 이 로직이 이 클래스에 있는 것 자체가 좋지 못하기 때문에 수정이 필요해서 더 언급은 안 드리겠습니다.

2021-07-29 14:25 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +        ResultView resultView = new ResultView();
inputView와 resultView는 외부로부터 매개변수를 받아서 입력 또는 출력을 하면 되는데 인스턴스 생성이 필요할까요?

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/InputView.java
> +    private StringBuilder insertCarCountAndTryCount() {
startInsertReturnStringBuilder()에서 호출만 하는데 이렇게 분리할 이유하신 이유가 있을까요?

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/InputView.java
> +        CarRacing carRacing;
입력을 받는 클래스에 CarRacing이 필요할까요?

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/InputView.java
> +
위에서부터 한 메서드 안에서 여러가지 일을 쭉 하고 있네요. 기능별로 분리해주세요.

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/InputView.java
> +        carRacing = new CarRacing(new Cars(carCount));
1. carRacing은 첫 줄에 선언하셨어요. 그런데 20줄 가까이 한번도 사용을 안 하고 여기에서 생성을 하셨네요. 이렇게 하신 이유가 궁금합니다.^^
2. 위에도 말씀 드렸지만 입력을 받는 클래스에서 CarRacing이 필요할까요?
3. 여기에선 경주게임을 실행까지 하셨네요. 이 클래스는 입력을 받는 클래스인데 이런 행위가 여기에 있는 것은 객체지향스럽지 못할 뿐더러 메서드명과도 전혀 일치하지 않는 행위예요.

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/ResultView.java
> +    private StringBuilder stringBuilder = new StringBuilder();
1. 이 stringBuilder 값을 인스턴스 변수로 가지고 생성을 하시는데 아래에는 setStringBuilder()가 있네요. 왜 이렇게 하셨는지 궁금합니다.^^
2. 이 stringBuilder 값을 인스턴스 변수로 가지고있을 필요가 있을까요? 그렇다면 이유도 궁금합니다.

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/ResultView.java
> +    private void resultRacing() {
이 메서드도 getResultRacing()에서 바로 호출만 하는데 이렇게 분리해야 할 이유가 있을까요?

2021-07-29 14:25 UTC, bass84 commented on src/main/java/view/ResultView.java
> +    public void getResultRacing() {
get을 쓰셨는데 반환하는 객체는 없네요?

2021-07-29 14:27 UTC, superkkj commented on src/main/java/CarRacing/CarRacing.java
> +    public StringBuilder moveCarsToString(int tryCount) {
이동만하는방법도 고민해봣는대 잘안돼서 문자열로반환했습니다 다시해보겠습니다

2021-07-29 14:27 UTC, superkkj commented on src/main/java/CarRacing/CarRacing.java
> +            cars.getCars().forEach(car -> stringBuilder.append(new String(new char[car.getCarPosition()]).replace("\0", "-") + "\n"));
네 ㅠㅠ

2021-07-29 14:40 UTC, superkkj commented on src/main/java/view/ResultView.java
> +    public void getResultRacing() {
같은거 저번에지적하셨는대 ㅠㅠ 죄송합니다

2021-07-29 14:42 UTC, superkkj commented on src/main/java/view/ResultView.java
> +    private void resultRacing() {
inputview랑 같게 생각했습니다 만약 코드를 수정할 경우가 생기면 전부 수정해야 된다? 그런생각때문에 ..

2021-07-29 14:50 UTC, superkkj commented on src/main/java/view/ResultView.java
> +    private StringBuilder stringBuilder = new StringBuilder();
변수로 선언해놓고.. 스트링벌더 set한다음 바로그냥 출력해주려고 선언했습니다 으음..

2021-07-29 14:57 UTC, superkkj commented on src/main/java/view/InputView.java
> +        carRacing = new CarRacing(new Cars(carCount));
그냥 코드흐름에따라 쓰다보니 맨밑에 쓰게됬네요... input는 입력값만 받음되는대 너무 쓸모없는코드였군요 ㅠㅠ

2021-07-29 15:12 UTC, superkkj commented on src/main/java/view/InputView.java
> +    private StringBuilder insertCarCountAndTryCount() {
저번에 알려주신대로 . 입력창에서 수정이 일어났을때 한번에 접근하면. 전체코드를 수정해야되기때문에 분리해놨씁니다

2021-07-29 15:17 UTC, superkkj commented on src/test/java/study/CarRacingTest.java
> +    void carRaicing() {
에고 검증하려고 하다가 만들다말앗네요 ㅠㅠ

2021-07-29 15:18 UTC, superkkj commented on src/main/java/CarRacing/Car.java
> +    public void carMove(int carMove) {
자동차를 움직인다 이런식으로 만들었는대 좀더간결하게만들겠습니다

2021-07-29 15:18 UTC, superkkj commented on src/main/java/CarRacing/CarRacing.java
> +    public void setCarList(int carCount) {
내부에서만쓰는대 굳이 퍼블릭으로 만들필요가없엇네요 수정하겠습니다. 생성할때 바로 자동차를 셋팅해주려고햇습니다

2021-07-29 15:18 UTC, superkkj commented on src/main/java/CarRacing/CarRacingMain.java
> +    private static int racingCount;
input에서 받은값을 저기다저장시키려고했습니다.

2021-07-29 15:19 UTC, superkkj commented on src/main/java/CarRacing/CarRacingMain.java
> +        Scanner sc = new Scanner(System.in);
네 분리하겠습니다

2021-07-29 15:19 UTC, superkkj commented on src/main/java/CarRacing/CarRacingMain.java
> +    private static CarRacing carRacing;
어..너무생각없이만들엇네요. ㅠㅠ

2021-07-29 15:19 UTC, superkkj commented on src/main/java/CarRacing/CarRacing.java
> +            carList.getCarListDistance();
get함수는 리턴이잇어야되는대  죄송합니다...

2021-07-29 15:21 UTC, superkkj commented on src/main/java/view/InputView.java
> +
기능별로 분리해보겠습니다.

2021-07-29 15:21 UTC, superkkj commented on src/main/java/view/InputView.java
> +        CarRacing carRacing;
역할이 맞지않네요 삭제하겠습니다

2021-07-30 01:30 UTC, superkkj commented on src/main/java/CarRacing/Car.java
> +    public int hashCode() {
처음에는 객체를 서로 비교하려고 만들었는대 코드를짜다보니 쓰이지가않네요...

2021-07-30 15:47 UTC, bass84 requested changes
기준님 수고하셨습니다~!

이전보다 좀 더 분리가 되어 나아진 점들이 있습니다.
고민을 많이 해보신 것 같아요. 👍 
질문 드린 것 중에 답변 안 주신 것도 한번 고민해보시고 답변주시면 감사하겠습니다.

몇몇 부분 수정해주시고 다시 PR 주세요~!

2021-07-30 15:47 UTC, bass84 commented on src/main/java/CarRacing/Car.java
> +    public int getPositon() {
메서드명 철자가 틀렸네요. 수정해주세요.

2021-07-30 15:47 UTC, bass84 commented on src/main/java/CarRacing/Cars.java
> +    private void addCarCount(int carCount) {
메서드명은 자동차수를 추가하는 건데 실제 내용은 자동차를 추가하는 내용이네요. 메서드명과 행위를 일치시키도록 노력해주세요^^

2021-07-30 15:47 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +    static final ResultView resultView = new ResultView();
이 부분은 질문 드린 게 있는데 답변이 없으시네요. 코드는 수정하셨는데 올바른 방향은 아닌 것 같습니다. 일단 고민해보시고 답변 주세요.

2021-07-30 15:47 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +    static Cars cars = null;
여기에서는 멤버변수로 변경하셨는데 그런 이유가 있으신가요?

2021-07-30 15:47 UTC, bass84 commented on src/main/java/CarRacing/Position.java
> +    public void move() {
1. Position이라는 객체는 위치에 대한 것만 관여해야 해요. 그렇다면 랜덤 값을 이 메서드에서 직접 호출하는 방식보다는 외부에서 받아서 처리하는 게 좋을 것 같습니다.
2. move라는 메서드명은 car에서는 어울릴 수 있지만 Postiion에서는 다소 안 어울리는 것 같아요. 다른 명칭을 한번 고민해보시면 좋을 것 같아요.^^

2021-07-30 15:47 UTC, bass84 commented on src/main/java/view/InputView.java
> +
여기 개행은 왜 하신 걸까요?

2021-07-30 15:47 UTC, bass84 commented on src/main/java/view/ResultView.java
> +    public void startRacing(List<Car> car) {
이 메서드명은 그리기를 담당하는 이 클래스에서 어울리는 이름은 아닌 것 같아요. 다른 이름 어떻게 하면 좋을까요?^^

2021-07-30 15:47 UTC, bass84 commented on src/main/java/view/ResultView.java
> +        car.forEach(s -> stringBuilder.append(new String(new char[s.getPositon()]).replace("\0", "-") + "\n"));
`new char[s.getPositon()]).replace("\0", "-") + "\n")`를 하나의 메서드로 따로 빼면 좋을 것 같아요.

2021-07-30 16:21 UTC, superkkj commented on src/main/java/CarRacing/Main.java
> +    static Cars cars = null;
아직 멤버변수랑 클래스 변수 적절히 사용법을 잘모르겠습니다. 그래서일단 컴파일오류안나는대로 멤버변수로 변경하였습니다

2021-07-30 16:23 UTC, superkkj commented on src/main/java/CarRacing/Main.java
> +    static final ResultView resultView = new ResultView();
밑에도 코멘트 달앗지만 변수 사용법을 적절히몰라서.. 어떻게 수정해야될지 감이잘안잡힙니다 ㅠㅠ

2021-07-30 16:29 UTC, superkkj commented on src/main/java/view/InputView.java
> +
습관적인대 코드를 좀더 보기쉽게 개인적으로 개행했습니다 수정하겠습니다.

2021-07-30 16:30 UTC, superkkj commented on src/main/java/CarRacing/Cars.java
> +    private void addCarCount(int carCount) {
네 알겠습니다 add 더하다 car 자동차 count 수 .. 자동차 추가.. 음 틀리네요 에고 ㅠㅠㅠㅠ

2021-07-30 16:31 UTC, superkkj commented on src/main/java/view/ResultView.java
> +        car.forEach(s -> stringBuilder.append(new String(new char[s.getPositon()]).replace("\0", "-") + "\n"));
네따로빼두도록하겠습니다.

2021-07-30 16:31 UTC, superkkj commented on src/main/java/CarRacing/Car.java
> +    public int getPositon() {
넵 바로수정하겠습니다.

2021-07-30 17:09 UTC, superkkj commented on src/main/java/view/ResultView.java
> +    public void startRacing(List<Car> car) {
다른이름으로 바꿔줘야겟죠.. ㅠ ㅠ

2021-07-30 17:09 UTC, superkkj commented on src/main/java/CarRacing/Position.java
> +    public void move() {
네 변경하겠습니다 .. 코드도 수정해야겠군욤

2021-07-31 03:23 UTC, merged