4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2459
Opened 2021-07-26 08:26 UTC by taeyoon216

리뷰 요청 드립니다!

2021-07-27 01:13 UTC, JunilHwang requested changes
안녕하세요 태윤님! Step3 마지막 피드백 내용이 전체적으로 반영되지 않았네요 ㅠㅠ 관련해서 다시 리뷰 남겼으니 확인 부탁드려요!

2021-07-27 14:00 UTC, JunilHwang requested changes
안녕하세요 태윤님! 피드백 반영 잘 해주셨네요 👍 
다시 몇 가지 고려해야할 부분에 대해서 남겨놨으니 확인 후 피드백 요청 부탁드려요!

2021-07-27 14:00 UTC, JunilHwang commented on src/test/java/edu/nextstep/racingcar/step4/domain/CarsTest.java
> +}
지금 테스트코드가 무척 빈약한 상태입니다.
strategy 관련 테스트 코드도 필요할 것 같아요!

car의 로직이 변경되었기 때문에 car 관련 테스트도 추가해주세요~

2021-07-28 02:01 UTC, JunilHwang approved these changes
안녕하세요 태윤님! 피드백 반영 잘 해주셨네요 👍 
이번 단계는 여기서 마무리 하겠습니다! 전체적으로 코드가 깔끔해졌네요 ㅎㅎ
다만 테스트 코드는 아직 많이 빈약해보여요! 어떤식으로 작성해야할지 감이 잡히지 않는다면 다른 분들이 작성한 것들을 참고해서 진행해주세요.

습관화 되어야 하는 부분이. 테스트코드를 통해서 도메인 코드들을 어떻게 사용할지 먼저 작성한 다음에 도메인 코드를 작성해야 한답니다! 그런 과정에서 메소드를 작은 단위로 분리하고 리팩토링을 하는 것이 이번 과정의 목적이라고 보시면 될 것  같아요.

이 외에도 자잘한 피드백 남겼으니 다음 단계 진행하실 때 참고해주세요!
이미 MVC로 잘 분리된 상태라서 마지막 단계에서 작업할 내용이 많지 않으리라 생각합니다. 
그래서 테스트 코드 위주로 보강하고 더 고칠 부분 없나 쭉 살펴보시면 좋을 것 같아요 ㅎㅎ 

고지가 코앞이네요. 조금만 더 힘내봅시다 💪

2021-07-28 02:04 UTC, merged

2021-07-28 04:11 UTC, taeyoon216 commented on src/main/java/edu/nextstep/racingcar/step4/domain/CarName.java
> +        if (name.length() > 5) {
넵! 변경하도록 할께요 :)

2021-07-28 04:12 UTC, taeyoon216 commented on src/main/java/edu/nextstep/racingcar/step4/domain/DefaultMoveStrategy.java
> +        return new Random().nextInt(NUMBER_OF_RANDOMS) >= THRESHOLD;
넵! 변경하도록 할께요 :)