Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2468
Opened 2021-07-26 15:04 UTC by jaeyoungjang2

이번 pull request는 step4로 제출을 하였지만, step3에 대한 코드를 다시 작성하여 컨펌을 받으려고 합니다.
이전에 보여드렸던 step3 구조가 너무 허접하여, 금일은 데이터 모델링을 어떻게 진행할지 계속해서 생각하고, 책도 찾아보았습니다.

많은 고민을 하여 코드를 작성 하였으며 이전보다는 구조적인 부분에서 많이 좋아진 것 같습니다. (제 개인적인 생각입니다..ㅎ)

컨펌 한번 부탁드립니다.

감사합니다.

2021-07-27 00:12 UTC, neojjc2 commented
#tag @neojjc2

2021-07-27 00:30 UTC, neojjc2 requested changes
안녕하세요 재영님 😄 

3단계 코드내용 정리 잘 해주셨네요 💯 👍 

소소한 의견 몇 가지 드렸습니다 😄 
한번 확인해주시면 감사하겠습니다 🙇 

그리고 구조 변경 된 부분에 대한 테스트 코드가 하나도 없는데요 😨 
이 부분도 추가 보완 요청 드립니다 🙇 

그리고 다음 PR 주실 때 4단계도 함께 반영해서 요청해주시면 됩니다 😄 

그럼 재 리뷰 요청 기다리고 있겠습니다 😄 🙇

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/Race.java
> +        return new int[]{numOfCar, numOfCycle};
굳이 이렇게 `array`로 변환하여 반환하신 이유가 있을까요?? 🤔 
이렇게 되면 `requestInput`을 호출하는 `RacingCarMain`에서도 이와 같이 
어렵게(?) 값을 꺼내야 합니다 😄 
```java
int numOfCar = raceInfo[0];
int numOfCycle = raceInfo[1];
```
저나 재영님 같은경우 코드 전체를 다 봐서 이해를 할 수 있겠지만 😄 
이 코드를 개선하기 위한 다른 개발자나 동료들이 이 부분을 본다면
`raceInfo`에 `0`번째에는 무슨 값이 들어있는지, `1`번에는 무슨 값이 들어있는지 
더더욱 알 수 없습니다 😨 

차라리 명시적으로 `getNumOfCar()`, `getNumOfCycle()` 두번 호출 하는 편이
가독성 측면에서도 더 괜찮아 보입니다 😄 
이 부분 개선 검토 부탁 드립니다 🙇 

그리고 반환 하실 일이 생기시더라도 `array`보다는 `java`의 좋은 `Collection` 들이 많이 있습니다 😄 
이 부분도 참고해주시면 감사하겠습니다 🙇

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/Race.java
> +            Car car = new Car(1);
`1`만 봐서는 `1`이 무슨 의미인지 알 수 없을 것 같습니다 😄 
매직넘버 추출 부탁 드립니다 🙇 

정리한번 하고 가시면 좋을 것 같아서 도움되실 만한 내용 공유 드립니다 😄 
> https://hoonmaro.tistory.com/44

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/InputView.java
> +    private Scanner sc = new Scanner(System.in);
```suggestion
    private static final Scanner SC = new Scanner(System.in);
```
이 부분도 한번만 초기화 될 수 있도록 정적 상수로 선언 되면 좋을 것 같습니다 😄

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/CarManager.java
> +    public void CanIGo() {
```suggestion
    public void canIGo() {
```
컨벤션 확인 부탁 드립니다 😄

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/CarManager.java
> +            car.MoveForward();
```suggestion
            car.moveForward();
```

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/Car.java
> +    public void MoveForward() {
```suggestion
    public void moveForward() {
```

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/InputView.java
> +    public void inputCarCheck(int numOfCar) {
예외 처리 좋습니다 👍

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/Race.java
> +    public void validInputConfirm() {
`validInputConfirm()`를 호출하기 전까지는 값에 대한 검증이 이뤄지지 않습니다 😄 
값에 대한 검증은 중요한 부분이므로 객체가 생성 되는 시점에 검증이 이뤄져야 더 강한 구속력(?)을 갖게 되는데요 😄 
만약 다른 개발자 분들이나 동료분들이 이 `Race` 객체를 가져다가 사용하면서 해당 부분들을 잊게(?) 된다면
정상동작은 기대하기 어려울 것 같습니다 😄 

이 부분도 한번 개선 검토 해주시면 감사하겠습니다 🙇

2021-07-27 00:30 UTC, neojjc2 commented on src/main/java/step4/Race.java
> +    private CarManager[] carManagers;
전체적으로 `array` 를 사용하여서 `array` 컨트롤을 하기 위해 반드시 `for (int i = 0; ` 등이 반복 되고 있습니다 😄 
물론 `array` 도 나쁘지 않지만 아무래도 `for (int i = 0` 로 제어를 하다보니 반복적으로 `for` 문이 등장하고 
`index`를 잘못 넣거나 하는 사람 실수(?) 등을 유발 할 수도 있습니다 😄 

```suggestion
    private List<CarManager> carManagers
```
와 `for-each`를 이용하여 한번 개선해보시면 좋을 것 같습니다 😄 
이 부분도 검토 부탁 드립니다 🙇

2021-07-27 00:32 UTC, neojjc2 commented
> 이번 pull request는 step4로 제출을 하였지만, step3에 대한 코드를 다시 작성하여 컨펌을 받으려고 합니다.
이전에 보여드렸던 step3 구조가 너무 허접하여, 금일은 데이터 모델링을 어떻게 진행할지 계속해서 생각하고, 책도 찾아보았습니다.
많은 고민을 하여 코드를 작성 하였으며 이전보다는 구조적인 부분에서 많이 좋아진 것 같습니다. (제 개인적인 생각입니다..ㅎ)
컨펌 한번 부탁드립니다.

네 정말 처음보다 많이 정리되고 개선된 흔적이 보여서 
많이 고생시켜드린 것 같아 제가 죄송하네요 😨 
하지만 그만큼 좋아졌습니다 😄 
그리고 4단계 요구사항이 반영 되려면 어쩔 수 없는 과정이기도 하구요 🙇 
다소 어렵고 지치실 수도 있는데 차근 차근 잘 하고 계십니다 😄 
화이팅 입니다 🔥

2021-07-28 13:39 UTC, jaeyoungjang2 commented
안녕하세요 멘토님!!
기존에 pull request가 닫히지 않아서 그대로 여기에 작성합니다.
제가 수정한 커밋들이 지금은 보이지 않는데, github설명을 보니 그대로 이어서 pull request를 작성하면 되는 것 같아
그대로 연결하여 진행하도록 하겠습니다.

말씀해주신 피드백 너무 감사합니다.
모든 피드백이 이해가 갔지만 validInputConfirm()을 객체가 생성할 때 검증을 하라는 것이 처음에는 저에게 와 닿지 않았습니다.
그럴거면 차라리 validInputConfirm() 부분을 input 받을 때 바로 검증하는 것이 더 좋지 않을까 라는 생각이 들었기 때문입니다.
 
조금 더 생각해보니 사용자로 부터 input값을 받는 메소드를 제가 만든 코드가 아닌 다른 사람의 것을 사용하는 경우에
해당  메소드에는 input값을 받기만 하고 validInputCheck를 진행하지 않는다면 코드 검증을 할 수 있는 방법이 없어지기 때문에 객체를 생성하는 시점에서 input값을 확인하는 것이 더 좋다고 말씀하신 것 같다. 라고 파악하면 될까요??

테스트를 작성하는게 뭔가 너무 어색합니다.ㅜㅜ
테스트는 최대한 간단하게 짜라고 하셨는데, 작성을 하다 보니 어느새 본래 코드와 다를바가 없어지고 있어서 당황스러운 상태입니다.
조금 더 살펴보고 또 추가해 보도록 하겠습니다.

감사합니다!

2021-07-29 01:01 UTC, neojjc2 commented
> 안녕하세요 멘토님!!
기존에 pull request가 닫히지 않아서 그대로 여기에 작성합니다.
제가 수정한 커밋들이 지금은 보이지 않는데, github설명을 보니 그대로 이어서 pull request를 작성하면 되는 것 같아
그대로 연결하여 진행하도록 하겠습니다.

네 맞습니다 😄 
이 후 미션 진행하실 때도 `Review Request` 되면 같은 `PR`에 그대로 작업해주시면 됩니다 😄 

> 말씀해주신 피드백 너무 감사합니다.
모든 피드백이 이해가 갔지만 validInputConfirm()을 객체가 생성할 때 검증을 하라는 것이 처음에는 저에게 와 닿지 않았습니다.
그럴거면 차라리 validInputConfirm() 부분을 input 받을 때 바로 검증하는 것이 더 좋지 않을까 라는 생각이 들었기 때문입니다.

> 조금 더 생각해보니 사용자로 부터 input값을 받는 메소드를 제가 만든 코드가 아닌 다른 사람의 것을 사용하는 경우에
해당 메소드에는 input값을 받기만 하고 validInputCheck를 진행하지 않는다면 코드 검증을 할 수 있는 방법이 없어지기 때문에 객체를 생성하는 시점에서 input값을 확인하는 것이 더 좋다고 말씀하신 것 같다. 라고 파악하면 될까요??

네 맞습니다 아주 정확하게 이해하셨어요 😄 
`validate`체크를 해서 통과가 되면 객체가 초기화 되도록 강제한다면 
이후 객체가 가진 값에 대해서 많은 부분 신뢰할 수 있게 됩니다 😄 
잘 이해해 주셨습니다 🙇 

> 테스트를 작성하는게 뭔가 너무 어색합니다.ㅜㅜ
테스트는 최대한 간단하게 짜라고 하셨는데, 작성을 하다 보니 어느새 본래 코드와 다를바가 없어지고 있어서 당황스러운 상태입니다.
조금 더 살펴보고 또 추가해 보도록 하겠습니다.
감사합니다!

테스트를 최대한 간단하게 작성하라의 의미를 다시 잘 생각해보면
**테스트가 최대한 간단하게 작성이 되어야 한다**는 의미이기도 합니다 
그러려면 어떻게 해야 할까요 ?? 😅 
테스트 대상인 객체들이 최대한 테스트가 간단하게 작성 될 수 있도록 
응집되고 메소드 단위도 적절해야 하며 구조도 간결해야 함을 의미합니다 😄 

개인적인 의견을 하나 더 드리자면 
테스트 작성이 어려운 객체일 경우 그 때가 리팩토링의 시점이라고 생각 합니다 😄 

잘 해주고 계시니 너무 좌절하지 마시고
꾸준히 포기만 안하시고 잘 따라와 주시면 됩니다 🙇 
화이팅 입니다 🔥

2021-07-29 01:15 UTC, neojjc2 requested changes
안녕하세요 재영님 🙇 

지난 번 3단계 리팩토링에 이어 추가적으로 4단계 요청사항 구현 잘 해주셨습니다 😄 

그래도 이전 보단 많이 구조가 개선이 되었는데, 
4단계 요구사항에서 조금만 더 다듬어지면 좋을 것 같아서
추가로 의견 더 드렸습니다 🙇 

다소 지치시겠지만, 한번 만 더 확인해주시고
개선 검토 해주시면 감사하겠습니다 🙇 

화이팅 입니다 💪

2021-07-29 01:15 UTC, neojjc2 commented on src/main/java/RacingCarMain.java
> +        Race race = new Race(nameOfCar, numOfCycle);
💯💯💯💯💯
이렇게 함으로써 `nameOfCar`, `numOfCycle` 값이 올바르지 않은 경우
경기 자체를 시작할 수 없게 됐네요 👍

2021-07-29 01:15 UTC, neojjc2 commented on src/main/java/step4/ResultView.java
> +        } else if (carPosition == maxCarPosition) {
### else 예약어를 쓰지 않는다.
* 힌트: if 조건절에서 값을 return하는 방식으로 구현하면 else를 사용하지 않아도 된다.
* else를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.

이 부분 한번 적용시켜 보시는건 어떨까요?? 😄 
그리고 추가적으로 하나 더 의견을 드리자면 우승자를 구하는 로직이 `ResultView`에 있습니다 😄 
만약 콘솔 출력이 아닌 우승자 정보를 어딘가에 저장한다거나 혹은 `html`, `json` 형태로 전달해야 한다면 
자동차 게임과는 상관 없이 계속 이 `ResultView`를 수정하고 사용해야 합니다 
(물론 이번 요구사항은 아닙니다만, 확장성 관점에서 의견 드립니다 😄)
 
그리고 이 `ResultView`가 없이는 자동차 게임의 우승자를 알 수도 없구요 😭 
이 부분 한번 만 더 개선 검토 해주시면 좋을 것 같습니다 😄 🙇

2021-07-29 01:15 UTC, neojjc2 commented on src/test/java/step4/ResultViewTest.java
> +        for (int i = 0; i < carPositions.length; i++) {
고민 하신 부분이 이 부분인 것 같은데 😄

테스트 코드와 원래 코드가 자꾸 닮아간다면 이건 분명
구조적으로 리팩토링을 해야하는 신호이기도 합니다 😄 

테스트는 원래 코드의 부분 부분이 잘 동작하는지를 보기 위함입니다 😄 
반대로 생각해보면 원래 코드가 부분 부분으로 나뉘어져 있지 않다는 의미 이기도 합니다 🙇 

개선 검토 해주시면 감사하겠습니다 😄

2021-07-29 11:24 UTC, jaeyoungjang2 commented
> else 예약어를 쓰지 않는다. 

else 를 쓰게 되면 가독성이 떨어진다고 한다.
힌트에 있는 것 처럼 return을 사용해서 else를 삭제하고 if문을 추가하였습니다. indent가 맞춰지면서 가독성이 좋아졌다는 점은 있지만, 
어떤 점이 더 좋아진 건지는 정확히 모르겠습니다.

> 그리고 추가적으로 하나 더 의견을 드리자면 우승자를 구하는 로직이 ResultView에 있습니다 😄
> 만약 콘솔 출력이 아닌 우승자 정보를 어딘가에 저장한다거나 혹은 html, json 형태로 전달해야 한다면
> 자동차 게임과는 상관 없이 계속 이 ResultView를 수정하고 사용해야 합니다
> (물론 이번 요구사항은 아닙니다만, 확장성 관점에서 의견 드립니다 😄)
> 그리고 이 ResultView가 없이는 자동차 게임의 우승자를 알 수도 없구요 😭
> 이 부분 한번 만 더 개선 검토 해주시면 좋을 것 같습니다 😄 🙇

사실 저도 많이 고민했던 부분입니다.
우승자를 구하는 로직이 race에 들어있는게 구조적으로 더 아름다워 보이긴 했습니다.
그러나 우승자를 구하는 로직까지 race에 들어가면 race 클래스의 덩어리가 너무 커지는 것 같아 무서웠습니다.
그렇다면 그 다음으로 이 로직이 들어가도 어색하지 않을 공간은 어디일까라고 생각하여서 넣은 곳이 resultView 단입니다.
멘토님이 보기에도 제 race 클래스의 무게감이 너무 커 보이지는 않는가요??

그래서 궁금한 점이 있습니다.
지금 제 구조를 봤을때 문제가 있어 보이지는 않은가요??
race 코드를 다시 분리를 시키는게 옳을까요??
멘토님은 레이싱 게임 프로젝트를 하실 때 어떻게 코드를 작성하셨는지 궁금합니다!

항상 감사합니다!!

2021-07-30 01:01 UTC, neojjc2 approved these changes
안녕하세요 재영님 😄 

요청사항 반영 잘해주셨습니다 🙇 

소소한 코멘트 하나 남겼습니다 😄 
한번 확인만 해주시면 감사하겠습니다 🙇 

이만 `merge` 하겠습니다 🙇 
정말 고생 많으셨습니다 😄

2021-07-30 01:01 UTC, neojjc2 commented on src/main/java/step4/Race.java
> +    public void findMaxPositionCarName(String carName, int carPosition) {
개선 잘해주셨습니다 👍 
질문 주신 것 처럼 `Race`가 너무 크다고 느껴지시면 우승자를 구하는 부분을 별도의 객체로 추출하시면 됩니다 😄 
그럼 우승자를 구하는 비즈니스 로직이 변경되더라도 그 부분만 수정하면 되니 
오히려 다른 객체들에 미치는 영향도 줄어드는 효과를 볼 수 있을 것 같네요 😄 
그게 `ResultView`에 있는 것 보다는 훨씬 더 객체들 간에 응집성 면에서 좋다고 생각합니다 🙇 

개인적으로 가독성 개선은 저와 재영님이 아닌
이 코드를 처음 보는
우리가 개발한 코드를 수정할 다른 개발자들을 위한 최소한의 배려라고 생각합니다 
그리고 가독성을 개선하다 보면 자연스럽게 중복적인 부분이 제거가 되고 
그런 부분들이 `method`나 `class`로 추출되다 보면
자연스럽게 테스트 코드도 풍성해질 수 있는 첫 출발점이라고 생각합니다 😄 

이 부분은 개인적인 의견이니 참고만 해주시면 감사하겠습니다 🙇

2021-07-30 01:04 UTC, neojjc2 commented
다른 사람들이 어떻게 작성했는지 참고 하는 것도 좋은 방법 중에 하나 입니다 😄 
이미 작업하고 계신 branch 중에 neojjc2 라는 branch를 가지고 계실텐데요 😄 
거기에 제가 했던 미션이 있습니다 🙇 
그 부분도 한번 참고해주시면 감사하겠습니다 😄

2021-07-30 01:04 UTC, merged