Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2483
Opened 2021-07-27 10:06 UTC by shineoov

3단계 피드백 내용 적용했습니다.

- 불필요한 인스턴스 변수 제거
-> 고민했던 부분이어서 수정하고 지우고 했었는데 얘기해주시고 생각해보니깐 확실히 불필요한 인스턴스 변수였던 것 같네요 ㅠㅠ

4단계도 피드백 부탁드립니다~!

감사합니다 ㅎㅎ

2021-07-27 18:55 UTC, jaeyeonling requested changes
4단계 미션도 잘 구현해주셨어요 👍 
코멘트 남겨두었으니 확인 부탁드려요!

2021-07-27 18:55 UTC, jaeyeonling commented on src/main/java/racingcar/ui/ResultView.java
> +    private static final String LINE_BREAK = "\n";
유닉스 계열에서는 "\n"이지만 윈도우 계열에서는 "\r\n"가 기본인데요.
이러한 문제를 해결하기 위해 `System.lineSeparator()`라는 기능을 지원하고 있습니다!

2021-07-27 18:55 UTC, jaeyeonling commented on src/main/java/racingcar/ui/ResultView.java
> +    private static List<String> getRacingWinner(List<RacingRecord> racingRecords) {
해당 기능은 도메인의 로직으로 보여지는데요!
도메인 로직을 View가 가지고 있으면 어떠한 문제가 있을지 고민 후 도메인으로 옮겨보면 좋겠습니다 :)

2021-07-28 03:13 UTC, shineoov commented on src/main/java/racingcar/ui/ResultView.java
> +    private static final String LINE_BREAK = "\n";
감사합니다~!

2021-07-28 03:14 UTC, shineoov commented on src/main/java/racingcar/ui/ResultView.java
> +    private static List<String> getRacingWinner(List<RacingRecord> racingRecords) {
앗 그러네요 ㅠㅠ
고민 좀 해보고 다시 PR 드리겠습니다!

2021-07-28 09:01 UTC, shineoov commented
우승자 구하는 로직을 뷰에서 위치를 변경하였고 마지막 자동차 경주 정보를 가져오는 부분도 메인 메소드에 있어서 위치를 변경했습니다. 

우승자 구하는 로직 위치를 RacingRecord(경주 기록) 에  static method로 옮기긴 했는데, 고민하고 있는 부분이
RacingRecord 받아 가공해서 리턴해주는 역활만 하는 새로운 클래스를 만들까 고민하고 있습니다. 

``` 
// 새로운 클래스 예시
public class RacingRecordManager {

    // 우승한 자동차
    public static List<String> getRacingWinner(List<List<RacingRecord>> racingRecords) {
        return null;
    }

    // 우승하지 못한 자동차
    public static List<String> getRacingLoser(List<List<RacingRecord>> racingRecords) {
        return null;
    }
    // 등등
}
```

제 생각에는 우승자만 구해야 한다면 RacingRecord 에  우승자 가져오는  static method 로 추가해도 나쁘지 않을 거 같고
꼴찌를 구해야하는등  추가기능이 필요하다면 새로운 클래스로 분리하는게  낫겠다고 생각이 드는데요. 
리뷰어님 생각이 궁금합니다.


감사합니다~!

2021-07-28 16:04 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
질문주신 내용 코멘트로 답변드렸으니 확인 부탁드리고 다음 단계에서 반영해주세요 :)

2021-07-28 16:04 UTC, jaeyeonling commented on src/main/java/racingcar/ui/ResultView.java
> +    private static void showRacingWinner(List<List<RacingRecord>> racingRecords) {
Q. 
우승자 구하는 로직을 뷰에서 위치를 변경하였고 마지막 자동차 경주 정보를 가져오는 부분도 메인 메소드에 있어서 위치를 변경했습니다.

우승자 구하는 로직 위치를 RacingRecord(경주 기록) 에 static method로 옮기긴 했는데, 고민하고 있는 부분이
RacingRecord 받아 가공해서 리턴해주는 역활만 하는 새로운 클래스를 만들까 고민하고 있습니다.

제 생각에는 우승자만 구해야 한다면 RacingRecord 에 우승자 가져오는  static method 로 추가해도 나쁘지 않을 거 같고
꼴찌를 구해야하는등 추가기능이 필요하다면 새로운 클래스로 분리하는게  낫겠다고 생각이 드는데요.
리뷰어님 생각이 궁금합니다.

A. 
제 생각을 말씀드리자면..!
아직 충분한 역할이 없다고 생각하여 클래스 분리보단 static class 분리를 우선으로 생각하신 것 같은데요
우승자를 구하는 것으로 충분한 역할을 가진다 생각하기도 하고, `List<List<RacingRecord>>` 와 같이 컬렉션이 중첩될 경우 가독성이 떨어지고 응집도가 떨어진다는 문제가 있기 때문에 해당 부분을 별도의 클래스로 분리하는 것이 좋은 방법이라 생각이 듭니다 ㅎㅎ

2021-07-28 16:04 UTC, merged