[Step3] 자동차 경주
next-step/java-racingcar pull request #2492
Opened 2021-07-27 15:18 UTC by idealbin

안녕하세요 리뷰어님!

이번 미션을 진행하다가 궁금한 점이 생겼는데요~
자동차 경주 게임에 대한 테스트 코드는 어떻게 작성해야 좋을까요?
게임 결과 예측이 어려워 테스트 코드 작성에 어려움이 있어 조언을 얻고자 합니다.

항상 좋은 리뷰 감사합니다! 😄 
무더위 조심하세요~ 🧊 🍉 🍦

2021-07-28 11:11 UTC, dbeod2 requested changes
안녕하세요. 안빈님! 

자동차 경주 시작해주셨네요!!! 👏🏻👏🏻👏🏻
코멘트로 질문 주신 부분은 해당 메서드쪽에 코멘트 달아두었습니다. 
그리고 몇가지 코멘트 남겨둔 부분이 있는데요. 
확인 해보시고 궁금하시거나 의견나누고 싶으신 부분이 있으시면 DM편하게 주세요 :)

2021-07-28 11:11 UTC, dbeod2 commented on src/main/java/racingcargame/Client.java
> +    }
Scanner 사용 후 종료시 scanner.close(); 를 선언해 암묵적으로 연결을 끊어주어야 합니다.
나중에 리소스 접근이 불가능하거나 connection pool이 꽉 차서 접근이 안되는 경우가 생길 수 있습니다.
그러하므로 I/O사용시에는 연결에 대해 확실하게 끊어줘야 합니다 🙂

2021-07-28 11:11 UTC, dbeod2 commented on src/main/java/racingcargame/RacingCarGame.java
> +    private ResultView resultView = new ResultView();
프러덕션 코드와 ui코드는 분리가 되어야합니다 ~ 
RacingCarGame에 ResultView코드를 분리해 보시는건 어떠실까요?🤔

2021-07-28 11:11 UTC, dbeod2 commented on src/main/java/racingcargame/RacingCarGame.java
> +    public void startGame(int car, int count) {
질문주신 메서드가 **startGame** 메서드네요! 

제가 봤을때 현재 한번에 두가지 일을 하는 것으로보여집니다. 

일단 createCars라는 메서드와 이중for문을 돌아서 결과값을 찍는 로직부터 분리해보시고,
도메인 단위로 테스트를 진행해보면 좋을 것 같습니다. 

예를 들자면 
RacingCar 도메인에서 해야하는 역할을 무엇인지 고민해보시고 구현해 보시는건 어떨까요? 
그러면 자연스럽게 RacingCar도메인 테스트를 작성하시게 될 것같으며, 고민하셨던 부분이 해소 될 것 같습니다!

2021-07-31 06:10 UTC, dbeod2 requested changes
안녕하세요 안빈님! 

3단계 자동차 경주 미션 피드백 적용 잘 해주셨는데요
몇가지 보완되면 좋을 것 같아서 코멘트 드렸습니다. 🙇🏻‍♀️
확인 부탁드리며, 궁금한 부분있으시면 편하게 DM 주세요! 

리뷰 재요청 기다리겠습니다! 🏎🏎🏎

2021-07-31 06:10 UTC, dbeod2 commented on src/main/java/racingcargame/Client.java
> +        inputView.scanner.close();
피드백 반영 👏🏻

2021-07-31 06:10 UTC, dbeod2 commented on src/main/java/racingcargame/RacingCar.java
> +    private ResultView resultView = new ResultView();
resultView와 프로덕션코드를 분리해보시는건 어떨까요? 
도메인에 ui코드가 함께있으면 단일책임원칙에 위배가 됩니다 :-) 

현재는 racingCar에서 움직임을 찍는 부분이 프러덕션 코드와 함께 섞여있습니다.
racingCar에 역할과 책임을 한번 생각해보시고 구현해 보시는 것을 추천드립니다!

2021-07-31 06:10 UTC, dbeod2 commented on src/main/java/racingcargame/RacingCarGame.java
> +    private int car, count = 0;
변수 선언시 같은 int 형태 변수라도 각각 선언해주는게 가독성에 좋을 것 같습니다 :-)

2021-07-31 06:10 UTC, dbeod2 commented on src/main/java/racingcargame/RandomNumberOption.java
> +        return random.nextInt(10);
숫자10도 의미있게 상수치환해주는건 어떨까요?.? 
이전 코멘트를 참고해주세요! 
[매직넘버 comment](https://github.com/next-step/java-racingcar/pull/2492#discussion_r678179174)

2021-07-31 06:10 UTC, dbeod2 commented on src/test/java/racingcargame/RacingCarTest.java
> +public class RacingCarTest {
테스트가 좀 부족한것 같아요! 🥲
경계값 테스트를 통해 더 많은 값에 대해 테스트 해보시는건 어떨지 의견드립니다! 
참고 링크 전달드려요! 
[경계값테스트](https://testmanager.tistory.com/200)

2021-08-01 08:52 UTC, idealbin commented on src/main/java/racingcargame/RacingCarGame.java
> +    public void startGame(int car, int count) {
말씀해주신대로 메소드가 두가지 일을 하는 것 같아서 분리하였습니다.

2021-08-01 09:03 UTC, idealbin commented
리뷰어님 안녕하세요~😄 
항상 좋은 리뷰 감사합니다. 👍 

다름이 아니라 주신 리뷰중에 궁금한 점이 있어 코멘트 드립니다.
https://github.com/next-step/java-racingcar/pull/2492#discussion_r680314535

이부분이 말씀해주신대로 단일 책임의 원칙에 위배는 된다고 생각하지만,
또 한편으로는 RacingCarGame은 게임을 중재하는 책임을 가진 컨트롤러라고 생각하면서 설계를 하였기에
RacingCarGame은 View와의 의존성을 가질 수 도 있다고 생각하는데요.
이에 대해서 리뷰어님의 의견이 궁금합니다.

또한 리뷰어님께서 말씀해주신 책임의 범주는 어디까지로 정의해야하는지도 함께 의견을 주시면 감사하겠습니다.

마지막으로 혹시 주시는 답변에 대한 리팩토링은 다음 단계 하면서 함께 진행해봐도 될까요?

감사합니다. 😄 😄

2021-08-02 02:15 UTC, dbeod2 approved these changes
안녕하세요 안빈님! 
피드백 잘 반영해주신 것 같아요! 👏🏻

질문에 대한 답변은 코멘트에 따로 달아드렸습니다! 

피드백 잘 반영해주셔서! 미션3단계는 여기서 머지하겠습니다. 

다음미션을 진행해주세요!

2021-08-02 02:15 UTC, dbeod2 commented on src/main/java/racingcargame/ResultView.java
> +           System.out.println(convertDistanceToLine(car.getDistance()));
아래와 같이 가독성 좋게 표현해보시는건 어떨까용?
```suggestion
           String line = convertDistanceToLine(car.getDistance());
           System.out.println(line);
```

2021-08-02 02:15 UTC, dbeod2 commented on src/main/java/racingcargame/RacingCar.java
> +public class RacingCar {
Q1.
리뷰에서 말씀해주신 책임의 범주는 어디까지로 정의해야 할까요?
> 제 사견으로는..! 
도메인 설계를 할 때, 도메인 하나를 숲이라 생각해보시고, 나머지 로직을 나무라고 생각해보세요! 
나무도 각각의 역할이 다를 수 있거든요 :-) 그 역할들을 쪼개다보면 도메인 별로 어떤 책임을 가지고 가야하는지 알 수 있을 거에요! 제가 말씀드렸던 부분은 RacingCar도메인은 RacingCar의 이동에 대한 책임만 가지고 가도 된다고 생각했고, 그안에 view로직이 포함되어 있어서 분리해달라고 말씀드린 부분입니다 :-)   

Q2.
말씀해주신대로 도메인-뷰 역할을 보면 단일 책임의 원칙에 위배는 된다고 생각하지만,
한편으로는 RacingCarGame은 게임을 중재하는 책임을 가진 컨트롤러라고 생각하면서 설계를 하였기에
RacingCarGame은 View와의 의존성을 가질 수 도 있지 않을까 생각했습니다.
이에 대해서 리뷰어님의 의견이 궁금합니다.
> 넵  안빈님께 리뷰드린 부분은 RacingCar도메인에 ResultView 로직이 포함되어있어서 전달드린부분이며, RacingcarGame 도메인이 컨트롤러라고 생각한다면 view와의 의존성을 가질 수 있지만 직접적으로 의존하지 않게하려면 dto를 활용해보시는게 어떨지 의견드립니다!

2021-08-02 02:15 UTC, merged