Step3 - 자동차 경주 리뷰 요청드립니다.
next-step/java-racingcar pull request #2498
Opened 2021-07-28 01:13 UTC by holeman79

자동차 경주 리뷰 요청드립니다.

감사합니다.

2021-07-28 16:19 UTC, bass84 requested changes
원진님 안녕하세요~! 3단계 작성하시느라 수고 많으셨습니다!
고민하신 흔적이 많이 느껴집니다.
클래스 별로 역할에 대한 분리가 잘 되어있네요~!
몇몇 작게 수정하셨으면 하는 부분들을 정리했고요,
질문 드린 것도 있는데 제가 특정 정답을 듣고자 해서 드린 질문은 아니고 순수하게 원진님의 의견이나 생각이 궁금해서 드린 질문이니 답변해주시면 감사하겠습니다.

수정하고 답변 남겨주신 후 다시 PR 주세요~!
화이팅입니다!!!

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/MovableStrategy.java
> +    boolean move();
boolean 컨벤션에 맞는 메서드명으로 만들어주시면 더 좋을 것 같아요.^^

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/Position.java
> +    public Position(int position) {
이 생성자는 내부에서만 쓰이는데 `public`으로 공개할 필요가 없어 보입니다. 오히려 외부로 공개하면 0보다 작은 값을 넣어서 호출하는 경우도 발생할 수 있으니 `private`으로 감춰주는 것이 오류 방지 차원에서도 더 좋을 것 같네요.

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/Position.java
> +    public Position move() {
불변객체로 만들고자 이런 생각하신 점 매우 좋습니다. 다만, 이미 생성자로 매개변수를 받고있고 그 외 다른 방식으로 이 객체를 조작할 방법은 없기 때문에 꼭 필요할 것 같지는 않습니다. 그리고 좀 더 방어적으로 해서 position에 final 키워드까지 했으면 더 좋았겠다는 생각도 듭니다.^^

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +        checkGreaterThanZero(roundCount);
1. carCount와 roundCount 값은 이 메서드를 호출하기 전에 이미 유효성 체크를 했습니다. 그럼에도 불구하고 유효성 체크하는 로직이 또 있네요. 이렇게 해야 할 이유가 있을까요? 만약 있다고 생각하시면 왜 그러신지 의견을 들어보고 싶어요.^^
2. roundCount만 체크하시는 이유가 있으신가요?

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private void checkGreaterThanZero(int roundCount) {
어떻게 보면 InputView에 있는 유효성 체크의 로직과 동일하다고 볼 수 있는데 동일한 체크 로직이 여기저기 나눠져 있는 것보다 한 곳에만 있으면 더 좋지 않을까요?

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +        }
이왕이면 java8 부터 등장한 Stream을 이용해서 생성해주시면 좋을 것 같아요.^^

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +    public void race(MovableStrategy movableStrategy) {
`MovableStrategy` 인스턴스를 현재는 Main에서 생성한 후에 매개변수로 받아서 실행하고 계시는데, 생성자에서 받아서 멤버변수로 사용하면 어떨까요?

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/view/InputView.java
> +    public static int receiveRoundCount() {
위의 `receiveCarCount()` 메서드와 마찬가지로 인상적입니다. 한 가지 아쉬운 점은 `receiveCarCount()` 메서드와 다른 점은 질의내용 뿐입니다. 어떻게 보면 동일한 내용의 메서드가 두개 있는 것 같다는 점인데요, 이것을 하나로 줄여보면 어떨까요?^^

2021-07-28 16:19 UTC, bass84 commented on src/main/java/racingcar/view/ResultView.java
> +    private static void print(int position) {
위의 메서드와 네이밍을 동일하게 하신 이유는 오버로딩을 생각하셔서 그렇게 하신 건가요?^^

2021-07-28 16:19 UTC, bass84 commented on src/main/java/step2/OperatorType.java
> +    private IntBinaryOperator operator;
이전에 코멘트 드렸던 건데 수정해서 반영해주셨네요~! 👍

2021-07-29 00:23 UTC, holeman79 commented on src/main/java/racingcar/domain/MovableStrategy.java
> +    boolean move();
https://softwareengineering.stackexchange.com/questions/348649/naming-of-bool-methods-is-vs-can-vs

2021-07-29 00:23 UTC, holeman79 commented on src/main/java/racingcar/domain/MovableStrategy.java
> +    boolean move();
https://softwareengineering.stackexchange.com/questions/348649/naming-of-bool-methods-is-vs-can-vs

2021-07-29 02:04 UTC, holeman79 commented on src/main/java/racingcar/domain/Position.java
> +    public Position(int position) {
테스트코드를 위해 private -> default 로 변경했는데 이에 대해서 어떻게 생각하시는지 궁금합니다. 

테스트를 위해 접근제어자를 default로 지정하는 경우를 종종 볼 수 있는데 테스트를 위해 이정도는 허용해도 좋을지, 아니면 테스트코드는 프로덕션 코드에 절대 영향을 주면 안되는지 리뷰어님의 생각이 궁금합니다.

2021-07-29 02:17 UTC, holeman79 commented on src/main/java/racingcar/domain/Position.java
> +    public Position move() {
위 피드백 적용하여 Position 클래스 move 메소드를 없애고 Car 클래스 move 메소드를 수정 하였습니다.

2021-07-29 04:38 UTC, holeman79 commented on src/main/java/racingcar/domain/RacingGame.java
> +        checkGreaterThanZero(roundCount);
1. 보통 UI에서 변수 타입과 Null, Empty, 패턴, 자리수 등을 체크하고 백엔드에서 비즈니스 검증로직을 체크하고 있는데 여기서 InputView의 유효성 체크를 좀 과하게 한 듯 하네요. 타입만 체크하도록 다시 수정하는게 나을 듯 싶습니다.
2.  Cars 객체 생성 할 때 carCount를 체크하기 때문에 이 곳에선 roundCount만 체크하였습니다.

2021-07-29 06:38 UTC, holeman79 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private void checkGreaterThanZero(int roundCount) {
위에서 말씀드렸듯이 UI에서는 Integer 타입 체크만하고 도메인에서 유효성 체크하도록 분리하겠습니다.

2021-07-29 07:09 UTC, holeman79 commented on src/main/java/racingcar/domain/RacingGame.java
> +    public void race(MovableStrategy movableStrategy) {
전략패턴을 사용할 때 고민하는 부분이 Strategy 인스턴스를 멤버변수로 보관할 지, 아니면 메소드 파라미터로 전달받아서 수행할 지 고민이 됩니다. 제가 내린 판단은 클래스 내에 Strategy 인스턴스를 사용하는 부분이 한 곳이면 메소드 파라미터로 수행하고 두 곳 이상이면 멤버변수로 받는 걸로 생각을 했는데 리뷰어님의 생각은 멤버변수로 받는 것이 더 적절한 것으로 생각하시나요?

2021-07-29 07:37 UTC, holeman79 commented on src/main/java/racingcar/view/ResultView.java
> +    private static void print(int position) {
음 아닙니다. 조금 더 상세하게 메소드 명을 정했어야 했네요. 수정해서 반영하겠습니다.

2021-07-29 14:28 UTC, bass84 commented on src/main/java/racingcar/domain/Position.java
> +    public Position(int position) {
테스트를 위해서 접근제한자를 변경하는 것은 원칙적으로 봤을 때 좋지 못한 방식이라고 볼 수 있습니다. public을 통해서 테스트를 하는 것이 정석이긴 합니다.
하지만, private 테스트가 꼭 필요하다면 설계의 문제일 수도 있습니다. 예를 들어, 새로운 클래스를 만들어 그 클래스의 public 메서드로 분리가 되었어야 했을 수도 있다는 거죠.
테스트 코드가 프로덕션 코드에 영향을 준다는 의미가 여러 의미가 있을 수 있겠지만, 원진님께서 물어보신 의미로라면 영향을 주지 않는 것이 맞다고 봅니다.

2021-07-29 14:38 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +        checkGreaterThanZero(roundCount);
1. 제 생각엔 여기에도 있는 게 맞는 것 같습니다. InputView와 RacingGame은 `입력을 받아서 RacingGame에 그 입력값을 사용한다`는 측면에서는 연결되어 있지만, 사실 둘은 역할만 놓고 봤을 때는 관련이 없는 객체들입니다. 예를 들어, RacingGame의 생성자는 매개변수로 carCount, roundCount를 받고 public으로 선언되어 있기 때문에 꼭 InputView를 통해 입력받았던 값만 넣는다는 보장이 없습니다. 그렇다면 유효성체크 되지 않은 값이 들어올 수도 있다는 의미가 됩니다. 그리고 생성자에서 유효성체크가 되지 않는다면, 실행중에 오류를 발생시킬 수 있는 것이죠.
2. 코드를 실행하면, 어떤 값이 다른 메서드를 호출하면서 매개변수로 넘어가는 과정들이 있는데 그 가장 마지막 단계에서 체크되는 것이 좋다고 생각하는 편입니다. 그런 면에서 좋은 체크 방식인 것 같습니다.^^

2021-07-29 14:45 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +    public void race(MovableStrategy movableStrategy) {
전략패턴은 실행 중에 그 전략이 바뀜을 의미합니다. 그래서 외부에서 받아서 실시간으로 변경 가능하게 하는 것이 맞을 것 같습니다. 다만, 현재 경우에는
1. 전략패턴을 main method에서 생성해서 고정하고 더 이상의 변화가 없다는 점
2. 정확히는 이 전략이라는 것이 바뀌거나 새로운 것을 추가한다는 가정이 없다는 점
을 생각했을 때 전략패턴을 써야 할 이유가 있을까 하는 생각이 들고, 동시에 어차피 지금처럼 사용할 것이라면 인스턴스 변수로 고정시켜서 사용해도 되지 않을까 라는 생각을 합니다.^^

2021-07-29 15:02 UTC, bass84 requested changes
원진님 수고 많으셨습니다~!

저에게 다시 질문 주신 것들에 대해서는 답변을 드렸으니 참고해주시고요,
전체적으로 잘 작성해주셨습니다!! 👍 👍 👍  소소한 몇 가지 수정했으면 하는 내용을 코멘트로 드렸으니 참고해서 수정해주세요!

얼른 마무리 하시고 4단계로 넘어가시죠!
화이팅!! 🔥 🔥 🔥

2021-07-29 15:02 UTC, bass84 commented on src/main/java/racingcar/domain/RacingGame.java
> +    public Cars getCars() {
RacingGame에서 Cars를 반환한다... 뭔가 조금 이상하다는 느낌 안 드시나요?^^ 만약 main method에서 Cars를 생성을 하고 그 값을 RacingGame에서 필요로 할 때 매개변수로 넣어준다면 initCars 메서드도 필요 없어지고 getCars 메서드도 필요 없어질 것 같아요. RacingGame에서 Cars의 상태를 가지고 있을 필요가 있겠냐는 질문을 위에서 드렸는데 그것에 대한 저의 답변이기도 합니다.^^

2021-07-30 12:12 UTC, holeman79 commented on src/main/java/racingcar/domain/RacingGame.java
> +    public void race() {
Cars 객체 내에서 car들에게 명령을 내린다는 뜻으로 이해했는데 잘 이해한게 맞을까요?

2021-07-30 17:11 UTC, bass84 approved these changes
원진님 작성하시느라 수고하셨습니다~!

코멘트 드렸던 부분 많이 반영해주셨네요.
몇몇 조금 생각해보셨으면 하는 내용을 언급 드렸는데 한번 생각해보시면 좋을 것 같아요.
merge 하겠습니다. 수고하셨어요!! 👍 👍 👍 
4단계 진행해주세요~!^^

2021-07-30 17:11 UTC, bass84 commented on src/main/java/Main.java
> +        List<Car> collect = IntStream.range(0, carCount).
변수명이 collect으로 된 건 조금 아쉽네요.^^;

2021-07-30 17:11 UTC, bass84 commented on src/main/java/Main.java
> +        }
이 while 루프를 제거해서 racingGame은 게임만 진행하도록 하고 그것이 끝나면 그 상태값을 이용해서 ResultView에서 출력을 하는 방식으로 바뀌면 좋을 것 같습니다. 예를 들면,
```
Result result = racingGame.race(cars);
ResultView.print(result);
```
같은 방식입니다.
지금 원진님께서 만드신 코드는 racingGame에 ResultView가 종속적으로 실행되는 형태라서요.

2021-07-30 17:11 UTC, merged