Step4 - 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2506
Opened 2021-07-28 09:35 UTC by ChangSubKwak

안녕하세요. 김선동 리뷰어님!
이번에는 조금 오래 걸렸습니다.
리뷰 잘 부탁드릴께요.
항상 좋은 리뷰에 감사드립니다.

2021-07-28 14:27 UTC, ksundong requested changes
안녕하세요. 창섭님! 😊

4단계 미션도 잘 진행해주셨네요!! 👏 👏 👏
질문드린 내용이 조금 있어서 변경요청을 드려요.

사용하지 않는 생성자는 제거해주세요!

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/strategy/RandomlyMovableStrategy.java
> +    public static RandomlyMovableStrategy initRandomSeed(Random random) {
왜 RandomSeed라는 이름을 가졌을까요?

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/strategy/RandomlyMovableStrategy.java
> +        return false;
if문이 없어도 되겠죠?

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/view/InputView.java
>  	}
입력값에 대한 검증은 하지 않나요?

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/view/InputView.java
> +	public String[] inputCarNameList() {
왜 `List`라는 이름을 지어주셨는지 궁금합니다.

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/view/ResultView.java
> +		System.out.println(winnersString.substring(1, winnersString.length() - 1) + OUTPUT_WINNER_STATEMENT);
1이라는 리터럴이 그냥 들어가 있네요? 1은 무슨의미인가요? 상수로 추출해봅시다.

2021-07-28 14:27 UTC, ksundong commented on src/test/java/racingcar/RacingCarTest.java
> +		});
이 부분은 어떻게 하면 효과적으로 테스트 할 수 있을까요?

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/exception/OverFiveCarNameException.java
> +    }
예외에 구체적인 정보가 들어가버렸습니다.
만약 6자로 제한이 바뀌면 클래스가 바뀌어야 합니다.

2021-07-28 14:27 UTC, ksundong commented on src/main/java/racingcar/model/RacingCars.java
>  			});
```java
racingCars.forEach(RacingCar::forward);
```

로 줄일 수 있고, 해당부분은 테스트가 되지 않은 것으로 보이네요~

2021-07-28 14:48 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +		this.movableStrategy = new RandomlyMovableStrategy();
Default값으로 둔 것인데요.
커멘트를 주신 이유는 의도하지 않은 로직 수행이 될 수 있어서 그런 걸까요?

2021-07-28 15:00 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +	private static final String DEFAULT_CAR_NAME = "empty";
넵, 알겠습니다.

2021-07-28 15:01 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +		}
리뷰어님, 칭찬과 채찍을 잘 사용하시는 것 같습니다.
감사합니다.

2021-07-28 15:03 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +		this.movableStrategy = movableStrategy;
넵, 알겠습니다. this함수를 이용하도록 해보겠습니다.

2021-07-28 15:15 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +		return new String(new char[this.position]).replace("\0", "-");
넵, 간편한게 다 좋은 것은 아니었군요.
StringBuilder로 구현하도록 할께요.

2021-07-28 15:17 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
>  	}
기본적인 것 지키는 것이 버릇들 때까지는 지키기 어려운 것 같아요.
바로 수정하였습니다.

2021-07-28 15:22 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
> +		stream = racingCars.stream();
넵, 알겠습니다. 바로 수정했습니다.

2021-07-28 15:23 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
> +		List<String> winners = stream.filter(car -> car.getPosition() == maxPosition).map(RacingCar::getCarName).collect(Collectors.toList());
네, 바로 개행하였습니다.

2021-07-28 15:46 UTC, ChangSubKwak commented on src/main/java/racingcar/strategy/RandomlyMovableStrategy.java
> +    public static RandomlyMovableStrategy initRandomSeed(Random random) {
테스트를 위해, 랜덤값을 강제로 원하는 값을 가져오기 위하여 사용한 함수인데, 랜덤값 **생성**을 위한 원천값인 Seed라는 단어를 "원하는 값을 **생성**"하는 뜻으로 해석하여 명명을 해버렸네요. "생성"이라는 공통점이 있어서 혼란이 있었던 것 같습니다. 
그리고 이함수는 테스트시에만 사용하기에 테스트 클래스로 옮겼습니다.

2021-07-28 16:24 UTC, ChangSubKwak commented on src/main/java/racingcar/strategy/RandomlyMovableStrategy.java
> +        return false;
넵, 맞습니다.

2021-07-28 16:26 UTC, ChangSubKwak commented on src/main/java/racingcar/view/InputView.java
> +	public String[] inputCarNameList() {
네, 자신에게 묻고 싶습니다. ㅜ
변수 명명의 일관성을 가지도록 inputCarNames로 바꾸었습니다.

2021-07-28 18:16 UTC, ChangSubKwak commented on src/main/java/racingcar/strategy/AlwaysMovableStrategy.java
> +}
이것을 람다식으로 바꾸는 것을 고민 해봤는데요. 
BooleanSupplier 을 @FunctionalInterface으로 interface 선언한 뒤에, 이것을 이용하면 
isMovable 함수는 다음과 같이 쓸 수 있게 되었습니다.
public BooleanSupplier isMovable = () -> true;

대신 함수를 담는 변수로 변경되면서 @Override를 할 수 없게 되었고 전략 패턴을 사용한 의존성 주입을 할 수 없게 되어 버렸습니다. 

힌트라도 주시면 한 번 해보도록 하겠습니다.

2021-07-28 18:28 UTC, ChangSubKwak commented on src/main/java/racingcar/view/InputView.java
>  	}
숫자을 입력받아야 하는데 문자를 입력받으면 InputMismatchException 를 던질때, 이것을 잡아서 예외처리 해야 하는 것일까요?

2021-07-28 18:29 UTC, ChangSubKwak commented on src/main/java/racingcar/view/ResultView.java
> +		System.out.println(winnersString.substring(1, winnersString.length() - 1) + OUTPUT_WINNER_STATEMENT);
넵, 알겠습니다.

2021-07-28 18:39 UTC, ChangSubKwak commented on src/main/java/racingcar/exception/OverFiveCarNameException.java
> +    }
예외 이름이 구체적이라는 말씀이신거죠?
그렇다면 OverFiveCarNameException 대신 기본 제공되는 IllegalArgumentException쓰는게 좋을까요?
아니면 6자제한 조건을 지킨다면 argException 정도로 하면 될까요?

2021-07-28 18:56 UTC, ChangSubKwak commented on src/test/java/racingcar/RacingCarTest.java
> +		});
제가 생각한 것이 맞는지는 모르겠는데, 이 테스트는 RacingCarsTest에서 RacingCars의 생성자를 입력 받으면 @ParameterizedTest를 쓰지 않고 테스트를 할 수 있을 것 같습니다. 그리고 람다식도 컬리 브래킷을 제거까지 의도하신 것이 아닌가 생각합니다.

2021-07-28 19:41 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
>  			});
줄일 수 있는 부분을 알려주셔서 감사합니다.
그리고 forwardCars 테스트 케이스 추가하였습니다.

2021-07-29 00:09 UTC, ksundong commented on src/test/java/racingcar/RacingCarTest.java
> +		});
예외가 발생하지 않는다는 것을 테스트하기 보단 정상적으로 생성되었는지 확인하는 테스트가 더 적절하지 않을까요?

2021-07-29 09:03 UTC, ksundong commented on src/main/java/racingcar/model/RacingCar.java
> +		this.movableStrategy = new RandomlyMovableStrategy();
음 그냥 궁금해서 여쭤봤습니다! ㅎㅎ

2021-07-29 09:05 UTC, ksundong commented on src/main/java/racingcar/model/RacingCar.java
> +		this.movableStrategy = movableStrategy;
넵 알겠습니다!

2021-07-29 09:05 UTC, ksundong commented on src/main/java/racingcar/model/RacingCar.java
> +		return new String(new char[this.position]).replace("\0", "-");
간편하게 보이지만, 한 줄일 뿐 생각할 구간이 더 많은 것 같아요~

2021-07-29 09:06 UTC, ksundong commented on src/main/java/racingcar/view/InputView.java
> +	public String[] inputCarNameList() {
넵!

2021-07-29 09:06 UTC, ksundong commented on src/main/java/racingcar/exception/OverFiveCarNameException.java
> +    }
NameValidationException 정도로 일반적인 이름을 주면 어떨까 싶네요!

2021-07-29 09:21 UTC, ksundong approved these changes
안녕하세요. 창섭님! 😊

4단계 미션 피드백도 잘 진행해주셨네요!! 👏 👏 👏
고생많으셨습니다.

간단한 피드백을 남겨드렸습니다. 확인해주세요!
이제 다음단계를 진행해봅시다~ 🚗

궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-29 09:21 UTC, ksundong commented on src/main/java/racingcar/model/RacingCar.java
> +	public String carName;
항상 상태는 가시성을 private 정도로 줄여주세요.
이는 캡슐화를 지키는 가장 첫번째 방법입니다!

2021-07-29 09:21 UTC, ksundong commented on src/main/java/racingcar/model/RacingCar.java
>  	}
메서드가 생성자보다 위에 위치하고 있습니다!
위치를 조정해주시는게 좋을 것 같아요~

2021-07-29 09:21 UTC, ksundong commented on src/main/java/racingcar/model/RacingCars.java
> +		return stream.map(RacingCar::getPosition)
한 줄로 작성해주세요~

2021-07-29 09:21 UTC, ksundong commented on src/main/java/racingcar/model/RacingCars.java
> +		List<String> winners = stream.filter(car -> car.getPosition() == getRacingCarsMaxPosition())
여기도 마찬가지로 한 줄로 작성해주세요~
굳이 stream을 변수로 뺄 필요는 없습니다~

2021-07-29 09:21 UTC, ksundong commented on src/main/java/racingcar/strategy/AlwaysMovableStrategy.java
> +}
`Functional Interface`는 암묵적으로 `@Override`가 아닐까요?
또한, 의존성 주입이 왜 안되는지 의문이 드네요!

```java
racingCar = new RacingCar("chang", () -> true);
```

재사용을 위해서라면 

```java
MovableStrategy alwaysMovableStrategy = () -> true;
```
로 해결이 될겁니다!

2021-07-29 09:21 UTC, ksundong commented on src/test/java/racingcar/RacingCarTest.java
> +	}
이 정적 메서드가 왜 필요했을까요? 궁금하네요!

2021-07-29 09:21 UTC, ksundong commented on src/test/java/racingcar/RacingCarTest.java
> +	// }
사용되지 않는 코드는 제거해주세요!

2021-07-29 09:21 UTC, merged

2021-07-29 11:15 UTC, ChangSubKwak commented on src/main/java/racingcar/exception/OverFiveCarNameException.java
> +    }
수정하였습니다.

2021-07-29 11:17 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +	public String carName;
기본적인 것을 못 지키는 건 조급함이 있어서 그런 것 같습니다.
마음을 다시 가다듬고 코드를 보도록 해보겠습니다.

2021-07-29 11:19 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
>  	}
이것도 기본적인 것이네요. ㅠ
PR전에 컨벤션 체크를 해봐야 겠습니다.

2021-07-29 11:21 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
> +		return stream.map(RacingCar::getPosition)
넵, 수정하였습니다.

2021-07-29 11:21 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCars.java
> +		List<String> winners = stream.filter(car -> car.getPosition() == getRacingCarsMaxPosition())
넵, 수정하였습니다.

2021-07-29 11:22 UTC, ChangSubKwak commented on src/test/java/racingcar/RacingCarTest.java
> +	// }
네, 제거 하였습니다.

2021-07-29 11:31 UTC, ChangSubKwak commented on src/main/java/racingcar/model/RacingCar.java
> +		return new String(new char[this.position]).replace("\0", "-");
동의해요. ^^

2021-07-29 11:35 UTC, ChangSubKwak commented on src/test/java/racingcar/RacingCarTest.java
> +		});
네, 아직 테스트 코드를 작성하는 경험이 없어서, 테스트의 핵심 파악이 부족한가 봅니다.
이 부분 정상적으로 생성되었는지 확인하도록 변경하였습니다.

2021-07-29 11:38 UTC, ChangSubKwak commented on src/test/java/racingcar/RacingCarTest.java
> +	}
그러게 말입니다. 야심한 밤, 리뷰요청을 목표로 하다 보니 오버페이스 했나 봅니다.
정적 메서드 바로 삭제하고, 메서드가 호출된 부분을 생성자로 대체하였습니다.

2021-07-29 11:59 UTC, ChangSubKwak commented on src/main/java/racingcar/strategy/AlwaysMovableStrategy.java
> +}
네, 힌트를 주셔서, 해결을 했습니다. 감사합니다. 👍 
저는 AlwaysMovableStrategy 클래스를 유지할려고만 했어요. 그 안에서 isMovable함수를 람다식으로 바꿀려고만 했습니다.  문법적으로 되지 않아서,  AlwaysMovableStrategy에 대한 객체생성을 쉽지 않구나라고 생각했습니다.  생각의 폭이 좁다고 해야할까요. 
그런데, 선동님의 첫번째 힌드를 보고, 생성자 안에 그냥 () -> true 를 직접 의존성 주입하는 것을 보고는 유레카를 속으로 외쳤습니다. 😄