Step3 - 자동차 경주
next-step/java-racingcar pull request #2512
Opened 2021-07-28 16:41 UTC by longbeom

안녕하세요 리뷰어님!

step3 리뷰 요청 드립니다..!

private 메서드의 경우 단위 테스트를 어떻게 해야 할지 고민이 되는데요,
혹시 좋은 방법이 있을까요..?

감사합니다🙏🏻

2021-07-29 02:08 UTC, bass84 requested changes
홍범님~ 3단계 구현하시느라 고생 많으셨어요!
요즘 날이 더운데도 열심히 하시는 모습 좋습니다!!

객체의 역할과 책임을 중점으로 코멘트들을 드렸습니다.
전체적으로 각 객체가 처리해야 할 역할을 조금 더 고민해보시고
거기에 맞춰서 수정해보시면 좋을 것 같습니다.

private 메서드를 테스트 하고 싶다면, 원칙적으로는 public 메서드를 통해서 하는 것이 맞습니다.
하지만 그 테스트가 필요하다고 생각이 드신다면, 설계가 잘못된 건가 한번 의심해볼 필요가 있습니다.
이번에 제가 드린 코멘트에서 객체의 역할과 책임에 대한 고민을 해보시면 답이 나올 수도 있어요.
고민해보시고 잘 모르겠으면 다시 문의 주세요~!^^

수정 후에 다시 PR 주세요~!

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Car.java
> +	public void advance() {
`this.position += COUNT_ADVANCE;` 이렇게 하면 좀 더 간편하게 될 것 같네요.^^

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Car.java
> +	public void stop() {
0을 더하는 것이긴 하지만, stop인데 연산할 필요가 있을까요?

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/InputView.java
> +		answers[1] = answerFromQuestion(QUESTION_NUMBER_OF_TRIALS);
1. `answerFromQuestion` 하나의 메서드로 분리되어서 한번씩 호출할 수 있는 것은 좋은데 이것을 두번 호출하는 모양새가 조금은 아쉽네요. 만약 질의가 더 늘어나면 `answerFromQuestion` 호출하는 코드가 더 늘어날텐데 그렇게 안 하고 한번에 다 처리할 수 있는 방법은 없을까요?^^
2. Array나 List에 순서대로만 정답을 받는다고 했을 때 이것을 나중에 처리하려는 클라이언트 입장에서는 이 메서드를 내용을 직접 찾아서 봐야 첫번째 값이 자동차 대수이고 두번째 값이 시도할 회수 라는 것을 알 수 있습니다. 만약 질의가 더 늘어나면 그만큼 더 헷갈릴 수 있게되고 사용하는 쪽에서 순서를 잘못 알고 있으면 오류를 낼 가능성도 높아집니다. 이런 의미에서 Array로 처리하는 것은 부적절해 보이네요.

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/InputView.java
> +	private int answerFromQuestion(String question) {
질의를 받아서 하나의 메서드로 처리하는 시도 좋네요~! 👍

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/InputView.java
> +	private void viewQuestion(String question) {
이 정도는 메서드로 분리를 하지 않아도 되지 않을까요? 하지만, 정답은 아니니 홍범님의 생각대로 하셔도 됩니다.^^

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Main.java
> +		int[] answers = new InputView().answers();
nputView를 인스턴스를 생성해서 할 필요는 없어 보여요. 인스턴스를 생성한다는 것은 해당 객체의 '상태'를 가지고서 그 이후에도 뭔가를 처리할 것이라는 의미인데 이 인스턴스로는 그럴 일이 없거든요.

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Main.java
> +		new Racing().play(answers);
여기도 마찬가지로 이렇게 사용하는 거라면 인스턴스를 생성할 이유가 없어 보입니다.

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Racing.java
> +	private final OutputView outputView = new OutputView();
1. 객체의 역할에 대해서 한번 생각해볼게요. 자동차 경주와 출력이라는 행위가 연관이 있을까요? 자동차 경주 관장만 하면 되고 출력이라는 행위는 자동차 경주가 할 역할은 아닌 것 같아요. 그렇다면 Racing에 OutputView가 있을 이유는 없다는 것이에요. outputView를 Racing에서 떼서 다른 곳에서 처리를 해야할 것 같은데, 어떻게 처리하면 좋을까요?^^
2. OutputView 역시 상태를 가지고 있을 필요가 없는 객체인데 인스턴스를 생성해야 할 이유가 없어 보입니다.

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Racing.java
> +		}
예를 들어 어떤 이유에서 `play()` 메서드를 두번 호출한다고 해볼게요. 그렇게 되면 play 메서드에서는 prepareCars를 호출할테고 그 때마다 자동차를 새로 생성하게 될 거예요. 그럼 우리가 생성하려는 자동차 수보다 더 많은 자동차들이 생성되겠죠? 그런 면에서 여기에서 자동차를 생성하는 방식으로 하는 것은 어떤 이슈를 만들 수가 있습니다. 그럼 다른 방식으로 자동차를 생성해야 할텐데 어떻게 하면 좋을까요?

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Racing.java
> +	private void gameByTrial(List<Car> cars) {
이 행위의 주체는 Racing이 좋을까요? 아니면 Car 또는 Cars가 좋을까요?

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Racing.java
> +	private void advanceOrStop(Car car) {
이 행위는 `자동차`가 하는 일이에요 그렇다면 Racing에 있어야 할 메서드가 아니라 Car에 있어야 할 메서드일 거예요.^^

2021-07-29 02:08 UTC, bass84 commented on src/main/java/step3/Racing.java
> +	private boolean isAdvance() {
이 행위 역시 `자동차`와 관련된 것이에요. 즉, Racing에서 해야 할 역할은 아니라는 의미이죠.

2021-08-01 17:27 UTC, longbeom commented
테스트

2021-08-01 17:28 UTC, longbeom commented
안녕하세요 리뷰어님 ! 

좀 늦었네요.. 🥲

처음부터 설계한다는 생각으로 다시 코드 작성했습니다!

리뷰 잘 부탁드려요!

2021-08-02 13:48 UTC, bass84 requested changes
작업하시느라 고생 많으셨어요!
며칠 동안 안 올라오길래 바쁘신 건가 했는데 많은 고민을 하시고 바꾸시느라 그런 것 같네요.
그 고민의 흔적이 많이 느껴졌습니다.
상당수 개선이 되어 이전보다 더 나아진 것 같고,
클래스 별로 역할을 잘 분리하셨다는 생각이 듭니다. 👍 👍 👍 
몇 부분 아쉬운 것이 있어서 코멘트 드렸는데
이 부분이 수정되면 훨씬 좋은 코드가 될 것 같습니다.
조금만 더 힘내서 마무리 하시고 다음 단계로 가시죠!!
수정 후 PR 주세요!
화이팅입니다!! 🔥 🔥 🔥

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/domain/Car.java
> +	private static final int CONDITION_ADVANCE = 4;
`private static final` 변수를 가장 상단에 놓는 것이 올바를 컨벤션이에요.^^

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/domain/Car.java
> +	private void advance() {
이 메서드는 advanceOrStop 메서드에서 사용하니 그 아래에 있는 것이 조금 더 가독성면에서 좋을 것 같네요~!

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/domain/Racing.java
> +	public int[][] race() {
이 전과 비교했을 때 결과를 저장하는 방식이 훨씬 좋아졌습니다. 하지만 int[][] 형태로 결과를 얻는 건 조금 아쉽다는 생각이 드네요. 배열로 하면 가독성면에서도 좋지 않다는 것도 있고, 배열은 정적이기 때문에 동적인 List에 비해 그 이후 사용에 있어서 다소 불편한 점들이 있어요. 특히 이런 2차원 배열은 더더욱 불편해 보입니다. 차라리 새로운 Object를 만들어서 그것을 List로 만들어서 결과를 반환하도록 만들면 어떨까요? 간단하게만 수정해도 될 것 같습니다.^^

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/domain/Racing.java
> +	private void raceOneTrial() {
Cars라는 일급컬렉션이 있었다면 좋았겠다는 생각이 드네요. 해당 클래스에서 이 메서드를 사용하면 될 것 같거든요~!^^

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/utils/RandomUtils.java
> +		return new Random().nextInt(RANDOM_BOUND);
이 메서드를 실행할 때마다 Random 인스턴스를 새로 생성하는 것은 비효율적이네요. 한번 생성해서 재사용하도록 수정해주시면 좋을 것 같아요.

2021-08-02 13:48 UTC, bass84 commented on src/main/java/step3/utils/Validator.java
> +	public static void validateOverZero(int number) {
InputView에 놓아도 될 메서드라고 봐요. 메서드명으로 유추는 가능하지만, 정확히 언제 사용해야 하는 유효성 체크인지는 클래스명 + 메서드명 조합으로 알 수 있는데 그것을 잘 나타내기는 어려워 보여서요.

2021-08-02 15:05 UTC, longbeom commented
안녕하세요 요한님!

피드백 반영해서 수정했습니다..!

말씀해주신대로 Cars 라는 일급컬렉션을 사용하니까 확실히 깔끔해진 것 같네요 😅

다시 리뷰 요청드립니다!

2021-08-03 01:17 UTC, bass84 approved these changes
홍범님 구현하시느라 수고하셨습니다.^^
제가 생각했을 때 이렇게 구현했으면 좋았겠다 싶은 방향으로 코멘트를 드렸는데 참고해주세요.
이제 4단계로 넘어가서 계속 진행하시죠!
화이팅입니다!!^^ 🔥 🔥 🔥

2021-08-03 01:17 UTC, bass84 commented on src/main/java/step3/domain/Racing.java
> +			RacingResult racingResult = new RacingResult(trials, resultOneTrial);
// 숫자형의 리스트로 받는다면 어떤 차량에 대한 결과인지를 정확하게 매칭하는 게 어려울 수 있어요.
 ```
public class Result {
    private int carIndex; -> 이 변수는 차를 생성할 때 만들면 좋습니다.
    private int position;
    ...
}
```
이와 같은 방식이었으면 어땠을까요?^^

2021-08-03 01:17 UTC, bass84 commented on src/main/java/step3/domain/RacingResult.java
> +	private final int trial;
trial은 사용하지 않는데 지워주세요~!

2021-08-03 01:17 UTC, merged