Step3 - 자동차 경주
next-step/java-racingcar pull request #2516
Opened 2021-07-29 06:07 UTC by brawman2

이번에도 잘 부탁드립니다. 🙂

저번 사칙연산에서 익힌 enum을 사용해서 구현했습니다~!

2021-07-30 04:07 UTC, vagabond95 requested changes
요구사항에 맞게 잘 구현해주셨네요!

특히 enum 으로 각 움직임을 분리하는 시도는 저도 생각을 못했던 부분인데 좋은 접근법인 것 같습니다 👍 👍 
그 외에 구현 내용에 대하여 몇가지 코멘트를 남겼는데요, 확인 후 리뷰요청 부탁드립니다!

2021-07-30 04:07 UTC, vagabond95 commented on src/main/java/carrase/CarRasingGame.java
> +		cars.stream()
단순 반복문이라면 for 문의 foreach 형식으로 구현해보는 것도 좋을 것 같습니다!

(지극히 개인적인 의견이지만) 단순히 콜렉션을 순회하는 로직을 stream 으로 구현했을 때 가독성이 조금 떨어진다는 느낌이 들더라구요 ㅎㅎ..

2021-07-30 04:07 UTC, vagabond95 commented on src/main/java/carrase/CarRasingGameUI.java
> +	private void printUncleSam() {
UncleSam 은 무슨 의미일까요?!

2021-07-30 04:07 UTC, vagabond95 commented on src/main/java/carrase/CarRasingGameUI.java
> +	public void start() {
UI 클래스는 자동차의 결과를 그리는 것에만 집중하는 것은 어떨까요~?
CarRacingGame 을 UI 클래스에서 관리하게 되면 UI 클래스는 '결과를 그리는 것' 과 '결과를 수행하는 것' 2개의 역할을 수행하게 될 것 같아요!

2021-07-30 04:07 UTC, vagabond95 commented on src/main/java/carrase/RacingCar.java
> +	public int getMileage() {
interface 의 메소드를 구현한 메소드는 @override 에노테이션을 붙히는 것을 권장드립니다!

2021-07-30 04:07 UTC, vagabond95 commented on src/main/java/carrase/CarBehavior.java
> +public enum CarBehavior {
오! 저도 움직임을 enum 으로 분리해보려는 시도는 생각을 못했는데 좋은 접근법인 것 같습니다!

2021-07-30 13:44 UTC, brawman2 commented on src/main/java/carrase/CarRasingGame.java
> +	public CarRasingGame(int input) {
엇... 인텔리제이 추천해주는 단어를 그냥 써버렸네요😖
감사합니다~!

2021-07-30 13:45 UTC, brawman2 commented on src/main/java/carrase/CarRasingGame.java
> +		cars.stream()
foreach로 수정하니 확실히 더 코드를 읽기 좋은 것 같습니다~!!

2021-07-30 13:46 UTC, brawman2 commented on src/main/java/carrase/CarRasingGameUI.java
> +	private void printUncleSam() {
예전 미국 징병 포스터 이름이었는데요.. 하하

얼른 일반적인 단어로 수정했습니다~!!

2021-07-30 13:47 UTC, brawman2 commented on src/main/java/carrase/CarRasingGameUI.java
> +	public void start() {
다시 살펴보니 start는 UI클래스에 어울리지 않네요~!

감사합니다~!

2021-07-30 13:47 UTC, brawman2 commented on src/main/java/carrase/RacingCar.java
> +	public int getMileage() {
이런 세밀한 부분도 가이드 주셔서 너무 감사합니다~!!

2021-07-30 13:48 UTC, brawman2 commented on src/main/java/carrase/CarBehavior.java
> +public enum CarBehavior {
저번 스텝에서 enum에 대해서 알 수 있어서 사용할 수 있었던 것 같습니다~~!!

감사합니다~~!!!

2021-08-01 02:34 UTC, vagabond95 approved these changes
병원에 입원하여 확인이 늦었습니다. 😢 
피드백 의도대로 너무 잘 반영해주셨습니다! enum 을 통해 분리를 잘 해주신 것 같아요 ㅎㅎ

다음 단계 진행해주세요!

2021-08-01 02:34 UTC, merged