Step4 자동차 경주(우승) 리뷰 요청 드립니다
next-step/java-racingcar pull request #2548
Opened 2021-07-31 14:23 UTC by jayyhkwon

안녕하세요 용근님~
주말 잘보내고 계신가요!?

Step3 마지막에 요청하신 피드백 반영 하였으며,
Step4 자동차경주(우승자)까지 코드 작성하여 리뷰요청드립니다~~

Step3에서 이야기한 getter에 대한 설명이 잘 이해가 되지 않아 한번 더 질문드립니다.
getter를 지양하는 이유가 객체에게 직접 일을 시키기 위함이라고 하셨는데 step3의 `Position` 객체는 단순 movedDistance를 랩핑한 객체로 밖에 쓰이지 않아서 사실상 getter와 역활이 같다고 생각이 드는데요.

이해를 위해 구체적인 예시를 설명해 주실 수 있으신가요?

2021-07-31 14:25 UTC, jayyhkwon commented
upstream/step3에 머지된 내용을 리베이스하려니 충돌이 나는것 같네요..

2021-08-01 05:23 UTC, yongdae commented
안녕하세요. 용현님 ~ :)

질문 주신부분에 대해 답변을 드리자면 Position은 위치값을 단순히 감싼 객체가 맞습니다. 👍 

getter를 지양하는 이유가 객체에게 직접 일을 시키기 위함이라고 하였지만 getter를 완전히 제거 할 수 없기 때문에
단순히 원시값을 반환하기보다는 VO와 같은 객체를 만들어보는 방법을 가이드 드린 부분입니다! 😄 

아 그리고 용현님 제 이름도 용근이 아니라 용대입니다. 😭

2021-08-01 05:43 UTC, yongdae requested changes
안녕하세요. 용현님 ~ :)

이전 피드백을 포함해서 빠르게 4단계를 잘 진행해주셨네요. 👍
진행해주신 내용에 대해 몇 가지 의견을 드렸습니다.

확인하시고 다시 리뷰 요청 부탁드려요~ 🔥🔥

2021-08-01 05:43 UTC, yongdae commented on src/test/java/step4/car/CarTest.java
> +class CarTest {
"각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다."
이 요구조건에 해당하는 테스트를 Cars가 아니라 Car에 추가해보면 어떨까요?

2021-08-01 05:43 UTC, yongdae commented on src/test/java/step4/car/CarsTest.java
> +    }
우승자는 한명 이상일 수 있다. 에 대한 요구 조건에 만족하는 테스트인 것 같아요!
하지만 "자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다." 에 대한 테스트와는 거리가 있는 것 같아요.

추가로 "자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다." 이 요구 조건을 충족시키는
이동을 한 자동차들의 목록에서 우승자를 가리는 테스트를 추가해보면 좋을 것 같아요. :)

2021-08-01 05:43 UTC, yongdae commented on src/main/java/step4/RandomValueGenerator.java
> +public class RandomValueGenerator {
이전 피드백을 잘 반영해주셨네요. 👍

2021-08-01 05:43 UTC, yongdae commented on src/main/java/step4/car/Car.java
> +    }
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

여기도 이 규칙을 적용해보면 좋을 것 같아요!

2021-08-01 05:43 UTC, yongdae commented on build.gradle
> +    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '2.23.0'
사용하시지는 않지만 라이브러리가 추가되어있네요. 😢

2021-08-01 05:43 UTC, yongdae commented on src/main/java/step3/RacingGame.java
> +    public void race(int gameCount) {
gameCount라는 매개변수 값을 안 받아도 경주를 진행 할 수 있지 않을까요? 🤔

2021-08-01 06:00 UTC, jayyhkwon commented on build.gradle
> +    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '2.23.0'
확인 감사합니다!
삭제하였습니다

2021-08-01 06:02 UTC, jayyhkwon commented on src/test/java/step4/car/CarTest.java
> +class CarTest {
자동차 이름에 대한 유효성검사는 `Car`의 책임인데 제가 작성할때 생각을 미처 못했나보네요!
피드백 감사합니다~~

2021-08-01 06:04 UTC, jayyhkwon commented on src/main/java/step3/RacingGame.java
> +    public void race(int gameCount) {
gameCount라는 매개변수를 받은 이유는
`race()`를 한번에 진행하는 게 아니라 필요한 만큼 진행할 수도 있지 않을까? 라는 생각이 들어서 추가한거였어요.

2021-08-01 06:05 UTC, jayyhkwon commented on src/main/java/step3/RacingGame.java
> +    public void race(int gameCount) {
필요하다면 `Overloading` 해서 매개변수가 없는 `race()`도 만들어볼까요?

2021-08-01 06:46 UTC, jayyhkwon commented on src/test/java/step4/car/CarsTest.java
> +    }
우승자 검증에 대한 테스트는 RacingGame의 역활이라 판단되어 RacingGameTest를 추가 작성하였습니다.

상세한 피드백 감사드립니다!!

2021-08-01 06:59 UTC, jayyhkwon commented on src/main/java/step4/car/Car.java
> +    }
`CarName` 을 추가하면서 원시값보다는 객체를 사용해야하는 이유를 느꼈습니다.

자동차 이름에 대한 유효성 검증 로직을 `Car` 객체가 아닌 `CarName` 객체가 담당하는게 맞으니까요 ㅎㅎ

그런 의미를 깨닫게 하기 위해 원시값을 그대로 리턴하는 게터를 쓰지 않는 규칙을 적용해보라고 말씀하신 게 아닐까하는 생각이 드네요~ ㅎㅎ

2021-08-01 07:04 UTC, jayyhkwon commented
죄송합니다 용대님 ㅠㅠ
저도 이름을 착각했군요...

2021-08-01 12:25 UTC, yongdae commented on src/main/java/step3/RacingGame.java
> +    public void race(int gameCount) {
네 일단은 오버로딩을 하시더라도 인자 없이도 게임을 진행할 수 있는 기능을
RacingGame 객체가 가지면 좋을 것 같아요. :)

2021-08-01 12:35 UTC, yongdae requested changes
안녕하세요. 용현님 ~ :)

빠르게 피드백을 반영해주셨네요!!
더불어 원시값을 사용하지 않고 포장해서 사용하는
의미를 아셨다니 기분이 좋네요 ~ 😄 

큰 의견은 아니지만 다음 단계로 넘어가기전에 마무리했으면
하는 의견이 아직 남아있어 다시 Request changes로 진행하겠습니다.

리뷰 내용 확인 후에 다시 리뷰 요청 부탁드려요. 🙇

2021-08-01 12:35 UTC, yongdae commented on src/main/java/step4/car/CarName.java
> +public class CarName {
피드백을 잘 반영해주셨네요. 👍 

추가로 CarName은 car 패키지 안에 있으니
car를 빼고 Name으로 바꿔봐도 좋을 것 같네요. :)

2021-08-01 12:35 UTC, yongdae commented on src/test/java/step4/car/CarNameTest.java
> +class CarNameTest {
자동차 이름에 대한 테스트도 추가 해주셨네요. 👍

2021-08-01 12:35 UTC, yongdae commented on src/test/java/step4/RacingGameTest.java
> +class RacingGameTest {
[이 피드백](https://github.com/next-step/java-racingcar/pull/2548#discussion_r680455048)이 반영된다면 자동차 경주가 원하는 횟수만큼 진행되고
종료되었는지 확인하는 테스트를 추가 해볼 수 있지 않을까요? :)

2021-08-01 13:34 UTC, jayyhkwon commented on src/test/java/step4/RacingGameTest.java
> +class RacingGameTest {
`RacingGameTest.isFinished()` 추가하였습니다!

2021-08-01 13:34 UTC, jayyhkwon commented on src/main/java/step4/car/CarName.java
> +public class CarName {
Name 클래스로 수정하였습니다!

2021-08-02 01:01 UTC, yongdae approved these changes
안녕하세요. 용현님 ~ :)

피드백을 잘 반영해주셨네요!!
이제 마지막 단계로 넘어가도록 하겠습니다. 🔥🔥

진행해주신 내용에 의견을 드린 부분이 있으니 해당 내용은
다음 단계에 같이 반영 부탁드리도록하겠습니다. 🙇

2021-08-02 01:01 UTC, merged

2021-08-02 15:08 UTC, jayyhkwon commented on src/main/java/step3/car/CarFactory.java
> +public class CarFactory {
Step4랑 착각하신거죠??
Step3에서는 Cars를 구현하지 않았습니다!

2021-08-02 15:08 UTC, jayyhkwon commented on src/main/java/step3/Main.java
> +        racingGame.race(tryCount);
반영했습니다