자동차경주테스트 우승자 커밋
next-step/java-racingcar pull request #2549
Opened 2021-07-31 17:09 UTC by superkkj

잘부탁드립니다 ..^^

2021-08-01 00:52 UTC, bass84 requested changes
기준님 안녕하세요~!
이전 단계에서 몇 번 말씀드렸던 게 아직 수정되지 않은 게 보이네요.
그 부분은 꼭 수정해주세요.
그리고 아직 컨벤션 지켜지지 않는 부분들이 계속 나옵니다.ㅠㅠ
이런 부분들은 안 나오도록 잘 체크해주시면 좋겠네요.

수정과 답변 완료하시면 다시 PR 주세요!

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/CarName.java
> +public class CarName {
CarName이라는 클래스를 분리하신 것을 한번 생각해보실 수도 있겠지만, 과연 필요한지는 한번 다시 생각해봐도 좋을 것 같아요.

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/CarName.java
> +    private String CarName;
변수명은 소문자로 시작해주세요.

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/CarName.java
> +    public CarName(String carName) {
`throw  new`는 띄어쓰기를 두 번 하셨네요.

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/Cars.java
> +    private void addCar(String carNames) {
생성자에 있어도 될 것 같은데 분리하신 이유가 있으실까요?

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +    static ResultView resultView = new ResultView();
두 view는 왜 인스턴스를 생성하셨을까요?

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +    static Winner winner = new Winner();
여기에 있는 멤버변수를 모두 static으로 생성하신 이유는 무엇일까요?

2021-08-01 00:52 UTC, bass84 commented on src/main/java/CarRacing/Winner.java
> +        StringBuffer victors = new StringBuffer();
StringBuffer를 사용하신 이유가 있을까요?

2021-08-01 00:52 UTC, bass84 commented on src/main/java/view/ResultView.java
>      public void printCarPosition(List<Car> car) {
변수명이 왜 car일까요?

2021-08-01 14:27 UTC, superkkj commented on src/main/java/view/ResultView.java
>      public void printCarPosition(List<Car> car) {
cars로 했어야됫는대 하... 수정하겠습니다... ㅠㅠ

2021-08-01 14:28 UTC, superkkj commented on src/main/java/CarRacing/Winner.java
> +        StringBuffer victors = new StringBuffer();
append 함수때문에  우승자나 레이스 일때 쉽게 출력할수 있어서 썻습니다.

2021-08-01 14:30 UTC, superkkj commented on src/main/java/CarRacing/CarName.java
> +    public CarName(String carName) {
수정하겠습니다 :)

2021-08-01 14:33 UTC, superkkj commented on src/main/java/CarRacing/CarName.java
> +public class CarName {
음 억지로 분리해서 구현해봤습니다. 이 리뷰어 받기전에 다른강의에선 일급콜렉션으로 짜셔서 저도 한번구현해보려고한건대... 음 제가 현제 구현한코드로 굳이필요없긴할거같습니다...

2021-08-01 14:33 UTC, superkkj commented on src/main/java/CarRacing/CarName.java
> +    private String CarName;
네 수정하겠습니다

2021-08-01 15:35 UTC, superkkj commented on src/main/java/CarRacing/Main.java
> +    static Winner winner = new Winner();
메인함수가 static 함수이기때문에 클래스변수도 static 으로 선언했습니다.

2021-08-02 12:29 UTC, bass84 commented on src/main/java/CarRacing/CarName.java
> +public class CarName {
일급컬렉션에 대해 잘못 이해하고 계신 것 같아요. [이 글](https://jojoldu.tistory.com/412) 참고해보세요~!

2021-08-02 12:37 UTC, bass84 commented on src/main/java/CarRacing/CarName.java
> +public class CarName {
일급컬렉션에 대해 잘못 이해하고 계신 것 같아요. [이 글](https://jojoldu.tistory.com/412) 참고해보세요~!

2021-08-02 12:37 UTC, bass84 commented on src/main/java/CarRacing/Cars.java
> +    private void addCar(String carNames) {
모르고 반영했다는 것들이 많이 있는데, 개발자로서는 매우 안 좋은 습관이라고 생각해요. 빠른 시일 내에 고쳐지시면 좋겠습니다~!

2021-08-02 12:37 UTC, bass84 commented on src/main/java/CarRacing/Winner.java
> +        StringBuffer victors = new StringBuffer();
StringBuffer와 StringBuilder의 차이에 대해서 먼저 이해하시고 사용하셔야 할 것 같아요. [이 글](https://ifuwanna.tistory.com/221) 참고해주세요. 
참고로 지금 사용하시는 자바 버전에서는 그 용도를 위해서는 StringBuffer/StringBuilder를 사용하지 않으셔도 됩니다.^^

2021-08-02 12:37 UTC, bass84 commented on src/main/java/CarRacing/Main.java
> +    static Winner winner = new Winner();
그렇다면 제가 궁금한 것은 Main이라는 클래스에 과연 멤버 변수가 필요하냐는 것입니다. 필요하다면 왜 필요한 것일까요?

2021-08-02 12:44 UTC, superkkj commented on src/main/java/CarRacing/Cars.java
> +    private void addCar(String carNames) {
네 죄송합니다 ㅠ_ㅠ

2021-08-02 13:14 UTC, bass84 requested changes
고생하셨습니다. 
간단한 것 몇 가지만 수정해주시면 좋을 것 같아요.
수정해서 PR 올려주세요~!
마무리 하고 다음 단계로 가시죠~!^^

2021-08-02 13:46 UTC, superkkj commented on src/main/java/CarRacing/CarName.java
> +public class CarName {
앗일급 컬렉션이아니라 원소값 보호인대 단어선택이잘못됫네요  글은 참고해서 잘보도록하겠습니다..

2021-08-02 13:50 UTC, superkkj commented on src/main/java/CarRacing/Winner.java
> +        StringBuffer victors = new StringBuffer();
감사합니다 👍  읽었던글인대 다시한번 꼼꼼이 읽겠습니다.

2021-08-02 13:51 UTC, superkkj commented on src/main/java/CarRacing/Cars.java
> +    private void addCar(String carNames) {
아 이거모르고반영한게아니라... 제가잘못봣네요 죄송합니다. 생성자로 수정하도록하겠습니다 .

2021-08-02 15:55 UTC, superkkj commented on src/main/java/CarRacing/Main.java
> +    static Winner winner = new Winner();
답변은 좀더 정리해서 답변드리겠습니다.

2021-08-03 02:29 UTC, bass84 approved these changes
구현하시느라 수고하셨습니다~!
이제 마지막 단계만 남겨두고 있네요!
끝까지 힘내시고 화이팅하세요!! 🔥 🔥 🔥

2021-08-03 02:30 UTC, merged

2021-08-03 14:11 UTC, superkkj commented on src/main/java/CarRacing/Main.java
> +    static Winner winner = new Winner();
코드 실행에는 문제가없지만 클래수 변수로 선언하는순간  메인 클래스가 실행하면서 메모리 공간에 같이 올라가기때문에 다른클래스에서도 사용 할수있습니다. 하지만 메인함수에서 실행하고 바로종료하기때문에. 클래스 변수로 선언 해서 이득이 되는부분이 없는거 같습니다.
그래서 inputView 클래스에서 따로 사용하는 함수를 스태틱함수로 변경해서 메인 함수내에서만 쓸수있게 수정을 했습니다.
만약 inputView가 다른클래스에서도 공유되는 개념으로 사용이 된다면. 클래스 변수로 필요할수도 잇을거같습니다