🚀 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2552
Opened 2021-08-01 11:18 UTC by JJongSue

안녕하세요
리뷰 요청드립니다...

2021-08-01 14:41 UTC, ksundong requested changes
안녕하세요. 종수님! 😊

4단계 미션을 진행하시느라 고생많으셨습니다.👏 👏 👏
점점 난이도가 높아지죠? 파이팅입니다! 💪

전체적인 로직면에서는 괜찮은데, 코드에서 조금 신경써주시면 좋을 것 같은 부분들이 있어서 변경 요청드립니다!

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/Car.java
>          moveCount = 0;
java의 멤버변수는 기본값으로 초기화가 되는데요.
이 부분은 굳이 초기화 시켜주지 않아도 좋을 것 같습니다!

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private static final Random random = new Random();
이 부분은 상수로 사용하지 말고, 의존성을 주입 받는 형태로 관리해야 테스트하기 좋지 않을까요?

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/RacingCar.java
>      }
메서드는 생성자 아래에 위치하는 것이 자바 컨벤션입니다!
지켜주세용!

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +        }
여기 0과 5는 상수로 추출해 볼 수 있지 않을까요?
그리고, 예외 메시지도 분명 변경과 연관이 있겠죠?

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +        Comparator<Car> carComparatorMaxMoveCount = Comparator.comparingInt(Car::getMoveCount);
`Comparator`와 `Comparable` 의 차이를 한 번 학습해보시는 것도 좋을 것 같아요.

2021-08-01 14:41 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +                .get()
`optional`을 그냥 `get`하는 일은 지양해주세요!
최소한 `isPresent()` 이후에 등장하거나, `orElse~`를 사용해주세요.

2021-08-01 14:41 UTC, ksundong commented on src/main/java/UI/InputView.java
> +        }
어떤 `Exception`이 발생할까요?
명확하게 `Exception`을 `catch`해서 해결해주는 방식을 권장드려요.

2021-08-01 14:41 UTC, ksundong commented on src/main/java/UI/InputView.java
> +        }
또한, 예외 포장을 이용해주세요. 해당 예외가 어떤 예외로 인해 발생되었는지를 stack trace에 남기기 위해선 반드시 포장을 해줘야 합니다!

2021-08-01 14:41 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +        racingCar = new RacingCar(inputCarCount, splitedCarName);
여기서 테스트가 변경되었다면 어떨까요?
사실 `carCount`는 이제는 필요없지 않을까요?

2021-08-01 14:41 UTC, ksundong commented on src/test/java/Car/RacingCarTest.java
> +    @RepeatedTest(5)
`RepeatedTest`를 사용해줄만한 이유가 있을까요?

2021-08-02 13:35 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
>      }
dd5089aeed9c789a4d27740d3ba01ecf46df6969

2021-08-02 13:35 UTC, JJongSue commented on src/main/java/Car/Car.java
>          moveCount = 0;
4a4db5c1faad66d08f126528a3d51cfe3e1ef3c5

2021-08-02 13:36 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +    private static final Random random = new Random();
381ca78639ade33a0fb46c0cddd160123ae4b61b
4df548c7409548b248c12f9d3d37b7afa793eb40

2021-08-02 13:36 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +        }
9764c624eb43f089cdac9d6e1dcc46575b7d720a

2021-08-02 13:37 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +                .get()
80425975bc33307f74f50178eb204003d482db0a

2021-08-02 13:37 UTC, JJongSue commented on src/test/java/Car/RacingCarTest.java
> +        racingCar = new RacingCar(inputCarCount, splitedCarName);
c20c70cd275bfb6af984d9374fbd513fd8ee5957

2021-08-02 15:15 UTC, ksundong requested changes
안녕하세요. 종수님! 😊

4단계 미션 피드백을 반영하느라 고생많으셨습니다.👏 👏 👏

실행해본 결과 요구사항과 약간 다른 부분이 있어서 변경요청을 드립니다.

- 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.

그리고 다른 피드백을 확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-02 15:15 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private static final int RANDOM_NUMBER_BOUND = 10;
과연 이것이 `RacingCar`가 가져야할 상수일지 생각해봅시다~

2021-08-02 15:15 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +        validate(carCount, carNames);
무엇을 `validate`하는지를 메서드에 작성해줬으면 좋을 것 같습니다.

2021-08-02 15:15 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +            car.move(random.nextInt(RANDOM_NUMBER_BOUND));
random을 이용한다는 발상은 좋은 것 같습니다!

2021-08-02 15:15 UTC, ksundong commented on src/main/java/Car/RacingCar.java
>      }
이 부분을 다음단계에서 개선해보시면 좋겠네요!

2021-08-02 15:15 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +                .orElse(new Car("empty"))
이미 `getMoveCount`를 쓴거, 그냥 `stream`을 `int`로 변환하고 그것의 `max`를 구한다음, `orElse(0)`을 사용해주는편이 낫지않았을까 싶네요.

2021-08-02 15:15 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +        car = new Car("testCar");
해당 이름은 요구사항 상 맞지 않는데, 예외가 발생하지 않으면 안될 것 같습니다~

2021-08-03 13:53 UTC, JJongSue commented on src/main/java/Car/RacingCarMain.java
> +        int carCount = carNames.length;
622af60b4d95be7b4dbe27fc55673b5bd46e6af4

2021-08-03 13:54 UTC, JJongSue commented on src/main/java/Car/Car.java
> +    }
aa7138c78bfad573f7031f0fc629b389df08ff3b

2021-08-03 13:54 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +    private static final int RANDOM_NUMBER_BOUND = 10;
06a8a98eebde1d52402ad0b1205c2e2b17fbfeb3

2021-08-03 13:54 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +        validate(carCount, carNames);
18c03c3f39ea76c2703802ff17275583cc46cf1b

2021-08-03 13:55 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +        }
18c03c3f39ea76c2703802ff17275583cc46cf1b

2021-08-03 13:56 UTC, JJongSue commented on src/main/java/Car/RacingCar.java
> +                .orElse(new Car("empty"))
18c03c3f39ea76c2703802ff17275583cc46cf1b

2021-08-03 13:56 UTC, JJongSue commented on src/main/java/UI/InputView.java
> +        String[] stplitedCarName = carNames.split(",");
b7ffbe1c8198337cb2e7384195167ad1ba23ff42

2021-08-03 13:57 UTC, JJongSue commented on src/test/java/Car/CarTest.java
> +        car = new Car("testCar");
8814fa6ee4b278de28d23c3789d7ff8a08fd630a

2021-08-03 14:38 UTC, ksundong approved these changes
안녕하세요. 종수님! 😊

4단계 미션 피드백을 반영하느라 고생많으셨습니다.👏 👏 👏

이제 마지막 단계네요! 💪  조금만 힘내시면 될 것 같습니다!
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-03 14:38 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +    private static final int RANDOM_NUMBER_BOUND = 10;
이 피드백은 무시해주셔도 좋을 것 같습니다~

2021-08-03 14:38 UTC, ksundong commented on src/main/java/Car/RacingCar.java
> +            car.move(random.nextInt(RANDOM_NUMBER_BOUND));
매개변수가 사용되지 않고 있네요!

2021-08-03 14:38 UTC, ksundong commented on src/main/java/Car/RacingCarMain.java
> +            racingCar.gameStart(random, randomNumberBound);
음 이런식으로 변경하는 것을 의도한 것은 아니었습니다!

2021-08-03 14:38 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +        car = new Car("test");
변경해주셨네요!

2021-08-03 14:38 UTC, ksundong commented on src/main/java/Car/Car.java
>      }
👍

2021-08-03 14:38 UTC, ksundong commented on src/test/java/Car/CarTest.java
> +    }
👍

2021-08-03 14:38 UTC, merged