[Step5] 자동차 경주(리팩토링) 리뷰 요청드립니다
next-step/java-racingcar pull request #2567
Opened 2021-08-02 17:18 UTC by jayyhkwon

안녕하세요 용대님~
벌써 자동차 경주 Step5까지 진행 하였네요.
꼼꼼하게 리뷰 해주신 덕분에 많이 배울 수 있었습니다. 감사합니다!

1. Step4 마지막에 요청하신 피드백 반영하였습니다.
2. Step4 코드 기반으로 Step5를 리팩토링 하였습니다.
- `RacingGame`의 view 로직을 `RaceResult`로 이동하였습니다. (`RacingGame.printTitle()`, `RacingGame.printProgressOfRace()`)
- 자동차 경주 결과에 대한 로직을 `RaceResult`로 이동하였습니다 (`RacingGame.getWinnerCarsOfRace()`, `RacingGame.getWinnersName()`)

2021-08-03 05:42 UTC, yongdae requested changes
안녕하세요. 용현님~
이야기해주신 것처럼 벌써 자동차 미션 마지막 단계네요. 😢

5단계 요구 사항에 맞추어 패키지 구분을 잘 해주셨네요. 👍 
몇 가지 고민해보면 좋을 부분이 있어 의견을 드렸습니다~

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 😄

2021-08-03 05:42 UTC, yongdae commented on src/main/java/step5/Main.java
> +        }
이 부분을 RacingGame이 가지고 있게하면 어떨까요? 🤔

2021-08-03 05:42 UTC, yongdae commented on src/main/java/step5/domain/race/RacingGame.java
> +    private boolean isFirstRace;
isFirstRace 변수는 화면 출력을 위한 변수로 보이는데
RacingGame은 모르게 하는 방법은 없을까요? :)

2021-08-03 05:42 UTC, yongdae commented on src/main/java/step5/domain/race/RaceResult.java
> +public class RaceResult {
ResultView를 사용한다거나 printTitle() 메소드를 가지고 있는 것을 보고 판단한다면
RaceResult는 View처럼 보이는데 View가요? 아니면 경주 결과를 가지는 domain인가요??

지금은 구분이 모호해보이네요. 😢

2021-08-03 05:42 UTC, yongdae commented on src/main/java/step5/domain/race/RacingGame.java
> +public class RacingGame {
RacingGame은 MVC 패턴으로로 구분한다면 어떤 역할을 맡는 객체인가요? 🤔

2021-08-03 13:27 UTC, jayyhkwon commented on src/main/java/step5/domain/race/RacingGame.java
> +public class RacingGame {
Controller 역활을 맡고 있습니다!

2021-08-03 13:30 UTC, jayyhkwon commented on src/main/java/step5/domain/race/RaceResult.java
> +public class RaceResult {
용근님 말대로 역활이 애매한 객체인것 같습니다.
`RaceResult` 라는 객체이름대로 경주 결과에 대한 모든 책임을 몰아놔서 그런 것 같습니다.

경주 결과에 대한 책임은 다시 `RacingGame`으로 이동시켰고,
View에 대한 책임은 `ResultView`로 이동시켰습니다

2021-08-03 13:30 UTC, jayyhkwon commented on src/main/java/step5/domain/race/RacingGame.java
> +    private boolean isFirstRace;
`ResultView`로 옮겼습니다

2021-08-03 13:31 UTC, jayyhkwon commented on src/main/java/step5/Main.java
> +        }
`RacingGame`이 가지고 있는 대신 ResultView에 대한 의존성이 추가되었습니다.

2021-08-04 00:23 UTC, yongdae approved these changes
안녕하세요. 용현님 😄
피드백을 잘 반영해주셨네요. 👍

자동차 미션 마지막까지 잘 따라와주셔서
처음에 했던 설계보다 탄탄한 설계를 가진 코드가 된 것 같네요. 💯 

수고하셨습니다!! 🙇

열심히 피드백을 드렸는데 도움이 잘 되셨는지 모르겠네요. 😓

미션은 종료되지만 한번 더 고민해보시면 좋을 부분이 있어
의견을 드렸으니 확인만 해보시면 좋을 것 같아요~

미션 마지막까지 고생 많으셨습니다!
볼링 미션까지 완주하시길 응원할께요. 🙏

2021-08-04 00:23 UTC, yongdae commented on src/main/java/step5/Main.java
> +        for (int i = 1; i <= tryLimit; i++)
for문을 사용하지 않고 경주를 진행시키는 방법도 고민해보시면 좋을 것 같네요. :)

2021-08-04 00:23 UTC, yongdae commented on src/main/java/step5/domain/race/RacingGame.java
> +public class RacingGame {
만약 그렇다면 domain 패키지 대신 controller 패키지를 만들어 분류했다면 좋았을 것 같아요. 😄

2021-08-04 00:23 UTC, merged