Step4 : 자동차 경주 (우승자)
next-step/java-racingcar pull request #2571
Opened 2021-08-03 13:27 UTC by minyul

안녕하세요! 

객체지향의 사실과 오해를 읽으면서 하니 재밌네요!

구현하면서 어렵다고 느낀 부분이

1. Random 숫자가 1부터 10까지 나오는지 확인하는 테스트를 하고 싶은데 구글에 찾아보면 반복문을 이용해서 하더라구요.. 좋은방법이 있 을까요? 
- NumberContainer 쪽 getRandomNumber를 테스트를 하고싶습니다.
private Random numberGenerator 
public int getRandomNumber() {
		return numberGenerator.nextInt(NUMBER_RANGE);
	}
	
2. 책을 읽고 step3 에서 좀 더 추가한 것이 아닌 step4 에서는 다시 새로 짰습니다. Race 라는 눈에 보이지 않는 추상적인 개념을 살아있는 생물처럼 구현하였는데요. 잘한 건지.. 궁금합니다 ㅎㅅㅎ..

오전에 일하면서 문뜩 생각이 나서 적용해보고 하니 신기합니다.
항상감사합니다!! 많이배우고있습니다!

2021-08-03 23:52 UTC, seok-2-o requested changes
요구사항을 만족하지 못하는부분이 있네요
몇가지 코멘트 남겨놓았으니 확인 후 리펙토링 진행해주세요.

2021-08-03 23:52 UTC, seok-2-o commented on src/main/java/step4/App.java
> +		}
자동차를 생성하는 행위는 Race가 책임 져도 될 것 같은데 어떻게 생각하시나요 ?

2021-08-03 23:52 UTC, seok-2-o commented on src/main/java/step4/Car.java
> +	private final int CAR_INIT_DISTANCE = 0;
보통 비공개 상수
공개 상수
인스턴스 필드
로 선언하는것이 관례입니다.

static 필드도 누락되었네요.

2021-08-03 23:52 UTC, seok-2-o commented on src/main/java/step4/Car.java
> +	private String carName;
`각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.`
는 어디에 구현되어 있나요 ?

2021-08-03 23:52 UTC, seok-2-o commented on src/main/java/step4/Race.java
> +	}
Race 의 핵심은 Cars 라면 winners 를 인스턴스 필드로 유지하는것이 아니라 오히려 Cars 를 인스턴스 필드로 유지하는게 좋지 않을까요 ?

2021-08-03 23:52 UTC, seok-2-o commented on src/main/java/step4/Race.java
> +	private List<Car> winners;
longestDistance와 winners 를 인스턴스 필드로 유지해야할 필요가 있는지 의문이네요

2021-08-04 10:30 UTC, minyul commented on src/main/java/step4/App.java
> +		}
음.. 고민을 많이 해봤습니다. 생각해보니까 경기라는 추상적인 객체는 경기를 하는 주체적인 객체가 있어야지 진행을 할 수있다고 생각했고 여기서는 그것들이 Car 라고 생각했습니다. 즉, 경기는 Car에 의존적이라고 생각했고 그래서 App이 아닌 Race에 책임을 부여하도록 수정하였습니다. 감사합니다!

2021-08-04 10:47 UTC, minyul commented on src/main/java/step4/Car.java
> +	private final int CAR_INIT_DISTANCE = 0;
수정하였습니다!

2021-08-04 10:47 UTC, minyul commented on src/main/java/step4/Race.java
> +	}
Race에 winner가 아닌 Cars를 주입시켰습니다! 수정하였습니다!

2021-08-05 11:37 UTC, minyul commented on src/main/java/step4/Car.java
> +	private String carName;
수정하였습니다!

2021-08-05 12:29 UTC, minyul commented on src/main/java/step4/Race.java
> +	private List<Car> winners;
수정하엿습니다!

2021-08-06 01:39 UTC, seok-2-o requested changes
아직 App 에서 너무 많은 일을 수행하고 있는것 같아서 피드백 남겨드렸어요

해당부분 고민해보면 좋을 것 같아요 :)

2021-08-06 01:39 UTC, seok-2-o commented on src/main/java/step4/Car.java
> +	private String carName;
Name 을 객체로 만든다면 어떤 장점이 생길까요?

2021-08-06 01:39 UTC, seok-2-o commented on src/main/java/step4/App.java
> +		}
new Race(container, carnames()) 로 자동차 생성을 race 로 위임하는건 어떤가요 ?

2021-08-06 11:24 UTC, minyul commented on src/main/java/step4/App.java
> +		}
수정했습니다!

2021-08-06 11:38 UTC, minyul commented on src/main/java/step4/Car.java
> +	private String carName;
일급객체에 책임을 주면서 테스트할때 용이가 편리합니다. 또한, 사이드 이펙트가 없다고는 하는데... 여기서는 몸소 느끼지 못하고 있습니다 ㅠ-ㅠ

2021-08-07 03:15 UTC, seok-2-o approved these changes
피드백 반영 정말 잘해주셨네요 👍 
다음 미션은 리펙토링입니다.
주어진 힌트를 가지고 개선 할점이 없는지 고민해보면 좋을 것 같아요 :)

즐거운 주말 되시길 바랄게요

2021-08-07 03:15 UTC, seok-2-o commented on src/main/java/step4/Name.java
> +	}
👍

2021-08-07 03:15 UTC, seok-2-o commented on src/main/java/step4/Race.java
> +		}
이번 과정에서 들여쓰기는 1번으로 제한하고 있어요
이는 가독성대문엔드 스트림을 사용하면 행위단위로 분리할 수 있어서 조금 가독성이 향상 되는것 같아요
```java
return cars.stream()
.filter(it -> it.getStatusWinnerStatus(max))
.collect(toList());

2021-08-07 03:15 UTC, seok-2-o commented on src/test/java/step4/AppTest.java
> +		});
```suggestion
		car.move(()->4);
```
Functional Interface 를 활용해보아요.

2021-08-07 03:15 UTC, merged