자동차 경주(우승자) Step5 리뷰 요청
next-step/java-racingcar pull request #2633
Opened 2021-08-21 16:13 UTC by devchang202

자동차 경주(우승자) Step5 리뷰 요청드립니다.

한 가지 질문이 있습니다.

리팩토링을 할 때 최대한 compile 에러도 발생시키지 않으면서 점진적으로 리팩토링하는게 좋다고 배웠습니다. 그럼 보통 구조적인 리팩토링을 하게 되면 Test 또한 변경이 불가피할 경우가 생기는데 이럴 때도 Test를 먼저 수정하고 로직 코드를 수정하는 것이 TDD 권장 방식일까요?

감사합니다~

2021-08-22 11:25 UTC, jaeyeonling requested changes
많은 부분을 리팩토링 하시느라 고생이 많으셨습니다 👍 
질문의 답변과 코멘트 남겨두었으니 확인 부탁드려요~

2021-08-22 11:25 UTC, jaeyeonling commented on src/main/java/racingcar/domain/Car.java
> +    public boolean equalsLocation(Object o) {
```suggestion
    public boolean equalsLocation(Car car) {
```

car만 받을 수 있도록 작성한다면 조금 더 깔끔한 코드를 작성할 수 있을 것 같아요 :)

2021-08-22 11:25 UTC, jaeyeonling commented on src/main/java/racingcar/domain/Location.java
> +    public String toString() {
toString 메서드의 일반 규약으로는 반환되는 문자열이 "사람에게 읽기 쉽도록 간략하지만 유용한 정보를 제공해야 된다." 라고 명시되어 있습니다
즉, toString에 View의 요구사항을 구현하는 것은 좋은 방법이 아니기 때문에, View의 요구사항은 따로 분리해주는 것이 좋습니다 :)

2021-08-22 11:25 UTC, jaeyeonling commented on docs/step5.md
> +# 🚀 5단계 - 자동차 경주(리팩토링)
Q. 리팩토링을 할 때 최대한 compile 에러도 발생시키지 않으면서 점진적으로 리팩토링하는게 좋다고 배웠습니다. 그럼 보통 구조적인 리팩토링을 하게 되면 Test 또한 변경이 불가피할 경우가 생기는데 이럴 때도 Test를 먼저 수정하고 로직 코드를 수정하는 것이 TDD 권장 방식일까요?

A. 맞습니다!
조금 더 자세히 말씀드리면, 수정할 부분에 대한 테스트 코드를 복붙하여 수정할 결과의 테스트를 만듭니다 (기존 테스트: Green, 복붙하여 수정한 테스트: Red)
이후 프로덕션 코드도 복붙하여 리팩토링한 뒤, 수정한 테스트 코드에선 복붙하여 리팩토링 한 프로덕션 코드에 연결합니다 (기존 테스트: Green, 복붙하여 수정한 테스트: Green)
이후 기존 테스트와 기존 프로덕션 코드를 삭제하고, 리팩토링한 코드를 남겨주시면 됩니다!

교살자 패턴에 대한 내용을 간력하게 남겨드렸는데요!
조금 더 자세한 내용은 https://johngrib.github.io/wiki/strangler-pattern/ 해당 내용을 확인해주세요 :)

2021-08-23 06:26 UTC, devchang202 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean equals(Object o) {
어쩐지 뭔가 구현이 중구난방으로 된다는 느낌이 있었는데... 감사합니다 ㅎ

2021-08-23 06:33 UTC, devchang202 commented on src/main/java/racingcar/domain/Location.java
> +    public String toString() {
이 부분과 관련해서 의견을 여쭙고싶습니다.

이번 PR을 할 때 Domain에서 UI 정보를 다 만들어서 String으로 ResultView에 전달하는 형식으로 리팩토링을 했습니다.
그 이유는 getter를 최대한 없애고 Domain 클래스들에 메세지를 넘겨줘서 기능을 실행시키도록 하는 게 옳은 설계 지향점이라는 것을 듣고 코드에 반영하기 위함이었습니다.

근데 말씀하신대로 UI 생성은 View에서 담당하는 것도 맞다고 생각되어서 고민이 많이 되었는데요,
이번에 수정한 것에서는 기본적인 값 정보만을 View로 String 형태로 전달 하고 (Race 클래스의 getCurrentRoundString, getCarStateInString을 이용) 마무리 UI 구성은 View에서 처리하도록 변경하였습니다.

이렇게 구현하는 것이 더 나은 것인지 의견을 여쭤보고 싶습니다.

2021-08-23 16:47 UTC, jaeyeonling commented on src/main/java/racingcar/domain/Location.java
> +    public String toString() {
좋은 의견 공유해주셔서 감사합니다 👍
먼저 그 이유는 getter를 최대한 없애고 Domain 클래스들에 메세지를 넘겨줘서 기능을 실행시키도록 하는 게 옳은 설계 지향점이라는 것을 듣고 코드에 반영하기 위함이었습니다.에 해당되는 메시지를 던져 기능을 실행시키는 구조는 좋은 구조입니다

하지만 View를 위해 위와 같은 조건을 지킬 필요는 없는데요!
위에 말씀해주신 내용은 도메인끼리의 규약을 나타낸다고 보시면 되고, 도메인과 View는 완전히 독립적인 상태로 존재해야 합니다
View는 언제든 변경될 수 있고, 상대적으로 우선순위가 낮기 때문에 크게 중요하게 생각하지 않으셔도 될 것 같아요 :)

이해하기 좋은 예를 설명드리자면, 수 많은 객체지향 아키텍처들(클린 아키텍처, 어니언 아키텍처, 헥사고날 아키텍처, ...)을 보면 추구하는 철학에 따라 모두 형태는 다르지만
도메인과 View를 최대한 멀리 위치시키고, 분리한다는 핵심은 같다는걸 볼 수 있습니다 😄

2021-08-24 09:37 UTC, jaeyeonling approved these changes
마지막까지 코멘트 잘 반영해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-08-24 09:37 UTC, merged