[자동차 경주] 3단계 - 자동차 경주
next-step/java-racingcar pull request #2715
Opened 2021-11-03 13:23 UTC by csh0034

안녕하세요.
3단계 - 자동차 경주 제출합니다.
2단계에 피드백 주신내용 고려하여 수정내용 같이 커밋하였습니다.

추가로 개발시 고민했던사항 관련해서 질문 사항이 있습니다.
도메인에 getter, setter 를 사용하지 않을 경우 어떻게 테스트 코드에서 검증 할수있을까요?
또 콘솔에 결과를 출력할때 객체 toString 구현을 이용하는것도 가능한 방법인지 입니다.

그외에도 부족한 부분 피드백주시면 고민해보겠습니다.
감사합니다.

2021-11-04 06:49 UTC, testrace requested changes
피드백 잘 반영해주셨네요. 💯
전반적으로 읽어나가기 편한 깔끔한 코드가 인상 깊었습니다. 👍👍

몇가지 의견 남겼으니 확인해주시고 리뷰 요청 부탁드려요.

2021-11-04 06:49 UTC, testrace commented on README.md
> +- RacingController
기능 목록 👍

2021-11-04 06:49 UTC, testrace commented on src/main/java/racingcar/model/Car.java
> +	}
접근제어자를 default로 제공하는 이유가 있을까요?
이미 public 정적 팩토리 메서드를 제공하고 있다면 생성자 메서드들은 private으로 감추어 정적 팩토리 메서드의 장점을 살릴 수 있을 것 같아요!

2021-11-04 06:49 UTC, testrace commented on src/main/java/racingcar/model/Position.java
> +	private static final int DEFAULT_POSITION = 1;
기본 위치를 0이 아닌 1로 설정하신 이유가 있을까요?

2021-11-04 06:49 UTC, testrace commented on src/main/java/racingcar/model/Position.java
> +	}
toString 메서드를 재정의 해주셨네요!
하지만 재정의된 메서드가 ui에 의존하고 있다고 생각됩니다.
이펙티브 자바의 아이템 12번을 참고해보시면 좋을 것 같아요!

2021-11-04 06:49 UTC, testrace commented on src/main/java/racingcar/rule/MoveRule.java
> +}
전략 패턴 👍

2021-11-04 06:49 UTC, testrace commented on src/main/java/racingcar/util/NumberUtils.java
> +	}
private 생성자 👍
생성자 내부에서 예외를 던진다면 혹시라도 클래스 내부에서 인스턴스화를 하는 실수를 방지할 수 있어요.
이펙티브 자바의 아이템 4번을 참고해보시면 좋을 것 같아요!

2021-11-04 06:49 UTC, testrace commented on src/test/java/racingcar/model/RacingGameTest.java
> +	}
검증하는 assert 코드가 빠졌네요.😢

2021-11-04 07:12 UTC, testrace commented
질문에 대한 답변입니다.

> 도메인에 getter, setter 를 사용하지 않을 경우 어떻게 테스트 코드에서 검증 할수있을까요?

구현하신 코드를 보니 답을 알고 계신 것 같아요. 😀

이미 getter/setter를 사용하지 않고 프로덕션 코드를 작성하셨는데, 어려움은 없으셨나요? 
프로덕션 코드나 테스트 코드나 어차피 같은 코드라고 생각합니다. 

getter/setter를 사용하는 이유도 생각해 보시면 좋을 것 같아요.

> 또 콘솔에 결과를 출력할때 객체 toString 구현을 이용하는것도 가능한 방법인지 입니다.

출력을 위해서 toString을 재정의 하는 것은 도메인이 ui에 의존하고 있다고 생각되는데요.
ui가 추가 또는 변경되는 경우 발생할 수 있는 문제를 고민해 보시면 좋을 것 같아요!
toString 재정의에 대해서는 이펙티브 자바의 아이템 12번을 참고해보시면 좋을 것 같아요!

2021-11-04 07:55 UTC, csh0034 commented on src/main/java/racingcar/model/Car.java
> +	}
getter, setter를 사용하지 않을 경우 생성자를 private 으로 하면 테스트코드에서 객체 생성을하여 equals 비교를 할 수 없어서 추가했습니다. package-private 이라 해당 패키지 외부에선 생성못하니 테스트를 위한 메서드를 추가하는 방법보다 괜찮다고 생각했습니다.
혹시 private으로 감출경우에 테스트를 위해 값을 비교할수있는 방법이 있을까요?

2021-11-04 07:59 UTC, csh0034 commented on src/main/java/racingcar/model/Position.java
> +	private static final int DEFAULT_POSITION = 1;
Round 의 개념과 혼동해서 1로 추가했습니다. Position 은 0부터 시작하는게 맞는것 같습니다.
다음 커밋시에 반영해두겠습니다. 😃

2021-11-04 08:35 UTC, csh0034 commented
안녕하세요 피드백 해주신 사항 반영하였습니다.
- 말씀해주신 이펙티브자바 아이템 12를 읽어보니, 현재 상태는ToString 을 이용 할 경우 객체의 주요정보를 반환하지 않고 ui 에 종속된 특정포맷을 리턴 하기때문에 사용 의도가 명확하지 않은것 같아 포맷된 형식을 반환하는 메서드를 추가 하는것으로 변경하였습니다.

2021-11-05 02:04 UTC, testrace commented on src/main/java/racingcar/model/Car.java
> +	}
테스트 코드에서 equals 메서드로 비교하기 위해 생성자의 범위를 default로 제한하신 것은 괜찮은 판단이라고 생각합니다. 😀
다만 패키지 구조에 따라 상황이 달라질 수 있을 것 같아요.

질문에 대한 답변으로,
private 생성자 또는 메서드를 테스트 하기 위해서 reflection을 사용하면 가능합니다.
개인적으로 reflection은 단점이 많아 가능한 사용하는 것을 지양하고 있어요.

개인적으로 `public Car(Position position)` 또는 `public static Car from(Position position)` 같이
Position을 직접 주입받는 생성자를 추가하는 방법을 선호합니다.
Model에서 여러 형태의 생성자가 있다면 테스트 코드 뿐만 아니라 프로덕션 코드에서도 객체의 유연성을 제공할 수 있다고 생각해요.

2021-11-05 02:07 UTC, testrace approved these changes
피드백 빠르게 반영해 주셨네요. 👍

한 가지 코멘트 남겨두었으나 다음 단계 진행하시면서
반영해 주시면 될 것 같아 이만 merge 하도록 하겠습니다.

다음 단계 진행 부탁드립니다!

2021-11-05 02:07 UTC, testrace commented on src/main/java/racingcar/exception/UtilCreationException.java
> +	private static final long serialVersionUID = -5133033660004772925L;
예외 클래스 👍

2021-11-05 02:07 UTC, testrace commented on src/main/java/racingcar/model/Position.java
> +	}
toString 메서드의 내용을 분리하셨네요! 👍
다만 여전히 모델이 뷰에 의존하고 있는 코드로 생각됩니다.
이동 거리를 대시가 아닌 다른 기호로 변경하는 요구사항이 추가된다면 뷰와 모델 중 어느 영역에 해당할까요?

2021-11-05 02:07 UTC, merged

2021-11-05 02:38 UTC, csh0034 commented on src/main/java/racingcar/model/Car.java
> +	}
코멘트 감사합니다. 
생성자의 경우에 Car() 생성자 밑에 하단 코드가 있는데 다른 방법인건가요 ?
```java
Car(Position position) {
	this.position = position;
}
```