🚀 2단계 - 문자열 계산기
next-step/java-racingcar pull request #2728
Opened 2021-11-04 05:03 UTC by hiro032

용대님 안녕하세요! 미션을 완료해서 pr 보내 봅니다.
 
저번에 피드백 주신 놓친 테스트도 추가했습니다. 감사합니다.🙏

2021-11-04 06:22 UTC, yongdae requested changes
안녕하세요. 민봉님 ~ :)
문자열 계산기를 잘 구현해주셨네요. 👍 

진행해주신 내용에대해 소소하지만 몇 가지 의견을 드렸습니다.
확인하시고 다시 리뷰요청 부탁드릴께요 ~ 🔥

2021-11-04 06:22 UTC, yongdae commented on src/test/java/step1/StringTest.java
> +    void indexOutOfBoundsExceptionTest() {
이전에 단계에서 이야기 드린 부분도 잊지 않고 테스트해보셨네요. 👍

2021-11-04 06:22 UTC, yongdae commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +class StringCalculatorTest {
미션에서 제시한 내용 외에도 각각 연산이나 예외 사항에 대해서 테스트를 잘 만들어주셨네요. 😄
추가로 미션에서 요구했던 **2 + 3 * 4 / 2** 이 부분을 테스트하는 내용도 넣어보면 어떨까요?

<img width="1037" alt="스크린샷 2021-11-04 오후 3 14 37" src="https://user-images.githubusercontent.com/4317804/140266677-66667886-d032-47c2-ae98-4bf1e7f59a0e.png">

2021-11-04 06:22 UTC, yongdae commented on src/main/java/stringcalculator/StringCalculator.java
> +            Number b = Number.from(split[i +1]);
변수 이름(a, b)을 축약하지 않고 쓰면 더 좋을 것 같은데 어떻게 생각하시나요?

2021-11-04 06:22 UTC, yongdae commented on src/main/java/stringcalculator/Operator.java
> +public enum Operator {
Enum을 활용해서 연산자를 잘 표현해주셨네요. 💯

2021-11-04 06:22 UTC, yongdae commented on src/main/java/stringcalculator/Number.java
> +public class Number {
숫자를 의미하는 Number 객체도 잘 만들어주셨네요. 👍

2021-11-04 06:22 UTC, yongdae commented on src/main/java/stringcalculator/Number.java
> +    }
지금은 숫자(Number)가 연산까지 가지고 있는데 이 부분을 Number 객체 대신 Operator가 가지게 해보면 어떨까요? 🤔

2021-11-04 06:42 UTC, hiro032 commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +class StringCalculatorTest {
아앗 자꾸 하나씩 빼먹네요..! ㅜㅜ

2021-11-04 06:48 UTC, hiro032 commented on src/main/java/stringcalculator/Number.java
> +    }
지금은 새 객체를 리턴해주고있고, Number 객체는 int값을 감싸고 있어서 
Operator에서 연산을 하게 된다면 getter를 사용해서 계산해야 될거같습니다 ㅜㅜ 
혹시 제가 잘못 이해하고 있는걸까요?? 피드백의 의미를 잘 모르겠습니다 😓

2021-11-04 06:48 UTC, hiro032 commented on src/main/java/stringcalculator/Number.java
> +    }
> 지금은 숫자(Number)가 연산까지 가지고 있는데 이 부분을 Number 객체 대신 Operator가 가지게 해보면 어떨까요? 🤔

지금은 새 객체를 리턴해주고있고, Number 객체는 int값을 감싸고 있어서
Operator에서 연산을 하게 된다면 getter를 사용해서 계산해야 될거같습니다 ㅜㅜ
혹시 제가 잘못 이해하고 있는걸까요?? 피드백의 의미를 잘 모르겠습니다 😓

2021-11-04 07:19 UTC, hiro032 commented on src/main/java/stringcalculator/StringCalculator.java
> +            Number b = Number.from(split[i +1]);
마땅한 이름을 떠올리지 못해서 a, b로 지었는데요,,, 
좀 더 의미를 드러내기 위해 first, second로 수정했습니다!

2021-11-04 11:52 UTC, yongdae requested changes
민봉님 빠르게 피드백을 반영해주셨네요. 👍 

소소한 의견이지만 본격적인 자동차 미션으로 넘어가기에 전에
문자 계산기를 마무리 짓는게 좋을 것 같아
한번 더 request change로 진행하도록 하겠습니다. :)

확인하시고 다시 리뷰 요청부탁드릴께요! 🙇

2021-11-04 14:02 UTC, hiro032 commented on src/main/java/stringcalculator/Operator.java
> +    DIV("/", (a, b) -> Number.from(a.getNumber() / b.getNumber()));
수정 완료 했습니다!

2021-11-04 14:03 UTC, hiro032 commented on src/main/java/stringcalculator/Operator.java
> +    private final String operator;
모호한 변수명이네요 ㅜ 수정 완료 했습니다!

2021-11-04 14:26 UTC, hiro032 commented on src/main/java/stringcalculator/Operator.java
> +    public static Number calc(String operation, Number a, Number b) {
> **계산식을 가지는 것**은 좋지만 **계산식을 수행하는 것** 까지 가지고 있을지 고민이 필요해보이는데 어떻게 생각하시나요? 🤔
> 피드백 주신 다른 부분을 다 수정했지만 이 부분이 잘 이해가 가지 않아서 댓글 남겨봅니다! 
제 생각은 계산식을 가지고 있는 클래스에서 계산식을 수행한다는게 맞다고 생각되는데요,,, 계산식의 수행을 다른곳에서 진행하게 되면 해당 심볼(+, -, 등등)에 해당하는 BiFunction을 꺼내서 외부에서 apply()를 하라는 의미일까요..? 😓

2021-11-05 01:07 UTC, yongdae commented on src/main/java/stringcalculator/Operator.java
> +    public static Number calc(String operation, Number a, Number b) {
지금 반영해주신 방향이 맞습니다. :)

이전에는 계산식을 매개변수로 받아 Operator가 실행시켜주는 구조였다면
지금은 Operator가 실행 될 뿐 계산식을 수행시키는 부분은 StringCalculator에 있는 구조입니다.

2021-11-05 01:14 UTC, yongdae approved these changes
의견드린 부분을 잘 반영해주셨네요. 👍 

그럼 다음 단계로 넘어가서 본격적으로 자동차 미션을 하러 가보시죠!! 🔥🔥
소소하지만 의견을 드린 부분이 있으니 다음 단계에서 반영 부탁드려요.

수고하셨습니다.

2021-11-05 01:14 UTC, yongdae commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +    void calcTest(String s, int expected) {
<img width="1701" alt="스크린샷 2021-11-05 오전 10 10 03" src="https://user-images.githubusercontent.com/4317804/140441592-e6ec43dd-0168-4f94-b28e-8c97771fa27d.png">

테스트를 통과하지 못하는 부분이 있네요. 😢

2021-11-05 01:14 UTC, yongdae commented on src/main/java/stringcalculator/Operator.java
> +    public Number calculate(Number first, Number second) {
피드백을 잘 반영해주셨네요. 👍

2021-11-05 01:14 UTC, yongdae commented on src/main/java/stringcalculator/StringUtils.java
> +    public static String[] split(String s) {
여기서도 변수 이름을 축약하지 않고 사용했다면 좋았을 것 같아요. :)

2021-11-05 01:14 UTC, merged

2021-11-05 01:15 UTC, hiro032 commented
> 의견드린 부분을 잘 반영해주셨네요. 👍

감사합니다 ㅎㅎ🙏

2021-11-05 01:22 UTC, hiro032 commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +    void calcTest(String s, int expected) {
연산 수행을 실행하는 위치를 옮기면서 생성한 커스텀 익셉션을 사용하지 않았네요!