Step2
next-step/java-racingcar pull request #2737
Opened 2021-11-04 14:34 UTC by jiseok-choi

안녕하세요!

기존에 작업하다가 수업듣고 새로 다시 코드 작성을 진행하느라 늦어졌네요

강의 한번 듣고 최대한 의식적인 연습을 하려고 노력했으나

마지막 의식적인 연습 6 부분의 리펙터링하는 부분의 Enum class 를 사용하는 부분이 어려워 해당 부분 피드백을 받고 싶어 리뷰 올립니다.

### 질문 1
주석으로 // 에러나는 코드 메소드 안에 다음과 같은 부분에서 에러가 나는 문제가 있었습니다.
Operation operation = Operation.valueOf(operator);

사칙연산을 Enum class 로 구현하고 주어지는 사칙연산기호에 맞게 Operation 을 컨트롤하는게 어렵습니다.
도움 요청드립니다 ㅜㅜ

### 질문 2 (추가질문)
MyNumber class 에서 파라미터로 받은 MyNumber.getNumber() 는 왜 되지 않는지 궁금합니다.
(그냥 파라미터.number 하면 되기에 해당 부분은 에러없이 진행하였습니다)

2021-11-05 00:53 UTC, yongdae requested changes
안녕하세요. 지석님! :)
열심히 문자열 계산기를 만들어주셨네요. 👍 

의견 주신 부분에 대한 답변을 포함해 리뷰를 진행하였습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요. 🔥

2021-11-05 00:53 UTC, yongdae commented on src/test/java/study/StringTest.java
> +    void splitOne() {
이전 단계에서 의견 드린 부분을 잘 반영해주셨네요. 👍

2021-11-05 00:53 UTC, yongdae commented on src/test/java/study/StringTest.java
> +    @DisplayName("split-1")
@DisplayName은 한글을 사용해서 작성해주셔도 좋습니다. :)

2021-11-05 00:53 UTC, yongdae commented on src/test/java/study/SetTest.java
> +    @CsvSource(value = {"1&true", "2&true", "3&true", "4&false", "5&false"}, delimiter = '&')
delimiter도 사용해주셨네요!

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Calculator.java
> +        Operation operation = Operation.valueOf(operator);
Q.
주석으로 // 에러나는 코드 메소드 안에 다음과 같은 부분에서 에러가 나는 문제가 있었습니다.
Operation operation = Operation.valueOf(operator);

사칙연산을 Enum class 로 구현하고 주어지는 사칙연산기호에 맞게 Operation 을 컨트롤하는게 어렵습니다.
도움 요청드립니다 ㅜㅜ

A.
Enum.valueOf()를 이용해서 원하시는 Operation을 반환을 하려면 문자값과 Operation의 값이 동일해야 합니다.

<img width="527" alt="스크린샷 2021-11-05 오전 9 29 17" src="https://user-images.githubusercontent.com/4317804/140438612-3e87e795-98da-4bc6-ac11-9c11a028dccf.png">

이렇게 정의되지 않고 

<img width="478" alt="스크린샷 2021-11-05 오전 9 29 42" src="https://user-images.githubusercontent.com/4317804/140438649-132ae3f3-c5bc-481f-954d-2852d6396530.png">

이런 형태(Enum 값과 텍스트 값이 동일)로 정의되어야만 원하시는 대로 Enum.valueOf()가 동작하기 때문에
산술 연산자를 값으로 사용하는 Operation는 Enum.valueOf()를 이용해서 올바른 값을 반환할 수 없습니다.

지금과 같은 상황에서는 Operation에  Operation을 반환하는 메서드를 별도로 정의해주시는게 좋습니다. 😄 

<img width="550" alt="스크린샷 2021-11-05 오전 9 34 43" src="https://user-images.githubusercontent.com/4317804/140439011-86a05a92-f14c-4d3f-9f06-2748bd3a4bd1.png">

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/MyNumber.java
> +    }
Q.
MyNumber class 에서 파라미터로 받은 MyNumber.getNumber() 는 왜 되지 않는지 궁금합니다.
(그냥 파라미터.number 하면 되기에 해당 부분은 에러없이 진행하였습니다)

A.
테스트를 해보니 잘 된다고 판단되는데 어떤 부분이 문제이신지 잘 모르겠어요. 😢
<img width="1539" alt="스크린샷 2021-11-05 오전 9 40 33" src="https://user-images.githubusercontent.com/4317804/140439436-ad1f2a16-5420-4312-bc1a-f0cbcb38ce80.png">

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Calculator.java
> +        String[] values = text.split(" ");
" "은 매직 리터럴로 보이는데 상수로 선언해서 사용해보면 어떨까요?

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Calculator.java
> +        }
+, -, *, / 와 같은 값은 Operation으로 대체해보면 좋을 것 같아요!

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Calculator.java
> +        if (second == 0) {
0은 매직 넘버로 보이는데 상수로 사용해보면 좋겠어요.

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Calculator.java
> +        }
이 부분의 +, -, *, / 도 Operation을 사용하게 바꿔보면 좋겠어요. :)

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/MyNumber.java
> +    public MyNumber(String s) {
규칙 5: 줄여쓰지 않는다(축약 금지).

이 규칙을 적용해서 s처럼 매개 변수 이름을 축약하지 않고 사용하는게 좋을 것 같아요.

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/MyNumber.java
> +    }
이 부분은 Calculator와 중복되는 부분으로 보여요.

2021-11-05 00:53 UTC, yongdae commented on src/main/java/calculator/Operation.java
> +public enum Operation {
Enum을 이용해서 연산자를 잘 만들어주셨네요. 💯

2021-11-05 00:53 UTC, yongdae commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
미션에서 요구했던 사칙연산에 대한 테스트를 추가해주세요! :)

<img width="997" alt="스크린샷 2021-11-05 오전 9 47 10" src="https://user-images.githubusercontent.com/4317804/140439889-b0f0f95f-ac9c-43b9-8fdf-42bbffaecb01.png">

2021-11-05 00:53 UTC, yongdae commented on src/test/java/calculator/MyNumberTest.java
> +    }
MyNumber도 산술 기능을 가지고 있어야 할 이유가 있을까요? 🤔

2021-11-05 00:53 UTC, yongdae commented on src/test/java/calculator/MyNumberTest.java
> +    }
Operation에 대한 테스트를 만들고 이 부분을 옮겨보면 어떨까요?

2021-11-06 08:40 UTC, jiseok-choi commented on src/test/java/study/StringTest.java
> +    void splitOne() {
감사합니다!

2021-11-06 08:41 UTC, jiseok-choi commented on src/test/java/study/StringTest.java
> +    @DisplayName("split-1")
넵 다음 테스트때는 더 알기 쉽게 작성하겠습니다~

2021-11-06 08:41 UTC, jiseok-choi commented on src/test/java/study/SetTest.java
> +    @CsvSource(value = {"1&true", "2&true", "3&true", "4&false", "5&false"}, delimiter = '&')
넵~!!

2021-11-06 08:42 UTC, jiseok-choi commented on src/main/java/calculator/Calculator.java
> +        Operation operation = Operation.valueOf(operator);
감사합니다 Enum class 에 대한 이해도가 낮아서 많이 배울수 있었습니다
의견주신대로 별도 메서드를 통해서 사칙연산 객체를 반환할 수 있게 수정하였습니다!

2021-11-06 08:43 UTC, jiseok-choi commented on src/main/java/calculator/MyNumber.java
> +    }
해당 부분은 제가 과제를 수행 중 리팩토링하여 생긴 중복되는 부분을 version 별로 분리하여 별도 테스트 진행했더니 문제 없이 테스트가 돌아갔습니다. 감사합니다

2021-11-06 08:43 UTC, jiseok-choi commented on src/main/java/calculator/MyNumber.java
> +    }
넵 감사합니다

2021-11-06 08:43 UTC, jiseok-choi commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
추가하였습니다!

2021-11-06 08:44 UTC, jiseok-choi commented on src/test/java/calculator/MyNumberTest.java
> +    }
다시 살펴보니 Operation 에 별도 사칙연산 기능이 있기에 불필요한 산술 기능인것 같습니다!

2021-11-06 08:45 UTC, jiseok-choi commented on src/test/java/calculator/MyNumberTest.java
> +    }
넵 수정하였습니다!

2021-11-06 12:09 UTC, yongdae requested changes
지석님! 주말에도 열심히 미션을 진행해주셨네요. 🔥 🔥 

다음 단계로 넘어가는 것도 좋지만 조금은 마무리 짓는게 필요해보여서
일단은 request change로 진행하도록 하겠습니다.

진행해주신 내용에 대해 다시 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요! 😄

2021-11-06 12:09 UTC, yongdae commented on src/main/java/calculator/ver3/Operation.java
> +
```suggestion
        PLUS("+", (x, y) -> x + y),
        MINUS("-", (x, y) -> x - y),
        MULTIPLY("*", (x, y) -> x * y),
        DIVIDE("/", (x, y) -> x / y);

        private String symbol;
        private BiFunction<MyNumberVer3, MyNumberVer3, MyNumberVer3> expression;

        Operator(String operator, BiFunction<MyNumberVer3, MyNumberVer3, MyNumberVer3> expression) {
            this.symbol = operator;
            this.expression = expression;
        }
```

람다와 BiFunction을 이용하면 이런 형태로 간결하게 코드를 만들 수 있어요.
이 부분은 학습에 도움이 되셨으면 하는 바램에 드리는 의견이니 반영하지 않고 그렇구나 정도로 이해하고 넘어가셔도 괜찮습니다. 😄

2021-11-06 12:09 UTC, yongdae commented on src/main/java/calculator/ver3/Operation.java
> +        for (Operation op : Operation.values()) {
규칙 5: 줄여쓰지 않는다(축약 금지).

이 규칙을 적용해서 변수 이름을 축약하지 않고 사용하는게 좋을 것 같아요.

2021-11-06 12:09 UTC, yongdae commented on src/main/java/calculator/ver3/Operation.java
> +            }
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

들여쓰기가 2번 사용되었어요!. 이 규칙을 적용해보면 어떨까요?

2021-11-06 12:09 UTC, yongdae commented on src/main/java/calculator/ver3/Operation.java
> +            throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
0과 에러 메시지는 상수로 치환할 수 있을 것 같아요!

2021-11-06 13:41 UTC, jiseok-choi commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +        List<String> values = Arrays.asList(text.split(" "));
풀리퀘스트 화면이 익숙치 않아서 접혀진 부분을 그냥 놓치고 간 부분이 많은것 같습니다 다시 보니 이전에 피드백 주신부분을 지금 확인하고 반영합니다.!!

2021-11-06 13:42 UTC, jiseok-choi commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +        MyNumberVer3 first = new MyNumberVer3(values.get(0)), second;
넵 확인하였습니다! 단순한 네이밍의 상수로 치환하였습니다!

2021-11-06 13:43 UTC, jiseok-choi commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +        int index = 1;
넵!!

2021-11-06 13:45 UTC, jiseok-choi commented on src/main/java/calculator/ver3/MyNumberVer3.java
> +    public MyNumberVer3(String s) {
수정하였습니다~!

2021-11-06 13:47 UTC, jiseok-choi commented on src/main/java/calculator/ver3/MyNumberVer3.java
> +        }
놓쳤던 부분 짚어주셔서 감사합니다!!

2021-11-06 13:49 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +
람다와 BiFunction 을 사용하면 이렇게 간결해지는군요!!
몰랐던 부분이였습니다 감사합니다

2021-11-06 13:51 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +        for (Operation op : Operation.values()) {
축약 금지! 규칙 적용했습니다!

2021-11-06 13:53 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +            }
넵 규칙반영하여 별도의 메서드로 분리하였습니다

2021-11-06 14:00 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +            throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
넵 치환하였습니다!!

2021-11-07 03:07 UTC, yongdae approved these changes
열심히 의견을 반영해주셨네요!! 💯 
그럼 이제 다음 단계로 넘어가서 자동차 경주 미션을 진행하도록 하겠습니다. :)

진행하신 내용에 대해 다시 의견을 남겨 놓은 부분이 있으니
다음 단계에 같이 반영부탁드릴께요~ 🔥 🔥 

수고하셨습니다!

2021-11-07 03:07 UTC, yongdae commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +    private final static String EMPTY_STRING = " ";
EMPTY_STRING 대신 DELIMITER와 같이 의미를 분명히 할 수 있는 변수명을 사용하면 좋을 것 같아요!

2021-11-07 03:07 UTC, yongdae commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +    private final static int ONE = 1;
ZERO, ONE보다 더 좋은 변수 이름은 없을까요?

2021-11-07 03:08 UTC, merged

2021-11-07 03:11 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +            return DIVIDE;
넵 다음 스텝에서 적용하겠습니다~!

2021-11-07 03:12 UTC, jiseok-choi commented on src/main/java/calculator/ver3/Operation.java
> +    }
감사합니다~ 자바를 더 공부해야겠네용

2021-11-07 03:13 UTC, jiseok-choi commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +    private final static String EMPTY_STRING = " ";
쓰는곳의 의미를 나타내는 변수명이 좋은거군요!

2021-11-07 03:13 UTC, jiseok-choi commented on src/main/java/calculator/ver3/CalculatorVer3.java
> +    private final static int ONE = 1;
고민해보겠습니다~!