🚗 [자동차 경주] 2단계 - 문자열 계산기
next-step/java-racingcar pull request #2742
Opened 2021-11-04 16:04 UTC by minchoi9509

안녕하세요 리뷰어님!

제가 git이나 테스트 코드 모두 사용 경험이 적어서 잘 하고 있는 건지 잘 모르겠네요😂
사소한 피드백도 좋으니 잘 부탁드립니다!

질문이 두 가지 있는데
1. 테스트 코드 중 blankOrNullTest(String value)  이 테스트가 돌아가지 않는데 혹시 문법적인 오류가 있을까요? 
2.  calculate() 메소드에서는 얼리 리턴을 사용하려고 했습니다. 우선은 방법을 알 수 없어 else 문에서는 의미 없이 -1을 리턴했는데 이렇게 하면 안될 것 같아서 그런데 다른 방법이 있을까요?

2021-11-05 02:52 UTC, SSONG22 requested changes
안녕하세요! 열심히 문자열 계산기 구현 해주셨네요 👍 
질문에 대한 답변은 코멘트로 남겼습니다 :)
확인해보시고 다시 리뷰요청 주세요😊

2021-11-05 02:52 UTC, SSONG22 commented on src/main/java/calculator/Calculator.java
> +            int first = isFirst(i) ? Integer.parseInt(formula.split(" ")[i]) : result;
다음에 할 미션들에서 지켜야 할 규칙 중 `규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.` 라는 내용이 있습니다:)
삼항연산자도 if문과 같은 의미기 때문에 위 규칙에 어긋나게 돼요(2depth) 
미리 연습해서 고쳐봅시다😁 

<img width="610" alt="스크린샷 2021-11-02 오후 9 04 52" src="https://user-images.githubusercontent.com/35327776/140446657-db12b20c-9311-4706-99a5-7fc4430b570d.png">

2021-11-05 02:52 UTC, SSONG22 commented on src/main/java/calculator/Calculator.java
> +        return "".equals(formula) || " ".equals(formula) || formula == null;
String에 빈 문자열을 확인하는 `isEmpty()`, 빈칸으로만 된 문자열을 확인하는 `isBlank()` 메서드도 있답니다 :)

2021-11-05 02:52 UTC, SSONG22 commented on src/main/java/calculator/Calculator.java
> +        if ("+".equals(operation)) {
요부분 코멘트는 질문 주신 2번째 내용에 대한 답변이 될 수 있겠네요:) 
사칙연산외에 다른 연산이 추가된다면 해당 메서드를 고쳐야 하는데, 이 때 발생할 문제점이 무엇일까요? 
지금은 간단한 계산식이기 때문에 코드 한 두줄 수정하는 것이라 생각할 수 있지만, 복잡한 비지니스 로직이라 가정하고 생각해보세요😵 
이 문제를 해결하는 다양한 방법이 있지만 문자열 계산기에서는 `enum` 을 활용해보시는 걸 추천드려요 😊

2021-11-05 02:52 UTC, SSONG22 commented on src/test/java/calculator/CalculatorTest.java
> +    void divideTest() {
0으로 나눌때의 테스트도 추가해보면 좋을 것 같아요:)

2021-11-05 02:52 UTC, SSONG22 commented on src/test/java/calculator/CalculatorTest.java
> +    void blankOrNullTest() {
바로 위 테스트와 동일한 테스트 코드기 때문에 없어도 될 것 같습니다 :)

2021-11-05 02:52 UTC, SSONG22 commented on src/test/java/calculator/CalculatorTest.java
> +    void blankOrNullTest(String value) {
질문해주신 부분인데요, 문법적인 오류도 없고 테스트도 저는 잘 돌아가는 걸로 나옵니다 😅
인텔리제이 문제 같은데  [블로그 링크](https://junho85.pe.kr/1527) 로 해결이 됐으면 좋겠습니다 ㅎㅎ

2021-11-05 17:29 UTC, minchoi9509 commented
리뷰어님! 소중한 피드백 감사드립니다 😊
Enum 클래스에 대해서 존재 자체만 알고 있었지 제대로 사용해보는 건 처음인 것 같습니다. 
자바의 함수형 인터페이스도 익숙지 않아서 시간이 많이 걸리네요!

테스트 코드 잘 나오지 않았던 부분은 분명히 질문 전에 올려주신 링크 수행 뒤에도 잘 되지 않았던 부분인데 오늘 다시 해보니까 잘 돌아가는 것 확인했습니다!

피드백 사항 중에 `isBlank()` 메소드 적용하는 부분도 적용을 하고 싶었는데 이상하게 `formula.isBlank()` 로 적용을 하면 Cannot resolve method 'isBlank' in 'String' 에러가 떠서 우선 기존 방식을 유지하였습니다.
검색해보니까 Java 11이상이면 사용이 가능하다고 하는데 현재 jdk 16 버전 사용하고 있는데 오류가 나는 부분이 이상하네요 ㅠㅠ

좋은 피드백 감사합니다!

2021-11-06 03:04 UTC, SSONG22 approved these changes
안녕하세요 민경님! 열심히 피드백 반영하셨네요 💯 
고생하셨어요, 바로 머지하겠습니다:)
코멘트 하나 남겼으니 확인해보시고, 다음 미션도 화이팅입니다! 😄 💪

2021-11-06 03:04 UTC, merged