Step3 - 자동차 경주
next-step/java-racingcar pull request #2750
Opened 2021-11-05 02:43 UTC by NohYooHan

2021-11-05 10:09 UTC, catsbi requested changes
벌써 3번째 미션을 제출해 주셨군요. 노력하시는 모습에 저도 감동입니다. 😍
몇가지 고민해보면 좋을 내용을 피드백했으니 한 번 확인해보시고 다시 리뷰요청해주시겠어요?
화이팅입니다. 👏

2021-11-05 10:09 UTC, catsbi commented on src/main/java/racingcar/Controller.java
> +public class Controller {
![image](https://user-images.githubusercontent.com/43158866/140493823-b3df910c-bd14-42a3-8eb7-d405e415abec.png)
> MVC Pattern (Simply)

Controller의 역할은 데이터와 사용자 인터페이스의 요소들을 잇는 다리 역할을 하는데 있습니다. 

하지만 현재 이 컨트롤러에서는 사용자인터페이스 역할도 같이 수행하고 있죠. 
한 번 분리해보는건 어떨까요?

2021-11-05 10:09 UTC, catsbi commented on README.md
> +## 요구 사항 정리
개발전에 문서로 생각을 정리하고 (나중에 수정될지라도) 개발 할 부분들을 적어두는건 좋은습관입니다. 👍 👍

2021-11-05 13:28 UTC, NohYooHan commented on src/main/java/racingcar/Car.java
> +    }
1번은 로컬 변수를 선언하여 재생성되지 않도록 수정하였습니다.

다만 2번의 피드백은 동의하기가 힘든데요,
제 의견은 이렇습니다.
* 요구사항 및 제약 조건이 바뀐다면 기능을 수정하고 배포가 필요한 부분입니다. 요구사항은 분명히 상수였는데 개발자가 마음대로 변수로 설계하는게 확장성 있는 설계가 아니라고 생각합니다. 
* 현재의 조건은 "모든 자동차가 동일한 조건으로 움직인다" 입니다. 이는 요구사항을 정확하게 반영하여 구현한 내용이고, 이는 요구사항을 동일하게 이해하고 개발에 참여해야하는 협업 환경에서 필요한 부분이라고 생각됩니다. 향후 "각 자동차가 낼 수 있는 속도가 다르다"라는 요구사항이 생긴다면, Car class의 설정 가능한 attribute로서 업데이트될 수 있다고 생각합니다.

2021-11-05 13:35 UTC, NohYooHan commented on src/main/java/racingcar/RacingGame.java
> +    private final List<Car> cars = new ArrayList<>();
오 좋은 지적 감사합니다!
일급 컬렉션을 사용하는 습관이 잘 안들어있는 것 같습니다.

2021-11-05 13:40 UTC, NohYooHan commented on src/main/java/racingcar/OutputView.java
> +            System.out.print(RACE_PRINT_CHARACTER);
상수명을 한참 생각했는데 스키드마크라는 표현이 있었군요! 감사합니다!

2021-11-05 13:53 UTC, NohYooHan commented on src/test/java/racingcar/RacingGameTest.java
> +        List<Integer> raceResult = racingGame.race();
Result도 일급객체로 감싸도록 하겠습니다

2021-11-05 14:10 UTC, NohYooHan commented on src/main/java/racingcar/Controller.java
> +public class Controller {
리팩토링했는데 한번 확인 부탁드리겠습니다!

2021-11-05 14:12 UTC, NohYooHan commented on src/test/java/racingcar/CarTest.java
> +        assertThat(car.move()).isGreaterThanOrEqualTo(0);
실제 자동차의 이동을 결정하는 currentPosition이 private이고 이를 조작하는 메소드도 private 메소드인데, 
이 때 어떻게 클래스를 확장/재정의하고 fakeObject를 정의할 수 있을까요? 
힌트 부탁드리겠습니다 ㅠ

2021-11-05 14:13 UTC, NohYooHan commented
피드백 감사합니다!
피드백 반영하고 리팩토링, 그리고 질문과 제 의견을 달았습니다! 확인 부탁드리겠습니다!

2021-11-05 15:24 UTC, catsbi commented on src/main/java/racingcar/Car.java
> +    }
> 요구사항 및 제약 조건이 바뀐다면 기능을 수정하고 배포가 필요한 부분입니다. 요구사항은 분명히 상수였는데 개발자가 마음대로 변수로 설계하는게 확장성 있는 설계가 아니라고 생각합니다.

제가 설명을 좀 잘 못 한것 같습니다. 제 피드백의 취지는, 해당 메서드의 경직성을 언급하고자 한 것입니다. 
메서드명은 isMovable입니다. 즉 움직있수 있는지 아닌지를 판단하는 메서드라는 의미죠. 
여기서 메서드명 어디에도 랜덤값이 1~9사이로 나오면 4이상일 경우 true를 반환한다는 의미를 내포하지 않습니다. 
그렇다면, 메서드명을 위 의미를 다 포함하도록 변경해야할까요? 

마틴 파울러의 `클린코드`에서는 이렇게 말합니다.  ([링크](https://catsbi.oopy.io/b67245f8-2bd5-414b-bde0-39bb49787cc3))
> 나쁜 코드의 책임에서 개발자는 벗어날 수 없다. 
> 일정 문제를 조율하지 못하는 개발자는 아마추어다.
> 나쁜 코드의 위험을 예견하지 못하는 관리자 말을 그대로 따르는 행동은 프로가 아니다.

> 고객사와 PM(프로젝트 관리자)이 요구사항과 일정을 잡으며 개발자에게 요구를 하지만, 프로젝트에 깊숙히 관여한건 개발자도 포함된다. 고객사와 PM은 자신의 임무를 다한 것이고 우리는 우리의 임무와 책임(좋은 코드를 사수하는 일)를 다해야 한다. 

즉, 우리는 모든 코드는 아닐지라도 변경가능성이 높은 비즈니스 로직 메서드에 대해서는 변화에 취약하지 않은 확장성있는 코드를 만들 필요가 있습니다. 

유한님의 의견 역시 클린코드의 내용 중 다음 내용을 보면 일치합니다. 
> 가독성이 좋은 코드를 작성하자. 
> 코드는 추측이 아닌 사실 기반으로 반드시 필요한 내용만 담아야 한다. 

요구사항이 변경되는건 우리의 추측이기에 굳이 확장성을 고려할 필요가 없다고 생각할 수 있습니다. 

하지만 이런 확장성 여부를 떠나서 해당 메서드는 현재 추상화가 덜 되어있는 구현 메서드입니다. 
움직일지 말지를 확인하는 메서드이지 값이 4이상인지 아닌지를 결정하는 메서드가 아닌 것이죠. 
저는 그렇기에 isMovable 메서드는 이동할 수 있을지 없을지에 대해서만 책임이 있고, 실제로 이게 이동을 할 지 말 지 결정하는건 MoveStrategy 혹은 MovableSupplier같은 인터페이스의 구현체가 결정할일이 아닌가 싶습니다. 

유한님은 개발에 대해 깊게 고민하시고, 자신의 생각을 어필하시는 모습이 너무 보기 좋습니다.👍 
저도 많이 배우고 갑니다. 😄

2021-11-05 15:27 UTC, catsbi commented on src/test/java/racingcar/CarTest.java
> +        assertThat(car.move()).isGreaterThanOrEqualTo(0);
위에서 유한님이 피드백주신 내용과 연관되어있는데요, 저는 isMovable은 이동을 할 지 말지에 대한 논리 값 반환의 책임만 있다고 생각하고 실제로 그 내부 구현은 MoveStrategy와 같은 인터페이스를 활용하여 FakeObject 구현체를 만들어 
테스트용 동작을 제어하는 방식과, 그 다음으로 Mocking을 이용하는 방식을 고려하고 있었습니다. 👴

2021-11-05 15:31 UTC, catsbi commented
> 피드백 감사합니다! 피드백 반영하고 리팩토링, 그리고 질문과 제 의견을 달았습니다! 확인 부탁드리겠습니다!

현재 리팩토링된 소스파일 커밋이 안된 것 같습니다 ㅠㅠ

2021-11-07 15:28 UTC, NohYooHan commented on src/main/java/racingcar/Car.java
> +    }
아 그렇군요! 저는 자동차라는 클래스 내부에서 이동에 대한 책임을 갖고있으면 된다고 생각했는데,
제안하신 방법처럼 인터페이스를 활용하여 책임을 더 세부적으로 분리하는 것에 대해 이해가 됐습니다. 
좋은 피드백 감사합니다!

2021-11-07 15:29 UTC, NohYooHan commented
다시 MoveStrategy를 추가하여 푸시했습니다! Controller에 대한 리팩토링을 한거였는데 혹시 제가 잘못된 방향으로 리팩토링한걸까여?

2021-11-08 05:21 UTC, catsbi approved these changes
피드백 적용에 고민을 많이하시고 유한님 스타일의 코드를 잘 녹여내신것 같습니다. 👍 
디자인패턴을 유도한것은 아니지만, 바로 적절하게 리팩토링하셔서 패턴까지 적용하시는게 좋았습니다.
코드에 대한 피드백은 각각 코멘트를 달아놨습니다. 한 번 고민해보시고 다음 미션에서는 적용해보도록 합시다. 
그리고 전체적인 피드백을 몇가지 드리자면, 다음과 같습니다. 

1. 테스트의 범위를 좀 더 풍부하게 할 필요가 있습니다.  잘되는 몇몇 케이스만 가지고 테스트를 끝냈다고하면, 해당 메서드가 안전하다는 보장을 할 수 없겠죠. 
2. 비즈니스 로직이 있는 public 메서드는 모두 테스트가 진행되어야 합니다. 즉, 지금 View Layer나 일급 컬렉션 등등 비즈니스 로직들이 산재해있는데 이런 모든 로직에 대한 테스트가 수행되야한다는 것이죠. 
(그전에 View Layer에 비즈니스 로직이 있어선 안되겠죠.)

그럼 다음 리팩토링은 다음 미션에서 해보는 걸로 하고 이번 미션은 여기서 merge 하도록 하겠습니다. 
3단계 미션 진행하느라 수고하셨습니다.

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/Controller.java
> +public class Controller {
제가 말한 MVC 구조는 MainApplication이 Root로써 프로그램을 실행하면 여기서 컨트롤러의 게임 진행 메서드를 호출함으로써 시작하고 출력되는걸 말한 것이였는데 여긴 아직 Controller가 Main Application 역할도 겸하고 있네요 ㅎㅎ.
다음 미션에서는 한 번 분리해보세요!

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/Controller.java
> +        outputView.printPlayRacing();
코드를 보니 View Layer에서 서비스 로직까지 같이 수행하고 있습니다. 
View Layer에서는 View에 관련된 책임(입력/출력)만 할 수 있도록 해주세요. 
비즈니스로직은 서비스 레이어에서 수행하는게 맞지 않을까요?

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/RacingGame.java
> +            carList.participate(new Car(new RandomMoveStrategy()));
RandomMoveStrategy는 모두 동일하게 사용하는 재활용 가능한 전략 객체인데 자동차마다 새로 생성해 줄 필요가 있을까요?

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/RacingGame.java
> +        return carList.moveAll();
이걸로도 충분하지만, 그래도 좀 심화과정으로 이야기를 하자면, 자동차 일급 컬렉션은 모두 전진 시켜야 할 책임까지는 없습니다. 
자동차 도메인 목록을 관리하고 추가/수정/제거 정도만해도 충분하죠. 실제 자동차들이 전진하라는 명령을 내리는건 서비스 레이어가 좀 더 적절합니다. 일급 컬렉션은 그 명령을 전달해주기만 하면 되는 것이죠.

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/collection/RacingResult.java
> +        return positions;
List를 그대로 반환해주면 final 키워드를 사용했더라도 내용 변화에대해서는 대처가 불가능합니다. 
final은 List 자료구조가 위치한 인덱스를 변경 못하는 것이지 내부의 값들을 변경못하는게 아니기 때문이죠. 
그럼 어떻게 해야할까요? 고민해보면 좋은 시간이 될 것입니다.

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/model/RacingGameRequest.java
> +    private int countOfTry;
변화 가능성이 없는 DTO의 필드면 final을 붙혀 불변성을 확보해도 되지 않을까요?

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/strategy/MoveStrategy.java
> +    public boolean strategicMove();
interface의 메서드는 public이 자동으로 붙기에 생략해주셔도 됩니다.

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/view/OutputView.java
> +    private final int countOfTry;
View Layer에서 가질만한 상태들이 아닙니다. OutputView는 출력만 잘 하면 됩니다.

2021-11-08 05:21 UTC, catsbi commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
StringBuilder가 자동차마다 생성되어 출력되고 있는데, 하나로 통합할 순 없을까요?

2021-11-08 05:21 UTC, catsbi commented on src/test/java/racingcar/CarTest.java
> +    public void 테스트_Car_move() {
car.move()가 여러번 호출되면 여러번 모두 제대로 증가되는지에 대한 테스트가 부족합니다.

2021-11-08 05:22 UTC, merged