🚀 [자동차 경주] 3단계 -  자동차 경주
next-step/java-racingcar pull request #2761
Opened 2021-11-05 16:44 UTC by kdhyo

리뷰어님 안녕하세요!!
3단계 구현 완료하여 PR 요청 드립니다.

저번에 늦은 시간까지 피드백을 주셔서 정말 감사했습니다!!

이번 구현하면서 랜덤 값 때문에 통합 테스트를 어떤 방향으로 짜야 할 지 조금 고민이 되더라구요...
그래서 일단은 랜덤을 제외한 단위로만 테스트 코드를 작성해 보았습니다.. 맞는지 모르겠네요..😅😅

또 나름대로 역할을 나누긴 했는데, Service 와 CarRacing 객체와의 역할을 분리한 게
너무 CarRacing 객체로 치우친 건 아닌가 싶기도 합니다.. ㅜ

진행하면서 이것저것 고민이 많아서 얘기가 좀 길었네요..하하
이번 PR도 잘 부탁드립니다! 감사합니다!! 😆😆

2021-11-06 13:08 UTC, liquidjoo requested changes
2단계 피드백 반영과 3단계 미션 너무 잘 구현해주셨어요 👍 
몇 가지 코멘트를 남겼어요
확인하고 다시 요청 주세요~
진행하면서 어려움이 있다면 언제든 DM 주세요 🙇

2021-11-07 12:13 UTC, kdhyo commented
리뷰어님 ! 피드백 감사합니다.
피드백 해주신 내용 반영하여 다시 리뷰요청 드립니다.

진행하다 보니 main 메소드 경우는 inputView를 호출하고, 비지니스를 호출하고, resultView를 호출하다 보니
절차지향처럼 느껴지게 되었는데.. 맞게 한 건지 모르겠어요 ㅠㅠ..

피드백 해주신 내용 중 매직넘버들을 각각 사용 객체로 빼서 사용해보았는데,
예외 메세지 같은 경우는 메세지들을 한 곳에 모아두는 게 더 깔끔할 것 같아서
따로 모아두는 방식을 유지했는데 괜찮을까요? 아니면 메세지들 또한 각각의 객체로 빼는 게 좋을까요?

2021-11-08 10:52 UTC, liquidjoo approved these changes
3단계 피드백 반영 너무 고생하셨어요~
몇가지 생각해볼 코멘트를 남겼어요!! 다음 단계에 반영해보면 좋을 것 같네요 :)
다음 단계 진행해주세요 🙇

2021-11-08 10:52 UTC, liquidjoo commented on src/main/java/carracing/model/Car.java
> +    private RacingHitory racingHitory;
```suggestion
    private RacingHitory racingHistory;
```
오타가 있는 것 같아요~

2021-11-08 10:52 UTC, liquidjoo commented on src/main/java/carracing/model/Car.java
> +    }
두 메서드의 단위테스트를 어떻게 할 수 있을까요?

2021-11-08 10:52 UTC, liquidjoo commented on src/main/java/carracing/model/Car.java
> +public class Car {
`Car` 도메인에 대한 단위테스트가 더 있으면 좋을 것 같아요 :)

2021-11-08 10:52 UTC, liquidjoo commented on src/main/java/carracing/CarRacingMain.java
> +        carRacingService.gameStart();
`Service` 에 리턴 값이 없어서 조금 어색 한 것 같아요~
백엔드에서 웹 프로그래밍의 플로우를 생각해보면 좋을 것 같네요!!

2021-11-08 10:52 UTC, liquidjoo commented on src/main/java/carracing/util/ExceptionUtils.java
> +public class ExceptionUtils {
Utils 같은 경우는 상수에 대한 중복이 많을 때 사용한는 것이 좋다고 생각을해요~
그렇지 않다면 각 객체에서 보는게 더 직관적일 것 같아요!

2021-11-08 10:52 UTC, merged