Step3 - 자동차 경주
next-step/java-racingcar pull request #2778
Opened 2021-11-07 07:44 UTC by jyami-kim

감사합니다.

아래와 같은 클래스 구조를 갖고있습니다.
![image](https://user-images.githubusercontent.com/26458200/140636699-47d9f6e9-d093-4be6-9478-06140365f0c7.png)

**참고사항**
- car의 identify 변수를 만들고 싶어서 멤버변수로 추가를 했음 : 그러나 현재 요구사항에서는 쓰이지 않음 > 추후 요구사항에서의 확장을 생각하여 정의
- history에 round 멤버변수. 각 history간의 순서를 저장하는 용도로 정의하였음 : 그러나 코드에서 해당 멤버변수를 이용한 조작이 없음 > 후에 요구사항에서 정렬에 대한 요구사항이 생길 경우를 대비하여 만든 변수

2021-11-07 15:36 UTC, heesunjeong requested changes
3단계 미션도 깔끔하게 잘 구현해주셨네요 👍 
몇가지 참고해보시면 좋을 것 같은 부분을 코멘트로 추가했는데요, 반영해보시면 좋을 것 같습니다!
진행하시면서 궁금하신 점이 생기면 언제든 코멘트나 DM으로 남겨주세요~!

2021-11-08 04:47 UTC, jyami-kim commented on src/main/java/com/kakao/racingcar/domain/Car.java
> +    public void tryMove(int conditionNumber) {
차가 움직일수 있는 조건을 CarConfig 객체로 관리하게 되어있는데요.
말씀하신대로 현재 같은경우 Car 도메인 수정 없이 유연하게 변경할 수 있게 위와같은 Config 클래스로 뺐습니다. (application.yml 과 같이 설정값들을 관리하는 파일과 같이 생각한게 의도였습니다.)

추상화를 어떤식으로 하는걸 의미하시는건지 의도와 목적을 잘 모르겠습니다. 좀 더 자세히 풀어써주시거나, 예제코드 또는 의도를 알려주시면 좋을 것 같습니다.

2021-11-08 14:52 UTC, heesunjeong approved these changes
피드백 반영 잘 해주셨습니다 👍 
질문주신 부분에 대해서 관련한 부분에 코멘트 추가했는데요, 확인해보시고 다음단계에 반영해보시면 좋을 것 같습니다. 만약 다른 의견이 있으시다면 함께 이야기를 더 해봐도 좋을 것 같아요 :)
이어서 다음 단계도 진행해주시면 됩니다~!

2021-11-08 14:52 UTC, heesunjeong commented on src/main/java/com/kakao/racingcar/domain/Car.java
> +    public void tryMove(int conditionNumber) {
지금은 랜덤한 값이 4보다 큰 경우에 움직이지만 차가 움직이는 조건이 달라진 게임도 진행해야한다면 해당 객체가 수정 되어야겠죠?
이에 대해서 확장성을 고려하여 구현을 고민해보셨으면 하는 의도였습니다~ 이때는 차가 움직이는 조건에 대하여 추상화하고 사용하는 조건을 주입받아서 사용할 수 있도록 전략패턴을 사용해서 구현해보는 방법은 어떨까요? :)

2021-11-08 14:52 UTC, merged

2021-11-09 00:28 UTC, jyami-kim commented
안녕하세요 희선님. 사실 해당 케이스에 왜 전략패턴을 사용해야하는지 잘 모르겠습니다.
만약 제가 Car 구현을 아래와 같이 내부 상수로 4를 정의했다면, 말씀하신대로 행동을 다르게 하기위해 전략패턴을 사용하는 건 괜찮아 보입니다.

그러나 현재 Car내부의 상수가 아닌, Config에서 상수를 받아오고있는 상황에서 왜 전략패턴으로 가야하는지 잘 이해가 안갑니다. 차가 움직이는 조건에 대해 객체로 관리하자는 말로 보이는데, 학습이니까 여러 시도를 해보는건 좋지만 실제 케이스에서 조건까지 객체로 만들어버리는건 오히려 관리를 힘들게 만드는건 아닐까 싶습니다.

### 현재 상황
```java
public class Car {
    private final int identify;
    private int position = 0;

    public Car(int identify) {
        this.identify = identify;
    }

    public int getPosition() {
        return position;
    }

    public void tryMove(int conditionNumber) {
        if (CarConfig.MOVE_PERCENTAGE <= conditionNumber) {
            position++;
        }
    }

    public int getIdentify() {
        return identify;
    }
}
```

### 전략 패턴을 사용해야하는 경우의 Car 클래스 정의

```java
public interface MovementCar {
    void tryMove(int conditionNumber);
}

public class EasyCar implements MovementCar {

    private final int identify;
    private int position = 0;

    private static final int MOVE_CONDITION = 4;

    public EasyCar(int identify) {
        this.identify = identify;
    }

    public int getPosition() {
        return position;
    }

    @Override
    public void tryMove(int conditionNumber) {
        if (MOVE_CONDITION <= conditionNumber) {
            position++;
        }
    }

    public int getIdentify() {
        return identify;
    }

}
public class HardCar implements MovementCar {

    private final int identify;
    private int position = 0;

    private static final int MOVE_CONDITION = 8;

    public HardCar(int identify) {
        this.identify = identify;
    }

    public int getPosition() {
        return position;
    }

    @Override
    public void tryMove(int conditionNumber) {
        if (MOVE_CONDITION <= conditionNumber) {
            position++;
        }
    }

    public int getIdentify() {
        return identify;
    }

}

```