3단계 - 자동차 경주
next-step/java-racingcar pull request #2803
Opened 2021-11-08 05:40 UTC by NowHappy

2021-11-08 12:45 UTC, sah3122 requested changes
미션 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요. 🙏 
미션 진행 도중 막히는 부분이나 질문이 있을시 언제든지 편하게 DM 주시면 됩니다 😄

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/CarList.java
> +            cars[i] = canMove()? ++cars[i] : cars[i];
이번 과정을 진행하면서는 삼항 연산자를 사용하기 보다는 조건문을 풀어서 구현해보세요 😄

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/CarList.java
> +    private int[] cars;
CarList 객체는 Car객체를 담고 있는 일급 컬렉션으로 인식될 수 있을것 같아요. 
Car 객체를 생성해보는건 어떨까요 ㅎㅎ 
또한 배열 보다는 리스트 컬렉션으로 구현하여 다양한 기능들을 활용해보세요 😄

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/view/ResultView.java
> +    public void draw(int[] result) {
이번 과정을 진행하면서 들여쓰기는 1로만 유지해보세요. 
자연스럽게 메소드의 크키가 작게 분리 될 수 있을거에요 😄

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +        }
결과값을 나타내는 로직은 ResultView에서만 담당할 수 있도록 변경해보세요 😄

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +    private int movementsCount;
반드시 필요한 상태값인지 고민해보세요 ❓

2021-11-08 12:45 UTC, sah3122 commented on src/test/java/calculator/CalculatorTest.java
>  public class CalculatorTest {
테스트코드가 풍부해졌네요 👍

2021-11-08 12:45 UTC, sah3122 commented on src/main/java/racingcar/CarList.java
> +    private boolean canMove() {
CarList 객체가 자동차의 움직임 여부를 판단하는것은 객체지향적으로 적절하지 않은 설계일것 같아요. 
객체 스스로가 이러한 행위를 할수 있도록 설계를 변경해보세요 !

2021-11-08 12:45 UTC, sah3122 commented on src/test/java/calculator/MyNumberTest.java
> +    @Test
마찬가지로 DisplayName을 명시해주시는것을 권장드립니다 ㅎㅎ
저는 팀원들이 테스트 코드를 확인할 때 쉽게 이해할 수 있을 정도로 작성하고 있어요 !

2021-11-13 08:07 UTC, NowHappy commented on src/main/java/racingcar/CarList.java
> +public class CarList {
자료형을 썻다기보단 복수형을 나타내고 싶어서 list라고 썻어요.
생각해보니 List라는 자료형이 있기 때문에  자료형으로 생각될 수도 있어서 좋지 않은 것 같아요. 
자료형을 의미한 경우면 자료형을 수정했을때 클래스명도 같이 수정해야 하는 번거로움이 있을 것 같아요!

2021-11-14 10:54 UTC, sah3122 requested changes
피드백 반영 잘해주셨네요 👍 
추가적으로 도전해보시면 좋을 내용들을 남겨두었어요. 🙏 
확인 부탁드립니다 😄

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/Car.java
> +        if(this.random.nextInt(range) > cutline) {
랜덤값과 같이 실행시점에 결정되는 값을 그대로 사용한다면, 테스트 하기 어려우실거에요. 
이러한 값들은(LocalDateTime.now() ... ) 외부에서 주입 받는 구조로 많이 사용하곤 합니다. 
이번 과정을 진행하면서는 자동차 움직임을 결정 짓는 전략객체를 생성하여 사용해보는것을 권장 드려요 😄 
https://niceman.tistory.com/133

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/Game.java
>  public class Game {
Game클래스가 너무 많은 역할을 하고 있는것 같아요. 
자동자 경주를 위해 필요한 값을 자동차 게임을 실행하는 새로운 객체로 전달하고, 게임을 실행, 결과값을 ResultView 객체로 전달하는 역할만 할 수 있도록 구현해보세요 😄 
이렇게 구현한다면 구조적으로 어떤 장점을 갖게 되는지도 고민해보세요 🙏

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +    private void roundOne() {
해당 메소드는 자동차 경주를 실행하는 메소드인데, roundOne이라는 메소드는 그 의미를 충분히 타나내지 못하는것 같아요. 
다른 메소드명을 고민해보세요 😄

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +    private final static int STEP = 1;
상수는 그값을 사용하는 곳에서 선언하는것이 어떨까요 ?

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/view/ResultView.java
> +        for (int i = 0; i < movement; i++) System.out.print(MOVEMENT);
이번 과정에서는 한줄짜리 코드도 중괄호를 생략하지 않고 작성해보세요. 
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2021-11-14 10:54 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +    private List<Car> cars = new ArrayList<>();
일급 컬렉션의 의미를 알고 계신것 같은데, 작성한 코드를 지우지 않고 다시 구현해보는것을 권장 드립니다 :) 
일급 컬렉션을 사용한다면 불필요한 메소드를 제공하지 않고 도메인 기능을 정의 할 수 있게 됩니다. 
https://jojoldu.tistory.com/412

2021-11-17 13:46 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
몇가지 코멘트를 남겨두었는데 다음 미션을 진행하면서 반영부탁드려요 😄

2021-11-17 13:46 UTC, sah3122 commented on src/main/java/racingcar/Car.java
> +    private final static int STEP = 1;
자바의 접근제어자는 아래 순서로 선호하는것이 컨벤션 입니다 😄 
```suggestion
    private static final int STEP = 1;
```
https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers

2021-11-17 13:46 UTC, sah3122 commented on src/main/java/racingcar/MovingStrategy.java
> +public interface MovingStrategy {
메소드를 하나만 제공하는 인터페이스는 @FunctionalInterface 로 선언하는것이 어떨까요 ? 
IDE에서 다른 메소드가 추가되는것을 막을수 있답니다 😄

2021-11-17 13:46 UTC, sah3122 commented on src/test/java/racingcar/CarTest.java
> +        MovingStrategy strategy = new RandomMovingStrategy(0); // 테스트 결과 고정하기 위해 seed 지정
자동차의 움직임을 테스트 하기 위해 랜덤 움직임 전략 객체를 사용하는것 보다 항상 움직이거나 항상 움직이지 않는 객체를 테스트 패키지에 정의하는것을 권장 드려요 😄

2021-11-17 13:46 UTC, sah3122 commented on src/main/java/racingcar/RandomMovingStrategy.java
> +    }
프로덕션 코드에 테스트를 위한 코드가 반영되는것은 권장하지 않아요 ! 
다른 코멘트를 참고해주세요 😄

2021-11-17 13:46 UTC, sah3122 commented on src/main/java/racingcar/Game.java
> +        this.strategy = new RandomMovingStrategy(randomSeed);
반드시 필요한 생성자 일까요 ? 
다른 코멘트를 참고해주세요 🙏

2021-11-17 13:46 UTC, sah3122 commented on src/main/java/racingcar/RandomMovingStrategy.java
> +public class RandomMovingStrategy implements MovingStrategy {
전략 객체 정의 좋습니다 👍

2021-11-17 13:46 UTC, merged