4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2827
Opened 2021-11-09 13:14 UTC by doorisopen

안녕하세요 리뷰어님~ 😃
4단계 - 자동차 경주(우승자) 리뷰 요청드립니다. 
감사합니다.

2021-11-10 10:20 UTC, liquidjoo requested changes
피드백 반영 및 4단계 미션 구현 잘해주셨어요 👍 
몇 가지 코멘트 남겼어요 ~ 확인하고 다시 요청 주세요 🙇 
진행하면서 어려움이 있거나 궁금한 점이 있으면 언제든 DM 주세요~

2021-11-10 10:20 UTC, liquidjoo commented on src/test/java/step3/domain/CarTest.java
>      void 랜덤_값이_4이상이면_한칸_전진한다() {
테스트를 위한 객체 `MoveNumberGenerator` 는 제거해주는 것이 좋을 것 같아요 :)

https://github.com/next-step/java-racingcar/pull/2785#discussion_r745505688

2021-11-10 10:20 UTC, liquidjoo commented on README.md
>  ## 기능 구현 목록
매번 기능 구현 정리 너무 좋아요 👍

2021-11-10 14:07 UTC, doorisopen commented on src/main/java/step3/domain/Car.java
> +    private String name;
오호 링크 감사합니다!

2021-11-11 12:14 UTC, liquidjoo approved these changes
4단계 피드백 반영 너무 좋았어요 💯 
더 도전해볼 만한 코멘트를 달았어요~
다음 단계 진행해주세요 🙇

2021-11-11 12:14 UTC, liquidjoo commented on src/main/java/step3/domain/Car.java
> +        return copy(this);
`this` 의 활용 👍 
```java
      if (isMove(generator)) {
          position++;
          return new Car(name, position);
      }
      return this;
```
이렇게 활용해도 괜찮을 것 같군요!

2021-11-11 12:14 UTC, liquidjoo commented on src/main/java/step3/domain/Cars.java
> +    public static Cars join(List<Car> carList) {
https://geosoft.no/javastyle.html
2.18 에 보면 컬렉션은 List 보단 복수형으로 사용하는게 더 좋을 것 같아요~

2021-11-11 12:14 UTC, liquidjoo commented on src/main/java/step3/domain/Cars.java
> +        return carList;
`carList` 에 대한 주솟값을 그대로 외부에 전달하면 어떤 문제가 발생할까요?

2021-11-11 12:14 UTC, liquidjoo commented on src/main/java/step3/domain/Participant.java
> +    }
`Cars` 에 더 어울리는 책임이 될 것 같아요~ `Participant` 객체에서 사용할 때 메시지 전달로 협업을 하듯이 만들어보면 어떨까요?

2021-11-11 12:14 UTC, liquidjoo commented on src/main/java/step3/domain/history/GameHistory.java
> +                .map(GameWinner::new)
`GameWinner` 에 로직을 옮겨보면 어떨까요? 어떤 장점이 있을까요?

2021-11-11 12:14 UTC, liquidjoo commented on src/test/java/step3/domain/CarTest.java
> +        car.move(new IntNumberGenerator() {
익명 함수 활용 👍

2021-11-11 12:16 UTC, merged

2021-11-11 12:19 UTC, doorisopen commented on src/main/java/step3/domain/Car.java
> +        return copy(this);
this 자체만 넘기게 되면 객체의 얕은 복사때문에 차동차의 상태값을 출력하는데 문제가 생기더라구요, 마땅히 떠오르는 방법이 없어서 객체를 새로 생성해서 반환하도록 했는데 더 좋은 방법이 있을까요??

2021-11-11 12:21 UTC, doorisopen commented on src/main/java/step3/domain/Cars.java
> +    public static Cars join(List<Car> carList) {
링크 감사합니다! 
기존에 변수명을 cars로 했었는데 객체 이름도 Cars 이다 보니 구분하기 위해서 List를 사용했었습니다. 이럼에도 복수형으로 사용하는게 좋은가요?!

2021-11-11 12:27 UTC, liquidjoo commented on src/main/java/step3/domain/Car.java
> +        return copy(this);
`Car` 의 참조가 이슈가 있었군요!!
매회 마다 확인 할 수 있는 `Cars` 를 새롭게 생성하는 방법이 있습니다 :)
자동차 경주 할 때 마다 결과 값을 저장하는 곳에 데이터를 새롭게 담으면 Car 와 의존이 떨어질 수 있지 않을까요?
Car 의 참조가 결과 값에 미치는 영향을 줄여볼 수 있을 것 같아요~!!

2021-11-11 12:29 UTC, liquidjoo commented on src/main/java/step3/domain/Cars.java
> +    public static Cars join(List<Car> carList) {
Cars 가 조금 특별한 경우이긴 하지만 대체로 복수형을 사용합니다 :)
클래스명과 똑같아서 구분을 주기 위함이었음을 몰랐던 것 같네요!!

2021-11-11 13:03 UTC, doorisopen commented on src/main/java/step3/domain/Cars.java
> +        return carList;
carList에서 car 객체들을 꺼내고 move 메소드를 호출하게되면 값들이 변경될 가능성이 있을 것 같은데 맞을까요?

2021-11-11 14:17 UTC, doorisopen commented on src/main/java/step3/domain/history/GameHistory.java
> +                .map(GameWinner::new)
우승자를 찾는 로직은 GameWinner 객체의 책임인 것 같네요, 장점은 객체의 역할과 책임이 좀 더 명확해지는 것 같습니다.