Step3. 자동차 경주
next-step/java-racingcar pull request #2840
Opened 2021-11-10 02:50 UTC by nelldkLee

코드리뷰 부탁드립니다. 앞선 PR도 확인 부탁드릴게요~
Random값이랑 출력부분이 있어서 TDD를 할 수 있는 부분이 제한적이던데 
추가할 수 있는 포인트가 있는지 확인부탁드릴게요.

2021-11-10 06:17 UTC, dbeod2 requested changes
안녕하세요! 동규님 

자동차 경주 미션 진행 빠르게 해주셨네요👏🏻👏🏻
고민해보면 좋을 것 같은 부분 코멘트로 남겨두었습니다. 
확인해보시고 리뷰 재요청주세요! 🙏

2021-11-10 06:17 UTC, dbeod2 commented on src/main/java/step3/CarGroup.java
> +            car.move(new Random().nextInt(RANDOM_MAX_INT_VALUE));
메소드가 실행될때마다 new Random() 인스턴스가 반복적으로 생성되는 것보다
한개를 만들어 놓고 사용하는게 자원적인 측면에서 더 좋을 것 같아요.🙏

2021-11-10 06:17 UTC, dbeod2 commented on src/main/java/step3/InputView.java
> +    private Scanner scanner;
Scanner 사용 후 꼭 close해주세요~

Scanner 사용 후 종료시 scanner.close(); 를 선언해 암묵적으로 연결을 끊어주어야 합니다.
나중에 리소스 접근이 불가능하거나 connection pool이 꽉 차서 접근이 안되는 경우가 생길 수 있습니다.
그러하므로 I/O사용시에는 연결에 대해 확실하게 끊어줘야 합니다 🙂

2021-11-10 06:17 UTC, dbeod2 commented on src/main/java/step3/RacingSystem.java
> +        new RacingSystem().racingStart();
경주 할 자동차 대수와 이동 횟수에 대한 예외처리가 필요해 보입니다 ~ 
확인 부탁드려요~! 

<img width="400" alt="스크린샷 2021-11-10 오후 3 08 26" src="https://user-images.githubusercontent.com/70149382/141059327-4650932f-b84e-4828-acb4-aea9d6fdf0cb.png">
<img width="400" alt="스크린샷 2021-11-10 오후 3 10 59" src="https://user-images.githubusercontent.com/70149382/141059546-5ea19e30-f339-438f-a10a-6266d9c0ac58.png">

2021-11-10 06:17 UTC, dbeod2 commented on src/main/java/step3/ResultView.java
> +        System.out.println();
이중 for문을 없애려면 어떻게 하면 좋을까요~? 🤔

2021-11-10 06:17 UTC, dbeod2 commented on src/test/java/step2/MyNumberTest.java
> +    @ValueSource(strings = {"", "  "})
@EmptySource 를 활용해보셔도 좋을 것 같습니다!

2021-11-10 06:17 UTC, dbeod2 commented on src/test/java/step3/CarTest.java
> +    void 자동차_앞으로_이동() {
테스트가 조금 부족한 것 같아요~! 
요구사항에 보시면 전진 조건이 4이상인 경우입니다. 
이동조건이 4이상과 이하일 때 테스트도 있으면 좋을 것 같아요!

2021-11-10 06:17 UTC, dbeod2 commented on src/test/java/step2/OperatorTest.java
> +    @Test
피드백 수정에 맞게 잘 작성해주셨네요!

2021-11-11 14:35 UTC, nelldkLee commented on src/main/java/step3/Car.java
> +    private final int MOVABLE_COUNT = 4;
넵. 바로 적용하였습니다.

2021-11-11 14:35 UTC, nelldkLee commented on src/main/java/step3/CarGroup.java
> +            car.move(new Random().nextInt(RANDOM_MAX_INT_VALUE));
불필요하게 반복 생성 부분 제거 하였습니다.

2021-11-11 14:37 UTC, nelldkLee commented on src/main/java/step3/InputView.java
> +    private Scanner scanner;
try문 밖으로 벗어날때 close를 하도록 try with resources 구문을 활요하였습니다.

2021-11-11 14:37 UTC, nelldkLee commented on src/main/java/step3/RacingSystem.java
> +        new RacingSystem().racingStart();
해당 부분 추가하였습니다.

2021-11-11 14:37 UTC, nelldkLee commented on src/main/java/step3/ResultView.java
> +        System.out.println();
메소드로 추출하여 depth를 1단계로 유지하도록 변경하였습니다.

2021-11-11 14:39 UTC, nelldkLee commented on src/test/java/step2/MyNumberTest.java
> +    @ValueSource(strings = {"", "  "})
@EmptySource를 찾아보니 null도 체크할 수 있는 @NullAndEmptySource 어노테이션으로 변경하였습니다.

2021-11-11 14:40 UTC, nelldkLee commented on src/test/java/step3/CarTest.java
> +    void 자동차_앞으로_이동() {
해당 부분 추가하였습니다.~!

2021-11-13 02:50 UTC, nelldkLee commented
변경사항 적용후 별도로 리뷰요청을 보내야 알림이 가나요?

2021-11-13 14:09 UTC, dbeod2 approved these changes
안녕하세요. 동규님

자동차 경주 피드백 반영 잘해주셨네요! 
변경사항 적용후 별도로 리뷰요청을 보내야 알림이 오도록 되어있습니다 :-) 
이번 미션 여기서 머지하겠습니다. 

다음미션을 진행해주세요!

2021-11-13 14:09 UTC, dbeod2 commented on src/main/java/step3/CarCount.java
> +        if (count < 1) {
유효검증 👍🏻

2021-11-13 14:09 UTC, dbeod2 commented on src/main/java/step3/CarGroup.java
> +            car.move(random.nextInt(RANDOM_MAX_INT_VALUE));
피드백 반영 👏🏻

2021-11-13 14:09 UTC, merged