🚀 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2858
Opened 2021-11-11 14:13 UTC by hiro032

#### 안녕하세요 리뷰어님! 4단계 마무리해서 PR드립니다!

이전에 힌트 주신걸 캐치 하지 못하고 3단계를 마무리 한것같은데 이번에는 조금? 이해한것 같습니다. 
하지만 여전히 풀지 못한 부분이 있는데요 이부분 질문드리면서 해결하려고 PR드려봅니다!

#### 질문 사항
- "게임이 n번 진행될 동안 자동차는 전진, 후진할 수 있다" -> 이 부분에 대한 테스트를 어떻게 작성해야할지 감이 오지 않네요ㅜㅜ

- TryCount라는 객체가 존재하는데요, 구현을 하다보니 각 자동차가 움직이는 Round개념이 필요할것 같아서 TryCount를 통해 계산하도록 구
현 했습니다. 별도의 객체를 만드는게 좋았을지 의문입니다.

- TryCount에 멤버 변수 두개를 분리 하면 좋을것 같다는 느낌이 들지만 마땅한 방법을 찾지 못하겠습니다. 

- 게임 기록을 저장해두는 Game, RoundLog 클래스가 있는데요, 마치 자료구조 처럼 활용됩니다. 이러한 클래스의 테스트는 어떻게 진행 해야 할까요? 아니면 자료구조 처럼 사용 되는 객체를 만들지 않는게 좋을까요?

- 객체의 상태를 변화 시키는 메서드를 테스트 할때, 테스트를 위한 생성자를 만들지 않고 구현하려다 보니 매우 힘들어 졌습니다😓 이 부분에 대한 조언이 있다면 듣고 싶습니다!

항상 좋은 피드백 감사합니다🙏!!

2021-11-12 07:39 UTC, yongdae commented
리뷰에 앞서 질문에 먼저 답변드려요.

Q. "게임이 n번 진행될 동안 자동차는 전진, 후진할 수 있다" -> 이 부분에 대한 테스트를 어떻게 작성해야할지 감이 오지 않네요ㅜㅜ

A. 리뷰를 통해 답변드리겠습니다.

Q. TryCount라는 객체가 존재하는데요, 구현을 하다보니 각 자동차가 움직이는 Round개념이 필요할것 같아서 TryCount를 통해 계산하도록 구
현 했습니다. 별도의 객체를 만드는게 좋았을지 의문입니다.

A. Round라는 개념을 객체로 만드는 방법은 `규칙 3: 모든 원시값과 문자열을 포장한다.` 이 개념과도 맞닿아 있는 개념으로 좋은 방법이라고 생각합니다. 

Q. TryCount에 멤버 변수 두개를 분리 하면 좋을것 같다는 느낌이 들지만 마땅한 방법을 찾지 못하겠습니다. 
A. 이 부분은 리뷰를 통해 답변드리겠습니다.

Q. 게임 기록을 저장해두는 Game, RoundLog 클래스가 있는데요, 마치 자료구조 처럼 활용됩니다. 이러한 클래스의 테스트는 어떻게 진행 해야 할까요? 아니면 자료구조 처럼 사용 되는 객체를 만들지 않는게 좋을까요?

A. 자료구조를 사용해야하는 경우에는 이야기하신 자료구조 같은 Game, RoundLog를 써야 한다고 생각합니다. 다만 자료 구조라고 하시는 부분이 객체를 의미이야기 하시는 건지 정말 자료구조를 이야기하시는 건지에 대해서는 잘 모르겠네요. 자료구조와 객체의 차이점은 무엇인가요?

Q. 객체의 상태를 변화 시키는 메서드를 테스트 할때, 테스트를 위한 생성자를 만들지 않고 구현하려다 보니 매우 힘들어 졌습니다😓 이 부분에 대한 조언이 있다면 듣고 싶습니다!

A. 이야기 하신 것처럼 이 부분은 테스트만을 위한 생성자를 사용하시기 때문이라고 생각됩니다. 불필요한 테스트 여부를 검증하고 꼭 필요한 내용이라면 프로덕션 코드에서도 같이 사용될 수 있는 형태로 만들어보는 것도 하나의 방법이 될 수 있다고 생각합니다. 일반적으로 테스트만을 위한 코드는 불필요한 상황일 확률이 높아요.

2021-11-12 08:23 UTC, yongdae requested changes
민봉님 4단계를 진행하시면서 설계가 좋은 방향으로 많이 바뀐것 같아요. 👍 
수고하셨습니다 !!

진행해주신 내용에 대해 의견을 드렸습니다.
확인하시고 리뷰 요청 부탁드릴께요. 🙇

2021-11-12 08:23 UTC, yongdae commented on src/test/java/racingcar/domain/CarNameTest.java
> +        assertThatThrownBy(() -> CarName.from(name)).isInstanceOf(CarNameException.class);
이름 길이는 5자 이상으로 변경하는게 맞을 것 같아요. :)

2021-11-12 08:23 UTC, yongdae commented on src/test/java/racingcar/domain/CarsTest.java
> +    void findWinnerTest(Cars cars, List<Car> expectedWinners) {
우승자가 여러명인 경우에대해서도 테스트를 추가해보면 좋겠어요. :)

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
> +    public GameLog play() {
이 기능을 사용한다면 `게임이 n번 진행될 동안 자동차는 전진, 후진할 수 있다.` 이 테스트르 만들 수 있지 않을까요?

정확히는 n번이 진행된다라는 기능에 대한 테스트는 TryCount를 통해 진행되었기 때문에
RacingGame을 통해서는 GameLog를 통해 경주가 잘 진행됐는지를 판별해보면 될 것 같은데 어떻게 생각하시나요? 🤔

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/TryCount.java
>      private int tryCount;
`TryCount에 멤버 변수 두개를 분리 하면 좋을것 같다는 느낌이 들지만 마땅한 방법을 찾지 못하겠습니다.`

두개의 멤버 변수를 분리하기 이전에 두개의 변수를 써야하는지에 대한 고민이 필요하다고 생각되요.
tryCount 변수 하나로도 충분하다고 생각되는데 2개를 사용해야 할까요?

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final GameLog gameLog;
규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이 규칙을 적용해보아도 좋을 것 같아요.

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/RoundLog.java
> +
이 부분도 `규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 이 규칙을 적용해 볼 수 있을 것 같아요.

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/Cars.java
> +            }
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

이 규칙을 적용해보면 좋겠어요. :)

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream().filter(car -> car.currentPosition().compareTo(winnerPosition) == 0)
0은 매직 넘버 같아요. 상수로 치환해보면 어떨까요?

2021-11-12 08:23 UTC, yongdae commented on src/main/java/racingcar/domain/CarName.java
> +public class CarName {
CarName 대신 Name은 어떨까요? 🤔

2021-11-13 16:28 UTC, hiro032 commented on src/test/java/racingcar/domain/CarNameTest.java
> +        assertThatThrownBy(() -> CarName.from(name)).isInstanceOf(CarNameException.class);
앗 감사합니다🙏

2021-11-13 16:32 UTC, hiro032 commented on src/test/java/racingcar/domain/CarsTest.java
> +    void findWinnerTest(Cars cars, List<Car> expectedWinners) {
추가 완료 했습니다 !

2021-11-13 16:50 UTC, hiro032 commented on src/main/java/racingcar/domain/Cars.java
> +            }
Position#biggerPosition()을 통해 indent를 줄여봤습니다

2021-11-13 16:53 UTC, hiro032 commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream().filter(car -> car.currentPosition().compareTo(winnerPosition) == 0)
compareTo 대신 equals로 비교 하는게 좋을것 같아 수정 했습니다!

2021-11-13 16:54 UTC, hiro032 commented on src/main/java/racingcar/domain/CarName.java
> +public class CarName {
재활용을 위해 넓은 의미의 네이밍을 사용하라는 의미시겠죠?! 수정 했습니다 ㅎㅎ

2021-11-13 18:04 UTC, hiro032 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final GameLog gameLog;
TryCount를 멤버로 갖고있지 않고, RacingGame#play(Trycount count)로 받아서 사용하게 수정 했습니다.

2021-11-13 18:14 UTC, hiro032 commented on src/main/java/racingcar/domain/RoundLog.java
> +
Position position을 제거해 봤습니다!

기록용 객체 생성을 많에 하게 된거같은 부담이 있습니다 ㅜ

2021-11-13 18:55 UTC, hiro032 commented on src/main/java/racingcar/domain/TryCount.java
>      private int tryCount;
TryCount 에서 finishRound를 사용하는 메서드가 하나밖에 없는걸 봐서 적절하지 않은 변수 인거 같다고 생각 했습니다. TryCount에서 라운드를 구하는걸 Round 객체를 만들어 옮겼습니다.

2021-11-14 09:26 UTC, yongdae approved these changes
주말에도 열심히 피드백을 반영해주셨네요. 👍 
자 그럼 자동차 미션 마지막 단계로 넘어가도록 하겠습니다~

진행해주신 내용에 대해서는 다시 의견을 드린 부분이 있으니
확인하시고 다음 단계에서 같이 반영 부탁드릴께요!

정말 수고 많으셨습니다. 🙇

2021-11-14 09:26 UTC, yongdae commented on src/main/java/racingcar/domain/Round.java
> +public class Round {
Round와 TryCount와 합치는 방법은 없을까요? 🤔 

[이전에 드린 의견](https://github.com/next-step/java-racingcar/pull/2858#discussion_r748054031)에 `TryCount 에서 finishRound를 사용하는 메서드가 하나밖에 없는걸 봐서 적절하지 않은 변수 인거 같다고 생각 했습니다.` 라고 이야기해주셨는데요.

TryCount 혹은 Round 객체 하나만으로 경주 진행 횟수에 대한 표현이 가능하다고 생각합니다. 물론 변수도 한개만 사용해서요.
지금은 두개의 개념이 곁치는 부분이 분명히 있고, 이 부분을 하나의 객체를 사용해서 정의했으면 좋겠습니다.

개념이 유사한 객체가 많아 질 수록 코드는 이해하기 어렵고 객체간의 경계선이 애매모호해지는 부분이 있습니다.
명확히 Round와 TryCount를 나눌 수 없다면 하나의 객체로 합치는게 어떨까요?

2021-11-14 09:26 UTC, yongdae commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream().filter(car -> car.currentPosition().equals(winnerPosition))
car.currentPosition() 이 메소드 대신 비교하는 위치값을 전달하고 결과(boolean)를 반환받는 형태로 만들어볼 수는 없을까요?

`규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.` 이 규칙을 적용한다고 생각하고
자동차에게 위치값을 가져와 비교하는 대신 이 위치값이 맞아? 라고 질문하는 형태로 만들어보면 좋을 것 같아요. :)

Position의 biggerPosition()의 처럼요.

2021-11-14 09:26 UTC, yongdae commented on src/main/java/racingcar/domain/Position.java
> +        if (position < 0) {
0은 매직 넘버로 보여요. 상수로 치환하는게 좋을 것 같아요.

2021-11-14 09:26 UTC, yongdae commented on src/main/java/racingcar/domain/Position.java
> +    public Position of() {
of()는 static을 안 활용하신 이유가 있으신가요?
정적 팩토리 메서드를 적용해주셨는데 한번 내용을 확인해보시는 것도 좋을 것 같아요! - [참고자료](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

2021-11-14 09:26 UTC, yongdae commented on src/main/java/racingcar/domain/Position.java
> +            return this;
this를 사용하면 어떤 문제가 발생할 수 있어요.

this를 반환하게 되면 변하기 쉬운(mutalbe) 객체가 됩니다.
그렇기 때문에 불변성을 유지 할 수 있게 새로운 Postion 객체를 반환하게 변경해보는게 어떨까요?

2021-11-14 09:26 UTC, merged

2021-11-15 12:04 UTC, yongdae commented on src/main/java/racingcar/domain/Round.java
> +    public Round nextRound() {
`생성자를 추가 하지 않고`라는 부분의 이야기를 잘 이해하지 못했어요. 😢 

    @Test
    void nextRound() {
        Round round = Round.from(0);
        assertThat(round.nextRound()).isEqualTo(Round.from(1));
    }

이런 방법은 사용하면 안되는 걸까요..?

2021-11-15 12:13 UTC, yongdae commented on src/main/java/racingcar/exception/RoundException.java
> +    private static final String MESSAGE = "Round값이 잘못 되었습니다.";
단순히 메시지만 다르게 되는 부분이라면 사용자 정의 예외 클래스가 메시지를 전달 받을 수 있게 생성자를 추가해주는 방법이 일반적인 방식이라고 생각합니다. 자바의 Exception 처럼요. 메시지마다 예외 클래스를 다시 정의한다면 관리가 어렵기도 하고 중복되는 부분이 계속 생겨나는 문제점이 있어요!

다만 예외의 카테고리를 명확히하고 싶거나 분류가 필요한 상황이라면 별도의 클래스를 따로 관리하는게 맞다고 생각합니다. :)