[Step3] 자동차 경주
next-step/java-racingcar pull request #2866
Opened 2021-11-12 10:07 UTC by KKambi

고민하는 시간이 많이 걸려서 PR이 늦었습니다.
로직이 어려운 건 아닌데, 확신을 내리지 못하는 부분이 너무 많아요..!

### 질문
1. 이번 미션은 제 코드의 어디가 좋고 어디가 나쁜지를 잘 모르겠어요.
항상 스프링 계층 구조에만 맞게 구현을 하다가, 이렇게 자유로운 미션을 받으니 기준이 없는 느낌입니다...

2. 컨트롤 타워의 역할을 하는 함수는 너무 많은 책임을 지게 되는데, 어떻게 컨트롤 타워를 없애야할 지 모르겠어요! 
예를 들어 `RacingController` 의 경우, start() 메소드가 4가지 일을 하는데요. 
괜찮은지 잘 모르겠네요.

3. 어느 메소드까지 테스트를 해야 할지 모르겠습니다!
```
- 위와 같이 `RacingController` 의 start() 메소드는 뭘 검증해야하는지...?
- `Car` 클래스의 getLocation()도 단순한 getter인데 이걸 검증할 필요가 있는지?
```

4. 메소드의 결과가 랜덤에 따라 달라지는 경우 테스트를 어떻게 하면 좋을까요?
ex) Racer 클래스의 `attemptToMove` 메소드

5. 테스트 커밋 또한 각 기능별로 분리해야 할까요? (저는 한 번에 했는데...)

2021-11-13 08:02 UTC, hyunssooo requested changes
안녕하세요. 
이번 step도 잘 진행해 주셨어요! 👍
몇 가지 코멘트 남겼습니다. 확인 부탁드립니다!
궁금하신 점이나 함께 고민하고 싶은 부분이 있으시면 코멘트나 디엠 남겨주세요! 
그리고 문자열 계산기와는 패키지를 분리해도 괜찮을 것 같아요.

2021-11-13 08:02 UTC, hyunssooo commented
1. MVC에 대해서 고민해 보시면 될 것 같아요. view에서 요청을 받고 controller가 해당 요청을 풀어낼 도메인 객체에게 위임하면 될 것 같습니다 :)

2. 개인적으로는 main() 을 controller라고 생각하고 미션을 진행할 것 같습니다.

3. 단순한 getter를 테스트하는 것은 의미 없습니다. 의미 있는 테스트를 작성하는 것은 추천드려요. 지금은 도메인에 대한 테스트만 작성해도 충분할 것 같아요.

4. 랜덤 값을 메서드 내부에서 의존하고 있으면 테스트하기 어렵습니다. 메서드 파라미터로 넘겨줘보는 것은 어떨까요?

5. 테스트와 기능을 합쳐서 커밋 하시면 충분합니다 :)

2021-11-14 10:15 UTC, KKambi commented
피드백 주신 부분 참고해서 수정했어요!

리뷰어님 말대로 너무 복잡하게 생각해서 과한 클래스 분리가 있었던 것 같고
View가 연관된 부분을 Car에서 걷어내니까 Bound Enum도 필요없게 됐습니다.
(원래 상수를 enum으로 관리하고 싶었어요)

뷰 계층을 나눴던 이유는 컨트롤러에 도메인 필드가 들어가면서 `3개 이상의 인스턴스 필드를 쓰지 않는다`는 규칙 때문이었어요. 도메인 필드를 빼니까 계층이 필요없어졌습니다.

수정하다가 질문이 생겨 코멘트 또 남깁니다!

1. InputCommand 관련, `요청마다 나눠서 처리하라`는 피드백에 제가 수정한 방향이 맞을까요?
2. MVC 패턴을 생각하며 수정해보라고 하셨는데, 제가 수정한 방향이 맞는지 아직도 확신이 안 서네요!
3. `Resolve conversation`은 리뷰어님이 확인하고 누르시나요? 아니면 제가 커밋해서 반영할 때마다 누르면 되는 걸까요?

2021-11-15 11:40 UTC, hyunssooo approved these changes
안녕하세요 :) 
이번 step 잘 진행해 주셨어요! 👍 
다음 step 진행 부탁드립니다!

2021-11-15 11:40 UTC, hyunssooo commented on src/main/java/com/kkambi/racing/domain/Car.java
> +
location 또한 클래스로 만들어보는 것은 어떨까요?

2021-11-15 11:40 UTC, merged

2021-11-15 11:44 UTC, hyunssooo commented
> InputCommand 관련, 요청마다 나눠서 처리하라는 피드백에 제가 수정한 방향이 맞을까요?

네 잘 진행해 주셨어요 :)

> MVC 패턴을 생각하며 수정해보라고 하셨는데, 제가 수정한 방향이 맞는지 아직도 확신이 안 서네요!

 mvc도 잘 진행해 주셨습니다! 

> Resolve conversation은 리뷰어님이 확인하고 누르시나요? 아니면 제가 커밋해서 반영할 때마다 누르면 되는 걸까요?

편하신 대로 하시면 되는데 개인적으로는 안 닫으시면 좋을 것 같아요. 🥲
저도 봐야 하는 경우가 생기는데 하나하나 열어보기가 번거롭더라고요.

2021-11-15 12:15 UTC, KKambi commented
피드백 감사합니다!
1. location 필드를 클래스로 만들라는 것은, 원시값을 포장하라는 원칙에서 나온걸까요?
( 0 이상의 정수여야한다는 제약도 있고... ) 
다음 스텝에서 한 번 해보겠습니다!

2. Resolve Conversation은 다음부터 누르지 않고 남겨두겠습니다!!