🚀 [자동차 경주] 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #2880
Opened 2021-11-13 17:21 UTC by kdhyo

안녕하세요 성주님! :)
벌써..(?) 드디어 자동차 경주 마지막 PR 요청 드립니다!

이번 5단계에는 4단계 전 자바지기님의 영상을 보고서 싹 지우고 새로 만들어보는 것도
좋은 경험일 것 같아서 새로 한 번 다시 만들어 봤습니다!

처음 만들 때는 TDD를 거의 활용하지 못했었는데,
다시 만들 때에는 그래도 구조가 어느 정도 잡힌 후에 하다 보니 어느 정도는 TDD 방식으로 구현을 할 수 있게 된 것 같아요!

하지만 하다가 아직도 어려운 부분들이 있어서 질문 드리고 싶은 게 몇 개 생겨서 남겨봅니다!

1. getter를 잘 사용한 것인지 모르겠습니다.
- History -> name -> car 순으로 구현할 당시에는 최대한 getter를 사용하지 않으려고 진행했습니다만..
결국 output에서 이름이나 history나 사용하려면 맨 위인 일급컬랙션(Cars)부터 name 등
getter를 사용하게 되었는데 알맞게 사용한 것인지 헷갈립니다 ㅠㅠ

2. 테스트코드의 내용
- 일단 초반 history, name 부터 구현할 당시에는 명확한 요구사항 등이 있어서 어떤 걸 테스트를 하면 되겠다! 싶어서 조금은 순조롭게 진행이 되었지만 Cars 나 RacingGameService 부터는 어떤 걸 테스트할 지가 조금 고민이 되더라구요..
특히 Cars 같은 경우는 car와 곂치는 내용이기에 중복된(?) 테스트케이스가 작성이 된 것 같아서
전체적으로 테스트케이스에 들어갈 내용이 알맞게 들어간 것인지 혹은 더 필요한 것이 있다면 피드백 부탁드립니다!

이번 피드백들을 통해 배운 점이 정말 많았습니다 감사합니다!!
마지막 리뷰까지 잘 부탁드립니다!! :)

2021-11-14 17:39 UTC, liquidjoo requested changes
기존 코드를 삭제하는 일이 쉽지 않을텐더 새로운 도전 정말 좋네요 💯 
5단계 미션 잘 구현해주셨어요~
코멘트 몇 개 남겼어요 확인하고 다시 요청 주세요 🙇

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
스프링의 컨트롤러가 싱글톤 패턴을 구현 하신 것 맞을까요?

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/controller/RacingCarController.java
> +        InputDto inputDto = InputDto.of(name, tryCount);
- 컨트롤러에선 Request를 다양한 방법으로 받아요~ 비지니스 로직을 수행함에 있어서 필요한 로직을 파라미터로 전달 받아보는 것은 어떨까요?
- InputDto 가 있다면 도메인 객체인 `Cars` 도 좋지만 `CarsDto` 를 만들어 값만 전달하는 구조체를 만들어도 괜찮을 것 같네요 :)

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/view/ResultView.java
> +    }
InputView는 상태값 없이 static 하게 정의 되었는데 ResultView는 Cars 라는 상태값을 가지게 되어 별도의 객체라고 느껴지네요 :)
화면 만을 위한 일급컬렉션을 만든 것 일까요?

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/domain/strategy/MoveStrategy.java
> +public interface MoveStrategy {
```suggestion
@FunctionalInterface
public interface MoveStrategy {
```

MoveStrategy인터페이스 👍 이런 형태의 인터페이스를 함수형 인터페이스라고 부른답니다. @FunctionalInterface가 무엇인지 찾아보고 공부해 보세요.

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/domain/model/Cars.java
> +    }
cars 에 대한 주솟값을 그대로 외부에 전달하면 어떤 문제가 발생할까요?

2021-11-14 17:39 UTC, liquidjoo commented on src/main/java/racingcar/domain/model/Cars.java
> +    }
`Winner` 라는 역할을 따로 만들어도 좋을 것 같아요 :)

2021-11-14 17:39 UTC, liquidjoo commented on src/test/java/racingcar/domain/model/CarsTest.java
> +
`moveCars` 도 테스트를 해볼 수 있을 것 같아요 :)
어떻게 테스트를 할 수 있을까요?

2021-11-14 17:39 UTC, liquidjoo commented on src/test/java/racingcar/domain/model/CarTest.java
> +
당연할 수 도 있지만 객체의 생성 동일 한 값이면 같은 객체인가 에 대해서도 테스트를 하면 좋습니다 :)

2021-11-15 07:51 UTC, kdhyo commented on src/main/java/racingcar/domain/model/Cars.java
> +    }
외부에서 cars를 받아 변경하면 의도치 않게 Cars 객체의 값이 같이 바뀌게 되기 때문에 문제가 됩니다!!

2021-11-15 09:23 UTC, kdhyo commented
안녕하세요 성주님! 이번 피드백을 하면서 궁금한 게 몇 개 생겨서 글로 남겨 봅니다!

1. 말씀대로 Winner를 다른 객체로 따로 분리를 해보았는데 말씀하신 의도와 맞는 지 헷갈리는 것 같습니다..

2. 스프링MVC 컨트롤러를 생각했을 때 리턴으로 페이지 명을 넘겨 페이지를 불러왔던 걸 생각해서
ResultView는 Application으로 따로 빼지 않고, 컨트롤러에서 호출하는 걸 그대로 유지했는데 괜찮을까요??

이번 리뷰도 잘 부탁드립니다!! (__)

2021-11-16 08:22 UTC, liquidjoo approved these changes
피드백 반영 너무 좋았어요 💯 
5단계 까지 피드백 반영하고 미션 수행 하시느라 너무 고생 많으셨어요~
저와 함께 자동차 경주 미션은 끝났지만 남은 미션들도 잘 해내시라 믿어요
수고하셨습니다 🙇

2021-11-16 08:22 UTC, merged