🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #2894
Opened 2021-11-14 13:56 UTC by hiro032

안녕하세요 용대님! 빠르게 PR드립니다!

5단계를 읽어보니 이미 domain과 view를 분리하고 있는 구조를 가진듯해서
이전에 주신 피드백 해결하고 PR드립니다.

전에 주신 피드백중 https://github.com/next-step/java-racingcar/pull/2858#discussion_r748825870 이 부분을 해결 하지 못했습니다.😓

이 부분을 정적 팩토리 메서드를 목적으로 사용한것이 아닌, RoundLog의 생성용으로 사용하는 생성자에 가까운데요
이 부분은 네이밍이 문제인지 이러한 사용 자체가 문제인지 잘 모르겠어서 의견을 듣고자 다시 요청 드립니다!

이전에 제가 질문드린 부분이 있었는데요, 이 부분에 대한 피드백은 받지 못해서 다시한번 요청 드려 봅니다! 🙇‍♂️

꼼꼼하게 봐주셔서 항상 감사합니다 ㅎㅎ 마지막 리뷰도 잘 부탁드립니다~!!😇

2021-11-14 13:57 UTC, hiro032 commented on src/main/java/racingcar/domain/Round.java
>      public Round nextRound() {
이 메서드에 대한 테스트도 진행 해보고 싶었지만,
생성자를 추가 하지 않고 어떻게 테스트를 추가해야할지 모르겠어서 하지 못했습니다...

이런 메서드의 테스트는 어떻게 진행하는게 좋을까요??

2021-11-15 12:27 UTC, yongdae requested changes
안녕하세요~ 민봉님 😄 
이제 자동차 경주 마지막 단계네요. 수고하셨습니다!!

의견 주신 부분에 대한 답변을 포함해 리뷰를 진행하였습니다.
확인하시고 리뷰 요청 부탁드릴께요~ 🔥

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/Application.java
>      public static void main(String[] args) {
![스크린샷 2021-11-15 오후 9 02 38](https://user-images.githubusercontent.com/4317804/141780374-905a91fb-f1a5-48a3-b027-9c1e8e481c28.png)

TryCount 클래스를 사용하는 곳이 있어서 컴파일 에러가 생겨요.

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isWinner(Position winnerPosition) {
isWinner() 대신 isSamePosition() 같은 이름은 어떤가요?

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/domain/Position.java
> +    public Position biggerPosition(Position other) {
이전 피드백을 잘 반영해주셨네요. 👍

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
> +        while (!current.equals(finalRound)) {
초기에 경주 횟수를 전달받고 점진적으로 횟수를 차감하는 방식으로 Round를 사용해보면 어떨까요?

Round를 이용해서 경주가 끝났는지를 판별 할 수 있다면
기존에 사용한 TryCount의 개념도 Round가 책임 질 수 있어요!

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
> +        while (!current.equals(finalRound)) {
초기에 경주 횟수를 전달받고 점진적으로 횟수를 차감하는 방식으로 Round를 사용해보면 어떨까요?

Round를 이용해서 경주가 끝났는지를 판별 할 수 있다면
기존에 사용한 TryCount의 개념도 Round가 책임 질 수 있어요!

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/domain/Round.java
>      public Round nextRound() {
의견 주신 부분에 [답변](https://github.com/next-step/java-racingcar/pull/2858#discussion_r749263667)드렸습니다. :)

2021-11-15 12:27 UTC, yongdae commented on src/main/java/racingcar/Application.java
>      public static void main(String[] args) {
추가로 Controller 클래스를 만들어보면 좋겠어요. 🤔
지금은 controller 패키지에 정의되거나 Controller 이름을 포함한 클래스가 없어요.

2021-11-15 13:16 UTC, hiro032 commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isWinner(Position winnerPosition) {
네이밍 짓기가 항상 어렵네요 ㅜㅜ

2021-11-15 13:32 UTC, hiro032 commented on src/main/java/racingcar/domain/RacingGame.java
> +        while (!current.equals(finalRound)) {
피드백 주신 의도에 맞는건지는 모르겠지만

- Round#isOver() 메서드를 만들어서 종료 판별을 할 수 있도록 만들었습니다.
- Round#play() 메서드로 라운드 횟수 차감된 라운드를 리턴해서 확인 하도록 했습니다.

지역 변수라고 해도 변수의 값이 자꾸 바뀌면 좋지 않다는 생각이 드는데요 이러한 방법이 괜찮은걸 까요?? 😵

2021-11-15 13:42 UTC, hiro032 commented on src/main/java/racingcar/Application.java
>      public static void main(String[] args) {
앗 죄송합니다 😓 TryCount - Round 사이에서 고민하다가 놓쳤네요..

controller 패키지와 클래스를 추가해서 main 메서드에서 실행되던 로직을 이동 시켰습니다

2021-11-16 02:40 UTC, yongdae requested changes
빠르게 피드백을 반영해주셨네요. 👍 

의견주신 부분 포함해서 리뷰 진행하였습니다.
내용 확인하시고 다시 리뷰 요청 부탁드릴께요!! :)

2021-11-16 02:40 UTC, yongdae commented on src/main/java/racingcar/domain/Cars.java
>      public List<Car> findWinners() {
규칙 8: 일급 콜렉션을 쓴다.

이 규칙을 적용해서 List<Car> 대신 우승자들을 의미하는 일급 콜렉션을 만들어서 사용해도 좋을 것 같아요. 😄

2021-11-16 02:40 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
>          }
while (!round.isOver()) {
      round.counting();

      cars.move();
      
      List<Car> history = cars.getHistory();

      for (Car car : history) {
        gameLog.add(RoundLog.of(Round.from(round.currentRound()), car));
      }
    }
이런 형태가 될 수 있도록 설계 내용을 수정해보면 어떨까요? 🤔 

`지역 변수라고 해도 변수의 값이 자꾸 바뀌면 좋지 않다는 생각이 드는데요 이러한 방법이 괜찮은걸 까요?? 😵`
라고 의견 주신 부분에 대한 답변으로 의견 드린 부분이에요.

2021-11-16 09:21 UTC, hiro032 commented on src/main/java/racingcar/domain/RacingGame.java
>          }
지역변수를 두지 않고 다시 구현을 해 보았습니다!
그런데 Round를 1부터 종료 라운드 까지 RoundLog에 기록 하고 싶었지만, 변수를 하나만 둔 채로 Round를 순서대로 기록하는 방법을 모르겠습니다 ㅜ

2021-11-16 13:41 UTC, yongdae requested changes
의견을 드린 부분에 대해 많이 고민하고 수정을 해주셨네요. 💯 

소소하지만 진행해주신 내용에 다시 한번 의견드렸습니다!
확인하시고 리뷰 요청 부탁드리겠습니다. 🔥

2021-11-16 13:41 UTC, yongdae commented on src/main/java/racingcar/domain/RacingGame.java
> +            cars.recode(Round.from(round), gameLog);
경주를 기록 할 때 Round를 꼭 사용해야 하나요?

[이야기](https://github.com/next-step/java-racingcar/pull/2894#discussion_r750068325) 주신것처럼 순서대로 기록해야하는 부분이 문제라면
GameLog를 경주가 1회 끝날때마다 반환하고 출력하게 한다면 어떤가요?

아니면 RoundLog가 하나의 횟수에 대한 `자동차`기록이 아니라 `자동차들` 기록을 가지게 한다면요? 🤔

2021-11-16 13:41 UTC, yongdae commented on src/test/java/racingcar/domain/WinnersTest.java
> +class WinnersTest {
Winners를 추가하고 테스트까지 잘 만들어 주셨네요. 👍

2021-11-16 13:41 UTC, yongdae commented on src/main/java/racingcar/domain/Round.java
>      }
isOver(), counting()에 대한 테스트도 만들어보면 좋을 것 같아요! :)

2021-11-17 02:33 UTC, hiro032 commented on src/main/java/racingcar/domain/RacingGame.java
> +            cars.recode(Round.from(round), gameLog);
아 제가 피드백 주신 부분을 뭔가 잘못이해 하고 있던것 같네요,,,,
자동차들 에 대한 기록을 통해 RoundLog를 만드니 지역변수를 쓸 필요가 없어졌습니다😄

2021-11-17 02:34 UTC, hiro032 commented on src/main/java/racingcar/domain/Round.java
>      }
테스트 추가 했습니다!

2021-11-17 02:56 UTC, hiro032 commented on src/main/java/racingcar/domain/Car.java
>      }
이러한 생성 메서드를 사용하는것에 대한 질문이 있습니다!

- DTO클래스를 생성하는게 맞지 않나? -> 그럼 getter역할을 하는 메서드를 통해 Car의 값을 꺼내야 할텐데 그런건 괜찮을까요??


- 메서드 네이밍 'from'은 정적 팩토리 메서드를 쓸때 사용하는 네이밍으로 알고있는데 기록용 참조 객체를 생성하기 위해선 어떤 네이밍이 적합할까요..?

2021-11-17 02:59 UTC, hiro032 commented on src/main/java/racingcar/domain/Car.java
>      }
이러한 생성 메서드를 사용하는것에 대한 질문이 있습니다!

- DTO클래스를 생성하는게 맞지 않나? -> 그럼 getter역할을 하는 메서드를 통해 Car의 값을 꺼내야 할텐데 그런건 괜찮을까요??


- 메서드 네이밍 'from'은 정적 팩토리 메서드를 쓸때 사용하는 네이밍으로 알고있는데 기록용 참조 객체를 생성하기 위해선 어떤 네이밍이 적합할까요..?

2021-11-17 10:49 UTC, yongdae approved these changes
안녕하세요. 민봉님. 😄 
자동차 미션 마지막 단계까지 잘 해주셨습니다!

고민하시고 노력하신만큼 좋은 미션 결과를 만들어주셨네요. 👍 
마지막까지 열심히 미션을 해주셔서 재미있게 리뷰를 할 수 있었습니다.
덕분에 또 한번 불타오르네요 🔥

제가 드린 피드백이 조금이나마 도움이 되었길 바래봅니다. 🙏
그동안 수고 많으셨습니다. 

볼링 미션까지 완주하시길 응원하겠습니다! 🎉

2021-11-17 10:49 UTC, yongdae commented on src/main/java/racingcar/domain/Winners.java
> +    }
다른 방법은 없을까요?

getWinners()를 이용해 우승자 목록을 반환하는 대신
우승자들의 이름을 문자값(String)으로 반환해볼 수 있다는 것도 하나의 방법이 될 수 있다고 고민해보셔도 좋을 것 같아요. :)

2021-11-17 10:49 UTC, merged