Step4 : 자동차 경주
next-step/java-racingcar pull request #2899
Opened 2021-11-15 00:41 UTC by kiriwiri

2021-11-15 02:24 UTC, bingbingpa requested changes
4단계 미션 빠르게 구현해주셨네요!
생각해 볼만한 피드백을 남겨드렸는데
확인해보시고 다시 한번 리뷰 요청 부탁 드려요. 
그리고 미션은 한 단계가 모두 끝나고 머지가 되면 다음 단계를 진행해주세요~

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/Car.java
> +        return new Car(this.name, this.location + Random.randomMove());
자동차 객체가 랜덤이라는 영역에 의존하지 않도록 하는 방법에 대해 고민해 보면 좋을거 같아요. 
자동차 객체가 move 할때는 이동할지 여부만 받아서 location 을 증가시킬 수 있지 않을까요?

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/CarService.java
> +    public List<Car> getWinnerCar(List<Car> cars) {
이 클래스를 자동차 객체들을 관리하는 일급 컬렉션으로 활용해 보는건 어떨까요?

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/CarService.java
> +        return cars.stream().filter(car -> car.getLocation() == maxValue).collect(Collectors.toList());
스트림 연산은 한줄에 하나씩 쓰는게 가독성에 더 좋을거 같아요. 
그리고 maxValue 를 구하는 것과 우승자를 찾는 로직을 메소드로 분리하면 가독성에 더 좋을거 같아요.

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/Executor.java
> +public class Executor {
해당 클래스가 메인 클래스인데 패키지를 다른 것들과 구별해서 
실행가능한 메인 클래스라는걸 좀 더 명시적으로 해주는게 어떨까요?

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/RacingGame.java
> +    private final ResultView resultView;
ResultView 는 인스턴스 변수를 가지지 않는 유틸성 클래스인데 의존성을 가질 필요가 있는가에 대해 고민해 보면 좋을거 같아요.

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/RacingGame.java
> +        racingCars = new Racing(racingCars).doRacing();
시도할 횟수만큼 Racing 객체가 만들어지고 있는데요.
Racing 객체를 한번만 생성하고도 게임을 수행할 수 있지 않을까요?

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/Random.java
> +    private static final java.util.Random random = new java.util.Random();
Random 이라는 클래스는 이미 java.util 패키지에 존재하기 때문에 다른 이름을 사용하는게 좋을거 같아요. 
이미 사용중인 Random 이라는 이름을 사용하면 
다른 사람들과 협업을 한다고 생각하면 혼란을 줄 수 있을거 같아요.

2021-11-15 02:24 UTC, bingbingpa commented on src/test/java/racingcar/RacingCarTest.java
> +        carList.forEach(car -> assertThat(car.getLocation()).isBetween(0, 1));
해당 테스트가 깨지네요!

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/Car.java
> +        return new Car(this.name, this.location + Random.randomMove());
그리고 move 메소드가 실행될 때 마다 자동차 객체를 생성하고 있는데요. 
자동차 객체를 한번만 생성하고, 게임을 수행 할 수 있는 방법에 대해 고민해보면 좋을거 같아요.

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/view/InputView.java
> +    private final static Scanner scanner = new Scanner(System.in);
private static final 로 적어줘야 맞습니다~

2021-11-15 02:24 UTC, bingbingpa commented on src/main/java/racingcar/view/ResultView.java
> +public class ResultView {
인스턴스 변수가 없는 유틸성 클래스라면 메소드를 static 으로 선언해도 되지 않을까요? 
그리고 유틸성 클래스로 사용한다면 다른곳에서 객체를 생성하지 못하도록 
기본 생성자를 private  선언해주는게 좋을거 같아요.

2021-11-15 04:39 UTC, kiriwiri commented on src/main/java/racingcar/Car.java
> +        return new Car(this.name, this.location + Random.randomMove());
@bingbingpa 
저는 move 기능 자체가 지금 랜덤으로 이동할지 아닐지로 되어 있기 때문에 여기에 들어가는게 이상하지 않다고 생각했는데욥 
이동할지 여부만 받아서 증가 하는것도 랜덤성과 의존하는 것 같은데 어떤 의미로 말씀하신건지 추가적으로 궁금합니다!

2021-11-15 04:40 UTC, kiriwiri commented on src/main/java/racingcar/CarService.java
> +        return cars.stream().filter(car -> car.getLocation() == maxValue).collect(Collectors.toList());
@bingbingpa 개인적으로 스트림 연산이 너무 길어지면 오히려 저는 가독성이 떨어지는 편입니다 ㅠㅠㅠ (물론 이 코드는 그렇게 긴건 아니지만용!) 이부분은 개인차가 있을 것 같아요

2021-11-15 05:28 UTC, bingbingpa commented on src/main/java/racingcar/Car.java
> +        return new Car(this.name, this.location + Random.randomMove());
@kiriwiri 
move 메소드가 랜덤이라는 영역에 의존하고 있기 때문에 테스트가 어려운 구조인거 같아요. 
move 메소드가 **특정한 값**에 대해서 정상적으로 동작하는지만 확인 한다면, 특정한 값이 의도한 값이든, 랜덤한 값이든 신경쓰지 않아도 될거 같아요.
즉, 프로덕션 코드가 동작하는 곳에서는 move 메서드가 랜덤 한 값을 받도록 하고, 테스트 코드가 동작하는 곳에서는 move 메소드가 의도한 값을 받도록 하는거죠.
이것과 관련해서는 **인터페이스 분리** 또는 **전략 패턴**이라는 키워드로 공부를 해보면 도움이 될 거 같아요.
혹시 설명이 부족하다면 말씀해주세요!

2021-11-15 05:30 UTC, bingbingpa commented on src/main/java/racingcar/CarService.java
> +        return cars.stream().filter(car -> car.getLocation() == maxValue).collect(Collectors.toList());
@kiriwiri 
언급하신 부분은 개인차니까 그럴 수도 있겠네요 ㅎㅎ 
그렇지만 maxValue 를 구하는 것과 우승자를 찾는 로직은 메소드로 분리해 보는게 어떨까요?
하나의 메소드에서 여러가지를 수행하게 되면 테스트하기도 어렵고, 재사용하기도 힘들다고 생각해요!

2021-11-15 06:38 UTC, kiriwiri commented
@bingbingpa 피드백 감사합니당 반영하였습니다!

2021-11-15 10:15 UTC, bingbingpa requested changes
피드백중에 아직 수정되지 않은거 몇개랑 
추가로 피드백 드린 부분이 있는데요.
확인해보시고 다시 한번 리뷰 요청 부탁 드려요~

2021-11-15 10:15 UTC, bingbingpa commented on src/main/java/racingcar/Cars.java
> +        return maxLocationValueOfCar.get().getLocation();
이 부분은 이렇게도 바꿔 쓸 수 있을거 같아요. 
~~~ java
cars.stream()
                .mapToInt(Car::getLocation)
                .max()
                .orElse(0);
~~~

2021-11-15 10:15 UTC, bingbingpa commented on src/main/java/racingcar/RacingGame.java
> +        ResultView.printStartResultView();
RacingGame 객체가 ResultView 에 의존하지 않고, 
게임이 끝난후 ResultView 를 리턴하도록 해보는건 어떨까요?

2021-11-15 10:15 UTC, bingbingpa commented on src/main/java/racingcar/util/CarMoveManager.java
> +public class CarMoveManager {
전략패턴을 사용하려고 하셨던걸까요? 
정확히 어떤 의도의 클래스인지 같이 이야기해보면 좋을거 같아요.
지금은 단지 RandomMove 클래스를 불필요하게 한 번 감싼 클래스라는 생각이 들어요.

2021-11-15 10:15 UTC, bingbingpa commented on src/main/java/racingcar/util/RandomMove.java
> +    private static final java.util.Random random = new java.util.Random();
이전 코드에서는 여기 클래스명이 Random 이라서 java.util 의 랜덤 클래스와 같았기 때문에 
명시적으로 java.util.Random 을 써줘야했지만 이제 클래스명이 RandomMove 로 바뀌었기 때문에 
java.util.Random 부분은 빼도 좋을거 같아요. 
그리고 유틸성 클래스라면 기본 생성자는 pirvate 로 명시적으로 선언해주는게 좋을거 같아요.

2021-11-15 10:15 UTC, bingbingpa commented on src/test/java/racingcar/RacingCarTest.java
> +public class RacingCarTest {
테스트 코드를 각각의 기능단위 클래스별로 나누면 보기 좋을거 같아요.

2021-11-15 13:41 UTC, kiriwiri commented on src/main/java/racingcar/util/CarMoveManager.java
> +public class CarMoveManager {
ㄴ ㅔ.. 저도 불필요하게 감쌌다는 똑같은 생각을 했으나
move를 종속시키지 않으려고 만든거였는데
위에 가이드 주신걸로 수정하면서 삭제 되었습니당

2021-11-15 13:49 UTC, kiriwiri commented on src/main/java/racingcar/RacingGame.java
> +        ResultView.printStartResultView();
중간결과를 전부 다 저장 할 필요가 없다고 생각해서
racing을 1회 try 할때마다 중간 결과를 Print만 하는 로직이어서
게임이 다 끝나고 print를 할 수 없는 구조입니다 ㅠ

2021-11-15 14:14 UTC, kiriwiri commented on src/main/java/racingcar/Cars.java
> +    public List<Car> getCars() {
이부분은 저도 어느정도는 공감하지만, 어떤 경우에는 특정  public 메소드에서 사용하는 private 메소드는 바로 밑에 있어야 저는 따라가기 편하더라구요 ㅠ

2021-11-15 14:19 UTC, kiriwiri commented on src/main/java/racingcar/Car.java
> +        return new Car(this.name, this.location + move);
제가 제대로 이해하고 수정한건지 확실하지 않네욥 좀 더 공부해보도록 하겠습니당!!

2021-11-15 14:20 UTC, kiriwiri commented
@bingbingpa 피드백 재 반영 했습니다 감사드립니당!!

2021-11-15 14:25 UTC, bingbingpa commented on src/main/java/racingcar/Cars.java
> +    public List<Car> getCars() {
맞아요. 저도 그건 동의해요 ㅎㅎ 
public 메소드와 연관있는 private 메소드라면 public 밑에 적어주는것도 나쁘진 않은거 같아요. 
그치만 위의 경우에는 private 보다 위에 있는게 보기에 더 좋다고 생각해요.

2021-11-16 04:17 UTC, bingbingpa approved these changes
피드백 반영잘해주셨네요!
소소하게 피드백 몇 개 남겨드렸는데요.
이건 다음 미션 하시면서 반영해 보면 좋을거 같아요. 
그럼 이번 미션은 머지 하도록 할게요.

2021-11-16 04:17 UTC, bingbingpa commented on src/main/java/racingcar/Cars.java
> +    private final NumberGenerator numberGenerator;
NumberGenerator 는 doRacing 메소드에서만 사용되니까 굳이 인스턴스 변수로 있지 않아도 될 거 같아요.

2021-11-16 04:17 UTC, bingbingpa commented on src/main/java/racingcar/Cars.java
> +            if (name.length() > 5) {
매직 넘버는 상수화 해주는게 가독성에 더 좋을거 같아요!

2021-11-16 04:17 UTC, bingbingpa commented on src/main/java/racingcar/util/NumberGenerator.java
> +    private static final java.util.Random random = new java.util.Random();
java.util.Random 은 생략 할 수 있을거 같아요.

2021-11-16 04:17 UTC, bingbingpa commented on src/test/java/racingcar/CarsTest.java
> +        String res = InputView.getInput("자동차 이름 입력");
이 부분에서 에러가 발생하는데요. 수정해보면 좋을거 같아요.

2021-11-16 04:17 UTC, bingbingpa commented on src/test/java/racingcar/CarTest.java
> +        car.move(numberGenerator);
move 라는 영역을 테스트하기 위해 isBetween 을 사용하고 있는데요. 
move 객체가 클래스가 아니라 인터페이스 타입을 받는다면 
이 부분을 다음처럼 해서 테스트 할 수 있을거 같아요. 
~~~ java
car.move(() -> 1);
car.move(() -> 0);
car.move(() -> 1);
~~~

이렇게 move 가 인터페이스 타입을 받는다면 람다식으로 임의의 의도한 값을 줘서 
isBetween 이 아닌 조금 더 명확한 테스트를 할 수 있을거 같아요. 
RacingTest 테스트 부분도 이런식으로 조금 더 명확하게 테스트를 해볼 수 있을거 같아요.

2021-11-16 04:18 UTC, merged