🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #2921
Opened 2021-11-16 14:03 UTC by soosue

마지막은 시간이 촉박하여 급하게 하게 된 것 같습니다.
리뷰 부탁드립니다! :)

2021-11-17 11:43 UTC, soosue commented
아직 리뷰 말아주시면 좋겠습니다.. Car를 불변객체로 만들기와 winners를 클래스로 빼는 부분을 아직 못했습니다... ㅠ

2021-11-17 11:57 UTC, hyunssooo requested changes
안녕하세요 :) 
방금 코멘트를 확인했네요! 
우선 여기까지만 남겨두겠습니다! 
다시 요청 부탁드릴게요!

2021-11-17 11:57 UTC, hyunssooo commented on src/main/java/racingcarfinal/domain/Position.java
> +    }
```java
    @Override
    public int compareTo(Position o) {
        return Integer.compare(value, o.value);
    }
```
이렇게 가능하겠네요 :)

2021-11-17 11:57 UTC, hyunssooo commented on src/main/java/racingcarfinal/domain/Cars.java
> +    }
```java
    public Cars(List<Car> cars) {
        this.cars = cars;
    }
```

해당 생성자를 추가하면 좀 더 유연한 테스트가 가능하지 않을까요?

2021-11-17 11:57 UTC, hyunssooo commented on src/main/java/racingcarfinal/domain/Cars.java
> +    }
public static인 이유가 있을까요? 
private이 맞을 것 같은데요🤔
우승자들 또한 객체로 만들어 볼 수 있지 않을까요?

2021-11-17 11:57 UTC, hyunssooo commented on src/test/java/racingcarfinal/domain/NameTest.java
> +    }
엣지 케이스 테스트 💯

2021-11-18 01:14 UTC, soosue commented
죄송합니다..! DM으로 따로 연락을 드렸어야했는데요.
자바지기님 강의를 듣다가 빨리 하는게 중요한게 아니라 얼마나 고민을 하고, 제대로 하는게 중요하다는 생각이 들어서 그랬습니다.

전부 다시 새로 짜봤습니다.. 번거롭게 해서 죄송합니다. ㅎㅎ

0. 테스트 코드를 먼저 짰습니다.
1. 도메인 로직에서 getter 안 사용하고, 객체에게 메시지를 보내려고 해봤습니다.
2. 그리고 왠만한 원시값은 모두 포장하려고 해봤습니다.
3. 도메인 객체를 불변객체로 만들려고 해봤습니다.

이 부분이 어려웠는데, 하위 도메인을 불변객체로 만들면, 하위 도메인을 상태 값으로 가지고 있는 상위 도메인은 불변객체가 아니게 되더라구요.

ex) Car가 final Position 가지면 Car가 move해서 Position이 변경되어야 할 경우. Car를 새로 생성해서 return 해야함.
-> Cars가 final List<Car>를 가지고 있는데, List<Car>가 변경 되어야 하므로 final이 없어지거나, list를 조작해야 하는 복잡성이 생김.

그래서 어느 부분까지 불변객체로 할 것인지 그 기준을 적당선에서 정해야겠다라는 생각을 했는데, 어떤 의견을 가지고 계신지 듣고 싶습니다.

리뷰 부탁드립니다!

2021-11-18 17:01 UTC, hyunssooo requested changes
안녕하세요 :) 
마지막 step도 잘 진행해주셨어요! 
이대로 끝내기 아쉬우니 몇 가지 코멘트 남겼습니다. 
확인 부탁드릴게요!

2021-11-18 17:01 UTC, hyunssooo commented on README.md
> +
📝👍

2021-11-18 17:46 UTC, soosue commented on src/main/java/racingcargamefinal/domain/Position.java
> +    }
아 네..! 실수하기 쉬우니깐 IDE의 힘을 빌리는게 나을까요??

2021-11-18 18:19 UTC, soosue commented on src/main/java/racingcargamefinal/domain/Winners.java
> +    }
지난번에 toString() 은 보통 디버깅용으로 많이 사용한다고 정해진 규칙에 따라서 정의하면 좋을 것 같다고 하셨었는데, 그게 view에서 사용을 하면 안된다는 의미인지는 몰랐네요..;;
규칙에 맞게 객체를 대표할 수 있는 내용으로 정의해서 사용하면 되는 줄만 알았습니다.😂

2021-11-18 18:25 UTC, soosue commented on src/main/java/racingcargamefinal/domain/Position.java
> +
아 전에 그렇게 작성을 했었는데요!
~~~java
private Position findMaxPosition() {
    Position maxPosition = cars.stream()
            .map(car -> car.getPosition())
            .max(Position::compareTo)
            .orElse(Position.ZERO);
    return maxPosition;
}
~~~
여기서 getPosition()을 쓸 수 밖에 없어서, getter를 안 써보려고 저렇게 작성했었는데,
getter를 쓰더라도 더 이해하기 쉬운 코드로 작성을 하는게 방향이 맞을까요?

2021-11-18 18:35 UTC, soosue commented
역시 한 번에 통과하진 못하네요.. 회심의 코드였는데 😥
이번에도 리뷰 부탁드립니다! :)

2021-11-19 00:35 UTC, hyunssooo commented on src/main/java/racingcargamefinal/domain/Position.java
> +
car 또한 Comparable을 구현해주면 됩니다 :)

2021-11-19 00:35 UTC, hyunssooo commented on src/main/java/racingcargamefinal/domain/Position.java
> +    }
넵 :)

2021-11-19 15:47 UTC, hyunssooo approved these changes
안녕하세요 윤수님 :) 
이번 미션 진행하신다고 정말 수고 많으셨습니다! 
저 또한 많은 경험을 할 수 있는 미션이었습니다! 
윤수님과 함께 미션을 진행하며 즐거웠습니다! 
이번 미션은 새로운 패키지에서 계속 새로 코드를 작성하셨지만 다음 미션에서는 기존 코드를 개선하는 경험도 꼭 해보셨으면 합니다! 
그동안 감사했습니다! 언제든 편하게 연락 주세요! 🙇‍♂️

2021-11-19 15:47 UTC, hyunssooo commented on src/main/java/racingcargamefinal/domain/Car.java
> +    }
포비가 강의에서 말씀하셨던 것처럼 전략 패턴을 이용해 볼 수 있을 것 같아요 :)

2021-11-19 15:47 UTC, hyunssooo commented on src/main/java/racingcargamefinal/domain/Car.java
> +    }
요 부분은 개인 취향일 수 있는데 isWinner()라는 메서드는 파라미터로 항상 최대값을 받아야 할 것 같아요. 
`isSamePosition()` 이라면 좀 더 유연하지 않을까요? 
이 경우도 파라미터로 어떤 것을 받을지 고민해보면 후보군에 Position, Car 가 있습니다. 
어떤 부분이 좀 더 유연할까요? 혹은 두 객체를 모두 지원할 수 도 있을 것 같아요 :)

2021-11-19 15:47 UTC, hyunssooo commented on src/test/java/racingcargamefinal/domain/CarsTest.java
> +    }
findWinners 의 리턴은 Winners의 객체이기 때문에 Winners의 객체와 비교하는 것이 맞지 않을까요?

2021-11-19 15:47 UTC, hyunssooo commented on src/test/java/racingcargamefinal/domain/CarTest.java
> +    }
getPosition() 보다 Car의 두 객체를 비교하는 방법은 없을까요? 
equals & hashCode 가 힌트입니다 :)

2021-11-19 15:47 UTC, hyunssooo commented on src/test/java/racingcargamefinal/domain/MoveValueTest.java
> +
MoveValue 클래스에서 전략패턴을 고민해보시면서 fake 객체 또한 한번 찾아보시면 좋을 것 같아요 :) 
`엘레강트 오브젝트` 라는 책을 추천 드립니다.

2021-11-19 15:47 UTC, merged

2021-11-20 14:27 UTC, soosue commented on src/main/java/racingcargamefinal/domain/Car.java
> +    }
~~~java
    public boolean isSamePosition(Car other) {
        return isSamePosition(other.position);
    }

    public boolean isSamePosition(Position maxPosition) {
        return position.equals(maxPosition);
    }
~~~
위와 같이 작성했다면, `isSamePosition(Position maxPosition)`의 경우 외부에서 사용하지는 않지만 public으로 놔둬도 괜찮을까요?

2021-11-20 14:34 UTC, soosue commented on src/test/java/racingcargamefinal/domain/MoveValueTest.java
> +
전략 패턴과 fake객체 관련하여 코드에 리뷰 내용을 반영해봤는데,
~~~java

public interface MovingStrategy {

    boolean canMove();

    final class CanMove implements MovingStrategy {
        @Override
        public boolean canMove() {
            return true;
        }
    }

    final class CanNotMove implements MovingStrategy {
        @Override
        public boolean canMove() {
            return false;
        }
    }

}
~~~
~~~java
public class CarTest {

    private final Car carCanMove = new Car("pobi", new MovingStrategy.CanMove());
    private final Car carCanNotMove = new Car("pobi", new MovingStrategy.CanNotMove());

    @Test
    void move() {
        Car movedCar = carCanMove.move();
        assertThat(movedCar).isEqualTo(new Car("pobi", 1));
    }

    @Test
    void moveFail() {
        Car unmovedCar = carCanNotMove.move();
        assertThat(unmovedCar).isEqualTo(new Car("pobi", 0));
    }

}
~~~

이렇게 사용하는게 맞을까요?