Step5
next-step/java-racingcar pull request #2922
Opened 2021-11-16 15:24 UTC by JaeHan-Kim

안녕하세요. 리뷰어님 5단계 리팩터링 해서 피드백 요청 드립니다.

아래와 같은 부분에 대해서 작업했습니다.

* 4단계에서 주신 피드백에 compareToRecord, inFormWinners, inFormFirstRecord 메서드 리팩토링 하면서 inFormWinners, inFormFirstRecord 의 이름은 변경하고 로직을 스트림을 기반으로 변경했으며 compareToRecord은 삭제했습니다.
* domain 패키지에 있던 RacingGame은 controller의 역할을 수행해서 패키지를 이동 시켰습니다.
* 우승자들을 출력해줄 때 RacingGame의 getCars를 이용해서 전체 자동차들의 목록을 ResultView에 전달 했는데 우승자들의 이름만 전달하도록 수정했습니다.

작업을 하면서 궁금한 부분이 있었는데 리뷰어님의 의견은 어떤지 궁금합니다.
* 자동차의 이름을 가져울때 car.getName().getName() 이렇게 호출하는데 따로 메시지로 받아올 이름이 생각이 안나는데 이럴때는 어떻게 처리 하시나요?

언제나 좋은 리뷰 감사드립니다.

2021-11-17 09:02 UTC, sah3122 commented
안녕하세요 😄 
질문에 대한 답변 남겨드릴게요 ! 

`자동차의 이름을 가져울때 car.getName().getName() 이렇게 호출하는데 따로 메시지로 받아올 이름이 생각이 안나는데 이럴때는 어떻게 처리 하시나요?`

car.getName().getName() 와 같이 사용하는경우 우선 디미터 법칙에 어긋나는 상황이에요. 
getter 를 통해 상태값을 꺼낸후, 내부 값을 또다시 조회 하고 있네요. 
이런 경우는 car.getName() 메소드에서 name.getName() 을 호출하는 형식으로 제공해주고 있어요. 
디미터 법칙에 대해 참고하실만한 문서 공유 드릴게요 😄 
https://meetup.toast.com/posts/215

2021-11-17 09:04 UTC, sah3122 requested changes
미션 구현 잘해주셨습니다 👍 
한가지 생각거리를 남겨두었는데 확인 부탁 드려요 !

2021-11-18 09:15 UTC, sah3122 commented
안녕하세요 재한님 ! 

좋은 질문 남겨주셨네요 😄 
`RoundLog, RoundLogs를 dto라 생각해서 dto패키지를 추가했는데 소스코드를 보니 Location, Name, Names도 단순 값만 취급해 주는 객체인 것 같은데 저 객체들이 dto인지 domain인지 고민 되는데 리뷰어님의 생각은 어떠신지요? 궁금합니다!`

Name, Location, Names와 같은 객체를 불변 객체 또는 Value Object라고 정의합니다. 
이러한 객체들은 Dto 클래스를 따로 만들기 보다는 불변 객체 자체를 DTO 용도로 사용하는것을 허용하곤 해요. 
DTO객체는 값을 전달하기 위해 사용하는 객체이고, 불변객체는 특정한 의미를 가지는 값 객체이며 외부로 노출되더라도 값이 변하지 않는것을 보장하기 때문이죠. 

불변객체에 대한 문서를 공유드릴게요 😄 
https://meetup.toast.com/posts/217

2021-11-18 09:16 UTC, sah3122 requested changes
피드백 반영 너무 잘해주셨네요 👍 
질문에 대한 답변과 마지막 미션을 남겨두었으니 확인 부탁드려요 🙏

2021-11-18 09:16 UTC, sah3122 commented on src/main/java/racinggame/domain/Cars.java
> +    public RoundLogs roundRacing(StateGenerator stateGenerator) {
도메인 클래스에서 DTO 클래스를 제공하는것도 UI와 도메인 로직이 분리되어 있다고 할수 없을것 같습니다 😄 
여전히 UI 요구사항이 변경되는 경우 도메인 객체가 영향을 받을수 있을것 같아요. 
도메인 객체는 DTO 객체의 존재 여부를 모르게 구현해볼수 있을까요 ? Cars 클래스에 DTO import 문이 없어질때까지 도전해보세요 !

2021-11-20 10:06 UTC, JaeHan-Kim commented
안녕하세요. 리뷰어님^^

Cars에서 DTO import 제거를 위해 고민해봤는데 맞는 방법으로 한지는 고민이 됩니다.

확인 후 피드백 부탁드립니다.
좋은 주말 보내세요!

2021-11-21 08:36 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
그동안 적지 않은 요구사항들 반영해주신다고 고생많으셨습니다 🙏 
남아 있는 미션들도 잘해내실것 같아요. 끝까지 화이팅입니다 💯

2021-11-21 08:36 UTC, sah3122 commented on src/main/java/racinggame/domain/Cars.java
> +        return Collections.unmodifiableList(cars);
불변 컬렉션으로 리턴 👍

2021-11-21 08:36 UTC, merged