자동차 경주 - 3단계 자동차 경주
next-step/java-racingcar pull request #2929
Opened 2021-11-17 13:16 UTC by ljlwpwp

3단계 자동차 경주 PR 요청 입니다.

작업내용
- Car 도메인 기준으로 설계 작업
- Input, Output 동작을 수행하는 Util 클래스 작성
- 단위 테스트 코드 작성

관련 링크
- https://edu.nextstep.camp/s/Hn1vR4Vs/ls/ra4jF08b

To. Reviewers
이번에도 좀 늦어졌네요. 다음과제도 별개로 바로 진행할 수 있도록 하겠습니다!

2021-11-18 08:43 UTC, parkeeseul requested changes
3단계 미션 잘 구현해주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드리겠습니다 😄 
남은 하루 즐거운 시간 보내시길 바라요!
미션 화이팅 입니다! 🔥

2021-11-18 08:43 UTC, parkeeseul commented on src/main/java/racingcar/common/util/RandomUtils.java
> +
클래스 변수 -> 일반 변수 -> 생성자 
순으로 선언해주는 것이 [컨벤션](https://myeonguni.tistory.com/1596) 입니다! 😄 
```suggestion
public class RandomUtils {
    private static int DEFAULT_RANDOM_SIZE = 10;

    private RandomUtils() {}
```

2021-11-18 14:16 UTC, ljlwpwp commented on src/main/java/racingcar/car/Car.java
> +    private int position;
꼼꼼한 리뷰 감사합니다.
적용 해두었습니다~

2021-11-18 14:19 UTC, ljlwpwp commented on src/main/java/racingcar/car/Car.java
> +        position = 1;
리뷰 주신 사항 반영 해두었습니다! https://github.com/next-step/java-racingcar/pull/2929/commits/0853a9086e71b6a469270eb3432569e104f0a997#diff-0943d32c3cfa4a4bb80e571ebda848732deea7ad9edfc8faf145facdd691f023R7

2021-11-18 14:21 UTC, ljlwpwp commented on src/main/java/racingcar/racing/RacingInfo.java
> +    private final int cars;
numOfCars, numberOfCars, countOfCars... 등등 고민 했었는데 
of 가 붙게 되면 변수명이 너무 길어 지는것 같아 *Count 라는 네이밍으로 설정 해보았습니다.
https://github.com/next-step/java-racingcar/pull/2929/commits/0853a9086e71b6a469270eb3432569e104f0a997#diff-7d0567a014f9a508453340deeb36f6d1e3155b032ad0a253f412e63c815b362eR4-R5

2021-11-18 14:27 UTC, ljlwpwp commented on src/main/java/racingcar/racing/RacingManager.java
> +public class RacingManager {
말씀 주신 내용 [ResultViewManager.java](https://github.com/next-step/java-racingcar/pull/2929/commits/0853a9086e71b6a469270eb3432569e104f0a997#diff-1c02abbfa86c5c2cace4da7ba995bf8da2fb2eddb3eeca346cde923258335ce8) 를 추가 하여 개선 해보았습니다.

2021-11-18 14:27 UTC, ljlwpwp commented on src/main/java/racingcar/common/util/RandomUtils.java
> +
여태 순서를 크게 고려하지 않았었는데 이번 기회에 잘 기억해두도록 하겠습니다.
감사합니다~

2021-11-18 14:29 UTC, ljlwpwp commented
@parkeeseul 
꼼꼼한 리뷰 감사합니다.
말씀 주신 내용 수정 해서 반영 해두었습니다!

2021-11-30 11:39 UTC, ljlwpwp commented
@parkeeseul 
안녕하세요~ 리뷰어님
바쁘시겠지만 수정된 내용 한번 확인 부탁 드립니다!

2021-12-01 14:39 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 추가 코멘트 남겨두었으니 확인해 보시고
추가적인 수정사항은 다음 단계와 함께 반영 부탁드리겠습니다!  😄 
다음 단계 진행해 주세요! 🔥

2021-12-01 14:39 UTC, merged