[자동차 경주] 5단계 - 자동차 경주 (리팩토링)
next-step/java-racingcar pull request #2943
Opened 2021-11-20 15:05 UTC by jiseok-choi

step 5 풀리퀘스트 요청드립니다

객체로 만들 수 있는 것들을 중점적으로 리팩토링 하였습니다!
패키지를 추가하여 클래스를 재배치 하였습니다.
기존의 InputView 클래스가 domain 관련 기능이 포함되어 있어서 분리하였습니다.

2021-11-21 05:06 UTC, yongdae requested changes
안녕하세요. 지석님~ :)
피드백을 포함해서 5단계 미션을 잘 진행해주셨네요. 👍 

진행해주신 내용에 대해 의견을 드렸습니다.
확인하시고 리뷰 요청 부탁드려요. 🙇

2021-11-21 05:06 UTC, yongdae commented on src/main/java/carracing/util/RandomCondition.java
> +public class RandomCondition {
자동차의 전진에 이용되는 값 생성 부분을 객체로 잘 분리해주셨네요. 💯

2021-11-21 05:06 UTC, yongdae commented on src/main/java/carracing/domain/Car.java
> +        int driveCondition = RandomCondition.getCondition();
이전처럼 Car가 RandomCondition을 모르게하는게 좋지 않을까요?

이전의 구조에서는 외부에서 값을 전달받아 사용하는 구조였다면
지금은 직접 RandomCondition을 호출해서 사용하는 구조에요.

Car가 RandomCondition에 대한 의존성을 가지고 있는게 좋을지 한번 고민해보면 좋겠어요. 🤔

2021-11-21 05:06 UTC, yongdae commented on src/test/java/carracing/RandomConditionTest.java
> +public class RandomConditionTest {
RandomCondition한 값에 대한 테스트를 할 수 있을까요?

난수는 실행 될 때마다 결과가 달라지기 때문에 테스트가 불가능하다고 생각되요.
우리는 난수를 테스트 할 수 없기 때문에 CarTest의 drivingCondition를 이용해서
유효범위를 정의하는 테스트를 정의했던게 아닐까요?

2021-11-21 06:33 UTC, jiseok-choi commented on src/main/java/carracing/Main.java
>  public class Main {
음 CarRacing 이 controller 패키지로 분리되어야 겠다는 생각이 드네요
모델과 뷰를 컨트롤 할 수 있는 CarRacing 이 controller패키지로 분류가 되어야겠군요..!!

2021-11-21 06:51 UTC, jiseok-choi commented on src/main/java/carracing/domain/Car.java
> +        int driveCondition = RandomCondition.getCondition();
원시값 파라미터를 피하려고 리팩토링 한것이 의존성을 늘리는 구조로 변경되어버린것 같네요..!

2021-11-21 08:08 UTC, jiseok-choi commented on src/test/java/carracing/RandomConditionTest.java
> +public class RandomConditionTest {
난수가 생성되는 범위에 대한 테스트라고 생각해서 만들었었는데
CarTest 의 drivingCondition 가 있는 이상 의미없는 테스트겠군요..!!

2021-11-21 08:23 UTC, jiseok-choi commented on src/main/java/carracing/domain/Winners.java
> +                .filter(car -> car.getPosition() == raceResult.maximumDistance)
Winners 가 전담하니 로직이 더 간단해진것 같습니다!

2021-11-21 13:43 UTC, yongdae requested changes
피드백을 잘 반영해주셨네요. 👍 

미션 종료에 앞서 매듭지었으면 하는 부분이 있어 몇 가지 의견을 다시 드렸어요~
확인하고 리뷰 요청 부탁드릴께요!! 조금만 더 힘내주세요. 🔥

2021-11-21 13:43 UTC, yongdae commented on src/main/java/carracing/Main.java
> +        inputView.tryCountQuestion();
이 부분도 CarRacing에 포함 시켜 보면 어떨까요? 🤔 

main()은 자동차 경주 게임을 실행하는 내용만 가지게 된다면 더 좋을 것 같아요!

2021-11-21 13:43 UTC, yongdae commented on src/main/java/carracing/util/Position.java
> +package carracing.util;
Position, Name, RandomCondition의 패키지는 domain이 맞나요?

Position, Name, RandomCondition 객체는 보조적으로 도와주는 객체라기보다는
자동차 경주에 필수적인 요소로 사용된다고 생각되는데 어떻게 생각하시나요? 🤔

2021-11-21 13:43 UTC, yongdae commented on src/main/java/carracing/domain/Winners.java
> +    }
```suggestion
    private final List<Car> winners;

    public Winners(List<Car> cars) {
        getMaximumDistance(cars);

        this.winners = cars;
    }

    public List<Car> getWinners() {
        int maximumDistance = getMaximumDistance(this.winners);

        return this.winners.stream()
                .filter(car -> car.getPosition() == maximumDistance)
                .collect(Collectors.toList());
    }

    private int getMaximumDistance(List<Car> cars) {
        return cars.stream()
                .mapToInt(Car::getPosition)
                .max()
                .orElseThrow(NoSuchElementException::new);
    }
```
이렇게 만들어보면 어떨까요?
아래의 두가지 관점을 기준으로 수정해보았어요. :)

- 멤버 변수의 사용을 줄인다.
- 우승자들의 목록을 구하는 시점은 getWinners()이 호출 될 때 해보면 어떨까?

2021-11-21 13:43 UTC, yongdae commented on src/main/java/carracing/domain/RaceResult.java
> +public class RaceResult {
RaceResult는 사용되지 않는 것 같아요. 지우는게 어떨까요?

2021-11-21 13:43 UTC, yongdae commented on src/main/java/carracing/controller/CarRacing.java
> +            carList.get(i).driving(RandomCondition.getCondition());
규칙 4: 한 줄에 점을 하나만 찍는다.

이 규치글 적용해보아도 좋을 것 같아요~

2021-11-22 12:19 UTC, jiseok-choi commented on src/main/java/carracing/Main.java
> +        inputView.tryCountQuestion();
자동차 경주 게임만 실행하는 코드로 구현 시도해보니 깔끔하고 좋은것 같습니다

2021-11-22 12:46 UTC, jiseok-choi commented on src/main/java/carracing/util/Position.java
> +package carracing.util;
domain 패키지가 맞는것 같습니다..!!
util은 사용자의 편리성을 도와주는 의미의 객체를 모아두는 곳이라고 생각해도 될까요?

2021-11-22 13:24 UTC, jiseok-choi commented on src/main/java/carracing/domain/Winners.java
> +    }
Winner 객체 초기화시 반드시 우승자만 있어야 한다는 고정관념에서 벗어날 수 있는 코드였습니다!
멤버변수도 줄어서 깔끔하고 좋은 것 같습니다.
덧붙여 람다를 잘 사용하고 싶네요..

2021-11-23 00:42 UTC, yongdae commented on src/main/java/carracing/util/Position.java
> +package carracing.util;
네 이야기하신게 맞습니다. 정확히는 사용자의 편의보다는 유용한 도구 정도의 개념이 더 좋을 것 같네요. :)

2021-11-23 00:47 UTC, yongdae commented on src/main/java/carracing/domain/Winners.java
> +    }
지석님이라면 경험이 조금 쌓이신다면 충분히 잘 사용하실 수 있을꺼에요!!

2021-11-23 01:00 UTC, yongdae approved these changes
안녕하세요. 지석님! 😄
마지막 의견까지 잘 반영해주셨네요~ 수고하셨습니다.

짧은 기간이었지만 함께 미션을 하면서 여러가지를 배울 수 있는 시간이었던 것 같습니다.
미션에서 드린 피드백이 지석님에게 도움이 되었기를 진심으로 바래봅니다. 🙏

끝으로 의견을 드린 부분이 있으니 한번 확인해보시면 좋을 것 같아요.
마지막까지 수고 많으셨고 남은 볼링 미션까지 꼭 완주하시기를 응원하겠습니다. 🎉

2021-11-23 01:00 UTC, merged

2021-11-24 14:50 UTC, jiseok-choi commented on src/main/java/carracing/Main.java
> +        carRacing.racingStart(carRacing.racingQuestion());
내부적으로 사용하니 확실히 깔끔하네요!

2021-11-24 14:50 UTC, jiseok-choi commented on src/main/java/carracing/domain/Winners.java
> +                .filter(car -> car.getPosition() == maximumDistance)
객체에게 물어봐라! 좋은 포인트 감사합니다