Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #2973
Opened 2021-11-26 16:22 UTC by glenn93516

안녕하세요 리뷰어님 4단계 리뷰 부탁드립니다 🙇 
3단계에서 주셨던 피드백들 최대한 적용해보았습니다

2021-11-27 10:05 UTC, hyunssooo requested changes
안녕하세요 :) 
이번 step 잘 진행해 주셨어요! 👍
몇 가지 가벼운 코멘트 남겼습니다! 확인 부탁드립니다!

2021-11-27 10:05 UTC, hyunssooo commented on src/main/java/racingcar/controller/RacingGameController.java
>      }
stream 을 사용해 볼 수 있을 것 같아요 :) 

```java
carNames.stream()
        .map(Car::new)
        .collect(Collectors.toList());
```

이 경우 메서드를 분리하는 이유는 딱히 없어 보이네요.

2021-11-27 12:13 UTC, glenn93516 commented on src/main/java/racingcar/view/ResultView.java
> +                        )
예리하게 봐주셔서 감사합니다. 구분하던 중에 실수로 들어갔네요 ㅎㅎ;
수정했습니다 193aa5e

2021-11-27 14:26 UTC, glenn93516 commented on src/main/java/racingcar/controller/RacingGameController.java
>      }
넵 stream이 아직 어색하네요ㅠㅠ 덕분에 훨씬 깔끔해졌습니다 감사합니다! e901590

2021-11-27 16:09 UTC, glenn93516 commented on src/main/java/racingcar/model/RacingGame.java
> +    }
적용했습니다! 3dcf592

2021-11-27 16:12 UTC, glenn93516 commented on README.md
> +  * 자동차의 이름은 5자를 초과할 수 없다
감사합니다. 적어두고 구현을 안했네요 ㅠㅠ cb1e609

2021-11-27 16:13 UTC, glenn93516 commented on src/main/java/racingcar/model/RacingGame.java
> +        int winnerPosition = cars.get(0).getPosition();
이런 메서드가 있었네요 감사합니다 덕분에 알아갑니다 f3295a8

2021-11-27 16:14 UTC, glenn93516 commented on src/main/java/racingcar/model/RacingGame.java
> +
불필요한 필드 제거했습니다. 수정하면서 자꾸 이런 부분을 놓치게 되네요
832841d

2021-11-27 16:14 UTC, glenn93516 commented on src/main/java/racingcar/model/RacingGame.java
> +
일급 컬렉션 적용해보았습니다! ea2628a

2021-11-27 16:15 UTC, glenn93516 commented on src/test/java/racingcar/RacingGameTest.java
> +        Car test3 = new Car("test3");
생성자 추가했더니 테스트가 더 편하고 간결해졌네요 7fb1f9d

2021-11-27 16:16 UTC, glenn93516 commented
리뷰어님 피드백 주신 부분 적용해보았습니다. 추가 피드백 부탁드립니다 🙇

2021-11-28 06:32 UTC, hyunssooo approved these changes
안녕하세요 민혁님 :) 
이번 step 진행하신다고 수고 많으셨습니다 :)
다음 step 진행 부탁드릴게요!

2021-11-28 06:32 UTC, hyunssooo commented on src/test/java/racingcar/view/InputViewTest.java
> +    }
이 테스트는 view의 책임일까요? 요구사항은 도메인 모델에서 처리하는 것이 맞습니다! 
적절한 객체에게 위임하고 view에서는 사용자의 입력, 출력에만 집중하는 것은 어떨까요? 
지금은 car 객체가 책임지는 것이 맞을 것 같아요. 
혹은 Name이라는 클래스를 만든다면 해당 클래스의 책임으로 볼 수 있을 것 같네요.

2021-11-28 06:32 UTC, hyunssooo commented on src/main/java/racingcar/model/RacingGame.java
> +    private final Cars cars;
이 클래스는 필요한가요?

2021-11-28 06:32 UTC, hyunssooo commented on src/test/java/racingcar/CarTest.java
> -    @ParameterizedTest(name = "4 이상이 나오면 1칸 전진해야 한다. {0}")
이 클래스는 패키지 이동이 필요해 보이네요 :)

2021-11-28 06:32 UTC, merged