Step5
next-step/java-racingcar pull request #2981
Opened 2021-12-01 07:29 UTC by juuxx

안녕하세요! 리뷰어님
전에 주신 피드백이랑 DM으로 얘기했던 피드백 추가해서 올립니다.
덕분에 많이 배우고 있습니다. 늘 감사합니다😊

2021-12-01 08:59 UTC, seondongpyo requested changes
마지막 단계 잘 작성해주셨네요 👍
이미 구조를 `MVC`로 잘 잡아주셔서 크게 어렵진 않으셨을텐데
마지막으로 조금 더 고민해보셨으면 하는 부분에 대해 코멘트 드렸으니
조금만 더 힘내주셨으면 좋겠습니다.
이미 잘해주셔서 크게 어렵게 느껴지진 않으실 거에요.

오늘 세 번째 강의가 있는 날이네요.
라이브 강의를 통해서 많은 인사이트를 얻어가셨으면 좋겠습니다.
그럼 다시 리뷰 요청 부탁드릴게요! 🔥

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/GamePlay.java
> +        printStart();
이 부분은 바로 `ResultView.printStart()`를 호출해도 될 것 같아요.
`printStart()` 안에서 어떤 특별한 로직 처리 없이 단순히 `ResultView.printStart()` 만을 호출하기 때문에
지금처럼 메서드로 감쌌을 때 딱히 얻을 수 있는 장점이 없어보이는데 어떻게 생각하시나요?

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/domain/Name.java
> +		if(" ".equals(name)){
```suggestion
		if (" ".equals(name)) {
```
1. 코딩 컨벤션 및 포맷팅 확인 부탁드릴게요.
2. 빈 문자열인 `""`에 대해서도 검증이 되었으면 좋겠습니다.
`" "`같이 공백이 포함된 경우는 검증하기 전에 `.trim()`을 호출하면 쉽게 처리 가능할 것 같아요.
지금은 `InputView.stringIntoNames()`에서만 `.trim()`이 호출되고 있지만요.

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/domain/RacingGame.java
> +    private final int tryNo;
자동차의 이름이나 위치 등은 `Name`, `Position` 등으로 원시 값을 포장해보셨는데
이왕 해보신 김에 `tryNo`도 값을 포장해보면 어떨까요?

2021-12-01 08:59 UTC, seondongpyo commented on src/test/java/study/racingcar/domain/RacingGameTest.java
> +	}
`28`라인과 `35`라인의 공백 라인은 제거해도 될 것 같아요.

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/view/InputView.java
>  			.collect(Collectors.toList());
매개변수로 전달되는 `value`에는 자동차 여러 대의 이름들을 포함하고 있기 때문에
복수형을 활용하여 `values`로 지어보는 건 어떨지 여쭤보고 싶구요.
`stream`으로 반복을 수행할 때 내부에서 사용하는 변수 `v`는 `value`로 바꿔보는 건 어떨까요?

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/view/InputView.java
> +		}
위에서 원시 값 `tryNo`의 포장에 대해서 말씀드렸는데요.
`tryNo`를 포장하게 되면 이런 예외 처리 로직들은 해당 클래스 안에서 처리해볼 수 있을 것 같네요.

2021-12-01 08:59 UTC, seondongpyo commented on src/main/java/study/racingcar/view/InputView.java
>  	private static final Scanner scanner = new Scanner(System.in);
`static final` 키워드를 통해 상수로 선언해보셨으니 이름을 대문자로 작성하면 어떨까요?

2021-12-01 09:02 UTC, juuxx commented on src/main/java/study/racingcar/view/InputView.java
>  	private static final Scanner scanner = new Scanner(System.in);
이름을 대문자로 작성하라는 게 무슨 말인지 알 수 있을까요?..

2021-12-01 09:10 UTC, seondongpyo commented on src/main/java/study/racingcar/view/InputView.java
>  	private static final Scanner scanner = new Scanner(System.in);
Slack DM으로 답변드렸습니다 😅

2021-12-03 01:48 UTC, seondongpyo approved these changes
피드백 반영 잘해주셨습니다 👍
추가로 고민해실만한 내용들에 대해 코멘트 드렸으니 확인 부탁드릴게요.

자동차 경주 미션 완료하시느라 그동안 고생 많으셨습니다.
부족한 리뷰어와 함께라서 성장에 많은 도움이 되셨는지 모르겠네요.
추가로 의견 나누고 싶으신 부분 있으시면 편하게 DM 주시구요.
마지막 미션까지 무사히 완주하시길 응원하겠습니다 🔥
함께해주셔서 감사합니다 🙇

2021-12-03 01:48 UTC, seondongpyo commented on src/main/java/study/racingcar/domain/Cars.java
> +		List<Car> createCars = new ArrayList<>(cars);
방어적 복사 👍

2021-12-03 01:48 UTC, seondongpyo commented on src/main/java/study/racingcar/domain/RacingGame.java
> +        return this.tryNo.value() == this.currentTryNo;
`tryNo`에서 값을 꺼내는 것보다 메시지를 보내서 처리하는 방식을 고민해보시면 좋을 것 같아요.

2021-12-03 01:48 UTC, seondongpyo commented on src/main/java/study/racingcar/view/InputView.java
> +        return getTryNo();
```suggestion
        return inputIntTryNo();
```
여기선 바로 `inputIntTryNo()`를 호출해도 괜찮을 것 같아요.
`getTryNo()` 내부에서 추가로 처리하는 로직이 없기 때문에, 메서드로 감싸는 의미가 크게 없어보여요.

2021-12-03 01:48 UTC, seondongpyo commented on src/test/java/study/racingcar/domain/NameTest.java
> +        String givenName = " ";
해당 테스트는 통과하지 않을 것 같은데요.
`Name` 생성자에서 전달받은 문자열을 먼저 `trim()`으로 처리한 다음 유효성 검증을 해보면 어떨까요?

2021-12-03 01:48 UTC, seondongpyo commented on src/test/java/study/racingcar/domain/RacingGameTest.java
> +	void setUp(){
```suggestion
	void setUp() {
```
코딩 컨벤션 확인해주시면 좋을 것 같아요.

2021-12-03 01:48 UTC, seondongpyo commented on src/test/java/study/racingcar/domain/RacingGameTest.java
> +	@DisplayName("tryNo 만큼 레이스 실행 시, isEnd TRUE")
다음 링크를 통해 테스트들의 설명을 조금 더 구체적으로 적어보면 좋을 것 같아요.
https://johngrib.github.io/wiki/junit5-nested/

2021-12-03 01:48 UTC, merged