[정승연] 문자열 계산기, 자동차 경주 게임
next-step/java-racingcar pull request #3019
Opened 2022-01-20 10:28 UTC by SeungYeonJeong

2022-01-21 08:12 UTC, liquidjoo requested changes
안녕하세요. 이번 미션에 리뷰어를 맡은 김성주 입니다 :)
코드 구현 잘해주셨어요 😄 
몇가지 코멘트 남겼습니다 확인하고 다시 요청주세요 🙇 
도움이 필요하시면 언제든 DM을 주세요

2022-01-21 08:12 UTC, liquidjoo commented on src/test/java/racingcar/RaceTest.java
> +}
파일 마지막에 엔터(개행문자)를 넣어주세요!!
이유는 리뷰를 진행할 때 깃허브에서 경고메시지를 지우기 위함입니다.
좀 더 알고 싶으시면 재미삼아 아래의 링크를 보시는 것도 추천 드립니다.

[https://minz.dev/19](https://minz.dev/19)
Intellij 를 사용하실 경우엔
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크해주시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2022-01-21 08:12 UTC, liquidjoo commented on src/main/java/racingcar/Race.java
> +    public static void repeatGame(int[] cars, String[] carNames, int times) {
매개 변수를 늘리는 것도 좋지만 객체의 상태 값을 활용해보는 것이 어떨까요?

2022-01-21 08:12 UTC, liquidjoo commented on src/main/java/racingcar/Race.java
> +        int[] cars = new int[carNames.length];
`Car` 라는 객체가 있으면 더 좋을 것 같아요 :)

2022-01-21 08:12 UTC, liquidjoo commented on src/main/java/racingcar/Race.java
> +        int randomNumber = (int) Math.floor(Math.random()*10);
Random 클래스를 활용해 봐도 좋을 것 같아요!!

https://mine-it-record.tistory.com/143

2022-01-26 16:14 UTC, SeungYeonJeong commented
안녕하세요! 두 번째 리뷰 요청 드립니다 😄
자바를 다뤄본 게 거의 처음이라 하나하나 검색해가며 프로젝트를 수행하고 있어 시간이 조금 걸렸습니다.

피드백을 반영하며 매개변수 대신 객체의 상태값을 사용하는 방향으로 코드를 수정해보긴 했는데, 해당 부분은 제대로 구현했는지 잘 모르겠습니다... 😅
또한 문자열계산기 구현시 else문을 사용하지 않고 구현해보라는 피드백을 주셨는데 해당 부분은 어떻게 구현해야할지 감이 안와 우선 해당 부분은 수정하지 않고 리뷰 요청 드립니다!

2022-01-27 15:31 UTC, liquidjoo requested changes
피드백 반영 좋았어요 :)
몇 가지 코멘트 남겼어요 확인하고 다시 요청 주세요 🙇

2022-01-27 15:31 UTC, liquidjoo commented on src/main/java/racingcar/Car.java
> +            OutputView.printCurrent(carNames, cars);
게임이 완전히 끝난 후에 자동차 경주의 결과를 보여줄 수 있도록 해보는 것이 어떨까요?

2022-01-27 15:31 UTC, liquidjoo commented on src/main/java/racingcar/OutputView.java
> +    }
자동차의 정보를 가지고 있는 객체가 있다면 화면 로직이 아닌 비지니스 로직으로 옮겨 갈 수 있을 것 같아요 :)

2022-01-27 15:31 UTC, liquidjoo commented on src/main/java/racingcar/OutputView.java
> +    }
객체 설계를 위해서 자동차라는 객체를 우선 만들어 보는 것이 좋을 것 같아요 :)
객체의 비교 및 메시지 전달을 통해서 구현해보는 것이 어떨까요?

2022-02-03 05:20 UTC, SeungYeonJeong commented
피드백 주신 내용 반영하고 Car 객체를 만들어 비즈니스 로직과 화면 로직을 보다 명확히 분리하기 위해 노력했습니다.
리뷰 부탁드립니다! 😊

2022-02-03 14:43 UTC, liquidjoo approved these changes
피드백 반영 잘해주셨어요 👍 
몇가지 코멘트 남겼어요~ 다음 단계에 같이 반영해주세요
다음 단계 진행해주세요 🙇

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/calculatorFunction/Calculator.java
> +    private ArrayList<String> parsedValues = null;
```suggestion
    private ArrayList<String> parsedValues;
```
생성자에서 초기화를 하기 때문에 null 로 명시적으로 초기화는 필요 없을 것 같아요 :)

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/calculatorFunction/Calculator.java
> +        int parsedValuesSize = parsedValues.size();
피드백 반영 👍 
요청마다 메서드 호출하는 일을 줄일 수 있어요 :)

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/calculatorFunction/Calculator.java
> +        operatorMap.put("/", Operations.class.getMethod("div"));
enum 을 활용해보면 어떨까요?

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/calculatorFunction/Operations.java
>  public class Operations {
enum 을 활용해보면 어떨까요?

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/racingcar/Car.java
> +    int distance;
default 도 좋지만 접근제어자를 명확히 private를 통해 상태값의 노출을 막아보는 것이 어떨까요?

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/racingcar/Race.java
>      public static void execute() {
- static method 없이 구현해 볼 수 있을까요?
- 너무 많은 책임이 있는 것 같아요 메서드 분리는 통해 나누어 보는 것이 어떨까요?

2022-02-03 14:43 UTC, liquidjoo commented on src/main/java/racingcar/Race.java
> +    public static ArrayList<Car> getWinners(ArrayList<Car> cars) {
Winner, Winners 와 같은 객체를 만들어 역할 및 책임을 분리해 보는 것이 어떨까요?

2022-02-03 14:43 UTC, liquidjoo commented on src/test/java/racingcar/RaceTest.java
> +    Car[] cars = new Car[3];
- 배열보단 컬렉션을 활용해보는 것이 어떨까요?
- List<Car> 를 감싸는 객체 Cars 를 만들어 보면 어떤 장점이 있을까요?

2022-02-03 14:43 UTC, merged