[박지현] 문자열 계산기, 자동차 경주게임
next-step/java-racingcar pull request #3024
Opened 2022-01-20 13:48 UTC by jihyunhillpark

문자열 계산기, 자동차 경주 게임에 대한 pull request입니다.

유양우, 김현수 팀원과 함께 pair programming을 진행하였습다.
4일동안 팀원들과 함께 하며 많은 것을 배울 수 있었고, 새로운 시각으로 프로젝트를 진행할 수 있었던 유의미한 시간이었습니다.

PR로 추가될 구현 사항은 다음과 같습니다.

### 문자열 계산기
- [x] 입력한 문자열 값에 따라 사칙 연산을 수행하는 기능. 사칙 연산을 모두 포함하는 기능 구현 - Calculator         
  - [x] 덧셈 - add()   
  - [x] 뺄셈 - sub()   
  - [x] 곱셈 - multiply()     
  - [x] 나눗셈 - divide()     
- [x] 공백 문자열을 빈 공백 문자로 분리하려면 String 클래스의 split(" ") 메소드를 활용한다. 반복적인 패턴을 찾아 반복문으로 구현한다. - FormulaUtil    
- [x] 사용자에게 문자열 입력을 받아 유효성을 검증하는 기능 구현 - FormulaInput#getFormula()    
  - [x] 입력값이 null이거나 빈 공백 문자일 경우 IllegalArgumentException throw     
  - [x] 사칙연산 기호가 아닌 경우 IllegalArgumentException throw 

### 자동차 경주
- [x] 사용자에게 경주할 자동차 이름을 입력받는 기능 구현 - RacingCarInput#getCarName
  - [x] 입력 값이 쉼표를 기준으로 구분되는지 검증 - isCommaSeperated()
  - [x] 시도할 횟수가 입력받는 기능 구현 - getRaceCount()  
- [x] 자동차 이름, 위치정보를 저장하는 자동차 클래스 - RacingCar 
  - [x] 자동차 이름의 길이가 5이하인지 검증 - isCorrectNameSize()
  - [x] 전진 하는 메서드 - moveForward()
- [x] 자동차게임 실행하는 클래스 - GameLauncher
  - [x] 필드로 자동차 리스트 관리
  - [x] 여러 자동차 한번에 전진 - start()
  - [x] 시도마다 결과를 출력 - printRacing()
  - [x] 우승자를 선정해서 출력 - printWinner()
- [x] 랜덤값 생성 클래스 - RandomUtil
  - 랜덤값 생성기능 구현 - createRandomNumber()
  
### 💡기타 논의 사항
1. 클래스, 메소드 등 Naming이 적절한지 피드백 주시면 감사하겠습니다 :)
2. 프로젝트의 클래스들이 낮은 결합도와 높은 응집도를 갖고 있는지 등 객체지향 관점에서 날카로운 피드백 주시면 감사하겠습니다 🔥
3. 사용자 입력에 대한 test이 적절하게 작성되었는지 피드백 주시면 감사하겠습니다 :)

2022-01-20 17:30 UTC, hyunniiii requested changes
안녕하세요 지현님~

미션 잘 구현해주셨습니다 😃 

몇가지 코멘트 남겼으니 확인부탁드립니다!

2022-01-20 17:30 UTC, hyunniiii commented on src/main/java/calculator/service/Calculator.java
> +            Operation operator = Operation.fromString(formulaStack.pop()).get();
`fromString` 메서드의 반환 타입이 `Optional`이네요. 
`Optional`은 nullable하기 때문에 `.get()`만 사용하면 값이 null일 경우 에러가 발생하겠네요.
`orElseThrow`등을 사용해 값이 `null`일때 문제가 되지 않도록 수정해보는건 어떨까요?

2022-01-20 17:30 UTC, hyunniiii commented on src/main/java/calculator/ui/FormulaInput.java
> +            input = bufferedReader.readLine();
```suggestion
            String input = bufferedReader.readLine();
```
중요한건 아니지만 14라인이 없어도 괜찮을 것 같아요 😃

2022-01-20 17:30 UTC, hyunniiii commented on src/main/java/calculator/service/Calculator.java
> +        for(int i = formula.size()-1; i>=0; i--){
intellij 코드 정렬 단축키 입니다. 
`option(cmd) + alt + l`

가독성을 위해 코드 정렬 한번 해주면 좋을 것 같습니다 : )

2022-01-20 17:30 UTC, hyunniiii commented on src/main/java/calculator/util/Operation.java
> +    }
```suggestion
  public static Operation from(String symbol) {
        return Arrays.stream(values())
                .filter(operation -> symbol.equals(operation.symbol))
                .findFirst().orElseThrow(IllegalArgumentException::new);
    }
```

이렇게도 표현이 가능합니다 : ) 
    
또한 하나의 매개변수를 받아서 인스턴스를 생성할 때 주로 `from`이라는 네이밍을 사용합니다. :)
네이밍에 관해서는 아래 링크 참고해주세요!
https://multifrontgarden.tistory.com/255

2022-01-24 08:25 UTC, jihyunhillpark commented on README.md
> +## 기능 구현
감사합니다~😊

2022-01-24 08:52 UTC, jihyunhillpark commented on src/main/java/calculator/service/Calculator.java
> +        Stack<String> formulaStack = new Stack<>();
첨부해 주신 링크 잘 보았습니다!
formulaStack의 경우 변수 이름에 **자료형**이 들어가서 적절한 의미를 표현하지 못하는군요! 
변수와 매개변수가 의미하는 것을 정확하게 표현하고자, 매개변수인 formula를 수식의 단어인 expression으로, 수식의 기호들을 하나씩 담는 stack은 symbols로 수정하였습니다.

2022-01-24 08:59 UTC, jihyunhillpark commented on src/main/java/calculator/service/Calculator.java
> +        for(int i = formula.size()-1; i>=0; i--){
네~알려주신 단축키로 정렬 완료했습니다 ; )

2022-01-24 09:02 UTC, jihyunhillpark commented on src/test/java/calculator/ui/FormulaInputTest.java
> +        // assertThat().isEqualTo(expected.get(0));
아하! 값을 입력하는 부분의 테스트는 지우도록 했습니다~

2022-01-24 09:13 UTC, jihyunhillpark commented on src/main/java/calculator/ui/FormulaInput.java
> +            input = bufferedReader.readLine();
오호~반영했습니다!

2022-01-24 09:40 UTC, jihyunhillpark commented on src/main/java/calculator/service/Calculator.java
> +            Operation operator = Operation.fromString(formulaStack.pop()).get();
오 감사합니다! 조언해 주신대로 `orElseThrow`를 통해 해당 부분을 고쳤는데, 적용하던 중 궁금한 것이 생겼습니다.
null 처리는 ifPresent - get로도 가능한데  orElseThrow을 사용하는 까닭은 가독성 때문인가요~?

2022-01-24 11:52 UTC, jihyunhillpark commented on src/main/java/calculator/util/Operation.java
> +    }
스트림 사용에 미숙했는데, 저렇게 사용할 수도 있군요!... stream API 에 대해 공부해야겠다는 생각이 드는군요
조언 주신대로 바꾸었고, 바뀐 코드에 맞춰 기존 Calculator에서 Optional null처리 부분을 삭제하였습니다!

* 그리고 클래스와 메소드에 대한 전반적인 네이밍을 다시 하여 적용하였습니다 : )

2022-01-24 11:57 UTC, jihyunhillpark commented on src/main/java/calculator/util/Operation.java
> +public enum Operation {
우와아!! 따봉따봉 👍👍감삼다!

2022-01-24 12:13 UTC, jihyunhillpark commented on src/test/java/racingcar/service/GameLauncherTest.java
> +    void 모든차앞으로전진() {
오호~~감사합니다! 이번 기회에 다른 테스트 코드들에도 적용해보았습니다 ; )

2022-01-24 12:18 UTC, jihyunhillpark commented
리뷰어님~ 유익한 피드백을 많이 주신 덕분에 부족함 점도 많이 깨닫고 배울 수 있었습니다!!🤩
말씀하신 부분들을 수정해보았는데, 확인하시다가 부족한 부분이 보이시면 언제든지 말씀해주세요!!
바쁘신데도 자세히 봐주셔서 감사합니다!! 
좋은 하루 되시길 바라요~~~ ; )

2022-01-24 15:03 UTC, hyunniiii commented on src/main/java/calculator/service/Calculator.java
> +            Operation operator = Operation.fromString(formulaStack.pop()).get();
`ifPresent`를 사용하셔도 됩니다.
`orElseThrow`나 `ifPresent`를 활용해서 `null`에 대한 처리만 하시면 됩니다 ~ ″̮ 
잘 처리해주셨네요 😃

2022-01-24 15:39 UTC, hyunniiii requested changes
안녕하세요 지현님 ″̮ 
테스트도 잘 작성해주셨네요.
몇가지 코멘트 남겼으니 확인 부탁드립니다!

또한 사용하지 않는 empty.txt는 삭제해주셔도 될 것 같습니다 ″̮

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/calculator/ui/ExpressionInput.java
> +        if (input == null || "".equals(input)) {
`input == null` 대신 `input.isEmpty()`도 사용할 수 있습니다 ″̮ 
`isEmpty` 말고도 `isBlank`도 있으니 아래 글 참고해주세요 😃 
https://stackabuse.com/java-check-if-string-is-null-empty-or-blank/

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/calculator/ui/ExpressionInput.java
> +    private static void isNotOperator(List<String> formular) {
메서드 이름이 `is~~`로 시작하면 대부분 boolean 타입을 리턴해줍니다.
`isNotOperator`는 반환형이 void네요. 
또한 여기서 처리해주지 않아도 알아서 예외처리를 해줄 것 같아요 ″̮

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/calculator/ui/ExpressionInput.java
> +    private static void isNotNumber(List<String> formular) {
여기도 마찬가지로 `is~`로 시작하네요! 
또한 Integer.parseInt로 파싱된 값을 사용하지 않는 것 같아요.
실제로 string에서 integer나 double 형으로 파싱해주는 곳에서 해주는건 어떨까요?

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/calculator/util/Operation.java
> +    DIVDE("/") {
```suggestion
    DIVIDE("/") {
```
오타가 있네요!

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/racingcar/service/GameLauncher.java
> +        }
이 로직을 메서드로 추출해주는건 어떨까요?

해당 로직은 인스터스 변수인 racingCarList에 값을 추가해주고 있어요.
이렇게 인스턴스 변수를 직접 참조해서 값을 추가하게 되면 사이드 이펙트가 발생할 수 있습니다.
메서드로 추출 후 racingCarList에 add를 해주기보다는 새로운 객체를  생성해서 리턴해주는건 어떨까요?

2022-01-24 15:39 UTC, hyunniiii commented on src/main/java/racingcar/service/GameLauncher.java
> +public class GameLauncher {
`racingCarList`를 나타내는 클래스명으로 수정해주는건 어떨까요?
또한 racingCarList 변수명에 자료형이 들어가있네요 ″̮

2022-01-24 15:39 UTC, hyunniiii commented on src/test/java/calculator/util/ExpressionUtilTest.java
> +        List<String> result = ExpressionUtil.split("6 / 2 + 3");
split 처럼 제공되는 메서드는 테스트를 따로 해주지 않아도 됩니다 ″̮

2022-01-24 15:39 UTC, hyunniiii commented on src/test/java/racingcar/domain/RacingCarTest.java
> +    @DisplayName("자동차 이름 검사 테스트")
테스트 네이밍은 자동차 이름 검사 테스트 보다는 `어떤 동작을 통해서 어떤 결과를 나타내는지 `로 작성해주시면 더 좋습니다.
이 테스트는 자동차 이름의 길이에 대한 테스트 같네요.
`자동차 이름의 길이가 n값 보다 크면 IllegalArgumentException 발생한다` 이런식으로 작성해주면 코드를 처음 본 사람이 코드 이해하는데 훨씬 많은 도움이 됩니다. ″̮

https://hilucky.tistory.com/216

2022-01-25 08:26 UTC, jihyunhillpark commented on src/main/java/calculator/ui/ExpressionInput.java
> +    private static void isNotOperator(List<String> formular) {
오 그렇네요~!Operation내부 from 함수를 통해서 예외를 처리하고 있는데 ExpressionInput에서 또 예외를 처리해주는 중복이 있었네요~
말씀에 따라서 불필요한 예외처리 부분은 삭제하였습니다.

2022-01-25 09:55 UTC, jihyunhillpark commented on src/main/java/calculator/ui/ExpressionInput.java
> +    private static void isNotNumber(List<String> formular) {
네~ isNotNumber 함수 부분은 불필요하여 삭제하도록 했습니다.

2022-01-25 10:05 UTC, jihyunhillpark commented on src/main/java/calculator/util/Operation.java
> +    DIVDE("/") {
매의 눈이십니다~!

2022-01-25 10:48 UTC, jihyunhillpark commented on src/main/java/racingcar/service/GameLauncher.java
> +        }
오호라! 그렇네요!!
```java
public class CarRace {

    private final List<RacingCar> racingCars;

    public CarRace(List<String> carName) {
        racingCars = getRacingCars(carName);
    }
```
getRacingCars() 메서드를 생성한 후 반환한 리스트를 할당하도록 했습니다!
실질적으로 발생할 수 있는 문제에 대해 알 수 있었습니다~ 감사합니다!

2022-01-25 11:35 UTC, jihyunhillpark commented on src/main/java/racingcar/service/GameLauncher.java
> +public class GameLauncher {
넵! 해당 클래스에서 자동차들이 움직이고 우승자가 결정되는 등 자동차 경주에서 발생할 수 있는 동작들이 정의되고 있어, 차들의 경주 의미 CarRace로 바꾸었습니다!
racingCarList도 racingCars로 자료형을 제외했습니다! 어제 같은 문제로 다른 곳에서도 변수명을 수정했는데 하마터면 놓칠뻔 했네요!감사합니다~

2022-01-25 12:18 UTC, jihyunhillpark commented on src/test/java/calculator/util/ExpressionUtilTest.java
> +        List<String> result = ExpressionUtil.split("6 / 2 + 3");
내장 메서드는 테스트 따로 하지 않기!! 잘 기억해두겠습니다~.~!!

2022-01-25 12:32 UTC, jihyunhillpark commented on src/test/java/racingcar/domain/RacingCarTest.java
> +    @DisplayName("자동차 이름 검사 테스트")
오~좋은 자료 감사합니다! 
주신 자료를 참고하여 테스트 네이밍을 수정해보았습니다.
자동차 경주 테스트 (RacingCarTest.java)는 **When_StateUnderTest_Expect_ExpectedBehavior** 의 형식을 따르도록 하였고,
문자열 계산기 테스트(CalculatorTest.java)는 **test[Feature being tested]** 의 형식을 적용해 보았습니다. 😚

2022-01-25 13:13 UTC, jihyunhillpark commented
안녕하세요 리뷰어님~
피드백 주신 것을 토대로 코드를 수정해보았습니다.
( 바쁘신 와중에도 자세한 피드백 주셔서 감사합니다! 😁)

한편, 코드를 수정하면서 피드백 주신 것 이외에도 다음과 같이 일부 내용들을 변경해보았습니다.
1. **문자열 계산기** 의 경우, 기존처럼 util 패키지에 있던 Operation.java의 역할과 패키지 이름과 맞지 않는다고 생각해서 domain패키지로 옮겼습니다.

2. **자동차 경주** 의 경우, Application에서 많은 로직을 처리하고 있다고 생각해 기존 GameLauncher 클래스를 CarRace클래스로 바꾼 뒤 역할을 다시 정의하고 지원하는 기능에 따라 메소드들을 추가했습니다. 

혹시라도 부족한 부분이 있다면 말씀해주시면 감사하겠습니다~.~
오늘도 좋은 하루 되시길 바랍니다! 감사합니다~

2022-01-25 14:38 UTC, hyunniiii commented on src/main/java/racingcar/domain/RacingCar.java
> +        return name + " : " + position;
`position`값 자체가 아닌 `-` 를 사용해서 보여주도록 수정해주세요 ″̮

2022-01-25 14:44 UTC, merged