[정승연] 문자열 계산기, 자동차 경주게임 (Step 2)
next-step/java-racingcar pull request #3053
Opened 2022-02-07 09:51 UTC by SeungYeonJeong

안녕하세요 성주 리뷰어님!
Step1에서 리뷰 주신 내용과 MVC 패턴을 고려하여 코드를 리팩토링하였습니다.
항상 좋은 리뷰 감사드립니다 😊

2022-02-08 15:32 UTC, liquidjoo requested changes
2단계 미션 잘 구현해주셨어요 👍 
생각해볼 만한 코멘트 몇 개 남겼어요
확인하고 다시 요청주세요 🙇

2022-02-08 15:32 UTC, liquidjoo commented on src/main/java/racingcar/view/OutputView.java
> +    public static void printResult(List<Car> cars) {
List<Car> 를 포장하고 있는 객체가 있으면 어떤 점이 좋을까요?
포장하고 있는 객체를 List로 만들어 볼 수 있으면 어떻게 구현해 볼 수 있을까요?

2022-02-08 15:32 UTC, liquidjoo commented on src/test/java/racingcar/domain/RaceTest.java
> +    void _0에서_9사이의_정수를_반환하는지_확인한다() {
난수를 어떻게 제어하면서 테스트를 해볼 수 있을까요?

2022-02-13 09:43 UTC, SeungYeonJeong commented on src/main/java/calculatorFunction/Calculator.java
> +    public void returnCalculatedValue() {
매서드를 병합하고 메서드명을 getAnswer로 변경하였습니다.

2022-02-13 09:43 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Car.java
> +        validateCarName(name);
유효성 검사를 먼저 실시하도록 수정하였습니다.

2022-02-13 09:44 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Car.java
> +    }
부 생성자에서 this()를 활용하도록 수정하였습니다.

2022-02-13 09:45 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Car.java
> +    }
정적 팩토리 메서드 패턴을 생성하였으나 필요가 없다 판단해 다시 삭제하였습니다.

2022-02-13 09:46 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Race.java
> +            OutputView.printResult(cars.getCars());
histories, history 메서드를 생성해 결과값을 저장하고, 마지막에 결과를 한 번에 보여주도록 수정하였습니다.

2022-02-13 09:47 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Winner.java
> +    private final List<Car> cars;
Cars를 활용하도록 수정하였습니다.

2022-02-13 09:48 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Race.java
> +    public void playGame() {
Movable 인터페이스를 생성해 이동가능여부 값을 넣어주어 랜덤 값에 의존하지 않고 테스트 가능하도록 변경하였습니다.

2022-02-13 09:51 UTC, SeungYeonJeong commented on src/main/java/racingcar/view/OutputView.java
> +    public static void printResult(List<Car> cars) {
histories 객체를 생성하여 결과를 마지막에 한 번에 출력하도록 구현하였는데, 제가 피드백을 제대로 이해한 건지 잘 모르겠습니다 😢

2022-02-13 09:51 UTC, SeungYeonJeong commented on src/test/java/racingcar/domain/RaceTest.java
> +    void _0에서_9사이의_정수를_반환하는지_확인한다() {
Movable 인터페이스를 생성해 이동가능여부 값을 넣어주어 랜덤 값에 의존하지 않고 테스트 가능하도록 변경하였습니다.

2022-02-13 09:52 UTC, SeungYeonJeong commented on src/main/java/calculatorFunction/Operators.java
> +public enum Operators {
😊😊😊

2022-02-13 09:57 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Cars.java
> +        return cars;
외부에서 cars를 수정할 수 있게 되는 것일까요..?
getCars를 사용하지 않고 데이터를 넘겨주는 방법이 잘 감이 오지 않아 우선 수정하지 않고 리뷰요청 드립니다 😢

2022-02-13 10:04 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Race.java
> +    }
이 부분도 어떤 식으로 구현해야할지 감이 오지 않아 우선 수정하지 않고 리뷰요청 드립니다 😢
메시지 전달의 개념을 잘 모르겠습니다.

2022-02-13 10:08 UTC, SeungYeonJeong commented on src/main/java/racingcar/domain/Winner.java
> +    private final List<Car> winners = new ArrayList<>();
`List<Car>` 를 갖는 객체가 보다 우승자를 저장하고 반환하기 편리해보여 이를 활용하였는데, `List<Winner>` 를 갖는 객체를 만들었을 때의 장점이 궁금합니다!

2022-02-13 10:11 UTC, SeungYeonJeong commented
안녕하세요 성주 리뷰어님!
리뷰 주신 내용에 기반해 리팩토링 수행하였습니다.
다만 몇몇 리뷰는 수정 방향성이 감이 오지 않아 우선 수정하지 않고 리뷰요청 드립니다 😢
방향성에 대해 조언해주시면 다시 리팩토링 해보겠습니다!
리뷰 부탁드립니다. 감사합니다 😄

2022-02-14 14:04 UTC, liquidjoo commented on src/main/java/calculatorFunction/Calculator.java
> +        this.result = Double.parseDouble(parsedValues.get(0));
만약 다른 사용자가 파라미터의 타입만 보고 사용했을 때에 어떤 문제가 일어날 수 있을까요?

2022-02-14 14:07 UTC, liquidjoo commented on src/main/java/racingcar/domain/Winner.java
> +    private final List<Car> winners = new ArrayList<>();
Car 의 도메인 로직이 Winner 를 만드는데 적절한 책임일까요?
Winner 에서 Car 의 도메인 로직 중 하나인 moveCarRandomly 가 필요할까요?
> 객체의 캡슐화도 생각해보면 좋을 것 같아요 :)

2022-02-14 14:09 UTC, liquidjoo commented on src/main/java/racingcar/view/InputView.java
> -    public List<String> getName() {
[](https://madplay.github.io/post/prefer-lists-to-arrays)배열 대신 컬렉션을 사용하면 어떨까요? 아래의 글이 도움 되면 좋겠어요.

[https://madplay.github.io/post/prefer-lists-to-arrays](https://madplay.github.io/post/prefer-lists-to-arrays)

2022-02-14 14:12 UTC, liquidjoo commented on src/main/java/racingcar/controller/RaceController.java
>          OutputView.printWinners(winner.getWinners());
Controller 의 역할이 무엇일까요?

2022-02-14 14:13 UTC, liquidjoo commented on src/main/java/racingcar/domain/Race.java
> +    private final List<List<Car>> histories = new ArrayList<>();
컬렉션에서 다시 컬렉션으로 사용하게 되면 가시성이 많이 떨어지게 되며 로직의 복잡도가 올라갈 것 같아요
List<Car> 를 포장할 수 있는 객체를 한번 만들어보면 어떨까요?

2022-02-14 14:14 UTC, liquidjoo commented on src/test/java/racingcar/domain/CarTest.java
> +        car.moveCarRandomly(() -> false);
랜덤적 요소가 강해 테스트하기 어려운 것을 테스트 하는 방법 중 하나인데 이를 전략패턴이라고 합니다 :)
> https://ehdgml3206.tistory.com/64

2022-04-04 06:02 UTC, closed without merging