[최현민] 문자열 계산기, 자동차 경주 게임 (step2)
next-step/java-racingcar pull request #3056
Opened 2022-02-09 08:05 UTC by Gal2o

피드백을 반영하여 리팩토링 진행했습니다.

부족한 부분 알려주시면 바로 바로 수정하겠습니다!

2022-02-09 10:50 UTC, vsh123 requested changes
현민님 안녕하세요!!
mvc에 맞게 Step2구현 잘해주셨네요!!

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!

2022-02-09 10:50 UTC, vsh123 commented on src/main/java/racingcar/view/Console.java
> +    public static int setTryCount() {
`set` 보다는 `get`느낌인데요! 어떻게 생각하시나요?

2022-02-09 10:50 UTC, vsh123 commented on src/main/java/racingcar/view/Console.java
>              throw new IllegalArgumentException(RacingCarException.CAR_NAME_INVALID);
`RacingCarException`을 활용해보면 어떨까요?

```suggestion
            throw new RacingCarException(RacingCarException.CAR_NAME_INVALID);
```

2022-02-09 10:50 UTC, vsh123 commented on src/main/java/racingcar/domain/FixedMove.java
> +public class FixedMove implements MoveStrategy {
해당 클래스는 미사용인 것 같은데요! 생성하신 이유가 있을까요?

2022-02-09 10:50 UTC, vsh123 commented on src/test/java/racingcar/domain/RandomGenerateTest.java
> +    @DisplayName("랜덤한 수의 범위는 0 ~ 9까지이다.")
랜덤에 대한 테스트는 결과값을 정확히 모르기때문에, 불확실한데요!! 만약 테스트하고싶다면 [RepeatedTest](https://www.baeldung.com/junit-5-repeated-test)를 통해 테스트를 여러번 수행해보면 어떨까요?

2022-02-09 10:50 UTC, vsh123 commented on src/test/java/racingcar/domain/RacingCarTest.java
> +        madeRacingCars.get(0).moveCar(moveStrategy);
`RacingCarTest`라면 `RacingCars`가 아니라 `RacingCar`객체만을 만들어서 테스트를 수행해보면 어떨까요?

2022-02-09 10:50 UTC, vsh123 commented on src/test/java/racingcar/domain/RacingCarTest.java
>      @DisplayName("테스트에 필요한 자동차들을 생성한다.")
해당메서드는 테스트가 아니기 때문에 `DisplayName`이 적용되지 않을거에요!

2022-02-09 10:50 UTC, vsh123 commented on src/main/java/racingcar/domain/MoveStrategy.java
> +public interface MoveStrategy {
`MoveStrategy` 활용 👍

2022-02-10 08:41 UTC, Gal2o commented on src/main/java/racingcar/domain/FixedMove.java
> +public class FixedMove implements MoveStrategy {
전략 패턴을 처음 적용해보다보니 사용하지 않을 클래스도 만들어버린 것 같습니다. 😭

2022-02-10 08:45 UTC, Gal2o commented on src/main/java/racingcar/view/Console.java
>              throw new IllegalArgumentException(RacingCarException.CAR_NAME_INVALID);
아이고.. 만들어두고 사용을 안했네요

2022-02-10 08:56 UTC, Gal2o commented on src/main/java/racingcar/view/Console.java
> +    public static int setTryCount() {
입력 받은 TryCount를 받아오니까 getTryCount가 적합할 것 같습니다!

2022-02-11 13:24 UTC, vsh123 requested changes
현민님 안녕하세요!
피드백 반영 잘해주셨네요! 💯 

몇가지 자잘한 내용을 코멘트 남겼습니다!
다음 요청에는 머지하도록 하겠습니다!! 궁금하신점은 코멘트 부탁드려요~!

2022-02-11 13:24 UTC, vsh123 commented on src/main/java/racingcar/view/Console.java
> +    public static List<String> setRacingCarNames() {
요것두 set보다는 get인 것 같아요~!

2022-02-11 13:24 UTC, vsh123 commented on src/main/java/racingcar/controller/RacingCarGame.java
>      private void setRacingWinners() {
해당 메서드 안에 `car.getCarDist() == maxMove`라는 내용이 있는데요!
`carDist`를 get하기보다는 car객체에게 메세지를 전달해보면 어떨까요?

```java
winners = cars.stream()
            .filter(car -> car.isMaxDist(maxMove))
            .collect(Collectors.toList());
```

2022-02-11 13:24 UTC, vsh123 commented on src/main/java/racingcar/controller/RacingCarGame.java
>      private List<RacingCar> winners;
해당 필드가 RacingCarGame에 있어야 할 필요가 있을까요??

`playRacingCarGame()`메서드안에서만 있어도 괜찮을 것 같아요!

2022-02-12 07:12 UTC, Gal2o commented on src/main/java/racingcar/controller/RacingCarGame.java
>      private void setRacingWinners() {
carDist를 받아오는 것과 Car객체에게 메시지를 전달하는 이유는 단위를 더 분리하기 위함으로 생각해도 될까요?

2022-02-12 07:12 UTC, Gal2o commented on src/main/java/racingcar/controller/RacingCarGame.java
>      private List<RacingCar> winners;
레이싱 게임을 하는데만 사용하니 지역변수로 선언하는 것이 맞는 것 같습니다. 😄

2022-02-12 13:20 UTC, vsh123 commented on src/main/java/racingcar/controller/RacingCarGame.java
>      private void setRacingWinners() {
넵! 코드를 작성할때는 해당 객체의 상태를 get해서 하려는 것보다, 항상 메서드를 통해 물어보는 습관을 가지면 좋을 것 같아요!

2022-02-14 03:03 UTC, vsh123 approved these changes
현민님 안녕하세요!
자동차 경주 미션 고생많으셨습니다!! :)

다음 미션도 화이팅하시길 바라겠습니다!!
이번 미션은 머지하도록 할게요!

2022-02-14 03:03 UTC, merged