[김현수] 문자열 계산기, 자동차 경주 게임 (step2)
next-step/java-racingcar pull request #3058
Opened 2022-02-09 17:55 UTC by hscom96

안녕하세요 리뷰어님 !! 😀
1단계 피드백 반영하여 리뷰 요청드립니다.

진행하며 정말 많은 깨우침이 있었습니다 😆
항상 감사드립니다 !!

2022-02-11 03:34 UTC, Rok93 requested changes
현수님 2단계도 잘 구현해주셨네요! 👍👍👍 
몇몇 코멘트 달아놓았으니 확인해서 반영해주세요! 🙏 
이해가 잘 안되거나 어려운 부분은 언제든지 DM주세요! 😃

2022-02-11 03:34 UTC, Rok93 commented on src/test/java/racingcar/domain/CarsTest.java
> +    void 유효성검증_중복검사(){
해당 테스트 코드는 통과하지 않을 것 같아요. 👀 
왜 그런지 고민해보고 혹시라도 이유를 잘 모르겠다면 같이 논의해봐요! 🤗

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/controller/RacingController.java
> +        RacingGame racingGame = initRacingGame(carNames, endRaceCount);
메서드로 추출할 필요 없이, 바로 RacingGame 객체를 생성해도 될 것 같아요! 😃 

```suggestion
        RacingGame racingGame = new RacingGame(Cars.of(carNames), endRaceCount, new RandomMoveStrategy());
```

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/domain/Name.java
> +    private void isCorrectNameSize(String name) {
**메서드 네이밍**에 주의해주세요. 🙏
`isXXX` 의 경우 반환 값 타입이 `boolean`이라고 생각하기 쉬워요. 🤔

[참고 자료](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/domain/RacingCar.java
>      }
`move` 메서드는 아래와 같이 변경해보면 어떨까요? 🤗 

```java
    public void move(MoveStrategy moveStrategy) {
        if (moveStrategy.isMoveable()) {
            position++;
        }
    }

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/domain/RacingGame.java
> +        List<Cars> racinglog = new ArrayList<>();
**변수명**은 `lowerCamelCase`를 지켜주세요! 🙏

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/view/RacingCarInput.java
> +        return Arrays.asList(input.split(COMMA));
`getCarName` 메서드 코드를 아래와 같이 변경해보면 어떨까요? 🤔
변수의 `선언`과 `할당`은 동시에 진행해주세요! 🙏

```java
RacingCarView.printMessage(INPUT_CARNAME_MESSAGE);
        try {
            String input = scanner.nextLine();
            return Arrays.asList(input.split(COMMA)); //todo: try문안에 위치시키게하기!
        } catch (IllegalArgumentException e) {
            System.out.println(ERROR_MESSAGE + e.getMessage());
            return getCarName();
        }
```

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/view/RacingCarInput.java
>      public static int getRaceCount() {
RacingCarInput 클래스 내부 메서드들은 `get` 보다는 `input`으로 시작하는게 더 좋지 않을까요? 🤔
되도록 `get`, `set`으로 시작하는 메서드명은 지양해주세요! 🙏

2022-02-11 03:34 UTC, Rok93 commented on src/main/java/racingcar/view/RacingCarView.java
> +        String winners = cars.getWinners().stream()
`cars.getWinners`는 Controller에서 호출하는게 맞지 않을까요? 🤔 
getWinners라는 메서드명 때문에 cars 객체의 상태 값을 외부로 호출하는 거라고 생각했는데 비즈니스 로직을 수행하는 메서드였군요? 🤔  

이렇듯 가급적 자바 진영의 관습적인 표현과 겹치는 네이밍은 지양하는 것이 좋습니다. 😃

2022-02-11 03:34 UTC, Rok93 commented on src/test/java/racingcar/domain/CarsTest.java
>      @CsvSource(value = {"true:1", "false:0"}, delimiter = ':')
`테스트 코드 네이밍`(= 모든차앞으로전진) 또한 신경써주세요! 🙏 
해당 테스트는 `전진하는 케이스`만 테스트하고 있는 것이 아니라 `전진하지 않은 케이스`에 대해서도 테스트하고 있는 것 같아요. 😃 
`모든_자동차_앞으로_전진_또는_정지`로 변경해보면 어떨까요? 🤗  (공백이 거슬린다면 `@DisplayName` 애너테이션을 사용하는 방법도 있어요!)

2022-02-12 12:41 UTC, Rok93 approved these changes
현수님 피드백 반영 잘해주셨어요! 💯 👍👍
자동차 경주 미션은 이 정도면 충분한 것 같아서 `이만머지`하도록 할게요! 👏👏👏 
이번 미션이 현수님의 성장에 많은 도움이 되셨으면 좋겠네요. 😃
피드백 반영하시느라 고생 많으셨고 남은 미션들도 화이팅입니다. 💪

2022-02-12 12:41 UTC, Rok93 commented on src/test/java/racingcar/service/RacingGameTest.java
> +class RacingGameTest {
RacingGame 클래스의 위치와 동일한 패키지 경로로 변경해주세요! 🙏

2022-02-12 12:41 UTC, Rok93 commented on src/main/java/racingcar/domain/RacingGame.java
>      public boolean isOngoing() {
isOngoing 메서드 내부의 `0`는 `매직 넘버`인 것 같아요. 🤔 
추가로 `tryRaceCount`(원시 값)을 포장해볼 수도 있을 것 같아요. 🤗

2022-02-12 12:41 UTC, Rok93 commented on src/main/java/racingcar/view/RacingCarView.java
> +public class RacingCarView {
`RacingCarInput`과 일관성을 맞춰서 `RacingCarOutput`으로 변경해보면 어떨까요? 😃

2022-02-13 07:15 UTC, hscom96 commented
마지막 피드백 반영했습니다 😃 리뷰어님이 피드백주신 덕분에 정말 많은 성장이 된것같습니다. 감사합니다 !

2022-02-14 01:09 UTC, merged