[박민상] 문자열 계산기, 자동차 경주 게임 (step2)
next-step/java-racingcar pull request #3060
Opened 2022-02-18 09:13 UTC by minsang0850

private 메소드는 테스트를 진행할 수 없어서 public으로 작성했는데 이런 경우에 어떻게 해야 하는지,
repeatGame처럼 랜덤 값이 들어가는 메서드는 어떻게 테스트를 진행해야하는지 궁금합니다.

2022-02-20 15:41 UTC, Rok93 requested changes
민상님 2단계 구현 잘해주셨네요! 👍
PR 코멘트로 질문 주신 내용은 코멘트로 답변 달아두었어요. 😊
몇몇 코멘트 남겨두었으니 확인해서 반영해주세요! 🙏

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/controller/RacingGame.java
> +        race.repeatGame(times.getTimes());
times 객체의 상태 값을 전달하는 것이 아니라, times 객체를 `repeatGame` 메서드의 인자로 넘겨주세요! 🙏

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
>      public void repeatGame(int times) {
PR 코멘트에도 질문 주셨지만, 해당 메서드를 보는 순간 테스트하기가 어려울 거라는 느낌이 들었어요. 👀
먼저 테스트를 위해서 private 메서드를 public 메서드로 변경하는 것은 지양해야 해요. 🙄 

그 이유는 repeatGame의 메서드드 안에는 테스트하기 힘든 부분이 섞여 있기 때문이에요. 🤔
저희의 목표는 테스트하기 힘든 부분을 테스트하기 쉬운 부분으로부터 분리함으로써 최대한 테스트 영역을 늘려나가는 것이에요. 🤗

감이 잘 안 잡히신다면 아래의 영상을 참고해보시면 좋을 것 같아요. 😃
[[OKKYCON: 2018] 정진욱 - 테스트하기 쉬운 코드로 개발하기](https://www.youtube.com/watch?v=cVxqrGHxutU)


(강의 자료에도 이런 힌트가 있어요!)
<img width="950" alt="image" src="https://user-images.githubusercontent.com/47850258/154849586-5c33cb8a-8502-44fc-81b4-154e979b7b8b.png">

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
> +    public List<String> WinnerNames() {
메서드의 네이밍은 `동사 or 동사구`의 `lowerCamelCase`로 작성해주세요! 🙏

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/domain/Times.java
> +    }
아래와 같이 변경해보면 어떨까요? 🤔 
```suggestion
    private int times;

    public Times(int times) {
        validateTimes(times);
        this.times = times;
    }

    private void validateTimes(int times) {
        if (times <= 0) {
            throw new IllegalArgumentException("[ERROR] - 0보다 큰 정수를 입력해주세요.");
        }
    }
```

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/domain/Times.java
> +        if (times <= 0) {
또한  `매직 넘버`인  `0`을 적절히 `상수`로 변경해보면 어떨까요? 🤗

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/view/InputView.java
> +        return sc.nextLine();
int 타입으로 받지않고 String으로 입력받는 이유가 있을까요? 🤔

2022-02-20 15:41 UTC, Rok93 commented on src/test/java/racingcar/domain/CarTest.java
> +
`Car#comparePosition` 메서드에 대한 테스트 코드도 작성해주세요! 🙏

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
>      public int getMaxScore() {
내부에서만 사용되는 메서드는 접근 제한자를 `private`으로 변경해주세요! 🙏

2022-02-20 15:41 UTC, Rok93 commented on src/main/java/racingcar/view/OutputView.java
> +        List<String> winnerNames = race.WinnerNames();
해당 부분은 비즈니스 로직인 것 같아요. 👀
Controller에서 `raceWinnerNames`를 호출한 뒤, 그 결과를 메서드 파라터로 넘기도록 변경해주세요! 🙏

2022-02-20 16:19 UTC, minsang0850 commented on src/main/java/racingcar/view/InputView.java
> +        return sc.nextLine();
nextint를 사용하면 버퍼에 \n이 남아서 다음에 nextline을 호출할때 에러가 발생했습니다.

2022-02-20 18:19 UTC, minsang0850 commented on src/main/java/racingcar/domain/Race.java
>      public void repeatGame(int times) {
메소드를 최대한 분리했는데도 어떻게 테스트해야할지 모르겠습니다 ㅠㅠ

2022-02-21 15:40 UTC, Rok93 requested changes
민상님 피드백 반영 잘 해주셨어요! 👍
이제 정말 얼마 안 남았어요! 💪
테스트 코드만 조금 보강하면 2단계는 마무리될 것 같아요. 😊
테스트 부분이 많이 어렵게 느껴지신다면 꼭 DM 주세요! 😉

2022-02-21 15:40 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
>          }
아래와 같이 times 객체의 상태 값을 외부애 꺼내서 직접 로직을 수행하는 것이 아니라 메시지를 보내보면 어떨까요? 🤗
[getter를 사용하는 대신 객체에 메시지를 보내자(https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)

```suggestion
        while(times.isOngoing()) {
            for (int j = 0; j < count; j++) {
                raceOneStage(cars);
            }
            times.decrease;
        }
```

2022-02-21 15:40 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
> +            raceOneTime(car, getRandomNumber());
`repeatGame` 메서드를 테스트하기 위해서는 테스트하기 어려운 `random` 요소를 **외부로 추출**해야해요. 😃
메서드 파라미터 혹은 생성자 파라미터로 Random 요소를 받아서 테스트하기 쉬운 코드와 어려운 코드를 분리해보세요! 🙏

2022-02-21 15:40 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
> +    public void raceOneTime(Car car, int randomNumber) {
이 메서드의 입장에서 메서드 파라미터로 들어오는 값이 `randomNumber`인지 알 필요가 없어요. 👀
`condition`과 같은 네이밍은 어떨까요? 🤗

2022-02-21 15:40 UTC, Rok93 commented on src/main/java/racingcar/domain/Times.java
> +        if (times < minTimes) {
아래와 같이 `minTimes`는 인스턴스 변수가 아니라 상수로 추출해야할 것 같아요. 🤔
```suggestion
    private static final int MIN_TIMES_VALUE = 1;
    
    private final int times;

    public Times(int times) {
        validateTimes(times);
        this.times = times;
    }

    private void validateTimes(int times) {
        if (times < MIN_TIMES_VALUE) {
```

2022-02-21 15:40 UTC, Rok93 commented on src/main/java/racingcar/domain/Race.java
> +    private void raceOneStage(List<Car> cars) {
`raceOneTime` 메서드는 Race 클래스 내부에서만 호출되는 메서드인 것 같아요. 🤔
접근 제한자를 `private`로 변경해보면 어떨까요? 🤔

2022-04-04 06:02 UTC, closed without merging