Step2 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #3151
Opened 2022-04-07 14:02 UTC by pangnem

문자열 덧셈 계산기 코드 제출합니다~

2022-04-07 15:17 UTC, seondongpyo requested changes
2단계 미션도 잘 진행해주셨네요!
몇 가지 고민해보실만한 부분들을 코멘트로 드렸는데 확인 부탁드릴게요.
미션 진행하시면서 질문이나 의견 나누고 싶으시면 편하게 DM 주세요!

조금만 더 힘내주시고 다시 리뷰 요청 부탁드립니다 🔥

2022-04-07 15:17 UTC, seondongpyo commented on src/test/java/calculator/PositiveTest.java
> +        }
숫자가 아닌 값과 관련된 프로그래밍 요구사항은 다음과 같습니다.
`문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw한다.`

요구사항에 따라 `NumberFormatException`이 아닌, `RuntimeException`을 던지도록 해보면 어떨까요?

2022-04-07 15:17 UTC, seondongpyo commented on src/test/java/calculator/PositiveTest.java
> +    class 생성자는 {
테스트 코드를 `@Nested`를 통해 계층형으로 작성하시는 걸 선호하시는 걸로 보입니다.
개인적으로는 inner class와 들여쓰기 때문에 테스트를 한 눈에 직관적으로 확인하는 게 어렵지 않을까 생각하는데,
주영님께서 생각하시는, 테스트를 이렇게 계층형으로 작성하는 데서 얻을 수 있는 이점이 무엇인지 궁금합니다.
(물론 코드를 어떻게 작성하느냐는 개인 취향의 문제이기 때문에, 꼭 테스트를 이렇게 작성하면 안 된다는 의미는 아닙니다)

2022-04-07 22:58 UTC, pangnem commented on src/main/java/calculator/Positive.java
> +    }
> equals() 메서드를 이렇게 재정의하신 이유를 설명해주실 수 있을까요?
positive 값을 테스트 하기 위해 테스트 코드에서 다음과 같이 값을 테스트 하기 위해 equals()를 재정의 하였는데요,
```java
assertThat(new Positive("1")).isEqualTo(1);
```
근데 지금 생각해보니 `getNumber()`라는 메서드가 이미 있어서 굳이 할필요는 없어 보이네요.

> 다음 테스트 코드는 어떻게 동작할까요?
assertThat(new Positive(1)).isEqualTo(new Positive(1));
positive 객체를 int형으로 변환하기 때문에 에러가 발생할 것 같습니다.

2022-04-08 03:50 UTC, pangnem commented on src/test/java/calculator/PositiveTest.java
> +    class 생성자는 {
저는 메서드의 Input이 달라짐에 따라 결과값이 달라지는 것을 아는게 중요하다고 생각했기 때문에 계층형으로 작성하는 것을 선호합니다. 
또한 메서드마다 구분하기 때문에 문제가 생겼을 때 해당 영역을 빠르게 찾을 수 있다는 것도 장점이라고 생각됩니다. ( 물론 팀 컨벤션이 가장 우선이지만요 )

Javascript의 Jest는 아예 함수 이름이 describe-context-it으로 되어 있어 직관적인 것 같은데, Java에서도 이런 라이브러리를 쓰면 그나마 조금 더 나아질 것 같긴 하네요. 그래도 일단 Junit에만 집중하는 게 좋을 것 같아요

2022-04-08 04:40 UTC, seondongpyo approved these changes
피드백 반영하시느라 고생 많으셨습니다!
이번 단계는 여기서 merge 하도록 할게요.

이제 본격적인 자동차 경주 미션이네요.
난이도가 조금 높아지지만 잘 해내실 거라 믿습니다.
다음 단계도 힘내주시고 즐거운 주말 보내시길 바랍니다 🔥

2022-04-08 04:40 UTC, seondongpyo commented on src/main/java/calculator/Positive.java
> +    }
생성자에서 먼저 호출되는 메서드가 `checkInt()`인데요,
코드의 가독성을 위해 `checkInt()` 메서드의 위치를 `toInt()`보다 위로 옮겨보는 건 어떨까요?

2022-04-08 04:40 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
현재 `StringAddCalculator` 클래스는 정적 메서드만을 포함하고 있기 때문에
생성자를 호출하여 인스턴스를 생성하지 않고도 사용할 수 있는 상태입니다.
굳이 인스턴스를 생성하지 않아도 된다면, `private` 생성자를 통해 불필요한 인스턴스화를 막아보는 건 어떨까요?
저번 리뷰 때 말씀드렸으면 좋았을텐데 코멘트가 늦었습니다 😥

2022-04-08 04:40 UTC, merged