feat: car racing game without tdd
next-step/java-racingcar pull request #3180
Opened 2022-04-09 13:52 UTC by akayj820

안녕하세요!
step3 자동차 경주 게임을 TDD로 구현해보려고 하니 어디서부터 시작해야할지 막막하더라구요🤔
그래서 기능을 조금씩 만들다보니 그냥 단위 테스트 없이 구현해버리고 말았습니다...
처음부터 다시 TDD로 구현해야할 지 아니면 지금 상태에서 리펙토링 해나가는 것이 좋을지 잘 모르겠어서 이렇게 리뷰 요청드립니다.
리뷰어님의 혜안이 필요합니다.🙏

2022-04-09 15:47 UTC, simjunbo requested changes
자동차 경주 첫번째 미션 잘 진행해 주셨습니다 :)

다음도 같이 고려해 보시기 바랍니다.

1) 현재 테스트가 구현되어 있지 않은데 UI 부분을 제외한 **핵심 기능 요구사항** 에 대해서 테스트를 구현해 보시면 좋을 것 같습니다.
2) README.md 파일에 구현한 기능 목록을 정리해 주시면 좀 더 쉽게 구현 내용을 파악할 수 있을 것 같습니다.
3) 앞에서 피드백 드린 커밋 유형 정말 잘 반영해 주셨습니다! 👍  단, 현재 커밋 단위가 너무 큰 것 같습니다.
요구사항에 나와 있는데로 앞으로는 기능 목록 단위로 commit 해 보는건 어떨까요? 

몇가지 리뷰 남겨 놓았으니 확인해 보시고 재요청 부탁드립니다!

저도 TDD를 잘 하는것은 아니지만 질문에 답변을 드리면
전체를 TDD로 시작하는 것 보다 외부 의존도를 갖지 않는 도메인 객체들로 시작해 보면 어떨까요?
의존도가 적어 테스트 설정이 비교적 단순하고 요구사항이 명확하기 때문에 테스트 케이스를 만들기 쉬울 것 같습니다.

저는 지금 상태에서 리팩토링 하는것도 괜찮다고 생각하고 대신 기능을 먼저 구현 하더라도 테스트 코드는 꼭 작성해 보시면 좋을것 같습니다.
그리고 미션을 진행 하시면서 의미있는 도메인이 추출되면 조금씩 TDD 대상을 늘려 보는것도 방법일 것 같습니다 😄

2022-04-09 15:47 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +    public static void main(String[] args) {
main이긴 하지만 메소드 라인이 조금 길어지는 것 같습니다.
의미 있는 메소드 단위로 도출 하거나 역할에 맞는 클래스에 위임해 보는것은 어떨까요 ?!

2022-04-09 15:47 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +        System.out.println("실행 결과");
위에서 피드백 드린 부분의 연장인데
RacingCar가 위치값을 가지고 있다면 
출력에 대한 역할은 ResultView 에서 처리할 수 있고
RacingGame의 역할은 좀 더 단순해 지지 않을까 생각됩니다.

2022-04-09 15:47 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +        Random random = new Random();
goAndStop 메서드가 호출될때마다 Random 객체가 새롭게 생성되서 비효율적인 것 같은데
좋은 방법이 없을까요 ?!

힌트) step2 '문자열 계산기'  Pattern.compile

2022-04-09 15:47 UTC, simjunbo commented on src/main/java/carracing/InputView.java
> +public class InputView {
InputView, ResultView 클래스도 외부에서 직접 인스턴스를 생성하지 못하도록 방지해보면 어떨까요 😄

2022-04-09 15:47 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +        if(random.nextInt(10) >= 4) {
요 부분도 의미 있는 상수로 도출해 보면 가독성이 더 좋으질것 같습니다.

2022-04-10 14:39 UTC, akayj820 commented on src/main/java/carracing/RacingCar.java
> +        route.append("-");
리뷰 주신 내용을 토대로 테스트 작성해보았습니다!

2022-04-10 14:41 UTC, akayj820 commented on src/main/java/carracing/RacingCar.java
> +    public StringBuilder route;
기능 구현만 빠르게 하려고 하다보니 바로 접근할 수 있도록 public 접근제어자를 사용하였습니다.
다시 차근차근 테스트 코드와 함께 작성하면서 말씀하신 부분도 private 으로 수정할 수 있었습니다.

2022-04-10 14:42 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +    private static boolean READY = true;
처음에 무조건 모든 자동차에 대해서 -로 출발상태를 표시해야한다고 생각해서 READY라는 조건을 추가하려다 보니 저런식으로 작성이 되었습니다. 해당 부분도 수정하여 출발상태는 표시하지 않고 바로 racing을 진행하도록 로직 수정하였습니다.

2022-04-10 14:43 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +    private static final boolean GO = true;
자동차의 전진/멈춤 여부에 대해 속성값을 RacingCar 클래스 안으로 옮기면서 해당 부분은 삭제하였는데 삭제하면서 의미파악이 더 어렵게 된 것은 아닌지 확인 한번 부탁드리겠습니다.

2022-04-10 14:44 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +    public static void main(String[] args) {
main 메소드를 GamePlay 클래스를 안에 따로 구현하였습니다. 나머지 메소드 들은 역할에 맞는 클래스들로 위임하여 구현해 보았습니다.

2022-04-10 14:45 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +        System.out.println("실행 결과");
RacingCar에 position 속성을 추가하여 리뷰 주신 내용을 실제로 적용해 보았습니다. 
말씀주셨던 것 처럼 RacingGame의 역할을 더 확실하게 분리할 수 있었습니다.

2022-04-10 14:46 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +        Random random = new Random();
이번에 리뷰 주신 내용과 지난 리뷰를 참고하여 해당 부분도 수정해보았습니다.

2022-04-10 14:47 UTC, akayj820 commented on src/main/java/carracing/InputView.java
> +public class InputView {
리뷰 주신 내용을 토대로 생성자에 private 접근제어자를 붙여 수정해보았습니다.

2022-04-10 14:47 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +        if(random.nextInt(10) >= 4) {
10이라는 리터럴을 의미 있는 상수로 변경해보았습니다.

2022-04-10 15:22 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +    private static final boolean GO = true;
@akayj820 moved에 대한 상태를 어떻게 사용할 계획인지 궁금합니다. ?! 🤔
앞으로 사용계획이 없다면 삭제 하는것은 어떨까요?

2022-04-10 15:29 UTC, akayj820 commented on src/main/java/carracing/RacingGame.java
> +    private static final boolean GO = true;
뭔가 계속 테스트를 염두하다보니 조금은 불필요한 필드가 추가되었던 것 같습니다. 말씀주신 부분 수정해서 다시 커밋하도록 하겠습니다.

2022-04-10 16:19 UTC, simjunbo approved these changes
피드백 멋지게 반영해 주셨네요 👍 
몇가지 소소한 리뷰 남겨 놓았으니 다음 단계 진행 시, 같이 고민해 주시면 좋겠습니다. 😄 

미션 진행 하시면서 궁금하신 부분이나 논의해보고 싶은 부분이 있다면
편하게 코멘트나 DM 남겨 주시기 바랍니다.

4단계 자동차 경주 미션도 화이팅 입니다 ❗❗❗

2022-04-10 16:19 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +    public static void racing(List<RacingCar> carList) {
참고만 하세요.
개인 취향일 수도 있는데 변수나 메서드등에 자료형 이름을 넣는것을 지양하는 편입니다.
만약 요구조건이 변경되서 List대신 Set을 사용한다면?
관련 부분의 수정이 필요할 것입니다.

cars 등의 복수형으로 표현해 보는 것은 어떨까요 ?!

2022-04-10 16:19 UTC, simjunbo commented on src/main/java/carracing/ResultView.java
> +    public static final String ROUTE = "-";
클래스 내에서만 사용되는 인스턴스 변수,클래스 변수, 상수, 메서드 등은 꼭 접근 제한자를 제한해서 외부에 노출되지 않도록 해주세요 😄

2022-04-10 16:19 UTC, simjunbo commented on src/main/java/carracing/RacingGame.java
> +import java.util.List;
사용 않는 import는 삭제해 주는 것이 좋습니다 😄 
링크드렸으니 참고하시기 바랍니다!

1) 단축키 사용
2) auto import 옵션에서 자동 삭제기능 ON

참고) https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=cutesboy3&logNo=221589827112&categoryNo=0&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView

2022-04-10 16:19 UTC, simjunbo commented on src/test/java/carracing/RacingGameTest.java
> +public class RacingGameTest {
테스트 케이스 잘 추가해 주셨네요 👍

2022-04-10 16:19 UTC, simjunbo commented on src/main/java/carracing/ResultView.java
> +    public static void printRacingCarsRoutes(List<RacingCar> carList) {
List는 순서를 보장하니까 다음과 같이도 사용할 수 있겠네요.

````

    public static void printRacingCarsRoutes(List<RacingCar> carList) {
        carList.forEach(car -> System.out.println(makeRacingCarRoute(car)));
    }
````

2022-04-10 16:19 UTC, merged