3단계 - 자동차 경주
next-step/java-racingcar pull request #3187
Opened 2022-04-09 16:53 UTC by devyonghee

안녕하세요 리뷰어님!!
1단계 자동차 경주가 제일 쉬운 과정이라고 하셨는데 생각보다 어려운 것 같습니다 😅

역할별로 클래스로 나누기 위해 노력했는데요
특히, 구현 중에 일급 컬렉션을 많이 활용하고자 했습니다.
그런데 `Tracks` 내부에 있는 필드명이 `tracks` 로 지으면서 고민이 많았는데요.
클래스명과 필드명이 동일하기 때문에 sonarLint 에서 경고 메세지를 보여주는데 
혹시 이런 경우 적절한 필드명이 있을지 궁금합니다.  🤔

이번 리뷰도 잘 부탁드리겠습니다!! 🙇‍♂️

2022-04-11 12:48 UTC, orgojy requested changes
안녕하세요 😄 용희님!

3단계 자동차 경주 미션도 잘 구현해주셨네요!
몇 가지 코멘트를 남겨 두었는데요. 확인해보시고 다시 요청 부탁드릴게요~!
곰곰히 생각해보시고, 의문이 있으신 부분은 코멘트를 활용해주세요.

전반적으로 객체지향과 일급컬렉션의 활용이 정석이고, 인상적이었습니다. 👍 
다만, 리뷰를 진행하는데 `RandomEngine`과 관련하여, 설계에 대한 코멘트를 남겼습니다.
다른 테스트와 코드가 연결되어있어서요. 이 부분부터 논의와 개선을 마치면 그때 다시 리뷰를 진행해도 좋을 것 같습니다.

2022-04-11 12:48 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/sample/RandomEngineSample.java
> +    public static final RandomEngine TEM_LIMIT_RANDOM_ENGINE = RandomEngine.from(new Random(), 1);
샘플 상수 필드를 잘 구현해주셨네요. 👍 
10인것 같은데 맞나요?
```suggestion
    public static final RandomEngine TEM_LIMIT_RANDOM_ENGINE = RandomEngine.from(new Random(), 10);
```
구현하신다면 `RandomEngine`의 테스트 케이스들도 구현해보시면 좋을 것 같아요. 😄

2022-04-11 12:48 UTC, orgojy commented on src/main/java/me/devyonghee/racingcar/model/CarFactory.java
> +    public static CarFactory of(int count, RandomEngine engine) {
이 지점에서 RandomEngine 를 이동 정책이 바뀔 때마다 Random을 이용한 구현 말고도 동작이 가능하게 개선해보면 좋겠네요.
어떻게 생각하세요?

2022-04-11 12:48 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/TracksHistoryTest.java
> +class TracksHistoryTest {
생성시, from에 경주기록이 있는 경우의 테스트를 작성해보는 건 어떨까요? 😄

2022-04-11 12:48 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/RacingCarsTest.java
> +        assertThatNoException().isThrownBy(() -> RacingCars.from(Collections.emptyList()));
Collection<RacingCar> cars 의 요소가 존재하는 케이스를 작성해보는 건 어떨까요?

2022-04-11 12:48 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/TracksTest.java
> +        assertThat(nextCycle.size()).isEqualTo(1);
이렇게 바꿔보셔도 가독성에 좋겠네요. 😄 
```suggestion
        assertThat(nextCycle.size()).isOne();
```

2022-04-11 12:48 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/DistanceTest.java
> +class DistanceTest {
외부 테스트 클래스에서 이 Distance 예시를 사용하는 경우가 많은 것 같은데,
상수로 선언하여 예시 케이스에 대해서 활용해보시는건 어떨까요?

2022-04-11 13:11 UTC, orgojy commented
요걸 까먹었네요.
MVC로 구성해서 Layer 별 책임을 분리시킨 점도 잘해주셨네요. 👍

2022-04-11 13:31 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/RandomEngine.java
> +public final class RandomEngine {
사실 저도 전략 패턴에 대해 고민이 많았는데요.
아직 어떤 방향으로 수정될지, 어떤 컨셉의 엔진이 추가될지 예상되지 않아 아직은 구현체를 의존하도록 했습니다. 
대신 추후 확장이 쉽도록 하나의 역할(메소드)만을 정의했는데요.
혹시 이부분에 대해서 어떻게 생각되시나요??

2022-04-11 13:33 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/sample/RandomEngineSample.java
> +    public static final RandomEngine TEM_LIMIT_RANDOM_ENGINE = RandomEngine.from(new Random(), 1);
아.. 0이 빠졌군요.. 바로 수정하겠습니다.
`RandomEngine` 에 대한 테스트는 `RandomEngineTest` 이곳에 정의했고 sample 만 별도의 클래스로 분리했습니다!!

2022-04-11 13:36 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/CarFactory.java
> +    public static CarFactory of(int count, RandomEngine engine) {
위에서 말씀해주신 전략 패턴과 연관이 있을 것 같습니다.
아직 섣부르게 인터페이스를 정의하는 것보다 추후 추가되는 기능에 따라 결정하고자 구현체를 이용했습니다!
그런데 어차피 하나의 메소드만을 이용하고 있기 때문에 `Engine` 이라는 인터페이스를 추가해도 좋긴하겠네요!!
전략 패턴으로 수정해보도록 하겠습니다!

2022-04-11 13:37 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/RacingCarsTest.java
> +        assertThatNoException().isThrownBy(() -> RacingCars.from(Collections.emptyList()));
위와 동일하게 추가하도록 하겠습니다!

2022-04-11 13:39 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/Tracks.java
> +    private final List<Track> tracks;
`Group` 이라는 단어도 있었군요! 기존에 하던 습관이 있어서 생각하지 못했던 것 같습니다. 
참고하겠습니다!! 감사합니다!🙇‍♂️

2022-04-11 13:39 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/TracksTest.java
> +        assertThat(nextCycle.size()).isEqualTo(1);
아! 감사합니다!! 수정하겠습니다!

2022-04-11 13:45 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/RacingCarTest.java
> +        when(random.nextInt(anyInt())).thenReturn(rotation);
최대한 실제 사용되는 구현체를 사용하는 것이 목적이었습니다.
하지만 `Random` 객체는 테스트하기 어려운 부분이기 때문에 어쩔 수 없이 `mock` 을 사용하게 됐습니다. 
이건 전략 패턴으로 변경하면서 `Fake` 객체를 사용하는 방향으로 수정해보겠습니다!

2022-04-11 13:46 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/DistanceTest.java
> +class DistanceTest {
`Distance` 객체에 이미 선언되어 사용되는 상수들이 있기 때문에
해당 상수로 대체하는 방향으로 변경하겠습니다!

2022-04-11 13:57 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/RacingCar.java
> +    private static final int MIN_MOVING_ROTATION_LIMIT = 4;
이 부분에 대해 다시 한번 더 고민해보고 작업해보겠습니다.

2022-04-11 15:53 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/RandomEngine.java
> +public final class RandomEngine {
`MovementPolicy` 이라는 인터페이스를 추가하면서 
전략 패턴을 적용해봤습니다!!

2022-04-11 15:54 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/controller/RacingCarRace.java
> +    private static final int RANDOM_LIMIT = 10;
말씀을 나눠보고 `RandomMovementPolicy` 이라는 구현체에게 이 역할을 위임하여 응집도를 높이고자 했습니다!

2022-04-11 15:55 UTC, devyonghee commented on src/main/java/me/devyonghee/racingcar/model/RacingCar.java
> +    private static final int MIN_MOVING_ROTATION_LIMIT = 4;
이동 정책에 대한 객체를 추가하여 값을 이동시켰습니다!

2022-04-11 17:40 UTC, orgojy commented on src/test/java/me/devyonghee/racingcar/model/RandomMovementPolicyTest.java
> +        assertThat(RacingCar.from(RandomMovementPolicy.from(random)).movement()).isEqualTo(expected);
다음과 같이 람다를 활용하는 방법도 참고해주세요~
mock을 따로 구현하지 않아도 가능할 것 같습니다.
```suggestion
        assertThat(RacingCar.from(() -> Movement.MOVE).movement()).isEqualTo(expected);
```

2022-04-11 17:42 UTC, orgojy approved these changes
안녕하세요 😄 용희님!

3단계 자동차 경주 미션도 잘 구현해주셨네요!
좋은 코드에 대해서 고민하신 흔적이 보이고 개선이 잘 이루어져서 좋네요.

개선점에 대해서 빠르게 파악하시고, 반영하시네요. 👍 

PR은 머지하도록 하겠습니다. 다음 미션도 응원합니다! 🚀

2022-04-11 17:43 UTC, merged

2022-04-12 01:34 UTC, devyonghee commented on src/test/java/me/devyonghee/racingcar/model/RandomMovementPolicyTest.java
> +        assertThat(RacingCar.from(RandomMovementPolicy.from(random)).movement()).isEqualTo(expected);
코멘트 감사합니다! 🙇‍♂️
그런데 이 테스트는 `RacingCar` 가 아니라 `MovementPolicy` 에 대한 테스트였는데 제가 실수했네요
그래서 람다보다 `Random` 을 그대로 mock 처리한 테스트로 유지하겠습니다!