Step3 자동차 경주[younlll]
next-step/java-racingcar pull request #3189
Opened 2022-04-09 17:35 UTC by younlll

안녕하세요!🙂
우선 미션 2에서 추가로 리뷰해주신 `사용하지 않는 변수 제거` 와 `enhanced for loop 사용`을 적용해보았습니다.

미션 3단계인 자동차 경주에서 일부 기능을 구현해보았습니다.
현재 구현한 내용은
1. 기능을 구현하기 전에 README.md 파일에 구현할 기능 목록을 작성했습니다.
2. 기능 목록 중 첫 번째와 두 번째로 기재한 `게임을 진행할 횟수 입력 받는다`와 `게임이 진행되는 동안 참여하게 되는 자동차의 수 입력 받는다`를 구현했습니다.

- - -

입력까지만 구현한 뒤에 PR을 요청한 이유는
1. 입력 하는 내용에 대한 테스트를 생각하고 작성한 뒤, 구현을 해보았는데 맞게 테스트를 고려한 것인지 확신이 들지 않습니다.
2. RacingGame 클래스에 구현한 예외 처리 메서드에 대해서 private로 만들어서 외부에서 접근이 되지 않도록 하고 싶습니다.
하지만 startRacingGame() 메서드를 통해서 예외 처리 메서드를 접근 하려면 키보드 입력을 받는 기능을 거쳐야하고
해당 기능을 거치지 않기 위해서 예외 처리 메서드를 직접 호출하려다 보니 public으로 선언을 하게 되었습니다.
이 부분에 관련해서 어떤 방식으로 풀어야할지 조언을 구하고싶습니다😥

2022-04-09 18:09 UTC, younlll commented
코드를 보다보니 사용하지 않는 패키지들을 안 지우고 push를 해버렸네요... 😥
다음 구현하면서 해당 부분 수정을 하겠습니다~

2022-04-10 02:59 UTC, csh0034 requested changes
안녕하세요. 유나님.

3단계 진행 하시느라 수고 많으셨습니다.

사용자가 입력한 정보에 따라 자동차의 상태를 화면에 출력한다는
기능 요구사항이 있는데 구현되어 있지 않네요. 단위 테스트도 빠져있구요 😢

기능 요구사항 및 프로그래밍 요구사항을 다시 확인 해주시고
수정후에 리뷰 요청 부탁드려요.

추가로 문자열 덧셈 계산기와 자동차 경주 패키지를 분리하여 
코드가 섞이지 않도록 구현 해주시면 좋을것 같습니다. 😃

2022-04-10 14:54 UTC, csh0034 requested changes
안녕하세요. 유나님.

3단계 진행 하시느라 수고 많으셨습니다.
몇가지 코멘트 남겨두었는데 확인해주시고
다시 리뷰 요청 부탁드립니다.


혹시 코멘트가 이해 안가시거나 추가로 궁금하신 사항 있으시면
편하게 DM 주세요 😄

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/view/OutputView.java
> +    public static String getDashOnDistanceByCars(int movementDistance) {
`Constant.MOVE_DISTANCE_MARK.repeat(movementDistance)` 로 간략하게 나타낼수 있을것 같습니다.
만약 넘어온 movementDistance 값에 대해 검증이 필요하다면 별도로 자동차의 포지션에 대한 값을 나타내는 객체(원시값을 wrapping 한 객체)를 추가해보는건 어떨까요?

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/model/CarsProgress.java
> +            cars.setDistanceTraveled(Constant.MOVEMENT_DISTANCE_INITIAL_VALUE);
해당 과정을 진행하며 setter 와 getter 의 사용을 최대한 사용하지 않는것을 추천드려요.
객체를 설계하였으나 내부 값을 임의로 변경하는건 올바른 객체 사용법이 아닙니다.

초기값을 세팅해주기 위함이라면 생성자를 통해서 해보는건 어떨까요?

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/model/CarsProgress.java
> +            cars.setDistanceTraveled(cars.getDistanceTraveled() + 1);
이경우 에도 getter 와 setter 를 사용하는것이 아닌 객체에게 메세지를 보내서 내부 값을 변경하게 해보는걸 고민해주시면 좋을것 같습니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/commons/Constant.java
> +public class Constant {
이전 단계에서 리뷰 드린 내용을 다시 정리하자면

"상수 클래스를 선언 하는것보다 각 클래스의 역할(책임)에 따라 해당 클래스에 선언하는것을 먼저 고려하는것이 좋다. " 라고 리뷰 드렸었습니다. 

하단 내용들은 여러 클래스에서 중복되는 내용이아니므로 InputView, OutView, 커스텀 예외 클래스 등등 내부에 선언 하는것으로
변경해주시는것이 명확할것 같습니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
하나의 자동차를 표현하는 클래스라면 Car 단수로 표현하는것이 좋을것 같습니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/domain/Cars.java
> +    public void setDistanceTraveled(int distanceTraveled) {
setter 보단 값이 1씩 증가하는게 명확하므로 내부에서 하나씩 증가하도록 처리하는 메서드로 변경해보는건 어떨까요?

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/controller/InputService.java
> +    private String validationInputValue(String inputValue) throws InputValueException {
RuntimeException 하위 클래스를 throw 하는것이 어떤 의미가 있을까요?
또한 메서드 내부에서 InputValueException 가 발생하고 있지 않습니다 😢

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/controller/InputService.java
> +public class InputService {
Service 라는 이름보단 사용자의 입력을 검증한다는 내용을 포함하는 더 구체적인 클래스명을 고민해주시는걸 추천드립니다.
추가로 이 클래스는 controller 의 역할이 아니기 때문에 다른 패키지에 있어야한다고 생각되는데 유나님은 어떻게 생각하시나요?

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/view/InputView.java
> +        return scanner.nextLine();
nextInt() 를 사용하여 int 로 받아오는게 좋을것 같습니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/controller/InputService.java
> +        if (!inputValue.matches(Constant.NUMERIC_REGEX)) {
입력값을 스캐너에서 int 로 받아오면 체크하지 않아도 될 것 같습니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/controller/RacingCarProgressService.java
> +public class RacingCarProgressService {
이 클래스도 InputService 에 남겨드린 리뷰사항과 동일합니다.

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/model/CarsProgress.java
> +public class CarsProgress {
domain 패키지와 model 패키지의 차이점은 무엇인가요?

2022-04-10 14:54 UTC, csh0034 commented on src/main/java/racingcar/exceptions/InputValueException.java
> +public class InputValueException extends RuntimeException {
throws 구문외엔 실제로 사용되고 있지 않네요 😢

2022-04-10 16:44 UTC, younlll commented on src/main/java/racingcar/view/InputView.java
> +public class InputView {
인스턴스 생성을 할 일이 없다는 것까지만 생각을 하고 default constructor로 인해서 생성이 될 가능성이 열려있다는 것까지 고려하지 못했습니다😥
리뷰 해주신 덕분에 이후 구현에 있어서도 고려할 수 있을 것 같습니다!!👍

2022-04-10 16:45 UTC, younlll commented on src/main/java/racingcar/view/OutputView.java
> +    public static String getDashOnDistanceByCars(int movementDistance) {
구현된 내용이 적절하게 사용한게 맞는지 고민하는 과정이 있었어야 하는데 IDE 기능으로 고민하지 않고 구현을 했었던 것 같습니다;;;;
~~자동차의 이동 거리를 Cars 클래스를 만들었고 cars.getDistanceTraveled()를 통해 거리를 받아오고 있습니다.
Wrapping을 했다고 생각했는데 제가 잘 못 이해하고 구현이 되어있는걸까요??~~
자동차의 이동 거리를 Car 클래스를 만들었고 car.getDistanceTraveled()를 통해 거리를 받아오고 있습니다.
Wrapping을 했다고 생각했는데 제가 잘 못 이해하고 구현이 되어있는걸까요??

2022-04-10 16:45 UTC, younlll commented on src/main/java/racingcar/model/CarsProgress.java
> +            cars.setDistanceTraveled(Constant.MOVEMENT_DISTANCE_INITIAL_VALUE);
처음 구현 시, 외부에서 값을 변경하지 못하도록 만들고 싶었는데 그럼 위치가 변경될 때마다 객체를 새로 생성해야하나?라는 생각때문에 setter와 getter를 생성하게 되었습니다!
지금 생각해보니 메서드를 통해 거리를 변경해주고 외부에서는 해당 메서드를 호출하면 되는거였네요😓

2022-04-10 16:45 UTC, younlll commented on src/main/java/racingcar/model/CarsProgress.java
> +            cars.setDistanceTraveled(cars.getDistanceTraveled() + 1);
이동거리의 변화를 주는 메서드를 구현한 뒤에 메서드를 호출하는 방식으로 변경하였습니다!!

2022-04-10 16:45 UTC, younlll commented on src/main/java/racingcar/commons/Constant.java
> +public class Constant {
클래스를 최대한 분리해봐야지 라고 생각하다보니 고려하지 못했었던 것 같습니다ㅠㅠ
필요에 맞게 각 클래스로 변경하였습니다!

2022-04-10 16:45 UTC, younlll commented on src/main/java/racingcar/domain/Cars.java
> +    public void setDistanceTraveled(int distanceTraveled) {
앗! 위에 리뷰를 보고 고민해서 수정한 내용이 여기 리뷰로 있었었네요ㅎㅎㅎㅎ

2022-04-10 16:51 UTC, younlll commented on src/main/java/racingcar/controller/InputService.java
> +    private String validationInputValue(String inputValue) throws InputValueException {
어랏... 저도 당황스럽네요;;

2022-04-10 16:54 UTC, younlll commented on src/main/java/racingcar/controller/InputService.java
> +public class InputService {
구현하면서 controller에 대한 역할이 아니라고 생각을 했습니다!
입력한 값에 대한 검증과 변환을 해주는 역할을 부여한거였는데 이 의도가 어떤 패키지로 들어가야 할지
정확히는 모르겠어서 controller에 넣어놓게 되었습니다;;

2022-04-10 16:59 UTC, younlll commented on src/main/java/racingcar/model/CarsProgress.java
> +public class CarsProgress {
CarProgress 클래스는 Car 객체의 값을 변경하는 역할을 주고 싶어서 만들게 되었습니다
그래서 model 패키지를 만들게 되었었는데
구현하다보니 저는 CarsProgress 클래스와 RacingCarProgressService 클래스의 역할이 같다라고 보여지게 되어서 고민이 되었었습니다.
RacingCarProgressService 클래스에 구현한 내용을 CarsProgress 클래스에 구현한 뒤에 RacingGame 클래스에서 CarsProgress의 메서드들을 호출하여 동작하는게 맞지 않을까.. 하는 고민이 있었습니다

2022-04-10 17:03 UTC, younlll commented on src/main/java/racingcar/controller/InputService.java
> +        if (!inputValue.matches(Constant.NUMERIC_REGEX)) {
사용자가 숫자 이외의 값이나 음수를 넣을 수 있다는 생각으로 예외처리를 추가하게 되었습니다.
근데 리뷰어님 말씀대로 사실상 int로 선언한 뒤에 잘 못된 값을 입력하여 오류가 발생하는 것과
커스텀 예외 메시지를 보여주는 것이 같다라는 생각이 드네요.

올바른 입력 값이 아닌 경우를 체크해야 한다면 체크한 뒤에 올바른 입력값을 다시 받도록 유도하게 된다면
이런 경우에는 검증이 필요하다는 생각이 듭니다
(이 부분은 자동차 경주의 기능 요구사항은 아닌 거겠죠?)

2022-04-10 17:06 UTC, younlll commented on src/main/java/racingcar/view/InputView.java
> +        return scanner.nextLine();
입력 값을 체크하지 않아도 된다는 리뷰에 nextLine()을 선언하게 된 이유를 적어두었습니다!
감사합니다 :)

2022-04-10 17:07 UTC, younlll commented on src/main/java/racingcar/exceptions/InputValueException.java
> +public class InputValueException extends RuntimeException {
예외처리가 의미가 없어지면서 커스텀 예외 클래스의 필요성이 없어졌네요.

2022-04-10 17:20 UTC, younlll commented
리뷰에 대한 답글로도 궁금한 내용을 남겨 놓기는 했습니다.
CarsProgress와 RacingCarProgressService 두 클래스의 역할이 같다는 생각이 듭니다.
RacingCarProgressService의 동작을 CarsProgress로 합친 뒤에 RacingCarProgressService 클래스를 삭제하는 것이 맞다는 생각이 드는데
조언 부탁드립니다

2022-04-10 17:23 UTC, younlll commented
리뷰를 읽고 리팩토링을 하면서 다시 생각해보니까 Car 클래스는 이동 거리에 대한 변경을 주고 이동 거리 값을 반환해주는 역할을 하고 있으니 model 패키지로 옮기는게 맞다는 생각을 했습니다.
이 부분에 대해서도 조언 부탁드립니다!

2022-04-10 17:29 UTC, younlll commented
지난번 라이브 코딩을 보면 테스트 코드 작성 시에
* 테스트 코드
```java
@Test
void test() {
    C.c();
    assertThat() ~
}
```

이런 식으로 작성한 뒤에 오류가 발생 했고 C 클래스를 IDE 기능을 통해 main 패키지 내에 클래스를 생성하고
이어서 c 메서드도 똑같이 생성을 하고 기능 구현을 했습니다.
라이브 코딩 시에 구현된 메서드들이 이렇게 생성하는 과정에서 static으로 만들어지게 되었습니다.

static은 불변의 특징으로 로드 시에 메모리에 올라가고 종료될 때까지 유지된다고 알고 있습니다.
모든 것을 static으로 생성하게 된다면 메모리 측면에서 문제가 될 수도 있지 않을까? 라는 생각을 하게 되었는데요.

이 고민이 제가 아직 어떤 기준으로 static을 선언 해줘야하는지 명확하지 않아 생겼다고 생각됩니다.

이 부분에 대해서 조언이나 혹시 참고할만한 글 또는 책의 내용이 있을지 질문 남깁니다.

2022-04-11 13:49 UTC, csh0034 requested changes
피드백 잘 반영해주셨네요 👍

추가로 피드백 드린 내용 반영하여
다시 리뷰 요청 부탁드립니다 😃

2022-04-12 14:09 UTC, younlll commented
어제 대화하면서는 많이 이해가 된거같았는데.... 다시 생각하면서 해보려니 어렵네욬ㅋㅋㅋㅋㅋㅋ😭

2022-04-13 10:08 UTC, csh0034 requested changes
피드백 잘 반영해주셨네요 👍

구조도 잘 잡혀 있어서 조금만 힘내주시면
될 것 같습니다!

코멘트 확인 해주시고 다시 리뷰 요청 부탁 드려요. 😃

2022-04-13 15:33 UTC, younlll commented on src/main/java/racingcar/controller/RacingGame.java
> +        PositionControl positionControl = new PositionControl();
이것저것 고려하면서 작성해보고 수정하고 반복하다보니
해당 메서드에서 사용을 안하니까 삭제해야 한다는걸 놓친 것 같습니다😓

2022-04-15 13:20 UTC, younlll commented on src/test/java/racingcar/model/CarTest.java
> +    void checkPositionMovedCar() {
전략패턴 적용을 해보려 했는데... 완전한 이해가 안간건지 어렵네요ㅠㅠㅠㅠ
인터페이스 분리를 해서 이동 여부를 구현체로 만들어보긴 했는데 이게 전략패턴인지를 모르겠습니다😥

2022-04-15 13:28 UTC, younlll commented on src/main/java/racingcar/controller/RacingGame.java
> +    private Cars cars;
Cars라는 객체를 생성할때마다 새로운 변수로 만들어져야 한다고 생각해서 인스턴스 변수로 구현을 해놓았습니다!

레이싱 게임에서 생성될 일이 1회밖에 없어서 클래스 변수로 변경을 했습니다

2022-04-15 13:29 UTC, younlll commented on src/main/java/racingcar/model/PositionControl.java
> +public class PositionControl {
값에 따라 움직임의 여부를 결정하는 기능을 제공한다고 생각해서 model에 두게 되었는데.. 잘못 생각한 걸까요ㅠㅠ

2022-04-15 13:34 UTC, younlll commented
인터페이스로 분리하고 인터페이스를 상속 받아 구현체를 통해서 움직임 여부를 판단하도록 변경하였습니다
일단 이렇게 구현한 부분이 전략패턴인지는 제가 아직 정확하게 모르겠습니다😥

그리고 Car클래스에서 PositionControl을 적용하는데 만약 이용하는 전략을 변경하게 되면 Car클래스를 수정하게 되는데
이것도 결국 의존을 하고 있는게 아닌가라는 생각이 듭니다

2022-04-15 15:02 UTC, csh0034 approved these changes
안녕하세요. 유나님.

피드백 반영 잘해주셨습니다 💯
  
다음단계 진행해주시면 됩니다 👍

2022-04-15 15:03 UTC, merged