Step3
next-step/java-racingcar pull request #3199
Opened 2022-04-10 14:02 UTC by pable91

안녕하세요.

자동차 경주 - 3단계 미션 PR 보냅니다.

감사합니다.

2022-04-11 07:05 UTC, vagabond95 requested changes
전반적으로 크게 피드백 드릴 부분이 없을 만큼 잘 구현해주셨습니다 👍 

의존성을 분리하는 부분에서 리펙토링해보면 좋을 부분에 대해서 간략한 코멘트 남겼는데요.
확인 후 다시 리뷰요청 부탁드립니다!

2022-04-11 07:05 UTC, vagabond95 commented on src/main/java/racingCar/Car.java
> +        if (value >= BOUNDARY) {
Car boundary 값에 대한 요구사항이 바뀌면, 
테스트 코드도 모두 변경될 것 같은데요!

Boundary 에 대한 의존성을 제거하고, 테스트할 수 있도록 리펙토링해보는 것은 어떨까요?
의존성이 제거되면 어떤 이점이 있을까요?

hint : [전략패턴](https://victorydntmd.tistory.com/292)

2022-04-11 13:42 UTC, pable91 commented on src/main/java/racingCar/Car.java
> +        if (value >= BOUNDARY) {
피드백 감사합니다.
전략패턴을 사용해서 수정해봤습니다.

1. 주신 hint에서는 전략패턴을 생성하고 다형성을 통해 Bus,Car에서 각각 전략을 선택하는데요. 
현재 저희 프로젝트에서는 이동수단의 추가가 이루어지지 않는다고 판단해서 Car객체가 직접 전략을 가지고 있는 방향으로 수정하였습니다. 

2. Car객체는 생성자에서 전략패턴을 매개변수로 받아서 초기화해주고 있습니다. 강의에서도 set,get을 웬만하면 피하라고 하셨고, 제 생각에도 굳이 set함수를 추가해서 프로덕션 코드나 테스트 코드에 수정이 더해져야하나 싶습니다. 

3. Car클래스 안에서 전략을 멤버변수로 가지고 있습니다. 해당 변수는 생성자에서 초기화가 이루어지기때문에 final을 써주는게 맞다고 판단하였습니다.  

제가 생각한 위 3가지 부분에 대해서 리뷰어 분의 피드백이 있다면 피드백 주세요. 

고생많으십니다 :)
감사합니다.

2022-04-12 02:35 UTC, pable91 commented on src/main/java/racingCar/RacingCarGame.java
> +    }
여기서 InputViewRacingCar, ResultViewRacingCar 클래스는 상태를 갖지않는 객체입니다.
private 생성자를 추가해서 객체를 생성하지 못하게 하고, 메소드들을 static으로 바꾸는건 어떤가요?????? 피드백 부탁드립니다.

2022-04-12 08:04 UTC, vagabond95 commented on src/main/java/racingCar/RacingCarGame.java
> +    }
클래스의 목적상 Utils 성 클래스 처럼 계속 상태를 가지지 않는 것이 확실시 된다면 얘기주신 것 처럼 static 으로 제공하는 것이 좀 더 의도에 맞을 것 같습니다!

2022-04-12 08:06 UTC, merged