Step3
next-step/java-racingcar pull request #3200
Opened 2022-04-10 14:05 UTC by rumor1993

안녕하세요! 오늘도 리뷰 잘 부탁드립니다!

질문 
 1. Car 클래스에 randomNuber()의 경우는 private 함수로 정의하고 싶었으나 
    이런 경우 유닛 테스트가 불가한 부분이 있어서 전체적인 방향을 public 함수로 구현하였는데
    private의 경우 어떤식으로 테스트 하는지 궁금합니다!
    
    public int randomNumber() {
        Random random = new Random();
        return random.nextInt(10);
    }
    
 2. InputView, ResultView 
  두 클래스는 제가 처음 작성해보는 부분이라서 궁금한 부분이 있어서 질문 드립니다
  InputView의 경우 저렇게 함수를 정의해서 하는 방식을 선호하는건지 아니면 다른 방식을 많이 사용하는지 
  알고 싶습니다

 ResultView의 경우는 해당 클래스를 Car클래스 안에 포함하여 출력하도록 하는 방법과
 ResultView를 선언하고 그 결과를 받아서 출력 하는 방법 중 어느 부분을 더 선호하는지 궁금합니다!

감사합니다!

2022-04-10 14:11 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
질문에 대한 답변은 인라인 코멘트로 함께 남겼습니다. 이외에도 생각해 보실 부분이 조금 있는 것 같군요.

살펴보시고 의견 혹은 수정 부탁드립니다. 👍

2022-04-10 14:11 UTC, wheejuni commented on src/main/java/car/Car.java
> +    private String distance;
거리를 문자열로 보관하는 것...좋은 방법이 아닌 것 같기는 합니다~

2022-04-10 14:11 UTC, wheejuni commented on src/main/java/car/Car.java
> +        if (number < 4) {
나중에 규칙이 바뀌면 어떤 변경이 일어나야 할지, 이런 수준의 변경을 의도하고 예상하고 계신지 궁금합니다.

2022-04-10 14:11 UTC, wheejuni commented on src/main/java/car/Car.java
> +    }
어떠한 경우에도 테스트 그 자체를 위해 메서드의 공개 수준, 심지어 로직 등이 바뀌면 안됩니다.
테스트 대상은 가만히 있고 테스트를 유연하게 작성해서 문제를 해결해 나가야 합니다. 무엇보다 테스트하기 좋은 구조를 생각하며 코딩해야겠고요.
테스트하기 좋은 코드 !== 테스트를 위해 수정된 코드 입니다. 

질문해주신 말씀을 생각해보면... `private` 메소드를 왜 테스트 해야 하나요? 전 그 필요성부터 좀 의심해보고 싶습니다.
모든 퍼블릭 메소드에 대한 테스트 케이스가 성공한다면 `private` 메소드는 자연스레 검증된 것 아닐까요? 
만약 그렇지 않다면 제대로 설계하고 작성한 프라이빗 메서드인지부터 의심해봐야 할 것입니다.

2022-04-10 14:11 UTC, wheejuni commented on src/main/java/car/CarRacing.java
> +    private ArrayList<Car> cars = new ArrayList<Car>();
`List` 타입으로 받는 것이 좋습니다. 그 이유에 대해서도 한번 생각해 보시면 좋겠네요.

2022-04-10 14:11 UTC, wheejuni commented on src/main/java/car/InputView.java
> +public class InputView {
`View` 성격의 클래스는 사실 우리가 지금 프로젝트 환경상 어쩔 수 없이 콘솔 기반 앱을 만들면서 생겨난 문제인 측면이 큽니다.
여기에서의 로직 구현이나 코딩 스타일은 사실 필요한 만큼, 편하신 만큼 진행해주시면 된다고 생각합니다.

2022-04-10 14:11 UTC, wheejuni commented on src/test/java/car/RacingTest.java
> +}
불펼요한 주석은 그때그때 지워주시면 좋겠습니다!

2022-04-10 15:35 UTC, rumor1993 commented on src/main/java/car/InputView.java
> +public class InputView {
넵! 감사합니다

2022-04-10 22:33 UTC, wheejuni approved these changes

2022-04-10 22:33 UTC, merged

2022-04-11 02:52 UTC, rumor1993 commented
안녕하세요!피드백건 수정하면서 질문사항은 커밋메시지가 아니라 코멘트에 추가하면 될까요?