Step2
next-step/java-racingcar pull request #3206
Opened 2022-04-11 10:14 UTC by Wu22e

2단계 문자열 덧셈 계산기 PR 드립니다!

1차 강의를 들으며 최대한 한 메서드에 한가지 일을 하도록 분리해 보았습니다.
SplitStringNumber클래스를 분리하면서 Pattern 인스턴스를 한번만 생성하여 사용할 수 있도록 하였습니다.
PositiveNumber 클래스를 분리하면서 convertPositiveNumberList 메서드의 위치를 어디에 둬야할지 애매하여
StringAddCalculator 클래스에 두었습니다.

미션2 리뷰 잘 부탁드립니다!

2022-04-12 07:55 UTC, vagabond95 requested changes
2단계도 요구사항에 맞게 잘 구현해주셨네요!

각 클래스별로 적절하게 역할이 잘 분리된 것 같습니다. 👍 

구현해주신 내용을 바탕으로 몇가지 코멘트 남겼는데요 ㅎㅎ 확인 후 다시 리뷰요청 부탁드립니다!

2022-04-12 07:55 UTC, vagabond95 commented on src/main/java/calculator/SplitStringNumber.java
> +    private static final String DEFAULT_DELIMITER = ",|:";
상수로 분리 👍

2022-04-12 07:55 UTC, vagabond95 commented on src/main/java/calculator/SplitStringNumber.java
> +    public static List<String> splitToStringValueList(String text) {
메소드에 리턴 타입을 적게 되면, 추후에 리턴타입이 변경되었을 때 메소드 이름도 같이 변경이 필요하므로 저는 최대한 지양하는 편입니다 :)

2022-04-12 07:55 UTC, vagabond95 commented on src/main/java/calculator/StringAddCalculator.java
> +    private static List<PositiveNumber> convertToPositiveNumberList(List<String> stringValueList) {
위 코멘트와 같은 맥락으로 파라미터 네이밍도 구체적인 타입을 명시하게 되면 변경에 취약할 것 같아요!

2022-04-12 07:55 UTC, vagabond95 commented on src/main/java/calculator/StringAddCalculator.java
> +    private static List<PositiveNumber> convertToPositiveNumberList(List<String> stringValueList) {
convertToPositiveNumberList 메소드가 해당 클래스의 위치하는 것은 괜찮아 보입니다 ㅎㅎ

2022-04-12 07:55 UTC, vagabond95 commented on src/main/java/calculator/PositiveNumber.java
> +public class PositiveNumber {
해당 클래스에 대한 테스트도 필요하지 않을까요~?

ex) 숫자로 바꿀 수 없는 문자열이 들어왔을 때의 예외상황

2022-04-12 15:17 UTC, Wu22e commented
메서드 네이밍에 리턴타입이 없도록 convert 뒷부분의 이름을 제거하였는데,
예를들어 추가적인 로직을 구현하다가 다른 타입으로 변경하는 비슷한 내용의 메서드가 계속해서 생겨날 경우 (ex : List<객체1> convert(List<객체2>) 메서드의 네이밍은 동일하게 가져가고 메서드 시그니쳐로 구분하게 되는 걸까요?

또 테스트 코드를 작성할떄 구체적인 테스트 데이터를 집어넣게되는데, 어느정도의 경우의 수를 가져가는게 좋다고 생각하시나요? (테스트 커버리지를 최대한으로 높일 수 있는 최소한의 경우의 수를 찾기위해 노력해야 하는걸까요?)

2022-04-13 13:42 UTC, vagabond95 commented
1. 저는 메소드에 객체의 복수명을 적는 편입니다! 예를들어 자동차라면 convertCars(...) 정도로요 ㅎㅎ 복수이지만 자료형은 나타내지 않으므로 내부에서 set 이나 map 으로 타입이 바뀌어도 네이밍에는 변경이 생기지 않게됩니다!

2. 테스트마다 다르겠지만 저는 바운더리 테스트라고 해서 실패지점의 끝값들과 정상적인 데이터를 넣는 것을 선호하는 편입니다! 가령 음수를 넣으면 안될 경우 음수 하나, 0, 양수 하나 정도로요 :) 핵심은 서로 다른 영역/범위의 수만 하나씩 테스트하는 경우의수면 커버리지가 어느정도 확보되지 않을까 싶어요~!

2022-04-13 13:42 UTC, vagabond95 approved these changes
피드백 의도에 맞게 잘 반영해주셔서 이번단계도 머지하도록 하겠습니다~!

질문주신 내용은 하위 코멘트에 남겼으니 다음단계 진행시 참고해주세요 :)

2022-04-13 13:43 UTC, merged