Step3
next-step/java-racingcar pull request #3212
Opened 2022-04-11 14:39 UTC by haemanlee

step3 진행했습니다.
충돌나서 브랜치 이름이 step3_fixed인것 양해부탁드립니다.

2022-04-11 15:16 UTC, bingbingpa requested changes
3단계도 빠르게 진행해주셨네요! 
몇 가지 생각할 만한 것들을  남겨드렸는데 
한번 확인해보시고 다시 한번 리뷰 요청 부탁드려요. 
궁금하신 사항이나 의견을 나누고 싶으면 언제든 편하게 의견 남겨주시거나 DM 주세요! 🙇

2022-04-11 15:16 UTC, bingbingpa commented on src/main/java/racingcar/Controller.java
> +        System.out.println("자동차 대수는 몇 대 인가요?");
입력 받는 부분과 출력하는 부분을 각각 InputView, ResultView 로 적절하게 옮겨보는건 어떨까요?

2022-04-11 15:16 UTC, bingbingpa commented on src/main/java/racingcar/Car.java
> +    }
이 메소드는 테스트에서만 사용되고 있어요.
그리고 동일한 본문을 가진 movable() 함수가 있는데요.
이 부분을 어떻게 개선하면 좋을지 고민해 보는게 좋을거 같아요. 
랜덤이라는 영역을 내부에서 처리하려고 하지 말고 별도로 분리해서 입력 받는다면 
조금 더 테스트 하기 쉬워지지 않을까요?

2022-04-11 15:16 UTC, bingbingpa commented on src/main/java/racingcar/Car.java
> +        Random random = new Random();
Car 클래스는 지금 랜덤한 수를 생성하고 거리를 이동하는 등 여러가지 책임을 가지고 있어요. 
랜덤한 수를 생성하는 부분이 Car 클래스의 역할인지 고민해보고 분리해 보는건 어떨까요?

2022-04-11 15:16 UTC, bingbingpa commented on src/main/java/racingcar/Controller.java
> +
불필요한 공백은 제거해주는게 좋을거 같아요.

2022-04-12 08:58 UTC, haemanlee commented on src/main/java/charactercalculator/CharCalculator.java
> +    private Matcher m;
감사합니다. 누락했습니다. 이번에 수정해서 반영하겠습니다.

2022-04-12 08:58 UTC, haemanlee commented on src/main/java/charactercalculator/CharCalculator.java
> +            m = Pattern.compile("//(.)\n(.*)").matcher(this.text);
감사합니다. 누락했습니다. 이번에 수정해서 반영하겠습니다.

2022-04-12 08:58 UTC, haemanlee commented on src/main/java/charactercalculator/CharCalculator.java
> +        String customSeparator = ",|:";
감사합니다. 누락했습니다. 이번에 수정해서 반영하겠습니다.

2022-04-12 08:59 UTC, haemanlee commented on src/main/java/racingcar/Car.java
> +    private final static int FORWARD_NUM = 4;
반영하였습니다. 감사합니다.

2022-04-12 11:29 UTC, haemanlee commented on src/main/java/racingcar/Cars.java
> +        return cars;
Cars cars = new Cars(carCount);
        cars.getCars().add(new Car());

이런 이슈가 있을 수 있어서 그런거 맞나요? 일단 리뷰해주신 부분 적용했습니다.

2022-04-12 11:31 UTC, haemanlee commented on src/main/java/racingcar/InputView.java
> +    public static Scanner scanner = new Scanner(System.in);
적용했습니다.

2022-04-12 11:56 UTC, haemanlee commented on src/main/java/racingcar/InputView.java
> +public class InputView {
네 명시적으로 private 생성자 추가하여 처리했습니다. 감사합니다.

2022-04-12 11:57 UTC, haemanlee commented on src/test/java/racingcar/CarTest.java
> +    @DisplayName("전진 조건 테스트")
감사합니다.

2022-04-12 11:57 UTC, haemanlee commented on src/main/java/racingcar/Controller.java
> +
제거했습니다. 감사합니다.

2022-04-12 12:02 UTC, haemanlee commented on src/main/java/racingcar/Controller.java
> +        System.out.println("자동차 대수는 몇 대 인가요?");
적용했습니다. 감사합니다.

2022-04-12 12:19 UTC, haemanlee commented on src/main/java/racingcar/Controller.java
> +        while ( startCount != playCount) {
네 GameService 라는 비지니스 클래스 생성해서 리펙토링 했습니다!

2022-04-12 12:44 UTC, bingbingpa commented on src/main/java/racingcar/Cars.java
> +        return cars;
네 맞습니다! 객체는 최대한 불변으로 유지해야 
나중에 유지보수나 디버깅하기 좋다고 생각해요. 
좀 더 자세한 내용 참고하시라고 링크 하나 남겨드릴게요.
[링크](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)

2022-04-12 16:26 UTC, haemanlee commented on src/main/java/racingcar/Car.java
> +        Random random = new Random();
random에 의한 이동은 따로 인터페이스와 클래스를 생성하였습니다. 감사합니다.

2022-04-12 16:33 UTC, haemanlee commented on src/main/java/racingcar/Car.java
> +        StringBuilder sb = new StringBuilder();
new Random() 과 StringBuilder private final 변수 처리하였습니다. 감사합니다.

2022-04-12 22:51 UTC, bingbingpa approved these changes
피드백 반영 잘해주셨네요! 💯
소소한 피드백 남겨드렸는데 그건 다음 미션 진행하시면서 반영해보면 좋을거 같습니다. 
그리고 다음 미션을 하면서는 패키지를 각각의 역할에 맞게
분리해보면 조금 더 깔끔할거 같아요. 
그럼 이번 단계는 머지하도록 하겠습니다. 
다음 미션도 화이팅 입니다! 🔥

2022-04-12 22:51 UTC, merged