Step4 리뷰요청 드립니다.
next-step/java-racingcar pull request #3236
Opened 2022-04-13 16:57 UTC by itdar

안녕하세요 휘준님!~
4단계 리뷰 요청 드립니다.
테스트케이스와 함께 기능 추가 및 수정 자체는 어렵지 않았으나.. 
연속적인 상황에서 클라이언트가 예외상황이 발생하게 (이름 길이 초과 5) 하는 경우 꺼버릴지 재시도하게 할지가 좀 고민되었네요.
우선은 재시도를 하게 하려면 검증로직의 위치가 도메인 레이어 밖으로 나오거나, 도메인 객체가 해당 레이어 밖으로 나오게 되는 것 같아서
예외발생 시 꺼버리게 해두었습니다. 어떻게 생각하실지 궁금합니다 ㅎㅎ

2022-04-14 13:44 UTC, wheejuni commented
@itdar 리뷰가 조금 늦어지고 있는데 조금만 더 기다려 주세요. 감사합니다. ㅠ

2022-04-14 14:37 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
몇 가지 개선 의견 드립니다. 반영 부탁드려요.

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/RacingCarMainApp.java
> +            System.exit(e.hashCode());
`System.exit()` 에 파라메터로 넘어가는 코드가 어떤 의미인지 학습해 보실 것을 권해요~

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/RacingCarMainApp.java
> +        } catch (IllegalArgumentException e) {
제가 느끼기엔 `try..catch` 까지 `createGame()` 메서드에서 이뤄져야 하는게 아닐까 싶긴 합니다.

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/domain/Car.java
> +            throw new IllegalArgumentException("차 이름은 공백 불가.");
이보다 더 상황에 맞는 예외를 설계해 보심이 어떠한지요?
그리고 가급적이면 `RuntimeException` 의 서브클래스 였으면 좋겠네요.

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/domain/RacingGame.java
> +            cars.add(new Car(carName));
호오 이거 stream.map 으로 안될까요??

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/domain/RacingHistories.java
> +    List<RacingHistory> histories = new LinkedList<>();
아래 펼쳐진 로직을 보니... 이 리스트도 별도의 컬렉션 객체로 관리되어야 할 것 같은 느낌은 듭니다?
컬렉션 객체에서 할 일이 좀 있는 것 같은데

- 1등 주자의 히스토리 리턴해주기
- 순위별 소팅하기

등을 해야할 것 같네요.

2022-04-14 14:37 UTC, wheejuni commented on src/main/java/step3/domain/RacingHistories.java
> +        List<String> firstRankNames = histories.get(histories.size() - 1).getFirstRankNames();
스트림 API의 종단 연산 메소드 중에 `Collectors.joining()` 이라는 게 있습니다.
아래 포문으로 도는 로직은 이걸로 좀 개선이 될 것 같은데 일단 시도를 해보시는 게 좋겠습니다.

2022-04-14 15:27 UTC, itdar commented on src/main/java/step3/domain/Car.java
> +            throw new IllegalArgumentException("차 이름은 공백 불가.");
길이만 예외로 두기가 허전해서 만들긴 했는데 이름이 공백일 경우는 없을라나요..ㅋㅋ
차 이름은 알파벳과 숫자로만 이루어지도록 조건을 바꾸었습니다!~
그리고 IllegalArgumentException 은 RuntimeException 상속해서 unchecked 는 맞는데요
명시적으로 외부로 throws 한 것은 예외 발생 시 클라이언트(main) 에서 확인 할 수 있게 하려고 잡아보았습니다!!

2022-04-14 15:31 UTC, itdar commented on src/main/java/step3/domain/RacingHistories.java
> +        List<String> firstRankNames = histories.get(histories.size() - 1).getFirstRankNames();
옙 시도해보겠습니다~!

2022-04-14 15:41 UTC, itdar commented on src/main/java/step3/RacingCarMainApp.java
> +        } catch (IllegalArgumentException e) {
음.. 그런거 같네요 아니면 RacingGame 내부에 아예 넣어버려도 괜찮을 것 같은데 도메인에 exit 을 넣는건 아닌 것 같고..
서비스에 옮겨보았습니다! ㅎㅎ

2022-04-14 15:45 UTC, itdar commented on src/main/java/step3/domain/RacingHistories.java
> +    List<RacingHistory> histories = new LinkedList<>();
엇 이 RacingHistories 가 RacingHistories 의 일급콜렉션을 생각하고 만든건 맞습니다!
말씀해주신 것 처럼 1등주자 히스토리 리턴이나 소팅해서 히스토리 객체를 내보낼까 했었는데..
클라이언트(main) 까지 RacingHistory 도메인 객체를 내보내서 다시 또 print 하기위해 로직이 들어가게 될 것 같아서
아예 최종 History 와 1등 주자들의 이름들을 곧바로 print 할 수 있는 String 으로 내보내게 만들어보았습니다!!

2022-04-15 00:02 UTC, wheejuni commented on src/main/java/step3/domain/RacingHistories.java
> +        List<String> firstRankNames = histories.get(histories.size() - 1).getFirstRankNames();
그저 끊임없는 시도만이 정답인 거 같습니다 ㅋㅋ

2022-04-15 00:02 UTC, wheejuni approved these changes
굳 수고하셨습니다 👍

2022-04-15 00:03 UTC, merged