Step3
next-step/java-racingcar pull request #3253
Opened 2022-04-14 15:56 UTC by sjhello

안녕하세요 리뷰어님!!

제 나름대로 기능요구사항을 객체의 책임과 역할로서 정리해보았는데 부족한 부분 피드백 부탁드립니다!

추가적으로... 저는 이번 미션을 진행하면서 일단 테스트 코드를 먼저 짠게 아닌, 메인 로직부분을 먼저 작성하고 작성한 코드의 main() 메소드를 실행하면서 기능이 돌아가는지를 우선으로 하면서 메인 로직을 작성하였는데요

테스트 코드를 작성하면서 느낀건데 제가 작성한 코드가 테스트 하기가 쉽지않은 코드라는것을 기능을 다 작성하고 깨달았습니다....

Car 객체의 Test코드를 작성하면서 "자동차 객체가 생성한 랜덤 값이 4이상 이면 자동차는 전진한다"는 테스트 코드를 작성하는 부분에서 막혔는데요..

```java
package racingcar;

import java.util.Random;

public class Car {
	public static final int LIMIT_RANDOM_NUMBER = 10;
	public static final int MOVE_CONDITION = 4;
	public static final String movingUnit = "-";
	private String status = "";
	private int valueToMovable;

	private void randomNumber() {
		Random random = new Random();
		int number = random.nextInt(LIMIT_RANDOM_NUMBER);
		this.valueToMovable = number;
	}

	public void move() {
		if (isMovable()) {
			status += movingUnit;
		}

		status += "";
	}

	public boolean isMovable() {
		randomNumber();

		if (this.valueToMovable >= MOVE_CONDITION) {
			return true;
		}

		return false;
	}

	public String carStatus() {
		return status;
	}

	public int getValueToMovable() {
		return valueToMovable;
	}
}
```

우선.. move()가 실행되면서 isMovable() 메서드에서 randomNumber()를 호출하는데요 
값이 랜덤으로 생성되어 테스트할때마다 테스트의 성공유무가 달라지는것을 알게되었습니다.

결론은 Car 객체의 "자동차 객체가 생성한 랜덤 값이 4이상 이면 자동차는 전진한다"는 테스트를 실행하면서 매번 바뀌는 랜덤값을 일정한 값으로 테스트 하기를 원하는데 방법이 있을까요?

2022-04-15 00:54 UTC, ghojeong requested changes
김상진 님!
질문에서 핵심을 잘 짚어내셔서 깜짝 놀랬습니다. 👍 

> 테스트 코드를 작성하면서 느낀건데 제가 작성한 코드가 테스트 하기가 쉽지않은 코드라는것을 기능을 다 작성하고 깨달았습니다....

처음 TDD 에 도전하면 누구나 마찬가지인것 같습니다.

참고로 테스트가 어려운 코드는, 동료 개발자가 재사용하기에도 어려운 코드라고 생각하셔도 좋을 것 같습니다.
동료들이 내 코드를 쉽게 사용할수 있을까? 했을 때
본인이 테스트하기 어려운 코드라면, 동료분들 또한 협업하기 어려워하시더라고요.

많지는 않지만, 굉장히 많은 부분이 달라지게 될 피드백을 남겼습니다.
화이팅입니다!

2022-04-15 00:54 UTC, ghojeong commented on README.md
> +# 객체 설명
제가 리뷰하고 있는 분들 중에서 제일 자세하게 요구사항을 정리해주셨군요. 👍 
매우 훌륭합니다.
동료 개발자였으면 커피라도 한잔 샀을 정도네요.
앞으로도 README 를 잘 정리하는 습관을 가지시면 좋을 것 같습니다.

2022-04-15 00:54 UTC, ghojeong commented on src/main/java/racingcar/Car.java
> +	public static final String movingUnit = "-";
```suggestion
	public static final String MOVING_UNIT = "-";
```

String 상수 또한, Int 상수 처럼 네이밍해주시면 좋을 것 같습니다.

2022-04-15 00:54 UTC, ghojeong commented on src/main/java/racingcar/Car.java
> +	}
> Car 객체의 "자동차 객체가 생성한 랜덤 값이 4이상 이면 자동차는 전진한다"는 테스트를 실행하면서 매번 바뀌는 랜덤값을 일정한 값으로 테스트 하기를 원하는데 방법이 있을까요?

매우 적절한 질문을 해주셨군요.
사실 자동차 미션에서 학습을 요구하는 가장 핵심을 질문 주셨네요.
멋집니다. 👍 

결국 테스트를 어렵게하는 것은 "랜덤" 숫자라고 할 수 있습니다.
랜덤 숫자는 사용자가 입력한 숫자처럼 개발자가 통제 혹은 예측하기 불가능하기 떄문입니다.

그에 대한 해결책으로 랜덤과 관련된 영역을, 도메인과 분리하기를 제안드립니다.
마치 사용자 입력을 InputView 라고 하는 ui 로 분리를 한 것처럼, 랜덤을 담당한 부분을 테스트가 필요없는 영역으로 분리해주세요.
랜덤 숫자를 도메인 외부에서 생성하고, 도메인에게 생성된 숫자를 "주입" 해주시기를 바랍니다.

"분리" 와 "주입"을 하는 데에는 여러가지 방법들이 있지만,
저는 개인적으로 [**전략 패턴**](https://ko.wikipedia.org/wiki/%EC%A0%84%EB%9E%B5_%ED%8C%A8%ED%84%B4)을 사용해보시기를 추천드립니다.

"숫자" 를 생성하는 전략을 도메인에게 주입할 수 있도록 만들고,
자동차 게임을 실행할 때에는 랜덤한 전략을,
테스트를 실행할 때에는 하드코딩된 시나리오로 동작하는 전략을 주입해서,
테스트 결과를 예측 가능하도록 리팩토링하셨으면 합니다.

2022-04-15 00:54 UTC, ghojeong commented on src/main/java/racingcar/ui/ResultView.java
> +		List<Car> cars = carStadium.getCars();
가능하시면 리팩토링을 진행하면서 `List<Car>` 를 Cars 라는 일급 컬렉션으로 만들어보시면 좋겠습니다.
앞으로 미션을 진행하면서 저 뿐만 아니라, 다른 리뷰어분들도 공통적으로 일급 컬렉션을 제안할 거라서요.
자동차 게임에서 한번 경험해보셨으면 합니다.

2022-04-15 00:54 UTC, ghojeong commented on src/test/java/racingcar/CarTest.java
> +	void movableTest(int number) {
```suggestion
	@DisplayName("자동차 객체가 전달받은 숫자가 4이상 이면 자동차는 전진한다")
	void movableTest(int number) {
```

랜덤이 아니라 하드코딩된 시나리오를 기반으로 테스트를 해보셨으면 합니다.

2022-04-17 09:37 UTC, ghojeong approved these changes
김상진 님 피드백 반영 잘해주셨습니다. 👍 
다음 Step 진행하시죠!
다음 Step 에서 고려하면 좋을 추가적인 피드백들도 남겨보았습니다.

2022-04-17 09:37 UTC, ghojeong commented on src/main/java/racingcar/util/generator/NumberGenerator.java
> +}
제가 의도한 부분을 매우 훌륭하게 반영해주셨습니다!! 👍

2022-04-17 09:37 UTC, ghojeong commented on src/main/java/racingcar/util/strategy/move/MoveStrategy.java
> +}
전략을 따로 만들어주신 것 또한 매우 좋습니다! 👍

2022-04-17 09:37 UTC, ghojeong commented on src/main/java/racingcar/util/strategy/move/CarMoveStrategy.java
> +	}
MOVE_CONDITION 이 4라는 것은 비즈니스 로직이므로,
CarMoveStrategy 에 대해서도 테스트 코드를 작성해보면 어떨까 제안해봅니다.

2022-04-17 09:37 UTC, ghojeong commented on src/main/java/racingcar/util/generator/RandomNumberGenerator.java
> +}
앞으로도 테스트하기가 어려운 외부 요소를 만나시면 interface 를 적극적으로 반영해주세요. 👍

2022-04-17 09:37 UTC, ghojeong commented on src/test/java/racingcar/domain/CarTest.java
> +	void movableTrue(int number) {
훨씬 그럴듯한 테스트군요!
요구사항이 구현되었는지 확인하기 편합니다. 👍

2022-04-17 09:37 UTC, ghojeong commented on src/test/java/racingcar/domain/CarsTest.java
> +	void getCarsSize(int number) {
ValueSource 의 활용 좋습니다. 👍

2022-04-17 09:37 UTC, ghojeong commented on src/main/java/racingcar/domain/Car.java
> +	}
NumberGenerator 와 MoveStrategy 가 null 인 Car 도 존재할 수 있나요?
기본 생성자를 남겨두신 이유가 궁금합니다.

2022-04-17 09:37 UTC, merged

2022-04-18 14:13 UTC, sjhello commented on src/main/java/racingcar/util/strategy/move/CarMoveStrategy.java
> +	}
추가해서 commit 하겠습니다!