4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #3287
Opened 2022-04-17 16:36 UTC by wlroh

정완님 안녕하세요! 교육생 노웅래입니다~

4단계 미션인 자동차 경주(우승자) 완료했습니다!
리뷰 잘 부탁드립니다~!

아 그리고 진행하면서 궁금한 점이 있었는데 자동차 전진하는 부분을 피드백 주신대로 추상화를 사용하는 방법으로 리팩토링하여 그에 따라 조건에 따른 position값 테스트 코드 작성했습니다
 디폴트 전략패턴인 'RandomMoving' 의 경우 랜덤 숫자 관련해서 개발자가 로직상 통제가 불가능한 데이터여서 별도의 전략패턴을 주입해주기 위해 테스트 코드에 MovingStrategy의 구현체로 'alwaysGoMoving'과 'alwaysStopMoving' 를 만들어서 주입해서 테스트 코드를 만들었습니다
 그런데... 한 곳이 아닌 여러 Test 클래스(CarTest, HistoriesTest)에서 사용이되다보니 계속 구현체를 만들어주었는데... 괜찮을까요??

main쪽에 구현체를 추가해서 테스트코드에서 가져다 쓸 경우 한번만 추가해주면 되지만 프로덕션용이 아니고 테스트를 위한 용도여서 main쪽에 추가를 안하고 일일히 필요한 테스트 클래스마다 구현했습니다...

2022-04-18 02:33 UTC, ghojeong requested changes
노웅래님!
전략 패턴을 제 의도대로 매우 훌륭하게 구현해주셨습니다. 👍 
마지막 Step 으로 넘어가기 전에, 커스텀 예외를 활용해보는 경험을 하면 좋을 것 같아서,
피드백을 드렸습니다. 😄

2022-04-18 02:33 UTC, ghojeong commented on src/main/java/racingcar/domain/input/CarInfo.java
> +            throw new IllegalArgumentException(INVALID_CAR_NAME_MESSAGE);
```java
public class InvalidCarNameException extends IllegalArgumentException {
    private static final String MESSAGE = "최소 하나 이상의 이름을 입력해야합니다.";

    public InvalidCarNameException() {
        super(MESSAGE);
    }

    public InvalidCarNameException(String message) {
        super(message);
    }
}
```

커스텀 예외를 사용해보는 것은 어떨지 제안해봅니다.

2022-04-18 02:33 UTC, ghojeong commented on src/main/java/racingcar/domain/strategy/MovingStrategy.java
> +}
제 의도와 잘 부합하는 군요! 👍 
앞으로 Random 처럼 통제불가능한 영역을 분리할 때는,
지금처럼 interface 를 적극적으로 활용해주세요. 💯

2022-04-18 02:33 UTC, ghojeong commented on src/test/java/racingcar/domain/CarTest.java
> +    };
> MovingStrategy의 구현체로 'alwaysGoMoving'과 'alwaysStopMoving' 를 만들어서 주입해서 테스트 코드를 만들었습니다
그런데... 한 곳이 아닌 여러 Test 클래스(CarTest, HistoriesTest)에서 사용이되다보니 계속 구현체를 만들어주었는데... 괜찮을까요??

잘 만드셨습니다.
만약 alwaysGoMoving 과 alwaysStopMoving 을 재활용할 경우,
별도의 Fixture 로 선언해서 재활용하는 것은 어떨지 제안해봅니다.


```java
public class Fixture {
    private Fixture() {}

    public static final MovingStrategy alwaysGoMoving = () -> true;

    public static final MovingStrategy alwaysStopMoving = () -> false;
}
```

2022-04-18 02:33 UTC, ghojeong commented on src/test/java/racingcar/view/ResultBuilderTest.java
> +    @DisplayName("tom 자동차가 두번 전진하면 'tom : --'를 반환한다.")
동료 개발자들이 파악하기 쉬울 만큼, DisplayName 을 잘 작성해주셨군요 👍 
테스트가 매우 명확합니다.

2022-04-18 02:33 UTC, ghojeong commented on src/main/java/racingcar/view/ResultView.java
> +        System.out.println(winnerNames + "가 최종 우승했습니다.");
"가 최종 우승했습니다." 를 static final String 상수로 선언해주시면 좋을 것 같습니다.

2022-04-18 02:37 UTC, ghojeong commented on src/main/java/racingcar/domain/input/CarName.java
> +            throw new IllegalArgumentException(MAX_CAR_NAME_MESSAGE);
요것도 커스텀 예외로 만들어주세요.

2022-04-18 15:40 UTC, wlroh commented on src/main/java/racingcar/domain/strategy/MovingStrategy.java
> +}
넵넵 감사합니다~! 정말... 인터페이스... 추상화의 힘은 어마어마하지만 그만큼 어렵다고 느껴지네요...
앗 혹시 추상화관련해서 여러가지 패턴기법들이 있는데 패턴 기법들을 많이 모르고 있어서 추천해주실만한 패턴기법이 있거나
참고할 사이트 혹은 책들이 있을까요...??

아 한가지 더 들었던 생각이 패턴기법을 사용하기 전에 추상화에 더 익숙해지고 나서 패턴기법들을 공부하는 것이 좋을까요..?

2022-04-18 15:41 UTC, wlroh commented on src/test/java/racingcar/domain/CarTest.java
> +    };
아하~~ 감사합니다 피드백 적용해보겠습니다!

2022-04-18 15:41 UTC, wlroh commented on src/main/java/racingcar/view/ResultView.java
> +        System.out.println(winnerNames + "가 최종 우승했습니다.");
넵넵 이부분도 수정하겠습니다~

2022-04-18 15:47 UTC, wlroh commented on src/main/java/racingcar/domain/input/CarInfo.java
> +            throw new IllegalArgumentException(INVALID_CAR_NAME_MESSAGE);
이러한 장점들로 인해 가능하면 최대한 '커스텀예외'를 사용하는 것이 좋지 않을까 생각했습니다~

2022-04-18 15:49 UTC, wlroh commented
안녕하세요~ 피드백 주신부분 적용했습니다
우선 fixture 관련해서 재사용성을 위해 별도의 클래스로 만들었는데 프로덕션 코드가 아니라서 
test 쪽에 패키지를 만들어서 추가해주었는데 괜찮을까요..??

아! 그리고 진행하면서 궁금하거나 고민거리들도 같이 코멘트 달아보았습니다... ㅠㅠ

2022-04-19 02:10 UTC, ghojeong commented
> 우선 fixture 관련해서 재사용성을 위해 별도의 클래스로 만들었는데 프로덕션 코드가 아니라서 test 쪽에 패키지를 만들어서 추가해주었는데 괜찮을까요..??

 넵 제 의도와 일치합니다. ❤️

2022-04-19 02:16 UTC, ghojeong commented on src/main/java/racingcar/domain/input/CarInfo.java
> +            throw new IllegalArgumentException(INVALID_CAR_NAME_MESSAGE);
> 커스텀 예외와 표준예외 둘다 장단점을 가지고 있고 정답은 없지만

제 피드백을 기억해주셔서 감사합니다! 👍 
본인만의 의견을 팀원과의 문화에 녹여낼 수 있는게 제일 중요합니다.

그런 의미에서, 제가 커스텀 예외와 표준예외를 사용하는 경우에 대한 제 의견을 한번 공유해보겠습니다.

저는 예외처리를 "프레임워크"가 할 경우에는 표준 예외를 사용합니다.
프레임워크가 자동으로 처리해주는 표준 예외가 있다면, 이에 맞는 예외를 던져주는게 개발 공수가 적게 들기 때문입니다.

반면 예외처리를 "개발자" 가 직접 해야할 경우에는 커스텀 예외를 사용합니다.
개발자는 본인이 될수도, 동료 걔발자가 될수도 있습니다.
이럴 경우에는 예외를 어떤 비즈니스 로직과 연관되어 있는지, 커스텀 예외로 만들어서 명시를 하는 편입니다.

2022-04-19 02:20 UTC, ghojeong commented on src/main/java/racingcar/domain/strategy/MovingStrategy.java
> +}
굳이 미리 공부하려 하시기 보다는, TDD-JAVA 교육과적을 끝까지 완주하는데 집중해보세요.
교육 커리큘럼 상으로 TDD 를 가르친다고 되어있지만,
저는 사실 "인터페이스"의 활용법에 대해서 더 많이 배웠습니다.

앞으로 미션을 진행하면서 더 변태적인 인터페이스 사용법들을 더 많이 경험하시게 되리라 생각합니다.

2022-04-19 02:40 UTC, ghojeong approved these changes
제 의도와 부합하게 피드백을 매우 잘 반영해주셨습니다. 👍 ❤️ 
마지막 Step5 가 남았는데, 하루 푹 쉬시고,
내일 라이브 강의를 듣고나서 Step5 미션 제출하는 것을 추천드립니다.
아마 내일 강의를 듣고 나시면, 굉장히 많은부분을 싹 갈아엎고 싶어지리라 생각합니다.
(내일 강의 많이 기대하세요 😄 )
심심하시면 로또미션 1단계를 먼저 진행하시는 것도 좋을 것 같습니다.

2022-04-19 02:40 UTC, merged

2022-04-19 13:34 UTC, wlroh commented
네 알겠습니다~!! 오늘은 지금까지 진행했던 부분들 다시 정리하는 시간을 보내면 되겠네요~
감사합니다!!!