Step4
next-step/java-racingcar pull request #3291
Opened 2022-04-18 12:29 UTC by jadenkim94

4단계 미션 완료하였습니다 :) 
많은 리뷰 부탁드립니다! 

-----------
질문 
TDD 를 공부하며 다양한 래퍼런스들을 찾다보니 **일급컬렉션 객체**를 활용하면 조금 더 깔끔하게 코드를 작성할 수 있을 것 같다는 생각이 들었습니다. 일급컬렉션 외에도 클린코드에 조금 더 빠르게 다가갈 수 있는 다양한 방법이 있을 것 같은데 키워드가 될 만한 것들이 있다면 알려주시면 너무 감사하겠습니다.

2022-04-18 15:12 UTC, seok-2-o requested changes
우승자구하는 미션 잘 진행해주셨네요 💯 
이전 미션에 비해 훨씬 좋아진 것 같아요.

소소한 몇가지 코멘트남겨드렸습니다. 
확인 후 리펙토링 진행해보면 좋을 것 같아요.

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +            .filter(car -> car.getPosition() == winningPosition())
매번 새로운 winningPosition을 찾을 필요가 있을까요?

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +            .filter(car -> car.getPosition() == winningPosition())
getPosition 를 사용하지 않고 비교할 수는 없을까요?

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +            .forEach(car -> winners.add(car));
collect 메소드를 이용하면 어떤가요?

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Position.java
> +        this.position = DEFAULT_POSITION;
int 의 default value 는 무엇인가요?

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/util/RandomValueGenerator.java
> +    private static final Random random = new Random();
소문자로 만든 이유가 궁금하네요.

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +        return cars.stream().mapToInt(car -> car.getPosition()).max().getAsInt();
```suggestion
        return cars.stream()
        .mapToInt(car -> car.getPosition())
        .max()
        .getAsInt();
```

2022-04-18 15:12 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +        cars.stream().forEach(car -> car.move());
stream 을 사용하신 이유가 있나요?

2022-04-23 08:49 UTC, jadenkim94 commented on src/main/java/racingversion2/car/Cars.java
> +            .filter(car -> car.getPosition() == winningPosition())
1. 말씀대로 매번 새로운 winningPosition 을 찾으면 성능을 저하하는 요소가 될 것 같네요! 감사합니다 :) 
2. get 을 사용하는대신 도메인에 메시지를 사용하는 방식으로 변경하였습니다.

2022-04-23 08:51 UTC, jadenkim94 commented on src/main/java/racingversion2/car/util/RandomValueGenerator.java
> +    private static final Random random = new Random();
특별한 이유가 있었던 건 아니고 실수입니다 😭

2022-04-23 08:53 UTC, jadenkim94 commented on src/main/java/racingversion2/car/Cars.java
> +        cars.stream().forEach(car -> car.move());
stream 을 연습하기 위해 사용할 수 있는 곳은 최대한 사용하려고 하고있습니다!

2022-04-23 10:19 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 
훨씬 간결하고 좋은 코드가 된 것 같습니다.

몇가지 피드백 남겨드렸습니다. 확인하시고 5단계에서 함께 고민해주세요.

5단계 미션은 리팩터링 미션입니다. 이미 MVC 구조를 가지고 있어서 크게 변경할 부분은
없어보이네요. 원하신다면 바로 PR 주셔도 무방합니다 :)

2022-04-23 10:19 UTC, seok-2-o commented on src/main/java/racingversion2/car/CarName.java
> +    }
정적 팩토리와 생성자를 모두 제공하는 이유가 있나요?

2022-04-23 10:19 UTC, seok-2-o commented on src/main/java/racingversion2/car/Cars.java
> +    public List<Car> findWinners(int winningPosition){
메소드 내부에서 winningPosition() 를 호출하는 것은 어떤가요 ?

2022-04-23 10:19 UTC, seok-2-o commented on src/main/java/racingversion2/view/InputView.java
> +
[[JAVA] Google Java Style Guide 번역](https://velog.io/@new_wisdom/JAVA-Google-Java-Style-Guide-%EB%B2%88%EC%97%AD)

스타일 가이드를 적용해보면 좋을 것 같아요.

2022-04-23 10:19 UTC, seok-2-o commented on src/test/java/racingversion2/RandomValueGeneratorTest.java
> +    void randomValueGenerator(){
표준 라이브러리를 테스트할 필요가 있을까요? 
그것도 무려 100번이나 수행하는 테스트네요 🤔

2022-04-23 10:19 UTC, seok-2-o commented on src/test/java/racingversion2/car/CarTest.java
> +    void move(){
움직이는 경우와 움직이지 않는경우를 분리하거나 ParamterziedTest 를 이용하면 좀더 명확하게 의도를 전달 할 수 있을 것 같아요

2022-04-23 10:19 UTC, seok-2-o commented on src/test/java/racingversion2/car/CarsTest.java
> +            new Car("benz", 3)));
종하님의 드림카는 무엇인가요?

2022-04-23 10:19 UTC, seok-2-o commented on src/test/java/racingversion2/car/CarsTest.java
> +        List<Car> winners = cars.findWinners(cars.winningPosition());
위에도 남겨드린 리뷰지만 cars.winningPosition() 가 외부로 노출 될 필요는 없을 것 같아요.

이전에는 스트림에서 매번 위닝포지션을 찾고 있어서 드린 피드백이였어요.

2022-04-23 10:19 UTC, merged