Step5. 자동차 경주(리팩토링)
next-step/java-racingcar pull request #3297
Opened 2022-04-19 07:17 UTC by nara1030

안녕하세요 선동님. 말씀해주신 부분들을 나름대로 반영해보았습니다.

1. 우승자 구하기 테스트를 `Competition` 클래스가 아닌 `Cars` 클래스에서 수행하여 객체 생성 시 불필요한 인자가 넘어가지 않게 되었습니다.
2.  `Controller` 클래스에서 우승자를 구하기 위해 getter를 사용하는 부분을 처리해주기 위해 일급 객체인 `RoundRecords`를 생성해주었고 `Competition` 클래스에서 필드로 갖도록 하였습니다. 외에도 getter가 사용된 부분을 객체에 던져 처리하도록 하였습니다.
3. `Car` 및 `Cars` 클래스의 `move()` 메소드가 기존에는 객체를 생성하여 반환하였는데 성능에 문제가 있을 수 있지 않냐는 피드백을 받았고 수정하였습니다.

이외 커밋 로그에서 최대한 반영하려고 하였습니다. 알려주신 깃헙의 커밋 로그를 보며 차례대로 따라가보았는데, 많은 공부가 되고 있습니다. 그리고 저번 피드백에서 `String`, `StringBuilder`, `StringBuffer` 관련하여 질문을 남기셨는데 작성하신 코드를 보니 `StringBuilder`를 사용하셨더라구요. 혹시 그 이유를 여쭤볼 수 있을까요?

감사합니다. 좋은 저녁 되세요!:)

2022-04-19 12:14 UTC, seondongpyo commented
> 그리고 저번 피드백에서 String, StringBuilder, StringBuffer 관련하여 질문을 남기셨는데 작성하신 코드를 보니 StringBuilder를 사용하셨더라구요. 혹시 그 이유를 여쭤볼 수 있을까요?

- 일단 현재 애플리케이션이 멀티스레드 환경이 아니고, 
- 자동차의 위치 값에 따라 문자열을 더하는 연산이 빈번하게 발생하기 때문입니다.

2022-04-19 12:23 UTC, seondongpyo requested changes
마지막 리팩토링 단계도 잘 구현해주셨네요!
몇 가지 코멘트 드렸는데, `RoundRecords`를 중점적으로 개선해보시면 좋을 것 같아요.
내일 있을 라이브 강의도 참고하시면 도움이 되실 거라 생각해요.
조금만 더 힘내주시고 다시 리뷰 요청 부탁드릴게요 🔥

2022-04-19 12:23 UTC, seondongpyo commented on src/main/java/racing/domain/Competition.java
> +    public List<Cars> progressCompetitionAndgetEntireRecords(Movable movable) {
`RoundRecords`를 컨트롤러에 그대로 반환하는 건 어떨까요?
`Competition`이 `RoundRecords`를 상태로 가짐으로써 얻을 수 있는 장점이 크게 없어보입니다.
전체 시도 회수에 대한 결과를 담은 `RoundRecords`를 컨트롤러로 반환하고,
반환된 `RoundRecords` 객체에서 우승자를 구하는 흐름은 어떻게 생각하시나요?

2022-04-19 12:23 UTC, seondongpyo commented on src/main/java/racing/ui/InputView.java
>      private static final Scanner scanner = new Scanner(System.in);
`static final` 키워드를 통해 상수로 선언하셨으니, 관례에 따라 이름을 대문자로 지어보면 어떨까요?
```suggestion
    private static final Scanner SCANNER = new Scanner(System.in);
```

2022-04-19 16:39 UTC, nara1030 commented
선동님 안녕하세요! 상세하게 코드 봐주셔서 감사합니다. 반복적으로 말씀해주신 덕에, 조금씩 체화되고 있는 느낌이 드네요. 피드백 주신 부분에 대하여 수정하였습니다! 혹시 제가 잘못 받아들였다거나 미진한 부분이 있다면 말씀해주시면 감사하겠습니다. 좋은 밤 되시길...🙇🪐

2022-04-20 00:37 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨습니다 👍
추가로 고민해보실만한 내용에 대해 코멘트 드렸는데 확인 부탁드릴게요.

자동차 경주 미션 완료하시느라 고생 많으셨습니다.
부족한 리뷰어와 함께라서 성장에 도움이 되었는지 모르겠네요.
더 궁금하시거나 의견 나누고 싶으시면 지금처럼 코멘트나 DM 부탁드릴게요.
마지막 볼링 점수판 미션까지 완주하시길 응원하겠습니다 🔥

2022-04-20 00:37 UTC, seondongpyo commented on src/test/java/racing/domain/CarsTest.java
>  }
![image](https://user-images.githubusercontent.com/64854054/164121109-3889d095-ed35-441f-be56-ec5c59ba0f30.png)

`CarsTest`에서 EOL 경고가 확인되는데, EOL이 무엇인지 찾아보시고 이를 해결해보시면 좋을 것 같아요.

2022-04-20 00:37 UTC, seondongpyo commented on src/main/java/racing/domain/Car.java
>      }
해당 메서드의 매개변수 이름을 `distance` 정도로 사용해보면 어떨까요? 
개인적으로는 `max-`라는 접두사가 있어서 그런지, 메서드를 호출할 때 
인자로 '최대' 위치 값만을 전달하여 우승자를 구하는 용도로만 사용해야 할 것 같은 느낌이 듭니다.

그리고 이 메서드는 테스트 케이스 검증에서도 사용해볼 수 있을 것 같아요.
현재 `CarTest` 클래스에서 자동차의 이동 여부에 따른 위치 값을 getter를 이용하여 검증하고 있습니다.
```
    @Test
    void 차가_전진() {
        car.move(() -> true);
        assertThat(car.getDistance()).isEqualTo(1);
    }
```

만약 getter 사용을 최소화한다고 하면, 검증 시 `isLocatedAt()`을 활용해볼 수 있을 것 같아요.
```
    @Test
    void 차가_전진() {
        car.move(() -> true);
        assertThat(car.isLocatedAt(1)).isTrue();
    }
```

2022-04-20 00:38 UTC, merged

2022-04-20 02:01 UTC, nara1030 commented on src/test/java/racing/domain/CarsTest.java
>  }
이 부분은 제 인텔리제이상에선 보이지 않던데.. 혹시 따로 설정을 해주신건지 궁금합니다.😮

2022-04-20 02:07 UTC, nara1030 commented on src/main/java/racing/domain/Car.java
>      }
`isLocatedAt()`을 사용함으로써 `getDistance()`를 없앨 수 있을까 싶었는데, `ResultView` 클래스에서 사용하고 있어 어렵네요. 한 가지 궁금한 점이 있는데 `setter`의 경우 객체 외부에서 객체의 상태를 변경할 수 있어서 자제할 필요가 있지만, `getter`의 경우는 필요하다면 생성해도 크게 문제가 없다고 생각해도 될까요?

2022-04-20 02:42 UTC, seondongpyo commented on src/test/java/racing/domain/CarsTest.java
>  }
해당 경고는 IDE가 아닌 GitHub 상에서 보여주는 경고입니다.
IntelliJ IDEA에서 다음처럼 설정해보시면 자동으로 마지막에 개행을 추가해주니 참고하시면 좋을 것 같아요.

![image](https://user-images.githubusercontent.com/64854054/164136191-7320fe12-7d9b-4044-880e-47432fdcc256.png)

2022-04-20 02:47 UTC, seondongpyo commented on src/main/java/racing/domain/Car.java
>      }
[링크](https://jessyt.tistory.com/158)를 통해 도서 `엘레강트 오브젝트`의 내용을 참고해보시면 좋을 것 같습니다.
어떻게 보면 말장난처럼 보일 수 있지만, '자료구조'와 '객체'의 의미와 둘의 차이에 대해서도 생각해보실 수 있을 거에요.