Step5
next-step/java-racingcar pull request #3304
Opened 2022-04-19 16:53 UTC by rumor1993

안녕하세요! 

리뷰 잘 부탁드립니다!
좋은 하루 되세요!

2022-04-19 23:08 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
몇가지 수정 의견 드렸는데, 확인 부탁드립니다.

2022-04-19 23:08 UTC, wheejuni commented on src/main/java/domain/car/CarRacingGame.java
> +        System.out.println("최종 우승했습니다.");
출력 클래스를 분리해보면 어떨까 싶습니다!

2022-04-19 23:08 UTC, wheejuni commented on src/main/java/domain/car/CarRacingGame.java
> +        List<Car> winners = getWinners();
`fix` 와 `find` 가 왜 별개의 로직이어야 하는지는 잘 모르겠습니다!
`Cars.getWinners()` 와 같은 메서드에서 한 번에 내려와야 하는 건 아닐지요?

2022-04-19 23:08 UTC, wheejuni commented on src/main/java/domain/car/Cars.java
> +        }
`.stream().forEach()` 활용해보셨으면 더 좋았을 것 같네요.

2022-04-19 23:08 UTC, wheejuni commented on src/main/java/domain/car/Cars.java
> +        if (max.equals(new Max(car.getDistance()))) {
이 로직이 `Car` 에 위치해야 한다는 생각입니다.

2022-04-20 14:11 UTC, rumor1993 commented on src/main/java/domain/car/Cars.java
> +        }
넵 스트림을 좀 더 써보는 연습을 해보겠습니다!

2022-04-20 14:11 UTC, rumor1993 commented on src/main/java/domain/car/CarRacingGame.java
> +        List<Car> winners = getWinners();
한곳에서 처리하도록 변경하였습니다!

2022-04-20 14:17 UTC, wheejuni approved these changes
👍

2022-04-20 14:17 UTC, merged