5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #3313
Opened 2022-04-20 13:56 UTC by SoonMyeong

안녕하세요!

말씀 주셨던 피드백 내용 반영하고 
5단계 내용인 " 핵심 비지니스 로직을 가지는 객체를 domain 패키지, UI 관련한 객체를 view 패키지에 구현한다. "
에 따라 패키지명을 변경했습니다!

오늘 강의 보면서 그동안 고민했던 내용에 대한 얘기도 나오고 했었는데
5단계까지 달려오면서 꽤 많은 고민을 했고 열심히 한 보람이 있었다는걸 느꼈습니다~ 
감사합니다!

2022-04-21 04:33 UTC, yongdae requested changes
자동차 미션 마지막 단계를 잘 수행해주셨네요. 💯 
진행해주신 부분에 대해 소소하지만 의견을 드렸습니다.

그리고 이전 단계에서 의견 드렸지만 미쳐 못보신 부분이 있는 것 같아요.
[반영되지 않은 부분](https://github.com/next-step/java-racingcar/pull/3239#discussion_r851704592)도 같이 확인 부탁드립니다. 😄

2022-04-21 04:33 UTC, yongdae commented on src/main/java/domain/RunRace.java
>  public class RunRace {
아직 [의견](https://github.com/next-step/java-racingcar/pull/3239#discussion_r851704884) 드린 RunRace에 대한 테스트가 추가되지 않았어요. 😭

2022-04-21 04:33 UTC, yongdae commented on src/main/java/domain/Cars.java
> +    public boolean isSize(int size) {
isSize는 조금 어색한 것 같아요.
checkSize 같은 이름을 사용해보면 어떨까요?

2022-04-21 04:33 UTC, yongdae commented on src/test/java/domain/RaceTest.java
> +class RaceTest {
테스트를 분리해주셨네요. 👍

2022-04-21 04:33 UTC, yongdae commented on src/main/java/RacingCarGame.java
> +import domain.RunRace;
RacingCarGame는 domain이 아닌 controller이 아닐까요? 🤔

2022-04-21 11:13 UTC, SoonMyeong commented on src/main/java/domain/RunRace.java
>  public class RunRace {
RaceTest 밑에 추가해뒀습니다!

2022-04-21 11:13 UTC, SoonMyeong commented on src/main/java/domain/Cars.java
> +    public boolean isSize(int size) {
그냥 둘껄그랬나봐요 ㅎㅎ; 네!

2022-04-21 16:52 UTC, yongdae requested changes
빠르게 피드백을 반영해주셨네요. 👍 

미션을 마무리짓기에 앞서 한번 더 의견을 드리는게 좋을 것 같아
Request changes로 진행하도록 하겠습니다. 🔥🔥

그럼 확인하시고 다시 리뷰 요청 부탁드립니다. 🙇

2022-04-21 16:52 UTC, yongdae commented on src/main/java/service/RunRace.java
>  public class RunRace {
제가 조금 더 상세히 의견을 드렸어야 했는데... 죄송합니다. 😭 

[이 의견을 드린 이유](https://github.com/next-step/java-racingcar/pull/3313#discussion_r854762623)는 RunRace 객체의 run() 테스트를 할 때 오롯히 RunRace만 가지고 테스트를 해보시길 원해서였습니다.
지금은 RunRace가 RaceRecord와 Cars 객체에 의존성을 가지고 있는데 이 연관성을 지울 수는 없을까요?

2022-04-21 16:52 UTC, yongdae commented on src/main/java/controller/Race.java
>  public class Race {
`Race 를 Controller에 두고 RunRace 를 Service에 둬봤습니다!`
이번에 피드백을 반영해주시면서 Race는 RunRace는 Service로  변경해주셨는데요.

<img width="1018" alt="스크린샷 2022-04-22 오전 1 40 39" src="https://user-images.githubusercontent.com/4317804/164509457-802592e3-91f1-420b-a380-73faa269d5ee.png">

Race가 Domain이라면 Controller의 역할을 한다고 판단하기에는 무리가 있다고 생각해요.

코드로 View 패키지와 비지니스를 알고 사용하는 Controller은 RacingCarGame 같은데
Race를 Controller역할로 보시는 이유가 있으신가요?

그리고 Service의 개념은 어떤 용도로 활용하고 계신지 알고 싶어요. 🤔

2022-04-22 11:31 UTC, SoonMyeong commented on src/main/java/service/RunRace.java
>  public class RunRace {
아..! 그러네요! 
의존성 분리 시켜보겠습니다!

2022-04-22 12:25 UTC, SoonMyeong commented on src/main/java/controller/Race.java
>  public class Race {
음...
아...  매우 중요한 질문을 주신거 같습니다!  제가 생각했던 대로 한번 적어보겠습니다

RacingCarGame 을 뷰로 생각을 했었어요  inputView, resultVivew 를 호출 하는 view 랄까요..?
그리고 Race 가 RacingCarGame 에서 받은 데이터를 가지고 
RunRace(핵심) 을 호출 이부분이 컨트롤러 부분이라고 생각하고 진행했었습니다!
서비스의 용도는 음.. 비즈니스 로직을 처리하는 부분으로 활용하고 있었어요.
RunRace 가 실질적으로 횟수를 반복하면서 자동차를 움직이게 하니 이게 핵심이지 않나..? 생각이 들어서 
서비스에 뒀었습니다!

정리하면 RunRace 가 핵심 비즈니스라 생각해서 서비스 레이어로 생각했었고 이를 호출하는 Race 를 컨트롤러로 뒀었습니다!

----
이렇게 적어놓고 MVC 검색좀 해봤는데요
애초에 MVC 라는 약자에 서비스는 포함되지도 않는데 나는 왜 서비스라는걸 굳이 썼을까? 에 대해 고민해보기 시작했습니다.
그냥 습관적으로 controller 가 있으니 service 도 있어야지 하는 생각도 아니고 그냥 평소에 컨트롤러 쓰면 
서비스도 당연히 써버릇 해왔으니 습관처럼 쓴거 같다 라는 결론이 나왔습니다..!

서비스에 대해 찾다보니 비즈니스 로직의 재사용성, 확장성 등을 위해서 만들어졌다 라는 글귀를 보게되었습니다.

흠.. 이건 그냥 갑자기 든 생각인데 저번 강의 때 토비가 인수테스트? 때는 서비스 테스트를 안한다고 했던 내용이 떠오르네요
도메인이 핵심비즈니스 로직을 가지고 있어서 그런건가.. 하는 생각도 들고...

아 좀 정리되지 않게 글을 쓴거 같네요

좀 찾아보고 내린 결론은 도메인 영역에서 비즈니스 로직을 처리하는데 현업에서는 여러 도메인의 비즈니스 로직을 의미있게 처리 하기위해 서비스레이어를 사용하는게 아닌 가하는 생각입니다!
(Layered Architecture 를 참고해봤습니다)  

결국 해당 요구사항처럼 현재는 서비스패키지는 없어도 된다는 생각입니다.

2022-04-22 23:27 UTC, yongdae approved these changes
안녕하세요. 미션 마지막까지 피드백을 잘 따라와주셨네요. :)

미션 처음부터 마지막까지 부단히 고민하고 노력하셔서 좋은 결과물이 나온거 같습니다. 😄
순명님 덕분에 또 한번 불타오르네요 🔥

열심히 피드백을 드린다고 드렸는데 잘 드렸는지 모르겠네요.
조금이나마 도움이 되었기를 바래봅니다. 🙏

마지막으로 의견을 드린 부분이 있으니 한번 확인만 부탁드릴께요

자동차 경주 미션은 끝났지만, 궁금한점이나 어려운점 있으면
언제든 편하게 DM 주세요!그동안 고생 많으셨습니다. 수고하셨습니다. 👍

끝까지 완주하시길 응원하겠습니다! 🎉

2022-04-22 23:27 UTC, yongdae commented on src/main/java/domain/RunRace.java
> +}
public class RunRace {
        private static final int RACE_FINISH_COUNT = 0;
        private int count;
    
        public RunRace(int count) {
            if (tryNo < 1) {
                throw new IllegalArgumentException("시도 횟수는 0보다 큰 값을 사용해주세요.");
            }
            this.count = count;
        }
    
        public void race() {
            count--;
        }
    
        public boolean isFinish() {
            return count == RACE_FINISH_COUNT;
        }
    }

지금은 RunRace가 가지고 있는 멤버 변수가 3개이기 때문에
`규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 이 규칙을 적용 할 수 있어요.

만약 이렇게 RunRace를 `경주 시도` 역할에 집중 할 수 있는 객체로 만들어보면 어떨까요?

2022-04-22 23:27 UTC, merged