Step5 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #3319
Opened 2022-04-21 14:40 UTC by kang-jisu

안녕하세요! 안이민리뷰어님! 자동차 게임 마지막 단계이네요 ☺️
어제 강의를 듣고 정리를 좀 해보았지만 이미 이전에 일급 컬렉션, 원시값 포장, MVC 구조에 대해서 피드백해주신 덕분에 
제 생각엔 (?) 많이 고칠 부분이 없었던 것 같았습니다!! ㅎㅎ 많은 걸 알려주셔서 감사합니다 👍

- getter를 쓰지 않고 메시지를 보내보기
  - `isMaxDistance`, `getMaxDistance` 
- 생성자 오버 라이딩 시 실제로 값을 할당하는 메서드를 제외하고는 `this`로만 사용해보기 

강의를 들으면서 이 두 가지를 제 코드에 적용해보았습니다!

--- 
그리고 조금 추가적인 수정인데 Car의 `state`를 모두 `distance`로 바꿨습니다! 
> 약간 설명을 해보자면 .. 
제가 Car의 현재 상태, 거리를 나타내는 필드를 `state`로 명명해서 사용했는데, 
이 이유가 Car의 현재 상태를 나타낸다고 생각했기 때문인데요! 
이 부분에 대해서 PositiveInteger일 때도, Distance로 변경했을 때도 계속 state라는 이름을 사용하고 있었지만
계속 다시 보니 객체의 상태를 나타내는 것이 필드이고 그걸 Distance 클래스로 나타냈기 때문에 필드 이름이 distance이어야 할 것 같더라고요..ㅎ
그냥 단순히 상태를 나타내니깐 state라고 해야지!라고 만들고 있었는데 그렇게 되면 앞으로 모든 필드이름을 state라고 할 것 같아서 ; ; 
이름 하나를 바꾸려니 실제 코드, 테스트코드, 테스트메서드명, string 값 등 바꿔야 할 게 너무 많아서 괜한 짓인가 싶긴 했지만 
오래 지나고 봤을 때 왜 state로 했지..?라고 의문이 들 것 같아서 그냥 변경해보았습니다..!  

추가적으로 피드백 주시진 않으셨지만 거슬리셨을 수도 있으셨을텐데 마지막에 와서야 대 변경을 해버렸네요..ㅎㅎ
실무에서 이런 변경을 했다간 큰일날 것 같긴한데.. 앞으로는 처음 이름을 지을 때 더 신경써보겠습니다!!
이해부탁드립니다 ( _ _ )

---
몇가지 궁금한 사항에 대해서는 코멘트로 달겠습니다!
마지막 단계도 리뷰 잘 부탁드리겠습니다!! 🚀

2022-04-21 14:49 UTC, kang-jisu commented on src/main/java/racingcar/model/Distance.java
> +    }
Distance의 값을 비교하기 위해서 compareTo 메서드를 구현해보았는데요!
이렇게 비교하는 메서드를 만들게되면 `implements Comparable`+`@override` 도 함께 해주는 것이 맞나요/좋은가요 ??
sort나 PQ에서 비교하는 상황이 없고, 단순히 메서드 이름을 `compareTo`라고 지은거여서 일단은 위에 말한 추가적인 구현은 해주지 않긴 했습니다!

그리고 외부에서 사용할 때 
```java
        if (state.compareTo(maxState) < 0) {
            return maxState;
        }
```
이렇게 -1, 0, 1 결과로 if문에서 사용하는 방식은 괜찮은 건지 궁금합니다!

2022-04-21 14:58 UTC, kang-jisu commented on src/main/java/racingcar/model/Cars.java
> +        return maxState;
Car에 메시지를 보내 Max값을 구해보고, value()로 꺼내지 않고 Distance 객체로 다뤄보고 싶어서 다음과 같이 변경했습니다..!
그런데 이런식으로 구현했을 때 maxDistance 값이 계속 변해도 되는걸까요.?
for loop라서 다른 메서드들과의 컨벤션도 안 맞는것 같아서요..!😢 stream을 이용한 max 계산이 조금 어려워진 것 같습니다 ㅠㅠ

2022-04-22 18:35 UTC, orgojy requested changes
안녕하세요 😄 지수님!

5단계 자동차 경주(리팩토링) 미션도 잘 구현해주셨네요!
몇 가지 코멘트를 남겨 두었는데요. 확인해보시고 다시 요청 부탁드릴게요~!
미션 시작부터 MVC를 잘 구현해주셔서 크게 변경할 부분은 없었습니다.
마지막 미션이니만큼 전체적으로 한 번 살펴보시면서, 객체의 책임은 어디까지 인가를 살펴보시면 학습에 더 좋으실 것 같습니다. 👍

2022-04-22 18:35 UTC, orgojy commented on src/main/java/racingcar/model/Car.java
> +    }
이 메서드가 어떤 역할은 하는 것일까요?
구현 로직과 사용 형태를 보면 같은 거리를 가진 자동차를 찾기위한 목적인데요.
네이밍을 다시 한 번 생각해보셔도 좋을 것 같습니다.

2022-04-22 18:35 UTC, orgojy commented on src/main/java/racingcar/model/Distance.java
> +    }
말씀하신 리턴값도 하나의 매직넘버입니다.
사용자체는 문제가 없는데, 매직넘버를 사용해서 조건식에 들어가게되면 가독성이 떨어지게 됩니다.
그래서 가장 많이 쓰는 리팩터링 방식으로 조건식을 메서드로 추출합니다.

리팩터링을 해보시면 아시겠지만, 조건식에서 true/false를 바로 반환해주는 경우가 아니면,
항상 그 비즈니스의 책임을 위임할 수 있는 적절한 객체로 이동하는 경우가 많습니다.
일단 한 번 시도해보시면 좋을 것 같습니다.

2022-04-22 18:40 UTC, orgojy commented on src/main/java/racingcar/model/Cars.java
> +        return maxState;
아래 코멘트에 답변은 달아드렸구요.
조금 첨언드리면,
`현재 상태: Cars -> Distance`
이미 비즈니스적으로 Distance라는 의존성을 가진 경우에는 애써 다른 형태로 의존성을 분리를 노력해도 이미 의존성은 가진 상태가 됩니다.
그래서 실무에서 부패방지계층을 구현하는 식으로 디자인패턴 등을 활용하여 인터페이스를 두는데요.
이 구현에서는 그럴 것 까지는 없다고 생각합니다.
이후 부터는 아래 동일한 부분에 코멘트 달아두었으니 확인부탁드릴게요! 😄

2022-04-23 05:17 UTC, kang-jisu commented on src/main/java/racingcar/model/Car.java
> +    private static final Distance MOVE_DISTANCE = Distance.ONE;
아!! 감사합니다! 특징이 다른 필드와 메서드들은 칸을 띄워 구분하도록 하겠습니다!!

2022-04-23 05:19 UTC, kang-jisu commented on src/test/java/racingcar/CarTest.java
> +        assertThat(maxDistance).isEqualTo(new Distance(4));
아아 그러네요! 재사용되는 로컬변수는 의미있는 이름으로 선언해서 사용해보겠습니다 !! 제안해주신 코드가 선언한 fourDistance가 assert문에서 반환되어야 한다는 의미도 더 잘 나타나는 것 같네요!! ㅎㅎ

2022-04-23 05:21 UTC, kang-jisu commented on src/main/java/racingcar/model/Car.java
> +    }
메서드이름으로만 보면 Car에서 Distance의 Max값을 계산해내야하는 책임이 있는 것이 되네요!ㅠㅠ
입력받은 Distance와 Car가 가지고있는 Distance값이 같은지 비교하는 목적이 드러나도록 `isSameDistance`로 변경하겠습니다!!

2022-04-23 05:28 UTC, kang-jisu commented on src/main/java/racingcar/model/Cars.java
> +        return maxState;
Cars에서 car.distance.value 로 내부에 값을 가져오지 않겠다는 것만 생각하다보니, 실제로 distance를 가져오려는 이유가 뭔지, 각각의 클래스가 가질 책임이 뭔지 고민이 조금 부족했던 것 같습니다!!

말씀해주신 것 처럼 Cars는 Car의 Distance에 대해 이미 의존성을 가지고 있으니, Car에서는 Distance 값을 가져오는 것, 그리고 Cars에서는 얻어온 Distance를 가지고 max값을 계산해서 winner를 얻어낸다는 의미를 잘 드러내도록 코드를 작성하는데 집중해보겠습니다!! 감사합니다 🤓

2022-04-23 05:35 UTC, kang-jisu commented on src/main/java/racingcar/model/Distance.java
> +    }
넵!! 만약 Distance의 비교가 필요하다면, compareTo와 그 리턴값인 매직넘버(-1,0,1)을 그대로 사용하기 보단 Distance에서 비교 조건에 대한 true/false를 반환해주는 메서드를 따로 구현해 사용해야겠네요.!!

만약에 사용하게 된다면 이렇게 해봐야겠다 하고 작성해보았는데 괜찮을까요? 아래 피드백주신 stream을 사용하다보니 해당 코드를 구현하다가 실제로 사용하지는 않았습니다!
```java
//Distance클래스
    public static final int COMPARE_GREATER = 1;

    public int isGreaterThan(Distance distance) {
        if (compareTo(distance) == COMPARE_GREATER) {
            return true;
        }
        return false;
    }

    private int compareTo(Distance distance) {
        return value - distance.value();
    }
```

2022-04-23 05:39 UTC, kang-jisu commented on src/main/java/racingcar/model/Cars.java
>      }
Car에서는 Distance 값을 가져오는 것
Cars에서는 얻어온 Distance를 가지고 max값을 계산해서 winner를 얻어내는 것
두가지의 책임이 드러나도록 작성하는 것에 유의해보겠습니다!

제안해주신 코드를 바탕으로 하면서 Distance에서 value를 가져오지 않고 compareTo 메서드를 이용해 max를 계산하도록 수정해보겠습니다!! 🚀

2022-04-23 06:07 UTC, kang-jisu commented
안녕하세요 리뷰어님! 피드백 바탕으로 다시 리팩토링해보았습니다!! 😊

말씀해주신대로 Car, Cars, Distance의 책임에 대해서 고민해보면서 
우승자를 구하는 로직에 있어서 **가지고 있는 Car의 값 중 Max 조건으로 우승자를 가려내는 책임은 Cars**에만 두고,
Car와 Distance에서는 'max'와 같은 **특정 조건이 아닌 Car와 Distance에 대한 상태만**을 메시지로 주고받도록 구현하도록 했습니다!!
그러기 위해서 Car, Distance에 있는 메서드가 어떤 외부 특정 조건에 제한되는 이름이 되지 않도록 유의해야겠습니다..!!ㅎㅎ

다시 한번 리뷰 잘 부탁드리겠습니다!!
감사합니다 🌟

2022-04-23 07:59 UTC, orgojy requested changes
안녕하세요 😄 지수님!
몇 가지 코멘트에 대해 생각을 많이 해보시고 잘 개선해보셨네요. 👍 
머지 전에 약간 아쉬웠던 코드들에 대해서 코멘트를 남겼구요.
생각해보면 좋을 부분에 대해서도 남겼습니다.
확인해보시고 다시 요청 부탁드릴게요~!

2022-04-23 07:59 UTC, orgojy commented on src/main/java/racingcar/model/Car.java
> +        return distance.equals(distance);
파라미터 자신을 비교하고 있습니다. 무조건 true가 되겠네요.
```suggestion
        return this.distance.equals(distance);
```
이 경우에는 false가 되는 테스트 케이스를 작성하시면 사전에 방지할 수 있겠네요. 😄

2022-04-23 07:59 UTC, orgojy commented on src/main/java/racingcar/model/Distance.java
> +public final class Distance implements Comparable {
Raw Type으로 인터페이스를 활용하시기보다는 Comparable 제네릭 그대로 활용하는게 좋습니다.
Raw Type이나 Object를 그대로 활용하시게 되면 런타임에 비즈니스가 예외가 발생하는 경우가 생길 수 있습니다.
제네릭을 사용하시면 컴파일 타임에 타입에 대한 검증이 끝나고 비즈니스 구현이 단조로워지실 겁니다.
```suggestion
public final class Distance implements Comparable<Distance> {
```
위 처럼 수정하시고 compareTo도 재정의를 다시 한 번 해보시는걸 추천드립니다. 😄

2022-04-23 07:59 UTC, orgojy commented on src/test/java/racingcar/CarTest.java
> +    void isSameDistanceTest() {
실패 케이스를 작성해보시면 현재 메서드의 구현 로직이 잘못되어있다는 것을 알 수 있을 것 같네요.

2022-04-23 07:59 UTC, orgojy commented on src/test/java/racingcar/DistanceTest.java
> +        assertThat(new Distance(1).compareTo(new Distance(2))).isEqualTo(-1);
이미 compareTo의 로직을 알고 있는 관계자는 테스트 케이스의 의미를 알 수 있지만,
하나의 케이스만 보고는 잘 모를 수도 있다고 생각합니다.
여러 케이스를 테스트해보는건 어떨까요? 😄

2022-04-24 03:01 UTC, kang-jisu commented on src/main/java/racingcar/model/Car.java
> +        return distance.equals(distance);
앗!! ㅠㅠ this를 빼먹었네요 !! 😢
결과가 true/false로 나올 수 있는 조건에 대해서 두가지 경우를 모두 테스트해보면서 구현이 올바르게 됐는지 잘 확인해봐야겠습니다!! 감사합니다 ㅠㅠ

2022-04-24 03:09 UTC, kang-jisu commented on src/main/java/racingcar/model/Distance.java
> +public final class Distance implements Comparable {
아아 ! Comparable 구현시 제네릭을 사용하니 `distance.compareTo(다른 클래스)` 와 같이 잘못된 사용이 컴파일타임에 검증되고 compareTo메서드에 Object에서 Distance로 값을 가져오는 과정도 생략되네요..!!
안그래도 오버라이딩 메서드 인자가 Object인 것이 이상했는데 ㅠㅠ compareTo메서드에 다른 값을 넣어보는 테스트를 했다면 눈치챘을 텐데 너무 당연하다고 생각하고 넘어간 것 같습니다😢 조심하겠습니다!! 감사합니다!!

2022-04-24 03:10 UTC, kang-jisu commented on src/test/java/racingcar/CarTest.java
> +    void isSameDistanceTest() {
넵! False를 반환하는 테스트를 구현하니 그래도 True로 나오고 있었네요 ㅠㅠ 경우에 대해 테스트를 잘 해서 미리 확인하겠습니다!! 감사합니다 !

2022-04-24 03:13 UTC, kang-jisu commented on src/test/java/racingcar/DistanceTest.java
> +        assertThat(new Distance(1).compareTo(new Distance(2))).isEqualTo(-1);
아아.!! compareTo가 반환할 수 있는 3가지(-1,0,1) 경우에 대해서 모두 테스트코드를 작성해야 테스트를 통해서 메서드가 어떤 역할을 하는지 파악하기 좋겠네요! 그런 과정에서 테스트가 실패한다면 구현이 잘못된 것을 발견할 수도 있구요..!!
입맛대로 (?) 성공하는 테스트코드만 한번 작성해본다는 생각말고 실제로 조건을 잘 테스트해보고 예외케이스를 잡고 테스트코드를 통해서 모든 기능을 검증해본다는 마음을 다시 한 번 가져야겠습니다 ㅠㅠ 이번엔 마음이 너무 급했던 것 같아요!!
감사합니다 :) 👍

2022-04-24 03:15 UTC, kang-jisu commented on src/test/java/racingcar/CarTest.java
> +    void isSameDistanceTest() {
그리고 이전에 테스트코드용 상수를 만들어 놓고 다시 Distance 상수를 사용했더라구요 😖
이런 부분도 유의하도록 하겠습니다!!

2022-04-24 03:23 UTC, kang-jisu commented
안녕하세요 리뷰어님! 피드백해주신 부분 다시 수정해보았습니다!!😊 

이번 단계에서 일부 테스트만 성급하게 작성하려는 저의 안좋은 습관이 바로 드러난 것 같아 반성하게되네요.. 😭
테스트 코드로 최대한 모든 경우를 확인해보려고 노력하겠습니다! ㅎㅎ 

다시 한번 감사드리고 리뷰 잘 부탁드리겠습니다! 🚀

2022-04-24 07:04 UTC, orgojy approved these changes
안녕하세요 😄 지수님!
자동차 경주(리팩토링) 미션도 잘 구현해주셨네요!
5단계까지 과정 중에 미션을 완료하는 것과 더불어서,
추가로 구현하셨던 구현 패턴과 생각에 대해서는 좋은 시도라고 생각했습니다.
특히, 열정적인 자세로 질문을 통해 코드를 개선해나가셨던 모습이 인상적이었습니다. 👍 
이번 단계 고생 많으셨구요.
PR은 머지하도록 하겠습니다. 다음 미션도 계속 응원합니다! 🚀

2022-04-24 07:05 UTC, merged

2022-04-24 12:44 UTC, kang-jisu commented
넵! 그동안 감사했습니다 리뷰어님!! ☺️ 
하나하나 좋은 접근법 추천해주시고 피드백 해주셔서 많이 배워가는 경험이었습니다 :D 
다음 단계들도 열심히 진행해보겠습니다! 👍🙇‍♀️