step5
next-step/java-racingcar pull request #3374
Opened 2022-05-06 15:58 UTC by youngsuseo

자동차 경주를 새로 개발하여 구조를 약간 변경하고 리팩토링하여 리뷰 요청 드립니다.

최대한 리뷰 해주신 부분들 반영하고 요청 드린다고 하긴 했는데
혹시 누락 된 부분들과 추가적으로 수정해야 하는 부분 있으면 말씀 부탁드리겠습니다!

2022-05-06 16:09 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/RacingCar.java
> +    }
과제에서는 실질적으로 move를 진행하는 position 클래스 바로 위에서 생성해서 주입했는데,
 
제 생각에는 MovingStrategy 같은 경우 RacingMain 처럼 Controller, service 역할을 하는 곳에서
RandomMovingStrategy 또는 SequentialMovingStrategy 객체를 생성해서 주입해주는 것이 좋을 것 같다라고 생각이 들었습니다. 다만, 그렇게 하다보면 해당 파라미터를 계속 가지고 다녀야 하기 때문에 도메인의 파라미터가 많아지는 단점이 생길 것 같습니다.

해당 객체는 어떤 위치에서 생성해서 주입해주는 것이 좋을까요?

2022-05-06 16:12 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +    }
이처럼 메서드 두개를 chaining으로 연결해서 호출해도 괜찮을까요?

해당 생성자에서 string으로 넘어온 값을 split하고 list로 넘겨주는 역할을 진행하는데
split 하는 것 따로, list 만드는 것을 따로 메서드로 구현했습니다.
이럴때는 그냥 하나의 메서드에서 split하고 List로 만드는 걸 같이 진행하는 것이 좋을까요?

2022-05-07 09:16 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingWinners.java
> +
@youngsuseo RacingCars가 RacingCar들의 상태를 갖는 일급컬렉션이니
RacingWinners 별도 분리 없이 처리하는게 좋을것 같습니다. (중복 처럼 보이네요)
도메인을 나눌때 현재 가지고 있는 상태의 값이 유의미한 값인지 또는 중복이 아닌지
같이 판단해 보면 좋을것 같습니다.

유틸클래스는 제가 참고 링크 남겨 놓았으니 확인해 보시기 바랍니다 😄 
참고) https://junroot.github.io/programming/Utility-Class/

2022-05-07 09:20 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCar.java
> +    }
@youngsuseo 저는 가급적 고수준의 도메인이 변경되지 않게
저수준 영역(Controller등 외부) 에서 주입받아 사용하는 것을 선호합니다.

장점으로는 전략의 변경에 따른 도메인로직 수정이 발생되지 않을것 이고
단점으로는 리뷰이님이 고민하셨던 것처럼 메소드나 생성자 주입을 통해서
처리해야 되기 때문에 파라미터가 많아 질 수 있는 단점이 있을것 같네요.

2022-05-07 09:22 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +    }
List 형태의 names를 주입받아서 RacingCars 내부에서는 List 형태 RacingCar로 변환만 해보는것은 어떨까요 ?!

지금 split 그리고 List 변환 작업이 RacingCars 내부에 있다 보니
역할이 커지는것 같습니다.

참고로 저는 생성에 대한 역할을 담당하는 Factory 클래스로 나누는 것을 선호합니다.
참고 ) https://johngrib.github.io/wiki/pattern/factory/

2022-05-07 09:39 UTC, simjunbo requested changes
리뷰이님 마지막 미션까지 잘 구현해 주셨습니다. 💯 
패키지를 분리해서 새로 구현까지 해주셨군요.

관련해서 질문해주신 부분 답변과 소소하게 리뷰 남겨 놓았으니
확인 한번 부탁드립니다.

자동차 경주 미션의 마지막에 얼마 남지 않았습니다.
화이팅입니다. ❗❗❗

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/RacingMainA.java
> +public class RacingMainA {
클래스 명이 RacingMainA 인 이유가 있을까요 ?!
패키지로 나누어져 있기 때문에 별도 구분을 위해 A를 붙일 필요는 없어 보입니다.

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/MovementCount.java
> +class MovementCount {
현재 해당 클래스를 사용하는곳이 없어 보이네요.
불필요한 클래스는 삭제해주세요 😄

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/MovingStrategy.java
> +    boolean checkCondition();
결과값을 체크하는 전략 패턴으로 잘 나누어 주셨네요 👍

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingGame.java
> +    private final MovementCount movementCount;
현재 사용되고 있지 않고 있네요.

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingPosition.java
> +    private int increase(MovingStrategy movingStrategy) {
전략 패턴 잘 적용해 주셨습니다 👍

2022-05-07 09:39 UTC, simjunbo commented on src/test/java/racing/CarsTest.java
> +        assertAll(
피드백 반영 잘해주셨습니다. 👍

2022-05-07 09:39 UTC, simjunbo commented on src/test/java/racing_refactoring/domain/RacingGameTest.java
> +        List<RacingCar> cars = new ArrayList<>();
이런 초기화 부분은 BeforeEach 를 사용해 보면 좋을 것 같습니다.

2022-05-07 09:39 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +        this.racingCars.set(index, racingCars.get(index).move());
```
    void move(){
        racingCars.forEach(RacingCar::move);
    }
```

이런식으로 그냥 순차적으로 호출 시키게 하면 어떨까요 ?!
현재 RacingGame 의 구조 때문에 set 형태로 사용하신것 같은데
RacingGame 클래스 역할에 대해서도 한번 고민해 보시면 좋을것 같습니다 😄

2022-05-07 13:44 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +    }
새로 만들려고 하는 RacingCar(List<String> names) 와 RacingCar(List<RacingCar> racingCars) 의
generic type만 달라 오류가 발생하더라고요ㅠㅠ
이런 상황에서는 RacingCar(String[] names) 의 형태의 생성자를 추가하는 것이 나을까요?

2022-05-07 13:51 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/MovementCount.java
> +class MovementCount {
MovementCount도 객체로 따로 빼서 생성자 내부에 validation 로직도 추가하는 걸 생각했는데
MovementCount객체를 사용하는  RacingGame 도메인에서도 따로 사용하는 것이 없다면
해당 변수 자체를 사용하지 않는 것이 좋다는 말씀이실까요?

그렇다면 movementCount도 0보다 크다라는 조건을 추가하고 싶은데
이건 RacingMain에서 진행하면 될까요?

2022-05-07 14:11 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +        this.racingCars.set(index, racingCars.get(index).move());
RacingCar.move 메서드가 RacingCar 라는 객체를 반환하게 되면서
racingCars 라는 list 안의 객체를 교체해야 하는 상황이 생겼는데,
forEach로 동작시키면 해당 객체를 교체할 수 없는 문제가 생겼습니다ㅠㅠ
혹시 어떤식으로 개선하는 방향이 좋을까요?

2022-05-07 17:57 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +    }
@youngsuseo 
List names 생성자에서 List RacingCar 형태로 만들던가
List racingCars 자체를 받아오던가 둘중 하나로 통일 시키면 좋을것 같습니다.

2022-05-07 18:08 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/MovementCount.java
> +class MovementCount {
@youngsuseo 검증을 위해서만 추가된 부분이라 역할을 다른곳으로 옮기고 사용하지 않는것이 좋을것 같습니다.

momvementCount 에 대해서 꼭 검증을 하시고 싶다면
입력 받는 부분에서 처리 시켜 보는건 어떨까요 ?!

얘를들어 InputDataView 를 현재 유틸 형태로 사용하고 계시니까
RacingCar 전용의 InputView를 나누어 보는것은 어떨까요?

````
ppublic class InputView {
    public List<String> inputRacingCar() {
        String inputNames = InputDataView.scan("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
        return split(iputNames);
    }

    public int inputMovementCount() {
        int movementCount = InputDataView.scanNumber("시도할 회수는 몇 회 인가요?");

        // 검증 로직

        return movementCount;
    }
}
````

2022-05-07 18:21 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +        this.racingCars.set(index, racingCars.get(index).move());
@youngsuseo RacingCar를 반환하지 않고 그냥 내부에서 계산 시키는건 어떨까요?
postion의 불변 형태가 깨지지만 move 시 새로운 객체를 만들어 Position을 넘겨주면
부수효과를 줄여볼 수 있겠네요.

```
public class RacingPosition {
    private int position;
    
    public RacingPosition move() {
        return new RacingPosition(position + 1);
    }
}

public class RacingCar {
    private RacingPosition position;
   
    void move(MovingStrategy movingStrategy) {
        if (movingStrategy.checkCondition()) {
            position = position.move();
        }
    }
}
```

2022-05-08 08:37 UTC, youngsuseo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +        this.racingCars.set(index, racingCars.get(index).move());
지금과 같이 RacingPosition 클래스의 position 인스턴스변수는 불변을 사용하지 않는 대신 새로운 객체를 생성해서 리턴해주는데,
제가 최초에 코드를 작성했던 방식인 List를 순회하면서 set 메서드를 실행하는 것이 좋지 않아서 그런걸까요?

클래스를 생성할 때 인스턴스 변수의 무조건적인 불변화는 좋지 않은 것 같은데, 혹시 해당 인스턴스 변수의 불변화를 진행하는 기준이 있을까요?

2022-05-08 08:53 UTC, simjunbo approved these changes
마지막에 드린 피드백 까지 아주 잘 반영해 주셨습니다 👍 
각 단계별로 여러가지 고민을 하시면서 꾸준하게 리팩토링 해주신 덕분에
처음보다 객체들의 역할이 분명해 졌으며 구조도 많이 개선된 것 같습니다.

저와 함께한 시간이 조금이라도 도움이 되셨길 바라며
자동차 경주 미션 하시느라 고생하셨습니다.

2022-05-08 08:53 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCar.java
> +    void move(MovingStrategy movingStrategy) {
전략을 외부에서 주입받는 형태로 변경해 주셨네요 👍 
전략이 변경된다고 해도 고수준의 도메인 형태는 변경없이 사용 가능하겠네요.

2022-05-08 08:53 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +    public RacingCars(List<RacingCar> racingCars) {
RacingCars 에서 생성에 대한 역할을 분리해 주셔서
역할이 좀 더 명확해 진것 같습니다 👍

2022-05-08 08:53 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingPosition.java
> +    private int position;
move 시, RacingPosition을 새로 만들어 주고 계시니까 여기는 final 형태로 사용하실 수 있겠네요.

2022-05-08 08:53 UTC, simjunbo commented on src/main/java/racing_refactoring/util/RacingCarFactory.java
> +public class RacingCarFactory {
생성을 담당하는 Factory 형태로 잘 분리해 주셨습니다 👍

2022-05-08 08:53 UTC, merged

2022-05-08 14:12 UTC, youngsuseo commented
항상 좋은 리뷰 남겨주셔서 감사했습니다.
제가 현업에서 의문이 가던 것들 질문드려도 친절하게 답변주시고, 알려주시고 가이드 해주시는 부분들이 
이전에 생각하지 못한 것들을 한번 더 생각하고 고민할 수 있는 시간들을 가질 수 있게 해주셨습니다.
덕분에 많이 배울 수 있었습니다. 정말 감사했습니다!! 🙇‍♂️

2022-05-08 14:33 UTC, simjunbo commented on src/main/java/racing_refactoring/domain/RacingCars.java
> +        this.racingCars.set(index, racingCars.get(index).move());
@youngsuseo 피드백 드렸던 이유는 기존에 List 를 생성 후, List index 별로
값을 set 해주는 과정에서 실수 소지도 생길 수 있고 상태가 변경될 수 있다고 생각해서 입니다.

개인적으로 부수효과에 안전한 불변 객체를 사용하는것을 선호 하며
만약 성능적으로 이슈가 있다면 영향도를 고려해서 final을 사용하지 않는것도
고려해 볼 것 같습니다.

참고) https://velog.io/@conatuseus/Java-Immutable-Object%EB%B6%88%EB%B3%80%EA%B0%9D%EC%B2%B4