Step2 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #3459
Opened 2022-09-20 12:45 UTC by devcs96

리뷰 부탁드립니다, 감사합니다!

2022-09-21 00:25 UTC, seokhongkim requested changes
찬수님 안녕하세요!
자동차 경주 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다!

2단계 미션 잘 구현해주셨습니다. 👍 
고민해보시면 좋을 것 같은 부분에 대해 코멘트 조금 남겼으니 확인 부탁드립니다. 🙏

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    private static final Pattern pattern = Pattern.compile(("//(.)\n(.*)"));
pattern 을 미리 만들고 재사용하는 것 좋습니다. 👍

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    private static final int DEFAULT_VALUE = 0;
상수로 분리하고 이름을 정하신 것 좋습니다. 👍 
조금 더 구체적인 이름을 사용해보면 어떨까요?
`기본값` 보다는 `기본 결과 값` 혹은 `기본 반환 값` 을 나타낼 수 있다면 파라메터의 기본값인지, 반환값의 기본값인지 한 눈에 들어올 것 같아요!

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +            throw new IllegalArgumentException("input must be number", e);
적절한 예외 사용과 cause 를 함께 포함해주는 것 좋습니다. 👍

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    private static int throwExpIfMinus(int num) {
메소드명이 구현이 아닌 행위를 나타내도록 변경해보면 어떨까요? 그리고 행위를 하나만 하도록 변경하는 것도 좋겠습니다.
현재 이름을 보면 `값이 음수인 경우 예외를 던진다` 로 구현을 서술하는 것 같아요. `값이 양수인지 검증`하는 행위를 서술하는 이름은 어떨까요?
값을 검증한 후 반환하고 있는데, 검증만 하는 메소드라면 반환값이 없어도 괜찮지 않을까요?

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
하나의 클래스에서 두가지 역할을 하는데 각각의 역할을 별도의 클래스로 분리해보면 어떨까요?
1. 문자열을 받아서 숫자 배열로 파싱하는 역할
2. 숫자 배열의 덧셈 결과를 계산하는 역할

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    private static final String FIRST_DEFAULT_DELIMITER = ":";
구분자 각각을 상수로 분리하신 것도 좋지만, 항상 같이 사용되는 값이라면 현 시점에는 하나로 만들어 놓는 것이 사용할 때마다 문자열을 합치는 계산을 하지 않아도 되서 효율적일 것 같다는 생각도 드네요! :)

2022-09-21 00:25 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    private static boolean isInvalid(String input) {
밸리데이션 좋습니다. 👍

2022-09-21 11:27 UTC, devcs96 commented on src/test/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
좋은 피드백 감사합니다 ! :) 많이 배웠습니다!

2022-09-22 23:57 UTC, seokhongkim approved these changes
찬수님, 2단계 미션 피드백 잘 반영해주셨네요! 👍 
조금 더 역할을 분리할 수 있다고 생각되는 부분에 코멘트 남겼습니다.
다음 단계 미션을 하실 때 연습하고 학습하셔도 좋을 것 같아서, 2단계 PR은 머지하도록 하겠습니다.

3단계 미션에서 뵙겠습니다. 😀

2022-09-22 23:57 UTC, seokhongkim commented on src/test/java/calculator/StringAddCalculator.java
> +    public static int splitAndSum(String input) throws IllegalArgumentException {
여력이 되신다면 `split` 하는 로직도 `StringSplitter` 와 같은 클래스를 만들어서 역할을 분리해도 좋겠네요! :)

2022-09-22 23:57 UTC, seokhongkim commented on src/test/java/calculator/StringIntParser.java
> +    public static Integer mapToInt(String input) throws IllegalArgumentException{
사소한 부분이지만 코멘트 남깁니다.
1. `IllegalArgumentException` 을 발생시킨다는 것을 `throws` 키워드로 명시적으로 작성하신 이유가 있을까요?
2. `IllegalArgumentException` 와 `{` 사이에 공백이 빠졌네요!

2022-09-22 23:57 UTC, merged

2022-09-23 00:07 UTC, devcs96 commented on src/test/java/calculator/StringIntParser.java
> +    public static Integer mapToInt(String input) throws IllegalArgumentException{
안녕하세요!! 의도는 client 단에서 해당 method를 사용할때 IllegalArgumentException 이 발생할 수도 있음을 명시적으로 표현하고자 throws에 사용하였는데 ,
RuntimeException 에 대해 문서화할떄는 
1./** @throws */ 와 같이 주석으로 문서화하는게 좋은지 , 
2. throws 키워드로 표현하는게 좋은지 
3. RuntimeException이 아닌 CheckedException 으로 예외 처리를 강제해야 하는지 

어떤 방법을 선호하시는지 궁금합니다!

2022-09-23 11:36 UTC, seokhongkim commented on src/test/java/calculator/StringIntParser.java
> +    public static Integer mapToInt(String input) throws IllegalArgumentException{
저는 주로 웹 개발을 했고, RuntimeException 인 경우 아무것도 정리하지 않습니다.
다만, 특별히 발생할 수 있는 예외를 문서화 할 필요가 있는 경우에는 javadoc 의 throws 를 이용해서 문서화하는 경우도 있으나 거의 작성하지 않습니다.

이유는 아래와 같습니다.
1. 제가 명시한 예외 외에 다른 예외가 발생할 수 있는데, 모든 예외를 제가 알 수는 없습니다. 게다가 모든 코드의 변경을 추적하여 문서화를 할 수 없습니다. 예를 들어, `Integer.parseInt` 또는 `validatePositiveNumber` 에서 다른 예외가 발생하거나, 기존의 예외를 변경하는 경우 사용하는 곳에서 문서화가 되어 있음을 알고 변경해줘야 하는데, 저는 이렇게 할 수 없다고 생각했습니다.
2. 클라이언트에서 예외 처리가 반드시 필요하다면 checked exception 을 이용하여 알려주는 것도 방법이라고 생각합니다. 다만, 이 경우에는 예외를 받아서 처리할 수 있는 대안이 있는 경우라고 생각합니다. 그렇지 않고 클라이언트가 예외를 받아서 할 수 있는 것이 없다면, 불필요한 try-catch 사용만 강제하는 것이라고 생각합니다. 이와 관련해서는 java 와 비교해 상대적으로 최근에 나온 kotlin, scala, groovy 등의 언어에서 checked exception 을 사용하지 않는 이유를 찾아보셔도 좋을 것 같습니다.

그럼에도 라이브러리를 개발하거나, 유틸리티성 메소드에서 문서화를 통해 명시적으로 발생할 수 있는 예외를 알려주는 것은 다른 개발자에게 도움이 된다고 생각합니다. :)

2022-09-23 16:37 UTC, devcs96 commented on src/test/java/calculator/StringIntParser.java
> +    public static Integer mapToInt(String input) throws IllegalArgumentException{
말씀주신대로 예외 변경이 생길때마다 호출하는쪽에서 변경해주기가 힘들겠네요 , 좋은 의견 감사합니다 : )