Step2 : 문자열 덧셈 계산기
next-step/java-racingcar pull request #3591
Opened 2022-09-23 07:26 UTC by cyj199637

안녕하세요! (2단계 - 문자열 덧셈 계산기) 구현 완료했습니다~
리뷰 부탁드립니다🙌🏻🙌🏻

2022-09-24 08:01 UTC, lowoon requested changes
안녕하세요! 이번 미션 리뷰를 맞게된 이상보입니다.
간단한 코멘트 남겼으니 확인해주세요ㅎㅎ

궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-09-24 08:01 UTC, lowoon commented on src/test/java/calculator/StringAddCalculatorTest.java
> +        assertThat(splitAndSum(null)).isZero();
2가지의 assert구문이 있는 경우에는 assertAll을 사용하면 좋습니다
차이가 어떤게 있는지 찾아보시면 좋을것 같아요!

2022-09-25 16:48 UTC, cyj199637 commented on src/main/java/calculator/StringAddCalculator.java
> +        return value.split(SEPARATORS);
말씀하신 `계산하는 로직` 이 숫자가 아닌 구분자를 계산하는 로직을 말씀하시는 것이 맞을까요??

2022-09-25 16:49 UTC, cyj199637 commented on src/test/java/calculator/StringAddCalculatorTest.java
> +        assertThat(splitAndSum(null)).isZero();
오! 좋은 정보 감사드립니다:)

2022-09-25 16:56 UTC, cyj199637 commented on src/main/java/calculator/StringAddCalculator.java
> +        int result = 0;
미션 이름이 덧셈 계산기라 거기에만 너무 초점이 맞춰졌나 보네요!
다른 동작들도 한 번 구현해보도록 하겠습니다~

2022-09-26 23:25 UTC, lowoon commented on src/main/java/calculator/StringAddCalculator.java
> +        return value.split(SEPARATORS);
아뇨 input에 대해서 분리를 하는 것도 calculator에서 하고 있는데요.
input을 담당하는 클래스를 둬서 해당 클래서에서 분리를 하고 분리를 완료한 값만 calculator로 넘기게 되면 calculator에서는 계산만 하게되어서 역할이 분리될 수 있지 않을까 하고 말씀드린거였습니다!

2022-09-26 23:29 UTC, lowoon approved these changes
고생하셨어요! 리뷰 반영 잘 해주셨어요! 😄
2단계는 이만 머지하도록 하겠습니다. 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-09-26 23:29 UTC, lowoon commented on src/main/java/StringCalculatorApplication.java
> +        System.out.println("계산하고 싶은 문자열을 입력해 주세요.");
input과 ouput을 담당하는 클래스를 만들 수도 있을거 같아요
만약 나누게 된다면 view를 담당하는 input, output의 역할은 어디까지 일까요??
숫자로의 변환까지 일까요 아니면 string을 받는 것까지 일까요??
한번 고민해보시면 좋을것 같아요ㅎㅎ

2022-09-26 23:29 UTC, lowoon commented on src/main/java/calculator/StringCalculator.java
> +        if (isImpossibleToParse(input)) {
원시값 포장을 참고하면 좋을거 같아요

2022-09-26 23:29 UTC, lowoon commented on src/main/java/calculator/operator/Operator.java
> +    public abstract int execute(int x, int y);
연산자 👍 
내부 객체로 Function을 가질 수도 있을거 같아요

2022-09-26 23:29 UTC, lowoon commented on src/test/java/calculator/StringCalculatorTest.java
> +     assertAll() : 여러 assertion을 모두 실행한 후, 통과하지 못한 모든 assertion을 함께 화면에 출력해 줌
:100:

2022-09-26 23:29 UTC, lowoon commented on src/main/java/calculator/StringCalculator.java
> +        if (input == null || input.isEmpty()) {
null 체크의 경우 개인적으로 `Objects.isNull(input)`사용하기는 합니다

2022-09-26 23:29 UTC, merged