2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #3592
Opened 2022-09-23 08:06 UTC by 0chil

어제 온라인 강의에서 배웠던 내용들과 지난 번 리뷰 때 말씀해주셨던 테스트 네이밍 방법을 적용해보았습니다.

테스트를 얼마나 작은 단위까지 쪼개야할지 고민이 많았는데,
하위 메서드들은 `기능(TODO) 단위` 테스트로 충분히 테스트 할 수 있다고 판단이 들어 더 잘게 쪼개지는 않았습니다.

2022-09-23 15:41 UTC, choihz requested changes
안녕하세요, 성철님!

2단계 역시 잘 진행해 주셨네요 👍 피드백을 몇 가지 남겨 두었는데 확인해 주시고, 궁금한 점이나 의견이 있으실 땐 부담 없이 코멘트나 DM 주세요!

2022-09-23 15:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +			throw new RuntimeException("음수가 있습니다");
조건/반복문에는 중괄호를 반드시 사용하는 것이 좋습니다([참고](https://naver.github.io/hackday-conventions-java/#need-braces)).

2022-09-23 15:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +	}
그런데 원래 positive가 `0`도 포함하는 개념인가요?

2022-09-23 15:41 UTC, choihz commented on src/test/java/calculator/PositiveTest.java
> +	}
이건 테스트 이름이 내용을 제대로 설명하지 못하고 있는 것 같습니다. 테스트에서 무엇을 검증하고 있나요?

2022-09-23 15:41 UTC, choihz commented on src/test/java/calculator/PositiveTest.java
> +	}
만약 프로그램 내에서 실제로 예외가 발생한다면 클라이언트는 아래와 같은 메시지를 보게 될 거예요.

> java.lang.NumberFormatException: For input string: "a"

이걸 봐서는 예외의 원인과 맥락을 제대로 파악하기 어려울 것 같은데요, 어떻게 하면 좋을까요?

2022-09-23 15:41 UTC, choihz commented on src/test/java/calculator/StringCalculatorTest.java
> +		assertThat(stringCalculator.calculate(null)).isEqualTo(zero);
`null`과 빈 문자열은 다르지 않나요?

2022-09-23 15:41 UTC, choihz commented on src/main/java/calculator/StringCalculator.java
> +	}
메서드 이름은 보통 동사나 전치사로 시작하도록 합니다([참고](https://naver.github.io/hackday-conventions-java/#method-verb-preposition)).

2022-09-23 15:41 UTC, choihz commented on src/test/java/calculator/StringCalculatorTest.java
> +	}
이쯤에서 궁금한 점이 있어요. `Positive`라는 "값 객체"를 잘 사용하고 있으신데, 이런 방식의 단점은 느끼신 게 없을까요? 제가 보기에는, 이 테스트에서만 해도 그냥 숫자를 사용하면 간단할 것을 계속 `new Positive(n)` 하며 객체를 생성하고 있으니 장황하고 번거로워 보이기도 하거든요. 성철님의 경험과 의견은 어떠한지 여쭤보고 싶습니다 😎

2022-09-23 15:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +			throw new RuntimeException("음수가 있습니다");
`RuntimeException`을 직접 사용하기보다 커스텀 예외를 만들어 보는 건 어떨까요? 어떤 장점이 있을까요?

2022-09-24 02:21 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +			throw new RuntimeException("음수가 있습니다");
뭔가 추가하게 되거나, 해당 블럭이 어디론가 이동해도 형태가 유지될 확률이 더 높겠군요..!

2022-09-24 02:36 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +	}
사실 0을 포함하는 not negative를 의미하고 싶긴 했는데, 마땅한 이름을 찾지 못했습니다. 🥲

2022-09-24 04:29 UTC, 0chil commented on src/test/java/calculator/PositiveTest.java
> +	}
문자열 생성자에는 숫자만 들어가야 한다는 것을 검증하고 있어요.

아래와 같이 수정해봤습니다.
```java
        @DisplayName("문자열 생성자는 숫자만 허용한다")
	@Test
	void string_constructor_accepts_number_only() {
		assertThat(new Positive("7")).isEqualTo(new Positive(7));
		assertThatThrownBy(() -> new Positive("1a"))
			.isInstanceOf(RuntimeException.class);
	}
```

2022-09-24 06:26 UTC, 0chil commented on src/main/java/calculator/StringCalculator.java
> +	}
이 부분에 관해 희주님은 어떻게 생각하시는지 궁금합니다.

[시작하며 - 이름 짓기](https://edu.nextstep.camp/s/DVVUSLFe/ls/yD1TBIWo), 이 문서가 보이실 진 모르겠으나,
[Elegant Objects](http://www.yes24.com/Product/Goods/96193044) 의 작자인 Yegor가 쓴 내용 ([Builders and Manipulators](https://www.yegor256.com/2018/08/22/builders-and-manipulators.html))으로 알고 있습니다.
이 분의 글이 논란의 여지가 있고, 조금은 극단적이라고 생각하기도 하는데, 강의 문서에도 있으니 한번 적용해보았습니다.

`separator()`와 `expression()`은 괜찮았지만, `calculate()`는 builder도, manipulator도 아닌 무언가네요.
계산과 계산 결과 반환을 동시에 수행하는 코드가 아니라면, 상태를 저장해두었다가 따로 반환하게 될 것 같은데 좋은 구조라는 생각은 들지 않네요.
전에도 느꼈지만, Yegor가 쓴 글은 실제로 적용하려고 하면 잘 되지 않는 부분들이 있습니다.
그럼에도 공감되는 부분이 있어 시도해 보았으나, 맥락이 부족해서 이해하기 어려운 코드이기도 합니다.

[Objects with -er](https://www.yegor256.com/2015/03/09/objects-end-with-er.html), [Inheritance is procedural](https://www.yegor256.com/2016/09/13/inheritance-is-procedural.html) 등 또 다른 글들도 있는데, 공감은 되지만 실제 적용은 더 고민해봐야겠네요. 어떻게 생각하시나요?

2022-09-24 07:08 UTC, 0chil commented on src/test/java/calculator/StringCalculatorTest.java
> +	}
말씀하신 부분처럼 매번 `new Positive()`를 하는 부분을 포함해 `Positive`를 사용하는 코드가 번거롭고 장황하긴 합니다 🥲

제가 느끼는 장점은 "음이 아닌 정수"에 대한 책임은 `Positive`가 지고, 
계산기는 수식을 자르고, 계산만 책임 지는 점입니다.

그러나 리뷰를 읽고 단점도 느끼게 되었는데, 코드가 장황해지고, 번거로워 지는 점은 모두
잘 만들어진 Integer를 버리고, 그걸 감싸서 어디에도 호환되지 않는 클래스를 만들어 버렸기 때문이라는 판단이 듭니다 🤔
(Positive를 Integer 처럼 사용하려고 봤더니 `final` 클래스네요🤔)

공통의 인터페이스도 없고, 확장도 불가해서 이 정도면 제가 Java를 거스르려고 한다는 생각이 들었습니다😱
Positive는 처음부터 만들지 않는 편이 좋았을까요?
다행히 제거는 간단하니 제거해서 돌아가보겠습니다 😀

2022-09-24 07:38 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +			throw new RuntimeException("음수가 있습니다");
`RuntimeException`보다 더 명확한 예외가 있으면 좋겠네요.
커스텀 예외를 만들어 보겠습니다.

2022-09-24 08:26 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +@Deprecated
사용하지 않아 `@Deprecated` 처리 하였습니다.

2022-09-24 08:26 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +
생성자에 try-catch를 사용하기는 뭔가 거부감이 있어 팩토리 메서드를 사용했습니다.

2022-09-24 08:26 UTC, 0chil commented on src/main/java/calculator/StringCalculator.java
> +	}
수식 사이의 빈칸도 0 취급하도록 하였습니다.

2022-09-24 08:26 UTC, 0chil commented on src/test/java/calculator/PositiveTest.java
> +	}
기존 나누어져 있던 두 테스트를 하나로 합쳐 의도가 더 명확해지게 하였습니다.

2022-09-24 08:26 UTC, 0chil commented on src/test/java/calculator/StringCalculatorTest.java
> +		assertThat(stringCalculator.calculate(",1")).isOne();
수식 사이의 빈 문자열도 0 취급

2022-09-24 08:33 UTC, 0chil commented on src/main/java/calculator/StringCalculator.java
> +	}
`Integer.parseInt()`가 실패할 경우 커스텀 예외를 던지게 해 사용자가 문제를 더 쉽게 파악하게 되었습니다.

2022-09-24 08:49 UTC, 0chil commented on src/test/java/calculator/PositiveTest.java
> +	}
사용자가 "1,a,4"를 입력한 경우에 
> java.lang.NumberFormatException: For input string: "a"

이런 예외 메세지를 보게 된다면 "아, a가 문제구나!", "a의 형식이 문제구나!" 라고 알기 쉽지 않을까요?
커스텀 익셉션을 추가할 수 도 있겠지만, 이미 Java에도 충분히 좋은 예외 클래스들이 있다고 생각합니다.
한글이냐 아니냐의 차이일 뿐, 어디가 문제인지 짚어주지 않는 커스텀 예외보다 알기 쉬울 것이라고 생각합니다.

2022-09-24 08:57 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +	}
문자열 생성자를 만드는 점과 생성자에 try-catch를 사용하는 점에
거부감이 있어 의도를 더 잘 나타내고자 팩토리 메서드를 사용했습니다.

2022-09-24 17:41 UTC, choihz approved these changes
안녕하세요, 성철님!

피드백 반영해 주신 내용들을 전부 확인했습니다 👍 이번에 남긴 코멘트는 다음 단계를 진행하며 함께 보시면 될 것 같아서 머지하도록 할게요. 궁금한 점이나 의견이 있으실 땐 부담 없이 코멘트나 DM 주세요.

그럼 다음 단계에서 다시 뵈어요~ 👋

2022-09-24 17:41 UTC, choihz commented on src/test/java/calculator/PositiveTest.java
> +	}
엄밀히 말하면 양수만 가질 수 있는 것은 아니죠. 항상 경계가 되는 값들에 주의를 기울여야 해요! 테스트 코드에서도 이런 값들을 꼭 확인해 주는 것이 좋구요.

2022-09-24 17:41 UTC, choihz commented on src/test/java/calculator/PositiveTest.java
> +			.isInstanceOf(RuntimeException.class);
이제는 `RuntimeException` 하위의 더 구체적인 예외를 던지고 있기 때문에, 테스트 코드에서도 이를 확인하면 좋겠죠.

2022-09-24 17:41 UTC, choihz commented on src/test/java/calculator/PositiveTest.java
> +		assertThat(Positive.ofString("7")).isEqualTo(new Positive(7));
> 이건 테스트 이름이 내용을 제대로 설명하지 못하고 있는 것 같습니다. 테스트에서 무엇을 검증하고 있나요?

이전에 위와 같은 코멘트를 남겼는데, 당시 코드는 아래와 같았죠.

```java
assertThat(new Positive("7")).isEqualTo(new Positive(7));
```

위 코드는 `new` 키워드를 통해 분명히 다른 인스턴스를 두 개 생성했는데도, `Positive`에서는 이 두 인스턴스를 같은 것으로 취급한다는 의미입니다. 지금도 팩터리 메서드를 사용하여 형식만 달라졌을 뿐 사실은 동일하구요. 그래서 이 검증문은 현재의 테스트 이름이 요구하는(?) 검증과는 결이 살짝 다르다고 느껴집니다.

혹시 이해하기 다소 어렵다면, 동일성과 동등성의 개념에 관해 학습해 보세요!

2022-09-24 17:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +			throw new NumberFormatException("숫자가 아닌 문자가 있습니다");
> 사용자가 "1,a,4"를 입력한 경우에 
> > java.lang.NumberFormatException: For input string: "a"
> 
> 이런 예외 메세지를 보게 된다면 "아, a가 문제구나!", "a의 형식이 문제구나!" 라고 알기 쉽지 않을까요?
> 커스텀 익셉션을 추가할 수 도 있겠지만, 이미 Java에도 충분히 좋은 예외 클래스들이 있다고 생각합니다.
> 한글이냐 아니냐의 차이일 뿐, 어디가 문제인지 짚어주지 않는 커스텀 예외보다 알기 쉬울 것이라고 생각합니다.

이미 제가 의도한 대로 잘 수정해 주셨네요?! 😮

만약 인용한 것처럼 `java.lang.NumberFormatException: For input string: "a"` 같은 메시지를 보게 되면, 말씀하신 것처럼 사용자는 '아, 여기는 a가 들어갈 수 없구나'라고 생각할 수 있을 거예요. 그런데 그렇다면 뭐가 들어가야 하죠? b? c? 숫자? 특수문자?

기존의 메시지는 이렇듯 지금 입력한 문자가 잘못되었음은 알리고 있지만, 그래서 무엇을 입력해야 하는지는 알려 주지 못하고 있었죠. 어떤 웹사이트에 회원가입을 하려고 비밀번호를 입력했는데, 계속 비밀번호의 형식이 잘못되었다는 메시지만 노출하는 경우를 떠올려 보면 좀 비슷하지 않을까요? 😣

2022-09-24 17:41 UTC, choihz commented on src/main/java/calculator/StringCalculator.java
> +	private String parseExpression(String input) {
> 이 부분에 관해 희주님은 어떻게 생각하시는지 궁금합니다.
> 
> [시작하며 - 이름 짓기](https://edu.nextstep.camp/s/DVVUSLFe/ls/yD1TBIWo), 이 문서가 보이실 진 모르겠으나,
> [Elegant Objects](http://www.yes24.com/Product/Goods/96193044) 의 작자인 Yegor가 쓴 내용 ([Builders and Manipulators](https://www.yegor256.com/2018/08/22/builders-and-manipulators.html))으로 알고 있습니다.
> 이 분의 글이 논란의 여지가 있고, 조금은 극단적이라고 생각하기도 하는데, 강의 문서에도 있으니 한번 적용해보았습니다.
> 
> `separator()`와 `expression()`은 괜찮았지만, `calculate()`는 builder도, manipulator도 아닌 무언가네요.
> 계산과 계산 결과 반환을 동시에 수행하는 코드가 아니라면, 상태를 저장해두었다가 따로 반환하게 될 것 같은데 좋은 구조라는 생각은 들지 않네요.
> 전에도 느꼈지만, Yegor가 쓴 글은 실제로 적용하려고 하면 잘 되지 않는 부분들이 있습니다.
> 그럼에도 공감되는 부분이 있어 시도해 보았으나, 맥락이 부족해서 이해하기 어려운 코드이기도 합니다.
> 
> [Objects with -er](https://www.yegor256.com/2015/03/09/objects-end-with-er.html), [Inheritance is procedural](https://www.yegor256.com/2016/09/13/inheritance-is-procedural.html) 등 또 다른 글들도 있는데, 공감은 되지만 실제 적용은 더 고민해봐야겠네요. 어떻게 생각하시나요?

앗 강의 자료에 저 내용이 있는 것은 이제 보았네요!

『엘레강트 오브젝트』는 저도 예전에 읽긴 했는데, 저 같은 경우는 '이런 방법도 있구나. 그런데 이게 진짜 되나?' 정도의 감상이었던 것 같아요. 말씀하신 것처럼, 책의 내용은 실제로 온전히 적용하기에는 어려운 부분이 많죠.

그리고 결정적으로 저 책을 모든 개발자들이 읽은 것도 아니고, 읽었다고 해도 모든 내용에 동의하여 따르자고 하는 사람도 별로 없을 것 같아요. 그렇기 때문에 보통의, "일반적으로 합의된" 규칙을 따르는 것이 좋겠다는 의미로 코멘트를 남겼었어요. 만약 어떤 팀이 프로젝트를 하는데 팀원들이 서로 독특한 규칙을 지키기로 합의했다면 다른 일반적인 내용은 의미가 없어질 수도 있겠죠. 정답이 있는 것은 아니니까요. 그렇기 때문에 더더욱, 일방적으로 리뷰어의 의견을 받아들이기보다 이렇게 의견을 나누는 것이 너무나 좋다고 생각합니다 😊

2022-09-24 17:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +public class Positive {
> 공통의 인터페이스도 없고, 확장도 불가해서 이 정도면 제가 Java를 거스르려고 한다는 생각이 들었습니다 😱
> Positive는 처음부터 만들지 않는 편이 좋았을까요?
> 다행히 제거는 간단하니 제거해서 돌아가보겠습니다 😀

절대 절대 그렇지는 않습니다!! 저는 다른 관점에서도 생각해 보시라는 의미에서 코멘트를 남겼던 거예요.

말씀하신 것처럼 값 객체를 사용하는 이점이 분명히 존재합니다. 하지만 그에 따라오는 단점도 이해해야 장단점을 비교하여 바른 의사결정을 내릴 수 있을 것이라고 생각했는데요, 이건 정말 모든 상황에서 마찬가지이겠지요.

또한 저희는 지금 일이 아니라 학습을 하고 있으니, 맞고 틀리고를 생각하기보다 최대한 다양한 시도를 해보는 것이 몹시 중요하지 않을까요?

2022-09-24 17:41 UTC, choihz commented on src/main/java/calculator/Positive.java
> +			throw new NegativeException();
> 메시지+Exception 이름으로 의도를 더 명확하게 전달할 수 있겠네요.

말씀하신 장점도 있구요. `RuntimeException`은 최상위 예외이기 때문에 이걸 코드에서 바로 사용하면 예상치 못한 상황이 발생할 수도 있어요. 프레임워크나 라이브러리 등에 이미 `RuntimeException`을 방어하는 코드가 있을 수도 있겠죠.

또한 예외는 계층 구조를 따르기 때문에, 이를 잘 설계하면 예외 상황을 효과적으로 처리할 수도 있어요. 이건 나중에 조금 더 복잡한 과제를 할 때 더 잘 드러날 것 같네요! 🙂

2022-09-24 17:41 UTC, choihz commented on src/main/java/calculator/exception/NegativeException.java
> +public class NegativeException extends NumberException {
[리뷰 반영](https://github.com/next-step/java-racingcar/pull/3592/commits/caac0831b621fbe5e503ed83402693ef0effa7bc)이라는 메시지로 여러 작업을 한번에 반영해 주셨는데요, 이렇게 하기보다 각각의 작업을 따로 커밋하는 편을 더 권장합니다.

2022-09-24 17:42 UTC, merged

2022-09-24 17:57 UTC, 0chil commented on src/test/java/calculator/PositiveTest.java
> +		assertThat(Positive.ofString("7")).isEqualTo(new Positive(7));
앗..! 이제 감이 오네요! 사실은 리팩터링 중 `@Deprecated`로 처리하고 놓친 부분인데 이것도 적용해보겠습니다!

2022-09-24 17:58 UTC, 0chil commented on src/main/java/calculator/StringCalculator.java
> +	private String parseExpression(String input) {
> 결정적으로 저 책을 모든 개발자들이 읽은 것도 아니고, 읽었다고 해도 모든 내용에 동의하여 따르자고 하는 사람도 별로 없을 것 같아요.

이 말이 되게 와 닿네요. 그렇다고 Yegor의 말이 정답인 것도 아니죠! 팀원들이 동의할 수 있는 코드를 만드는 것도 되게 중요할 것 같습니다.
그래도 이런 시도를 해보고 경험을 얻어놓으면 다음에 더 좋은 방법도 보일 수 있겠죠! 좋은 의견 나눠주셔서 감사합니다 😀

2022-09-24 18:02 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +public class Positive {
다음번엔 좀 더 재밌고 의미있는 값 객체 포장으로 만들어보겠습니다!

2022-09-24 18:03 UTC, 0chil commented on src/main/java/calculator/Positive.java
> +			throw new NegativeException();
그렇군요. 거기까지는 생각해보지 못했네요. 과제를 하면서 느껴봤으면 좋겠습니다. 리뷰 감사합니다!