Step3 리뷰 요청드립니다
next-step/java-racingcar pull request #3631
Opened 2022-09-24 15:57 UTC by runnz121

각 클래스의 내부 메서드를 private으로 접근제한하여 public으로 열려있는 메소드만 테스트 해보았습니다.

2022-09-25 04:19 UTC, ep1stas1s requested changes
미션 잘 구현해주셨네요 👍 
몇가지 코멘트를 남겼는데 참고해서 리팩토링 진행해보시길 바랍니다ㅎㅎ
궁금한 점 있으시면 언제든 DM주세요~!

2022-09-25 04:19 UTC, ep1stas1s commented on src/main/java/InputReview.java
> +    private int attempts;
위 코멘트와 유사한데, UI가 변경되었을 때 변경을 최소화하려면 어떻게 할지 고민해보시면 좋을 것 같습니다 :)

2022-09-25 04:19 UTC, ep1stas1s commented on src/main/java/InputReview.java
> +        if (this.cars < 0) throw new NotPositiveNumberException("양수만 입력하세요");
```suggestion
        if (this.cars < 0) {
            throw new NotPositiveNumberException("양수만 입력하세요");
        }
```
중괄호를 생략할 때, 자잘한 실수가 발생할 수 있으니, 항상 중괄호를 사용하시는걸 추천드립니다ㅎㅎ

2022-09-25 04:19 UTC, ep1stas1s commented on src/main/java/CarPlay.java
> +public class CarPlay {
CarPlay의 역할이 많아보이는데 조금 나눠보는건 어떨까요~?
처음에 적응이 힘들땐, 번거롭더라도 최소 단위 기능부터 구현해보시면 도움이 되실것 같은데요

기능 요구사항을 봤을 때, 핵심로직중 가장 작은 기능은 아래 조건일것 같아요
> 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.

그럼 우선 자동차에 해당하는 클래스를 만들고, 랜덤한 숫자와 4이상인걸 판별하는 메서드를 구현 및 테스트를 해볼 수 있겠네요
원하는 대로 구현 및 테스트가 완료되면, 그 결과에 따라 차가 이동하는 메서드를 만들고 테스트해볼 수 있을 거에요.
이 과정에서 public이었던 메서드가 private으로 변경될 수도 있을거에요...ㅎㅎ 적응하는 기간이니 해보다보면 조금 더 각(?)이 보이지 않을까싶습니다ㅎㅎ
이런 식으로 점차 넓혀가면서 도메인(핵심로직)을 구현해가보시는 걸 조심스럽게 추천드려봅니다...ㅎㅎ

2022-09-25 04:19 UTC, ep1stas1s commented on src/main/java/CarPlay.java
> +    private boolean addMoveCount() {
메서드명이 add로 시작하는데 boolean을 반환하는게 조금 어색하네요 😅

2022-09-25 04:19 UTC, ep1stas1s commented on src/test/java/CarPlayTest.java
> +    private static int attempts;
static으로 사용하신 이유가 있으실까요~?

2022-09-25 15:49 UTC, ep1stas1s requested changes
역할을 나눠서 리팩토링 진행해보시면 좋을 것 같아서 몇가지 코멘트 더 남겼습니다...ㅎㅎ
한 번 참고해보시고 궁금한 점 있으시면 언제든 DM주세요~!

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/service/InputReview.java
> +public class InputReview {
```suggestion
public class InputView {
```
오타가 있네요 :)

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/service/InputReview.java
> +    private Car car;
InputView에서 Car를 알아야할까요? 그리고 상태를 가지는 게 맞을까요?
InputView는 입력을 받는 역할만 수행하도록 변경해보시면 좋을 것 같습니다~!

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/service/InputReview.java
> +        car.setCars(inputNumber);
사이드 이팩트를 줄이기위해 setter는 지양하는 편인데요
클린코드 과정중에 아예 안쓰는 연습을 해보시면 좋을 것 같습니다ㅎㅎ

예를 들어 Car 생성에 필요한 값을 다 입력 받은 후에 생성자를 통해 만들면 될 것 같아요

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    public Car() {
다른 생성자가 없다면, 기본 생성자는 자동으로 생성되어 생략 가능합니다

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    private int attempts;
Car와 CarPlay의 역할이 조오금 애매하네요...ㅎㅎ
이름만 봐서는 Car는 각 자동차 마다의 상태를 가지고, CarPlay는 이러한 여러 개의 자동차를 이동시키는 역할을 할 것만 같은데요
지금은 Car가 이러한 상태값들을 전부 들고 있네요

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    private int cars;
특히 Car가 cars라는 필드를 가지는게 어색하네요...!
만약 Car가 하나의 자동차를 의미한다면, 얼만큼 이동했는지를 의미하는 필드를 가지면 어떨까요??

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    public List<Integer> renewedCarList() {
마찬가지로 하나의 자동차를 의미한다면 해당 메서드가 여기 위치하는 것이 맞나 고민이 필요합니다
(입력받은 값을 통해 일급컬렉션을 적용해보셔도 좋을 것 같습니다)

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/service/InputReview.java
> +            throw new NotPositiveNumberException("양수만 입력하세요");
```suggestion
        if (inputNumber < 0) {
            throw new NotPositiveNumberException("양수만 입력하세요");
        }
```

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/service/ResultView.java
> +public class ResultView {
View에서 많은 도메인 로직을 가지고 있네요...!
결과를 출력하는 view 역시, 결과를 출력하는 역할만 수행하도록 변경해보시면 좋을 것 같습니다ㅎㅎ

2022-09-25 15:49 UTC, ep1stas1s commented on src/test/java/CarPlayTest.java
> +    void checkReturnBiggerThanFour(int input) {
true를 반환하는 경우와 false를 반환하는 테스트를 나눠서 진행해보시면 더 명확하겠네요~!

2022-09-25 15:49 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    public boolean isMovingForward(int randomNumber) {
값을 주입받으면서 테스트가 가능해졌네요 👍 
다만 해당 메서드는 클래스 내부에서만 사용하는데 public일지는 고민이 필요해보입니다

2022-09-26 14:10 UTC, runnz121 commented on src/main/java/step3/domain/Car.java
> +    public Car() {
테스트동작시 기본생성자가 없으면 테스트가 동작하지않아 작성하였습니다

2022-09-26 14:12 UTC, runnz121 commented on src/main/java/step3/service/ResultView.java
> +public class ResultView {
최종출력 로직만 남겨놓고 변환하는 로직을 carplay클래스로 옮겼습니다

2022-09-26 14:12 UTC, runnz121 commented on src/test/java/CarPlayTest.java
> +    void checkReturnBiggerThanFour(int input) {
if 문으로 true, false가 기대되는 값을 나누어 테스트 하였습니다

2022-09-26 23:00 UTC, ep1stas1s approved these changes
리팩토링 진행하시느라 고생 많으셨습니다 👍 
코멘트 추가로 남긴 게 있는데 참고해서 다음 스텝에서 반영해주시면 좋을 것 같아요!
질문 있으시면 언제든 DM주세요!!

2022-09-26 23:00 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    private int currentStatus;
status라는 단어가 모호한 것 같네요
이동한 거리, 위치같은 느낌의 단어는 어떨까요?

2022-09-26 23:00 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    public Car carAction() {
구조가 변경되고 랜덤한 요소를 메서드 내부에서 생성하다보니, 테스트가 불가능한 구조가 되었네요 😢 
랜덤한 요소는 외부에서 주입받고, 
Car 클래스에서는 매개변수로 넘겨받은 값을 기반으로 이동할지, 말지를 선택하는 방향으로 구현해주시면 테스트가 용이할 것 같습니다!

2022-09-26 23:00 UTC, ep1stas1s commented on src/main/java/step3/service/CarPlay.java
> +            for (int j = 0; j < updateCarList.get(i).getCurrentStatus(); j++) {
2depth인 메서드가 있네요!

2022-09-26 23:00 UTC, ep1stas1s commented on src/main/java/step3/service/CarPlay.java
> +    public CarPlay(InputView inputView) {
CarPlay가 도메인(핵심로직)으로 보이는데, view에 해당하는 클래스를 들고 있네요
입력받은 값이 필요하다면, UI환경에 따른 변경을 최소화하기 위해, 특정 값만 전달받는 게 어떨까 싶습니다ㅎㅎ

2022-09-26 23:00 UTC, ep1stas1s commented on src/main/java/step3/service/CarPlay.java
> +    public void convertCarStatusToPrint(InputView inputView) {
View의 역할로 보이는데 ResultView에서 자동차 객체를 받아 출력해주는 건 어떨까요?

2022-09-26 23:02 UTC, ep1stas1s commented on src/test/java/CarPlayTest.java
> +    void checkReturnBiggerThanFour(int input) {
true값만 반환하는 테스트와 false값만 반환하는 테스트를
아예 따로 메서드를 만들어서 진행해보시라는 의도였습니다ㅎㅎ
나눠져 있으면 다른 개발자가 더 읽기 좋을 것 같아서요~

2022-09-26 23:02 UTC, ep1stas1s commented on src/main/java/step3/domain/Car.java
> +    public Car() {
엇 혹시 어느 테스트가 동작하지 않던가요...?

2022-09-26 23:33 UTC, merged