3단계 : 자전거 경주 리뷰 요청
next-step/java-racingcar pull request #3632
Opened 2022-09-24 15:59 UTC by JIWON0813

3단계 리뷰 요청합니다!

구현을 했는데 생각보다 테스트 코드가 많지 않아 어떤 걸 더 구현해야 할지 모르겠습니다...

추가로 각 클래스에서 구현하는 메서드의 역할이 맞는지도 좀 헷갈렸습니다

2022-09-24 17:15 UTC, KIMSIYOUNG requested changes
안녕하세요.
미션 잘 구현해주신 것 같아요.
몇가지 코멘트 드렸는데 고민해보시고 접근이 어려우시다면 디엠이나 코멘트 주세요!

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Car.java
> +    public int currentPosition(){
getter와 어떤게 다른건가요?

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Car.java
> +        this.position += RacingCar.move();
RacingCar.move()를 보지 않았는데 직관적으로 이해되지 않는 것 같아요. 자동차가(Car) 움직이는데 RacingCar 클래스의 static move를 사용해야하는 이유가 있나요?

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(result).isBetween(0, 9);
해당 테스트가 랜덤을 테스트하고 있나요?

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(result).isBetween(0, 1);
마찬가지로 해당 테스트가 이동여부를 테스트하나요? 항상 움직이거나 움직이지 않아도 동작하는 테스트 아닌가요?

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCar.java
> +    public static int move() {
자동차가 갈지말지 결정하는건 자동차의 역할에 가까워보여요.

2022-09-24 17:15 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +public class RacingCarTest {
프로그램에서 발생할 수 있는 동작은 테스트해주신 것보다 훨씬 다양한 것 같아요. 작은 프로그램이니 발생가능한 대부분의 동작을 모두 테스트해보려고 하신다면 구현도 달라질 것 같습니다.

2022-09-25 06:26 UTC, JIWON0813 commented on src/main/java/RacingCar/Car.java
> +    int name;
접근제어자 추가해 수정했습니다~

2022-09-25 06:26 UTC, JIWON0813 commented on src/main/java/RacingCar/Car.java
> +    public int currentPosition(){
getter와 같은 역할인데 네이밍이 현재 포지션이 더 맞는거같아 고민하다가 위와같은 네이밍으로 했습니다 그냥 getter가 맞는 것 같아 변경했습니다

2022-09-25 06:26 UTC, JIWON0813 commented on src/main/java/RacingCar/Car.java
> +        this.position += RacingCar.move();
RacingCar.move 의 역할이 맞지않에 Car 의 move로 로직을 합쳤습니다!

2022-09-25 06:28 UTC, JIWON0813 commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(result).isBetween(0, 9);
System에 관련된 테스트가 필요없어보여 제거했습니다!

2022-09-25 06:28 UTC, JIWON0813 commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(result).isBetween(0, 1);
position으로 확인하는걸로 변경했습니다!

2022-09-25 06:28 UTC, JIWON0813 commented on src/main/java/RacingCar/RacingCar.java
> +    public static int move() {
Car move 역할로 변경했습니다~

2022-09-25 06:34 UTC, JIWON0813 commented on src/test/java/RacingCar/RacingCarTest.java
> +public class RacingCarTest {
피드백 반영해서 정리를 하고보니 오히려 테스트가 더 없어져서 어떤 테스트를 넣어야할지 모르겠습니다

메소드 단위로 나눠보면

racing
 - round <- 내부 move메서드 호출이므로 move 테스트
  - move <- 테스트 구현 완료
 - roundResult <- View로직은 테스트 제외

initCar
초기화해서 개수를 확인하려고했지만 carList는 해당 프로그램에서 한번 선언되고 값만 따로 쓰여 
private static final로 지정한 후 사용하고 있어서 test코드에서 호출을 따로 할 수가 없습니다
test코드에서 자동차의 개수가 제대로 만들어 졌는지를 확인하기 위해 접근제어자를 변경하거나 getter를 만드는게 맞지 않다고 판단되는데 어떤 방식으로 진행하면 될까요?

scan
관련 scan로직들은 모두 System.in 기능이기 때문에 테스트코드 제외

위와 같이 정리하다보니 어떤 테스트 코드를 더 짜야할지 모르겠습니다....

2022-09-26 15:57 UTC, KIMSIYOUNG requested changes
안녕하세요.
조금 더 상세하게 피드백드렸는데 혹시 감이 잘 안오신다면 디엠 부탁드립니다!
같이 이야기하면서 구현해보면 좋을 것 같습니다.
그리고 현재 3개의 테스트가 깨지는데요. PR보내기전엔 항상 만들어주신 프로그램이 정상동작하는지를 확인하시고 보내주시면 좋을것 같습니다.

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(car.getPosition()).isBetween(0, 1);
요 부분은 반영이 안된건가요? 전 리뷰에서 처럼 자동차가 가든 안가든 항상 통과하는 테스트아닌가요?

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +public class RacingCarTest {
음 넵넵! 조금 더 구체적으로 각 클래스별로 코멘트 달아두겠습니당! 테스트를 위해 public 으로 변경하는 것은 지양해주세요! 필요에 따라 getter 정도는 열어도 괜찮다고 생각합니다🙂

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCar.java
> +        return scanner.nextInt();
사용자는 어떠한 것도 입력할 수 있습니다. 모든 예외에 대해서 처리할 필요는 없지만 사용자가 입력한 값을 변환하는 과정에 발생하는 예외들도 방어하고 테스트로 구현해야하지 않을까요?

1. 숫자를 입력하지 않은 경우 
2. 부적절한 숫자를 입력한 경우 등

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCar.java
> +        return scanner.nextInt();
추가로 현재의 구조에서는 이를 방어하더라도 메인에서 직접 호출하고 있기 때문에 테스트할 수 없습니다. 말씀하신대로 실제 코드에서는 private으로 사용할 수 있는데 테스트를 위해서 public으로 열어야할 것 같아요. 

이를 해결할 수 있는 방법이 public으로 변경하는 것 이외에도 객체를 분리하는 것도 방법이 될 수 있을 것 같아요. 이를 담당하는 객체들을 둘 수도 있겠죠?  기존에 구현하던 방식과 다르게 구현하는 것을 고민해보는 계기가 되면 좋을 것 같습니다.

입력을 받는 부분과 입력받은 값을 우리 프로그램에 맞게 변환하는 것은 분리되어야 할 것 같아요🙂

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCar.java
> +public class RacingCar {
최대한 객체로 분리하여서 더 작은 단위로 기능들을 분리하다보면 테스트하기가 용이하실 것 같습니다. 아래 말씀드린 내용들을 테스트 해주시면 좋을 것 같아요.

1. 사용자가 숫자가 아닌 타입을 입력한 경우
2. 0이하의 숫자를 입력한 경우
3. 4이상의 값이 주어지면 자동차가 움직인다에 대한 테스트
4. 4미만의 값이 주어지면 자동차가 움직이지 않는다에 대한 테스트

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/InputView.java
> +        System.out.println("자동차 대수는 몇 대 인가요?");
인풋뷰에서 노출만하지 않고 입력을 받아오는 것 까지 담당하면 좋을 것 같아요.

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Car.java
> +    private int position;
자동차의 초기 위치는 정해져있기 때문에 생성자에 포함되지 않아도 될 것 같아요.

2022-09-26 15:57 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Car.java
> +        if (result >= 4) {
4라는 숫자가 우리 프로그램에서 어떤 값인지 상수로 표현해주시면 좋을 것 같아요.

2022-09-27 17:27 UTC, JIWON0813 commented on src/test/java/RacingCar/RacingCarTest.java
> +public class RacingCarTest {
감사합니다! 피드백을 보고 기존에 구현하던 방식과는 다른 방식으로 생각해보고 재구현했습니다.
 전체적으로 구조 자체를 많이 변경했습니다. 테스트코드는 억지로 예외처리를 날리는 2개 테스트가있어 해당 테스트는 실패로 떨어지고 나머지는 성공하는 것 확인했습니다. 리뷰 부탁드립니다~

2022-09-28 14:02 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰 반영 잘 해주셨네요!
미션은 여기서 머지하도록 하겠습니다.
몇가지 코멘트 추가로 드렸는데, 편하게 반영해보시고 어려운 부분이 있다면 말씀주세요!

2022-09-28 14:02 UTC, KIMSIYOUNG commented on src/test/java/RacingCar/RacingCarTest.java
> +        assertThat(racing.getCarList().size()).isEqualTo(3);
조금만 더 나아가서 Cars에서 난수를 생성하지 않고 메인에서 난수를 생성하여 전달한다면 Cars에 있는 다른 메소드도 테스트할 수 있을 것 같습니다. (모든 차들이 이동했는지 등)

구현하는 방법은 외부에서 난수생성기를 Cars에게 전달하거나, 생성된 난수리스트를 전달하는 방법이 있을 것 같아요.

2022-09-28 14:02 UTC, merged