🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #3679
Opened 2022-09-26 13:19 UTC by min16

2022-09-26 13:32 UTC, min16 commented on src/main/java/racing/Car.java
> +        return distance;
사실 Car#distance도 private으로 해야하는데, 테스트 코드를 작성하려고 public으로 했어요.
하지만 테스트 작성을 위해 production 코드를 수정하는건 맞다고 생각하지 않아서, private가 맞는 것 같습니다. (그렇다면 Car 테스트는 무엇을 해야할지 모르겠어요..)

2022-09-27 10:48 UTC, ddaaac requested changes
안녕하세요 민지님 👋 

요구사항들을 만족시키려는 노력이 보이는 PR이었습니다 👍 
지금하고 계신 고민들도 너무 좋은 고민인 것 같아요.

남겨주신 질문에 대한 대답과 코멘트를 남겨놨으니 확인해주시고 다시 리뷰 요청 주세요~

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/Car.java
> +        ResultView.printDistance(distance());
[MVC 패턴](https://tecoble.techcourse.co.kr/post/2021-04-26-mvc/)에 대해서 학습해보고 Model이 다른 컴포넌트를 알지 못하도록 코드를 살짝 수정해보면 좋을 것 같아요! 
+) 요구사항 중에 UI 로직을 제외하고 테스트 코드를 작성해보라는 항목이 있는데, MVC 중 모델 컴포넌트에 대해서만 테스트 코드를 작성해보시면 될 것 같습니다.

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/Car.java
> +    }
일반적으로 클래스는 상수 - 필드 - 생성자 - 메서드 - getter/setter 등등의 순서로 작성합니다.
또 각 구성요소 사이에는 개행을 넣으면 조금 더 읽기 좋은 코드가 될 것 같네요 😄

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/Car.java
> +        return distance;
이 부분은 getter 이군요. getter라면 getXX라는 네이밍을 사용해주는 게 좋을 것 같습니다.

저는 이번 미션 같은 경우에 getter가 꼭 필요하다고 생각해요.
1. 매 라운드마다 자동차의 위치를 출력해야합니다. 이 때 distance 값을 알아야 출력할 수 있겠죠. -> 이처럼 내부 상태가 다른 로직에 쓰이는 것이 아닌 단순 데이터로 쓰일 때는 getter를 사용해도 괜찮다고 생각해요.
2. 말씀해주신대로 테스트할 때 필요합니다. 이 것도 1번과 마찬가지로 Car를 테스트하기 위해 데이터를 사용하는 거라고 생각해서 괜찮다는 생각이 드네요.

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/CarRacing.java
> +    private int rounds = 0;
- [불변 객체](https://tecoble.techcourse.co.kr/post/2020-05-18-immutable-object/)에 어떤 장점이 있을지 생각해 보시면 좋을 것 같아요.
- rounds가 불변이 될 수 없다면 그 이유에 대해 한 번쯤 생각해 볼 수 있을 거 같아요. rounds가 인스턴스 변수일 필요가 있을까요? 지역 변수로도 충분하지 않을까요?

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/CarRacing.java
> +    private static final String RESULT_TITLE = "실행 결과";
출력에 관련된 문구들이네요. View에 위치하는게 적절해보여요.

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/CarRacing.java
> +        for (int i = 1; i <= rounds; i++) {
"실행 결과"라는 문구는 여기서 출력해도 될 것 같습니다 😄

2022-09-27 10:48 UTC, ddaaac commented on src/main/java/racing/ResultView.java
> +    }
[java에서 여러 String을 결합하는 방식](https://baeldung-cn.com/java-multiline-string)에는 여러 방식이 있는데요, 링크의 글을 읽어보고 각 방식들의 장단점에 대해 학습해보시면 좋을 것 같아요!

2022-09-27 10:48 UTC, ddaaac commented on src/test/java/study/CarTest.java
> +        assertThat(car.distance()).isIn(0, 1);
이 부분을 작성하시면서 아마 의문점이 많으셨을 거라고 생각이 들어요 😄 
아마 다음 수업시간에 다룰 내용일테니 일단 이 부분은 넘어가주셔도 될 것 같습니다.

2022-09-27 10:48 UTC, ddaaac commented on src/test/java/study/CarRacingTest.java
> +public class CarRacingTest {
여기 테스트에 대해서는 우선 MVC 패턴을 나눠보고 다시 얘기해보는 게 좋을 것 같아요.
수정할 수 있는 데까지 수정해주시고, 여러 고민이 드시면 지금처럼 일단 작성한 부분까지 PR 보내주시면 될 것 같습니다!

2022-09-27 10:50 UTC, ddaaac commented on src/test/java/study/CarTest.java
> +package study;
테스트가 위치한 패키지 한 번 확인해주세요 😄

2022-09-27 13:19 UTC, min16 commented on src/main/java/racing/Car.java
> +        return distance;
> 1. 매 라운드마다 자동차의 위치를 출력해야합니다. 이 때 distance 값을 알아야 출력할 수 있겠죠. -> 이처럼 내부 상태가 다른 로직에 쓰이는 것이 아닌 단순 데이터로 쓰일 때는 getter를 사용해도 괜찮다고 생각해요.

- 제가 짠 구조에선 자동차 위치 출력도 Car에서 하기 때문에 distance를 private로 두려고 했는데, Car에서는 위치 정보만 알려주고 출력은 다른 곳에서 한다면, 말씀하신대로 getter를 제공하는게 맞다고 생각합니다.
- getter는 일반적으로 getXX를 사용하나요? 지금처럼 distance() 로는 잘 안 짓나요? 

> 2. 말씀해주신대로 테스트할 때 필요합니다. 이 것도 1번과 마찬가지로 Car를 테스트하기 위해 데이터를 사용하는 거라고 생각해서 괜찮다는 생각이 드네요.

- 만약 production code에서는 위치 정보를 제공 안해도 된다면, 오로지 테스트할 때만 필요하다면, 테스트를 위해서라도 public으로 제공하는게 맞다고 생각하는지 궁금합니다. (이것에 대한 제 주관이 뚜렷한 건 아닌데, 현재는 부정에 가깝습니다.  [위 코멘트](https://github.com/next-step/java-racingcar/pull/3679#discussion_r980042144)처럼요)
-  한편으로 테스트하기 어려운 환경(지금처럼 테스트만을 위해 public으로 둬야하는 상황)이면 설계 구조에 문제가 있는건 아닌가 생각되어지네요. 즉, 구조를 잘 짜면 이런 고민도 안하지 않을까.. 란 생각이 들어요.

2022-09-27 14:06 UTC, min16 commented on src/main/java/racing/CarRacing.java
> +    private int rounds = 0;
- 불변객체는 변경이 이루어지면 안되는 경우에 쓰이는 것 같아요.
- rounds는 불변이 될 수 있어요! 왜냐하면 한번 라운드가 설정되면 변경될 일이 없어야 하거든요. 자바에서는 한번 세팅하고 변경하면 안되는 경우 모두 불변객체로 만드는 편인가요? 
- 전역 변수로는 안 맞는 것 같아요. 왜냐면 CarRacing 객체는 여러개 만들어질 수 있는데, rounds 값을 공유하면 안되니까요! 
- 제가 더 고려해보거나 놓친 부분이 있을까요?

2022-09-27 14:15 UTC, min16 commented on src/main/java/racing/CarRacing.java
> +        for (int i = 1; i <= rounds; i++) {
이럴수가.. 이런 실수를 하다니 ㅜㅜ 확인 감사합니다.

2022-09-27 14:54 UTC, min16 commented on src/main/java/racing/ResultView.java
> +        return stringBuilder.toString();
distance가 0 또는 1 그리고 그 이상일 때 처리를 해준건데, 코드가 썩 마음에 들진 않습니다. 더 가독성 좋은 코드가 있을 것 같은데.. 

1) for 문 안에 0, 1일때 처리 넣기 -> for 문 안이 복잡해지는 것 같아 마음에 안듦
2) 1일때 처리도 early return -> `stringBuilder.toString()`을 두 라인에서 써야해서 마음에 안듦

2022-09-27 14:59 UTC, min16 commented on src/main/java/racing/CarRacing.java
> +        }
17L~21L 은 게임 진행에 대한 내용이라 한 메소드로 묶고 싶은데, 메소드 명을 뭐로 하면 좋을지 모르겠네용.

2022-09-29 13:23 UTC, ddaaac requested changes
안녕하세요 민지님 👋 

리뷰 반영 잘 해주셨습니다. 조금 더 나누고 싶은 부분들이 있어서 다시 RC 남겨요.

코멘트 확인해주시고 리뷰 요청 주세요!

2022-09-29 13:23 UTC, ddaaac commented on src/main/java/racing/CarRacing.java
> +        }
전 개인적으로 진행을 의미하는 지금 `play`도 괜찮다고 생각되네요 😄

2022-09-29 13:24 UTC, ddaaac commented on src/test/java/study/CarTest.java
> +package study;
넵넵 프로덕션 코드와 동일한 패키지를 사용해주시면 됩니다.

2022-10-01 06:52 UTC, min16 commented on src/main/java/racing/Car.java
> +        return distance;
답변 감사합니다. 정해진 정답은 없고 여러 경험을 쌓다보면, 상황에 따라 적절하게 결정하면 되는군요.

2022-10-01 07:03 UTC, min16 commented on src/main/java/racing/CarRacing.java
> +    private int rounds = 0;
- 아.. final은 런타임에 세팅이 불가하군요. 그래서 rounds는 불변 변수가 아니구요. 이해했습니다.
- 제가 지역변수를 전역변수로 알아 듣고 답변드렸네요 😓 네 동의합니다. rounds가 인스턴스 변수일 필요는 없어 보이네요.

2022-10-01 07:44 UTC, min16 commented on src/main/java/racing/ResultView.java
> +        return stringBuilder.toString();
>이 부분도 마찬가지로 StringBuilder를 인스턴스 변수가 아닌 지역 변수로 선언해주면 좋을 것 같아요. 이 부분이 인스턴스 변수라면 멀티스레드에서 문제가 발생할 수 있습니다. 어떤 문제일지 한 번 고민해보셔도 좋을 거 같아요.

StringBuilder는 멀티 쓰레드에서 안전하지 않기 때문에, 인스턴스 변수로 정의하면 제대로 동작하지 않는군요! 
확인해보니 멀티 쓰레드 환경에선 StringBuffer를 사용해야하네요.

>아무것도 append 하지 않은 StringBuilder의 toString()은 어떤 문자열을 반환할까요?

`""` 을 리턴하네요!

2022-10-01 07:56 UTC, min16 commented on src/main/java/racing/CarRacing.java
> +    }
처음에는 CarRacing 클래스가 모델이라 생각했는데, MVC 패턴 관점에서 보니까 컨트롤러가 맞는 것 같습니다.
컨트롤러면 클래스 명 뒤에 Controller를 붙이는 편인가요? 🤔

2022-10-01 07:57 UTC, min16 commented on src/main/java/racing/InputView.java
> +        if (value < 1) { value = 1; }
맞습니다.. 멋대로 1로 저장해버렸네요 😓  기획자가 보면 울분을 터뜨리겠어요.

2022-10-03 04:58 UTC, ddaaac approved these changes
안녕하세요 민지님 👋 

리뷰 반영 너무 잘해주셨습니다 👍

다음 단계 미션 진행해주세요~

2022-10-03 04:58 UTC, ddaaac commented on src/main/java/racing/CarRacing.java
> +    }
저도 큰 생각없이 xxxController라는 네이밍을 사용하고 있었는데 민지님 코멘트를 보고 찾아보니 [예전 스프링 독스](https://docs.spring.io/spring-framework/docs/3.0.0.M3/reference/html/ch16s10.html)에

> If you follow the pretty standard convention of naming your Controller implementations as xxxController, ...

라는 문장이 있는 걸 보니, 관례처럼 사용하고 있는 네이밍인 것 같아요.

2022-10-03 04:59 UTC, merged