자동차 경주 3단계 미션 리뷰 요청
next-step/java-racingcar pull request #3684
Opened 2022-09-26 14:10 UTC by jwoo-o

자동차 경주 3단계 미션 리뷰 요청 드립니다.

2022-09-27 10:21 UTC, catsbi requested changes
안녕하세요 진우님, 3단계 미션 잘 구현해주셨네요 👍 
기능 구현 잘 해주셨는데, 테스트 케이스가 좀 부족한 것 같고, 설계적으로 피드백이 필요한부분들이 좀 있어 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 해주시기 바랍니다. 😊

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/Race.java
> +        InputView inputView = new InputView();
View Layer는 별도의 상태를 가지지 않기 때문에 재사용이 가능할 것 같네요 👍

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Car.java
> +    private final Move move;
변수명은 해당 값이 무엇을 의미하는지에 대한 정보를 명확하게 알려줄 수 있어야 합니다. 
Move라는 변수명과 타입명이 해당 변수의 목적을 제대로 알려주기 힘들어보여요. 좀 더 적절한 이름은 없을까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Car.java
> +           position.append("-");
스키드마크가 `-` 라고 지정을 도메인 객체에서 해주고 있네요. 출력에 대한 책임은 View Layer에 있는게 맞지 않을까요?
도메인에서는 상태에 대해서만 다뤄주는게 좋을 것 같네요 👍

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Car.java
> +        position = new StringBuilder();
위치정보가 StringBuilder 이면 나중에 우승자를 구하거나 거리에 대한 요금을 계산하거나 할 때 문자열의 길이를 또 구하거나 해야하는데, 효율적일까요? 🤔

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Car.java
> +        if (move.move())
move()라는 동사는 움직이라는 의미로 보이지 움직일 수 있냐고 물어보는 로직으로 보이지 않습니다. 
논리값 반환을 기대한다면 접두사로 is, has, exists등의 접두사를 붙혀보는건 어떨까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Cars.java
> +    private final List<Car> carList;
List 자료구조와 같은 타입은 필드 초기화를 해주시면 Null Safe할 수 있습니다 👍

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Cars.java
> +    private final int tryNumber;
tryNumber가 인스턴스 변수로 관리해야할 필요가 있는 값일까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/Move.java
> +public interface Move
메서드가 하나짜리인 인터페이스면 적절한 애노테이션을 붙혀서 명시적으로 하나의 기능을 제공함을 알려줄 수 있지 않을까요 ㅎㅎ

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/RandomMove.java
> +    private final Random random = new Random();
Random보다는 ThreadLocalRandom을 활용하면 좀 더 나은 퍼포먼스를 기대할 수 있습니다 👍

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/model/RandomMove.java
> +        return random.nextInt(MAX) >= 4;
매직넘버(4)는 상수로 분리해주시면 어떨까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/view/InputView.java
> +{
해당 객체는 별도의 상태를 가지고 있지 않네요. 
싱글턴 패턴을 사용해보는건 어떨까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +    private final Cars cars;
View Layer에서 상태를 가질 필요가 있을까요?

2022-09-27 10:21 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +            });
함수안에 반복문(forEach)이 있네요. 이것도 일종의 2detph 로직이죠. 분리해보는건 어떨까요?

2022-09-27 10:21 UTC, catsbi commented on src/test/java/step3/CarTest.java
> +class CarTest
테스트가 Car 도메인 하나만 있는것 같은데, Cars 일급 컬렉션이나, 이동전략등의 테스트 케이스를 작성해보는건 어떨까요?

2022-09-27 14:55 UTC, jwoo-o commented on src/main/java/step3/model/Car.java
> +           position.append("-");
좋은 지적 감사합니다.
도메인 객체에 출력에 대한 책임을 전가해버렸네요 ㅠ

2022-09-28 08:41 UTC, catsbi approved these changes
진우님 피드백 빠르게 반영해주셨네요. 💯 
몇 가지 설계적인 관점에서 피드백을 남겨드렸는데, 확인해보시고 다음 미션 진행하시면서 같이 고민해보시면 좋을 것 같아요. 

다음 미션에서는 객체지향 생활체조 원칙을 좀 더 생각해보시고, SOLID원칙 중 SRP에 좀 더 신경써보시면 좋을 것 같습니다 👍 

3단계는 여기서 머지하도록 하겠습니다

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step2/PositiveNumber.java
> +            throw new IllegalArgumentException("홀수로는 생성 할 수 없습니다.");
홀수가 아니라 음수 아닐까요 ㅎㅎ

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step3/model/RandomMovingStrategy.java
> +    private final Random random = new Random();
ThreadLocalRandom을 사용하면 좀 더 높은 퍼포먼스를 기대해 볼 수 있습니다 👍

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step3/view/InputView.java
> +    }
이건 싱글턴이 아닌 정적 팩토리 메서드네요. 호출할 때마다 매번 새로운 인스턴스를 생성하네요 ㅎㅎ 
미리 생성해놓고 반환하도록 하는건 어떨까요?

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +    private final int tryNumber;
View Layer가 상태를 가질 필요가 있을까요?

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +        IntStream.range(0, tryNumber).forEach(value -> step(cars));
View Layer에서 비즈니스 로직을 가지네요. 
View에서는 출력에 대한 로직만 가지는게 어떨까요? 전진에 대한 책임은 각 자동차가 가지고, 각 자동차에게 전진하라는 메세지를 보내는게 일급 컬렉션이라면 일급 컬렉션에게 전진 하라는 notify를 하라고 명령을 내리는건 어디가 좋을까요?

2022-09-28 08:41 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +        IntStream.range(0, car.getPosition()).forEach(value -> builder.append("-"));
`-` 스키드마크는 상수로 분리해보는건 어떨까요?

2022-09-28 08:41 UTC, merged