🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #3692
Opened 2022-09-26 20:00 UTC by shinseongsu

- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [x] 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [x] 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.

- [x] 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외
- [x] 자바 코드 컨벤션을 지키면서 프로그래밍한다. (intellij code style)

2022-09-27 00:16 UTC, testrace requested changes
안녕하세요 성수님 😄 
3단계도 요구사항에 맞게 잘 구현해 주셨네요 👍 

인터페이스를 적극적으로 활용한 설계가 인상 깊었습니다!!
[코드리뷰 3단계](https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md) 를 참고하셔서 해당 단계의 커밋만
PR에 포함해 주시면 좋을 것 같습니다!

몇 가지 코멘트 남겨두었으니 확인해 주시고 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/controller/RacingGame.java
> +    }
InputView를 주입받는 형태로 구현해 주셨네요 👍 
RacingGame이 Controller라면 ResultView도 주입 받으면 어떨까요?

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/domain/Car.java
> +    private StringBuilder moved;
자동차의 상태로 StringBuilder를 사용해 주셨네요.
출력을 위한 선택이라고 보여지는데요, 간접적이지만 View에 의존하고 있다는 생각이 듭니다.
domain이 view에 의존하는 것에 대해서 어떻게 생각하세요?

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/domain/CarMovableStrategy.java
> +        Random random = new Random();
Random 객체를 매번 생성하기 보다 상수로 선언해서 재사용하면 어떨까요?

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/domain/Car.java
> +    }
전략 패턴을 위한 인터페이스가 존재하니 인터페이스를 주입받아서 자동차를 움직일 수 있게하면 어떨까요?

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/domain/MovableStrategy.java
> +public interface MovableStrategy {
전략 패턴을 위한 인터페이스 💯 
선언된 함수가 1개라면 `@FunctionalInterface` 애너테이션을 적용해 보시는 것도 좋을 것 같습니다 😃

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/service/RacingGameService.java
> +public interface RacingGameService {
인터페이스를 자주 활용하시는 것 같아요!
어떤 경우에 인터페이스를 만드시는 기준이 궁금합니다 🤔

2022-09-27 00:16 UTC, testrace commented on src/main/java/racing/service/RacingGameServiceImpl.java
> +    private final int tryCount;
스프링에서 사용하는 `@Service` 애너테이션을 적용한 클래스처럼 만들어 주신 것 같아요!
스프링에서는 싱글톤으로 관리는 객체이기 때문에 무상태성을 지향합니다.
그렇다면 RacingGameServiceImpl가 상태를 가질 필요가 있을까요?
스프링의 Service처럼 만든 것이 어떤 의도로 Service라는 이름으로 클래스를 만들어주셨는지 궁금합니다 🤔

2022-09-27 00:16 UTC, testrace commented on src/test/java/racing/domain/CarTest.java
> +    }
테스트가 가독성도 좋고 의도를 명확하게 표현하고 있네요 👍 
자동차를 움직이게 할 수 있는 숫자의 범위가 0 ~ 10000 으로 변경된다면 이 테스트 코드는 어떻게 변경되어야 할까요?
자동차를 움직이게 하는 경계값으로 테스트하면 어떨까요?

2022-09-27 00:16 UTC, testrace commented on src/test/java/racing/domain/CarsTest.java
> +class CarsTest {
CarTest와 테스트 내용이 다르지 않은 것 같아요.
CarTest에서 자동차의 전진, 멈출을 테스트 했으니 CarsTest에서만 할 수 있는 테스트를 하면 어떨까요?

2022-09-27 07:56 UTC, shinseongsu commented on src/main/java/racing/controller/RacingGame.java
> +    }
input output 둘다 주입받아서 하는 형태로 말씀하신거죠? 넵 알겠습니다 😄

2022-09-27 08:00 UTC, shinseongsu commented on src/main/java/racing/domain/CarMovableStrategy.java
> +        Random random = new Random();
오 상수로 선언하는게 더 깔끔하게 표현할 수 있겠네요 👍

2022-09-27 08:06 UTC, shinseongsu commented on src/main/java/racing/service/RacingGameService.java
> +public interface RacingGameService {
저는 인터페이스 기준을 이렇게 잡고 있습니다.
1. 메소드를 정의할때
2. 로그인 같이 kakao, google를 이용할 경우 메소드 이름은 같은데 안에 내용이 변경 될때,
3. 랜덤과 같이 테스트를 위해 전략패턴을 진행하기 위해

2022-09-27 08:08 UTC, shinseongsu commented on src/main/java/racing/service/RacingGameServiceImpl.java
> +    private final int tryCount;
Spring의 service같이 만들어야 리뷰어분들께 익숙한 패턴으로 보여질것같아 이러한 형식으로 만들게 되었습니다

2022-09-27 08:12 UTC, shinseongsu commented on src/main/java/racing/domain/Car.java
> +    private StringBuilder moved;
확실히 view 출력을 위해 저장하는 느낌이 강하게 드네요

2022-09-27 08:13 UTC, shinseongsu commented on src/main/java/racing/domain/Car.java
> +    }
Car 라는 도메인에서는 조건을 넣기보다 인터페이스로 움직이도록 수정 하겠습니다

2022-09-27 08:14 UTC, shinseongsu commented on src/main/java/racing/domain/MovableStrategy.java
> +public interface MovableStrategy {
오 그렇군요 

```
함수형 인터페이스(Functional Interface)는 추상 메서드가 딱 하나만 존재하는 인터페이스를 말합니다.

그리고 람다식은 이러한 함수형 인터페이스를 기반으로만 작성이 될 수 있습니다.
```

찾아보니 함수형으로 만들 수 있는 인터페이스이네요 적극적으로 활용하도록 해보겠습니다 😄

2022-09-27 08:15 UTC, shinseongsu commented on src/test/java/racing/domain/CarTest.java
> +    }
아~ 경계값 테스트 필기..필기.. 👍

2022-09-27 08:16 UTC, shinseongsu commented on src/test/java/racing/domain/CarsTest.java
> +class CarsTest {
그렇군요 중복되는 느낌이 있었는데 감사합니다 👍

2022-09-28 17:10 UTC, shinseongsu commented
## 수정 사항
- Car에서 move를 StringBuilder -> int 로 수정
- Random 객체 상수
- Service 에서 count 가지고 있는거 수정

2022-09-28 23:12 UTC, testrace commented on src/main/java/racing/controller/RacingGame.java
> +    public RacingGame(InputView inputView, ResultView resultView) {
ResultView를 주입받도록 변경해 주셨네요 💯

2022-09-28 23:12 UTC, testrace commented on src/main/java/racing/domain/Car.java
> +    private int moved;
변수명 moved 보다는 자동차의 위치를 뜻하는 이름으로 부여하면 어떨까요?

2022-09-28 23:12 UTC, testrace commented on src/main/java/racing/domain/CarMovableStrategy.java
> +        return 0;
1과 0이 무엇을 뜻하는지 상수로 치환해서 이름을 부여해 보시면 좋을 것 같아요 😃

2022-09-28 23:12 UTC, testrace commented on src/main/java/racing/ui/ResultViewImpl.java
> +        System.out.println("-".repeat(car.getMoved()));
매직 리터럴 `"-"` 도 상수로 치환할 수 있을 것 같아요!

2022-09-28 23:12 UTC, testrace commented on src/main/java/racing/service/RacingGameService.java
> +public interface RacingGameService {
인터페이스를 정의하시는 기준이 명확하게 있으시네요!
성수님의 기준이 잘못된 것은 없는 것 같아요. 😃

2022-09-28 23:16 UTC, testrace approved these changes
안녕하세요 성수님 😄 
피드백 반영 잘해 주셨네요 💯 

바로 다음 단계 진행해 주세요 🔥 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다!
궁금한 내용이 있으시면 언제든지 편하게 DM 주세요!

2022-09-28 23:16 UTC, merged

2022-10-05 13:52 UTC, shinseongsu commented on src/main/java/racing/domain/Car.java
> +    private int moved;
거리를 뜻한 distance로 변경하도록 하겠습니다 제가 네이밍에 많이 약해서 ㅠㅠ 😢

2022-10-05 13:52 UTC, shinseongsu commented on src/main/java/racing/domain/CarMovableStrategy.java
> +        return 0;
아 그렇군요 상수로 표현하면 다들 알아보기 쉽겠네요

2022-10-05 13:53 UTC, shinseongsu commented on src/main/java/racing/ui/ResultViewImpl.java
> +        System.out.println("-".repeat(car.getMoved()));
되도록 하드 코딩된 것을 줄이도록 노력하겠습니다

2022-10-05 13:55 UTC, shinseongsu commented on src/main/java/racing/service/RacingGameService.java
> +public interface RacingGameService {
제가 일부러 SPRING 처럼 만든 이유중에 이번 강의가 Java 기반이라 비슷하게 만들면 멘토님의 스프링 팁을 얻을 수 있을 것같아서 그랬습니다 😄