Step3 clean
next-step/java-racingcar pull request #3701
Opened 2022-09-27 11:26 UTC by daakludens

2022-09-27 11:29 UTC, daakludens commented
석홍님, 안녕하세요. step3-clean 브랜치로 새로 따서 PR 다시 올렸습니다.
그 과정에서 히스토리가 좀 지저분해져서.. 죄송합니다.. :pray:
리뷰 부탁 드리겠습니다..

2022-09-27 23:36 UTC, seokhongkim requested changes
희재님, 3단계 미션 잘 구현해주셨습니다! 👍 
UI, 도메인을 분리하기 위해 고민하신 흔적이 보이네요.

조금 더 고민해보시면 좋을 것 같은 부분을 코멘트로 남겼습니다.
코멘트 확인 부탁드려요. 🙏 

코멘트 보시고 같이 논의해야 할 내용이나 궁금한 점이 있으시면 깃헙 코멘트 또는 슬랙 DM으로 편하게 말씀 부탁드립니다.

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/Race.java
> +        InputView inputView = new InputView();
1. 입력 값을 가지고 오는 책임을 `InputView` 에서 모두 해보는 것은 어떨까요?
현재는 `Race` 가 `InputView` 의 구현을 모두 아는 상태에서 `InputView` 의 메소드를 정해진 순서에 따라 호출해줘야 하네요.

2. `InputUtil` 에서 사용하는 `Scanner` 의 자원을 사용이 끝나면 정리해줘야 할 것 같아요.
try with resources 문법을 사용해보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/Race.java
> +    private static void race(int numOfCars, int numOfRounds) {
메소드 이름은 `race` 인데, 초기화하는 작업과 `end`(종료) 메소드를 호출하네요.
메소드에서 수행하는 역할을 나눠보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/Race.java
> +    private static void end(Set<Car> cars, int numOfRounds) {
메소드 이름은 `end` 인데, 경기를 진행하는 역할을 하네요.
메소드 이름을 행위를 서술할 수 있도록 변경해보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/domain/Car.java
> +    private final StringBuilder steps;
현재 위치를 문자열로 관리하는군요.
나중에 화면에 문자 출력이 아니라 현재 위치를 숫자로 출력하도록 변경하면 어떻게 해야 할까요?
현재 구현은 `Car` 라는 도메인 객체가 `-` 를 이용해서 화면에 출력하라는 UI 구현을 모두 알고 의존하는 것으로 보여요.

`Car` 객체에서는 위치 값을 관리하고, 출력에 대한 책임은 `ResultView` 에서 관리해보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/domain/Car.java
> +        int randomNumber = InputUtil.getRandomNumberBetweenZeroAndNine();
난수를 만드는 역할을 `InputUtil` 에서 관리해야 할까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/domain/Car.java
> +        return randomNumber >= 4;
`4` 라는 값은 도메인에서 유의미한 상수로 보여요.
이름을 부여하고 상수로 분리해서 관리해보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/domain/Car.java
> +        int randomNumber = InputUtil.getRandomNumberBetweenZeroAndNine();
또한 난수를 생성하는 메소드를 static 으로 관리하면, 자동차가 움직이고 움직이지 않는지 동작을 테스트하기 어려울 것 같아요.
어떻게 하면 자동차의 동작을 테스트하기 쉬울까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/test/java/step3/domain/CarTest.java
> +        mockCar = new Car(steps);
이 생성자는 테스트를 위해서만 존재하는 것 같아요.
프로덕션 코드가 테스트를 위해 변경되는 것은, 테스트 코드에 프로덕션 코드가 의존하는 것과 유사하다고 생각해요.
테스트 코드의 변경과 요구사항이 프로덕션에 영향을 주기 때문에 그렇습니다.

테스트에서 사용하기 위한 목적의 메소드, 접근 제어자 변경 없이 테스트를 하기 쉬운 구조를 고민해보면 어떨까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/test/java/step3/domain/CarTest.java
> +        boolean result = mockCar.isMovable(value);
`isMovable` 은 프로덕션 코드에서는 `private` 으로 관리되어도 될 것 같은데, 테스트를 위해 `public` 으로 열려있는 것은 아닐까요?

2022-09-27 23:36 UTC, seokhongkim commented on src/test/java/step3/domain/CarTest.java
> +    void isMovableSuccess(int value, boolean expected) {
이동하지 않는 경우에 대한 테스트도 있는데 `isMovableSuccess` 는 이동이 성공하는 경우에 대한 테스트인 것으로 보이네요!

2022-09-27 23:36 UTC, seokhongkim commented on src/test/java/step3/domain/CarTest.java
> +    @CsvSource({ "0,false", "3,false", "4,true", "7,true", "9,true" })
경계값을 이용하여 테스트 대상을 잘 선정해주신 것으로 보여요! 💯

2022-09-27 23:36 UTC, seokhongkim commented on src/main/java/step3/Race.java
> +    private static void runOneRound(Set<Car> cars) {
자동차 경주를 진행하는 것도 중요한 도메인 로직인데, 이에 대한 테스트를 하려면 어떻게 해볼 수 있을까요?

2022-09-28 12:54 UTC, daakludens commented on src/main/java/step3/Race.java
> +        InputView inputView = new InputView();
Race에 책임이 너무 많은게 문제인 것 같네요. 실제 경주에만 집중하고 그 외 시작과 종료, 그에 관련된 로직을 최대한 분리시켜 보도록 해보겠습니다. 
그리고 scanner의 경우 try-with-resource로 close하겠습니다.

2022-09-28 13:00 UTC, daakludens commented on src/main/java/step3/domain/Car.java
> +    private final StringBuilder steps;
음.. 빠르게 출력시키려고 문자열로 관리했는데 읽고 보니 너무 출력에 초점을 맞춘 필드가 된 느낌이 드네요.
그러면 Car에서는 int 값으로 현재 위치만을 관리하고, ResultView에서 위치값을 "-" 로 변환해 출력하는 방식으로 해보겠습니다.

2022-09-28 13:02 UTC, daakludens commented on src/main/java/step3/domain/Car.java
> +        int randomNumber = InputUtil.getRandomNumberBetweenZeroAndNine();
유틸 클래스에 넣었는데 네이밍이나 취지에는 맞지 않네요.. 차라리 다른 유틸 클래스로 넣거나 실제 사용되는 클래스에 넣는게 나을 것 같습니다.

2022-09-28 13:02 UTC, daakludens commented on src/main/java/step3/domain/Car.java
> +        return randomNumber >= 4;
아이고.. 상수화 시키는 걸 또!!! 네넵, 이거 수정하겠습니다.

2022-09-28 13:09 UTC, daakludens commented on src/main/java/step3/domain/Car.java
> +        int randomNumber = InputUtil.getRandomNumberBetweenZeroAndNine();
네, 차라리 goOrStop을 테스트 시키는게 더 나을 것 같습니다..
이건 좀 더 고민해봐야겠네요..

2022-09-28 13:18 UTC, daakludens commented on src/main/java/step3/Race.java
> +    private static void runOneRound(Set<Car> cars) {
음........ Random 기능을 분리해야지만 가능할 것 같습니다.
분리 방법 한 번 도모해보겠습니다..

2022-09-28 13:20 UTC, daakludens commented on src/test/java/step3/domain/CarTest.java
> +    void isMovableSuccess(int value, boolean expected) {
아하 네이밍이 부적절했네요. 이름을 바꾸거나 네이밍을 바꿔 2개의 메서드로 분리하는 방법으로 리팩토링 해보겠습니다.

2022-09-30 15:57 UTC, daakludens commented
안녕하세요! 주신 피드백 반영해서 수정해봤습니다.

일단 랜덤값 테스트의 경우 랜덤값으로 전진 여부를 던져주는 클래스로 따로 분리해서 테스트 가능하도록 바꿔봤습니다.

그리고 Scanner에 try-with-resource 추가 부분 말씀해주셔서 생각해봤습니다. 
사용 후 close로 닫으려면 하나의 try-catch 안에 두 번의 입력 로직이 수행되어야 하는 걸로 이해를 했습니다. 그러면 자동차와 라운드 개수 값을 한 번에 가져오려면 vo 같은 옮기기용 클래스를 추가하거나 그 안에 Race 객체를 생성해 값을 넣을 수는 있을 것 같습니다. 하지만 그러면 너무 번거로워지게 되더라고요.
또한 System.in은 사용자가 임의로 종료시키면 다른 곳에서 예상치 못하게 에러가 발생할 수도 있다는 글도 봤어서.. 우선 close 없이 수정을 해보았습니다.
이 부분은 석홍님의 의견을 한 번 물어보고 싶었습니다. 읽어주셔서 감사합니다 🙏

2022-10-01 06:24 UTC, seokhongkim commented
> 그리고 Scanner에 try-with-resource 추가 부분 말씀해주셔서 생각해봤습니다.
사용 후 close로 닫으려면 하나의 try-catch 안에 두 번의 입력 로직이 수행되어야 하는 걸로 이해를 했습니다. 그러면 자동차와 라운드 개수 값을 한 번에 가져오려면 vo 같은 옮기기용 클래스를 추가하거나 그 안에 Race 객체를 생성해 값을 넣을 수는 있을 것 같습니다. 하지만 그러면 너무 번거로워지게 되더라고요.
또한 System.in은 사용자가 임의로 종료시키면 다른 곳에서 예상치 못하게 에러가 발생할 수도 있다는 글도 봤어서.. 우선 close 없이 수정을 해보았습니다.

말씀하신 것처럼 `System.in` 리소스를 임의로 종료하면 다시 사용할 때 문제가 된다는 내용이 있네요. :)
바로 종료하기 전에 잘 찾아보신 것 같습니다. 👍 

저는 위에 말씀하신 VO 또는 DTO를 이용하여 입력값을 한번에 읽어오는 방향을 생각했습니다.
하지만 분명 클래스를 추가해야 하는 것은 사실이고, 코드 복잡도가 올라갈 수 있다는 면도 이해되어 지금 방법을 그대로 사용하시는 것도 괜찮겠네요.

많은 고민을 하고 결정하신 내용인 것 같습니다. 고생하셨습니다. 😀

2022-10-01 06:32 UTC, seokhongkim approved these changes
희재님, 3단계 미션 피드백 잘 반영해주셨습니다. 💯 
피드백 반영하는 과정에서 많은 고민을 하신 것 같아요. 이 고민이 희재님에게 도움이 되었으면 좋겠습니다.
3단계 PR은 이만 머지하도록 하겠습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-10-01 06:32 UTC, seokhongkim commented on src/main/java/step3/RaceMain.java
> +        receiveRaceInputs();
현재 메소드의 흐름을 보면 아래와 같네요.

`입력 값을 읽기` 메소드 내에서 `값을 초기화` 하는 메소드를 호출하고, `값을 초기화` 하는 메소드 내에서 `경기를 시작` 하는 메소드를 호출합니다.
`값을 초기화` 하는 메소드를 `입력 값을 읽기` 메소드에서 호출해야 할 이유가 있을까요? 메소드 내에서 다른 메소드를 호출한다는 것은, 그 메소드의 역할도 함께 하고 있다는 것은 아닐까요?

이런 맥락에서 `main` 에서 `receiveRaceInputs`, `setUpRace`, `startRace` 를 직접 호출하는 것은 어떨까요?

2022-10-01 06:32 UTC, seokhongkim commented on src/main/java/step3/domain/CarMove.java
> +    Random random = new Random();
접근 제어자를 default 로 사용하신 이유가 있을까요?
정적 상수로 관리해도 된다면 `static`, `final` 을 붙여주면 어떨까요?

2022-10-01 06:32 UTC, seokhongkim commented on src/main/java/step3/domain/Race.java
> +    private static final int INITIAL_STEP = 0;
모든 차의 초기 위치가 0 이라면, 자동차 경주가 아니라 차에서 직접 초기 위치를 가지고 있는 건 어떨까요?
경주에서 차의 초기 위치를 알아야 할 필요가 있을까요?

2022-10-01 06:32 UTC, seokhongkim commented on src/test/java/step3/domain/RaceTest.java
> +    void createRace() {
자동차 경주를 진행하는 것도 중요한 도메인 로직이니 테스트해보면 어떨까요?

2022-10-01 06:32 UTC, merged