Step2 리뷰 요청
next-step/java-racingcar pull request #3715
Opened 2022-09-27 21:53 UTC by jackson-hong

2022-09-27 23:50 UTC, seokhongkim requested changes
지운님, 2단계 미션 잘 구현해주셨습니다! 💯 
입력값을 관리하는 클래스와 숫자를 관리하는 클래스의 역할을 잘 나눠주셔서 코드를 읽고 이해하기 좋았습니다.

조금 더 고민해보시면 좋을 것 같은 부분에 코멘트를 남겼으니 확인 부탁드립니다. 🙏 

추가로, 중간에 주석으로 질문 남겨주신 내용에 대해서도 제 생각을 답변으로 남겼습니다.
질문을 깃헙 코멘트로 남겨주시면 아래와 같은 이점을 얻을 수 있을 것 같아요. 😀 
1. 코드에 필요하지 않은 주석이 남지 않습니다. 클린코드의 주석에 대한 내용을 참고해보셔도 좋을 것 같아요.
2. 질문과 논의해야 할 내용이 문서화가 됩니다. 제가 답변드린 후에 관리를 위해 코드에서는 주석을 삭제하게 될 것 같은데, 이 경우 어떤 질문이 있어서 제가 답변을 남겼는지 파악이 어려울 것 같습니다.

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/InputText.java
> +    private static final String DEFAULT_SEPARATORS = ",|:";
유의미한 문자열을 상수로 관리하고 적절한 이름 사용하신 것 좋습니다. 💯

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/InputText.java
> +    private static final String CUSTOM_SEPARATOR_FINDERS = "//(.)\n(.*)";
패턴을 한번만 만들고 재사용 할 수 있도록 Pattern.compile 의 결과를 상수로 가지고 있으면 어떨까요?

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/InputText.java
> +public class InputText {
입력 값을 감싸는 값 객체 사용 좋습니다. 👍

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/InputText.java
> +    public boolean isBlank() {
적절한 밸리데이션 좋습니다. 👍

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/PositiveNumber.java
> +        if(value < 0) throw new RuntimeException("NEGATIVE NUMBER");
잘못된 인자임을 알려줄 수 있는 예외는 어떤 게 있을까요?

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/PositiveNumber.java
> +public class PositiveNumber {
여기도 숫자를 감싸는 값 객체 사용 좋습니다. 👍

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/StringAddCalculator.java
> +* {} 없는 if문은 어떻게 생각하시나요?
저는 모든 조건문, 루프에 일관되게 `{ }` 를 사용하는 것을 선호합니다.
1. 한 눈에 조건문과 루프의 범위가 보입니다.
2. 추후 코드가 추가/삭제될 때, 변경된 범위가 코드가 추가/삭제된 영역으로 한정되어 비교하기 수월합니다. `{ }`를 추가하거나 삭제한다면 그 범위까지 변경된 것으로 들어와 헷갈릴 것 같아요.
3. 저 혹은 함께 일하는 개발자가 실수로 조건문, 루프에 포함되거나 포함되지 않아야 할 로직을 잘 못 작성하는 버그를 방지할 수 있습니다.

2022-09-27 23:50 UTC, seokhongkim commented on src/main/java/StringAddCalculator.java
> +        for(PositiveNumber number : numbers){
조건문, 루프에서 `for` 와 `(` 사이에 공백이 들어가기도 하고 공백이 없기도 하네요.
또 어떤 상황에서는 `{` 를 사용하고, 그렇지 않은 경우도 있네요.

일관된 컨벤션을 정해서 적용해보면 어떨까요? 저는 코드를 읽을 때 한 눈에 더 잘 들어올 것 같아요!

2022-09-27 23:50 UTC, seokhongkim commented on src/test/java/StringTest.java
> +    // 실무에서 test 메소드명을 지으실 때 영어를 선호하시나요 한글을 선호하시나요?
저는 메소드명은 영어로 작성하고, 필요한 경우 `@DisplayName` 을 사용하여 테스트 내용을 조금 더 서술하는 것을 선호합니다.
메소드 명을 한글로 작성하는게 더 이해하기 쉽고, 관리 측면에서 편한 점도 있기 때문에 선호에 따라 일관된 방법으로만 해보시면 좋을 것 같아요!

2022-09-28 13:17 UTC, jackson-hong commented
항상 좋은 피드백 주셔서 정말 감사합니다~!
피드백 주신 부분 반영하였습니다~!

그리고 혹시 InputText.split() 메소드를 혹시 좀 더 리팩토링 할 수 있는 방법이 있을까요?
리턴하는 부분에서에서 반환되는 로직이 비슷해서 좀 더 좋은 방법이 있을 거 같은데 잘 떠오르지 않네요!ㅠ

2022-09-29 13:24 UTC, seokhongkim approved these changes
지운님, 2단계 피드백 잘 반영해주셨습니다. 💯 

질문 남겨주신 부분에 대해서는 `InputText` 클래스에 남긴 코멘트를 참고 부탁드려요 🙏 
2단계 미션 잘 진행해주셔서 PR도 이만 머지하겠습니다.
혹시 코멘트 남긴 내용에 대해 더 고민되시는 부분 있다면 깃헙 코멘트나 슬랙 DM으로 편하게 말씀 부탁드려요.

3단계 미션에서 뵙겠습니다. 😀

2022-09-29 13:24 UTC, seokhongkim commented on src/main/java/InputText.java
> +    private final Pattern pattern;
`Pattern` 은 thread safe 하고 immutable 하므로 `CUSTOM_SEPARATOR_FINDERS` 와 같이 private static final 상수로 관리해도 될 것 같아요.
> https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
> Instances of this class are immutable and are safe for use by multiple concurrent threads. Instances of the [Matcher](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html) class are not safe for such use.

2022-09-29 13:24 UTC, seokhongkim commented on src/main/java/InputText.java
> +        if(hasCustomSeparator()){
기존에 구현하신 코드가 충분히 가독성이 괜찮았던 것 같은데, 지금 코드로 변경하신 이유가 있을까요?
```suggestion
Matcher m = pattern.matcher(this.text);
if (m.find()) {
    String customDelimiter = m.group(1);
    return m.group(2).split(customDelimiter);
}
return this.text.split(DEFAULT_SEPARATORS);
```

2022-09-29 13:24 UTC, merged

2022-09-29 20:50 UTC, jackson-hong commented on src/main/java/InputText.java
> +        if(hasCustomSeparator()){
추후 확장성을 고려해서 메소드화 해보았는데 굳이 그럴 필요는 없었던거 같네요!
저는 평소에 코드를 설계 할 때 확장성을 고려해서 설계를 할 경우 가끔 오버엔지니어링인가 라는 의문이 들곤 하는데요
혹시 홍석님은 확장성에 대해 얼마나 고민하시는지 궁금합니다!

2022-10-01 03:35 UTC, seokhongkim commented on src/main/java/InputText.java
> +        if(hasCustomSeparator()){
지운님께서 말씀하신 확장성과 오버 엔지니어링 사이의 고민은 저도 늘 고민하게 되고, 참 답을 찾기 어렵더라구요.

저는 아래와 같은 방법을 사용하는데, 지운님도 지운님만의 방법을 고민해보시면 좋을 것 같아요.
1. 처음부터 확장성을 고려하지는 않고 작성한다.
2. 기능이 변경, 확장될 필요가 있을 때 기존의 코드를 리팩토링한다.
3. 단, 처음부터 변경의 방향성을 알 수 있는 경우(e.g., 사업 부서에서 다음 스텝으로 하고 싶은 아이템이 있는 경우, 개발 조직에서 논의했을 때 우서순위에 따라 뒤로 미뤄놓은 기능이 있는 경우)에는 변경을 반영하기 쉬운 방향으로 설계한다.

언젠가 정답을 처음부터 알 수 있는 때가 오면 좋겠다는 생각이 드네요. 😀