3단계 - 자동차 경주
next-step/java-racingcar pull request #3730
Opened 2022-09-28 14:48 UTC by jimbaemon

Race 결과 반환타입을 어떻게 해줘야 할지 잘 모르겠습니다.
피드백 부탁드려요 :)

2022-09-29 13:41 UTC, JunHoPark93 requested changes
안녕하세요~ 3단계 구현하시느라 고생많으셨습니다.
몇가지 코멘트 남겨두었는데요, 구조의 변경이 일어나야될거같아요.
각자의 역할을 충분히 고민해보시고 수정부탁드려요 😊
잘 안되면 말씀주세요!

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/Race.java
> +        ArrayList<String> result = new ArrayList<>();
인터페이스로 선언하는게 좋을거같아요~

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/Race.java
> +    private ArrayList<ArrayList<String>> scoreBoard = new ArrayList<>();
final 누락되었네요!
그리고 리스트의 리스트로 선언하는게 가독에 좋지가 않네요 개선해볼수있을까요?

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/InputView.java
> +    }
InputView인데 결과출력도 들어가있는 구조네요! OutputView도 분리해보면 어떨까요?

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/Car.java
> +    public int compare(Car o1, Car o2) {
비교 구현도 잘해주셨네요 👍

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/Car.java
> +        return random.nextInt(9) >= 4;
숫자들도 의미있는 상수로 만들어보면 어떨까요?

2022-09-29 13:41 UTC, JunHoPark93 commented on src/main/java/racing/Car.java
> +    private static final String ROAD = "-";
도메인에 출력로직이 들어가있네요! OutputView가 담당하도록 변경해보아요

2022-09-29 14:02 UTC, jimbaemon commented on src/main/java/racing/Race.java
> +    private ArrayList<ArrayList<String>> scoreBoard = new ArrayList<>();
스코어보드 역활을 하는 클래스로 전환하는게 좋을까요? 
아니면 리스트를 다른형으로 변환하는게 좋을까요? :)

2022-09-29 14:04 UTC, jimbaemon commented on src/main/java/racing/Race.java
> +        ArrayList<String> result = new ArrayList<>();
혹시 어떤 부분때문에 인터페이스로 선언하는게 좋다고 판단하셨는지 여쭤봐도 괜찮을까요? :)

2022-09-29 14:04 UTC, jimbaemon commented on src/main/java/racing/Car.java
> +    public int compare(Car o1, Car o2) {
감사합니다 :)

2022-09-29 14:39 UTC, jimbaemon commented
질문 두가지만 드릴게요 :)
1. 객체별로 가져야하는 값과 상태, 행위를 요구사항에서 어떻게 분리하는 편이신지 여쭤봐도 괜찮을까요? 이 예제를 바탕으로 알려주셔도 괜찮고 완전히 새로운 예시여도 괜찮습니다.
2. 먼저 이 과정을 끝내본 경험자로서 다른분들 예제를 어느 시점에 참조하는게 좋을까요? merge 이후? 아니면 개선 사항을 잘 모르겠을때??

2022-10-02 02:00 UTC, JunHoPark93 commented on src/main/java/racing/Race.java
> +        ArrayList<String> result = new ArrayList<>();
지금 미션에 가깝게 말씀드리면, 특정 구현에 종속되지 않는 구조를 가져갈 수 있어요. 구현해주신 MovingRule은 인터페이스로 선언해서 CarRacingApplicationMain에서 사용하고있는데 그 구조는 왜 그렇게 가져갔는지 생각해보시면 좋을거같아요 😊
구체클래스에 의존적이지 않게 구조를 가져갈 수 있습니다. 지금의 List예시는 크게 와닿지 않을 수 있는데요, 프로그램이 점점 커지면서 같은 명세를 가진 구현체들이 여럿 나오는경우가 빈번한데요, 그때 장점을 더 크게 느끼실수있을거같아요. 혹은 라이브러리나 프레임워크를 열어보시면서 인터페이스가 어떻게 사용되는지 보면 도움이 될거에요~

2022-10-02 02:01 UTC, JunHoPark93 commented on src/main/java/racing/Race.java
> +    private ArrayList<ArrayList<String>> scoreBoard = new ArrayList<>();
스코어보드 역할을 하는 클래스가 더 좋아보입니다. 실제로 그렇게 잘 해주셨네요~
아마 다음 미션에서 컬렉션을 감싸는 클래스들을 하나씩 만들어볼텐데요, 역할에 맞게 설계하는것을 경험해보실 수 있을거에요. 미리 잘 해주셨어요 😊

2022-10-02 02:09 UTC, JunHoPark93 commented
> 객체별로 가져야하는 값과 상태, 행위를 요구사항에서 어떻게 분리하는 편이신지 여쭤봐도 괜찮을까요? 이 예제를 바탕으로 알려주셔도 괜찮고 완전히 새로운 예시여도 괜찮습니다.

주로 큰것에서 작은것으로 생각하시면 편하실거에요. 지금 미션에서는 '경주'가 될거같은데요, 경주에는 '자동차들', '점수판' 이 필요하고 '자동차'안에는 '이름', '위치' 등이 필요하게 되겠죠. 큰것을 먼저 만들어보고 하나씩 분리해보면 좋을거같아요. 클래스가 여러 인스턴스 변수들이 필요하고 하나 이상의 역할을 담당하고 있을때 분리의 필요성을 느낄 수도 있구요. 하시다보면 조금씩 익숙해지실거같아요~
답변이 되었을까요?

> 먼저 이 과정을 끝내본 경험자로서 다른분들 예제를 어느 시점에 참조하는게 좋을까요? merge 이후? 아니면 개선 사항을 잘 모르겠을때??

머지 이후에도 하는건 어떨까요? 리뷰어와 소통하면서 혼자 고민해보시는걸 추천드리는 이유는 먼저 다른 분들이 하는걸 봐버리면 이미 머릿속에 그 솔루션이 존재하는 상태로 코드를 만들게되어요. 물론 다른 분이 한 솔루션이 더 나이스(?)할수도있어요. 그럼에도 불구하고 먼저 해보라고 하는 이유는 나중에 "왜 그렇게 생각하지 못했을까"를 복기해볼수있어요. 몇 번 복기하다보면 나중에 참조할 것이 없는 상황에서 좋은 솔루션을 도출해 낼 수 있다고 생각합니다.
답변이 되었을까요?

2022-10-02 02:13 UTC, JunHoPark93 requested changes
안녕하세요~ 리뷰 반영 하느라 고생많으셨어요.
커밋도 잘 나누어주셔서 보기 좋네요 👍
다만 코멘트 몇 개 더 남겨두었는데 한 번 더 확인해주시고 반영해보면 좋을거같아요.
질문 주신 부분은 코멘트 따로 남겨두었으니 참고 부탁드려요 😊

2022-10-02 02:13 UTC, JunHoPark93 commented on src/main/java/racing/domain/NoRule.java
> +public class NoRule implements MovingRule{
isPossibleToMove의 결과를 NoRule이라는 구체클래스를 열어봐야 동작을 알 수 있습니다. 클래스이름만 보고도 구현을 유추해볼 수 있도록 하는 네이밍을 고민해보면 좋을거같아요.

2022-10-02 02:13 UTC, JunHoPark93 commented on src/main/java/racing/domain/NoRule.java
> +public class NoRule implements MovingRule{
그리고 컨벤션 전체적으로 확인 부탁드려요~ 
첫 미션이니 만큼 한개도 빼먹지 말고 고쳐보는게 의미있을거같아요 😊

2022-10-02 02:13 UTC, JunHoPark93 commented on src/test/java/racing/domain/CarTest.java
> +import racing.domain.NoRule;
쓰이지 않는 import들 전체적으로 확인부탁드려요 :)

2022-10-02 05:25 UTC, jimbaemon commented on src/main/java/racing/Race.java
> +        ArrayList<String> result = new ArrayList<>();
의존을 줄이고 추상화 할수 있는 부분을 찾는 능력을 자주 연습해야 겠네요 :) 좋은 피드백 감사합니다.

2022-10-02 05:28 UTC, jimbaemon commented
> 주로 큰것에서 작은것으로 생각하시면 편하실거에요. 지금 미션에서는 '경주'가 될거같은데요, 경주에는 '자동차들', '점수판' 이 필요하고 '자동차'안에는 '이름', '위치' 등이 필요하게 되겠죠. 큰것을 먼저 만들어보고 하나씩 분리해보면 좋을거같아요. 클래스가 여러 인스턴스 변수들이 필요하고 하나 이상의 역할을 담당하고 있을때 분리의 필요성을 느낄 수도 있구요. 하시다보면 조금씩 익숙해지실거같아요~ 답변이 되었을까요?

일단 만들고 역활이 분리될수 있는 곳을 찾아서 분리해 주라는것 같네요. 리팩토링 책에서 비슷한 내용을 본것 같은데 또 상기 시켜주셔서 감사합니다. 충분한 답변이 되었습니다.

> 머지 이후에 참조 하는건 어떨까요? 리뷰어와 소통하면서 혼자 고민해보시는걸 추천드리는 이유는 먼저 다른 분들이 하는걸 봐버리면 이미 머릿속에 그 솔루션이 존재하는 상태로 코드를 만들게되어요. 물론 다른 분이 한 솔루션이 더 나이스(?)할수도있어요. 그럼에도 불구하고 먼저 해보라고 하는 이유는 나중에 "왜 그렇게 생각하지 못했을까"를 복기해볼수있어요. 몇 번 복기하다보면 나중에 참조할 것이 없는 상황에서 좋은 솔루션을 도출해 낼 수 있다고 생각합니다. 답변이 되었을까요?

네 감사합니다 :) 끝내놓고 또 열심히 스캔하고 다녀야 겠네요.

2022-10-03 01:17 UTC, JunHoPark93 approved these changes
안녕하세요~ 재요청드린것 잘 반영해주셨어요.
질문에 대한 답이 되었다니 다행입니다 👍
이만 머지할게요. 다음 step에서 뵙겠습니다~

2022-10-03 01:17 UTC, merged