feat: 3단계 자동차 경주
next-step/java-racingcar pull request #3734
Opened 2022-09-28 15:55 UTC by imyoi

안녕하세요, 3단계 자동차 경주 리뷰요청 올립니다 
---
- [x] 기능 요구사항
- [x] 프로그래밍 요구사항
- [x] commit message convention
- [x] README.md 

> 추가로 궁금한 점입니다
> 기능 요구사항에 접근하는데에는 오래 걸리지 않았으나 아직은 테스트케이스를 짜는게 어렵게 느껴지는 것 같습니다
> 어떤 걸 테스트로 삼아야 하고 어떤 건 테스트를 굳이 하지 않아도 되는지 감이 안 잡히고 고민이 많이 됩니다ㅜㅜ

부족하겠지만 알려주시면 열심히 공부해가볼게요ㅇㅅㅇ!!
이번 미션도 리뷰잘부탁드립니다!

2022-09-29 14:14 UTC, KIMSIYOUNG requested changes
안녕하세요.
미션 잘 구현해주셨네요!
몇가지 코멘트 남겼는데 확인 부탁드립니다.

2022-09-29 14:14 UTC, KIMSIYOUNG commented on README.md
> +- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
요구사항을 잘 작성해주셨는데요. 요구사항을 기반으로 테스트에 접근해보는 것도 괜찮을 것 같아요. 작성해주신 요구사항을 기반으로 테스트를 뽑아보면 아래와 같이 나올 것 같아요.

1. 자동차는 전진할 수 있다
2. 자동차는 전진하지 않을수도 있다
3. 자동차는 여러번 이동할 수 있다.
4. 4이상인 경우에만 전진해야 한다. -> 나머지 케이스는 전진하지 않아야 한다. 좀 더 나아가면 네번이라고 입력받으면 전진해야하나? 이런것도 고민해볼 순 있겠죠
5. 랜덤은 테스트할 수 없으니 제외
6. 출력은 테스트 대상이 아니니, 테스트제외

어떤 테스트를 해야하는지를 고민할 때는 프로그램이 어떻게 동작할 수 있는가에 대해서 고민해보면 좋을 것 같아요. 프로그램이 동작할 수 있는 다양한 것들에 대해서 테스트를 작성하려고 하면 좋지 않을까 싶습니다.

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/Car.java
> +    public void setDistance() {
객체는 단순히 값을 저장하는 데이터덩어리가 아니라, 주체적으로 행위를 수행할 수 있습니다.
자동차가 어떤 조건에 따라서 움직일지에 대한 판단은 자동차 스스로 할 수 있는 것 같아요.
아래의 isMove메소드와 해당 메소드를 조합해보면 어떨까요?

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/InputView.java
> +            if (number < 0) {
인풋뷰는 말그대로 입력을 받기위한 뷰 및 입력받기만을 담당하는 역할이어야 합니다.
다른 사람들이 인풋뷰에서 양수를 입력하지 않으면 예외를 던질것이라는 것을 해당 메소드를 보지 않고 예상할 수 있을까요?

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/RacingGame.java
> +    private static final List<Car> cars = new ArrayList<>();
상수는 대문자로 작성해주는 것이 규칙입니다.

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/RacingGame.java
> +    private static final List<Car> cars = new ArrayList<>();
추가로 static 데이터는 모든 쓰레드에서 공유하는 데이터입니다. 멀티쓰레드 환경에서 다양한 사용자가 프로그램을 실행한다면, 값이 계속해서 공유되어 의도치않은 결과가 나올 수 있을 것 같아요.

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/RacingGame.java
> +        for (int i = 0; i < tryCount; i++) {
자동차의 묶음을 관리해주는 객체를 따로 두면 어떨까요? 일급컬렉션이라는 키워드로 공부해보면 좋을 것 같아요.

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/test/java/step3/RacingGameTest.java
> +class RacingGameTest {
테스트는 리드미에 코멘트 드렸는데 어떤 테스트가 더 필요할지 고민해보시면 좋을 것 같습니다.
가장 핵심이 되는 로직은 잘 테스트해주셨어요👏

2022-09-29 14:14 UTC, KIMSIYOUNG commented on src/main/java/step3/InputView.java
> +public class InputView {
이번 미션은 MVC구조로 구현하는 것도 포함이기 때문에, MVC구조에 맞게 패키지를 분리해보면 어떨까요? 해당 클래스뿐만 아니라 다른 클래스들도 분리해주세요.

2022-09-30 05:30 UTC, imyoi commented on src/main/java/step3/Car.java
> +    public void setDistance() {
데이터를 셋해주는 것과 자동차가 움직일 수 있는 조건을 판단하는 것을 별도로 생각하게 된 것 같습니다ㅜㅁㅜ
조언주신대로 조합해서 리팩토링 해보겠습니다 :ㅇ

2022-09-30 05:31 UTC, imyoi commented on src/main/java/step3/RacingGame.java
> +        for (int i = 0; i < tryCount; i++) {
공부해서 꼭 적용해보도록 하겠습니다 👍

2022-09-30 05:33 UTC, imyoi commented on README.md
> +- [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
코멘트 모두 확인했습니다!! 제출 때 생각할 수 없었던 것들 찝어주셔서 감사해요
참고해서 수정 후 다시 리뷰올리겠습니다 :D

2022-10-05 08:32 UTC, KIMSIYOUNG commented on src/main/java/step3/InputView.java
> +            if (number < 0) {
어떠한 것을 사용하셔도 괜찮을 것 같습니다. 다만 사용자에게 어떤 것이 잘못되었다는 것을 노티만 해줄 수 있다면 괜찮을 것 같아요. nextInt를 사용한다면 InputMismatchException을 catch해서 유의미한 메시지를 담아서 다시 예외를 던지는게 적절할 것이고, nextLine이라면 NumberFormatException을 잡아야서 다시 유의미한 메시지를 던져준다면 괜찮을 것 같아요.

2022-10-05 08:39 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰 잘 반영해주셨네요.
몇가지 조금 더 학습하면 좋을 것들이 있어 코멘트 남겼습니다.
다음 단계에서 같이 반영해주세요! (다음단계 제출하실 때 현재 단계 링크 한 번 부탁드립니다!)

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/domain/Car.java
> +    public void setDistance() {
사용하지 않는 메소드는 제거해주세요.

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/domain/Car.java
> +    public void move(int randomValue) {
잘 수정해주셨네요. 추후에는 조금 더 나아가서 전략패턴이라는 것도 학습해보시면 좋을 것 같습니다.

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/RacingGame.java
> +    private void moveEvent(int randomValue) {
자동차를 관리하는 일급컬렉션은 단순히 값을 포장하기만 하는게 아니라, 스스로 자신의 자동차들에게 움직임을 시킬 수 있는 능동적인 객체입니다.
외부에서 값을 꺼내서 자동차를 이동시킨다면 의미가 퇴색될 것 같아요. Cars에게 역할을 위임해보면 어떨까요?

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/RacingGame.java
> +    private static final ResultView resultView = new ResultView();
상수는 대문자가 규칙입니다. 그리고 위치도 다시 한번 확인해주세요.

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/UserInputException.java
> +    public static int isValidForNumber(String input) {
현재는 우연히 몇대의 자동차를 할건지, 몇번할건지가 비슷한 요구사항을 가지지만 이 둘은 다른 기능입니다.
다른 기능에서 같은 메소드를 의존하는 형태는 지양해주세요. 중복되더라도 따로 작성해주는게 좋을 것 같습니다.

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/main/java/racing/UserInputException.java
> +    public static int isValidForNumber(String input) {
조금 더 나아가서 사용자 입력을 받는 부분까지만 담당을 하고, TryCount, CarCount 와 같은 객체를 만들어서 해당 객체에게 Validation 역할을 위임하는건 어떨까요?

객체지향 학습중에는 static한 형태의 객체나 메소드는 꼭 필요한 경우가 아니라면 지양해주시면 좋을 것 같아요. 객체지향에서 왜 static을 지양하는지도 학습해보면 좋을 것 같습니다.

2022-10-05 08:39 UTC, KIMSIYOUNG commented on src/test/java/racing/RacingGameTest.java
> +class RacingGameTest {
생성하신 도메인 각 클래스에 대해서는 단위테스트를 작성해주세요.

2022-10-05 08:39 UTC, merged