Step4 자동차 경주(우승자)
next-step/java-racingcar pull request #3741
Opened 2022-09-29 00:45 UTC by allstarkenny

- 항상 좋은 리뷰 감사합니다 🙏 
- 이전 리뷰에서 의견 주셨던것도 반영하였습니다. https://github.com/next-step/java-racingcar/pull/3654

2022-09-29 13:08 UTC, catsbi requested changes
kenny님 4단계 미션 잘 진행해주셨습니다 👍 
매번 꼼꼼하게 고민 많이 하시면서 기능 구현하시는것 같아서 저도 열심히 피드백 해야겠다는 마음이네요 😁

리팩토링을 해보면 좋을 만한 부분들이 보여 피드백 남겨드렸으니 확인 후 리뷰요청 해주세요!

2022-09-29 13:18 UTC, allstarkenny commented on src/main/java/racing/controller/RacingGameController.java
> +        RacingGameSerice racingGameSerice = new RacingGameSerice(names);
* 아 오타가.. 수정해둘께요 😢 
* 흠.. 🤔  무상태성 계층인 것이 더 좋아 보이긴 하네요. 미리 이름을 넘기지 않고 추후에 실행될때 한번에 넘겨봐야겠네요. 고민할거리를 던져주셔서 감사합니다 🙏

2022-09-29 13:26 UTC, allstarkenny commented on src/main/java/racing/model/Car.java
>  public abstract class Car {
아하 뭔가 추후에 차 종류가 추가되지 않을까? 라는 생각에 추가했었던 부분입니다.
지금 당장은 불필요한 부분이긴 하네요. 수정해보겠습니다. 🙏

2022-09-29 13:26 UTC, allstarkenny commented on src/main/java/racing/controller/RacingGameController.java
> +        }
너무 좋습니다 👍

2022-09-29 13:27 UTC, allstarkenny commented on src/main/java/racing/model/Car.java
> +    private String name;
아하 수정해볼께요.

2022-09-29 13:27 UTC, allstarkenny commented on src/main/java/racing/model/DefaultCar.java
> +    private int speed = 1;
오 우선 옮겨놨는데 수정을 안했군요 😢 수정하도록 하겠습니다. 🙏

2022-09-29 13:30 UTC, allstarkenny commented on src/main/java/racing/service/RacingGameSerice.java
> +    private List<Car> cars;
https://github.com/next-step/java-racingcar/pull/3741#discussion_r983532872 오호 여기 남긴 내용과 동일한 내용이여서 다행이네요 ㅎㅎ
수정해보겠습니다. 🙏

2022-09-29 13:31 UTC, allstarkenny commented on src/main/java/racing/service/RacingGameSerice.java
> +            CarMoveProcess(car);
오.. 자체 리펙토링 중에 이상한게 들어갔네요 😢 수정하겠습니다.

2022-09-29 13:34 UTC, allstarkenny commented on src/main/java/racing/util/UserIntegerInputHandler.java
> +public class UserIntegerInputHandler extends UserInputHandler {
흠.. InputView에서 사용하는 getUserInput() 메소드 구조가 사용자에게 질의 내용 보여주고 사용자의 Input을 받는 구조가 동일하여 이걸 재사용성 있게 추가해볼까? 라는 생각에 넣었습니다.
받아야 하는 값에 따른 유효성 체크도 다 다르고 추후에 다른 Input을 받아야 할때 도움이 되지 않을까요? @catsbi

2022-09-29 13:37 UTC, allstarkenny commented on src/main/java/racing/view/ResultView.java
> +        System.out.println(String.join(",", winnerNames) + "가 최종 우승했습니다.");
너무 좋습니다 😄

2022-10-03 13:42 UTC, catsbi approved these changes
kenny 님 피드백반영 하신데서 많은 고민들을 하신게 보이네요 👍 
일정들로 바쁘시더라도 꾸준히 진행해주시면 괜찮습니다. 

이전에 비교해서 많이 객체가 나뉜 것 같습니다. 다만 아직 MVC 패턴 적용이라거나 책임 분리, 메서드 네이밍등 피드백이 필요한 부분들이 보여 코멘트 남겨드렸습니다. 
이 내용들은 다음 미션인 리팩토링 미션과 연관되어 있기에 같이 반영해보시면 좋을 것 같습니다. 

이번 미션은 여기서 머지하도록 하겠습니다. 고생하셨습니다 👏

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/CarName.java
> +    private String name;
final이 붙어도 될 것 같네요.

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +    private List<Car> cars;
Collection 타입의 인스턴스 변수는 필드 초기화를 해주면 null safe하게 설계하기가 편해집니다.

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +        }
코드 depth가 2를 넘어가네요. 줄여볼순 없을까요?

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +    }
이동할 수 있는지 그 여부 판단과 이동에 대한 책임을 자동차가 아니라 자동차 일급 컬렉션이 가지고 있네요. 
이를 현실세계로 도입해보면 밥먹는 것을 내가 아닌 내 부모님이 제어하는 것인데, 동작은 하겠지만 적절한 책임이라고 할 수는 없겠죠 ㅎㅎ cars에서는 notify만 해주는걸로  충분할 것 같아요

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +            winnerPosition = car.getPosition() > winnerPosition ? car.getPosition() : winnerPosition;
삼항연산자도 if-else와 동일하게 취급합니다. 즉 depth가 2를 넘어가는 것이죠. 🤔

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +        ArrayList<String> lapTimes = new ArrayList<>();
참조타입은 최대한 추상화 타입을 사용하는게 좋습니다.

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/Cars.java
> +        lapTimes.add("");
마지막에 `""` 공백이 추가되야 할 이유가 있을까요?

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/RaceResult.java
> +    }
메서드명은 check인데 내용은 setter네요. 이름을 혼동되게 지으면 나중에 휴먼에러가 발생할 가능성이 너무 높아집니다 😥

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/RacingWinner.java
> +public class RacingWinner {
우승자는 단수가 아니라 복수인데 클래스명은 단수로 되어있네요

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/model/RacingWinner.java
> +        return join(names);
그냥 List<String> winnerNames로 반환해도 될 것 같네요. 전체적으로 지금 출력에 대한 책임들이 모두 일급 컬렉션과 도메인에 있네요.

2022-10-03 13:42 UTC, catsbi commented on src/main/java/racing/service/RacingGameService.java
> +    private Cars cars;
이 계층은 무상태 계층일까요 상태 계층일까요?

2022-10-03 13:42 UTC, merged

2022-10-04 00:45 UTC, allstarkenny commented on src/main/java/racing/service/RacingGameService.java
> +    private Cars cars;
이런.. 상태를 가지고 있겠네요
다음 미션때 수정해보겠습니다 🙏

2022-10-04 00:46 UTC, allstarkenny commented on src/main/java/racing/model/RacingWinner.java
> +        return join(names);
오호 좋습니다.

2022-10-04 00:46 UTC, allstarkenny commented on src/main/java/racing/model/RacingWinner.java
> +public class RacingWinner {
앗 다음 미션때 수정하겠습니다. 🙏

2022-10-04 00:46 UTC, allstarkenny commented on src/main/java/racing/model/RaceResult.java
> +    }
초기에 다른 일을 하는 메소드였다가 수정하면서 역할이 단순 setter로 바뀌었네요 😢  다음 미션 진행하면서 수정해볼께요 🙏

2022-10-04 00:48 UTC, allstarkenny commented on src/main/java/racing/model/Cars.java
> +        ArrayList<String> lapTimes = new ArrayList<>();
아하 수정하도록 하겠습니다.

2022-10-04 00:49 UTC, allstarkenny commented on src/main/java/racing/model/Cars.java
> +            winnerPosition = car.getPosition() > winnerPosition ? car.getPosition() : winnerPosition;
이부분이 고민이였는데.. stream에 filter를 쓰시는 분들도 계셔서 오호 이렇다면? 이라고 해서 넣어봤습니다 😅 
메소드로 분리해보겠습니다 🙏

2022-10-04 00:50 UTC, allstarkenny commented on src/main/java/racing/model/Cars.java
> +        }
앗 나중에 리펙토링 해야지 하고 남겨둔 부분인데 그대로 올라갔네요 😭 
수정하겠습니다.

2022-10-04 00:53 UTC, allstarkenny commented on src/main/java/racing/model/Cars.java
> +    private List<Car> cars;
오 너무 좋습니다 ❤️

2022-10-04 00:53 UTC, allstarkenny commented on src/main/java/racing/model/CarName.java
> +    private String name;
다음 미션때 추가해볼께요.

2022-10-04 01:27 UTC, allstarkenny commented on src/main/java/racing/model/Cars.java
> +    }
앗 그러네요. 자식으로 내려보겠습니다. 🙏