feat : 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #3742
Opened 2022-09-29 01:20 UTC by yeojin822

리뷰 잘부탁드립니다 😄

2022-09-29 06:37 UTC, seondongpyo requested changes
4단계 미션도 잘 작성해주셨네요 👍
몇 가지 의견을 드렸는데 확인 후 다시 리뷰 요청을 부탁드릴게요.
조금만 더 힘내주세요 🔥

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/view/InputView.java
> +public class InputView {
`private` 생성자를 추가하여 인스턴스화를 막아보면 어떨까요?

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/view/InputView.java
> +    }
사용하지 않는 메서드는 제거해도 될 것 같습니다.

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/view/InputView.java
> +        if (carName.length() > 5) {
숫자 리터럴은 상수로 선언하여 의미를 부여해보면 어떨까요?

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/view/ResultView.java
> +        System.out.println(cars.stream().map(n -> n.getCarName()).collect(Collectors.joining(",")));
- 하나의 라인에 점(`.`)이 많다보니 가독성이 좋다고 말하긴 어려운 코드 같아요.
객체지향 생활 체조 원칙의 `규칙 4: 한 줄에 점을 하나만 찍는다.`를 참고하여 개선해보면 어떨까요?
- 자동차 경주 결과 메시지를 다음처럼 출력해보면 어떨까요? 지금은 우승자의 이름만 출력되고 있어요.
`pobi, honux가 최종 우승했습니다.`

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/constant/Question.java
> +    carCount("자동차 대수는 몇 대 인가요?"),
관례에 따라 enum 상수의 이름은 전부 대문자로 작성해보면 어떨까요?

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Race.java
> +        ready(carNames);
`Race`는 역할과 책임에 따라 자동차 경주를 진행하고 그 결과를 반환하는 기능만 수행하도록 해보면 어떨까요?
`Race` 내부에서 자동차를 직접 생성하는 대신 외부에서 자동차를 생성해서 `Race`로 전달해보면 좋을 것 같아요.

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +    private final String carName;
상수와 인스턴스 변수의 구분을 위해 공백 라인을 추가해보면 어떨까요?
```suggestion
    private static final int MOVE_MIN_NUM = 4;
    
    private final String carName;
```

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +    private int position = 0;
int 타입의 인스턴스 변수는 객체 생성 시 자동으로 `0`으로 초기화되니, 직접 값을 할당하지 않아도 될 것 같아요.

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +        this.carName = carName;
다른 생성자를 호출하는 방식으로 변경해보면 어떨까요?
```suggestion
        this(carName, 0);
```

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Race.java
> +    public List<Car> findWinner(List<Car> cars) {
우승자가 1명 이상일 수도 있으니 메서드의 이름을 `findWinners`로 지어보면 어떨까요?

2022-09-29 06:37 UTC, seondongpyo commented on src/test/java/racingcar/RaceTest.java
> +        assertThat(winner.get(0).getCarName()).isEqualTo("car3");
객체에서 리터럴 값을 꺼내서 검증하는 대신에 객체로 검증을 해보면 어떨까요?
```
Car car1 = new Car("car1", 3);
Car car2 = new Car("car2", 5);
Car car3 = new Car("car3", 7);

List<Car> cars = List.of(car1, car2, car3);

assertThat(winner).contains(car3);
```

2022-09-29 06:37 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +    public Car(String carName, int position) {
생성자가 외부에 열려있다보니, 누군가가 실수로 `position` 값을 음수로 전달하는 경우도 있을 것 같아요.
`position` 값이 유효한지 검증하는 로직을 추가해보면 어떨까요?

2022-09-29 13:50 UTC, yeojin822 commented on src/main/java/racingcar/Car.java
> +    public Car(String carName, int position) {
미처 생각하지 못했네요 추가하겠습니다! 👍

2022-09-29 15:45 UTC, yeojin822 commented on src/main/java/racingcar/Race.java
> +    public List<Car> findWinner(List<Car> cars) {
감사합니다! 
그리고 다른질문이긴 한데 규칙4번에 대해 검색하다보니 규칙4번의 목적이 결합도를 낮추기 위한 것이라는 글을 봤는데요
혹시 스트림이 결합도에 영향을 미칠까요..?
굳이 따지자면 응집도... 에 가까운건 아닐까 생각했는데 찾아보다가 답을 모르겠어서 질문드립니다

2022-09-30 00:11 UTC, seondongpyo commented on src/main/java/racingcar/Race.java
> +    public List<Car> findWinner(List<Car> cars) {
stream 사용 시 규칙 4를 적용하는 건 가독성 향상이 목적이라고 보시면 될 것 같고,
말씀하신 결합도와 관련된 내용은 '디미터의 법칙'이라는 걸 찾아보시면 도움이 되실 것 같아요.
디미터의 법칙은 객체에서 값을 꺼내는 대신 메시지를 보내서 처리하라는 내용과도 연결됩니다.
https://limdingdong.tistory.com/10
https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/

2022-09-30 01:34 UTC, yeojin822 commented on src/main/java/racingcar/Race.java
> +    public List<Car> findWinner(List<Car> cars) {
감사합니다!

2022-09-30 04:12 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍
추가로 몇 가지 의견을 드렸는데 다음 단계에서 반영해보시면 좋을 것 같습니다.
마지막 리팩토링 단계도 힘내시고 즐거운 주말 되시길 바랍니다 🔥

2022-09-30 04:12 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +        }
유효한 자동차 위치 값의 조건과 예외 메시지가 일치하지 않아 보이네요. 0 이상이 되어야 하지 않을까요?

2022-09-30 04:12 UTC, seondongpyo commented on src/test/java/racingcar/CarTest.java
> +    void 생성자_음수입력() {
자동차 위치 값 검증 테스트 👍

2022-09-30 04:12 UTC, seondongpyo commented on src/main/java/racingcar/RacingCarApplication.java
> +            ResultView.printRace(Race.playRace());
`playRace()`가 2번 호출된다면 시도 횟수마다 자동차가 2번씩 이동하지 않을까요?

2022-09-30 04:12 UTC, seondongpyo commented on src/main/java/racingcar/Race.java
>  public class Race {
`Race` 클래스의 멤버와 메서드를 모두 `static`으로 작성하신 특별한 이유가 있으실까요?

2022-09-30 04:12 UTC, merged

2022-09-30 04:26 UTC, yeojin822 commented on src/main/java/racingcar/Race.java
>  public class Race {
Race를 경기장이라고 생각했을때
경기장 1개만 있으면 된다고 생각해서 추가로 인스턴스를 생성하지 않고 사용하려고 static을 사용했습니다.
혹시 static이 아니라 인스턴스를 생성해서 사용하는것이 더 나을까요 ?

2022-10-01 01:11 UTC, seondongpyo commented on src/main/java/racingcar/Race.java
>  public class Race {
좋은 생각입니다만, 요구사항이 변경되어 자동차 경주를 여러 번 수행해야 하는 상황이 발생하면 어떻게 될까요?
만약이지만 지금의 자동차 경주 애플리케이션이 크게 성공하여 웹 기반의 애플리케이션으로 변경되어야 한다면
멀티스레드 환경에서는 여러 요청이 `Race`에 접근하게 되니 의도한대로 동작하지 않을 가능성이 높아 보여요.
지극히 개인적인 의견이니 참고만 해주시고, 편하신 대로 진행하셔도 됩니다.