Step4 : 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #3753
Opened 2022-09-29 12:33 UTC by codeleesh

안녕하세요 리뷰어님

4단계 자동차 경주 미션 리뷰 요청드립니다.
3단계에서 주신 리뷰도 반영해보았습니다.

적절하게 패키지를 이동를 하고 싶어서 클래스를 옮기다가 문제가 생겼는지 커밋 내용이 많아졌습니다.
4단계도 객체간 분리를 잘 진행을 해보고 싶어서 고민을 하게 되었습니다.
`객체간 책임 분리 입장` 에서 분리가 잘 되었는지 코드 리뷰 받고 싶습니다.

추가로 3단계 질문 남겨주신 정적 팩토리 메소드 관련해서 댓글로도 달았지만 이곳에도 남겨놓겠습니다.

정적 팩토리 메소드 의 장점이라고 생각하는 부분은 다음과 같다고 생각이 듭니다.

생성자의 역할을 대신하면서 좀 더 가독성이 좋은 코드를 작성할 수 있도록 해준다고 생각합니다.
핵심적인 특징은 다음과 같습니다.

이름을 가질 수 있어서 사용하는 사람이 의도를 이해할 수 있습니다.
객체 생성을 캡슐화할 수 있어서 내부 상태를 외부에 들어내지 않고 외부에 필요한 부분만 제공할 수 있습니다.
사실 정리를 해보니 정적 팩토리 메소드 를 사용하는 부분에 대해서 필요없다는 생각이 들었습니다.

혹시 이외 장점말고 리뷰어님이 생각하시는 장점이 있으신가요?

2022-09-30 14:33 UTC, lxxjn0 commented
리뷰를 달기에 앞서 작성해주신 정적 팩토리 메서드에 대한 답변을 달아두도록 하겠습니다 :)

앞선 코드에서 제가 생성자와 정적 팩토리 메서드의 차이에 대해서 여쭤본 이유는 두 메서드가 동일한 파라미터를 받고 결국 동일한 행위를 하는 상태였기 때문이었어요! 말씀하신대로 정적 팩토리 메서드의 장점은 이름을 지을 수 있어서 사용자로 하여금 유의미한 정보를 전달할 수 있습니다. 하지만 그 꼴이 생성자와 동일하다면 해당 메서드의 장점이 정말 부각이 될 수 있는지 의문이 생길 수 있을 것 같아요!!

그래서 저의 경우를 예로 들자면 저는 생성자는 인스턴스가 가지는 필드를 추가적인 가공없이, 필드와 동일한 타입의 파라미터를 받아서 생성하는 경우 주로 사용하고 정적 팩토리 메서드는 생성자로 생성할 수 없는, 다른 타입의 파라미터를 받아서 객체를 생성해야 할 때 사용합니다. 아래 간단한 예를 들어볼게요.

```java
public class Names {
    private final List<String> names;

    public Names(List<String> names) {
        this.names = names;
    }

    public static Names from(String nameInput) {
        List<String> names = Array.stream(nameInput.split(","))
                .map(String::trim)
                .collect(Collectors.toList());

        return new Names(names);
    }
}
```

(여기서 바로 쓴 코드라 컴파일 오류가 나거나 조금 틀린 부분이 있을 수도 있습니다 ㅠㅠ)

저 같은 경우에는 앞서 말씀드린 것처럼 정적 팩토리 메서드를 '특정한 로직을 통해 객체를 생성'하거나 또는 '클래스의 필드와 다른 타입을 통해 객체를 생성'할 경우 사용하고 있습니다. 

당연히 클래스가 가지고 있는 필드와 다른 타입으로 객체를 생성하려고 한다면 분명 특정한 로직을 통해 타입 변경이 필요할 것이고, 이는 결국 첫번째 기준인 '로직을 통해 객체를 생성'하는 부분이 되므로 결국 두 가지 상황은 거의 일맥상통 할 것입니다. 

이렇게 명확한 기준을 통해서 생성자와 정적 팩토리 메서드를 구분지어 사용한다면 해당 코드를 보는 사용자는 어떠한 객체를 마주하더라도 생성자를 사용해서 생성할 때는 '아 아무런 가공없이 내가 전달하는 값을 객체가 가지게 되겠구나'를 인지할 수 있을 것이고, 만약 정적 팩토리 메서드를 사용하여 생성한다면 '내가 직접 가공을 해서 객체를 생성해야 하는 불편함을 정적 팩토리 메서드에 전달해주면 알아서 특정한 로직을 통해 객체를 생성해주겠구나'를 인지할 수 있을 것입니다.

이처럼 전체 프로젝트에 통일되는 관점이 있다면 이는 마찬가지로 코드의 가독성을 증가시키는 효과도 함께 낳을 수 있어요. 이러한 이유에서 이전 코드처럼 정적 팩토리 메서드가 단순히 생성자의 로직을 전달만 하는 의미로 사용되기엔 결국 생성자를 호출하는 것과 다를바가 없다고 생각이 들었어요.

지금과 같은 관점을 단순히 생성자, 정적 팩토리 메서드에만 적용하지 말고, 코드 전체적인 부분에서 본인이 가지는 관점이나 철학을 일관되게 가져가면서 코드를 작성한다면 더 좋은 코드를 작성할 수 있을 것 같아요!! 👍🏼

2022-10-01 14:06 UTC, lxxjn0 requested changes
상호님, 미션 구현하느라 수고 많으셨어요 👍🏼 추가된 요구사항에 대해서 적절히 잘 구현해주신 것 같네요 :) 

몇 가지 아쉬웠던 부분은 메서드나 변수 명 등 명명에 대해서 조금 더 고민해보면 좋을 것 같아요!! 메서드의 경우 메서드가 하는 행위와 이름이 일치하지 않는 경우가 종종 있었습니다. 그리고 도메인 로직에 UI 로직이 섞여 있는 경우가 많이 있었어요. getter 메서드에 getter 네이밍 형식이 지켜지지 않은 부분도 있구요. 

제가 남겨준 피드백 바탕으로 한번 코드 개선 부탁드리겠습니다 👍🏼

2022-10-01 14:06 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingScore.java
> +    private static final Map<Integer, List<RacingCar>> racingScores = new HashMap<>();
추가로 RacingCar 객체를 넘겨주기 보다는 출력을 위해서 필요한 값만 가지는 DTO를 한번 사용해 보는 것은 어떨까요? 인스턴스를 넘겨주게 된다면 Score 객체에서도 RacingCar 객체에 대한 접근이 가능해요. 불필요한 의존을 끊어낸다면 도메인 객체가 보다 안전하게 관리되고 사용될 수 있을 것 같아요!!

2022-10-01 14:06 UTC, lxxjn0 commented on src/main/java/racing/view/ResultView.java
> +    private ResultView() {}
클래스로 활용하기 위해 인스턴스화를 방지했군요!! 💯

2022-10-02 12:15 UTC, codeleesh commented on src/main/java/racing/controller/RacingCarsPlay.java
> +public class RacingCarsPlay {
네 그렇게 생각합니다!

2022-10-02 12:41 UTC, codeleesh commented on src/main/java/racing/domain/CarNames.java
> +    }
생성자와 정적 팩토리 메소드에 대해서 상세하게 리뷰 주신 내용 감사합니다.

한가지 궁금한 것은 검증 로직을 두는 곳이 생성자와 정적 팩토리 메소드 중 정해진 곳이 있나요?

생성자에 둔다면 검증 로직을 통일성있게 가져갈 수 있지 않을까 싶은 생각도 들어서요.

2022-10-02 12:41 UTC, codeleesh commented on src/main/java/racing/domain/CarNames.java
> +    public List<CarName> list() {
네 수정하겠습니다!

2022-10-02 12:51 UTC, codeleesh commented on src/main/java/racing/domain/CarNames.java
> +public class CarNames {
네 해당 클래스에서는 검증 로직만 진행을 하고 있는데, 하나의 클래스에서 합치도록 하겠습니다.

2022-10-02 12:51 UTC, codeleesh commented on src/main/java/racing/domain/RacingAttempt.java
> +    public void remain() {
적절한 동사로 수정하도록 하겠습니다.

2022-10-02 14:23 UTC, codeleesh commented on src/main/java/racing/domain/RacingScore.java
> +    private static int sequence = 0;
네 동시성 관리에 대한 위험성이 존재하는 부분을 간과했네요. 가이드 주신데로 수정해보겠습니다.

2022-10-02 14:24 UTC, codeleesh commented on src/main/java/racing/domain/RacingCars.java
> +    }
`CarName` 안에서의 역할로 가져간다면 더 좋을것 같습니다.

2022-10-02 14:25 UTC, codeleesh commented on src/main/java/racing/domain/RacingCar.java
> +    }
필요한 필드만 넘겨서 UI 로직에서 이를 조합해서 처리하면 좋을것 같습니다.

2022-10-02 15:14 UTC, codeleesh commented on src/main/java/racing/domain/RacingScore.java
> +    private static final Map<Integer, List<RacingCar>> racingScores = new HashMap<>();
네 리뷰 감사합니다. 그렇게 된다면 불필요한 의존을 끊어낼 수 있게 되네요!

2022-10-02 15:17 UTC, codeleesh commented on src/main/java/racing/domain/RacingCars.java
> +    }
원래 처음에 생각한 의도는 리뷰어님께서 해주신 부분으로 진행을 하였습니다.

그러다 메인 로직이 조금 무겁다는 생각이 들어서 객체 안으로 들어가게 되었습니다.

그러디보니 랜덤의 대한 테스트 부분이 어려워졌다는 것을 확인하게 되었습니다.

말씀해주신 부분으로 수정해본다면 랜덤의 대한 테스트 부분도 개선이 될것 같고 RacingCars 입장에서도 불필요한 의존도 필요없을것 같습니다.

2022-10-02 15:28 UTC, codeleesh commented on src/main/java/racing/domain/RacingCars.java
> +    public void enter(final MovingStrategy movingStrategy) {
테스트를 하기 위해서 열어두지는 않고 더 많은 테스트 케이스를 작성하여서 커버리지를 올리는 것이 맞다고 생각합니다.

해당 메소드는 리팩토링 하면서 잘못 작성한 것 같습니다. 수정하겠습니다.

질문 주신 답변에 대해서는, 
테스트를 하기 위해서 메소드를 열어둔다면 

가장 큰 부분은 클래스가 의도와 다르게 오염될 수 있고 이것은 오류를 만들어 낼 수 있다고 생각합니다.

2022-10-02 15:32 UTC, codeleesh commented
리뷰어님 안녕하세요, 소중한 리뷰 감사합니다.

내용들 반영하여서 다시 요청드립니다.

한가지 여쭤보고 싶은 부분은, 메소드명 또는 인스턴스 변수명을 지을때 방법 또는 참고하시는 자료가 있는지 궁금합니다.

일전에 공유해주신 자료는 알고 있는데 혹시 다른 참고하시는 자료가 있는지 궁금하여서 여쭤봅니다.

그럼, 소중한 리뷰 부탁드립니다.

감사합니다.

2022-10-04 18:43 UTC, lxxjn0 commented on src/main/java/racing/domain/CarNames.java
> +    }
저도 검증 로직의 경우 유형에 따라서 위치를 달리두고 있습니다. 실제 도메인의 필드에 대한 검증일 경우 생성자에, 정적 팩토리 메서드로 넘어온 파라미터에 대한 검증일 경우에는 정적 팩토리 메서드에 두는 편인 것 같아요!! 각 값이 어디서 검증되는 것이 적절한지를 생각해보면 명확한 위치가 나올 것 같아요 👍🏼

2022-10-04 18:46 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingCars.java
> +    public void enter(final MovingStrategy movingStrategy) {
좋은 답변 주셔서 감사합니다. public 메서드의 경우는 외부에 노출되는 메서드, 즉 해당 객체의 행위를 나타내고 이는 곧 해당 객체의 책임과 의미를 드러내기도 합니다. 추가로 언제든지 외부에서 접근할 수 있는 메서드, 즉 인터페이스와 같은 역할을 하는데 이러한 메서드는 개발자의 의도에 맞게 구현되고 계획되어야 합니다.

실제로 객체가 할 수 있는 행위들만 퍼블릭으로 열어둬야 하는데 테스트를 위한 메서드가 열린다면 이는 의도하지 않은 객체의 행위를 낳을 수도 있습니다. 이런 때문에 단순히 테스트만을 위한 퍼블릭 메서드는 적절하지 않다고 생각하고 말씀하신대로 오히려 다양한 테스트 케이스를 통해 내부 로직을 검증하는 것이 더 맞지 않을까 생각합니다 :)

2022-10-04 18:53 UTC, lxxjn0 approved these changes
상호님, 피드백 반영하시느라 수고 많으셨습니다 👍🏼 

제가 남겨준 피드백에 대해서 꼼꼼히 확인하시고 진행해주셔서 좋은 코드로 개선된 것 같아요!! 나머지 간단한 부분만 남겼으니 이는 확인만 해주시면 될 것 같아요!!

추가로 여쭤보신 질문에 대한 답변은 고민을 오래 하기도 하면서 누군가 이러한 변수 명 또는 메서드 명을 마주했을 때 납득할만한가?를 생각하고 진행하는 것 같아요!! 정말 해당 값들을 명확하고 정확하게 표현하는 이름인지, 그 이름에 걸맞는 의미를 가지거나 행위를 하는 것인지 등을 곰곰히 생각하고 고민하면서 이름을 짓는 것 같습니다. 

이름을 짓는 것이 생각보다 많은 시간이 소요되고 힘들긴 하지만 그렇게 고민한 만큼 명확한 이름을 가질 수 있고 객체도 명확하고 간결해지는 것 같아요!! :)

2022-10-04 18:53 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingCar.java
>      }
해당 로직은 여전히 자동차의 위치를 `-`로 표현한다는, 즉 UI 로직을 담고 있어요!! View 클래스에서 position을 getter로 가져와서 처리하면 UI 로직과의 의존을 끊어낼 수 있을 것으로 보여집니다.

2022-10-04 18:53 UTC, lxxjn0 commented on src/main/java/racing/dto/RacingCarDto.java
> +    }
dto에서 변환된 포지션을 가지기 보다는 단순히 int 값의 위치를 가지고 View에서 이를 처리하는 로직을 가진다면 UI 로직을 분리할 수 있을 것 같아요!!

2022-10-04 18:53 UTC, merged