자동차 경주 Step5
next-step/java-racingcar pull request #3767
Opened 2022-09-30 10:56 UTC by gumsu

안녕하세요 준호님.
벌써 마지막 스탭까지 오게 되었네요. 그동안 좋은 리뷰 해주셔서 감사합니다. 😇
덕분에 코드 짜는 법도 많이 배우게 되었고, 짧은 기간이지만 제가 성장할 수 있도록
도움을 주셔서 감사합니다. 마지막 리뷰도 잘 부탁드립니다.

controller 에는 어떠한 것이 들어가야할 지 모르겠어서 패키지만 만들어둔 상태인데,
그냥 application 클래스에 있는 것을 옮기면 되는걸까요??

2022-10-01 01:34 UTC, JunHoPark93 requested changes
안녕하세요~ 5단계 까지 구현하셨네요!
고생많으셨습니다. 피드백 몇가지 남겨두었는데 확인 후 반영 부탁드려요 😊
궁금한점 코멘트 남겨주셔요!

2022-10-01 01:34 UTC, JunHoPark93 commented on src/main/java/racinggame/RacingGameApplication.java
> +import racinggame.domain.RacingCar;
> controller 에는 어떠한 것이 들어가야할 지 모르겠어서 패키지만 만들어둔 상태인데,
> 그냥 application 클래스에 있는 것을 옮기면 되는걸까요??

패키지에 파일이 없어서 형상에 올라오진 않은거같어요~
<img width="766" alt="스크린샷 2022-10-01 오전 10 21 12" src="https://user-images.githubusercontent.com/20608121/193377636-33f02f44-74ac-4e6c-a13a-303d63995a3e.png">
넵 현재 구조에서는 이 클래스를 옮기는게 맞아보여요. 컨트롤러에서 입/출력 view와 domain을 바라보니 이동시켜주시면 될거같아요.

2022-10-01 01:34 UTC, JunHoPark93 commented on src/main/java/racinggame/domain/RandomMovingStrategy.java
> +    private static final int MAX_BOUND = 10;
잘 분리해보셨네요 👍 유연한 구조를 가져감으로써 이점을 뭐라고 생각하셨나요?

( + 컨벤션 다시 확인해주셔요. 컨벤션은 초기 미션에서는 사소한거라도 습관을 들이기 위해서 리뷰어들이 계속 이야기할거에요~)

2022-10-01 01:34 UTC, JunHoPark93 commented on src/main/java/racinggame/domain/RandomMovingStrategy.java
> +        return generateRandomNumber()>= MAX_POINT_TO_MOVE;
컨벤션 확인 부탁드려요 :)

2022-10-01 01:34 UTC, JunHoPark93 commented on src/main/java/racinggame/domain/RacingCar.java
> +        return cars.stream()
이부분은 참고만 해보셔요!
내부적으로 스트림을 두번을 돌고있는데요, 한번 수행으로 할 수 있을까요?

💡 참고 키워드: max, sorted, compare

2022-10-01 01:34 UTC, JunHoPark93 commented on src/main/java/racinggame/domain/Car.java
> +package racinggame.domain;
name 속성은 final로 가져가면 어떨까요?

2022-10-02 10:15 UTC, gumsu commented on src/main/java/racinggame/domain/RandomMovingStrategy.java
> +    private static final int MAX_BOUND = 10;
테스트 하기 힘든 부분을 분리해서 테스트 가능한 구조로 변경 된게 가장 큰 이점인 것 같습니다.!

2022-10-02 11:06 UTC, gumsu commented on src/main/java/racinggame/domain/RacingCar.java
> +        return cars.stream()
말씀하신 부분 수정해보았는데, 이게 맞는지 모르겠습니다......!!

2022-10-03 01:19 UTC, JunHoPark93 commented on src/main/java/racinggame/domain/RandomMovingStrategy.java
> +    private static final int MAX_BOUND = 10;
넵 이번 미션에서 중요한 부분에 대해서 잘 이야기해주셨어요! 테스트코드 뿐만 아니라 실제 프로덕션코드에서도 장점을 느끼실수있는데요, 미션을 진행해보시면서 경험하실거같아요 👍

2022-10-03 01:38 UTC, JunHoPark93 approved these changes
안녕하세요 끝까지 리뷰 반영 잘 해주셨습니다 🙏
궁금한게 남아있으면 다시 말씀주세요.
고생많으셨어요. 꼭 완주하시길 바랍니다 👍

2022-10-03 01:38 UTC, merged