[자동차 경주] 3단계 - 자동차 경주
next-step/java-racingcar pull request #3770
Opened 2022-09-30 14:07 UTC by lyle0101

안녕하세요! 이번 자동차 경주 3단계를 구현하면서 몇 가지 궁금한 점이 있어 남깁니다.

1. 요구 사항별로 커밋을 분리해서 구현해보려고 했는데 저는 코드를 짤 때 전체적인 그림을 그리면서 맞춰나가는 편이라 커밋 분리가 어려웠습니다. 혹시 이런 경우에 권장하시는 방법이 있을까요?
2. UI 관련 클래스를 제외하고 단위 테스트 코드를 작성했는데, 일부 코드는 테스트가 어려웠습니다. 예를 들어 로직상 랜덤하게 값이 결정되는 경우, 함수 실행 여부만을 검사해야 하는 경우, 또는 getter 가 없는 멤버 변수에 대한 테스트 등이 있었습니다. 그래서 테스트를 많이 작성하지 못했는데, 제가 나열한 경우에 대해서는 어떻게 테스트를 하는게 좋을까요?

감사합니다.

2022-09-30 14:45 UTC, younlll requested changes
안녕하세요 지수님!
몇 가지 코멘트와 질문에 대한 저의 생각을 남겨두었습니다~
확인 하시고 다시 리뷰 요청 부탁드립니다 🙏

2022-09-30 14:45 UTC, younlll commented on README.md
> +## Step 3 기능 목록
기능 요구사항 정리 👍👍

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/Car.java
> +    private static final Random random = new Random();
내부에서만 사용되고 재할당 되지 않아 상수로 선언해주셨네요! 👍👍
변수명은 대문자로 바꿔주시면 좋을 것 같습니다~

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/Car.java
> +    }
random값을 통해 움직임의 여부를 결정하는 역할이 Car의 역할일까요?? 🤔
지수님의 생각이 궁금합니다~ 🙂

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/Race.java
> +    private final List<Car> cars = new ArrayList<>();
여러 대의 자동차를 관리하기 위해 컬렉션을 사용해주셨는데요~
일급 컬렉션을 활용해보는건 어떨까요?
https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/RaceInput.java
> +    }
음수가 입력되는 경우의 처리는 어떻게 되는걸까요? 🤔

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/RaceInput.java
> +    private static final Scanner scanner = new Scanner(System.in);
내부에서만 사용되며 재할당 되지 않기때문에 private static final 선언을 해주셨군요!! 👍👍

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/RaceInput.java
> +public class RaceInput {
유틸리티 클래스로 보이는데 인스턴스 메소드와 인스턴스 변수를 사용하지 않고 정적 메소드와 정적 변수를 이용하면서
유틸리티 클래스의 인스턴스화를 방지 해보는건 어떨까요?

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/RaceOutput.java
> +public class RaceOutput {
RaceInput 클래스의 리뷰랑 같이 봐주시면 좋을 것 같습니다~

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/RaceOutput.java
> +    private final List<Car> cars;
변수로 선언하지 않고도 자동차 별 이동거리를 표시하는 것이 가능할것 같습니다~

2022-09-30 14:45 UTC, younlll commented on src/main/java/step3/Step3.java
> +        }
자동차 경주를 컨트롤하는 역할을 갖는 클래스를 만들어 보는건 어떨까요?

2022-09-30 14:45 UTC, younlll commented on src/test/java/step3/CarTest.java
> +public class CarTest {
Random값에 대한 전진과 정지 동작을 테스트 해보고 싶으시다면 `전략패턴`을 활용해 보시면 좋을것 같습니다!

2022-09-30 14:51 UTC, younlll commented
> 질문1. 요구 사항별로 커밋을 분리해서 구현해보려고 했는데 저는 코드를 짤 때 전체적인 그림을 그리면서 맞춰나가는 편이라 커밋 분리가 어려웠습니다. 혹시 이런 경우에 권장하시는 방법이 있을까요?

제가 요구 사항별 커밋이란 말이 지수님을 헷갈리게 만든거 같네요 😥
구현하시는 작은기능들의 단위를 하나씩 커밋해주시면 될 것 같습니다!
예를들어 Car 클래스를 구현 중 먼저 자동차 위치에 대한 기능을 구현을 했다면 `feat: 자동차 위치에 대해 구현`이라는 커밋 메시지를 남겨주시고
그 다음 해당 기능에 대해 테스트를 했다면 `test: 테스트 내용~`을 남겨주시는 방식으로 진행하시면 될 것 같습니다.



> 질문2. UI 관련 클래스를 제외하고 단위 테스트 코드를 작성했는데, 일부 코드는 테스트가 어려웠습니다. 예를 들어 로직상 랜덤하게 값이 결정되는 경우, 함수 실행 여부만을 검사해야 하는 경우, 또는 getter 가 없는 멤버 변수에 대한 테스트 등이 있었습니다. 그래서 테스트를 많이 작성하지 못했는데, 제가 나열한 경우에 대해서는 어떻게 테스트를 하는게 좋을까요?

코멘트로 남겨드린 역할과 책임을 분리하시고 main에서 자동차 경주에 대해 컨트롤하는 별도의 클래스를 만들어 분리한다면 테스트 코드 작성이 조금 더 쉬워지지 않을까라는 생각이 듭니다!

추가로 궁금하신 점이나 이해가 안가시는 부분이 있다면 질문 주신 것처럼 편하게 연락 주시면 감사하겠습니다~

2022-10-01 01:28 UTC, lyle0101 commented on src/main/java/step3/Car.java
> +    private static final Random random = new Random();
`private static final` 로 선언하긴 했지만 상수라기 보다는 한 번 선언하고 공유하는 객체로써의 느낌이라고 생각해서 대문자로 선언하지 않았는데 이런 경우에도 보통 대문자로 선언하는게 일반적인가요? RaceInput.java 의 scanner 와 동일하게 생각했습니다!

2022-10-01 01:31 UTC, lyle0101 commented on src/main/java/step3/Race.java
> +    private final List<Car> cars = new ArrayList<>();
앗 이전에 일급 컬렉션으로 구현한 사례를 봤었는데 이름도 모르고 올바른 방법인지도 몰라서 일급 콜렉션으로 구현하지 않았네요 😂

2022-10-01 01:32 UTC, lyle0101 commented on src/main/java/step3/RaceInput.java
> +    }
음수가 입력되는 경우에는 예외 처리를 해야할 것 같습니다! 요구 사항에만 집중하다 보니 빼먹었네요 😅

2022-10-02 01:40 UTC, younlll requested changes
안녕하세요!
리뷰 내용 중 변경이 필요한 부분은 수정과 리팩토링을 거쳐 다시 리뷰 요청해주시면 되겠습니다!

2022-10-06 16:52 UTC, younlll approved these changes
안녕하세요. 지수님!
3단계 미션 잘 구현해주셨네요!!

많은 고민과 노력한 부분들이 코드에서 잘 느낄 수 있었습니다! 👍👍

몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다.

이번 단계는 이만 머지하도록 하겠습니다!
다음 단계도 파이팅입니다! 🔥

2022-10-06 16:52 UTC, younlll commented on README.md
> +* 자동차의 상태를 화면에 출력한다.
요구사항 정리 👍

2022-10-06 16:52 UTC, younlll commented on src/main/java/step3/Step3.java
> +        raceManager.startRace();
main 에서 주입을 통해 생성과 사용이 분리된점 👍

2022-10-06 16:52 UTC, younlll commented on src/main/java/step3/RaceInput.java
> +    private static final Scanner scanner = new Scanner(System.in);
불변 및 내부에서만 사용되며 재할당 되지 않는 부분에 대한 처리 👍

2022-10-06 16:52 UTC, younlll commented on src/main/java/step3/RandomStrategy.java
> +public class RandomStrategy implements MovableStrategy {
전략 패턴 적용 💯👍

2022-10-06 16:52 UTC, younlll commented on src/main/java/step3/Car.java
> +    }
전진 전략, 멈춤 전략을 세워서 자동차가 정상적으로 전진하는지 혹은 멈추는지 테스트가 가능해보입니다!

2022-10-06 16:52 UTC, younlll commented on src/main/java/step3/RaceInput.java
> +        this.numberOfTry = Integer.parseUnsignedInt(scanner.next());
음수 입력에 대한 방지 👍

2022-10-06 16:53 UTC, merged