Step4 : 자동차경주(우승자)
next-step/java-racingcar pull request #3771
Opened 2022-09-30 14:22 UTC by Parkyunhwan

안녕하세요! lowoon님!

오랜만에 PR드리는 것 같네요 ㅎㅎ..
이번에도 잘 부탁드립니다.

이번에는 저번 스텝에서 리뷰 주신 것 기반으로 리팩토링 진행한 것과 우승자 뽑는 것을 문서로 정리하면서 개발진행하였습니다.
문서 먼저 정리하니 기능별로 커밋을 찍기가 편한 것 같네요..!

2022-10-01 07:09 UTC, lowoon requested changes
안녕하세요 윤환님!
4단계도 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/RacingCarApplication.java
> +        String answer = InputView.askQuestionAnswer("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분");
질문할 내용을 parameter로 넘겨주고 있는데요.
사용자에게 어떻게 보여줄지는 view의 역할이라고 볼 수 있을텐데요.
어떻게 생각하시나요?
메세지가 변경될때 view가 아닌 application이 수정되고 이 수정을 인해 application내 로직이 영향을 받을 수 있지 않을까요?

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/RacingCarApplication.java
> +        RacingGame racingCar = new RacingGame(tryNums, names);
변수이름이 racingCar보다는 racingGame이 더 명확하지 않을까요??

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    public static int askQuestionAnswerInt(String question) {
위의 askQuestion 메서드는 사용되지 않는것 같아요!

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +            return Integer.parseInt(str);
int로의 변환까지 view의 역할로 본 것일까요??
view의 역할과 책임을 어떻게 정의하셨을까요??

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/Positive.java
> +public class Positive {
PositiveNumber가 더 명확하지 않을까요??

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/RoundCars.java
> +        names
생성자 내에서 forEach로 cars에 넣어주는 것이 아닌 List<Car>를 만들어서 할당할 수도 있지 않을까요?

2022-10-01 07:09 UTC, lowoon commented on src/main/java/racingcar/RoundCars.java
> +        RoundCars roundCars = new RoundCars();
해당 메서드가 밑의 `deepCopy`메서드에서만 사용되는데 필요할까요??
deepCopy 메서드명도 getRoundCars로 하고 get안에서 새로운 객체로 감싸서 return하도록 할 수 있지 않을까요??

2022-10-02 11:33 UTC, Parkyunhwan commented on src/main/java/racingcar/view/InputView.java
> +            return Integer.parseInt(str);
저는 View의 역할과 책임을 일반화된 입력을 받아 사용자가 원하는 타입으로 반환해주는 것으로 정의하였습니다.
그래서 InputView에는 어떤 특정할 질문도 없고 Application에서 질문을 넘기고 답변을 받는 형식으로 만들었습니다.
RacingCarAppilcation 이니 main메서드에서 RacingCar에 대한 질문을 넘겨줘도 되지 않나요? InputView는 RacingCar와 관련되지 않는 다른 도메인에서도 쓰일 수 있는 클래스라고 생각했습니다.

2022-10-02 11:38 UTC, Parkyunhwan commented on src/main/java/racingcar/RoundCars.java
> +        names
추천 감사합니다! 혹시 기존 방식에 비해 어떤 장점이 있을 지 알 수 있을까요?

2022-10-02 12:00 UTC, Parkyunhwan commented on src/main/java/racingcar/RoundCars.java
> +        RoundCars roundCars = new RoundCars();
createRoundCars 는 deepCopy에만 쓰이고 있어서 private 일반 메서드로 변경하였습니다!

deepCopy 메서드명은 새로운 인스턴스로 반환한다 라는 의미를 표현하기 위해 사용하였습니다.

2022-10-02 12:03 UTC, Parkyunhwan commented on src/main/java/racingcar/RacingCarApplication.java
> +        String answer = InputView.askQuestionAnswer("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분");
RacingCarAplication이니 이를 위해 어떤 질문을 할지 Application에서 넘겨줄 수 있지 않나요? 저는 InputView를 RacingCar뿐만아니라 다른 클래스도 사용할 수 있는 클래스로 만들기 위해 입력을 받도록 만들었습니다.
InputView에 특정메시지를 가지고 있으면 RacingCar에 의존되는 거라고 볼 수 없나요?

2022-10-02 12:04 UTC, Parkyunhwan commented on src/main/java/racingcar/RacingCarApplication.java
삭제하였습니다

2022-10-02 12:51 UTC, Parkyunhwan commented on src/main/java/racingcar/RacingCarApplication.java
> +    public static final int FORWARD_CONDITION_LOW_BOUND = 2;
저는 Moving 조건을 RacingGame 밖에서 주입하여 결정할 수 있도록 하려고 했습니다. (움직이는 기준을 바꿀 수 있도록)
RacingGame의 움직임 조건이 게임마다 바뀔 수 있으니 밖에서 주입받아도 되지 않나요?
application의 역할은 RacingGame의 실행을 위해 필요한 값을 받고 필요한 설정을 수행하여 racing을 하는 것이라고 생각합니다.

lowoon님의 피드백을 받아 움직임에 대한 기준을 RacingGame으로 옮겼고 RacingGame의 움직임 전략을 언제든지 바꿀 수 있도록 chageMovingStrategy() 메서드를 추가하였습니다..!

2022-10-03 07:08 UTC, lowoon commented on src/main/java/racingcar/RacingCarApplication.java
> +    public static final int FORWARD_CONDITION_LOW_BOUND = 2;
그 부분은 요구사항에 맞지 않는 부분이라고 생각되는데요. 
추후를 고려해 조건을 주입받는 형식으로 한다고 했을 경우에도 입력받은 값을 application에서 관리 혹은 수정하는 것이 아닌 game에 전달해야하지 않을까요?
부분 또한 자동차 경주의 비지니스 로직이니까요

application은 흐름에 대한 제어의 역할만 할 뿐 비지니스 로직에는 관여를 하지 않아야 한다고 생각합니다.

2022-10-03 07:25 UTC, lowoon commented on src/main/java/racingcar/RacingCarApplication.java
> +        String answer = InputView.askQuestionAnswer("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분");
현재의 구조에서 다른 곳에서 사용하는 경우를 고려하지는 않았구요.
고려를 할 경우에도 각각의 경우에 따라 view를 새로 만들어 주거나 각각의 경우에 맞는 메서드를 만들어 주어야하지 않을까요?
사용자에게 어떻게 보여줄지에 대한 역할은 view가 맡고 있다고 생각되는데, 이 역할을 application에서 하는 것은 아니라고 생각되서요.
만약에 하나의 어플리케이션에서 자동차 게임 이후에 로또게임이 진행이 된다고 하면 이때도 application에서 메세지를 입력해주는 걸까요?

도메인과 함께 view에 대해서 이야기할 때, 역할과 책임에 대해서 여쭤보고 있는데요.
객체지향에서 항상 이야기하는 부분이 역할과 책임이라고 생각합니다. 객체라는 것을 분리를 할 때 고려해야 하는 부분이니까요.
재사용성이 아닌 역할과 책임, 객체가 해야하는 일에 대해서 생각할 때 맞는 것 같은지 생각해보시면 좋을것 같아요.

2022-10-03 07:33 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +            return Integer.parseInt(str);
화면, 즉 view와 관련된 부분은 각각의 상황이나 web, pc등 client에 따라 다른 형식으로 보여질 수 있을텐데요.
이렇게 화면의 경우에는 여러 client에 맞추기위해서 종속적으로 바뀌게 되는 부분이라고 생각을 합니다.
그렇기 때문에 서버에서는 데이터만 넘겨주고 client에서 어떻게 보여줄지를 정한다고 생각하거든요.

2022-10-03 08:14 UTC, lowoon approved these changes
안녕하세요 윤환님!
리뷰반영 잘해주셨네요 👍 
질문에 답변 남겼고, 코멘트도 남겼으니 확인해 주세요ㅎㅎ
step4는 이만 머지하도록 하겠습니다~

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-03 08:14 UTC, lowoon commented on src/main/java/racingcar/RacingGame.java
> +            roundCars.moveCars(racingRecord, movingStrategy);
racingRecord를 moveCars의 파라미터로 넘겨서 내부에서 자기 자신을 racingRecord를 넘기고 있는데요.
이 방법이 아닌 moverCars후에 roundCars에서 cars를 가지고 와서 racingRecord에 넘겨주거나 moveCars가 매판에 대한 결과인 RoundRecord를 return 하도록 해서 그 객체를 racingRecord에 넘겨주는게 어떨까요?
racingCars는 자동차들에 대한 관리만 담당을 하고 있는데 racingRecord를 알아야 할까요?
게임의 흐름 관리를 game에서 하고 있으니 매판 이동 후 결과를 저장하는 흐름은 racingGame에서 관리를 해줘야하지 않을까요?

2022-10-03 08:14 UTC, lowoon commented on src/main/java/racingcar/view/ResultView.java
> +            print("");
""를 출력해야하나요?
그리고 위에 printStartMessage메서드가 있는데 메서드로 분리할 필요가 있을까요?

2022-10-03 08:14 UTC, lowoon commented on src/test/java/racingcar/RacingGameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
어떤 에러가 발생했는지 정확하게 확인해야하지 않을까요?

2022-10-03 08:15 UTC, merged