🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #3791
Opened 2022-10-02 07:01 UTC by BosukNam

말씀 주신 부분 추가로 반영 + 패키지를 분리하여 리팩토링 하였습니다.
변경 내용은 아래에 작성하였습니다.
감사합니다~! 👍

- controller, service, domain, view 패키지 분리 및 클래스 작성
- Cars 에 있던 generator 사용부를 Car 클래스로 이동 (move 시 generate 값 확인하여 이동)
- Winner 클래스 내 static 메소드를 일반 public 메소드로 변경 -> List 가 리턴되지 않도록 수정 (받는 쪽에서 조작 불가. size 만 리턴)
- InputView 클래스에서 자동차 이름 파싱 및 5글자 초과 방지로직 수행하도록 이동
- CarsTest 내 Car 개별이동 테스트를 CarTest 로 이동

2022-10-03 11:49 UTC, ksy90101 requested changes
안녕하세요 :) 리뷰어 김세윤입니다.
5단계까지 너무 고생 많으셨습니다 💯 
간단한 피드백을 남겨봣습니다. 확인해주시면 감사하겠습니다.
언제든 질문은 환영이니, DM으로 연락주세요~

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/service/RacingGameService.java
> +public class RacingGameService {
Service가 숫자를 만드는 Generator를 가지고 잇다면, 여기 메서드들도 테스트 코드를 작성할수 있지 않을까요?
현재는 바로 주입을 하는듯 하네요.

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Cars.java
> +        }
```suggestion
        for (Map.Entry<String, Car> entry: cars.entrySet()) {
            entry.getValue().move();
        }
```
이런식으로 변경해볼수 있을듯 하네요.
아니면
```
for (Car car: cars.values()) {
            car.move();
        }
```
이런식도 있을꺼같습니다 :)

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Cars.java
> +        return cars.size();
cars.size()는 int로 나오는데 굳이 이걸 Integer로 변경해야 할 필요가 있을까요?

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Cars.java
> +    private final Map<String, Car> cars;
질문이 있습니다!
혹시, Cars를 Map으로 구현하신 이유가 있을까요~?

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final NumberGenerator numberGenerator;
상수와 필드는 개행으로 분리해두면, 가독성이 더 올라갈듯 합니다.

```suggestion
    public static final Integer MIN_VALUE_TO_MOVE_CAR = 4;
    
    private final Position position;
    private final NumberGenerator numberGenerator;
```

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final NumberGenerator numberGenerator;
각 Car마다, NumberGenerator를 가지고 있어야 할 필요가 있을까요?
해당 상태는 누가 가지면 좋을지 한번 고민해보시면 좋을거 같아요.

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final String name;
Name도 결국 원시값일듯 한데, 한번 포장해보면 어떨까요?
제가 알기론 Validate가 존재하는걸로 알고 있습니다!

2022-10-03 11:49 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/Car.java
> +        this.position = new Position();
외부 주입을 한번 고려해보시면 어떨까요?
그렇다면 쉽게 우승자 Car를 만들어서 유연하게 테스트 코드를 작성할수 있을듯 한데요.

2022-10-03 14:13 UTC, BosukNam commented
피드백 감사합니다~! 관련 내용 다시 반영해보았습니다.
좋은 의견 감사합니다!! 😁

- Car Position 주입으로 변경
- CarName 객체 추가
- Cars 내 map 객체 list로 변경, winner 가져오는 메소드 추가 (Winner 클래스에서 삭제)
- Winner 클래스는 static 만 가지도록 수정
- RacingGameService 에서 NumberGenerator 활용하도록 수정
- 관련 테스트 코드 추가, 수정

2022-10-03 14:15 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Cars.java
> +        }
좋은 의견 감사합니다. 해당 내용은 Map 객체에서 List 객체로 변경되어서 나중에 Map을 사용할 때 참고 해보겠습니다!

2022-10-03 14:15 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Cars.java
> +        return cars.size();
좋은 의견 감사합니다. 해당 내용 반영해보았습니다!

2022-10-03 14:16 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Cars.java
> +    private final Map<String, Car> cars;
좋은 의견 감사합니다. 해당 내용은 Map 객체에서 List 객체로 변경했습니다! 
개별 자동차의 움직임을 테스트 하려고 저렇게 작성했다가 다시 원복했어요~!

2022-10-03 14:16 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final NumberGenerator numberGenerator;
좋은 의견 감사합니다. 해당 내용 반영해보았습니다!

2022-10-03 14:16 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final NumberGenerator numberGenerator;
좋은 의견 감사합니다. 해당 내용 반영해보았습니다! (서비스 객체가 가지도록 수정)

2022-10-03 14:16 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Car.java
> +    private final String name;
좋은 의견 감사합니다. 해당 내용 반영해보았습니다!

2022-10-03 14:17 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/Car.java
> +        this.position = new Position();
좋은 의견 감사합니다. 해당 내용 반영해보았습니다!/
사실 우승자 Car 반환은 stream filter를 사용하긴 해서 position 외부주입으로 바꾸어도 큰 변경점은 찾지 못했어요 😅

2022-10-04 11:10 UTC, ksy90101 commented on src/main/java/com/game/racing/domain/car/CarName.java
> +        }
validate를 메소드로 추출해두면, 어떤 validate인지 가독성을 높일수 있을듯 하네요!

2022-10-04 11:11 UTC, ksy90101 commented on src/test/java/com/game/racing/domain/car/CarTest.java
> +        car.move();
움직였다느걸 어떻게 보장할수 있나요?
간헐적으로 테스트 코드가 깨질듯 하네요.

2022-10-04 11:12 UTC, ksy90101 approved these changes
안녕하세요 :)
5단계까지 너무 잘 구현해주셨네요 💯 
간단한 피드백을 남겼지만, 머지를 진행하여 충분하다고 생각되어, 머지하도록 하겠습니다.
다음미션인 로또도 파이팅입니다!!

2022-10-04 11:12 UTC, merged

2022-10-04 13:05 UTC, BosukNam commented on src/main/java/com/game/racing/domain/car/CarName.java
> +        }
좋은 의견 감사합니다! 머지는 됐지만 개인 깃헙 프로젝트에는 반영해볼게요~!