자동차 경주 - 4단계
next-step/java-racingcar pull request #3800
Opened 2022-10-02 13:36 UTC by samkimuel

안녕하세요 세윤님! 4단계 리뷰도 잘 부탁드립니다🙇‍♂️

질문 사항은 코드 코멘트로도 남겨놓겠습니다! 감사합니다~!

### 질문
- Cars 클래스가 우승자들 선정하는 책임을 가지게 하고 ResultView 클래스가 우승자들 이름을 추출하여 출력하는 책임을 가지게 했는데, 우승자들 이름을 추출하는 역할을 ResultView가 맡는게 이상하지는 않을까요?

2022-10-02 13:37 UTC, samkimuel commented on src/main/java/racingcar/step3_4/ResultView.java
> +	}
우승자 이름을 추출하는 부분인데, 여기서 해도 괜찮을까요??

2022-10-03 12:58 UTC, ksy90101 requested changes
안녕하세요 :) 리뷰어 김세윤 입니다!
4단계도 고생 많으셨습니다!!
간단한 피드백을 좀더 남겨봣는데, 한번 확인해주세요.
아울러, 패키지에 대한 정리도 필요해 보입니다. 각 뭉쳐놔야 하는 클래스 파일들을 패키지로 잘 정리해보시면 좋을듯 합니다.
언제든 질문이 있다면 DM으로 요청주세요~

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Cars.java
> +			.getAsInt();
max값이 null이 나올수도 잇지 않을까요?
.orElseThrow()가 더 어울릴듯 해요.

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/InputView.java
> +    public InputView() {
굳이 기본생성자를 명시 해야 할까요?

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Car.java
> +	private Name name;
Name은 불변이여야 하지 않을까요?
이름이 변경되면 이상할꺼 같아서요!

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Cars.java
>  		}
```
carNames.getNames().stream().map(Car::new).collect(Collectors.toList())
```

스트림을 이용하면 이렇게 간단하게 작성할수 잇을듯 하네요 :)

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Cars.java
> +	}
한번 객체로 Winners를 만들어서 처리해보면 어떨까요?

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/GameAttribute.java
> +	private final List<String> carNames;
Names라는것을 만들어두고, 여기선 Names를 안쓰는 이유가 무엇인가요?

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Name.java
> +    }
InputValidator

여기에 해당 로직이 있는듯 한데,굳이 중복해야 할까요?

2022-10-03 12:58 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Name.java
> +    private final String name;
상수와 필드는 개행을 두고 구분해놓으면 어떨까요?

2022-10-03 13:11 UTC, samkimuel commented on src/main/java/racingcar/step3_4/Cars.java
> +			.getAsInt();
max값이 존재할 수밖에 없다고 생각해서 값을 받도록 작성했는데, 이곳에서도 체크를 하는 게 좋겠네요.

2022-10-03 13:53 UTC, samkimuel commented on src/main/java/racingcar/step3_4/Name.java
> +    }
InputView에서는 InputValidator에 의존해서 검증을 진행하는데,
Name 도메인 클래스에서 필요한 검증로직을 InputValidator에 작성하면서 InputValidator에 의존해야할까? 라는 의문을 가지고 클래스 내에 검증로직을 작성했습니다. 코드 중복은 감안하더라도 의존은 안하는 방향이 좋을 것 같다고 생각했어요. 만약 검증 로직을 InputValidator에 담는다면 Name이 InputValidator를 의존해도 괜찮을까요?

2022-10-03 13:57 UTC, samkimuel commented on src/main/java/racingcar/step3_4/GameAttribute.java
> +	private final List<String> carNames;
InputView에서 입력한 데이터를 Game으로 전달하는 DTO 역할을 목적으로 만들었는데,
InputView에서 입력받은 데이터를 도메인 객체로 만들어서 전달해주기보다 좀 더 raw한 데이터를 전달하도록 했어요.
InputView에서 Names 도메인 객체를 생성해서 전달해준다면 도메인에 의존하게 되는 것 같다는 느낌이 들어서요!

2022-10-05 14:56 UTC, samkimuel commented on src/main/java/racingcar/step3_4/Cars.java
> +	}
Winners 객체로 포장해서 전달하도록 수정하면서 ResultView에서 컨버팅하도록 했습니다.

2022-10-06 11:20 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/GameAttribute.java
> +	private final List<String> carNames;
Names가 도메인이군요. 저는 VO로 보긴 했는데 ㅎㅎ

2022-10-06 11:20 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/Name.java
> +    }
Validator를 도메인에 의존을 안하는 이유가 있나요?

2022-10-06 11:22 UTC, ksy90101 approved these changes
안녕하세요 :)
4단계도 고생 많으셨습니다 💯 
수정해주셔서 전체적으로 깔끔해 져서 이만 머지하도록 할게요.
5단계떄 리팩토링 파이팅입니다!!

2022-10-06 11:22 UTC, merged

2022-10-10 06:26 UTC, samkimuel commented on src/main/java/racingcar/step3_4/Name.java
> +    }
만약 InputValidator의 메서드를 사용한다면 추후에 Name 관련된 요구사항이 변경될 경우 InputValidator까지 수정해야하는 경우가 발생할 것 같았어요. 그렇게 수정되면 다른 데까지 영향이 전파될 수도 있을 것 같았습니다.  다른 객체와 결합도가 올라가면 좋지 않을 것 같다는 생각이 들어서 이렇게 작성했었습니다.