🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #3801
Opened 2022-10-02 15:12 UTC by GimunLee

안녕하세요. 리뷰 부탁드립니다. 감사합니다!

## 질문

* Track 클래스에서 자동차 움직임을 출력하고 있는데 이게 메인으로 가는게 나을까요? 다른 사람이 main을 처음 봤을때 track.start()하고 끝나는게 어색할 수 있겠다는 생각이 불현듯 들어서 질문드립니다.

2022-10-03 04:56 UTC, bingbingpa requested changes
주말에도 열심히 미션 진행해주셨네요! 👍
질문 주신 내용 포함해서 몇가지 코멘트 남겨드렸는데
한 번 확인해보시고 다시 한번 리뷰 요청 부탁드립니다.🙏

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/BasicEngine.java
> +    private int movableNumber = DEFAULT_MOVABLE_NUMBER;
둘중에 하나의 변수만 있으면 되지 않을까요?

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/Car.java
> +    private static final Random random = new Random();
자동차 클래스는 어떤 조건에 따라 position 을 변경하는 역할을 하는거 같은데요.
랜덤이라는 역할까지 함께하고 있어요.
이부분을 별도로 분리해보는건 어떨까요? 
`Engine` 이라는 인터페이스를 만들었으니 이를 구현한 클래스 자체에서 랜덤한 값에 의해 이동가능여부를 리턴하도록 해보는건 어떨까요?

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/Car.java
> +        if (engine.canMove(random.nextInt(9))) {
9가 어떠한 값을 의미하는지 상수로 나타내주면 더 좋을거 같아요.

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/InputView.java
> +        }
`InputView` 는 사용자로부터 값을 입력받는 역할이라고 생각하는데
여기서 validation 까지 하고 있어요.
이부분은 별도의 value class 로 만들어서 validation 의 역할을 하도록 해보는건 어떨까요?
그리고 try catch 를 사용하는 비용이 작지는 않기 때문에 이를 정규식으로 validation  해보는건 어떨까 생각합니다.

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/RacingGame.java
> +        }
메인에서 어떠한 비즈니스 로직을 수행하기 보다는 이를 직접 사용하는 클래스에서 하는건 어떨까요?

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/Track.java
> +    private final Car[] cars;
특별한 경우가 아니라면 배열보다는 리스트를 사용하는게 좋다고 생각해요.
이와 관련해서 참고할만한 링크 하나 남겨드릴게요.
[링크](https://velog.io/@banjjoknim/%EC%95%84%EC%9D%B4%ED%85%9C-28.-%EB%B0%B0%EC%97%B4%EB%B3%B4%EB%8B%A4%EB%8A%94-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)

2022-10-03 04:56 UTC, bingbingpa commented on src/test/java/racing/RacingGameTest.java
> +        car.setEngine(new BasicEngine(-1));
테스트를 위해 `Car` 클래스에 불필요하게 `setEngine` 이라는 메소드가 열러 있다는 생각이 들어요. 
위에서도 언급드렸지만 자동차 클래스는 Engine 이라는 인터페이스 타입을 받아 canMove() 를 호출만 하는
형태라면 별도의 setter 는 필요 없을거 같아요.

2022-10-03 04:56 UTC, bingbingpa commented on src/main/java/racing/Track.java
> +    }
질문주신 부분에 대한 제 생각은 지금 구현하신 방식대로 해도 크게 상관은 없다고 생각해요.
다만 지금처럼 출력과 관련된 부분을 Track 에서 직접 수행하기 보다는 
출력 부분은 따로 리턴해서 출력을 담당하는 클래스에서 해주는게 좋다고 생각해요. 
Track 클래스는 전체적인 게임을 진행하는 클래스처럼 보이는데 
만약 출력과 관련된 요구 사항이 변경되면 이 클래스도 불필요하게 변경이 필요할거 같아요.

2022-10-03 04:56 UTC, bingbingpa commented on src/test/java/racing/RacingGameTest.java
> +public class RacingGameTest {
테스트는 하나의 문서 역할도 한다고 생각하는데요.
그래서 가급적이면 테스트 클래스명은 해당 클래스와 일치해야 보기가 더 좋다고 개인적으로 생각해요.
여기서는 `Car` 클래스에 대해 테스트 하고 있으니 `CarTest` 와 같은 이름은 어떨까요? 
그리고 전반적으로 테스트가 조금 부족하지 않나라는 생각이 조금 들어요. 
입력값이 유효한지나, 트랙이 잘생성되었는지 랜덤한 값이 예상한 유효 범위 안에서 잘 만들어지는지 등을  
좀 더 테스트 해볼 수 있지 않을가 생각합니다.

2022-10-03 04:57 UTC, bingbingpa commented
다음 미션 부터는 git commit 은 구현한 기능 목록 단위로 추가하도록 해보면 좋을거 같아요 😁

2022-10-05 08:11 UTC, GimunLee commented
@bingbingpa 
피드백 정말 감사합니다. 주신 피드백 적용할 수 있는 부분은 적용하였습니다.
커밋 단위와 기능 목록은 다음 미션부터 잘 챙겨보도록 할게요! 
프로젝트 일정과 겹쳐서 그런지 빨리 하기 급급하네요 ㅠㅠ.

2022-10-05 13:32 UTC, bingbingpa commented on src/test/java/racing/RacingGameTest.java
> +        car.setEngine(new BasicEngine(-1));
다음 미션 진행하시면서 한 번 고민해보시고 또 의견 나눠보면 좋을거 같습니다. 😄

2022-10-05 13:44 UTC, bingbingpa approved these changes
피드백 반영 잘해주셨네요!👍 
이번 미션은 이만 머지하도록 하겠습니다.
코멘트 몇가지 남겨드렸는데 한 번 확인해보시면 좋을거 같습니다.
다음 미션도 화이팅 입니다! 🚀

2022-10-05 13:44 UTC, bingbingpa commented on src/main/java/racing/RacingOption.java
> +    int reps;
private 로 접근을 제한해주는건 어떨까요?

2022-10-05 13:44 UTC, bingbingpa commented on src/main/java/racing/Track.java
> +    }
`RacingOption` 은 인스턴스 변수로 존재할 필요는 없지 않을까요? 
그리고 이 메소드가 외부에서 호출 되서 자동차 리스트가 만들어지는거 보다 
생성자로 받은 RacingOption 를 이용해서 바로 자동차 리스트 컬렉션에 넣어주는건 어떨까요? 
외부에서는 Track 인스턴스를 생성하고 게임을 시작하는 `start` 메소드만 알면 될 거 같은데
불필요하게 외부에서 createCars 라는 내부적인 부분까지 알고 있는거 같은 느낌이 들어요.

2022-10-05 13:44 UTC, merged