Step4 자동차 경주 (우승자)
next-step/java-racingcar pull request #3804
Opened 2022-10-02 18:37 UTC by JIWON0813

3단계 마지막 피드백까지 반영해 수정 후 4단계 구현했습니다

잘 부탁드립니다!

2022-10-03 07:50 UTC, KIMSIYOUNG requested changes
안녕하세요.
4단계 미션도 깔끔하게 잘 구현해주셨네요.
4단계 자체에 대한 리뷰보단 몇가지 코멘트 추가로 남겼는데 확인 부탁드립니다.
어려운 부분이 있다면 편하게 말씀해주세요!

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCarApplication.java
> +        Validate.emptyCheck(carListString);
자동차의 이름은 어떠해야한다 라는 로직이, 여기서 수행해야하는게 맞을까요?

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCarApplication.java
>  public class RacingCarApplication {
MVC구조를 학습하고 있는만큼, 패키지를 전체적으로 다 분리해보면 어떨까요? `Controller, View, Model` 요렇게 3가지로 나누어서 각각 어디에 들어갈지 고민해보시면 좋을 것 같습니다.

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/RacingCarApplication.java
> +            racing.round(randomNumber.randomList(carList.size()));
흔히 getter 를 지양하는 이유는 이런 형태때문이에요.

Racing이 자신이 관리하고 있는 자동차에 대해서 관리할 책임을 가지고 있는데, 외부에서 그 자동차를 모두꺼내가서 몇개인지 세고 있어요.

Racing객체에게 `니가 관리하는 자동차가 몇개야?` 라고 물어봐야 하지 않을까요?

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Racing.java
> +    public List<Car> winner() {
깔끔하게 잘 구현해주셨네요. 디미터의 법칙을 지키기 위해서 줄바꿈을 해보는건 어떨까요?

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Racing.java
> +
테스트가 용이하도록 잘 구현해주셨네요. 그럼 다음 스텝으로 이렇게 구현해보면 어떨까요? 

난수를 생성하는 메소드를 가지고 있는 객체를 파라미터로 전달받아서 실행한다. 라고 구현해보면 어떨까요? 

이 떄 여전히 테스트가 가능하려면 숫자 생성기라는 인터페이스를 난수생성기가 구현하고 있고, 테스트에서는 고정된 숫자 생성기를 만들어서 사용한다면 좋을 것 같아요.

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Racing.java
> +
그리고 변수명에는 기본적으로 타입은 안 적는게 좋을 것 같아요. 이미 타입에서 어떤 것인지 보여주고 있지 않나요? 추가로 타입을 바꿀 때 변수명도 바꿔야하는데 놓치기 쉬운 부분 같아요. 
randomNumbers 정도로만 해도 좋을 것 같습니다.

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Racing.java
> +            Validate.carNameCheck(carName);
각 자동차의 이름체크를 여기서 하는게 맞을까요? 자동차가 자신의 이름에 대한 제약사항을 알고 있어야하지 않을까요?

2022-10-03 07:50 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Validate.java
> +    public static void emptyCheck(String input) {
Validator와 같은 클래스는 모든 기능을 여기에 밀어넣기 때문에 사용하기엔 편리하지만 객체지향과는 거리가 멀다고 생각되어요.

각 객체들이 자신의 제약사항을 알고 있어야하지 않을까요?

2022-10-06 12:49 UTC, KIMSIYOUNG requested changes
안녕하세요.
미션 구현 잘 해주셨네요.
몇가지 코멘트 드렸는데 확인 부탁드립니다.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Controller/RacingCarApplication.java
> +        String carListString = inputView.carNameList();
List 와 같은 네이밍은 지양해주세요. Map, Set, List 자료구조가 달라지는 경우 변수명도 수정해줘야하기 때문에 복수형정도로만 적으면 될 것 같아요. 어플리케이션 전체에 다 퍼져있는데 같이 고쳐주세요. List<String> carNames = ...

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Controller/RacingCarApplication.java
> +package RacingCar.Controller;
패키지명은 소문자로 시작합니다.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/StopNumber.java
> +public class StopNumber implements Number{
사용하지 않는 클래스네요. 해당 클래스가 필요했던 이유는 테스트를 위해서인 것 같은데 구현할 떄도 테스트패키지에 있으면 좋을 것 같습니다.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/FixNumber.java
> +        return 4;
MoveNumber라고 네이밍 되어야 할 것 같아요.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Controller/RacingCarApplication.java
> +        List<Car> carList = racing.carList(carListString);
자동차를 관리하는 Cars라는 객체가 있으면 어떨까요?

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Car.java
> +    private int STANDARD_TO_MOVE_NUMBER = 4;
상수는 static과 함께 클래스 가장 상단에 위치해야합니당.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/View/InputView.java
> +
위에 있는 메소드는 scanInt()인데 음수를 체크하고 있네요. 사용하는 사람이 메소드네이밍으로 예상할 수 있을까요?

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Winner.java
> +        return carList.stream().filter(x -> x.getPosition() == max).collect(Collectors.toList());
자동차의 값을 꺼내와서 비교하는 것이 아니라, `너 이 위치랑 같은 위치니? isSamePosition`정도로 구현하는게 객체지향에 더 가까운 것 같습니다.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Winner.java
> +        var optional = carList.stream().max(Comparator.comparing(Car::getPosition));
값이 없는 것에 대한 처리없이 아래에서 get()을 하고 있네요.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Racing.java
> +        for (int i = 0; i < carList.size(); i++) {
아래와 같이 표현할 수도 있습니다.

```java
      for (Car car : carList) {
            int random = randomNumber.random(RANDOM_NUMBER_RANGE);

            car.move(random);
        }

```

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Racing.java
> +    private void init(String[] carArray, List<Car> carList) {
자신이 관리하지 않는 값에 값을 채워주는 것은 지양해야할 것 같아요. Cars 라는 객체를 구현하고 레이싱에서 필드변수로 가지면 자연스러울 것 같아요.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Racing.java
> +    public List<Car> carList(String carInput) {
이런 구조는 객체지향이라기보단 static 메소드와 다를게 없는 것 같아요.

2022-10-06 12:49 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/Model/Winner.java
> +public class Winner {
단위테스트가 없네요.

2022-10-06 15:51 UTC, JIWON0813 commented
2차 피드백 반영해서 푸시했습니다!

너무 어렵네요... Cars로 만들고 안에서 필드로 List<Car> cars를 꺼내지 않고 개발해보려니 Racing객체와 ResultView에서 사용이 불가능해 도전해보다가 실패했습니다... 좀 더 객체지향적으로 개발할 수 있을 것 같은데 결국 getter를 쓰거나 메인에서 변수를 받아 매개변수로 넣어야하는 상황이 자꾸 생기네요....

2022-10-07 12:29 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰 반영 잘 해주셨네요🙂
몇가지 코멘트 더 드렸는데 다음 미션에서 같이 반영해보시면 좋을 것 같아요.
어려운 부분 있다면 편하게 말씀 부탁드립니다.

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Car.java
> +    public Car(String name, int position) {
주 생성자가 가장 위에 있는게 좋을 것 같습니다.

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Cars.java
> +    public List<Car> makeCars(String input) {
아래와 같이 표현할 수도 있을 것 같아요.

```java

public List<Car> create(String input) {
        return Arrays.stream(input.split(DELIMITER))
            .map(Car::new)
            .collect(Collectors.toList());
    }


```

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Number.java
> +    int random(int range);
인터페이스 입장에선 random 이 아닙니다. 각 클래스별로 독립적으로 생각해주시면 좋을 것 같아요🙂

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/StopNumber.java
> +public class StopNumber implements Number {
테스트 패키지에서도 동일하고 프로덕션 코드를 구현할 수 있어요. 

요 클래스는 테스트 패키지에 들어가는게 적절할 것 같아요.

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Winner.java
> +public class Winner {
Winner 도 자신이 승패를 판단해야하는 자동차를 알고 있어도 될 것 같아요. 아래와 같이 작성해보면 어떨까요? 

Winner winner = new Winner(cars);
List<Car> winners = winner.findWinners();
print

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Winner.java
> +        if (car == null) {
승자가 없는 경기란 애초에 잘못된 프로그램이니까 예외를 던지는게 더 적절할 것 같습니다. 

그리고 null 을 반환하는 경우는 꼭 필요한 경우가 아니라면 지양해주세요. null로 인해서 생기는 다양한 문제들을 조금 찾아보시면 많이 위험할 수 있겠다라고 느끼실 것 같아요!

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Winner.java
> +        return cars.stream().filter(x -> x.isSamePosition(max)).collect(Collectors.toList());
스트림을 사용할 땐 개행을 해줘야 가독에 도움이 되는 것 같아요.

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Cars.java
> +public class Cars {
Cars 의 역할은 현재 CarFactory 정도인 것 같아요.

자신이 관리하는 List<Car>를 알고 있고, 각 자동차들에게 움직이라는 메시지를 전달할 수 있는 객체로 만들어보면 어떨까요?

구현이 조금 어려우실 것 같아서 아래와 같은 흐름으로 컨트롤러가 작성될 것 같아요.

```java
Cars cars = new Cars(input);
for (int i =0; i<round; i++) {
    cars.move(randomNumber);
    print(cars.getCars());
}

```

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/domain/Cars.java
> +public class Cars {
값을 꺼내지 않는게 중요한게 아니라, 값을 꺼내고 변경/비교 하는 등의 행위로 객체가 훼손되는게 문제이기에 `getter`를 지양하는거라고 생각해요.
그렇기 때문에 출력을 위해서 사용하는건 당연하다고 생각합니다🙂

2022-10-07 12:29 UTC, KIMSIYOUNG commented on src/main/java/RacingCar/controller/RacingCarApplication.java
> +        String carListString = inputView.carNames();
요 네이밍처럼 List가 Map 으로 바꼈어도 carListString이었겠죠?🙂

2022-10-07 12:29 UTC, merged