Step3 : 자동차 경주
next-step/java-racingcar pull request #3805
Opened 2022-10-03 05:24 UTC by cyj199637

3단계 - 자동차 경주 구현 완료했습니다:)
리뷰 부탁드립니다~

2022-10-03 08:37 UTC, lowoon requested changes
안녕하세요 yoonjeong님!
3단계도 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-03 11:58 UTC, cyj199637 commented on src/main/java/racingcar/view/OutputView.java
> +            System.out.print("-");
for 문 쓰는게 거슬렸는데 이 방법이 훨씬 더 좋을 것 같네요:) 피드백 감사합니다!

2022-10-03 12:00 UTC, cyj199637 commented on src/test/java/racingcar/CarsTest.java
> +
이 부분 고민했던 부분 중 하나인데요, 현재 move 메소드가 정해진 결과를 반환해주거나 예측할 수 있는 범위 내에서 상태 변화를 시켜주는 메소드가 아니라서요 이럴 경우 어떻게 테스트를 작성하는게 좋을까요? 아니면 메소드를 다시 짜야하는 것이 좋을까요?

2022-10-03 12:07 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
> +        this.carList.clear();
현재 테스트 코드에서만 사용하고 있습니다. 테스트 코드를 보시면 하나의 테스트를 마칠 때마다 변수로 선언된 Cars의 carList를 비워주고 있는데요. 테스트 코드에서만 사용하는 것이 조금 이상해 보일 수는 있지만, 그렇다고 해당 동작을 외부에서 carList를 꺼내서 직접 clear 해주는 것이 좋은가? 라는 의문이 들어 만든 메소드였습니다!
사실 테스트마다 Cars 객체를 새로 만드는 등의 방식으로 다르게 풀 수도 있겠지만요ㅋㅋㅋ

2022-10-04 14:39 UTC, cyj199637 commented
일단 아직 답변주지 않은 부분을 제외한 나머지 부분에 대해서 리팩토링 진행했습니다:)

2022-10-04 23:41 UTC, lowoon commented on src/main/java/racingcar/Cars.java
> +        this.carList.forEach(Car::move);
저 내용은 참고만 하시면 될것 같은데 개인적으로 list의 경우에도 forEach를 통해 출력이 아닌 로직을 동작하는 것에 대해서는 for문 사용을 권장드리고 있는데요.
forEach의 경우 front 개발을 하시던 분들이 많이 사용하시는 경향이 있는 것 같고, 다른 개발자가 보기에도 forEach보다 익숙한 for문이 파악하기 좋을 것 같다는 개인적인 생각입니다!
이 부분은 개인적인 의견이라 참고만 하시면 될 것 같아요!

2022-10-04 23:42 UTC, lowoon commented on src/main/java/racingcar/Cars.java
> +        this.carList.clear();
네 맞습니다!
테스트만을 위한 코드가 운영코드에 있어도 되는가에 대해서 고민을 해보면 좋을거 같아요!
의견 주시면 저의 의견을 말씀드리도록 하겠습니다ㅎㅎ

2022-10-04 23:54 UTC, merged

2022-10-06 11:22 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
> +        this.carList.forEach(Car::move);
오 그렇군요! 또 다른 관점을 알아가게 되네요 감사합니다:)

2022-10-06 11:47 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
> +        this.carList.clear();
개인적으로는 운영 환경에서 사용되는 비즈니스 로직을 해치치 않는 선까지는 괜찮지 않을까라는 생각은 들어요
메소드 하나로 테스트 코드 작성 난이도가 낮아지는 것도 장점이라고 생각해서요!

2022-10-06 12:19 UTC, cyj199637 commented on src/main/java/racingcar/util/RandomGenerator.java
> +    private static final Random random = new Random();
지금은 랜덤 숫자를 반환하는 메소드만 있지만 랜덤으로 반환할 값들이 더 생길 수 있고 또 그런 역할을 하는 메소드들은 프로젝트 전반적으로 사용할 수 있을 거라고 생각해서 util 패키지로 따로 분리해뒀어요!

2022-10-06 12:20 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
> +    public void moveAll() {
Car.move 메소드만 신경쓰다 보니 정작 Cars를 놓친 케이스 같네요...🥲

2022-10-06 12:51 UTC, cyj199637 commented on src/main/java/racingcar/Racing.java
> +        cars.moveAll();
전체 결과를 반환하게 되면 출력을 어떻게 할 수 있을까요?한 번의 시도마다 결과를 출력하는 것으로 요구사항을 이해했고 출력 로직을 비즈니스 로직에 들어가지 않도록 하기 위해 저렇게 작성했는데 만약에 전체 결과를 반환하게 했을 경우 출력 부분을 어떻게 할 지가 감이 안 잡히네요...Car 객체마다 각각의 시도에 대한 결과를 갖고 있도록 하는 방향은 어떨까요?

race 메소드를 static 하게 만들었던건 race를 비즈니스 로직이라고 생각하지 않아서 간과했던 것 같네요 이 부분 수정하도록 하겠습니다~

2022-10-06 12:51 UTC, cyj199637 commented on src/main/java/MainApplication.java
> +        System.out.println("실행 결과");
현재 결과를 출력하는 메서드가 한 번의 시도마다 실행되는 메서드라 해당 부분 제외시켰습니다 이것도 수정하도록 할게요!

2022-10-08 08:05 UTC, lowoon commented on src/main/java/racingcar/util/RandomGenerator.java
> +    private static final Random random = new Random();
말씀하신 것처럼 하나의 도메인, 로직에서 사용되는 것이 아닌 여러 곳에서 사용될 수 있는 공통 로직들을 util로 빼는데요.
위의 [코멘트](https://github.com/next-step/java-racingcar/pull/3805#discussion_r985512286)에서 참고하라고 드린 링크에 나온 내용인데 말씀하신 util을 활용하는 방식으로 하려면 interface strategy를 만들고 해당 클래스가 createNumber()를 가져서 상속받은 RandomNumberStrategy에서 해당 util 클래스를 사용하도록 해야할텐데요.
해당 구조에서는 너무 과한 구조라고 생각되어서 말씀드려 봤습니다.
step4에서는 잘 구현해주셨네요ㅎㅎ 💯