Step4 : 자동차 경주 (우승자)
next-step/java-racingcar pull request #3841
Opened 2022-10-05 03:08 UTC by sienna011022

2022-10-05 03:42 UTC, sienna011022 commented on src/main/java/carRacing/level3/controller/RacingGameController.java
> +	List<Car> carList = new ArrayList<>();
* **목적** : initiateCars를 Cars 밑으로 보내기 위한 리팩토링을 해보았습니다.

* **문제** : 그런데 일급 콜렉션 객체를 생성하기 위해서 new Cars(리스트) 를 넣어주어야 생성이 되더라고요.

* **해결 방안**  : 그래서 controller에서 가짜(?) 리스트를 하나 만들어서 객체 하나를 생성한 뒤 ,
initiateCars()를 호출하여 Cars안에서 this로 리스트를 재 정의하게 해주었습니다.

 이 방법이 맞는 방법인지 궁금합니다.

2022-10-05 03:45 UTC, sienna011022 commented on src/main/java/carRacing/level3/model/strategy/WinnerStrategy.java
> +	List<String> winnerList = new ArrayList<>();
혹시 이런 전역 변수들의 선언의 순서가 따로 정해져있나요?
 구글링 해보았는데 원하는 해답이 안 나오네요..!

2022-10-05 09:06 UTC, KIMSIYOUNG requested changes
안녕하세요.
미션 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인 부탁드립니다.

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/Cars.java
> +	public void initiateCars(List<String> carNameList) {
생성자를 두개이상 두는 경우 부 생성자가 주 생성자를 부르도록 구성하는 것이 좋습니다. 

주생성자에 필수적인 기능들을 넣어두고, 부생성자를 통해 다양한 형태를 지원해주는 구조가 좋을 것 같아요.

이 메소드에서 this(Intstream...)으로 가면 좋을 것 같아요.

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/Cars.java
> +	public void initiateCars(List<String> carNameList) {
```java
carNameList.stream()
			.map(Car::new)
			.collect(Collectors.toList())

```

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/strategy/WinnerStrategy.java
> +public class WinnerStrategy {
전략패턴이 아닌데 전략으로 빼야하는 이유가 있나요? Winner라는 객체로 풀어보면 어떨까요?

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/view/input/InputView.java
> +	private void validateLength(String carName) {
이런 역할은 자동차의 역할이 아닐까요?

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/strategy/WinnerStrategy.java
> +	private static int maxLocation;
왜 static인가요? static 필드와 일반 필드는 어떤게 다른지 설명해주시면 좋을것 같아요.

2022-10-05 09:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/controller/RacingGameController.java
>  public class RacingGameController {
프로그램은 어디서 실행할 수 있나요?..

2022-10-05 09:10 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/controller/RacingGameController.java
> +	List<Car> carList = new ArrayList<>();
이해를 잘 못했어요. Cars를 생성할 때 List<Car>를 null로 두거나 final로 생성할 때 주입받은 것으로 생성하면 되지 않나요?

2022-10-06 07:07 UTC, sienna011022 commented on src/main/java/carRacing/level3/infra/error/NameLengthException.java
> +package carRacing.level3.infra.error;
보통 프로젝트 할 때 infra안에 error를 집어 넣었습니다,아무래도 메인 코드는 아니고..무언가 부가기능이라고 생각해서 infra에 넣었는데 혹시 보통 error 패키지는 어떻게 네이밍 하나요?

2022-10-06 07:25 UTC, sienna011022 commented on src/main/java/carRacing/level3/model/strategy/WinnerStrategy.java
> +	private static int maxLocation;
접근제어자 개념이 부족한것 같습니다. 다시 정리해보겠습니다!!

2022-10-06 13:06 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰 잘 반영해주셨고 잘 구현해주신 것 같아요.
미션은 여기서 머지하겠습니다.
추가 코멘트 남겼는데 천천히 고민하시고 적용해보시면 좋을 것 같아요.

2022-10-06 13:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/controller/RacingGameController.java
>  	InputView inputView = new InputView();
접근제어자는 학습이 되면 모두 달아주세요.

2022-10-06 13:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/Location.java
> +		location += MOVE_LOCATION;
객체를 쪼개려고 노력해주셨네요. 좋은 방향인 것 같습니다.

그리고 불변을 적용해보시려고 한 것 같은데요! 본인의 위치를 수정하면 가변아닌가요? 

불변으로 만들려고 하셨다면 new Location(location + 1)로 해주셔야 자신은 변하지 않고, 새로운 객체가 나올 것 같아요.

2022-10-06 13:06 UTC, KIMSIYOUNG commented on src/main/java/carRacing/level3/model/Winner.java
> +		maxLocation = cars.maxCarLocation();
필드변수와 지역변수에 대해서도 학습해보시고 해당 필드가 필드변수로 있어야하는지 고민해보시면 좋을 것 같아요.

2022-10-06 13:06 UTC, KIMSIYOUNG commented on src/test/java/carRacing/level3/CarTest.java
> +		Car car = new Car("test");
자동차의 전진, 스탑 여부를 판단하기 위해 전략패턴을 사용했는데 정작 테스트에는 전략을 사용하지 않네요

2022-10-06 13:07 UTC, merged

2022-10-08 23:58 UTC, sienna011022 commented on src/main/java/carRacing/level3/model/Winner.java
> +		maxLocation = cars.maxCarLocation();
Winner클래스 내에서 maxLocation변수는 addWinner()함수와 decideWinner()함수만 사용하는 변수입니다. 

decideWinner()에서 addWinner()를 호출하는 구조를 가지고 있고요

decideWinner()에서 addWinner()를 호출 할 때 파라미터로 maxLocation을 넘겨 줄 수는 있겠지만

이미 addWinner()에 파라미터가 두개나 있어서 파라미터가 3개가 되는 것을 지양하는 것으로 알아  필드변수로 빼는 선택을 해보았습니다.