Step4
next-step/java-racingcar pull request #3856
Opened 2022-10-05 14:22 UTC by elmo-devv

2022-10-06 10:06 UTC, testrace requested changes
안녕하세요!
4단계 요구사항이 일부 누락되었네요 😢 
관련 코멘트와 패키지에 대해서 코멘트 남겼으니 확인 후 다시 리뷰 요청해 주세요.

2022-10-06 10:06 UTC, testrace commented on src/main/java/step4/RacingCarApplication.java
> +    }
경주에 참가하는 자동차들을 배열로 만들기보다 자바의 컬렉션을 사용하면 어떨까요?
1대의 자동차를 표현하는 Car가 있듯이 여러대의 자동차를 표현하는 클래스도 있으면 좋을 것 같아요

2022-10-06 10:06 UTC, testrace commented on src/main/java/step4/model/Car.java
> +    private final static Random random = new Random();
사용되지 않는 코드는 제거해 주세요.

2022-10-06 10:06 UTC, testrace commented on src/main/java/step4/model/Car.java
> +    }
```suggestion
    public int advanceCar(int randomValue) {
        if(isAdvanced(randomValue)) {
            this.location++;
        }
        return this.location;
    }
```

2022-10-06 10:06 UTC, testrace commented on src/main/java/step4/controller/CarController.java
> +public class CarController {
어떤 의도로 만드셨을까요?
사용되지 않는 클래스는 삭제해 주셔도 좋습니다.

2022-10-10 06:37 UTC, testrace requested changes
안녕하세요 😃 
브랜침이름은 step4인데 우승자를 구하는 요구사항 구현이 누락된 것 같아요
요구사항과 코멘트 확인하시고 다시 리뷰 요청 부탁드립니다!

2022-10-10 06:37 UTC, testrace commented on src/main/java/step3/InputView.java
> +    }
InputView는 입력 받은 이름들만 전달을 하고, Car 도메인 객체를 만드는건 RacingCar 또는 자동차들을 생성하는 별도의 객체에서 수행하면 어떨까요?

2022-10-10 06:37 UTC, testrace commented on src/main/java/step3/Name.java
> +    private String name;
문자열 포장 👍 
final 키워드를 붙여서 불변 객체로 만들어도 좋을 것 같아요!

2022-10-10 06:37 UTC, testrace commented on src/main/java/step3/RacingCar.java
> +        System.out.println();
출력을 담당하는 ResultView에서 출력하면 어떨까요?

2022-10-10 06:37 UTC, testrace commented on src/main/java/step3/ResultView.java
> +        System.out.print(carName + " : ");
실행결과 예시와 다르네요 😢 
![image](https://user-images.githubusercontent.com/8064743/194809504-879ee078-6bb2-492d-84a1-f5ffece327ae.png)

2022-10-10 06:37 UTC, testrace commented on src/test/java/step3/NameTest.java
> +public class NameTest {
Position 처럼 정상 생성되는 테스트도 있으면 좋을 것 같아요! 😃

2022-10-10 08:22 UTC, elmo-devv commented
안녕하세요 구현하지 않은 winner  구현하는 부분 추가했습니다 !
감사합니다!

2022-10-10 23:32 UTC, testrace approved these changes
안녕하세요 😃 

기능 요구사항뿐만 아니라 프로그래밍 요구사항과 기능 목록 및 commit 로그 요구사항을 지키면서 진행하시길 추처드립니다!
지난 피드백에 적용될 부분이 없는지 다시 한번 더 검토 해보시는 것도 좋을 것 같아요.
조금 빠른 진행을 위해 머지하도록 하겠습니다.
몇 가지 피드백 남겼는데 다음 단계 진행 하시면서 확인 부탁드릴게요!

2022-10-10 23:32 UTC, testrace commented on src/main/java/step3/Name.java
> +    }
toString을 orverride 해주셨네요!
지금 현재로써는 view를 위해 재정의가 된 것 같은데요, 간접적으로나마 view에 의존하지 않도록 변경하면 어떨까요?

2022-10-10 23:32 UTC, testrace commented on src/main/java/step3/Position.java
> +    }
comparable을 구현해서 override 애너테이션과 int 리턴을 하면 어떨까요?
Position 에 새로운 책임이 생겼으니 테스트 코드도 있으면 좋을 것 같아요

2022-10-10 23:32 UTC, testrace commented on src/main/java/step3/RacingCar.java
> +    private static final ResultView resultView = new ResultView();
프로그래밍 요구사항 중 [컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) 확인 부탁드려요!

2022-10-10 23:32 UTC, testrace commented on src/main/java/step3/RacingCar.java
> +    private static List<Car> winner = new ArrayList<>();
winner를 일급 컬렉션으로 변경하면 어떨까요?
피드백 강의를 참고해보시면 좋을 것 같아요!

2022-10-10 23:32 UTC, testrace commented on src/main/java/step3/ResultView.java
> +    }
테스트 코드가 없네요 👀

2022-10-10 23:33 UTC, merged

2022-10-21 02:18 UTC, elmo-devv commented on src/main/java/step3/Name.java
> +    }
잘 이해가 가지 않아서 그러는데 view 에 의존하지 않으려면 혹시 어떤식으로 구현해야할까요...?