Step5
next-step/java-racingcar pull request #3860
Opened 2022-10-05 15:49 UTC by hoduulmu

안녕하세요! 이번 피드백도 잘부탁드립니다.

이번 과제는 원시값과 콜렉션을 포장하며 프로그램을 객체들이 메세지를 주고받으며 상호작용하게 만드는데도 노력했지만 구조를 단순화 시키기 위해서도 노력했습니다.

이 과정에서 App 클래스가 자동차 경주의 라운드를 진행하는 책임을 가지게 바뀌었습니다.

선동님은 도메인 객체가 모든 라운드를 진행하고 결과를 한번에 View 객체에 넘기는 방식이 낫다고 보시나요 아니면 지금처럼 App 클래스가 중간중간 결과를 View 객체에게 넘기는 방식이 낫다고 생각하시나요

별거 아닌 것에 고민하고 있는 것일 수도 있겠지만 View 객체와 도메인 객체를 아예 분리시키려면 전체 결과를 한번에 주는게 맞다고도 생각되기도 하고 고민되어 여쭤봅니다!

2022-10-06 01:29 UTC, seondongpyo requested changes
마지막 단계도 잘 작성해주셨네요 👍
원시 값과 문자열 포장, 전략 패턴 도입이 인상적이었습니다.
몇 가지 코멘트를 드렸는데 확인 후 다시 리뷰 요청을 부탁드릴게요 🔥

2022-10-06 01:29 UTC, seondongpyo commented on src/main/java/racing/domain/car/Position.java
> +public class Position {
원시 값 포장 👍

2022-10-06 01:29 UTC, seondongpyo commented on src/main/java/racing/domain/RacingGame.java
> +    private final CarGroup carGroup;
자동차 경주를 구성하는 요소는 `자동차`와 `시도 횟수`라고 볼 수 있는데요, 그런 의미에서 본다면 
자동차 경주를 수행하는 `RacingGame`이 `시도 횟수`를 상태로 관리하는 것이 어울리지 않을까란 생각이 드는데
재훈님께선 어떻게 생각하시는지 의견이 궁금합니다.

2022-10-06 01:29 UTC, seondongpyo commented on src/main/java/racing/App.java
> +        printWinner(racing.winner());
> 선동님은 도메인 객체가 모든 라운드를 진행하고 결과를 한번에 View 객체에 넘기는 방식이 낫다고 보시나요 아니면 지금처럼 App 클래스가 중간중간 결과를 View 객체에게 넘기는 방식이 낫다고 생각하시나요

경우에 따라 다르겠지만 저는 전자가 더 나은 방식이라고 생각해요.
`MVC` 구조로 봤을 때 `Controller`의 역할을 하는 `App` 클래스에서 굳이 `while` 반복을 사용하지 않아도 되고
메서드도 자주 호출할 필요가 없으니 코드 가독성 측면에서는 더 깔끔하지 않나 생각합니다.

2022-10-08 10:32 UTC, hoduulmu commented on src/main/java/racing/domain/RacingGame.java
> +    private final CarGroup carGroup;
시도 횟수의 경우 횟수를 감소하는 것 외의 로직이 없기 때문에 App에서 담당해도 상관없지 않나라고 생각했는데 RacingGame이 관리하게 하고 객체로 뽑아내고 보니 시도 횟수가 생성될 때 0 이하로 방지하는 유효성 로직도 있고 앞으로의 확장성 측면에서도 RacingGame이 관리하는게 맞는것 같습니다.
제가 구조를 단순하게 한다고 하려다 오히려 App 클래스의 로직을 무겁게 만든거 같네요

2022-10-08 10:34 UTC, hoduulmu commented on src/main/java/racing/App.java
> +        printWinner(racing.winner());
저도 동감합니다. 제가 이번 리팩토링에서 구조를 단순화 한다는게 App 클래스의 책임을 무겁게 만든거 같다는 생각이 들어요

2022-10-08 10:34 UTC, hoduulmu commented on src/test/java/racing/domain/car/CarTest.java
> +class CarTest {
수정했습니다!

2022-10-08 10:34 UTC, hoduulmu commented
선동님 수정사항 반영했습니다! 다시 한번 확인 부탁드려요

2022-10-09 03:20 UTC, seondongpyo approved these changes
피드백을 잘 반영해주셨네요 👍
크게 드릴 말씀이 없어서 자동차 경주 미션은 여기서 마무리하도록 하겠습니다.
남은 연휴 즐거운 시간 되시고 마지막 미션까지 완주하시길 응원하겠습니다 🔥

2022-10-09 03:21 UTC, merged