4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #3871
Opened 2022-10-06 03:57 UTC by cohys7

안녕하세요!
3단계 PR 리뷰 반영 및 4단계 자동차 경주 진행 했습니다!
리뷰 부탁드립니다!

+) 3단계 PR 리뷰에 코멘트 이어서 달아두었습니다!
확인 부탁드립니다!

감사합니다~ 😊

2022-10-07 14:06 UTC, ksy90101 commented on src/main/java/racingcar/View.java
> +    private void printComma(int i) {
i라는 단어보단, 더 의미있는 단얼르 쓰는게 좋을듯 합니다 :)

2022-10-07 14:07 UTC, ksy90101 commented on src/main/java/racingcar/View.java
> +            printComma(i);
join()으로 바로 처리 가능하지 않을까요?

2022-10-07 14:10 UTC, ksy90101 commented on src/main/java/racingcar/domain/Name.java
> +    public static final int MAXIMUM_LENGTH = 5;
private도 괜찮지 않을까요?

2022-10-07 14:12 UTC, ksy90101 commented on src/main/java/racingcar/domain/Cars.java
> +    }
Winners 객체를 만들어서, Winners를 추출하는 로직을 해두면 어떨까요?

2022-10-07 14:12 UTC, ksy90101 requested changes
안녕하세요 :)
전체적으로 너무 잘 구현 해주셨네요 💯 
원시값도 잘 포장해주셨구요!!
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다 :)

2022-10-11 13:29 UTC, cohys7 commented on src/main/java/racingcar/View.java
> +    private void printComma(int i) {
무심코 for 문에서 사용하던 i를 그대로 적었네요.
말씀주신데로 변수명 수정이 필요해보입니다.

다만 join을 사용하니 해당 메소드를 사용할 필요가 없어 삭제 했습니다!
다음번에는 변수명에 대해서도 좀더 고민해서 지어보겠습니다 :)

2022-10-11 13:30 UTC, cohys7 commented on src/main/java/racingcar/View.java
> +            printComma(i);
List<Name> 으로 되어있어서 join을 사용하지 못했습니다.
stream으로 이름을 전부 가져오니 join해서 프린트 가능하네요!

다만 수정 하면서 고민 되는 부분은 View와 도메인 분리의 기준입니다!

어떻게 보면 Name의 값을 가져와서 출력하는 것이니 모두 View에서 해도 괜찮을 것 같다는 생각이 드는데,
매번 getter를 쓸 때마다 고민이 됩니다!

https://github.com/next-step/java-racingcar/pull/3871/commits/c4366747a48ed62d3e992ed9a0c6bd107c428859

2022-10-11 14:01 UTC, cohys7 commented on src/main/java/racingcar/domain/Location.java
> +        return new Location(location + 1);
현재 로직 상 Location은 계속 변화하는 값인데,
Location을 불변 객체로 두어서 이점이 되는  부분은 없는 것 같습니다.

작은 프로그램이라 성능에 유의미한 차이는 없겠지만,
인스턴스를 계속 생성하는 것이 성능 상으로는 좋을 것 같진 않습니다.

Car를 불변으로 두고 Location을 가변으로 사용하는 것이 더 좋을 것 같습니다!

https://github.com/next-step/java-racingcar/pull/3871/commits/3b991fbcf74c49dc64adabf88fc3dc5cd93d0893

2022-10-11 14:41 UTC, cohys7 commented on src/main/java/racingcar/domain/Cars.java
> +    }
Winners를 추출하기 위해서는 List<Car>가 필요하니,
Winners 보다 Cars 객체에서 winner를 구하는 것이 좋다고 생각했습니다.

Winners 객체를 만들 더라도 결국
1. 가장 멀리있는 위치를 구하기
2. 해당 위치에 있는 차의 이름 가져오기

두 가지 로직은 Cars에게 구해달라고 다시 보내야할 것 같은데,
Winners 객체를 만들어서 분리했을 때 다른 이점이 있는 것일까요?

우선 역할에 따라 메서드 분리 부터 수정해 보았습니다!

https://github.com/next-step/java-racingcar/pull/3871/commits/6216995d50f6ebfcc3be7c6d0c96bc13ad1ce993

2022-10-12 13:03 UTC, ksy90101 commented on src/main/java/racingcar/View.java
> +            printComma(i);
getter는 상태를 보내주는것이기 때문에, 현재 구조상에선 어쩔수 없을듯 해요.
그러나 우리가 한번 고민해보면 웹에서 DTO를 사용할때도 getter를 항상 열어주잖아요. 결국 상태값을 리턴한다는 느낌으로 생각하시면 좋지 않을까 합니다 ㅎㅎ

2022-10-12 13:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Location.java
> +        return new Location(location + 1);
네. 사실 저희가 상태를 관리하게 되면서 불변을 유지하지 못하는 경우는 굉장히 많을듯 해요.
따라서, 무조건 불변보단, 효과적인 방법을 택하는게 좋은듯 합니다.

2022-10-12 13:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Cars.java
> +    }
책임 분리라고 생각하시면 좋을거 같아요.
Cars와 Winners는 현실세계에서 고민해보면 다른 친구가 될꺼고, 내부는 Car라는 것으로 동일하긴 할거에요.
일급컬렉션 개념으로 생각한다면 두개를 분리하는것도 하나의 방법이라고 생각합니다.

2022-10-12 13:08 UTC, ksy90101 commented on src/main/java/racingcar/domain/Location.java
> +    }
Compare를 상속받아서 비교를 구현해도 좋을거 같긴 하네요 :)

2022-10-12 13:08 UTC, merged

2022-10-25 17:30 UTC, cohys7 commented on src/main/java/racingcar/domain/Location.java
> +    }
상속해서 구현해 보았습니다!

https://github.com/next-step/java-racingcar/pull/3972/commits/50e72e619d8aeffd55164460a5d4918e9bf792e8