Step3 - 자동차경주
next-step/java-racingcar pull request #3876
Opened 2022-10-06 16:21 UTC by kmdrp

[온라인 코드리뷰 요청](https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md) 을 반영하느라 이전 PR요청이 Closed 되고 브랜치가 삭제되었습니다. 
일단 피드백 반영하여 다시 올려봅니다.

2022-10-07 14:05 UTC, hyunssooo requested changes
안녕하세요.
몇 가지 코멘트 남겼습니다. 확인 부탁드릴게요.
궁금한 점이나 함께 고민해 보고 싶은 부분이 있으시면 편하게 dm이나 코멘트 남겨 주세요.

2022-10-07 14:05 UTC, hyunssooo commented on src/main/java/racingcar/RaceController.java
> +
https://github.com/next-step/java-racingcar/pull/3874#discussion_r989078783

제 말은 controller 필드에 존재하면 안 된다는 말이었습니다. view를 input, output으로 나눠 controller가 view를 의존하는 모습으로 구현해 보는 것은 어떨까요? 혹은 지금은 main()을 controller라고 생각해도 괜찮을 것 같아요.

2022-10-07 14:05 UTC, hyunssooo commented on src/test/java/step3/CarTest.java
> +
프로덕션과 테스트 패키지는 동일해요.

2022-10-07 14:05 UTC, hyunssooo commented on src/test/java/step3/CarTest.java
> +    }
필요할까요??

2022-10-07 14:05 UTC, hyunssooo commented on src/main/java/racingcar/Car.java
> +    }
랜덤에 대한 의존성 분리 💯 
그럼 더 이상 random이라는 단어는 필요하지 않을 것 같아요.

2022-10-07 14:07 UTC, hyunssooo commented
https://edu.nextstep.camp/s/DVVUSLFe/ls/6GcCH4YB 아래에 commit 컨벤션이 있는데 참고해 보면 좋을 것 같아요.

https://github.com/next-step/java-racingcar/pull/3874#discussion_r989239706

> 질문) 단순히 model의 상태를 출력하는것이 model에 변화가 있다고 볼수 있나요?

전 pr에서 car 필드에서 StringBuilder로 `-` 를 추가해 주고 있었습니다.
`-` 문자 자체는 view에 보여주기 위함인데요. 만약 view에서 `*` 로 바뀐다고 해서 도메인 모델인 `Car`도 변해야 할까요?

2022-10-07 14:09 UTC, hyunssooo commented on src/main/java/racingcar/Car.java
> +
작성하신 클래스들도 적절하게 패키지 분리해 보는 것은 어떨까요?

2022-10-11 08:16 UTC, kmdrp commented on src/test/java/step3/CarTest.java
> +    }
테스트 내용이 변경되었는데 제거를 안햇네요 제거했습니다 !

2022-10-11 08:16 UTC, kmdrp commented on src/test/java/step3/CarTest.java
> +
여기도 수정하겠습니다

2022-10-11 08:21 UTC, kmdrp commented on src/main/java/racingcar/Car.java
> +    }
변수명에서 random이 빠져도 되겠네요

2022-10-11 08:38 UTC, kmdrp commented
> https://edu.nextstep.camp/s/DVVUSLFe/ls/6GcCH4YB 아래에 commit 컨벤션이 있는데 참고해 보면 좋을 것 같아요.
> 
> [#3874 (comment)](https://github.com/next-step/java-racingcar/pull/3874#discussion_r989239706)
> 
> > 질문) 단순히 model의 상태를 출력하는것이 model에 변화가 있다고 볼수 있나요?
> 
> 전 pr에서 car 필드에서 StringBuilder로 `-` 를 추가해 주고 있었습니다. `-` 문자 자체는 view에 보여주기 위함인데요. 만약 view에서 `*` 로 바뀐다고 해서 도메인 모델인 `Car`도 변해야 할까요?

설명해주신 덕분에 이해했습니다 !! 단순히 출력한다는 기능에만 신경쓰고 있었네요

2022-10-11 08:42 UTC, kmdrp commented on src/main/java/racingcar/Car.java
> +
정확히 mvc모델을 따라가긴 어렵지만 기능별로 패키지를 분리해보았습니다.   - ([823ffc1](https://github.com/next-step/java-racingcar/pull/3876/commits/823ffc1bcd635f835d7a1cd064dbca690b21195c))

2022-11-02 08:50 UTC, kmdrp commented on src/main/java/racingcar/contorller/RaceController.java
> +    }
제가 네이밍을 controller라고 한게 오해를 불러 일으킨것 같네요
mvc 패턴의 controller의 역할의 해서가 아닌
자동차 경주의 여러 기능을 총괄하는 객체이기 때문에 controller 라고 명명했습니다.

2022-11-02 10:08 UTC, hyunssooo approved these changes
안녕하세요.
남겨주신 코멘트에 제 생각 남겼습니다.
다음 step 진행하시면서 참고 부탁드리고 기존에 남긴 코멘트들도 확인해 주시면 좋을 것 같아요.

2022-11-02 10:08 UTC, hyunssooo commented on src/main/java/racingcar/contorller/RaceController.java
> +    }
그렇다면 controller 라는 이름은 변경하는 것이 좋아보입니다. 
많은 개발자들이 오해하지 않을까요? 
`자동차 경주의 여러 기능을 총괄하는 객체` 라면 도메인 모델로 볼 수 있을 것 같은데 아래에 `System.out.println()` 는 view에 관련된 로직 아닐까요?

2022-11-02 10:08 UTC, merged