Step4 : 자동차 경주(우승자)
next-step/java-racingcar pull request #3884
Opened 2022-10-07 19:11 UTC by cyj199637

4단계 - 자동차 경주(우승자) 미션 구현 완료했습니다!
그리고 저번 단계 미션 PR에도 답글 달았으니 확인하시고 더 피드백 부탁드립니다:)
(https://github.com/next-step/java-racingcar/pull/3805)

이번 단계 미션에서도 잘 부탁드립니다🙌🏻

2022-10-08 08:35 UTC, lowoon requested changes
안녕하세요 yoonjeong님!
4단계도 잘 구현해주셨네요 👍 
답변 남겼고, 코멘트도 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +        }
검증을 view에서 하고 있는데요.
저는 개인적으로 view에서는 간단한 검증(string인지 int인지 정도)만 하고 로직과 관련된 검증은 객체에서 해야하지 않나라고 생각합니다.
검증이 특정 비지니스 로직과 관련이 있기 때문에 원시값을 포장한 객체를 만들어서 해당 객체를 생성할 때 검증을 하도록 하면 역할과 책임에 맞지 않을까요?

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Cars.java
>      public List<Car> carList() {
메서드명이나 변수명에서 자료구조를 나타내지 않도록 권장하고 있습니다.
getCars로 만들 수 있지 않을까요??

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Cars.java
>      public void moveAll() {
cars를 생성할 때 strategy를 할당하는게 아니라 moveAll 메서드에서 parameter로 넘겨주는 것이 변경에 유연하지 않을까요??
몇개는 random으로 하고 몇개는 지정한 숫자로 하는 경우에 어떻게 될까요?

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Cars.java
> +    public List<Integer> allPosition() {
getPositions로 해도 되지 않을까 해요.
다른 사람들이 봤을때에도 이해하기 쉬운 메서드명이 좋지 않을까요?

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +        cars.carList().forEach(car ->
여러가지 방법이 있을텐데요.
moveAll에서 List<Car>를 반환할 수도 있고, racingResult 내부에서 List<Car>를 가질수도 있을거 같아요.
그러면 RacingResult.from(cars)도 될거 같고,
아니면 
``` java
        List<RacingResult> currentResult = cars.carList()
                .stream().map(RacingResult::from)
                .collect(Collectors.toList());
        result.add(currentResult);
```
도 가능하겠네요.
역할과 책임에 맞다고 생각되는 방법을 고민해보시면 좋을것 같아요!

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +        int maxPosition = cars.maxPosition();
cars에서 maxPosition을 구하는 것처럼 우승자도 cars에게 물어볼 수 있지 않을까요?

2022-10-08 08:35 UTC, lowoon commented on src/test/java/racingcar/CarsTest.java
> +        Cars cars = new Cars(carNames, new NumberGenerateStrategy() {
테스트용 strategy를 테스트 코드에 만들어 두면 매번 만들지 않고 여러 테스트에서 활용할 수 있지 않을까요?

2022-10-08 08:35 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +    public Racing(List<String> carNames, NumberGenerateStrategy strategy) {
strategy를 변수로 넘겨받고 있는데요.
비지니스 로직과 관련이 있으니 racing 내부에서 생성해서 관리하는 것이 맞지 않을까요?

2022-10-08 16:41 UTC, cyj199637 commented on src/main/java/racingcar/view/InputView.java
> +        }
덕분에 좋은 아이디어가 떠올랐네요:) 한 번 다시 리팩토링 해보도록 하겠습니다!

2022-10-08 16:42 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
>      public List<Car> carList() {
개인적으로는 클래스 이름과 그 클래스가 가진 필드 이름을 똑같이 짓지 않도록 하는 편이라 저런 이름이 나오게 됐습니다만..🥲
조금 더 고민해보도록 하겠습니다!

2022-10-08 16:43 UTC, cyj199637 commented on src/main/java/racingcar/Cars.java
>      public void moveAll() {
> 몇개는 random으로 하고 몇개는 지정한 숫자로 하는 경우에 어떻게 될까요?

라고 해주셨는데 그럼 Car 에 strategy를 할당하는 방향은 어떻게 생각하시나요?

2022-10-08 16:47 UTC, cyj199637 commented on src/main/java/racingcar/Racing.java
> +        int maxPosition = cars.maxPosition();
`우승자` 라는 개념이 n대의 Car 를 관리하는 Cars 보다는 게임을 진행하는 Racing 에서 관리해야 되지 않을까?
라는 생각에서 해당 메소드를 Racing 에서 구현하게 되었는데요! 이 부분에 대해서는 어떻게 생각하시나요??

2022-10-08 16:52 UTC, cyj199637 commented on src/main/java/racingcar/Racing.java
> +    public Racing(List<String> carNames, NumberGenerateStrategy strategy) {
처음에는 말씀해주신대로 Racing 내부에서 생성해서 관리하다가 테스트가 어려워져서 다음과 같은 방법으로 바뀌었는데요!
역시 다른 방식을 고민해봐야겠네용

2022-10-09 09:53 UTC, lowoon commented on src/main/java/racingcar/Cars.java
>      public void moveAll() {
'전략에 의한 숫자의 생성을 어디의 책임으로 볼것이냐'에 대한 개인의 의견에 따라 다를 것 같은데요.
저는 car에서 할당받아서 사용해도 괜찮다고 생각합니다.
실제로 숫자를 사용하는 곳이 car이기 때문에 car내부에서 사용할 숫자를 만들어서 사용하는 것도 car의 책임에 포함시킬 수 있을 것 같아요!

2022-10-09 09:59 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +        int maxPosition = cars.maxPosition();
이 부분에 대해서는 저도 계속해서 고민을 하는 부분인데요.
'cars에서 비지니스 로직에 대해 어디까지 알게 할거냐'에 대해서 고민해보고 개인의 기준을 만들어야 한다고 생각합니다.
car의 move 메서드의 경우에도 특정 숫자 이상일 때만 이동을 하게 되는데 이 부분도 게임 진행과 관련이 있는 부분이니까요.
저는 개인적으로 cars가 car의 list를 가지고 있기 때문에 racing에서 get해서 게산을 하기보다 데이터를 가지고 있는 객체에게 물어보는 것이 맞다고 생각합니다.
`우승자`라는 개념을 분리하고 싶다면 racing에서 maxPosition을 가져오고 가져온 값을 parameter로 메서드에 넘겨서 parameter의 값과 같은 car들을 반환한다고 하면 우승자의 개념이 사라지지 않을까요?
```java
public List<String> getSamePositionCars(int position) {
        return cars.stream()
            .filter(car -> car.getPosition() == position)
            .map(Car::getName)
            .collect(Collectors.toList());
}
```

2022-10-09 10:23 UTC, lowoon requested changes
안녕하세요 yoonjeong님!
코멘트 반영 잘 해주셨네요 👍 
질문에 답변 남겼고, 코멘트도 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-09 10:23 UTC, lowoon commented on src/main/java/racingcar/Racers.java
> +    public List<Integer> positions() {
가지고 있는 데이터를 반환할 때는 get으로 많이 표현하는 것 같아요!

2022-10-09 10:23 UTC, lowoon commented on src/main/java/racingcar/Racers.java
> +        carNames.forEach(name -> {
생성자에서는 변수에 할당하는 방식으로 많이 사용하는 것 같아요!
```java
        this.cars = carNames.stream()
            .map(Car::new)
            .collect(Collectors.toList());

```

2022-10-09 10:23 UTC, lowoon commented on src/main/java/racingcar/dto/RacingInput.java
> +
모든 입력에 대한 검증을 맡고 있는데요.
Name과 Number객체로 나누어서 관리할 수도 있지 않을까요?

2022-10-09 10:23 UTC, lowoon commented on src/main/java/racingcar/dto/RacerResult.java
> +        racerResult.carName = car.getName();
기본 생성자를 만들어서 아래와 같이 할 수 있지 않나요??
```java
return new RacerResult(car.getName(), car.getPosition());
```

참고하시면 좋을것 같아요!
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2022-10-09 10:23 UTC, lowoon commented on src/main/java/racingcar/dto/RacingResult.java
> +        RacingResult racingResult = new RacingResult();
여기도 기본 생성자를 만들고 할당해서 return할 수 있지 않나요?

2022-10-09 10:23 UTC, lowoon commented on src/test/java/racingcar/RacingTest.java
> +        Racing racing = new Racing(carNames, new SameNumberGenerateStrategy());
strategy를 만들때 생성자의 parameter로 List<Integer>를 넘겨서 list의 있는 값을 return하도록 하면 임의로 우승자도 만들 수 있을 것 같아요!
이러한 방법도 있다고 참고만 하시면 될 것 같습니다ㅎㅎ

2022-10-10 11:34 UTC, cyj199637 commented on src/main/java/racingcar/Racing.java
> +        int maxPosition = cars.maxPosition();
우승자 개념을 어떻게 분리할지에서 막혔었는데 제안해주신 코드가 많은 도움이 되었습니다! 감사합니다:)

2022-10-10 11:42 UTC, cyj199637 commented on src/main/java/racingcar/dto/RacerResult.java
> +        racerResult.carName = car.getName();
참고 문서 감사합니다:)

2022-10-11 00:11 UTC, lowoon approved these changes
안녕하세요 yoonjeong님!
리뷰 반영 잘 해주셨네요 👍 
이만 step4는 머지하도록 하겠습니다.
코멘트 남겼으니 확인해 주시고 step5에 반영해주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-11 00:11 UTC, lowoon commented on src/main/java/racingcar/Car.java
> +        this.strategy = new RandomNumberGenerateStrategy();
제가 괜찮다고 말씀드린 부분은 car에서 strategy를 할당하는게 아니라 move의 parameter로 넘겨서 car까지 strategy를 알아도 될 것 같다는 의미였습니다;;;;
다음 로또 미션에서 진행을 할텐데 현재 구조에서 몇개는 random으로 진행을 하고 몇개는 지정한 숫자로 진행을 하는 경우를 만들 수 있나요?
전략이라고 하는 부분은 자동차 경주 전체 로직, 흐름과 관련이 있는 부분이기 때문에 racing에서 관리를 해야한다고 생각하는데요.
이 부분에 대해서 고민해보시면 좋을 것 같아요!

2022-10-11 00:11 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +    public Racing(final List<String> carNames, final NumberGenerateStrategy strategy) {
테스트에서만 사용이 되고 있는데요.
Racing에 strategy를 넘겨서 우승자가 예상한대로 나오는지를 테스트 하고 싶은 거라면 위의 이름만 있는 생성자는 제거하고 해당 생성자만 사용해도 되지 않을까요?

2022-10-11 00:12 UTC, merged

2022-10-12 13:43 UTC, cyj199637 commented on src/main/java/racingcar/Racing.java
> +    public Racing(final List<String> carNames, final NumberGenerateStrategy strategy) {
제거를 하면 좋을 생성자가 Racing의 생성자가 맞을까요?? 그렇게 되면 위에서 리뷰해주신 것처럼 strategy를 내부에서 생성해서 관리하기가 어려워 보이는데...제가 잘못 이해한걸까요??

2022-10-13 08:16 UTC, lowoon commented on src/main/java/racingcar/Racing.java
> +    public Racing(final List<String> carNames, final NumberGenerateStrategy strategy) {
위에서 제가 strategy를 racing 내부에서 생성해서 관리하는 것을 말씀드렸었는데 잘못 말씀드린 것 같아요 😭 죄송해요
이름만 받는 생성자는 제거하고 전략을 넘겨받는 생성자만 남기는게 좋을것 같습니다.
racing에서 관리는 하되 내부에서 생성이 아닌 생성자로 주입을 받는 형태가 확장성에 용이할 거에요.
처음에 yoonjeong님이 구현해주신 방법이 맞는 방법이였습니다!