4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #3889
Opened 2022-10-08 12:16 UTC by 0chil

안녕하세요 희주님! 이제 날씨가 춥네요 🥶 건강 조심하세요!
지난 단계에서의 피드백도 반영 후 미션을 시작했습니다.
리뷰 잘 부탁드립니다.
이번 미션도 [노션](https://www.notion.so/4-3fe39dfadc984d89bdfa914ab2efbb83)에 정리하며 진행했는데 시간되시면 한번 봐주시면 감사하겠습니다!

2022-10-09 12:23 UTC, choihz requested changes
안녕하세요, 성철님!

구현해 주신 내용과 작성해 주신 문서를 확인하고 몇 가지 코멘트를 남겨 두었습니다. 궁금한 점이나 의견이 있으실 땐 부담 없이 코멘트나 DM 주세요.

성철님도 항상 건강 잘 챙기시고요!! ☺️

2022-10-09 12:23 UTC, choihz commented on src/main/java/racingcar/domain/Car.java
> +	}
> - `compareTo()`는 어떨까?
>     
>     우선 `position`은 확실히 대소비교의 대상이다.
>     
>     name은 사전순으로 대소비교할 수는 있으나, 현재 도메인에서는 그런 비교가 유효하지 않은 것 같다.
>     
>     크기를 비교한다면 `position`만 비교하는게 맞아보인다.
>     
>     따라서 **position만을 비교하는 기존의 상태를 유지**하려고 한다.
>     
>     - `Comparable` 인터페이스에 `(x.compareTo(y)==0) == (x.equals(y))` 를 왠만하면 지키라고 써있다.
>         - 지키지 않는다면 별도로 명시하라고 쓰여있다. 난 안 지킬거니까 주석으로 명시해줘야겠다.

사실 `equals()`나 `compareTo()` 같은 메서드를 구현할 때, 일반적으로 널리 받아들여지는 규약을 지키지 못하는 상황이라면, 정말 그것을 구현해야만 하는 상황인지 고민해 보고 그렇지 않다면 구현하지 않는 편이 더 낫다는 생각이 들어요. 지금의 `Car`도 꼭 `compareTo()`가 필요한 상황은 아닌 것 같아요.

2022-10-09 12:23 UTC, choihz commented on src/main/java/racingcar/Game.java
>  	}
메서드를 어떤 순서로 배치하는 중이신가요?

2022-10-09 12:23 UTC, choihz commented on src/main/java/racingcar/domain/Cars.java
>  	}
`maxCar`라는 건 두 개 이상일 수 있지만 여기서는 하나만 리턴되겠네요. 그런데 사실 중요한 건 `maxCar`가 아니라 `maxPosition` 아닐까요? 게다가 이건 두 개 이상일 수 없죠.

2022-10-09 12:23 UTC, choihz commented on src/test/java/racingcar/domain/CarTest.java
> +	}
이 테스트는 getter를 테스트하고 있는 걸까요? 단순 getter까지 확인할 필요가 있을까요?

2022-10-09 12:23 UTC, choihz commented on src/test/java/racingcar/domain/PositionTest.java
> +	}
> - 생성자는 다른 곳에서도 많이 쓰이므로 작성하지 않아도 매번 테스트 될 것이다.
>     
>     아무 로직도 없고 단순히 상태를 꺼내거나, `private` 필드를 설정하는 데 테스트가 필요할까?
>     
>     아니라고 생각이 든다.
>     
>     그러나 생성자에 따로 테스트 할 수 없는 로직이 있다면, 이에 대한 테스트는 필요할 것이다.
>     
>     (그런 생성자는 만들면 안되는 것이 아닐까)

이 테스트는 생성자 테스트가 아닌가요? 생성자 외 다른 메서드를 통해 테스트할 수는 없는 로직으로 보이는데, (작성하신 내용에 따르면) 이 생성자는 올바른 생성자가 아닌 걸까요?

2022-10-09 12:23 UTC, choihz commented on src/test/java/racingcar/domain/PositionTest.java
> +			.isInstanceOf(RuntimeException.class);
더 구체적인 예외로 검증하면 좋을 것 같아요!

2022-10-09 12:23 UTC, choihz commented on src/main/java/racingcar/domain/Name.java
> +	private static final String DEFAULT_NAME = "이름 없음";
> “기본값”을 만드는 것이 잘 하는 행동인지는 모르겠다.

사실 이건 비즈니스적인 결정일 것 같아요. 비즈니스 로직에서 기본값을 필요로 한다면 그렇게 구현하면 되는데, 그렇지 않은 경우이고 기본 동작을 쉽게 예상할 수 없다면, 차라리 안 만드는 게 나을 수도 있다는 생각이 들어요.

2022-10-12 10:01 UTC, 0chil commented on src/main/java/racingcar/Game.java
>  	}
비슷한 성격의 메서드끼리 배치하고 있고, 상수 - 인스턴스 변수 - 생성자 - 메서드 - 게터 순으로 배치하고 있습니다. 
알파벳과 같은 정렬은 따로 하고 있지 않아요.

2022-10-12 11:29 UTC, 0chil commented on src/main/java/racingcar/domain/Name.java
> +	}
앞 뒤로 공백을 입력하면 공백도 이름의 일부로 인정하고 있습니다.
`validateNameNotBlank` 는 이름이 공백으로만 이루어지지 않았음을 검증하는 메서드입니다.

2022-10-13 08:37 UTC, 0chil commented on src/main/java/racingcar/domain/Car.java
> +	}
무슨 말씀인지 잘 이해했습니다. 아예 구현하지 않는 게 더 나을 수 있겠네요.
이 커멘트를 보고 아예 제거해보려고 했습니다.
maxPosition() 은 `Cars` 에서, 차끼리 위치 비교는 상태를 꺼내지 않고, `Car`에서 하고 싶은데 그렇게 하기가 쉽지 않네요.

1) `Car` 의 `hasPositionGreaterThan()`
<img width="508" alt="image" src="https://user-images.githubusercontent.com/39221443/195353680-4d15e6df-0320-4e56-b581-a649cf0cee5d.png">

2) `Cars`의 `findWinnerNames()`
<img width="502" alt="image" src="https://user-images.githubusercontent.com/39221443/195353424-a656484a-6a7e-4b97-a735-24c7b8f8ae35.png">

3) `Cars`의 `getMaxPosition()` << 고민되는 부분
- 선택 1. 상태 값(`int`)을 꺼내어 비교한다
  <img width="454" alt="image" src="https://user-images.githubusercontent.com/39221443/195353463-844c646e-1560-4d01-acb7-741dd422a9ad.png">


- 선택 2. 상태 값을 최대한 꺼내지 않고 비교한다 (`Car`-`Car` 비교)
  <img width="413" alt="image" src="https://user-images.githubusercontent.com/39221443/195355285-df5ce334-a139-4a84-a020-086ec2fb707a.png">

- 선택 3. `Position` 객체를 꺼내어 비교한다
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/39221443/195356544-e30a6269-6b74-4eb5-8bfb-a4685271fdbf.png">

2022-10-13 09:25 UTC, 0chil commented on src/test/java/racingcar/domain/CarTest.java
> +	}
생성부터 출력까지 상태가 잘 유지되는지 체크하는 테스트이므로 필요할 것 같습니다!
이게 없다면 차에 이름이 잘 부여되었는지 확인을 `CarsTest`에서 하게 될 것 같아서 필요한 테스트라고 생각합니다.

2022-10-14 08:58 UTC, 0chil commented on src/test/java/racingcar/domain/PositionTest.java
> +	}
~~(그런 생성자는 만들면 안되는 것이 아닐까)~~ -> 생성자가 하는 일이 따로 있는 경우(검증 등)은 별다른 방법이 없으니 테스트해야 할 것 같아요.

2022-10-14 10:57 UTC, 0chil commented on src/main/java/racingcar/domain/Cars.java
>  	}
동의합니다. 우승자를 찾는데 필요한 것은 `maxCar`가 아니라 `maxPosition`이죠!
`compareTo()` 오버라이딩은 제거했습니다. 
하지만 위치를 꺼내어 비교하는 것이 아니라, `Car`끼리 비교하는 것은 중요하다고 생각했기 때문에
조금 다른 방식으로 의도를 더 명확하게 드러내도록 수정했습니다.

2022-10-14 11:29 UTC, 0chil commented
`Car`의 `compareTo()` 와 `equals()`를 모두 제거했습니다. 
하지만 위치를 꺼내어 비교하는 것이 아니라, Car끼리 비교하는 것은 중요하다고 생각해서
조금 다른 방식으로 의도를 더 명확하게 드러내도록 수정했습니다.

2022-10-14 11:33 UTC, 0chil commented on src/main/java/racingcar/domain/Car.java
> +
차끼리 비교하는 부분은 이곳입니다!

2022-10-14 11:33 UTC, 0chil commented on src/main/java/racingcar/domain/Cars.java
> +	}
우승자를 찾는 부분입니다

2022-10-15 13:31 UTC, choihz approved these changes
안녕하세요, 성철님!

수정해 주신 내용을 확인하고 몇 가지 코멘트를 남겨 두었습니다. 다음 단계를 진행하며 함께 확인해 주세요~

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Name.java
> +		}
매직 넘버는 상수로 만들 수 있겠죠?

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Cars.java
> +		if (cars.size() <= 0) {
`cars.size()`는 음수가 될 수 없기 때문에, 0인지만 보면 되겠네요~

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Cars.java
> +			throw new CarCountException("자동차는 1개 이상이어야 합니다");
```suggestion
			throw new CarCountException("자동차는 1대 이상이어야 합니다");
```

ㅎㅎㅎ

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Car.java
> +	}
`Position` 객체를 직접 받는 것이 아니라 안에서 생성하는 것이 어색하게 느껴지는 것 같아요.

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Car.java
>  	@Override
`name`이 추가되었는데 `toString()`은 수정되지 않아도 될까요?

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/domain/Cars.java
> +	}
> 하지만 `new Car()`를 만드는게 조금 마음에 걸린다.

스트림과 `reduce()` 사용을 고려해 보셔도 될 것 같아요.

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/Game.java
>  	}
> 비슷한 성격의 메서드끼리 배치하고 있고, 상수 - 인스턴스 변수 - 생성자 - 메서드 - 게터 순으로 배치하고 있습니다. 
> 알파벳과 같은 정렬은 따로 하고 있지 않아요.

여기서 순서에 관해 여쭤보았던 이유는, `main()`에서 실제로 사용되는 순서와 다르게 배치되어 있어서였어요 👀

2022-10-15 13:31 UTC, choihz commented on src/main/java/racingcar/Game.java
>  	}
또한 이 메서드들이 실제로 `Game`에 필요한지도 생각해 볼 만한 문제인 것 같아요. 콘솔에 출력하는 로직은 무조건 `OutputView`에 있어야 할까요? 그 출력이 입력을 받기 위한 것이라도요.

2022-10-15 13:31 UTC, merged

2022-10-16 13:27 UTC, 0chil commented on src/main/java/racingcar/domain/Car.java
> +	}
이 부분은 어떻게 개선할지 더 고민해보겠습니다

2022-10-16 13:28 UTC, 0chil commented on src/main/java/racingcar/domain/Car.java
>  	@Override
수정이 필요하겠네요.!

2022-10-16 13:30 UTC, 0chil commented on src/main/java/racingcar/domain/Cars.java
> +	}
Reduce() 사용! 고려해보겠습니다.

2022-10-16 13:38 UTC, 0chil commented on src/main/java/racingcar/Game.java
>  	}
View 는 입출력 로직을 담당하고, `InputView` 는 입력을 위한 입출력 로직을 담당하므로
`InputView`에 출력이 함께 들어가면 이런 메서드가 필요하지 않겠네요!
메서드가 잘못된 곳에 들어가 오히려 응집력이 부족해졌다는 생각이 듭니다..!