자동차 경주 5단계
next-step/java-racingcar pull request #3903
Opened 2022-10-10 06:56 UTC by samkimuel

안녕하세요! 이제 마지막 단계 PR 이네요ㅎㅎ

리팩토링 하면서 수정한 부분이 조금 있는데, 부족한 부분 피드백 부탁드립니다!

감사합니다🙇‍♂️

2022-10-10 12:26 UTC, ksy90101 requested changes
안녕하세요 :)
마지막 5단계까지 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 한번 확인해보시면 좋을듯 합니다.
질문은 언제든지 DM이나 코멘트로 남겨주세요~

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/domain/Game.java
> +        this.randomValueGenerator = randomValueGenerator;
숫자를 생성하는 전략인듯 한데, 이름 자체가 무조건 랜덤값을 생성하는 전략같네요.
이름을 좀 더 변경해보면 어떨까요?

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/view/ResultView.java
>  public class ResultView {
InputView에 오타가 있네요.

private static final String COMMA_SEPERATOR = ",";

private static final String COMMA_SEPARATOR = ",";

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/RacingCarApp.java
> +import racingcar.step3_4.domain.RandomValueGenerator;
RandomValueGenerator은 도메인일까요?

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +        }
```suggestion
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(String.valueOf(DASH_MARK).repeat(Math.max(0, carPosition)));
```

이런식도 가능합니다 :)

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +            stringBuilder.append(" : ");
이 부분도 매직스트링으로 하면 어떨까요?

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +            .collect(Collectors.joining(", "));
여기도 상수로 관리하면 좋을듯 하네요.

2022-10-10 12:26 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +            .map(Name::toString)
https://velog.io/@tonic523/toString%EA%B3%BC-view%EB%8A%94-%EC%96%B4%EB%96%A4-%EC%B0%A8%EC%9D%B4%EA%B0%80-%EC%9E%88%EB%82%98%EC%9A%94

이글을 한번 참고해볼까요?

2022-10-10 12:53 UTC, samkimuel commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +        }
익숙한 for문 사용했는데, 이게 더 깔끔해보이네요!👍

2022-10-10 13:10 UTC, samkimuel commented on src/main/java/racingcar/step3_4/RacingCarApp.java
> +import racingcar.step3_4.domain.RandomValueGenerator;
도메인이 의존하고 있어서 함께 두었는데, 다른 패키지로 구분하겠습니다.
아니면 도메인 패키지의 하위 패키지로 구분하는 게 좋을까요??

2022-10-10 13:10 UTC, samkimuel commented on src/main/java/racingcar/step3_4/view/ResultView.java
> +            .map(Name::toString)
객체를 그대로 반환하는 것에서 객체의 값을 반환하도록 수정했습니다~!

2022-10-11 10:40 UTC, ksy90101 commented on src/main/java/racingcar/step3_4/RacingCarApp.java
> +import racingcar.step3_4.domain.RandomValueGenerator;
현재 자동차 경주를 하면서 어떻게 패키지 전략을 가져가고 싶으신지 고민해보세요 :) 
어떤방식을 하실 예정이였나요~?
예를들면 MVC로 나눌수도 있을테고, 아니면 도메인별로 묶고 싶기도 하셨울거 같은데요 ㅎㅎ

2022-10-11 12:02 UTC, ksy90101 approved these changes
안녕하세요 :) 5단계까지 너무 고생 많으셨습니다 💯 
이만 자동차 경주게임은 끝내도록 할게요!
다음 미션 로또도 파이팅입니다~

2022-10-11 12:02 UTC, merged