Step4 리뷰 요청
next-step/java-racingcar pull request #3913
Opened 2022-10-11 13:09 UTC by jackson-hong

항상 좋은 피드백 감사합니다 👍

2022-10-12 00:24 UTC, seokhongkim requested changes
지운님 4단계 미션 잘 구현해주셨습니다. 👍 

조금 더 고민해보시면 도움이 될 것 같은 부분이 있어 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙏 

코멘트와 관련하여 질문이나 같이 논의해보면 좋을 내용이 있다면 깃헙 코멘트 또는 슬랙 DM으로 편하게 말씀 부탁드려요. 😀

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/core/Car.java
> +    private final String carName;
자동차의 이름과 위치를 관리하는 값 객체를 만들어보시면 좋을 것 같아요.
자동차 이름은 null, 빈 문자열일 수 없고 길이가 5 이하여야 하는 제약 조건을 가지고 있네요.
자동차의 위치도 0보다 큰 값이어야 하고, `이동하라` 는 요청에 한 칸씩 이동하는 특성을 가지고 있는 것으로 보입니다. :)

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/core/RacingApp.java
> +    private final Validator validator = new Validator();
자동차 이름을 관리하는 객체를 만들면 `Validator` 가 하는 일을 해당 객체에게 전달할 수 있겠네요!

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/core/Referee.java
> +    public List<Car> getWinners(List<Car> cars) {
자동차 목록을 관리하는 일급 컬렉션을 만들어보면 어떨까요?
해당 클래스를 통해 가장 앞에 있는 자동차 목록을 가져와도 좋겠네요.

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/view/ResultView.java
> +        if (winners.size() == 1) {
`String.join` 을 사용해서 분기문과 반복문을 제거해보면 어떨까요?

2022-10-12 00:24 UTC, seokhongkim commented on src/test/java/racing/core/RefereeTest.java
> +public class RefereeTest {
꼼꼼한 단위 테스트 작성 좋습니다. 👍

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/core/Validator.java
> +       if(carName.length() > 5) throw new RuntimeException("car name is too long");
예외 상황을 조금 더 잘 표현해줄 수 있는 예외는 무엇이 있을까요?

2022-10-12 00:24 UTC, seokhongkim commented on src/main/java/racing/core/Validator.java
> +       if(carName.length() > 5) throw new RuntimeException("car name is too long");
`5` 라는 값도 상수로 관리해보면 어떨까요?

2022-10-12 07:01 UTC, jackson-hong commented on src/main/java/racing/core/Car.java
> +    private final String carName;
혹시 Car 객체 자체에서 제약조건을 관리하는 것은 어떤가요?

2022-10-12 13:09 UTC, jackson-hong commented on src/main/java/racing/core/Referee.java
> +    public List<Car> getWinners(List<Car> cars) {
일급 컬렉션 구현 중에 한가지 궁금증이 생겼습니다~!
혹시 석홍님께서는 일급컬렉션의 equals의 경우는 어떻게 구현하시나요?

2022-10-12 23:59 UTC, seokhongkim commented on src/main/java/racing/core/Car.java
> +    private final String carName;
현 시점에 `Car` 에서 관리하는 것이 큰 부담은 안 될 수 있지만, 아래와 같은 부분을 고려할 때 별도의 클래스로 분리하는 것이 좋다고 생각합니다.
1. 클래스가 알아야 하는 비즈니스 규칙의 범위가 작아져서 클래스의 복잡도가 내려가고, 밀집도는 올라갑니다.
2. 자동차 이름이나 위치가 프로젝트 내에서 `String`, `int` 대신 사용될 수 있으며, 자동차 이름과 위치를 사용하는 곳에서는 특정한 제약조건을 만족하는 값이 있을 것이라고 생각할 수 있습니다.

2022-10-13 00:08 UTC, seokhongkim requested changes
지운님, 4단계 미션 피드백 잘 반영해주셨습니다. 👍 
다음 단계로 넘어가기 전 조금 더 고민해보시면 좋을 것 같은 부분이 있어 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-10-13 00:08 UTC, seokhongkim commented on src/main/java/racing/core/CarList.java
> +public class CarList {
이후에 내부 구현이 `Set` 으로 변경된다면 클래스의 이름이 `CarSet` 으로 변경될까요? :)
클래스의 이름과 메소드의 이름에는 세부 구현에 대한 내용이 들어가지 않는 것이 좋습니다.
그래야 이후 구현이 변경하는 작업을 더 쉽게 진행할 수 있습니다.

2022-10-13 00:08 UTC, seokhongkim commented on src/main/java/racing/core/CarList.java
> +    public boolean equals(Object o) {
`AbstractList` 의 `equals` 구현을 참조해보시고, 이걸 사용하는 방법을 고민해보시면 어떨까요?
더 쉽게 구현하는 방법도 있을 것 같습니다. :)

2022-10-13 00:08 UTC, seokhongkim commented on src/main/java/racing/core/Referee.java
> +    public CarList getWinners(CarList cars) {
여기에서 주요 로직을 구현하기 위해 `CarList` 를 데이터 저장소처럼 사용하는 것으로 보입니다. `CarList` 의 내부 구현을 아는 상태에서 순서대로 메소드를 호출해서 `Referee` 가 로직을 구현하는 형식이죠. 그렇다면 `CarList` 와 `Referee` 는 강한 결합을 가지고 있는 것은 아닐까요?

`CarList` 에게 `우승자 목록을 달라` 고 요청해보면 어떨까요?

2022-10-13 23:33 UTC, seokhongkim approved these changes
지운님, 4단계 미션 피드백 잘 반영해주셨습니다. 👍 

4단계 PR은 이만 머지하도록 하겠습니다.
코멘트 조금 남겼는데, 5단계 미션 진행하실 때 참고해보셔도 좋겠습니다. :)

5단계 미션에서 뵙겠습니다. 😀

2022-10-13 23:33 UTC, seokhongkim commented on src/main/java/racing/core/CarDetails.java
> +public class CarDetails {
`distance` 와 `carName` 이 `CarDetails` 로 감싸졌지만, 거리와 자동차 이름만 관리하는 클래스는 없는 것 같아요.
이 부분은 나중에 값 객체에 대해 조금 더 고민해보시면 도움이 될 것 같습니다.

`distance` 와 `carName` 을 관리하는 클래스가 별도로 있을 때 얻을 수 있는 장점은 프로젝트 내에서 `Distance`, `CarName` 타입인 경우 특정한 조건을 만족할 것이라는 사실을 알고 사용할 수 있다는 점입니다. 또한 필요한 값만 전달할 수 있죠.
`distance` 와 `carName` 을 모두 사용하는 곳에서는 `CarDetails` 를 사용할 수 있겠지만, 각각의 값만 사용하고 싶은 경우 어려움이 있습니다.

추가로 `Detail`, `Data`, `Information` 과 같은 이름은 구체적인 정보를 전달하지 못하므로 이름을 지을 때 사용하시지 않는 것이 좋습니다. 클린코드 책을 참고해보시면 좋을 것 같아요!
다른 개발자가 봤을 때 `Car` 와 `CarDetails` 의 차이를 이름만 보고 알기 어렵지 않을까요? :)

2022-10-13 23:33 UTC, seokhongkim commented on src/main/java/racing/core/Cars.java
> +    public void sortDesc() {
정렬한 후 첫 번째 자동차를 반환하는 방법을 사용하신 이유가 있을까요?

여쭤보는 이유는 정렬 알고리즘은 O(n log n) 정도의 성능을 보장하므로, 최댓값을 구할 때 1회 스캔하면서 비교하는 알고리즘보다 느립니다. 1회 스캔하면서 비교하면 O(n) 의 시간을 보장할 수 있습니다.
그럼에도 정렬을 선택하신 이유가 있는지 궁금했습니다. :)

2022-10-13 23:33 UTC, seokhongkim commented on src/main/java/racing/core/Cars.java
> +            CarDetails o2CarDetails = o2.getCarDetails();
나중에 `Distance` 만 관리하는 클래스가 만들어진다면, `Comparable` 을 구현하고 이를 이용해서 `sort` 하는 형태로도 변경이 가능할 것 같습니다.

2022-10-13 23:33 UTC, merged