Step4 자동차 경주(우승자)
next-step/java-racingcar pull request #3934
Opened 2022-10-16 04:57 UTC by rshak8912

안녕하세요. 리뷰요청드립니다.

감사합니다

2022-10-16 08:07 UTC, lowoon requested changes
안녕하세요 john님!
4단계도 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/util/RandomUtil.java
>      public static int generateMovePossibleNumber() {
사용하지 않는 객체는 제거하는게 좋을것 같아요.

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    private int tryCount;
view에서 변수를 가지고 있는게 맞을까요?
view의 역할과 책임은 무엇일까요?
view는 static 변수들로 이루어져도 괜찮지 않을까요?
그리고 scanner를 input view에서만 사용하는데 parameter로 전달을 받아야 할까요?

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    public RacingModel getUserInputData() {
view에서 객체를 반환하는게 맞을까요?
view와 도메인이 종속성을 가지면 어떤 부분이 안좋을까요?

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/race/RandomNumberGenerator.java
> +        return new Random().nextInt(RANDOM_NUMBER_UPPER_BOUND);
random을 매번 생성해야하나요?

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
>      private static final int RANDOM_RANGE = 10;
사용하지 않는 변수는 제거하는게 좋습니다

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
> +    private String[] names;
변수와 메서드 사이에는 빈줄로 띄워주는게 다른 개발자들이 보기에 좋습니다

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/race/Result.java
>  public class Result {
이 객체가 필요한가요?
만약 결과를 관리하는 것이라면 결과만 관리해야하지 view를 호출해야할까요?

2022-10-16 08:07 UTC, lowoon commented on src/main/java/racingcar/App.java
> +            cars.getRacingCars().add(new Car(racingModel.getNames()[carIndex],0));
일급객체에서 list를 가져와서 외부에서 추가해주고 있는데요.
이렇게 하면 일급객체의 의미가 없지 않을까요?
일급객체를 사용하는 이유는 무엇일까요?
생성자에서 생성할 수는 없는걸까요?

2022-10-17 23:18 UTC, rshak8912 commented on src/main/java/racingcar/util/RandomUtil.java
>      public static int generateMovePossibleNumber() {
네, 중복되어 있던 것 같습니다.

2022-10-17 23:20 UTC, rshak8912 commented on src/main/java/racingcar/view/InputView.java
> +    private int tryCount;
view는 화면에 보이는 역활을 합니다.
static까지는 고려를 못했는데 static이 좋을 것 같습니다.
메서드 안에서 생성하는게 좋을 것 같습니다.

2022-10-17 23:28 UTC, rshak8912 commented on src/main/java/racingcar/view/InputView.java
> +    public RacingModel getUserInputData() {
view가 도메인에 의존하게 될 것 같습니다.

2022-10-17 23:31 UTC, rshak8912 commented on src/main/java/racingcar/race/RandomNumberGenerator.java
> +        return new Random().nextInt(RANDOM_NUMBER_UPPER_BOUND);
static변수로 변경하였습니다.

2022-10-17 23:32 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingModel.java
>      private static final int RANDOM_RANGE = 10;
네 참고하겠습니다

2022-10-17 23:33 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingModel.java
> +    private String[] names;
네 참고하겠습니다

2022-10-17 23:35 UTC, rshak8912 commented on src/main/java/racingcar/race/Result.java
>  public class Result {
지난 번 리뷰 때 결과를 담당하는 클래스를 만들어보라 하셔서 만들었는데 의도와 맞지 않게 개발을 한 것 같습니다.

https://github.com/next-step/java-racingcar/pull/3885


[lowoon](https://github.com/lowoon) [10 days ago](https://github.com/next-step/java-racingcar/pull/3885#discussion_r990611940)
결과를 담당하는 클래스도 만들면 어떨까요?

Author
@[rshak8912](https://github.com/rshak8912) rshak8912 [9 days ago](https://github.com/next-step/java-racingcar/pull/3885#discussion_r990777406)
Result클래스로 분리하는 방법이 있을 것 같습니다.
분리하여 진행 해보겠습니다.

2022-10-17 23:37 UTC, rshak8912 commented on src/main/java/racingcar/App.java
> +            cars.getRacingCars().add(new Car(racingModel.getNames()[carIndex],0));
저도 개발하면서 의도와 맞지 않은 것이라고 생각하였는데 개선 방법이 떠오르지 않아 개발하였었습니다.
수정하겠습니다

2022-10-19 10:01 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    private int tryCount;
언제 close할지는 inputview에서 모를 것이기 때문에 app에서 하면 되지 않을까요??
흐름을 알고 있는 건 app이니까요

2022-10-19 10:02 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    public RacingModel getUserInputData() {
참고하시면 좋을 것 같아요
https://tecoble.techcourse.co.kr/post/2021-05-16-dto-vs-vo-vs-entity/
https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2022-10-19 10:02 UTC, lowoon commented on src/main/java/racingcar/race/Result.java
>  public class Result {
제가 생각했던 객체의 역할과 다른 것 같아요

2022-10-19 10:12 UTC, lowoon requested changes
안녕하세요 john님!
이전에 남긴 코멘트 반영이 되지 않은 것 같아요!
코멘트 반영해주시고 추가로 코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/race/Car.java
>      }
빈줄로 띄워주면 좋을것 같구요.
위의 생성자는 테스트에서만 사용이 되는데 필요한가요?
테스트만을 위한 코드가 운영코드에 있어도 괜찮을까요?

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
> +    public RacingModel(String[] names, int tryCount) {
RacingModel이 자동차 경주의 비지니스 로직을 담당하는 클래스일까요?
그렇다면 tryCount와 이름을 가지는게 아니가 RacingCars를 가지고 있어야하지 않을까요?
tryCount는 가지고 있지않고 race를 실행할때 넘겨받을 수 있지 않을까요?

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
> +        final NumberGenerator numberGenerator = new RandomNumberGenerator();
메서드 내부에서 생성을 하고 있는데요.
만약 다른 generator가 추가되면 또 메서드 내에서 생성하는 걸까요?
RacingModel을 생성할 때 넘겨받는건 어떨까요?

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/util/RandomUtil.java
>      public static int generateMovePossibleNumber() {
제거가 안된 것 같아요

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +        this.names = inputName.split(",");
한번에 모든 입력을 다 받기보다 시도 횟수 입력과 이름 입력의 메서드를 분리하면 어떨까요?

2022-10-19 10:12 UTC, lowoon commented on src/main/java/racingcar/race/RacingCars.java
> +        this.racingCars.add(car);
테스트가 없는것 같고 list를 가지고 있는 것 외에 역할이 없는것 같아요.

2022-10-22 16:41 UTC, rshak8912 commented on src/main/java/racingcar/view/InputView.java
> +        this.names = inputName.split(",");
제거하였습니다
네 분리하겠습니다.

2022-10-22 16:42 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingModel.java
> +        final NumberGenerator numberGenerator = new RandomNumberGenerator();
외부에서 생성 후 넘기는 방법이 유연한 것 같습니다.
적용하겠습니다.

2022-10-22 16:49 UTC, rshak8912 commented on src/main/java/racingcar/race/Car.java
>      }
네 적용하였습니다

2022-10-22 17:06 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingModel.java
> +    public RacingModel(String[] names, int tryCount) {
네 수정하겠습니다

2022-10-22 17:13 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingCars.java
> +        this.racingCars.add(car);
일급객체로 관리하는 것 외에 더 부가적으로 할 수 있는게 어떤 게 있을까요?
테스트는 추가하겠습니다

2022-10-23 09:36 UTC, lowoon approved these changes
안녕하세요 john!
이번에도 코멘트 단 내용이 다 반영이 되지 않은 것 같아요...
이번 단계는 이만 머지하도록 하겠습니다.
코멘트 확인해서 다음 미션에는 꼭 반영주세요

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/race/Car.java
> +    public Car(String name, int position) {
이름만 가지는 생성자는 제거하고 name과 positon을 parameter로 받는 생성자만 있어도 되지 않나요?
그리고 메서드, 생성자들도 빈줄로 띄워주는 것이 보기 좋습니다.

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +    public static int tryCount;
input view에서는 변수가 필요없지 않을까요?
그리고 scanner는 inputview에서만 사용하기 때문에 내부에서 생성해서 관리해도 되지 않을까요?

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/view/ResultView.java
> +    public ResultView(RacingCars racingCars) {
result view가 result를 받아서 데이터를 뽑아내서 print하는게 좋지 않을까요?
result에서 view를 가지면 어떤점이 안좋을까요?

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/race/RandomNumberGenerator.java
> +        return new Random().nextInt(10);
매번 random을 생성해야 할까요?

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/race/RacingCars.java
>      public List<Car> getRacingCars() {
```java
public class ClassName {
	// private static final
	// 상수
	// 클래스 변수
	// 인스턴스 변수
	// 생성자
	// 팩토리 메서드
	// 일반 메서드
	// getter, setter
	// equals, hashCode, toString
}
```
순으로 작성하는 것이 좋습니다.
그리고 app에서 RacingCars를 만들어서 add하는 것이 아닌 정적팩토리 메서드로 input name을 받아서 내부에서 racingCars를 생성할 수 있지 않을까요

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
> +    public void racingStart(RacingCars racingCars, NumberGenerator numberGenerator) {
이 메서드는 racingCars가 가지고 있어야하지 않을까요?
데이터를 가지고 있는 객체에게 물어보는 것이 아닌 데이터를 꺼내서 로직을 돌게하는 이유가 있나요?

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/App.java
> +        initRacingCar(cars);
racingModel이 자동차경주의 비지니스 로직을 담당하는 걸까요?
그러면 racingModel내부에 racingCars를 가질 수 있을 것 같구요.
```java
String names = InputView.receiveNames();
RacingModel racingModel = new RacingModel(names);
Result result = racingModel.race(InputView.receiveTryCount());
ResultView.printResult(result);
```
순으로 로직을 짤 수 있지 않을까요?
어떤 차이가 있고 어떤점이 좋을까요?

2022-10-23 09:36 UTC, merged

2022-10-23 09:36 UTC, lowoon commented on src/main/java/racingcar/race/RacingCars.java
> +        this.racingCars.add(car);
추가로 단 [코멘트](https://github.com/next-step/java-racingcar/pull/3934#discussion_r1002676297) 내용을 확인하면 좋을것 같습니다.

2022-10-23 12:19 UTC, rshak8912 commented on src/main/java/racingcar/race/Car.java
> +    public Car(String name, int position) {
네 참고하겠습니다

2022-10-23 12:21 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingCars.java
>      public List<Car> getRacingCars() {
네 참고하겠습니다.

2022-10-23 12:22 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingModel.java
> +    public void racingStart(RacingCars racingCars, NumberGenerator numberGenerator) {
"데이터를 가지고 있는 객체"를 고려하지 못하였던것 같습니다.

2022-10-23 12:23 UTC, rshak8912 commented on src/main/java/racingcar/App.java
> +        initRacingCar(cars);
작성하신 코드가 의미가 간결하고 역할과 책임이 분리된 것같습니다.

2022-10-23 15:39 UTC, rshak8912 commented on src/main/java/racingcar/view/ResultView.java
> +    public ResultView(RacingCars racingCars) {
view에 의존적이게 될 것 같습니다

2022-10-23 15:39 UTC, rshak8912 commented on src/main/java/racingcar/view/InputView.java
> +    public static int tryCount;
참고하겠습니다.