Step5 자동차 경주 리팩토링
next-step/java-racingcar pull request #3971
Opened 2022-10-25 15:32 UTC by rshak8912

안녕하세요. 지난 step4에서 피드백 주셨던 내용 최대한 반영하였습니다.

피드백 많은 도움 되었습니다.

감사합니다

2022-10-26 08:34 UTC, lowoon requested changes
안녕하세요 john님!
5단계도 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
>          System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
정보에 대해서 노출하는 것을 scanner와 묶을 수 있을것 같아요.
input을 받기위해 하나의 메서드라고 봐도 될 것 같아서요.

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/race/RacingCars.java
> +        return new RacingCars(cars);
```java
        List<Car> cars = Arrays.stream(names)
            .map(name -> new Car(name, 0))
            .collect(Collectors.toList());

        return new RacingCars(cars);
```
처럼 할 수 있을 것 같아요~

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/race/RacingCars.java
> +    public static void addCar(Car car) {
테스트에서만 사용하는 코드인데요.
테스트만을 위한 코드가 운영코드에 있어도 괜찮을까요?

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/race/Result.java
> +        for (int trys = 0; trys < racingModel.getTryCount(); trys++) {
Result 역할이 애매한것 같은데요.
Result는 실제로 실행한 결과만 가지고 있어야하는 것 아닌가요?
결과가 경주를 실행시키는 것이 맞을까요?
그리고 경주 실행이 중요 비지니스 로직인데 테스트가 없는 것 같아요

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/App.java
> +        RacingModel racingModel = new RacingModel(tryCount);
```java
RacingModel racingModel  = new RacingModel(names, tryCount); // 내부에서 cars 생성
Result result = new Result(racingModel.race()); // race의 return으로 게임 결과 
```
RacingModel을 비지니스 로직을 담당하는 객체로 정의한다면 위와 같이 진행할 수 있을 것 같구요.
tryCount의 경우에는 원시값 포장 객체를 만들어서 양수에 대한 검증을 위임할 수 있을 것 같아요

2022-10-26 08:34 UTC, lowoon commented on src/main/java/racingcar/view/ResultView.java
> +    private static RacingCars racingCars;
cars를 내부에 가지는게 아니라 parameter로 받아서 보여주면 되지 않나요?

2022-10-29 08:47 UTC, rshak8912 commented on src/main/java/racingcar/view/InputView.java
>          System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
네 receiveNames()와 묶었습니다

2022-10-29 08:48 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingCars.java
> +        return new RacingCars(cars);
감사합니다. 반영하겠습니다

2022-10-29 08:51 UTC, rshak8912 commented on src/main/java/racingcar/race/RacingCars.java
> +    public static void addCar(Car car) {
테스트에서만 사용하는 코드는 제거되어야 합니다. 테스트 방식을 수정하겠습니다.

2022-10-29 09:24 UTC, rshak8912 commented on src/main/java/racingcar/view/ResultView.java
> +    private static RacingCars racingCars;
네 수정하겠습니다

2022-10-29 12:13 UTC, rshak8912 commented on src/main/java/racingcar/App.java
> +        RacingModel racingModel = new RacingModel(tryCount);
첫줄은 수정하겠습니다.
둘째줄 코드는 이해가 가질 않습니다.
race의 return으로 게임결과를 return 하는데, 그 결과를 받아서 Result를 생성한다는 의미가 와닿지 않습니다.

2022-10-29 12:16 UTC, rshak8912 commented on src/main/java/racingcar/race/Result.java
> +        for (int trys = 0; trys < racingModel.getTryCount(); trys++) {
Result는 게임의 진행과 그 단계를 보여주는 용도로 아래와 같은 규칙을 참고하여 개발하였었습니다.

"자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다."


그리고 피드백 해주신 내용을 바탕으로 ResultView에서는 결과를 출력하지만, 최종 결과(승자)만 출력하였습니다.
Result는 게임의 진행 상태를 갖고, ResultView에서 우승자를 출력하도록 설계하면 안좋은 방법일까요?
클래스 이름 때문이라면 변경하겠습니다.

테스트는 추가하겠습니다

2022-10-30 10:44 UTC, lowoon commented on src/main/java/racingcar/race/Result.java
> +        for (int trys = 0; trys < racingModel.getTryCount(); trys++) {
네 클래스 이름때문에 헷갈리는 것같아 게임 진행을 맡는 클래스라면 다른 이름을 가지는게 좋을것 같아요!

2022-10-30 10:47 UTC, lowoon approved these changes
안녕하세요 john님!
코멘트 잘 반영해주셨네요 👍 
이만 5단계는 머지하도록 하겠습니다!
자동차 경주 미션 수고하셨습니다

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-10-30 10:47 UTC, lowoon commented on src/main/java/racingcar/race/RacingModel.java
>  public class RacingModel {
result가 경주의 흐름을 제어하는 객체라면 racingModel의 객체의 역할과 책임이 무엇인지 모르겠어요.

2022-10-30 10:49 UTC, lowoon commented on src/main/java/racingcar/App.java
> +        RacingModel racingModel = new RacingModel(tryCount);
race의 결과로 모든 판에 대한 name, position을 가진 car들의 List를 반환하도록 하고 result 내부에서 이 list를 가지도록 하는 방식을 설명드렸습니다.

2022-10-30 10:49 UTC, merged