Step5: 자동차경주(리팩토링)
next-step/java-racingcar pull request #3996
Opened 2022-11-14 08:44 UTC by wisdom08

## 작업 목적
- 자동차 경주 리팩토링 

## 주요 변경점
- 원시타입의 값을 객체로 포장
- 도메인이 view 에 의존적인 상태였던 코드 개선
- 가독성을 위해 코드 개선 

## 고민
https://github.com/next-step/java-racingcar/pull/3988#discussion_r1020708631
- 위 코멘트에 대해서 개선하지를 못했습니다. position과 name값을 객체로 포장하고나서 Car 에게 메시지를 보내야하는건지 아니면 position과 name 각각 메시지를 보내야하는지 감이 좀 잡히지가 않습니다.

2022-11-14 16:22 UTC, csh0034 requested changes
이전단계에서 부터 구조가 잘 잡혀있어서
크게 변경사항은 없네요 🙂

지금 상태로 머지해도 되지만 고민해주신
흔적들이 많이 보여 조금만더 개선해보도록 
몇가지 코멘트 남겨드렸습니다.

확인해주시고 다시 요청 부탁드려요!

2022-11-14 16:22 UTC, csh0034 commented on src/main/java/race/domian/Car.java
> +        return position.isMaxPosition(maxPosition);
Position 객체에게 메시를 보내 처리를 해주셨네요 👍

2022-11-14 16:22 UTC, csh0034 commented on src/main/java/race/domian/Name.java
> +    private static final String CHARACTER_LIMIT_ERROR = "이름은 5자를 초과할 수 없습니다.";
상수는 인스턴스 변수보다 상단에 선언해주세요!

2022-11-14 16:22 UTC, csh0034 commented on src/main/java/race/domian/Position.java
> +    public Position move() {
this 를 반환해야하는 이유가 있을까요?

2022-11-15 00:15 UTC, wisdom08 commented on src/test/java/race/domian/NameTest.java
> +    void 이름_공백_불가() {
오... 1단계 때 써본 기억이 나는데 까먹고 있었네요. 감사합니다. 
`@ParameterizedTest` 에 대해서 찾아보다가 `@NullAndEmptySource`의 존재도 알게 되었는데요.

해당 테스트에서 null 체크도 같이 해주는게 적절할까요? 
아니면 null 인 경우의 테스트코드는 추가로 작성하는게 더 적절할까요?

2022-11-15 00:20 UTC, wisdom08 commented on src/test/java/race/domian/NameTest.java
> +    void 이름_공백_불가() {
음 null 인 경우에 아예 컴파일에러가 뜨네요. 아 그래서 `@EmptySource` 를 써야하는군요 ㅎㅎ

2022-11-15 00:57 UTC, csh0034 commented on src/test/java/race/domian/NameTest.java
> +    void 이름_공백_불가() {
Name 생성자에세 null 체크를 하지 않고 바로 length() 를 호출하기 때문에 NullPointerException 이 발생할것 같습니다.
이 경우는 런타임 예외이죠!

null 체크도 하도록 추가하고 NullAndEmptySource 를 사용하면 될것 같습니다 😄

2022-11-15 05:14 UTC, wisdom08 commented on src/test/java/race/domian/NameTest.java
> +    void 이름_공백_불가() {
아 런타임 예외!! 
단어 하나하나 좀 제대로 써야겠네요. 
null 체크하는 StringUtil 클래스를 만들고 테스트코드도 변경했습니다.

2022-11-15 05:34 UTC, wisdom08 commented on src/main/java/race/domian/Position.java
> +    public Position move() {
포비님 강의를 보고 해당 메서드를 추가했었는데 this를 반환하거나 반환하지 않거나 선택적인 문제라고 들었는데요. 
반환한다고 해서 성능상으로 큰 이슈가 있을까? 생각해봤는데 크지 않을 것 같아서 개선하지 않고 내버려두 것 같아요. 

승훈님 코멘트를 보고 반환해야할 이유가 있을까? 코드 확인도 다시하고, 생각을 해봤는데 찾지 못해서 우선 반환하지 않게 변경하고 테스트코드도 수정해볼게요! 
move 메서드에서 this 를 반환하지 않으면 CQRS 패턴을 적용했다고도 할 수 있을까요?

2022-11-16 10:37 UTC, csh0034 commented on src/main/java/race/domian/Position.java
> +    public Position move() {
제가 코멘트 드린 이유로는 성능과 관련된 내용이라기보단 프로덕션 코드에서 반환된 Postion 을 사용하고 있지 않아서였습니다.
만약 Position 이 불변이라면 this 가 아닌 변경된 Position 을 생성하여 리턴해야겠죠!

값을 리턴하지 않는다면 조회와 명령이 분리되었기 때문에 정확히는 CQS 가 맞습니다 😃 
CQRS 에는 CQS 보단 거시적인 개념이며 하단 글 보시면 도움될것 같습니다.

[CQRS 패턴에 대한 오해 풀기](https://wonit.tistory.com/628)

2022-11-16 11:07 UTC, csh0034 approved these changes
안녕하세요. 지혜님 😄 

코멘트 반영 잘 해주셨네요 💯 
마지막 단계 이만 머지하도록 하겠습니다.

이번 단계를 마지막으로 자동차 경주 미션도 마무리되었네요!
그동안 자동차 경주 미션 진행하시느라 수고 많으셨습니다 👍

2022-11-16 11:07 UTC, csh0034 commented on src/main/java/race/domian/Position.java
> +        return position - car.getPosition();
`return Integer.compare(position, car.getPosition());`

2022-11-16 11:08 UTC, merged