Step1 - 문자열 계산기, 자동차 경주
next-step/java-racingcar pull request #4019
Opened 2023-03-04 12:18 UTC by aaaicu

Readme.md 를 어떻게 작성해야하는지 잘모르겠어요 ㅠㅠ 
먼저 작성하고 구현해야 하는 것 같은데
반대로 먼저 구현하고 나중에 작성했습니다..!

2023-03-05 09:54 UTC, mskangg requested changes
안녕하세요! 재현님! 
이번 미션 리뷰를 맡은 강민수입니다. 🙇‍♂️
전체적으로 잘 작성해주셨네요!
Java 언어에 대해 익숙해보이셔서 문법보단 다른 가이드 위주로 드렸습니다!
코멘트 확인해보시고 반영 부탁드립니다!
그럼 화이팅!! 🔥

2023-03-05 09:54 UTC, mskangg commented on src/main/java/calculator/Calculator.java
> +        String[] split = removeBlankMathExpression.split("[(+|-|*|/)]");
java 에서 String.split()은 기본적으로 정규식 API를 사용하고 있습니다.
https://docs.oracle.com/javase/8/docs/api/

해당 코드를 살펴보면 매번 Pattern.compile()을 사용해 새로운 인스턴스를 생성하는것을 볼 수 있습니다.
이 부분은 큰 오버헤드가 아니지만, 인지하고 계시면 좋겠다 싶어 리뷰 남깁니다!

관련된 글 남겨드리겠습니다.
http://www.bar54.de/2014/01/java-string-split-vs-pattern-split/

다만, 구현소스를 보면 아시겠지만 매번 정규식패턴을 사용하진 않습니다.
https://stackoverflow.com/questions/29393086/pattern-split-slower-than-string-split

2023-03-05 09:54 UTC, mskangg commented on src/main/java/racing/Car.java
> +        if (name.length() > 5) {
매직넘버 (1, 2) 를 의미있는 상수화 시키는 것도 좋아보여요 :)
관련된 글 남겨드리겠습니다.

https://prodo-developer.tistory.com/118

2023-03-05 09:54 UTC, mskangg commented on src/main/java/racing/Car.java
> +    private int location;
보통 클래스 선언시 매개변수, 생성자, 메서드 순서로  작성합니다!
다른 클래스는 저렇게 작성하셨는데, 이것만 밑에있네용? 🤔

2023-03-05 09:54 UTC, mskangg commented on src/main/java/racing/Car.java
> +    }
랜덤함수가 내장되어있는 함수군요!
이 미션의 기능 요구 사항중  하나인 `전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.`를 만족하는 메서드로  보여집니다.
테스트코드를 살펴보니 `move()`에 대한 메서드는 `public`으로 열려있음에도 작성하지 않았더군요..!

이 메서드의 테스트코드를 작성해보아요!!
그리고 랜덤값이 1로 나왔을때 위치가 변하지 않음을 검증하는 테스트코드는 어떻게 작성할 수 있을까요? 🤔

2023-03-05 09:54 UTC, mskangg commented on src/main/java/racing/Car.java
> +public class Car implements Comparable<Car> {
👍

2023-03-05 09:54 UTC, mskangg commented on src/main/java/racing/Race.java
> +        return participationCars.stream().filter(c -> c.isEqualLocation(winner)).collect(Collectors.toList());
`자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.` 를 만족시키는 메서드군요.
테스트코드도 추가되면 좋을 것 같아요~~

2023-03-05 09:54 UTC, mskangg commented on src/test/java/calculator/StringCalculatorTest.java
> +    @ParameterizedTest(name = "{displayName} [{index}]: ''{argumentsWithNames}''")
`@ParameterizedTest`를 통해 테스트를 모아두셨군요 👍

2023-03-05 09:59 UTC, mskangg commented
> https://github.com/next-step/java-racingcar/pull/4019#issue-1609752609 

저같은 경우는 기능 요구사항을 README에 항상 적어놓고 시작합니다!

### 기능 요구 사항
- [ ] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- [ ]  각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.
- [ ]  자동차 이름은 쉼표(,)를 기준으로 구분한다.
- [ ]  전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [ ]  사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- [ ]  전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.
- [ ]  자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.
- [ ]  자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.

이렇게 되겠군요!

그런다음 저 요구사항 네이밍 그대로 테스트코드 `@DisaplayName` 으로 옮겨놓고 TDD 로 개발하곤 하는데요!
모든 기능을 이렇게 구현할 수 없으니, `@DisplayName`을 조금씩 쪼개거나 합쳐서 네이밍을 수정하면서 개발한 후 기능리스트를 체크하고 커밋하고 합니다!

개발은 요구사항 정리가 첫 시작이니, 이렇게 해보시는건 어떠실까용?? 😄

2023-03-05 14:19 UTC, aaaicu commented on README.md
> +* 경주 참가자들의 목록 중 우승자 확인
오! 체크리스트 문법을 몰랐었는데 사용해보면 좋을 것같아요 감사해요 😀

2023-03-05 14:39 UTC, aaaicu commented on src/main/java/calculator/Calculator.java
> +public class Calculator {
오! 클래스 안에 속성이 없다는 건 객체를 생성해서 상태를 관리할 필요가 없다는 말이 되는군요! 🤓
그리고 static메서드만으로 구성되어 있으니까
private 으로 생성자를 막아서 실수로라도 인스턴스를 생성하는걸 방지하기 위함이 맞을까요?

2023-03-05 14:51 UTC, aaaicu commented on src/main/java/racing/Car.java
> +public class Car implements Comparable<Car> {
👏🙏

2023-03-05 15:01 UTC, aaaicu commented on src/main/java/racing/Car.java
> +        if (name.length() > 5) {
네! 확인했습니다. 
질문이 있는데 주신 링크의 내용에서는 public static final ~ 이렇게 선언하는데 
꼭 static일 필요가 있는 건가요? 그냥 public final ~이렇게 선언해도 될 때는 언제인지 헷갈리더라고요! 😱

2023-03-05 15:05 UTC, aaaicu commented on src/main/java/racing/Car.java
> +    private int location;
옷 그렇네요😅

2023-03-05 15:07 UTC, aaaicu commented on src/test/java/calculator/StringCalculatorTest.java
> +    @ParameterizedTest(name = "{displayName} [{index}]: ''{argumentsWithNames}''")
👏👏 감사합니다 🤓

2023-03-05 15:27 UTC, aaaicu commented on src/main/java/calculator/Calculator.java
> +        String[] split = removeBlankMathExpression.split("[(+|-|*|/)]");
오 몰랐던 사실인데 이렇게 친절하게 리뷰해주셔서 감사해요!
이런점을 인지하고 있다면 불필요한 리소스를 줄이는데 도움이 될 것 같아요👍

`private static final Pattern operatorPattern = Pattern.compile("[(+|-|*|/)]");`

로 상수로 한번만 패턴객체를 만들면 되는 걸까요!

2023-03-05 16:22 UTC, aaaicu commented on src/main/java/racing/Car.java
> +    }
사실 해당부분에 대해서 잘 모르겠어서 찾아보았어요ㅜㅜ
https://www.slipp.net/questions/559 를 참고했습니다!

제가 작성한 move 메서드에서 직접적으로 Random 클래스를 의존하고 있었고
그러다보니 move 메서드의 고유한 역할에 대한 단위테스트가 불가능했던 것 같아요
그말은 제가 구현한 메서드가 한가지 이상의 기능들로 결합되어있었다는 생각을 했어요. 

이렇게 이해하는게 맞는 방향성인지 리뷰 부탁드려요!

2023-03-05 16:25 UTC, aaaicu commented on src/main/java/racing/Race.java
> +        return participationCars.stream().filter(c -> c.isEqualLocation(winner)).collect(Collectors.toList());
이 부분은 
`    @Test
    @DisplayName("위치가 가장 높은 차가 우승자가 된다.")
    void getRacingWinners() {
        Car carA = new Car("carA", 1);
        Car carB = new Car("carB", 2);
        Car carC = new Car("carC", 5);
        Car carD = new Car("carD", 5);
        List<Car> racingCars = List.of(carA, carB, carC, carD);

        Race race = new Race(racingCars, 0, new Random());
        List<Car> racingWinners = race.getRacingWinners();

        Assertions.assertThat(racingWinners).containsExactly(carC, carD);
    }`

이렇게 구현을 해놓았었는데 
다른방향으로 테스트 코드를 작성했어야 하는 걸까요? 🥲

2023-03-06 04:54 UTC, mskangg commented on src/main/java/racing/Car.java
> +        if (name.length() > 5) {
클래스 내부 변수를 상수로 사용할땐, 변하지 않게 final 값을 주었으니 매번 할당하지않고 static 하게 사용하기 위해 static final을 사용하곤 합니다

2023-03-06 05:10 UTC, merged