Step2 문자열 덧셈 계산기 입니다.
next-step/java-racingcar pull request #4150
Opened 2023-04-04 13:28 UTC by JHyunJung

2023-04-05 12:51 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    public static int splitAndSum(String input) throws Exception {
예외를 던지는 부분이 존재하지 않는데 throws Exception이 필요할까요?

2023-04-05 12:52 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        String regex = "//(.)\n(.*)";
이런 부분은 상수로 관리하는게 어떨까요?
https://crazykim2.tistory.com/741
해당 글을 한번 참고해보세요!

2023-04-05 12:52 UTC, ksy90101 commented on src/main/java/Calculator.java
> +                throw new RuntimeException();
RuntimeException보단 의밍있는 예외를 사용해보면 어떨까요?
직접 만들어 봐도 좋구요!

2023-04-05 12:53 UTC, ksy90101 commented on src/main/java/Calculator.java
> +            int num = Integer.parseInt(number);
혹시라도 number가 String이라 잘못된 값이 들어올수도 있지 않을까요?

2023-04-05 12:54 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        splitedNumbers = input.split(",|:");
여기 ",|:"이것도 상수화를 하면 어떨까요?

2023-04-05 12:55 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        for (String number : numbers) {
여기를 한번 Stream을 연습겸 사용해보면 어떨까요?

2023-04-05 12:55 UTC, ksy90101 requested changes
안녕하세요 :) 빠른 2단계 미션 고생하셨습니다~
간단한 피드백을 남겼는데 한번 확인해주세요!!

테스트 코드는 잘 작성해주셨네요 👍

2023-04-06 09:43 UTC, JHyunJung commented
> 안녕하세요 :) 빠른 2단계 미션 고생하셨습니다~ 간단한 피드백을 남겼는데 한번 확인해주세요!!
> 
> 테스트 코드는 잘 작성해주셨네요 👍

코드 리뷰 반영하여 업데이트 하였습니다.

2023-04-08 00:51 UTC, ksy90101 commented on src/main/java/Calculator.java
> +                    }
이런 부분들을 메서드로 뺸다면 더 보기 깔끔할거 같아요.

2023-04-08 00:51 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    private static int sumNumbers(String[] numbers) {
```suggestion
    }
    
    private static int sumNumbers(String[] numbers) {
```

개행하나도 클린코드를 지킬수 있는 방안입니다 :)

2023-04-08 00:52 UTC, ksy90101 approved these changes
안녕하세요 :) 2단계도 고생 하셨습니다.
간단한 피드백을 남기긴 했지만 3단계에서 충분히 수정가능하니, 머지하고 3단계때 뵙겠습니다..!!

2023-04-08 00:52 UTC, merged