2단계 문자열덧셈계산기
next-step/java-racingcar pull request #4209
Opened 2023-04-05 14:34 UTC by So-JunHyeok

2단계 문자열 덧셈 계산기 완료했습니다! 리뷰 요청드립니다~

2023-04-06 13:43 UTC, sah3122 requested changes
문자열 덧셈 계산기 구현 잘해주셨네요 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드리며 질문이 있으시다면 편하게 DM 주세요 !

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public int checkNull_Empty(String value)throws Exception{
java의 네이밍 컨벤션은 일반적으로 CamelCase를 사용합니다 😄 
아래 문서를 보고 코드 스타일 가이드를 학습해보세요 ! 
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        }
```suggestion
        if (result == 0) {
            return result;
        } else {
            values = checkSeparator(value);
            int calcul = 0;
            for (String val : values) {
                calcul += checkNegative(Integer.valueOf(val));
            }
            result = calcul;
        }
```
들여쓰기와 공백 문자를 적절히 사용하면 가독성을 향상 시킬수 있어요. 
Intellj를 사용하고 계시다면 아래 가이드를 통해 코드 포맷을 맞춰보세요 😄 
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        return result;
이번 미션을 진행하면서 if - else 구문을 사용하지 않고 구현해보는것을 경험해보세요 😄 
위 코드는 아래와 같이 변경할수 있을것 같아요 🙏 
```suggestion
        if(value == null || value.isEmpty()){
            result = 0;
        }
        return result;
```

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        if(m.find()){
공백 라인을 적절한 위치에 사용함에 따라 문맥을 구분 시켜 가독성을 높일수 있어요. 
```suggestion
        String[] number;
        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(value);

        if(m.find()){
```

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(value);
Pattern 과 같이 생성 비용이 큰 객체는 재사용할수 있는 방법을 고민해보세요. 
https://icarus8050.tistory.com/64

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +            if(0 > value){
일반적으로 코드는 왼쪽에서 오른쪽으로 읽습니다. 
사소하지만 비교하고자 하는 변수를 왼쪽에 선언하는것이 가독성이 더 좋다고 생각해요 !

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public int splitAndSum(String value)throws Exception{
메서드에 Exception을 전파한다고 선언해주셨는데 이유가 있을까요 ?

2023-04-06 13:43 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +public class StringAddCalculator {
문자열 계산기 구현 잘해주셨습니다 👍 
이번 과정을 통해 클린코드과 객체지향 프로그래밍을 학습하게 되실거에요. 
문자열을 분리하는 객체와 계산을 담당하는 객체를 생성하여 책임을 분산 시켜볼수 있을것 같은데 도전해보세요 😄

2023-04-06 13:43 UTC, sah3122 commented on src/test/java/study/StringAddCalculatorTest.java
> +    public void splitAndSum_null_또는_빈문자() throws Exception {
Junit5 에는 DisplayName을 지원합니다. 
테스트의 의도는 @DisplayName을 통해 나타내보세요 !

2023-04-06 16:27 UTC, So-JunHyeok commented on src/main/java/study/StringAddCalculator.java
> +    public int splitAndSum(String value)throws Exception{
호출한 메서드에  예외를 전달하려면 throws Exception을 선언해줘야 한다고 해서 최종적으로 StringAddCalculatorTest에 Exception을 전달하려고 선언했었습니다!

2023-04-10 13:46 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
몇가지 고민거리를 추가로 남겨두었는데 다음 미션을 진행하며 반영 부탁드려요 😄

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    Pattern pattern = Pattern.compile("//(.)\n(.*)");
자바에서는 상수를 표현할때 static final 접근 제어자를 선언합니다 😄 
```suggestion
    private static final Pattern pattern = Pattern.compile("//(.)\n(.*)");
```

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        number = value.split(",|:");
매직넘버는 의미있는 상수로 선언하면 가독성을 높일수 있습니다.
기본 분자열 구분자라는 상수로 나타내보는것이 어떨까요 ㅎㅎ 

https://www.slipp.net/questions/356

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public String[] checkSeparator(String value) {
check로 시작하는 메소드 네이밍은 내부에서 어떤 값을 검사하는것을 기대하게 됩니다. 
문자열을 구분자로 분리하는 역할을 나타낼수 있는 네이밍을 고민해보는건 어떨까요 ?

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public int checkNegative(int value) {
객체지향 프로그래밍을 연습활겸 양수를 보장하는 클래스를 선언하여 책임을 분리시켜 보세요 😄

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public int[] stringSeparation(String[] values) {
마찬가지로 메소드 네이밍과 메소드에서 하는 역할이 일치하지 않네요. 
조금더 의미있는 네이밍을 고민해보세요 👍

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +public class StringAddCalculator {
전체적으로 메소드의 접근 제어자를 public 으로 선언해주셨는데 외부로 노출하지 않아도 된다면 private으로 선언하여 캡슐화를 하는것이 어떨까요 ?

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +    public int checkNull_Empty(String value) {
메소드 네이밍은 lowerCamelCase 표기법을 따라주세요 ! 
https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

2023-04-10 13:46 UTC, sah3122 commented on src/main/java/study/StringAddCalculator.java
> +        return -1;
0과 -1같은 정수에 의미를 부여하기 보다는 일반적인 boolean 타입을 사용하는것을 권장 드립니다. 
더 많은 상황을 나타내야 한다면 enum class 를 사용하는 방법을 권장드려요 👍 
특정 값들이 의미를 가지는 순간 다른 개발자들이 의미를 파악하기 어려울뿐만 아니라 코드를 읽기가 어려워집니다 😄

2023-04-10 13:46 UTC, merged