#자동차경주 step2 미션 진행 완료입니다.
next-step/java-racingcar pull request #4249
Opened 2023-04-06 09:44 UTC by juno-junho

clean code 가이드를 따라, 메서드 분리와 각 메서드 및 변수 네이밍에 대해 고민했습니다.
 - try catch 블록을 별도의 함수로 뽑아냈습니다.
 - builder 메서드 경우 네이밍시 명사를 사용했습니다.
 
미션을 진행하면서 고민사항은 다음과 같습니다.
1. 함수를 최대한 한 가지 일만 하도록 쪼개려 노력했는데, 어느 수준까지 쪼개야 하는지가 애매합니다.
 - 예를들어, 배열을 돌면서 각 요소의 합을 구할때, looping 과정과 sum 과정 까지 따로 분리해야하는지, 아니면 합쳐 이 정도면 하나의 일을 하고 있다고 할 수 있는지 궁금합니다.
 2.  sumUsingDelimiter 메서드 안에서 convertedNum와 checkIfIsNegative를 합쳐서 stream으로 간결하게 만들수도 있는데, stream을 사용하기 위해서 별도의 함수를 생성하는 것은 어떻게 생각하는지 궁금합니다.

앞으로 리뷰 잘 부탁드리겠습니다! 😀

2023-04-08 00:52 UTC, ksy90101 commented on src/main/java/calculator/Positive.java
> +    public int getNumber() {
```suggestion
    }

    public int getNumber() {
```

개행도 의미있게 작성해주세요.

2023-04-08 00:53 UTC, ksy90101 commented on src/main/java/calculator/Positive.java
> +        this.number = Integer.parseInt(number);
String이 들어오니, 숫자가 아닌 값이 들어오면 터지지 않을까요?
validate를 해보는걸 추천합니다.

2023-04-08 00:53 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        }
steam의 sum을 이용해보면 어떨까요?

2023-04-08 00:53 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +    private static int[] toInts(String[] values) {
```suggestion
    }
    
    private static int[] toInts(String[] values) {
```

개행도 의미를 가집니다.

2023-04-08 00:55 UTC, ksy90101 commented on src/main/java/study/StringAddCalculator.java
> +        REGEX.insert(3, customDelimiter);
3이라는 단어도 상수화를 시키면 어떨까요?

2023-04-08 00:57 UTC, ksy90101 commented on src/main/java/study/StringAddCalculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);
https://velog.io/@banjjoknim/%EC%95%84%EC%9D%B4%ED%85%9C-6.-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%ED%94%BC%ED%95%98%EB%9D%BC

Matcher는 비싼객체이기 떄문에 상수화를 시키는게 좋습니다.

2023-04-08 00:58 UTC, ksy90101 requested changes
안녕하세요 :)
간단한 피드백을 남겼으니 확인 부탁드립니다.
아울러 같은 행동을 하는게 2개 클래스가 있던데 강의에서 들었던거 vs 본인이 직접 생각해서 작성해보신거 두개가 있는게 맞을까요~?

2023-04-08 00:59 UTC, ksy90101 commented
1. 함수를 최대한 한 가지 일만 하도록 쪼개려 노력했는데, 어느 수준까지 쪼개야 하는지가 애매합니다.
- 기준 자체가 한가지 일입니다. 메서드에 로직이 음수 / 숫자 검증 이렇다면 음수와 숫자 검증을 두개로 분리하고 그걸 사용하는 메서드가 있는 그런 방안으로 생각하시면 됩니다. 너무 쪼개려고 하지 말고, 최대한 쪼개고 본인이 생각했을때 더이상 쪼갤게 없다면 그냥 넘어가셔도 충분합니다.
2. sumUsingDelimiter 메서드 안에서 convertedNum와 checkIfIsNegative를 합쳐서 stream으로 간결하게 만들수도 있는데, stream을 사용하기 위해서 별도의 함수를 생성하는 것은 어떻게 생각하는지 궁금합니다.
steam은 학습 목적으로 사용해 보시면 좋습니다 :)

2023-04-08 01:04 UTC, juno-junho commented
> 안녕하세요 :) 간단한 피드백을 남겼으니 확인 부탁드립니다. 아울러 같은 행동을 하는게 2개 클래스가 있던데 강의에서 들었던거 vs 본인이 직접 생각해서 작성해보신거 두개가 있는게 맞을까요~?

네 study안에 있는 코드만 확인하시면 될것 같습니다..! calculator 클래스 안에 있는 파일들은 강의를 들으면서 작성한 것입니다!

2023-04-08 01:10 UTC, juno-junho commented on src/main/java/study/StringAddCalculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);
이펙티브 자바 학습을 아직 하지 않았는데, 
이펙티브자바 아이템 6 파트를 읽어보고 수정하겠습니다!

2023-04-08 01:10 UTC, juno-junho commented on src/main/java/study/StringAddCalculator.java
> +        REGEX.insert(3, customDelimiter);
3과 0같은 매직넘버는 상수로 모두 분리시키겠습니다!

2023-04-08 01:15 UTC, juno-junho commented on src/main/java/calculator/StringCalculator.java
> +        }
study안의 내용은 포비님 강의를 들으며 작성한 내용입니다!
포비님은 로또 미션까지는 oop에 대한 연습을 위해서 stream 사용을 지양하라고 하시던데 어떻게 생각하시나요?

2023-04-08 06:21 UTC, juno-junho commented on src/main/java/study/StringAddCalculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);
이펙티브 자바  ITEM 6를 읽고 적용시켰습니다.
Pattern과 Matcher 모두 내부 구조를 보니 new 키워드로 새로운 Pattern과 Matcher를 생성해서 반환하는 팩토리 메서드더라고요. (compile(), matcher()) 
따라서 Pattern은 상수화 시켰지만, Matcher는 어쩔수 없이 매번 객체를 생성해줘야 하는 것을 확인할 수 있었습니다.
하지만 matcher를 static 변수로 설정해 놓으면, textUpdate() 메서드의 파라미터를 제거할 수 있는 것을 확인하여 static 변수로 변경했습니다.
이것에 대해서는 어떻게 하는 것이 좋을까요? 현재 제가 리펙토링한 방식이 올바른 방법일까요?
(추가적으로 이펙티브 자바를 꼭 한번 다 읽어 봐야겠다는 생각이 들었습니다! :) )

2023-04-08 06:27 UTC, juno-junho commented on src/main/java/study/StringAddCalculator.java
> +    public static Matcher matcher;
Matcher는 상수로 뺄수가 없었습니다. (매번 다른 text마다 해당하는 matcher 객체를 생성해야 하므로)
하지만 이렇게 static 변수로 선언하여 textUpdate()의 파라미터의 개수를 1개에서 0개로 줄일 수 있었습니다. 
이것은 괜찮은 방법일까요?

2023-04-09 06:48 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        }
학습을 어떤걸 더 할것인가.를 선택하면 좋을거 같습니다.
Stream을 더 많이 사용하게 되기 때문에 전 권장했던것이고 oop를 좀더 하고 싶다면 for문을 사용하셔도 무관하긴 합니다 :)

2023-04-09 06:48 UTC, ksy90101 commented on src/main/java/study/StringAddCalculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);
네네 이정도만 충분합니다 :)

2023-04-09 06:49 UTC, ksy90101 commented on src/main/java/study/StringAddCalculator.java
> +    public static Matcher matcher;
matcher까지 상수로 뺼 필요는 없습니다.

2023-04-09 06:50 UTC, ksy90101 approved these changes
2단계 고생 많으셨습니다.
질문에 대한 답변은 다 남겨두었습니다.
3단계도 파이팅입니다~

2023-04-09 06:50 UTC, merged