Step3_레이싱 게임
next-step/java-racingcar pull request #4268
Opened 2023-04-06 15:58 UTC by goodcodings

안녕하세요! 리뷰어님 
step 3 코드도 잘 부탁드립니다

------------------------------

테스트 코드는 아직 작성하지 않았는데.. 하나하나씩 작성하면서 코드 리펙토링 진행하겠습니다.ㅠㅠㅠ

2023-04-07 02:07 UTC, catsbi requested changes
안녕하세요 병성님. 3단계 미션 정말 빠르게 구현해주셨네요. 
짧은시간안에 가독성좋은 코드를 잘 만드셨습니다 👍 

다만 몇 가지 피드백이 필요해 코멘트 남겨드렸고, 무엇보다 테스트케이스가 존재하지 않네요 ㅠㅠ 이 부분 확인해서 TC작성해서 다시 리뷰요청 해주세요.

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/RacingGame.java
> +        ArrayList<RacingCar> racingCarList = new ArrayList<>();
참조타입은 최대한 추상화된 타입(Ex: List, Set, Map)을 사용해주세요. 코드의 유연성을 늘려줄 수 있습니다.

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/RacingGame.java
> +            racingCarList.add(RacingCar.of(moveStrategy, new Position()));
정적 메서드 팩토리 패턴 👍

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/domain/RacingCar.java
> +    }
전략패턴을 잘 사용하고 계시네요 👍

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/strategy/MoveStrategy.java
> +@FunctionalInterface
💯

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/strategy/RandomMoveStrategy.java
> +    private final static Random RANDOM = new Random();
동시성문제나 성능문제로 Random보다는 ThreadLocalRandom을 권장드립니다 👍

2023-04-07 02:07 UTC, catsbi commented on src/main/java/step3/view/InputView.java
> +    private int numberOfReps;
상태값을 가지지 않는 계층으로 만들어도 될 것 같아요 👍

2023-04-07 02:08 UTC, catsbi commented
테스트에 대해 넥스트스텝 페이지에 있는 내용과 더해서 추가적으로 해당 포스팅을 참고해주시면 좋을 것 같습니다 [[link](https://catsbi.oopy.io/b13326d7-7b96-4a33-a974-3024c64eff5f)]

2023-04-07 03:51 UTC, goodcodings commented on src/main/java/step3/view/InputView.java
> +    private int numberOfReps;
어제 해당 객체에 대해서 문의 드리고자하는 코멘트를 남겨놨었는데.. 
제가 깜박하고 코멘트 커밋을 못했네요 ㅠㅠ

아래는  제가 여쭤보고자하는 코멘트입니당!
====================================
사용자에게 안내하는 메세지의 책임을 가져하는 객체
사용자로 부터 입력받은 값에 대한 책임을 가져야하는 객체 이렇게 2가지 객체로 나누어야할거같은데...

고민이 많이 되네요... 한가지의 객체에서 복합적인 책임을 가지고 있는거같아서..
멘토님의 의견이 궁금합니다!

2023-04-07 04:02 UTC, goodcodings commented on src/main/java/step3/RacingGame.java
> +    private boolean flag;
멤버변수를 사용하고 있어서 동시성 문제가 발생할수 있는 가능성이 존재하네요 ㅠㅠ
멤버변수에 flag를 넣은 이유는 프로그램을 강제로 종료시킬 상황이 발생할수도 있을거같아서 넣어놨는데... 

지금 생각해보니 비정상적인 경우에 프로그램을 강제로 종료시켜야할 상황이 발생할수도 있을거같아
이런경우는 예외를 발생시켜 프로그램을 종료 시켜야할거같은데 리뷰어님은 이런경우에 어떤식으로 풀어나가는지 궁금합니다!

2023-04-07 04:11 UTC, goodcodings commented on src/main/java/step3/RacingCarApplication.java
> +        RacingGame racingGame = new RacingGame(new InputView(), new PrintView(), new RandomMoveStrategy());
싱글턴 패턴을 사용하게 되면 모듈간 의존성 높아질거같아서 외부에서 객체를 주입 받을수있게 코드를 작성해봤는데 
혹시 리뷰어님은 어떻게 생각하시는지 궁금합니다!

2023-04-07 04:11 UTC, goodcodings commented on src/main/java/step3/RacingGame.java
> +        ArrayList<RacingCar> racingCarList = new ArrayList<>();
감사합니다, 요걸 놓쳤네요 ㅠㅠㅠㅠ

2023-04-07 06:31 UTC, catsbi commented on src/main/java/step3/RacingCarApplication.java
> +        RacingGame racingGame = new RacingGame(new InputView(), new PrintView(), new RandomMoveStrategy());
싱글턴 패턴과 모듈간 의존성은 전혀 상관이 없어 보입니다. 
```suggestion
        RacingGame racingGame = new RacingGame(InputView.instance(), PrintView.instance(), RandomMoveStrategy.instance());
```
이 코드와 위 코드의 의존성 차이는 없습니다. 둘 다 RacingGame이 세 구현체에 의존하고 있다는 공통점이 있죠 ㅎㅎ 
여기서 의존성을 줄이고자 한다면, 이보다는 추상화를 통해 제어의 역전을 고려하는게 맞겠죠 ㅎㅎ

2023-04-07 06:34 UTC, catsbi commented on src/main/java/step3/RacingGame.java
> +    private boolean flag;
예외를 던지는 상황에선 적절한 로깅과 이후 대책은 정책(기획)에 따라 결정되는게 맞다고 봅니다 👍 
해당 미션에서는 unchecked exception이 발생하면  어떻게 동작하고 계속해서 동작하라 라는 기획이 없으므로, 예외를 던지고 종료하면 될 문제로 보이네요!

2023-04-07 06:41 UTC, catsbi commented on src/main/java/step3/view/InputView.java
> +    private int numberOfReps;
SRP 원칙때문에 책임에 대해서 고민을 많이하고, 이 내용은 정답이라기보다는 아직도 여러 의견들이 나오고 있는데요. 
저는 클린 아키텍처에서 얘기하는 바를 공감하고 추구하는 편입니다. 

클린 아키텍처에서는 SRP를 소개하며 한 객체가 책임져야 하는건 특정 기능이 아니라 하나의 Actor에 대해 책임진다고 표현을 합니다. 좀 더 풀면 하나의 모듈은 하나의 사용자 또는 이해 관계자에 대해서만 책임져야한다고 말합니다. 이 집단을 actor라 표현하고 있구요. 

그런의미에서 사용자와 통신하며 UI를 담당하는 View Layer는 입력받은 값이 유효한지 책임질 필요가 있을까? 싶어요. 있다 한들 입력한 값이 Null이 아닌지 그 이상을 체크할 필요가 있는가 싶네요. 그냥 값을 받아 전달해준다. 정도로 고민을 멈춰도 충분하지 않을까 싶어요. 전달받은 값이 정상적인지, 혹은 비즈니스 유효성에 충족하는지는 좀 더 적절한 도메인 계층에서 검사하는게 맞지 않을까 싶네요. 

더 깊게들어가 검증기(Validator)까지 갈수도 있지만, 굳이 벌써 과도하게 검증기 계층까지 가기보단  도메인 계층을 잘 활용해보면 어떨까싶어요. 

객체로만 보면 책임에 대해 혼동될 수 있지만 좀 더 범위를 늘려서 계층적으로 본다면 View Layer이고 이 View Layer가 해야 할 책임만 지면 될 것 같습니다 👍

2023-04-09 14:15 UTC, catsbi approved these changes
병성님 3단계 피드백 빠르게 잘 반영해주셨습니다. 
리뷰를 빨리 해드렸어야 했는데 늦어서 죄송합니다 🙇‍♂️

몇 가지 피드백을 남겨드렸으니 확인해보시고 다음 미션에서 같이 반영해보는걸로 하죠. 
특히 부족한 테스트 케이스(TC)를 좀 더 풍부하게 구성해보시길 바랍니다.

2023-04-09 14:15 UTC, catsbi commented on src/main/java/step3/RacingGame.java
>      public void stop() {
예외만을 던지기 위한 메서드는 굳이 필요가 없습니다. 
경주를 멈추기 위해서라면 다른 별도의 기준을 잡고 해도 될 것 같습니다. 

UI를 이용한다면 `while(requestContinue()) {... }` 이런식으로 할 수 있을 것이고, 변수를 사용한다면 해당 로직 내부에서 선언한 지역변수등을 이용할 수 있겠죠(Ex: RepeatStatus status)

2023-04-09 14:15 UTC, catsbi commented on src/main/java/step3/strategy/draw/DashDrawStrategy.java
> +public class DashDrawStrategy implements DrawStrategy {
전략 패턴을 훌륭하게 사용하고 계시네요 👍

2023-04-09 14:15 UTC, catsbi commented on src/main/java/step3/strategy/draw/DashDrawStrategy.java
> +    }
사실 이 방법도 완전히 안전하지 않습니다 ㅎ 왜일까요.

2023-04-09 14:15 UTC, catsbi commented on src/test/java/step3/RacingGameTest.java
> +        RacingGame racingGame = RacingGame.of(InputView.getInstance(), PrintView.of(DashDrawStrategy.getInstance()), RandomMoveStrategy.getInstance());
테스트 대상이 되는 RacingGame이나 정보들은 테스트케이스에서 픽스처가 달라질 구실이 안보이는데, BeforeSetUp애노테이션을 활용해 분리해도 될 것 같네요

2023-04-09 14:15 UTC, catsbi commented on src/test/java/step3/RacingGameTest.java
> +    public void 레이싱게임_테스트() {
racingGame의 play메서드의 반환값으로 유추되는게 사이즈밖에 없나요? 이 메서드가 왜 존재하는지에 대해 테스트를 해야 하지 않을까요?

2023-04-09 14:15 UTC, catsbi commented on src/test/java/step3/strategy/draw/DashDrawStrategyTest.java
> +        assertThat(drawStrategy.draw(input)).isEqualTo(resultString);
음수, null,blank등을 넣었을때에 대한 테스트 케이슨 없을까요?

2023-04-09 14:15 UTC, catsbi commented on src/test/java/step3/view/InputViewTest.java
> +class InputViewTest {
UI Layer는 보통 테스트 범위에서 벗어납니다. 
프로젝트 계층에는 내가 제어할 수 있는 것과 제어할 수 없는 것이 있는데, 여기서 제어할 수 있는 범위를 늘리고 제어할 수 있는 것들만 테스트하려 합니다. 제어 할 수 없는 것을 테스트하는건 큰 의미가 없기 때문이죠.

2023-04-09 14:15 UTC, merged