Step2 문자열 덧셈 계산기
next-step/java-racingcar pull request #4279
Opened 2023-04-07 05:17 UTC by gurioh

2023-04-08 07:48 UTC, dave915 requested changes
안녕하세요! 미션 구현 잘 해주셨네요 :) 
몇가지 피드백 남겼습니다. 확인 부탁드릴게요!

2023-04-08 07:48 UTC, dave915 commented on src/main/java/calculator/StringCalculator.java
> +        Pattern pattern = Pattern.compile(PATTERN);
Pattern 클래스는 컴파일 후 재사용 하는것을 추천드릴게요 :)

https://medium.com/webeveloper/%EC%9E%90%EB%B0%94-%EC%98%AC%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%A0%95%EA%B7%9C%EC%8B%9D-%ED%8C%A8%ED%84%B4-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-c2479c33ab8b

2023-04-08 07:48 UTC, dave915 commented on src/main/java/calculator/StringCalculator.java
> +           if(matcher.group(0) ==  null)
⌥⌘L 또는 Ctrl+Alt+L 을 사용하여 Reformat을 한번 해주면 좋을 것 같아요 :) 
```suggestion
        if (customDelimiter.isBlank()) {
```

2023-04-08 07:48 UTC, dave915 commented on src/test/java/calculator/StringCalculatorTest.java
> +        }).isInstanceOf(RuntimeException.class);
같은 RuntimeException 이더라도 메세지가 다를 수 있기때문에 메세지도 같이 확인 해 주는편이 좋다고 생각합니다 :) 
```suggestion
        }).isInstanceOf(RuntimeException.class)
        .hasMessage("음수는 입력이 불가합니다. 양수를 입력하세요.");
```

2023-04-08 07:48 UTC, dave915 commented on src/main/java/calculator/StringCalculator.java
> +        }
😀
```suggestion
        if (text == null || text.isBlank()) {
            return ZERO;
        }
```

2023-04-08 07:48 UTC, dave915 commented on src/main/java/calculator/StringCalculator.java
> +        return text.substring( text.indexOf("\\n")+2).split(customDelimiter);
`"\\n"` 도 변수로 분리해서 의미를 부여해 주세요 :)

2023-04-10 00:52 UTC, gurioh commented on src/main/java/calculator/StringCalculator.java
> +        Pattern pattern = Pattern.compile(PATTERN);
넵 재사용하도록 수정하였습니다.

2023-04-10 00:53 UTC, gurioh commented
@dave915 안녕하세요~!!  피드백적용하였습니다. 확인부탁드려도 될까요??

2023-04-10 16:09 UTC, merged