2단계-문자열 덧셈 계산기
next-step/java-racingcar pull request #4289
Opened 2023-04-07 14:39 UTC by biblekimm

2단계-문자열 덧셈 계산기 PR 드립니다.

2023-04-08 01:00 UTC, ksy90101 commented on src/main/java/util/Value.java
> +        }
이런 경우 메서드로 분리해보면 어떨까요?

2023-04-08 01:00 UTC, ksy90101 commented on src/main/java/util/Value.java
> +public class Value {
Value보단 값을 나타내는 단어를 쓰는게 좋을꺼 같아요.

Number와 같은 단어가 있을듯 하빈다.

2023-04-08 01:00 UTC, ksy90101 commented on src/main/java/util/Value.java
> +    int value;
값 객체는 불변인게 좋을수 있어요 :)

2023-04-08 01:00 UTC, ksy90101 commented on src/test/java/util/SetTest.java
> +
```suggestion

```

2023-04-08 01:01 UTC, ksy90101 commented on src/main/java/util/StringAddCalculator.java
> +        }
학습 목적으로 stream을 한번 사용해보면 어떨까요?

2023-04-08 01:02 UTC, ksy90101 commented on src/main/java/util/StringAddCalculator.java
> +            values[i] = Integer.parseInt(inputValues[i]);
Integer.parseInt를 사용했을떄 숫자가 아닌 값이 들어오면 터질거 같아요. validate를 해보면 어덜까요?

2023-04-08 01:02 UTC, ksy90101 commented on src/main/java/util/StringAddCalculator.java
> +        Matcher m = Pattern.compile(DELIMITER_REGEX_CUSTOM).matcher(input);
MAtcher는 비싼 객체이기 떄문에 상수화 시키는게 좋습니다.

https://velog.io/@banjjoknim/%EC%95%84%EC%9D%B4%ED%85%9C-6.-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%ED%94%BC%ED%95%98%EB%9D%BC

2023-04-08 01:02 UTC, ksy90101 commented on src/main/java/util/StringAddCalculator.java
> +        if (StringUtils.isEmpty(input)) {
이정돈 직접 만들어 보면 어떨까요?
굳이 StringUtils를 사용하기 보단은요 :)
학습의 목적으로 최소한의 라이브러리를 써보시는걸 추천해요!

2023-04-08 01:03 UTC, ksy90101 requested changes
안녕하세요 :)
2단계 고생 하셨습니다!!
간단한 피드백을 남겼으니 확인 한번 부탁드립니다~

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/Value.java
> +        }
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/Value.java
> +public class Value {
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/Value.java
> +    int value;
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/StringAddCalculator.java
> +        }
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/StringAddCalculator.java
> +            values[i] = Integer.parseInt(inputValues[i]);
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/StringAddCalculator.java
> +        Matcher m = Pattern.compile(DELIMITER_REGEX_CUSTOM).matcher(input);
반영 했습니다. 감사합니다.

2023-04-09 03:27 UTC, biblekimm commented on src/main/java/util/StringAddCalculator.java
> +        if (StringUtils.isEmpty(input)) {
반영 했습니다. 감사합니다.

2023-04-09 06:44 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.apache.commons:commons-lang3:3.12.0'
사용하지 않다면, 의존성 제거를 해보면 좋을거 같아요.

2023-04-09 06:45 UTC, ksy90101 commented on src/main/java/util/Constants.java
> +public class Constants {
이렇게 상수를 모아부는것도 좋지만, 연관되어 있는 애들끼리 하나의 클래스에 묶어두는게 더 좋을수도 있습니다.

이렇게 class로 빼는 경우는 공통적으로 쓰는 상수라는 개념에서 이렇게 많이 쓰는거 같아요.

이건 그냥 의견이기 때문에 참고부탁드립니다.

2023-04-09 06:45 UTC, ksy90101 approved these changes
안녕하세요 :) 2단계도 고생 많으셨어요~
간단한 피드백을 남겼는데, 다음 단계에서 적용해주시면 될거 같아요~
3단계도 파이팅입니다!!

2023-04-09 06:45 UTC, merged