Step 3 구현 완료 리뷰 요청합니다.
next-step/java-racingcar pull request #4305
Opened 2023-04-08 12:52 UTC by dkajffkeh

2023-04-08 15:09 UTC, testrace requested changes
안녕하세요 호연님 😄 
3단계 깔끔하게 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드립니다.
궁금한 점이나 의견 있으시면 편하게 DM 주세요!

2023-04-08 15:09 UTC, testrace commented on src/main/java/com/nextstep/racingcargame/core/Car.java
> +    }
요구사항과 로직이 다른 것 같아요 😢 
> 기능 요구사항
> 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 `4이상`일 경우이다.

2023-04-08 15:09 UTC, testrace commented on src/test/java/com/nextstep/racingcargame/core/CarTest.java
> +    }
랜덤 값의 범위(0-9)가 달라지면 테스트도 많이 변경되어야 할 것 같은데요
움직임의 기준 값을 경계로 테스트하면 어떨까요?
두 테스트 코드가 거의 비슷하니 `@CsvSource`를 활용해서 중복을 제거하는 방향도 고민해 보시면 좋을 것 같아요 😃

2023-04-08 15:09 UTC, testrace commented on src/test/java/com/nextstep/racingcargame/core/CarsTest.java
> +    }
new 키워드를 활용해 직접 생성하는 경우도 테스트되면 좋을 것 같아요
```java
    @Test
    @DisplayName("사용자 입력한 값에 따라 자동차 객체가 생성된다")
    void create() {
        final Cars cars = new Cars(-1);
        ...
        final Cars cars = new Cars(0);
        ...
        final Cars cars = new Cars(3);
        ...
    }
```

2023-04-08 15:39 UTC, dkajffkeh commented on src/main/java/com/nextstep/racingcargame/core/Car.java
> +    }
자동차 경주를 관장하고 있는곳 racingcargame/core 패키지 하위 이외의 곳에서 Car 라는 객체를 생성하는것을 막고자 하는 의미에서
작성해보았습니다~

2023-04-08 16:23 UTC, dkajffkeh commented on src/main/java/com/nextstep/racingcargame/core/Cars.java
> +        }
차량을 움직이는부분에 대해 좀더 명확히 보여지기 위해 객체를 생성 하였는데 막상 생각해보니 객체의 도움을 받지 않았을경우
코드를 좀더 간결하게 바꿀 수 있을것같습니다!!

2023-04-10 02:55 UTC, testrace approved these changes
안녕하세요 호연님
피드백 반영 잘해주셨네요 👍 
바로 다음 단계로 넘어가겠습니다!

2023-04-10 02:55 UTC, testrace commented on src/main/java/com/nextstep/racingcargame/core/Car.java
>      }
도메인 객체가 UI에 의존하기보다 UI에 도메인에 의존하는 방향으로 변경하는건 어떨까요?

2023-04-10 02:55 UTC, testrace commented on src/main/java/com/nextstep/racingcargame/core/ClientInput.java
> +    }
입력 받는 기능이 core 패키지 내부로 들어왔네요
입력 받는 기능은 핵심 로직이 아니니 view 패키지 내부에 있어도 괜찮을 것 같아요

2023-04-10 02:56 UTC, merged