2단계 - 문자열 덧셈 계산기 : 최초 커밋
next-step/java-racingcar pull request #4326
Opened 2023-04-09 11:02 UTC by jerry-shin

조금 늦었는지 모르겠지만 2단계 PR 요청드립니다.

목요일 온라인 강의를 못듣고, 다시 듣기 도중. 포비님 라이브 코딩 보기전에 멈추고

일단 삽질 하더라도 먼저 스스로 과제 수행해보고 코드리뷰 받아보는게 더 좋을 것 같아서 그렇게 해보았어요.

이제 라이브 코딩도 시청할 예정입니다.

그럼 리뷰 부탁드립니다. 감사합니다!

2023-04-09 15:11 UTC, shared-moon requested changes
의용님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 한번 정리하고 가면 좋을 것 같아
리뷰 재요청 부탁드립니다!
고생 많으셨어요 :)

2023-04-09 15:11 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +        if (input.startsWith(CUSTOM_DELEMITER_START)) {
`Pattern`과 `Matcher` 를 써보는 건 어떨까요 ?

2023-04-09 15:11 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +    private String removeCustomDelemiter(String target) {
이 부분도 `Pattern`과 `Matcher`를 이용하면 좀 간결해 질 수 있을 것 같아요. 추가로, 지금 기능상으로는 굳이 substring을 쓸 필요는 없어보이는데요! substring의 반환값은 어떻게 만들어지는걸까요 ?

2023-04-09 15:11 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +        if (number < 0) {
제한값도 상수로 빠지면 좋을 것 같아요!

2023-04-09 15:11 UTC, shared-moon commented on src/test/java/StringCalculatorTest.java
> +public class StringCalculatorTest {
테스트 작성 잘 해 주셨네요 :)

2023-04-10 16:01 UTC, jerry-shin commented on src/main/java/StringCalculator.java
> +    private String removeCustomDelemiter(String target) {
substring의 반환값은 어떻게 만들어지는걸까요 ? 
-> 이 질문의 의도를 정확히 이해하지 못했는데요. 이미 코드를 리팩토링 한 상태긴 한데, 이 매소드는 커스텀 구분자를 삭제한 스트링을 만들기 위해 substring을 사용하고 이값을 리턴하기 위해 사용하였습니다.

2023-04-11 22:56 UTC, shared-moon approved these changes
의용님 안녕하세요!
피드백 반영을 잘 해 주셨네요 :)
이번 미션은 머지 하도록 하겠습니다.
고생 많으셨어요 :)

2023-04-11 22:56 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +    private String removeCustomDelemiter(String target) {
`substring` 은 결국 문자열을 새로 만들기 때문에, 상수풀을 채우게 될 수 밖에 없습니다. 물론 큰 문제는 아니긴 하지만, 새로운 문자열을 생성하는 행위가 무분별하게 일어날 경우 시스템에 악역향을 미칠 수 있기에 한번 짚어봤어요! 구글에 `문자열 상수풀`을 검색하시면 관련 정보 찾아보실 수 있을거에요!

2023-04-11 22:56 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +        Pattern pattern = Pattern.compile(CUSTOM_DELEMITER_REGEX);
👍

2023-04-11 22:56 UTC, shared-moon commented on src/main/java/StringCalculator.java
> +        if (input == null || input.isBlank()) {
👍

2023-04-11 22:56 UTC, merged