Step3 완료
next-step/java-racingcar pull request #4327
Opened 2023-04-09 11:21 UTC by player-geun

안녕하세요 태현님! 이번에도 리뷰 잘부탁드립니다 :) 몇 가지 질문사항에 대해서 질문남길게요!
1. 테스트 커버리지는 얼마나 되야 될까요?? 현재 CarRacing의 play() 메서드는 테스트를 하기 힘들어서 진행을 못했는데, 해당 메서드도 테스트 코드를 작성해야 할까요??
2. 위의 맥락에서 View 부분도 현재 테스트 코드가 없습니다. `new ByteArrayInputStream(input.getBytes());` 를 추가하여 테스트 코드를 작성하려고 했으나 InputView의 Scanner 를 인스턴스 변수로 선언하는 경우, 입력값이 제대로 입력되지 않아 테스트 코드가 정상적으로 동작하지 않았습니다. 만약 Scanner 변수를 메서드의 지역변수로 선언해주면 해당 테스트 코드가 작성이 됩니다. 
- 테스트하기 좋은 코드가 좋은 코드라고 들었는데, 이런 경우 Scanner를 메서드를 호출할 때마다 새로 생성하는 비용을 감수하고 테스트 코드를 작성하는 방향으로 가야할까요??
- 또한 왜 Scanner 변수를 인스턴스 변수로 선언했을 때는 `new ByteArrayInputStream(input.getBytes());` 을 통해 입력되지 않고, 지역 변수로 선언한 경우에만 해당 코드가 제대로 작동할까요??

(Junit에서 Scanner와 System.out을 테스트 하는 방법에 대해 찾아보고 적용시키는 과정에서 발생한 문제입니다 !!)
방법 출처 : https://steadyjay.tistory.com/m/10

2023-04-10 16:05 UTC, dave915 requested changes
근우님! 3단계 미션 구현 잘 해주셨습니다! 👍
몇가지 간단한 피드백과 코멘트 남겼어요! 확인 부탁드릴게요 :)

2023-04-10 16:05 UTC, dave915 commented
>테스트 커버리지는 얼마나 되야 될까요?? 현재 CarRacing의 play() 메서드는 테스트를 하기 힘들어서 진행을 못했는데, 해당 메서드도 테스트 코드를 작성해야 할까요??

커버리지는 높을 수록 좋다고 생각합니다. 
play 메소드 같은 경우 유저와 도메인 로직 중간에 있는 로직이기 때문에 테스트 하지 않아도 될 것 같아요 :) 
궁금한점 있으시면 DM 부탁드릴게요! 

>위의 맥락에서 View 부분도 현재 테스트 코드가 없습니다. new ByteArrayInputStream(input.getBytes()); 를 추가하여 테스트 코드를 작성하려고 했으나 InputView의 Scanner 를 인스턴스 변수로 선언하는 경우, 입력값이 제대로 입력되지 않아 테스트 코드가 정상적으로 동작하지 않았습니다. 만약 Scanner 변수를 메서드의 지역변수로 선언해주면 해당 테스트 코드가 작성이 됩니다.
>- 테스트하기 좋은 코드가 좋은 코드라고 들었는데, 이런 경우 Scanner를 메서드를 호출할 때마다 새로 생성하는 비용을 감수하고 테스트 코드를 작성하는 방향으로 가야할까요??
>- 또한 왜 Scanner 변수를 인스턴스 변수로 선언했을 때는 new ByteArrayInputStream(input.getBytes()); 을 통해 입력되지 않고, 지역 변수로 선언한 경우에만 해당 코드가 제대로 작동할까요??
(Junit에서 Scanner와 System.out을 테스트 하는 방법에 대해 찾아보고 적용시키는 과정에서 발생한 문제입니다 !!)
방법 출처 : https://steadyjay.tistory.com/m/10

미션 구현 요구사항 중 `단, UI(System.out, System.in) 로직은 제외` 라는 문구가 있습니다! 해당 부분은 테스트 코드 작성하지 않아도 될것 같아요! 
하지만 궁금하시다면! 다음 PR 보내실때 말씀 하신 부분을 따로 구현 해 두시면 해당 부분 보면서 같이 의견 나누면 좋을 것 같습니다! 

>Car 클래스의 distance 변수같은 경우, Java에서 인스턴스 변수는 자동으로 초기화되는 것을 활용하여 따로 초기화해주지 않았습니다. 인스턴스 변수에 0과 같은 디폴트 값으로 초기화하더라도 초기화 코드를 작성해줘야하나요??

굳이 작성하지 않아도 되지만, 한편으로는 작성 해 주는게 조금 더 친절 한 코드가 될 수 있을 것 같아요 😀

2023-04-11 11:54 UTC, player-geun commented
안녕하세요 태현님! 말씀하신 피드백 반영하여 수정하였습니다! 몇 가지 질문사항 남겨놓도록 할게요!
1. getter, setter 메서드도 테스트 커버리지를 위해 테스트 해야 하나요??
2. Cars의 moveForward() 함수는 내부에서 랜덤값을 만들기 때문에 테스트하기가 어렵습니다. for문 마다 새로운 랜덤값을 생성해야 해서 랜덤값을 외부에서 주입받을려면, 랜덤값에 대한 배열을 주입받아야 하는 것 같습니다. 이런 경우 매개변수가 복잡하더라도 클라이언트에서 추가적으로 일을 더 해야할까요, 테스트하기 어렵더라도 이렇게 가져가는 것이 맞을까요??
3. CarRacing에서 Cars 변수를 지역변수로 전환하였습니다. CarRacing의 "상태"와 어울리지 않다고 판단하였는데, 태현님은 어떻게 생각하시나요??

2023-04-11 11:54 UTC, player-geun commented on src/main/java/study/step3/domain/Car.java
> +        return position += randomValue;
요구사항을 잘못 파악한 것 같습니다! 수정했습니다!

2023-04-11 11:55 UTC, player-geun commented on src/main/java/study/step3/domain/Car.java
> +        if (randomValue < 4) {
조건을 전략패턴화하여 구현하였습니다!

2023-04-13 11:42 UTC, dave915 requested changes
근우님 안녕하세요! 피드백 반영한 부분 확인했습니다 💯 
몇가지 피드백 더 남겼어요! 확인 부탁드릴게요 :)

2023-04-13 11:43 UTC, dave915 commented
>getter, setter 메서드도 테스트 커버리지를 위해 테스트 해야 하나요??

음.. getter 같은 경우엔 저는 개인적으로 안해도 된다고 생각합니다.. ㅎㅎ 
setter는 우선 setter 메소드 자체는 지양 하고, 객체의 상태를 변경 할 땐 의미 있는 메소드 명을 사용 한다고 가정하면.. 객체 상태 변경을 확인 한다는 의미로 테스트가 필요하다고 생각해요 :) 

>Cars의 moveForward() 함수는 내부에서 랜덤값을 만들기 때문에 테스트하기가 어렵습니다. for문 마다 새로운 랜덤값을 생성해야 해서 랜덤값을 외부에서 주입받을려면, 랜덤값에 대한 배열을 주입받아야 하는 것 같습니다. 이런 경우 매개변수가 복잡하더라도 클라이언트에서 추가적으로 일을 더 해야할까요, 테스트하기 어렵더라도 이렇게 가져가는 것이 맞을까요??

관련해서 코드상에 피드백 남겼습니다!

> CarRacing에서 Cars 변수를 지역변수로 전환하였습니다. CarRacing의 "상태"와 어울리지 않다고 판단하였는데, 태현님은 어떻게 생각하시나요??

구현에 따라서 CarRacing 의 play가 여러번 실행 될 수 있기 때문에, 저도 근우님과 동일하게 CarRacing의 상태에서 제외 시키는 편이 좋다고 생각합니다 :) 

>제가 영어 이슈가 좀 있어서... 움직임 조건의 구현체 이름을 LessThanMoveCondition 이라고 지었습니다(이하인 조건을 표현하려고 했는데, 고민을 더 해봐도 현재는 이게 최선이네요 ㅜㅜ). 태현님이라면 어떻게 지으셨을까요??

아.. 저도 아마 비슷하게 지었을껏 같아요 🥲
의미가 명확한 객체명 이라고 생각합니다 ㅎㅎ

2023-04-15 06:27 UTC, player-geun commented
안녕하세요 태현님! 말씀하신 피드백 반영하여 수정하였습니다! 질문사항 남겨놓도록 할게요!

> MoveConditionStrategy 에서 distance 에 따른 전진 가능 유무 MoveStrategy 에서 distance 생성 을 해주고 있는 걸로 보이는데요! MoveConditionStrategy 를 생성할때 MoveStrategy를 정해주고 Car에서는 아래와 같이 사용하면 어떨까요?
> 
> 객체에서 기능 동작 할 때 불확실한 부분을 아예 분리 해보세요 :)

해당 부분을 반영하면서 moveForward는 매개변수로 거리를 전달받는 형식에서 벗어나게 되었습니다. 하지만 이러는 경우 moveForward() 테스트가 어려워지는 것 같습니다. random 값을 메서드 안에서 생성해줘서 외부에서 특정 랜덤값에 따른 결과값을 테스트하기가 불가능한 것 같습니다. 이런 경우,  테스트 용이성과 비슷한 객체끼리 의존을 갖는 형태로 변경하는 객체지향적 설계 중에 어느 것을 더 우선시 해야할까요??

2023-04-16 09:30 UTC, dave915 commented
>테스트 용이성과 비슷한 객체끼리 의존을 갖는 형태로 변경하는 객체지향적 설계 중에 어느 것을 더 우선시 해야할까요??

저는 두가지 중에 어느 것 하나 우선시 할 수 없다고 생각합니다! 만약 테스트 용이성을 살려서 설계 하다보면 자연스럽게 새로운 역할의 클래스들이 도출되어서 말씀 하신 비슷한 객체끼리 의존하게 될 것 같아요 :)

2023-04-16 09:31 UTC, dave915 approved these changes
근우님 피드백 반영 확인했습니다.
몇가지 코멘트 남겨두었습니다. 이건 다음 단계 진행하면서 같이 반영해주세요 :) 
이만 머지하겠습니다.

2023-04-16 09:31 UTC, dave915 commented on src/main/java/study/step3/domain/Car.java
> +        if (moveConditionStrategy.isPossible()) {
이렇게 되면 Car 입장에서는 moveConditionStrategy.isPossible() 메소드의 구현 방법과 관계없이 오로지 true/false 인지만 신경쓰면 돼요! 
Car의 이동 테스트를 할때 랜덤으로 true를 리턴하는 것이 아닌 무조건 true를 리턴하는 moveConditionStrategy 를 구현해서 테스트 하는건 어떻게 생각하시나요?

2023-04-16 09:31 UTC, dave915 commented on src/main/java/study/step3/domain/Cars.java
> +            cars.add(new Car(new LessThanMoveCondition(4, new RandomMove())));
>또한 객체에서 기능 동작 할 때 불확실한 부분을 아예 분리하셔라고 했는데, 이 부분에 대해서 조금더 자세히 설명부탁드려도 될까요?? 

이 질문에 대한 답을 여기다가 남겨둘게요! 
지금 Car의 moveForward 메소드 내에 랜덤으로 이동 여부를 결정 하는 로직이 Cars로 올라와서 이제 moveForward는 테스트 하기 쉬워졌을거에요. 
하지만 아직 Cars내에서 LessThanMoveCondition을 참조 하기 때문에 Cars의 moveForward는 테스트 하기 힘들거에요 🥲
LessThanMoveCondition 도 Car와 동일하게 Cars를 생성할때 전달 받도록 수정해볼까요? 

이런식으로 불확실한 로직을 상위 객체로 올리게 되면 점점 테스트 가능한 메소드 들이 많아질거에요 :)

2023-04-16 09:31 UTC, dave915 commented on src/main/java/study/step3/domain/LessThanMoveCondition.java
> +        return false;
😀
```suggestion
        return moveStrategy.createMove() >= criteria;
```

2023-04-16 09:31 UTC, merged