[단위 테스트] 2단계 - 문자열 덧셈기
next-step/java-racingcar pull request #4335
Opened 2023-04-09 14:44 UTC by tataki26

리뷰 부탁 드립니다 :)
감사합니다!

2023-04-10 11:55 UTC, kyucumber reviewed
요거 PR이 close 되었는데 한번 확인 부탁드릴게요.

2023-04-11 13:39 UTC, kyucumber requested changes
안녕하세요 MR이 close되면서 리뷰가 조금 지연되었네요.

몇가지 코멘트 남겨두었으니 확인 부탁드려요.

2023-04-11 13:39 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +    public static int splitAndSum(String input) {
대부분 메서드가 static 메서드로 이루어져있네요.

지금과 같은 복잡도 정도라면 static을 사용해도 무방합니다.

하지만 static 키워드, 즉 정적 메서드는 객체 지향의 특징인 다형성 등을 구현할 수 없는 여러가지 단점이 있습니다. 이번 과정에서는 static 키워드의 사용을 지양하고 꼭 정적 메서드로 구현될 필요가 있는 것인지 한번 더 고민하고 사용해보시면 좋겠습니다.

https://tecoble.techcourse.co.kr/post/2020-07-16-static-method/

2023-04-11 13:39 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +        return ",";
힌트로 제공된 정규식을 사용하는건 어떨까요?

```java
// java.util.regex 패키지의 Matcher, Pattern import
Matcher m = Pattern.compile("//(.)\n(.*)").matcher(text);
if (m.find()) {
    String customDelimiter = m.group(1);
    String[] tokens= m.group(2).split(customDelimiter);
    // 덧셈 구현
}
```

그리고 Patten.compile은 비싼 객체이므로 상수로 추출하는것을 고려해보세요.
지금 정도라면 성능상 문제는 없겠지만 반복문 내에서 저런 비싼 객체를 생성하는것은 GC 등의 문제로 성능에 좋지 않습니다.

2023-04-11 13:39 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +            throw new RuntimeException("input must be a non-negative integer");
요구사항엔 RuntimeException으로 나와있었을 것 같은데요. RuntimeException의 구체 타입인 IllegalArgumentException 혹은 IllegalStateException이 적절하진 않은지 고민해보시면 좋겠습니다.

2023-04-11 13:39 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +            }
지금은 isPositive의 호출이 더하는 전단계에 항상 이루어지지만 isPositive의 호출이 누락된 경우에 음수가 들어갈 수 있을 것 같아요.

PositiveNumber와 같은 래핑된 클래스를 만들고 생성자에서 양수인지를 검증하는 형태로 구현해볼 수 있을 것 같습니다.

2023-04-12 06:07 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +    public static int splitAndSum(String input) {
테스트 클래스에 StringAdder 클래스 인스턴스를 생성하도록 코드 수정했습니다! :)
인텔리제이의 자동 옵션을 사용하다 보니 모든 함수를 static으로 정의하는 실수를 저질렀네요 ㅠㅠ

2023-04-12 06:16 UTC, tataki26 commented on src/test/java/StringAdder/StringAdderTest.java
> +}
몰랐던 내용이었는데 덕분에 배웠습니다, 감사합니다! 👍

2023-04-12 06:23 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +            throw new RuntimeException("input must be a non-negative integer");
첫 설계 시에는 IllegalArgumentException가 더 적합하다고 생각해서 적어 놨었는데 나중에 요구 사항 확인하다가 변경했던 기억이 있네요. 
다시 복구했습니다 :)

2023-04-12 06:35 UTC, tataki26 commented on src/test/java/StringAdder/StringAdderTest.java
> +    }
요청하신 대로 methodSource를 활용해서 테스트하는 방향으로 수정했습니다 :) 
중복 코드도 줄고 훨씬 편하네요!

2023-04-12 06:42 UTC, tataki26 commented on src/test/java/StringAdder/StringAdderTest.java
> +    }
찾아보니 JUnit 5에서는 @NullAndEmptySource 애노테이션이 추가되었다는 걸 알게 되었습니다
앞으로 null이나 빈 값에 대한 테스트에는 해당 애노테이션을 적극 활용 해보겠습니다~

2023-04-13 16:06 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +            }
네! 피드백 주신 내용대로 반영했습니다 👍

2023-04-16 16:49 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +        }
stream을 사용해서 수정했습니다!

2023-04-16 16:50 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +        return ",";
힌트 참고해서 splitString 다시 작성했습니다 :)

2023-04-16 16:53 UTC, tataki26 commented on src/main/java/StringAdder/StringAdder.java
> +        }
ArrayList를 사용하는 방향으로 수정했습니다 :)

❗❗❗ sumAll을 stream 구문으로 수정 하면서 String을 int로 바꾸고 음수 체크하고 더하는 역할까지 오히려 더 늘어나게 되었는데 함수형 프로그래밍을 사용하면 어쩔 수 없는 부분인가요?

2023-04-16 16:59 UTC, tataki26 reviewed
피드백 내용 반영하여 리팩토링 진행했습니다 :)
질문도 몇 개 추가했는데 확인 부탁드립니다!
시간 내주셔서 정말 감사합니다 👍

2023-04-17 13:23 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +        }
조건이 2개면 그렇게 하셔도 되고, 그게 아니라면 메서드를 분리하실수도 있습니다.

2023-04-17 13:25 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +        }
> ❗❗❗ sumAll을 stream 구문으로 수정 하면서 String을 int로 바꾸고 음수 체크하고 더하는 역할까지 오히려 더 늘어나게 되었는데 함수형 프로그래밍을 사용하면 어쩔 수 없는 부분인가요?

이런 경우면 숫자로 변환하는 부분을 분리하고 변환을 마친 뒤 `List<Integer>`에 대해서만 Stream과 sum을 활용하시면 될 것 같네요. 전처리는 어쩔 수 없이 필요한 부분인데 그걸 하나의 Stream으로 처리할 필요는 없습니다.

2023-04-17 13:31 UTC, kyucumber approved these changes
몇가지 코멘트 남겨두었으니 확인 부탁드려요.

남긴 코멘트는 꼭 확인해주시고 다음 단계 진행에 참고 부탁드립니다.

다음 단계 진행을 위해 머지하겠습니다.

2023-04-17 13:31 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +    }
이부분에 대해 코멘트를 남기셔서 답변을 달긴 했는데요. 여기다가도 남깁니다.

이 sumAll 메서드는 아래 역할을 수행하고 있어요.

1. String으로 나뉜 토큰들을 Integer로 변환하는 역할
2. PositiveNumber로 변환하는 역할
3. getNumber를 통해 Integer로 변환하는 역할
4. 전체 합을 구하는 역할

객체지향의 SOLID 중 단일 책임 원칙이 있는데 메서드가 하나의 책임만 하도록 변경해볼 수 있을 것 같아요.

2023-04-17 13:31 UTC, kyucumber commented on src/main/java/StringAdder/StringAdder.java
> +    public int sumAll(ArrayList<String> strArr) {
함수 파라미터나 리턴 타입에는 ArrayList와 같은 구체 타입이 아닌 List를 사용해주세요.

List를 사용할 때 우리는 내부 구현체가 ArrayList든 LikedList든 구체 타입을 모르고 사용할 수 있는데 이렇게 구체 타입을 적어주시면 이런 장점을 누릴 수 없습니다. 이후에 LinkedList로 변경한다고 하면 변경 비용도 커질거구요.

2023-04-17 13:31 UTC, merged