step2
next-step/java-racingcar pull request #4349
Opened 2023-04-10 04:25 UTC by devcat36

2023-04-10 12:59 UTC, serverwizard requested changes
2단계 미션 진행 하시느라 고생 많으셨어요. 👍

소소한 코멘트 몇 개 남겼는데, 확인해 주시면 좋을 것 같아요.
그럼 화이팅입니다.

2023-04-10 12:59 UTC, serverwizard commented on src/test/java/StringCalculatorTest.java
> +    public void zeroIfNull() {
@DisplayName을 통해 테스트 의도를 나타내주시면 더 좋을 것 같네요 :)

2023-04-10 12:59 UTC, serverwizard commented on src/main/java/StringCalculator.java
> +    public static Long sumOfNumbers(String input) {
현재 sumOfNumbers()메소드는 1개 이상의 책임(덧셈, split)을 가지고 있는 것 같은데요.
split하는 책임은 별도의 객체를 만들어 위임해 보는 건 어떨까요?

즉, StringCalculator(문자열 덧셈 계산기)는 덧셈 책임만 가지도록 하고 그 외 책임들은 별도의 객체를 만들어 그곳에서 처리하도록 해보는 건 어떨까요?

2023-04-10 12:59 UTC, serverwizard commented on src/main/java/StringCalculatorInput.java
> +        return Pattern.compile(extractorRegex).matcher(input);
참고로, Pattern 객체는 생성 비용이 비싼 객체인데요.
이런 객체가 자주 사용되는 경우라면, 사용될 때마다 생성하는 방식보단 캐싱해서 사용하는 것이 좋을 것 같아요.
이를 위해 Pattern 객체를 static final로 선언하는 건 어떨까요?
<img width="857" alt="image" src="https://user-images.githubusercontent.com/23587638/230327955-69fb3138-7934-4cef-bade-acb7ffe671fd.png">
- https://a1010100z.tistory.com/167

2023-04-12 09:57 UTC, devcat36 commented on src/test/java/StringCalculatorTest.java
> +    public void zeroIfNull() {
DisplayName 을 통해 테스트 설명을 추가하였습니다.

2023-04-12 09:57 UTC, devcat36 commented on src/main/java/StringCalculator.java
> +    public static Long sumOfNumbers(String input) {
split 을 StringCalculatorInput 에서 담당하도록 처리하여 StringCalculator 는 Sum 및 Positive check 만 담당하도록 하였습니다.

2023-04-12 09:58 UTC, devcat36 commented on src/main/java/StringCalculatorInput.java
> +        return Pattern.compile(extractorRegex).matcher(input);
비싼 객체인지 모르고 있었습니다. 캐싱 적용하였습니다.

2023-04-14 03:13 UTC, serverwizard approved these changes
2단계 문자열 덧셈 계산기 미션 잘해주셨네요. 👍 👍 

몇 가지 소소한 리뷰 남겨뒀으니 
다음 단계 진행하시기 전에 참고만 부탁드릴게요.

그럼 남은 미션도 화이팅입니당!

2023-04-14 03:13 UTC, serverwizard commented on src/main/java/StringCalculator.java
> +        }
자바 스트림을 이용하면 해당 로직을 간단하게 표현할 수 있답니다. 
```
1. longs.stream()
             .reduce(0L, Long::sum);
2. longs.stream()
              .mapToLong(i -> i)
              .sum();
3. ...
```

2023-04-14 03:13 UTC, serverwizard commented on src/main/java/StringCalculatorInput.java
> +    private static List<String> split(String input, String regex) {
split하는 책임도 StringCalculatorInput객체가 아닌 별도의 객체를 만들어서 위임해보면 좋을 것 같네요. :)

2023-04-14 03:13 UTC, serverwizard commented on src/test/java/StringCalculatorTest.java
> +    @DisplayName("String calculator returns 0 when input is null")
👍

2023-04-14 03:13 UTC, serverwizard commented on src/test/java/StringCalculatorTest.java
> +public class StringCalculatorTest {
도메인 테스트 코드 작성 👍

2023-04-14 03:13 UTC, merged