Step4 - 자동차경주(우승자) PR입니다
next-step/java-racingcar pull request #4377
Opened 2023-04-10 13:38 UTC by 201411167

## 작업내용
- 자동차경주(우승자) 관련 기능 추가
- 테스트코드 작성
- 작업은 step3 브랜치에서 생성했습니다.
  - 관련pr : https://github.com/next-step/java-racingcar/pull/4347

2023-04-11 10:37 UTC, heowc commented on src/main/java/study/Car.java
> +    }
해당 코드는 테스트 코드에만 사용되는 것 같아서 제거해도 될 것 같아요 🤔

2023-04-11 11:03 UTC, heowc requested changes
4단계로 먼저 진행해주셨네요 😅 

이전 단계가 마무리 되지 않았다면 먼저 마무리 된 이후에 다음 단계를 진행해주시면 좋을 것 같아요~
(제가 늦어져서 진행해주신거라면 죄송합니다 🙏 )

3단계 코멘트를 포함하여 소소한 코멘트가 있으니 확이 부탁드릴 겸 request change드렸습니다.
궁금하시거나 어려움인 있으시다면 코멘트 주세요 💪

2023-04-12 09:05 UTC, 201411167 commented on src/main/java/study/Car.java
> +        status += "\n";
이 부분은 확실히 View 로직인거 같은데 객체에까지 넣어버렸네요
이 부분은 수정하도록 하겠습니다.

2023-04-12 09:05 UTC, 201411167 commented on src/main/java/study/CarRace.java
> +    }
테스트코드에 남아있는 메소드 때문에 미사용메소드를 제대로 확인하지 못한 것 같아요.
이 부분도 수정하겠습니다.

2023-04-13 04:59 UTC, heowc approved these changes
5단게에서 뵙겠습니다 👍

2023-04-13 04:59 UTC, merged