3단계 - 자동차 경주
next-step/java-racingcar pull request #4384
Opened 2023-04-10 15:16 UTC by joooahn

잘 부탁드립니다

2023-04-11 03:44 UTC, wooobo requested changes
3단계 잘 진행해주셨습니다!

코멘트 남겨드렸는데 확인 후 재요청 부탁드려요! 🙏

2023-04-11 03:44 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
[Clean Code "의미있는 네이밍"](https://ostarblog.tistory.com/6)

`Info`, `Data` 이러한 네이밍은 사용하지 않는 편입니다 🙏

2023-04-11 03:44 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +        return currentDistance - prevDistance > 0;
```suggestion
    public boolean isMoved(value) {
        return value > 0;
```

`isMoved`는  사용하는 입장에서`비교 검증`의 책임이 가장 큰것 같아요. 
이미 계산된 (`currentDistance - prevDistance`) 의 값을 넣어준다라는 관점으로 접근한다면, 메소드의 책임이 좀 더 명확해지지 않을까요?


물론, 현재 로직에서는 큰문제는 없습니다. 
이번 과정을 진행하시면서 메소드의 책임을 분명히 하고 하나의 개념만 작업을 할 수있도록 훈련해보시면 좋을것 같아요!

2023-04-11 03:44 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +    public boolean isRandGreaterThan4() {
```suggestion
    public boolean isRandGreaterThan(...)
```
세부사항을 외부로 과도하게 노출시키고 있는것 같아요

네이밍을 통해 세부사항을 과도하게 노출하는 것은 안좋다고 생각해요.
구현코드를 수정하면 `isRandGreaterThan4` 이름또한 수정해줘야 하는 부분이 있기 때문이에요.
이름을 좀 더 일반화 하거나,
변하는 부분을 변수로 분리해보아요.

2023-04-11 03:44 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +    private int currentDistance = 0;
불변객체를 고민해보아요.

2023-04-11 03:44 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
`CarInfo` 에대한 테스크 클래스가 없네요 🤔

2023-04-12 10:26 UTC, joooahn commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
@wooobo 리뷰 감사합니다
CarInfo의 테스트 클래스 말씀하시는거겠죠?(태스크 클래스 검색해보니 나오지 않아서ㅎㅎ)

클래스 네이밍 수정했습니다
- CarInfo > Car
- RacingInfo > Racing

CarInfo의 테스트 추가했습니다

2023-04-12 10:27 UTC, joooahn commented on src/main/java/racingcar/CarInfo.java
> +    public boolean isRandGreaterThan4() {
@wooobo 
말씀하신 문제점이 공감이 가네요
isRandGreaterThan(...)
파라미터를 받아 비교하도록 변경했습니다

2023-04-12 10:29 UTC, joooahn commented on src/main/java/racingcar/CarInfo.java
> +    private int currentDistance = 0;
@wooobo 
사실 제가 불변객체에 대해 깊게 고민하고 개발해 본적이 없는 것 같네요
덕분에 이번 기회에 여러 생각을 해 보았습니다
위의 Car 클래스 같은 경우는 변화하는 자동차의 현재 상태를 나타내야 하는데
불변객체로 만들면 변화하는 상태를 나타낼 수 없을 것 같아요
이런 경우엔 어떻게 해야 하는지 모르겠습니다

2023-04-13 01:59 UTC, wooobo requested changes
안녕하세요!

코멘트 남겨 놓았습니다! 😄 

확인 후 재요청 부탁드립니다! 🙏

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/Car.java
> +        return diff > 0;
`isMoved` 입장에서 `diff`라는 개념을 가지는 변수명을 사용할 필요가 있을지 생각이 들었어요 🤔 
단순하게 `isMoved(1)` 이렇게 사용하도록 변경된 구조 아닐까요?
`car.isMoved` 메소드 안에서 사용하는 인자의 성격은 무엇인지 고민해보면 그냥 단순한 숫자값아닐까요?

제가 이러한 부분을 고민하는 이유는 코드의 가독성과 오용을 막기 위해서입니다.
외부로 부터 의미를 부여 받는것이 아닌 객체 or 메소드 자체 그 안에서 의미를 생각해보면 어떨까요?
(이러한 부분이 커지면 불필요한 개념 or 종속성이 생길수 있다고 생각해요 🤔 )

`int diff`물론 괜찮습니다! 하지만, 이러한 관점도 한번 고려해봐주세요~ 🙏

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/RacingService.java
> +    }
`racing.getCars();` 만 호출하는데 한번 더 메소드로 분리한 이유가 궁금해요!

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/RacingService.java
> +                .filter(car -> car.getResultOfRand() > 4)
```suggestion
                .filter(car -> car.전진())
```

객체에게 메시지를 던져보면 어떨까요?

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/ResultView.java
> +            String dashes = "-".repeat(car.getCurrentDistance());
```suggestion
            String dashes = "-".repeat(car.결과? or 전진한갯수?);
```

의미를 좀 더 분명하게 하면 좋을것 같아요.
객체를 능동적으로 사용할 수 있도록 객체에게 의미를 확실하게 전달해보는건 어떨까요? 🤔 

<img width="551" alt="스크린샷 2023-04-13 오전 10 46 27" src="https://user-images.githubusercontent.com/12059592/231625145-0dda09ac-b048-483b-aee9-620993304236.png">

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
죄송합니다!
`테스트 클래스`  맞습니다! ^^;;;

2023-04-13 01:59 UTC, wooobo commented on src/main/java/racingcar/Car.java
> +    private int currentDistance = 0;
```
        Distance currentDistance = Distance.zero();
        
        public void ...() {
                currentDistance = currentDistance.plus(1);
        }
```

>불변객체로 만들면 변화하는 상태를 나타낼 수 없을 것 같아요
이런 경우엔 어떻게 해야 하는지 모르겠습니다

A. 
새로운 객체를 반환하도록 시켜보시면 될것 같아요!

2023-04-13 01:59 UTC, wooobo commented on src/test/java/racingcar/RacingCarTest.java
> +        Car car = new Car();
테스트 코드 또한 응집성이 중요하다고 생각하는데요!

- CarTest
- RacingTest

이렇게 분리시켜보면 어떨까요?

2023-04-13 01:59 UTC, wooobo commented on src/test/java/racingcar/RacingCarTest.java
> +        assertThat(car.isRandGreaterThan(4)).isFalse();
[8. 테스트당 개념 하나.](https://catsbi.oopy.io/a4aad7d3-73ed-463d-99aa-c677c9747e44#414d4fad-01ac-457d-aabf-4a142a460c11)

하나의 테스트 메소드에 많은 개념이 들어가져 있어요 🤔 

테스트 하고자 하는 도메인 메소드 단위로 하나씩 진행해보면 어떨까요?

2023-04-13 10:46 UTC, joooahn commented on src/main/java/racingcar/RacingService.java
> +    }
이럴 필요가 없네요 처음 클래스 만들때 넣고 잊고있었습니다ㅋㅋ;

2023-04-13 10:48 UTC, joooahn commented on src/main/java/racingcar/RacingService.java
> +                .filter(car -> car.getResultOfRand() > 4)
말씀하신 25 Line에선 rand 결과에 대한 필터링을 한 후, 바로 아래줄(26Line)에서 Car::moveFoward를 사용하고 있습니다
이 구조에 문제가 있나요?

2023-04-18 02:58 UTC, wooobo approved these changes
3단계 수고하셨습니다! ^^

코멘트 확인 부탁드려요~

다음단계 진행해주세요 😄

2023-04-18 02:58 UTC, wooobo commented on src/main/java/racingcar/InputView.java
> +@Data
![스크린샷 2023-04-18 오전 11 42 18](https://user-images.githubusercontent.com/12059592/232656838-a323bbf6-879c-4d9d-b815-9d423ae4be62.png)

이번과정에서는 특별한 라이브러리를 사용하기 보다는 순수한 객체로 직접 작성해보시는것을 추천드려요!
`@Data` 를 사용하는것은 나쁜것이 아닙니다.
하지만, 이번 과정에서 강조하는 조건들을 철저하게 지키기 위한 노력을 해보시면 새로운 관점들이 보일거라고 생각합니다!

2023-04-18 02:58 UTC, wooobo commented on src/main/java/racingcar/RacingService.java
> +                    return rand > racing.getThreshold() ? car.moveFoward(rand) : car;
문제가 있다기 보다는 객체지향 개발에서 본다면 아쉬움이 있는것 같아요!

`Racing`를 단순한 자료구조로 사용하고 있는것 같아요!
상태를 가진 객체에게 메시지를 전달하고 객체가 직접 상태를 관리할수 있도록 하려면 어떻게해야하는지 고민해보면 좋을것 같아요!

2023-04-18 02:58 UTC, wooobo commented on src/main/java/racingcar/RacingService.java
> +                    return rand > racing.getThreshold() ? car.moveFoward(rand) : car;
저는 정답이 없다고 생각하고, 다양한 관점으로 생각하려고 노력하는 편입니다.

다른 관점으로 본다면, 
```suggestion
                    return racing. forwardable() ? car.moveFoward(rand) : car;
```

`rand > racing.getThreshold()`의 상태 판단을 객체에게 맡김으로써 코드의 의도를 파악하기에 쉬워졌고 응집성이 높아졌다고 생각하기 때문에 생각해보았어요!

2023-04-18 02:58 UTC, wooobo commented on src/main/java/racingcar/RacingService.java
> +                    return rand > racing.getThreshold() ? car.moveFoward(rand) : car;
추가적으로 객체의 메소드가 생겼으므로 TDD를 진행하기에도 더 용이할것 같네요! 😄

2023-04-18 02:59 UTC, merged