🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #4392
Opened 2023-04-10 23:49 UTC by MoonHKLee

3단계 구현 완료했습니다.
잘 부탁드립니다.

2023-04-11 11:44 UTC, seondongpyo requested changes
3단계 미션도 잘 작성해주셨네요 👍
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청 부탁드리겠습니다 🔥
궁금하거나 나누고 싶은 의견 있으시면 편하게 연락 주세요 🙏

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +    public void push(int number) {
자동차 입장에선 스스로 '이동'하는 행위이니, 메서드 이름을 `move()` 정도로 지어보는 건 어떨까요?

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/Game.java
> +    private final Car[] cars;
[배열보다는 `List`를 사용](https://velog.io/@new_wisdom/Effective-java-item-28.-%EB%B0%B0%EC%97%B4%EB%B3%B4%EB%8B%A4%EB%8A%94-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)해보면 어떨까요?

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/Game.java
> +        }
- `1`과 같은 숫자 리터럴은 상수로 선언하여 의미를 부여해보면 어떨까요?
- 자동차 대수와 시도 횟수는 모두 `InputView`에서 입력을 받으니, `InputView`에서 검증을 하는 건 어떨까요?

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/Game.java
> +    private Car[] createCars() {
자동차 묶음을 외부에서 생성하고, `Game`을 생성할 때 이를 생성자로 전달해볼 수도 있을 것 같아요.

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/InputView.java
> +    private final Scanner scanner;
`InputView` 또한 `OutputView`처럼 정적 메서드만을 갖는 유틸리티 클래스로 만들어보는 건 어떨까요?
자동차 대수나 시도 횟수 같은 값을 View가 꼭 상태로 가지고 있을 필요는 없어보여요.

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/OutputView.java
> +public class OutputView {
정적 메서드만을 갖는 유틸리티 클래스이니 인스턴스를 생성하지 않고도 사용이 가능하지만
누군가는 실수로 생성자를 호출하여 인스턴스를 생성하려고 할 수 있으니, 
`private` 생성자를 추가해서 불필요한 인스턴스화를 막아보면 좋을 것 같아요.

2023-04-11 11:44 UTC, seondongpyo commented on src/main/java/racingcar/RandomNumber.java
> +    static Random random = new Random();
접근 제어자를 `package-private(default)`로 설정하신 이유가 있으실까요?

2023-04-11 11:44 UTC, seondongpyo commented on src/test/java/racingcar/CarTest.java
> +public class CarTest {
단위 테스트 👍 모든 값에 대한 테스트도 좋지만 경계 값을 위주로 테스트해도 충분할 것 같아요.

2023-04-11 11:44 UTC, seondongpyo commented on src/test/java/racingcar/CarTest.java
> +    void test1(int number) {
테스트 메서드들의 이름도 테스트의 목적에 맞게 지어보는 건 어떨까요?

2023-04-11 23:55 UTC, MoonHKLee commented on src/main/java/racingcar/Car.java
> +    public void push(int number) {
쓸데없는 메서드를 만들어서 메서드명 중복이 안생기게하려고 이상한 이름을 지은것같네요.
이정도는 하나로 통일하는게 좋은것같습니다.ㅎㅎ

2023-04-11 23:57 UTC, MoonHKLee commented on src/main/java/racingcar/Car.java
> +        return number >= 4;
그러네요 상수 선언하여 의미 부여하는게 좋을것같네요

2023-04-12 00:18 UTC, MoonHKLee commented on src/main/java/racingcar/Game.java
> +        }
자동차 대수와 시도횟수를 모두 `InputView`에서 검증을 받으니 올바르게 횟수가 입력되었는지 확인하는 자동화된 테스트가 InputView로 이동하게 되어 수동으로 진행하게 변경되었는데 이것에 대해서는 어떻게 생각하시나요?

2023-04-12 00:57 UTC, seondongpyo commented on src/main/java/racingcar/Game.java
> +        }
넵 이 부분은 검증을 각각 `Game`과 `InputView`에서 처리하는 것이 어떻게 다른지 한 번 경험해보셨으면 하는 차원에서 말씀드렸구요, 객체지향 생활 체조 원칙의 ['규칙 3: 모든 원시값과 문자열을 포장한다.'](https://velog.io/@jhp1115/%EC%9B%90%EC%8B%9C%EA%B0%92%EA%B3%BC-%EB%AC%B8%EC%9E%90%EC%97%B4-%ED%8F%AC%EC%9E%A5)를 적용하여 '자동차 대수'와 '시도 횟수'라는 원시 값들을 클래스로 포장해보시는 것도 추천을 드립니다. 원시 값을 포장하면 자연스럽게 검증 로직이 해당 클래스 내부로 옮겨지기 때문에 또 다른 경험을 느끼실 수 있으리라 생각합니다.

2023-04-12 10:42 UTC, MoonHKLee commented on src/main/java/racingcar/Game.java
> +    }
핵심 도메인 로직을 분리하고 나니 게임이 갖고 있지 않아도 되는 변수를 제거할 수 있었네요.

2023-04-12 11:13 UTC, MoonHKLee commented on src/main/java/racingcar/Game.java
> +    private Car[] createCars() {
의존성 주입으로 해결하는 방법 좋은것같네요 차 생성은 게임이 알 필요 없는 로직인것 같습니다.

2023-04-12 11:43 UTC, MoonHKLee commented on src/main/java/racingcar/InputView.java
> +    private final Scanner scanner;
좋은 리팩토링 방향인것 같네요 모두 의존성 받아서 진행하는 형태로 진행되는게 좋을것같네요.

2023-04-12 12:01 UTC, MoonHKLee commented on src/main/java/racingcar/RandomNumber.java
> +    static Random random = new Random();
아뇨 단순히 private 키워드를 빼먹었습니다.

2023-04-12 12:08 UTC, MoonHKLee commented on src/test/java/racingcar/CarTest.java
> +    void test1(int number) {
DisplayName으로 이미 테스트의 목적을 설명하고 있는데 메서드명까지 자세하게 적어야할까요?

2023-04-13 00:35 UTC, seondongpyo approved these changes
피드백 반영하시느라 고생 많으셨습니다 👍
이번 단계는 여기서 merge 하겠습니다.
다음 단계에서 뵐게요 🔥

2023-04-13 00:35 UTC, seondongpyo commented on src/main/java/racingcar/Car.java
> +    private int position;
상수와 인스턴스 변수를 구분하게 쉽도록 공백 라인을 추가해보는 건 어떨까요?
```suggestion
    private static final int MOVABLE_COUNT = 4;
    
    private int position;
```

2023-04-13 00:35 UTC, seondongpyo commented on src/main/java/racingcar/RacingCar.java
> +        Scanner scanner = new Scanner(System.in);
`Scanner`는 클라이언트로부터 값을 입력 받을 때만 사용하니, `InputView` 내부에서 관리하는 건 어떨까요?

2023-04-13 00:35 UTC, seondongpyo commented on src/test/java/racingcar/CarTest.java
> +    void testNonMove(int number) {
> DisplayName으로 이미 테스트의 목적을 설명하고 있는데 메서드명까지 자세하게 적어야할까요?

단위 테스트 작성 시, 보통 의도를 드러내기 위해 테스트하려는 메서드의 이름을 표기하는 경우가 종종 있습니다.
(ex. `Car`의 `move()` 메서드를 테스트하려고 한다면 테스트 메서드 이름은 `move()`)
이러면 해당 테스트 코드가 어떤 프로덕션 코드를 호출하여 동작하는지 쉽게 파악할 수 있다는 장점이 있습니다만,
물론 프로덕션 코드의 메서드 이름이 변경된다면 테스트 코드의 이름도 함께 변경해야 한다는 단점도 존재합니다.
테스트 메서드 이름과 관련해서 코멘트를 드린 것은, 다양한 방식으로 테스트 메서드를 작성해보시고
어떤 방식이 개인 혹은 함께 협업할 때 더 적절할지를 한 번 고민해보시면 좋을 것 같아서였습니다.

테스트 메서드 네이밍과 관련해서는 다음 링크들을 참고해보시면 좋을 것 같아요.
https://middleearth.tistory.com/39
https://eunjin3786.tistory.com/563

2023-04-13 00:35 UTC, merged