Step3
next-step/java-racingcar pull request #4406
Opened 2023-04-11 13:05 UTC by yoonjaej3

안녕하세요 준철님

자동차 경주를 하면서 궁금한게 있어서 질문드려요

주어진 입력값에 대한 예외 처리를 하는게 맞을까요?
예를들면 숫자가 들어오는게 아닌경우, 마이너스가 들어온 경우, 0이 들어온 경우 등등 입력값들에 대해 신경써주는게 TDD 클린코드 교육에서 신경써줘야 되는지요

리뷰 부탁드립니다 :)

2023-04-13 01:23 UTC, neojjc2 commented
> 주어진 입력값에 대한 예외 처리를 하는게 맞을까요?
예를들면 숫자가 들어오는게 아닌경우, 마이너스가 들어온 경우, 0이 들어온 경우 등등 입력값들에 대해 신경써주는게 TDD 클린코드 교육에서 신경써줘야 되는지요

요 부분은 리뷰어분들 마다 다르실 것 같은데요 꼭 구현을 해야하는 범위로 보시는 분들도 계시고
그렇지 않으신 분들도 계신걸로 알고 있습니다 😄 
사실 검증이나 예외 처리 같은 부분은 디테일하게 들어가면 들어갈 수록 요구사항과 별개로 개발 범위가 
늘어나는 부분이기 때문에 상대적일 수 있다고 생각합니다
그러기에 이 교육과정을 진행하시면서 미션마다 다른 리뷰어를 만나실 꺼구요 😅 

제 개인적인 기준은 요구사항에 기술되지 않은 검증 등은 **필수는 아닙니다** 
하지만 중요하다고 생각되는 부분, 혹은 검증이 되면 더 좋겠는 부분들에 대한 의견은 드릴 예정입니다 🙏 

어느정도 자율성이 보장되어있는 미션이니
그 부분에 대해서는 너무 고민 안하셔도 될 것 같습니다 🙇

2023-04-13 01:24 UTC, neojjc2 commented
#tag @neojjc2

2023-04-13 02:15 UTC, neojjc2 requested changes
안녕하세요 윤재님 😄 

3단계 진행 잘 해 주셨네요
제가 슬랙을 재설치 했는데 뭔가 알람이 꺼져있었나봅니다
리뷰가 늦은점 죄송합니다 🙇 

몇 가지 의견 드렸는데요
한번 보시고 개선검토 해주시면 좋을 것 같습니다 😄 

방향 잡기가 어려우시다면 언제든 DM 주세요 🙇 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙇

2023-04-13 02:15 UTC, neojjc2 commented on src/main/java/main.java
> +public class main {
```suggestion
public class Main {
```

2023-04-13 02:15 UTC, neojjc2 commented on src/main/java/main.java
> +        StringBuffer[] currentCar = new StringBuffer[carNumber];
일단 먼저 `main`에 만 있는 기능에 대한 역할과 책임을 적절하게 분리하는 작업부터 개선되면 좋을 것 같습니다 😄 
지금은 `main` 이라는 `function`안에 모든 기능들이 수행 되어있고 
절차지향적으로 구조가 잡혀있는데요 😄 

(예가 적절하지 않을 수도 있는데) 제가 닌텐도 같은 게임기를 만들고 있는데 
그 중에 윤재님이 만드신 자동차 경주 게임을 제 `main`에서 호출해서 실행시키고 싶습니다 
그리고 경주를 진행하는 룰도 좀 다양하게 가져가고 싶고요 😄 

그런 관점에서 기존에 있는 구조를 어떻게 개선할 지 
한번 고민해주시면 좋을 것 같습니다 🙏

2023-04-16 14:21 UTC, yoonjaej3 commented
안녕하세요 준철님 
말씀하신대로 절차지향적보다는 객체지향적으로 코드를 짯는데 리뷰한번 부탁드릴게요
테스트 코드는 아직 제 코드에 수정이 많이 일어날거같아서 작성하지 않았어요

2023-04-17 00:29 UTC, neojjc2 approved these changes
안녕하세요 윤재님 😄 

그래도 많이 개선해 주셨네요 💯 
고민의 흔적이 느껴집니다 👍 

조금만 더 정리되면 좋을 것 같아서 
의견 드렸는데요 
요건 다음 단계 진행하시면 자연스럽게 필요성을 아실 것 같아서 
다음 단계 하시면서 같이 고민해주시면 좋을 것 같습니다 
그리고 이번 단계에서 빠진 테스트도 같이 챙겨주세요 😄 🙏 

요청사항 반영해주시느라 고생많으셨습니다

이만 `merge` 하겠습니다 🙏

2023-04-17 00:29 UTC, neojjc2 commented on src/main/java/RacingCar/Car.java
> +    public String move(int num) {
그래도 많은 개선을 해주신 덕에 이전 구조보다는 한결 나아졌습니다 😄 

다만 이 부분은 조금만 더 개선되면 좋을 것 같습니다 
지금은 외부 값에 의해서 `Car`의 가장 중요한 (레이싱에서도 가장 중요한) `location` 값을 변경할 수 있습니다 

꼴지를 하던 `Car`가 임의로 혹은 잘못된 `Car`의 사용으로 값을 변경하게 한다면
`Car`객체의 가장 중요한 데이터에 값에 대한 무결성이 깨질 수 있습니다 

```java
car.move(getRandomNumber(10)); // 이렇게 사용하는게 아닌
car.move(1_000_000); // 누군가 이렇게 사용하거나, Car객체를 사용하는 다른 객채에서 이와같이 호출 하는 경우 
```

이 부분에 대해서 조금만 더 개선되면 문제 없을 것 같습니다 😄

2023-04-17 00:29 UTC, neojjc2 commented on src/main/java/RacingCar/Car.java
> +            location += "-";
`Car`의 `location`과 출력에 대한 `formatting`이 같이 섞여 있네요 😄 
이렇게 되면 나중에 `Car`의 `location`정보만 필요하다거나 출력 `formatting`이 변경 될 경우 (지금은 `-`이지만 `*`이나 공백 등의)
계속적으로 수정이 발생할 수 밖에 없는 부분이기도 합니다 
요 부분도 한번 더 고민해주시면 감사하겠습니다 🙏

2023-04-17 00:30 UTC, merged