Step3 자동차경주게임
next-step/java-racingcar pull request #4426
Opened 2023-04-12 09:51 UTC by lovepizza132

리뷰어님 이렇게 하는게 맞는것인지 잘 모르겠습니다...

물경력으로 아는게 정말 없습니다... 그러니 과감하게 말씀해주세요!
정말 발전하고 싶습니다.
리뷰 해주시면 피드백 성실하게 반영하겠습니다.

감사합니다.

2023-04-14 00:03 UTC, csh0034 requested changes
3단계 잘 구현 해주셨네요 😄 
리뷰드린 내용 확인해주시고 다시 요청부탁드려요!

2023-04-16 06:21 UTC, csh0034 approved these changes
3단계 잘 진행해주셨네요 👍 

몇가지 코멘트 남겨두었는데 다음 단계와 함께 
진행해주시면 될 것 같아 머지하겠습니다.

다음단계에서 뵙겠습니다. 😄

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/domain/Racing.java
> +  public static MoveStrategy defaultRacingMoveStrategy() {
전략의 경우 외부에서 주입받는 형태(startRacingRound 메서드의 파라미터)로 해보시면 좋을것 같아요.

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/domain/RacingCars.java
> +  private RacingCar[] racingCars;
배열보단 컬렉션을 사용할경우 다양한 메서드와 stream api 를 사용할수 있는 장점이 있습니다. 🙂

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/domain/Racing.java
> +    for (RacingCar racingCar : this.racing.statusOfRacingCars()) {
RacingCars 의 필드명이 racing 이네요! 헷갈릴수있을것 같습니다.
cars 정도가 좋을것 같아요.

추가로 RacingCars 의 내부값을 꺼내와서 하는것이 아닌 racing.tryToMove 와 같이 메세지를 보내보면 좋을것 같습니다.

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/domain/RacingCar.java
> +  public RacingCar() {
디폴트생성자는 다른 생성자가 없을경우 자동으로 생성되므로 제거해주세요!
리팩토링과정에서 남아있는것같네요~ 🤔

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/repository/MoveStrategy.java
> +public interface MoveStrategy {
전략 잘 추가해주셨네요! 

움직임에 대한 전략이기 때문에 움직일지말지 (decideMoveOrHold) 에 대한 처리만 해주고 
실제 얼마큼 움직일지는 자동차가 판단해보는것도 좋을것 같습니다.

추가로 `@FunctionalInterface` 로 적용해보시면 좋을것 같아요!

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/repository/CarInterface.java
> +public interface CarInterface {
구현체가 반드시 하나인데 인터페이스가 꼭 필요한걸까요?🤔

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/repository/CarInterface.java
> +package racingcar.repository;
repository 는 영속계층, 즉 데이터를 저장하는 layer 의 대한 패키지명으로 주로 쓰입니다.

이경우 CarInterface 및 상수 클래스를 제거후 strategy 와 같은 패키지명으로 해보면좋을것같아요!

2023-04-16 06:21 UTC, csh0034 commented on src/main/java/racingcar/repository/ConstantMoveFactors.java
> +public final class ConstantMoveFactors {
이번과정에서 최대한 상수클래스를 안두는것을 추천드립니다 🙂

각 역할에 맞는 클래스를 분리했다면 해당값을 처리하고있는 클래스에 상수를 두는것이
더 자연스럽게 읽힐수 있을것 같아요!

2023-04-16 06:21 UTC, csh0034 commented on build.gradle
> +    implementation 'org.jetbrains:annotations:20.1.0'
해당의존성을 추가해주신 이유가 있으실까요? 🤔

2023-04-16 06:21 UTC, csh0034 commented on src/test/java/racingcar/RacingCarTest.java
> +public class RacingCarTest {
각 도메인으로 분리해주신 단위로 테스트 코드 작성해주세요!

RacingCarTest, RacingCarsTest, RandomNumberTest ...

2023-04-16 06:22 UTC, merged

2023-04-16 10:57 UTC, lovepizza132 commented on build.gradle
> +    implementation 'org.jetbrains:annotations:20.1.0'
저도 왜들어갔는지 몰라서 삭제했습니다!

2023-04-16 11:45 UTC, lovepizza132 commented on src/main/java/racingcar/domain/RacingCars.java
> +  private RacingCar[] racingCars;
말씀해주셔서 인지했었는데 깜빡한 것 같습니다. 다시 피드백 주셔서 이번에는 적용했습니다!

2023-04-16 11:46 UTC, lovepizza132 commented on src/main/java/racingcar/repository/CarInterface.java
> +package racingcar.repository;
디테일한 피드백 감사합니다.

2023-04-16 11:48 UTC, lovepizza132 commented on src/main/java/racingcar/repository/CarInterface.java
> +public interface CarInterface {
ㅜㅜ 사실 한번 사용해보고 싶은 마음이 커서 써보긴 했습니다ㅜㅜ
혹시 방법이 틀린것은 아니죠? 
이렇게 리뷰를 받을 수 있을 때 피드백을 받아서 더 나은 상황에 적절하게 이용하는 법을 배우고자 그랬습니다!

2023-04-16 11:49 UTC, lovepizza132 commented on src/main/java/racingcar/repository/ConstantMoveFactors.java
> +public final class ConstantMoveFactors {
감사합니다. 리뷰어님! 
위에 적은 인터페이스와 마찬가지로 어느 상황에 상수 클래스를 써야하는지 피드백을 받고싶어서 억지(?)로 사용해본것도 있습니다! 
그런데 이렇게 디테일하게 피드백주시고 정말 감사합니다.

2023-04-17 04:04 UTC, csh0034 commented on src/main/java/racingcar/repository/CarInterface.java
> +public interface CarInterface {
구현체가 반드시 하나라면 꼭추가되지 않아도 될것 같습니다 😄