Step3
next-step/java-racingcar pull request #4436
Opened 2023-04-12 13:07 UTC by Ryeoung

작업 현황
1. step 2 피드백 반영
2. step 3 자동차 경주 과제 수행

슬랙으로 궁금한 점을 메세지로 보냈었는 데 상세한 답변 감사드립니다.!!!!!!

2023-04-13 12:22 UTC, parkeeseul requested changes
3단계 미션 잘 진행해 주셨네요 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다
화이팅 입니다 🔥

2023-04-13 12:22 UTC, parkeeseul commented on src/test/java/study/step3/CarTest.java
> +  }
car.move() 는 랜덤 로직을 포함하고 있기 때문에, 해당 테스트는 랜덤에 대한 테스트라고 볼 수 있을 것 같아요
랜덤이라는 요소는 일반적으로 테스트하지 않는데요. 이유는 랜덤 자체가 어떠한 규칙을 가지지 않기 때문입니다.
Car를 테스트 가능하도록 개선해 보면 어떨까요? 😄

2023-04-13 12:22 UTC, parkeeseul commented on src/main/java/study/domain/racingGame/CarCondition.java
> +  private final int MAX_NUM = 9;
상수는 다음과 같이 static 을 선언해 주면 어떨까요? 😄 
```suggestion
public class CarCondition {
  private static final int MIN_NUM = 4;
  private static final int MAX_NUM = 9;
```

2023-04-18 00:31 UTC, Ryeoung commented on src/main/java/study/domain/racingGame/CarCondition.java
> +  }
답변이 늦어져서 죄송합니다. 
테스트를 위해 접근 수준을 올렸는 데 그렇게하면 OOP에 맞지 않아서 private으로 변경하겠습니다.

2023-04-18 00:36 UTC, Ryeoung commented on src/test/java/study/domain/racingGame/CarCondition.java
> +    return num >= MIN_NUM && num <= MAX_NUM;
조건을 명확하게 주는 게 불필요한 행동일까요 ??? ㅠㅠ

2023-04-18 00:40 UTC, Ryeoung commented on src/test/java/study/domain/racingGame/Cars.java
> +  private List<Car> carList;
자동차 목록을 뜻하는 영어로 CarLIst라고 했는 데 너무 자료형을 뜻하는 것 같으면 변수명도 cars로 바꿔야할까요?

2023-04-18 00:44 UTC, Ryeoung commented on src/main/java/study/domain/racingGame/Car.java
> +  }
getter는 너무 필드의 상태 값이 나와있어서 캡슐화가 잘 안되는 것 같아 주행거리를 구하다라는 느낌으로 find~를 사용했는데 너무 이상할까요?

2023-04-18 00:45 UTC, Ryeoung commented on src/main/java/study/domain/racingGame/CarCondition.java
> +  private final int MAX_NUM = 9;
넵 값이 고정되어있어서 객체를 생성할 때마다 메모리를 사용하는 것는 불필요한 내용이네요 static으로 수정하도록 하겠습니다.

2023-04-18 01:10 UTC, Ryeoung commented on src/test/java/study/step3/CarTest.java
> +  }
넵 move의 매개 변수로 받아서 move 테스트가 가능하도록 하겠습니다.

2023-04-19 04:14 UTC, Ryeoung commented on src/test/java/study/domain/racingGame/CarCondition.java
> +    return num >= MIN_NUM && num <= MAX_NUM;
만약 랜덤값이 0 ~ 20으로 분리될 때  max_num 도 변경해야되니 분리되는 게 더 좋아보이네요 상세한 설명 감사드립니다.!!!

2023-04-20 14:14 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요 😄 
소소한 추가 코멘트 남겨 두었으니 확인 부탁드리고
추가적인 수정 사항은 다음 단계와 함께 반영 부탁드립니다.
다음 미션 진행해 주세요

2023-04-20 14:14 UTC, merged