4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #4439
Opened 2023-04-12 13:52 UTC by Saerang

winner 테스트코드 만들기가 어려워져서 car 에 position 을 받을 수 있는 구조로 변경을 해야할 것 같은데,
5단계에서 하면 좋을까요? 아니면 4단계에서 수정하고 넘어가면 좋을까요?

2023-04-13 00:18 UTC, Hyeon9mak requested changes
안녕하세요 석균님, 4단계 고생 많으셨습니다.
3단계를 잘 만들어주셨기 때문에 큰 변화없이 4단계가 충족 된 것 같아요! 👍 

car 에서 position 을 받는 방법은 car 생성자의 접근제한 수준을 손보면 쉽게 해결될 것 같은데요? 😉 
생성자를 일반적인 메서드와 다르게 생각해주시면 좋겠어요.

조금 더 고민해보면 좋을 포인트 리뷰 남겼습니다!
궁금하신 점 DM, 코멘트 남겨주세요 🙇‍♂️

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/README.md
> +- [x] 4미만인 경우 움직이지 않는다.
체크 리스트 활용 좋습니다 👍

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Cars.java
> +    }
동료 개발자가 "이름 구분 기준을 `,` 에서 `|` 로 바꿔주세요." 라는 요구사항을 접하면 domain 과 view 중 어떤 패키지를 먼저 열어보게 될까요?
`,` 로 이름을 구분한다는 것을 꼭 자동차 경주에서 해결해야할까요?

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Position.java
> +            throw new IllegalArgumentException("0 에서 9 사이 숫자만 이동 가능합니다. 입력숫자:" + number);
비즈니스에 핏한 메세지! 👍

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Position.java
> +    }
- `compareTo` 덕분에 비교가 용이하겠네요! 👍 
- `toString` 을 오버라이딩 한 이유가 있을까요?

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Winner.java
> +    }
필드멤버와 생성자 사이에 개행이 들어가면 가독성이 조금 더 좋아질 것 같아요 😉

2023-04-13 00:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Winner.java
> +    }
`Cars` 일급 컬렉션에게 "너희들 중 가장 높은 포지션을 가져와봐" 메세지를 보낼 수도 있겠네요 😉 

> 객체에 메세지를 보내라

2023-04-13 00:30 UTC, Saerang commented on src/main/java/racingcar/domain/Position.java
> +    }
테스트코드에서 Postion 값을 보려고 toString을 오버라이딩 했었습니다.

2023-04-13 00:51 UTC, Saerang commented
Cars에도 아래와 같은 생성자가 추가가 되고, Car 에서 생성자의 접근 제한 수준을 올리게 되어야 테스트가 용이해지는데, 테스트 코드를 위한 생성자 수준을 올리게 되는게 괜찮다고 보시는건가요? 

```
Cars(String names, List<Position> positions) 
```

2023-04-14 01:50 UTC, Hyeon9mak approved these changes
안녕하세요 석균님
질문주신 내용에 대해서는 DM 으로 주고 받은 메세지로 대체하겠습니다 🙇‍♂️ 

> 네 저는 그렇게 생각중이에요.
결국 객체에게 기대하는 것은 그 객체가 어떠한 동작을 수행하고 어떠한 책임(수정할 이유)를 가지는지 일텐데요,
생성자는 메서드와 달리 동작수행, 책임과는 거리가 멀어서 접근제한 설정이 비교적 자유롭다고 생각합니다.

> 테스트만을 위한 생성자가 만들어지는 것에 대해서도 역시나 OK 라고 생각합니다.
그 근거는 생성자를 정말 단순하게 객체를 생성하는 방법, 게이트웨이 정도로만 생각하기 때문이에요.
결국 저희가 테스트를 통해 확인하고 싶은 것은 "이 로직이 성공적으로 수행될 것인가?" 일뿐, 객체가 생성되는 과정은 아니죠!!
생성자에 검증 로직을 넣고 생성자를 테스트할 때도, 생성자를 테스트 한다기보다 생성자 내부 검증 로직을 테스트 하기 위이고,
생성자는 여전히 객체를 생성하는 동작만 수행하겠구요.

마지막 단계를 진행하시면서 `Cars` 생성자에 대한 부분 고민해주세요!

2023-04-14 01:50 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Cars.java
>      }
`Cars` 의 생성자를 유연하게 두는 것의 장점도 있지만,
어떻게 분리할지 내부에서 알고 있거나 파라미터로 전달 받는 것에 대해서는 view 에 의존적으로 느껴져요 😢 

가령 자동차 경주 게임 규칙에는 아무 변화가 없는 상태에서 콘솔이 아닌 웹 이미지로 입/출력 방식이 변경된다면
view 에 대한 변화만 반영하기 위해 domain, view 패키지를 나누어주셨을텐데요,
현재 구조에서는 domain 패키지에도 변화가 발생할 것 같아요 😱

2023-04-14 01:51 UTC, merged

2023-04-14 01:51 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Cars.java
> +    }
https://github.com/next-step/java-racingcar/pull/4439#discussion_r1166190039 답변입니다!