Step3
next-step/java-racingcar pull request #4492
Opened 2023-04-15 13:47 UTC by std-freejia

안녕하세요 이동규 리뷰어님. 

3단계에서는 단계마다 테스트코드를 어떻게 짜야 할지 막막한 부분이 있었습니다. 
scanner 로 입력받는 '자동차 대수와 게임 시도 횟수' 를 테스트코드에 넣는 과정이 어려웠습니다. 

그리고 RacingGame 클래스의 playGame 메서드를 구현했는데요. 
해당 함수에서 자동차리스트를 이동시키고, 결과 출력하는 내용이 있습니다. 
결과 출력하는 로직은 RacingGame 클래스에서 빼내고 싶은데요. 그러려면 List<Car> cars 변수를 밖으로 노출시켜야 합니다. 
제가 원하는 대로 리팩토링 하려면 어떻게 해야 할지 궁금합니다. 

위 2가지 고민에 대해 팁을 부탁드려도 될까요 ? 

항상 감사합니다.

2023-04-15 19:39 UTC, brainbackdoor requested changes
3단계 미션 진행하느라 고생하셨어요~ 
질문주신 부분들에 대한 답변은 Comment로 갈음할 수 있을거 같아요.
확인해보시고 추가로 궁금한 점 있으시면 DM 주세요~
주일 잘 보내세요! 🙏🏻

2023-04-15 19:39 UTC, brainbackdoor commented on src/main/java/racing/Car.java
> +    static private int makeRandomPower() {
```suggestion
   private int makeRandomPower() {
```

2023-04-15 19:39 UTC, brainbackdoor commented on src/main/java/racing/Car.java
> +        return (randomPower >= 4) ? randomPower : 0;
- 값을 하드코딩하기보다는 상수로 관리하는 것이 유지보수하기에 좋다고 생각합니다. 상수(static final)를 만들고 이름을 부여하면 이 변수의 역할이 무엇인지 의도를 드러내기에 좋다고 생각합니다.
- 랜덤 로직이 move() 메소드 내에 있으면 테스트하기 어렵지 않을까요?

2023-04-15 19:39 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +    }
- RacingGame이 InputView를 의존하고 있군요. InputView로 받은 countOfCar, turn를 인자로 받도록 구성하는 것은 어떨까요?
- 테스트코드 기반으로 프러덕션 코드를 작성하다보니 main 메소드를 구현하지 않으셨군요. 그러다보니 Scanner로 입력 받는 부분을 테스트코드에 넣는 부분에서 고민점이 생기셨군요. 정적팩토리 메소드에서 Scanner에 대한 의존성을 제거한다면 테스트코드 작성에 어려움이 없을듯합니다.

2023-04-15 19:39 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +        ResultView.printCarsLocation(this.cars);
이 부분도 마찬가지입니다. 도메인 모델과 Presentation Layer 를 분리해보세요.
만약, 현재 자동차게임을 웹 서비스로 변경한다면 RacingGame에서 어떤 부분을 수정하게 될까를 한번 생각해보세요.
그러려면 질문하신대로 `List<Car>`를 노출해야 하지 않을까 생각하실 수도 있지만, (물론 지금처럼 작은 애플리케이션은 그렇게 해도 무방합니다)
GameResult와 같은 값 객체를 만들어 응답할 수도 있을거에요.

2023-04-15 19:39 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +    }
- 값을 꺼내서 처리하지 말고, Cars 와 같은 일급컬렉션을 작성하는건 어떨까요?

2023-04-15 19:39 UTC, brainbackdoor commented on src/test/java/racing/RacingGameTest.java
> +}
위 피드백 반영 후 테스트코드를 다시 작성해보세요~

2023-04-16 13:42 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +        ResultView.printCarsLocation(this.cars);
MVC 모델을 떠올리며 각 클래스들을 view, service, dto 패키지 등으로 분리하여 반영했습니다.

2023-04-16 14:14 UTC, std-freejia commented on src/main/java/racing/Car.java
> +        return (randomPower >= 4) ? randomPower : 0;
랜덤 값을 만드는 메서드를 유틸 클래스로 빼는 식으로 수정해봤습니다

2023-04-16 14:15 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +    }
Scanner 로 초기 파라미터를 입력받는 InputView 클래스를 main 메서드에서 호출하는 식으로 반영했습니다.

2023-04-16 14:19 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +    }
안녕하세요 리뷰어님. 리뷰 주신 내용 반영하려고 노력했습니다. 

필드를 하나만 가지고 컬렉션을 래핑한 일급컬렉션을 Cars 클래스 구현으로 반영해봤습니다. 
비즈니스 로직을 분리한다는 점이 장점이라고 하는데, 단점은 뭐가 있는지 설명해주실 수 있을까요?

여기서 값을 꺼내서 처리한다는게 this.cars.get(i)를 사용하지 말자는 피드백인지 궁금합니다.

2023-04-16 14:22 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +    }
Cars 컬렉션 내부에서 '게임 한 번 시도' 했을 때 모든 자동차들을 랜덤 값 만큼 이동시키는 로직을 포함했습니다. 

반복문 내에서 각 자동차가 움직이는 move() 를 호출하고 onceResult 에는 길이 int를 저장합니다. 

뭔가 짜면서도 찜찜한데요.. 이 부분 패드백 부탁드리고 싶습니다. 

`public GameResult playOnceTurn() {
        List<Integer> onceResult = new ArrayList<>();

        for (int i = 0; i < cars.size(); i++) {
            this.cars.get(i).move(RandomInt.getPossibleInt());
            onceResult.add(this.cars.get(i).getLocation());
        }
        return new GameResult(onceResult);
    }`

main 메서드에서 모든 게임 시도에 대한 자동차들의 위치를 List로 모으다 보니깐 GameResult 리스트를 리턴시켜서 출력하게 되었습니다. 
3중 for 문 느낌의 ResultView 클래스가 되어서 찜찜합니다.

2023-04-17 17:34 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +    }
음.. 질문은 Cars 객체의 playOnceTurn 메소드 코드에 대한 피드백과 3중 for 문 형태가 된 ResultView 에 대한 피드백이군요.

1. playOnceTurn()에 대하여..
우선, 찜찜하다고 하신 이유를 좀 더 구체적으로 작성해주셔야 답변하기가 수월할듯합니다. 
그냥 코드 보고 피드백을 남기자면..
현재 코드의 경우, Stream API를 활용하는게 가독성이 좋아 보입니다. 매번 값을 꺼내서 처리하는 형태의 코드보다는 객체에 메시지를 보내는 형태를 선호합니다. 

```java
    public GameResult playOnceTurn() {
        List<Integer> onceResult = this.cars.stream()
                .map(car -> car.move(RandomInt.getPossibleInt()))
                .map(Car::getLocation)
                .collect(Collectors.toList());
        return new GameResult(onceResult);
    }
```

다만, Cars 객체가 RandomInt를 직접 의존하고 있는 것이 적절한지, 그리고 이럴 경우 playOnceTurn() 메소드를 테스트하기 어렵다는 생각이 드는데요.
위 Comment에서도 이야기했듯 외부에서 주입하는 것은 어떨까요

```java
    public GameResult playOnceTurn(GameRule rule) {
        return new GameResult(this.cars.stream()
                .map(car -> car.move(rule.apply()))
                .map(Car::getLocation)
                .collect(Collectors.toList()));
    }
```


2. String의 repeat 함수를 사용한다면, 코드상에서 for문을 숨길 수 있지 않을까요 (if 문이든, for문이든 숨길 뿐이지 로직 자체를 없앨 수는 없습니다.)

```java
    public static void printGameResults(List<GameResult> results) {
        results.forEach(v -> printOnceTurn(v.getResult()));
        printNewLine();
    }

    private static void printOnceTurn(List<Integer> phase) {
        phase.forEach(v -> System.out.println(CAR.repeat(v)));
        printNewLine();
    }

    private static void printNewLine() {
        System.out.print("\n");
    }
```

2023-04-17 17:41 UTC, brainbackdoor commented
음.. 기능 요구사항을 오해하신거 같아요.
`전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.`
즉, 0~9 사이의 랜덤 값을 우선 구해야 합니다.
그리고 그 값이 4이상 일 경우에 1칸 이동합니다.


현재  RandomInt.makeRandomInt() 는 0 ~ 7 까지의 랜덤 값을 구합니다. 
그리고 getPossibleInt()은 랜덤값이 4미만이면 0을 응답, 그게 아니라면 랜덤값을 그대로 응답합니다.

2023-04-17 17:42 UTC, brainbackdoor requested changes
피드백 반영하시느라 고생하셨어요~ 
질문주신 부분과 추가 피드백 남겨두었는데요. 
기능 요구사항을 일부 오해하신거 같아 Request Changes 했어요.
확인해보고 반영 부탁드려요~ 
좋은 밤 보내세요~

2023-04-17 17:45 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +        ResultView.printCarsLocation(this.cars);
패키지도 하나의 추상이라고 생각합니다.
현재 구조에서는 service 등의 패키지가 도출될 필요는 없다고 생각해요.
혹시 Service Layer에는 어떤 객체들이 위치해야 할까요?

2023-04-17 17:50 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +    }
일급컬렉션도 결국 하나의 wrapper class 입니다. 객체를 도출시킬 때는 그 나름의 역할과 책임이 분명해야 하는데요.
그렇지 않다면, 불필요한 클래스 파일들이 많아지게 됩니다.
위 케이스에서는 Car 객체들의 move를 모두 수행시켜야 하는 경우가 발생하는데요. 
RacingGame 객체에서 이를 수행한 후 result에 추가하는 것까지 모두 맡길지 Cars 객체를 도출하여 메시지를 보내는게 나을지는 프로그래머의 판단입니다. 
저는 Cars 객체를 도출하는 것이 현재 playOnceTurn() 메소드 기능에 대한 테스트를 작성하기 더 용이하다고 생각해요.

2023-04-18 13:14 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +    }
GameResult class를 삭제하고, Cars 일급컬렉션을 활용하도록 수정했습니다.

2023-04-18 13:41 UTC, std-freejia commented on src/main/java/racing/RacingGame.java
> +    }
stream API 다루는 연습을 해보겠습니다. 감사합니다.

2023-04-18 18:59 UTC, brainbackdoor commented on src/main/java/racing/Car.java
> +        return (randomPower >= 4) ? randomPower : 0;
이와 관련해서 뼈대코드도 추가해두었는데요. 이 부분 이해가 안가시더라도 5단계 미션 진행하면서 경험하실 수 있으니, 지금은 그냥 지나가도 좋을듯합니다.

> https://github.com/next-step/java-racingcar/pull/4492#discussion_r1169066010

2023-04-18 19:12 UTC, brainbackdoor commented on src/main/java/racing/RacingGame.java
> +        ResultView.printCarsLocation(this.cars);
음.. 위에서 말씀드렸듯이 자동차 경주 애플리케이션에서는 service와 같은 패키지는 도출될 필요가 없다고 생각해요.
Car, Cars, GameResult 등은 domain layer에 위치한다고 생각하구요.
우리가 계층형 아키텍쳐에서 사용하는 용어들 (service, repository 등), 그리고 스프링의 각 종 애노테이션 (`@Service, @Reository 등`) 도 각각 역할이 있는데요. 가령, `@Service`의 경우 주석을 보면 DDD에서 영감을 얻었고, Business Service Facade 의 일종이라고 이야기합니다.
즉, 서브시스템을 사용하기 쉽도록 만든 인터페이스 역할을 한다는 의미인데요. 그러다 보니 다른 domain layer들 간의 제어나 트랜잭션 관리 등이 이 곳에서 이루어집니다.
현재 자동차게임의 경우, 규모가 작아서 하나의 도메인으로 이루어져있다고 봐도 무방하다고 생각되어서 service 란 이름을 가진 패키지를 두는 것은 좀 어색하다고 생각하여 남긴 피드백이에요.

```
ndicates that an annotated class is a "Service", originally defined by Domain-Driven Design (Evans, 2003) as "an operation offered as an interface that stands alone in the model, with no encapsulated state."
May also indicate that a class is a "Business Service Facade" (in the Core J2EE patterns sense), or something similar. This annotation is a general-purpose stereotype and individual teams may narrow their semantics and use as appropriate.
```

2023-04-18 19:18 UTC, brainbackdoor commented on src/main/java/racing/domain/Cars.java
> +            int randomNumber = randomGameRule.getPossibleInt();
```java
public interface GameRule {
    int apply();
}
```

지난번에 드렸던 피드백은 위와 같은 인터페이스를 도출한 후, playOnceTurn() 메소드가 인터페이스를 의존하도록 구성하라는 의미였어요.
그리고 외부에서 GameRule의 구현체인 RandomGameRule과 같은 객체를 주입하도록요.
그러면 테스트 코드에서는 RandomGameRule가 아닌 별도의 클래스 (가령, MustGoGameRule)과 같은 클래스를 주입하면 테스트하기가 용이해지겠지요.

2023-04-18 19:20 UTC, brainbackdoor approved these changes
피드백 반영하시느라 고생하셨어요~ 
이번 단계에서 달성하고자 하는 목표는 이룬듯 하여 여기서 머지할게요~
추가적인 고민점들은 다음 단계 미션 진행하면서 해결해봐요~
좋은 하루 보내세요 🙏🏻

2023-04-18 19:20 UTC, merged