Step3
next-step/java-racingcar pull request #4497
Opened 2023-04-16 02:00 UTC by foameraserblue

안녕하세요 리뷰어님~ 토요일 밤에 DM 드려서 죄송합니다.
리뷰어님도 바쁘셨을텐데 이번주 평일에 일이많아서 부득이하게 주말에 디엠까지 드리면서 과제했습니다 다음부턴 평일에도 과제 열심히 하겠습니다!

이번과제를 하다가 조금 궁금한점이 생겼습니다.
제 코드의 Car 객체의 move 함수를 보시면 아시겠지만 랜덤값을 condition 이라는 변수로 받아서 차를 움직일지 말지 결정합니다.

테스트코드를 쓰다보니 Random.nextInt() 기능을 move 함수 내에서 쓰면 테스트코드 쓰기가 너무 어려워져 이렇게 조건을 파라미터로 받는방식을 취했는데요

결국 이 구조에서는 Random 값 추출 기능을 Racing 객체 내에서 뽑아 할당하게되더라구요

제생각에는 Car 객체는 스스로 움직일지 말지를 결정해야되고
Random 객체와의 의존성은 Car 객체가 가지고있는게 맞지않나? 싶은데요
Random 객체의 위치와 랜덤값을 뽑는 기능은 어떤 객체에 존재하는게 맞을지 의견이 궁금합니다.
감사합니다!

2023-04-16 05:38 UTC, younlll requested changes
안녕하세요.
자동차 미션이 본격적으로 시작되셨네요 🙌

몇 가지 코멘트 남겨드렸습니다.
확인해주시고 다시 리뷰요청 부탁드립니다. 🙏

2023-04-16 05:38 UTC, younlll commented on README.md
> +5. 스코어보드 확인
요구사항 정리 👍

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Car.java
> +    }
기본생성자로 다른 매개변수가 있는 생성자가 없다면 작성하지 않아도 자동 생성이 됩니다.
명시를 해준 이유가 있으신걸까요?

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Racing.java
> +    private final List<Car> racingCars;
여러 대의 자동차를 관리하기 위해 컬렉션을 사용해주셨는데요~
일급 컬렉션을 활용해보는건 어떨까요?
https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Racing.java
> +        final Car[] racingCars = new Car[carCount];
리스트로 만들지 않고 배열로 처음에 선언한 이유가 있으실까요?

2023-04-16 05:38 UTC, younlll commented on src/test/java/step3/CarTest.java
> +    @DisplayName("조건이 4 이상일 경우에만 전진한다")
```suggestion
    @ParameterizedTest(name = "조건이 4 이상일 경우에만 전진한다")
    @CsvSource(value = {"1,0", "2,0", "3,0", "4,1", "5,1", "6,1", "7,1", "8,1", "9,1"})
```

@ParameterizedTest에 displayname입력이 가능합니다!

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
유틸리티 클래스로 보이는데요! 유틸리티 클래스의 인스턴스화를 방지해보는건 어떨까요?
https://suintodev.tistory.com/35?category=1043045

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Car.java
> +        return condition >= 4;
4라는 숫자만 봐서는 무슨 의미인지 알기 어려울 수도 있을 것 같다는 생각이 듭니다.
이와같은 것들을 매직 넘버/매직 리터럴 이라 하는데 의미를 알 수 있도록 상수로 선언해보는 건 어떨까요?

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Car.java
> +    public int currentLocation() {
메서드 명은 보통 동사로 시작하는게 컨벤션입니다!
참고하실 수 있는 링크 남겨드립니다~
https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/

2023-04-16 05:38 UTC, younlll commented on src/main/java/step3/Racing.java
> +    }
이미 Car라는 객체에서 위치라는 상태를 갖고 있음에도 Racing클래스에서 scoreBoard에서 한번 더 관리해주도록 구현하신 이유가 궁금합니🤔

2023-04-16 05:40 UTC, younlll commented
저는 Car가 위치라는 상태는 갖고 있을 수 있지만 움직일지 말지는 Car의 역할이 아니지 않나?라는 생각이 있습니다.
실제에서도 보면 움직임은 운전자가 결정한다고 생각되어서요.
그래서 움직임을 결정해줄 수 있는 별도의 외부 객체를 만들어서 관계를 맺어주는 방향으로 저는 생각해서
이전에 구현했었습니다.

고민하시는 부분에 참고가 되셨으면 좋겠네요 :)

2023-04-16 12:58 UTC, foameraserblue commented on src/main/java/step3/Racing.java
> +    }
문제 조건에 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.
라는 문구가있어서 레이싱을 전부 끝내고 모아진 데이터를 한번에 출력하는 방식으로 구현했습니다.
혹시 조금 과할까요? 바로바로 출력하게도 가능은합니다

2023-04-17 02:22 UTC, younlll commented on src/main/java/step3/Car.java
> +    public int currentLocation() {
아하 제가 이해가 조금 부족했던 것 같습니다.
빌더의 용도로 사용중이시면 맞게 하신 것 같습니다.

2023-04-17 02:23 UTC, younlll commented on src/main/java/step3/Racing.java
> +    }
아하! 저는 정훈님의 의견이 궁금했어서 질문을 드렸던거여서요.
의도가 이해가 잘 되었습니다!!

2023-04-17 02:31 UTC, younlll approved these changes
안녕하세요.
3단계 미션 잘 진행해주셨습니다.
피드백 반영도 잘 해주셨고 제가 궁금했던 부분에 대해
의견도 주셔서 구현의도가 잘 이해되어 좋았습니다 :)

이번 단계는 이만 여기서 머지하도록 하겠습니다.
다음 단계에서 뵙겠습니다 :)

2023-04-17 02:31 UTC, merged