5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #4506
Opened 2023-04-16 09:28 UTC by dkswnkk

안녕하세요 멘토님! 벌써 미션의 마지막이네요.. 🥲 짧지만 많은 것을 배울 수 있었습니다.
마지막 리뷰 잘 부탁드립니다!!

- https://github.com/next-step/java-racingcar/pull/4340
- MoveStrategy 전략 패턴을 사용하여 리팩토링했습니다.
- List<RacingCar> cars; 를 일급 컬렉션으로 묶어서 책임을 분리시켰습니다.

추가로 궁금한 사항은 코멘트로 남겨놓았습니다!!

2023-04-16 09:32 UTC, dkswnkk commented on src/main/java/domain/RacingCarList.java
> +public class RacingCarList {
https://jojoldu.tistory.com/412
일급 컬렉션 관련하여 동욱님의 포스팅을 참고하였는데,
 **Collection을 Wrapping 하면서, 그 외 다른 멤버 변수가 없는 상태를 일급 컬렉션이라 합니다.** 라는 문구 때문에 계속 고민되었습니다. 

```java
    private final List<RacingCar> cars;
    private final MoveStrategy moveStrategy;
```
현재 전략패턴을 추가함으로써 MoveStrategy moveStrategy; 필드로 인해 변수가 두 개인데 문제가 될까요?

2023-04-16 09:41 UTC, dkswnkk commented
현재 ```OutputView.class```에서

```java
    public static void printCarsNameAndPositionStatus(List<RacingCar> cars) {
        for (RacingCar car : cars) {
            printCarNameAndPosition(car);
        }
        System.out.println();
    }

    public static void printWinners(List<RacingCar> winners) {
        String winnerNames = winners.stream()
                .map(RacingCar::getName)
                .collect(Collectors.joining(", "));

        System.out.println("최종 우승자: " + winnerNames);
    }
```

다음과 같이 메서드의 파라미터를 ```List<RacingCar>``` 타입으로 받고 있습니다. 
이번에 리팩토링을 진행하면서 ```RacingCarList```라는 일급 컬렉션으로 묶었는데 해당 ```OutputView.class```의 요 메서드들에서도 파라미터를 ```RacingCarList```로 받아야 할지 궁금합니다! 

```RacingCarList```로 받아버리면 아래처럼
```java
    public static void printCarsNameAndPositionStatus(RacingCarList cars) {
        for (RacingCar car : cars.getCars()) {
            printCarNameAndPosition(car);
        }
        System.out.println();
    }

    public static void printWinners(RacingCarList winners) {
        String winnerNames = winners.getWinners().stream()
                .map(RacingCar::getName)
                .collect(Collectors.joining(", "));

        System.out.println("최종 우승자: " + winnerNames);
    }
```
각 메서드 로직에서 ```RacingCarList```의 ```List<RacingCar>```를 꺼내기 위해 ```get()```이 추가되어야 하다 보니 고민이 되었습니다!

2023-04-18 03:10 UTC, serverwizard requested changes
자동차 미션 5단계를 잘 구현해주셨네요. 💯👍

소소한 코멘트 몇 개 남겼는데, 확인해주시면 좋을 것 같아요.
그럼 화이팅입니다.

2023-04-18 03:10 UTC, serverwizard commented on src/main/java/controller/RacingCarController.java
>      public static void main(String[] args) {
메인 메소드만 보고도 흐름이 잘 느껴지네요 👍

2023-04-18 03:10 UTC, serverwizard commented on src/main/java/domain/RacingCarGame.java
> +    public RacingCarList playAndReturnCars() {
playAndReturnCars 메소드 파라미터로  MoveStrategy를 받도록 하면 어떻게 될까요?

2023-04-18 03:10 UTC, serverwizard commented on src/main/java/domain/RacingCarList.java
> +public class RacingCarList {
일급 컬렉션이란 학습하신대로 `Collection을 Wrapping 하면서, 그 외 다른 멤버 변수가 없는 상태`를 의미하는대요.
이를 위해 racingCarGame.playAndReturnCars 메소드 파라미터로 MoveStrategy를 받도록 하면 이를 해결할 수 있을 것 같아요.

참고로, MoveStrategy moveStrategy를 필드로 가지는 게 문제라기 보단 MoveStrategy moveStrategy를 필드로 꼭 가져야만 하는지를 고민해보셨으면 해요.

2023-04-18 13:19 UTC, dkswnkk commented on src/main/java/domain/RacingCarList.java
> +public class RacingCarList {
왜 파라미터로 받을 생각을 못 했을까요...🥲 피드백 감사합니다 ㅎㅎ

2023-04-19 13:17 UTC, serverwizard approved these changes
자동차 5단계 미션 잘 구현해주셨네요. 💯👍

PR 보내실 때마다 코드가 깔끔해지는 걸 느낄 수 있어 좋았습니다.
그럼 마지막까지 화이팅입니다. 🔥

2023-04-19 13:17 UTC, serverwizard commented on src/main/java/controller/RacingCarController.java
> +            RacingCarList cars = racingCarGame.playAndReturnCars(new RandomMoveStrategy());
깔끔하네요 👍

2023-04-19 13:17 UTC, serverwizard commented on src/main/java/domain/RacingCar.java
> +    public void moveForward(MoveStrategy moveStrategy) {
👍

2023-04-19 13:17 UTC, merged