[Step3] 3단계 - 자동차 경주
next-step/java-racingcar pull request #4520
Opened 2023-04-16 14:18 UTC by Ojeegu

### 고민 및 질문사항
- dirve() 메서드의 테스트 코드를 작성할 때 willMovint(number) 조건이 true인 경우에만 해당 carList에 "-" 문자열을 추가했는지 확인하는 방법을 사용하였습니다. 테스트코드에서는 모두 성공이 나왔는데, 나중에 실행해보니 number 변수가 각 car마다 변하지 않고 동일하게 적용되어 모든 자동차가 동일한 이동 패턴을 갖는다는 것을 확인하였습니다. 이런 경우에는 테스트 코드를 어떻게 더 자세히 짤 수 있을까요? 테스트 코드만으로 모든 실수를 잡아낼 수 없다는 걸 알지만 어느정도까지 세세하게 짜야하는 지 잘 모르겠습니다.

### 지난 피드백
- 이번에는 최대한 다른 사람의 것을 보지 않고 구글로 개념만 취합하여 제가 짜보는 식으로 진행하였습니다.
- int[] 배열을 List<Integer>로 수정하였습니다.

이번 리뷰도 잘 부탁드립니다. 감사합니다. 😀

2023-04-17 11:58 UTC, wheejuni requested changes
수고 많으셨습니다. 🙇 
몇 가지 의견 드립니다. 참고해주시면 감사하겠습니다.

2023-04-17 11:58 UTC, wheejuni commented on src/main/java/step3/view/OutputView.java
> +        System.out.print(sb);
다른 sysout과의 간섭을 예방하기 위해, 항상 `.println()` 을 사용하시는 것을 추천합니다.
둘 사이의 차이에 대해서 학습해 보셔도 좋겠습니다.

2023-04-17 11:58 UTC, wheejuni commented on src/main/java/step3/domain/CarOperator.java
> +                car.getMovingList().add(CAR_MOVED);
몇 가지 개선이 필요합니다.

1. `Car` 에게 생성된 숫자를 알려주면 자동차가 알아서 가게 하는 구조가 되었으면 합니다. 자동차는 원래 스스로 굴러가야겠죠?
2. `movingList` 를 get 해서 그 안의 원소를 바꾸고 있습니다. 데메테르의 법칙 위반입니다.
3. `Car` 의 위치는 숫자로 표현되어야 하지 않을까요? `CAR_MOVED` 는 위치에 대한 표현(presentation) 일 것 같은데요? 현재 위치를 문자열로, 그것도 문자열 리스트로 보관하는 것.. 괜찮을까요?

2023-04-17 11:58 UTC, wheejuni commented on src/main/java/step3/domain/Car.java
> +    private final List<String> movingList;
아래 코멘트 참고 부탁 드립니다!

2023-04-17 11:58 UTC, wheejuni commented on src/main/java/step3/domain/Car.java
> +    public List<String> getMovingList() {
필요한 게터인지요? 이 메소드를 사용하고자 하는 측에선 어떤 정보를 알기 원할까요?

2023-05-12 04:10 UTC, Ojeegu commented on src/main/java/step3/domain/Car.java
> +    public List<String> getMovingList() {
수정 코드에서, getMovingList는 OutputView에게 전달되어 총 n번의 시도 동안 언제 차가 이동했고, 이동하지 않았는지 알 수 있도록 만들었습니다. 해당 정보를 토대로 움직인 경우에는 문자열"-"를 추가하고, 움직이지 않은 경우에는 추가하지 않도록 구현하였습니다.

2023-05-12 04:17 UTC, Ojeegu commented on src/main/java/step3/domain/CarOperator.java
> +                car.getMovingList().add(CAR_MOVED);
1. Car 클래스에 drive 메서드를 추가하고, CarOperator에 있던 willMoving메서드를 Car 클래스로 옮겨서, 랜덤 숫자에 따라 자동차가 직접 움직이도록 수정하였습니다.
2. addMoving 메서드를 만들어서 데메테르 법칙을 준수하도록 수정하였습니다.
3. 각 라운드(시도)마다 차가 움직였는지, 움직이지 않았는지를 0과 1로 나타내도록 수정하였습니다. 이렇게 하는 것이 레이싱에서 좀 더 직관적이라고 생각했는데, 다시 생각해보니 각 라운드마다 현재 위치를 저장하는 것이 나을 것 같다는 생각도 듭니다. 두 방식의 차이가 클까요?

2023-05-12 14:04 UTC, f-lab-scott commented on src/main/java/step3/domain/CarOperator.java
> +                car.getMovingList().add(CAR_MOVED);
@Ojeegu 3에 대해서는... 각 라운드마다 움직일 수 있는 변량이 1이라 보고, 그렇게 움직인 변량들의 합을 `Car` 에서 보관해야 하지 않았나 하는 생각이 들긴 했었습니다.

2023-05-12 14:05 UTC, f-lab-scott approved these changes

2023-05-12 14:06 UTC, merged