Step4 자동차 경주(우승자)
next-step/java-racingcar pull request #4590
Opened 2023-04-19 10:46 UTC by choesoyeong

잘 부탁드립니다.

2023-04-20 11:49 UTC, catsbi requested changes
안녕하세요 소영님. 리뷰가 늦어 죄송합니다 😥
4단계 자동차 경주 우승자 미션 잘 구현해주셨는데, 몇 가지 피드백이 있어 코멘트 남겨드렸으니 확인 후 리뷰요청 부탁드려요.

2023-04-20 11:49 UTC, catsbi commented on README.md
> +  + [X] 각 자동차는 5자 이하의 이름을 가진다.
```suggestion
  [X] 각 자동차는 5자 이하의 이름을 가진다.
  [x] 5글자 이상의 이름을 전달하면 예외를 던진다. 
```

이런식으로 작성하면 테스트코드작성할때도 좀 더 편하겠죠 ㅎㅎ

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/Car.java
>      private MoveStrategy moveStrategy = new FourOverTenMoveStrategy();
자동차가 어떤 전진전략을 가지는지 구현체를 직접 가지고 있으면, 객체지향패러다임(SOLID)중 D(DIP)를 어기게 될 것 같아요. OCP도 어긋나게 될 것 같구요. Default Strategy라고해도 변경가능하기에 외부 주입으로 사용하도록 바꾸는건 어떨까요?

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/Car.java
> +            throw new IllegalArgumentException("Length of the car name has exceeded 5.");
어떤 이름을 전달해서 이런 예외를 던졌는지 클라이언트에게 보여주면 더 좋을 것 같네요 👍

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/CarCollection.java
> +        }
- 반복문안에 분기문이 있다보니 코드의 들여쓰기(indent)가 3이 되버리네요. 2 이하로 줄일 수 없을까요? 
- 한 줄짜리 코드도 블럭`{}` 생략은 지양해주세요.
- Stream API를 활용해봐도 좋을 것 같네요 ㅎㅎ

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/CarCollection.java
> +        return positions;
두 메서드를 하나로 합칠 수 없을까요? Stream API의 map과 max를 써도 될 것 같네요.

좀 더 깊게 생각해보면 car라는 객체는 이동거리로 정렬가능하다는 개념을 가지고 있기에 Car라는 객체가 Comparator를 구현하도록 하면 좀 더 편하게 구할 수 있겠죠

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/CarScore.java
> +    private Integer carPosition;
Wrapper타입을 사용하시는 이유가 있을까요?

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/GameService.java
> +    private List<String> carNames;
Service Layer가 인스턴스 변수를 가져야 할 이유가 있을까요? 
인스턴스 변수가 있다면 동시성이나 힙오염과 같은 신경써야할 부분들이 늘어날 것 같아요. 재사용성도 급격히 떨어지구요. 무상태(stateless) 계층으로 설계해볼 수 없을까요?

2023-04-20 11:49 UTC, catsbi commented on src/main/java/racingcar/GameService.java
> +        return new ScoreBoard(results, winners);
로직을 작성할 때 대입/메서드호출/반환 등 개념적으로 구분되는 영역들을 개행으로 구분하면 가독성을 더 높힐 수 있습니다.

2023-04-20 11:49 UTC, catsbi commented on src/test/java/racingcar/CarTest.java
>  public class CarTest {
현재 설계된 객체에 비해 테스트가 너무 부족한 것 같네요.
TDD(Test Driven Development)가 무엇인지 고민해보고, 실행해보면 좋을 것 같아요. 
기능구현을 해보는게 이번 미션의 목적은 아니니까요 ㅎㅎ 
TDD에 대해 포스팅한 내용이 있으니 참고해보면 좋을 것 같습니다.

[[링크](https://catsbi.oopy.io/b13326d7-7b96-4a33-a974-3024c64eff5f)]

2023-04-26 13:29 UTC, choesoyeong commented
안녕하세요.
격무로 인해 피드백 반영이 늦어졌습니다ㅠㅠ

의견 주신 내용 반영했습니다!
- readme 수정
- Car에서 전진전략 정의하는 부분 제거
- IllegalArgumentException 메시지 변경
- Stream 사용하여 indent 축소
- Car comparable 구현
- carPosition int타입으로 변경
- Game Service에서 carNames, trialNumber 변수 제거

+) 추가로 궁금한 점이 있습니다.
멘토님이 달아주신 코멘트에 제가 몇 개 답글을 달고 있는데 혹시 잘 보이시나요?

2023-04-26 15:04 UTC, catsbi approved these changes
소영님, 4단계 미션 잘 구현해주셨어요. 피드백 반영이 잘 된 것 같습니다 💯 
바로 다음 미션으로 넘어가시죠. MVC패턴이나 객체들의 패키지 구조에 대해서도 같이 고민해보면 좋을 것 같습니다 👏

코멘트 주신것이 이번 4단계 미션을 의미한다면 보이지 않는 것 같습니다. 제가 이메일 알림을 잘 못보고 다른 이메일에 섞여 확인이 늦을 수 있으니 필요하시다면 언제든 편하게 DM주시면 됩니다 ㅎㅎ

2023-04-26 15:04 UTC, catsbi commented on src/main/java/racingcar/Car.java
> +        return Integer.compare(this.position, o.position);
이펙티브자바에서도 기본 라이브러리를 잘활용하는것을 권장합니다. 직접 하나하나 구현하는것보다 유지보수하는 비용이 적게 들죠 ㅎㅎ

2023-04-26 15:04 UTC, merged