#자동차경주 step4 미션 진행 완료입니다.
next-step/java-racingcar pull request #4592
Opened 2023-04-19 11:07 UTC by juno-junho

step 4 미션 진행 완료 했습니다!

2023-04-19 23:35 UTC, ksy90101 commented on src/test/java/study/racingcar/domain/CarNameTest.java
> +    }
이런경우 @parameterizedTest를 진행해보면 어떨까요?
중복코드 제거가 될거 같아요!

2023-04-19 23:38 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/RacingCarGame.java
>  public class RacingCarGame {
View레이어는 한곳에서만 의존을 가지고 있어야 하지 않을까요?
현재 구조가 Controller를 만들었다면 Controller에서 의존을 가지고 있어야 하지 않을까 해요.
차후에 View가 수정되면 의존이 복잡하다면, 수정하기가 어려운듯 하빈다.

2023-04-19 23:40 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/Car.java
>      public String toString() {
View와 관련된 코드가 있으면 안좋은거 같아요.

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

이글을 읽고 toString은 언제 쓰는지 한번 공부해보시면 어떨까요?

2023-04-19 23:44 UTC, ksy90101 requested changes
안녕하세요 :)
전체적으로 구조 및 요구사항을 잘 작성해주시고, 구조를 잘 잡아주셔서 리뷰하기 편했던거 같습니다.
간단한 피드백을 남겼는데, 한번 확인해주시면 감사하겠습니다 :) 
질문이 있다면 언제든 슬랙으로 맨션주세요~

2023-04-19 23:44 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/Result.java
> +    }
position을 이용해 Comapreable을 사용해보면 어떨까요?
그럼 maxPosition을 구할수 있을거라고 생각해요.

stream의 max()라는 메서드를 이용해서 말이죠.

2023-04-19 23:44 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/Result.java
> +    private int maxLength = Integer.MIN_VALUE;
상수화를 시키는게 좋을거 같습니다.

2023-04-20 08:52 UTC, juno-junho commented on src/test/java/study/racingcar/domain/CarNameTest.java
> +    }
넵 수정하겠습니다!

2023-04-21 11:20 UTC, juno-junho commented on src/main/java/study/racingcar/domain/RacingCarGame.java
>  public class RacingCarGame {
그런데 `RacingCarGame`에서 게임을 진행하면서 중간 중간 출력하는 값들은 어떻게 처리해야 할까요..?
`Outputview`와 `RacingCarGame` 사이에 하나의 레이어를 더 만들어야 할까요?
그렇다고 게임을 진행하는 일을 `RacingCarGame` 밖에서 처리해 줄 수도 없고요.. 어떻게 해야 할까요?

2023-04-21 11:56 UTC, juno-junho commented on src/main/java/study/racingcar/domain/Car.java
>      public String toString() {
winner 클래스에서도 toString 사용법이 잘못된것 같아 list에서 꺼내 string으로 변환하는 로직을 view로 뺐습니다!

2023-04-21 13:19 UTC, juno-junho commented on src/main/java/study/racingcar/domain/Result.java
> +    }
max 사용시 compareTo를 통해서 최댓값을 구할 수 있다는 것을 배웠습니다!
Car의 getPosition의 값을 비교해 최댓값을 구할 수 있을 것 같아 comparable 사용 대시 다음과 같이 리펙토링 했습니다.

2023-04-21 13:20 UTC, juno-junho commented on src/main/java/study/racingcar/domain/Result.java
> +    private int maxLength = Integer.MIN_VALUE;
삭제했습니다!

2023-04-21 13:35 UTC, juno-junho reviewed
전체적으로 잘못된 toString을 교정했습니다.
toString은 값을 조작하는 것이 아니라 로그 형태로 해당 객체의 모든 인스턴스 변수를 포함해 출력(로깅)하기 위한 용도로 사용해야 한다는 것을 알았습니다.
그래서 winners 클래스와 Car 클래스에서 toString을 삭제하고, view 로 출력과 관련된 로직들은 모두 분리했습니다.

궁금한 점은 다음과 같습니다.
1. Domain 안은 rule이 변경됨에 따라 코드를 수정하지 않아도 되게끔 Rule 클래스를 만들었는데, 출력과 관련된 rule과 도메인 로직과 관련된 rule을 분리해 DomainRule, OutputViewRule로 분리 시켰습니다. 이것에 대해서는 어떻게 생각하시나요?

2. getter를 사용하는 대신 position 객체의 toString을 getter 처럼 사용하는 것 또한 getter를 사용하지 마라는 원칙을 말장난 처럼만 지키는 잘못된 방법인것이죠?

3. domain 패키지의 테스트 커버리지를 RacingCarGame 클래스를 제외하고는 100%를 지켰습니다.  테스트는 괜찮은 편인가요? RacingCarGame 클래스는 테스트하기 힘들지 않나요?

4.  `CarTest`나 `GameCarTest `경우  인스턴스 변수를 테스트 안에서 받아서 사용하는데, 이럴때 혹시 @nested 를 사용하여 클래스 안에서 격리 시켰는데 이것에 대해서 어떻게 생각하시나요?
특히 CarTest 경우 DomainRule에 의존시켜 Rule이 변경되더라도 테스트 리펙토링 내성을 높히려 했는데 이것에 대해서는 어떻게 생각하세요?

감사합니다! :)

2023-04-21 13:43 UTC, juno-junho commented
![image](https://user-images.githubusercontent.com/72647031/233651382-dff7a1cc-76ae-45c6-9e68-583b7e98bc4f.png)

2023-04-21 14:05 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/RacingCarGame.java
>  public class RacingCarGame {
레이어를 만들필요가 없죠. OutputView에게 데이터를 넘겨 거기서 View 데이터로 파싱한 후 진행하면 되지 않을까요?

2023-04-21 14:09 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/GameCars.java
> +                .filter(car -> car.getPosition() == maxPosition)
Car에게 이 position이 맞냐? 라고 물어본다면 getter를 최소화 할수 있지 않을까요?

2023-04-21 14:09 UTC, juno-junho commented on src/main/java/study/racingcar/domain/RacingCarGame.java
>  public class RacingCarGame {
그렇다면  제가 한 방법 괜찮지 않나요?

2023-04-21 14:10 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/Position.java
> +    }
이렇게 구현하시기 보단, EqualsTo를 오버라이딩 해서 사용하시면 어떨까요?

2023-04-21 14:12 UTC, ksy90101 commented on src/main/java/study/racingcar/domain/RacingCarGame.java
>  public class RacingCarGame {
지금 생각해보면 결국 이 클래스가 Controller 역할을 하게 되는거 같아요.
굳이 Controller라는 클래스를 만들다 보니, 관리하기가 어려움을 겪고 계신거 같네요.
Controller와 RacingCarGame을 하나로 합쳐서 구조를 짜보면 어떨까요?

2023-04-21 14:13 UTC, ksy90101 commented on src/main/java/study/racingcar/rule/DomainRule.java
> +public class DomainRule {
준호님이 생각하시는 Rule이라는 객체는 무엇일까요?
사실 차라리 그냥 Game이 numberGenertor 객체를 가지고 있으면 되는거 아닌가 해서요.

2023-04-21 14:15 UTC, ksy90101 commented
1. Domain 안은 rule이 변경됨에 따라 코드를 수정하지 않아도 되게끔 Rule 클래스를 만들었는데, 출력과 관련된 rule과 도메인 로직과 관련된 rule을 분리해 DomainRule, OutputViewRule로 분리 시켰습니다. 이것에 대해서는 어떻게 생각하시나요?

> 이것도 리뷰에 남겼어요!

getter를 사용하는 대신 position 객체의 toString을 getter 처럼 사용하는 것 또한 getter를 사용하지 마라는 원칙을 말장난 처럼만 지키는 잘못된 방법인것이죠?

>  네 맞습니다. 차라리 getter를 사용하는게 더 좋을수 있어요. 차라리 의미 전달을 확실히 하는게 더 좋아요.

> domain 패키지의 테스트 커버리지를 RacingCarGame 클래스를 제외하고는 100%를 지켰습니다. 테스트는 괜찮은 편인가요? RacingCarGame 클래스는 테스트하기 힘들지 않나요?

> View의 의존이 없다면 가능하죠. 랜덤값은 저희가 만든 인터페이스를 최대한 맨위 레이어로 빼면 가능할거 같아요. 그러나 리뷰를 좀 남겨봤는데,제가 말한대로 하면 어려울수 있죠. 근데 Scanner가 있어도 사실 가능하긴 합니다.
https://choichumji.tistory.com/118
위 글을 읽어보시면 도움이 될겁니다.

2. CarTest나 GameCarTest 경우 인스턴스 변수를 테스트 안에서 받아서 사용하는데, 이럴때 혹시 @nested 를 사용하여 클래스 안에서 격리 시켰는데 이것에 대해서 어떻게 생각하시나요?
특히 CarTest 경우 DomainRule에 의존시켜 Rule이 변경되더라도 테스트 리펙토링 내성을 높히려 했는데 이것에 대해서는 어떻게 생각하세요?

> 네 @Nest 를 잘 써주셨네요. 말씀하신 대로 사용한다면 Nest의 장점을 잘 취하신것입니다.

2023-04-21 14:16 UTC, merged