Step5
next-step/java-racingcar pull request #4683
Opened 2023-04-27 08:15 UTC by yoonjaej3

안녕하세요 준철님 

말씀하신대로 도메인 별로 나눠 봤는데 개선사항이 뭐가 더 있을까요?

2023-04-28 00:58 UTC, neojjc2 commented
#tag @neojjc2

2023-04-28 00:59 UTC, neojjc2 commented
> 안녕하세요 준철님
Racing 클래스를 Domain 패키지에 두는게 맞을까요?
여기서 Racing은 자동차 경주게임의 규칙? 진행사항? 같은 의미에요
Racing이라는 클래스에 너무 많은 것들이 들어있는 느낌인데 이것도 더 쪼개는게 맞는거죠?

네 윤재님 😄 
그런 포인트가 느껴지신다면 쪼개는게 맞습니다 👍 
`Racing`의 부담을 좀 덜어주시죠 😄

2023-04-28 01:09 UTC, neojjc2 requested changes
안녕하세요 윤재님 😄 

마지막 단계 잘 진행해 주셨습니다 
이번 자동차 미션 처음 주신 PR에 비하면
정말 많이 정리된 것 같아요 😄 

고민하고 계신 부분에 대해서 의견 드렸습니다
마지막 단계인만큼 정리하시는 마음으로 
조금만 더 개선해보시면 어떨까요?? 😄 

재 리뷰 요청 기다리고 있겠습니다
조금만 더 힘내주세요 🙏

2023-04-28 01:09 UTC, neojjc2 commented on src/main/java/RacingCar/Model/Car.java
> +    private static final int LIMIT_NUM = 5;
보통 상수가 가장 제일 위치합니다 😄 

```java
private static final int FORWARD_NUM = 4;
private static final int LIMIT_NUM = 5;

private int location;
private String name;
```

2023-04-28 01:09 UTC, neojjc2 commented on src/main/java/RacingCar/Model/Racing.java
> +    ArrayList<Car> cars = new ArrayList<Car>();
`private`으로 접근제한을 할 필요가 있을 것 같네요 😄

2023-04-28 01:09 UTC, neojjc2 commented on src/main/java/RacingCar/Model/Racing.java
> +    }
고민하고 계신 것 처럼 `Racing`이 하고 있는 역할이 
* 경기를 (Round)를 운영하는 규칙관리 및 운영
* 경기결과에 대한 관리 (우승자)
* 경기에 참가하는 자동차들을 관리하는 역할  

이렇게 3가지 인데요 🤔 
* 경기를 (`Round`)를 운영하는 규칙관리 및 운영 

정도만 부여하고 나머지는 별도 객체들에게 역할과 책임을 부여해보시는것도 괜찮을 것 같습니다 🙇

2023-04-28 01:09 UTC, neojjc2 commented on src/main/java/RacingCar/Model/Racing.java
> +        Winner winner = new Winner();
이 부분은 `Winner`로 적절하게 잘 위임해주신 것 같아요 😄

2023-04-30 05:53 UTC, yoonjaej3 commented on src/main/java/RacingCar/Controller/RacingCar.java
> +        output.printWinner(racingRound.getWinner(registeredCar.getRegisteredCar()));
준철님 프로젝트마다 스타일이 다 다르겠지만
output.printWinner(racingRound.getWinner(registeredCar.getRegisteredCar()));
보시는 저 코드를 쪼개는게 맞을까요? 
ArrayList<Car> registeredCar = registeredCar.getRegisteredCar();
ArrayList<Car> winnerCar = racingRound.getWinner(registeredCar);
output.printWinner(winnerCar );

예를들면 위에 형태로요!

2023-05-01 03:19 UTC, neojjc2 commented on src/main/java/RacingCar/Controller/RacingCar.java
> +        output.printWinner(racingRound.getWinner(registeredCar.getRegisteredCar()));
굳이 그럴필요까지는 없어보입니다 😄 
기능상으로 크게 다르지 않고 가독성을 개선하기 위해서라면 의미가 있겠지만
한 줄로 쓰셔도 무방할 것 같아요 🙇

2023-05-01 03:22 UTC, neojjc2 approved these changes
안녕하세요 윤재님 😄 

마지막 단계에 개선사항까지 하시느라 정말 고생 많으셨습니다 
고생하시고 잘 참여해주신 덕분에 코드가 많이 정리된 것 같습니다 😄 

저랑은 이번이 마지막입니다 🙏 
자동차 미션 진행하시면서 학습하셨던 내용들 
한번 더 정리하시고 다음 미션으로 넘어가시면 더 좋을 것 같네요 

그동안 자동차 미션 하시느라 정말 수고 많으셨습니다
남은 미션들도 모두 완주하시길 응원하겠습니다 

이만 merge 합니다 

LGTM 👍 

🚗 🚗 🚗 🚗 🚗 
🏎️ 🏎️ 🏎️ 🏎️ 🏎️

2023-05-01 03:24 UTC, merged