Step4
next-step/java-racingcar pull request #4689
Opened 2023-04-28 12:07 UTC by pullup-dip-burpee

안녕하세요 Step 4 를 구현하였습니다.

감사합니다.

2023-04-28 15:51 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-04-28 15:51 UTC, kyucumber commented on src/main/java/racingcar/SimpleCar.java
> +    }
테스트에서만 사용하는 코드로 보이네요. 비즈니스 로직에서 제거하고 Test Fixture를 만들어보시는건 어떨까요?

2023-04-28 15:51 UTC, kyucumber commented on src/test/java/racingcar/CarTest.java
> +        assertThat(copiedCar.getPosition()).isEqualTo(car.getPosition());
이 테스트는 position과 name 자체가 복사되므로 무의미한 테스트가 될 것 같은데요 한번 확인해주시면 좋을 것 같아요.

2023-04-28 15:51 UTC, kyucumber commented on src/test/java/racingcar/CarTest.java
> +        assertThat(copiedCar.getPosition()).isEqualTo(car.getPosition());
Random 로직을 어떻게 테스트 할 수 있을지, 자동차의 이동에 대한 부분을 추상화하거나 할 수 있는 부분은 없을지 고민해보셔도 좋을 것 같습니다.

Strategy Pattern을 활용해보셔도 좋을 것 같아요.

2023-04-28 15:51 UTC, kyucumber commented on src/test/java/racingcar/CarTest.java
> +    }
```suggestion
    private SimpleCar car = new SimpleCar("test");
```

각각의 테스트는 분리되어 동작하기 때문에 BeforeEach 없이 위와 같이 할당해 사용하셔도 괜찮을 것 같아요. BeforeEach를 써도 무관하나 코드 양을 줄일 수 있습니다.

2023-04-28 15:51 UTC, kyucumber commented on src/main/java/racingcar/CarRacingGame.java
> +                .map(SimpleCar::new).collect(Collectors.toList());
CarList라는 일급 컬렉션에 이 책임의 일부를 옮겨도 괜찮지 않을까요?

2023-04-28 15:51 UTC, kyucumber commented on src/main/java/racingcar/CarRacingGame.java
> +    }
여기서 체크를 하더라도 다른 곳에서 SimpleCar를 생성할 때 유효하지 않은 이름을 입력하는 경우가 생길 수 있을 것 같아요.
SimpleCar를 만들 때 이름에 대한 제약 조건을 검증하고 여기서는 체크하지 않는건 어떨까요?

2023-04-28 15:51 UTC, kyucumber commented on src/main/java/racingcar/CarList.java
> +                .collect(Collectors.toList());
Stream을 잘 활용해주셨네요 👍

2023-05-04 11:01 UTC, pullup-dip-burpee commented on src/test/java/racingcar/CarTest.java
> +        assertThat(copiedCar.getPosition()).isEqualTo(car.getPosition());
리뷰 주셔서 감사합니다. 

코멘트 주신 부분 중 position과 name 자체가 잘 복사되는지 테스트를 하여 했습니다. 

Random 리팩토링 진행하겠습니다.

2023-05-04 11:04 UTC, pullup-dip-burpee commented on src/main/java/racingcar/CarRacingGame.java
> +    }
반영하여 해당 부분 제거하겠습니다.

2023-05-04 11:32 UTC, pullup-dip-burpee commented on src/main/java/racingcar/CarRacingGame.java
> +                .map(SimpleCar::new).collect(Collectors.toList());
반영했습니다.

2023-05-04 11:33 UTC, pullup-dip-burpee commented
@kyucumber 
상세히 리뷰 주셔서 감사합니다. 리뷰 주신 부분 대부분 반영하여 코드 수정하였습니다.

2023-05-11 15:28 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

남겨둔 코멘트는 다음 단계 진행에 참고 부탁드릴게요.

다음 단계 진행을 위해 머지하겠습니다.

2023-05-11 15:28 UTC, kyucumber commented on src/main/java/racingcar/SimpleCar.java
> +    }
인터페이스를 교체하면 해당 테스트가 정상적으로 동작하는지 테스트해볼 수 있지 않을까요~?

2023-05-11 15:28 UTC, merged