Step5
next-step/java-racingcar pull request #4693
Opened 2023-04-29 14:59 UTC by seominah

안녕하세요. 원철님 ! 
마지막 단계 진행완료 하였습니다.
원시값을 포장하는 부분과 패키지 분리하는 작업만 수행하였습니다. 
항상 꼼꼼하고 빠른 피드백 감사합니다 :)

2023-04-30 05:52 UTC, heowc requested changes
마지막 단계이네요~

마지막인 만큼 약간의 아쉬움이 있어(?) 코멘트를 남겨보았습니다
확인해보시고 궁금하신 점이나 어려운 점이 있다면 말씀주세요 ✉️

2023-04-30 05:52 UTC, heowc commented on src/main/java/carracing/domain/Game.java
> +        System.out.println(resultView.printWinner(winners.addWinners()));
getWinners 에서 addWinners 바뀐 이유가 있을까요?
addWinners는 뭔가 파라미터를 받아야할 것 같은 메소드명이라서요 🤔

2023-04-30 05:52 UTC, heowc commented on src/main/java/carracing/domain/Name.java
> +    public Name() {
이 생성자가 필요한 이유가 잇을까요?
요구사항에는 이름 비어있지 않고 5자 이하여야 해서요 🤔

2023-04-30 05:52 UTC, heowc commented on src/main/java/carracing/domain/Game.java
> +package carracing.domain;
main 메소드를 가진 클래스가 도메인일지 다시 한번 고민해보시면 좋을 것 같아요~

- 도메인이란 무엇을 의미하는지
- main 메소드와 어떠한 연관이 있는지?
- main 메소드를 가진 클래스는 어느 영역으로 봐야하는지?
- 등등

2023-04-30 05:52 UTC, heowc commented on src/main/java/carracing/domain/Position.java
> +public class Position {
원시값 포장 👍

2023-04-30 05:52 UTC, heowc commented on src/test/java/carracing/domain/WinnerTest.java
> +        cars = List.of(new Car(new Name("pobi"), new Position(4)),
Car가 Name과 Position을 항상 필요하는 부분이라면 생성자에서 만드는 것도 하나의 방법입니다 👍

2023-04-30 11:46 UTC, seominah commented on src/main/java/carracing/domain/Name.java
> +    public Name() {
앗 ! 테스트를 진행하다가 생성하였는데 요구사항에 위반되엇네요..! 
삭제하겠습니다! :D

2023-04-30 15:02 UTC, seominah commented on src/main/java/carracing/domain/Game.java
> +        System.out.println(resultView.printWinner(winners.addWinners()));
리스트에 우승자를 추가하여 add라는 명칭이 조금 더 괜찮다고 생각했는데 파라미터를 받을것 같은 메소드명일 수 있군요 ! 
findWinner라는 명칭은 어떤가요 !?

2023-04-30 15:24 UTC, seominah commented on src/main/java/carracing/domain/Game.java
> +package carracing.domain;
main 메소드를 가진 클래스는 프로그램을 실행시키는 것으로 비즈니스 로직을 가지는 domain영역에 포함되면 안될거 같습니다 ! 
1. 도메인이란 해결하고하자하는 문제의 영역, 핵심 비즈니스를 담당하는 영역입니다.
2. main 메소드는 프로그램을 실행하는 부분으로 도메인에 의존적일거 같습니다! 
3. Root 영역에 존재해야할거 같습니다 !

2023-04-30 15:25 UTC, seominah commented on src/test/java/carracing/domain/WinnerTest.java
> +        cars = List.of(new Car(new Name("pobi"), new Position(4)),
String, int로 전달하여 생성자에서 Name과 Position을 생성해주는게 좋겠네요 ! 감사합니다 :D

2023-05-01 06:54 UTC, heowc commented on src/main/java/carracing/domain/Game.java
> +        System.out.println(resultView.printWinner(winners.addWinners()));
기존 메소드명이 더 맞지 않을까 싶은데요~
오히려 `addWinners` 생성자에서 사용하는 `getWinner`에 더 맞는 표현이 아닐까 싶어요~

2023-05-01 06:57 UTC, heowc approved these changes
마지막 피드백 까지 고생 많으셨습니다~

다음 단계를 진행해주세요~ 👍

2023-05-01 06:57 UTC, merged