step5
next-step/java-racingcar pull request #4708
Opened 2023-05-03 09:34 UTC by poistargram

Race부터 도메인 영역으로 봤습니다.
뷰 영역으로 빼려고 Race의 각 라운드 스냅샷을 List에 저장했는데요~

약간 코드가 복잡해진 감이 있는데 리뷰 부탁드릴게요! 감사합니다.

2023-05-05 03:00 UTC, ksy90101 commented on src/main/java/racingcar/domain/Race.java
> +        racingCarsList.add(new RacingCars(cars, new RandomNumberGenerator()));
new RandomNumberGenerator를 매번 생성할 필요가 있을까요?
하나의 인스턴스로 재활용을 할수 있을듯 해요.
인스턴스가 계속 만들어 진다면 메모리에 계속 올라갈듯 해요!

2023-05-05 03:00 UTC, ksy90101 commented on src/main/java/racingcar/domain/Race.java
> +        return cars.get(raceCount.getValue()-1).getWinners();
-1을 하는 이유가 있나요?

2023-05-05 03:01 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Car.java
> +    }
Copy를 하는것도 좋지만, 위에서도 같이 계속 인스턴스를 만들면, 메모리에 계속 올라가서 성능상 좋지 않습니다.
굳이 Copy를 해야 할까? 고민해보시면 좋을거 같아요.

2023-05-05 03:01 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Car.java
> +    public void move(NumberGenerator numberGenerator){
```suggestion
    public static Car from(String name){
        return new Car(0, name);
    }
    
    public void move(NumberGenerator numberGenerator){
```

2023-05-05 03:01 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Car.java
> +    public boolean isWinner(int position){
실제 로직은 Winner보단, `Postion이 같은지?`를 의미하는거라고 생각이 들어요.
그런 이름으로 나타내면 어떨까요?

2023-05-05 03:02 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Name.java
> +        }
이 2개의 validate가 어떤걸 나타내는지 메소드로 뺀다면 의미전달이 더 잘 되지 않을까요?

2023-05-05 03:02 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/RacingCars.java
> +    private final List<Car> cars;
위에 CarResource가 있던게 그거와 이거와 다른게 무엇인가요?

2023-05-05 03:03 UTC, ksy90101 commented on src/main/java/racingcar/view/input/request/CarRequest.java
> +    public CarResource toResource(){
👍

2023-05-05 03:03 UTC, ksy90101 requested changes
안녕하세요 :)
5단계도 고생하셨습니다.
근데 의아한게 도메인에 변경점들이 많은데, 그거에 대한 테스트 코드가 미흡한거 같아요.
그 부분을 한번 살펴보시면 어떨까요?ㅎㅎ
질문이 있다면 언제든 슬랙으로 연락주세요~

2023-05-05 08:05 UTC, poistargram commented on src/main/java/racingcar/domain/Race.java
> +        racingCarsList.add(new RacingCars(cars, new RandomNumberGenerator()));
스프링의 Context처럼 재활용할 인스턴스를 보관한 레이어를 못정해서 우선 매번 새로운 빈을 주입했는데요~ 
우선 Race에서 인스턴스를 1회만 생성하고 주입하는 걸로 변경할게요!

2023-05-05 08:06 UTC, poistargram commented on src/main/java/racingcar/domain/Race.java
> +        return cars.get(raceCount.getValue()-1).getWinners();
자동차 경주 횟수가 5회인 경우 실제 RacingCars 의 리스트는 0~4번까지 저장되기 때문에 
최종 결과를 담은 마지막 RacingCars에서 위너를 구하기 위함입니다!

2023-05-05 08:10 UTC, poistargram commented on src/main/java/racingcar/domain/car/Car.java
> +    }
매 경기마다 RacingCars를 copy해서 매번 다른 인스턴스로 두는 결정을 했는데요~
우선 출력에 관한 의존성을 도메인과 완전히 분리하기 위함입니다!

위에서 언급한 내용처럼 Race부터 Car까지 도메인 영역으로 보고 
입출력에 대한 더티레이어가 있는 부분을 Controller로 여겼는데요~

요구사항의 출력을 보면 각 라운드 별로 Car의 상태를 출력해야 하는데
라운드 반복에 대한 역할은 Race가 가지고 있어서 각 라운드별 스냅샷을 저장하지 않으면 출력에 대한 요구사항을 풀기 어렵더라구요!

다른 의견 있으면 주시면 감사하겠습니다!

2023-05-05 08:50 UTC, poistargram commented on src/main/java/racingcar/domain/car/RacingCars.java
> +    private final List<Car> cars;
CarResource는 Car를 만들기 위해 받은 웹계층의 입력모델을 도메인 계층으로 넘기기위한 객체이구요~
RacingCars는 List<Car>를 감싼 일급컬렉션으로 생각하고 만들었어요.

2023-05-05 09:06 UTC, poistargram commented
안녕하세요 ~ 빠른 리뷰 감사드려요!

몇가지 피드백 반영 후 다시 리뷰 요청드립니다!
추가로 테스트 관련해서 어떤 부분에 추가하면 좋을지 고민이 되는데요~

특히 winner를 구하는 과정에서 
Race -> RacingCars -> Car까지 메세지가 흐르다보니
Race에서 호출하는 winner는 테스트 세팅이 어려운데 이런 부분도 다 작성해야 하나 의문이 드네요 ㅎㅎ

조언주시면 감사할게요!

2023-05-06 08:02 UTC, ksy90101 commented on src/main/java/racingcar/domain/Race.java
> +        racingCarsList.add(new RacingCars(cars, new RandomNumberGenerator()));
네 굳이 지금 단계예서 스프링처럼 할 필요는 없어보여요!

2023-05-06 08:02 UTC, ksy90101 commented on src/main/java/racingcar/domain/Race.java
> +        return cars.get(raceCount.getValue()-1).getWinners();
아. 인덱스로 하는군요.
그렇다면 Map을 쓰는것도 방법일거 같아요.
key에 횟수 / value에 결과를 두는거죠.

2023-05-06 08:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Car.java
> +    }
스냅샷을 저장하는건 좋은거 같아요.
근데, 그 스냅샷을 Car를 복사하면서 만들 필요가 있을까요?
차라리 스냅샷을 저장하는 객체를 만드는게 더 좋을수도 있을거 같아요.
view는 단순히 어떻게 보면 String을 내려주는것이니깐요.

2023-05-06 08:07 UTC, ksy90101 approved these changes
안녕하세요 :)
5단계까지 고생 많으셨습니다.
피드백 적용하시느라 고생 많으셨어요.
답변들을 보면서 많은 고민을 하신게 느껴지네요.
답을 달아야 하는것들은 다 달아두었습니다.

이만 자동차 경주게임은 마무리 해도 될듯해서 머지 하도록 할게요.
혹시라도 좀더 보면 좋을것들이 있다면 슬랙으로 연락주세요~
고생많으셨어요!

2023-05-06 08:07 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/RacingCars.java
> +                .collect(Collectors.toList());
get을 해서 로직이 필요하다는건, 어떻게 보면 racingCars에 역할이라고 생각이 들어요.
즉, 지금 영역은 RacingCars에서 해야 하지 않을까 합니다.
getter를 어쩔수 없이 만들어야 할때가 있지만, 최대한 밖에서 해당 상태를 사용하는 일은 최소화 해야 한다고 생각합니다.

2023-05-06 08:07 UTC, merged