Step1: 문자열 계산기 및 자동차 경주 구현
next-step/java-racingcar pull request #4732
Opened 2023-07-04 07:59 UTC by dongjoo0-0

문자열 계산기는 다음 기능을 포함하고 있습니다.
1. 빈 문자열 또는 null 입력시 0 반환
2. 숫자 하나 입력시 해당 숫자 반환
3. 여러 숫자를 컴마(,) 및 콜론(:) 구분자로 입력시 해당 숫자들의 합 계산
4. “//”와 “\n” 문자 사이에 커스텀 구분자 지정 가능
5. 음수 및 숫자가 아닌 문자열의 경우 RuntimeException 예외 발생

자동차 경주는 다음 기능을 포함하고 있습니다.
1. 자동차 이름을 컴마(,)로 구분하여 5자 이내의 문자열을 입력받음
2. 시도 횟수를 숫자로 입력받음
3. 위 두 가지 경우를 제외한 입력은 예외 처리하여 다시 입력받음
4. 입력받은 이름과 시도 횟수를 통해 경주 실행, 경주 과정 출력
5. 매 시도시 일정 확률로 자동차 전진
6. 가장 앞에 있는 자동차들 이름 우승자로 출력

2023-07-04 14:22 UTC, sihyung92 requested changes
안녕하세요 동주님 ㅎ 리뷰어 성시형입니다 반갑습니다
깔끔하게 잘 구현해주셨네요~ 몇몇 리뷰 남겼으니 확인해주세요.

추신으로 남겨주신 질문들은 리뷰 중에 답이 된거 같아 리뷰로 대신하겠습니다 ㅎ 
다음 질문은 리뷰 중 작성하지 않아서 코멘트로 답변할게요

> 사소한 부분이긴 한데, Output.java printInitialStatus 메소드에서 System.out.println("\n실행결과")라고 작성하였는데, println을 한 줄 더 쓸지 \n을 쓸지 어떤 것이 더 나은 방법일까요?

System.out.println()에 cmd + b (윈도우는 단축키가 다를텐데요, 참조를 찾아가는 단축키입니다)를 눌러보시면 newLine()이라는 메서드를 호출하고, 내부는 다음 처럼 작성되어 있네요
```java
    public void newLine() throws IOException {
        write(System.lineSeparator());
    }
```
System.lineSeparator() 메서드는 mac에선 \n, window에선 \r\n을 반환하므로 \n 보단 System.out.println()로 하면 OS 의존성 없이 동작하는 코드를 만들 수 있습니다..........만 
사실 그게 그거라고 생각합니다 ㅎ ㅎ

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Game.java
> +    /** Move all cars in GameBoard. */
꼼꼼하게 주석을 남겨져 있지만, [프로그래머의 뇌](https://www.yes24.com/Product/Goods/105911017)에선 좋지 않은 주석이 오히려 가독성을 떨어뜨린다는 실험 결과를 제시합니다.

코드를 작성하는 시간의 대부분은 이미 작성된 코드를 읽는 시간이므로 코드 가독성 (주석을 포함하여)는 코드 생산성과 매우 직접적으로 연관된 중요한 가치인데요, 
그렇다면 좋은 주석은 어떤 것인가 생각해볼 수 있습니다.

클린 코드 등에서 [좋은 주석에 대해 제시](https://velog.io/@hangem422/clean-code-comment)하므로 한번 읽어보시길 권합니다~!

코드의 대부분의 주석은 메서드가 하는 일을 그대로 표현하고 있는데, 이는 동어 반복에 해당해 가치있는 주석으로 보기 어려울거 같습니당 ㅎㅎ
개인적으로 좋아하는 말은 "좋은 주석은 '어떻게'를 설명하지 않고, '왜' 그 코드가 거기 있는지 설명한다"는 말입니다. 
넥스트 스탭에선 최대한 가독성있는 코드를 통해 표현하고 주석은 차선으로 택하라고 권하는데, 한동안 주석을 금하고 주석 없이도 의도가 표현되는지 확인하는 연습도 가독성을 키우는데 좋은 방법인 것 같습니다.

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Game.java
> +                .orElse(1);
1은 매직넘버인데요, 이 1이 어떤 의미인지 알기 어렵습니다. Car가 1로 초기화 된걸 본다면 눈치 챌 수 있겠지만, 그걸 알기 전까지 다른 사람은 이 1이란 숫자를 수정할 수 없습니다.
매직넘버는 상수화를 통해 의미있는 문자열로 변경함으로써 대처할 수 있습니다. 상수화 해서 의도를 표현해볼까요?

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Input.java
> +    public static int processTryCount() {
반복 로직 등은 내부에 감추고 객체 역할에 충실한 부분 좋습니다 ㅎ

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Input.java
> +        } catch (RuntimeException e) {
scanner.nextLine()에 커서를 올리고 F1을 눌러보시면, 어떤 런타임 오류가 발생 할 수 있는지 나옵니다. NoSuchElementException이 보이는데, 이 오류는 RuntimeException인데, 이 오류도 "숫자만 입력받을 수 있습니다"라는 오류 메시지와 어울리는지 생각해볼 필요는 있습니다.

의도한 오류만 catch 할 것인지, 혹은 모든 오류를 잡고 복구할지는 개발자의 선택이지만 Exception, RuntimeException 등의 catch는 의도와 다르게 동작할 가능성이 있다는 걸 염두하면 좋습니다 ㅎ

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
name에 대한 validation은 Input에서만 진행하면 충분할까요?
데이터 validation은 어느 로직에서 진행하는게 좋을까요?

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/RacingCarRunner.java
> +        Output.printWinners(game.getWinnerNames());
깔끔하네요 ㅎ 
다만 메서드 추출을 통해 조금 더 가독성있게 리팩토링할 수 있는 여지는 보입니다.

2023-07-04 14:22 UTC, sihyung92 commented on src/test/java/racingcar/CarTest.java
> +    }
isMove() 가 public 필요가 없다는 리뷰를 반영하면 해당 메서드는 없어지게 될텐데요,
테스트의 목적을 생각해 봤을 때 아래 2개의 테스트와 다르지 않으므로 해당 테스트는 없어도 좋다는 생각이 듭니다 ㅎ

2023-07-04 14:22 UTC, sihyung92 commented on src/test/java/racingcar/GameTest.java
> +    }
Game이란 객체의 단위 테스트가 이루어지지 않았다는 생각이 듭니다.

Game의 기능이 많아질수록 해당 테스트는 유지보수하기 어렵게 될텐데요, 
나중엔 200 라인 정도되는 테스트 코드 중 틀린 부분을 찾지 못한 누군가가 빨리 배포하기 위해 해당 코드를 주석치거나 삭제하고 나가는 엔딩으로 다가오게 됩니다.

각 메서드 단위별로 테스트를 작성해 유지보수하기 좋은 테스트로 만들어볼까요? ㅎ ㅎ

2023-07-04 14:22 UTC, sihyung92 commented on src/main/java/racingcar/Input.java
> +        if (carNames.length == 0) throw new IllegalArgumentException();
if의 메서드 블록 `{}` 은 생략이 가능하지만 전 프로그래밍 중 가장 핵심 파트는 if문과 for문이라고 생각합니다 ㅎ 개인적으로 if문의 범위를 오인할 수 있을 수 있는 `{}` 생략은 잘 안하는 편입니다.

2023-07-04 14:22 UTC, sihyung92 commented on README.md
> +5. 실행 결과를 출력하는 기능
기능 목록에는 어떤 유효성 검사가 있는지 작성해주면 풍부한 기능 명세서가 됩니다 ㅎ

2023-07-05 00:52 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +    }
테스트를 위해서 public으로 만들었는데, 아래 남겨주신대로 같은 내용의 테스트가 존재하므로 테스트를 굳이 작성하지 않아도 괜찮을 것 같습니다!

2023-07-05 00:58 UTC, dongjoo0-0 commented on src/main/java/racingcar/Game.java
> +    /** Move all cars in GameBoard. */
보내주신 링크 읽어보겠습니다! 제가 작성한 대부분의 주석이 나쁜 주석의 대표적인 예시로 나와있네요,,, 코드로 의미를 설명할 수 있도록 해봐야겠습니다.

2023-07-05 01:33 UTC, dongjoo0-0 commented on src/main/java/racingcar/Game.java
> +                .orElse(1);
일단 CAR_INIT_POSITION으로 수정했습니다! 한가지 고민되는건 Car.java에서도 constructor에서 1로 초기화 시키는데, 이 부분도 상수화 시켜서 같이 묶는게 좋을까요? 혹은 Car.java에서 따로 상수를 관리하는 것이 좋을까요? 혹은 그냥 1로 놔두는것이 좋을까요?

2023-07-05 01:39 UTC, dongjoo0-0 commented on src/main/java/racingcar/Input.java
> +        } catch (RuntimeException e) {
Validation 시 발생하는 IllegalArgumentException에 대해서 해당 메시지를 출력하도록 수정했습니다! RuntimeException이 많은 Exception을 포함하는 개념이라는 걸 꼭 고려해야겠네요!

2023-07-05 02:01 UTC, dongjoo0-0 commented on src/main/java/racingcar/Input.java
> +        if (carNames.length == 0) throw new IllegalArgumentException();
확실히 오해할 수 있을 것 같아요! 수정해보았습니다.

2023-07-05 02:29 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
Car에서 String name에 대해 유효한 입력인지 믿을 수 없을 수도 있다는 생각이 드는데요, Name이라는 새로운 클래스를 만들어서  validation과 input 입력을 분리해 보는 것은 어떨까요? 마찬가지로 시도 횟수도 TryCount라는 클래스로 validation을 할 수 있을 것 같습니다.

2023-07-05 02:31 UTC, dongjoo0-0 commented on README.md
> +5. 실행 결과를 출력하는 기능
유효성 검사 작성해보았습니다.

2023-07-05 02:47 UTC, dongjoo0-0 commented on src/main/java/racingcar/RacingCarRunner.java
> +        Output.printWinners(game.getWinnerNames());
다른 부분은 명확한 것 같아 for 루프만 따로 메소드를 추출해보았습니다.

2023-07-05 03:16 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +    }
다른 방식으로 구성해 보라는 말씀은 어떤 의미일까요? 일단은 toString의 모호함에 대해 이해하여서, statusToString으로 메소드 이름을 바꿔보았습니다!

2023-07-05 04:56 UTC, dongjoo0-0 commented on src/test/java/racingcar/GameTest.java
> +    }
run은 Car::move만 실행하는데 CarTest에서 move 관련 로직을 테스트하기 때문에, 중복이라고 생각해서 테스트하지 않았습니다.
대신 getCars와 winnerTest를 조금 더 유닛 테스트로 구분하려고 해서 수정해보았습니다.

2023-07-05 05:45 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +    }
주 생성자를 하나 두고, 부 생성자들을 만드는 방식으로 생성자를 만들면, 한 가지 멤버 변수에 대한 변화를 적용시키기 쉬울 것 같습니다. 이를테면 Car 생성할 때 인자로 받는 String name을 CarName이라는 새로운 객체로 받게 되면 현재와 같은 경우는 두 생성자 다 수정해야 하지만 주생성자/부생성자 패턴에서는 주생성자에 주요한 로직을 수정하면 해결되는 등 유지보수가 편해질 것 같아요!

2023-07-05 05:46 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +    }
해당 패턴 적용하여 수정해보았습니다.

2023-07-05 07:11 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
근데 시도 횟수는 "음수가 아닌 숫자"여야 하는 제약조건이 int 타입으로도 충분한 것 같아서 TryCount 클래스를 만들필요는 없을 것 같습니다. 오늘 수업에서 이렇게 객체를 분리하는 것에 대해 배워서, 한번 CarName만 따로 만들어 보았습니다.

2023-07-05 07:56 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +    }
그렇게 했다가, Output으로 출력을 도맡아하는 것이 좋을 것 같아 Output에서 처리하도록 바꿔보았습니다.

2023-07-05 13:29 UTC, sihyung92 commented on src/main/java/racingcar/Car.java
> +    }
넵 public api는 향후 클라이언트 코드 (해당 클래스의 인스턴스를 생성하여 활용하는 코드) 중 누군가가 사용할 수도 있음을 암시합니다. 비즈니스 로직에 필요 없는데 노출할 경우 향후 유지보수 소요가 생기기 때문에, 테스트 용도로 public으로 만드는 것은 자제하는 편입니다. 절대규칙은 아니고 (개발원칙에 절대란 잘 없습니다) 테스트를 위해 private 코드를 public으로 열지 않는 경향이 있다~ 정도로만 이해해주시면 좋을거 같습니다

2023-07-05 13:30 UTC, sihyung92 commented on src/main/java/racingcar/Car.java
> +    }
넵 말씀해주신 부분이 리뷰 의도에 부합합니다 ㅎㅎ

2023-07-05 13:34 UTC, sihyung92 commented on src/main/java/racingcar/Game.java
> +                .orElse(1);
이건 저도 고민되는 부분인데, 어떨 때는 하나의 상수를 (Car에서 선언한) 만들어 여러 객체가 같이 쓰는 것이 좋을 때도 있고, 각각 따로 쓰는게 좋을 때 도 있습니다.
하나로 쓰면 로직의 원천이 되는 값(single source of truth 라고도 합니다)을 하나로 관리하고 한 군데만 수정하면 여러 로직을 한번에 변화하는 장점이 있으나, 상수명을 수정하면 여러 클래스를 다 수정해야하는 등 참조에서 오는 불편함이 있습니다. 
이거는 상황마다 살펴가며 적절히 결정하면 될텐데, 이번 미션 같은 경우 Car의 상수를 선언해 해당 값을 나눠 쓰는게 합리적으로 보입니다.
동주의 의견도 궁금합니다!

2023-07-05 13:37 UTC, sihyung92 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
넵 VO에 대해서 학습하셨군요 ㅎ Name이라는 VO에 검증책임을 준다면 어디서 만들어지는지에 대해 걱정할 필요가 없겠죠.

리뷰 의도 자체는 view 로직과 비즈니스 로직 중 validation이 어디에 들어가면 좋을까? 였습니다. 이번엔 VO를 활용해 그런 걱정은 덜었지만, 항상 활용할 수 있는 건 아닌데요. 동주는 view 로직 (즉 InputView)과 비즈니스 로직(즉 Car) 중 선택해야 한다면 어디에 validation을 적용하실 건가요? ㅎ

2023-07-05 14:02 UTC, sihyung92 approved these changes
안녕하세요 동주 ㅎ 리뷰 금방 반영해주셨네요
몇가지 리뷰를 남겼지만 굳이 request 까지 필요한 내용은 아니라고 판단되어 머지합니다!
혹시 더 이야기 나누고 싶으신 부분이 있다면 DM 주세요~

2023-07-05 14:34 UTC, merged

2023-07-06 01:58 UTC, dongjoo0-0 commented on src/main/java/racingcar/Game.java
> +                .orElse(1);
저도 처음에는 Car에 넣고 그것을 공유하고자 했는데, 상수를 공유하면 언급하신 부분에 대한 불편함이 걱정되었습니다. 다른 분 하신 걸 참고해보니 default로 선언해서 같은 패키지 내에서만 활용가능하게 하고, MVC 별로 패키지를 분리해서 사용하셨더라고요! 2단계 부분에서 마침 MVC 패턴 적용, 일급콜렉션, 모든 원시값 포장 등의 내용이 있어서 해당 내용을 적용하면서 반영해보겠습니다!

2023-07-06 02:14 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +        this.name = name;
말씀해주셔서 생각해보니 자동차 이름의 제약조건이라는게 순수히 도메인에 관련된 내용이기 때문에, View 로직에 있는 것이 이상하다고 느껴지네요! 그래서 CarName을 만든 것인데, 이렇게 VO를 만들 수 없더라고 validation 자체는 비즈니스 로직에 있는 것이 맞다는 생각이 듭니다.
그러다보니 지금 Input에서 CarName을 생성하고 있는데, 여전히 제약조건을 View에서 확인하고 있는 것 같아요! 그래서 Step2에서는 해당 부분을 Controller가 처리할 수 있도록 분리해보려고 합니다!

2023-07-06 02:15 UTC, dongjoo0-0 commented on src/main/java/racingcar/Car.java
> +        this.random = random; /* for mocking random in test */
아하 그렇군요! Random을 다른 용도로 쓸 수 있다는 것을 파악하지 못했네요! 소 뒷걸음치다가 쥐 잡은 느낌..ㅎㅎ 말씀해주신 부분이 미처 생각지 못한 부분이라 도움이 될 것 같습니다!