Step2: 자동차 경주 리팩토링
next-step/java-racingcar pull request #4755
Opened 2023-07-07 10:17 UTC by gunner6603

안녕하세요! 자동차 경주 리팩토링 진행했습니다.

MVC 구조로 어플리케이션 구조로 변경했고, 지난 PR에서 언급해주신 부분도 업데이트 했습니다.

### 변경사항
* RandomGenerator의 메소드를 인스턴스 메소드로 변경함 c8fcc88ff55743a45c5b76f419ec4f62b500ee02
* 뷰 로직을 도메인으로부터 분리함 (여러 커밋에 걸쳐 변경)
* 문자 리터럴을 추가적으로 상수화 14d7388828c89a224adcfd964d8802e6da5b64fd
* 에러 메시지 내용 추가 a4f949216074f67a49c56f2d59ab791b9e7cd12f
* 필드 순서에 구글 자바 코드 스타일 반영 4961be862f2e6bb5eedff8871908bc7309714e9d
* 테스트 메소드명 변경 699a0ad5ff7c3afc0250a36355cf9baa5d91b2fd
* 복잡도가 높은 메소드를 더 작게 분리 4bb75f793e2fa3587774b768f5912d84a8f04477
* Name 클래스에 equals, hashcode, toString 메소드 추가 d54d970da1cec3dc24980cc22f4dbc943e2a2f34
* final 키워드 추가 4bb75f793e2fa3587774b768f5912d84a8f04477
* Cars 클래스에 대한 테스트 추가 26b3d6edfc2655776998d7f9fba157e6ea1d9a4f

### 여쭤보고 싶은 부분
* CarRacingGame 객체 내부의 Car, Cars 객체를 바깥으로 노출하지 않으면서, 뷰를 CarRacingGame으로부터 분리하기 위해 CarFormatter 객체를 외부에서 주입해서 Cars 객체까지 전달하는 방법을 택했는데, 더 나은 방법이 있는지 궁금합니다!

2023-07-07 14:20 UTC, sihyung92 requested changes
안녕하세요 건님~~ 
1단계 때 남겨두었던 리뷰들을 잘 반영해주셨네요 ㅎ
리뷰 확인해주시고 또 요청해주세요

### Q&A
- CarFormatter보다 더 나은 방법이 있을지

당장 구현해야하는 포맷에 맞춘 응답 구현 뿐만 아니라 향후 다른 뷰의 대응을 도메인 코드 수정 없이 반영할 수 있으니 좋은 구현입니다 ㅎ 누가 급하게 웹 뷰 맞춰달라고 하면 휴가중에 노트북 부랴부랴 열 필요 없이 한마디 하시면 됩니다. "CarFormatter 구현해서 넣기만 하면 된다고 해주세요~"

2023-07-07 14:20 UTC, sihyung92 commented on src/main/java/car/domain/Cars.java
> +            .collect(Collectors.toUnmodifiableList());
ㅎㅎ 불변 리스트 활용 좋네요

2023-07-07 14:20 UTC, sihyung92 commented on src/main/java/car/domain/Cars.java
>          list = Arrays.stream(split(names))
해당 로직은 view 로직에 가깝습니다. 콘솔 뷰는 ","로 구분되는 문자열을 넘기기 용이하지만, 웹뷰나 모바일뷰나 xml 양식으로 전송하는 다른 서버 등으로부터 받은 데이터를 ","로 이어지는 문자열을 만들어내기 위해 또다른 작업을 필요로 할 거에요.

도메인에서는 공용된 컬렉션 라이브러리인 List<String>으로 받는게 낫지 않을까요?

2023-07-07 17:09 UTC, gunner6603 commented on src/main/java/car/domain/Cars.java
>          return names.split(",");
넵 알겠습니다!!

2023-07-07 17:14 UTC, gunner6603 commented on src/main/java/car/domain/Cars.java
> +    List<Car> getList() {
Cars 클래스의 move 메소드를 테스트하기 위해 getList 메소드가 필요한데, 해당 메소드를 public으로 선언하면 해당 메소드를 다른 패키지의 프로덕션 코드에서 사용할 가능성이 생기고, 내부 구현이 외부로 노출되어 유지보수가 어려워질 것이라고 판단해서 default로 선언했습니다!

2023-07-07 17:15 UTC, gunner6603 commented on src/main/java/car/domain/CarRacingGame.java
> +public class CarRacingGame {
넵 RacingCarGame에 대한 테스트도 작성해 보겠습니다!

2023-07-08 05:38 UTC, sihyung92 commented on src/main/java/car/domain/Cars.java
> +    List<Car> getList() {
테스트를 위해 프로덕션 코드의 접근 제어자를 변경하면 다른 프로덕션 코드에 의해 오용될 우려가 생깁니다 (캡슐화 저해) 
물론 테스트도 중요한 가치이므로 정말 방법이 없다면 개방하는 것도 방법이지만 코드를 살펴보니 WinningStrategy를 구현해 검증하는 방식도 보이는 거 같아요.

2023-07-08 05:40 UTC, sihyung92 requested changes
안녕하세요 건님~~ 
반영 빠르게 잘 해주셨군요!!
테스트와 관련된 리뷰를 2가지 남겼으니 반영하고 또 요청주셔요~~ ㅎㅎ

2023-07-08 05:40 UTC, sihyung92 commented on src/main/java/car/domain/CarRacingGame.java
> +public class CarRacingGame {
isNotFinished와 
resolveWinnerNames에 대한 테스트가 보이지 않습니다 ㅎ
각 메서드를 의존하는 Controller 및 View의 테스트가 없으므로 해당 기능에 대해 확신을 가지려면 테스트를 작성하는 편이 좋습니다.
당장 기능엔 별로 필요 없어보이지만 (굳이 해야되나?) 다음 기능을 개발할 때 이 기능들까지 다시 검증해볼 필요가 없어지므로 나중에 보상을 받는 느낌입니다

2023-07-08 07:52 UTC, gunner6603 commented on src/main/java/car/domain/CarRacingGame.java
> +public class CarRacingGame {
넵 해당 메서드들에 대한 테스트를 추가적으로 작성했습니다!
resolveWinnerNames 메서드의 경우, cars 필드로부터 우승자 Car 객체 리스트를 가져오고, Name 리스트를 추출하는 역할이라 메서드 전체를 테스트하면 우승자 선출 로직에 대한 테스트까지 포함되는 것 같아 우승자 리스트를 받아오는 부분은 selectWinnersFromCars라는 메서드로 분리했습니다.
이때 접근 제어자를 default로 설정하고 테스트 시에는 이 메서드를 오버라이딩해서 Name 리스트 추출 부분만 테스트를 할 수 있도록 했는데, 더 좋은 방법이 있을지 궁금합니다!

2023-07-08 07:54 UTC, gunner6603 commented
CarRacingGame 클래스에 대한 테스트를 추가적으로 작성했습니다!
resolveWinnerNames 메서드의 경우, cars 필드로부터 우승자 Car 객체 리스트를 가져오고, Name 리스트를 추출하는 역할이라 메서드 전체를 테스트하면 우승자 선출 로직에 대한 테스트까지 포함되는 것 같아 우승자 리스트를 받아오는 부분은 selectWinnersFromCars라는 메서드로 분리했습니다.
이때 접근 제어자를 default로 설정하고 테스트 시에는 이 메서드를 오버라이딩해서 Name 리스트 추출 부분만 테스트를 할 수 있도록 했는데, 더 좋은 방법이 있을지 궁금합니다!

2023-07-08 08:03 UTC, gunner6603 commented on src/main/java/car/domain/Cars.java
> +    List<Car> getList() {
앗 제가 이 코멘트를 방금 봤네요! 이 부분도 반영해 보겠습니다!!

2023-07-08 08:35 UTC, gunner6603 commented
WinnerStrategy 구현을 통한 검증과 default 접근 제어자에 대해 말씀해 주신 부분을 참고해서 추가적으로 수정해 보았습니다!
(슬랙을 보니 아직 확인 표시가 없어서 추가 커밋을 올렸습니다!)

* Cars 클래스의 getList 메서드를 삭제하고 테스트에서 모든 자동차가 움직였는지 확인하는 부분은 format 메서드로 확인했습니다.
* selectWinnersFromCars의 접근 제어자를 private으로 변경하고, WinnerStrategy를 구현해서 CarRacingGame에 주입하는 방식으로 테스트를 수정했습니다.

2023-07-09 07:33 UTC, sihyung92 approved these changes
안녕하세요 건님!
리뷰 잘 반영해주신 부분 확인해서 머지할게요. 
첫 미션 수고하셨습니다 ㅎㅎ
앞으로도 화이팅입니다!

2023-07-09 07:33 UTC, merged