[Step2] 자동차 경주 리팩토링
next-step/java-racingcar pull request #4762
Opened 2023-07-08 18:11 UTC by dahyen0o

안녕하세요, 해당 미션의 두번째 PR 올립니다.
아직 전체 리팩토링이 완료되지 않았습니다. (README에서 ```테스트 패키지 정리``` 이후 부터 구현되지 않았습니다.) 
시간이 늦어 우선 제출합니다.. 😭

저번 리뷰에서 언급해주신 내용 이외에도 해당 객체가 담당하는 역할이 적절한 지를 고민하며 전체적으로 리팩토링을 진행했습니다.

감사합니다. 🙇‍♀️

2023-07-09 16:40 UTC, yjksw requested changes
안녕하세요 세은님 ~! 
2단계 구현 잘 해주셨습니다 ㅎㅎ 

사소한 코멘트 몇개 남겼으니 적용 부탁드려요 🙌
혹 시간이 부족하시다면 test 패키지 구조 리팩토링 정도만 하고 요청주셔도 좋습니다

2023-07-09 16:40 UTC, yjksw commented on src/main/java/calculator/Number.java
> +            throw new ArithmeticException(OVERFLOW_MESSAGE);
`ArithmeticException` 을 사용하셨군요 ㅎㅎ
java docs에서 어느 상황에 위 exception을 사용하는지 한번 공부해보아도 좋을 것 같아요 ~

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/RandomMovableStrategy.java
> +        throw new IllegalArgumentException(NOT_VALID_RANGE_MESSAGE);
자동차의 움직임을 판별할 때, 범위 밖의 수를 판단하는 것이 적절한지 고민이 되는군요!
`isMove()`  자체에서는 움직임에 대해서만 책임을 지게되면, `isStoppableNumber(), isMovableNumber()` 이렇게 두가지 분기로 나뉘지 않을 수 있지 않을까요 ? 

두 분기를 따로 관리하면 아래와 같은 문제가 있을 수 있을 것 같아요. 
1) 기준이 바뀔 때 위 두 분기를 모두 관리해줘야 하고, 그 과정에서 무결성이 깨질 수 있음 
2) 코드가 더 길고 이해해야하는 것이 하나 늘어남

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/domain/Cars.java
> +    public void move(final MovableStrategy movableStrategy) {
move()에서 두 가지 일을 하고 있군요! 
실제로 자동차가 움직이는 것과, maxPosition를 기록하는 것을 모두 수행하고 있는 것 같아요.
그래서 메서드명만 보았을 때, maxPosition 갱신을 어디서 하는지 찾기 어려운 부분도 있었답니다. 
메서드는 그 이름에서 표현하고 있는 것만 정확히 수행하는 것이 가독성이나 협업 측면에서 큰 도움이 되어요.

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/domain/Cars.java
> +    private Position maxPosition;
요것을 Cars의 변수로 두고 관리할 필요가 있을까요? 🤔
필요성과 비용을 비교해서 고민해보아도 좋을 것 같아요 ~

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/domain/Name.java
> +    private final String value;
저는 개인적으로 value라는 모호한 이름보다, 이전에 사용하셨던 name이 더 좋을 것 같아요 😊

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/domain/Position.java
> +    }
아무 매개변수를 가지지 않는 `Position.of()` 가  어떤 값을 만들지 사용하는 입장에서는 알기 어려울 수 있을 것 같아요 ~  
java util에서 제공하는 클래스들도, `String.valueOf(int a)` 등과 같이 반드시 매개변수를 받고 있어요 ㅎㅎ 
기본값을 제공하고 싶다면 `Collections.emptyList()` 같이 좀 더 명확하게 제공하면 좋답니다.

2023-07-09 16:40 UTC, yjksw commented on src/main/java/racingcar/dto/RaceResponse.java
> +    public static final class CarResponse {
내부 클래스로 두신 이유가 있나요 ? ㅎㅎ

2023-07-09 16:40 UTC, yjksw commented on src/test/java/racingcar/RacingCarTest.java
>  public class RacingCarTest {
test와 main의 패키지 구조는 동일해야합니다 ! ㅎㅎ
그래야지 각 객체에 대해서 어떤 테스트가 되고 있는지 명확히 알 수 있기 때문이에요. 
IDE를 사용하신다면 `option + enter` 조합으로 바로 동일한 구조의 test 클래스를 생성할 수 있어요 !

2023-07-09 16:54 UTC, yjksw commented
안녕하세요 ~! 질문에 대한 답변입니다 😊


> 포장된 값을 필드로 가지는 객체에서 getter로 반환하는 타입은 포장된 값이 적절한가요, 아니면 원시값이 적절한가요?
예를 들어 제 코드에서 car의 name을 반환할 때 Name으로 반환해야할 지, String으로 반환해야할 지 궁금합니다.
저는 getter면 해당 필드를 그대로 반환해야 한다고 생각해 포장된 값을 반환했는데, 이러니 코드에서 두 번 getter를 사용하는 일이 생겨 오히려 번거롭지 않나 하는 생각도 듭니다.

상황마다 다를 것 같은데요, 저도 둘 중 무엇이 적절한지 명확히 구분하기는 어려운 것 같아요 ~ 
출력을 위한 것이라면 raw한 값을 전달하는 것이 좋을 것 같은데, 메서드명이 단순 getter라면 타입 그대로를 반환하길 기대할 것 같긴 하네요. 

> Name, Position, Round는 Integer처럼 하나의 값이라 생각해 VO로 변경했습니다. 해당 리팩토링이 적절한 지 궁금합니다

구현하신 애플리케이션에서 위 값들이 VO로 여겨진다면 적절하다고 생각해요 ! ㅎㅎ 
하지만 Name 등을 VO로 정의하려면 지금처럼 중복에 대한 명확한 정책이 있어야한다는 것만 기억하면 좋을 것 같아요.

2023-07-10 01:47 UTC, dahyen0o commented on src/main/java/racingcar/domain/Name.java
> +    private final String value;
저도 그런데.. solarLint에서 클래스 이름과 동일하게 변수 이름을 짓지말라고 경고를 띄워서 바꿨습니다. 그래서 우선 하나의 필드만 가지는 VO들의 이름을 바꿔줬는데 name이 더 나을까요?

2023-07-10 09:33 UTC, dahyen0o commented on src/main/java/racingcar/dto/RaceResponse.java
> +    public static final class CarResponse {
RaceResponse 안에서만 쓰이기 때문에 뒀습니다..! 그런데 접근 제어자를 public으로 해놨네요 ㅠㅠ

2023-07-10 15:44 UTC, dahyen0o commented
안녕하세요, README의 4차 목록 중 구현 못했던 목록들 + 리뷰 주신 내용들로 수정해 다시 올렸습니다!
또한 일부 댓글에 대해 답댓글을 남겼습니다..! 확인 부탁드립니다 🥹
감사합니다 🙇‍♀️

2023-07-11 11:41 UTC, yjksw approved these changes
안녕하세요 😊
리뷰 적용해주신 것 잘 확인했습니다 ~! 
잘 구현해주셔서 이만 머지할게요. 
앞으로도 화이팅 입니다 🙌

2023-07-11 11:41 UTC, yjksw commented on src/main/java/racingcar/RandomMovableStrategy.java
> +        return !isStoppableNumber(number);
부정문은 한번 떠 꼬아서 생각해야하기 때문에 가독성을 떨어뜨린답니다 ㅎㅎ

2023-07-11 11:41 UTC, yjksw commented on src/main/java/racingcar/domain/Cars.java
> +                .orElseThrow(() -> new IllegalArgumentException("자동차가 존재하지 않습니다.")).getPosition();
`max, Comparator` 보다 stream에서 제공하는 `max()` 를 사용해보면 어떨까요 ?

2023-07-11 11:41 UTC, yjksw commented on src/test/java/racingcar/domain/RoundTest.java
> +}
왜 인텔리제이는 파일 마지막에 개행을 하도록 경고문을 띄울지 공부해봐도 좋을 것 같아요 ~ 😊

2023-07-11 11:41 UTC, yjksw commented on src/main/java/racingcar/dto/RaceResponse.java
> +    public static final class CarResponse {
CarResponse 독립적으로 사용되는 곳이 있다면 밖으로 빼는 것이 좋을 것 같네요 ~!

2023-07-11 11:42 UTC, merged