안녕하세요~! 빌드 오류 문제를 계속 해결하지 못해서 질문 드립니다...
next-step/java-racingcar pull request #4826
Opened 2023-10-31 17:28 UTC by suzhanlee

오랜 시간 검색해봤는데 해결을 전혀 못하겠습니다 ㅠㅠ
<img width="1039" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/6a6aeb82-7d52-40f5-abec-a9646be60f99">

우선 빌드 오류는 위와 같이 뜹니다!
코끼리로 다시 빌드를 해도 같은 오류가 나옵니다!

혹시 .idea가 오류가 난게 아닐까 싶어서 삭제하고 다시 재빌드 해도 동일한 문제가 나타납니다

문제가 있을 만한 설정들은 모두 캡쳐해봤습니다.

<img width="818" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/d3f718cf-e942-4c9e-bf8b-f7c5c59f918c">

<img width="709" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/a6d8d8ba-0177-42cb-82e6-bd2d97c9bece">

<img width="824" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/66192450-ddda-41c0-99cf-f71fb399df61">

<img width="822" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/11867ff6-061f-44d6-b16a-448c04649cdc">

<img width="824" alt="image" src="https://github.com/next-step/java-racingcar/assets/108535068/4472bb18-a145-4f4f-b991-c614dfd6021e">

제가 최근에 환경변수를 자바 17로 변경했는데 혹시 그것과 관련해서 문제가 발생할 수도 있을까요?

혹시 몰라서 프로젝트와 gradle 모두 자바 17로 바꿔봤는데도 동일한 문제가 발생합니다!

2023-11-01 11:59 UTC, javajigi requested changes
저도 처음보는 에러네요.
에러 메시지를 통해 검색해 보니 최근에 비슷한 오류가 몇 건 보이네요.
혹시 intellij 버전이 최신이라면 이전 버전으로 변경해 보는 것은 어떨까요?

https://youtrack.jetbrains.com/issue/IDEA-332475/IntelliJ-fails-to-open-project-after-upgrading-to-Kotlin-1.9.10-Gradle-8.3.3-and-Java-17-Missing-ExternalProject-for

한번 도전해 보시고 해결이 되지 않는다면 DM이나 채널에 문의해도 좋을 것 같아요

2023-11-01 14:16 UTC, pci2676 commented
<img width="1019" alt="image" src="https://github.com/next-step/java-racingcar/assets/13347548/ac4b41e6-79d9-4577-9353-9c1cbdca34ba">

음 gradle 프로젝트가 인식이 안된것 같아보이는데요...

오른쪽 gradle 탭에는 어떻게 나오나요?
<img width="2560" alt="image" src="https://github.com/next-step/java-racingcar/assets/13347548/a3b598d3-0030-475c-aa02-0a4c1fe12dfc">


---

.idea 다시 지우고 아래 부분도 바꿔보시고 import를 다시 수행해보시면 어떨까요?

<img width="983" alt="image" src="https://github.com/next-step/java-racingcar/assets/13347548/db889311-4dba-4075-b060-5aa9f14d8acc">


다른 설정이 변경되어서 그럴수도 있을것 같은데
repository를 다시 clone받아서 실행도 해보셨을까요?

2023-11-05 14:30 UTC, pci2676 approved these changes
빠른 미션진행을 위해 머지하겠습니다!

2023-11-05 14:30 UTC, pci2676 commented on settings.gradle
> +rootProject.name = 'java-racingcar'
ㅠㅠ 정말 고생하셨습니다.

2023-11-05 14:30 UTC, merged