Step1
next-step/java-racingcar pull request #4851
Opened 2023-11-01 11:15 UTC by sudo-init

branch 변경 없이 sudo-init branch에서 테스트 코드 작성 후에 commit, push 해버려서..

step1 branch 생성 후에 코드를 아래와 같이 바꿔 준 후 다시 commit, push 했습니다..ㅎㅎ;;

public class StringTest {
    @Test
    public void split1() {
        String[] result = "1,2".split(",");
        assertThat(result).contains("1");
    }

    @Test
    public void split2() {
        String[] result = "1,2".split(",");
        assertThat(result).containsExactly("1", "2");
    }
}

2023-11-01 13:50 UTC, seokhong requested changes
응민님 안녕하세요.
자동차경주 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다. 🙂 

1단계 학습 테스트 미션의 요구사항 중 split 에 대한 테스트만 작성하신 것으로 보입니다.
미션 페이지에 있는 다른 요구사항에 대한 테스트 코드도 작성 후 리뷰 요청 부탁드립니다.
> https://edu.nextstep.camp/s/twbNYuxs/ls/SrNBPJDS

2023-11-01 13:50 UTC, seokhong commented on src/test/java/study/StringTest.java
> +    public void split1() {
테스트가 검증하는 내용이 무엇인지 알 수 있도록 테스트의 이름을 변경해보면 어떨까요?
이름으로 설명하기 어렵다면, `@DisplayName` 어노테이션을 이용해보셔도 좋겠습니다.

2023-11-02 06:35 UTC, sudo-init commented
석홍님 안녕하세요.

1단계 학습 테스트 미션의 요구사항 모두 반영하여 다시 리뷰 요청 드립니다.

피드백 주신 내용, 어떤 테스트인지에 대한 설명도 반영했습니다 ㅎㅎ

리뷰하시고, 또 피드백 부탁드려요!

2023-11-02 09:36 UTC, javajigi approved these changes
학습 테스트 구현 잘 했네요. 👍 
소소하게 피드백 남겼어요.
1단계는 온라인 코드 리뷰 사이클을 경험하는 것이라 제가 대신 빠르게 merge합니다.

2023-11-02 09:36 UTC, javajigi commented on src/test/java/study/SetCollectionTest.java
> +        assertEquals(3, numbers.size(), "Set의 크기는 3이어야 함");
굳이 중복으로 테스트할 필요가 있을까?

2023-11-02 09:36 UTC, javajigi commented on src/test/java/study/StringTest.java
> +            char result = "abc".charAt(3);
```suggestion
            "abc".charAt(3);
```

2023-11-02 09:36 UTC, merged