2단계 문자열 덧셈 계산기
next-step/java-racingcar pull request #4865
Opened 2023-11-01 14:44 UTC by myunghoonju

안녕하세요.   

StringAddCalculator 클래스를 추가 하였어요.   
  아래에 세가지 함수로 구성되어 있는 splitAndSum() 구현.
  -  findPattern()
  -  getNumbers()
  -  checkPositive()

2023-11-02 04:43 UTC, nooose requested changes
안녕하세요 명훈님!
자동차 경주 미션 리뷰어 성준혁입니다.
2단계에서 처음 뵙네요 ㅎㅎ

아쉬운 부분이 있어서 한 번 더 보기로 했어요
코멘트 남겼으니 확인해 보시고 재요청 주시면 빠르게 피드백 드리겠습니다.

미션 진행하시다가 질문 있으면 언제든지 DM 남겨주세요!

2023-11-02 04:43 UTC, nooose commented on src/test/java/step2/StringAddCalculatorTest.java
> +}
<img width="116" alt="image" src="https://github.com/next-step/java-racingcar/assets/36617783/75e8e465-bf52-42e6-837a-8885bfd92da0">

빨간 경고가 보이네요 

[블로그](https://velog.io/@jangws/EOL%EC%9D%84-%EB%84%A3%EC%96%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0%EC%99%80-git%EC%97%90%EC%84%9C-CRLF-EOL-%EC%B0%A8%EC%9D%B4%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)에서 잘 설명하고 있으니 확인해 보세요~

2023-11-02 04:43 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    }
findPattern 메서드에서 커스텀 딜리미터를 찾으면 해당 딜리미터를 리턴하고
그렇지 않으면 기본 딜리미터를 반환하고 있습니다.
이후 결과를 다시 getNumbers 메서드에 보내서 문자열을 가져오는 방식이네요

```suggestion
    private static String findPattern(String data) {
        String delimiter = "";
        Matcher m = STRING_PATTERN.matcher(data);
        if (m.find()) {
            return m.group(1);
        }

        try {
            delimiter = data.split(",|:").length > 0 ? ",|:" : "";
        } catch (Exception e) {
            // nothing to do
        }

        return delimiter;
    }

    private static String[] getNumbers(String data, String pattern) {
        Matcher m = STRING_PATTERN.matcher(data);
        if (m.find()) {
            return m.group(2).split(pattern);
        }

        return data.split(pattern);
    }
```
그렇다면 getNumbers에서는 받은 pattern(구분자)을 기반으로 split해야하지 않을까요?
그리고 이 두 메서드를 합쳐보면 앞서말한 split이라는 메서드를 만들 수 있을 것 같습니다.

2023-11-02 04:43 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    }
명훈님은 pattern이라는 변수명을 사용하셨는데
pattern보다는 구분자 용도로 사용하고 있기에 delimiter라는 변수명이 더 적합해 보입니다.

2023-11-02 04:43 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    }
```suggestion
    private static void checkPositive(int number) {
        if (number < 0) {
            throw new IllegalArgumentException("음수는 허용하지 않습니다. - " + number);
        }
    }
```
aNumber가 뭘까요? 🤔 
의미가 없다면 number로 사용해도 될 것 같습니다.

또한 `RuntimeException` 대신 적절한 표준 예외를 사용하면 어떨까요?
매개변수 값이 잘못되었다는 예외인 `IllegalArgumentException`에 메시지까지 담아 예외를 던지면 좋을 것 같아요
<img width="522" alt="image" src="https://github.com/next-step/java-racingcar/assets/36617783/54b8d070-476a-4edd-bf41-94cbe5db6754">

2023-11-02 04:43 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    private static final Pattern STRING_PATTERN = Pattern.compile("//(.)\n(.*)");
재사용 좋네요 👍
기본 구분자도 상수로 정의하고 재사용할 수 있지 않을까요?

2023-11-02 04:43 UTC, nooose commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
```suggestion
    @NullAndEmptySource
    @ParameterizedTest(name = "입력값: {0}")
    public void splitAndSum_null_또는_빈문자(String input) {
        int result = StringAddCalculator.splitAndSum(input);
        assertThat(result).isEqualTo(0);
    }
```
NullAndEmptySource 이런 어노테이션도 있으니 ParameterizedTest와 함께 테스트 해보세요 👏

2023-11-02 04:43 UTC, nooose commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
입력값에 따라 결과가 달라진다는 이유로 테스트가 여러 개 존재하는데요
이런 부분도 1단계에서 배운 ParameterizedTest와 CsvSource를 활용해 보면 좋지 않을까요?

제공되는 테스트 코드 그대로 사용하지 않으셔도 됩니다 😄

2023-11-02 17:34 UTC, myunghoonju commented
안녕하세요!  
하나하나 배우게 되는 코멘트 주셔서 감사해요.   
아래 내용들을 수정해보았어요. 리뷰 부탁드려요~  

리뷰반영
- 함수 인수명 변경 data to numberStr
- findPattern(), geNumbers()  함수 통합
- 테스트 수정(jUnit annotations 추가)

2023-11-03 13:42 UTC, nooose approved these changes
피드백 잘 받아서 해주셨는데
제 의도와는 다르게 작업해 주신 부분이 남아 있네요

넘어갈지 고민을 좀 해봤는데요
피드백 바로 수용하실 수 있을 것 같아 머지하기로 했어요

코멘트 읽어보시고 다음 단계 진행하셔도 될 것 같습니다.
수고하셨습니다. 🙇

2023-11-03 13:42 UTC, nooose commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
```suggestion
    @ParameterizedTest(name = "입력: {0}, 결과: {1}")
    @CsvSource(value = {
            "1-1",
            "1,2-3",
            "1,2:3-6"
    }, delimiter = '-')
    public void splitAndSum(String input, int expected) {
        int result = StringAddCalculator.splitAndSum(input);
        assertThat(result).isEqualTo(expected);
    }
```
이렇게 여러개를 하나로 묶어 처리할 수 있을 것 같아요

2023-11-03 13:42 UTC, nooose commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
```suggestion
    @ParameterizedTest
    @NullAndEmptySource
    public void splitAndSum_null_또는_빈문자(String input) {
        int result = StringAddCalculator.splitAndSum(input);
        assertThat(result).isEqualTo(0);
    }
```

NullAndEmptySource를 사용했으니 반복 코드는 제거해도 될 것 같네요

2023-11-03 13:42 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    private static final Pattern SPECIAL_PATTERN = Pattern.compile(SPECIAL_DELIMITER);
```suggestion
    private static final String BASIC_DELIMITER = ",|:";
    private static final String SPECIAL_DELIMITER = "//(.)\n(.*)";
    private static final String NEGATIVE_NUMBER_ERROR = "문자열에 음수가 포함되어 있습니다.";
    private static final Pattern SPECIAL_PATTERN = Pattern.compile(SPECIAL_DELIMITER);
```

개행없이 상수끼리 묶어도 좋아보이는데 어떻게 생각하시나요?

2023-11-03 13:42 UTC, nooose commented on src/main/java/step2/StringAddCalculator.java
> +    }
```suggestion
    private static int sum(List<String> numbers) {
        int result = 0;
        for (String number : numbers) {
            int parsedInt = Integer.parseInt(number);
            checkPositive(parsedInt);
            result += parsedInt;
        }
        return result;
    }
```

양수 검증을 위해서 문자열을 int로 변환하고 
합산할 때 문자열을 다시 int로 변환하는 작업을 하고 있네요.
sum 내부에서 양수인지 음수인지 한번에 체크할 수 있지 않을까요?

2023-11-03 13:42 UTC, merged