자동차 경주 - 단위테스트: 2) 문자열 덧셈 계산기
next-step/java-racingcar pull request #4874
Opened 2023-11-02 03:23 UTC by gilbertlim

2023-11-03 05:16 UTC, mskangg requested changes
2단계 미션 잘해주셨습니다!
`ParameterizedTest`를 통해 다양한 케이스를 테스트해주셨군요! 👍 
몇가지 피드백 드렸으니 확인 부탁드립니다! 🙇

2023-11-03 05:16 UTC, mskangg commented on src/main/java/study/step2/StringAddCalculator.java
> +        }
split 시 1개 이하인 경우 이 로직을 타게 되는데, sum 에서도 동일한 validation을 호출하고 있네요!
sum() 에 NumberFormatException 캐치를 추가해서 처리하는건 어떠신가용? 🤔

2023-11-03 05:16 UTC, mskangg commented on src/main/java/study/step2/StringAddCalculator.java
> +        }
matcher가 되던 안되던, 결국 sum() 를 호출하고 있군요!
`findDelimiter()` 메서드를 만들어서 리팩토링이 가능해보입니다!

```java
private static String findDelimiter(String text) {
    Matcher m = CUSTOM_DELIMITER_PATTERN.matcher(text); 
    if (m.find()) { 
        return DEFAULT_DELIMITER + '|' + m.group(1); 
    } 
    return DEFAULT_DELIMITER; 
}
```

```suggestion
        String delimiter = findDelimiter(input);
        String[] split = input.split(delemiter);
	return sum(split);
```

2023-11-03 15:14 UTC, gilbertlim commented on src/main/java/study/step2/StringAddCalculator.java
> +        }
메서드를 분리하는데 도움이 많이 되었습니다.
findDelimiter()에서 custom delimiter (m.group(1)) 만 추출하고 끝내기에는 너무 아까워서
target이되는 string(m.group(2))을 구해 split 까지 처리하도록 하고, 함수명을 split()으로 변경했습니다.

2023-11-03 15:17 UTC, gilbertlim commented on src/test/java/study/step2/StringAddCalculatorTest.java
> +        });
수정했습니다!

2023-11-03 15:25 UTC, gilbertlim commented on src/main/java/study/step2/StringAddCalculator.java
> +        }
try...catch 가 indent를 잡아먹기도 하고
sum()는 인자가 int인데, NumberFormatException은 string -> int 형변환이 일어날 때 발생해서 같이 처리하기어려웠습니다ㅜㅜ

2023-11-04 02:15 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요 👍 
그럼 이제 다음 단계 진행해주세요~! 🔥

2023-11-04 02:15 UTC, merged