Step2 PR입니다.
next-step/java-racingcar pull request #4900
Opened 2023-11-03 06:35 UTC by beyondorder

안녕하세요.
'2단계 - 문자열 덧셈 계산기' pr입니다.

custom_delimiter가 존재하는 경우에 대한 케이스 분리를 더 깔끔하게 하고자 하는 고민이 있었습니다.
더 나은 방향에 대해 조언부탁드리겠습니다.

감사합니다.

2023-11-03 15:21 UTC, shared-moon requested changes
석현님 안녕하세요 ~ 2단계 미션 잘 진행 해 주셨네요
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드립니다!
고생 많으셨어요 ! 🔥

2023-11-03 15:21 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +        if(isBlank(s)) return 0;
코드 블럭은 생략하면 예기치 않은 동작을 할 수가 있어 되도록이면 같이 써주는게 좋을 것 같아요 ~

2023-11-03 15:21 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +    static final String CUSTOM_DELIMITER_REGEX = "(\\/\\/)(.*)(\\n)(.*)";
prefix는 굳이 그룹으로 묶을 필요가 있을까요 ?

2023-11-03 15:21 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +    private static boolean isBlank(String s) {
null은 Blank로 보기는 좀 애매한 것 같습니다. null도 포함해서 보통 isEmpty 정도로 표현합니다 ~

2023-11-03 15:21 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +    private static int[] IntArrayFromStrNumbersArray(String[] numbers) {
자바의 메서드 네이밍은 lowerCamelCase를 따르고 있어요 ~

2023-11-03 15:21 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +        Arrays.stream(numbers).forEach(StringAddCalculator::throwExceptionIfMinusValue);
이거 한번 더 돌 필요 없이 위에서 int로 만들어줄때 체크하면 되지 않을까요 ?

2023-11-04 01:09 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +    public static int add(String s) {
s대신 input 으로 반영해보겠습니다.

2023-11-04 01:09 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +    static final String CUSTOM_DELIMITER_REGEX = "(\\/\\/)(.*)(\\n)(.*)";
1,3번째 그룹은 사용하지 않으므로 해제하겠습니다.

2023-11-04 01:11 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +        return customDelimiterRegexMatcher.group(BODY_GROUP_NUMBER).split(customDelimiter);
재성님의 첫강의에서 극단적인 메소드 분리를 시도해보라고 하셔서 홀린듯이 파편화해버렸네요.
이 메소드 외에 한가지 일만 하는 다른 메소드도 파편화하지 않고 인라인 반영하겠습니다.

2023-11-04 01:11 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +    private static String[] getStrNumbers(String s) {
static 제거하였습니다.

2023-11-04 01:11 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +    private static boolean isBlank(String s) {
isEmpty로 변경반영하겠습니다.

2023-11-04 01:12 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +    private static int[] IntArrayFromStrNumbersArray(String[] numbers) {
lowerCamelCase 로 작성한다고 한건데 오타 작성하였네요. 찾아주셔서 감사합니다.

2023-11-04 01:13 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +        Arrays.stream(numbers).forEach(StringAddCalculator::throwExceptionIfMinusValue);
반영하였습니다.

2023-11-04 01:22 UTC, beyondorder commented on src/main/java/study/StringAddCalculator.java
> +        return customDelimiterRegexMatcher.find();
이 부분에 조언을 얻고자 합니다.

- 계산기 입력에 **커스텀구분자가 포함된 경우와 포함되지 않은 두가지 케이스**가 있다
- 두 케이스를 구분하여 배열을 추출하기 위해서 정규식을 통해 분기 처리가 필요하다.

말씀주신 것처럼 해당 메소드에서 구분자를 리턴하더라도 상위레벨에서는 분기가 필요하지 않을까 싶은 의견입니다.

제가 생각하지 못한 방향이 있다면 조언 부탁드립니다.

2023-11-04 15:09 UTC, shared-moon approved these changes
석현님 안녕하세요 ~
피드백 반영 잘 진행 해 주셨네요!
이번 미션은 여기서 머지 하도록 하겠습니다.
고생 많으셨어요!

2023-11-04 15:09 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +            throw new RuntimeException("Minus Value Error !!!");
좀 더 디테일한 예외를 사용하는건 어떨까요 ~?
그리고 메세지가 약간 이해가 잘 안되는 것 같아요. 음수를 허용하지 않는다라는 뜻이 더 드러나면 좋을 것 같습니다.

+ 굳이 예외 메세지가 영어일 필요는 없을 것 같아요..!

2023-11-04 15:09 UTC, shared-moon commented on src/main/java/study/StringAddCalculator.java
> +        return customDelimiterRegexMatcher.find();
오 말씀하신게 맞습니다 ~ 커스텀 구분자가 있는 경우 입력값도 달라서 분기가 한번은 있어야 할 것 같아요!
이전에 그냥 find()만 하는걸 간과하고 boolean 리턴값만 보고 굳이 한번 더 리턴할 필요 없어보여서 저렇게 말한 것 같아요!
석현님이 이해하신게 맞습니다!

2023-11-04 15:09 UTC, merged