Step2 문자열계산기 테스트 + step1 수정사항
next-step/java-racingcar pull request #4902
Opened 2023-11-03 08:17 UTC by jmnl225

안녕하세요!
지난번에 step1의 수정사항과 step2 문자열 계산기 미션을 올리려고합니다.

그런데 이번에도 저의 한계를 많이 확인하게 되었습니다...ㅠㅠ

1. negativeException() 메소드에서 throw new RuntimeException(); 을 해주었는데도 테스트의 splitAndSum_negative()를 통과하지 못했습니다. ㅠㅠ 혹시 그 이유를 알 수 있을까요? 

2. 분명.. 어제 저녁에 리팩토링 하는 방법을 배웠는데 직접 해보려니 쉽지 않네요 ㅠㅠ.. 더 할 수 있을 것 같은데 막상 함수로 바꿔보니 return을 어떻게 처리해야할지 찾지 못했습니다.

수정은 하고싶은데 더이상 손을 대지 못하고 PR드립니다. ㅠㅠ!

2023-11-03 15:53 UTC, jmnl225 commented on src/main/java/study/StringAddCalculator.java
> +            if (s.isEmpty()){
이 부분을 리팩토링 해야할 것 같은데 손을 대지 못했습니다...

2023-11-04 02:12 UTC, ohtaeg requested changes
2단계 미션도 잘해주셨어요! 👍 피드백 반영도 잘해주셨구요!! 👍 
다음 미션을 진행하기전에 같이 고민해보면 좋을 포인트들이 있어서 Request changes 하였습니다..!
주셨던 질문에 대해 코멘트 및 리뷰를 드렸는데 확인해주신 후 반영하여 재요청주시면 감사하겠습니다 :)
즐거운 주말 화이팅입니다 🔥

2023-11-04 02:12 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +            }
정규 표현식이 개선되면 이 조건문은 필요 없어질 것 같네요 😄

2023-11-04 02:12 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +    private static int sum(String[] stringList) {
> 분명.. 어제 저녁에 리팩토링 하는 방법을 배웠는데 직접 해보려니 쉽지 않네요 ㅠㅠ.. 더 할 수 있을 것 같은데 막상 함수로 바꿔보니 return을 어떻게 처리해야할지 찾지 못했습니다.

리팩토링이 많이 어려운 부분이죠 ㅠㅠ
리팩토링을 해야하는 신호는 크게 다음과 같다고 생각하는데요!

1. 테스트를 못하는 구조는 리팩토링이 필요한 신호
2. 메서드가 2가지 이상의 기능을 수행하고 있을 때
3. 메서드가 하고자하는 기능과 파라미터가 모순이 있을 때

현재 잘해주셔서 테스트가 가능하지만 메서드들이 2가지 이상의 일을 수행하고 있으며
기능과 파라미터의 불일치 모순이 조금 보이는 것 같아요 👀 

가령 sum()을 해준다는건 숫자들의 합을 구해줘야하는데 파라미터가 String 배열을 받음으로써
정수로 parsing 해주는 기능이 추가되는 구조 같아요..!
메서드를 단순하게 만드는 방향으로 리팩토링을 진행해보시면 어떨까요 :) ?

```suggestion
    private static int sum(int[] numbers) {
```

2023-11-04 02:12 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +        return sum(stringList);
변수 명에 String과 같은 타입, 자료형 (List)을 네이밍에 넣는 것은 개인적으로 권장 드리지 않습니다 :)
변수 명에 자료형을 쓰지 않아도 타입을 통해 충분히 어떤 변수인지 파악이 가능하다고 생각하며
만약 타입 변경시 변수 명도 변경해야되는 관리 포인트가 증가하는 단점도 존재한다고 생각합니다! ㅎㅎ

2023-11-04 02:12 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +            throw new RuntimeException();
동료 개발자가 봤을 때 어떠한 이유로 예외가 발생했는지 메시지도 추가해주시면 좋을 것 같아요 😄

2023-11-04 02:12 UTC, ohtaeg commented on src/test/java/study/SetTest.java
> -        //???
피드백 반영 👍

2023-11-04 02:12 UTC, ohtaeg commented on src/test/java/study/StringTest.java
> +        assertAll(
assertAll 활용 👍 👍

2023-11-06 07:46 UTC, jmnl225 commented on src/main/java/study/StringAddCalculator.java
> +public class StringAddCalculator {
질문 감사합니다!
생각도 못한 부분이라 이번 기회를 통해 static 메서드와 인스턴스 메서드에 대해 알아보았습니다.
static만 선언되어 있는 static class는 어떤 단점들이 있는지도 함께 생각해보게 되었습니다.
1. static만 선언되어있다면 인스턴스 변수 사용을 할 수 없습니다.
2. GC가 관리하지 않기때문에 메모리 사용량이 증가할 수 있습니다.
3. 외부에서 인스턴스로 생성하는 의미가 없습니다.. 

장점으로는 프로젝트에서 자주 사용하는 기능을 정적 메서드로 구현해두면 효율적인 사용이 가능할 것 같습니다!

2023-11-06 11:43 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨어요 👍 
소소한 코멘트들을 드렸는데 확인해주시면 감사하겠습니다!
다음 미션도 화이팅입니다 🔥
갑자기 날씨가 변덕스럽게 추워졌습니다. 감기 조심하시구요 😄

2023-11-06 11:43 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +    private StringAddCalculator() {
인스턴스 생성 못하도록 👍

2023-11-06 11:43 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +        return sum(getNumbers(customDelimiter(text)));
메서드 분리 👍

2023-11-06 11:43 UTC, ohtaeg commented on src/main/java/study/StringAddCalculator.java
> +    private static String[] customDelimiter(String text){
해당 메서드 명을 통해 유추하기론 커스텀 구분자로 문자열을 구분하는 기능인 것 같지만
실제 내부에서는 기본 구분자도 구분하는 기능을 수행하고 있네요 :)
메서드 명을 좀 더 명확하게 하시거나 기능을 더 분리하면 좋을 것 같아요 😄

2023-11-06 11:43 UTC, ohtaeg commented on src/test/java/study/StringAddCalculatorTest.java
> +    public void splitAndSum_null_또는_빈문자() {
null과 빈 공백에 대한 테스트는 다음과 같은 어노테이션들을 활용해보는 것도 좋을 것 같아요 😄
`@NullSource`
`@EmptySource`
`@NullAndEmptySource`

2023-11-06 11:43 UTC, merged