🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #4919
Opened 2023-11-04 03:22 UTC by hyeonjinnoh

# 🚀 3단계 - 자동차 경주

## 기능 목록
- [x]  사용자로부터 자동차 대수를 입력 받을 수 있다
- [x]  사용자로부터 시도할 회수를 입력 받을 수 있다
- [x]  입력받은 회수만큼 게임이 진행된다
- [x]  0부터 9사이 random 값을 생성할 수 있다
- [x]  random 값이 4 이상일 경우 자동차는 전진할 수 있다
- [x]  자동차 상태를 출력할 수 있다

## 결과
![image](https://github.com/next-step/java-racingcar/assets/111402515/e3c86133-578d-40ca-aee4-af3b18d39855)

2023-11-04 16:32 UTC, shared-moon requested changes
현진님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
전체적으로 깔끔하게 잘 만들어 주셨는데, 한 번 고민해보면 좋을 것 같은 내용이 있어 코멘트를 남겨뒀습니다.
확인 후 리뷰 재요청 부탁드려요!

2023-11-04 16:32 UTC, shared-moon commented on src/main/java/step3/Game.java
> +    public Game(int numberOfCars, int numberOfTry) {
테스트에서만 사용되는 메서드/생성자는 가급적 지양하는게 좋습니다!

2023-11-04 16:32 UTC, shared-moon commented on src/main/java/step3/Game.java
> +        this(InputView.numberOfCars(), InputView.numberOfTry());
만약 InputView나 ResultView가 입력, 출력하는 방식이 변경된다면 이런 부분들은 전부 다 변경에 영향을 받지 않을까요 ?

2023-11-04 16:32 UTC, shared-moon commented on src/main/java/step3/Game.java
> +    public List<Car> cars() {
이것도 테스트에서만 사용되고 있는 것 같아요!

2023-11-04 16:32 UTC, shared-moon commented on src/main/java/step3/Game.java
> +    public void play() {
이 메서드는 테스트가 없는 것 같아요 ~

2023-11-04 16:32 UTC, shared-moon commented on src/test/java/step3/CarTest.java
> +        assertThat(car.position()).isIn(NOT_MOVED, MOVED);
이 메서드는 움직이거나 안움직이거나 둘 중에 하나가 결과로 나와야 하는데, 지금 검증부분에서 잡고 있는게 두가지 경우 전부라서 테스트로서 의미가 좀 없을 것 같아요.
랜덤 요소에 의해 동작하는거라 테스트가 좀 까다로워서 그러셨을 것 같은데요, 추상화를 이용하여 실제 구현부를 주입받는 식으로 만들면 테스트에서도 원하는 결과가 나오도록 컨트롤 할 수 있지 않을까요 ?

2023-11-04 16:32 UTC, shared-moon commented on src/test/java/step3/RandomUtilTest.java
> +    public void 랜덤값_0부터_9사이() {
현재 검증 로직은 해당 클래스에서 랜덤 조건이 바뀌더라도 성공 할 수도 있는 테스트로 보입니다.
랜덤 자체를 테스트하는거라 좀 애매하긴 한데, 저는 랜덤요소가 들어가는 경우 모수를 여러번 해서 확률을 좀 높이는 방법도 사용 한 기억이 있네요..!

2023-11-05 06:40 UTC, hyeonjinnoh commented on src/test/java/step3/CarTest.java
> +        assertThat(car.position()).isIn(NOT_MOVED, MOVED);
기존에 move 함수 내에서 직접 랜덤 값을 생성하고, 그에 따라 이동하도록 구현했었는데요
RandomUtil 내부에 게임을 위한 RANDOM_BOUND = 10을 static final 변수로 가지는게 올바르지 않다 생각하여 RandomUtil의 bound를 외부에서 주입하는 형태로 변경했으며, 
RacingGame에서 bound 10을 주입한 RandomUtil을 가지고 랜덤값을 생성하여 Car의 move 함수에 전달하도록 변경했습니다

2023-11-05 06:44 UTC, hyeonjinnoh commented on src/test/java/step3/RandomUtilTest.java
> +    public void 랜덤값_0부터_9사이() {
해당 테스트는 랜덤 라이브러리 자체에 대한 테스트가 아닌가 싶어 의미가 없다 판단하여 제거했습니다

2023-11-05 06:45 UTC, hyeonjinnoh commented on src/main/java/step3/Game.java
> +        this(InputView.numberOfCars(), InputView.numberOfTry());
InputView의 입력 방식이 변경된다는 말씀은 예를 들어 numberOfCars 함수에 매개변수가 추가되는 등의 변화가 있을 수 있다는 뜻으로 받아들였고, 따라서 Game 외부에서 사용자로부터 값을 입력 받은 후 Game에 주입하는 방식으로 변경했습니다

2023-11-05 06:47 UTC, hyeonjinnoh commented on src/main/java/step3/Game.java
> +    public Game(int numberOfCars, int numberOfTry) {
아래 코멘트와 같이 Game에 주입하는 방식으로 변경하며 이 부분은 해결된것같습니다

2023-11-05 06:47 UTC, hyeonjinnoh commented on src/main/java/step3/Game.java
> +    public List<Car> cars() {
Game 클래스 내에서 자동차를 생성하도록 했었는데, 이 부분을 CarGenerator로 분리했습니다

2023-11-05 06:53 UTC, hyeonjinnoh commented on src/main/java/step3/Game.java
> +    public void play() {
게임 실행 후 자동차들의 위치 범위를 판단하는 테스트코드를 추가로 작성했습니다

또한, 지금 요구사항에서는 그렇게 필요한 부분은 아니라는 생각도 들긴하지만.. 일반적인 게임이 가져야하는 변수와, 자동차 게임이 가지는 변수가 다르다 생각되어 기존 Game 클래스를 추상 클래스로 변경하고 RacingGame 클래스를 새로 작성했습니다

2023-11-05 16:25 UTC, shared-moon approved these changes
현진님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 진행 전 확인해보시면 좋을 것 같아요!
이번 미션은 여기서 머지 하도록 하겠습니다.
고생 많으셨어요!

2023-11-05 16:25 UTC, shared-moon commented on src/test/java/step3/RacingGameTest.java
> +    public void 게임_결과() {
> '추상화를 이용하여 실제 구현부를 주입받는다'의 의도를 제대로 파악한게 맞을까요?

현재는 랜덤요소때문에 테스트가 좀 부정확한 것 같은데요
RandomUtil에서 랜덤값을 받는 부분을 MoveStrategy 같은 인터페이스로 추상화시켜서 외부에서 전략을 받도록 만들면, 테스트할때는 무조건 4 이상인 경우, 4 미만인 경우가 테스트 될 수 있어서 말씀 드렸었습니다~

물론 지금은 CarTest에서 값에 따른 이동여부가 테스트 되고 있어 여기서는 단순히 호출만 봐도 충분할 것 같긴 합니다 ~

그래서, 차라리 무조건 성공하는 범위로 테스트하기보단 Car를 mocking 하거나 List<Car> 를 일급컬렉션으로 묶어서 mocking 하는걸로 호출만 테스트 해보는건 어떨까 하는 생각이 드네요!

2023-11-05 16:25 UTC, shared-moon commented on src/test/java/step3/CarTest.java
> +    @ValueSource(ints = {0, 1, 2, 3})
굳이 다 볼 필요 없이 엣지 값만 테스트해도 되지 않을까요 ~?

2023-11-05 16:26 UTC, merged