2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #4932
Opened 2023-11-04 09:35 UTC by gkssk4163

2단계 구현 완료해서 피드백 요청드립니다 😊

**문자열 덧셈 계산기(StringAddCalculator) 구현**
- 문자를 구분자로 나눠 각 숫자를 더하는 기능 구현
- 커스텀 구분자를 추출하는 기능을 분리하기 위한 SeparatorManager 구현

Q1. for문 안에 if문이 한 줄로 들어가 있는 부분이 있는데 이것도 2 indent 로 보나요?
Q2. 커스텀 구분자를 추출하는 기능을 문자열덧셈계산기와 분리하고 싶어서 Class를 따로 만들어봤는데요, 클래스 분리를 저렇게 하는 것이 맞는지 잘 모르겠습니다 ㅎ

2023-11-05 06:48 UTC, mskangg requested changes
2단계 미션 잘구현해주셨습니다! 👏
몇가지 피드백 남겨드렸으니 확인부탁드려요! 🙇‍♂️

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/SeparatorManager.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(str);
Pattern.compile()은 매번 새로운 인스턴스를 생성하기에 static 변수로 선언하는게 좋습니다 😄
해당 구현부를 살펴보세요!

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/SeparatorManager.java
> +public class SeparatorManager {
Clean Code 2장 의미 있는 이름에 나오는것처럼 클래스명을 Manager 와 같은 모호한 단어를 사용하지 않는것이 좋아보입니다! 
https://velog.io/@dnr6054/Clean-Code-2-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84

이 클래스는 문자열에서 구분자를 찾는 클래스이니 `StringSeparator`나 `SeparatorFinder` 와 같이 의미를 명시해주는 것도 좋아보여요!
(클래스명, 변수명, 메서드명 짓는게 제일 어려운것 같습니다 😂)

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/SeparatorManager.java
> +    private static ArrayList<String> separators = new ArrayList<>();
separators 를 static 으로 선언해주셨네요!
static 변수를 공용변수로 사용한다면, 멀티쓰레드환경인 java에서 문제가 발생할 확률이 높습니다! 🤔
synchronized 를 사용할 수 있지만, 지금은 변수를 빼는게 좋아보이네요!

그리고 커스텀구분자가 공용으로 사용되는 구조기 때문에 처음 실행과 두번째 실행에서 원하는 결과가 다르게 나올 것 같아요!
예를 들어 처음 함수 호출시 커스텀구분자가 `;` 였고 두번째 실행시 `!` 이거 였다면, input이 `//;\n1!2;3` 이어도 통과가 되는 구조로 되어있습니다!

요구사항이 커스텀 구분자를 누적하는게 아닌 input에 대한 커스텀 구분자가 사용되는 것이기 때문에 변경이 필요해보입니다! 🧐

//;\n1;2;3 = 6 (0)
//;\n1;2!3 = error

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +        return sum(toInts(split(str)));
💯

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +        }
이부분이 인덴트가 2군요!
어떻게하면 줄일 수 있을까요? 🤔

2023-11-05 06:48 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +            if (!isBlank(strNumbers[i])) numbers[i] = Integer.parseInt(strNumbers[i]);
여기도 인덴트를 줄여보아요!

2023-11-05 06:48 UTC, mskangg commented on src/test/java/step2/StringAddCalculatorTest.java
> +class StringAddCalculatorTest {
같은 메서드를 테스트한다면 junit5 의 `@ParameterizedTest`를 사용해보는건 어떠신가요?

https://velog.io/@ohzzi/junit5-parameterizedtest

2023-11-05 06:49 UTC, mskangg commented
> Q1. for문 안에 if문이 한 줄로 들어가 있는 부분이 있는데 이것도 2 indent 로 보나요? 
> Q2. 커스텀 구분자를 추출하는 기능을 문자열덧셈계산기와 분리하고 싶어서 Class를 따로 만들어봤는데요, 클래스 분리를 저렇게 하는 것이 맞는지 잘 모르겠습니다 ㅎ

1. 넵 이것도 2 indent 입니다!
2. 클래스구분을 해주셨는데, 어색하지 않은것 같아요! 잘 나눠주신것 같습니다. 다만, 리뷰에도 남겨드렸다시피 네이밍은 고민해보아요!

2023-11-05 13:46 UTC, gkssk4163 commented on src/main/java/step2/SeparatorFinder.java
> +        customSeparator = null;
static 변수를 공용 변수로 사용된 부분을 제거하고 이렇게 변경해보았습니다.
static을 제거하긴 했지만 커스텀구분자를 저장히기 위해 선언한 `private String customSeparator;` 해당 부분 정보가 계속 유지되어서 `findCustomSeparator()`에서 `customSeparator = null;` 이런식으로 초기화를 진행해주었습니다.
뭔가 좋은 방법이 아닌 것 같다고 느껴져서 다른 방식이 있는지 궁금합니다! 😂

2023-11-06 10:56 UTC, mskangg requested changes
피드백 반영 잘해주셨네요!! 👏 
바로 머지하기엔 아쉬워서 한번만 더 고민해주세요! 🙇‍♂️
DM도 괜찮습니다 😁

2023-11-06 10:56 UTC, mskangg commented on src/main/java/step2/SeparatorFinder.java
> +        customSeparator = null;
`findCustomSeparator()` 메서드 명만 보면 customSeparator 를 리턴해야 할것 같은데, 로직을 보아하니 구분해야할 문자열을 넘기고 있네요 🤔
`customSeparator` 를 인스턴스 변수로 꼭 필요한가? 에 대해 고민이 필요해보입니다!

음.. 🤔
저라면 pattern.matcher()를 두번 하더라도 메서드를 나눠 활용할 것 같아요!
findCustomSeparator()
findText()
와 같이 메서드를 두번 호출하는 것도 방법이될 거라 생각합니다!

또 다른 방법은 class 를 추가하여 구분자와 텍스트를 내부변수로 갖는 dto를 구현하여 리턴하는 것도 방법이 될 것 같네요!

2023-11-06 10:56 UTC, mskangg commented on src/test/java/step2/StringAddCalculatorTest.java
> +    @MethodSource({"nullOrEmptyString", "invalidInputs"})
💯

2023-11-06 14:17 UTC, gkssk4163 commented on src/main/java/step2/StringAddCalculator.java
> +        StringAddCalculatorDto calcDto = sf.getStringAddCalculatorDto(str);
제시해 주신 방법 두 가지 중에 구분자와 텍스트를 내부변수로 갖는 dto를 구현하는 방식으로 수정해보았습니다!
text와 customSeparator를 찾는 함수를 각각 만드는 것보다 하나의 함수에서 한번에 찾아서 dto에 저장해 놓는 것이 유지보수에 더 용이할 것 같아서 dto로 구현해보았습니다.

이전에 구현한 `findCustomSeparator()` 함수는 구분자를 별도 내부변수로 저장하고 구분자를 제외한 text를 리턴해서 함수의 기능이 명확하지 않았는데, dto를 사용해서 구현하니 text와 구분자를 저장해두고 필요한 곳에서 꺼내서 사용할 수 있게 되어서 기능이 좀 더 명확해진 것 같습니다. 😊👍

2023-11-07 02:22 UTC, mskangg approved these changes
피드백 반영 잘해주셨어요! 👍 
그럼 재밌는(?) 자동차 경주 미션 시작해주세요!

2023-11-07 02:22 UTC, merged