🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #4940
Opened 2023-11-04 14:04 UTC by hoon25

## 내용
- Step2 리뷰반영 
- Step3 기능구현

Step2리뷰는 PR에 댓글 달아두었습니다.(https://github.com/next-step/java-racingcar/pull/4892)

## 기타
- 계산기는 문자열 파싱 부분을 책임사슬패턴으로 구현
- 레이싱은 자동차 이동기능을 전략패턴으로 구현

헤당 디자인패턴을 적용시키는 것은 처음이라 이상한 부분이 많은것 같네요 🥲
리뷰 감사합니다!!

2023-11-04 17:37 UTC, catsbi requested changes
창훈님 본격적인 자동차 경주 미션입니다! 👍 

저번 미션 리팩토링도 잘 해주셨고 자동차 경주도 고민 많이 하신것 같네요!
전체적으로 크게 문제는 없어보이나 고민해보면 좋을만한 부분들이 좀 보여서 피드백 남겨드렸어요. 확인 후 리뷰요청 해주세요!

2023-11-04 17:37 UTC, catsbi commented on src/main/java/calculator/CalcNumbers.java
> +            throw new RuntimeException();
저는 명시적으로 미션에서 지정하는게 아닌이상 RuntimeException, Exception, Throwable과 같은 최상위 예외를 사용하는것을 비권장드립니다. 어째서일까요?! 한 번 알아보면 좋을 것 같아요!

2023-11-04 17:37 UTC, catsbi commented on src/main/java/calculator/TextCalculator.java
> +import calculator.text_split.concrete.*;
import wildcard(*)를 사용하지 않기를 권장드립니다. 
소스파일에서 불러오는 모듈 파악의 가독성을 낮출수 있거든요. IDE의 code style 의 indent쪽에서 바꿔줄 수 있을꺼에요!

2023-11-04 17:37 UTC, catsbi commented on src/main/java/calculator/text_split/concrete/CustomDelimiterSplit.java
> +package calculator.text_split.concrete;
package 이름은 camel이나 snake case 명칭을 따르지 않습니다. 그냥 textsplit이라고 하셔도 될 것 같아요 ㅎㅎ

2023-11-04 17:37 UTC, catsbi commented on src/main/java/calculator/text_split/concrete/CustomDelimiterSplit.java
> +    private static final Pattern CUSTOM_PATTERN = Pattern.compile(CUSTOM_DELIMITER_PATTERN);
💯

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Car.java
> +    private Integer position;
굳이 이유가 없다면 최대한 primitive 타입을 사용하기를 권장드릴게요! Integer같은 Wrapper타입은 기본저긍로 컬렉션등에서 제네릭 타입으로 사용하기 위한 객체로써 primitive값과 항상 오토박싱 이슈로 성능을 신경써야하는 관리 포인트만 늘어날 수 있거든요!

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/CarRace.java
> +        }
이건 비즈니스 로직 + 출력 로직을 모두 컨트롤러 계층에서 책임지고 있는걸로 보이네요! 
경주는 온전히 서비스에 맡기고 응답받은 경기 결과를 출력 계층에 전달만 해주는걸로 컨트롤러의 역할은 끝 아닐까요?!

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Cars.java
> +public class Cars {
일급 컬렉션 👍

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Cars.java
> +    private final List<Car> cars;
이런 컬렉션 타입의 필드는 필드 초기화를 해주면 좀 더 null safe한 상태로 만들어줄 수 있습니다.

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Cars.java
> +    }
다른 협업개발자가 외부에서 다음과 같은 코드를 작성하면 어떻게 될까요? 

```java
cars.getCars().clear()
```

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Cars.java
> +    }
정적 팩토리 함수를 사용하셨네요 👍

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/Track.java
> +        cars = makeCars(carCount, new RandomMoveStopStrategy());
트랙을 만들 때 마다 전진 전략을 새로 만들어야 할까요?

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/move_strategy/RandomMoveStopStrategy.java
> +        return i >= 4;
매직 넘버는 상수로 분리해주면 가독성을 높힐 수 있을 것 같아요. 
그냥 4보다 큰 경우 true인 것과 기준치보다 높을 경우라고 작성된 것은 가독성에서 분명히 차이가 있죠 ㅎㅎ

2023-11-04 17:37 UTC, catsbi commented on src/main/java/car_racing/move_strategy/RandomPoint.java
> +    public static final Random random = new Random();
Radom을 쓰려면 차라리 ThreadLocalRandom을 써보는건 어떨까요? 
참고: https://velog.io/@sojukang/Random-%EB%8C%80%EC%8B%A0-ThreadLocalRandom%EC%9D%84-%EC%8D%A8%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

2023-11-04 17:37 UTC, catsbi commented on src/test/java/car_racing/README.md
> +- [x] 화면에서 값을 입력한다.
readme를 좀 더 상세하게 작성하면 바로 테스트 코드를 작성할수 있을꺼에요. 👍

2023-11-05 12:30 UTC, hoon25 commented on src/main/java/calculator/CalcNumbers.java
> +            throw new RuntimeException();
내가 직접 발생시킨 예외인지 시스템이 발생시킨 예외인지 구별하기 어려운 점이 클 것 같아요! 
Unchecked Exception인 RuntimeException을 상속받아서 구현했습니다!

2023-11-05 12:58 UTC, hoon25 commented on src/main/java/car_racing/Track.java
> +        cars = makeCars(carCount, new RandomMoveStopStrategy());
`private static final MoveStrategy moveStrategy = new RandomMoveStopStrategy();`
상수로 두었는데 적절할까요?

2023-11-05 13:12 UTC, hoon25 commented on src/main/java/car_racing/Cars.java
> +    }
`    public List<Car> getCars() {
        return Collections.unmodifiableList(cars);
    }
`
로 불변객체를 받아서 수정할 수 없게 변경했는데 괜찮은가요?

2023-11-05 13:14 UTC, hoon25 commented on src/test/java/car_racing/README.md
> +- [x] 화면에서 값을 입력한다.
다음단계에 좀 더 꼼꼼한 README 작성 시도해볼게요!

2023-11-05 13:15 UTC, hoon25 commented on src/main/java/car_racing/move_strategy/RandomMoveStopStrategy.java
> +        return i >= 4;
`MINIMUM_MOVABLE_DISTANCE`로 상수로 처리했어요!

2023-11-05 13:33 UTC, catsbi commented on src/main/java/car_racing/Cars.java
> +    }
굳굳! 잘하셨습니다

2023-11-05 13:34 UTC, catsbi commented on src/main/java/car_racing/Track.java
> +        cars = makeCars(carCount, new RandomMoveStopStrategy());
네 그것도 괜찮은 생각입니다 ㅎㅎ 
그런데 SOLID원칙도 계속 같이 고민해보시면 좀 더 다양한 아이디어들도 나올테니 고민해보세요. 
(미션과는 무관하기에 여유가 될 때만.. ㅎㅎ)

2023-11-05 13:58 UTC, hoon25 commented on src/main/java/car_racing/CarRace.java
> +        }
TrackHistory 클래스를 두고 출력로직을 분리하였습니다.(차들의 1회 `run()`마다의 상태를 저장하는 클래스)

여기서 깊은 복사로 구현을 했어야 해서 [refactor(UI) : UI계층 분리를 위해 TrackHistory 사용](https://github.com/next-step/java-racingcar/pull/4940/commits/8f23864c873c95aae3ea34f0b082134a6c07a134)
로 작업을 했는데 clone방식이 적절한지 확인 부탁드릴게요!

2023-11-05 14:01 UTC, hoon25 commented on src/main/java/car_racing/move_strategy/RandomPoint.java
> +    public static final Random random = new Random();
처음 알게된 클래스네요! 적용 완료했습니다!

2023-11-05 14:47 UTC, catsbi commented on src/main/java/calculator/CalcNumbers.java
> +            throw new RuntimeException();
네 추가하자면 제가 언급한 예외객체들은 검사/비검사 예외의 최상위 객체들로써 모든 검사 / 비검사 예외를 포함하고 있습니다. 그래서 실질적으로 예외가 발생해서 그 예외 내용을 클래스가 표현하려해도 최상위 예외로 번역되며 디버깅시 실제 어떤 예외가 발생했는지 파악하기가 힘들어지는 문제가 있기 때문이에요

2023-11-05 15:08 UTC, catsbi approved these changes
창훈님 피드백 잘 반영해주셨어요 👍 
몇가지 추가적인 피드백 남겨드렸으니 확인해보시고 다음 미션에서 같이 고민해보면 좋을 것 같아요. 머지하도록 하겠습니다!

2023-11-05 15:08 UTC, catsbi commented on src/main/java/carracing/Cars.java
> +    public Cars copyOf() {
여기때문에 clone을 사용하셨군요! 
고민해보면 좋을게 있어요. 이 함수와 사용하는 사용처를 보면 View Layer로  Car라는 도메인을 그대로 반환하고 있는데 이보다는 Response객체(Ex: RacingHistory)등을 응답하며 외부에 노출해도 좋을 정보들만 담도록 하는게 좋지 않을까요?!

2023-11-05 15:08 UTC, catsbi commented on src/main/java/carracing/Track.java
> +public class Track {
도메인 영역으로 보이는데 dto로 보이는 필드를 가지고 있네요. 인스턴스 변수에 dto를 가지지 않도록 하는게 어떨까요?

2023-11-05 15:08 UTC, catsbi commented on src/main/java/carracing/move_strategy/RandomPoint.java
> +        return random.nextInt(10);
매직 넘버는 상수로 분리해주면 어떨까요? Ex: Threshold

2023-11-05 15:08 UTC, merged