2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #4942
Opened 2023-11-04 14:34 UTC by sunga08

2단계 미션 PR입니다. 

커스텀 구분자를 추출하는 부분에서 더 나은 방법은 없을지, 제가 구현한 방식에서 리팩토링을 더 할 수 있을것 같으면서도 방법이 떠오르지 않았는데.. 이 부분에 대해서도 코멘트 주실게 있으면 부탁드리겠습니다! 감사합니다.

2023-11-05 11:13 UTC, wooobo requested changes
안녕하세요 성아님!

2단계 잘진행해주셨습니다! 
코멘트 남겨 놓았는데 확인 후 재요청 부탁드려요! 🙏 

그럼 즐거운 일요일 저녁되세요~ 😄

2023-11-05 11:13 UTC, wooobo commented on README.md
> +* [X] 음수를 전달할 경우 RuntimeException 예외가 발생해야 한다. (예 : “-1,2,3”)
요구사항 정리 좋네요!

2023-11-05 11:13 UTC, wooobo commented on src/main/java/calculator/Calculator.java
> +    }
```suggestion
    private static void checkNegative(int number) {
        if(number < 0){
            throw new RuntimeException();
        }
    }
```
`PositiveNumber`가 있다면 해당 객체의 책임을 맡아서 진행할수 있을것 같아요!
양수만 가지는 객체를 만들어보는거죠!

2023-11-05 11:13 UTC, wooobo commented on src/main/java/calculator/Calculator.java
> +        }
```suggestion
        if (text.startsWith("//")){
            String[] result = split(text, "//|\n");
            customDelimiter = result[1];
            text = result[2];

            return sum(toInts(split(text, customDelimiter)));
        }
```

해당 로직을 이해하거나 테스트코드 혹은 전체 로직을 이해해야지 `"//"`,`"//|\n"` 에 대한 의미를 이해할 수 있을것 같아요!
사람이 이해하기 쉽게 의미있는 이름의 변수로 선언해보는건 어떨까요!?

```
public class Calculator {

    public static final String DELIMITER = ",|:";
    public static final String CUSTOM_START_TEXT = "//" ;
```

2023-11-05 11:13 UTC, wooobo commented on src/main/java/calculator/Calculator.java
> +        }
![스크린샷 2023-11-05 오후 8 09 31](https://github.com/next-step/java-racingcar/assets/12059592/9819c5be-0092-441f-946b-83a945ad3457)

변하는것과 변하지 않는것을 잘 고민해보면,
`sum(toInts(split(text, {변하는부분})));`
반복되는 패턴이 보입니다!

그렇다면, 구분자를 추출하는 책임을 가진 메소드가 있으면 로직이 훨씬 간단해지지 않을까요!?

2023-11-05 12:35 UTC, sunga08 commented on src/main/java/calculator/Calculator.java
> -            return sum(toInts(split(text, customDelimiter)));
delimiter 추출 부분만 빼려고 보니 text도 custom delimiter인 경우 따로 추출을 해줘야 해서 메소드로 분리했는데, 분리하고 보니 if 조건이 두 개의 메소드에서 반복되는데.. 이 부분만 하나의 메소드로 만들기엔 어려워보이고.. 이렇게 분리하는게 맞을까요? 😅

2023-11-06 15:01 UTC, wooobo approved these changes
안녕하세요 성아님!

리뷰 늦어져서 죄송합니다.
질문 주신것에 답변 달아놓았습니다!
다음 미션진행하실때 참고해주시면 도움될꺼에요!
궁금하신점있으시면 DM주세요~ ㅎ

그럼 다음미션 기대하겠습니다!

2023-11-06 15:02 UTC, merged