step2 문자열계산기
next-step/java-racingcar pull request #4956
Opened 2023-11-05 09:21 UTC by thxogusrla3

안녕하세요! step2 문자열 계산기 PR입니다.

코드리뷰 감사드립니다!

2023-11-05 10:04 UTC, testrace requested changes
안녕하세요 태현님 😃 
2단계 구현 잘해주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청해 주세요
궁금한 점이나 의견 있으시면 편하게 DM 남겨주세요

2023-11-05 10:04 UTC, testrace commented on README.md
> +- [x] 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw한다.
작은 기능 단위로 목록을 작성해 보셔도 좋을 것 같아요 😃

2023-11-05 10:04 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +    public static int splitAndSum(String text) {
커스텀 구분자와 패턴 객체를 상수로 관리해 주셨네요 👍 
기본 구분자도 상수로 관리할 수 있을 것 같아요 

가독성을 위해 클래스 변수, 멤버 변수, 메서드 사이에 개행을 추가하면 어떨까요?

2023-11-05 10:04 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +        return getSum(stringsToInts(text.split("[,:]")));
파라미터로 다른 메서드를 호출하는 방식은 가독성이나 디버깅이 어려울 것 같아요 😢 
구분자를 기준으로 분리하는 메서드를 분리하면 중복되는 코드도 줄일 수 있을 것 같아요
```java
public static int splitAndSum(String text) {
    ...
    int[] numbers = split(text);
    return sum(numbers);
}
```

2023-11-05 10:04 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +    private static int getSum(int[] values) {
getXX 형식의 메서드명은 getter를 연상하게 되는데요 
int 배열을 합산하는 메서드이니 이름을 sum 으로 해도 좋을 것 같은데 태현님 생각은 어떠신가요?

2023-11-05 10:04 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +    }
이 메서드만 봐서는 숫자 1, 2가 무엇을 뜻하는지 알기 어려울 것 같아요
상수로 치환해서 이름을 부여하면 어떨까요?

2023-11-05 10:04 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +                return false;
메서드명과는 다르게 음수도 숫자가 아니라고 판단하네요
음수를 판단하는 메서드를 분리하면 어떨까요?

2023-11-05 10:04 UTC, testrace commented on src/test/java/calculator/CalculatorTest.java
> +    }
`@ParameterizedTest`와 함께 `@NullAndEmptySource`를 활용해 보시면 좋을 것 같아요

2023-11-05 10:04 UTC, testrace commented on src/test/java/calculator/CalculatorTest.java
> +    }
DisplayName과는 다르게 음수에 대한 테스트는 누락되었네요 😢

2023-11-05 12:03 UTC, thxogusrla3 reviewed
문자열계산기 리뷰내용 수정 후 재요청입니다!

2023-11-05 14:07 UTC, testrace approved these changes
피드백 반영 잘해주셨네요 👍 
코드 포맷과 관련 코멘트 남겼는데 확인 부탁드려요
커밋하시기 전에 reformat code 기능을 활용해 보시면 좋을 것 같아요
다음 단계에서는 [온라인 코드리뷰 요청 3단계](https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md)를 참고하셔서 단계별로 브랜치를 만들어 진행해 주세요
본격적인 자동차 경주 미션 화이팅입니다 🔥

2023-11-05 14:07 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +    }
isNegative 음수인 경우 true를 반환해야 하지 않을까요?
boolean 타입을 리턴하는 경우 코드도 조금 간결하게 줄일 수 있을 것 같아요
```suggestion
    private static boolean isNegative(String text) {
        return Integer.parseInt(text) < 0;
    }
```

2023-11-05 14:07 UTC, merged

2023-11-06 00:34 UTC, thxogusrla3 commented on src/main/java/calculator/Calculator.java
> +            ints[i] = Integer.parseInt(val);
개행 추가하는 부분에 대해선 기준은 없습니다!