3단계 - 자동차 경주 구현
next-step/java-racingcar pull request #4973
Opened 2023-11-05 14:45 UTC by Taegoon

2023-11-06 13:30 UTC, shared-moon requested changes
태군님 안녕하세요 ~
3단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드려요~
고생 많으셨습니다!

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/InputView.java
> +    public static Map<String,String> input(){
Map을 사용하신 이유가 있을까요 ~?
인풋 메서드를 나눠두면 굳이 입력값을 묶을 필요가 없어보입니다!
묶어서 사용 하더라도, 리턴값으로는 새로운 클래스를 정의해서 넘겨주는게 좋지 않을까요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCar.java
> +    @Getter @Setter
저희 미션 진행간 getter setter는 최대한 지양하고 있습니다 :)

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCar.java
> +                moveStr+="-";
DASH도 상수로 뺴는게 어떨까요 ~?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCar.java
> +            if(randomList.get(i).doubleValue()>=4){
Threshold도 상수로 빼는게 좋을 것 같습니다 ~

혹시 double로는 왜 굳이 치환하신걸까요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCar.java
> +    private Map<Integer, Double> randomList;
Map의 변수명은 키가 무슨 의미인지도 나타내주는 게 좋다고 생각합니다. 지금같은 경우는 randomsByStep 같은 느낌으로요!

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarViewMain.java
> +        Map<String,String> inputValue = new HashMap<String,String>();
둘 다 굳이 미리 선언할 필요가 없어보여요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +    public static Map<String,RacingCar> creatCar(String carText, String loopText){
오타가 있는 것 같아요 ~

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +        if(text.contains(".")){
아래에 parseInt로 안잡히는 케이스일까요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +    public static double randomValue(){
이거 리턴값이 왜 double인걸까요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +    public static Map<Integer, Double> creatRandom(int loopNum){
혹시 랜덤값을 미리 만들어서 통째로 넘기시는 이유가 뭘까요 ?
맵을 쓰면서 전체적으로 코드가 굉장히 직관적이지 못한데, 어떤 이점을 얻고자 사용하셨는지가 궁금합니다 ~

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +            car.setDrive(drive);
파라미터를 받는 생성자를 만들면 setter를 제거할 수 있지 않을까요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +        Map<String,RacingCar> carMapList = new HashMap<String,RacingCar>();
가능하면 Map 대신에 의미를 가지는 클래스를 만들어주시는게 좋을 것 같아요 ~

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +    public static int countDrive(Map<Integer, Double> randomListMap){
오 이거 이렇게 할꺼면 map으로 만드는게 아니라 그냥 매 반복문에서 random값으로 체크해서 바로 결과를 리턴하는게 낫지 않나요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/ResultView.java
> +            System.out.println("차량들이 레이싱을 하지 않았습니다.");
이 경우가 나오려면 경기 횟수가 0으로 입력을 받았어야 할 것 같은데요, 그건 앞에서 입력값을 검증하고 있지 않나요 ?

2023-11-06 13:30 UTC, shared-moon commented on src/main/java/study/ResultView.java
> +    public static void result(Map<String,RacingCar> carMapList){
타입은 Map인데 변수명이 List라서 아래에서 읽을 때 헷갈리는 것 같아요 ~

2023-11-06 13:30 UTC, shared-moon commented on src/test/java/study/RacingCarGameTest.java
> +        int result = RacingCarGame.checkValue(null);
Exception 발생인데, 이건 결과가 0일 경우를 체크하고 있는 것 아닌가요 ~?

2023-11-06 13:30 UTC, shared-moon commented on src/test/java/study/RacingCarGameTest.java
> +        assertThatThrownBy(()->RacingCarGame.checkValue("xxxx"))
이건 내부에서만 쓰이는 메서드 아닌가요 ? 왜 public으로 빠져 있을까요 ~?

2023-11-06 13:30 UTC, shared-moon commented on src/test/java/study/RacingCarGameTest.java
> +        double value = RacingCarGame.randomValue();
이건 사실상 Random클래스에 대한 테스트라 굳이 없어도 될 것 같습니다 ~

2023-11-06 13:30 UTC, shared-moon commented on src/test/java/study/RacingCarGameTest.java
> +public class RacingCarGameTest {
테스트 클래스는 각 클래스마다 하나씩 만들어주세요 ~

2023-11-06 15:03 UTC, Taegoon commented
Step3 수정 사항 보완
1. inputCarValue, inputStepValue 분리
2. DASH도 상수, Threshold도 상수
3. Map 변수명 가독성 높게 수정

2023-11-07 09:56 UTC, shared-moon approved these changes
태군님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 두었는데요, 다음 미션 진행 전 확인 부탁드려요~
이번 미션은 머지하도록 하겠습니다.
고생 많으셨어요!

2023-11-07 09:56 UTC, shared-moon commented on src/main/java/study/RacingCarGame.java
> +    private static Map<Integer, Double> _creatRandom(int loopNum){
`_` 는 실수로 들어간걸까요 ?

2023-11-07 09:56 UTC, shared-moon commented on src/main/java/study/RacingCar.java
> +    private Map<Integer, Double> randomsByStep;
Map을 절대 사용하면 안된다 라는건 아니지만, Map을 사용했을때의 단점은 DM으로 말씀 드린 것 같아요!
굳이 Map을 써야 될 이유가 없는 부분으로 보입니다. 말씀드린대로

- Map 대신 응답 클래스를 활용한다
- 응답을 각각 나눠서 묶지 않고 활용한다

둘 중에 하나로 바꿔보시면 좋을 것 같아요 ~

그리고 미션 진행간 `@Getter @Setter`는 지양하고 있으니 어노테이션은 지워주세요 ~

2023-11-07 09:56 UTC, shared-moon commented on src/test/java/study/RacingCarGameTest.java
> +        assertThat(carsMap.get("CarNo0").getLoopCount()).isEqualTo(3);
LoopCount는 CarNo0 에 대해서만 검증이 되면 되는걸까요 ?

2023-11-07 09:56 UTC, merged

2023-11-07 12:13 UTC, Taegoon commented on src/main/java/study/RacingCarGame.java
> +    private static Map<Integer, Double> _creatRandom(int loopNum){
private 함수 선언시 함수명 보통 _를 붙는 관행이 있어서 추가 한부분이에요.

2023-11-07 12:41 UTC, Taegoon commented on src/main/java/study/RacingCar.java
> +    private Map<Integer, Double> randomsByStep;
아노테이션 삭제 후 함수로 변경 하였어요.