🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #4988
Opened 2023-11-06 07:26 UTC by yoohojeong

🧑‍💻기능 요구사항
---
> - [x] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
> - [x] 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
> - [x] 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
> - [x] 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.

🧑‍💻 프로그래밍 요구사항
---
> - [ ] 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외
> - [x] UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

🔥 테스트 결과
---
> <img width="348" alt="Screen Shot 2023-11-06 at 4 26 16 PM" src="https://github.com/next-step/java-racingcar/assets/23239084/8b83855f-04a9-4474-be80-5c7c8156a99e">

2023-11-06 07:52 UTC, yoohojeong commented on src/test/java/step3/SimpleRacingCarGameTest.java
> +class SimpleRacingCarGameTest {
'모든 로직에 단위테스트를 구현한다'
단위테스트를 어디까지 구현해야할지 감이 잘 안잡혀서.. 조언을 구하고싶습니다.
단위테스트를 구현하려면 해당 함수의 반환값과 기대값 비교가 가능하거나
또는 기대되는 에러가 있어야할 것 같은데..
그런식으로 구현할만한 함수가 딱히 없는 것 같아.. 고민이 많이 됩니다,,

일단은 SimpleRacingCarGame.java 내에서 단위테스트를 구현할만한게 아래 두개 정도라고 판단하여.. 구현하였습니다.
많은 조언 주시면 감사하겠습니다~!

2023-11-06 12:17 UTC, seokhong requested changes
호정님, 3단계 미션 잘 구현하셨습니다. 👍 
고민하신 내용에 대한 답변과 함께 코드에 코멘트를 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/presentation/InputView.java
> +public class InputView {
`InputView` 에 필드를 놓고 값을 저장해서 반환하신 이유가 있을까요?
입력과 출력이 여러 단계에 걸쳐서 발생한다면 어떻게 될까요? :)
`InputView` 는 값을 요청해서 바로 반환하는 기능을 주로 해보면 어떨까요? 반환을 위한 객체가 필요하다면 dto 와 같은 별도의 클래스를 만들어 보셔도 좋겠습니다.

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/RacingCarGameMain.java
> +                OutputView outputView = new OutputView(game.start());
`OutputView` 를 생성하는 시점에 `game.start()`의 결과를 전달할 필요가 있을까요? 그리고 `OutputView` 에서 필드로 값을 관리해야 할 이유도 있을까요?
결과를 출력하는 시점에 출력을 위해 필요한 값만 전달해서 지역 변수로 관리해보면 어떨까요?

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +                return IntStream.range(0, carCnt).mapToObj(id -> new Car(String.valueOf(id)))
자동차에 id 를 전달하신 이유가 있을까요?

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +                if (isAbleToMove()) {
값이 4 이상일 때 이동할 수 있다는 건 자동차가 스스로 판단할 수 있는 부분 아닐까요?
난수를 생성하고 이동 여부를 결정해서 이동하기까지 모두 `Car` 스스로 할 수 있을 것 같아요.
`car.move()` 와 같이 호출했을 때 스스로 이동을 결정하고 이동하도록 구현해보면 어떨까요?

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +        private void recordPathForCarInThisRound(Car car) {
출력을 위한 값 생성을 `SimpleRacingCarGame` 에서 모두 관리하다보니 `SimpleRacingCarGame` 이 복잡해진 것으로 보입니다.
아래와 같이 기능을 나눠보면 어떨까요?

```
public class RacingCarGameMain {

    public static void main(String[] args) {
        // InputView 를 통해 필요한 값을 입력 받음

        // SimpleRacingCarGame 을 생성해 자동차 게임을 준비함

        // 아래 과정을 전체 라운드에 대해 수행함
        // SimpleRacingCarGame 을 이용해 라운드를 1회 진행함
        // OutputView 를 통해 1라운드 진행 결과를 출력함
    }
}
```

핵심은 도메인(`SimpleRacingCarGame`, `Car`)에서는 출력과 관련된 정책을 모른다는 것입니다.
출력을 위해 필요한 정보는 도메인 객체로부터 얻을 수 있지만, 해당 정보를 바탕으로 출력을 만드는 것은 `OutputView` 가 수행하는 것이죠.
이렇게 하면 의존성의 방향이 도메인에서 UI로 발생하지 않습니다.

또한, 도메인 로직에 대한 테스트도 `SimpleRacingCarGame`, `Car` 클래스에 대한 테스트 작성을 통해 수행할 수 있습니다.

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +                this.path = START_POINT;
미션의 출력 결과를 참고해보면 시작 위치에 "." 은 없는 것으로 보입니다. :)

> https://edu.nextstep.camp/s/twbNYuxs/ls/4iPs94sh

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +        public String getPath() {
`SimpleRacingCarGame` 에 남긴 것과 동일한 맥락에서, 출력을 "-" 형태로 하는 것은 UI의 기능입니다.
출력 방식이 "*" 로 변경된다면 `Car` 클래스가 변경되는 것이 적절할까요?
`Car` 의 핵심 기능은 위치를 관리하는 것이니, 현재 위치를 나타낼 수 있는 더 적절한 방법을 찾아보면 어떨까요?

2023-11-06 12:17 UTC, seokhong commented on src/test/java/step3/SimpleRacingCarGameTest.java
> +class SimpleRacingCarGameTest {
단위 테스트는 도메인의 모든 개별 클래스에 대해 작성하실 수 있습니다.
예를 들면, `Car` 클래스의 이동이 잘 되는지를 검증할 수도 있겠죠.

코멘트 남긴 내용을 참고하시어 리팩터링을 진행하시면 테스트 할 코드가 조금 더 나올 수 있어 보입니다. :)
앞으로 4단계, 5단계 미션에서도 자동차 경주의 기능을 계속해서 추가하고 리팩터링을 진행할 것이므로, 천천히 연습하고 학습하시면 될 것 같습니다.

2023-11-06 12:17 UTC, seokhong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요!

2023-11-06 12:27 UTC, yoohojeong commented on src/main/java/step3/domain/Car.java
> +                this.path = START_POINT;
앗 넵 가끔 자동차가 한 번도 움직이지 않아서 공백 라인이 생길 때가 있어서.. 제가 임의로 "."를 추가해서 START_POINT를 표시했습니닷.. ^^ 그래도 요구사항대로 하는게 나을 것 같으니 다시 빼도록 하겠습니다 ㅎㅎ

2023-11-06 12:33 UTC, yoohojeong commented on src/main/java/step3/presentation/InputView.java
> +public class InputView {
아,, 입출력이 여러 단계에 걸쳐서 발생 할 가능성을 생각못했군요.. 말씀 주신 것처럼 dto로 반환하는게 좋을 것 같습니다.

2023-11-06 12:36 UTC, yoohojeong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +                if (isAbleToMove()) {
이동하는 것(레이싱) 자체를.. Game  클래스의 영역이라 생각했는데 생각해보니 이동 주체는 Car이기 때문에..
Car 도메인에 들어가는게 더 맞겠군요.

2023-11-06 23:27 UTC, yoohojeong commented on src/main/java/step3/application/SimpleRacingCarGame.java
> +        private void recordPathForCarInThisRound(Car car) {
SimpleRacingCarGame 내에서 전체 라운드 수행을 해야할 것 같아서. .꾸역꾸역 해당 클래스 내에 담았는데,,
전체 라운드 수행을 Main으로 빼니까 도메인에서 UI로 의존하는 코드가 사라졌군요~!

2023-11-07 03:40 UTC, yoohojeong commented on src/main/java/step3/RacingCarGameMain.java
> +                OutputView outputView = new OutputView(game.start());
모든 라운드의 게임이 끝난 뒤에 시스템 출력을 하는 컨셉에서
매라운드가 종료 될 때마다 OutputView에 List<Car> 를 넘겨서 출력하는 컨셉으로 바꿨습니다!

이렇게 하니까 게임 결과(car.currentPosition)는 Car객체가 가지고있으면서
OutputView에선 Car의 currentPosition을 가져와서 출력만 하면되니까..
각 도메인의 역할이 분명해지면서 의존성이 분리된 것 같아 좋군요..

2023-11-07 03:48 UTC, yoohojeong commented on src/main/java/step3/domain/Car.java
> +        public String getPath() {
넵  Car에선 currentPosition으로 현재 위치만 변경하고 출력 관련 로직은 OutputView로 옮겼습니다.
이번 미션에서 도메인의 기능을 명확하게 분리하는게 어려웠는데.. 자세한 팁과 근거 너무 감사합니다.

2023-11-07 11:07 UTC, seokhong approved these changes
호정님, 3단계 미션 코멘트 잘 반영하셨습니다. 👍 
3단계 PR 머지하겠습니다.
코멘트 남긴 내용은 다음 단계 미션 진행하실 때 참고 부탁드립니다.
4단계 미션에서 뵙겠습니다. 🙂

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +        private int currentPosition;
위치 값은 항상 0 이상이어야 하니, 위치를 관리하는 클래스를 관리해보셔도 좋겠습니다. :)

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +                return random.nextInt(RANDOM_BOUND) >= 4;
`4` 라는 값도 상수로 관리해보면 어떨까요?

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +        public boolean movedForwardIfCan() {
테스트를 위해 이동 여부를 반환하신 것으로 보이네요!
`Car` 에서 난수 생성을 `Random` 객체를 통해 직접 하다보니, 이동 여부를 외부에서 제어하기 어려우셨을 것 같아요.
난수 생성을 위한 객체를 `Car` 를 생성하는 시점에 생성자를 통해 주입받아보면 어떨까요? 프로덕션 코드에서는 난수를 생성하는 객체를 전달하고, 테스트에서는 원하는 값을 생성하는 객체를 전달할 수 있을 것 같아요. 그럼 테스트에서 원하는 값을 전달하고, 그에 따라 이동 여부를 검증할 수도 있겠네요!

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +                currentPosition = START_INIT_VALUE;
미션의 출력 결과를 참고해보시면, 최초 위치는 0번이 되어야 할 것 같아요. :)

말씀하신 것처럼 한 번도 이동하지 않은 경우를 고려하신 코드라고 이해했습니다. 다음 단계에서는 출력 형태가 달라지니 최초 위치를 0으로 시작해보셔도 좋겠습니다.

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/SimpleRacingCarGame.java
> +}
여기도 마지막 줄에 newline 이 없다고 경고를 띄워주네요!

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/domain/SimpleRacingCarGame.java
> +        private final int carCnt;
`carCount` 와 같이 원래 단어를 줄여쓰지 않으시는 것을 추천합니다.
항상 같은 규칙으로 줄여서 작성하는 경우는 괜찮으나, 그렇지 않다면 코드의 양이 많아짐에 따라 코드를 검색할 때 어려움이 있습니다. 또한 간단한 줄여쓰기라도 원래 단어를 한 번 더 생각해야 하므로, 코드를 읽을 때 조금 더 고민해야 하는 단점이 있습니다.

2023-11-07 11:07 UTC, seokhong commented on src/main/java/step3/presentation/OutputView.java
> +                IntStream.range(0, currentPosition).forEach(i -> System.out.print(PATH_SIGN));
`PATH_SIGN.repeat(currentPosition)` 으로도 동일한 기능을 구현할 수 있을 것 같아요!

2023-11-07 11:07 UTC, merged

2023-11-08 07:45 UTC, yoohojeong commented on src/main/java/step3/domain/Car.java
> +        public boolean movedForwardIfCan() {
음.. Random 객체를 Car 생성 시에 생성자를 통해 주입 받게 되면..  
RacingCarGame 도메인에 Random 객체를 선언해야하는데.. 
단위테스트를 위해 Random 객체를 쓰는 주체가 아닌 RacingCarGame 도메인에 Random 객체를 선언해도 괜찮을까요..?

2023-11-08 12:40 UTC, seokhong commented on src/main/java/step3/domain/Car.java
> +        public boolean movedForwardIfCan() {
여러 방법이 있을 것 같아요. 말씀하신 것처럼 현재 구조에서는 `RacingCarGame` 에서 `Random` 객체를 생성해서 전달하는 방법이 있고, `joinCars` 의 인자로 받는 방법도 있겠네요.
이외에 구조를 변경한다면 외부에서 자동차 목록을 만들고(자동차 목록을 만드는 클래스에서 `Random` 객체를 생성하겠네요) `RacingCarGame` 에 전달하는 방법도 있습니다.
혹은, 난수 생성을 `RacingCarGame` 에서 수행하고, `Car` 에게 `move` 를 요청하면서 난수를 인자로 전달해서 자동차가 이동 여부를 판단하도록 구성하는 방법도 있습니다.

어떤 방법이든, 자동차가 이동하는 규칙은 변할 수 있다고 생각하기에, 자동차의 이동 규칙과 관련된 객체를 만들고 자동차에게 전달해준다면 테스트도 용이하고 추후 변경에도 더 쉽게 대응할 수 있을 것 같아요! :)