Step3: 자동차경주
next-step/java-racingcar pull request #4994
Opened 2023-11-06 12:40 UTC by Jane096

2단계 미션에서 리뷰 주신 내용을 많이 반영해보려고 고민했습니다!!
피드백 부탁드립니다~

2023-11-07 09:23 UTC, serverwizard requested changes
지은님, 3단계 미션 잘 구현해 주셨네요. 👍
코멘트 남긴 내용 확인 부탁드립니다. 🙂

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/Cars.java
> +        return this.currentStatus == null ? "-" : this.currentStatus + "-";
현재 화면과 관련된 "-" 부분이 "*"로 변경되게 되면, Cars 도메인 객체까지 영향을 받게 될 것 같은데요~
보통 도메인 객체는 화면 요구사항(`애플리케이션 외부 요구 사항`)이 아닌 비즈니스 로직(`애플리케이션 내부 요구 사항`)이 변경될 때만 영향을 받으면 좋을 것 같아요~

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/RaceStartLine.java
> +        Race.playing(cars, times);
MVC 패턴에 맞게 코드 구조를 변경해보는 건 어떨까요?
![image](https://user-images.githubusercontent.com/23587638/107108391-df80ef80-687a-11eb-869f-ed3707f9cca2.png)

변경하시면서 아래 고민들도 함께 해보시면 좋을 것 같아요~
- Model(또는 도메인, 핵심 비즈니스 로직을 가진 객체)에 해당하는 클래스는 누구인지? ex. RacingCar(또는 Car)
- View(또는 UI)에 해당하는 클래스는 누구인지? ex. ConsoleInputView, ConsoleOutputView
- Controller(메인 메소드를 가지는 클래스)에 해당하는 클래스는 누구인지? ex. RacingCarGameMain

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/RaceResult.java
> +        System.out.println(Arrays.toString(this.board));
현재 RaceResult라는 도메인 객체가 화면 출력을 책임지고 있는데요.!

아래 그림대로 Controller(메인 메소드를 가지는 클래스)를 통해 View와 도메인 객체를 연결해 보는 건 어떨까요?
<img width="704" alt="image" src="https://github.com/next-step/java-racingcar/assets/23587638/c0ed3a53-d791-4314-9132-9bad52e25ba3">

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/Race.java
> +                if (Cars.isMovable(getRandomValue())) {
아래 객체지향 생활 체조 원칙을 준수해 보면 어떨까요? (메소드 추출 연습)
```
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
```

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/Cars.java
> +public class Cars {
Car가 아닌 Cars로(복수) 클래스명을 지으신 이유가 있으실까요?
보통 일급 컬렉션(내부에 컬렉션을 가지고 있는 객체)명을 지을 때 복수명을 많이 지어서 물어봐요~
- https://jojoldu.tistory.com/412

2023-11-07 09:23 UTC, serverwizard commented on src/main/java/step3/Race.java
> +public class Race {
Race객체 속성으로 자동차 경주에 참여하는 자동차들을 가져 보는 건 어떨까요?
```
private final List<Car> cars;
```

2023-11-07 14:10 UTC, Jane096 commented on src/main/java/step3/Cars.java
> +public class Cars {
s를 붙여서 클래스를 생성하는게 익숙해서 붙였던 것 같습니다. 일급 컬렉션을 가진 클래스에 복수형 이름을 짓는 것은 놓쳤던 부분이네요.. 공유주신 블로그 참고해서 수정해보겠습니다!

2023-11-07 14:11 UTC, Jane096 commented on src/main/java/step3/Race.java
> +                if (Cars.isMovable(getRandomValue())) {
앗 이부분 indent가 많이 들어갔네요! 놓치고 있었던 부분이었습니다. 다른 객체나 메서드로 빼보도록 하겠습니다!

2023-11-07 14:18 UTC, Jane096 commented on build.gradle
> +    testImplementation 'org.mockito:mockito-core:4.8.0'
테스트 코드에 void 메서드를 테스트하기위한 verify()를 호출하기 위해서 추가해봤던 디펜던시 입니다!

2023-11-07 15:26 UTC, Jane096 commented on src/main/java/step3/RaceStartLine.java
> +        Race.playing(cars, times);
네! MVC 형태에 따라서 디렉토리를 좀 더 세분화하여 나눠보도록 하겠습니다~

2023-11-07 15:33 UTC, Jane096 commented
리뷰 주신 부분 체크하여 로직을 많이 변경해보았습니다!
계속 수정을 하다보니 부족한 부분이 많았네요... 피드백 주시면 감사하겠습니다!!!

2023-11-08 09:48 UTC, serverwizard requested changes
지은님, 3단계 피드백 반영 잘 해주셨어요. 👍
추가적으로 확인해볼 피드백 남겨드렸으니 확인해주시면 감사하겠습니다!.

2023-11-08 09:48 UTC, serverwizard commented on src/main/java/step3/controller/RaceStartLine.java
> +        int times = new RaceInputView(scanner).raceTimeInput();
View 객체 같은 경우에는 꼭 객체를 생성해서 사용해야 할지 고민해 보시면 좋을 것 같아요.
아래와 같이 사용하게 구현할 수는 없는지에 대해서요~
```
RaceInputView.raceTimeInput()
```

2023-11-08 09:48 UTC, serverwizard commented on src/main/java/step3/model/Car.java
> +        this.currentStatus = START_VALUE;
자동차가 생성되자마자 현재 위치가 1이 될 것 같아요.
int형과 같은 primitive type은 0을 기본 값으로 가지기 때문에 어떤 초기화도 해주지 않는 건 어떨까요?

2023-11-08 09:48 UTC, serverwizard commented on src/main/java/step3/model/Race.java
> +            new RaceResultView(cars).show();
아래와 달리, 현재 Race 도메인 객체에서 RaceResultView View 객체를 의존하고 있는데요!
이럴 경우, View객체에 변경이 발생하게 되면 도메인 객체까지 영향이 갈 수 있을 것 같아요.

아래 그림대로 Controller(메인 메소드를 가지는 클래스)에서 View 객체에게 작업 위임을 해보는 건 어떨까요?
<img width="704" alt="image" src="https://github.com/next-step/java-racingcar/assets/23587638/c0ed3a53-d791-4314-9132-9bad52e25ba3">

2023-11-08 09:48 UTC, serverwizard commented on src/main/java/step3/controller/RaceStartLine.java
> +    public static void main(String[] args) {
아래 그림 흐름대로 main 메소드를 구현하신 부분 멋지시네요 👍 
<img width="721" alt="image" src="https://github.com/next-step/java-racingcar/assets/23587638/40993edd-3330-4264-85e2-684bd9ee01e1">

만약 아래와 같이 구현한다면 자동차 경주 게임을 사용하는 입장에서 RacingGame 객체만 알면 될 것 같은데 어떻게 생각하시나요? (정답은 아님, 비교를 위한 코드일 뿐) 
```
public static void main(String[] args) {
        int carCount = InputView.getCarCount();
        int tryCount = InputView.getGameTryCont();

        RacingGame racingGame = new RacingGame(carCount, tryCount);
        while (!racingGame.isEndGame()) {
            racingGame.startRacing(new Random().nextInt(10))
            ResultView.printResult(racingGame.getCars());
        }
    }
```

2023-11-08 09:48 UTC, serverwizard commented on src/main/java/step3/model/Race.java
> +    public static int getRandomValue() {
도메인 객체 메소드인데 테스트 코드 작성하기가 어려울 것 같네요! 
어떻게 하면 도메인 객체인데 테스트하기 쉽게 만들 수 있을까요?
<힌트>
도메인 객체 외부(여기서는 컨트롤러)로 부터 랜덤값을 받는 방식

2023-11-08 09:48 UTC, serverwizard commented on src/test/java/step3/RacingCarTests.java
> +    @ValueSource(ints = {3})
이왕 @ParameterizedTest를 이용하시는 거, 몇 가지 값에 대해 함께 테스트를 해보시면 좋을 것 같아요!
```
@ValueSource(ints = {1, 2, 3})
```

2023-11-08 09:55 UTC, Jane096 commented on src/main/java/step3/controller/RaceStartLine.java
> +        int times = new RaceInputView(scanner).raceTimeInput();
넵 이 부분은 기존처럼 static으로 생성하여 불필요하게 객체를 생성하지 않도록 수정해보겠습니다~

2023-11-08 09:55 UTC, Jane096 commented on src/main/java/step3/model/Car.java
> +        this.currentStatus = START_VALUE;
네네! 불필요하게 1로 초기화할 필요가 없었네요!!

2023-11-08 10:04 UTC, Jane096 commented on src/main/java/step3/controller/RaceStartLine.java
> +    public static void main(String[] args) {
model <-> view 사이에서 관계를 가지는게 아닌 컨트롤러와 관계를 가지도록 해보면 그림과 같은 구조가 될 수 있을 것 같네요. View가 바뀌어도 model이 영향받지 않는 구조가 될 것 같습니다. 이 부분도 좀 더 mvc 하게 보일 수 있도록 수정해보겠습니다!

2023-11-08 12:48 UTC, Jane096 commented on src/main/java/step3/model/Race.java
> +    public static int getRandomValue() {
MAX_RANDOM_VALUE를 외부에서 주입받도록 한다면 좀 더 테스트가 쉬워질 것 같습니다!

2023-11-09 07:17 UTC, serverwizard approved these changes
지은님, 3단계 미션 잘 마무리하셨습니다. 👍
3단계 PR 머지하겠습니다.

간단한 코멘트 몇 개 남겨뒀는데, 이건 4단계 미션 진행하실 때 함께 반영해보시면 좋을 것 같습니다 :)

2023-11-09 07:17 UTC, serverwizard commented on src/main/java/step3/model/RaceBoard.java
> +        return IntStream.range(0, cars).mapToObj(car -> new Car())
해당 로직을 Race 생성자 내에서 진행할 수도 있을 것 같은데 어떻게 생각하시나요?
RaceBoard 객체가 반드시 필요한 객체인지 고민해 보시면 좋을 것 같아요~

2023-11-09 07:17 UTC, serverwizard commented on src/test/java/step3/RacingCarTests.java
> +public class RacingCarTests {
Car와 Race 도메인 객체에 대해서도 테스트 코드를 작성해 보시면 좋을 것 같아요 :) 
참고로 테스트 클래스명은 보통 `프로덕션 클래스명 + Test`로 짓습니다.

2023-11-09 07:17 UTC, serverwizard commented on src/main/java/step3/model/Race.java
> +    private final List<Car> cars;
이번 기회에 일급 컬렉션(내부에 컬렉션을 가지고 있는 객체)에 대해서도 학습해 보시면 좋을 것 같아요.
- https://jojoldu.tistory.com/412

2023-11-09 07:17 UTC, merged

2023-11-09 11:51 UTC, Jane096 commented on src/main/java/step3/model/Race.java
> +    private final List<Car> cars;
넵!! 주신 내용 계속 기억하면서 4단계 때 작업 해보겠습니다!!

2023-11-09 11:51 UTC, Jane096 commented on src/test/java/step3/RacingCarTests.java
> +public class RacingCarTests {
넵 4단계 때는 도메인 객체에 따라 테스트를 나누어 보는게 좋을 것 같습니다!!

2023-11-09 11:52 UTC, Jane096 commented on src/main/java/step3/model/RaceBoard.java
> +        return IntStream.range(0, cars).mapToObj(car -> new Car())
아 그렇네요.. 레이스를 할려면 레이스 생성 시점에 만드는 것이 불필요한 객체를 줄일 수 있을 것 같습니다!!

2023-11-09 12:07 UTC, Jane096 commented on src/main/java/step3/controller/RaceStartLine.java
> +            new Race(carList).playing(Race.getRandomValue());
뭔가 계속 나눠야하고 다른 책임이 있지 않을까 고민하다가 메서드로 빼게 되었는데, 이런 부분에 있어서는 오히려 간단하게 작성하는 것도 좋은 방법이 될 수 있을 것 같네요.. 아직 어디를 나누고 어디를 간단하게 써야하는지에 대해 많은 고민이 필요한 것 같네요 ㅠㅠ