4단계 - 자동차 경주(우승자) 구현
next-step/java-racingcar pull request #5013
Opened 2023-11-07 06:25 UTC by cjsrhd94

4단계 자동차 경주(우승자) 과제 제출입니다.

이전에 코멘트 해주셨던 'random 값과 상관없이 메서드를 테스트 할 수 있도록 추상화를 해볼 것'에 대해 전략 패턴을 사용하여 테스트용 클래스를 따로 작성해 보았습니다. 이것도 일종의 테스트 더블(?) 이라고 할 수 있을지는 모르겠네요 ㅎㅎ 부족한 부분이 있다면 조언해주시면 감사하겠습니다.

1. 이번에 우승자를 뽑는 getWinners라는 로직을 작성하였는데, 저같은 경우 racingGame 객체를 생성할 때  일괄적으로 START_LOCATION을 Car객체의 위치로 설정을 해주고 있고, 이 값은 임의로 변경할 수 없게 해놓았습니다. 이런 경우 테스트 코드를 작성할 때 다양한 경우의 테스트를 하기 어려운데 구조를 개선하여 다양한 테스트를 할 수 있게 리팩토링할 수 있을까요?

2023-11-07 11:23 UTC, kyucumber requested changes
우승자 관련 요구사항 잘 구현해주셨네요.

간단한 코멘트 남겨두었으니 확인 부탁드릴게요.

2023-11-07 11:23 UTC, kyucumber commented on src/test/java/racingcar/RacingGameTest.java
> +		MoveStrategy strategy = new FixedStrategy();
> 이전에 코멘트 해주셨던 'random 값과 상관없이 메서드를 테스트 할 수 있도록 추상화를 해볼 것'에 대해 전략 패턴을 사용하여 테스트용 클래스를 따로 작성해 보았습니다. 이것도 일종의 테스트 더블(?) 이라고 할 수 있을지는 모르겠네요 ㅎㅎ 부족한 부분이 있다면 조언해주시면 감사하겠습니다.

이렇게 테스트에서 클래스를 교체해주셨는데요. [테스트 더블](https://tecoble.techcourse.co.kr/post/2020-09-19-what-is-test-double/) 중 Fake로 볼 수 있을 것 같아요~

2023-11-07 11:23 UTC, kyucumber commented on src/main/java/racingcar/FixedStrategy.java
> +public class FixedStrategy implements MoveStrategy{
테스트에서만 쓸 클래스가 테스트 패키지가 아닌 곳에 노출되어 있네요. 테스트 패키지로 옮기면 어떨까요?

2023-11-07 11:23 UTC, kyucumber commented on src/test/java/racingcar/RacingGameTest.java
> +		MoveStrategy strategy = new FixedStrategy();
lambda expression을 사용해 표현해볼 수 있을까요?

FunctionalInterface와 lambda에 대해 찾아보고 학습해보시면 좋겠습니다.

2023-11-08 13:59 UTC, kyucumber requested changes
간단한 코멘트 남겨두었으니 확인 부탁드려요.

2023-11-08 13:59 UTC, kyucumber commented on src/test/java/racingcar/RacingGameTest.java
> +		RacingGame game = gameInit.apply("rac1,rac2,rac3");
이렇게 쓰신 이유가 있을까요? new RacingGame("")이 더 효율적인 방법으로 보여요.

2023-11-08 13:59 UTC, kyucumber commented on src/test/java/racingcar/RacingGameTest.java
> +		MoveStrategy strategy = () -> new FixedStrategy().move();
아래가 더 효율적인 방법 아닐까요~? FixedStrategy를 없애고 클래스 변수로 빼도 될 것 같네요.

```suggestion
		MoveStrategy strategy = () -> 4;
```

2023-11-08 15:04 UTC, cjsrhd94 commented on src/test/java/racingcar/RacingGameTest.java
> +		RacingGame game = gameInit.apply("rac1,rac2,rac3");
FunctionalInterface와 lambda를 사용해보라는 코멘트를 제가 잘못 이해한거 같아요. 저도 기존 방법이 더 효율적이라고 생각합니다!

2023-11-08 15:10 UTC, cjsrhd94 commented on src/test/java/racingcar/RacingGameTest.java
> +		MoveStrategy strategy = () -> new FixedStrategy().move();
제안해주신 방법이 테스트를 하기에도 더 용이한 측면이 있을것 같아요!

2023-11-09 13:43 UTC, kyucumber approved these changes
피드백 잘 반영해주셨네요.

다음 단계 진행을 위해 머지하겠습니다.

2023-11-09 13:43 UTC, merged