Step3 자동차 경주
next-step/java-racingcar pull request #5016
Opened 2023-11-07 08:45 UTC by geunnseung

- Car 클래스가 RandomNumMaker를 참조해서 랜덤으로 숫자가 만들어져서 테스트를 하기가 어려웠습니다
- 랜덤 값이 4이상, 4미만, 4일 때 경우를 다 테스트 해보고 싶었는데 방법이 잘 안떠오릅니다
- 커밋 내역을 좀 신경써보려 했는데 엉킨 부분이 있습니다
- View 관련 클래스 메소드들도 테스트를 할 필요가 있을까요?

2023-11-07 14:02 UTC, nooose requested changes
승근님! 3단계 잘 해주셨네요
피드백 남겼으니 읽어보시고 재요청 부탁드립니다.
질문 있으면 DM 남겨주세요~

2023-11-07 14:02 UTC, nooose commented on src/main/java/carRacing/CarRacing.java
> +	}
CarRacing를 생성하고 makeCars를 호출하기 보다는
`new RacingCar(carCount);` 인스턴스 생성과 동시에 자동차 리스트를 초기화해도 괜찮을 것 같네요 😄

2023-11-07 14:02 UTC, nooose commented on src/main/java/carRacing/InputView.java
> +		if(count < MINIMUM_NATURAL_NUM) {
```suggestion
		if (count < MINIMUM_NATURAL_NUM) {
```

2023-11-07 17:07 UTC, geunnseung commented on src/main/java/carRacing/Car.java
> +	}
moveCar 메소드에 매개변수를 넣는 방법으로 해결하라는 말씀이신가요?

2023-11-08 14:52 UTC, geunnseung commented
1. Car클래스가 RandomNumMaker에 의존하지 않도록 RandomNumMaker는 랜덤값만 만들고 Car 클래스의 moveCar 메소드에 매개변수를 받게 한 뒤 움직일 수 있는지에 대한 메소드도 만들었습니다
2.  CarRacing의 makeCars와 테스트한 moveCar 메소드를 호출하는 moveCars메소드도 테스트를 할 필요가 있는지 궁금합니다

2023-11-08 15:29 UTC, nooose approved these changes
안녕하세요 승근님!

잘해주셔서 3단계는 여기서 머지 할게요
4단계 진행하면서 반영하면 좋을 내용들 코멘트에 남겼어요
질문에 대한 답변도 포함되어 있으니 확인해 보세요

수고하셨습니다.

2023-11-08 15:29 UTC, nooose commented on src/main/java/carRacing/Car.java
> +	}
```suggestion
	private boolean isCarForward(int num) {
		return num >= MINIMUM_TO_MOVE;
	}
```
moveCar에서만 사용하고 있으니 private 접근제한자로 변경하는 게 좋겠네요

2023-11-08 15:29 UTC, nooose commented on src/main/java/carRacing/CarMain.java
> +		List<Car> cars = carRacing.makeCars(carCount);
```suggestion
		CarRacing carRacing = new CarRacing(carCount)
```
`List<Car>` 을 래핑하고 컬렉션과 관련된 로직을 CarRacing이 처리하고 있는데
이러한 객체를 일급컬렉션이라고 합니다.

하지만 위 코드에서는 일급컬렉션 활용이 되지 않는 것 같습니다.

위 처럼 생성자를 호출하여 생성과 동시에 내부 자동차 리스트를 초기화하면
일급컬렉션의 장점이 더 드러나지 않을까요?
```java
public CarRacing (int carCount) {
    // cars 리스트 초기화
} 
```

2023-11-08 15:29 UTC, nooose commented on src/main/java/carRacing/ResultView.java
> +
```suggestion
	private static final String HYPHEN = "-";
```
외부에 노출할 필요가 없는 상수이니 private 접근제한자로 변경하는 것이 좋을 것 같습니다.
그리고 HYPHEN 보다는 자동차 거리를 표현하는 다른 의미를 적어주는 것이 가독성에 도움을 줄 것 같아요!

2023-11-08 15:29 UTC, nooose commented on src/test/java/carRacing/CarTest.java
> +	}
테스트가 가능하도록 move에 랜덤한 정수값을 넣는 방법을 택하셨네요 😄

만약 비즈니스 요구사항이 변경되어
랜덤한 값이 아닌 외부 시스템과 연계 후 변경되어야 한다면 어떻게 될까요?
그러면 이 상황에서는 코드 구조가 많이 변경될 것 같습니다.

그렇다면 더욱더 유연한 방법이 필요한데요
방법 중 하나가 전략패턴을 활용하는 방식입니다.
```java
void move(Strategy strategy) {
    if (strategy.isForward()) {
        moveCount += 1;
    }
}
```

도메인 Car는 Strategy인 인터페이스에만 의존하고
실제 Strategy의 구현체는 상황에 따라 다르게 주입하면 해결할 수 있을 것 같습니다.

테스트에서는 전진만 하는 전략
실제 프로덕션 코드에는 랜덤전략을 주입하면 유연하게 대처가 가능해져요!

2023-11-08 15:29 UTC, nooose commented on src/main/java/carRacing/CarMain.java
> +			result.showResult(cars);
`new RandomNumMaker()`가 매번 생성될 필요는 없을 것 같아요

2023-11-08 15:29 UTC, nooose commented on src/test/java/carRacing/CarTest.java
> +	}
위 방법대로 구현된다면
moveCars도 테스트하기가 수월해질 것 같습니다!

2023-11-08 15:29 UTC, merged