🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5029
Opened 2023-11-07 13:47 UTC by hyeonjinnoh

### 🚀 5단계 - 자동차 경주(리팩토링)
- domain 패키지의 객체가 view 패키지 객체에 의존하지 않도록 변경
- step4의 코드 리뷰 반영
  - IntStream -> for 반복문
  - maxPosition 값을 한번만 구하도록 변경
  - position 출력 시 한번에 출력하도록 변경
  - 테스트 코드 작성 시 지역 변수로 테스트 객체 생성하도록 변경
- TDD 강의 및 자동차 경주 피드백 강의에 따라 원시값 포장 및 일급 콜렉션으로 리팩토링

---
### 질문

**Q1**
4강 이후 강의에서 getter 사용은 domain <-> view 이외에 사용은 안하는게 좋다하셨는데,
원시값을 포장하다 보니 view가 아니라 domain 영역에서 다른 도메인의 값을 불러와야하는 상황이 있더라구요 (e.g. Cars의 maxPosition 함수)
getter를 사용해서 값을 가져오는게 아니라 객체에 질문을 던지는 방법이 있지만 max값을 구하는 함수에서는 그렇게 구현하기 어려운데
이럴땐 getter를 사용하는게 맞는지 아니면 다른 처리 방법이 있는지 궁금합니다

**Q2**
C++ 개발자로 잠깐 일했던 경력이 있습니다
그렇다보니 특정 횟수만큼 반복해야하는 상황에서 for (int i = 0; i < 5; i++) 과 같은 로직을 구현하면 C++처럼 구현하는것같아 저번 step4와 같이 IntStream.range를 주로 사용하고 있습니다
특정 횟수만큼 반복이 필요할 때 for (int i = 0; i < 5; i++)와 같은 코드를 사용하는게 Java스러운 코드가 맞는지 궁금합니다
또 for문에서 사용되는 변수는 C++에서는 통상 i로 표현하는데, Java도 동일할까요?

2023-11-07 17:51 UTC, shared-moon requested changes
현진님 안녕하세요 ~
5단계 미션 잘 진행 해 주셨네요!
코멘트를 조금 남겨놨는데요, 마지막 미션이니 한번만 다시 보면 좋을 것 같아요~
확인 후 리뷰 재요청 해주세요!
고생 많으셨습니다 :)

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public Car(String name, int position) {
테스트를 위해 만들어진 생성자 같은데요
생성자, 메서드는 테스트만을 위해 만드는걸 지양하는게 좋습니다~

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Name.java
> +    private void validate(String name) {
👍

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Cars.java
> +            .mapToInt(Position::position)
요거 위에서 바로 mapToInt 할 수 있지 않을까요 ?
반복문을 2번 돌게 되는거라 메서드 레퍼런스 사용을 포기하는게 더 나을 것 같습니다..!

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Cars.java
> +    private int maxPosition() {
>Q1
4강 이후 강의에서 getter 사용은 domain <-> view 이외에 사용은 안하는게 좋다하셨는데,
원시값을 포장하다 보니 view가 아니라 domain 영역에서 다른 도메인의 값을 불러와야하는 상황이 있더라구요 (e.g. Cars의 maxPosition 함수)
getter를 사용해서 값을 가져오는게 아니라 객체에 질문을 던지는 방법이 있지만 max값을 구하는 함수에서는 그렇게 구현하기 어려운데
이럴땐 getter를 사용하는게 맞는지 아니면 다른 처리 방법이 있는지 궁금합니다

VO를 사용하시면 결국 그 안의 값이 필요한 거기 때문에 getter (혹은 값을 가져오는 어떤 것)는 당연히 필요하다고 생각합니다. getter를 지양하는 것의 목적은 무분별한 사용으로 인해 정보의 은닉이 제대로 되지 않는 것을 막기 위함이고, 필요한 곳에서는 쓰는게 맞습니다. 물론 말씀하신 것 처럼 굳이 getter가 아니라 객체에 질의를 해서 얻을 수 있는 정보라면 그 방향을 먼저 고민하는게 더 좋습니다!

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/Runner.java
> +        for (int round = 0; !game.isEnd(round); round++) {
>Q2
C++ 개발자로 잠깐 일했던 경력이 있습니다
그렇다보니 특정 횟수만큼 반복해야하는 상황에서 for (int i = 0; i < 5; i++) 과 같은 로직을 구현하면 C++처럼 구현하는것같아 저번 step4와 같이 IntStream.range를 주로 사용하고 있습니다
특정 횟수만큼 반복이 필요할 때 for (int i = 0; i < 5; i++)와 같은 코드를 사용하는게 Java스러운 코드가 맞는지 궁금합니다
또 for문에서 사용되는 변수는 C++에서는 통상 i로 표현하는데, Java도 동일할까요?

약간 이 고민은 이 부분에서 하신 것 같아서 여기에 적어봅니다 ~
자바라고 따로 형식이 있진 않습니다. Stream API는 자바 8 버전부터 나온 기능으로 자바스러운 방법이라기보단 그냥 선언형 프로그래밍을 가능하게 해주는 도구라고 보시는게 맞을 것 같습니다.
저번에 피드백 드린 부분은, Stream API를 사용하기보단 for문을 이용하는게 더 가독성이 좋을 것 같아 코멘트 해 봤었는데요, 상황에따라 for문/Stream API 중 적절한 걸 고르면 되기 떄문에 뭐가 더 자바스럽고 아니고는 없다는 말씀을 드리고 싶네요!

자바도 반복문에서는 `i` 자주 사용합니다 ~

추가로 이 부분에서, game.isEnd 는 오히려 가독성을 해치는 것 같네요. for문을 몇번을 도냐가 중요한 부분이라 사이즈나 횟수 등을 나타내는게 직관적으로 보이는데, isEnd() 를 사용하면 언제 끝나는지는 안에 들어가 봐야 알 수가 있어서요..! 통상적으로 사용되지 않는 표현이라는 점도 가독성에 악영향을 준다는 생각이 듭니다 ~

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public Name name() {
Name의 값을 꺼내서 String 으로 리턴해주는 건 어떨까요 ?

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public boolean isMaxPosition(int maxPosition) {
사실 이 메서드는 바깥에서 넘어오는게 maxPosition인지 아닌지 알 방법이 없어보여요 ~
isMaxPosition보다는 좀 더 범용적으로 equalsPosition 정도로 표현해주는게 어떨까 싶네요!

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public Position position() {
요것도 그냥 Position 값을 꺼내서 int로 리턴해주는게 어떨까요 ?

2023-11-07 17:51 UTC, shared-moon commented on src/main/java/step3/domain/RacingGame.java
> +    private static final int RANDOM_BOUND = 10;
요거 상수로 정의될거면 그냥 RandomUtil이 가지고 있는건 어떨까요 ?

2023-11-07 17:51 UTC, shared-moon commented on src/test/java/step3/CarGeneratorTest.java
> +            .containsExactly(NAME_OF_CARS);
NAME_OF_CARS를 리스트로 바꾸고 equals로 비교하는건 어떨까요 ~?

2023-11-07 17:51 UTC, shared-moon commented on src/test/java/step3/RacingGameTest.java
> +            assertThat(position.position()).isBetween(0, NUMBER_OF_TRY);
불완전한 테스트인 것 같아요 ~
예를 들어 Car의 move 메서드가 무조건 움직이도록 바뀌거나 무조건 안움직이도록 바뀌어도 통과되는 테스트 아닌가요 ?
랜덤요소 때문에 테스트가 어려우실 것 같은데 RandomUtil.random 부분을 전략패턴을 이용해 추상화하면 테스트에서도 컨트롤이 가능할 것 같아요 ~

2023-11-08 07:10 UTC, hyeonjinnoh commented on src/main/java/step3/domain/Car.java
> +    public Car(String name, int position) {
`TDD 강의 및 자동차 경주 피드백` 강의에서 테스트를 위한 생성자는 괜찮다고 말씀해주셔서 작성했는데 어렵네요🥲
이 부분은 조금 더 생각해보고 제 기준을 만들어야겠어요

2023-11-08 07:15 UTC, hyeonjinnoh commented on src/main/java/step3/domain/Car.java
> +    public Name name() {
원시데이터를 Name과 Position으로 포장했기 때문에 최종적으로 실제 데이터가 필요한 시점에 꺼내 쓰는게 좋지 않을까 생각했습니다
해서 직접 사용이 필요한 ResultView에서 데이터를 꺼내서 사용하고 있구요!

혹시 리뷰어님은 어떤 점에서 이 부분에 String으로 리턴하는게 좋을거같다고 생각하셨는지 의견 궁금합니다!

2023-11-08 07:15 UTC, hyeonjinnoh commented on src/main/java/step3/domain/Car.java
> +    public Position position() {
위 코멘트와 동일합니다

2023-11-08 07:20 UTC, hyeonjinnoh commented on src/main/java/step3/domain/RacingGame.java
> +    private static final int RANDOM_BOUND = 10;
이 부분은 [step3의 코멘트](https://github.com/next-step/java-racingcar/pull/4919#discussion_r1382516369)로 한번 남겼었는데요,
RandomUtil 내부에서 레이싱 게임만을 위한 RANDOM_BOUND 값을 변수로 가지고 있는것은 RandomUtil과 RacingGame간 의존관계가 생긴다 생각하여 RacingGame에서 해당 값을 관리하도록 구현했습니다
(물론 지금의 요구사항만으로는 RandomUtil을 사용하는 곳은 RacingGame밖에 없으니 RandomUtil이 가져도 되겠지만요..!)

2023-11-08 07:23 UTC, hyeonjinnoh commented on src/test/java/step3/RacingGameTest.java
> +            assertThat(position.position()).isBetween(0, NUMBER_OF_TRY);
자동차의 움직임 자체는 CarTest에서 수행되고 있어 RacingGameTest에서는 정확한 위치까지 테스트할 필요는 없다 생각했습니다

전략패턴을 말씀하셨는데, 전략패턴 역시 CarTest의 move함수에서 int random 값 대신 MoveStrategy를 사용할 수 있는 부분이라 생각하는데 혹시 RacingGameTest에서도 전략패턴을 사용하려면 어떤식으로 구현하면 될까요~?

2023-11-08 16:13 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public Car(String name, int position) {
간혹 필요한 부분이 있긴 합니다. 예를 들어 Entity 클래스를 만들었는데, 기본적으로 Entity 클래스의 id값은 AUTO_INCREMENT를 사용하니 생성자로는 받질 않는데, 테스트를 하려면 값을 넘겨줘야 해서 필요한 부분인데요! 지금 상황에선 딱히 만들 필요가 없어 보여서 지양하는게 좋다는 말씀을 드렸습니다..!

2023-11-08 16:26 UTC, shared-moon commented on src/test/java/step3/RacingGameTest.java
> +            assertThat(position.position()).isBetween(0, NUMBER_OF_TRY);
말씀하신 대로 Car에서 동작을 위한 값을 파라미터로 받고 있기 때문에, 파라미터에 따라 움직이고 말고는 테스트가 되고 있어 사실 안봐도 무방하긴 하다고 생각합니다.

하지만 그런 의도라면 position을 검사하기보단 cars와 car를 목킹하여 원하던 메서드가 호출 됐는지 여부를 보는게 더 맞을 것 같습니다!

현재 RacingGameTest 입장에서는 생성자에서 만들어진 Cars를 받도록 하고 Cars를 목킹해서 NUMBER_OF_TRY만큼 cars.move()가 불렸는지 확인하면 될 것 같고, CarsTest에서도 move에 대한 테스트를 만들고 Car를 목킹하여 car.move가 불렸는지만 봐도 충분할 것 같습니다~

전략패턴을 말씀드린 이유는 position을 검사하고 계셔서 말씀드려봤었구요! 말씀대로 Car에서 전략을 직접 받아도 되고, 지금 구현에서 random값을 뽑는 부분까지만 전략을 전달해도 될 것 같습니다 RacingGame.playRound 에서부터 전략을 전달 받는 식으로 구성을 해둔다면 Test에서는 무조건 움직이거나 무조건 움직이지 않는 방향으로 테스트를 구성해 볼 수 있을 것 같아요 ~

전략패턴보단 위의 방식으로 테스트를 만들어보는게 더 나을 것 같긴 합니다 :)

2023-11-08 16:35 UTC, shared-moon commented on src/main/java/step3/domain/Cars.java
> +        Position maxPosition = new Position(DEFAULT_POSITION);
요건 그냥 참고차 ..

DEFAULT_POSITION을 Position 타입으로 바꿔두고

```
        return cars.stream()
                .map(Car::position)
                .max(Comparator.comparingInt(Position::position))
                .orElse(DEFAULT_POSITION);
```

요렇게 표현도 가능할 것 같아요!

2023-11-08 16:47 UTC, shared-moon commented on src/main/java/step3/domain/Car.java
> +    public Name name() {
랩핑 클래스를 getter로 참조하는 경우는 그 자체로 그 데이터가 필요한 시점이지 않을까요 ? 그 외의 경우라면 질의를 통해 해결하는게 맞을 것 같구요..!
직접 사용을 한다고 하신 ResultView에서도 결국 꺼내자마자 다시 .name()으로 값을 꺼내고 있고 Position도 마찬가지구요!

모든 경우에 정답이라고는 말하기 어렵지만 대다수의 경우 필드를 그대로 리턴하는 getter보다 의도에 맞게 내부에서 직접 값을 만들어서 리턴하는게 추후 변경시에도 영향 범위를 줄일 수 있어 좋다고 생각합니다 ~

예를 들어 Car의 이름을 저장하는 클래스가 한 100글자 제한을 가진 LongName이라는 클래스로 바꿨다고 할 때, car.name 을 원시타입으로 리턴했을 경우에는 name()의 내부 구현만 바뀌면 되지만 Name을 그대로 리턴한 경우에는 name()을 호출하는 모든 곳이 변경되어야 할테니까요..!

2023-11-08 16:49 UTC, merged