자동차경주(우승자) step4 PR입니다.
next-step/java-racingcar pull request #5036
Opened 2023-11-07 19:37 UTC by akfls221

안녕하세요!

step3에서 리뷰해주신 내용을 기반으로 수정을 했습니다 ㅎㅎ

1. Controller에서 움직임에 대한 전략을 DI하는 것이 더 자연스럽단 생각이 들어 해당 부분을 수정했습니다.
2. 추가로 전략에대해 기존엔 움직여야할 position까지 반환했다면 움직일 수 있는지에 대한 여부를 반환하도록 수정했습니다.
3. 추가로 기능을 구현하다보니 Position이라는 객체의 역할이 애매하다는 생각이 들어 제거하는 방향으로 선택을 했습니다.

리뷰감사합니다 ㅎㅎ!

2023-11-08 10:04 UTC, serverwizard requested changes
태권님, 4단계 미션 잘 구현해 주셨어요. 👍
간단한 코멘트 남긴 내용 있는데 확인 한 번 부탁드립니다. 🙂

2023-11-08 10:04 UTC, serverwizard commented on src/main/java/racingcar/util/Splitter.java
> +    }
정말 꼼꼼하시네요 👍

2023-11-08 10:04 UTC, serverwizard commented on src/test/java/racingcar/domain/car/CarTest.java
> +            String inputName = "ServerWizard";
테스트 코드에 낯익은 뭔가가 나왔네요 😄

2023-11-08 10:04 UTC, serverwizard commented on src/test/java/racingcar/domain/game/RacingGameTest.java
> +    class SuccessCondition {
테스트 코드가 정말 꼼꼼 그 자체입니다. 👍

2023-11-08 11:28 UTC, akfls221 commented on src/main/java/racingcar/view/InputView.java
> +            throw new IllegalArgumentException("숫자만 입력할 수 있습니다.");
앗... 집중력이 떨어졌었나봅니다...ㅠㅠ 수정한다고 하고 두었네요ㅠㅠhttps://github.com/next-step/java-racingcar/pull/5036/commits/b0c43b33a276e8ef6b4b081c5c98d1621e614dda수정했습니다!

2023-11-08 11:28 UTC, akfls221 commented on src/main/java/racingcar/view/InputView.java
> +    public static String getCarCount() {
ㅎㅎ 여기도 ... 이전에 썼던 메소드명을 ...https://github.com/next-step/java-racingcar/pull/5036/commits/f464717b0267fd360f896cb8b27720eab452c6fc 수정했습니다!

2023-11-08 11:30 UTC, akfls221 commented on src/main/java/racingcar/domain/car/Car.java
> +        this.position = DEFAULT_CAR_POSITION;
넵 ㅎㅎ 명시하는게 좋다고 생각했는데 명시하지 않아도 될 상황이었던거 같습니다 https://github.com/next-step/java-racingcar/pull/5036/commits/41573dd3e2cd3bd1339176c31cea79e663b87cde 수정했습니다!

2023-11-08 11:35 UTC, akfls221 commented on src/main/java/racingcar/domain/car/Cars.java
> +                .filter(car -> car.getPosition() == getMaxPosition())
아하 맞네요 객체에 메세지만 전달하고 그 행동에대한 판단책임은 해당 객체가 들고있는점... 감사합니다!ㅎㅎ
https://github.com/next-step/java-racingcar/pull/5036/commits/36f30b9da12d9651496e38d11c593c93fc7a6779 수정했습니다 ㅎㅎ!

2023-11-08 11:35 UTC, akfls221 commented on src/main/java/racingcar/domain/game/RacingGame.java
> +    private Cars createCars(String inputCarName) {
자동차 생성에 대한 책임은 cars에 있는게 맞는거 같네요 ㅎㅎ cars의 생성이아닌 결국 자동차의 생성이니ㅎㅎ 감사합니다
https://github.com/next-step/java-racingcar/pull/5036/commits/699e5eca6084cf52352ecd5c76f41624f05e6424 수정했습니다!

2023-11-09 06:16 UTC, serverwizard approved these changes
태권님, 4단계 미션 잘 마무리하셨습니다. 👍
4단계 PR 머지하겠습니다.
5단계 미션에서 뵙겠습니다. 🙂

2023-11-09 06:16 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Cars.java
> +        this.cars = Arrays.stream(carNames)
일급 컬렉션에서 진행 👍

2023-11-09 06:16 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Cars.java
> +                .filter(car -> car.isEqualPosition(getMaxPosition()))
객체에게 메시지를 보내는(메소드 호출) 방식 👍

2023-11-09 06:16 UTC, merged