자동차 경주 - 단위테스트: 4) 자동차 경주(우승자)
next-step/java-racingcar pull request #5061
Opened 2023-11-08 16:14 UTC by gilbertlim

2023-11-09 13:12 UTC, mskangg requested changes
4단계도 잘구현해주셨네요! 👏 
랜덤요소를 주입받는 방식으로 구조를 변경해서 테스트도 쉽게하셨습니다! 👍 
몇가지 피드백 추가로 드렸으니, 고민해보시고 반영 부탁드립니다!

2023-11-09 13:12 UTC, mskangg commented on docs/step4.md
> +- [x] 자동차 경주 게임을 완료한 후 누가 우승했는지 알려줌(우승자는 1명 이상)
요구사항 체크리스트 💯

개인적인 팁을 드리자면, 요구사항을 상세히 작성하셨으니 그 워딩 그대로 테스트코드를 작성해보시는건 어떠신가요?

- [ ] 자동차 이름은 1자 이상 5자 이하

테스트코드에 그대로 작성! 
```
@DisplayName("자동차 이름은 1자 이상 5자 이하") 
void test()
```
한 뒤 TDD 한다면? 빠지는것 없이 요구사항을 만족할 수 있을겁니다 :)

2023-11-09 13:12 UTC, mskangg commented on src/main/java/study/step4/Car.java
> +    }
`자동차 이름은 1자 이상 5자 이하` 일 경우만 차가생성되야하는데, 지금 name에 validation 이 없네요..!

2023-11-09 13:12 UTC, mskangg commented on src/main/java/study/step4/Car.java
> +    private final String name;
지금도 충분하지만, 학습의 일환이니 원시값을 포장해보는것도 좋을것 같아요!
name 을 관리하는 CarName 값객체로 관리해보시는건 어떠신가요? 🤔

관련하여 링크 남겨드릴게요!
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/

2023-11-09 13:12 UTC, mskangg commented on src/main/java/study/step4/Car.java
> +    private static boolean isForwardCondition(int number) {
static일 필요 없을것 같아요 :)

2023-11-09 13:12 UTC, mskangg commented on src/main/java/study/step4/Racing.java
> +    NumberGenerator numberGenerator;
랜덤요소를 주입방식으로 뺐군요 👏

2023-11-09 13:12 UTC, mskangg commented on src/test/java/study/step4/RuleTest.java
> +    }
Rule 에서 `자동차 이름은 1자 이상 5자 이하` 를 검증하고 있군요!
그런데, 결국 자동차 이름을 상태로 관리하고 생애주기를 함께하고 있는 Car에선 정작 validation을 하고 있지 않고 있습니다!
이부분에 대해 고민이 필요해보여요! 🧐

2023-11-10 04:39 UTC, gilbertlim commented on src/test/java/study/step4/RuleTest.java
> +    }
자동차의 속성을 다른 주체에서 테스트하고 있었네요.
자동차에서 이름 validation이 되게끔 수정했습니다

2023-11-10 04:42 UTC, gilbertlim commented on src/main/java/study/step4/Car.java
> +    private final String name;
네 한번 시도해보겠습니다 ㅎㅎ

2023-11-11 08:07 UTC, mskangg approved these changes
피드백 반영 정말 잘해주셨습니다!! 👏 
소소한 피드백 남겨드렸으니, 다음 단계에 적용해주셔도 될것 같아요!
그럼 마지막 미션도 화이팅!! 🔥

2023-11-11 08:07 UTC, mskangg commented on src/main/java/study/step4/domain/Car.java
> +    }
생성자에서도 객체의 생성책임을 다하고 있군요 👍 

다만, 매개변수가 적은 생성자는 보통 부생성자라고해서 주생성자를 호출하는 방식을 사용합니다.

```java
    public Car(String name) {
        this(name, 1);
    }
```

이렇게 하면 validation과 같은 검증을 주생성자 안에서 진행할 수 있어요~!

2023-11-11 08:07 UTC, mskangg commented on src/main/java/study/step4/domain/CarName.java
> +    private final String name;
👍

2023-11-11 08:07 UTC, mskangg commented on src/main/java/study/step4/domain/Cars.java
> +    }
값을 꺼내서 사용하지 않고 메세지를 보내어 객체지향으로 구현해보시는건 어떠신가용?

```suggestion
    private void addWinner(List<Car> winners, Car car) {
        if (car.isWinner(maxPosition())) {
            winners.add(car);
        }
    }
```

2023-11-11 08:07 UTC, merged