4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5065
Opened 2023-11-08 17:05 UTC by ch200203

리뷰어님~ 4단계 리뷰 요청드립니다!

도메인단위로 테스트 코드를 분리해보는데 
`Round` 도메인에서 `playRound`를 실행하려고 하는데 랜덤 값이라서 위치가 잘 변화하였는지 테스트 코드로 확인하는 게 쉽지 않더라고요.
이럴 경우에는 어떻게 테스트 코드를 짜야 할까요? 
혹은 어떻게 구조를 변경하는게 테스트를 하는데 유리한 구조일까요?

2023-11-09 11:04 UTC, seokhong requested changes
철환님, 4단계 미션 잘 구현하셨습니다. 👍 
질문 남겨주신 내용에 대한 답변과 함께 코멘트 추가로 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-09 11:04 UTC, seokhong commented on src/main/java/racingcar/view/ResultView.java
> +    private String buildRoundResult(final Car car) {
여기도 메서드의 호출 순서와 배치 순서를 고민해보시면 좋겠습니다.

2023-11-09 11:04 UTC, seokhong commented on src/test/java/racingcar/CarTest.java
> Round 도메인에서 playRound를 실행하려고 하는데 랜덤 값이라서 위치가 잘 변화하였는지 테스트 코드로 확인하는 게 쉽지 않더라고요.
이럴 경우에는 어떻게 테스트 코드를 짜야 할까요?
혹은 어떻게 구조를 변경하는게 테스트를 하는데 유리한 구조일까요?

말씀하신 내용을 테스트하기 위해서는 `playRound` 가 실행됐을 때 항상 자동차가 이동하도록 제어하는 것이 필요해 보입니다. `Round` 를 생성하는 시점에 `RandomNumberGenerator` 를 전달하는데, 테스트에서는 `NumberGenerator` 를 구현한 다른 클래스를 만들어서 사용해보면 어떨까요? 예를 들어서 [5, 5, 5] 와 같이 리스트를 전달하면, 해당 리스트에 있는 값을 순서대로 반환하는 `NumberGenerator` 의 구현체를 만들 수도 있어 보입니다.

2023-11-11 16:55 UTC, ch200203 commented
리뷰어님! 말씀해주신 부분 추가해보면서 고민인 부분이 몇가지 있어 질문 드립니다.

생성자를 많이 사용하는 것에 대해서 어떻게 생각하는지 궁금합니다.
테스트 코드를 작성하고, 새로운 객체를 반환할려고 하다보니 도메인에 생성자를 계속 생성하는 일이 잦더라구요. 
그렇게 되다보니 생성자가 너무 많아지는 것 같아 코드가 지저분해지는 느낌을 받았습니다.

진행된 마지막 라운드를 가져오는 것과 Cars에서 바로 찾아서 쓰는 것 차이가 없는 경우에도
게임 진행 로직에 맞춰서 `List<Round>`를 만들고 여기서 마지막 `Round`를 꺼내고 다시 `Cars`를 꺼내는 과정에 맞게 테스트를 진행하는게 맞는지 궁금합니다.

2023-11-12 08:28 UTC, seokhong approved these changes
철환님, 4단계 미션 코멘트 잘 반영하셨습니다. 👍 
4단계 PR 머지하겠습니다.
질문 남겨주신 내용에 대한 답변과 함께 코멘트 추가로 남겼습니다. 이 내용은 다음 단계 미션에서 참고 부탁드립니다.
5단계 미션에서 뵙겠습니다. 🙂

2023-11-12 08:28 UTC, seokhong commented on src/test/java/racingcar/CarsTest.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.  
파일 마지막의 newline 은 무슨 역할을 하는지 학습해보신 후, IDE 설정을 통해 휴먼 에러를 방지해보시면 좋겠습니다.

2023-11-12 08:28 UTC, seokhong commented on src/test/java/racingcar/CarsTest.java
> +        Car avante = new Car("아반떼", 5);
> 생성자를 많이 사용하는 것에 대해서 어떻게 생각하는지 궁금합니다.
테스트 코드를 작성하고, 새로운 객체를 반환할려고 하다보니 도메인에 생성자를 계속 생성하는 일이 잦더라구요.
그렇게 되다보니 생성자가 너무 많아지는 것 같아 코드가 지저분해지는 느낌을 받았습니다.

이 질문과 연결된 코드라고 생각해서, 여기에 코멘트 남깁니다.

생성자를 많이 사용하는 것이, 여러 곳에서 호출하는 것이 아니라 여러 종류의 생성자를 만드는 것이라는 측면에서 봤을 때 프로덕션 코드의 필요에 의해 다양한 생성자를 제공하는 것은 괜찮다고 생각합니다.
다만, 테스트에서 사용하기 위해 생성자를 추가하는 것은 지양해야 한다고 생각합니다. 비단 생성자뿐만 아니라, 테스트만을 위한 메서드 생성도 동일하게 생각합니다. 테스트 코드가 프로덕션 코드에 의존하고 있으므로 테스트로 인해 프로덕션 코드의 변경이 발생하면 안 된다고 생각하며(의존성 측면), 테스트는 프로덕션 코드와 동일한 코드를 이용해 작성해야 프로덕션에서 사용하는 코드를 모두 검증할 수 있다고 생각하기 생각하기 때문입니다.

프로덕션의 여러 곳에서 생성자를 사용하는 측면에 대해서는, 이 경우 코드의 결합도와 응집도를 살펴봐야 한다고 생각합니다. 여러 곳에서 객체를 생성한다는 것은 많은 코드가 결합되어 있다는 것일 수도 있어서, 구조를 변경해야 할 필요가 있을 수도 있습니다. 구체적인 코드를 가지고 얘기해보면 좀 더 깊은 이야기를 나눌 수 있을 것 같습니다.

2023-11-12 08:28 UTC, seokhong commented on src/test/java/racingcar/RacingGameTest.java
> +class RacingGameTest {
> 진행된 마지막 라운드를 가져오는 것과 Cars에서 바로 찾아서 쓰는 것 차이가 없는 경우에도
게임 진행 로직에 맞춰서 List<Round>를 만들고 여기서 마지막 Round를 꺼내고 다시 Cars를 꺼내는 과정에 맞게 테스트를 진행하는게 맞는지 궁금합니다.

이는 프로덕션 코드의 구현이 이렇게 되어 있는 상황이고, 프로덕션 코드가 잘 동작하는지 검증하는 측면에서 필요할 수 있다고 생각합니다. `RacingGame` 이 `List<Round>`를 반환하도록 되어 있으므로, `RacingGame` 의 정상 동작을 검증하기 위해서는 어쩔 수 없이 `List<Round>`를 가져와서 확인해야 할 것 같네요.

이 테스트 코드는 검증하는 내용이 없는데, 아마도 위 질문과 연결되어 있어서 그럴 것이라고 생각합니다. :)
다음 단계를 진행하시며 위 내용, 코드에 남긴 코멘트와 함께 고민해보시면 좋겠습니다!

2023-11-12 08:28 UTC, seokhong commented on src/main/java/racingcar/domain/Car.java
> +    public boolean isAtMaxPosition(final int maxPosition) {
인자로 `maxPosition` 이 아닌 어떤 값이 들어오더라도, 해당 위치에 있으면 true 를 반환할 것으로 보입니다.
`isAtPosition` 으로 이름을 변경해보면 어떨까요? 이 메서드를 사용하는 곳에서 항상 `maxPosition` 을 전달해줄 것이라고 가정하기보다는, 이 메서드의 기능을 중심으로 이름을 작성해보시면 좋겠습니다.

2023-11-12 08:28 UTC, seokhong commented on src/main/java/racingcar/domain/Car.java
> +        return position.getPosition() == maxPosition;
`maxPosition` 도 `Position` 타입으로 전달받을 수 있지 않을까요?
`position.getPosition()` 으로 값을 꺼내서 비교하기보다는, `position` 에게 `maxPosition` 을 전달해서 같은 값인지 물어보는 건 어떨까요?

2023-11-12 08:28 UTC, seokhong commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final int truCountNumber;
`tru` 가 `try` 의 오타로 보이네요!

2023-11-12 08:28 UTC, seokhong commented on src/main/java/racingcar/domain/Winners.java
> +    public List<Car> findWinners(final Cars cars) {
이 기능은 `Cars` 또는 `RacingGame` 에서 제공할 수도 있지 않을까요?
`RacingGame` 에게 `findWinners` 를 요청하면, `RacingGame` 이 `Cars` 에게 가장 앞선 자동차의 위치를 요청하고, 이후 해당 위치에 있는 차 목록을 요청하는 형태로도 변경이 가능해 보입니다. `RacingGame` 과 `Cars` 를 말씀드린 이유는, 이 메서드는 `Cars` 만 있으면 동작하는 기능이므로, `Cars` 클래스에서 직접 제공하거나, `Cars` 를 필드로 가진 `RacingGame` 이 제공하는 것이 응집도가 더 높아지는 방향이라고 생각하기 때문입니다.

2023-11-12 08:28 UTC, merged

2023-11-14 00:21 UTC, ch200203 commented on src/test/java/racingcar/RacingGameTest.java
> +class RacingGameTest {
넵 5단계 리팩터링 미션에서 더 고민해 보도록 하겠습니다 :)

2023-11-14 00:57 UTC, ch200203 commented on src/main/java/racingcar/domain/Winners.java
> +    public List<Car> findWinners(final Cars cars) {
자동차들이라는 메인 도메인에서 별도로 관리했던 이유는 'Winners'라는 개념이 'Car'라는 큰 개념에서 파생된 개념이라고 생각했었습니다. `Cars`는 참여한 자동차들, `Winners`는 우승한 자동차들 이라는 개념으로 생각했는데요.
따라서 도메인을 분리해야지 테스트를 단위적으로 할 수 있을 거라는 생각을 했었습니다.
말씀하신것처럼 Car -> Cars, Car -> Winners 대신 Car -> Cars -> Winners(가장 앞선 자동차들) 이라는 방식으로 생각하는 것이 응집도를 위해서 좀 더 용이할 것 같네요!