<feat> step3 자동차 경주
next-step/java-racingcar pull request #5078
Opened 2023-11-09 08:29 UTC by jmnl225

안녕하세요 ㅠㅠ
분명 로컬에서 step3 브런치를 새로 파서
기능목록을 작성하고 하나씩 커밋을 했는데
마지막에 푸시할때 제가 깃을 잘못건드려서 step3 깃 기록이 모두 날라가버렸습니다...... ㅠㅠㅠㅠ
그래서 local history에 있는 파일만 복구해서 과정없는 결과물만 전달드리게 되었습니다. 죄송합니다ㅠ..

미션을 진행하면서 기능목록을 따라 개발했지만 TDD의 훈련을 제대로 하지 못했습니다.
분명 테스트케이스를 먼저 만들고 설계대로 개발을 진행해야하는데 테스트케이스를 나중에 작성하고 있었습니다. ㅠㅠ
어떻게해야 테스트 케이스를 먼저 만들고 개발하는 방법을 적용할 수 있는지 팁이 있을까요?

제가 진행한 순서는 다음과 같습니다.
UI클래스 (InputView , ResulteView) 생성 - 사용자에게 받은 데이터 excpetion 처리 - 받은 데이터 출력 테스트 코드 작성 - 메인 로직: 난수 생성 - 출력 코드 작성

2023-11-09 10:33 UTC, ohtaeg requested changes
3단계 미션도 잘 수행해주셨습니다 👍 
주셨던 질문에 대해 코멘트 및 피드백들을 드렸는데 한번 고민해보시면 좋을 것 같아요 :D
반영 후 재요청 부탁드립니다 😄

2023-11-09 10:33 UTC, ohtaeg commented on README.md
> +5. 리팩토링
> 미션을 진행하면서 기능목록을 따라 개발했지만 TDD의 훈련을 제대로 하지 못했습니다.
분명 테스트케이스를 먼저 만들고 설계대로 개발을 진행해야하는데 테스트케이스를 나중에 작성하고 있었습니다. ㅠㅠ
어떻게해야 테스트 케이스를 먼저 만들고 개발하는 방법을 적용할 수 있는지 팁이 있을까요?

저는 맨땅에서 미션을 진행할 때 최소한의 설계를 먼저 하는 편입니다 ㅎㅎ
**요구사항을 통해 명사 동사들을 분리**해서 어떤 기능이 있고 어떤 객체들이 필요한지 리스트업 해놓는 다음
리스트업한 내용 바탕으로 추상화하는 과정을 거칩니다..!

작은 단위, 기능부터 개발하는 편이며, 이때 어떤 값을 파라미터로 받아야 어떤 값을 리턴해야하는지 설계를 하면서 코드를 작성합니다 :) 
'이런 입력 값을 넣으면 이런 값이 반환될거야 혹은 이런 동작을 하게될거야' 라는 식으로 테스트 코드를 작성하며
이때 필요한 값이 바뀌거나 반환 값이 바뀌거나 의존 관계의 수정 등이 발생하게되면서 실패하면서 리팩토링하는 TDD 사이클을 맛보게 되더라구요 :)

2023-11-09 10:33 UTC, ohtaeg commented on src/main/java/study/InputView.java
> +public class InputView {
View를 만들어주셨네요 👍

2023-11-09 10:33 UTC, ohtaeg commented on src/main/java/study/ResultView.java
> +    }
static 메서드로만 이루어진 객체라면 인스턴스를 생성하지 않도록 하면 좋을 것 같아요 :)

2023-11-09 10:33 UTC, ohtaeg commented on src/main/java/study/RacingCar.java
> +        Random random = new Random();
getRandom() 메서드를 수행할 때마다 Random 객체가 생성되는 구조군요!
Random 객체를 재사용하는 방향은 어떨까요?

2023-11-09 10:33 UTC, ohtaeg commented on src/main/java/study/RacingCar.java
> +import static study.StringAddCalculator.splitAndSum;
2단계 미션인 문자열 계산기와 자동차 경주 미션은 별도의 미션이라 패키지 분리를 통해 서로 의존하지 않도록 변경해주시면 좋을 것 같아요 😄

2023-11-09 10:33 UTC, ohtaeg commented on src/main/java/study/RacingCar.java
> +public class RacingCar {
RacingCar에대한 테스트 코드가 없는데요! 중요한 비지니스 로직을 다루는 객체는 꼭 테스트 코드를 작성해주세요 😄 

만약 테스트하기 힘든 구조라면 RacingCar가 가지고 있는 기능을 
최소한으로 메서드 분리하면서 클래스 분리를 해보면 좋을 것 같아요 :)

테스트 코드를 작성하면 좋은 점 중 하나가 “예측 가능한 결과“에 대한 로직을 만들 수 있다는 것입니다.
특정 입력값에 대해 특정 결과값이 나오는 것을 예측 가능하도록 작성해보세요!
반대로 생각하면, 결과 예측이 안되는 메소드의 경우 설계가 잘못되었거나 많은 기능을 가지고 있다는 뜻인데요!

제가 보았을 땐 게임의 흐름을 중재하는 책임과 자동차를 직접 움직이게 하는 책임들을 가지고 있는 것 같아요 :)
RacingCar에 대한 책임은 무엇으로 정의하셨을까요?

2023-11-15 08:33 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨습니다 👍 
몇개의 코멘트를 더 드렸는데 확인해주신 후 반영해주시면 감사하겠습니다 :)
잘 개선되고 있으니 다음 미션을 수월하게 진행하기 위해 한번 더 리팩토링 해보면 좋을 것 같아요 😄 
화이팅입니다 🔥

2023-11-15 08:33 UTC, ohtaeg commented on src/main/java/study/racingCar/Controller.java
> +                    p = p.increase(model.randomNum());
Position을 Car 객체가 갖고 있도록 설계를 해주셨다면 Position을 갖고오지말고 Car에게 직접 물어보면 어떨까요 :) ?
상태를 가지는 객체를 설계를 해주셨다면 내부 데이터를 노출시켜 로직을 처리하도록 구현하지 말고
해당 객체에 메시지를 보내 그 객체 스스로가 일을 할 수 있도록 설계하는 방향으로 리팩토링 해볼 수 있을까요? 😄

2023-11-15 08:38 UTC, jmnl225 commented on src/main/java/study/racingCar/Position.java
> +    int position(){
default가 아니면 테스트를 할 수 없어서 private에서 변경했습니다.
ㅠㅠ 이 부분으로 고민이 많았는데 접근제어자가 private일 경우에는 테스트 코드를 아예 작성하지 않아야하나요?
public 접근제어자를 최소한으로 줄이고 싶은데 private를 대체하기 위해 default로 설정하는 게 맞는지 잘 모르겠습니다.. 이런 부분은 어떻게 제가 지식을 보완할 수 있을까요!? ㅠㅠㅠ 너무 스스로가 답답하네요..

2023-11-15 08:40 UTC, jmnl225 commented on src/main/java/study/racingCar/RacingModel.java
> +public class RacingModel {
MVC 모델로 나누어서 만들어보고싶었는데 결과적으로 랜덤값만 제공하는 객체가 되었습니다..

2023-11-15 08:42 UTC, ohtaeg commented on src/main/java/study/racingCar/Position.java
> +    int position(){
테스트를 작성할 때 외부에 공개된 메서드 혹은 인터페이스만 사용해야 된다고 생각합니다.
private 메서드는 외부에 노출되지 않는 객체의 세부 사항을 구현할텐데요 :)
객체의 세부 사항이 구현된 private 메서드를 테스트한다는 것은 내부 정보를 보여 주는 것과 다름이 없다고 생각해요!
그렇기 때문에 정보 은닉을 위배한다고 생각합니다.

또한 private 메서드에 대해 테스트 코드를 작성한다면 테스트 코드와 프로덕션 코드의 결합도가 강해질 것 같아요. 프로덕션 코드의 수정이 생긴다면 public, private 테스트 코드들을 전부 수정해야 겠죠?
보통 private 메서드 같은 경우는 public 메소드에 의해 도출되어 나온 것이므로
private 메서드의 호출은 결국 외부에 공개된 메서드들이 호출하는 경우가 아닐까 싶어요.
그렇기 때문에 **public 메서드를 통해 private 메서드들을 간접적으로 테스트를 하는 것이 자연스럽다고 생각**합니다.

만약 private 메서드를 간접적으로 테스트하는 것만으로 충분하지 않고 따로 테스트해야 된다는 것은
리팩토링이 필요하다는 신호이므로 클래스 분리나 메서드 분리 등을 생각해보는 것도 좋을 것 같습니다.

2023-11-15 08:42 UTC, jmnl225 commented on src/main/java/study/racingCar/Position.java
> +        return new Position();
이 부분은 제가 재성님께 조언을 받아서 한번 wrapping을 한 상태로 리턴을 해보도록 구현해보았습니다. 그런데 말씀주신것과 같이 new Position()으로 객체를 새로 생성하면 값이 초기화가 되어버려서ㅠㅠ 그냥 기존의 자기 자신을 Position() 객체로 리턴하도록 수정해보겠습니다!

2023-11-15 08:43 UTC, ohtaeg commented on src/main/java/study/racingCar/Position.java
> +    int position(){
> 이런 부분은 어떻게 제가 지식을 보완할 수 있을까요!? ㅠㅠㅠ 너무 스스로가 답답하네요..

누구나 다 처음부터 잘할 수 없습니다 ㅎㅎ 저또한 비슷한 고민을 많이 했었구요!
그래서 많은 분들과 얘기도 나눠보고 많은 코드를 접하게되면 성장을 하게 될거에요 😄 
이미 충분히 잘해주고 계시니 너무 걱정하지마시구 스트레스 받지마세요!!

2023-11-15 08:46 UTC, ohtaeg commented on src/main/java/study/racingCar/RacingModel.java
> +public class RacingModel {
아하 이해완료 하였습니다 😄 
RacingModel이란 클래스 명이 조금 넓은 의미로 이해되기도 하고 명확하지 않아서 여쭤보게 되었습니다 :)
현재 랜덤값만 제공하는 객체가 되었다면 랜덤을 기준으로 네이밍을 해보면 어떨까요 :) ?

2023-11-15 10:21 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨어요 👍 👍 
소소한 코멘트들을 드렸는데 다음 미션을 진행하시면서 고민해보시면 좋을 것 같아요 :)
4단계도 화이팅입니다 🔥

2023-11-15 10:21 UTC, ohtaeg commented on src/main/java/study/racingCar/PlayCarRacingGame.java
> +            carList.getCar(j).move(generator.randomNum());
Car에게 직접 물어보도록 변경 👍

2023-11-15 10:21 UTC, ohtaeg commented on src/main/java/study/racingCar/Position.java
> +        return this;
👍 👍

2023-11-15 10:21 UTC, ohtaeg commented on src/main/java/study/racingCar/CarList.java
> +    private Car[] carList;
개인적으로 변수 명에 String과 같은 타입, List 등과 같은 자료형을 네이밍에 넣는 것을 권장 드리지 않는데요 :)
변수 명에 자료형을 쓰지 않아도 타입을 통해 충분히 어떤 변수인지 파악이 가능하다고 생각하며
만약 타입 변경시 변수 명도 변경해야되는 관리 포인트가 증가하는 단점도 존재한다고 생각합니다! ㅎㅎ

2023-11-15 10:21 UTC, ohtaeg commented on src/main/java/study/racingCar/PlayCarRacingGame.java
> +    public void play(int cars, CarList carList){
이미 CarList 객체를 통해 자동차들을 관리하고 있기에 cars int값이 따로 필요한지 고민해보시면 좋을 것 같아요 :)

2023-11-15 10:21 UTC, ohtaeg commented on src/main/java/study/racingCar/PlayCarRacingGame.java
> +            carList.getCar(j).move(generator.randomNum());
만약 해당 피드백이 반영된다면 CarList에 자동차들을 관리하고 있기에 CarList를 통해 움직이도록 하면 어떨까요 :) ?

```suggestion
    public void play(int cars, CarList carList){
        RandomNumGenerator generator = new RandomNumGenerator();
        cars.move(generator);
```

2023-11-15 10:22 UTC, merged