4단계 - 자동차 경주(우승)
next-step/java-racingcar pull request #5085
Opened 2023-11-09 15:57 UTC by sunga08

4단계 리뷰 요청드립니다.

4단계를 진행하면서 고민되는 부분이 있어서 같이 남깁니다. 감사합니다 🙂

1. 구현 내용상으로는 3,4단계가 이어지는것 같은데, 3단계에서 구현한 객체나 메소드를 4단계에서 사용할 수 있는 것도 있지만, 활용하지 못하는 상황이 되는 경우엔 이전에 만든 것은 그냥 두고 다음단계를  위한 객체나 메소드를 구현하는게 맞을까요? 
예를들면 제 코드에서 3단계에서 사용한 Cars객체나 RacingCar의 addMoving, movingResult 메소드는 4단계 구현시에는 활용하지 못하는데 그냥 이 상태로 둬도 괜찮은지요..! 아니면 3단계, 4단계를 별도의 클래스로 분리해야하는건지..아니면 두 단계 모두에서 활용할 수 있는 방향으로 리팩토링을 해야하는건지 고민이 되었습니다..

2. 각 단계의 main 함수도 별도의 클래스로 분리해야 할까요?

2023-11-10 08:36 UTC, wooobo requested changes
안녕하세요 성아님!

4단계 잘진행해주셨습니다!!!
몇가지 코멘트 남겨놓았는데 확인 후 재요청 부탁드려요~

화이팅입니다~!

2023-11-10 08:36 UTC, wooobo commented on src/main/java/racingCar/RacingCar.java
>  public class RacingCar {
> 구현 내용상으로는 3,4단계가 이어지는것 같은데, 3단계에서 구현한 객체나 메소드를 4단계에서 사용할 수 있는 것도 있지만, 활용하지 못하는 상황이 되는 경우엔 이전에 만든 것은 그냥 두고 다음단계를 위한 객체나 메소드를 구현하는게 맞을까요?
예를들면 제 코드에서 3단계에서 사용한 Cars객체나 RacingCar의 addMoving, movingResult 메소드는 4단계 구현시에는 활용하지 못하는데 그냥 이 상태로 둬도 괜찮은지요..! 아니면 3단계, 4단계를 별도의 클래스로 분리해야하는건지..아니면 두 단계 모두에서 활용할 수 있는 방향으로 리팩토링을 해야하는건지 고민이 되었습니다..

실제 프로덕션 코드 만드신다는 생각으로 해주시면 됩니다~
그렇다면, 리팩토링 혹은 변경되는 구조에 따라서 사용하지 않는 코드는 제거하고
적절한 commit 메시지와 함께 commit해주시면 됩니다!

답변이 되었을까요~?

2023-11-10 08:36 UTC, wooobo commented on src/main/java/racingCar/RacingCar.java
>  public class RacingCar {
> 각 단계의 main 함수도 별도의 클래스로 분리해야 할까요?

자동차 경주는 하나의 섹션이므로 그렇게 하실필요는 없다고 생각합니다~ ^^

2023-11-10 08:36 UTC, wooobo commented on src/test/java/racingCar/racingCarTest.java
> +            assertThat(cars.getCarList().get(i).getForwardCnt()).isBetween(0, 5);
[[OOP] 디미터의 법칙(Law of Demeter)](https://mangkyu.tistory.com/147)

객체에게 값을 꺼내오기 보다는, 객체간의 비교를 하거나 적절한 메시지를 던지면 좋을것 같아요! 

이런 느낌으로요!
`assertThat(cars.forwardCountOf(i)).isBetween(0, 5);`

2023-11-10 08:36 UTC, wooobo commented on src/test/java/racingCar/racingCarTest.java
> +            assertThat(cars.getCarList().get(i).getForwardCnt()).isBetween(0, 5);
### 객체지향 생활 체조 원칙이란?

...
규칙 5: 줄여쓰지 않는다(축약 금지).
...

이번 과정진행하는 동안은 축약보다는 명확한 메세지를 전달할수 있도록 해보아요~

`cnt->count`

2023-11-10 08:36 UTC, wooobo commented on src/test/java/racingCar/racingCarTest.java
> +        assertThat(cars.getCarList().get(0).getCarName()).isEqualTo("aaa");
`assertAll`을 활용해보아요~

2023-11-10 08:36 UTC, wooobo commented on src/test/java/racingCar/racingCarTest.java
> +    @DisplayName("자동차 이름이 5자를 초과할 경우 예외를 발생한다.")
비지니스 로직이 변경되면, 테스트 설명으로 인해 혼란스러울것 같아요!
좀 더 일반화하면 어떨까요? 
`자동차 이름의 최대길이를 넘으면 예외발생` 이런식으로요!

2023-11-10 08:36 UTC, wooobo commented on src/main/java/racingCar/Car.java
> +        if(carName.length()>5){
```suggestion
        if(carName.length()> MAX_NAME_LENGTH){
```

매직넘버를 의미를 드러내는 상수화해보아도 좋겠네요!

2023-11-13 15:49 UTC, sunga08 commented on src/test/java/racingCar/racingCarTest.java
> +            assertThat(cars.getCarList().get(i).getForwardCnt()).isBetween(0, 5);
메시지를 던지기 위해서 cars.forwardCountof()를 구현하면 테스트를 위한 메소드를 구현하게 되는 것 같은데 괜찮은걸까요?

2023-11-14 07:34 UTC, wooobo approved these changes
안녕하세요 성아님!

4단계 잘 진행해주셨습니다!
몇가지 코멘트 남겨 놓았는데 다음단계 진행시 참고 부탁드려요~ 

화이팅입니다!

2023-11-14 07:34 UTC, wooobo commented on src/main/java/racingCar/RacingCar.java
> +            System.out.println();
`ResultView` 를 만들어 주셨으니 `System.out.println();` `ResultView`쪽 책임이 아닐지 고민이되네요!

2023-11-14 07:34 UTC, wooobo commented on src/test/java/racingCar/racingCarTest.java
> +                () -> assertThat(cars.carNameOf(0)).isEqualTo("pobi"),
값을 꺼내와서 비교하려고하는 부분들이 많아보여요.
`equals`,`hashcode`함수를 재정의해서 객체간의 비교해보면 어떨까요?

```suggestion
                () -> assertThat(cars.find(1)).isEqualTo(new Car("pobi",1)),
                
                또는
                
                () -> assertThat(cars.contains(new Car("pobi",1))).isTrue(),
```

예를 들면 이런식으로요!

2023-11-14 07:46 UTC, merged