🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5086
Opened 2023-11-09 17:09 UTC by chunghyunleeme

step4 와 슬랙에도 남겼지만, 보기 편하시라고 여기에도 동일한 질문 남기겠습니다!

저는 domain 패키지 밑에 car, racing 패키지를 별도로 구분 하고
racing 클래스 List를 담는 ParticipatingCars라는 일급 콜랙션으로 분리를 하였는데,
우선 여기서 질문은 Car클래스에 디폴트 접근제어자로 이름과 위치를 세팅하는 생성자가 있는데
우승자를 구하는 함수는 racing 패키지 밑에 ParticipatingCars클래스 안에 있기 때문에 위에 만든 디폴트 생성자를 사용하지 못하여
RacingTest에서 car의 위치를 세팅을 못하는데, 이런 경우 car와 racing의 패키지를 나누지 말았어야 할까요?

2023-11-10 10:59 UTC, seokhong commented
질문 남겨주신 내용은 step4 코멘트에 답변 드려서 생략하겠습니다. :)
동일한 질문이라면 링크를 이용해서 질문을 공유해주시면, 원하시는 한 곳에서 답변을 받을 수 있을 것 같습니다~!

2023-11-10 11:10 UTC, seokhong requested changes
충현님, 마지막 단계 미션 잘 구현하셨습니다. 👍 
이번 단계 미션 내용 중 "**테스트 가능한 부분과 테스트하기 힘든 부분을 분리해 테스트 가능한 부분에 대해서만 단위 테스트**를 진행한다." 를 진행할 수 있는 방법을 고민해서 적용해보시면 더 도움이 될 것 같습니다. 이외에 코멘트 조금 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-10 11:10 UTC, seokhong commented on src/main/java/racing/domain/car/Car.java
> +    private final static int THRESHOLD = 4;
오라클 문서에 따르면 자바에서 상수(static variables)는 필드보다 상단에 배치합니다. :)

> https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2023-11-10 11:10 UTC, seokhong commented on src/main/java/racing/domain/car/Car.java
>      public Car(String name, int position) {
이 생성자는 테스트만을 위해 필요한 것으로 보이네요.
난수 생성 방법을 제어함으로써 자동차의 이동 여부를 제어할 수 있으니, 이 생성자는 삭제하고 다른 방법으로 테스트하면 어떨까요?

2023-11-10 11:10 UTC, seokhong commented on src/main/java/racing/domain/car/Car.java
>      private boolean isOverThreshHold(int input) {
이 메서드는 `move` 에서 사용되니, `move` 메서드에 이어서 배치해보면 어떨까요?
클린 코드 책의 "위에서 아래로 코드 읽기: 내려가기 규칙" 을 참고해보시면 좋겠습니다.

2023-11-10 11:10 UTC, seokhong commented on src/main/java/racing/domain/racing/Racing.java
>              int input = random.nextInt(RANDOM_SEED_NUMBER);
난수 생성을 제어하는 방법을 고민하고 적용해보시면 도움이 될 것 같습니다!
현재 `Racing` 내부에서 `Random` 을 생성하고, 이를 이용해서 난수를 생성하는데요. 난수를 생성하는 클래스를 만들고, 이를 `Racing` 을 생성할 때 외부에서 전달해주면 어떨까요? 테스트에서는 다른 클래스를 전달함으로써, 테스트가 실행될 때 난수 생성을 제어하고 도메인을 테스트 할 수 있을 것 같습니다.

> https://edu.nextstep.camp/s/twbNYuxs/ls/0dqXf2eV

2023-11-10 11:10 UTC, seokhong commented on src/main/java/racing/domain/racing/Racing.java
> +            int max = 0;
`Position` 을 비교하고, `Position` 의 최댓값을 반환하는 메서드로 보이네요.
`int max;` 대신, `Position max;` 로 선언하고 구현할 수 있는 방법이 있을까요? `car#isForward` 도 `Position` 을 인자로 받아도 동작하도록 구현이 가능할 것 같아요!

2023-11-10 11:10 UTC, seokhong commented on src/test/java/racing/domain/car/CarTest.java
> +    void winner() {
이 테스트는 삭제해도 괜찮을까요?

2023-11-10 11:10 UTC, seokhong commented on src/test/java/racing/domain/car/PositionTest.java
> +public class PositionTest {
포지션에 대한 단위 테스트 작성 좋습니다. 👍 
포지션의 크기 비교 메서드(`compareTo`)도 구현하셨으니, 이를 테스트하고 활용해보셔도 좋겠습니다. :)

2023-11-13 11:09 UTC, chunghyunleeme commented on src/main/java/racing/domain/car/Car.java
>      private boolean isOverThreshHold(int input) {
넵 뭔가 public 함수 먼저, private 함수는 따로 나눠야 할 것같아서 그랬는데,
말씀해주신 방식이 더 가독성 측면에서 좋아보이네요!

2023-11-14 05:32 UTC, seokhong requested changes
충현님, 마지막 미션 코멘트 잘 반영하셨습니다. 👍 
"**테스트 가능한 부분과 테스트하기 힘든 부분을 분리해 테스트 가능한 부분에 대해서만 단위 테스트를 진행한다.**"를 진행하시기 위해 `RandomNumber` 객체를 추가하신 것으로 보이는데요. 이를 활용해서 테스트에서 난수 생성을 제어하는 코드를 구현해보시면 도움이 될 것 같아서 코멘트를 추가로 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-14 05:32 UTC, seokhong commented on src/main/java/racing/domain/racing/RandomNumber.java
> +    public RandomNumber(int bound) {
최초 생성하는 시점에 난수를 생성해서 필드로 저장하면, 이후 `randomNumber()` 메서드 호출시에는 항상 같은 값이 반환될 것으로 보입니다.
`randomNumbeer()` 메서드로 요청이 오는 시점에 난수를 생성해서 반환하면 어떨까요?

2023-11-14 05:32 UTC, seokhong commented on src/main/java/racing/domain/racing/Racing.java
> +    private final RandomNumber randomNumber;
난수를 생성하는 객체를 만드신 것 같은데, 실제 코드에서는 여전히 `Racing` 에서 생성한 `Random` 을 통해 난수를 생성하네요. `RandomNumber` 를 통해 난수를 생성하도록 변경해보면 어떨까요?

2023-11-14 05:32 UTC, seokhong commented on src/test/java/racing/domain/racing/RacingTest.java
> +    void winners() {
`Racing` 이 난수를 생성하는 `RandomNumber` 객체를 인자로 받을 수 있게 되었으니, 이제 `Racing` 을 생성한 후 경주를 진행해서 우승자를 판단할 수 있을 것 같아요.
기존에는 `Racing` 을 생성하고 경주를 진행하면, `RandomNumber` 가 난수를 생성하므로 경주의 결과가 랜덤으로 나왔을텐데요. 이제 `RandomNumber` 를 상속(또는 별도의 인터페이스를 추가하고 구현)한 클래스를 만들고, 테스트에서 해당 클래스가 정해진 숫자를 반환하도록 제어하면 우승자도 테스트에서 정할 수 있겠네요. 예를 들어, 정해진 숫자를 반환하는 클래스가 5, 1, 5, 1, 5, 1을 순서대로 반환하도록 하고 두 대의 자동차가 경주에 참여하는 상황이라고 하면, 항상 첫 번째 자동차는 이동하고 두 번째 자동차는 멈춰 있으므로 첫 번째 자동차가 우승자로 나올 수 있겠네요.

2023-11-16 08:13 UTC, merged