deepredk(김진홍) 자동차경주 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5089
Opened 2023-11-09 23:39 UTC by deepredk

안녕하세요! 구현 및 리팩토링 완료했습니다.

2가지 부분이 조금 걸립니다.

1번째는 아래 코드입니다
```java
    @Test
    @DisplayName("자동차 이름들을 ,로 구분하여 받아 자동차들을 생성한다")
    void carNames() {
        // given
        DriveStrategy driveStrategy = () -> false;
        Cars cars = new Cars(driveStrategy, "a,b");

        // when
        RoundResult roundResult = cars.drive();
        List<DriveResult> driveResults = roundResult.driveResults();

        // then
        assertThat(driveResults.size()).isEqualTo(2);
        assertThat(driveResults.get(0).name).isEqualTo("a");
        assertThat(driveResults.get(1).name).isEqualTo("b");
    }
```
Cars에서 테스트만을 위해서 List<Car>을 반환하는 메서드를 만들거나 하고싶지 않아서
cars.drive()의 결과를 이용해서 name을 확인하도록 했는데 이렇게 해도 괜찮은건지 궁금합니다.

2번째는 아래 코드입니다
```java
    private static String[] getWinners(List<DriveResult> driveResults, int maxDistance) {
        List<String> winners = new ArrayList<>();
        // 이 부분 Stream 사용 안하고 indent 1이 나오게끔 할 수 있는 좋은 방법이 있을까요??
        for (DriveResult driveResult : driveResults) {
            if (driveResult.drivenDistance == maxDistance) {
                winners.add(driveResult.name);
            }
        }
        return winners.toArray(String[]::new);
    }
```
Stream을 사용하지 않고 indent를 1로 줄이는 방법이 조금 억지스러운 `addIfWinner(List<String> winners, DriveResult driveResult)`밖에 생각이 안 나서 indent 2로 유지했는데 혹시 이에 대해 조언주시면 감사드릴 것 같습니다!

외에도 피드백 많이 부탁드립니다 ㅎㅎ

p.s.: 3단계 때 꼼꼼한 피드백 많이 주신 덕분에 많은 부분 배웠습니다 감사합니다 ㅎㅎㅎ

2023-11-10 09:59 UTC, csh0034 requested changes
4단계 구현하시느라 수고많으셨습니다 😃 
몇가지 코멘트 남겨두었는데 확인부탁드려요!

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/Car.java
> +        validateName(name);
생성자를 통해 이름 검증을 해주신점 너무 좋네요 👍

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/Car.java
> +        if (name.length() > 5) {
경계값이 되는 조건은 상수로 선언해보면 좋을것같아요.
이를 활용하여 테스트코드에서도 참조가 가능합니다.

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/Cars.java
> +        String[] arrCarNames = carNames.split(",");
값을 전달 받을때 view 에서 구분자를 통해 분리된 문자열 배열 또는 리스트를 받는건 어떨까요? 🤔
만약 ui 의 관심사에 해당하는 문자열 구분자가 변경된다면 도메인까지 영향이 있을것 같습니다!

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/view/RacingInputView.java
> +    private RacingInputView() {
private 생성자를 통한 인스턴스화 방지 👍

class 키워드앞에 final 을 추가하여 상속을 막으면서 생성자 내부에서 예외까지 발생시킨다면
내부에서도 인스턴스화를 할수없도록 처리 가능할것 같아요.

`java.util.Objets` 생성자를 보시면 좋을것 같습니다.

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/Car.java
> +    public String name() {
테스트를 위해 해당 메서드가 추가되었네요!
반드시 테스트에서 검증을 해야한다면 default 또는 protected 로 선언하여 외부 패키지에서 호출하지 못하도록 하는 방법도 있을것 같아요.

하단 코멘트는 꼭 적용은 안하셔도됩니다.
 drivenDistance 도 출력에 사용하기위해 외부로 값이 제공된다면 result 관련 클래스가 필요없을수도 있을것 같은데  고민해보시면 좋을것 같습니다.

2023-11-10 09:59 UTC, csh0034 commented on src/test/java/camp/nextstep/edu/racingcar/domain/CarTest.java
> +    void carName() {
예외 발생하는 경계값인 5 를 기준으로 성공하는 테스트와 실패하는 
테스트를 분리해보면 좋을것 같습니다.

추가로 `@ParameterizedTest` 의 적절한 input 을 고려한다면 중복되는 부분 제거가 가능할것 같아요!

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/Winners.java
> +public class Winners {
static 만 존재하여 인스턴스화를 하지 않는 클래스를 
도메인 또는 객체라고 볼수있을까요? 🤔

우승자의 경우엔 Cars 와 Car 에게 메세지를 보내서 처리해보면 좋을것 같습니다.

2023-11-10 09:59 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/result/DriveResult.java
>  public class DriveResult {
DriveResult 는 Car 와 전략을 제외한다면 인자가 동일한데 중복이지 않을까요? 🤔

2023-11-10 10:07 UTC, csh0034 commented
질문에 대해 답변드립니다.

1. 현재구조에선 잘 해주셨다고 생각합니다.
코멘트에 드린내용 고민해보시면서 반영한다면 구조는 변경될것 같아요.

2. 반복문과 조건문이 만나면 indet 가 2가 되기 때문에 Stream 을 사용하지 않고 힘들것 같아요.
Map<거리, List<이름>> 을 사용하여 분류후에 해본다면 할순있겠지만 코드가 복잡해서
꼭 Stream 을 사용하지 않아야한다면 말씀해주신 방법이 좋을것 같습니다.

2023-11-16 07:33 UTC, deepredk commented on src/main/java/camp/nextstep/edu/racingcar/domain/result/DriveResult.java
>  public class DriveResult {
@csh0034 
중복이 아니라고 생각합니다! DriveResult는 이미 지나간 과거의 Car의 상태를 담아내는 역할을 하고있기 때문입니다

2023-11-16 07:35 UTC, deepredk commented on src/main/java/camp/nextstep/edu/racingcar/domain/Winners.java
> +public class Winners {
Cars가 반환한 RoundResult가 Cars를 또 호출하게 하는 것은 어색한 것 같아
Winners 클래스를 삭제하고 RoundResult에 getWinners()를 추가해보았습니다!

2023-11-17 02:31 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/result/DriveResult.java
>  public class DriveResult {
그런관점에서 본다면 중복으로 보지 않아도 될 것 같아요!

2023-11-17 02:37 UTC, csh0034 approved these changes
리뷰 잘 반영해주셨네요 💯 
이만 머지하도록 할게요!
마지막 단계까지 화이팅입니다 😄

2023-11-17 02:37 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/RacingGame.java
> +    public static final String CAR_NAME_DELIMITER = ",";
구분자에 대한 값은 ui 영역이기때문에 inputView 에서 처리하면 더 좋을것 같습니다

2023-11-17 02:37 UTC, csh0034 commented on src/test/java/camp/nextstep/edu/racingcar/domain/CarTest.java
> +        new Car(input, () -> true);
결과는 동일하지만 `assertThatNoException` 를 적용해볼수도 있을것 같습니다.

2023-11-17 02:37 UTC, csh0034 commented on src/main/java/camp/nextstep/edu/racingcar/domain/result/DriveResult.java
> +    public final String name;
가시성은 최대한 낮춰주세요!

2023-11-17 02:38 UTC, merged