피드백 내용 반영해서 리팩토링 진행했습니다.
next-step/java-racingcar pull request #5093
Opened 2023-11-10 08:47 UTC by PowerBBear

피드백 내용 반영해서 리팩토링 진행했습니다.

Cars를 만들시에 RacingGame과 차이가 없어보여서 RacingGame을 수정해서 사용했습니다.

테스트도  Model 별로 진행하였습니다.

2023-11-10 15:47 UTC, ohtaeg requested changes
마지막 단계도 잘해주셨습니다 :) 👍 
다음 미션을 진행하기전에 단위 테스트가 조금 부족하여 Request changes 하였습니다!
테스트 작성후 재요청 주시면 미션이 종료될 것 같아요 ㅎㅎ
마지막까지 화이팅입니다 🔥

2023-11-10 15:47 UTC, ohtaeg commented on README.md
> +  - Cars를 만들시에 RacingGame과 툴이 너무 비슷하여 만들지 않았습니다.
👍 👍

2023-11-10 15:47 UTC, ohtaeg commented on src/main/java/racingcar4/model/Car.java
>          }
carTurn()에 대한 단위 테스트를 꼭 작성해주세요! 😄

2023-11-10 15:47 UTC, ohtaeg commented on src/main/java/racingcar4/model/Car.java
> +    public boolean victoryCar(int maxPosition) {
해당 메서드도 단위 테스트 부탁드립니다 :)

2023-11-11 05:02 UTC, PowerBBear commented on src/main/java/racingcar4/model/Car.java
>          }
carTurn에 임의의 숫자를 넣어줄수가 없는데 어떻게 테스트를 진행하면 좋을까요?

2023-11-11 16:47 UTC, ohtaeg commented on src/main/java/racingcar4/model/Car.java
>          }
carTurn에 임의의 숫자를 받도록 변경해주시는 방향도 있지만

그렇지 않은경우 Car 객체 생성시 생성자에서 랜덤 번호를 만들어주는 이동 정책 객체를 받아

carTurn()에서 이동 정책을 통해 이동할지 말지 판단하도록 하면 어떨까요 :) ?

2023-11-12 13:40 UTC, ohtaeg approved these changes
마지막 미션까지 피드백 반영을 잘해주셨습니다 👍 
이로써 자동차 경주 미션이 끝났네요 🎉
남은 미션들도 화이팅하시길 바랄게요!!
고생 많으셨습니다 😄

2023-11-12 13:40 UTC, ohtaeg commented on src/main/java/racingcar4/model/Car.java
> +    public void carTurn(int number) {
외부에서 받도록 해주셨군요 👍

2023-11-12 13:40 UTC, ohtaeg commented on src/test/java/racingcar/RacingCar4CarTest.java
> +        Car car = new Car("shy");
👍 👍

2023-11-12 13:40 UTC, merged