🚀 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5111
Opened 2023-11-12 01:05 UTC by gkssk4163

3단계 피드백 및 4단계 기능 구현하여 PR 올립니다~!😁

2023-11-12 06:36 UTC, mskangg requested changes
4단계도 잘 구현해주셨어요! 👏 
이전 단계에서 피드백 드렸던 부분까지 잘 적용해주셨습니다!
다만, 전체적으로 getter로 클래스의 상태를 꺼내서 활용하는 방식으로 구현하셨더라구요..!
이 부분을 객체간의 대화, 즉 메세지를 보내서 원하는 결과를 얻는 방식으로 구현해보시는걸 추천드립니다! 🙂

2023-11-12 06:36 UTC, mskangg commented on src/test/java/step3/domain/RacingGameTest.java
> +    }
💯

2023-11-12 06:36 UTC, mskangg commented on src/test/java/step3/domain/RacingGameTest.java
> +    void runRoundWhenCarMovingTest() {
👏

2023-11-12 06:36 UTC, mskangg commented on src/main/java/step3/README.md
> +  - [X] 자동자 이름 목록을 입력 받는다.
체크리스트 👏

2023-11-12 06:36 UTC, mskangg commented on src/main/java/step3/domain/RacingCar.java
> +    private String name;
`규칙 3: 모든 원시값과 문자열을 포장한다.`

자동차이름을 포장해보시는건 어떨까요? 🤔

2023-11-12 06:36 UTC, mskangg commented on src/main/java/step3/domain/Winners.java
> +        if (racingCar.getDistance() != maxDistance) return;
값을 꺼내기보단 메세지를 보내보아요

2023-11-12 06:36 UTC, mskangg commented on src/main/java/step3/domain/Winners.java
> +            maxDistance = getMax(maxDistance, racingCar.getDistance());
이 부분도 getter를 사용하지 말고 구현해보시는건 어떨까요!?

2023-11-12 08:14 UTC, gkssk4163 commented
피드백 수정하였습니다~!

`규칙 3: 모든 원시값과 문자열을 포장한다.` 라는 규칙은 아직 어색하네요 😂

`CarName` 이라는 객체를 만들어서 이름에 대한 기능만 분리하는 것을 좋았으나, `RacingCar.name` 으로 접근하던 것이 `RacingCar.CarName.value` 로 depth가 늘어나다보니 접근하기가 불편하다고 느껴지는 부분이 있었습니다

2023-11-13 08:55 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요!
getter를 사용하지 않고 메세지를 보내는 방식이 어색할 순 있지만, 캡슐화를 위해선 필요하다고 생각해요 :)
잘 구현해주셨습니다!

질문 사항중 `RacingCar.CarName.value` 처럼 뎁스가 더 들어간 경우가 어색하다고 하셨는데, 
도움이 될만한 글링크 남겨드릴게용
https://prohannah.tistory.com/204

그럼 마지막 미션도 화이팅~! 🔥

2023-11-13 08:55 UTC, merged