5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5126
Opened 2023-11-13 05:55 UTC by hyoin11

안녕하세요 동휘님~!

4단계에서 사용하였던 Racing 없애고 RacingController를 생성해 횟수만큼 Cars를 이동할 수 있게 수정해보았습니다.
도메인 영역에서는 view 영역을 의존하지 않게 컨트롤러를 통하도록 수정해보았습니다.

그럼 마지막 미션도 리뷰 잘 부탁드립니다!

2023-11-13 12:51 UTC, dhmin5693 approved these changes
효인님 안녕하세요.

날이 갈수록 코드가 깔끔해져 가는게 눈에 띄네요.
5단계 요구사항은 MVC 기반의 리팩토링입니다.
다시 한번 고민해보시고 요청주세요 💪

2023-11-13 12:51 UTC, dhmin5693 commented on src/main/java/racing/view/ResultView.java
>          System.out.println(BLANK);
이번 미션 목표는 영역 분리입니다.
표준 입력 및 출력(sout)은 domain 영역에선 제거하시고 view 영역인 `ResultView`에서만 수행해주세요.
`ResultView`는 controller 영역에서만 호출할 수 있습니다.

2023-11-13 12:52 UTC, dhmin5693 requested changes
효인님 안녕하세요.

날이 갈수록 코드가 깔끔해져 가는게 눈에 띄네요.
5단계 요구사항은 MVC 기반의 리팩토링입니다.
도메인 영역에 System.out.println 을 전부 걷어내주셔야 합니다.

다시 한번 고민해보시고 요청주세요 💪

2023-11-14 07:44 UTC, hyoin11 commented
안녕하세요 동휘님!

도메인 영역에 throw 메시지를 뿌려는 부분을 InputView로 옮겨주었습니다!

혹시 추가적으로 아쉬운 부분이 있다면 말씀주시면 감사하겠습니다~!

2023-11-15 14:07 UTC, hyoin11 commented
동휘님 안녕하세요~!

피드백 바탕으로 자동차 이름과 위치 클래스를 분리하였습니다.
ResultView에서도 우승자 이름을 찾아내기 위해 로직이 포함된것 같아 우승자 클래스를 분리해보았습니다.

2023-11-15 15:16 UTC, dhmin5693 approved these changes
효인님, 정말 고생 많으셨습니다.
처음 시작하셨을때랑 정말 많이 달라졌음이 느껴지는데 효인님은 어떻게 생각하시나요?
그 동안 제가 드린 의견이 효인님의 성장에 도움이 되었으면 좋겠네요.

제가 너무 많은 내용을 요구했나 싶기도 하지만 그 요구 한 번에 긍정적인 변화가 너무 눈에 띄어서 그랬으니 너른 양해 부탁드려요. 😁

남은 과정도 힘내시기 바랍니다.

2023-11-15 15:16 UTC, dhmin5693 commented on src/main/java/racing/domain/CarName.java
> +    }
여기를 통해 생성되는 인스턴스는 비지니스 상 오류가 발생할 수 있겠네요.

2023-11-15 15:16 UTC, dhmin5693 commented on src/main/java/racing/domain/CarName.java
> +    public static CarName checkCarName(String carName) {
보통 매개변수가 1개인 팩토리 메소드는 from을, 2개 이상이면 of라는 이름을 사용하는 편입니다.

이펙티브 자바에 나오는 내용이에요.

2023-11-15 15:16 UTC, dhmin5693 commented on src/main/java/racing/domain/CarPosition.java
> +public class CarPosition {
name과 position의 분리 👍 
코드가 분리되면서 무엇을 느끼셨을지도 궁금하네요.

2023-11-15 15:16 UTC, dhmin5693 commented on src/main/java/racing/domain/Winners.java
> +    List<String> winners;
```suggestion
    private final List<String> winners;
```

불변과 캡슐성을 보장해주면 어떨까요?

2023-11-15 15:16 UTC, merged