Step2
next-step/java-racingcar pull request #5142
Opened 2023-11-14 07:44 UTC by jaegil-jeong

2023-11-14 14:05 UTC, serverwizard requested changes
문자열 덧셈 계산기 잘 구현해 주셨네요. 👍

간단한 코멘트 조금 남겼습니다.
확인 부탁드릴게요 🙂

2023-11-14 14:05 UTC, serverwizard commented on src/main/java/step2/StringAddCalculator.java
> +        Matcher matcher = Pattern.compile(CUSTOM_DELIMITER_PATTERN).matcher(text);
Pattern객체는 생성 비용이 아주 비싼 객체에 해당하는데요. (compile할 때마다 객체 생성됨)
<img width="520" alt="image" src="https://github.com/next-step/java-racingcar/assets/23587638/31cfca74-9dea-45d9-aa7e-e3e1d16e6524">

따라서, 매번 메소드가 실행될 때마다 똑같은 기능의 객체를 생성하는 것보다 이를 상수(static final)로 선언(= 캐싱)하고 재사용하는 건 어떨까요?

2023-11-14 14:05 UTC, serverwizard commented on src/test/java/step2/StringAddCalculatorTest.java
> +    @Test
@ DisplayName을 통해 테스트 의도를 명확히 나타내 주시면, 문서화로서의 역할도 할 수 있을 것 같아요~

2023-11-14 14:05 UTC, serverwizard commented on src/test/java/step2/StringAddCalculatorTest.java
> +    public void splitAndSum_null_또는_빈문자() {
@NullAndEmptySource 에 대해서도 학습해보시면 좋을 것 같아요~

2023-11-15 02:15 UTC, jaegil-jeong commented
안녕하세요
제가 사정으로 과정을 뒤늦게 시작하여 진도를 맞추기 위해
클래스 분리를 제외하고 리팩토링 하였습니다.

2023-11-15 13:24 UTC, serverwizard approved these changes
2단계 미션 잘 반영해 주셨네요. 👍
이만 머지하도록 하겠습니다.

그럼, 3단계 미션에서 뵙겠습니다. 🙂

2023-11-15 13:24 UTC, serverwizard commented on src/main/java/step2/StringAddCalculator.java
> +    private static final Pattern pattern = Pattern.compile(CUSTOM_DELIMITER_PATTERN);
상수로 선언(= 캐싱)하여 재사용 👍 👍

2023-11-15 13:24 UTC, serverwizard commented on src/main/java/step2/StringAddCalculator.java
> +            String[] tokens = matcher.group(2).split(delimiter);
의미 있는 이름의 상수로 대체해봐도 좋을 것 같네요~

2023-11-15 13:24 UTC, serverwizard commented on src/test/java/step1/SetCollectionTest.java
> +        assertThat(actual).isEqualTo(3);
중요한 건 아니지만, 아래와 같이 검증을 해볼 수도 있을 것 같아요 :) 
```
assertThat(numbers).hasSize(3);
```

2023-11-15 13:24 UTC, merged