🚀 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5149
Opened 2023-11-14 14:46 UTC by h3yon

안녕하세요.
코드리뷰 및 승인 요청드립니다. 감사합니다!

2023-11-15 17:14 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/application/Race4Service.java
> +    }
Service라는 네이밍 의도 및 내부에서 가지는 raceCars라는 프로퍼티를 보았을 때 핵심 비즈니스 로직을 다루려는 의도로 만드신 것 같은데요.

서비스 내부에 출력 부분이 혼재되어 있습니다. 이번 단계에 제거할 필요는 없으나 다음 단계에는 비즈니스 로직과 입, 출력이 섞이지 않도록 개선해보세요.

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/application/Race4Service.java
> +    }
구현 의도에 따라 다르겠지만 게임 시도는 외부에서 클라이언트에 의해 컨트롤될 것 같은데요. 몇번 수행할지를 프로퍼티로 저장할 필요가 있을까요? 지금은 이 받은 값에 따라 게임 횟수가 고정되면서 게임 횟수 변경 등의 요구사항을 수용할 수 없는 상태로 보여요.

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/application/Race4Service.java
> +        race4Cars.forEach(car -> car.moveForwardByCondition(randomNumber));
5번 게임을 실행한 뒤 우승자가 잘 나오는지 버그 등은 없는지 단위 테스트가 필요할 수 있을 것 같습니다. 지금은 setter를 열어서 테스트를 하고 계신 것 같은데요, 랜덤이 포함되어 있는 이 Race4Service의 playGame 같은 메서드는 어떻게 테스트할 수 있을까요?

이를 위해 설계를 바꾸라는 것은 아닙니다. 다만 학습의 관점에서 추상화를 통해 책임을 분리하고 Race4Service를 테스트해볼수도 있을 것 같아요.

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/domain/Race4Car.java
> +    private int position;
Car가 가지는 프로퍼티나 책임을 적절히 잘 설계해주셨네요. 👍

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/domain/Race4Car.java
> +public class Race4Car {
Race4Car에는 여러 메서드가 있는데 테스트가 작성된 것은 보이지 않네요 😭 단위 테스트를 추가해보는건 어떨까요?

2023-11-15 17:14 UTC, kyucumber commented on src/main/java/racing4/domain/Race4Car.java
> +    public void setPosition(int position) {
setPosition은 테스트 메서드에서만 호출됩니다.

테스트를 위한 비즈니스 로직을 정의한 것 같은데요. 이 메서드가 다른데서 호출된다면 임의로 Car의 포지션을 조작할 수 있겠네요. 이 메서드가 존재하는게 맞을 지 고민이 필요해보여요.

2023-11-19 07:38 UTC, h3yon commented
코드리뷰 반영했습니다.
리뷰 및 승인 요청 드립니다~!
- [feat: 코드리뷰 반영 - 불필요한 setPosition 메서드 제거](https://github.com/next-step/java-racingcar/pull/5149/commits/5a2cd8d3a70da991d3cb6d30587f179c8f5b59f8)
- [feat: 코드리뷰 반영 - Race4Car 테스트코드 보충](https://github.com/next-step/java-racingcar/pull/5149/commits/ef8a1de935de5b896e13520545541ee73402d757)
- [feat: 코드리뷰 반영 - Race4Service 프로퍼티로 저장하지 않도록 변경](https://github.com/next-step/java-racingcar/pull/5149/commits/125101503cfb07e2215868ef2fc17adfefe7b01b)
- [feat: 코드리뷰 반영 - Race4Service 출력 부분 분리](https://github.com/next-step/java-racingcar/pull/5149/commits/7834b8027990a57644f74c64dbea24fc57a3eb5f)

2023-11-19 15:23 UTC, kyucumber approved these changes
수고 많으셨습니다.

다음 단계 진행을 위해 머지할게요. 남겨둔 코멘트는 한번 확인 부탁드립니다.

2023-11-19 15:23 UTC, kyucumber commented on src/test/java/racing4/application/Race4ServiceTest.java
> +class Race4ServiceTest {
> 5번 게임을 실행한 뒤 우승자가 잘 나오는지 버그 등은 없는지 단위 테스트가 필요할 수 있을 것 같습니다. 지금은 setter를 열어서 테스트를 하고 계신 것 같은데요, 랜덤이 포함되어 있는 이 Race4Service의 playGame 같은 메서드는 어떻게 테스트할 수 있을까요?

이 부분은 별도로 코멘트 반영하지 않으셔서 추가 리뷰 없이 넘어가도록 하겠습니다~!

2023-11-19 15:23 UTC, kyucumber commented on src/test/java/racing4/view/ResultViewTest.java
> +class ResultViewTest {
View는 비즈니스 로직의 범위가 아니므로 이번 과정에서는 테스트를 하지 않으셔도 괜찮을 것 같아요.

2023-11-19 15:23 UTC, merged