Step4
next-step/java-racingcar pull request #5154
Opened 2023-11-15 13:43 UTC by frank-jeongwooshin

안녕하세요 !

앞의 피드백을 반영하려고 노력하여 코드 작성하였는데, 리뷰 부탁드립니다 !

2023-11-15 16:55 UTC, nooose requested changes
전단계와 비교했을 때 코드가 많이 깔끔해졌네요
피드백 남겼으니 읽어보시고 재요청 부탁드립니다!

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Car.java
>      }
입력 부분에서 검증을 하더라도
Car 객체가 정상 생성된다는 보장은 없습니다.
```java
new Car("안녕하세요자동차");
```
시간이 지나고 요구사항이 추가되면서 
실수로 이런 코드가 동작해 5글자가 초과된 이름이 들어온다면 어떻게 될까요?

이런 문제로 생성자 안에 유효성 검증 로직을 정의하는 것이 좋습니다.
```java
public Car(String name) {
        validate(name);
        this.name = name;
}
```

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Car.java
>      }
이 부분과 관련하여 자동차 객체 생성 시 검증이 잘 되는지 
테스트 코드도 작성되면 좋겠네요

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Car.java
> +            moveCount += 1;
👍

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Racing.java
> +        for(String name : carNames.split(",")){
`,` 구분자로 파싱하는 부분은 입력관련 클래스에서 처리할 수 있을 것 같습니다.
 데이터를 받을 때 `List<String>` 이름 리스트로만 받아서 처리할 수 있게끔요

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Racing.java
>          System.out.println("실행 결과");
Racing에서 직접 출력 관련 메서드를 사용하고 있네요
doRacing으로 옮겨도 되지 않을까요?

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Racing.java
> +    private static List<String> getWinners(List<Car> cars) {
getWinners에서 이름 리스트를 반환하는 대신 우승자 Car 리스트를 반환해도 될 것 같아요!

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Racing.java
> +        for(Car car : cars){
```suggestion
        for (Car car : cars) {
```
이렇게 띄어쓰기를 사용하는 것이 좋습니다.
보편적인 컨벤션입니다 😄

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/ResultView.java
>          System.out.println(resultMessage);
```java
        String winners = String.join(", ", cars);
        System.out.println(String.format("우승자는 %s 입니다.", winners));
```
이러면 훨씬 간결할 것 같아요 😄

2023-11-15 16:55 UTC, nooose commented on src/test/java/racing/RacingTest.java
> +        };
```suggestion
        Strategy forwardStrategy = () -> true;
```

인터페이스에 있는 메서드의 반환 타입과 파라미터를 봤을 때
`boolean isMovable();` 입력값은 없고 반환 타입은 boolean이라는 것을 확인할 수 있습니다.
이렇게 인터페이스에서 구현해야 할 메서드가 하나이고 타입, 파라미터가 뭐가 들어가야 하는지 알 수 있기 때문에 추론이 가능합니다.
추론이 가능한 부분은 위 람다식을 사용하여 익명 클래스를 대체할 수 있습니다.

2023-11-15 16:55 UTC, nooose commented on src/test/java/racing/RacingTest.java
>  }
이런 부분은 해피 케이스이기 때문에 테스트가 통과되었다고 보기 힘듭니다.
`,` 가 포함된 이름들을 넣었을 때 어떤 예외가 발생했다를 검증하는 것이 올바를 것 같습니다.

2023-11-15 16:55 UTC, nooose commented on src/main/java/racing/Car.java
>      private int moveCount = 1;
1이라는 부분도 DEFAULT_COUNT 같은 상수로 선언할 수 있을 것 같아요
상수명은 참고입니다

2023-11-16 14:25 UTC, frank-jeongwooshin commented on src/main/java/racing/Racing.java
> +        for(String name : carNames.split(",")){
위의 말씀은 scanner 시에 useDelimiter() 메소드를 사용해 처리하시는 걸 말씀하시는 걸까요??
차라리 저는 input에서 split을 진행한 후 carNames에 string[] 으로 변형하는 방법을 사용하였는데 혹시 위의 방법과 제가 한 방법 둘다 최적화되지 않고 다른 좋은 방법이 있다고 생각하시면 알려주세요!

관련해서 학습해서 도전하겠습니다.

2023-11-16 14:28 UTC, frank-jeongwooshin commented on src/main/java/racing/Racing.java
> +    private static List<String> getWinners(List<Car> cars) {
처음에는 Car로 할까 하다가 showResult함수에서 car.getName()을 호출해야하기 때문에 이름 리스트를 반환하는 방향으로 구현하였는데, Car로 반환하게 되면 어떤 점에서 이점이 있을 수 있을까요?

2023-11-16 14:44 UTC, frank-jeongwooshin commented
안녕하세요 ! 리뷰 요청이 조금 늦었습니다. 
관련해서 코멘트 밑에 댓글 형식으로 달아놓은 의문 사항이나 제 의견을 적어 두었는데 확인 부탁드립니다.

감사합니다!

2023-11-16 15:04 UTC, nooose commented on src/main/java/racing/Racing.java
> +        for(String name : carNames.split(",")){
`useDelimiter()` 사용 없이 InputView에서 split 후 전달만 하면 될 것 같습니다. 👍
사용자 경험을 위해서 공백도 지워주면 좋겠죠? (ex. `" abc,    def"` -> `["abc", "def"]`)
trim을 참고해 보세요!

2023-11-16 15:09 UTC, nooose commented on src/main/java/racing/Racing.java
> +    private static List<String> getWinners(List<Car> cars) {
맞습니다 현재는 이름밖에 없습니다.
하지만 시간이 지나 다른 요구사항이 생겨서 우승자의 메타 데이터도 같이 포함시켜 출력해 달라고 했을 때 
타입부터 시작해서 많은 변화가 일어날 것 같아요

Car라는 타입으로 정해졌다면 출력할 데이터가 추가되어도 입력타입과 반환 타입은 변경되지 않고
객체에 필드 추가만 하면 해결됩니다.

또 Car 자체를 사용한 우승자 정보를 가지고 통계를 낼 수도 있어 범용적으로 사용할 수 있게 됩니다.

2023-11-16 15:25 UTC, nooose approved these changes
이제 마지막 단계네요 😄
코멘트 읽어보시고 다음 단계에서 반영 부탁드립니다.
(답변도 남겨놨어요)

2023-11-16 15:25 UTC, nooose commented on src/main/java/racing/Validate.java
> +public class Validate {
유틸클래스로 보이는데요
유틸클래스로 만드신 이유가 있을까요?

2023-11-16 15:25 UTC, nooose commented on src/main/java/racing/Racing.java
>          }
자동차 생성과 자동차 이동을 
매번 리스트를 반복돌리면서 처리하고 있네요

이를 한번에 처리할 수 있는 Cars라는 일급컬렉션을 만들어 보면 어떨까요?
Cars 내부에서 컬렉션을 처리하면 좋을 것 같아요

### 예시
```java
Cars cars = new Cars(carNames);
cars.move(strategy);
```

2023-11-16 15:25 UTC, nooose commented on src/test/java/racing/RacingTest.java
> +    void 자동차_이름_확인(String name){ validName(name); }
테스트 코드는 검증메서드로 끝나는 것이 맞습니다.

2023-11-16 15:25 UTC, nooose commented on src/test/java/racing/RacingTest.java
>          }
이 부분도 검증을 하는 부분이 빠져있는 것 같아요
```
assertDoesNotThrow(() -> new Car("123"));
```

이런식으로 검증을 해볼 수 있겠네요

2023-11-16 15:25 UTC, merged