5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5159
Opened 2023-11-17 15:41 UTC by kmj990929

안녕하세요 리뷰어님!
4단계에서 피드백 주신 내용 및 기타 자잘한 내용 수정 (final 변수로 변경, code format 맞추기 등) 을 포함하여 PR드립니다.
4단계에서 피드백주신 내용 중 'moveOrStop' method 인자 관련 피드백에 의견이 있어 [코멘트](https://github.com/next-step/java-racingcar/pull/5119#discussion_r1394981437)를 추가해두었는데요, 함께 확인을 부탁드릴 수 있을까요?!
항상 친절한 피드백 감사합니다.

2023-11-18 12:14 UTC, testrace requested changes
안녕하세요 민주님
피드백 반영 잘해주셨네요 👍 
질문에 대한 답변과 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-11-18 12:14 UTC, testrace commented on src/main/java/racingcar/model/RacingCar.java
> +    private final MoveStrategy moveStrategy;
[질문](https://github.com/next-step/java-racingcar/pull/5119#discussion_r1397293675)에 답변입니다
경주 도중 전략이 변경되어야 한다면 이동 전략을 관리하는 책임이 추가 되는데요
자동차가 이동하는 책임만 수행하기 위해 이동 전략을 분리했는데 전략을 관리하는 책임이 추가된 것 같아요
전략 패턴을 적용하면서 자동차는 `MoveStrategy` 인터페이스만 의존할 수 있게 되었는데 
생성자에서는 구현체에 의존하고 있으니 전략 패턴의 이점이 드러나지 않는 것 같아요

현재 요구 사항에서는 자동차가 전략을 필드로 가지고 있어서 문제가 되진 않으니 수정하지 않고 진행하셔도 괜찮을 것 같아요

2023-11-18 12:14 UTC, testrace commented on src/main/java/racingcar/model/RacingCar.java
> +        this.position = new Position(this.position.step());
position 객체에게 메시지를 보내도 좋을 것 같아요
```suggestion
        this.position = this.position.increase();
```

2023-11-18 12:14 UTC, testrace commented on src/test/java/racingcar/model/RacingCarTest.java
> +        RacingCar car1 = new RacingCar(new VarMoveStrategy(3), "abc");
자동차가 이동 전략에 의해 움직이니 인수와 관련된 DisplayName을 변경하면 좋을 것 같아요
숫자에 대해 알고 있어야 하는 VarMoveStrategy 대신 AlwaysMoveStrategy 를 활용할 수 있겠네요

2023-12-04 12:35 UTC, kmj990929 commented on src/main/java/racingcar/model/RacingCar.java
> +    private final MoveStrategy moveStrategy;
이해했습니다 자세한 설명 감사합니다!!
말씀해주신 방식으로 수정해보았습니다

2023-12-05 03:33 UTC, testrace approved these changes
안녕하세요 민주님
피드백 반영 잘해주셨네요 👍 고생 많으셨습니다!
자동차 미션은 여기서 마무리하겠습니다
남은 미션들도 화이팅입니다 🔥

2023-12-05 03:40 UTC, merged