안녕하세요 woodo님 5단계 미션 완료했습니다.
next-step/java-racingcar pull request #5166
Opened 2023-11-19 06:46 UTC by jhd7130

안녕하세요 woodo님!

5단계 코드 리뷰 요청드립니다.

저번에 피드백 주신것들 반영해 보려고 노력했습니다.
가장 어려웠던 부분은 view를 도메인까지 침투시키지 않고 각 객체들의 상태를 출력하는 방식이었습니다.

도메인 객체의 상태를 출력해야하는데 상태를 조회하기 보다는 필요한 요소를 String으로 반환 받을 수 있도록 구현해봤습니다.
경주의 진행 사항은 히스토리를 남기고 해당 히스토리를 출력하는 방식을 사용했습니다.

감사합니다.

2023-11-20 13:54 UTC, wooobo requested changes
안녕하세요 희두님!

5단계 잘진행해주셨습니다.
몇가지코멘트남겨두었는데 확인부탁드려요~!

2023-11-20 13:54 UTC, wooobo commented on src/main/java/step5/domain/Winners.java
> +public class Winners {
Cars랑 똑같은 상태를 가지는데 Winners를 만들어야하나요?

2023-11-20 13:54 UTC, wooobo commented on src/test/java/step5/domain/Step5CarTest.java
> +        Assertions.assertThat(car.isDistance(2)).isTrue();
```suggestion
        Assertions.assertThat(car.sameDistance(2)).isTrue();
```

같냐라고 물어보는게 개인적으로는 자연스럽네요🤔

2023-11-20 13:54 UTC, wooobo commented on src/test/java/step5/domain/Step5CarsTest.java
> +        String names = "포비, 그르릉, 아톰";
참고용으로 공유합니다~
[링크](https://jojoldu.tistory.com)

2023-11-20 13:54 UTC, wooobo commented on src/test/java/step5/domain/Strep5NameTest.java
> +    @DisplayName("이름 길이 5자 초과 금지")
5자라는 조건이변경되면 테스트 설명이 불일치되는 이슈가있겠네요 ㅜ

2023-11-20 13:54 UTC, wooobo commented on src/main/java/step5/view/InPutView.java
> +
[static method만을 가지는 utility class는 private 생성자를 가지도록 구현한다.](https://www.slipp.net/questions/360)

참고해주세요~

2023-11-20 13:54 UTC, wooobo commented on src/main/java/step5/domain/car/Distance.java
> +        this.distance += distance;
불변객체로 하면 어떨까요?

2023-11-20 13:58 UTC, jhd7130 commented on STEP5README.md
> +# 🚀 5단계 - 자동차 경주(리팩토링)
하하 죄송합니다 ㅠㅠ ㅋㅋㅋ 제가 잘못 적었네요

2023-11-20 14:01 UTC, jhd7130 commented on src/main/java/step5/domain/Winners.java
> +public class Winners {
코드 상의 가독성을 올리기위해서 Winners라는 새로운 이름으로 만들어봤는데 이럴때는 변수명을 winners라고 정의해주는게 좋을까요?

2023-11-22 22:38 UTC, wooobo requested changes
안녕하세요 희두님!

피드백에 대해 고민해주셔서 감사합니다 🙏 
코멘트 남겨 놓았는데 확인 후 재요청 부탁드려요~!

2023-11-22 22:38 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +public class Cars {
> 코드 상의 가독성을 올리기위해서 Winners라는 새로운 이름으로 만들어봤는데 이럴때는 변수명을 winners라고 정의해주는게 좋을까요?

`class 아빠 {}` 
아빠라는 클래스가 있다고 생각해보겠습니다.
```
아빠 철수아빠 = new 아빠("철수");
아빠 영희아빠 = new 아빠("영희");
```

역할은 하나이지만, 객체의 이름은 불려지는곳에서 다르게 변할 수 있습니다.
제가 집중하는것은 역할과 책임입니다. 결국 같은 역할과 책임이라면 같은 객체로 접근해본 관점입니다 😄

2023-11-22 22:38 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +    public Cars voteWinner() {
`Winners`라는 객체가 있는데 `Cars`에서 winner라는 키워드가 다소 많이 보이는게 어색하네요.

`Winners`를 만들었다면 저는 `Winners`에게 `winner`관련 키워드를 모아 둘것 같아요

2023-11-22 22:38 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +        stringBuilder.append("\n");
UI(ResultView) 책임일것 같네요 🤔

2023-11-22 22:38 UTC, wooobo commented on src/main/java/step5/domain/car/Distance.java
> +    public String statusToString() {
```suggestion
    }
    
    public String statusToString() {
```

공백또한 코드켄벤션이라고 생각합니다.

2023-11-22 22:38 UTC, wooobo commented on src/main/java/step5/domain/car/Distance.java
> +    }
```suggestion
    public boolean fartherThan(Distance distance) {
        return this.distance > distance.distance;
    }

    public Distance deepCopy() {
        return Distance.of(this.distance);
    }
```

메소드 배치또한 중요합니다. 
`equals`, `hashCode` 메소드 보다는 위에 두는게 좋다고 생각합니다.

2023-11-23 00:57 UTC, jhd7130 commented on src/main/java/step5/domain/car/Cars.java
> +        stringBuilder.append("\n");
OutPutView와 Cars의 경우 다른 객체입니다. 캡슐화를 지키려고 하다보니 내부 상태의 외부노출 없이 내부 상태를 결과와 같은 형태로 뽑아내기 위해서 자신의 상태를 String 형태로 반환할 수 있는 메서드를 만들었습니다. getter의 성격을 가지는 메서드 없이 해보고 싶은데 머리 속에 잘 떠오르지를 않네요.. 

어떤 키워드를 찾아보면 객체의 상태를 외부로 노출 시키지 않고 내부 상태를 원하는 형태로 뽑아낼 수 있을까요?

2023-11-23 01:13 UTC, jhd7130 commented on src/main/java/step5/domain/car/Cars.java
> +    public Cars voteWinner() {
Cars랑 똑같은 상태를 가지는데 Winners를 만들어야하나요? 라는 피드백을 4단계 구현에서 받았어요. 이전에 상태는 같지만 다른 역할과 책임을 가지고 있다고 생각해서 Winners를 만들었어요. 
피드백을 받은 뒤에는 Winner를 뽑기 위해서는 경주에 참가한 Cars 객체의 상태가 필요하니 Cars 객체가 winner 관련 키워드들이 있어도 괜찮다고 판단했고 리펙토링 했어요. 

피드백에 대한 제 생각은 Cars와 같은 상태를 가진 Winners를 만드는 것보다는 Cars를 가진 Winners를 객체를 사용하고 winner 키워드를 Winners에 모아두면 되겠다 생각이드네요. 
하지만 이렇게 할 경우 Cars 내부의 list를 활용해야해서 다시 Cars 내부에 뭔가 winner 키워드가 들어가야할 것 같다는 생각이 들어요... 이러면 Cars 내부에 들어있는 메서드는 최대한 winner 키워드를 빼고 '최대 거리의 차 뽑기', '같은 거리의 차 뽑기'등의 의미를 가진 메서드들로 뽑아내야하지 않을까 하네요.

그냥 생각 나열입니다! 혹시 보시고 피드백 주실 것 있으시면 주시고 아니면 답변 안주셔도 됩니다!!

2023-11-23 09:51 UTC, wooobo approved these changes
안녕하세요 희두님!

5단계까지 수고 많으셨습니다 ><
다소 혼란스러운 코멘트를 남겨 드린것 같아 죄송하네요 ㅎㅎ 😂 
다양한 관점의 공유정도로 봐주세요~

그럼 이만 `merge` 진행하겠습니다!
남은 미션도 화이팅입니다!

2023-11-23 09:51 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +public class Cars {
> 이러면 Cars 내부에 들어있는 메서드는 최대한 winner 키워드를 빼고 '최대 거리의 차 뽑기', '같은 거리의 차 뽑기'등의 의미를 가진 메서드들로 뽑아내야하지 않을까 하네요.

좋은 접근입니다 👍

2023-11-23 09:51 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +        stringBuilder.append("\n");
> getter의 성격을 가지는 메서드 없이 해보고 싶은데 머리 속에 잘 떠오르지를 않네요..

값을 꺼내오는것 없이 사실 할수는 없죠 😂 
저의 코멘트가 다소 불필요한 코멘트가 아니었나 생각이드는 코멘트같아요!! ㅎㅎ
오히려 혼란스럽게 만든것 같네요 ㅜㅜ

구현 하신것도 충분히 좋은 구현입니다! 😄 

사실 느낌적으론 별차이 없는것 같긴한데,
그래도 코멘트 남겨 놓았으니 제 관점도 한번 공유해봅니다.
지금 구조에서 최대한 녹여볼려고 했는데 구현하신게 더 나은것 같기도 하네요! 😄 


```
# OutPutView
public void printHistory(Racing racing) {
    List<String> result = racing.history(":","-");
    System.out.println(String.join("\n", result));
}

# Racing
public List<String> history(String s, String s1) {
    List<Cars> cars = racingHistory.history();

    return cars.stream()
            .flatMap(car -> car.status(s, s1).stream())
            .collect(Collectors.toList());
}


# RacingHistory
public List<Cars> history() {
    return Collections.unmodifiableList(this.history);
}

# Cars
public List<String> status(String s, String s1) {
    return cars.stream()
            .map(car -> car.status(s, s1))
            .collect(Collectors.toList());
}

# Car
public String status(String s, String s1) {
    return name + s + distance.statusToString(s1);
}
```

2023-11-23 09:51 UTC, wooobo commented on src/main/java/step5/domain/car/Cars.java
> +        stringBuilder.append("\n");
```
# RacingHistory
    @Override
    public String toString() {
        StringBuilder allHistory = new StringBuilder();
        for (Cars history : this.history) {
            allHistory.append(history.statusToString());
        }
        return allHistory.toString();
    }
```

`toString`은 기본 메소드로 다양한곳에서 사용할수있는 개념같아서.
`toString`보다는 별도의 메소드로 분리시켜도 좋지 않을까 생각되네요! 🤔

2023-11-23 09:51 UTC, wooobo commented on STEP5README.md
> +- 리팩토링 요구사항
[[Git] 커밋 메시지 규약 정리 (the AngularJS commit conventions)](https://velog.io/@outstandingboy/Git-%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80-%EA%B7%9C%EC%95%BD-%EC%A0%95%EB%A6%AC-the-AngularJS-commit-conventions)

참고해주시면 좋을것 같아서 공유합니다~

2023-11-23 09:51 UTC, merged

2023-11-26 15:08 UTC, jhd7130 commented
@wooobo 리뷰어님 마지막 리뷰까지 감사드립니다! 
예로 구현해주신 부분이 깔끔해보입니다 잘 공부해서 다음 단계에서 또 열심히 해보겠습니다!
경주 게임 리뷰해주셔서 감사합니다 정말!!
그럼 좋은 하루되시고 화이팅하십쇼!!