🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5172
Opened 2023-11-20 08:42 UTC by hvoiunq

step4 하고 로또를 진행하느라 이제야 PR을 올리게 되었습니다!

패키지 구조와 service에서 view 를 직접 호출하고 있는 부분을 제거하였고,
Car객체 내 Postion 원시값 분리해서 구현했습니다!

이번 step도 잘 부탁드립니다!!

2023-11-20 13:27 UTC, bingbingpa requested changes
이전 단계에서 이미 잘 리팩토링 해주셔서 크게 수정할 부분은 없는 것 같네요.
다만 한가지 테스트 불가능한 부분을 어떻게 테스트 가능하도록 
할지에 대해 생각해봤으면 해서 리뷰 하나 남겨 드렸는데요.
이 부분만 한번 더 고민해보시고 다시 한번 리뷰 요청 부탁드려요.

2023-11-20 13:27 UTC, bingbingpa commented on src/main/java/study/domain/Car.java
> +    private Position position;
`final` 을 붙여주면 좋을 것 같아요.

2023-11-20 13:27 UTC, bingbingpa commented on src/main/java/study/domain/Car.java
> +        return RandomNumberGenerator.getRandomNumber();
moving(int num) 은 테스트에서만 사용 되고 있고, 
getRandomNumber 는 테스트에서 오버라이드해서 사용하고 있는데요. 
이 부분은 랜덤이라는 부분이 Car 내부에 있기 때문에 발생하는 부분인 것 같아요. 
Car 외부에서 랜덤한 값을 생성하고 전진 가능 여부를 파라미터로 받도록 해보면 어떨까요? 
Car 에서는 특정 인터페이스 타입만 받아서 특정 메소드를 호출하는 형태로 하면 
불필요하게 테스트만을 위한 메소드와 protected 를 없앨 수 있지 않을까요? 
테스트에서눈 특정 인터페이스를 구현한 테스트 가능한 구현체를 사용 하도록 하는 형태로 변경해보는건 어떨까요?

2023-11-26 14:43 UTC, hvoiunq commented on src/main/java/study/domain/Car.java
> +        return RandomNumberGenerator.getRandomNumber();
아 이렇게 protected 추가한 이유가, 
수업에서 random 테스트가 힘든 경우를 protected 로 선언해 테스트 가능하도록 구조하도록 하는 부분이 있어서 였는데요..!
제가 과거에 설계 해둔대로 외부에서 num을 받도록 해놓은 상태라면 이런 protected 는 불필요하다고 봐도 되는거젰죠?!

2023-11-27 04:09 UTC, bingbingpa approved these changes
마지막 미션 리뷰 잘 반영해주셔서 머지하도록 하겠습니다. 
남은 미션들도 응원하도록 하겠습니다! 🔥
수고하셨습니다.

2023-11-27 04:09 UTC, merged