자동차 경주 2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #5277
Opened 2024-03-06 15:33 UTC by sinterhoo

안녕하세요. 2단계 문자열 덧셈 계산기 제출합니다!

1단계 테스트 코멘트 주신 부분도 반영할까 했는데, 아직 공부중이라 추후 과제에 Assertion 여러 기능 적용해보겠습니다 ㅎㅎ

메소드 분리는 크게
1. 메인 splitAndSum
2. 문자열에서 String[]로 분리하는 메소드
3. 입력으로 받은 문자열이 유효한 값인지 체크하는 메소드
4. 입력으로 받은 값을 더해주는 메소드

로 나눠봤습니다!

메소드들을 좀 더 분리할까 고민했는데, 너무 잘게 자르면 더 복잡해질 거 같아서 이대로 유지했습니다..!

궁금한 점은 하나의 객체에서 문자열을 자르고, 검증하고, 숫자로 바꿔서 계산을 하는 역할을 모두 수행하고 있는데, 메소드로 분리하는 게 아니라 아예 객체를 따로 분리하는 것도 괜찮을까요?

지금은 요구사항이 단순하니 상관없을 거 같은데, 여러 가지 조건이 추가되면 하나의 클래스에서 너무 많은 역할을 할 수도 있겠다는 생각이 들어서 궁금합니다!

2024-03-07 08:58 UTC, ksy90101 requested changes
고생하셨습니다~ 간단한 피드백을 남겼으니 확인 해주세요~
질문이 있다면 언제든 DM이나 댓글 달아주세요!

2024-03-07 08:58 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +    private static final Pattern CUSTOM_PATTERN = Pattern.compile("//(.)\n(.*)");
👍

2024-03-07 08:58 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +        }
1. validate같은 느낌인데, 어떤걸 validate를 분리해놔도 좋을거 같습니다.
2. 혹시라도 "  " 이런 값이 들어오면 어떻게 될지 고민해보면 좋을거 같습니다. 그러한 차이로 인해 isEmpty vs isBlank 메서드의 차이가 있는데 한번 알아보시면 좋을거 같아요~

2024-03-07 08:58 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +        return value.split("[,:]");
"[,:]"를 상수로 해두면 좋을거 같습니다.
상수를 통해 해당 부분의 의미를 나타내면 어떨까 생각이 들어요!

2024-03-07 08:58 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +        }
혹시 해당 부분을 Stream으로 해보면 어떨까요?
https://kapentaz.github.io/java/Java8-stream-sum-%EA%B5%AC%ED%95%98%EA%B8%B0/
위 글을 한번 참고해보셔도 좋을거 같습니다.

2024-03-07 08:58 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +                throw new IllegalArgumentException();
IllegalArgumentException보단, NumberFormatException이 더 어울리는게 아닐까요?
각 의미가 있는 예외를 쓰는게 더 좋다고 생각이 듭니다.

2024-03-07 08:58 UTC, ksy90101 commented on src/test/java/step2/StringAddCalculatorTest.java
> +    @Test
@ParameterizedTest
@NullAndEmptySource

이 키워드를 한번 찾아보시면 어떨까요?

2024-03-07 08:58 UTC, ksy90101 commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
이 부분을 ParatmerziedTest로 해볼수 있을꺼 같아요.,
@MethodSource를 사용하면 어떨까 생각이 들어요.

2024-03-07 15:27 UTC, sinterhoo commented on src/main/java/step2/StringAddCalculator.java
> +        }
1. 분리할까말까 고민했던 부분인데, 역시 하나의 역할을 하는 만큼 분리하는 게 좋을 거 같습니다! 반영 완료했습니다.
2. 요구사항에서 빈문자열의 경우 0이고, 공백은 양수가 아닌 값이기 때문에 Exception이 터진다고 생각했습니다! isBlank의 경우에는 공백 문자를 모두 true로 반환해주는군요..!

2024-03-07 15:27 UTC, sinterhoo commented on src/main/java/step2/StringAddCalculator.java
> +        return value.split("[,:]");
변하지 않는 고정된 값이므로 상수가 맞는 거 같습니다. 지역 변수로 할까 고민했는데, 우선 클래스 멤버 변수로 상수화 했습니다!

2024-03-07 15:28 UTC, sinterhoo commented on src/main/java/step2/StringAddCalculator.java
> +        }
저도 Stream이나 람다를 좋아해서 자주 쓰는 편인데, 함수형 프로그래밍 파트가 따로 있는 거 같아서 우선 기본에 충실하자는 생각에 기본 문법들 위주로 구현했던 거 같습니다..! 기본 문법에 더 익숙해지면 자바8 이후 문법들도 적극 반영해보겠습니다. (향상된 for문을 사용하긴 했지만요.. ㅋㅋㅋ)

2024-03-07 15:32 UTC, sinterhoo commented on src/main/java/step2/StringAddCalculator.java
> +                throw new IllegalArgumentException();
이 부분은 고민을 해봤는데 결론이 잘 나지 않는 거 같습니다.
초기 설계의 목적은 파싱이 실패해서 NumberFormatException이 일어났지만, 결국 사용자 입장에서 메서드 호출 시 잘못된 인수 전달을 했기 때문이라고 생각해서 IllegalArgumentException을 터트리도록 했습니다.
Exception이 일어난 직접적인 원인을 그대로 터트려줄지.. 아니면 좀 더 포괄적인 의미에 맞는 Exception을 전달해줄지 고민인데 어떻게 생각하시나요?
CustionException을 사용하는 이유도 Exception이 터진 명확한 이유를 보여주기 위해서라고 생각했어서, CustomException 대신 이 과제에서는 IllegalAgumentException으로 치환해서 보내줬는데, 리뷰어님의 생각이 궁금합니다!

2024-03-07 15:33 UTC, sinterhoo commented on src/test/java/step2/StringAddCalculatorTest.java
> +    @Test
ParameterizedTest의 경우 1단계에서 사용해봐서 알고 있었는데, NullAndEmptySource라는 기능도 있었군요! 신기해서 적용해봤습니다!

2024-03-07 15:34 UTC, sinterhoo commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
ParatmerziedTest를 사용하지 않았던 이유가 테스트 이름을 설정하는게 너무 번거롭더라구요!
테스트의 이름을 통해서 이 테스트가 어떤 기능을 확인하는지 명확하게 보여주고 싶은데, Paratmerzied의 경우에는 name 옵션을 통해서 어느정도 설정할 수는 있지만, 모두 비슷한 네이밍 포멧을 갖게 되어서 알아보기 힘들다는 생각이 들었습니다.
리뷰어님은 어떻게 생각하시나요..?!

2024-03-08 12:21 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +        }
오 네 :) stream이라는 방법도 한번 써보셨으면 좋겠다. 라는 생각에 제안드렸던것뿐이였습니다.
이미 사용을 고민하셧다면 괜찮을거 같습니다~
차후에도 더 사용할 일이 많을테니깐요!

2024-03-08 12:24 UTC, ksy90101 commented on src/main/java/step2/StringAddCalculator.java
> +                throw new IllegalArgumentException();
개인적으로 예외는 사용자가 보는 부분이 아니라고 생각합니다.
예외에 대한 메시지같은것을 사용자에게 전달을 하는것이죠.
제가 봤던 관점은 프로그램을 개발하고 로그를 확인하는 과정에서 예외를 보고 어떤 문제가 있는지 빠르게 캐치하고 하는것이라고 생각했습니다. 

IllegalAgumentException을 포괄적인 개념으로 쓰는것도 있지만, 이 예외 자체도 실제로 의미를 가지고 잇다고 생각합니다.
제가 말씀드린 부분에선 이미 표준예외에 대해서 의미있는 IllegalException이 있기 떄문에 관련된 부분을 쓰는게 더 어울리다고 생각이 들어요.

2024-03-08 12:25 UTC, ksy90101 commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
네. 이름을 짓는게 어려울수 있지만, 실제 그럴땐 @DisplayName을 사용해서 인자를 넣어서 나타내고 합니다.
https://programmer-ririhan.tistory.com/391
이글을 한번 참고해보시면 어떨까 합니다!

2024-03-08 12:30 UTC, ksy90101 approved these changes
> 궁금한 점은 하나의 객체에서 문자열을 자르고, 검증하고, 숫자로 바꿔서 계산을 하는 역할을 모두 수행하고 있는데, 메소드로 분리하는 게 아니라 아예 객체를 따로 분리하는 것도 괜찮을까요? 지금은 요구사항이 단순하니 상관없을 거 같은데, 여러 가지 조건이 추가되면 하나의 클래스에서 너무 많은 역할을 할 수도 있겠다는 생각이 들어서 궁금합니다!

객체로 분리해보는것도 좋지만, 현재는 간단하게 메서드를 분리하고, 테스트를 작성해보는걸 목표로 하는 단계이기때문에 지금과 같은 방식도 충분하다고 생각합니다. 3단계부터 객체로 분리하면서 진행해볼수 있기 떄문에 이번 단계에선 이정도로 마무리 하면 어떨까 생각이 듭니다!

아울러 차후 여러 가지 조건이 추가되었을때 분리하는것도 나쁘지 않은 전략이라고 생각합니다. 처음부터 너무 분리를 해두면 작은 기능에 많은 리소스를 쓰기도 하며, 더 어려워 보일수 있을거 같습니다. 그러다 보니 분리를 맨 처음부터 하는 경우도 있지만, 처음엔 적당히 하다가, 차후 리팩토링을 하기도 합니다 :) 


2단계 고생 많으셨습니다~ 이만 마무리 하고 3단계에서 뵙겠습니다!

2024-03-08 12:30 UTC, merged

2024-03-08 13:38 UTC, sinterhoo commented on src/main/java/step2/StringAddCalculator.java
> +                throw new IllegalArgumentException();
좋은 의견 감사합니다!

2024-03-08 13:39 UTC, sinterhoo commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
오 전에 DisplayName을 사용했는데도 제목 설정이 안돼서 뭔가 했더니, Run tests using을 IntelliJ IDEA로 변경하니 해결되는 문제였군요.. 글 참고해서 자주 써먹도록 하겠습니다 감사합니다!