2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #5285
Opened 2024-03-07 07:49 UTC by westkitekim

안녕하세요 리뷰어님!
2단계 리뷰요청 드립니다.

1단계 피드백 주신 부분들도 수정했습니다

아직 2단계임에도 불구하고 정말 많은 부족함을 느끼네요😭
코드를 작성하면서 도저히 생각이 나지 않는 부분들은
다른 분들이 작성한 코드들을 참고하며 진행해보았는데요.
이렇게 해도 되는건지 잘 모르겠습니다..

개선해 나가야하는 부분이 있다면 
촌철살인으로 알려주시면 감사하겠습니다🥶

2024-03-07 13:38 UTC, catsbi requested changes
서연님 2단계 미션 잘 구현해주셨어요. 
안풀리는 부분에 대해 고민하면 할수록 성장동력이 되니 계속 고민해보시면 좋을 것 같습니다 👍 

몇 가지 피드백을 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +    }
현재 splitAndSum이라는 함수는 인자를 분리하고 더한다는 의미를 가지고 있는데요! 
하나의 함수에서 최소 두 개의 기능이 구현되야함을 알 수 있습니다. 

그럼 테스트를  할 때 두 기능의 경우의 수를 모두 고려해서 테스트를 작성해야하는데, 2개까진 문제가 안될 수 있지만, 
3개, 4개가 될수록 테스트는 힘들어지겠죠! 왜 힘든지 잘 생각해보면 좋을 것 같아요. 

하나의 함수에서 많은 책임을 지지 않도록 하면 좋을 것 같습니다. 

우선 분리할 수 있는 대표적인 기능들을 구분해보면 
1. 인자 유효성 검증 
2. 인자 분리
3. 분리된 인자 총합 계산

이렇게 3가지인데요. 수도 코드로 구현해보면

```suggestion
    public static int splitAndSum(String text) {
        if(유효성검사(text) {
            // throw logic...
        }
        
        List<String> splitTextList = 문자열분리(text);
        return 총합계산(splitTextList);
    }
```

이렇게 나뉠 수 있겠죠!

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +        Matcher customMatcher = Pattern.compile(CUSTOM_SEPARATOR).matcher(text);
Pattern 객체는 객체 생성비용이 큰 객체입니다. 그렇기에 함수 호출시마다 매 번 새롭게 생성하는건 문제가 될 수 있지 않을까요?

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +                    .split(customMatcher.group(DELIMITER_INDEX));
매직넘버를 잘 분리해주셔서 가독성이 높아졌네요 👍

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +        if (text.contains("-")) {
`-` 도 매직 리터럴로 상수 분리를 고려해볼 수 있습니다. 

재활용 가능성이 없는 명확하고 가독성있는 값의 경우 상수로 분리를 하지 않는게 더 나을수도 있습니다. 
그렇기에 어느게 더 가독성이 높을지 고민해보면 좋을 것 같아요

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +            throw new IllegalArgumentException("Contains a negative number.");
어떤 값이 음수인지에 대해서도 Message에 노출되면 좋을 것 같네요!

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +        if (isNullOrBlank(text)) return 0;
단 한줄짜리 분기문도 블럭`{}` 생략은 지양해주세요! 코드의 일관성을 깨트리고 쌓이다보면 가독성도 같이 떨어지게 됩니다

2024-03-07 13:38 UTC, catsbi commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    }
ParameterizedTest 애노테이션과 ValueSource(or CsvSource)등을 활용해보면 테스트에 필요한 인자값을 주입받을 수 있습니다. 이를 활용해보셔도 좋을 것 같습니다!

2024-03-07 13:38 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
현재 해당 계산기 객체는 모든 함수가 정적 함수인것으로 보아 유틸리티 객체로 보여요. 
그렇다면 생성자 제한 또는 싱글턴 패턴을 활용해 무의미한 객체 생성을 피해보면 어떨까요?

2024-03-11 14:44 UTC, westkitekim commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
넵 private으로 생성자 제한을 해보았습니다. 
싱글턴 패턴을 활용한다면 getInstance()를 활용하는 부분을 말씀하시는 걸까요?

2024-03-11 14:45 UTC, westkitekim commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    }
이전 과제에서 활용했던걸 깜빡하고 있었네요..
피드백 주신대로 ParameterizedTest , CsvSource 어노테이션을 활용해봤습니다.
더 수정할 부분이 있다면 피드백 부탁드립니다!
감사합니다

2024-03-11 14:46 UTC, westkitekim commented on src/main/java/calculator/StringAddCalculator.java
> +        if (isNullOrBlank(text)) return 0;
넵 코드 컨벤션에 유의하도록 하겠습니다👍

2024-03-11 14:52 UTC, westkitekim commented on src/main/java/calculator/StringAddCalculator.java
> +            throw new IllegalArgumentException("Contains a negative number.");
(질문)
이 부분은 제대로 구현이 된건지 잘 모르겠어요.
한솔님께서 말씀하신게 분리된 이후의 음수를 개별적으로 출력해야하는지,
아니면 인자로 받은 text값 전체를 노출시켜야 하는지 어느 부분을 말씀하신 걸까요?

저는 후자로 수정했습니다.
하지만 '-' 가 몇개가 포함될 지 모르기 때문에 정확한 음수값을 노출시키려면 분리 작업을 다시 거친 후에 모든 음수를 출력하는게 나을까요?

2024-03-11 14:55 UTC, westkitekim commented on src/main/java/calculator/StringAddCalculator.java
> +        if (text.contains("-")) {
재활용 가능성은 없다고 생각하지만 
단순히 "-" 만 놓고 본다면 무슨 뜻인지 모를 수 있을 것 같네요..
가독성을 위해서 매직리터럴로 분리해보았습니다.

재활용 가능성이 없지만 가독성이 떨어진다면 말씀하신 것처럼 가독성을 위해서라도 최대한 매직리터럴로 분리하는게 나을까요?

2024-03-11 15:13 UTC, westkitekim commented on src/main/java/calculator/StringAddCalculator.java
> +    }
한솔님, 피드백 주신 수도코드를 바탕으로 다시 수정해보았어요.

제가 처음 코드작성시 '인자 유효성 검증'에 여러 검증이 있을 것 같다는 생각에 
큰 하나의 validate() 함수로 묶고 그 안에서 
1. null , empty 검증, 
2. 음수검증
3. 단일 문자열 검증 
이렇게 작성을 했었는데요

splitAndSum() 함수 내부에 제가 묶었던 검증 로직(validate())이 더 많은 책임을 지도록 한다는 말씀이실까요?

"그럼 테스트를 할 때 두 기능의 경우의 수를 모두 고려해서 테스트를 작성해야하는데, 2개까진 문제가 안될 수 있지만,
3개, 4개가 될수록 테스트는 힘들어지겠죠! 왜 힘든지 잘 생각해보면 좋을 것 같아요."
-> 책임을 많이 지면 안된다. 책임 분리원칙 까지는 이해가 가는데 테스트가 왜 힘들어지는지는  테스트코드에서 기능별로 메소드로 분리하면 되지 않을까 생각이 들어서 잘 떠오르지 않아서요.. 혹시 예시같은게 있을까요?

상세한 답변 감사드립니다 !

2024-03-12 07:51 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +    }
@westkitekim 
음 예를 들어, 나는 분리가 제대로 되는지 여러 조건으로 테스트를 해야하는데, 내부적으로 분리뿐아니라 합계까지 같이 동작을 하다보니 내가 의도하는 결과가 나오는지 찾기가 힘들 수 있겠죠. 혹은 functionA라는 함수가 내부적으로 A라는 매개변수를 A-B-C-D로 데이터를 가공해서 D를 반환하는데, 내가 테스트하려는건 A에서 B로 변환하는게 제대로 되는지를 테스트하고 싶은 경우 하나의 함수로 이 부분을 테스트하기는 쉽지 않겠죠!

2024-03-12 07:52 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +        if (text.contains("-")) {
네 이 부분은 정해진 규칙이 명확하게 있는건 아니지만, 저는 분리를 하는편입니다. 이 부분은 서연님 취향 혹은 팀 컨벤션에 맞추시면 될 것 같네요!

2024-03-12 07:53 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
네 맞습니다!

2024-03-12 07:55 UTC, catsbi approved these changes
서연님 2단계 피드백 잘 반영해주셨어요 ㅎㅎ 여러 고민들을 하며 더 나은 방법을 고민해보시고 코멘트도 다 남겨주신게 인상깊네요 💯  

2단계 머지하겠습니다 3단계 진행해주세요!

2024-03-12 07:55 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +    }
생성자 제한 👍

2024-03-12 07:56 UTC, merged