[step2] 문자열 덧셈 계산기
next-step/java-racingcar pull request #5292
Opened 2024-03-07 14:53 UTC by duyankim

문자열 덧셈 계산기 실습 내용을 구현하였습니다.

##  개발 내용

- [X] 빈 문자열 또는 null 값을 입력할 경우 0을 반환한다
- [X] 숫자 하나를 문자열로 입력할 경우 해당 숫자를 반환한다
- [X] 숫자 두개를 컴마(,) 구분자로 입력할 경우 두 숫자의 합을 반환한다
- [X] 구분자를 컴마(,) 이외에 콜론(:)을 사용할 수 있다
- [X] “//”와 “\n” 문자 사이에 커스텀 구분자를 지정할 수 있다
- [X] 음수를 전달할 경우 RuntimeException 예외가 발생한다

2024-03-08 00:24 UTC, Hyeon9mak requested changes
안녕하세요 도연님! 계산기 잘 구현해주셨습니다.
몇 가지 간단한 코멘트 남겼으니 확인해주세요!

2024-03-08 14:36 UTC, duyankim commented on src/main/java/study/StringAddCalculator.java
> +    }
현재 `StringAddCalculator`클래스는 다른 패키지에서 접근할 필요가 없으므로 접근을 제한하였습니다.
접근을 제한하면 클래스를 캡슐화하여 내부 구현을 외부로부터 감출 수 있습니다. 

다른 패키지에서도 해당 메소드에 접근할 수 있어야 한다면 public으로 선언하는 것이 적절할 것 같습니다.

2024-03-08 14:39 UTC, duyankim commented on src/main/java/study/StringAddCalculator.java
> +        return Integer.parseInt(value);
에러메세지를 수정하였습니다. 
"양수만 입력 가능합니다" -> "음수는 입력 가능하지 않습니다"

2024-03-08 14:39 UTC, duyankim commented on src/test/java/study/StringAddCalculatorTest.java
> +    }
음수 테스트 추가하였습니다.

2024-03-08 14:40 UTC, duyankim commented on src/main/java/study/StringAddCalculator.java
> +    }
Pattern 상수화 하였습니다.

2024-03-09 11:07 UTC, Hyeon9mak approved these changes
안녕하세요 도연님! 피드백 잘 반영해주셨습니다. 👍 
간단한 코멘트 남겼으니 다음 단계 진행 전에 살짝 참고해주세요~
다음 단계에서 뵙겠습니다!

2024-03-09 11:07 UTC, Hyeon9mak commented on src/main/java/study/StringAddCalculator.java
> +    }
1 과 2는 각각 어떤 의미를 가질까요? 의미를 유추하기 어려운 숫자... 매직넘버네요!
각각을 상수로 분리하여 이름을 부여해주면 훨씬 이해하기 쉽겠어요 😄 👍

2024-03-09 11:07 UTC, Hyeon9mak commented on src/test/java/study/StringAddCalculatorTest.java
> +    }
👍

2024-03-09 11:07 UTC, merged