deepredk(김진홍) 자동차경주 4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5305
Opened 2024-03-08 04:16 UTC by deepredk

안녕하세요 리뷰어님!
3단계 피드백 반영 및 4단계 완료했습니다

이번에도 잘 부탁드립니다

2024-03-08 10:06 UTC, testrace requested changes
안녕하세요 진홍님 😃 
엄청 빠르게 진행해 주셨네요!
항상 커밋 로그를 잘 남겨주신 덕에 흐름을 파악할 수 있어 리뷰에 도움이 되고 있습니다 👍 
몇 가지 코멘트 남겨두었는데요 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-08 10:06 UTC, testrace commented on src/test/java/racingcar/RacingGameTest.java
> +                expected.append(carName).append(" : ").append("-".repeat(i)).append('\n');
> 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
indent가 2이상인 메소드의 경우 메소드를 분리하면 indent를 줄일 수 있다.

UI 관련 테스트는 요구사항에서도 제외하고 있지만, 다 검증을 해주고 계셔서 위 규칙을 적용해 보시면 좋을 것 같아요

2024-03-08 10:06 UTC, testrace commented on src/test/java/racingcar/RacingGameTest.java
> +        assertThat(winnerNames).containsExactly("a", "b");
앞선 코멘트 드린 테스트와 내용이 다르지 않은 것 같아요 중복 되는 테스트가 아닌가 싶은데요 
진홍님의 생각은 어떠신가요?

2024-03-08 10:06 UTC, testrace commented on src/main/java/racingcar/RacingGame.java
>      public void drive(int round) {
(참고만 해주세요, 반영하지 않으셔도 괜찮습니다.)
요구사항 충족에는 문제가 없지만 다양한 관점으로 테스트를 해보셔도 좋을 것 같아요
<img width="405" alt="image" src="https://github.com/next-step/java-racingcar/assets/8064743/6d3fde1e-61c9-4fdb-8de9-4f367cf0ec28">

2024-03-08 12:14 UTC, deepredk commented on src/main/java/racingcar/Car.java
>      private int drivingDistance = 0;
어 넵! distance도 객체로 감싸겠습니다

그런데 혹시 궁금한 게 있는데요
Name의 경우 5자 이하여야 한다는 제약조건 때문에 객체로 감싸는 장점이 충분히 느껴지는 데 반해서
distance의 경우 딸려오는 메서드나 제약조건 같은게 따로 없는데 '꼭 감싸야 하나?' 하는 생각이 사실 들었습니다

distance와 같은 것까지 전부 객체로 감싸는 이것을 이후 코딩에도 똑같이 적용한다면
사실상 거의 모든 멤버 필드를 다 객체로 감싸게 될 것 같은데
1. 이렇게까지 하는 게 정말 실보다 득이 큰게 맞는걸까? 극단으로 가는건 아닌가?
2. 클린코드를 진지하게 추구하는 일부 회사가 아니라면 이렇게까지 객체를 분리하는 건 낯설어하지 않을까?

이런 생각이 전부터 계속 들었는데
이 부분에 대해서 리뷰어님의 의견을 여쭙고 싶습니다!

2024-03-08 12:15 UTC, deepredk commented on src/main/java/racingcar/Car.java
> +    public Car(DrivingStrategy drivingStrategy, String name) {
아아 생각해보니 그게 더 좋을 것 같습니다. 반영하겠습니다!

2024-03-08 12:17 UTC, deepredk commented on src/main/java/racingcar/Car.java
> +        return name.name();
빌더 메서드의 이름은 명사로 하라는 책 엘레강트 오브젝트의 조언과 Java17 record의 getter 메서드 이름 형태를 참고하였습니다!
저도 좀 낯설긴 한데 역시 getter가 더 직관적인가요?

2024-03-08 12:20 UTC, deepredk commented on src/main/java/racingcar/Name.java
> +        this.name = name.trim();
assertValidName 메서드 내부에서 trim을 적용한 것은 '앞뒤 공백 제외 글자수를 세기 위함'이고
다시 한번 trim 메서드를 호출한 이유는 '앞뒤 공백을 날리기 위함'입니다

null 체크를 하지 않은 상태에서 바로 trim을 하기엔 좀 그래서 요렇게 trim을 2번 사용했습니다

대신 널체크와 5자 초과 검증을 분리해보겠습니다!

2024-03-08 12:27 UTC, deepredk commented on src/test/java/racingcar/CarsTest.java
> +        assertThat(winners).containsExactly(listCars.get(0), listCars.get(1));
와 저도 이 부분 좀 아쉽긴 했는데 그렇다고 0, 1을 변수로 선언해서 이름 붙이는 건 투머치같아서 냅뒀었는데 이런 좋은 방법이 있었군요
많이 배워갑니다. 반영하겠습니다 감사합니다!

2024-03-08 12:31 UTC, deepredk commented on src/test/java/racingcar/RacingGameTest.java
> +        assertThat(winnerNames).containsExactly("a", "b");
RacingGame 객체에서 'name 부분을 추출'하는 로직이 부가적으로 있어서
테스트에서 아예 제외하기는 또 좀 그런 것 같아서 추가했습니다

대신 Cars의 getWinners를 모킹하는 방향으로 한번 반영해보겠습니다!

2024-03-08 13:24 UTC, deepredk commented on src/main/java/racingcar/RacingGame.java
>      public void drive(int round) {
조언 감사합니다! 요 부분을 한번 5단계에서 세세하게 적용해보겠습니다 😃

2024-03-08 13:36 UTC, testrace commented on src/main/java/racingcar/Car.java
> +        return name.name();
단순 질문이었습니다 😃 
저도 엘레강트 오브젝트에서 말하는 명사형 네이밍을 즐겨 사용합니다

2024-03-08 13:57 UTC, testrace commented on src/main/java/racingcar/Car.java
>      private int drivingDistance = 0;
많은 고민을 하신게 느껴집니다 😃 

>1. 이렇게까지 하는 게 정말 실보다 득이 큰게 맞는걸까? 극단으로 가는건 아닌가?

비유가 적절한지 모르겠습니다만
알지만 안하는 것과 몰라서 못하는 것은 다르다고 생각해요
지금 득실을 판단하기 보다 이번 과정에서 극단적으로 구현해보신 후 실무에 어디까지 적용이 가능한지 경험해 보시는 것이 좋은 판단 기준이 될 것이라 생각합니다 😃 

>2. 클린코드를 진지하게 추구하는 일부 회사가 아니라면 이렇게까지 객체를 분리하는 건 낯설어하지 않을까?

진홍님께서 학습하신 내용을 코드로 보여주고 전파한다면 덜 낯설어 하게 되지 않을까요? 😄

2024-03-08 14:06 UTC, deepredk commented on src/main/java/racingcar/Car.java
>      private int drivingDistance = 0;
조언 감사합니다 ㅎㅎ final 키워드라던지 객체 감싸는거라던지 한번 정말 극단적으로 해봐야겠습니다

리뷰어님의 생각은 혹시 어떠신가요??
모든 primitive 필드를 객체로 감싸는 것이 거의 무조건 좋다고 생각하시는 쪽이신가요?

2024-03-09 11:34 UTC, testrace requested changes
안녕하세요 진홍님 😃 
피드백 반영 잘해주셨네요 👍 
조금 더 개선하면 좋을 것 같은 부분이 있어 코멘트 남겨두었습니다
확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-09 11:34 UTC, testrace commented on src/main/java/racingcar/RacingGameConsole.java
> +    private static final DrivingStrategyImpl DRIVING_STRATEGY = new DrivingStrategyImpl();
변수의 타입은 구현체보다 추상 타입으로 선언하면 어떨까요?
```suggestion
    private static final DrivingStrategy DRIVING_STRATEGY = new DrivingStrategyImpl();
```

(참고만 해주세요)
개인적으로 ~Impl 접미사는 활용하지 않는 편인데요
단순 구현체라는 의미로는 클래스가 무엇을 뜻하는지 파악하기 어렵다는 점에서 입니다
List 라는 인터페이스의 구현체의 이름이 ListImpl이 아닌 ArrayList, LinkedList 등 클래스가 무엇인지 나타내고 있습니다
랜덤 숫자로 이동 가능 여부를 판단하니 클래스명에서 표현되면 좋을 것 같아요

2024-03-09 11:34 UTC, testrace commented on src/test/java/racingcar/CarTest.java
> +        Car car = new Car(NAME);
자동차를 생성하는 코드가 반복되니 테스트 fixture를 활용해 보시는 것도 좋을 것 같아요
테스트 코드도 유지보수 대상이니 리팩터링으로 반복을 제거할 수 없는지 고려해 보시면 좋을 것 같아요

2024-03-09 11:34 UTC, testrace commented on src/test/java/racingcar/RacingGameTest.java
> +        racingGame.drive(5, () -> true);
단순히 반복되는 값들은 변수로 만들어서 재사용하면 어떨까요?
람다식도 상수로 만들 수 있으니 참고해 주시면 좋을 것 같아요
```java
private static final int FIVE_TIMES = 5;
private static final DrivingStrategy ALWAYS_MOVE = () -> true;

...
test() {
  ...
   racingGame.drive(FIVE_TIMES, ALWAYS_MOVE);
}
```

2024-03-09 11:34 UTC, testrace commented on src/main/java/racingcar/RacingGameConsole.java
> +        racingGame.drive(round, DRIVING_STRATEGY);
round 값도 원시 타입이니 포장하면 어떨까요?
최소값의 제약도 있고 round.isEnd() 같은 메서드도 추가할 수 있을 것 같아요

2024-03-09 11:34 UTC, testrace commented on src/main/java/racingcar/Cars.java
> +    protected Cars() {
생성자는 테스트를 위해 추가해도 좋다고 생각합니다
다만 프로덕션에서 사용할 수 있는 수준으로 구현해야 책임을 온전히 수행할 수 있습니다.
비어 있는 컬렉션으로 getResult, getWinners 등이 의도하는대로 동작한다고 보장을 할 수 있는지 고민해 보시면 좋을 것 같아요

2024-03-09 12:02 UTC, deepredk commented on src/main/java/racingcar/Car.java
> +        return drivingDistance.getDrivingDistance();
오 훨씬 좋은 이름 같습니다! 감사합니다

2024-03-09 12:17 UTC, deepredk commented on src/main/java/racingcar/Name.java
> +        if (name == null) {
**null 체크를 생성자, assert 메서드 두곳에서 하는 이유?**
=> 리팩토링하면서 놓친 부분입니다! assert 메서드에서의 null 체크는 불필요하니 삭제하겠습니다

참고) 제 코드의 의도는 아래와 같습니다
1. 바로 trim을 하면 null일 시 예외 터지니 null부터 체크하고
2. null 아니면 trim()이 예외없이 실행되니 trim()을 하는데
3. 이 trim()한 값이 '멤버변수 값 초기화'에도 쓰이고 '글자수 검증'에도 쓰이니까 두 곳 모두에서 trim()을 하기보다 멤버변수에 바로 trim()으로 초기화를 한 뒤, 그 값을 재활용해서 검증 메서드로 보냄

2024-03-09 12:18 UTC, deepredk commented on src/main/java/racingcar/Name.java
> +        if (name == null) {
null 체크를 생성자, assert 메서드 두곳에서 하는 이유?
=> 리팩토링하면서 놓친 부분입니다! assert 메서드에서의 null 체크는 불필요하니 삭제하겠습니다

참고) 제 코드의 의도는 아래와 같습니다

바로 trim을 하면 null일 시 예외 터지니 null부터 체크하고
null 아니면 trim()이 예외없이 실행되니 trim()을 하는데
이 trim()한 값이 '멤버변수 값 초기화'에도 쓰이고 '글자수 검증'에도 쓰이니까 두 곳 모두에서 trim()을 하기보다 멤버변수에 바로 trim()으로 초기화를 한 뒤, 그 값을 재활용해서 검증 메서드로 보냄

2024-03-09 12:29 UTC, deepredk commented on src/main/java/racingcar/Cars.java
> +    public Cars(String[] carNames) {
제네릭 타입 소거때문에 `List<Car>`과 `List<String>`이 둘 다 `List`로 취급돼서 오버로딩이 안됩니다 😭

2024-03-09 12:54 UTC, deepredk commented on src/main/java/racingcar/Cars.java
> +    public Cars(String[] carNames) {
아! static 팩토리 메서드로 하면 될 것 같습니다
static 팩토리 메서드 사용해서 개선하겠습니다!

2024-03-09 13:31 UTC, deepredk commented on src/main/java/racingcar/RacingGameConsole.java
> +        racingGame.drive(round, DRIVING_STRATEGY);
```java
public void drive(int roundAmount, DrivingStrategy drivingStrategy) {
    Round round = new Round(roundAmount);
    for (int i = 0; i < round.value(); i++) {
        cars.drive(drivingStrategy);
        roundResults.add(cars.result());
    }
}
```

메서드 파라미터까지 Round round로 바꾸기엔
RacingGame 객체를 사용하는 쪽에서 Round라는 객체를 알아야 할 필요성이 생기는 부분이 번거로울 수 있을거라 생각해서 위와 같이 변경했습니다!

혹 더 좋은 방향 있다면 피드백 부탁드리겠습니다

2024-03-10 10:09 UTC, testrace approved these changes
안녕하세요 진홍님 😃 
피드백을 굉장히 빠르게 반영해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다음 단계 진행해 주세요!

2024-03-10 10:09 UTC, testrace commented on src/test/java/racingcar/CarsTest.java
> +            String.format("%s : -\n%s : -\n%s : -", CAR_NAMES.get(0), CAR_NAMES.get(1), CAR_NAMES.get(2)));
CarFixture가 있다면 index를 활용하지 않고 검증할 수 있을 것 같아요
```suggestion
        cars.drive(ALWAYS_MOVE);
        assertThat(cars.result()).isEqualTo(
            String.format("%s : -\n%s : -\n%s : -", CarFixture.K3, CarFixture.K5, CarFixture.K9));
```

2024-03-10 10:09 UTC, testrace commented on src/test/java/racingcar/CarsTest.java
> +            String.format("%s : --\n%s : --\n%s : --", CAR_NAMES.get(0), CAR_NAMES.get(1), CAR_NAMES.get(2)));
다음 단계의 내용이라 여태껏 코멘트 드리지 않았는데요
이 테스트가 정말 필요한 테스트인지 고민해 보시면 좋을 것 같아요

2024-03-10 10:09 UTC, testrace commented on src/test/java/racingcar/RoundTest.java
> +    }
불변 객체는 값이 변하지 않기 때문에 여러 인스턴스가 필요없는데요
같은 값을 가지는 객체는 항상 동일할 수 있도록 도전해 보셔도 좋을 것 같아요 
아래 테스트가 통과한다면 동일한 인스턴스라고 볼 수 있겠네요
```java
assertThat(Round.valueOf(1)).isSameAs(Round.valueOf(1));
```

2024-03-10 10:10 UTC, merged

2024-03-11 11:30 UTC, deepredk commented on src/main/java/racingcar/Cars.java
> +        return new Cars(cars);
와우 덕분에 유용한 Collector 하나 알아갑니다 감사합니다!