3단계 - 자동차 경주
next-step/java-racingcar pull request #5318
Opened 2024-03-09 03:48 UTC by movingone

중간에 궁금한점이 생겨서 PR날립니다

CarRacing이라는 객체를 만들고 Racing() 메서드 외에는 private 하는것이 CarRacing이라는 객체의 입장에서는 외부에서 사용할때 다른 메서드는 어떤것이 있는지 어떻게 작동되는지 모르는것이 좋다고 생각하여 모두 private 달았는데 막상 테스트를 하려고 하니 테스트 할때 만큼은 public 으로 수정하는것이 맞는것인지 궁금증이 생겼습니다.

메서드 명에 있어서 좀 깔끔하지 않다거나, 아쫌 아쉬운데 하는 것들이 있다면 의견 부탁드립니다

2024-03-09 04:52 UTC, movingone reviewed
테스트 코드를 작성하려고 하다보니 저의 코드를 자꾸 되돌아보게 되는데, 어느정도 매개변수가 있어야 할 것같다는 생각이 듭니다. 매개변수가 3, 4 개씩 너무 많아서는 안되지만 아예 없다보니 테스트 하는데 임의로 줘야할 값이 많이 생기는 것 같습니다. 

테스트 작성을 위해서만이 아니라 좀 객체지향 적으로 짜려고 한다 했을때 어느정도의 매개변수 형식으로 넘겨주는 것이 좋을까요?

매개변수 없이 메서드 안에서 할려한것이 잘못된 객체지향 일까요?

2024-03-09 05:17 UTC, movingone reviewed
System.out.println 와같이 출력하는 값들은 어떻게 테스트틀 작성하는게 좋을까요?

StringBuilder를 통해서 값을 저장하는 함수하나 그 값을 출력하는 함수 하나로 나눠서 안의 값을 확인하면 될까요?

2024-03-09 08:15 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
처음 접하시는 개발 방법론이 조금 생소하실 수도 있겠습니다. 다른 분들의 코드 리뷰 요청 사항도 적극적으로 참고해 보시면, 힌트가 될 수 있겠습니다. 추가적인 질문은 얼마든지 환영입니다. 🙇

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacing.java
> +package racingcar;
1. 모든 메소드가 `static` 인 것은 완벽하게 코드 스멜 중 하나입니다. Racing 한 게임을 하나의 인스턴스로 생각해 주시면 좋습니다. 거기서부터 출발한다면 클래스 책임 분리 및 테스트 하기 좋은 코드로 갈 수 있는 첫 걸음이 될 것 같습니다.

레이싱 게임 -> 레이스 -> 자동차 의 개념으로 생각하시면 어떨까요? 게임이 레이스를 포함하고, 레이스가 자동차를 갖고 있는 개념입니다.

2. 기본적으로 우리가 진행하는 미션들은 거의 무조건 세 개 이상의 클래스 파일을 필요로 합니다. 테스트 클래스를 제외하고, 클래스가 하나밖에 나오지 않았다면 뭔가 방향성이 잘못된 것으로 생각해 주시면 됩니다.

3. 기본적인 코딩 컨벤션은 준수해 주시면 좋습니다. 예를 들어, Java에서 메소드의 이름은 소문자로 시작합니다. 이런 부분에 대해서 제가 모두 리뷰를 드리게 되면 생산적인 코드 리뷰 과정이 되지 못하기 때문에, IDE의 코드 포매팅을 활용하셔도 좋고, [기본적인 Java 코딩 컨벤션](https://naver.github.io/hackday-conventions-java/)은 숙지한 상태에서 작업 진행해주시면 대단히 감사하겠습니다.

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacing.java
> +        System.out.println("자동차 대수는 몇 대 인가요?");
Sysout 등 UI요소에 대한 테스트는 진행해 주지 않으셔도 됩니다.

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacing.java
> +public class CarRacing {
`CarRacing` 을 아까 설명드린 레이싱 게임 한 판의 개념으로 리팩터링 해주시면 좋을 것 같고,
테스트 코드 이외에도, 실제 애플리케이션의 진입점이 될 수 있는 `public static void main()` 을 포함하는 퍼블릭 클래스가 있어야 합니다.

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacing.java
> +    static void Racing() {
이 메소드를 앞서 말씀드린 psvm 메소드가 구현된 클래스 쪽으로, 메인 메소드로 이동시켜 주시면 됩니다.

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacing.java
> +            cars[i] = new LinkedList<>();
자동차는 `-` 기호가 아닌 정수형 값을 자신의 위치 정보로서 가져야 합니다.

2024-03-09 08:15 UTC, wheejuni commented on src/test/java/racingcar/CarRacingTest.java
> +class CarRacingTest {
아래 케이스에 대한 테스트가 부재합니다.

1. `GO_CONDITION` 이 넘는 숫자를 입력받은 자동차가 스스로 한 칸을 움직이는지?
2. 1의 결과에 따라, 자동차는 자신의 위치를 문자열로 변환하여 리턴할 수 있는지?

2024-03-09 08:15 UTC, wheejuni commented
> 테스트 코드를 작성하려고 하다보니 저의 코드를 자꾸 되돌아보게 되는데, 어느정도 매개변수가 있어야 할 것같다는 생각이 듭니다. 매개변수가 3, 4 개씩 너무 많아서는 안되지만 아예 없다보니 테스트 하는데 임의로 줘야할 값이 많이 생기는 것 같습니다.
> 
> 테스트 작성을 위해서만이 아니라 좀 객체지향 적으로 짜려고 한다 했을때 어느정도의 매개변수 형식으로 넘겨주는 것이 좋을까요?
> 
> 매개변수 없이 메서드 안에서 할려한것이 잘못된 객체지향 일까요?

이것에 대해서는 지금 단계에서 고민하실 필욘 없고, 테스트 케이스 안에서 임의로 값을 얼마든지 부여하시기 바랍니다.

2024-03-13 12:15 UTC, wheejuni approved these changes

2024-03-13 12:15 UTC, merged