3단계 - 자동차 경주
next-step/java-racingcar pull request #5333
Opened 2024-03-09 19:20 UTC by eleeje97

3단계 리뷰 잘 부탁드립니다! :)
감사합니다.

2024-03-10 01:05 UTC, wooobo requested changes
안녕하세요 다은님!

와우 3단계 잘 진행해주셨네요!
몇가지 코멘트 남겨 놓았어요~

확인 후 재요청 부탁드려요~

2024-03-10 01:05 UTC, wooobo commented on src/main/java/racing/domain/AttemptCount.java
> +        if (isZeroOrNegativeNumber(number)) {
지키고자하는 책임를 가진 객체가 new 될때부터 그러한 규칙을 가지고 생성된다면 어떨까요?

2024-03-10 01:05 UTC, wooobo commented on src/main/java/racing/domain/RacingCar.java
> +    public void attempToMove(int randomNumber) {
`attemptToMove` 😎

2024-03-10 01:05 UTC, wooobo commented on src/main/java/racing/domain/RacingCar.java
> +    public void attempToMove(int randomNumber) {
랜덤이라는 의미는 호출 하는곳에서의 의미 아닐까요?
랜덤이라는 복잡한 의미를 가진 단어를 끌고 들어와야 할까요?

> 단어는 우리의 사고에 큰 영향을 끼칠수 있습니다.

2024-03-10 01:05 UTC, wooobo commented on src/test/java/racing/AttemptCountTest.java
> +        assertThat(attemptCount.getNumberOfAttempt()).isEqualTo(5);
객체간의 비교를 하려면 무엇을 구현해야할까요?

2024-03-10 15:05 UTC, eleeje97 commented on src/main/java/racing/domain/AttemptCount.java
> +public class AttemptCount {
같은 기능을 가지고 있는 시도횟수, 자동차대수를 일반화하여 `Count`클래스로 만들었습니다!

2024-03-10 15:18 UTC, eleeje97 commented on src/test/java/racing/AttemptCountTest.java
> +        assertThat(attemptCount.getNumberOfAttempt()).isEqualTo(5);
객체간의 비교를 할 때는 equals(), hashCode()를 구현해야 합니다!
그런데 저는 Count클래스의 멤버변수 값을 테스트하는 것이라고 생각했는데, 
위 테스트에서 객체간의 비교가 필요한 것일까요!?

2024-03-10 15:30 UTC, eleeje97 commented on src/main/java/racing/domain/AttemptCount.java
> +        if (isZeroOrNegativeNumber(number)) {
저는 해당 클래스의 생성자에서 위 로직을 호출하므로 
객체가 생성될 때 그 규칙을 가지고 생성된다고 생각했는데 
제가 잘못 이해한걸까요??

2024-03-10 15:33 UTC, eleeje97 commented on src/main/java/racing/domain/RacingCar.java
> +    public void attempToMove(int randomNumber) {
RacingCar에서는 해당 숫자가 랜덤숫자인지 알 필요가 없겠네요!
변수명 수정하였습니다.

2024-03-11 04:41 UTC, wooobo approved these changes
안녕하세요 다은님!

3단계 잘 진행해주셨습니다~
이만 `merge`진행하겠습니다!

그럼 좋은 하루 되세요!

2024-03-11 04:41 UTC, wooobo commented on src/main/java/racing/domain/Count.java
> +public class Count {
어쩌면 양수라는 이름이 어울릴지도 모르겠네요 ㅎ🤔

2024-03-11 04:41 UTC, wooobo commented on src/main/java/racing/domain/RacingCar.java
> +    private static final int MOVE_BORDER_NUMBER = 4;
[참고](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html)

컨벤션에 정답은 없지만 static 변수는 인스턴스 변수보다 위에 있는게 일반적인것 같아요 ㅎ

2024-03-11 04:41 UTC, merged