3단계 - 자동차 경주 게임을 구현했습니다.
next-step/java-racingcar pull request #5335
Opened 2024-03-10 03:48 UTC by yuus95

## 작업 내용
- 자동차 게임 경주 구현

## 회고
- 랜덤 클래스의 책임을 어디에 넣을지 고민하다 일글컬렉션에 넣었습니다. 이유는 
한번 생성할 때 랜덤 유틸클래스를 가지고 있으면,  한번만 생성되고 재사용이 가능할 거 라고 생각했습니다.

- 테스트를 위해 메소드 하나가 더생성됐는데 이게 맞는 방향일까 고민이 되지만 우선 구현했던 그대로 제출했습니다. 불필요한 메소드라고 생각이 들긴 하네요..

- 자동차는 움직이기만 하고 움직이도록 이벤트를 발생하는건 Racing이라고 생각했습니다.
이 때 일급컬렉션을 이용하여 리스트에게 행위를 요청할 경우를 컨트롤 할 수 있게 구현했습니다. 
일급컬렉션을 사용할 때 이게 맞는 방향인지는 모르겠지만... 코드는 조금 더 명확해지는 것 같습니다. 

- 테스트 커버리지가 적당한지 스스로 판단하기 어려운 부분도 있었던 것 같습니다. 
테스트 커버리지가 어느정도야 적당할까요...

2024-03-10 03:49 UTC, yuus95 commented on src/main/java/stringAddCalculator/StringNumberDelimiter.java
> +            return new StringDelimiter(String.valueOf(input.charAt(CUSTOM_DELIMITER_INDEX)), true);
Step2 말씀해주신 부분 수정해서 넣어놨습니다!
merge가 된상태라 우선 여기다 작성했습니다~!

2024-03-11 00:27 UTC, neojjc2 commented
#tag @neojjc2

2024-03-11 00:46 UTC, neojjc2 requested changes
안녕하세요 유신님 🙇 

3단계 구현 잘 해주셨습니다 💯 
2단계 개선 요청사항도 잘 반영해주셨네요 👍 

구조가 조금만 개선되면 더 좋을 것 같아서
몇 가지 의견 드렸습니다.

한번 보시고 개선 검토 해주시면 감사하겠습니다 🙇 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙏

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/Car.java
> +        if (moveNumber >= VERIFY_START_MOVE_NUMBER && moveNumber <= VERIFY_END_MOVE_NUMBER) {
`moveNumber`가 4하고 9사이 일 경우에만 1씩 전진할 수 있는 구조네요 🤔 
마치 가속페달 혹은 브레이크페달을 밟았는데, 차가 전진할지, 멈출지를 차가 판단하는 구조입니다. 

가정을 하나 해보면, 만약 게임에 대한 `Car`의 위치를 체크해야 하는 `Car`들이 필요하고
(예를들면 경기를 중계하는 차들이라고 해볼께요 😅) 
5위치, 10위치에 세워둬야 하는 요구사항이 생긴다면, 지금 구조에서는 불가능합니다.

또한 `RacingGame`중에 문제가 발생해서 진행중인 차들을 다시 시작 점 (`position=0`) 으로 옮겨야 하는 상황이 생긴다면 지금구조에선 방법이 없습니다.

저희가 운전을 할 때도 가속페달을 밟거나, 브레이크를 밟아서 가고 서는 부분을 결정해주는 것 처럼
이미 `RandomNumberCreator`를 통해 게임을 제어하는 요소를 분리하셨으니, 이번엔 
전략패턴을 한번 적용해 볼 시점이 온 것 같습니다 🙇

차에게 움직일지 말지를 외부에서 제어할 수 있게 한번 개선해보면 좋을 것 같아요 😄 
요 내용 한번 참고해보시면 좋을 것 같습니다. 
> https://jackjeong.tistory.com/108

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/CarList.java
> +public class CarList {
오 일급컬렉션을 사용해주셨네요 좋습니다 👍 

하지만 이름은 좀 변경이 필요할 것 같습니다. 
늘 네이밍은 고민이죠 😭 클래스 명에 `List`가 들어었어서 나중에 `Map`이나 `Set`등으로 내부 컬렉션이 변경된다면 
요 이름을 어떻게 할 지 고민하게 될 것 같아요 🤣

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/CarList.java
> +    private final RandomNumberCreator randomNumberCreate;
생성 단계부터 `RandomNumberCreator`에 대한 의존성을 가져갈 필요가 있을지 고민한번 해주시면 좋겠습니다. 
`moveWithRandomNumber`때 인자로 `Creator`를 전달하게 한다면 좀 더 유연해질 것 같습니다 😄

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/InputView.java
> +        return new Racing(carNumber, tryNumber);
`InputView`는 사용자로부터 입력 값을 받는 정도로만 역할위임하시고 
게임에 필요한 것들을 준비해서 셋업을 하는 역할은 `RacingCar`가 하는건 어떨까 의견드려봅니다 🙏

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/Racing.java
> +    private static final RandomCreator randomCreator = new RandomCreator();
상수 이므로 대문자 선언되면 더 좋을 것 같습니다 🙏 
```suggestion
    private static final RandomCreator RANDOM_CREATOR = new RandomCreator();
```

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/step3/RandomCreator.java
> +    private static final Random random = new Random();
```suggestion
    private static final Random RANDOM = new Random();
```

2024-03-11 00:46 UTC, neojjc2 commented on src/main/java/stringAddCalculator/StringNumberDelimiter.java
> +            return new StringDelimiter(String.valueOf(input.charAt(CUSTOM_DELIMITER_INDEX)), true);
리뷰 사항 반영 감사합니다 💯

2024-03-11 11:28 UTC, yuus95 reviewed
리뷰해주셔서 감사합니다. 
전략패턴관련 내용을 고민을 많이했는데...
맞게 구현했는지 모르겠습니다. 하하.. 관련하여 코맨트를 달았는데 의도가 맞는지 확인 한번 부탁드립니다!

상수표현을 왜 계속 비슷하게 놓칠까 생각해봤는데, 
Random 등 특정 클래스 타입을 상수라고 생각을 안하고 코드를 작성하는 습관이네요.. 고치겠습니다~!
(대부분 String,int만 상수로 지정 하던 습관 때문 인 것 같습니다....)

2024-03-11 11:28 UTC, yuus95 commented on src/main/java/step3/CarList.java
> +public class CarList {
CarFirstCollection 자동차 일급컬렉션 이라는 직관적인 네이밍은 혹시 어떨까요?
우선 해당 내용 반영해놓겠습니다..!

2024-03-11 11:28 UTC, yuus95 commented on src/main/java/step3/CarList.java
> +    private final RandomNumberCreator randomNumberCreate;
CarList 의 moveWithRandomNumber()에 메소드 파라미터로 할당한 뒤 Racing에서 호출할 때 넣었으면,
해당 의존성은 필요 없어도 되겠군요. 
가지고 있는 필드가 전달 목적으로만 가지고 있어  외부또는 내부에 전달만 하고 사용을 안한다면  고민한번  해보고 선언을 해야 될 것 같습니다!

2024-03-11 11:28 UTC, yuus95 commented on src/main/java/step3/CarList.java
> +    private final RandomNumberCreator randomNumberCreate;
우선 전략패턴을 적용하면 크게 로직이 바뀌어... 의도만 파악해봤습니다!

2024-03-11 11:28 UTC, yuus95 commented on src/main/java/step3/InputView.java
> +        return new Racing(carNumber, tryNumber);
ÌnputRequest`라는 객체를 만들어서 사용자의 요청을 받아서 외부에서 Racing 만들 수 있도록 책임을 분리했습니다.

2024-03-12 05:54 UTC, neojjc2 commented on src/main/java/step3/Car.java
> +        if (moveNumber >= VERIFY_START_MOVE_NUMBER && moveNumber <= VERIFY_END_MOVE_NUMBER) {
그보다는 (아실수도 있지만) 단일책임원칙이나 개방폐쇄원칙을 준수할 수 있기 때문입니다. 
물론 예를 들어주신 다양한 조건이 있는 케이스를 위해서 전략패턴을 사용할 수도 있겠습니다만, 
유연성이나 재 사용성 측면에서 고민한 결과로 만들어진 해법 중에 하나라서 그렇습니다 😄 
그리고 Runtime 이 변경사항에 대해서 용이한데요 
다양한 Stragegy를 미리 만들어놓고 Runtime시 요구상에 따라서 객체들을 바꿔 넣을 수 있기 때문에
기존 코드에 대한 수정 없이 변경사항에 대해서 쉽게 대처가 가능한 구조가 됩니다 😄 
요 개념과 비슷하지만 약간은 다른(?) 템플릿 메소드 패턴도 있는데요
이번에 함께 정리해보시면 좋을 것 같습니다 🙏 
> https://refactoring.guru/ko/design-patterns/template-method

2024-03-12 05:57 UTC, neojjc2 commented on src/main/java/step3/CarList.java
> +public class CarList {
네 좋습니다 👍 
> 근데 개인적으로는 알고리즘이나, 디자인패턴들이 들어간 이름을 선호하진 않습니다 😅

2024-03-12 05:57 UTC, neojjc2 commented on src/main/java/step3/CarList.java
> +    private final RandomNumberCreator randomNumberCreate;
네네 좋습니다 👍

2024-03-12 06:05 UTC, neojjc2 approved these changes
안녕하세요 유신님 🙇 

다소 많은 요청사항을 드린게 아닌가 걱정했는데, 
많은 개선을 해주셨네요 👍 

정말 수고 많으셨습니다 🙏 
개선의 효과는 다음단계 요구사항 반영하시면서 
한번 경험해보시죠 😄 

3단계 진행하시느라 수고 많으셨습니다 🙇

2024-03-12 06:05 UTC, merged

2024-03-12 09:50 UTC, yuus95 commented on src/main/java/step3/Car.java
> +        if (moveNumber >= VERIFY_START_MOVE_NUMBER && moveNumber <= VERIFY_END_MOVE_NUMBER) {
템플릿 메소드는 진짜 하나의 템플릿으로 추상화한 뒤,  구현체에서 구현하여 사용하는거였군요!
본체의 전원을 키는 행위등  전반적인 특정 행위는 같지만 내부 구현이 다를 경우 사용하면 유용할 거 같습니다. 
주말에 예시들을 직접구현해서 저도 한번 작성 해봐야겠네요~!

전략 패턴을 사용해본 결과 어떠한 정의된 행동을 외부에서 변경하여 사용할 수 있다는게 말씀 하신 것 처럼 좋은 것 같습니다. 
다양한 행동을 취할 수 있도록 객체를 유연하게 설계할 수 있을 것 같아요! 

좋은 정보 공유해주셔서 감사합니다~!

2024-03-12 09:51 UTC, yuus95 commented on src/main/java/step3/CarList.java
> +public class CarList {
@neojjc2 
혹시 그렇다면 선호하는 네이밍이 있으실까요~!?
`Cars`..?