[Step3] 자동차 경주
next-step/java-racingcar pull request #5349
Opened 2024-03-10 15:17 UTC by Danden1

안녕하세요.

이번 과제는 어떻게 클래스를 설계하고 테스트를 해야할 지 많은 고민을 했습니다.

클래스 설계 같은 경우에는 DDD 의 layered architecture를 이용했습니다.

- presentation
- application
- domain
- infra

총 4개의 layer로 구분됩니다.

이렇게 구성한 이유는 랜덤숫자를 생성하는 부분 때문입니다,
서비스를 운영하다가, 추후에 랜덤숫자를 기반으로 이동하는 것이 아닌 다른 방식으로도 동작할 수도 있을 수도 있습니다.
(파일을 읽어서 한다든가, 다른 복잡한 로직이 들어가든가 등)

이처럼 기술적인 부분이 수정이 된다면, infra layer의 클래스만 수정하고 다른 layer의 클래스들은 수정하지 않아도 됩니다.
또한 테스트할 때에도 최대한 의존성을 줄일 수 있어서 이런 식으로 설계했습니다.

### 질문

1.  클래스 네이밍을 할 때 ~er을 붙이지 말라는 내용을 봤습니다. 그렇다면 controller(mvc할 때)로도 이름을 지으면 안되는 걸까요?
2. 랜덤 숫자를 테스트할 수 있는 좋은 방법이 있는 지 궁금합니다. (제가 테스트한 방법이 어떤지 봐주시면 감사하겠습니다.)
3. getPosition() 같은 getter를 쓰지말라고 하셨는데, 이는 nextstep만의 룰일까요? 아니면 실제로도 getter를 잘 안 쓰는 지 궁금합니다. (제가 본 예제들 코드나 현재 회사 코드내에서도 많이 보여서 질문드립니다. 너무 오랫동안 이러한 코드들을 봐와서 어색하네요...)
4. RacingCarService에서 차량 정보를 줄 때 깊은 복사를 하려고 하는 메소드(cars())가 있습니다. 근데 복사할 객체가 많아지면 객체를 복사하는 연산 때문에 속도나 heap 영역에 지장이 있을 수 있을 것 같습니다. 실제로 값이 변하는 것을 막기 위해서 이러한 깊은 복사를 많이 이용할 지, 아니면 팀 내에서 다른 곳에서 변경을 하면 안 된다는 룰을 적용하는 것이 좋을까요?

<br>

감사합니다!

2024-03-11 14:44 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2024-03-11 14:44 UTC, kyucumber commented on README.md
>  * 모든 피드백을 완료하면 다음 단계를 도전하고 앞의 과정을 반복한다.
> 클래스 네이밍을 할 때 ~er을 붙이지 말라는 내용을 봤습니다. 그렇다면 controller(mvc할 때)로도 이름을 지으면 안되는 걸까요?

er로 네이밍 하는 것을 지양하라는 것은 어떤 사람이 이와 관련된 내용을 주장했는지, 어디서 보신건지에 따라 주장하는 바가 다를 것 같아서 명확히 의도를 알기는 어렵네요. 

개인적인 생각이지만 er로 네이밍 하는 경우 클래스가 무엇인지가 아닌 무엇을 하는지 행동에 초점을 맞추어 네이밍이 되기 때문에 지양하라는 것일 것 같은데요. 컨트롤러의 경우 나눠진 레이어를 표현하기 위한 용어라 er을 붙이지 말라는 내용과 맥락이 조금 다른 것 같습니다.

그리고 -er로 네이밍 하는것에 대한 저의 생각을 말씀드리면 당연히 잘 정의된 도메인 클래스 안에 각각에 걸맞는 행동이 위치하는게 좋으니 당연히 행동에 초점을 맞춘 -er로 네이밍 하는 것을 지양하는게 맞겠지만 때에 따라 역할이 명확히 드러나기도 해서 무조건적으로 지양해야 할지는 좀 고민이 되네요.

2024-03-11 14:44 UTC, kyucumber commented on src/main/java/racingcar/domain/Car.java
> +    public int position() {
> getPosition() 같은 getter를 쓰지말라고 하셨는데, 이는 nextstep만의 룰일까요? 아니면 실제로도 getter를 잘 안 쓰는 지 궁금합니다. (제가 본 예제들 코드나 현재 회사 코드내에서도 많이 보여서 질문드립니다. 너무 오랫동안 이러한 코드들을 봐와서 어색하네요...)

getter를 쓰지말라는 것은 단순히 값을 가져오거나 setter로 처리하는 부분을 지양하기 위해 극단적으로 말씀하신 부분이 있을 것 같네요. 예를들면 getPosition으로 위치를 체크하고 setPosition으로 위치값을 + 1 하는 부분이 move로 대체된 것과 같은 예시를 들 수 있을 것 같습니다.

move로 구현할 수 있는데 get 이후 set하는 형태로 구현되는 부분을 지양하라는 것이지 극단적으로 getter를 아예 사용하지 말라는 것은 아닙니다. 여기서 구현하신 것 처럼 getPosition을 position으로 바꾸는 것이 강의에서 의도하는 바는 아닙니다. 오히려 자바의 컨벤션을 해쳐서 더 혼란스럽네요.

2024-03-11 14:44 UTC, kyucumber commented on src/main/java/racingcar/infra/MoveCommandImpl.java
> +        throw new IllegalArgumentException(String.format("%d~%d 사이의 숫자만 가능합니다.", MIN_NUMBER, MAX_NUMBER));
그리 중요한 부분은 아니지만, 아래의 객체지향 생활 체조 원칙을 위반하고 있습니다.

- 규칙 2: else 예약어를 쓰지 않는다.

명확하게 검증 후 예외를 던지는 형태로 메서드를 추출하고 else if 없이 구현해볼 수 있을 것 같네요.

2024-03-11 14:44 UTC, kyucumber commented on src/test/java/racingcar/utils/TestNumber.java
> +public class TestNumber implements Number {
테스트를 위해 인터페이스를 갈아끼우는 형태로 잘 구현하셨네요 👍 

> 랜덤 숫자를 테스트할 수 있는 좋은 방법이 있는 지 궁금합니다. (제가 테스트한 방법이 어떤지 봐주시면 감사하겠습니다.)

다만 우리는 자동차 경주에 대한 도메인을 구현하고 있습니다. 랜덤 숫자에 대한 테스트를 고민하고 숫자에 대한 부분을 추상화하기보단 자동차가 이동할 지 말지에 대한 부분을 추상화하는게 더 낫지 않을까 생각되어요. 도메인에 정책이 구현되어 있어야 하기 때문입니다.

당연히 인프라쪽도 추상화가 되어 있다면 유연하게 교체하거나 이중화하거나 할 수 있기 때문에 유용하겠지만 우리는 도메인에 대한 정책을 관리하고 테스트할 것이기 때문에 MoveCommand를 활용하는게 더 자연스럽다고 생각합니다.

사실 추상화를 어떻게 할지에 대한 정답은 없습니다. 다만 이렇게 숫자를 가져오는 부분이 추상화가 되면 이동 여부 결정 과정에수 숫자를 쓰지 않는다면 추상화가 크게 의미가 없게 됩니다. 도메인에 따라 어느 수준에서 추상화를 할 지, 어떤 행동을 추상화할지 고민해보면 좋을 것 같아요.

2024-03-11 14:44 UTC, kyucumber commented on src/main/java/racingcar/application/RacingCarService.java
> +    public List<Car> cars() {
> RacingCarService에서 차량 정보를 줄 때 깊은 복사를 하려고 하는 메소드(cars())가 있습니다. 근데 복사할 객체가 많아지면 객체를 복사하는 연산 때문에 속도나 heap 영역에 지장이 있을 수 있을 것 같습니다. 실제로 값이 변하는 것을 막기 위해서 이러한 깊은 복사를 많이 이용할 지, 아니면 팀 내에서 다른 곳에서 변경을 하면 안 된다는 룰을 적용하는 것이 좋을까요?

Car는 현재 int 타입의 변수 하나가 있습니다. 이를 인스턴스화하면

- int 타입의 4바이트
- 기타 헤더 8바이트(인스턴스나 클래스 정보)
  - 이 부분은 잘 기억이 나지 않으니 참고만 부탁드립니다. 정확할 필요는 없는 상황으로 보여요.

인스턴스 하나에 총 12바이트를 가지게 됩니다.
이런 인스턴스가 대략 100개 가량 있어야 1KB가 될거고, 이런 인스턴스가 1000개 가량 더 있어야 1MB가 됩니다.

그렇게 힙 사이즈에 많은 공간을 차지 하지 않을 뿐더러 JVM 내부에서는 GC를 통해 참조되지 않는 데이터를 지속적으로 힙에서 제거합니다.

말이 길어졌는데 엄청나게 큰 인스턴스가 아니고, 참조만 잘 제거된다면 인스턴스가 생성되는 것 자체는 아무런 문제가 없습니다. 이 복사 때문에 연산을 많이 쓴다면 CPU를 늘려야 할 것이고, 참조가 지워지기 전에 힙이 많이 차는거라면 힙 용량을 적절히 늘려야겠죠. 힙을 늘리고 CPU도 늘려도 해결이 되지 않으면 Scale Out을 통해 장비의 대수를 늘리면 됩니다.

2024-03-11 14:44 UTC, kyucumber commented on src/main/java/racingcar/domain/MoveType.java
> +    }
movePosition이란 메서드의 이름만 보면 전달받은 position 파라미터만큼 move를 수행할 것 같은데요. 헷갈릴 여지가 있는 것 같아요.

리뷰를 하다보니 엘레강트 오브젝트 책을 읽으신 것 같은데(아니면 죄송합니다. 😭 ) 저자가 작성한 내용들이 나쁜 것은 아니지만 일반적인 자바 컨벤션을 위반하거나 혼란을 줄 수 있는 내용도 많습니다.

협업하는 팀에서만 컨벤션이 잘 맞으면 상관은 없으나 일반적으로 통용되는 것은 아님을 인지하고 사용하시면 좋겠습니다. 저 책의 내용이 잘못되었고 저런 메서드 네이밍이 나쁘다는 것은 절대 아닙니다. 개발에는 정답이 없으니까요.

2024-03-12 10:01 UTC, Danden1 commented on src/main/java/racingcar/infra/MoveCommandImpl.java
> +        throw new IllegalArgumentException(String.format("%d~%d 사이의 숫자만 가능합니다.", MIN_NUMBER, MAX_NUMBER));
궁금한 점이 하나 있습니다!

좋은 코드, 나쁜 코드라는 책에서 enum을 예시로 설명을 하는 글이 있습니다.

```
public enum GameName {
  LOL, MAPLE;
}


public String getGame(GameName gameName) {
  switch(gameName) {
     case LOL:
         return "LOL;
      case MAPLE:
         return "MAPLE";
      default:
         throw new RuntimeException();
    }
  
}
```

enum 같은 경우에는 이런 식으로 확장성을 염두에 두고 하라는 글이 있습니다. 만약 새로운 필드가 추가되면, 이에 대해 구현하지 않으면 예외가 발생시킴으로써 처리하라는 글입니다.
저도 이를 염두에 두고 설계를 했습니다. 제가 구현한 것처럼 하는 것은 별로 일까요?

(물론 NextStep은 객체지향 생활 체조 원칙이라는 룰이 있으니 수정하겠습니다! )

2024-03-12 10:03 UTC, Danden1 commented on src/main/java/racingcar/application/RacingCarService.java
> +    public List<Car> cars() {
그렇군요. 제가 다니는 회사에서는 복잡한 필드를 가지고 있는 수만개의 데이터를 다루다보니 이러한 고민을 했었습니다.

답변 감사합니다!

2024-03-12 10:05 UTC, Danden1 commented on src/main/java/racingcar/domain/MoveType.java
> +    }
엘레강트 오브젝트는 읽지 않았습니다 ㅎㅎ..
NextStep에서는 이 책을 기반으로 다루고 있더라고요. 그래서인지 getter를 사용하지 말라는 글이있어서 이런 식으로 했습니다.

2024-03-12 11:10 UTC, Danden1 commented on src/test/java/racingcar/utils/TestNumber.java
> +public class TestNumber implements Number {
답변 감사합니다. 

저도 모르게 테스트를 위한 코드를 구현하려고 했던 것 같습니다.

그래서 좀 더 생각을 해본 것은 저희 도메인은 차량을 이동할 때는 무조건 "숫자"를 이용한다고 이해를 해서 원래 infra layer에 있던 Number 인터페이스를 domain으로 변경했습니다. 

숫자를 생성하는 방식(랜덤)을 infra라고 가정해서 수정은 했는데... 이렇게 하는 것이 잘 모르겠습니다.

너무 어렵네요 ㅠㅠ

2024-03-12 11:29 UTC, Danden1 commented on src/main/java/racingcar/domain/Car.java
> +    public int position() {
답변 감사합니다!

2024-03-12 11:34 UTC, Danden1 commented
안녕하세요. 

리뷰어님이 피드백 주신 부분에서 의문점이 드는 부분은 코멘트로 답글 남겼습니다!

- 메소드 네이밍 변경(get 추가)
- Number의 layer 변경(infra -> domain)
- else if 제거

정성스러운 피드백 감사합니다!

2024-03-12 13:33 UTC, kyucumber commented on src/main/java/racingcar/infra/MoveCommandImpl.java
> +        throw new IllegalArgumentException(String.format("%d~%d 사이의 숫자만 가능합니다.", MIN_NUMBER, MAX_NUMBER));
> 저도 이를 염두에 두고 설계를 했습니다.

기존 코드의 경우 "%d~%d 사이의 숫자만 가능합니다"와 같은 문구가 있습니다. 이외 같은 의도를 파악하지 못했네요. 기존 구현을 생각하면 오히려 혼란을 주었을 것 같은데요.

특정 범위의 숫자만 가능한지 여부를 체크하는 메서드 하나와 적절한 enum을 찾지 못한 경우에 대한 부분을 분리하는게 좋을 것 같습니다.

2024-03-12 13:35 UTC, kyucumber commented on src/test/java/racingcar/utils/TestNumber.java
> +public class TestNumber implements Number {
> 저희 도메인은 차량을 이동할 때는 무조건 "숫자"를 이용한다

개인적으로 추상화의 의도 자체가 유연함을 부여하기 위함인데 숫자라는 부분에 강결합 될 필요가 있나 하는 생각이 드네요. 이동 여부를 결정하는 형태로 추상화가 되는게 도메인에 더 적절하지 않을까 하는 생각이 듭니다.

다만 추상화엔 정답은 없으므로 의도하신 대로 구현해도 무방할 듯 하네요.

2024-03-12 13:35 UTC, kyucumber approved these changes
남겨두신 코멘트에 답변 달아두었습니다. 다음 단계 진행에 참고 부탁드려요.

다음 단계 진행을 위해 머지하겠습니다.

2024-03-12 13:36 UTC, merged