[3단계] 자동차 경주
next-step/java-racingcar pull request #5353
Opened 2024-03-11 00:34 UTC by sm9171

안녕하세요. 리뷰어님 저번 2단계에 피드백 준 부분과 3단계 작업 추가적으로 완료하였습니다.

2024-03-11 09:41 UTC, Hyeon9mak requested changes
안녕하세요 상민님, 3단계 잘 진행해주셨습니다.
고민해보실만한 부분들에 코멘트를 남겼는데요,
몇 가지 중복되는 의미의 코멘트도 존재할거에요!
잘 고민해보시고 리팩터링 해보시면 좋을거 같습니다 😄 👍 
궁금하신 점 질문 남겨주세요~

2024-03-11 09:41 UTC, Hyeon9mak commented on TODO.md
> +- [ ] 실행결과를 보여준다.
👀 😃

2024-03-11 09:41 UTC, Hyeon9mak commented on src/main/java/calculator/Calculator.java
>  	}
음... 의견이 잘못 전달 된 것 같네요!

```java
public class Calculator {
    private static final Pattern CUSTOM_SEPARATOR_PATTERN = Pattern.compile("...");
}
```

요런 의도의 피드백이었습니다.

2024-03-11 09:41 UTC, Hyeon9mak commented on src/main/java/racingcar/Car.java
> +    }
"자동차 이동 위치를 `-` 대신 `>>` 로 바꿔주세요!" 라는 요구사항이 동료 개발자에게 전달되면,
동료 개발자는 `ResultView` 와 `Car` 클래스 파일 중 어디를 먼저 열어보게 될 것 같으신가요?
만약 `ResultView` 를 먼저 열어볼 것 같다면, `-` 를 그리는 책임은 `ResultView` 로 이동해야할 것 같아요 😉

2024-03-11 09:41 UTC, Hyeon9mak commented on src/main/java/racingcar/Cars.java
> +	}
모든 자동차를 이동시킬 때마다 무조건 `Random` 인스턴스를 생성해야하는 걸까요? 😱

2024-03-11 09:41 UTC, Hyeon9mak commented on src/main/java/racingcar/Cars.java
> +	}
`System.out` 을 이용해서 출력을 진행한다는 건 view 들의 책임 아닐까요? 🤔

2024-03-11 09:41 UTC, Hyeon9mak commented on src/main/java/racingcar/InputView.java
> +	}
매 입력을 받을 때마다 Scanner 인스턴스를 생성할 필요는 없어보여요!

2024-03-11 09:41 UTC, Hyeon9mak commented on src/test/java/racingcar/RacingCarTest.java
> +            assertThat(car.getPosition()).isEqualTo(1);
테스트 하고 싶은 내용은 "4 이상이면 전진한다." 인데, 꼭 난수를 활용할 필요가 있을까요? 🤔 
진짜 검증하고 싶은 내용이 무엇인지 고민해볼 필요가 있겠어요!

2024-03-11 12:08 UTC, sm9171 commented on src/test/java/racingcar/RacingCarTest.java
> +            assertThat(car.getPosition()).isEqualTo(1);
그럼 난수같이 제가 컨트롤 할 수없는 부분은 제외하고 테스트를 진행하는게 맞을까요?

2024-03-11 12:13 UTC, sm9171 commented on src/main/java/racingcar/InputView.java
> +	}
네 상수 필드로 뺐습니다 😄

2024-03-11 12:13 UTC, sm9171 commented on src/main/java/racingcar/Cars.java
> +	}
네 생각 해보니까 출력은 Cars의 책임이 아닌것 같아서 resultVIew로 책임을 전환했습니다.

2024-03-11 12:14 UTC, sm9171 commented on src/main/java/racingcar/Cars.java
> +	}
random 인스턴스를 상수화 했습니다. 😄

2024-03-11 12:15 UTC, sm9171 commented on src/main/java/racingcar/Car.java
> +    }
뭔가 문자 관련된 책임은 view쪽이 맞다고 생각합니다. ResultView 로 이동하겠습니다.

2024-03-12 04:42 UTC, Hyeon9mak approved these changes
안녕하세요 상민님! 피드백 잘 반영해주셨습니다.
간단한 코멘트 남겼으니 다음 단계 진행하면서 함께 참고해주세요.
다음 단계에서 뵙겠습니다. 💪

2024-03-12 04:42 UTC, Hyeon9mak commented on src/main/java/calculator/Calculator.java
> +	private static final int NUMBERS_INDEX = 2;
😉 👍

2024-03-12 04:42 UTC, Hyeon9mak commented on src/main/java/racingcar/ResultView.java
> +		Cars cars = new Cars();
자동차 게임 결과에 대해서는 앞으로 `InputView`, `ResultView` 만 열어보면 끝이네요! 👍

2024-03-12 04:42 UTC, Hyeon9mak commented on src/main/java/racingcar/Cars.java
> +	public static final Random RANDOM = new Random();
내부에서만 사용되는 것 같아요!
IntelliJ 를 사용하시는 경우 상수 단축키(`OPT` + `CMD` + `C`) 를 연속 2회 입력하시면 기본 접근제한 설정이 가능해요~

2024-03-12 04:42 UTC, Hyeon9mak commented on src/test/java/racingcar/RacingCarTest.java
> +		assertThat(car.getPosition()).isEqualTo(1);
> 그럼 난수같이 제가 컨트롤 할 수없는 부분은 제외하고 테스트를 진행하는게 맞을까요?

컨트롤 할 수 없는 부분은 제외한다... 라기보단..!
"난수는 어차피 테스트하는 것이 의미가 없다."
"난수 생성 라이브러리는 어차피 신뢰하고 사용할 수 있다."

요런 느낌입니다 ㅎ.ㅎ!

2024-03-12 04:42 UTC, merged