🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #5354
Opened 2024-03-11 03:11 UTC by hellonayeon

안녕하세요 선동님!
3단계 미션 리뷰 요청드립니다.

2단계에서 남겨주신 피드백 확인하고 반영했습니다.
리뷰 꼼꼼하게 해주셔서 감사드립니다.

3단계 미션을 진행하다 보니, 요구사항의 범위나 테스트 범위에 대해 혼자 고민하는 시간이 길어져서
일단 스탑하고 리뷰 요청 드렸습니다.
의견이나 수정할 내용 공유 주시면 빠르게 반영해서 다시 리뷰 요청드리도록 할게요 🥹

미션 관련해서 고민한 내용은 아래 글과 코드 조각으로 남겨둘게요.
감사합니다!

---

미션 관련하여 겪었던 어려움 공유드립니다. 
동일한 경험이나 해결할 수 있는 좋은 방법을 알고 계신다면 공유 부탁드려요 🫠

```

"기능 요구사항 분리" 를 어떻게 해야할지 고민입니다.

3단계 미션 시작 초기 단계에 가장 어려웠던 부분은
미션에서 주어진 기능 요구사항 기반으로 추가적인 요구사항을 분리 (TODO LIST 작성) 였는데요.

그래서 요구사항 바탕으로 객체들의 역할 정도만 정리하고 단위 테스트 코드 작성을 시작했던 것 같아요.
(앞서 진행했던 2단계 미션처럼 '어떤 값이 들어왔을때 어떤 값이 나와야한다 ~' 형식으로 요구사항을 분리하기가 어렵더라구요..)

우선은 객체들의 역할을 간단하게만 적어두고 단위 테스트 작성을 진행했는데요,
요구사항이 복잡해지면 객체들의 역할을 뽑아내는게 쉽지 않더라도 객체 기준으로 요구사항을 추출하는게 더 좋은건지, 
기대하는 입출력 값 기준으로 먼저 요구사항들을 뽑아내고 가는게 좋은건지 잘 모르겠습니다.

추가적으로 미션을 진행하다 보니 "요구사항에 나와있지 않은 부분", 특히 예외처리 부분에서 어떤 기준으로 구현하고 테스트 해야할지 방향을 잡지 못했던 것 같습니다. 
```

2024-03-11 03:14 UTC, hellonayeon commented on src/main/java/racingcar/Car.java
> +    }
자동차를 설계할때 외부에서 자동차의 전진 거리(`distance`)를 굳이 접근할 필요가 없다고 생각했는데,
테스트 검증을 위해 메서드가 distance 를 리턴하게끔 생성했습니다.

즉, 단위 테스트를 먼저 작성하니 실제로 리턴값이 필요하지 않거나, 인스턴스 내부에서 사용하는 변수라 외부에서 호출할 일이 없는 경우인데도 불구하고
값을 리턴하도록 메서드를 작성한 것 같아요.

설계의 문제인가 싶기도 하고.. 이런 경우는 어떻게 하는게 좋을까요?

2024-03-11 03:16 UTC, hellonayeon commented on src/main/java/racingcar/Car.java
> +    }
유사한 내용으로 단위 테스트 검증을 위해 `getter` 가 필요할 수도 있겠다 싶었는데, 이런 경우에는 어떻게 하는게 좋을까요.

2024-03-11 03:23 UTC, hellonayeon commented on src/test/java/racingcar/CarsTest.java
> +    }
Random 으로 전진 조건 값을 생성해서 바로 단일 자동차(Car) 의 move() 메서드 인자로 넘겨주다 보니, 
일급 컬렉션(Cars, 다수개의 자동차를 관리하는 인스턴스) 에 대한 move() 를 테스트할 수 없었는데요.

이게 설계로 인한 문제인지, 아니면 Cars 는 Car 에 대한 단위 테스트를 믿고 가야하는건지 궁금합니다.

2024-03-11 03:25 UTC, hellonayeon commented on src/main/java/racingcar/app/CarRaceApp.java
> +    }
클라이언트 앱 구현이 필요 할까요?

미션에서 기대 입출력값을 정리해주셔서 똑같이 구현하려고 작성하긴 했는데,
프로그래밍 요구사항에서 System.out, in 단위 테스트는 생략인걸 보니 
미션 자체가 도메인 테스트만 하는게 목적인 것 같기도 하고 .. 해서 가볍게 여쭤봅니다.

2024-03-11 03:25 UTC, hellonayeon commented on src/main/java/racingcar/README.md
> +  - 자동차의 이동 결과를 출력한다.
객체 역할을 기준으로 기능 요구사항 분리

2024-03-11 13:17 UTC, seondongpyo requested changes
3단계 미션도 잘 구현해주셨네요 👍
몇 가지 코멘트 드렸는데, 확인 후 다시 리뷰 요청을 부탁 드리겠습니다.
궁금하신 점 있으시면 언제든 편하게 코멘트나 슬랙으로 DM 주세요!

2024-03-11 13:17 UTC, seondongpyo commented on src/main/java/racingcar/README.md
> +  - 자동차의 이동 결과를 출력한다.
> "기능 요구사항 분리" 를 어떻게 해야할지 고민입니다.

> 3단계 미션 시작 초기 단계에 가장 어려웠던 부분은
미션에서 주어진 기능 요구사항 기반으로 추가적인 요구사항을 분리 (TODO LIST 작성) 였는데요.

> 그래서 요구사항 바탕으로 객체들의 역할 정도만 정리하고 단위 테스트 코드 작성을 시작했던 것 같아요.
(앞서 진행했던 2단계 미션처럼 '어떤 값이 들어왔을때 어떤 값이 나와야한다 ~' 형식으로 요구사항을 분리하기가 어렵더라구요..)

> 우선은 객체들의 역할을 간단하게만 적어두고 단위 테스트 작성을 진행했는데요,
요구사항이 복잡해지면 객체들의 역할을 뽑아내는게 쉽지 않더라도 객체 기준으로 요구사항을 추출하는게 더 좋은 방법인지, 
기대하는 입출력 값 기준으로 먼저 요구사항들을 뽑아내고 가는게 좋은 방법인지 잘 모르겠습니다.

> 추가적으로 미션을 진행하다 보니 "요구사항에 나와있지 않은 부분", 
특히 예외처리 부분에서 어떤 기준으로 구현하고 테스트 해야할지 방향을 잡지 못했던 것 같습니다.
또한 클래스 추상화를 어떻게 해야할지도 고민이 많이 되었습니다.

> 이런 내용들을 매번 고민하다가 심플하게 요구사항에 있는 기본만 일단 잘 구현해보자 라는 생각으로 코드를 작성했네요 🙊 

도메인 지식이 부족할 땐 일단 대략적으로 필요하겠다 싶은 클래스들을 설계하고, 그 다음 각각의 클래스에 상태와 기능을 추가하여 요구사항을 우선적으로 만족하도록 작성하는 편입니다. 그러면서 문득 하나의 클래스에 너무 많은 책임이 부여됐다면 '원시 값 포장'이나 '일급 컬렉션' 등을 적용하여 역할과 책임을 조금씩 나누고 있습니다. 도메인에 대해 잘 알고 있다면 크기가 작은 클래스에서 큰 클래스 순으로 설계하기 쉽겠지만, 그렇지 않다면  클래스 설계를 고민하는 데에 시간을 쏟기 보다는 큰 클래스부터 작은 클래스 순으로 진행하는 것이 개인적으로는 빠르고 편하다고 느끼고 있습니다.

저도 지금 나연 님께서 말씀하셨던 고민들을 많이 했었는데, 저 같은 경우는 처음부터 '미션 코드를 완벽하게 작성해야 한다'라는 강박 관념이 강했던 거 같아요. 아무래도 저장소가 public으로 오픈이 되어 있고, 누구나 내가 작성한 코드를 볼 수 있다는 심리적인 압박감도 작용을 했었구요. 하지만 그러다보니 코드에 대해 고민하는 시간이 점점 늘어가면서 미션 진행 속도가 점점 더디게 되는 부작용이 있더라구요. 나연 님께서는 어떤 입장이신지 제가 알 순 없지만 감히 말씀을 드리자면 일단 생각나는 대로, 손이 가는 대로 작성해보셨으면 좋겠어요. 각 미션에는 '정답 코드'라는 건 존재하지 않습니다. 지금 나연 님께서 고민하고 계시는 예외 처리, 클래스 추상화 등이 본인 입장에서는 부족하다고 생각하실 순 있어도 '틀린' 코드는 아니기 때문에, 의견을 주고 받으며 조금씩 더 좋은 방향으로 발전시켜간다는 생각으로 자신감을 가지고 임해보시면 좋을 것 같아요.

2024-03-11 13:55 UTC, hellonayeon commented on src/main/java/racingcar/Car.java
> +    private void validateNegativeDistance() {
String.repeat() 의 인자로 음수 값을 전달할 경우 Exception 이 발생해서 검증 로직을 추가했어요.
하지만 위에서 리뷰 주신 것 처럼 자동차 위치를 표현하는 역할이 view 로 이동되면 해당 로직이 필요가 없어지겠네요!

```java
    @Nested
    @DisplayName("[학습 테스트]")
    class LearningTest {

        @Test
        @DisplayName("[학습 테스트] String.repeat()")
        void string_repeat() {
            assertThat("-".repeat(3)).isEqualTo("---");

            // repeat 인자로 음수를 전달하는 경우
            assertThatThrownBy(() -> {
                "-".repeat(-1);
            })
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("count is negative: -1");
        }

    }
```

2024-03-11 14:08 UTC, hellonayeon commented on src/main/java/racingcar/Cars.java
> +    private final List<Car> carList;
`-List` 는 특수한 의미, 자바에서는 자료구조를 표현하는 단어로 이와 같이 이미 약속된 단어를 사용하면 다른 의미로도 해석될 수 있어요 🥹 

`클린 코드 2장: 의미있는 이름, 그릇된 정보를 피하라`

2024-03-11 14:11 UTC, hellonayeon commented on src/main/java/racingcar/exception/CarErrorMessage.java
> +public enum CarErrorMessage {
커스텀 예외 클래스를 구현하고 있고, 
커스텀 예외에 대응되는 메시지는 피드백처럼 예외 클래스 내부에 있는게 예외를 관리하고 의미를 파악하기 더 좋을 것 같네요!!

2024-03-11 15:16 UTC, hellonayeon commented on src/main/java/racingcar/Car.java
> +    private void validateNegativeDistance() {
주어진 요구사항 자체가 `전진` `정지` 라서 현재 위치가 음수인지 검증하는 로직은 없어도 될 것 같아요.
Car 클래스에서 특수기호를 변환하려다 보니 생긴 불필요한 로직이네요 😃

2024-03-11 17:21 UTC, hellonayeon commented
선동님 좋은 말씀 감사합니다 !
같은 고민에 대한 경험을 공유해주셔서 그런지 모든 내용이 와닿네요.

먼저 고민하고 경험해보신 분과 함께 더 나은 코드에 대해 끊임없이 고민해본다는 마음으로 
미션에 임해보겠습니다 🫡

2024-03-12 04:39 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
추가로 몇 가지 코멘트 드렸는데 확인 부탁 드리겠습니다.
다음 단계도 힘내시길 응원합니다 🔥

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/Car.java
> +    }
자동차의 `이동 조건`을 상태로 가지는 대신에 외부에서 전달 받아서 처리해보는 건 어떨까요?
보다 자동차의 움직임을 더 유연하게 만들어볼 수 있을 것 같은데 어떻게 생각하시나요?

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/CarMoveCondition.java
> +public interface CarMoveCondition {
👍

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/Car.java
> +    private int distance;
객체지향 생활 체조 원칙의 `규칙 3: 모든 원시값과 문자열을 포장한다.`를 적용해보면 어떨까요?

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/CustomCarMoveCondition.java
> +public class CustomCarMoveCondition implements CarMoveCondition {
테스트에서만 사용되는 코드라면 `/src/test/java` 하위로 옮기는 게 적절해 보이는데 어떻게 생각하시나요?

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/RandomCarMoveCondition.java
> +public class RandomCarMoveCondition implements CarMoveCondition {
👍

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/domain/RandomValueGenerator.java
> +public class RandomValueGenerator {
`RandomCarMoveCondition`을 추가해주셔서 더 이상 사용하지 않는 코드로 보이니, 제거해도 괜찮지 않을까요?

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/ui/InputView.java
> +    private final static Scanner SCANNER = new Scanner(System.in);
상수 네이밍 컨벤션에 따라 `static final` 순으로 작성해주시면 좋을 것 같습니다.
```suggestion
    private static final Scanner SCANNER = new Scanner(System.in);
```

2024-03-12 04:39 UTC, seondongpyo commented on src/main/java/racingcar/ui/ResultView.java
> +    }
사용자로부터 값을 입력받을 때 출력하는 메시지들이니, `InputView` 내부로 옮겨보는 건 어떨까요?

2024-03-12 04:39 UTC, seondongpyo commented on src/test/java/racingcar/CarTest.java
> +        Car car = new Car(new CustomCarMoveCondition("MOVE"));
특정 값에 의한 이동 조건 대신에, 자동차가 `항상 이동`하거나 `항상 멈추는` 조건들을 만들어보면 어떨까요?

2024-03-12 04:39 UTC, merged

2024-03-12 13:10 UTC, hellonayeon commented on src/main/java/racingcar/domain/Car.java
> +    }
'자동차가 자신이 어떻게 움직일지 전략을 가지고 있어야지' 라는.. 상태 중심 생각 때문에 이 둘이 의존관계를 맺게끔 설계했던 것 같아요.

피드백 바탕으로 외부에서 메서드 파라미터로서 넘겨주니까 
Car 인스턴스 생성 시 생성자에 조건 객체를 더이상 넘겨주지 않아도 되고,
이동조건을 상태로 가지는게 아니라 외부로부터 필요할때 입력 받아 사용하니까 Car 객체는 유연해졌다고 느껴지네요!

질문 안주셨으면 생각 못해봤을 것 같아요. 의견 공유해주셔서 감사합니다 !!


> 혹시 제가 피드백을 잘못 이해했다면 다시 리뷰 부탁드립니다.
```java
/* to-be */

public class Car {

    private final Distance distance;

    public Car() {
        this.distance = new Distance();
    }

    public void move(CarMoveStrategy moveStrategy) {
        if (moveStrategy.isMovable()) {
            distance.increase();
        }
    }

    public Distance getDistance() {
        return this.distance;
    }

}
```

2024-03-13 03:22 UTC, hellonayeon commented on src/test/java/racingcar/CarTest.java
> +        Car car = new Car(new CustomCarMoveCondition("MOVE"));
`항상 이동` `항상 정지` 조건을 만듦으로써 단위테스트에서 자동차 상태 변화가 수월해졌어요 😃

리팩토링 전에는 `CustomCarMoveCondition("MOVE")` 로 불필요한 문자열을 넘겨 줘야하고 파라미터에 제약이 없어서
부실하다는 생각이 들었는데요.

이동 조건을 넓은 범위로 구체화해서 발생한 문제인 것 같아요. 
명확하게 `AlwaysMoveCondition` `AlwaysStopCondition` 구체클래스들을 만들어두고 필요한걸 주입해서 사용하도록 했습니다.

의견 공유주셔서 감사합니다!