[Step4] 자동차 경주(우승자)
next-step/java-racingcar pull request #5365
Opened 2024-03-11 12:09 UTC by nimohLee

4단계 구현 완료했습니다.

- 최대한 getter 없이 구현해보려고 했는데 한계에 부딪혀 값 객체에만 getter를 사용하는 전략으로 수정하였습니다.

- 말씀하신대로 일급 컬렉션을 iterable를 구현체로 만드는 것에 대해 고민을 해봤습니다. 저는 Cars를 순회하더라도 Car 자체에 Tell Don't ask 를 크게 위반하는 행위가 없어서 괜찮을 것 같다는 생각입니다. 또한 테스트 작성 시에 iterable을 구현하고 있으면, Assertions에 내장된 많은 메서드를 사용할 수 있다는 점을 무시할 수 없었습니다. 어떻게 생각하시나요?

2024-03-11 23:40 UTC, testrace requested changes
안녕하세요 호민님 😃 
4단계 잘 구현해 주셨네요 👍 
질문에 대한 답변과 몇 가지 코멘트 남겨두었는데요
확인해 주시고 다시 리뷰 요청 부타드려요

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition())
@maxPosition은 매번 호출하지 않고 한번만 호출해 두면 어떨까요?
`int maxPosition = maxPosition();`

>최대한 getter 없이 구현해보려고 했는데 한계에 부딪혀 값 객체에만 getter를 사용하는 전략으로 수정하였습니다.

getter를 활용하지 않고 메시지를 보내면 어떨까요?
```suggestion
                .filter(car -> car.samePosition(maxPosition))
```

우려하신 것처럼 getter가 존재하는 것만으로도 의도와 다른 방향으로 사용될 수 있는데요 
이 부분은 개발자가 최대한 의식적으로 노력을 해야하는 부분이라고 생각합니다

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/InputView.java
> +    private boolean isCarNameLengthOverStandard(List<String> carNameList) {
불필요한 공백은 제거해 주시면 좋을 것 같아요
```suggestion

    private boolean isCarNameLengthOverStandard(List<String> carNameList) {
```

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/InputView.java
> +    private String scanNextLine() {
가독성을 위해 메서드 사이에 공백을 두면 어떨까요?

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Name.java
> +    final String name;
Name 객체 👍 
캡슐화를 위해 접근제어 범위를 private으로 지정하면 어떨까요?
자동차 이름 길이에 대한 제약을 가지고 있으니 단위 테스트를 추가하면 어떨까요?

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Position.java
>      private int position;
Name처럼 final 키워드를 붙이면 어떨까요?
Position을 불변객체로 활용하면 좋을 것 같아요

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Race.java
> +        List<String> carNameArr = inputView.inputtedCarNameList(CAR_NAME_MESSAGE);
타입은 List인데 변수명에는 arr이 포함되어 있네요
변수명에 ~List 등을 사용하는 경우 해당 자료구조에 의존할 수 있는데요
타입이 변경되는 경우 변수명도 함께 변경되어야할 것 같아요
타입보단 변수의 용도에 따른 이름으로 부여하면 어떨까요? 여러대의 자동차 이름이라면 carNames 가 될 수 있겠네요

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/InputView.java
> +    public List<String> inputtedCarNameList(String message) {
아래와 같은 상황에 대한 검증이 추가되면 어떨까요?
<img width="419" alt="image" src="https://github.com/next-step/java-racingcar/assets/8064743/730f6d38-8abd-4814-b38b-c0bc8914a496">

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/ResultView.java
> +        System.out.println(stringBuilder + "가 최종 우승했습니다.");
StringBuilder를 활용해주셨군요 👍 
String#join 메서드도 활용해 보시면 좋을 것 같아요
```java
List<String> winnerNames = ...;
System.out.println(WINNER_DELIMITER, winnerNames);
```

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/strategy/MoveStrategy.java
> +@FunctionalInterface
👍

2024-03-11 23:40 UTC, testrace commented on src/test/java/racing/CarsTest.java
> +    void getWinnerList_one_winner() {
테스트의 의도를 쉽고 빠르게 이해할 수 있도록 DisplayName을 추가하면 어떨까요?

2024-03-11 23:40 UTC, testrace commented on src/test/java/racing/StringUtilTest.java
> +    void splitStringToList() {
ParameterizedTest를 활용해 보셔도 좋을 것 같아요

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Cars.java
> +    public List<Car> getWinnerList() {
우승자 목록도 하나의 객체로 도출하면 어떨까요?
```suggestion
    public Winners getWinners() {
```

2024-03-11 23:40 UTC, testrace commented on src/main/java/racing/Cars.java
>  public class Cars implements Iterable<Car> {
>말씀하신대로 일급 컬렉션을 iterable를 구현체로 만드는 것에 대해 고민을 해봤습니다. �저는 Cars를 순회하더라도 Car 자체에 Tell Don't ask 를 크게 위반하는 행위가 없어서 괜찮을 것 같다는 생각입니다. 또한 테스트 작성 시에 iterable을 구현하고 있으면, Assertions에 내장된 많은 메서드를 사용할 수 있다는 점을 무시할 수 없었습니다. 어떻게 생각하시나요?

좋은 접근이신 것 같아요 😃 
저는 개인적으로 도메인 객체라면 메시지를 보내는 방식을 선호해서 코멘트 드렸습니다
(Iterator 타입을 꺼내는 것만으로도 메시지는 보내는 방식이 아니라고 생각해요)
일급 컬렉션이 반드시 iterable을 구현하지 않아야 한다는 조건은 없으니 지금 상태를 유지하셔도 좋습니다
테스트 코드에서의 장점을 말씀해 주신 것처럼 CarsTest 등에서 iterable을 활용한 테스트가 있다면 더 좋았을 것 같네요 😃

2024-03-12 12:11 UTC, nimohLee commented
피드백 주신대로 Position의 position 필드를 final로 하려고 하니, position++ 하는 로직에 걸려서 기존 Position 객체로는 final을 붙일 수가 없었습니다. 대신 final을 붙이고, add()가 호출되면 new Position()을 반환하는 형태로 변경했습니다.

하나 고민되는 것은 Position을 add() 할 때마다 객체가 생성되는 건데, 이게 과연 좋은 코드인 지 모르겠습니다.

2024-03-12 23:17 UTC, testrace requested changes
안녕하세요 호민님 😃 
피드백 반영 잘해주셨네요 👍 
다음 단계 진행하기 전에 꼭 반영되었으면 하는 부분이 있어 코멘트 남겨두었습니다
확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-12 23:17 UTC, testrace commented on src/main/java/racing/Name.java
> +        validNameIsNotEmpty(name);
validation 👍

2024-03-12 23:17 UTC, testrace commented on src/main/java/racing/Position.java
> +        return new Position(position + addPosition);
불변 객체를 잘 활용해 주셨네요 👍 
>하나 고민되는 것은 Position을 add() 할 때마다 객체가 생성되는 건데, 이게 과연 좋은 코드인 지 모르겠습니다.

지금 미션의 내용으로는 불변 객체의 장점을 알기 쉽지 않다고 생각해요 😃 
다음 미션에서 본격적으로 불변 객체의 장점이 드러날텐데요 이번 미션에서는 연습 삼아 사용해 본 것으로도 충분하다 생각합니다
흔히 쓰이는 String, Integer 등의 클래스도 불변 클래스인데요 자바에서 불변객체를 어떻게 관리하는지 찾아보시면 좋을 것 같아요

2024-03-12 23:17 UTC, testrace commented on src/main/java/racing/Race.java
>          while (currentTryCount < tryCount) {
(optional)
tryCount 값을 객체로 도출하면 어떨까요?
최소 값의 제약과 남은 시도 횟수에 대한 책임을 부여해볼 수 있을 것 같아요

2024-03-12 23:17 UTC, testrace commented on src/main/java/racing/Winners.java
> +    private static final String WINNER_DELIMITER = ",";
클래스 구현 순서는 다음과 같은 순서로 위치하면 어떨까요?

```
class  T {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2024-03-12 23:17 UTC, testrace commented on src/main/java/racing/Winners.java
> +    public String toString() {
이펙티브 자바에선 toString을 디버깅 등의 용도로 항상 재정의하라고 제안하는데요
호민님은 어떤 경우에 toString을 재정의 하시는지 궁금합니다

2024-03-12 23:17 UTC, testrace commented on src/test/java/racing/CarsTest.java
> +    @DisplayName("우승자가 한 명인 경우 우승자 목록 조회")
CarsTest 내부의 일부 코드가 컴파일이 되지 않네요 😢 
<img width="572" alt="image" src="https://github.com/next-step/java-racingcar/assets/8064743/104af14f-568a-4924-bbb8-fd24e0a93d26">

사소하게 테스트가 실패할 수는 있어도 컴파일 에러가 있는 코드는 반드시 수정이 필요하다 생각합니다
커밋 이전에 모든 테스트를 수행해 보시면 좋을 것 같아요

2024-03-12 23:17 UTC, testrace commented on src/test/java/racing/NameTest.java
> +        String exceptionName = "a".repeat(MAX_CAR_NAME_LENGTH + 1);
요구사항이 변경되지 않았음에도 의도치 않게 MAX_CAR_NAME_LENGTH 값이 변경된다면 테스트가 실패하면서 인지할 수 있어야 하는데요
프로덕션 코드의 상수를 활용한다면 상수 값이 변경되더라도 통과할 수 있기 때문에 의도치 않은 변경을 감지할 수가 없습니다
테스트 코드에서는 프로덕션의 상수를 참조하지 않고 하드코딩하면 어떨까요?

2024-03-12 23:38 UTC, nimohLee commented on src/main/java/racing/Winners.java
> +    public String toString() {
원래는 Winners 내부 리스트 목록을 출력하는 winnersToString 같은 메서드를 만들려고 했습니다. toString() 과 다를 바가 없다고 생각하여 toString을 재정의하는 것을 선택했습니다. toString을 재정의하면 클라이언트 코드에서 일일히 메서드를 호출해주지 않아도 되는 이점도 있고, 어차피 기본 인스턴스 주소를 출력할 일은 없다고 생각했습니다.

2024-03-12 23:39 UTC, nimohLee commented on src/main/java/racing/Winners.java
> +    public String toString() {
이펙티브 자바 매번 아이템 5까지만 읽고 포기했었는데 이번 기회에 다시 시도 해봐야겠네요..!

2024-03-13 00:00 UTC, nimohLee commented on src/test/java/racing/NameTest.java
> +        String exceptionName = "a".repeat(MAX_CAR_NAME_LENGTH + 1);
좋은 의견 감사합니다!

저는 좋은 단위테스트의 특징인 FIRST에서 Repeatable을 생각하고 항상 성공하도록 작성한 것인데요.

리팩터링할 때만 테스트가 항상 성공해야하고, 요구사항 변경이나 의도치 않은 변경의 경우에는 오히려 테스트가 실패하도록 하는 건가요?

저는 상수를 의도적으로 변경했을 때 테스트 코드를 다시 바꾸는 것이 안 좋다고 생각했었습니다.

2024-03-13 10:27 UTC, nimohLee commented on src/main/java/racing/Race.java
>          while (currentTryCount < tryCount) {
이 부분이 감이 안 잡히네요.. TryCount를 불변 값 객체로 두는 걸 말씀하시는건가요?

2024-03-13 11:32 UTC, testrace commented on src/main/java/racing/Race.java
>          while (currentTryCount < tryCount) {
불변객체를 의도해서 코멘트 드린건 아니었구요
시도 횟수를 직접 조작하기 보다 객체에게 메시지를 보내는 방식을 의도해서 코멘트 드렸어요
```java
TryCount tryCount = new TryCount(count);
while(tryCount.hasLeft()) {
...
}
```
이런 것까지 객체로 만드나 싶기도 하시겠지만 학습 과정이니 최대한 경험을 해보셨으면 하는 마음입니다.

2024-03-14 09:50 UTC, testrace approved these changes
안녕하세요 호민님 😃 
피드백 반영 잘해주셨네요 👍 
정적 팩토리 메서드도 잘 활용해주셨습니다!
마지막 단계로 넘어가시죠 🔥

2024-03-14 09:50 UTC, testrace commented on src/main/java/racing/TryCount.java
> +public class TryCount {
객체 도출 👍

2024-03-14 09:50 UTC, testrace commented on src/test/java/racing/TryCountTest.java
> +        assertThat(tryCount.hasLeft()).isTrue();
꼼꼼한 테스트 까지 💯

2024-03-14 09:50 UTC, testrace commented on src/test/java/racing/TryCountTest.java
> +        TryCount tryCount = TryCount.from(1);
클래스명에서 수와 관련된 객체임을 알 수 있으니 from 대신 valueOf 도 좋을 것 같아요 😃

2024-03-14 09:50 UTC, merged