feat: 문자열 계산기 요구사항 구현
next-step/java-racingcar pull request #5379
Opened 2024-03-11 15:14 UTC by ZhenxiKim

문자열 계산기 PR요청드립니다. 첫번째 미션 리뷰주신 내용은 step1 브랜치에서 수정하도록 하겠습니다.

이번 미션은 하나의 메서드는 하나의 일만 수행하도록 쪼겠습니다. 제일 어려웠던 부분은 메서드명 짓기였습니다~

2024-03-12 11:45 UTC, mskangg requested changes
2단계 미션도 잘 구현해주셨네요~!
다만, 요구사항을 잘못 이해하신것 같아 코멘트 드렸습니다!
확인 부탁드립니다 🙇

2024-03-12 11:45 UTC, mskangg commented on StringAddCalculatorTestTodo.md
> +- [x] 음수를 전달할 경우 RuntimeException 예외가 발생해야 한다. (예 : “-1,2,3”)
체크리스트 👍

2024-03-12 11:45 UTC, mskangg commented on src/test/java/StringAddCalculatorTest.java
> +    @EmptySource
`@NullAndEmptySource` 으로 합칠수 있어용 😄

2024-03-12 11:45 UTC, mskangg commented on src/main/java/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(str);
Pattern.compile 의 구현부를 살펴보시면 항상 인스턴스를 새롭게 생성하고 있어요!
이런 경우 static 으로 선언하는 것이 좋습니다 :)

2024-03-12 11:45 UTC, mskangg commented on src/main/java/StringAddCalculator.java
> +        return sum(split(str, extractSeperator(str)));
str 이라는 변수가 4번이나 들어가는군요..!
메모리를 재활용하는 방식으로 구현하신것 같은데, 이런 경우 새롭게 변수를 재할당하는 것이 가독성이 좋을 수 있어요!

그리고 선언된 값을 중간에 값을 변경하거나 재활용하는 방식은 안티패턴으로 보기도 합니다!

ex)

```java
String a = "a";
if(any) {
  a = "b"
}
return a;
```

위와 같은 코드는

```java
if(any) {
  return "b"
}
return "a";
```

로 리팩토링될 수 있습니다.

splitAndSum 메서드를 리팩토링해보자면,

```suggestion
        String formattedStr = formattingStr(str);
        String seperator = extractSeperator(str);
        return sum(split(formattedStr, seperator));
```

이렇게 할 수 있을것 같은데, 이런 방식으로 구현해보시는건 어떠신가용??

2024-03-12 11:45 UTC, mskangg commented on src/main/java/StringAddCalculator.java
> +        }
구현부를 살펴보니,

validationNumber 시 숫자가 아니면 0으로 판단하여 처리하고 있네요!
원하는 결과는 나오곘지만, 구분자와 상관없이 값을 구하는 로직으로 처리되고 있어 요구사항과 맞지 않습니다.

예를 들어 입력값이 `//!\n1[2&3` 이라면 커스텀 구분자인 `!`로 숫자를 추출해야하는데, 숫자가 아닌 다른값들이 있으니 `RuntimeException` 을 발생시켜야 하고 `//!\n12!3` 로 입력된다면 `15` 가 나와야하는데, 6이 나올것 같을것 같아요!

이런 다양한 상황을 테스트케이스를 추가하여 검증해보시는것 추천드립니다!

이부분은 다시한번 확인 부탁드립니다! 🙇

2024-03-19 13:06 UTC, ZhenxiKim commented on src/main/java/StringAddCalculator.java
> +        return sum(split(str, extractSeperator(str)));
하나의 변수를 계속 재활용 하면 어디서 변경되었는지 추적하기 힘들겠군요!

2024-03-19 13:48 UTC, ZhenxiKim commented
리뷰 반영 완료했습니다. 확인 부탁드립니다~ @mskangg

2024-03-24 08:32 UTC, mskangg approved these changes
step2 완료되기전에 step3 를 요청해서 nextstep 리뷰페이지에 이게 빠져있어서 확인을 못했네요 😅
피드백 반영 잘해주셨습니다~! 👏

2024-03-24 08:32 UTC, mskangg commented on src/main/java/StringAddCalculator.java
> +    private static final Pattern PATTERN = Pattern.compile("\\/\\/(.)\\\\n(.*)");
👍

2024-03-24 08:32 UTC, merged