[STEP 3] 자동차 경주 (kylekim2123, 김영주)
next-step/java-racingcar pull request #5389
Opened 2024-03-11 20:11 UTC by kylekim2123

### PR 개요
- "step 3 자동차 경주"에 대한 수행 내용을 제출합니다.
- 최대한 테스트 코드를 먼저 작성 후 기능을 구현하려고 노력했습니다. 하지만 아직은 많이 어려움 겪고 있습니다.
---

### 기능 요구사항
1. 사용자는 자동차 대수를 입력할 수 있다.
    - [x]  자동차 대수를 입력받는다.
    - [x]  자동차 대수가 정수 형태가 아닌 경우 예외를 던진다.
    - [x]  자동차 대수가 0이하의 숫자인 경우 예외를 던진다.
2. 사용자는 시도 횟수를 입력할 수 있다.
    - [x]  시도 횟수를 입력받는다.
    - [x]  시도 횟수가 정수 형태가 아닌 경우 예외를 던진다.
    - [x]  시도 횟수가 0이하의 숫자인 경우 예외를 던진다.
3. 매 시도마다 각 자동차는 0에서 9사이의 난수를 받아, 전진하거나 전진하지 않는다.
    - [x]  0에서 9사이의 난수를 생성한다.
    - [x]  난수가 0이상 3이하인 경우, 자동차는 전진하지 않는다.
    - [x]  난수가 4이상 9이하인 경우, 자동차는 전진한다.
4. 사용자는 자동차 경주의 과정을 볼 수 있다.
    - [x]  자동차 경주의 과정을 출력한다.

---

### 설계
![image](https://github.com/next-step/java-racingcar/assets/49775540/79b2014b-4b69-429f-be85-664ad23488a8)
1. **RacingCarApplication**
    - **필드**
        - 없음
    - **메서드**
        - `void main()`
            - 사용자 입출력 관련한 구현체를 생성 및 주입한다.
            - 자동차 경주를 실행한다.

2. **RacingGame**
   > 자동차 경주 프로그램에서 컨트롤러 역할을 담당한다.
    - **필드**
        - `InputView inputView` : 사용자 입력 객체
        - `OutputView outputView` : 사용자 출력 객체
    - **메서드**
        - `void play()`
            - 사용자 입출력 관련 메서드를 호출한다.
            - 레이스 객체를 생성하고 실제 레이스를 진행한다.

3. **Car**
   > 자동차에 해당하는 도메인 객체이다.
    - **필드**
        - `int number` : 자동차 번호
        - `int position` : 자동차 현재 위치
        - 자동차 번호가 0이하의 수라면 IllegalArgumentException을 던진다.
    - **메서드**
        - `int number()` : 자동차 번호를 반환한다.
        - `int position()` : 자동차 위치를 반환한다.
        - `void moveForwardOrStop()` : 조건에 따라 자동차가 전진하거나 전진하지 않는다.
            - 조건수가 0~3이면 전진하지 않고 위치를 유지한다.
            - 조건수가 4~9이면 전진한다. (위치를 +1 한다.)
            - 조건수가 0 미만이거나 9 초과라면 IllegalArgumentException을 던진다.
        - `Car from()` : 자동차 번호를 받아 Car 객체를 생성하는 정적 팩토리 메서드이다.

4. **Race**
   > 경주에 해당하는 도메인 객체이다.
    - **필드**
        - `List<Car> cars` : 경주에 참여하는 자동차 객체 리스트
        - `int playingCount` : 시도 횟수
        - `List<RoundResult> roundResults` : 라운드 결과들의 모임 리스트
    - **메서드**
        - `void run()` : playingCount 수 만큼의 라운드를 진행한다.
        - `GameResult result()` : 경기 결과를 GameResult 객체로 변환하여 반환한다.
        - `Race setUp()` : 경주 객체를 초기화 및 생성한다.
            - 자동차 대수가 0이하면 IllegalArgumentException을 던진다.
            - 시도 횟수가 0이하면 IllegalArgumentException을 던진다.
            - 자동차 대수에 따라 Car 객체 리스트를 생성한다.
            - Race 객체를 생성하는 정적 팩토리 메서드이다.

5. **RandomNumberGenerator**
   > 자동차 전진 여부에 해당하는 난수를 생성한다.
    - **필드**
        - 없음
    - **메서드**
        - `int generateRandomNumberBetweenZeroAndNine()` : 0~9의 난수를 생성한다.

6. **vo**
    - CarResult : 자동차 1대의 번호와 위치를 가지는 DTO
    - RoundResult : 1개의 라운드의 모든 자동차들의 정보(= CarResult)를 가지는 DTO
    - GameResult : 게임 전체 라운드의 모든 정보(= RoundResult)를 가지는 DTO

7. **view**
    - InputView : 사용자 입력 인터페이스
        - 입력 받은 숫자가 정수 형태가 아니면 NumberFormatException을 던진다.
    - OutputView : 사용자 출력 인터페이스
    - ConsoleInputView : 콘솔 전용 입력 구현체
    - ConsoleOutputView : 콘솔 전용 출력 구현체

---

항상 감사드립니다. :)

2024-03-11 20:28 UTC, kylekim2123 reviewed
항상 정성스러운 리뷰 감사드립니다. 이번에도 궁금한 부분에 대해 따로 남겼습니다!

2024-03-11 20:28 UTC, kylekim2123 commented on src/main/java/calculator/Operand.java
> +import static java.text.MessageFormat.format;
- [이전 리뷰](https://github.com/next-step/java-racingcar/pull/5281/files#r1515779564)
- 와일드 카드를 사용하지 않고, import 문을 풀어서 쓰도록 설정을 변경했습니다.

2024-03-11 20:28 UTC, kylekim2123 commented on src/main/java/calculator/StringAddCalculator.java
> +    private static final int EXPRESSION_INDEX = 2;
- [이전 리뷰1](https://github.com/next-step/java-racingcar/pull/5281/files#r1515804687)
- [이전 리뷰2](https://github.com/next-step/java-racingcar/pull/5281/files#r1515805231)
- 재사용 가능한 Pattern 객체와 매직넘버들을 상수 처리 하였습니다.

2024-03-11 20:28 UTC, kylekim2123 commented on src/test/java/calculator/OperandTest.java
> +}
- [이전 리뷰](https://github.com/next-step/java-racingcar/pull/5281/files#r1515830053)
- 새로 만든 Operand 클래스에 대한 테스트 코드 추가하였습니다.

2024-03-11 20:28 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Car.java
> +    }
Random 이라는 외부 라이브러리에 대한 의존성을 없애기 위해서, 바깥에서 난수를 정하고 매개변수로 주입하는 방식을 택했습니다.
그러다보니 조건에 따라 행위가 달라져서, 메서드가 moveForwardOrStop 과 같은 형식으로 뭔가 두 가지 일을 하는 듯한 느낌이 들고 있습니다.
그래서 이걸 외부에서 조건문으로 나눠서 3이하면 stop을 호출하고, 4이상이면 moveForward()를 호출하는 방식으로 해볼까도 생각했으나, 뭔가 이는 자동차가 스스로 판단하는 도메인 로직이라고 생각해서 현재와 같은 방식으로 진행했습니다.
어떤 방식이 더 바람직한지 아니면 다른 방법이 있을지 리뷰어님 의견 듣고 싶습니다!

2024-03-11 20:28 UTC, kylekim2123 commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    private static final int TEN = 10;
뭔가 의미가 없이 단순히 숫자의 이름으로 매직넘버를 상수처리 하는 것도 의미가 있는지? 궁금합니다 ㅎㅎ
10이나 TEN이나 비슷하지 않나라고 생각이 들기도 하는데요! 무조건 상수처리를 하는게 좋을까요?

2024-03-12 09:08 UTC, catsbi requested changes
영주님 3단계 자동차 경주 미션 잘 구현해주셨어요!. 
코드 여기저기서 고민을 많이 하고 구현하신게 보이네요 ㅎㅎ
저도 재밌게 봤습니다. 추가적으로 몇가지 피드백 남겼으니 확인 후 다시 리뷰요청 부탁드려요!

2024-03-12 09:08 UTC, catsbi commented on src/main/java/racingcar/domain/Car.java
> +    }
위 질문과 연계해 답변을 드리겠습니다. 

임의의 값을 외부에서 주입받도록 하는건 좋습니다! 
그런데 자동차마다 전진조건이 달라질 경우(4가 아니라 5부터 이동한다던가... 범위가 0~9가 아니라 -10 에서 30이라던가...)
자동차 객체에서 직접 대응이 힘들 것으로 보여요. 여기서 전략패턴을 활용해보면 어떨까 싶네요!

그럼 다음과 같이 작성할 수 있고 추상화를 통해 자동차 자체에서 4이상이든 3이하든 숫자가 뭘 제공하는지에 대해 궁금할 필요 없이 결과만 확인하면 될 것 같아요. 

```java
public void moveForwardOrStop(MovableStrategy strategy) {
        if (strategy.movable()) {
            move();
        }
    }
```
그럼 해당 자동차에서는 구체적으로 어떤 조건에 움직이는지에 대해 알 필요가 없고, OCP, DIP, LSP 원칙 모두 만족하는 구조로 작성할 수 있을 것 같네요!

2024-03-12 09:08 UTC, catsbi commented on src/main/java/racingcar/domain/Race.java
> +    private final List<Car> cars;
Collection 타입은 필드 초기화를 해주면 null safe한 설계가 가능합니다 ㅎㅎ

2024-03-12 09:08 UTC, catsbi commented on src/main/java/racingcar/domain/Race.java
> +    public static Race setUp(final int carCount, final int playingCount) {
setUp이라는 함수명은 인스턴스의 값을 설정하는 걸 기대할 수 있는 함수명으로보이는데 실제로는 정적 팩토리 함수네요! 
정적 팩토리 메서드 패턴에서 사용되는 네이밍 관례들이 있는데 살펴보면 좋을 것 같아요!

2024-03-12 09:08 UTC, catsbi commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    private static final int TEN = 10;
TEN으로 하면 무의미해보일 수 있는지 NUMBER_MAX_LIMIT 이런식으로 네이밍이 된다면 의미가 좀 더 명확해지니 의미있을 수 있죠!

2024-03-12 09:08 UTC, catsbi commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +public final class RandomNumberGenerator {
해당 객체를 사용하는건 너무 구체화에 의존하는것 같아요. 좀 더 확장성있게 사용할 수 없을까요? 
generate() 함수를 정의한 interface NumberGenerator  인터페이스와 
이를 구현한 RandomNumberGenerator 구현체가 있다면 사용하는 측에서도 특정 구현체가 아닌 인터페이스에 의존할 수 있지 않을까요!

2024-03-12 09:08 UTC, catsbi commented on src/test/java/racingcar/domain/RaceTest.java
> +    @DisplayName("Race 객체 생성 시, 0 혹은 음의 정수의 레이싱 시도 횟수를 전달하면 IllegalArgumentException을 던진다.")
특정 구현체 예외를 작성해버리면 해당 주석도 로직에 종속되버리는 문제가 생겨요 그냥 예외라고만 해도 충분할 것 같습니다!

2024-03-14 12:35 UTC, kylekim2123 reviewed
리뷰 감사드립니다!!!

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/controller/RacingGame.java
> +        } catch (final Exception e) {
[반영] [aec8516](https://github.com/next-step/java-racingcar/pull/5389/commits/aec85160c41be5d7af2f916aceba2122fd72766e)
- 아무래도 Exception으로 포괄적으로 잡으면, 각 상황별 예외처리가 힘들 것 같습니다. 지금은 단순히 예외 메시지만을 출력하고 있기 때문에, 큰 문제는 없을 것으로 생각되지만 예외처리가 다양해지면 지금과 같은 방법으로 처리 하기는 어렵다고 생각합니다.
- 그래서 비즈니스 로직에 대한 예외는 각각의 메시지를 출력하고, 그 외의 예외에 대해서는 서버 에러 메시지로 출력되도록 변경했습니다.

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Race.java
> +    private final List<Car> cars;
해당 부분은 리뷰어님과 논의를 해보고 싶습니다!
현재 필드를 모두 final로 설정하여 생성자 초기화를 강제하고 있는데, 그럼에도 불구하고 final을 제거하고 빈 리스트로 필드 초기화를 해주는 것이 더 좋은 방법일까요?

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/controller/RacingGame.java
> +    private static final String PLAYING_COUNT_INPUT_MESSAGE = "시도할 회수는 몇 회 인가요?";
[반영] [aec8516](https://github.com/next-step/java-racingcar/pull/5389/commits/aec85160c41be5d7af2f916aceba2122fd72766e)
- RacingScreen에 해당 메시지를 이관하여 관리하도록 변경했습니다.

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/controller/RacingGame.java
> +            outputView.printOneLine(race.result().toString());
[반영] [aec8516](https://github.com/next-step/java-racingcar/pull/5389/commits/aec85160c41be5d7af2f916aceba2122fd72766e)
- RacingGame : 도메인 객체 Race를 생성 및 호출하여 비즈니스 로직을 전개하는 컨트롤러
- RaceScreen : 비즈니스 로직 전개에 필요한 사용자 입출력을 담당하는 뷰

이렇게 두 역할로 책임을 분리해서 객체를 만들어 보았습니다. RacingGame을 생성할 때 RaceScreen 객체를 주입하는 방식을 택했습니다.

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Car.java
> +    }
[반영] [05fd98f](https://github.com/next-step/java-racingcar/pull/5389/commits/05fd98fdff3050d5416ce496a0047f5a8a8b57b2)
- Car에서 전진 조건에 따라 판별하는 로직을 모두 제거했습니다.
- CarMovement 객체를 만들어서, 해당 객체에서 Car의 전진 조건을 판별합니다.
- CarMovement에는 MovingStrategy와 NumberGenerator를 composition으로 넣어주고 있습니다. 그리고 전진 여부에 대해 (1) 조건수를 생성하고, (2) 조건수가 전진조건에 맞는지 판별 하여 Car에게 그 결과를 돌려줍니다.
- MovingStrategy와 NumberGenerator는 각각 상위 추상화 타입으로써, 추후 요구사항이 변경되면 구현체를 다르게 넣어주기 위해 이렇게 설계했습니다.

말씀하신 전략 패턴이 이런식으로 하는 것인지 사실 아직도 많이 헷갈립니다 ㅎㅎ
가감 없는 피드백 부탁드립니다!!

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Car.java
> +    public static Car from(final int number) {
[반영] [a161bde](https://github.com/next-step/java-racingcar/pull/5389/commits/a161bde4553d539c96ee987ed167dbe2ff3ad1d0)
- 말씀하신대로 from, of와 같은 정적 팩토리 메서드를 모두 제거하고 new를 이용해 생성하도록 변경했습니다!

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Race.java
> +    public static Race setUp(final int carCount, final int playingCount) {
정적 팩토리 메서드가 모두 삭제된 관계로, 해당 setUp도 삭제되었습니다.
말씀하시는 네이밍 관례가 from, of와 같은 것일거라 예상하는데, 다음부터는 관례 잘 지켜서 작성해보도록 하겠습니다.

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +public final class RandomNumberGenerator {
[반영] [d7de9c9](https://github.com/next-step/java-racingcar/pull/5389/commits/d7de9c985a6ce6e7ae18155003b15f4f2e393194)
- NumberGenerator라는 상위 인터페이스 타입을 선언하고, 상위 타입으로 의존성을 주입받도록 변경했습니다.

2024-03-14 12:35 UTC, kylekim2123 commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +    private static final int TEN = 10;
[반영] [d7de9c9](https://github.com/next-step/java-racingcar/pull/5389/commits/d7de9c985a6ce6e7ae18155003b15f4f2e393194)
- 생각해보니 의미를 더 명확하게 해볼 생각을 못했었네요! 다른 클래스들의 상수도 최대한 의미 부여를 해서 다시 작성했습니다. 감사합니다!

2024-03-14 12:35 UTC, kylekim2123 commented on src/test/java/racingcar/domain/RaceTest.java
> +    @DisplayName("Race 객체 생성 시, 0 혹은 음의 정수의 레이싱 시도 횟수를 전달하면 IllegalArgumentException을 던진다.")
[반영] [0aec488](https://github.com/next-step/java-racingcar/pull/5389/commits/0aec488c890f904e8669739ca2e49ed0a6d7ecbb)
- 말씀하신대로 DisplayName과 테스트메서드 명에서도 모두 특정 예외에 대한 언급을 제거했습니다.

2024-03-14 12:42 UTC, kylekim2123 commented on src/main/java/racingcar/domain/Race.java
> +        final CarMovement carMovement = new CarMovement(new BasicMovingStrategy(), new RandomNumberGenerator());
@catsbi 
가장 많이 고민했던 부분입니다.
물론 지금 요구사항에는 사용자가 어떤 이동 전략을 사용할 것인지, 조건수를 생성하는 전략은 어떤걸 사용할 것인지 정하지 않기 때문에, 제가 임의로 코드에서 정하고 있긴 합니다ㅎㅎ

이걸 애초에 RacingCarApplication.java 단에서부터 생성해서 생성자 주입으로 쭉 넘겨주는 것이 좋을지, 아니면 지금과 같은 방식으로 하는게 좋을지 너무 고민이었습니다.

추가적으로 Config 클래스 같은 것을 하나 생성해서, 일종의 싱글톤 컨테이너를 따로 구현해서 사용하는 방법에 대해서는 어떻게 생각하시는지 궁금합니다!

2024-03-15 12:10 UTC, catsbi approved these changes
영주님, 3단계 피드백 반영 너무 잘 해주셨어요 👍 

추가적으로 피드백 남겨드렸는데 다음 미션에서 같이 고민해보면 좋을 것 같아요. 
그리고 현재 테스트가 부족한 부분들이 보여요. 가장 핵심인 Race의 run함수도 테스트가 안되고 있는 것 같아요. 그리고 전략 구현체들에 대한 테스트도 있으면 좋겠네요 ㅎㅎ

2024-03-15 12:10 UTC, catsbi commented on src/main/java/racingcar/domain/Race.java
> +        final CarMovement carMovement = new CarMovement(new BasicMovingStrategy(), new RandomNumberGenerator());
좋은 고민이에요 👍 
이처럼 여기서 구현체에대한 생성책임을 다 가지고 있으면 SOLID원칙중 OCP, DIP를 위배하게 되죠. 
즉, 앞으로 여러 전략을 유연하게 변경하고, 다양한 조건으로 경주를 하기가 어려워진다는 의미가 되기도 하는데요. 

config를 활용해 의존성을 책임지는 부분을 분리하는건 좋은 생각인 것 같아요. ㅎㅎ 
Spring의 DI와IOC에 대해 참고해서 설계해보셔도 좋을 것 같네요!

2024-03-15 12:10 UTC, catsbi commented on src/main/java/racingcar/domain/movement/RandomNumberGenerator.java
> +    private static final Random random = new Random();
Random보다는 ThreadLocalRandom을 권장드립니다. [참고](https://velog.io/@sojukang/Random-%EB%8C%80%EC%8B%A0-ThreadLocalRandom%EC%9D%84-%EC%8D%A8%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-03-15 12:10 UTC, catsbi commented on src/test/java/racingcar/domain/movement/BasicMovingStrategyTest.java
> +    @ValueSource(ints = {4, 9})
3일때 false를 반환하는지도 케이스가 있으면 어떨까요? 경계값 테스트를 좀 더 채울 수 있을 것 같아요

2024-03-15 12:10 UTC, catsbi commented on src/test/java/racingcar/domain/movement/BasicMovingStrategyTest.java
> +                .hasMessageContaining("자동차의 전진/정지 조건은 0이상 9이하의 자연수만 가능합니다.");
이 예외 메세지는 휴먼에러 발생 확률이 크고, 프로덕션의 메세지와 동기화 이슈도 있어서, 상수로 지정해서 검증하는걸 권장드립니다

2024-03-15 12:10 UTC, catsbi commented on src/main/java/racingcar/domain/Race.java
> +        this.cars = readyCars(carCount);
생성자에 값 할당이나 정말 간단한 변환식정도가 아니라면, 정적 팩토리 메서드 패턴을 권장드려요 ㅎㅎ

2024-03-15 12:10 UTC, catsbi commented on src/main/java/racingcar/domain/Race.java
> +    private static List<Car> readyCars(final int carCount) {
생성자 호출시 같이 호출되는 함수로 보여요. 생성자 테스트시 해당 로직도 같이 신경쓰며 분기 테스트가 진행되야해서 까다로워보이네요 ㅠㅠ

2024-03-15 12:12 UTC, merged