[Step4] 자동차 경주(우승자)
next-step/java-racingcar pull request #5390
Opened 2024-03-11 20:16 UTC by NaayoungKwon

### Description
- Step3에서 리뷰해주신 부분 반영했습니다.
- 이번에는 Test를 먼저 러프하게 작성한 다음, 구현을 진행해봤습니다.
- indent depth를 최대 1까지만 하려니 우승자를 확인하는 부분에서 리팩토링하기가 쉽지않아 stream을 사용했습니다. 🥹

2024-03-12 15:38 UTC, dhmin5693 requested changes
안녕하세요~

전반적으로 잘 해주셨는데 조금만 수정해주시면 좋을 것 같아 수정 요청 한 번 드려봅니다.
남긴 피드백 참고해주세요.

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/Main.java
>    public static void main(String[] args) {
> 함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.

main 메소드가 조금 깁니다. 다른 메소드로 역할을 나눠보세요.

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/Main.java
> +  }
> 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.

이름에 대한 validation의 책임은 `Car`나 `Name`을 만들어서 부여하는건 어떨까요?
StringUtil.checkLength는 "입력은 %d 이하여야 합니다" 라는 메시지를 출력하지만 요구사항을 읽어보면 "5자를 초과하여 입력할 수 없다"보다는 차 이름의 길이에 제약을 부여하고 있습니다.

이름을 받자마자 검증해도 됩나다만 더 적절한 도메인으로 옮기는 데에서 오는 장점도 큽니다 :)

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/game/generator/IntGenerator.java
> +  int nextInt(int bound);
매개변수로 bound가 쓰이고 있네요. bound는 경계값을 의미합니다.
구현체를 미리 정해두고 인터페이스가 설계된 것 같습니다.

객체지향의 5대원칙 중 DIP에서는 "추상화(인터페이스)로부터 세부 사항(구현체)이 나와야 하며 거꾸로 추상화가 세부사항을 의존한다면 객체지향의 관점에서 잘못된 설계"라고 정의합니다.

인터페이스를 다시 설계해보세요.

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
`List<Car>` 를 하나의 책임으로 묶는다면 이 메소드를 더 적당한 위치로 옮길 수 있지 않을까요?

[일급 컬렉션](https://jojoldu.tistory.com/412) 을 고려해보세요.

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
메소드의 반환값은 `List<String>` 이 의도를 더 명확하게 만들어 줄 수 있을 것 같고 for 내부엔 `String.format` 을 써보시는건 어떠신가요?

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/game/GameResult.java
> +  List<String> roundResults;
접근 제한자에 항상 주의해주세요 😢

2024-03-12 15:38 UTC, dhmin5693 commented on src/main/java/racingCar/game/GameResult.java
> +  }
RacingCarGame의 playGames에서 `GameResult` 의 생성 시기를 조정하면 setter는 필요하지 않아요.

setter는 객체의 불변성을 잃어버리게 합니다.
불변 객체는 가변 객체 대비 상대적으로 디버깅이 쉬우며 사이드 이펙트로부터도 더 안전한 편입니다.
값이 고정되어 있기 때문에 보아야 할 지점이 적어 예측이 더 쉽기 때문입니다.

객체지향을 더 잘 구현하려면 최대한 불변 객체를 활용해보세요.
TDD 미션 중엔 setter를 아예 사용하지 않는다고 생각하시면 됩니다.

2024-03-12 15:38 UTC, dhmin5693 commented on src/test/java/racingCar/CarTest.java
> +  @DisplayName("차 인스턴스를 생성하면 이름이 있다")
"이름이 있다" 보다는 의도한 이름이 잘 저장되어있는지를 검증하는게 더 낫지 않을까요?

2024-03-13 14:55 UTC, NaayoungKwon commented on src/main/java/racingCar/game/generator/IntGenerator.java
> +  int nextInt(int bound);
IntGenerator.nextInt 메소드에 입력으로 넣는 bound가 이미 랜덤 값 중 최댓값을 정해둔다고 가정해서 그럴까요?
어떤 Generator이던 간에 최댓값은 생성 요청시를 기준으로 최댓값을 지정해둔다는 생각으로 매개변수를 지정 했었습니다.

DIP를 개념적으로 알면서도 컬렉션이 아닌 객체를 직접 구현하게 되면 실천을 잘 하지 못한 것 같네요..!
RandomGenerator 별로 최댓값이 다를 수도 있으니, 생성자에 파라미터로 넣도록 변경했습니다!
혹시 더 개선해야한다면 말해주세요 😊

2024-03-13 14:55 UTC, NaayoungKwon commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
한 라운드 별로 결과를 전달하기 위해 하나의 String으로 모아서 return 했습니다.
String.format 으로 수정했습니다!

2024-03-13 15:44 UTC, NaayoungKwon commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
코드를 다시보니 cars의 내부 원소들의 순서를 변경해버렸네요..

일급 컬렉션으로 힌트를 주셔서, 주신 링크를 포함해 학습했는데요,
하나의 컬렉션을 필드로 가지면서, 해당 컬렉션과 관련된 로직을 전부 일급 컬렉션에서 처리하도록 의존성을 뜯어내버린다고 이해하면될까요?

RacingCar라는 클래스를 새로 생성하고 cars를 필드로 두고, RacingCarGame에서 가지고 있던 의존성을 뜯어내다보니, 
이렇게하면 RacingCarGame에서는 자동차들을 움직이고, 위치를 가져오는 등의 로직이 주가 되었는데, RacingCar를 그냥 호출만 해버리는 것 처럼 되고있어서 제가 제대로 학습한건지 잘 모르겠네요 😂

2024-03-13 15:47 UTC, NaayoungKwon commented
안녕하세요. 리뷰어님!
꼼꼼하게 확인해주시고, 레퍼런스도 전달해주셔서 감사합니다.
주신 코멘트 들 중 👍  표시를 해 둔 것은 대체로 수정 반영을 했습니다.
그 외에 다른 코멘트들은 궁금한 점들이 더 있어 추가로 답글을 달아두었습니다.
편하실 때 확인해주시면, 이후에 좀 더 학습해보고 남은 부분 개선해보겠습니다~!

2024-03-14 14:11 UTC, dhmin5693 commented on src/main/java/racingCar/Main.java
>    }
winner message의 책임은 view 영역이 더 맞지 않을까요?

2024-03-14 14:11 UTC, dhmin5693 commented on src/main/java/racingCar/game/generator/IntGenerator.java
> +  int nextInt(int bound);
추상화의 원칙을 이해하셨다면 큰 문제 없습니다 👍 

말씀하신 대로 최대값을 다르게 정의하는 데에서 오는 장점이 있겠네요.
다만 이 미션의 특징 상 절대 바뀌지 않는 도메인 정보라 생각하여 이런 리뷰를 남겨두었어요.

2024-03-14 14:24 UTC, dhmin5693 approved these changes
반영 잘 해주셨네요 👍 
수고하셨습니다.
step5 진행해주세요.

2024-03-14 14:24 UTC, dhmin5693 commented on src/main/java/racingCar/game/generator/RandomGenerator.java
> +  }
DIP 원칙이 잘 지켜진 것 같습니다 😄

2024-03-14 14:24 UTC, dhmin5693 commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
초기화하는 형태의 메소드는 가급적 생성자에서 실행시켜 주시는게 좋습니다.

1. 생성자 자체의 목적이 생성 및 초기화입니다.
2. 이 코드를 여러 명이 관리하게 된다면, 누군가는 실수로 initiateGame 를 호출하지 않게 될 가능성이 있습니다.

2024-03-14 14:24 UTC, dhmin5693 commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
`RacingCarGame` 의 이름은 그대로고 일급 컬렉션이 되었군요.
`RacingCars`와 분리하시는건 어떤가요?

제가 말씀드렸던 일급 컬렉션은 컬렉션 데이터를 조금 더 잘 활용해보는게 목적이에요.
playGame이나 getGameResult처럼 출전한 car 모두에게 영향을 주는 메소드는 이 클래스의 책임입니다.

playGames는 라운드 정보를 알고 있고 그걸로 게임을 N번 반복하는데 일급 컬렉션의 책임까진 아닌 것 같아요.
round를 필드로 갖는 별개의 클래스로 옮겨보는건 어떤가요?

playGames는 매개변수로 통제가 되고 있는데요, 실생활에서 생각을 해보겠습니다.
자동차 경주 대회가 3월 14일에 열리고 그 날 3회의 round만 하게 됩니다.
`playGames(3)` 을 여러 번 호출하면 3회의 round를 호출한 만큼 수행하지 않을까요?
그럼 자동차는 3 round만을 돌아야 하지만 3 * (호출횟수) 만큼 진행하여 데이터가 꼬이는 문제가 발생할 수 있습니다.

2024-03-14 14:24 UTC, dhmin5693 commented on src/main/java/racingCar/game/RacingCarGame.java
> +  }
> 하나의 컬렉션을 필드로 가지면서, 해당 컬렉션과 관련된 로직을 전부 일급 컬렉션에서 처리하도록 의존성을 뜯어내버린다고 이해하면될까요?

넵 맞습니다 :)

일부 책임만 이동해주시면 더 좋을 것 같습니다.

2024-03-14 14:24 UTC, merged