Step4 자동차경주 리팩토링을 진행했습니다.
next-step/java-racingcar pull request #5401
Opened 2024-03-12 11:28 UTC by yuus95

## 작업 내용
자동차 경주 리팩토링 진행

## 회괴
요구사항이 변경 됐을 경우, 테스트코드가 모두 깨지는 이슈가 있는것 같습니다..
하나하나 수정하고 커밋을 해야하지만 모든 테스트코드가 깨져서 우선 한번에 다 고치고 커밋을 날리긴 했는데, 

요구사항이 변경됐을 때 테스트코드양이 많다면 하나 수정하는데도 엄청 오래 걸리겠다는 생각이 들었습니다. 

기존 구현되어 있던 로직을 수정하는 바람에 TDD를 하지 않고, 중간 로직을 만들다가 테스트코드를 작성하게 되는 경향이 있더라고요 아직 
미숙하다는 느낌이 들었던 과제였습니다.  언능 적응해야되겠습니다. 하하

2024-03-13 00:09 UTC, neojjc2 requested changes
안녕하세요 유신님 🙇 

4단계 구현 잘 해주셨네요 💯 
이전 단계에서 구조에 대한 개선을 잘 해주셔서 큰 수정없이 요구사항이 잘 반영된 것 같습니다.

조금만 정리되면 좋을 것 같아서 몇 가지 의견 드렸는데요,
보시고 개선검토 해주시면 감사하겠습니다 🙏 

그럼 재 리뷰요청 기다리고 있겠습니다 🙇

2024-03-13 00:09 UTC, neojjc2 commented on src/main/java/step3and4/car/CarFirstCollection.java
> +        return winPosition;
스트림 사용에 익숙하신 것 같네요 👍 
`max`를 사용하는 방법도 있을 것 같습니다 😄 이 부분은 참고만 부탁 드리겠습니다 🙏 
```java
return cars.stream()
            .mapToInt(Car::getPosition)
            .max()
            .orElse(0);
```

2024-03-13 00:09 UTC, neojjc2 commented on src/main/java/step3and4/car/CarFirstCollection.java
> +                .collect(Collectors.toList()).toArray(new String[0]);
굳이 `String array`를 사용하신 이유가 있을까요?? 🤔 
`array`는 섬세한 조작이 가능한 장점이 있습니다만, `index`를 알아야 하고 값을 추가하거나, 변경하는데 귀찮음도 있고 
경우에 따라서는 휴먼에러를 발생시킬 수 있는 잠재적인 문제가 있습니다.
이미 `List`로 잘 변환을 해주셨으니 그대로 사용하셔도 될 것 같아요 😄 

그리고 이미 `winPosition`을 잘 구해주셨는데 `compare`는 좀 불필요해보입니다.
물론 `compare`를 잘 구현해주시긴 했지만 좀 더 단순한 방법으로 승자를 구할 수 있을 것 같아요 🙇 

```java
return cars.stream()
            .filter(car -> car.getPosition() >= winPosition)
            .map(Car::getName)
            .collect(Collectors.toList());

```

2024-03-14 12:09 UTC, yuus95 reviewed
리뷰해주셔서 감사합니다!
리뷰내용 기반으로 코드를 수정했습니다!

코맨트 달아주신것처럼
생각해보니 리팩토링후 테스트코드가 터지는 것을 확인하여 어디 부분에 영향을 주는지 쉽게 확인할 수 있
겠네요 수정하면서 수정 범위를 확인할 수 있으니간요.

원시값 포장에 대한 의문점이 있어서 코멘트 하나 남겼습니다! 확인한번 부탁드립니다!

객체 지향적으로 설계하기 위해서는 객체 스스로가 책임을 질 수 있게 설계 해야 겠다는 생각이 듭니다. 
매번 유효성검증을 부모? 제일 상단의 도메인 클래스에서만 하고 있어서 코드가 길어졌는데 
책임을 분리하면 조금 더 깔끔 해질 것 같네요.

2024-03-14 12:09 UTC, yuus95 commented on src/main/java/step3and4/car/CarFirstCollection.java
> +                .collect(Collectors.toList()).toArray(new String[0]);
경우에 따라서 휴먼에러인경우는 배열에 추가할 경우를 의미할까요??
MaxInt를 이용하여 최댓값이랑 똑같은 자동차들을 반환하는걸로 기능을 수정했습니다!

List를 반환안했던 이유는 기존 사용하고 있는 변수들을 배열로반환하고 있어서 똑같이 맞출려고 했던 것 같습니다. 

List를 이용하여 표현할 수 있도록 수정하겠습니다!

2024-03-14 12:09 UTC, yuus95 commented on src/main/java/step3and4/car/CarFirstCollection.java
> +        return winPosition;
조금 더 명확하게 표현할 수 있는 방법이군요! 해당 내용 반영해서 수정하겠습니다!

2024-03-14 12:09 UTC, yuus95 commented on src/main/java/step3and4/car/CarFirstCollection.java
> +}
이부분은 비즈니스 로직을 잘못 짠 것 같습니다. ㅜ
테스트코드에서는 항상 성공해서 당연히 되는줄 알았는데, 놓친 테스트 케이스가 있는 것 같네요.. 
조금 더 확실한 테스트코드를 작성해야 할 것 같습니다 .

재수정해서 올리겠습니다!

2024-03-15 00:32 UTC, neojjc2 commented
@yuus95 유신님 추가 수정 완료 되시면 다시 리뷰요청 부탁 드리겠습니다 🙇

2024-03-18 00:24 UTC, neojjc2 approved these changes
안녕하세요 유신님 🙇 

요청사항 깔끔하게 반영해주셨네요 💯 
4단계 진행하시느라 정말 수고 많으셨습니다. 

어느덧 마지막 단계만 남았습니다. 
그간 잘 진행해주셔서 잘 정리만 해주시면 
무난하게 마무리 지을 수 있을 것 같네요 😄 

이만 `merge`하겠습니다 🙏

2024-03-18 00:24 UTC, neojjc2 commented on src/main/java/step3and4/Positive.java
> +    public boolean equalsNumber(int winPosition) {
비교의 역할을 위임하신 것 너무 좋네요 👍

2024-03-18 00:24 UTC, neojjc2 commented on src/main/java/step3and4/car/Car.java
> +    class Name {
잘 위임해주셨습니다 👍

2024-03-18 00:24 UTC, merged