Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5402
Opened 2024-03-12 12:29 UTC by sinterhoo

구조를 변경하는 데에 시간을 많이 사용했던 거 같습니다.

바꾸다보니 스프링 부트를 이용한 프로젝트랑 모습이 점점 비슷해지네요..!

공부할 내용은 쌓여 가는데 정리를 잘 못하고 있는 거 같아서 많이 정리해야겠습니다 정성의 리뷰 항상 감사합니다!!

---

궁금한점
- 자동차 경주 우승자를 결정하는 로직을 service에 작성했고, 내부에서만 사용하는 기능이다보니 private으로 설정했습니다. 그런데 이러면 단위테스트를 작성할 수 없다는 문제가 생겼는데.. 접근 제어를 public으로 바꾸는게 좋을까요? 아니면 우승자를 선정하는 로직 설계를 잘못한 걸까요?
- 그리고 최대한 리뷰를 반영하려고 했는데, 좀 더 개선할 점이 있을지 알고 싶습니다!

2024-03-13 14:29 UTC, ksy90101 requested changes
안녕하세요~ 벌써 4단계까지 왔네요!
4단계에서 전반적인 구조를 변경해주셨군요 MVC형태로.
고생 많으셨습니다~
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다!

질문이 있다면 언제든 DM주시면 이야기 나누면 좋을거 같아요~

2024-03-13 14:29 UTC, ksy90101 commented on src/main/java/step3/Car.java
> +    private String name;
name은 final로 불변으로 하는게 좋지 않을까요?

2024-03-14 14:35 UTC, sinterhoo commented on src/main/java/step3/Car.java
>      MoveStrategy moveStrategy;
실수한 거 같습니다! 수정했습니다.

2024-03-14 14:37 UTC, sinterhoo commented on src/main/java/step3/CarRacingService.java
> +    public RacingResultDto executeRacing(int attemptCount) {
원시값을 포장하는 건 추가적인 의미나 행동을 제공할 때 더 유효하다고 생각하는데요 attempCount에 음수값 검증 로직 외에 추가로 맡을 역할이 있을까요? 감이 잘 안오네요..
원시값 포장은 우선 Name에 적용했습니다..!

2024-03-14 14:37 UTC, sinterhoo commented on src/main/java/step3/CarRacingService.java
> +    }
위임하고 추가적으로 테스트코드 작성했습니다!

2024-03-15 10:16 UTC, ksy90101 approved these changes
고생하셧습니다~
이제 마지막 5단계이네요!
4단계는 이만 마무리 하고, 5단계에서 마지막으로 뵐꼐요~
간단한 답변들과 간단한 리뷰 남겼으니 참고해주세요~
언제든 질문이 있다면 DM으로 연락주세요!
고생하셨습니다!

2024-03-15 10:16 UTC, ksy90101 commented on src/main/java/step3/CarName.java
> +        }
차라리 이 부분을 validate함수로 뺴면 어떨까요?
그게 더 생성자 입장에서도 메서드 입장에서도 깔끔해 보여서요~

2024-03-15 10:16 UTC, ksy90101 commented on src/main/java/step3/Cars.java
> +        int maxDistance = cars.stream()
```suggestion
    public List<String> searchWinners() {
        int maxDistance = cars.stream()
```

2024-03-15 10:16 UTC, ksy90101 commented on src/main/java/step3/Cars.java
> +                .collect(Collectors.toList());
불변 컬렉션을 리턴하는게 어떨까요?

2024-03-15 10:16 UTC, ksy90101 commented on src/main/java/step3/Cars.java
> +                .filter(car -> car.getCurrentLocation() == maxDistance)
car.getCurrentLocation() == maxDistance

해당 부분도 car에게 메시지를 던져서 응답을 받으면 어떨까요?

2024-03-15 10:16 UTC, merged