[4단계 - 자동차 경주(우승자)] 실습 구현을 마쳤습니다.
next-step/java-racingcar pull request #5425
Opened 2024-03-13 14:35 UTC by kwanik-kor

## 1. 개요
[🚀 4단계 - 자동차 경주(우승자)](https://edu.nextstep.camp/s/E42ziiPQ/ls/kVBxCNYT)의 실습 내용을 구현하였습니다.

## 2. 작업내용
- [x] 3단계 학습 테스트 실습 리팩토링
- [x] 4단계 자동차 경주 기능 구현

---
항상 꼼꼼히 리뷰해주셔서 감사합니다🙏

2024-03-14 03:29 UTC, seondongpyo requested changes
4단계 미션도 잘 작성해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/domain/Car.java
> +public class Car {
이전 단계에서 `Car` 클래스에 대한 단위 테스트를 언급 드렸는데, 추가해보시면 어떨까요?
미션의 요구사항대로 핵심 비즈니스 로직을 갖는 도메인에 대해서는 단위 테스트를 꼭 작성하시길 부탁 드립니다.
`모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외`

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/domain/Car.java
> +    public static Car withName(String name) {
해당 정적 팩토리 메서드를 호출할 때, 전달 받은 자동차 이름의 길이가 5자를 넘게 되면 어떻게 될까요?

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/domain/Cars.java
> +import java.util.stream.IntStream;
사용하지 않는 패키지는 제거해주셔도 될 것 같습니다.

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/domain/Cars.java
> +    }
해당 public 메서드들에 대한 단위 테스트도 작성해보면 어떨까요?

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/view/result/CarMovementResult.java
> +    }
내부에서 별다른 처리를 하지 않는다면 생성자를 직접 호출해서 인스턴스를 생성해도 되지 않을까요?
인스턴스 생성 시 생성자 대신 정적 팩토리 메서드를 자주 사용하시는 이유가 있으신가요?

2024-03-14 03:29 UTC, seondongpyo commented on src/main/java/step4/view/result/CarMovementRoundResults.java
> +                : Optional.of(results.get(results.size() - 1));
삼항 연산자는 `if-else`의 축약형이기 때문에, `else 예약어를 쓰지 않는다.`는 요구사항을 위반하고 있습니다.
삼항 연산자를 사용하지 않고 작성해보시는 걸 권장 드립니다.

2024-03-17 05:38 UTC, kwanik-kor commented on src/main/java/step4/domain/Car.java
> +public class Car {
사실 차량의 움직임이 랜덤으로 움직이는 건에 대해서 어떻게 테스트코드를 작성해야할 지 고민이었는데, 목요일 라이브강의를 통해서 방법을 알게된 것 같습니다! 관련해서 반영하도록 하겠습니다!

2024-03-17 05:47 UTC, kwanik-kor commented on src/main/java/step4/domain/Car.java
> +    public static Car withName(String name) {
사실 Input에서만 검증을 했던 이유는 요구사항을 조금 다르게 해석했기 때문인 것 같습니다! 차량의 이름길이가 5글자 이하여야 하는 것은 언제든지 바뀔 수 있는 요구사항이니 Input에서만 검증을 하고 `자동차`라는 객체는 순수하게 그 값을 가질 수 있도록 구현해야겠다라고 생각했던 것 같아요! 선동님의 의견도 궁금합니다!

2024-03-17 05:55 UTC, kwanik-kor commented on src/main/java/step4/domain/Cars.java
> +    }
해당 public 메서드들은 Car의 move와 CarMovementRoundResultTest를 통해서 검증이 되고 있다고 생각합니다! 선동님은 어떻게 생각하시나요~?

2024-03-17 05:56 UTC, kwanik-kor commented on src/main/java/step4/view/result/CarMovementResult.java
> +    }
정적 팩토리 메서드의 경우 생성자에 명확한 의미를 부여해줄 수 있어서 즐겨쓰는 편인데, 말씀해주신 대로 기본 생성자와 동일하다면 굳이 정적팩토리 메서드를 쓰는 메리트가 있지 않을 것 같네요ㅠㅠ 수정하겠습니다!

2024-03-17 06:00 UTC, kwanik-kor commented
꼼꼼한 리뷰 감사합니다! 말씀해주신 사항들에 대해 수정 반영완료하였습니다!
수정 작업을 함에 있어서 궁금한사항들을 다시 커맨트로 남겼습니다!

2024-03-17 23:55 UTC, seondongpyo approved these changes
피드백 반영하시느라 고생하셨습니다.
추가로 몇 가지 의견 드렸는데 확인 부탁 드릴게요.
마지막 단계도 힘내시길 응원합니다 🔥

2024-03-17 23:55 UTC, seondongpyo commented on src/main/java/step4/domain/Car.java
> +    public static Car withName(String name) {
'자동차'의 이름과 관련된 요구사항이므로, 이름을 상태로 관리하는 주체인 `Car`에서 검증을 하는 게 맞지 않을까요?
오히려 반대로 `RacingInputView`에서는 순수하게 사용자로부터 값을 입력만 받고, 유효성 여부는 해당 값을 실제로 관리하는 곳에서 처리하는 걸 고민해보시면 좋을 것 같습니다.

2024-03-17 23:55 UTC, seondongpyo commented on src/main/java/step4/domain/Cars.java
> +    }
지금은 자동차의 이동에 대한 제약이 없기 때문에 각각의 `Car`가 `move()`를 호출하는 단순한 위임 구조이지만,
추후에 요구사항이 변경되어 `moveAll()`을 변경해야 한다면 `Car`의 `move()`에 대한 테스트만으로도 충분할지 한 번 고민해보시면 좋을 것 같아요.

2024-03-17 23:55 UTC, seondongpyo commented on src/test/java/step4/CarTest.java
> +        car.move(strategy);
- 자동차가 이동하지 않는 경우에 대한 케이스도 추가해보면 어떨까요?
- 람다를 활용해보면 어떨까요?
```suggestion
        car.move(() -> true);
```

2024-03-17 23:55 UTC, merged