4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5428
Opened 2024-03-13 15:09 UTC by kimsunghyun1995

2024-03-13 17:01 UTC, nooose requested changes
3단계 머지하면서 충돌이 많이 발생했네요 😨
3단계 피드백 반영하면서 같이 해결하면 될 것 같아요
재요청 부탁드립니다 🙇

2024-03-15 12:25 UTC, nooose requested changes
안녕하세요 성현님!
코멘트 남겼으니 읽어보시고 재요청 부탁드립니다. 🙇‍♂️

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/RacingCarGameLogic.java
> +        }
```suggestion
        for (String name: names) {
            cars.add(new Car(name, INIT_CAR_DISTANCE));
        }
```
enhanced for loop 문법을 사용하면
인덱스를 명시할 필요가 없어집니다.

인덱스가 필요한 게 아니라면 거의 사용하지 않는 것 같아요

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/RacingCarGameRule.java
>  public class RacingCarGameRule {
주로 개발을 할 때 도메인 모델을 뽑아낼 수 있음에도 불구하고 
서비스 또는 싱글톤 객체를 만드는 것 같아요 😢 

이것도 하나의 모델로 해석해 볼 수 없을까요?

메소드를 봤을 때 Car 리스트를 담당하는 클래스네요
이런 Car 컬렉션을 담당하는 `Cars` **일급컬렉션**을 한번 사용해보는 것이 어떨까요?

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +    private String name;
이름 길이에 대한 검증이 이뤄지지 않고 있습니다 😔

> 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +    }
이름이 만약 100글자, 거리가 음수인 Car가 생성되는 상황을 막아야하는데요
검증 로직이 생성자에 있다면 Car 객체가 생성될 때 유효한 Car임을 보장할 수 있게됩니다.

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +    }
관련한 테스트 코드도 있으면 좋겠습니다.

2024-03-15 12:25 UTC, nooose commented on src/test/java/car/RacingCarTest.java
> +        assertThat(winners.size()).isEqualTo(3);
```suggestion
        assertThat(winners).hasSize(3);
```

2024-03-15 12:25 UTC, nooose commented on src/test/java/car/RacingCarTest.java
> +        List<Car> cars = IntStream.range(0, 3).mapToObj(index -> new Car("test" + index, index)).collect(Collectors.toList());
```java
        List<Car> cars = List.of(
            new Car("test0", 0),
            new Car("test1", 1),
            new Car("test2", 2)
        );
```
위 상황은 충분히 객체를 만들어서 테스트 재료를 쉽게 구할 수 있어보여요
IntStream은 순차적으로 늘어나는 값을 처리할 때 사용하면 좋겠습니다.

2024-03-15 12:25 UTC, nooose commented on src/test/java/car/RacingCarTest.java
> +        assertThat(winners.get(0).getName()).isEqualTo("test2");
```suggestion
        assertThat(winners.get(0)).isEqualTo(new Car("test2", 2));
```
이렇게도 테스트하면 좋을 것 같은데 ...
고민해 보면 좋겠습니다! 😃

2024-03-15 12:25 UTC, nooose commented on src/test/java/car/RacingCarTest.java
> +        assertThat(winners.size()).isEqualTo(2);
```suggestion
        assertThat(winners).hasSize(2);
```

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/RacingCarGameLogic.java
> +            ResultView.getInstance().printLineBreak();
printMove 에서 개행을 처리하면 될 것 같아요
```suggestion
            ResultView.getInstance().printMove(cars);
```

2024-03-15 12:25 UTC, nooose commented on src/main/java/racingcar/model/Car.java
>          if(isMove) {
```suggestion
        if (isMove) {
```
> 단축키(Windows : Ctrl + Alt + L. Mac : ⌥ (Option) + ⌘ (Command) + L.)를 사용한다.

단축키를 이용해서 놓친 컨벤션을 바로 잡을 수 있습니다

2024-03-16 14:27 UTC, kimsunghyun1995 commented on src/main/java/racingcar/ui/InputView.java
> +        return scanner.next();
제가 생각하는 입력클래스는 단순 입력기능만 수행하는 역할로만 생각했었습니다!
프론트, 백단 중 어디에서 파싱하느냐 차이인 것 같은데,, 백단에서 파싱 작업을 수행하는게 더 맞는 역할로 생각되는데 어떻게 생각하시나요?

2024-03-16 14:27 UTC, kimsunghyun1995 commented on src/main/java/racingcar/ui/ResultView.java
> +        System.out.println(distanceView);
오 처음 알았네요! 감사합니다

2024-03-16 15:18 UTC, kimsunghyun1995 commented on src/main/java/racingcar/RacingCarGameRule.java
>  public class RacingCarGameRule {
네 말씀대로 cars에 대한 일급컬렉션을 사용하니, 도메인 중심으로 코드가 진행되는 것 같네요!
훨씬 깔끔해진 것 같습니다

2024-03-17 01:00 UTC, nooose commented on src/main/java/racingcar/ui/InputView.java
> +        return scanner.next();
그럼 `,` 아닌 `@` 로 분리요청이 들어왔을 때도 누군가는 변경해야하는데 
어느 쪽이 변경되어야 하는 게 맞을까요?

2024-03-17 01:22 UTC, nooose requested changes
피드백 잘 반영되었네요 👍
제 실수로 리뷰가 한 번에 올라가지 않았는데요 😅
리뷰 위에 있는 코멘트까지 읽어보시면 좋겠습니다.
재요청 부탁드립니다!

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +    private String name;
요구사항으로 봤을 때 이름은 변경되지 않으니 final을 붙여 불변을 유지하는 게 어떨까요?

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +        }
if와 예외를 던지는 것 까지 묶어서
하나의 메소드로 만들어보면 좋을 것 같아요
```java
check(name); // 예시 
```

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +        }
isCarName, isCarDistance 메소드가 너무 떨어져있는 것 같아요
호출하는 곳과 가까이 배치하는 게 좋습니다.

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +        }
만약 필드값이 계속 추가되면 생성자내에 검증로직이 추가될텐데..
복잡해질 것으로 예상됩니다.
name, distance를 CarName, Distance 같이 값 객체로 래핑해보면 어떨까요? 

객체 생성 자체만으로 유효한 값임을 보장할 수 있고 책임을 분리할 수 있습니다!

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +        return distance == car.distance && Objects.equals(name, car.name);
👍

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Cars.java
> +    }
테스트하기 위해서 isMovingForward을 public으로 열어뒀네요
이 방법도 테스트를 제어하기에는 좋은 방법 같지만 캡슐화를 깨뜨리는 행위 같아요

이 방법 대신 전략패턴을 사용해서 자동차에게 전략을 전달해보면 어떨까요?
프로덕션 코드에서는 랜덤전략, 테스트에서는 제어가 가능하도록 무조건 전진하는 전략을 선택할 수 있습니다.

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Cars.java
> +        return this.cars.stream().map(Car::getDistance).max(Integer::compareTo).orElseThrow(NoSuchElementException::new);
가로로 늘어지면 아주 조금 읽기 불편한 것 같아요
모든 사람이 코드를 볼 때 큰 화면에서 본다는 보장도 없구요
그래서 어느정도 구분을 짓고 개행을 넣어주면 좋겠습니다.
```suggestion
    private int getMaxDistance() {
        return this.cars.stream().map(Car::getDistance)
        .max(Integer::compareTo)
        .orElseThrow(() -> NoSuchElementException("메시지"));
```

예외에는 항상 메시지를 넣어주는 것이 좋습니다. 😄

2024-03-17 01:22 UTC, nooose commented on src/main/java/racingcar/model/Cars.java
> +                .filter(car -> car.isMaxDistance(maxDistance))
```suggestion
                .filter(car -> car.isSameDistance(maxDistance))
```
이게 좀 더 자연스럽지 않나요? ㅎㅎ

2024-03-17 01:28 UTC, kimsunghyun1995 commented on src/main/java/racingcar/ui/InputView.java
> +        return scanner.next();
음.. 생각해보니, 단순한 분리요청은 프론트에서 하는게 더 효율적인 것 같네요.

만약 지금처럼 한 개의 기호가 아닌 여러가지 기호를 이용한 분리요청 등 로직이 복잡하게 바뀐다면, 백단에서 처리해야 할 것 같다고 생각하는데,, 지금 프로젝트에서는 프론트가 더 좋을 것 같네요

2024-03-17 06:21 UTC, nooose requested changes
놓친 부분이 있는 것 같아 Request changes 했습니다. 
재요청 부탁드립니다 🙇

2024-03-17 14:51 UTC, nooose commented on src/main/java/racingcar/ui/InputView.java
> +        return scanner.next();
반대로 생각해보면 이해하기 쉬울 것 같아요
알파벳 목록 리스트를 A > B > C > D 이렇게 구분자(`>`)로 표시해야한다고 했을 때
도메인에서 `A > B > C > D` 으로 문자열을 만들어 응답하는 것이 맞을까요?

백은 데이터 그대로 [A, B, C, D]를 응답하고 프론트는 view 요구조건에 맞게 렌더링하는것이 맞을 것 같습니다.

2024-03-18 14:53 UTC, kimsunghyun1995 commented on src/main/java/racingcar/model/Cars.java
> +    }
좋은 의견 감사드립니다.
제 생각에는 isMovingForward에 대한 테스트는 굳이 필요 없었던 것 같기도 합니다.
왜냐하면, 해당 메소드를 사용하는 public 메소드인 move만 검증해도 충분했다고 생각됩니다,,

전략패턴을 사용하긴 했는데, 위 내용이 적용된다면(move만 검증) 큰 차이를 잘 모르겠습니다,,

2024-03-18 16:58 UTC, nooose approved these changes
성현님 피드백이 많았는데 잘 따라와 주셨네요
5단계에서 고민하면 좋을 내용도 같이 남겼으니
같이 반영하면 되겠네요 👍
수고하셨습니다.

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/Car.java
> +        return this.distance.getDistance();
디미터 법칙을 지킬 수 있겠네요 👍

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/CarName.java
> +            throw new IllegalArgumentException("이름이 5자 초과합니다");
예외 메시지도 하나의 정보입니다.
`이름은 5글자 이하이어야 합니다.` 같이
문제를 해결할 수 있는 정보를 전달해 주는 것이 좋습니다.

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/Car.java
>  public class Car {
name, distance 값을 래핑하셨네요 👍

---

트집잡는 것은 아닌데.. CarName, Distance는 컬렉션을 관리하는 객체가 아니므로 
일급 컬렉션으로는 보기 어려울 것 같네요 😅

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/Distance.java
> +            throw new IllegalArgumentException("거리가 음수입니다.");
이 부분도 좀 더 친절한 메시지를 던져주면 좋겠습니다.

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/MoveStrategy.java
> +public interface MoveStrategy {
특성에 맞게 명시적으로 선언하면 좋겠네요!
```java
@FunctionalInterface
public interface MoveStrategy { ... }
```

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/Cars.java
> +        this.cars.forEach(car -> car.move(() -> isMovingForward(RandomManager.getInstance().getRandomValue())));
만드신 MoveStrategy 전략을 Cars 까지 끌어올리면 Cars도 테스트하기 쉽게 변할 수 있겠네요 😄

```java
public void moveCars(MoveStrategy strategy) {
  // isMovingForward 대신 strategy를 전달
}
```

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/model/Cars.java
> +                .map(Car::getDistance)
Car 클래스에 Comparable를 구현하면 최대 이동거리인 Car를 좀 더 쉽게 구할 수 있어보이네요

2024-03-18 16:58 UTC, nooose commented on src/main/java/racingcar/RacingCarGameService.java
> +        ResultView.getInstance().printRacingcarWinners(winners);
InputView는 RacingCarGameService 밖에서 호출되고
ResultView는 RacingCarGameService 내부에서 호출되네요

호출 방향이 어색한 것 같습니다.
개선해볼 수 없을까요?

2024-03-18 17:02 UTC, merged