🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5446
Opened 2024-03-14 15:56 UTC by hellonayeon

안녕하세요 선동님!
덕분에 벌써 마지막 단계까지 왔네요 🥹

미처 작성하지 못했던 도메인 단위 테스트가 없는지, 추상화 레벨을 높이기 위해 원시값 포장한 도메인에 추가할 메시지가 있는지 확인하고 리팩토링하는 위주로 5단계 진행했습니다.

꼼꼼하게 리뷰해주셔서 놓쳤던 부분이나 생각해보지 못했던 내용들 많이 챙겨가고 있습니다. 👍

2024-03-14 16:00 UTC, hellonayeon reviewed
일급 컬렉션, 원시값 포장을 사용하다보니 `.get()` 체이닝이 많이 발생하는거 같아요.
선동님은 이런 경우에 어떻게 하시나요? (commit [dea2ab6](https://github.com/next-step/java-racingcar/pull/5446/commits/dea2ab6556c82ab85f08c4971ffffd9170a1ce33))

2024-03-15 04:21 UTC, seondongpyo commented
> 일급 컬렉션, 원시값 포장을 사용하다보니 `.get()` 체이닝이 많이 발생하는거 같아요. 선동님은 이런 경우에 어떻게 하시나요? (commit [dea2ab6](https://github.com/next-step/java-racingcar/pull/5446/commits/dea2ab6556c82ab85f08c4971ffffd9170a1ce33))

클래스가 상태로 일급 컬렉션을 갖는 경우에 자주 발생할 수 있는 이슈입니다.
현재 구조에서는 `ResultView`의 메서드들을 예시로 보면 좋을 것 같네요.
```java
public static void printWinnerNames(Winners winners) {
    System.out.println(MessageFormat.format("{0}가 최종 우승했습니다.", formatNames(winners.get())));
}

private static String formatNames(Names names) {
    return String.join(",", names.getNameStrings());
}
```
우승자의 이름을 출력하기 위해 `winners.get().getNameString()`처럼 연속적으로 getter를 호출할 수밖에 없는데요,
`Winners`에 `getNameString()` 메서드를 추가한다면 위와 같은 메서드의 호출 회수를 줄여볼 수 있겠습니다.
```java
// class Winners
public List<String> getNameString() {
    return this.names.getNameStrings();
}
```

2024-03-15 04:23 UTC, seondongpyo requested changes
마지막 단계도 잘 구현해주셨습니다 👍
마지막 단계이기도 하고, 단계의 이름 답게 리팩토링을 조금 더 해보면 좋을 것 같아서
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-03-15 04:23 UTC, seondongpyo commented on src/main/java/racingcar/domain/Cars.java
마지막 단계이니만큼, 조금 더 구조를 개선해보면 좋을 것 같아서 의견 드려봅니다.

1. 우승자를 구하는 로직을 리팩토링해보면 어떨까요?
```java
public Winners getWinners() {
    Distance maxDistance = findMaxDistance();
    return new Winners(findNames(maxDistance));
}
```
위 코드에서 `findMaxDistance()`를 호출하여 우승할 자격이 있는 최대 거리를 구하는 것까진 좋습니다만,
이후에 `findNames(maxDistance)`를 처리하는 과정이 개인적으로는 다소 복잡하다는 느낌이 듭니다.
앞서 우승자를 구하기 위한 `Distance`를 계산해서 알고 있는 상황이니, 자동차 경주가 끝난 현 시점에서는
각 자동차가 해당 `Distance` 값을 가지고 있는지 메시지를 보내서 처리해볼 수 있지 않을까요?

```java
public Winners getWinners() {
    Distance maxDistance = findMaxDistance();
    List<Name> names = cars.stream()
        .filter(car -> car.isWinner(maxDistance)) // 자동차에게 메시지를 보낸다
        .map(Car::getName)
        .collect(Collectors.toList());
    return new Winners(names);
}
```

2. `Winners`가 현재 일급 컬렉션인 `Names`를 상태로 가지고 있는데, 이러면 코멘트로 언급해주신 것처럼
연속적인 getter의 호출(`Winners → Names → Name`)이라는 구조가 아쉽게 다가옵니다.
`Winners`가 `List<Name>`을 상태로 갖는 일급 컬렉션으로 만들어보는 건 어떻게 생각하시나요?

3. `Winners` 클래스의 이름에 대해서도 고민을 해보면 좋을 것 같습니다.
`Winners`의 의미를 생각해보면, 우승자란 결국 경주에서 가장 멀리 이동한 `자동차(Car)들`이기 때문에
이름만을 상태로 갖는 것보다는 실제 우승한 자동차들을 상태로 갖는 것이 적절하지 않나 생각해요.
아니면 지금처럼 이름만을 상태로 가지도록 한다면 `Winners` 보다는 `WinnerNames`가 적절할 것 같습니다.

2024-03-17 10:46 UTC, hellonayeon commented
필요할때 별도의 생성자들을 추가하는 것 보다, 주생성자와 부생성자 개념을 활용했을 때 
도메인 생성에 대한 관리도 편리하고 유연성이 향상될 수 있다는 걸 피드백을 직접 반영해보니 알겠네요 .. 👍

이전 단계부터 생성자 작성하는 부분이 개인적으로 부족하다 느꼈는데 덕분에 한 번 짚고 넘어가네요. 
레퍼런스 공유 및 피드백 감사합니다 !

---

**[1]** 자동차가 자신의 `Distance` 를 알고 있으니 `maxDistance` 를 전달받아, 자신이 직접 우승자인지 확인하는 로직을 추가했어요.
`Map` 으로 복잡하게 우승자를 구하던 로직이 `Cars` 를 한번 탐색하면 구해지는 구조로 수정되었습니다 !

---

**[2, 3]** 선동님께서 말씀주신 내용 중 아래 내용에 공감이 되어서 `Winners` 가 `List<Car>` 의 상태를 갖도록 수정했어요.
> 우승자란 결국 경주에서 가장 멀리 이동한 자동차(Car)들이기 때문에
이름만을 상태로 갖는 것보다는 실제 우승한 자동차들을 상태로 갖는 것이 적절하지 않나 생각해요.

처음에 `Winners` 는 `String[] names` 를 리턴하는 메서드만 가지고 있었는데요. 
`하나의 메서드는 1depth 를 넘지 않도록 작성한다` 라는 규칙을 지키기 위해, 메서드를 분리했더니 아래와 같이 메서드 파라미터가 3개가 되더라구요.

1️⃣ **as-is**
```java
public Winners getWinners() {
        Distance winDistance = findWinDistance();
        List<Car> winners = new ArrayList<>();
        for (Car car : cars) {
            addWinner(winDistance, winners, car);
        }
        return new Winners(winners);
    }

    private void addWinner(Distance winDistance, List<Car> winners, Car car) {
        if (car.isWinner(winDistance)) {
            winners.add(car);
        }
    }
```

`클린코드: 함수 인수` 에서 삼항은 가능한 피하면 좋다해서 아래와 같이
`Winners` 에서 `Car` `winDistance` 를 받아 `Car.isWinner()` 메시지를 보내서 `Winners` 자신의 상태에 우승자를 추가할 수 있도록 수정했어요.

2️⃣ **to-be**
```java
public Winners getWinners() {
        Distance winDistance = findWinDistance();
        Winners winners = new Winners();
        for (Car car : cars) {
            winners.add(car, winDistance);
        }
        return winners;
    }
```

추가로 `Cars` 애서는 `winDistance` 까지 구하고, `Winners` 에서 `Cars` `winDistacne` 를 받아서 구하는 방법도 작성해보았는데,
생성자에 결국 우승자인지 판별하는 로직이 들어가는 것이기 때문에 채택하지는 않았어요 🤔

_생성자 내부 로직 관련 내용들을 더 확인해보니, 데이터를 추가적으로 가공을 하는게 아니라 상태 값을 초기화하는 것이기 때문에 이 방법도 나쁘지 않을 것 같아요._

3️⃣ **(to-be)가 될뻔 했던 코드**
```java
 public Winners(Cars cars, Distance winDistance) {
        this.winners = new ArrayList<>();
        setWinners(cars, winDistance);
    }

    private void setWinners(Cars cars, Distance winDistance) {
        for (Car car : cars.get()) {
            add(car, winDistance);
        }
    }
```

결과적으로 앞으로 이런 이슈를 맞닥드리게 된다면 저는 2️⃣, 3️⃣ 번의 스타일로 작성할 것 같아요.

2024-03-18 00:04 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍  
지금까지 자동차 경주 미션 진행하시느라 정말 고생 많으셨습니다.
다음 로또 미션도 힘내시고, 마지막 미션까지 꼭 완주하시길 응원하겠습니다 🔥

2024-03-18 00:04 UTC, merged