🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #5458
Opened 2024-03-15 19:05 UTC by hhhhhwi

안녕하세요..!
늦게 나마 3단계 PR을 올립니다..!

책임을 나누는 데에 중점을 두고 개발을 해보았는데,
막상 단위 테스트를 짜려고 하니, 어떤 검증을 해야하지..? 라는 고민이 들었습니다 😢 

제가 너무 추상화 없이 룰에 종속되게 개발을 한 게 문제이지 않을까? 라는 생각이 들었는데요..!

막상 고치려고 하니 어디서부터 손을 대야할지 막막하여..
먼저 피드백을 받는 것이 좋겠다 싶어 PR 올립니다..! 

늦었지만 잘 부탁드립니다! 감사합니다!

2024-03-16 06:06 UTC, nooose requested changes
3단계 충분히 잘 해주셨어요
피드백 받고 싶다면 언제든지 DM, PR 모두 괜찮습니다.

방향정도만 잡을 수 있게 피드백 소소하게 남겼어요. 재요청 부탁드립니다.

> 너무 추상화 없이 주어진 룰에 종속되게 개발을 한 게 문제 ...

처음부터 너무 섣부른 추상화는 오히려 코드를 망치는 지름길이 될 수 있습니다.
개발을 하다가 이런 부분에서 추상화가 필요하겠다 싶을 때 적용하면 좋습니다.
시작하기 전에 모든 상황을 다 파악한다면 정말 전문가죠~
점진적인 리팩토링을 경험하는 것이 이 과정 중 하나니까 너무 걱정하지 않으셔도됩니다.

2024-03-16 06:06 UTC, nooose commented on src/main/java/racingcar/PrintView.java
> +	public static void printCarMoving(boolean[] moving, int trial) {
```suggestion
	public static void printCar(Car car) {
```
값을 꺼내서 view에게 전달하지 않고 객체 자체를 넘기면 좋겠습니다.

2024-03-16 14:07 UTC, hhhhhwi commented on src/main/java/racingcar/Game.java
> +		}
자동차의 수와 시도 회수가 상태값이라고 생각하고 구현헀었는데, 외부에서 입력 받는 값이니 Game 객체에서 관리하지 않아도 될 것 같네요..!

2024-03-16 16:13 UTC, hhhhhwi commented on src/test/java/racingcar/TestCarMoveStrategy.java
> +public class TestCarMoveStrategy implements CarMoveStrategy{
랜덤값에 대한 테스트가 어려워 테스트를 위한 객체를 따로 만들었습니다..!

2024-03-16 16:18 UTC, hhhhhwi commented on src/main/java/racingcar/Car.java
> +	private boolean[] moving;
제가 자동차의 움직임 여부에 초점을 두다보니 boolean 배열을 상태값으로 뒀던 것 같은데요..! 그러다보니 Car 객체에 여러 책임이 있었던 것 같습니다..! Car에는 위치 변경에 대한 책임만 두고, 움직임을 위한 조건에 대한 책임을 CarMoveStrategy에 옮기는 방향으로 수정해보았습니다!

2024-03-17 01:47 UTC, nooose approved these changes
코드가 군더더기 없이 깔끔하네요 👍
피드백 남겼는데 4단계에서 반영하면 좋겠습니다.
수고하셨습니다.

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/InputView.java
> +	private static final String NUMBER_OF_TRIAL_INPUT_GUIDE = "시도할 회수는 몇 회 인가요?";
메시지를 상수 처리했네요
inputNumberOfCar 메소드를 봤을 때 정확히 어떤 메시지가 출력되는지 알 수 없기 때문에
코드위로 올려봐야 알 수 있습니다.
이런 이유로 매직넘버 값만 상수처리하고 메시지는 그대로 사용하는 편입니다.

개인적인 의견이니 참고만해주세요~

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/PrintView.java
> +	}
```suggestion
	public static void printResultMessage() {
		System.out.println("\n" + RESULT_MESSAGE);
	}

	public static void printCarMoving(Car car) {
		for(int i = 0; i < car.getPosition(); i++) {
			System.out.print("-");
		}

		printEmptyLine();
	}
	
        public static void printEmptyLine() {
		System.out.println();
	}
```
printEmptyLine를 printCarMoving 아래에 배치하면 좋겠네요
이래야 `printEmptyLine()` 메소드가 뭔지 확인할 때 코드를 다시 위로 올려보지 않아도 됩니다.

2024-03-17 01:47 UTC, nooose commented on src/test/java/racingcar/CarTest.java
> +		Car car = new Car(carMoveStrategy);
메소드가 하나인 인터페이스의 장점을 살리면 아래와 같은 표현도 가능합니다!
```suggestion
		Car car = new Car(() -> true);
```

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/CarMoveStrategy.java
> +	boolean isMovable();
테스트 제어가 가능하겠네요 👍

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/RandomCarMoveStrategy.java
> +		return new Random().nextInt(10) >= 4;
4가 무엇인지 의미를 나타내면 좋겠습니다.

2024-03-17 01:47 UTC, nooose commented on src/test/java/racingcar/CarTest.java
> +		assertThat(car.getPosition()).isGreaterThan(0);
한칸씩 이동되는 것을 요구사항으로 보고있기 때문에
정확하게 `isEqualTo`로 비교하는 게 맞지 않을까요?

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/Game.java
> +	}
생략해도 될 것 같아요 😄

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/Game.java
> +		}
배열대신 리스트를 사용해보면 어떨까요?
리스트와 비교했을 때 배열은 공변문제도 있고 편의성도 떨어집니다.

이펙티브 자바의 `배열대신 리스트를 사용하라`를 검색해 보시면 좋은 글들이 많으니 참고해보세요 🔍

2024-03-17 01:47 UTC, nooose commented on src/main/java/RacingGame.java
> +		game.play(InputView.inputNumberOfCar(), InputView.inputNumberOfTrial());
InputView는 game 외부에서 실행되고
ResultView는 game 내부에서 실행되네요

UI 호출 흐름이 약간~ 어색해 보이는데 고민해 보면 좋겠습니다

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/Car.java
> +		for(CarMoveStrategy carMoveStrategy : carMoveStrategies) {
오.. 여러 전략을 가질 수 있게 구현하셨네요 👍

2024-03-17 01:47 UTC, nooose commented on src/main/java/racingcar/PrintView.java
> +		}
System.out 콜을 줄이려면 어떻게 하면 좋을까요?

2024-03-17 01:47 UTC, merged

2024-03-18 13:53 UTC, hhhhhwi commented on src/main/java/racingcar/PrintView.java
> +	}
옷 이건 생각치도 못했는데..! 섬세한 피드백 감사합니다 🙇

2024-03-18 13:54 UTC, hhhhhwi commented on src/test/java/racingcar/CarTest.java
> +		Car car = new Car(carMoveStrategy);
ㅇ0ㅇ.. 부끄럽지만 위 표현은 몰랐네요..! 감사합니다 😄

2024-03-18 14:05 UTC, hhhhhwi commented on src/test/java/racingcar/CarTest.java
> +		assertThat(car.getPosition()).isGreaterThan(0);
아..! 증가의 의미를 더 강조하고 싶었는데 오히려 헷갈릴 수 있겠군요..!