4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5498
Opened 2024-03-18 16:36 UTC by ljg294

2024-03-19 14:40 UTC, ksy90101 requested changes
안녕하세요!
벌써 4단계까지 오셨네요~
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다~
언제든 질문이 있다면 DM주세요~

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/Race.java
> +//                .collect(Collectors.toList());
어... 주석은 지우는게 좋을거 같아요!

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/Race.java
>      private final NumberGenerator numberGenerator = new RandomNumberGenerator();
여기서 정의를 내린다면 Race 클래스에 대해선 테스트 하기가 어려울거 같은데
인자로 받아서 하면 테스트 코드 작성이 충분히 가능하지 않을까요?

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/Race.java
> +        return carList;
이런 부분을 충분히 stream을 사용해서 가능하지 않을까 생각이 드네요!

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/RacingApplication.java
> +//        int racingCarCount = scan.nextInt();
여기도 주석은 제거 하는게 좋을거 같습니다!

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/ViewPrinter.java
> +    private List<Car> carList;
List라는 단어보단 복수형을 사용해서 상태를 나타내면 어떨까요?

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/ViewPrinter.java
> +    private List<Car> carList;
View단에서 상태를 가지고 있는게 좋을까요?

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/object/Car.java
> +    private String name;
한번 Name을 VO로 만들어 보면 어떨까요?

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/object/Car.java
> +    }
원래 순서는 생성자 -> 비지니스 로직 -> getter/setter로 두는 경우가 많아요!

2024-03-19 14:40 UTC, ksy90101 commented on src/test/java/step3/RaceTest.java
> +//    }
여기도 주석은 제거 하면 좋겠어요~

2024-03-19 14:40 UTC, ksy90101 commented on src/main/java/step3/Race.java
> +        List<Car> carList = new ArrayList<>();
한번 carList를 일급컬렉션으로 만들어보면 어떨까요?

2024-03-23 10:14 UTC, ljg294 commented
1급 컬렉션으로 사용해보고 stream() 도 적극 사용했습니다.
불필요한 테스트가 있는지 궁금합니다.
저번에는 private method 테스트에 관한 내용들을 얘기해주셨는데, 이번엔 **과연 모든 public method별로 테스트를 진행해야 하는가?** 가 궁금합니다
항상 감사합니다.

2024-03-23 14:09 UTC, ksy90101 approved these changes
최대한 해볼수 잇는 public 테스트를 작성해보면 어떨까요?
일단 연습의 목적으로 작성해보면 좋을거 같아요~
피드백을 남기긴 했지만 5단계가 남아 있기 때문에 머지할게요~
마지막 5단계에서 같이 적용해주시면 좋을거 같습니다

언제든 DM으로 질문이 있다면 편히 연락주세요!

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/RacingApplication.java
> +        Scanner scan = new Scanner(System.in);
이런 View부분에서도 InputView에서 해야 하지 않을까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Car.java
> +    }
뭔가 MaxPostgion, isWinner라는건 Car입장에선 모르는 개념같아요.
즉, isSmaePosition처럼 Postigion이 같은지에 대해서 더 아는 정보 같은데
따라서 isWinner보단 isSamePosition과 같은게 더 어울리는게 아닐까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +    private NumberGenerator numberGenerator = new RandomNumberGenerator();
여기서 이렇게 하드코딩으로 생성하면, Cars는 테스트 하기 위해 생성자가 필요한거 같은데 무조건 더 윗 레벨에서 처리하면 어떨까요?
이렇게 되면 Cars를 사용하는 그 클래스에서 테스트가 불가능하지 않을까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +        Validator.validateCarNames(carNamesString);
CarNmae의 Validate는 Name 내부에서 하는게 더 어울리는게 아닐까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +                .filter(carName -> !carName.isBlank())
흠.. isBlank()가 아닌것들을 filter를 한다는것이 좀 이상하네요.
Name을 생성할때 빈값이 들어오면 에러를 던져야 할거 같은데...

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +        return cars;
이런 경우에 불변 리스트를 return하면 어떨까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +    public Winners findWinners() {
👍

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/Cars.java
> +                .forEach(winners::addWinner);
forEach를 하지 말고 toCollection을 쓰면 되지 않을까요?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/vo/Name.java
> +    }
5글자 이하라는 조건이 잇지 않았나요!?

2024-03-23 14:09 UTC, ksy90101 commented on src/main/java/racing/domain/vo/Position.java
> +    }
여기도 위와 비슷한거 같아요.! maxPostition이라는건 이 도메인에서 알수 없는거 아닐까요?

2024-03-23 14:09 UTC, merged