Step4
next-step/java-racingcar pull request #5542
Opened 2024-04-26 00:12 UTC by jaejeong1

리뷰 잘부탁드립니다 :)

2024-04-26 01:07 UTC, javajigi requested changes
자동차 경주 게임부터 하나씩 구현해 가는 모습 💯 
피드백 남긴 부분과 강의 영상 참고해 리팩터링 도전해 보면 좋겠습니다.
끝까지 포기하지 말고 미션 진행할 수 있는 부분까지 도전해 보시죠.

2024-04-26 01:07 UTC, javajigi commented on src/main/java/Car.java
>      public void move() {
```suggestion
    public void move(MovePolicy movePolicy) {
```
생성자를 통해 MovePolicy을 전달하고 있는데 메서드를 통해 전달하는 것은 어떨까?
두 가지 방법은 어느 방법으로 구현하는 것이 좋은 것이 있을까?

2024-04-26 01:07 UTC, javajigi commented on src/main/java/Cars.java
> +            maxPosition = Math.max(maxPosition, car.getPosition());
```suggestion
            maxPosition = car.max(maxPosition);
```
위와 같이 Car에 메시지를 보내도록 구현하는 것은 어떨까?

2024-04-26 01:07 UTC, javajigi commented on src/main/java/RacingCar.java
> +    }
핵심 로직을 구현하는 부분(상태 변경 등과 같은)과 View 로직(System.in을 통해 값 입력, System.out을 통해 값 출력)을 분리한다.
한 객체에 이 두 가지 로직이 같이 구현되어 있는 경우 추후 View가 되었을 때 핵심 로직을 구현하는 코드를 재사용할 수 없다.
또한 View에 종속되는 순간 테스트하기도 힘들다. 
이 연습은 웹 프로그래밍을 할 때 DB에 종속된 코드와 DB에 종속되지 않은 코드를 분리함으로써 테스트 가능하도록 구현하는 것과 같은 연습이다.

2024-04-26 01:07 UTC, javajigi commented on src/main/java/RacingCar.java
>      private int carCount;
Cars를 통해 현재 참여하는 자동차 갯수를 구할 수 있는데 굳이 이 값을 인스턴스 변수로 가질 필요가 있을까?

2024-04-26 01:07 UTC, javajigi commented on src/test/java/CarTest.java
>          when(movePolicy.isAbleToMove()).thenReturn(true);
mockito 프레임워크를 사용하지 않고 단위 테스트 가능한 구조가 되도록 설계해 본다.
이 과정의 모든 미션은 mockito 프레임워크 없이 구현할 것을 추천

이와 관련해서는 2차 라이브 강의의 두 부분 참고할 것을 추천

- 2시간 18분 34초: 자동차 이동 유무 로직을 TDD로 구현 - 라이브 코딩
- 2시간 11분 07초: 단위 테스트하기 어려운 부분을 TDD로 도전하기 이론 강의

2024-05-06 11:27 UTC, jaejeong1 commented on src/main/java/Car.java
> +        this.name = DEFAULT_NAME;
네, 주 생성자는 1개를 두고, 나머지 부 생성자는 주 생성자를 호출하도록 하는 방식이군요! 습관화 해보도록 하겠습니다 :)

2024-05-06 11:45 UTC, jaejeong1 commented on src/main/java/Car.java
>      public void move() {
1. 생성자를 통해 MovePolicy를 객체 생성 시에 지정
2. 메서드를 통해 전달 

자동차의 전진 방식은 변할수없다 와 같은 요구 사항이 있을 때는 1번을 통한 불변성 보장을,
불변성 보장이 필요없는 상황에서는 MovePolicy 메서드 전달을 통한 결합도 감소 측면에서 장점이 있다고 생각합니다 :) 

이번 미션에서는 후자가 유효하다고 생각해 제안주신 방법대로 리팩토링해보았습니다!

2024-05-06 14:35 UTC, jaejeong1 commented on src/main/java/RacingCar.java
> +    }
네, 해당 RacingCar 클래스는 뷰 로직을 제외한 Cars의 Racing 비즈니스 로직만을 담당하는 클래스이므로 view 로직을 제외했습니다 :)

2024-05-06 14:36 UTC, jaejeong1 commented on src/main/java/RacingCar.java
>      private int carCount;
뷰 로직이 포함된 RacingCar 클래스를 테스트하기 위한 용도의 프로퍼티였는데, 불필요합니다. 삭제하였습니다!

2024-05-06 15:03 UTC, jaejeong1 reviewed
피드백 반영해보았습니다. 끝까지 미션 완료해보겠습니다!!

2024-05-06 23:55 UTC, javajigi approved these changes
끝까지 포기하지 않고 미션 도전하는 모습 보기 좋네요. 💯 
피드백 반영 잘 했습니다.
피드백 하나 더 남겨봤어요.
이 미션의 마지막 단계는 리팩터링인데요.
힌트 영상 또는 라이브 강의 영상 참고해 추가 리팩터링 도전해 보면 어떨까요?

MVC 패턴 구조로 구현한 샘플 코드도 공유해 봅니다.

```
public class RacingGameApplication {
    public static void main(String[] args) {
        String carNames = InputView.getCarNames();
        int tryNo = InputView.getTryNo();

        RacingGame racingGame = new RacingGame(carNames, tryNo);
        RacingResult result = null;
        while(racingGame.isEnd()) {
            result = racingGame.race();
            ResultView.printResult(result);
        }
        ResultView.printWinners(result); // RacingResult에서 우승자를 구해 출력
    }
}
```

위 코드에서 힌트를 얻어 본인의 코드에 개선할 부분이 있는지 검토해 보고 리팩토링할 부분이 있다면 리팩토링에 도전해 보세요.
단, 이미 위와 같은 구조로 구현했다면 특별히 개선할 부분은 없으면 바로 리뷰 요청해도 될 것 같아요.

2024-05-06 23:55 UTC, javajigi commented on src/main/java/Cars.java
> +            car.move(movePolicy.isAbleToMove());
```suggestion
            car.move(movePolicy);
```
movePolicy를 car.move()에 전달하고 move() 메서드가 호출하도록 구현하는 것은 어떨까?

2024-05-06 23:55 UTC, merged

2024-05-07 01:23 UTC, jaejeong1 commented on src/main/java/Cars.java
> +            car.move(movePolicy.isAbleToMove());
네, car가 move하기위한 조건(policy)을 전달해주는 것이 좀 더 객체지향적인 설계로 보이네요. 적용해보았습니다 :)