🚀 2단계: 문자열 덧셈 계산기
next-step/java-racingcar pull request #5589
Opened 2024-09-24 13:58 UTC by zooucat

안녕하세요, 리뷰어님! 
미션을 완료하여 1단계 리뷰내용 반영과 함께 2단계 기능구현에 대한 PR 올립니다. 

# 기능 요구사항
- 쉼표(,) 또는 콜론(:)을 구분자로 가지는 문자열을 전달하는 경우 구분자를 기준으로 분리한 각 숫자의 합을 반환
- 앞의 기본 구분자(쉼표, 콜론)외에 커스텀 구분자를 지정할 수 있다. 커스텀 구분자는 문자열 앞부분의 “//”와 “\n” 사이에 위치하는 문자를 커스텀 구분자로 사용한다.
- 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 발생한다.

# 고민사항
0에 대한 요구사항은 별도로 없다보니, 0에 대한 처리는 어떻게 해야할지 고민은 많이 했습니다. 
`Positive`객체를 만들기엔 0은 양수가 아니고, `Number`객체를 만들고 `Positive`와 `Zero`와 `Negative`를 만들기엔 과도한 구현인것 같아 양수와 0을 value로 가질 수 있는 `PositiveOrZero` 객체를 만들게 되었습니다. 
일급객체인 `PositiveOrZeros` 라는 네이밍은 맘에 들진 않네요. 🤣

2024-09-24 14:52 UTC, jinyoungchoi95 requested changes
안녕하세요 윤정님 😄

자동차 미션을 함께하게 된 최진영입니다.

미션 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZero.java
> +public class PositiveOrZero {
> 0에 대한 요구사항은 별도로 없다보니, 0에 대한 처리는 어떻게 해야할지 고민은 많이 했습니다.
Positive객체를 만들기엔 0은 양수가 아니고, Number객체를 만들고 Positive와 Zero와 Negative를 만들기엔 과도한 구현인것 같아 양수와 0을 value로 가질 수 있는 PositiveOrZero 객체를 만들게 되었습니다.

수학적 정의에 따라서 다르긴하지만 고민되신다면 `NaturalNumber` 정도로도 충분히 의미를 전달할 수 있을 것 같아요. 혹은 `Number`라고 단순히 지정하고 해당 도메인 객체에 대해서 0이상이어야한다는 도메인 정보를 취급하는 방법도 있을 것 같네요.

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/StringAddCalculator.java
> 혹시 롬복을 비롯한 별도 라이브러리를 추가해도 괜찮을지도 궁금합니다!

필요한 라이브러리가 있으시다면 추가하셔도 좋아요. 다만, 미션과정 내에서 라이브러리를 지양함으로써 순수하게 자바만을 사용하면서 얻어가는 내용들도 있으니 고민해보시면 좋을 것 같아요 :)

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZero.java
> +        this(Integer.parseInt(value));
숫자가 아닌 값이 들어오면 예측 불가능한 에러가 발생할 수 있을 것 같네요!

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZero.java
> +        if (value < 0) {
0을 최소값이라는 도메인 정보라고 생각한다면 상수화해보는건 어떨까요?

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZero.java
> +    public PositiveOrZero add(PositiveOrZero addend) {
👍 

`PositiveOrZero`가 생성 시 validation은 잘 되는지, `add` 호출 시 잘 더해지는지도 테스트해볼 수 있겠네요 :)

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZeros.java
> +    }
생성자에서 `String[] strings`가 바로 쓰인다면 List를 받는 생성자는 없어도 되지 않을까요?

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/number/PositiveOrZeros.java
> +                .reduce(ZERO, PositiveOrZero::add);
ZERO를 생각해보면, `PositiveOrZeros`에서 모든 값을 더할때 시작하는 초기값이므로 상수를 외부에서 public하게 두고 쓰는것보다 `PositiveOrZeros`가 초기값을 담은 `PositiveOrZero` 상수를 들고 있는게 좀 더 적절하지 않을까요?

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/utils/StringUtils.java
> +    private StringUtils() {}
(반영하지 않으셔도 됩니다.) 일반적으로 utils를 사용할때 private으로 걸어두면 접근이 불가능하지만 심하게 이를 제어하고자할때는 리플렉션까지 고려하여 생성자에 예외를 걸어두기도합니다.

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/StringAddCalculator.java
> +    private static final int TARGET_TEXT_INDEX = 2;
상수 👍

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/main/java/calculator/StringAddCalculator.java
> +        return positiveOrZeros.addAll().value();
int값으로 반환하길 원한다면 `addAll()`의 반환값을 int로 두면 되지 않을까요?
```java
return this.positiveOrZeros
                .stream()
                .reduce(ZERO, PositiveOrZero::add)
                .value();
```
혹은 `PositiveOrZero`를 value object로 쓰고싶으시다는 니즈가 있으시다면 `splitAndSum`의 반환을 int가 아닌 `PositiveOrZero`를 반환하여도 좋을 것 같아요.

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/test/java/calculator/StringAddCalculatorTest.java
> +class StringAddCalculatorTest {
테스트 👍

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    }
```suggestion
    @ParameterizedTest
    @CsvSource({"1,1", "2,2", "3,3", "4,4", "5,5", "6,6", "7,7", "8,8", "9,9"})
    @DisplayName("숫자 하나를 문자열로 입력할 경우 해당 숫자를 반환한다.")
    void test02(final String text, final int expected) {
        // when
        final var result = StringAddCalculator.splitAndSum(text);

        // then
        assertThat(result).isEqualTo(expected);
    }
```
1. 일반적으로 테스트코드의 검증부에는 가능하면 로직이 들어가지 않는 것이 좋아요. (parseInt와 같은) 물론 지금은 간단한 로직이기는 하지만 하나씩 들어가다보면 테스트코드를 복잡하게하는 원인이 되고 혹시나 그 로직에 잘못된 값을 넣어 원하지 않는 동작을 실행할 수도 있어요.

2. 숫자를 문자열로 넣어 해당 숫자를 반환한다면 9개의 케이스를 돌리기보다는 1개만 돌려도 되지 않을까요? 테스트케이스는 물론 많으면 좋긴하지만 명확하게 테스트하고자하는 엣지케이스만 테스트해도 충분하지 않을까싶어요.

2024-09-24 14:52 UTC, jinyoungchoi95 commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    @DisplayName("\"//;\\n1;2;3\" 문자열을 입력했을 때 6을 반환한다.")
테스트를 설명하는 문구를 작성할때는 "기능이 어떻게 의도대로 동작하는가"를 표현하는 것이 중요해요. 테스트 코드를 문서화라는 관점에서 바라본다면 이 기능이 어떤 값을 반환하는가가 중요하기보단 어떻게 동작하는가가 문서로써 동작할 수 있게끔 도와주니까요.

그래서 6을 반환한다는 케이스에 대한 설명이고 테스트하고자하는 대상은 "커스텀 문자열을 넣었을 때 커스텀 문자열로 모든 수를 더할 수 있다"가 조금 더 적절하지 않을까요?

2024-09-24 15:03 UTC, zooucat commented on src/main/java/calculator/number/PositiveOrZero.java
> +public class PositiveOrZero {
> 혹은 `Number`라고 단순히 지정하고 해당 도메인 객체에 대해서 0이상이어야한다는 도메인 정보를 취급하는 방법도 있을 것 같네요.

오.. 좋은 내용 감사합니다. 실무에서도 항상 도메인 객체명에 대해 이름을 정할 때 고민이 있었는데 이런 방법도 있었군요! 👍

2024-09-24 15:29 UTC, zooucat commented on src/main/java/calculator/number/PositiveOrZeros.java
> +                .reduce(ZERO, PositiveOrZero::add);
리뷰어님이 남겨주신 것처럼 현재 상황에서의 ZERO는 일급 객체 내에서 모든 값을 더할 때 시작하는 초기값으로만 사용하고 있습니다만 저는 PositiveOrZero가 다른 곳에서도 사용될 수 있는 VO로 접근을 했다보니 public으로 선언했었습니다..!

2024-09-24 16:16 UTC, zooucat commented
코드를 굉장히 꼼꼼하게 리뷰해주셔서 감사합니다! 
항상 개발하면서 많은 고민을 했던 네이밍이라던지, 제가 몰라서 놓쳤던 부분들을 짚어주셔서 많은 도움이 되었습니다 :)

2024-09-24 16:22 UTC, zooucat commented on src/main/java/calculator/utils/StringUtils.java
> +    private StringUtils() {}
유틸을 리플렉션하는 경우를 많이 보지못했다보니 예외까지 걸어둘 생각을 못했었네요!
말씀하신 것처럼 생성자에 예외를 걸어두면 인스턴스화는 확실히 방지되겠군요 👍

2024-09-25 00:28 UTC, jinyoungchoi95 approved these changes
안녕하세요 윤정님 😄

피드백 잘 반영해주셨네요 👍 다음 미션 진행을 위해 머지하겠습니다 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-09-25 00:28 UTC, merged