2단계 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #5650
Opened 2024-09-28 09:12 UTC by pum005

2024-09-28 13:09 UTC, catsbi requested changes
시환님 2단계 미션 잘 진행해주셨어요 readme.md도 작성을 해주셨네요 👍 

코드 부분 몇 가지 고치고 넘어가면 좋을 부분들이 있어 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-09-28 13:09 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
인스턴스 변수를 가지지 않는 유틸리티 클래스로 보입니다. 
생성자 제한 혹은 싱글톤 패턴을 적용해보는건 어떨까요?

2024-09-28 13:09 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +            throw new IllegalArgumentException("양의 정수가 입력되어야 합니다!");
입력된 잘못된 값이 무엇인지도 같이 출력 메세지에 포함되면 디버깅이 더 쉬워질 것 같아요 ㅎㅎ

2024-09-28 13:09 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +        int ret = Integer.parseInt(num);
num이 숫자가 아닌 경우 발생하는 예외에 대한 처리는 필요 없을까요?

2024-09-28 13:09 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +        Matcher m = Pattern.compile(CUSTOM_DELIMETER).matcher(text);
Pattern.compile은 비용이 큰 동작입니다. 그렇기에 너무 잦은 호출은 성능저하로 이어질 수 있을 것 같아요. 
이 로직이 매 번 새로 생성되야 할 이유가 있을까요? 상수로 분리되도 괜찮을 것 같네요!

2024-09-28 13:09 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +            return m.group(2).split(customDelimiter);
1이나 2라고만 작성되어있으면 이 코드의 의도가 무엇인지 자세히 알기 힘들 것 같아요. 이런 매직넘버는 상수로 분리하여 적절한 네이밍으로 가독성을 높혀보면 어떨까요?

2024-09-28 13:09 UTC, catsbi commented on src/main/java/utils/validator/Validator.java
> +public class Validator {
클래스명이 Validator라면 검증을 책임질 것 같은데 util.validator 패키지에 있다는건 최상위 패키지이기에 이 프로젝트 전체의 검증을 모두 책임질 것으로 해석될 수 있을 것 같은데 SRP 원칙을 지킬수 있을지 체크해보는것도 좋을 것 같아요

2024-09-28 13:09 UTC, catsbi commented on src/test/java/StringAddCalculatorTest.java
> +    @DisplayName("splitAndSum 메소드는 문자열이 ', or :' 로 구분되어 입력 되었을때, 숫자의 합을 반환해야 한다.")
주석이 너무 구체적이면 차후 기획변경이 있을 경우 항상 같이 동기화를 해줘야하는데, 주석은 컴파일에 영향을 받지 않기에 놓치면서 테스트의 실제 동작과 주석이 달라지게될 수 있습니다. 

```suggestion
    @DisplayName("splitAndSum 메소드는 문자열이 유효한 경우, 숫자의 합을 반환한다.)
```

이 정도로만 작성되도 충분하지 않을까 싶네요!

2024-09-29 09:23 UTC, pum005 commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
감사합니다 :) 

싱글톤 패턴을 적용할때, 이 유틸리티 클래스는 Eager 와 Lazy 전략 중 어떤게 적절 할까요??

2024-09-29 09:26 UTC, pum005 commented on src/main/java/StringAddCalculator.java
> +            throw new IllegalArgumentException("양의 정수가 입력되어야 합니다!");
감사합니다 :) 수정하겠습니다!

2024-09-29 09:33 UTC, pum005 commented on src/main/java/StringAddCalculator.java
> +        Matcher m = Pattern.compile(CUSTOM_DELIMETER).matcher(text);
감사합니다!

향후에 커스텀 구분자가 많아지도록 요구사항이 변경된다면, 유지보수 측면에서

다양한 Pattern.compile(CUSTOM_DELIMETER) 상수들을 StringAddCalculator 클래스에서 관리하는게 좋을까요??
아니면 새로운 클래스로 분리 하는게 좋은가요??

2024-09-29 09:34 UTC, pum005 commented on src/main/java/StringAddCalculator.java
> +            return m.group(2).split(customDelimiter);
그렇네요! 수정하겠습니다!

2024-09-29 09:37 UTC, pum005 commented on src/main/java/utils/validator/Validator.java
> +public class Validator {
감사합니다! :)

사용자의 입력을 검증하는 InputValidator 로 명칭을 정했는데, SRP 를 지키는 것일까요?

2024-09-29 09:37 UTC, pum005 commented on src/test/java/StringAddCalculatorTest.java
> +    @DisplayName("splitAndSum 메소드는 문자열이 ', or :' 로 구분되어 입력 되었을때, 숫자의 합을 반환해야 한다.")
네! 감사합니다!

2024-09-29 10:32 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
호출빈도나 호출시점에 따라 전략을 정하는데, 계산기 프로그램에서 계산기 객체 호출은 필수적이고 즉각적이기 때문에 이를 고려하면 어떤 전략을 선택하던 큰 차이가 없을 것 같네요 ㅎㅎ

2024-09-29 10:34 UTC, catsbi commented on src/main/java/StringAddCalculator.java
> +        Matcher m = Pattern.compile(CUSTOM_DELIMETER).matcher(text);
보통 상태(state)를 관리한다고 분리하게되는순간 사실 관리포인트 노출 및 관리지점의 이중화로 유지보수성에 좋은 상황은 아닙니다.  정말 필요해질정도로 많아질 시점에 분리를 고민해봐도 좋아요. 

개발 방법론중에는 YAGNI라는게 있는데 You Ain't Gonna Need it 라는 말로 정말로 필요할때까지 만들지 말라는 말로, 오버 엔지니어링에 대한 화두이기도 해요. 

정리하면 분리는 정말 책임이 커지면서 각각의 책임이 분리되야할 시점에 되면 좋다 입니다

2024-09-29 10:36 UTC, catsbi commented on src/main/java/utils/validator/Validator.java
> +public class Validator {
음, 그것도 결국 input에 대한 검증기라는건데 input이라는 용어 자체도 범용적이지 않을까요? 
인터페이스 추상화를 통해 검증기를 정의하고 각각의 패키지내의 구현체(CalculatorValidator)등으로 구분하여 범위를 최대한 좁히는게 중요하지 않을까요?

2024-09-29 10:39 UTC, catsbi approved these changes
시환님 피드백 반영 빠르게 잘 해주셨어요 👍 

질문주신부분들은 코멘트에 대댓글로 남겨놨으니 확인해주시고, 다음 단계 진행해주세요!
2단계는 여기서 merge하도록 하겠습니다!

2024-09-29 10:39 UTC, catsbi commented on src/main/java/calculator/StringAddCalculator.java
> +    private static final Pattern customDelimeterPattern = Pattern.compile(CUSTOM_DELIMETER_REGEX);
CUSTOM_DELIMETER_REGEX 이 별도로 사용될일이 없다면, 굳이 상수로 선언되는 Pattern의 매개변수도 상수로만들진 않아도 될 것 같네요!
```suggestion
    private static final Pattern customDelimeterPattern = Pattern.compile("//(.)\n(.*)");
```

2024-09-29 10:39 UTC, merged