자동차 경우 구현
next-step/java-racingcar pull request #5653
Opened 2024-09-28 13:05 UTC by gyeongjae-ham

구현 내용
1. Main 클래스 - 자동차 경주 실행 클래스
2. Car - 자동차 클래스
3. CarRace - 경주를 제어하는 클래스

질문 내용
1. CarRace 환경에서 random한 값을 테스트하기 어려워서 interface로 주입되도록 해서 값을 제어해서 테스트했는데 그냥 최종 결과 값이 랜덤 값을 넘어서는지 확인만 하면 되는건지 아니면 이렇게 제어해서 테스트하는 게 더 좋은 테스트인지 궁금합니다
2. 테스트에 쉽게 수정하다 보니 상위에 주입하는 책임을 계속 넘기는 방향으로 리팩토링이 진행됐는데 이럴 경우 어느 부분까지 책임을 넘기고 말아야 하는지 테스트하기 좋은 환경이 우선일까요? 아니면 로직의 흐름 파악이 쉬운 정도가 우선일까요?

2024-09-29 07:15 UTC, csh0034 requested changes
3단계 구현 잘 해주셨네요 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요!

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/race/InputView.java
> +public class InputView {
입력부분을 InputView  사용하여 잘 분리해주셨네요 👍

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/race/RandomNumber.java
> +public interface RandomNumber {
`@FunctionalInterface` 에 대해 학습후 적용해보시면 좋을것 같아요!

또한 `여러 알고리즘을 캡슐화하고 상호 교환 가능하게 만드는 패턴.` 인 `전략패턴` 형태로
잘 구현해주셨네요 💯

추가로 정수를 반환할수도 있지만 움직일지에 대한 여부(boolean) 을 반환할수도 있지 않을까요? 🤔

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/race/CarRandomNumber.java
> +public class CarRandomNumber implements RandomNumber {
자동차에 대한 랜덤한 숫자를 반환하는 책임이 있으므로 randomRange 자체를 외부에서
받지 않고 가지고 있도록 해보는건 어떨까요?

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/race/Car.java
> +        if (conditionNumber >= 4) {
매직넘버는 상수로 선언해보면 좋을것 같아요 🙂

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/race/CarRace.java
> +        ResultView.output(cars);
`핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.`

요구사항에 맞춰 도메인 코드에서 ui 로직에 대한 참조/호출이 없도록 분리해보시면 좋을것 같습니다.

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/Main.java
> +        InputView inputView = new InputView();
ResultView 는 static method 만 가지고 있는데 InputView 는 객체를 생성하고있네요!
다르게하는것이 필요한걸까요? 🤔

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/Main.java
> +public class Main {
Main 또한 race 에 대한 진입점이므로 패키지를 이동해보시면 좋을것 같습니다!

2024-09-29 07:15 UTC, csh0034 commented on src/main/java/Main.java
> +    private static List<Car> initCars(int carCount) {
`List<Car>` 를 생성하는 로직은 CarRace 에 책임으로 볼수있지 않을까요? 🤔

2024-09-29 07:15 UTC, csh0034 commented on src/test/java/race/CarTest.java
> +class CarTest {
조건별 단위테스트 작성 👍

2024-09-29 07:17 UTC, csh0034 commented
추가로 `AngularJS Commit Message Conventions` 를 사용하여 커밋해야하는 
`commit 로그 요구사항` 이 적용되지 않은것 같아요 🥲 
이후 커밋부터는 적용해보시면 좋을것 같습니다!

2024-09-29 07:33 UTC, csh0034 commented
### 두가지 질문 함께 답변드리겠습니다.

랜덤/시간/외부호출 등과 같이 제어할수 없는 영역은 테스트코드 작성을 어렵게 만듭니다.
해주신 방법과 같이 책임을 분리한후에 다른 구현체를 사용하여 테스트하는것이 좋다고 생각합니다.

이때 고민은 어디서 주입을 해줘야 하는가 일텐데요.
DI 가 가능한 환경이라면 생성시 주입해주겠지만 그렇지 않을 경우 가능한 외부로
보내서 main 까지 가면 좋지만 우선은 핵심로직을 담당하는 도메인의 외부라면 괜찮다고 생각합니다.

2024-09-29 08:21 UTC, gyeongjae-ham commented on README.md
> +## 기능 목록 정리
넵 알겠습니다!

2024-09-29 08:21 UTC, gyeongjae-ham commented on src/main/java/race/RandomNumber.java
> +public interface RandomNumber {
생각해보니 어차피 조건을 따지는 목적자체는 boolean에 가깝다는 생각이 들어서 수정했습니다!

2024-09-29 08:21 UTC, gyeongjae-ham commented on src/main/java/race/CarRandomNumber.java
> +public class CarRandomNumber implements RandomNumber {
책임이 해당 클래스에 있다는 걸 확인했습니다 감사합니다!

2024-09-29 08:21 UTC, gyeongjae-ham commented on src/main/java/race/Car.java
> +        if (conditionNumber >= 4) {
넵!!

2024-09-29 08:21 UTC, gyeongjae-ham commented on src/main/java/race/CarRace.java
> +        ResultView.output(cars);
아아 넵 알겠습니다!!

2024-09-29 08:22 UTC, gyeongjae-ham commented on src/main/java/Main.java
> +        InputView inputView = new InputView();
음 생각해보니 전혀 다를이유가 없습니다 똑같이 static method로 수정하겠습니다!

2024-09-29 08:22 UTC, gyeongjae-ham commented on src/main/java/Main.java
> +public class Main {
넵 알겠습니다!

2024-09-29 08:22 UTC, gyeongjae-ham commented on src/main/java/Main.java
> +    private static List<Car> initCars(int carCount) {
네 확인해보니 당연히 CarRace의 책임으로 보입니다 감사합니다!

2024-09-29 08:22 UTC, gyeongjae-ham commented on src/test/java/race/CarTest.java
> +class CarTest {
감사합니다!

2024-09-29 12:16 UTC, csh0034 requested changes
리뷰 반영 잘해주셨네요!
추가로 몇가지 코멘트 남겨두었는데
확인 부탁드립니다 😄

2024-09-29 12:16 UTC, csh0034 commented on src/main/java/race/RandomNumber.java
> +public interface RandomNumber {
해당 인터페이스에 이름과 기능이 매칭되지 않는것 같아요!
이름에 대해서 고민해보시면 좋을것 같습니다 🙂

2024-09-29 12:16 UTC, csh0034 commented on src/main/java/race/CarRace.java
> +        ResultView.output(cars);
출력부분이 도메인코드에 여전히 존재하는것 같아요! 🤔

2024-09-29 12:16 UTC, csh0034 commented on src/main/java/race/CarRace.java
> +    private int tryCount;
tryCount 를 보면 인자로 받아 단순히 getter 로 노출되고 있습니다.
과정중엔 setter/getter 사용하지 않는걸 권장하는데요!

외부에서 CarRace 에게 race 를 진행해야하는지  메세지를 보내보는건 어떨까요?

2024-09-29 12:16 UTC, csh0034 commented on src/main/java/race/RaceInput.java
> +public class RaceInput {
getter 만 제공하기 위함이라면 InputView 에서 한번에 처리하지 않고
각각 질문을 한다면 해당클래스를 제거해볼수 있지 않을까요?

2024-09-29 12:16 UTC, csh0034 commented on src/test/java/race/CarRaceTest.java
> +        FixedCheckForward goCondition = new FixedCheckForward(FIX_FORWARD_CONDITION);
타입선언시 가능하면 구현체 변경에 용이하기 때문에 상위타입으로 선언해보는걸 추천드려요!

2024-09-29 12:16 UTC, csh0034 commented on src/test/java/race/FixedCheckForward.java
> +public class FixedCheckForward implements RandomNumber {
boolean 값을 생성자로 꼭 받아야 하는걸까요? 🤔

2024-09-29 12:16 UTC, csh0034 commented on src/main/java/race/Car.java
> +    public int getForwardResult() {
getter 를 꼭 제공해야하는지에 대해서 고민해보시면 좋을것 같습니다.

2024-09-29 12:17 UTC, csh0034 commented
하단과 같이 실행결과가 요구사항에 있는 부분과 다른것 같아요.
함께 확인 부탁드립니다!

```text
자동차 대수는 몇 대 인가요?
5
시도할 회수는 몇 회 인가요?
1
-
-
-
-
-

--
-
--
--
-

--
-
--
--
-
```

2024-09-30 00:52 UTC, csh0034 approved these changes
리뷰 반영잘해주셨습니다 👍 
몇가지 코멘트 남겨두었는데 다음단계 진행전에
확인 부탁드려요!

2024-09-30 00:52 UTC, csh0034 commented on src/main/java/race/CarRace.java
> +    private void checkCarForward() {
check/validate/verify 등과 같은 접두사는 validation 검증에 주로 쓰입니다.
의미를 잘 전달할 수 있는 이름에 대해서 고민해보시면좋을것 같아요!

2024-09-30 00:52 UTC, csh0034 commented on src/main/java/race/Car.java
> +    private final static String EXPRESS_STRING = "-";
만약 출력시 `*` 로 변경되어야 한다면 도메인 코드의 변경이 발생합니다.
이는 도메인코드가 ui 에 의존적이라고 볼 수도 있을것 같아요.

이전에 리뷰는 getter 를 사용하지 않는것이 아닌 비지니스 로직에선 사용하지 않더라도
출력 `요구사항`에 의해 값을 제공해야한다면 getter 를 추가할수 있다 등과 같이 기준을
세워보셨으면 해서 드린내용입니다 🙂

2024-09-30 00:52 UTC, csh0034 commented on src/test/java/race/CarTest.java
> +        int forwardResult = car.getForwardResult();
getter 가 제거되어 컴파일 실패하네요 🥲

코드 변경후엔 테스트코드를 실행해보는 습관을 만들수있도록 해보시면 좋을것 같아요!

2024-09-30 00:52 UTC, merged