Step2 - 문자열 덧셈 계산기
next-step/java-racingcar pull request #5659
Opened 2024-09-29 04:34 UTC by Ujoonnee

안녕하세요 리뷰어님, 2단계 리뷰 요청드립니다.

과제를 하다가 라이브 강의 후에 처음부터 다시 시작해서 `step2 초기화 및 패키지명 변경` 커밋부터 확인해 주셔도 무방할 것 같습니다.

지금 단계에서는 Stream API 없이 과제를 수행해 보라는 말씀이 있으셔서 시도해 봤는데
이렇게까지 생각할 부분이 많아질 줄은 상상도 못했네요 ㅠㅠ 

사소한 문제점이라도 신랄하게 지적해 주시면 감사하겠습니다!

---

> assertj 는 평소에도 사용해보셨을까요?
> api 를 잘 활용해주셨네요 💯

제 업무 환경이 java7 + svn 이어서 assertj, stream 은 커녕 git 이랑도 아직 좀 서먹해서..
API 검색 + 이게 맞나??? 하느라 과제하는데 오래 걸린 것 같습니다 😂
지금 보니 커밋도 과하게 쪼갠건가 싶네요 🙏

2024-09-29 04:50 UTC, Ujoonnee commented on src/main/java/calculator/StringAddCalculator.java
> +            return new String[0];
빈 String 배열을 반환하면 어차피 sum 에서 for 문을 타지 않아 0을 메서드 결과로 반환할 것

sum 메서드를 타지 않고 splitAndSum 의 동작을 바로 중지시키는게 바람직할까요?

2024-09-29 04:53 UTC, Ujoonnee reviewed
sum 메서드가 int 배열이나 리스트가 아닌 String 배열을 받는 것이 적절치 않아 보여 split 결과의 타입을 List<Integer> 로 변환 후 sum 메서드를 호출하도록 함

2024-09-29 05:38 UTC, mskangg commented on src/main/java/calculator/StringAddCalculator.java
> +            return new String[0];
지금은 리턴밸류가 int 로 변환되었군요!
작성해주신대로 early return 이 좋을것 같아요 👍

2024-09-29 06:10 UTC, mskangg requested changes
> 커밋마다 생각했던 내용을 공유드리고 싶은데 PR에서 comment 로 남기기에는 너무 많을 것 같다는 생각이 드네요.
혹시 좋은 방법이 있을까요?

내용을 공유하고 싶다면, 따로 메모장에 정리해두었다가 PR 올릴때 공유해주시면 좋을것 같아요!
특정 코드에 대한 내용을 공유하고 싶다면 PR 올리신 뒤 files changed 눌러서 해당 라인에 코멘트 남겨주셔도 무방합니다 :)

>제 업무 환경이 java7 + svn 이어서 assertj, stream 은 커녕 git 이랑도 아직 좀 서먹해서..
API 검색 + 이게 맞나??? 하느라 과제하는데 오래 걸린 것 같습니다 😂

아이고.. 레거시가 많은 곳에서 업무하고 계시는군요!
그럼에도 불구하고 따로 시간내어 교육을 신청해서 발전하시려는 모습 정말 보기좋습니다!
혹시나 과정 진행중 편하게 DM 주시면 답변해드릴게요!

> 지금 보니 커밋도 과하게 쪼갠건가 싶네요 🙏

잘해주셨어요 💯 

2단계도 꼼꼼히 잘 구현해주셨네요!
parameterized 테스트까지 사용하시고 좋습니다 👍 
몇가지 피드백 남겨드렸는데, 확인부탁드릴게요!

2024-09-29 06:10 UTC, mskangg commented on src/main/java/calculator/StringAddCalculator.java
> +            result.add(Integer.parseInt(number));
`문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw한다.`

split 으로 들어오는 문자열 중 숫자가 아닌경우 NumberFormatException 이 발생할것 같아요!
try/catch 블럭으로 핸들링하는건 어떨까요?

2024-09-29 06:10 UTC, mskangg commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    @MethodSource("provideForbiddenCustomDelimiterInput")
ParameterizedTest 를 잘 활용해주셨네요 👍

2024-09-29 06:10 UTC, mskangg commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    void 계산에_음수를_사용할_수_없다(String input) {
숫자가 아닌 문자열에 대한 테스트는 없네용..
추가하는건 어떨까요?

2024-09-29 06:24 UTC, Ujoonnee commented on src/main/java/calculator/splitter/Splitter.java
> +public abstract class Splitter {
아이고 커밋 전에 삭제했어야 했는데 놓쳤습니다 ㅎㅎ;;

2024-09-29 06:25 UTC, Ujoonnee commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    void 계산에_음수를_사용할_수_없다(String input) {
추가하겠습니다!

2024-09-29 07:11 UTC, Ujoonnee commented on src/main/java/calculator/StringAddCalculator.java
> +            validateNumber(number);
> split 으로 들어오는 문자열 중 숫자가 아닌경우 NumberFormatException 이 발생할것 같아요! try/catch 블럭으로 핸들링하는건 어떨까요?

parseInt 실행 중 발생할 NumberFormatException 을 catch 블럭에서 메시지 변경을 위해서 같은 exception 을 던지는 상황이 뭔가 내키지 않았고, 최대한 indent depth 를 줄이기 위해서 따로 메서드를 추출했습니다.

2024-09-30 02:18 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 💯 
그럼 다음 단계 진행해주세요~! 🙇

2024-09-30 02:18 UTC, mskangg commented on src/main/java/calculator/StringAddCalculator.java
> +        }
👍

2024-09-30 02:18 UTC, mskangg commented on src/test/java/calculator/StringAddCalculatorTest.java
> +                .hasMessage("숫자 이외의 문자를 사용할 수 없습니다.");
👍

2024-09-30 02:18 UTC, merged