3단계 - 자동차 경주
next-step/java-racingcar pull request #5662
Opened 2024-09-29 07:45 UTC by Park1122

멘토님 리뷰 부탁드립니다!
해당 개발을 하면서 가장 어려웠던 점은 테스트 코드 작성이었던 것 같습니다.
정확히 어느 부분을 테스트해야하나 고민하다가 자동차 움직이는 기능 부분을 테스트 코드로 작성해봤습니다.

2024-09-30 03:15 UTC, shared-moon requested changes
정욱님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
전체적으로 깔끔하게 만들어주셔서 아주 좋았는데, 테스트를 조금 고민하시는 것 같아서 구조에 대한 의견을 좀 남겨봤어요!
이번에 고거 한번 더 고민해보고 지나가면 좋을 것 같아요!
확인 후 리뷰 재요청 부탁드려요!

2024-09-30 03:15 UTC, shared-moon commented on src/main/java/study/step3/car/RacingCar.java
> +    public void move(int number) {
👍 
근데 요거 이 미션 할때마다 항상 의견이 갈리는 부분이긴 한데요, 혹시 움직일지 말지를 RacingCar가 가지고 있는 것에 대해서 어떻게 생각하실까요? 저는 개인적으로 RacingCar는 움직이는 것만 가지고 있고 해당 조건은 게임의 조건이라 바깥에 있는게 더 어울리지 않나 하고 생각하거든요!

2024-09-30 03:15 UTC, shared-moon commented on src/main/java/study/step3/game/RacingCarGame.java
> +        this.inputView.questionCarCount();
요거는 굳이 this 안써도 되지 않을까요 ?

2024-09-30 03:15 UTC, shared-moon commented on src/main/java/study/step3/game/RacingCarGame.java
> +        int carCount = validateCarCount(this.inputView.getCount());
validate인데 리턴값이 있는게 좀 어색한 것 같아요!

2024-09-30 03:15 UTC, shared-moon commented on src/test/java/study/step3/RacingCarTest.java
> +public class RacingCarTest {
RacingCarGame이 너무 많은 책임을 가지고 있는 것 같기도 하네요!
인풋을 밖에서 받아 생성자로 주입받는 방식으로 만든다면 유효성검사 테스트는 진행 해 볼 수 있지 않을까요 ?

2024-09-30 10:32 UTC, Park1122 commented on src/main/java/study/step3/car/RacingCar.java
> +    public void move(int number) {
단순히 게임의 조건으로만 본다면 말씀주신대로 RacingCar 바깥에 있는게 더 합리적인 것 같습니다!

2024-10-01 12:02 UTC, shared-moon approved these changes
정욱님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
이번 미션은 여기서 머지 하도록 하겠습니다!
다음 미션도 화이팅 하세요!

2024-10-01 12:02 UTC, shared-moon commented on src/main/java/study/step3/RacingCarMain.java
> +        InputView inputView = new InputView();
👍

2024-10-01 12:02 UTC, shared-moon commented on src/test/java/study/step3/RacingCarTest.java
> +    void input_유효성_검사_자동차_2대미만() {
👍

2024-10-01 12:03 UTC, merged