🚀 3단계 - 자동차 경주 구현
next-step/java-racingcar pull request #5682
Opened 2024-09-30 11:03 UTC by joonkb

안녕하세요, 리뷰어님!

🚀 3단계 - 자동차 경주 미션 리뷰 요청드립니다.

이번 미션을 구현하면서 몇 가지 질문이 생겼습니다:

1. Car 객체가 스스로 랜덤값을 받아 전진할지 멈출지 결정하는 방식과, 외부에서 판단 후 Car 객체에 명령하는 방식 중 어느 쪽이 더 나은 설계인지 판단할 수가 있을까요?  더 좋은 방법이 있다면 그 이유나 기준이 궁금합니다.
2. GameController 클래스에서 `createCars()`라는 private 메서드를 정의했습니다. 제가 정의한 요구사항에 따라 "자동차 대수를 입력받아 배열을 반환"하는 기능을 구현했지만, 내부적으로만 사용되므로 테스트 코드를 작성하지 않았습니다. 제가 테스트 단위를 잘못 잡은 걸까요? 아니면 private 메서드를 테스트할 방법이 있는지 궁금합니다.

이번에도 많은 피드백 부탁드립니다.

감사합니다!

2024-09-30 15:15 UTC, jinyoungchoi95 requested changes
안녕하세요 병준님 😄

3단계 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-09-30 15:15 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +public class Car {
> Car 객체가 스스로 랜덤값을 받아 전진할지 멈출지 결정하는 방식과, 외부에서 판단 후 Car 객체에 명령하는 방식 중 어느 쪽이 더 나은 설계인지 판단할 수가 있을까요? 더 좋은 방법이 있다면 그 이유나 기준이 궁금합니다.

어느쪽이 더 나은 설계라기보다는 둘 다 각각 장단점이 있을 것 같은데요. `Car`가 스스로 판단하는 경우에 대해서 이야기하면 `Car`가 움직임에 대한 책임을 가지고 있어 외부에서는 이에 대한 내부 동작을 알 필요없어 캡슐화를 할 수 있을 것 같네요.

2024-09-30 15:15 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +    private List<Car> createCars() {
> GameController 클래스에서 createCars()라는 private 메서드를 정의했습니다. 제가 정의한 요구사항에 따라 "자동차 대수를 입력받아 배열을 반환"하는 기능을 구현했지만, 내부적으로만 사용되므로 테스트 코드를 작성하지 않았습니다. 제가 테스트 단위를 잘못 잡은 걸까요? 아니면 private 메서드를 테스트할 방법이 있는지 궁금합니다.

private 메서드는 단순히 코드를 기능적으로 분리한 것이지, 그것을 개별적으로 테스트하려고 접근하는 것보다는 기능 자체가 테스트하기 좋은 구조인지에 대해 먼저 고민해봐야 할 것 같아요. 현재는 테스트하기 힘든 구조로 보이진 않는데요.

초기 설계 단계에서 보면, createCars 메서드는 아마도 처음에는 생성자 안에 있었을 가능성이 큽니다. 이때 생성자가 너무 많은 책임을 가지게 되면서 해당 로직이 분리된 것으로 보여요. 그렇다면, 생성자를 통해 객체가 잘 생성되었는지를 테스트하는 것이 더 적절한 접근일 것 같아요.

생성된 필드 값이 예상대로 설정되었는지 테스트하는 방법은 다양한데요. 예를 들어, equals 메서드를 재정의하여 객체 간 비교를 하거나, Assertions 클래스의 다양한 메서드를 활용할 수 있을 것 같습니다.

2024-09-30 15:15 UTC, jinyoungchoi95 commented on README.md
> +- [ ]  자동차 대수를 입력받아 해당 크기의 자동차 배열을 반환한다.
기능요구사항 정리 👍 

10-11 라인의 todo도 체크되어야하지 않을까요?

2024-09-30 15:15 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +    }
아무동작을 하지 않는 메소드는 제거해주는 것이 좋을 것 같아요.

`move()`를 호출하였을때 움직일 수 있으면 position을 증가시키고 아니면 동작을 하지 않는 메소드 하나로 통일할 수 있지 않을까요?

2024-09-30 15:15 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +        return status.toString();
관습적으로 `toString()`은 디버깅의 목적으로 사용되기 때문에 출력용으로 사용을 지양하여야합니다 :)

2024-09-30 15:15 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +    public String showStatus() {
프로그래밍 요구사항의
> 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.

는 도메인코드에서 ui와 관련된 코드를 분리하는 것을 의미해요. "-"를 출력하는 것은 화면단의 요구사항이므로 `Car`는 단순히 현재 위치값을 반환하고 무엇을 출력할지는 View로 넘겨보면 좋을 것 같아요 😄

2024-10-01 03:47 UTC, joonkb commented on src/main/java/racingcar/controller/GameController.java
> +    private List<Car> createCars() {
안녕하세요, 리뷰어님 🙇‍♂️
이번에 다시 수정하기를 GameController 클래스에 `getCars()` 라는 getter()를 추가하여 반환하는 값에 대한 사이즈 및 원소를 검증하는 테스트 코드를 추가하였습니다. 이에 따라 `eqauals()`, `hashcode()` 메서드도 추가하여 테스트를 진행하였습니다. 
리뷰어님이 의도한바가 맞는지 궁금하고, 리뷰어님이라면 어떻게 하셨을지도 궁금합니다..ㅎ

2024-10-01 03:53 UTC, joonkb commented
안녕하세요, 리뷰어님! 🙇‍♂️

🚀 3단계 - 자동차 경주 미션 리뷰사항 반영하여 코드리뷰 요청드립니다!

이번 미션을 진행하면서 드는 생각은 경험이 부족해서인건지 테스트 코드 작성을 위해서 로직을 억지로 끼워 맞추는것 같은 느낌이 들었습니다.. 

코드를 더 간단하게 할 개선거리가 있는지, 패키지 구조는 달리 할만한 의견이 있는지도 궁금합니다..!

이번에도 많은 피드백 부탁드리겠습니다!! 🙏

감사합니다!

2024-10-01 12:38 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +    private List<Car> createCars() {
네 지금정도면 충분할 것 같아요 :)

2024-10-01 12:53 UTC, jinyoungchoi95 approved these changes
안녕하세요 병준님 😄

피드백 잘 반영해주셨네요 👍 다음 미션 진행을 위해 머지하겠습니다 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +    private static boolean movable(int randomNumber) {
```suggestion
    private boolean movable(int randomNumber) {
```
static 제거되어도 될 것 같아요 :)

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/model/Car.java
> +    public static final int RANDOM_THRESHOLD = 4;
```suggestion
    private static final int RANDOM_THRESHOLD = 4;
```
접근이 불필요한 상수는 막아주는 것이 좋을 것 같아요 😄

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +    private List<Car> cars;
```suggestion
    private final List<Car> cars;
```
컬렉션의 참조값도 final로 막아줄 수 있을 것 같네요

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +    private int numberOfCars;
자동차의 갯수를 계속 들고있기보다 생성시점에 `createCars`로 바로 생성하면 `numberOfCars`를 가지고 있을 필요가 없지 않을까요?

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +        ResultView.showResultDescription();
다음 단계를 진행하실때는 Controller에서도 `ResultView`를 없애보는건 어떨까요? 흔히 mvc를 생각하더라도 controller는 "출력"을 담당하는 역할은 아니므로 이를 별개로 봐주시는 게 좋을 것 같습니다 :)

2024-10-01 12:53 UTC, jinyoungchoi95 commented on src/main/java/racingcar/controller/GameController.java
> +    }
전반적으로 public, private메소드의 위치가 정해진 규칙이 따로 없는 것 같은데요. 가독성을 중시한다면 각 메소드들의 위치도 가독성에 영향이 가는만큼 미션진행하면서 병준님만의 메소드 배치 컨벤션을 만들어보시는 것도 좋을 것 같아요.
(정해진 컨벤션은 따로 없습니다.)

2024-10-01 12:53 UTC, merged