🚀 3단계 - 자동차 경주
next-step/java-racingcar pull request #5686
Opened 2024-09-30 11:31 UTC by jonghyeonLeee

안녕하세요. 

3단계 미션을 진행했습니다. 

1799c72cbf106219964f7b2793ee5f7d6ba0cd10 커밋에서 랜덤하게 대시를 더하는 기능을 추가 하였는데, 
랜덤한 값은 어떤식으로 테스트를 진행하면 좋을지 궁금합니다 !

자바가 미숙하여 ㅜㅜ.. 다른 부분도 보이는대로 알려주시면 수정하도록 하겠습니다!

감사합니다.

2024-09-30 13:36 UTC, dhmin5693 requested changes
안녕하세요!

미션이 많이 어렵게 느껴지실 수 있는데요, 최대한 도와드리겠습니다.
우선 제가 드린 피드백 위주로 생각을 해보시고 수정하신 다음 다시 리뷰 요청주세요.

어려우시면 언제든지 DM 보내주셔도 좋습니다.
힘내세요!!

2024-09-30 13:36 UTC, dhmin5693 commented on src/main/java/com/warmup/step3/CarRacing.java
> +        int tryNumber = scanner.nextInt();
## 프로그래밍 요구사항
- 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외
    - 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
    - UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.
---

UI 로직은 분리해주세요.

2024-09-30 13:36 UTC, dhmin5693 commented on src/main/java/com/warmup/step3/CarRacing.java
> +        String[] carArray = makeStringArray(carNumber);
`ArrayList` 는 `List`를 배열의 형태로 구현한 콜렉션이지만 결국 근본은 배열입니다. 
또한 배열을 더 잘 사용하기 위한 기능의 집합이죠.

배열을 꼭 사용해야 하는 특별한 이유가 없다면 `List`를 사용하는게 가독성이나 유지보수 면에서도 유리합니다.

2024-09-30 13:36 UTC, dhmin5693 commented on src/main/java/com/warmup/step3/CarRacing.java
> +    }
메소드 하나에 모든 로직이 구현되어 있네요.
조금 더 객체지향적으로 분리하는 연습을 해보시는건 어떨까요?

예를 들어 자동차 하나는 `RacingCar` 혹은 `Car` 로 떼어낼 수 있어요.
자동차 경주는 `RacingGame` 같은 걸로도 분리할 수 있구요.

2024-09-30 13:36 UTC, dhmin5693 commented on src/main/java/com/warmup/step3/CarRacing.java
> +    }
무작위 테스트가 어렵다고 질문해주셨어요.

왜 어려울까요?
근본적인 이유는 "실행값이 매번 달라지기 때문" 입니다.
조금 더 파헤쳐보면 멱등성이라는 성질과도 연관이 있는 내용이에요.
코드 레벨에서의 멱등성은 주어진 매개변수가 변하지 않는다면 반환값도 달라지지 않아야 합니다.

하지만 랜덤은 반환값 자체를 예측하기 어렵다는 특성을 갖죠.
안타깝게도 어떻게 구현하던 이 특성 자체를 지울 수는 없습니다.

단, **직접 사용하지 않는다면** 무작위 로직을 감출 수 있습니다.
자바에 아직 익숙하지 않으시다 하니 힌트를 하나 드리면 **인터페이스**를 먼저 공부해보시면 좋아요.

이러한 특징을 약결합이라고 합니다.
Spring 등을 다루신다면 프레임워크 내부 구현이 대부분 인터페이스로 이루어져 있으며 약결합의 장점을 잘 이용하고 있습니다.

굉장히 어려운 부분이에요.
공부를 해도 잘 모르시겠다면 언제든 DM주셔도 좋습니다 :)

2024-09-30 13:36 UTC, dhmin5693 commented on src/test/java/com/warmup/step3/CarRacingTest.java
> +    public void isEquals_입력한_숫자만큼_문자열_배열_반환() {
메소드명보다는 `@DisplayName`을 조금 더 적극적으로 사용하시는걸 권장드립니다.

무엇에 관한 테스트인가를 표현하기엔 더 편리합니다.

2024-10-07 10:26 UTC, jonghyeonLeee commented on src/test/java/com/warmup/step3/CarRacingTest.java
> +    public void isEquals_입력한_숫자만큼_문자열_배열_반환() {
Test 코드들 모두 DisplayName을 추가하였습니다!

2024-10-07 10:29 UTC, jonghyeonLeee commented on src/main/java/com/warmup/step3/CarRacing.java
> +    }
[b0809f4](https://github.com/next-step/java-racingcar/pull/5686/commits/b0809f49727aa8e1d7750ba9f3adb6bb4a716428)
1. 인터페이스 추가하고 더미 클래스, 리얼 클래스로 구분했습니다.   
2. 더미 클래스에선 함수에서 의도한 리턴을 구현, 리얼 클래스는 실제 로직 및 리턴값을 구현했습니다.    
3. 더미 클래스 기반으로 테스트 코드를 작성했습니다. 

의도하신 내용인지 모르겠네요 ㅜㅜ 목업쪽과 인터페이스를 알아보다가.. 일단 구현했습니다. 
피드백 부탁드립니다.

2024-10-07 10:29 UTC, jonghyeonLeee commented on src/main/java/com/warmup/step3/CarRacing.java
> +    }
[5cce101](https://github.com/next-step/java-racingcar/pull/5686/commits/5cce1016b2e48d173ae00cb2176e3db88610798d)

메인 함수를 최대한 구분하여 구현했습니다!

2024-10-07 10:29 UTC, jonghyeonLeee commented on src/main/java/com/warmup/step3/CarRacing.java
> +        String[] carArray = makeStringArray(carNumber);
Car 객체 구현 후 리스트로 수정했습니다~!

2024-10-07 10:30 UTC, jonghyeonLeee commented on src/main/java/com/warmup/step3/CarRacing.java
> +        int tryNumber = scanner.nextInt();
[cebb31d](https://github.com/next-step/java-racingcar/pull/5686/commits/cebb31dd96d701a89d9c3532c348b029912e76d3)

UI로직 구현했습니다!

2024-10-07 10:40 UTC, jonghyeonLeee commented
안녕하세요! 피드백 주신 내용 반영했습니다. 
기존 코드를 그대로 사용하지 않고 객체지향 적으로 접근.. 해보고 패키지도 다시 구조를 잡아봤습니다. 
감사합니다!

2024-10-07 12:39 UTC, dhmin5693 approved these changes
안녕하세요.

되게 고민을 많이 하신게 코드에서 느껴지네요. 😄 
다만 약간 방향이 다른 것 같아 관련된 부분에서 리뷰를 남겨두었어요.
이번 미션은 충분히 수고하셨으니 일단 4단계 진행하시면서 꼭 참고해보셨으면 합니다.

궁금한 점 있으시면 언제든지 DM으로 질문해주세요.

2024-10-07 12:39 UTC, dhmin5693 commented on src/main/java/com/racing/utils/IRandomMove.java
> +public interface IRandomMove {
인터페이스명이 다소 부적절해 보입니다.

우선 I로 시작하는 형태는 헝가리안 표기법으로 알고 있는데 자바에선 사용하지 않구요,
인터페이스는 "이런 동작을 한다"고 안내한다는 느낌으로 가되 어떻게 움직일지는 구현체가 결정해야 합니다.
지금은 `Random`을 인터페이스명에 명시해버려서 움직임이 무작위라는걸 확정지어버린 느낌이거든요.

2024-10-07 12:39 UTC, dhmin5693 commented on src/test/java/racing/utils/DummyRandomMoveTestHelperTest.java
> +    }
무조건 false를 내리는 `DummyRandomTestHelper` 의 설명으로는 부적합하지 않을까요?

2024-10-07 12:39 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Car.java
> +    }
`IRandomMove` 가 약간 잘못 사용되고 있는 느낌입니다.

1. 인터페이스로 분리할 고민을 하신 건 굉장히 좋은 접근 방법입니다.
2. 다만 인터페이스를 통해 무작위 등 개발자가 통제하기 어려운 로직을 분리하면 개발자의 의도대로 코드를 작성하기도 쉽고 테스트 작성도 훨씬 편리합니다.
    - 지금은 `Car`가 `IRandomMove`를 구현하는 구조입니다. 그리고 그 구현체 메소드에는 `RacingHelper` 를 직접 의존합니다.
    - 따라서 이 로직에는 무작위 로직이 강하게 결합되어 있습니다.
    - 약하게 연결하는 구조로 바꾸어보세요. 인터페이스를 통해 간접적으로 의존하면 됩니다.

2024-10-07 12:39 UTC, dhmin5693 commented on src/main/java/com/racing/utils/DummyRandomTestHelper.java
> +public class DummyRandomTestHelper implements IRandomMove {
실제로는 사용하지 않는 클래스네요.
테스트용도로 쓰려면 test 패키지 아래에 작성하는게 더 맞습니다.
그리고 테스트 자체도 큰 의미는 없어보입니다.

인터페이스의 활용이 약간 애매하여 생긴 문제같아요.
`Car`에 남긴 리뷰를 확인하여 수정해보시기 바랍니다.

2024-10-07 12:39 UTC, dhmin5693 commented on src/main/java/com/racing/utils/RacingHelper.java
> +    }
`IRandomMove`의 구현 메소드는 이 메소드가 더 적절하지 않을까요?

2024-10-07 12:39 UTC, merged