3 단계 - 자동차 경주
next-step/java-racingcar pull request #5690
Opened 2024-09-30 14:15 UTC by kdfasdf

안녕하세요 리뷰어님!
2단계 피드백 반영하였습니다.
3단계 리뷰 부탁드립니다!!

오늘 PR 보낼 수 있을 까 걱정했는데 보내게 되어서 다행이네요ㅎㅎ
객체지향적인 사고를 하는 것이 익숙하지 않아 이번 미션 체감 난이도가 좀 있었던 것 같습니다. feat :종료 UI 구현 커밋 이후 최대한 리펙토링을 해보았는데 아직 부족하거나 어색한 부분이 많은 것 같네요

질문 사항
이번에 자동차 전진 테스트코드를 작성하면서 getter 메서드가 필요해서 프로덕션 코드에서 사용하지 않았던 getter 메서드를 추가해주었는데요. 이런경우 객체의 설계를 다시 고민해봐야 할까요??

2024-09-30 16:20 UTC, jinyoungchoi95 requested changes
안녕하세요 대호님 😄

3단계 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    }
> 이번에 자동차 전진 테스트코드를 작성하면서 getter 메서드가 필요해서 프로덕션 코드에서 사용하지 않았던 getter 메서드를 추가해주었는데요. 이런경우 객체의 설계를 다시 고민해봐야 할까요??

getter를 지양하라는 것은 도메인 로직을 필요한 도메인에 두지 않고 getter로 가져와 외부에서 로직을 실행하는 코드를 지양하라는 것인데요. 특정 값이 필요하다면 사용하셔도 좋을 것 같아요.

혹은 equals 재정의를 통해 객체 비교로 테스트를 하는 방법도 있고, junit에는 이러한 필드값을 테스트할 수 있는 방법도 제공하고 있으니 한번 찾아보시면 도움이 되실 것 같네요 😄

2024-09-30 16:20 UTC, jinyoungchoi95 commented on README.md
> +## 기능 목록
기능목록 👍 

만들어주신 각 클래스가 어떻게 동작하는지로 구분하여 정리해주셔도 좋을 것 같아요.

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +        System.out.println(location);
프로그래밍 요구사항의

> 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.

는 도메인코드에서 ui와 관련된 코드를 분리하는 것을 의미해요. "-"를 출력하는 것은 화면단의 요구사항이므로 Car는 단순히 현재 위치값을 반환하고 무엇을 출력할지는 View로 넘겨보면 좋을 것 같아요 😄

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    public static class Builder {
builder는 필드가 다양할때 매우 유용하게 사용되는데요. 다만 builder 자체가 결국 불변하게 생성할 수 있다보니 null이 들어갈 수 있는 불안정한 코드를 만들 수 있습니다. 현재는 `Builder`가 오히려 코드 복잡도를 올리는 것 같아보이네요 👀

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    Car(Builder builder) {
default나 protected는 결국 어떤 방법에서 접근이 가능하기 때문에 접근이 완전히 제어된다고 보긴 어렵습니다. 접근 제어에 도움을 주는 거죠.

가능하면 미션 내에서는 public과 private으로 접근 제어를 하면서 어떻게 불필요 메소드를 public을 제거하며 private을 테스트가능한 구조로 만들 수 있을 지 고민해보시면 많은 도움이 될 것 같아요 :)

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    public void move() {
`move()` 실행 시 위치가 변화하는지도 테스트하면 좋을 것 같네요 😄

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/Utils/RandomUtil.java
> +    public int getRandomValue(int num);
이미 클래스, 메소드 이름에 Random이라는 구현내용이 들어가있어 interface로 추상화되어있다고 보기는 어려울 것 같아요.

"랜덤한 숫자를 생성한다"에서 "숫자를 생성한다"를 추상화하고자하는 목적이 있다면 "숫자를 생성한다"로 interface 네이밍을 고민해보시면 좋을 것 같아요 :)

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/Utils/RandomGenerator.java
> +    Random random = new Random();
```suggestion
    private final Random random = new Random();
```
로 수정하면 더 안정적일 것 같아요 😄

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/Utils/InputUtils.java
> +    public static final String INPUT_NUMBER_OF_MOVEMENT = "시도할 회수는 몇 회 인가요?";
```suggestion
    private static final String INPUT_NUMBER_OF_CAR = "자동차 대수는 몇 대 인가요?";
    private static final String INPUT_NUMBER_OF_MOVEMENT = "시도할 회수는 몇 회 인가요?";
```
외부 호출이 없는 상수의 접근제어는 private으로 막는게 좋을 것 같네요

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/Utils/InputUtils.java
> +
```suggestion

```
불필요한 공백이 있네요 👀

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Vehicles.java
> +public class Vehicles {
`Car`의 List를 가진 의미로 단순히 `Cars`여도 좋지 않을까요?

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Vehicles.java
> +    List<Car> list = new ArrayList<>();
```suggestion
    private fianl List<Car> cars = new ArrayList<>();
```
1. 접근제어는 막아두는 것이 좋을 것 같아요 :)
2. 변수의 컬렉션을 네이밍할 때 변수명에 컬렉션의 타입을 명시하는 것은 지양하는 것이 좋아요.

[클린코드 2장. 의미 있는 이름 - 그릇된 정보를 피하라](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md#%EA%B7%B8%EB%A6%87%EB%90%9C-%EC%A0%95%EB%B3%B4%EB%A5%BC-%ED%94%BC%ED%95%98%EB%9D%BC)

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Vehicles.java
> +    RandomGenerator randomGenerator = RandomGenerator.getRandomGenerator();
1. 이걸 필드로 들고 있을 필요가 있을까요? 필요한 곳에서 파라미터로 주입하여주면 되지 않을까요?
2. 인터페이스로 잘 추상화해두셨는데 구현체를 들고 있을 필요는 없어보여요

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Vehicles.java
> +            System.out.println();
출력부는 마찬가지로 domain에서 분리하여주세요 :)

2024-09-30 16:20 UTC, jinyoungchoi95 commented on src/test/java/race/CarRaceTest.java
> +    @ValueSource(ints = {5, 10, 7})
테스트 케이스가 많이 있으면 좋은데 그것보다 중요한 것은 엣지케이스를 잘 판별하는 것이에요. 5, 10, 7은 케이스가 많기만할뿐 사실 5나 10 하나로 테스트해도 이 테스트의 엣지케이스를 충족한다면 많은 테스트 케이스가 오히려 가독성을 떨어뜨리기도해요.

2024-10-01 07:57 UTC, kdfasdf commented on src/main/java/race/vehicle/Car.java
> +    public static class Builder {
builder를 사용한 이유는 Car 클래스에서 location 변수의 타입을 StringBuffer로 사용하면 출력하기에도 조금 더 편할 것 같다고 생각한게 원인이었는데요. 
초기 상태인 "-" 도 매직넘버이서 INITIAL_CONDITION 으로 상수화 해주니 생성자를 사용하면 형변환해야하는 상황이 생기더라구요. 그래서 형변환을 Car 객체 내부에 숨기려고 builder를 사용한 것이었는데 좋지 못한 생각이었을까요?? 그냥 location 변수를 String으로 사용하는 것이 더 좋았을까요??

2024-10-01 08:05 UTC, kdfasdf commented on src/main/java/race/vehicle/Car.java
> +    }
넵 감사합니다!!  다른 방법들도 한번 찾아봐야겠네요!

2024-10-01 08:06 UTC, kdfasdf commented on src/main/java/race/vehicle/Car.java
> +    public void move() {
자동차_전진() 으로 작성해보았습니다!

2024-10-01 09:02 UTC, kdfasdf commented on src/test/java/race/CarRaceTest.java
> +    @ValueSource(ints = {5, 10, 7})
경계값만 남겨보았습니다!

2024-10-01 09:03 UTC, kdfasdf commented on src/main/java/race/vehicle/Vehicles.java
> +public class Vehicles {
변경했습니다!

2024-10-01 09:04 UTC, kdfasdf commented on src/main/java/race/vehicle/Vehicles.java
> +    List<Car> list = new ArrayList<>();
접근제어자를 꼭 확인해야겠네요... 위에서 언급해주셨던 접근제어자 모두 수정하였습니다!

2024-10-01 09:05 UTC, kdfasdf commented on src/main/java/race/Utils/RandomUtil.java
> +    public int getRandomValue(int num);
NumberGenerator라는 이름으로 바꾸어보았습니다!

2024-10-01 09:07 UTC, kdfasdf commented on src/main/java/race/vehicle/Car.java
> +        System.out.println(location);
ResultView로 분리해보았습니다!

2024-10-01 09:11 UTC, kdfasdf commented on src/main/java/race/vehicle/Vehicles.java
> +    RandomGenerator randomGenerator = RandomGenerator.getRandomGenerator();
위에 INITIAL_CONDION 이랑 randomGenerator은 list에 Car 인스턴스를 추가해주면서 builder에게 넘겨줄 인자들이었는데요. randomGenerator는 싱글톤으로 구현되어 있으서 getRandomGenerator()를 인자로 넘겨주었는데 INITIAL_LOCATION은 위에 언급했던 형변환 문제 때문에 Car 클래스 안으로 넣어보았습니다. 
사실 이번에 builder 부분이 스스로 의문이 들었던 부분이라 이 부분도 확신이 안서네요.

2024-10-01 09:33 UTC, kdfasdf commented on README.md
> +## 기능 목록
리펙토링이랑 피드백을 반영하면서 돌아보니 말씀해주신 것 처럼 세부 기능 목록을 각각 어떤 클래스가 하는지 분석했다면 덜 어렵지 않았을까 라는 생각이 들었어요.
하지만 명확히 구분했어도 지식과 경험의 한계로 잘못된 설계를 한 상황이라면 리펙토링 하는 과정에서 수정이 발생하는데요. (이번에 ResultUtils 와 ResultView가 그랬던 것 같습니다...) 이런 경우에 회사에서는 어떤 업무 싸이클로 흘러가는지 궁금합니다.
최근에 도메인 설계팀이 따로 있는 조직도 있다고 들어서 궁금하네요ㅎㅎ

2024-10-01 09:41 UTC, kdfasdf commented
안녕하세요 리뷰어님!!
피드백 주신 부분 일부 반영해보았습니다. 
피드백 반영하면서 정리된 생각이나 궁금한 점, 어려웠던 점 어떻게 반영했는지 이전 피드백에 남겨보았습니다. 확인해주시면 감사하겠습니다!!

2024-10-01 12:59 UTC, jinyoungchoi95 commented on README.md
> +## 기능 목록
미션하는 것과 크게 다르지 않은 것 같아요. 가능하면 설계단계에서 이후 수정이 자유로운 방법으로 설계하고 설계가 잘못되었다면 미션에서 코드 고치듯이 고치는거죠. 대부분 테스트를 기반으로 코드가 커버되어있기 때문에 설계가 변경되더라도 테스트를 통해서 자유롭게 코드 리팩터링을 진행하는 것 같네요.

프로덕트를 만들어가는 조직 내에서 설계와 개발을 모두 담당하기 때문에 따로 분리되는 경우는 저도 처음 들어보는 것 같네요 🤔

2024-10-01 13:04 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    public static class Builder {
"-" 조차도 UI를 담당하는 로직이기 때문에 location을 다른 방식(int 등)으로 저장하는 것이 맞습니다. 화면의 요구사항이 *로 출력하는 것으로 변경된다면 화면의 요구사항으로 인해 서버 도메인 코드가 변경되는 일이 되는 것이니까요.

Builder는 객체 내부에 숨기기위해서 사용한다기보단 생성자의 매개변수가 너무 많아져 이를 구분짓기 힘든 것(예를들면 String String String으로 들어오면 어디에 어떤 값을 넣어야하는지 판단이 힘듦)을 해결하기 위해 사용하는 것이지 말씀하신 방법과는 조금 멀어보여요.

[[이펙티브 자바] 아이템 2. 생성자에 매개변수가 많다면 빌더를 고려하라](https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-2.-%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EA%B0%80-%EB%A7%8E%EB%8B%A4%EB%A9%B4-%EB%B9%8C%EB%8D%94%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)

2024-10-01 13:11 UTC, jinyoungchoi95 approved these changes
안녕하세요 대호님 😄

피드백 잘 반영해주셨네요 👍 몇가지 남겨둔 코멘트는 다음 미션 진행하면서 함께 반영부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/Utils/NumberGenerator.java
> +    public int getValue(int num);
```suggestion
    int getValue(int num);
```
인터페이스에 public은 제거되어도 될 것 같네요 😄

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/playGame.java
> +}
[eol](https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/)이 발생하고 있어요. 개발환경에 따라 에러가 발생하지 않을 수는 있으나 가능하면 제거해주시는 것이 좋습니다.

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    public static final String INITIAL_LOCATION = "-";
위에서 말씀드린 것처럼 "-"도 ui의 요구사항이므로 분리부탁드려요 :)

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Car.java
> +    private NumberGenerator numberGenerator;
```suggestion
    private final StringBuffer location = new StringBuffer(INITIAL_LOCATION);
    private final NumberGenerator numberGenerator;
```
로 불변하게 만들 수 있을 것 같네요 😄

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/vehicle/Cars.java
> +        return this;
return할 필요는 없지 않을까요?

2024-10-01 13:11 UTC, jinyoungchoi95 commented on src/main/java/race/View/ResultView.java
> +            separateRound();
`ResultView`는 print와 같은 출력만을 담당하는 클래스이므로 실제로 move와 같은 동작은 domain 코드에서 실행하도록 수정하면 좋을 것 같아요 :)

2024-10-01 13:11 UTC, merged