4단계 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5696
Opened 2024-09-30 18:29 UTC by sinyebin

안녕하세요 자동차 경주(우승자) 리뷰부탁드립니다!
아직 어떤 항목을 테스트 코드를 만들어야 할지 감을 잡기가 어렵습니다.
혹시 테스트 코드를 만드는 메소드를 선정하는 기준이 있을까요?

2024-10-01 12:21 UTC, mskangg requested changes
4단계도 잘 구현해주셨어요! 👏 
몇가지 피드백 남겨드렸는데, 확인부탁드릴게요! 🙇

2024-10-01 12:21 UTC, mskangg commented on src/main/java/racingcar/Car.java
> +        validateCarName(carName);
생성자에서 잘 검증해주셨네요 👍

2024-10-01 12:21 UTC, mskangg commented on src/main/java/racingcar/Race.java
> +    public List<String> getWinnerCarList() {
우승자를 구할 때, `setMaxDistance()` 를 호출하는 것은 어떨까요?
`Race`에게 메세지를 보낼 때 `우승자를 알려줘` 라고 했으니, 우승자의 로직은 `setMaxDistance()` 가 필수로 보여져요!
현재 최대 포지션을 찾고 구하는 로직을 `Race`의 관리할 책임으로 두었으니 이 구조가 조금더 자연스러워보여요!

예빈님은 어떻게 생각하시나요? 🤔

2024-10-01 12:21 UTC, mskangg commented on src/main/java/racingcar/RacingCar.java
>          for (int i = 0; i < race.getTryCount(); i++) {
이전 단계의 코드지만, 가이드는 드려야할것 같아서 피드백 드릴게요!

[📖 객체지향 생활 체조 원칙](https://edu.nextstep.camp/s/KIXpLZ6i/ls/TOMG8TDx)
- 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

처럼 게터를 사용하지 않고 구현해보시는건 어떨까요?
코드를 전반적으로 살펴보면 객체안의 있는 값을 대부분 꺼내서 로직을 구현하고 계신것 같아, 피드백 드려봅니다 😊

2024-10-04 08:37 UTC, sinyebin commented on src/main/java/racingcar/README.md
> ++ [x] 우승자 확인
감사합니다! 
이번에 체크리스트를 만들어서 적용해봤는데 대부분의 public 코드를 검증할 수 있는것 같습니다.
추가적으로 질문사항이 있습니다.
1.  void로 return 하는것에도 test코드를 만드시는건가요?
2. 테스트를 위해 private가 아닌 public으로 선언해도 되는걸까요?
이번 같은 경우 input값이나 random 값을 어떻게 처리해야 테스트 코드에 적용하는지 잘 모르겠어서
인위적으로 값을 넣기 위해서 
`    public void setGoCar(int randomNum) {
        if (randomNum >= 4) {
            distance += 1;
        }
    }`
이렇게 public으로 설정하였습니다.

2024-10-04 08:41 UTC, sinyebin commented on src/main/java/racingcar/Race.java
> +    public List<String> getWinnerCarList() {
저는 단계별로 생각해서 
1. maxDistance 구하기 
2. 구한값으로 우승자 구하기
이런 방식으로 생각했는데 굳이 2가지를 나누지 않고
우승자를 구할때 가장 많이 이동한 거리를 구하는게 좋아보이네요!

2024-10-04 08:44 UTC, sinyebin commented on src/main/java/racingcar/RacingCar.java
>          for (int i = 0; i < race.getTryCount(); i++) {
getter를 사용하고 있는 부분이 많았었네요;

2024-10-04 08:45 UTC, sinyebin reviewed
피드백 반영하였습니다!

2024-10-04 08:47 UTC, sinyebin reviewed
추가 수정하여 올렸습니다.

2024-10-05 00:49 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요 👍 
질문에 대한 답변과 소소한 피드백 남겨드렸으니, 확인부탁드립니다 🙇
그럼 마지막 단계도 화이팅 🔥

2024-10-05 00:49 UTC, mskangg commented on src/main/java/racingcar/Car.java
> +    public void setGoCar(int randomNum) {
https://github.com/next-step/java-racingcar/pull/5696#discussion_r1787368942

테스트를 위해 public 으로 변경하기 전에 테스트하기 어려운 구조기 때문에 이런경우가 아닐까? 라는 생각을 우선 하셔야합니다 :)

외부에선 `goCar()` 를 통해 전진이라는 메세지를 받고 있죠.
그렇기 때문에 값의 여부를 판단하고 전진하는 메서드(setGoCar)는 `private` 으로 선언되어있는 구조입니다.

그럼 이런 구조에서 `goCar(int randomNumber)` 로 메서드 시그니쳐를 변경한다면 굳이 `public` 으로 변경하지 않고도 테스트코드에서 활용이 가능해보여요!

만약, `getRandomNum()` 과 같이 랜덤을 강제하고 싶다면 `goCar(Random random)` 을 전달 받아서 구현하는 방법도 있습니다.
그럼 테스트 코드 클래스로
```java
public class FakeFixRandom extends Random {
    private int fixedNumber;

    public int nextInt(int bound){
        return fixedNumber;
    }
}
```

원하는 고정값만 리턴하는 클래스를 만들어 `goCar(fakeFixRandom)` 로 의도된 고정값을 넘겨주어 테스트를 할 수 있는 구조로 변경하는 방법도 있습니다.

위처럼 private 인 경우 테스트를 하고 싶다면 리팩토링 신호로 판단하고 구조를 의심해볼 필요도 있다는점을 말씀드리고 싶었어요 😄

2024-10-05 00:49 UTC, mskangg commented on src/main/java/racingcar/Race.java
> +    public List<String> getWinnerCarList() {
`getWinnerCarList` 로 메서드명을 작성했으니 `List<Car>` 를 리턴하는게 자연스러워 보이네요 :)

2024-10-05 00:49 UTC, merged