Step3 : 3단계 자동차 경주 게임
next-step/java-racingcar pull request #5710
Opened 2024-10-01 14:39 UTC by Slowth-KIM

## 구현 내용
- 하나의 클래스와 메서드에 여러 책임과 역할이 생기지 않도록 구현해보려고 했습니다.
- Tell, Don't Ask 원칙에 맞게 작성해보려고 했는데 생각보다 어렵기도 해서 더 수정해야할 내용이 있다면 말씀 주시면 감사하겠습니다.
- 객체를 설계할 때 보통 어떤 방식으로 접근하시나요?
   - 탑다운 형식으로 하는지? 객체 설계하는 부분이 많이 어렵더라구요.

2024-10-01 23:19 UTC, csh0034 requested changes
3단계 전략패턴 적용 및 컨트롤러 추가
잘해주셨네요 💯 
몇가지 코멘트 남겨두었는데 확인부탁드려요!

2024-10-01 23:19 UTC, csh0034 commented on README.md
> +## 자동차 경주 게임 학습 테스트 목록
목록 작성후 커밋마다 체크해 나가신점 좋네요 👍

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/racingcar/MoveStrategy.java
> +public interface MoveStrategy {
전략패턴 인터페이스 추가 💯
`@FuntionalInterface` 에 대해서 학습후 적용해보는것도 좋을것 같습니다.

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/racingcar/CarPosition.java
> +public class CarPosition {
원시값 wrapping 👍

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/racingcar/RacingCars.java
> +public class RacingCars {
컬렉션을 wrapping 하는 일급컬렉션 형태 잘 구현해주셨네요 💯

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/racingcar/RacingCars.java
> +    public void addCar(MoveStrategy strategy) {
addCar 가 호출되지 않으면 RacingCar 가 존재하지 않게 됩니다.
생성자/정적팩토리메서드 등을 활용하여 객체 생성시 초기화도 같이 수행하도록 해볼수 있을것 같아요!

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/RacingGameController.java
> +public class RacingGameController {
컨트롤러 구현 잘해주셨네요.
다만 현재 main 메서드가 없어 실행해볼수가 없네요.
추가해보시면 좋을것 같습니다.

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/ConsoleInputView.java
> +            return readPositiveNumber(); // 재귀적 호출
검증 실패시 재입력 처리 👍

2024-10-01 23:19 UTC, csh0034 commented on src/main/java/racinggame/racingcar/CarPosition.java
> +    public boolean isAtStart() {
해당 메서드는 최종적으론 테스트코드에서 호출하기 위함인데 
꼭 필요한걸까요? 🤔

2024-10-01 23:19 UTC, csh0034 commented on src/test/java/racinggame/RacingGameInputViewTest.java
> +class RacingGameInputViewTest {
`모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외`

이미 추가를 해주셔서 그대로 두어도 되지만 ui 에 대한 테스트는 수행하지 않으셔도 됩니다!

2024-10-01 23:25 UTC, csh0034 commented
우선 보통 도메인(핵심로직) 에 대한 단위테스트는 실제 테스트하려는 클래스와 동일한 패키지구조를
테스트 패키지에 생성하며 뒤에 Test 를 추가하는것이 일반적입니다.

- main/java.racinggame.racingcar.CarPosition
- test/java.racinggame.racingcar.CarPositionTest

이에 맞춰서 도메인별 단위테스트를 분리해보는걸 추천드려요.

추가로 객체를 설계할때는 여러 방법이 있는것 같아요.
앞으로의 미션에서 책임(인터페이스)주도 설계 또는 in->out, out->in 방식 등을 학습하게됩니다.

저의 경우엔 요구사항의 복잡도에 따라 다르게 접근하지만 가능하면 요구사항으로부터 
핵심 비지니스로직을 처리하는 대상을 설계한후에 원시값/문자열 wrapping 은 필요한 경우 진행하고있습니다.

2024-10-02 01:19 UTC, Slowth-KIM commented on src/main/java/racinggame/RacingGameController.java
> +public class RacingGameController {
RacingGame 이라는 클래스를 추가하고, 그 안에 main 메서드를 추가했습니다.

2024-10-02 01:27 UTC, Slowth-KIM reviewed
> 이번 테스트 코드 작성시 어떤 식으로 단위를 나눌 지 고민하다가 
자동차 생성, 이동, 게임 컨트롤러라는 큰 행위를 기준으로 나눴는데 도메인으로 나누는 방법은 생각하지 못했네요.
다음 미션때는 도메인 단위로 분리해보도록 하겠습니다.

- 도메인 단위로 분리할 때 너무 잘게 쪼개지거나 너무 적게 테스트가 들어가게 되는 경우는 어떻게 처리하시나요?

2024-10-02 01:27 UTC, Slowth-KIM commented on src/main/java/racinggame/racingcar/CarPosition.java
> +    public boolean isAtStart() {
놓친 부분이네요 삭제 처리했습니다.

2024-10-02 01:27 UTC, Slowth-KIM commented on src/main/java/racinggame/racingcar/MoveStrategy.java
> +public interface MoveStrategy {
제가 자바8 이후의 문법과 객체지향은 아직 익숙하지 않아서 위와 같은 어노테이션은 처음 보는데 보통 이후의 문법 사용법을 숙지하려면 어떤 걸 보는게 좋을까요?

2024-10-02 14:41 UTC, csh0034 approved these changes
리뷰 반영 잘해주셨네요!
다음단계 에서 뵙겠습니다 😄

2024-10-02 14:41 UTC, csh0034 commented on src/main/java/racinggame/racingcar/RacingCars.java
> +    public static RacingCars create(int numberOfCars, MoveStrategy moveStrategy) {
정적 팩토리 메서드 사용하여 잘 처리해주셨네요 💯

2024-10-02 14:41 UTC, csh0034 commented on src/main/java/racinggame/racingcar/RacingCars.java
> +    public List<RacingCar> getCars() {
사용하지 않는 코드네요!

2024-10-02 14:41 UTC, csh0034 commented on src/main/java/racinggame/RacingGameController.java
> +public class RacingGameController {
5단계 에서 고민할 부분이긴하지만 미리 구현해주셔서 코멘트 남깁니다.

컨트롤러가 main 메서드를 가지면 되지 않을까요? 🤔

2024-10-02 14:41 UTC, csh0034 commented on src/main/java/racinggame/ConsoleResultView.java
> +        String result = POSITION_MARKER.repeat(adjustedPosition == MIN_POSITION ? 1 : adjustedPosition);
요구사항의 실행 결과를 보면 5회 수행시에 5번을 출력했습니다.
맨처음 race 에서 모두 전진하였기 때문에 대쉬가 모두 존재하는데요.

현재 출력시 조정을 하는 코드가 있어 무조건 전진한것 처럼보입니다.
요구사항과 동일하게 출력할수있게 해보시면 좋을것 같아요!

2024-10-02 14:41 UTC, merged

2024-10-02 14:44 UTC, csh0034 commented
> 도메인 단위로 분리할 때 너무 잘게 쪼개지거나 너무 적게 테스트가 들어가게 되는 경우는 어떻게 처리하시나요?

내가 테스트하려는 대상을 독립적으로 검증 가능하기 때문에 잘게 쪼게졌다는건 책임이 명확하며 SRP 를 지키게
되는 구조라고 볼 수 있기 때문에 좋다고 생각해요.

클린코드 9장, 단위 테스트 부분 보시면 도움되실것 같습니다.