Step3 자동차 경주
next-step/java-racingcar pull request #5747
Opened 2024-10-03 15:36 UTC by hyeyoungs

안녕하세요~ 3단계 리뷰 요청드립니다. ☺️

아직 기능사항 분리가 조금 어렵고,
클래스 설계 이후 단위테스트 코드 작성을 먼저하는게 어려운 것 같습니다.
어떻게 하면 TDD를 더 쉽게 접근할 수 있을까요?

2024-10-03 23:51 UTC, dhmin5693 commented
> 아직 기능사항 분리가 조금 어렵고, 클래스 설계 이후 단위테스트 코드 작성을 먼저하는게 어려운 것 같습니다. 어떻게 하면 TDD를 더 쉽게 접근할 수 있을까요?

기능 분리는 원래 어렵습니다. 연습으로 접근하는게 제일 좋다고 생각해요.
리뷰를 하고 있는 저 역시도 처음엔 별반 다르지 않았거든요.

그리고 TDD 자체도 원래 어려운 내용이에요. 그러다보니 생산성도 약간은 떨어지는 느낌을 받게 되죠.
TDD 방법론 자체를 연습하셔도 좋지만 저는 이 과정을 통해 적절한 코드 분리와 책임의 할당에 더 집중해서 공부하시는게 좋다고 생각합니다.

그 이유를 말씀드리면, TDD가 어려운 이유는 기능 분리부터 이미 어려움을 겪기 때문이거든요.
앞 단계에서 어려움을 느끼는데 뒷 단계를 바로 할 수는 없잖아요?

너무 조급하게 접근하지 마시고, 이 과정을 통해 하나하나 배워간다는 마음가짐으로 나아가시면 될 것 같습니다 :)

2024-10-03 23:51 UTC, dhmin5693 requested changes
안녕하세요.

코드는 깔끔하고 적당하게 잘 작성해주셨는데요,
아주 약간의 프로그래밍 요구사항 위반이 있어 수정 요청 드립니다.

질문에 대한 답변도 남겨두었으니 꼭 확인해주세요.

2024-10-03 23:51 UTC, dhmin5693 commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
randomNumber가 필드일 필요가 있나요?

`Movement` 하나에서 isMove() 는 항상 같은 값이 나오게끔 의도하신 내용인가 궁금하여 여쭤봅니다.

2024-10-03 23:51 UTC, dhmin5693 commented on src/main/java/racingcar/RacingGame.java
> +        run(carCount, racingCount);
UI 로직은 분리해주세요.

---

## 프로그래밍 요구사항
- 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외
    - 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
    - UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

2024-10-03 23:51 UTC, dhmin5693 commented on src/main/java/racingcar/Car.java
> +    public void move(boolean isMove) {
무작위의 역할 분리 👍

2024-10-04 01:31 UTC, hyeyoungs commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
안녕하세요~ 리뷰 감사합니다.
Movement 테스트 코드를 추가할 때, randomNumber값 조절하려구 필드로 두었습니다.
곰곰이 생각해보니, 필요한 값을 생성할 때 주입하는 방법으로 하면 될 것 같아서 이렇게 수정하려고 합니다.
이 방법보다 더 좋은 방법이 있을까요?

2024-10-04 01:32 UTC, hyeyoungs commented on src/main/java/racingcar/RacingGame.java
> +        run(carCount, racingCount);
로직 분리했습니다. 감사합니다. 😆

2024-10-04 01:32 UTC, hyeyoungs commented
답변 감사합니다.
과정을 통해 적절한 코드 분리와 책임의 할당에 더 집중해보겠습니다.
단계를 알려주셔서 감사해요 ☺️

2024-10-04 06:56 UTC, hyeyoungs commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
ㄴ 변하는 값에 대한 가장 괜찮은 접근법은 런타임 의존성과 컴파일 타임 의존성을 다르게 하는 방법이 있다는것을 찾게 되었습니다.
그래서 TestMovement, RandomMovement 만들어서 의존성 역전으로 적용해보았습니다. 😄

2024-10-04 06:56 UTC, hyeyoungs commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
1. 보통 변하는 값은 다 추상화를 시키는 걸까요?
2. 실무에서 추상화는 보통 Repository 단에서 많이 하고 있는데,  
추상화는 `랜덤, 시간, 데이터베이스/외부 API에 접근해서 데이터 가져오는 것` 처럼 변하는 값이나 외부에서 데이터를 가져올 때 한다고 이해하면 되는지 궁금합니다. 

(생각해보니 외부에서 가져올 때 추상화를 하면, 데이터 가져오는 방식이 바껴도 일관된 방식으로 데이터를 요청해서 서비스단과 같이 상위 비즈니스 로직 코드를 수정할 필요가 없긴 할 것 같아요)

2024-10-04 07:50 UTC, dhmin5693 commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
아시겠지만 개발 업무에서 무조건이라는건 없어요.
일반적으로 가장 많이 쓰이는 사례는 `LocalDateTime.now()` 일건데, 매 호출마다 현재 시간이 계속 바뀌기 때문에 보통 이런 방법을 사용합니다.

1. API request 등 최상단 객체에서 주입받은 값을 그대로 사용한다.
2. controller 에서 1회만 생성하여 하위로 내려보내는 형태로 사용한다.
3. 별도의 추상화 클래스를 두고 사용한다.

1, 2를 보시면 아시겠지만 반드시 추상화하고 있지는 않구요,
이 값을 주요 로직으로부터 분리하기만 하면 됩니다.

분리하는 이유는 저런 값이 로직 내부에서 직접 생성되면 개발자가 로직을 직접 통제하기 어렵기 때문이거든요.

만약 시간 기준을 now로 생성해서 사용하는 API가 있고 어제 실행되었던 API에서 오류가 있어 어제 날짜로 실행해보고 싶은 경우가 있다고 한다면 어떨까요?
시간 자체를 건드릴 수 없어서 무조건 현재 기준의 결과만 주겠죠?

2024-10-04 07:52 UTC, dhmin5693 approved these changes
반영도 잘 하셨고 내용 이해도 매우 잘 해주신 것 같습니다 👍 
다음 단계 진행해주세요.

2024-10-04 07:52 UTC, dhmin5693 commented on src/main/java/racingcar/Movement.java
> +public interface Movement {
별도로 말씀드린 부분은 아닌데 추상화까지 하셨네요!
좋습니다 👍

2024-10-04 07:52 UTC, dhmin5693 commented on src/main/java/racingcar/RandomMovement.java
> +public class RandomMovement implements Movement {
이렇게 작은 단위로 추상화를 하게 되면 테스트가 어렵거나 통제가 어려운 조각을 매우 작은 단위로 관리할 수 있다는 장점이 생깁니다.

항상 내 코드를 스스로 통제할 수 있는게 좋다는 내용만 기억하시면 돼요.

2024-10-04 07:52 UTC, dhmin5693 commented on src/main/java/racingcar/TestMovement.java
> +public class TestMovement implements Movement {
테스트용 👍

2024-10-04 07:52 UTC, merged

2024-10-04 12:45 UTC, hyeyoungs commented on src/main/java/racingcar/Movement.java
> +    int randomNumber =  new Random().nextInt();
감사합니다.
예시를 들어서 설명해주신 덕분에 이해가 되었어요 ☺️
개발 업무에서 '무조건'이라는 게 없다는 말이 확실히 와닿고
상황에 맞춰 유연하게 설계하고 테스트할 수 있는 방식이 중요하다는 걸 다시 한 번 느끼게 돼요 🚀
자세하게 리뷰해주셔서 감사합니다.