Step3  3단계 - 자동차 경주
next-step/java-racingcar pull request #5751
Opened 2024-10-04 08:05 UTC by wiseongjun

Step3
## 기능 요구사항

- 초간단 자동차 경주 게임을 구현한다.
- 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
- 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.

## 구현 한 기능사항

1. 자동차는 입력받은 n대 만큼 생성됨.
2. 자동차는 입력받은 n번 만큼 이동을 시도함.
3. 자동차는 n번의 이동 시도 중 Random값이 4 이상일 때 이동함.
4. 입력이 이상할경우 익셉션을 발생시킴.

2024-10-04 11:33 UTC, catsbi requested changes
성준님 3단계 미션 빠르게 PR 해주셨네요. 👍 

몇 가지 고민해보면 좋을 부분들이 있어 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-10-04 11:33 UTC, catsbi commented on src/main/java/step3/domain/Car.java
> +		}
4라는 값 역시 왜 randVal이 4이상이어야 전진인지 이해하기 힘들 수 있어요. 이런 매직넘버는 상수로 분리하여 가독성 향상을 꾀해볼 수 있을 것 같네요. 

그리고 this.position++;은 만약 해당 자동차의 속도가 1이 아니라 2여서 position이 2씩 늘어날 수도 있을 것 같은데 move()나 함수로 만들어서 실제 이동하는것만 책임지는 함수를 만들어보면 어떨까요?

2024-10-04 11:33 UTC, catsbi commented on src/main/java/step3/service/RacingGame.java
> +public class RacingGame {
이 객체는 현재 controller / service 계층이 뒤섞여있고, + 상태를 가지는 객체(stateful object)로 보입니다.

미션 프로그래밍 요구사항을 보면 UI 계층은 테스트를 하지 않는다고 하고 있죠. 
그럼 이 객체는 테스트를 해야할까요 말아야할까요? 

그리고 cars, moveCount과 같은 상태를 가지고 있기 때문에 해당 객체는 재사용성이 떨어지는 객체로 매 번 새로 만들어줘야 하는 객체로 보입니다. 

도메인이 아닌 service나 controller와 같은 중계 계층은 무상태(stateless)일수록 높은 재사용성을 가지기 때문에 권장되는 설계입니다. 

이를 고려해서 컨트롤러와 서비스계층을 분리하고, 무상태 설계를 해보면 어떨까요?

2024-10-04 11:33 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +		System.out.println("");
System.out 을 이용한 출력은 간단한 디버깅을 제외하고는 권장되지 않습니다. 그 이유가 뭘까요?

2024-10-04 11:33 UTC, catsbi commented on src/test/java/step3/service/RacingGameTest.java
> +		racingGame.setRaceInfo(carCount, 1);
setter를 이용한 값 설정으로 객체 초기화 하는 방식을 java beans pattern이라 하는데, 현재로썬 거의 사용하지 않는 안티패턴이에요. 
객체의 불변성을 떨어트려 위변조에 취약한 구조를 가지게 되거든요

2024-10-04 13:43 UTC, wiseongjun commented on src/main/java/step3/domain/Car.java
> +		}
매직넘버 상수로 하는 습관 들이겠습니다!
moveForward 함수와 speed 변수를 만들어서 speed만큼 움직이게 변경했습니다. 
확장성을 생각해서 개발하는 습관도 만들겠습니다!

2024-10-04 13:45 UTC, wiseongjun commented on src/main/java/step3/view/ResultView.java
> +		System.out.println("");
일단 성능문제가 있고 로깅 라이브러리를 사용하는게 에러메시지나 로그들을 더 관리하기 쉽기 때문입니다.

2024-10-04 13:45 UTC, wiseongjun commented on src/test/java/step3/service/RacingGameTest.java
> +		racingGame.setRaceInfo(carCount, 1);
생성자에서 파라미터 받아서 불변성을 유지하게 변경시켜봤습니다.

2024-10-04 15:47 UTC, wiseongjun commented
리뷰사항 적용은 했는데 아직도 긴가민가한 부분이 많아요 ㅜㅜ..
1. stateless 한 방향으로 하려고했더니 race랑 result는 관계없는 동작인것같은데 
관리하려면 state가 있어야 할것 같다는 생각이 들었어요.
2. return되는 int[][]의 값을 파악하기 힘들어요. (클래스로 만들던가 해야할까요?)
3. view에 필요한 result값으로 service TEST에 사용하는것도 애매한것 같아요. 
자동차가 올바르게 생성됐는지 테스트하려면 지금은 result값을 갖다쓰고있는데
getCarSize 같이 테스트만을 위한 함수를 만들어야 할까요?

2024-10-05 12:15 UTC, catsbi requested changes
성주님 3단계 피드백 반영 빠르게 해주셨네요. 
그런데 현재 좀 더 고민해보면 좋을 포인트들이 있어서 코멘트 남겨드렸으니 확인 부탁드립니다! 

그리고 질문에 답변드리자면, 
1. 서비스에서 경주(race)가 수행되고 그 결과를 반환하는건 상관없는 행위는 아닌 것 같아요. 매 라운드마다 각 자동차의 경주 기록을 저장해서 레이스 종료 후 해당 기록을 반환해야하는건 별도 상관없는 동작으로 보이진 않습니다. 
2. 네 굳이 알고리즘 문제가 아니라면 이차원 배열보다는 Collection API를 활용해주시면 좋을 것 같습니다. 
3. 이 질문이 발생하는 이유는 race는 경주임에도 자동차 생성책임을 같이 가지고 있기 때문인데요. 자동차 생성을 책임지는 함수가 분리되어 있다면, 그 함수를 테스트하면 되지 않을까요?  테스트를 작성할 때는 여러 조건에 따른 테스트 커버리지를 고민하면서 작성하면 좋은데요. 다음 글을 참고하시면 좋을 것 같습니다. https://catsbi.oopy.io/7c084479-c9d0-44a1-acb9-f6b43a19e332

2024-10-05 12:15 UTC, catsbi commented on src/main/java/step3/domain/Car.java
> +		if (input >= MIN_MOVE_VALUE) {
매직넘버를 상수로 분리하니 가독성은 좋아진것 같네요. 그런데, 현재는 매개변수가 특정 값 이상일 경우 전진한다는 하나의 비즈니스 로직만을 가지고 있는데, 만약 자동차별로 2의 배수인경우, 3의 배수인경우에만 전진하거나, 오전에는 2의 배수, 오후에는 3의 배수만 전진하는 식으로 전진에 대한 조건이 유동적으로 변경되는경우 어떻게 리팩토링을 해볼 수 있을까요?

2024-10-05 12:15 UTC, catsbi commented on src/main/java/step3/service/RacingGame.java
> +	public static int[][] race(int carCount, int moveCount) {
굳이 2차원 배열을 사용해야할까요? 

경주에 대한 기록을 하는 RacingHistory 객체를 만들어서 거기에 매 라운드별 라운드 값과, 각 자동차의 기록을 저장하면 되지 않을까요?

2024-10-05 12:15 UTC, catsbi commented on src/main/java/step3/service/RacingGame.java
> +	private static int[] moveCars(Car[] cars) {
moveCount가 매우 높은 값일 경우 Random 객체 생성을 매번 새로 해야할까요? 불필요한 객체 생성을 피해주세요!

그리고 현재 자동차의 전진에 대한 조건을 서비스 계층에서 모두 책임지고 있는데, 그렇게되면 실제 도메인 계층은 도메인이 아닌 VO에 더 가까워집니다. 

서비스의 주 목적은 비즈니스 로직 진행을 위한 각 도메인 오케스트레이션인데요. 이 함수가 임의의 랜덤값을 가지고 전진하는게 아니라 좀 더 유동적으로 유연성과 확장성을 가지는 로직으로 추상화해볼순 없을까요? 

```java
private static List<RacingHistory> moveCars(List<Car> cars) {
    List<RacingHistory> racingHistories = new ArrayList();
    for (Car car: cars) {
        car.move(moveStrategy);
        RacingHistory history = RacingHistory.from(car);
        racingHistories.add(history);
    }

    return racingHistories;
}
```

정말 대략적인 수도코드를 작성한다면 이런식으로도 가능할 것 같네요.

2024-10-05 12:15 UTC, catsbi commented on src/main/java/step3/view/ResultView.java
> +		System.out.println("");
System.out을 권장하지 않는다는건 다른 방법으로 출력을 해보라는 피드백이였습니다. 
StringBuilder나 StringBuffer를 사용해보는건 어떨까요?

2024-10-05 12:15 UTC, catsbi commented on src/test/java/step3/service/RacingGameTest.java
> +		assertThat(car.getPosition()).isNotEqualTo(prevPosition);
하나의 테스트 케이스에서 여러 경우가 동시에 테스트되고 있어요 이러면 단위테스트라고 하기가 애매해지고, 이 테스트 케이스의 항목중 하나만 바뀌어도 다른 테스트까지 영향이 갈 수 있습니다.

2024-10-07 10:36 UTC, wiseongjun commented on src/main/java/step3/domain/Car.java
> +		if (input >= MIN_MOVE_VALUE) {
전략패턴으로 한번 구현해보겠습니다.

2024-10-07 13:10 UTC, wiseongjun commented
많이 미숙해서 아직도 잘 모르는 부분이 많지만 적어주신 힌트 덕분에 어찌저찌 수정 완료했습니다!
상세한 리뷰 덕분에 개발하면서 여러가지 고민을 할수있어서 너무 좋았습니다!
더 수정해야할 부분 있으면 코드 리뷰 부탁드립니다!

2024-10-07 19:40 UTC, catsbi approved these changes
성준님 계속된 피드백 열심히 잘 반영해주셨어요 👍 

몇 가지 피드백을 추가 하긴했는데, 반영은 다음 4단계 진행하면서 같이 해보는걸로 하시죠. 
머지하도록 하겠습니다!

2024-10-07 19:40 UTC, catsbi commented on src/main/java/step3/domain/Car.java
> +	private Integer position;
굳이 이유가 있는게아니라면 wrapper타입보단 primitive 타입을 권장드려요!

2024-10-07 19:40 UTC, catsbi commented on src/main/java/step3/domain/Car.java
> +		this.position += this.moveStrategy.getMovePosition(randVal);
randVal도 임의의 값 문자열에 의한 전진조건 평가인데 이러면 전진전략의 유연함과 확장성이 Int타입의 숫자로만 제한되어 의도한만큼의 확장성은 나오지 않을 것 같네요. 🤔  다음과 같은 방식도 고민해보세요!
```suggestion
	public void move() {
		if (movable()) { position += speed; }
	}
	.
	.
	.
	public boolean movable() {
	    return moveStrategy.movable();
	}	
		
```

2024-10-07 19:40 UTC, catsbi commented on src/main/java/step3/domain/CarAtDefaultStrategy.java
> +public class CarAtDefaultStrategy implements CarMoveStrategy {
자동차 전진전략을 RandomMovableStrategy나 DefaultRandomMoveStrategy등으로 지어서 랜덤값 생성에 대한 책임도 같이 가져도 무관할 것 같네요!

2024-10-07 19:40 UTC, catsbi commented on src/main/java/step3/domain/CarAtMorningStrategy.java
> +public class CarAtMorningStrategy implements CarMoveStrategy {
이건 제가 임의로 정한 전략일뿐이니 굳이 사용하지 않는 전략을 만드실 필요까진 없습니다 ㅋㅋㅋ 그래도 코드로 작성해본 연습은 👍

2024-10-07 19:40 UTC, merged