자동차 경주 5단계 리팩토링 코드 리뷰 요청드립니다.
next-step/java-racingcar pull request #5758
Opened 2024-10-04 15:24 UTC by JeonJe

자동차 경주 5단계 리팩토링 코드 리뷰 요청드립니다.

# 변경사항
---
1. 4단계에서 사용한 자동차 위치를 기록하는 CarRecord를 제거하였습니다. Car 이동 시 새로운 객체를 반환하도록 변경하였습니다.
2. 라운드 결과 목록을 가지고 있는 RoundRecords를 제거하였습니다. RoundRecords로 인해 코드가 좀 더 복잡하다고 느꼈습니다. Race 객체에서 ReoundRecord 리스트를 바로 사용하도록 하였습니다.
3. RoundRecord에서 해당 라운드의 가장 빠른 자동차 이름을 반환하지 않고 자동차 자체를 반환하도록 변경하였습니다. 자동차이름은 ResultView에서 찾도록 변경하였습니다.
4. 테스트 시 getter로 값을 비교하지 않고 객체 자체로 비교하도록 usingRecursiveComparison을 써보았습니다.
5. domain, view 패키지 적용하였습니다.

2024-10-05 07:37 UTC, nooose requested changes
항상 이전 리뷰를 잘 정리해 주셔서, 리뷰하는 데 큰 어려움이 없었습니다. 🥰
MVC 구조도 잘 잡혀있는 것 같아요.
몇 가지 코멘트 남겼으니 확인해 주시고재요청 부탁드립니다!

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/domain/Car.java
>      }
생성자 내에 유효성 체크가 없네요

```java
new Car("5글자이상5글자이상", -1);
```
private 이지만 내부적으로 위 코드가 실행되면 어떻게 될까요?

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/domain/Car.java
>          if (canMove(randomNumber)) {
move가 canMove를 호출하고 있으니,
move 아래에 canMove 메소드를 선언하는 것이 좀 더 가독성에 좋을 것 같습니다.

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/domain/Car.java
>          }
이름을 정의하는 데 있어서 유효성 로직이 많아진다면 
Car가 복잡해 질 수 있을 것 같아요.

지금 상황에서는 굳이 필요하지는 않지만
연습삼아 name 원시값도 한번 객체로 포장해 보면 어떨까요?

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/domain/Car.java
> +    public Car move(int randomNumber) {
상황이 변경되어 랜덤이 아닌 외부 요인으로 인해 자동차의 움직임이 결정된다고 했을 때,
코드가 크게 변경될 것 같습니다. 테스트 코드도 같이 깨지게될테구요

`randomNumber`를 주입받는 대신 전략을 주입해 보면 어떨까요?

```java
public Car move(MoveStrategy strategy) {
    if (strategy.isMovable()) {
        // 이동
    }
}
```

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/domain/Car.java
> +    }
👍

2024-10-05 07:37 UTC, nooose commented on src/main/java/carracing/view/ResultView.java
> +                .collect(Collectors.toUnmodifiableList());
RoundRecords가 없어지면서 뷰에서 마지막 라운드 기록을 찾고 있는데, 
이 부분에 비즈니스 로직이 들어가 있는 것 같아 약간의 아쉬움이 있네요. 어떻게 생각하시나요?

해당 부분은 반영하지 않으셔도 괜찮습니다. 😊

2024-10-05 07:37 UTC, nooose commented on README.md
> +  - [x] 테스트가 가능한 부분에 대해 단위 텥스트 작성하기
요구사항 정리 깔끔하네요 👍
```suggestion
- [x] 5단계 요구사항
  - [x] 핵심 비지니스 로직을 가지는 객체를 domain 패키지로, UI 관련 패키지를 view 패키지로 나누기
  - [x] domain 패키지는 view 패키지에 의존하지 않도록 구현하기
  - [x] 테스트가 가능한 부분에 대해 단위 테스트 작성하기
```
😄

2024-10-05 07:42 UTC, nooose commented
> 4\. 테스트 시 getter로 값을 비교하지 않고 객체 자체로 비교하도록 usingRecursiveComparison을 써보았습니다.

👍👍
Car에 `equals` 를 오버라이드 했으므로 자동차 리스트를 비교하는 테스트 케이스에서는
`isEqualTo` 만 사용해도 될 것 같습니다.

2024-10-06 07:21 UTC, JeonJe commented on src/main/java/carracing/domain/Car.java
>          if (canMove(randomNumber)) {
public, private 메소드 배치 순서 관련하여 질문있습니다!
방법은 크게 2가지가 있다고 생각합니다.
1. public 메소드를 먼저 배치하고 private 메소드는 public 메소드에서 호출한 순서대로 배치한다.
2. 가독성을 고려하여 public 메소드와 prviate을 묶어서 배치한다.

1번 방식은 일관성이 있는 장점이 있고, 가독성 측면에서는 2번이 좋은 방법인 것 같습니다.
다른 분들은 어떤 방식을 더 선호하는지 궁금합니다!

2024-10-06 09:57 UTC, JeonJe commented on src/main/java/carracing/domain/Car.java
>      }
Car의 원시값인 name과 position에 대해 Name, Position으로 Wrapping만들어서 각각 이름과 위치를 검증하는 역할까지 가지도록 하였습니다

2024-10-06 09:57 UTC, JeonJe commented on src/main/java/carracing/domain/Car.java
> +    public Car move(int randomNumber) {
Car move메소드에 이동 전략을 넘겨 받아 이동 여부를 판단하도록 변경하였습니다. 전략은 난수로 이동하는 전략과 테스트용 전진, 정지 전략 총 3가지를 적용해보았습니다.

2024-10-06 09:59 UTC, JeonJe commented on src/main/java/carracing/view/ResultView.java
> +                .collect(Collectors.toUnmodifiableList());
ResultView에서 비지니스 로직을 제거하였습니다. ResultView는 우승자 자동차에서 이름을 추출해 보여주는 역할만 하도록 변경하였습니다. 
- 라운드 결과와 우승자를 출력하는 부분을 하나의 메소드에서 처리해서 ResultView가 우승자를 찾는 비지니스 로직 수행하고 있었습니다. 이를 분리 하였고, 우승 자동차 모곩은 race로부터 값을 가져도록 변경하였습니다.

2024-10-06 13:59 UTC, nooose commented on src/main/java/carracing/view/ResultView.java
> +                .collect(Collectors.toUnmodifiableList());
`모곩` 😂

2024-10-06 14:08 UTC, nooose commented on src/main/java/carracing/domain/Car.java
>          if (canMove(randomNumber)) {
저는 개인적으로 
1번 방법이 일관성과 가독성 모두 가져갈 수 있는 방법이라고 생각합니다.

코드는 위에서 아래로 자연스럽게 읽혀야한다고 생각합니다.
그리고 public 메소드와 private 메소드가 너무 멀리 떨어져있으면 코드를 읽고 수정하는 데 있어서 어려움이 많을 것 같아요

2번 방법처럼 public/private 별로 묶으면 참 예쁠 것 같다고 생각해요
그러나 코드 거리가 늘어나기 때문에 좋은 방법은 아니라고 생각합니다.

저의 개인적인 의견이었습니다. 😁

2024-10-06 14:27 UTC, nooose approved these changes
안녕하세요 전제님!
처음부터 끝까지 미션 구현을 매우 훌륭하게 해주신 점 정말 좋았습니다.
각 단계에서 분리와 설계가 이미 잘 되어 있어서,
5단계에서 추가로 드릴 리뷰는 없는 것 같네요.

마지막으로 몇 가지 코멘트를 남기면서 마무리하겠습니다. 
도움이 되셨길 바랍니다!

2024-10-06 14:27 UTC, nooose commented on src/main/java/carracing/domain/car/Car.java
> +    }
정적팩토리 메소드인 `of` 와 생성자는 어떤 차이가 있나요?
별다른 행위가 없다면 기존 생성자를 사용해도 되지 않을까요?

2024-10-06 14:27 UTC, nooose commented on src/main/java/carracing/domain/car/Car.java
> +            Position increasedPosition = Position.from(position.increase());
```suggestion
            Position increasedPosition = position.increase();
```
이렇게도 사용해 볼 수 있을 것 같아요

2024-10-06 14:27 UTC, nooose commented on src/main/java/carracing/domain/car/Name.java
> +        }
이 부분도 주 생성자에 포함시킨다면 유효성 검사를 한곳에서 처리할 수 있을 것 같아요.
결국에는 하나의 생성자를 호출하게 될테니까요

2024-10-06 14:27 UTC, nooose commented on src/test/java/carracing/domain/move/ForwardStrategy.java
> +public class ForwardStrategy implements MoveStrategy{
```suggestion
public class ForwardStrategy implements MoveStrategy {
```

2024-10-06 14:27 UTC, nooose commented on src/main/java/carracing/domain/move/RandomNumberMoveStrategy.java
> +public class RandomNumberMoveStrategy implements MoveStrategy {
반영하셨네요!
👍👍

2024-10-06 14:27 UTC, nooose commented on src/test/java/carracing/domain/race/RaceTest.java
> +        Race race = Race.of(carNames, 1, moveStrategy);
인터페이스가 단일 메소드만 가지고 있어 함수형 인터페이스로 볼 수 있는데요
이때 람다식을 사용하면 클래스 구현 없이도 표현할 수 있습니다.

```suggestion
        Race race = Race.of(carNames, 1, () -> true);
```
참고만 해주세요~

2024-10-06 14:28 UTC, merged

2024-10-06 14:42 UTC, JeonJe commented on src/main/java/carracing/domain/car/Car.java
> +    }
생성자와 정적 팩토리 메서드를 혼용해서 사용하지 않고, 객체 생성을 위해서는 정적팩토리 메소드만 사용한다! 라는 일관성을 지키기 위한 의도로 사용했습니다.
피드백 주신대로 별 다른 행위가 없으면 기본 생성자를 사용해도 좋을 것 같습니다👍

2024-10-06 14:44 UTC, JeonJe commented on src/main/java/carracing/domain/car/Car.java
> +            Position increasedPosition = Position.from(position.increase());
더 좋은 방법이 있었네요!👍👍

2024-10-06 14:47 UTC, JeonJe commented on src/main/java/carracing/domain/car/Name.java
> +        }
정적 팩토리 메서드가 많으면 중복된 검증 코드가 많이 생길 수도 있겠네요. 감사합니다.

2024-10-06 14:48 UTC, JeonJe commented on src/test/java/carracing/domain/race/RaceTest.java
> +        Race race = Race.of(carNames, 1, moveStrategy);
전혀 생각도 못한 부분인데, 추후 미션에서 사용할 일 있으면 적용해보겠습니다👍

2024-10-06 14:53 UTC, JeonJe commented
이번 미션을 진행하면서 많은 좋은 내용을 배울 수 있었습니다. 
덕분에 step1 코드와 비교해보면, 훨씬 더 깔끔하고 변경에 유연한 코드로 개선되었습니다.
휴일과 밤낮을 가리지 않고 리뷰를 요청드렸음에도🥲, 항상 빠르고 꼼꼼한 피드백을 주셔서 정말 감사드립니다.
정말 많은 도움을 받았습니다. 그동안 고생 많으셨습니다!