Step5
next-step/java-racingcar pull request #5765
Opened 2024-10-05 08:14 UTC by gyeongjae-ham

1. Position 클래스 적용
2. TryCount 클래스 적용
3. RandomNumber 클래스 적용

질문 내용
1. getCarName이나 getPosition과 같은 출력 부분때문에 getter를 쓴 부분은 어쩔수 없는걸까요? 아니면 제가 생각하지 못한 방법이 있는걸까요? 얘네들 메시지 호출 형태로 넘기자니 책임이 아닌거 같아서 고민이 됩니다
2. String carName, int maxPosition 같은 경우는 감싸는 형태로 구현해 봤더니 이점이 없다고 느껴서 구현하지 않았습니다.

2024-10-05 10:15 UTC, csh0034 requested changes
원시값 wrapping 잘 해주셨네요 💯 
몇가지 코멘트 남겨두었는데 확인 부탁드려요!
추가로 MVC 구조에 맞춰 패키지도 분리해보시면 좋을것 같습니다.

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/Position.java
> +public class Position {
원시값 wrapping 👍
TryCount 와 같이 불변클래스로 사용해볼수도 있지 않을까요?

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/CarName.java
> +public class CarName {
Car 에서 자동차 이름 길이에 대한 검증 책임을 추가한 이후에
사용해보도록 하면 좋을것 같아요!

2024-10-05 10:15 UTC, csh0034 commented on src/test/java/race/PositionTest.java
> +class PositionTest {
단위테스트도 작성 잘해주셨네요 👍

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/CarRace.java
> +    private int calculateMaxPosition(int size, List<Car> cars) {
내부에 cars 를 사용하기 위함이라면 인자로 전달해야하는걸까요? 🤔

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/CarRace.java
>          return cars;
반환한 컬렉션에 대해서 변경을 할 수 없도록 [unmodifiable collection](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/) 을 적용해보시면 좋을것 같습니다.

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/CarRace.java
>              collectWinners(car, maxPosition, raceResult);
응답에 필요한 처리를 위해 전달하는 인수를 출력인수라고 합니다.
클린코드에서는 출력인수 사용을 권장하지 않는데요.
car 에 대한 winner name 을 리턴으로 받아 raceResult 에 추가해보시면 좋을것 같습니다.

2024-10-05 10:15 UTC, csh0034 commented on src/main/java/race/ForwardCheck.java
> -public interface ForwardCheck {
랜덤한 부분을 테스트하기위해 추가해주신 전략패턴 형태를 제거하신 이유가 있으실까요? 🤔

2024-10-05 10:16 UTC, csh0034 commented
### 1

비지니스 로직 처리를 위해 타 객체의 값을 꺼내와 처리하기 위한 getter 가 아닌
`출력 요구사항` 에 의해 사용한 경우라면 문제 없다고 생각합니다.

### 2

CarName 의 경우엔 코멘트에 추가드린 내용 참고해주시면 될 것 같아요!

2024-10-06 01:52 UTC, gyeongjae-ham commented on src/main/java/race/CarName.java
> +public class CarName {
넵넵 감사합니다!

2024-10-06 01:52 UTC, gyeongjae-ham commented on src/main/java/race/Position.java
> +public class Position {
넵넵 감사합니다!

2024-10-06 01:52 UTC, gyeongjae-ham commented on src/main/java/race/ForwardCheck.java
> -public interface ForwardCheck {
네 인스턴스 변수를 2개까지로 유지하기 위해서 제거하는 방향으로 진행했습니다!

2024-10-06 01:54 UTC, gyeongjae-ham commented on src/main/java/race/CarRace.java
> +    private int calculateMaxPosition(int size, List<Car> cars) {
와우.... 그냥 생각없이 추출한게 위험하군요 감사합니다!

2024-10-06 01:57 UTC, gyeongjae-ham commented on src/main/java/race/CarRace.java
>          return cars;
정말 감사합니다. 위험성에 대해 알고있으면서도 전혀 생각하지 못한 부분이었습니다!! 👍

2024-10-06 02:05 UTC, gyeongjae-ham commented on src/main/java/race/ForwardCheck.java
> -public interface ForwardCheck {
네 인스턴스 변수를 2개로 유지하기 위해서 수업한 내용을 토대로 random 부분을 상위 객체로 이동시키는 방식으로 구현했습니다

2024-10-06 02:05 UTC, gyeongjae-ham commented on src/main/java/race/CarRace.java
>              collectWinners(car, maxPosition, raceResult);
생각지 못했던 부분을 알게되었습니다 감사합니다!!

2024-10-06 02:41 UTC, gyeongjae-ham commented on src/main/java/race/CarRace.java
>          return cars;
처음에 방어적 복사로만 하도록 수정했습니다. 다시 생각해보니 애초에 방어적이 아니라 변경이 불가해야 하는 메소드인걸로 생각되어져서 unmodifiable collection 적용하겠습니다 감사합니다!!

2024-10-06 10:55 UTC, csh0034 approved these changes
안녕하세요. 경재님.

피드백 반영 너무 잘해주셨습니다. 👍
몇가지 코멘트만 드리고 마지막 단계는 이만 머지하도록 할게요!

그동안 자동차 경주 미션 진행하시느라 수고 많으셨고
앞으로의 미션도 응원하겠습니다. 🎉🎉

2024-10-06 10:55 UTC, csh0034 commented on src/main/java/race/car/Car.java
> +        this.carName = carName;
```suggestion
        this(carName, new Position(1));
```

2024-10-06 10:55 UTC, csh0034 commented on src/main/java/race/car/Car.java
> +    public void forward(RandomNumber randomNumber) {
전략패턴의 경우 생성자를 통해 주입하여 인스턴스를 가지고 있을수도 있고
사용하는 메서드에 파라미터로 전달하여 사용해볼수도 있습니다.

인스턴스 변수의 수를 줄이기 위함이라면 파라미터로 전달하도록 적용해볼수도 있겠네요 🙂

2024-10-06 10:55 UTC, csh0034 commented on src/test/java/race/CarNameTest.java
> +package race;
테스트클래스의 위치는 테스트하려는 대상과 같은 패키지에 존재하는것이 일반적입니다.
다음 미션에선 위치에 맞춰 구현해보시면 좋을것 같아요!

2024-10-06 10:55 UTC, csh0034 commented on src/main/java/race/race/CarRace.java
> +    private List<String> getWinners(int maxPosition) {
stream api 를 사용한다면 하단과 같이 표현해볼수도 있겠네요!

```java
        return cars.stream()
            .filter(car -> car.isMaxPosition(maxPosition))
            .map(Car::getCarName)
            .collect(Collectors.toList());
```

2024-10-06 10:55 UTC, merged