Step3: 자동차 경주
next-step/java-racingcar pull request #5782
Opened 2024-10-06 22:42 UTC by maeng24

### Step3: 자동차 경주

 - 요구사항에 맞추고, 가능한 테스트를 세분화하여 사이클을 여러개 만들어 개발해보려고 노력하였습니다.
 - 메서드 분리에 신경썼습니다.

#### 질문사항
 - 출력 결과물에 대한 (System.out.print) 대해 테스트를 할 때, 더 좋은 방법이 있을까요? 지금 방법이 썩 마음에 들지 않습니다.. ㅠㅠ
 - ResultView 출력시 원하는 폼의 출력을 위해 이중 포문을 사용하게 되었습니다. 더 좋은 방법이 있을까요? 
   혹은 저런 경우 리팩토링을 하는 것이 좋을지, 한다면 어떻게 리팩토링을 하는 편이신지 궁금합니다.

2024-10-06 22:42 UTC, maeng24 commented
+ step 2 에 주신 피드백도 반영해보았습니다.

2024-10-09 07:03 UTC, mskangg requested changes
3단계도 잘 구현해주셨네요!
입출력 테스트 쉽지않으셨을텐데, 고생하셨네요 👍 
질문에 대한 답변과 몇가지 피드백 남겼는데, 확인 부탁드릴게요 🙇

2024-10-09 07:03 UTC, mskangg commented on README.md
> +-[x] 랜덤 난수가 4 이상일 경우 이동한다.
자동차 경주에서 가장 중요한 로직인데, 테스트코드는 없네요.
`4 이상인 경우 전진한다` 를 테스트하려면 어떻게 해야할까요?
지금 구조에서 어렵다면, 테스트하기 어려운 구조라 그런걸거에요.
이런 경우는 리팩토링의 신호로 판단하여 구조를 바꿔보는것도 하나의 방법입니다 :)

핸들링하기 어려운 부분들(랜덤)은 외부에서 주입받아서 처리하면 쉽게 해결되기도 합니다.

2024-10-09 15:10 UTC, maeng24 commented on README.md
> +-[x] 랜덤 난수가 4 이상일 경우 이동한다.
해당 테스트들은 RacingCarTest의 25~68라인 사이의 테스트를 사용하여 테스트를 진행하였습니다.

@DisplayName("UI 입력 테스트")
@DisplayName("UI 입력 오류 테스트")
@DisplayName("랜덤 난수 발생 테스트")
@DisplayName("랜덤 난수 발생 값에 따른 자동차 이동 테스트")

2024-10-10 05:59 UTC, mskangg commented on README.md
> +-[x] 랜덤 난수가 4 이상일 경우 이동한다.
테스트하기 어려운(제어하기 힘든) 값들은 외부에서 주입받게 처리하면 테스트할 수 있을거에요!
'숫자가 4 이상인 경우에만 전진한다' 이니 랜덤요소를 빼서 생각해보면 될것같아요 😄 
전진할때 비교대상인 숫자를 전달받으면 어떨까요? 5를 집어넣으면 전진하는지 테스트하면 검증을 할 수 있을것 같습니당

2024-10-13 05:29 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👍 
추가적으로 피드백 남겨드렸는데, 이부분은 다음 단계 진행하면서 반영 부탁드립니다~!
그럼 화이팅 🔥

2024-10-13 05:29 UTC, mskangg commented on src/main/java/step3/MockOutputView.java
> +public class MockOutputView implements OutputView {
👍

2024-10-13 05:29 UTC, mskangg commented on src/main/java/step3/RacingCar.java
> +    private int[] carPosition;
모든 차량의 포지션을 들고 있는 구조군요!
하나의 차량(객체) 마다 position 을 갖고 있으니 클래스를 분리하는것도 좋을 것 같은데, 어떨까요?

그렇다면, `private List<Car> cars` 가 되어 의미전달이 명확해질것 같아요

2024-10-13 05:29 UTC, merged