Step4 - 자동차 경주(우승자)
next-step/java-racingcar pull request #5783
Opened 2024-10-07 02:14 UTC by Ujoonnee

안녕하세요 리뷰어님, 4단계 리뷰 요청 드립니다!

요구사항 중 궁금한 점이 있어 코멘트 남겼습니다. 확인 부탁드립니다!

2024-10-07 13:17 UTC, mskangg requested changes
4단계도 잘 구현해주셨네요~!
> 요구사항 중 궁금한 점이 있어 코멘트 남겼습니다. 확인 부탁드립니다!

코멘트가 없는것 같아요 😭
DM 주셔도 되니 확인해주세용~!
몇가지 피드백 남겼으니 같이 확인 부탁드립니다 🙇

2024-10-07 13:17 UTC, mskangg commented on src/main/java/race/README.md
> +-[x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.
👍

2024-10-07 15:21 UTC, Ujoonnee commented
> 코멘트가 없는것 같아요 😭 

코멘트가 아니라 리뷰로 달아놔서 안보인 것 같습니다 ㅠㅠ 헷갈리게 해드려서 죄송합니다. 다시 코멘트 달아놓겠습니다.

2024-10-07 15:22 UTC, Ujoonnee commented
```java
// Cars.java
public void move() {
    Random random = new Random();
    cars.forEach(car -> car.accelerate(random.nextInt(10)));
}
```

> 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외

라는 요구사항이 있습니다.

Cars 의 move 메서드는 리스트 내 전체 Car 들의 accelerate 메서드를 호출합니다.

Car 의 accelerate 메서드에 대한 테스트가 이미 있는 상황해서 해당 메서드를 반복만 하는 경우에도 테스트를 작성할 필요가 있을까요?

2024-10-07 15:23 UTC, Ujoonnee commented
```markdown
-[ ] git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.
```
기능 단위로 커밋을 추가하기에는 하나의 커밋에 너무 많은 내용이 들어가지 않을까요?

2024-10-07 15:59 UTC, Ujoonnee commented
> position 을 꺼내서 max 를 호출하는것보단, car 에게 메세지를 보내서 max 인지 구하는 방법도 있을것 같아요 :)

피드백 반영 전 우승자 선발 기능이 최대 전진 수 기능, 선발 기능 으로 쪼개졌고, 테스트도 추가되었습니다.

getter 의 사용을 지양하고 그 과정에서 기능이 분리되면서 더 세세한 테스트가 가능하도록 변경하는 효과가 있구나~ 하고 느껴졌습니다.
그런데 한편으로는 getter 를 완벽하게 배제할(print 제외) 필요가 있을까? 하는 의문도 들었습니다.

```java
int maxPosition = cars.stream()
    .mapToInt(Car::getPosition)
    .max()
    .orElseGet(0);
```
이 부분을 피드백 주신 내용으로 수정하면서 그 생각을 계속 하게 되네요.

실제 업무에서는 아예 getter 를 쓰지 않는 것이 힘든 경우가 많을 것 같은데요, 주로 얼마나 제한적으로 getter 를 사용하시는지 궁금합니다!

2024-10-08 08:54 UTC, mskangg approved these changes
피드백 잘 반영해주셨네요!
코멘트를 보니, 미션을 진행하시면서 많은 고민을 하신게 느껴져서 좋았습니다 👍 
추가적인 피드백과 코멘트에 대한 답변도 함께 남겼으니, 이 부분 확인 부탁드릴게요!
충분히 고민해보시고 다음 단계에 반영 부탁드립니다 🙇

2024-10-08 08:54 UTC, mskangg commented on src/main/java/race/Cars.java
> +    }
https://github.com/next-step/java-racingcar/pull/5783#issuecomment-2397236311

무엇을 테스트할지가 명확하다면 작성할 필요성이 있는지 없는지를 판단할 수 있겠죠!
우준님이 판단하시기에 작성할필요가 없다고 느낀 이유가 `Car 의 accelerate 메서드에 대한 테스트가 이미 있는 상황해서 해당 메서드를 반복만 하는 경우` 인거죠?

다른 시각에서 본다면 `Cars` 의 책임엔 `모든 차를 움직여야하는 책임`이 있는것이니 그것또한 테스트 대상으로 볼 수 있을것 같아요!
만약 모든 차량중 하나의 차량이 항상 전진하지 않는다면 테스트코드가 없을경우 검증을 할 수 없겠죠?

정리하면 `모든 차량이 accelerate 한다`를 테스트하기 위해선 필요할 수도 있을것 같아요 😄
그리고 검증의 방식은 `accelerate` 의 호출 횟수만 판단해도 무방하다고 생각합니다 :)

위와 연관된 내용은 아니지만, 테스트 관련되어 평소 좋아하는 글이 있어서 링크 남겨놓을게요!
https://blog.kingbbode.com/m/52?category=737337
https://jojoldu.tistory.com/611

2024-10-08 08:54 UTC, mskangg commented on src/main/java/race/README.md
> +-[ ] git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.
https://github.com/next-step/java-racingcar/pull/5783#issuecomment-2397238800

너무 많은 내용이 들어간다면 기능을 세부적으로 나누지 않았다는 얘기인것 같아요!
체크리스트를 좀더 세부적으로 나누고 기능을 잘게 쪼개는것도 연습해보시는것 추천드립니다 👍

2024-10-08 08:54 UTC, mskangg commented on src/main/java/race/Cars.java
> +    }
> 실제 업무에서는 아예 getter 를 쓰지 않는 것이 힘든 경우가 많을 것 같은데요, 주로 얼마나 제한적으로 getter 를 사용하시는지 궁금합니다!

제가 주를 잡고 운영하고 있는 프로젝트에선 롬복의 @getter를 igonore 해서 사용하고 있어요 :)
getter 를 의도적으로 제한해야 풍부한 도메인 모델이 나오고 책임들이 세분화되어 단위테스트를 세부적으로 할 수 있기에 이렇게 하고 있어요 ㅎㅎ
api 의 리턴을 위해 사용해야 하는 dto 에는 getter를 어쩔 수 없이 만들어야 하니, dto 는 예외로 두고 있구요

2024-10-08 08:54 UTC, mskangg commented on src/main/java/race/Race.java
> +        resultView.printWinners(cars.getWinners(maxPosition));
maxPosition 을 구한 뒤 우승자를 구하는 것도 사실 우승자를 구하기 위한 로직으로 보여져요!
위와 같이 우승자를 구하는 로직이 분리되어 있다면, `getWinners(maxPosition-1)` 로 호출하게 되면 잘못된 우승자가 나올 수도 있는 방식이라 개인적으론 이런방식을 선호하진 않아요 🤔 (이 방법이 잘못됐다는건 절대 아닙니다 ㅎㅎ)

`우승자를 구한다` 와 같은 중요한 비즈니스는 maxPosition 을 구하는 로직을 강제해 변경하는건 어떨까요?

```java
public List<Car> findWinners(){
}
```

2024-10-08 08:54 UTC, merged