feat: 문자열 덧셈 계산기 구현
next-step/java-racingcar pull request #5790
Opened 2024-10-08 06:37 UTC by gae-bak

문자열 덧셈 계산기 코드리뷰 부탁드립니다!

2024-10-08 14:49 UTC, seondongpyo requested changes
2단계 미션도 잘 구현해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
패키지를 하나 생성해서 해당 패키지 하위로 옮겨보면 어떨까요?

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +public class StringAddCal {
객체지향 생할 체조 원칙 중 `규칙 5: 줄여쓰지 않는다(축약 금지).`를 참고해주세요.
```suggestion
public class StringAddCalculator {
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +    public static int splitAndSum(String input) throws RuntimeException {
Nit: 언체크 예외는 호출 스택에 따라 알아서 예외가 전파되기 때문에 지금처럼 꼭 명시하지 않아도 될 것 같습니다.

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        if (nullOrEmpty(input) == false) {
요구사항에 따라 '빈 문자열 또는 null 값을 입력할 경우'에만 0을 반환해야 하기 때문에, 조건식이 참이 되어야 하지 않을까요?
```suggestion
        if (nullOrEmpty(input)) {
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +    public static String[] customDelimeter(String input) {
```suggestion
    public static String[] customDelimiter(String input) {
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(input);
매번 계산할 때마다 `Pattern` 인스턴스를 생성하는 대신에, 미리 하나의 인스턴스를 생성해두고 이를 재활용해보면 어떨까요?

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        if(m.find()) {
코드 포맷팅 확인해주시면 좋을 것 같습니다.
```suggestion
        if (m.find()) {
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        return input.split(",|:");
`,|:`과 같은 리터럴은 하드 코딩하는 대신에 상수로 선언하여 의미를 부여해보면 어떨까요?

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        return i;
아래와 같이 한 줄로 줄여서 작성해 볼 수 있을 것 같습니다.
```suggestion
        return Integer.parseInt(input);
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +        return true;
메서드 이름을 보면 수식이 빈 문자열 또는 null인지를 확인한다는 의미이니, 실제로 수식이 빈 문자열이거나 null이라면 반환값이 true가 되어야 하지 않을까요?
```suggestion
        return input == null || input.isEmpty();
```

2024-10-08 14:49 UTC, seondongpyo commented on src/main/java/StringAddCal.java
> +    public static int calAllSum(String[] split) {
매개변수의 이름으로 'split'이라는 이름보다는 조금 더 명확하고 직관적인 이름으로 변경해보면 어떨까 생각합니다.

2024-10-08 14:49 UTC, seondongpyo commented on src/test/java/StringAddCalTest.java
> +    void 빈문자열_혹은_null값이_들어오면_0() {
공백 또는 null을 테스트하는 경우라면 `@NullAndEmptySource`를 활용해보시면 좋을 것 같습니다.
https://velog.io/@ohzzi/junit5-parameterizedtest#nullsource-emptysource-nullandemptysource

2024-10-08 14:49 UTC, seondongpyo commented on src/test/java/StringAddCalTest.java
> +    void 숫자_두개를_컴마_구분자로_입력할_경우_두_숫자의_합을_반환한다() throws Exception {
구분자가 콤마(`,`)가 아닌 콜론(`:`)만 있는 수식의 경우도 테스트해보면 어떨까요?

2024-10-08 14:49 UTC, seondongpyo commented on src/test/java/StringAddCalTest.java
> +    void 음수를_전달할_경우_RuntimeException_예외가_발생해야_한다() {
다음 요구사항에 따라, 숫자 이외의 값이 전달되는 경우에 대한 테스트도 추가해보면 어떨까요?
> 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw한다.

2024-10-14 07:00 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +public class StringAddCal {
수정완료

2024-10-14 07:01 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +    public static int splitAndSum(String input) throws RuntimeException {
언체크 예외에 대해서 알아보기

2024-10-14 07:09 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +        if (nullOrEmpty(input) == false) {
수정 완료

2024-10-14 07:10 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +    public static String[] customDelimeter(String input) {
수정 완료

2024-10-14 07:11 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +        return true;
수정 완료

2024-10-14 07:13 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +    public static int calAllSum(String[] split) {
수정 완료

2024-10-14 07:42 UTC, gae-bak commented on src/test/java/StringAddCalTest.java
> +    void 빈문자열_혹은_null값이_들어오면_0() {
수정 완료

2024-10-14 07:46 UTC, gae-bak commented on src/test/java/StringAddCalTest.java
> +    void 숫자_두개를_컴마_구분자로_입력할_경우_두_숫자의_합을_반환한다() throws Exception {
수정 완료

2024-10-14 08:17 UTC, gae-bak commented on src/main/java/StringAddCal.java
> +    public static int splitAndSum(String input) throws RuntimeException {
수정 완료

2024-10-14 11:53 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
다만 몇 가지 반영이 안 된 부분들이 있는데요, 
추가로 드린 코멘트와 함께 확인해주시면 좋을 것 같습니다.
다음 단계에서 뵐게요 🔥

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
정적 메서드만을 포함하는 클래스라면, `private` 생성자 등을 추가하여 불필요한 인스턴스화를 막아보면 어떨까요?
https://burningfalls.github.io/java/why-should-the-constructor-of-a-utility-class-be-private/

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +         return 0;
코드 포맷팅 확인해주시면 좋을 것 같습니다. IDE로 IntelliJ IDEA를 사용 중이시라면, 
단축키(Windows는`Ctrl + Alt + L`, Mac은 `Cmd + Option + L`)를 활용해보시는 걸 권장 드립니다.
```suggestion
            return 0;
```

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(input);
이전 코멘트를 참고해주세요. https://github.com/next-step/java-racingcar/pull/5790#discussion_r1792011685

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +        if(m.find()) {
이전 코멘트를 참고해주세요. https://github.com/next-step/java-racingcar/pull/5790#discussion_r1792012529

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +        return input.split(",|:");
이전 코멘트를 참고해주세요. https://github.com/next-step/java-racingcar/pull/5790#discussion_r1792013825

2024-10-14 11:53 UTC, seondongpyo commented on src/main/java/calculator/StringAddCalculator.java
> +        return i;
이전 코멘트를 참고해주세요. https://github.com/next-step/java-racingcar/pull/5790#discussion_r1792016416

2024-10-14 11:53 UTC, seondongpyo commented on src/test/java/calculatortest/StringAddCalculatorTest.java
> +//    @ParameterizedTest
사용하지 않는 코드 주석은 제거해보면 좋을 것 같습니다.

2024-10-14 11:53 UTC, seondongpyo commented on src/test/java/calculatortest/StringAddCalculatorTest.java
> +    }
`value`에 `null`과 공백이 전달되어 각각 테스트가 실행이 되기 때문에, 테스트 코드는 한 줄이면 충분할 것 같습니다.
```suggestion
        assertThat(StringAddCalculator.splitAndSum(value)).isEqualTo(0);
    }
```

2024-10-14 11:53 UTC, merged