Step5 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5817
Opened 2024-10-14 14:33 UTC by devcsb

# 변경사항
- 4단계 머지해주시면서 주신 피드백들을 반영했습니다!
- strategy package 분리, ui -> view로 패키지명 수정, GameApplication의 로직을 GameController로 분리하고 이관했습니다.

# 의문점
RandomStrategyTest에서는 움직임전략을 테스트하는데,
``` MoveStrategy moveStrategy = () -> true;
    assertThat(moveStrategy.isMovable()).isTrue();
```
와 같이 작성하다보니 테스트 작성이 과연 필요한걸까? 하는 의문이 드는데, 더 좋은 테스트방법이 있을까요?

이외에도 전반적으로 테스트가 빈약한 느낌이 드는데, 사실 어떤 값을 어떻게 더 테스트해야될 지 잘 떠오르지가 않는 상황입니다.
어떤 식으로 테스트를 보충할 수 있을 지 힌트나 가이드를 주시면 정말 감사하겠습니다!

2024-10-16 16:57 UTC, csh0034 requested changes
5단계 잘 구현 해주셨네요 💯 
크게 리뷰드릴 부분은 없지만 질문에 대한 답변 코멘트에
남겨두었는데 확인 부탁드립니다 😄

2024-10-16 16:57 UTC, csh0034 commented on src/main/java/racingcar/domain/Cars.java
> +    return new Cars(
```suggestion
    return carNames.stream()
        .map(Car::new)
        .collect(Collectors.collectingAndThen(Collectors.toList(), Cars::new));
```

2024-10-16 16:57 UTC, csh0034 commented on src/main/java/racingcar/domain/Car.java
> +  public int compareTo(Car other) {
우승자를 구한 핵심로직은 compareTo, isSamePosition 입니다.
해당 기능에 대한 단위테스트를 작성해보시면 좋을것 같아요!

2024-10-16 16:57 UTC, csh0034 commented on src/test/java/racingcar/strategy/RandomStrategyTest.java
> +class RandomStrategyTest {
람다표현식을 통해 처리를 해주셨기 때문에 테스트 클래스명에 있는 Random 의 의미가 없어진것 같아요.

랜덤이라는게 테스트가 불가능하기 때문에 자동차의 움직임을 테스트가능한 형태로 만들기 위해  
전략패턴이 추가되었다고 생각합니다.

따라서 RandomStrategyTest 는 필요하지 않다고 볼 수 있을것 같아요!

2024-10-17 13:19 UTC, devcsb commented on src/main/java/racingcar/domain/Cars.java
> +    return new Cars(
collectingAndThen() 라는게 있었네요!

2024-10-17 13:27 UTC, devcsb commented on src/main/java/racingcar/domain/Car.java
> +  public int compareTo(Car other) {
가장 작은 단위의 핵심로직이 무엇인지 찾아보고, 그에 대해서 테스트를 작성해보는 연습을 해야겠네요. 감사합니다!

2024-10-17 13:29 UTC, devcsb commented on src/test/java/racingcar/strategy/RandomStrategyTest.java
> +class RandomStrategyTest {
말씀해주신 것처럼, 테스트도 관리해야할 코드라는 점, 테스트코드에서 테스트하는 것이 true가 true냐, false가 false냐 정도를 검증하는 것이라서, 과감히 삭제해도 되는 것 같네요.

2024-10-18 01:52 UTC, csh0034 approved these changes
안녕하세요. 수봉님.

피드백 반영 너무 잘해주셨습니다. 👍
마지막 단계는 이만 머지하도록 할게요!

그동안 자동차 경주 미션 진행하시느라 수고 많으셨고
앞으로의 미션도 응원하겠습니다. 🎉🎉

2024-10-18 01:52 UTC, csh0034 commented on src/test/java/racingcar/domain/CarTest.java
> +  void compareTo(int pobiCarPosition, int jasonCarPosition, int expected) {
단위테스트 추가 잘해주셨네요 💯

2024-10-18 01:52 UTC, merged