🚀 5단계 - 자동차 경주(리팩토링)
next-step/java-racingcar pull request #5818
Opened 2024-10-15 12:26 UTC by jonghyeonLeee

안녕하세요! 

5단계를 진행했습니다. 

인터페이스로 분리하는 부분이 계속.. 이해가 안됐지만 파라미터를 받는 방향으로 진행해봤습니다!!

4단계 피드백 적용 하였으며, 
MVC 분리, 프리미티브 타입을 클래스로 구현, model에선 view와 controller를 상속 받지 않도록 최대한 분리해봤습니다!!

피드백 주시면 반영하도록 하겠습니다!

감사합니다~ :)

2024-10-15 16:18 UTC, dhmin5693 requested changes
안녕하세요.

이번 과제를 진행하면서 고민을 되게 많이 하신 것 같아요.
어려운 점 있으시면 언제든지 DM으로 질문해주세요.
몇 가지 피드백을 남겼으니 수정하시면서 꼭 참고 부탁드립니다.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/Main.java
>  public class Main {
이번엔 Main의 책임을 일부 분리해보는건 어떨까요?
Main에서는 로직을 시작하는 정도의 책임만 가지는게 더 적절합니다.
그 자체로도 진입점 역할을 하고 있거든요.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/utils/RandomStrategy.java
> +public interface RandomStrategy {
이 인터페이스명에서 `Random`을 언급하면 구체적인 방법을 명시하게 됩니다.
인터페이스는 방향을 "제시"하는 용도로만 사용하시는게 좋아요.

근데 이 인터페이스는 이미 방향뿐만 아니라 갈 길까지 전부 알려주는 느낌이네요.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/Main.java
> +        RacingHelper racingHelper = new RacingHelper();
RacingHelper 보다는 더 괜찮은 이름으로 변경해주세요.
상위 인터페이스인 `RandomStrategy` 를 연상해내기 어렵습니다.
인터페이스의 이름이 이미 하위 구현체의 역할을 정해버려서 그런 것일수도 있어요.

그리고 하위 구현체를 그대로 사용하면 인터페이스를 통한 약결합이라는 장점을 가져갈 수 없습니다.
구현체가 아니라 인터페이스를 활용하는 방법으로 바꿔보세요.

방법은 여러가지가 있습니다.
1. `Car` 의 생성자에서 `RandomStrategy` 를 주입받아 사용합니다.
2. moveAllCars 에서 직접 사용하지 않고 매개변수 형태로 `RandomStrategy`을 사용합니다.
    - 이렇게 되면 moveAllCars에서 직접 생성하지 않고 외부로부터 주입받는 형태가 됩니다.
    - 따라서 사용자의 필요에 따라 다른 구현체로 바꾸어 사용할 수 있습니다.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/CarName.java
> +public class CarName {
원자 단위의 책임 분리 👍

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Position.java
> +public class Position {
👍

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    }
domain에서는 sout 을 사용하시면 UI를 분리한 의미가 퇴색됩니다.

sout은 UI에서만 사용해주세요.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    List<Car> carList;
private이 아닌 이유가 있을까요?

그리고 List와 같은 자료형은 필요에 따라 언제든지 변경할 수 있습니다.
예를 들면 Set으로 바꿀 수 있겠죠?

따라서 carList보다는 복수형 용어를 사용하시는걸 추천드립니다.
`Cars`처럼 일급컬렉션인 경우에는 items 같은 용어를 사용해도 나쁘지 않아요.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    }
[방어적 복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable) 기법에 대해 공부해보시면 좋습니다.

`Cars`를 생성한 위치 주변에서 `Cars`를 생성하는데 사용한 List를 변경하면 `Cars`도 영향을 받게 됩니다.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    }
```suggestion
    public List<Car> getCarList() {
        return Collections.unmodifiableList(this.carList);
    }
```

읽기 전용 데이터로 변경해서 내보내셔야 외부의 영향을 받지 않게 됩니다.
`getCarList().add(car)` 를 수행하면 `Cars`가 변경되어 버립니다.

2024-10-15 16:18 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    public int findMaxPosition() {
private 메소드여도 괜찮지 않을까요?

2024-10-22 10:12 UTC, jonghyeonLeee commented on src/main/java/com/racing/domain/Cars.java
> +    public int findMaxPosition() {
[0c567b0](https://github.com/next-step/java-racingcar/pull/5818/commits/0c567b0b58f38c78ffd76ee7c8bc59cdec55dbab)

작성할 때 직접 테스트를 하였는데 추후 간접 테스트를 하고 있다 판단하여 private 변경 후 테스트 코드 제거했습니다!

2024-10-22 10:13 UTC, jonghyeonLeee commented on src/main/java/com/racing/domain/Cars.java
> +    }
[13b1a3c](https://github.com/next-step/java-racingcar/pull/5818/commits/13b1a3cc789a5bfaca6503f5c1ba1bebd91ff09e)

방어적 복사 기법 공부 후 외부에서 변경하지 못하도록 해당 내용 반영 했습니다.

2024-10-22 10:18 UTC, jonghyeonLeee commented on src/main/java/com/racing/domain/Cars.java
> +    List<Car> carList;
[be64fc4](https://github.com/next-step/java-racingcar/pull/5818/commits/be64fc491b3497b91ccd7bf19a6812675f43a0ea)

private로 필드를 막았어야 했는데 빼먹었네요 ㅜㅜ 수정했습니다. 
items로 변경할 경우 Cars.getItems() 와 같이 일반적인 메서드로 표현할 수 있어 가독성에서도 좋아 보여 수정했습니다. 

중복된 값에 대한 처리 여부가 문제에 명시되지 않아 습관적으로 List를 사용했는데 추후 관련된 내용이 있으면 Set으로 리팩토링 해보겠습니다! :)

2024-10-22 10:18 UTC, jonghyeonLeee commented on src/main/java/com/racing/domain/Cars.java
> +    }
[16ee9f8](https://github.com/next-step/java-racingcar/pull/5818/commits/16ee9f83420bf8c8363a7f424dafa2aa650835ee)

해당 내용 적용했습니다 :)

2024-10-22 10:19 UTC, jonghyeonLeee commented on src/main/java/com/racing/Main.java
>  public class Main {
[9a3199f](https://github.com/next-step/java-racingcar/pull/5818/commits/9a3199fe556425f94ce983e9fa74436f23bcc138)

메인 진입점을 분리했습니다!

2024-10-22 10:20 UTC, jonghyeonLeee commented on src/main/java/com/racing/Main.java
> +        RacingHelper racingHelper = new RacingHelper();
이 부분이 이해되지 않아 수정을 못했습니다 ㅜㅜ.. 
혹시 시간 나실 때 페어코딩이나 다른 도움을 받을 수 있는 부분이 있을지 문의드립니다!

2024-10-22 15:22 UTC, dhmin5693 requested changes
안녕하세요.

마지막 미션이라 일단 수정 요청 한번 더 드려보는데요,
시간 상 다음 미션 수행하시는게 더 도움이 될 것 같기는 합니다.

일단 남긴 피드백 확인해보시고 수정이 필요없다고 생각하시거나 다음 미션 진행하고 싶으시면 수정없이 바로 요청주셔도 괜찮습니다.

어려운 점 있으실 때 또 DM주시면 상세히 답변드리겠습니다.

2024-10-22 15:22 UTC, dhmin5693 commented on src/main/java/com/racing/service/RacingService.java
> +    public static void startRacingGame() {
startRacingGame에서 input까지 다 하기보다는 input은 미리 받은 뒤 dto 등으로 넘기면 조금 더 깔끔하게 구현할 수 있을 것 같네요.

2024-10-22 15:22 UTC, dhmin5693 commented on src/main/java/com/racing/service/RacingService.java
> +    }
startRacingGame에서 직접 input을 수행하지 않고 Main(혹은 다른 클래스)에서 input을 수행한 다음 dto로 보낸다면 어떨까요?

startRacingGame 자체 테스트가 지금은 불가능한데 가능해질 수 있습니다.

하지만 아직 걸림돌이 하나 있는데 advanceAllCars 에서 직접적으로 `Random` 로직에 의존하고 있어요.
DM으로 말씀드렸듯 여기서 이렇게 직접 사용하기 때문에 startRacingGame 가 불가능해 지는 것입니다.

`RacingService` 의 필드로 Strategy를 가져가고 사용하는 방법도 있으니 한 번 고려해보세요.

2024-10-22 15:22 UTC, dhmin5693 commented on src/main/java/com/racing/domain/Cars.java
> +    public int findMaxPosition() {
private 도 테스트가 필요할 만큼 복잡한 순간도 분명 있지만, public을 통해 간접적으로 테스트하는게 방법 자체가 더 올바릅니다.

private을 굳이 따지자면 public의 코드를 따로 접어둔 느낌이니까요.

2024-10-22 15:22 UTC, dhmin5693 commented on src/main/java/com/racing/utils/CarMovement.java
> +public class CarMovement implements MovementStrategy {
`MoveStrategy`는 적절한 명칭이 맞는데요,
`CarMovement`  보다는 `RandomMovementStrategy`는 어떠신지요?

저번에도 남긴 부분인데 구현체와 인터페이스는 이름으로도 연관이 있어보여야 좋습니다.

2024-10-22 15:22 UTC, dhmin5693 commented on src/main/java/com/racing/Main.java
> +        RacingHelper racingHelper = new RacingHelper();
1. service의 필드에 `CarMovement` 를 필드로 가집니다. 그럼 service를 초기화할 때 전략을 선택적으로 밀어넣을 수 있습니다.
2. moveAllCars의 매개변수가 지금 cars 하나만 있는데 cars, movementStrategy 2개로 해두시면 이 메소드를 호출할 때 전략을 선택적으로 사용할 수 있습니다.

전략 패턴의 기본은 언제든지 전략을 바꾸어 사용할 수 있어야 한다는 것임을 생각해보시면 도움이 될 수 있습니다.

2025-03-16 23:50 UTC, closed without merging