Step4: 자동차 경주 우승자
next-step/java-racingcar pull request #5822
Opened 2024-10-19 10:43 UTC by maeng24

## Step4 : 자동차 경주 (우승자)

 - 역할에 따라 메서드를 적절한 객체에 만들고, 개발하는데 신경썼습니다.
 - 줄이 길어지면 메서드를 분리하려고 노력하였습니다.
 - 메서드 명이 일관성을 가질 수 있도록 신경썼습니다. 

### 질문사항

 - else if 를 쓰지 않기 위해 생각을 많이 했습니다. 아예 새로운 방법으로 개발을 하게 되기도 하더라구요. 리팩토링 하려 노력중이지만, 사실 업무 코드에는 else if 나 switch를 사용하는 부분이 꽤 많고 / 익숙하기 때문인지.. 가끔 그게 더 단순하고 깔끔하게 느껴지기도 합니다. 현업에서도 else if 를 지양하시는 편인지 궁금합니다.
 - step3의 코드를 디벨롭 하여 개발했습니다. 이렇게 하는게 맞나요?

2024-10-20 05:42 UTC, mskangg requested changes
> 현업에서도 else if 를 지양하시는 편인지 궁금합니다.

필요한 곳이라면 그렇게 사용합니다!
코드엔 항상 정답이 아니니, 충분한 고민 끝에 else if 가 더나은 구조라면 그렇게 차용하는 편이에요 :)
지금 구현하시면서 어디부분이 else if 가 좋은 구조였는지 궁금하네요! 🧐
그 부분 변경해서 요청 부탁드릴게요! 🙏 

4단계도 잘 구현해주셨네요!
질문에 대한 답변과 함께 피드백 남겨드렸는데, 확인해주세요~!

2024-10-20 05:42 UTC, mskangg commented on README.md
> +-[x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한명 이상일 수 있다.
👍

2024-10-20 05:42 UTC, mskangg commented on src/main/java/step4/Car.java
> +package step4;
> step3의 코드를 디벨롭 하여 개발했습니다. 이렇게 하는게 맞나요?

패키지를 나눠주셨는데, 이렇게해도되지만 저는 패키지를 나누지않고 계속 디밸롭해서 개발합니다 :)
이전 단계의 코드들은 어차피 branch 로 남아있을테니까요!
그리고 PR 에서의 변경사항이 더 잘드러나기 때문에 위처럼 진행하는게 다른 리뷰어 분들도 편하실거에요 😁

2024-10-20 05:42 UTC, mskangg commented on src/main/java/step4/RacingCar.java
> +            maxPosition = Math.max(maxPosition, car.getPosition());
자동차의 포지션을 꺼내지않고 메세지를 보내어 처리하는건 어떨까요?

`규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.`
위와 같이 의도적으로 게터를 제거해보고 개발해보는것 추천드릴게요 👍 
물론 출력을 위한 get 은 필요하니 그부분은 어쩔수없지만요 😅

2024-10-20 05:42 UTC, mskangg commented on src/main/java/step4/RacingCar.java
> +            if (car.getPosition() == maxPosition)
`규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.`

2024-10-20 08:27 UTC, maeng24 commented on src/main/java/step4/Car.java
> +package step4;
넵 감사합니다!

2024-10-22 13:34 UTC, maeng24 commented
비즈니스 로직 파트에 있는 게터 메서드의 사용을 빼고, (출력은 어쩔수 없이 두었습니다 ㅠㅠ)

2024-10-24 05:24 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👍 
소소한 피드백 남겼는데, 다음 단계의 요구사항이니 고민해보시면 좋을것 같아요!
그럼 다음 단계 화이팅! 🔥

2024-10-24 05:25 UTC, merged